import type { AccaQuestion } from "@/lib/acca-content"

/*
 * SBR bank wave S1 part A (areas A,B) — 2026-07-13
 * Blueprint: Area A (Conceptual & regulatory framework) 25 + Area B (Reporting financial performance) 40 = 65.
 * Difficulty: 16 easy / 30 medium / 19 hard. Type mix: 55 mcq / 10 number (all number questions sit in area B).
 * Correct-option distribution across the 55 mcq: index0 = 14, index1 = 14, index2 = 14, index3 = 13.
 * All company names and figures are invented; prose is original; public SBR syllabus only.
 * Every numeric question was re-solved digit-by-digit from its own stem and every IFRS rule was verified before writing.
 */
export const SBR_WAVE1A: AccaQuestion[] = [
  /* ═══════════════ Area A — Conceptual & regulatory framework (25 mcq) ═══════════════ */
  {
    id: "SBR2-A-01",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "According to the IASB Conceptual Framework, the objective of general purpose financial reporting is to:",
    options: [
      "Provide financial information about the reporting entity that is useful to existing and potential investors, lenders and other creditors in making decisions about providing resources to the entity",
      "Present the financial position of the entity in a manner that guarantees the statements are entirely free from error",
      "Enable the directors to demonstrate the efficiency of their stewardship, this being the sole objective of reporting",
      "Determine the taxable profits of the entity for the relevant tax authority",
    ],
    correct: 0,
    explanation:
      "The Framework states the objective is to provide financial information useful to the primary users (investors, lenders and other creditors) for resource-allocation decisions. 'Free from error' describes an aspect of faithful representation, not the objective, and absolute freedom from error is not attainable. Stewardship is an important part of the objective but not the SOLE objective. Tax determination is a separate regulatory purpose, not the objective of general purpose reporting.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR2-A-02",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "Which pairing correctly identifies the TWO fundamental qualitative characteristics of useful financial information under the Conceptual Framework?",
    options: [
      "Comparability and understandability",
      "Relevance and faithful representation",
      "Timeliness and verifiability",
      "Reliability and prudence",
    ],
    correct: 1,
    explanation:
      "The two fundamental characteristics are relevance and faithful representation. Comparability, understandability, timeliness and verifiability are the four ENHANCING characteristics, so those options mislabel enhancing ones as fundamental. 'Reliability' was replaced by faithful representation in the 2010 revision, and prudence supports neutrality (an aspect of faithful representation) rather than being a characteristic in its own right.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-A-03",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "For information to be a perfectly faithful representation, the Conceptual Framework states it should have three characteristics. These are that the depiction is:",
    options: [
      "Relevant, reliable and comparable",
      "Material, prudent and verifiable",
      "Complete, neutral and free from error",
      "Accurate, certain and unbiased",
    ],
    correct: 2,
    explanation:
      "Faithful representation means the depiction is complete, neutral and free from error. 'Relevant/comparable' confuses faithful representation with other characteristics; 'material/prudent/verifiable' mixes the materiality entity-specific aspect of relevance with an enhancing characteristic; and 'accurate/certain' is wrong because free from error does not mean perfectly accurate or certain — estimates can still be faithful if the process is described and applied appropriately.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-A-04",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "A financial controller argues that because the company has used the same depreciation method every year, its statements are automatically comparable. Which statement is correct?",
    options: [
      "Consistency and comparability are identical concepts and the terms may be used interchangeably",
      "Comparability requires that every entity in the world uses identical accounting policies",
      "Consistency is an enhancing characteristic and comparability is merely the technique used to achieve it",
      "Consistency (using the same methods over time) helps to achieve comparability, but comparability is the objective and consistency is only the means of achieving it",
    ],
    correct: 3,
    explanation:
      "Comparability is the enhancing characteristic (the goal); consistency is the use of the same methods within an entity over time, which HELPS achieve comparability. Consistency and comparability are therefore related but not identical, so the first option is wrong. Comparability does not demand that all entities use identical policies — it enables users to identify similarities and differences. The third option reverses the roles of consistency and comparability.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR2-A-05",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "Under the 2018 Conceptual Framework definition, an ASSET is:",
    options: [
      "A present economic resource controlled by the entity as a result of past events",
      "A resource controlled by the entity from which future economic benefits are probable and can be measured reliably",
      "Any resource that is legally owned by the entity",
      "A present obligation of the entity to transfer an economic resource as a result of past events",
    ],
    correct: 0,
    explanation:
      "The current definition is a present economic resource controlled by the entity as a result of past events, an economic resource being a right with the potential to produce economic benefits. The second option is the SUPERSEDED definition — 'probable' and 'reliably measured' were removed from the definition and moved to recognition. Control, not legal ownership, is the test (e.g. leased assets). The fourth option is the definition of a liability.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-A-06",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "Which of the following best reflects the current Conceptual Framework definition of a LIABILITY?",
    options: [
      "A future sacrifice of economic benefits that is probable and can be measured reliably",
      "A present obligation of the entity to transfer an economic resource as a result of past events",
      "Any amount owed to a third party that is legally enforceable",
      "A present economic resource controlled by the entity as a result of past events",
    ],
    correct: 1,
    explanation:
      "A liability is a present obligation to transfer an economic resource as a result of past events. The first option imports the old 'probable/reliably measured' thresholds into the definition — these now belong to recognition, not the definition. A liability can be constructive as well as legal, so requiring legal enforceability is too narrow. The final option is the definition of an asset.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR2-A-07",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "Under the Conceptual Framework, which statement about income, expenses and equity is correct?",
    options: [
      "Income is any inflow of cash received during the period",
      "Equity is defined directly as the amount for which the shareholders could sell their shares",
      "Income is increases in assets, or decreases in liabilities, that result in increases in equity other than contributions from holders of equity claims",
      "Expenses include distributions to owners such as dividends paid",
    ],
    correct: 2,
    explanation:
      "Income is defined via changes in assets and liabilities that increase equity, excluding owner contributions. Income is not the same as cash inflows (cash received in advance is a liability, not income). Equity is the residual (assets less liabilities), not the market value of shares. Dividends are distributions to owners and are not expenses.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-A-08",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "The 2018 Conceptual Framework revised the criteria for recognising an element. An asset or liability is now recognised only if recognition provides users with:",
    options: [
      "Information about a flow of economic benefits that is more than 50% probable, regardless of measurement",
      "A legally enforceable right or obligation, irrespective of relevance",
      "Certainty that the future economic benefits will flow to or from the entity",
      "Relevant information and a faithful representation, weighing the benefits of that information against the cost of providing it",
    ],
    correct: 3,
    explanation:
      "Recognition now depends on whether it results in relevant information and a faithful representation, subject to the cost constraint — the old fixed 'probable inflow + reliable measurement' thresholds were removed. Legal enforceability alone is not the test, and recognition never requires certainty (uncertainty is addressed through relevance and faithful representation, including disclosure).",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR2-A-09",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "Under the Conceptual Framework, derecognition of an asset normally occurs when:",
    options: [
      "The entity loses control of all or part of the recognised asset",
      "The asset becomes fully depreciated, regardless of whether control is retained",
      "Management decides the asset is no longer strategically important to the business",
      "The asset's fair value falls below its carrying amount",
    ],
    correct: 0,
    explanation:
      "Derecognition of an asset is triggered by the loss of control over all or part of it. A fully depreciated asset that is still controlled and used is not derecognised (it stays at nil or residual value). A change in management's strategic view does not, of itself, remove control. A fall in fair value below carrying amount is an impairment/measurement issue, not derecognition.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-A-10",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "Which of the following is a feature of the HISTORICAL COST measurement basis under the Conceptual Framework?",
    options: [
      "It is updated at each reporting date to reflect current market conditions",
      "It measures assets at the value of the costs incurred to acquire or create them, updated only for consumption, impairment or collection",
      "It reflects the price that would be received to sell the asset in an orderly transaction between market participants at the measurement date",
      "It measures a liability at the present value of the cash the entity expects to be obliged to transfer",
    ],
    correct: 1,
    explanation:
      "Historical cost is an entry value that is updated only for consumption (e.g. depreciation), impairment or payment/collection — it is not routinely remeasured to current conditions. Options that update to current market conditions or use exit/selling price describe fair value, and the present value of expected transfers is fulfilment value; both of these are CURRENT value bases, not historical cost.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-A-11",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "Which of the following is NOT a current value measurement basis identified in the Conceptual Framework?",
    options: [
      "Fair value",
      "Value in use (for assets) or fulfilment value (for liabilities)",
      "Historical cost",
      "Current cost",
    ],
    correct: 2,
    explanation:
      "The Framework identifies two broad measurement bases: historical cost and current value. Current value comprises fair value, value in use / fulfilment value, and current cost. Historical cost is the other, separate basis and is therefore NOT a current value basis.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-A-12",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "In the context of the Conceptual Framework's chapter on the reporting entity, which statement is correct?",
    options: [
      "A reporting entity must always be a single legal entity",
      "Consolidated financial statements provide information about the parent alone as a single legal entity",
      "A reporting entity is always a group comprising a parent and its subsidiaries",
      "A reporting entity is an entity that is required, or chooses, to prepare financial statements; it can be a single entity, a portion of an entity, or comprise more than one entity",
    ],
    correct: 3,
    explanation:
      "A reporting entity need not be a legal entity and may be a single entity, a portion of an entity, or more than one entity (e.g. a group). Consolidated statements report on the parent AND its subsidiaries as a single economic unit, not the parent alone. A reporting entity is not always a group — an individual company preparing its own statements is a reporting entity too.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR2-A-13",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "An entity adopts the PHYSICAL capital maintenance concept. Under this concept, a profit is earned only if:",
    options: [
      "The physical productive capacity of the entity at the end of the period exceeds that at the beginning, after excluding transactions with owners",
      "Closing net assets in money terms exceed opening net assets, with no adjustment for price changes",
      "Closing net assets exceed opening net assets after adjusting the opening figure for the change in a general price index",
      "Revenue exceeds the cash expenses actually paid during the period",
    ],
    correct: 0,
    explanation:
      "Physical capital maintenance defines profit only after the entity's physical operating (productive) capacity is maintained, and it requires the current cost measurement basis. Measuring maintenance of money net assets with no price adjustment is MONEY (nominal) financial capital maintenance; adjusting opening capital by a general price index is REAL financial capital maintenance. A cash revenue-less-expenses test ignores accruals and capital maintenance altogether.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-A-14",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "Which statement about MATERIALITY under the Conceptual Framework and IAS 1 is correct?",
    options: [
      "Materiality is a uniform quantitative threshold (for example 5% of profit) prescribed by the IASB",
      "Information is material if omitting, misstating or obscuring it could reasonably be expected to influence the decisions of primary users; materiality is entity-specific",
      "Materiality applies only to the statement of financial position",
      "An item that is quantitatively small can never be material",
    ],
    correct: 1,
    explanation:
      "Materiality is entity-specific and judgemental — the IASB deliberately sets no fixed percentage threshold. It concerns whether omitting, misstating or obscuring information could influence users' decisions, and applies to all the financial statements, not just the statement of financial position. Small items can be material for qualitative reasons (e.g. related-party dealings or a change that turns a loss into a profit).",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR2-A-15",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "The principle that transactions should be accounted for according to their commercial reality rather than merely their legal form is best described as:",
    options: [
      "Prudence",
      "Consistency",
      "Substance over form, which is an aspect of faithful representation",
      "The accruals (matching) concept",
    ],
    correct: 2,
    explanation:
      "Reporting substance over form is part of faithful representation — representing the economic phenomenon rather than only its legal form. Prudence is caution under uncertainty; consistency is using the same methods over time; and accruals is recognising effects when they occur rather than when cash moves — none of these is the substance-over-form principle.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR2-A-16",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "The Conceptual Framework describes prudence as supporting neutrality. Which statement reflects the CURRENT meaning of prudence?",
    options: [
      "Prudence requires the deliberate understatement of assets and income to create hidden reserves",
      "Prudence permits the deliberate overstatement of liabilities in order to smooth reported profits",
      "Prudence has been removed from the Framework entirely",
      "Prudence is the exercise of caution when making judgements under conditions of uncertainty, and it does not permit the deliberate over- or under-statement of assets, liabilities, income or expenses",
    ],
    correct: 3,
    explanation:
      "Prudence is caution under uncertainty and supports neutrality; crucially, it does NOT permit deliberate misstatement in either direction. Deliberately understating assets/income or overstating liabilities to create reserves or smooth profits breaches neutrality. Prudence was not removed — it was reinstated explicitly in the 2018 Framework.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-A-17",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "Which statement about the GOING CONCERN assumption is correct under the Conceptual Framework and IAS 1?",
    options: [
      "Financial statements are normally prepared assuming the entity will continue in operation for the foreseeable future; if management intends or needs to liquidate or cease trading, a break-up basis is used and the fact is disclosed",
      "Going concern is one of the enhancing qualitative characteristics of useful information",
      "The going concern assessment must cover a period of exactly 12 months from the reporting date and no longer",
      "If there is any doubt whatsoever about going concern, the entity must immediately adopt the historical cost measurement basis",
    ],
    correct: 0,
    explanation:
      "Going concern is an underlying assumption: statements assume continuity unless liquidation or ceasing to trade is intended or unavoidable, in which case a different basis is used and disclosed. It is an assumption, not an enhancing qualitative characteristic. The assessment covers at least, but is not limited to, 12 months — it is not capped at 12 months. Doubt (a material uncertainty) triggers disclosure, not an automatic change of measurement basis.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR2-A-18",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "Which statement about the IFRS standard-setting structure and due process is correct?",
    options: [
      "The IFRS Interpretations Committee issues full IFRS Standards",
      "The IASB develops and issues IFRS Standards, and its due process includes publishing exposure drafts and public consultation",
      "The IFRS Foundation Trustees write the technical content of the Standards",
      "IFRS Standards automatically have the force of law in every jurisdiction without any local endorsement process",
    ],
    correct: 1,
    explanation:
      "The IASB sets IFRS Standards through a transparent due process involving exposure drafts and public consultation. The Interpretations Committee issues interpretations (e.g. IFRIC pronouncements) and addresses application questions, not full Standards. The Trustees provide governance and oversight, not the technical drafting. IFRS Standards acquire legal force only where a jurisdiction adopts or endorses them.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-A-19",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "IFRS Standards are generally described as 'principles-based' rather than 'rules-based'. A consequence of a principles-based approach is that:",
    options: [
      "There is no need for professional judgement because every situation is fully prescribed in advance",
      "Detailed numerical rules eliminate any possibility of structuring transactions to circumvent a standard",
      "It relies on professional judgement to apply broad principles, which can improve relevance but requires robust disclosure and ethical application",
      "It guarantees that all entities produce identical accounting treatments in every circumstance",
    ],
    correct: 2,
    explanation:
      "A principles-based approach depends on professional judgement applied to broad principles, which enhances relevance but makes robust disclosure and ethics essential. It does not remove the need for judgement (that describes a rules-based system). Rules-based regimes are actually MORE prone to 'form over substance' structuring around bright lines. And judgement means treatments will not be perfectly identical across all entities and circumstances.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-A-20",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "A financial accountant is offered a large bonus that depends on the company reporting profit above a target. She is considering recognising revenue early on incomplete contracts to hit the target. Under the IESBA/ACCA Code, this primarily creates which threat, and what is the correct response?",
    options: [
      "A familiarity threat; she should document her reasoning and proceed with the early recognition",
      "An advocacy threat; she should recognise the revenue because senior management supports it",
      "No threat arises because performance-related bonus schemes are normal commercial practice",
      "A self-interest threat to objectivity and integrity; she must not manipulate revenue recognition, should apply IFRS 15 faithfully, and should consider safeguards including escalation and, if unresolved, seeking advice",
    ],
    correct: 3,
    explanation:
      "A personal financial incentive to misstate profit is the classic self-interest threat to objectivity and integrity. It is not a familiarity threat (that arises from close relationships) nor an advocacy threat (promoting a client's position); management support does not make the manipulation acceptable. The existence of a bonus is not itself the problem — using it to justify breaching IFRS 15 is. The correct response is to apply the standard faithfully and use safeguards such as escalation.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR2-A-21",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "Which of the following correctly lists the FIVE fundamental principles in the IESBA/ACCA Code of Ethics?",
    options: [
      "Integrity; objectivity; professional competence and due care; confidentiality; professional behaviour",
      "Integrity; independence; prudence; confidentiality; professional behaviour",
      "Honesty; objectivity; scepticism; confidentiality; regulatory compliance",
      "Integrity; objectivity; materiality; going concern; professional behaviour",
    ],
    correct: 0,
    explanation:
      "The five fundamental principles are integrity, objectivity, professional competence and due care, confidentiality, and professional behaviour. Independence is a requirement for assurance engagements rather than one of the five fundamental principles, and prudence, scepticism, materiality and going concern are accounting/audit concepts — not fundamental ethical principles — so the other lists are incorrect.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-A-22",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "An accountant posts misleading claims on social media that exaggerate her firm's services and disparage a competitor. Which fundamental principle is she most directly breaching?",
    options: [
      "Confidentiality",
      "Professional behaviour",
      "Professional competence and due care",
      "Objectivity",
    ],
    correct: 1,
    explanation:
      "Professional behaviour requires compliance with laws and regulations and avoiding conduct that discredits the profession, including making exaggerated claims or unsubstantiated comparisons with others. Confidentiality concerns misuse of information, competence concerns maintaining skill and diligence, and objectivity concerns bias or undue influence — none of these is the principle most directly breached by misleading marketing.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR2-A-23",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "Which statement about the IASB's Management Commentary and the objective of a narrative report accompanying the financial statements is correct?",
    options: [
      "Management commentary forms part of the audited financial statements and must reconcile line by line to the trial balance",
      "Management commentary is prohibited from containing any forward-looking information",
      "Management commentary provides management's insight into the entity's performance, position and prospects, complementing but not forming part of the financial statements, and should be balanced and free from bias",
      "Management commentary is intended as a complete replacement for the notes to the financial statements",
    ],
    correct: 2,
    explanation:
      "Management commentary is a narrative report that accompanies but does not form part of the financial statements; it gives management's balanced, unbiased view of performance, position and prospects (which can include forward-looking information about risks and strategy). It is therefore not part of the audited primary statements, is not barred from forward-looking content, and does not replace the notes.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR2-A-24",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "During an engagement an accountant discovers strong evidence of money laundering by a client. Regarding the fundamental principle of CONFIDENTIALITY, the correct position is:",
    options: [
      "Confidentiality is absolute and overrides any legal duty to report the matter",
      "He may sell the information to interested third parties because it now concerns the public interest",
      "He should immediately publish the findings publicly to warn the market",
      "Confidentiality does not apply where there is a legal or professional right or duty to disclose; suspected money laundering must be reported to the appropriate authority, for example through the firm's money laundering reporting officer",
    ],
    correct: 3,
    explanation:
      "Confidentiality is not absolute — it yields where there is a legal or professional right or duty to disclose, and suspected money laundering carries a legal reporting obligation (typically via the MLRO to the relevant authority). Selling the information would itself breach confidentiality and integrity, and publishing it to the market is neither authorised nor the correct channel; the required route is a report to the proper authority, not public disclosure.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR2-A-25",
    paper: "SBR",
    area: "A",
    type: "mcq",
    stem: "The enhancing qualitative characteristic of UNDERSTANDABILITY implies that:",
    options: [
      "Information is classified, characterised and presented clearly and concisely, while assuming users have a reasonable knowledge of business and economic activities and are willing to study the information diligently",
      "Complex economic phenomena should be excluded from the financial statements whenever they are difficult for users to understand",
      "Financial statements must be made understandable to any member of the public who has no financial knowledge at all",
      "Information should be simplified even where doing so would make it less relevant or less faithfully represented",
    ],
    correct: 0,
    explanation:
      "Understandability means presenting information clearly and concisely, assuming a reasonably knowledgeable and diligent user. It does NOT justify omitting complex but relevant matters (that would reduce relevance/completeness), it does not target users with no financial knowledge, and it must not be pursued at the expense of relevance or faithful representation.",
    marks: 2,
    difficulty: "easy",
  },
  /* ═══════════════ Area B — Reporting financial performance (30 mcq + 10 number) ═══════════════ */
  {
    id: "SBR2-B-01",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "IFRS 15 uses a five-step model for recognising revenue. Which of the following is the correct FIRST step of the model?",
    options: [
      "Determine the transaction price",
      "Identify the contract with a customer",
      "Allocate the transaction price to the performance obligations",
      "Recognise revenue when (or as) a performance obligation is satisfied",
    ],
    correct: 1,
    explanation:
      "The five steps in order are: (1) identify the contract, (2) identify the performance obligations, (3) determine the transaction price, (4) allocate the price to the obligations, and (5) recognise revenue as obligations are satisfied. Determining and allocating the price and recognising revenue are steps 3, 4 and 5 respectively, so they cannot be the first step.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR2-B-02",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Under IFRS 15, revenue is recognised OVER TIME (rather than at a single point in time) when which criterion is met?",
    options: [
      "The customer has paid a non-refundable deposit at the start of the contract",
      "Legal title to the goods has passed to the customer",
      "The entity's performance creates an asset with no alternative use to the entity and the entity has an enforceable right to payment for performance completed to date",
      "The goods have been physically delivered to the customer's premises",
    ],
    correct: 2,
    explanation:
      "One of the three over-time criteria is that performance creates an asset with no alternative use plus an enforceable right to payment for work done to date (the others being the customer simultaneously receiving and consuming the benefits, or the customer controlling the asset as it is created). A deposit, the passing of legal title, and physical delivery are indicators of transfer of control at a POINT in time, not over-time criteria.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-B-03",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Vellamo operates an online platform that arranges sales of independent artisans' goods. It never obtains control of the goods before they transfer to buyers, and it earns a fixed commission on each sale. Under IFRS 15, Vellamo should recognise revenue equal to:",
    options: [
      "The gross amount paid by the customer, because it processes the customer's payment",
      "The gross amount paid by the customer, because it sets the price displayed on the website",
      "Nil, because online platforms are never permitted to recognise revenue",
      "The net commission it retains, because it acts as an agent — it does not obtain control of the goods before they are transferred to the buyer",
    ],
    correct: 3,
    explanation:
      "Because Vellamo never controls the goods before transfer, it is an agent and recognises only the net commission. Processing payment and displaying a price are not, on their own, evidence of control, so recognising the gross amount would wrongly treat an agent as a principal. Recognising nil is also wrong — the agent still earns and recognises its commission revenue.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-B-04",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Under IFRS 15, a contract modification is accounted for as a SEPARATE contract when:",
    options: [
      "The modification adds distinct goods or services and the contract price increases by an amount that reflects their standalone selling prices",
      "The remaining goods are not distinct from those already transferred and form part of a single performance obligation",
      "The modification only changes the price of goods that have already been delivered",
      "The customer cancels the original contract in its entirety",
    ],
    correct: 0,
    explanation:
      "A modification is a separate contract only if it adds distinct goods/services priced at their standalone selling prices. If the added goods are not distinct, the modification is treated as part of the existing contract using a cumulative catch-up (or, for distinct remaining goods not at standalone price, prospectively). A repricing of already-delivered goods and a full cancellation are not the separate-contract scenario.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR2-B-05",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "IFRS 15 requires variable consideration to be estimated using either the expected value or the most likely amount, and then included in the transaction price only to the extent that:",
    options: [
      "The full estimated amount is always included regardless of the level of uncertainty",
      "It is highly probable that a significant reversal of cumulative revenue recognised will not occur when the uncertainty is subsequently resolved",
      "The customer has confirmed the variable amount in writing",
      "The variable element exceeds 50% of the fixed consideration in the contract",
    ],
    correct: 1,
    explanation:
      "This is the 'constraint' on variable consideration: include it only if it is highly probable that a significant revenue reversal will not occur when the uncertainty resolves. It is therefore not always included in full, does not require written customer confirmation, and does not depend on any fixed percentage relationship to the fixed consideration.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-B-06",
    paper: "SBR",
    area: "B",
    type: "number",
    stem: "Aldermoor Co leases equipment on 1 January under a 4-year lease with payments of $50,000 payable ANNUALLY IN ARREARS. The interest rate implicit in the lease is 8%. Under IFRS 16, what is the lease liability recognised at inception, to the nearest $?",
    numericAnswer: 165606,
    unit: "$",
    tolerance: 300,
    explanation:
      "The lease liability is the present value of the lease payments. The 4-year annuity factor at 8% is (1 - 1.08^-4) / 0.08 = (1 - 0.735030) / 0.08 = 0.264970 / 0.08 = 3.31213. Liability = $50,000 x 3.31213 = $165,606 (to the nearest $). Discounting each payment individually (50,000/1.08 + 50,000/1.08^2 + 50,000/1.08^3 + 50,000/1.08^4) gives the same result.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-B-07",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Under IFRS 16, a lessee is permitted (but not required) to elect NOT to recognise a right-of-use asset and lease liability for which of the following?",
    options: [
      "All leases with a lease term exceeding 12 months",
      "Leases of specialised, high-value equipment",
      "Short-term leases of 12 months or less, and leases of low-value assets",
      "Any lease where the lessee is not the legal owner of the underlying asset",
    ],
    correct: 2,
    explanation:
      "IFRS 16 provides recognition exemptions for short-term leases (12 months or less, with no purchase option) and low-value asset leases; for these the lessee may expense payments on a straight-line basis. Leases over 12 months and high-value equipment are exactly what must be capitalised, and the whole model applies to lessees precisely because they control a right of use without owning the asset.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-B-08",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Selby Co sells a building to a finance house and immediately leases it back. The transfer QUALIFIES as a sale under IFRS 15. Under IFRS 16, how does the seller-lessee account for the building on the sale-and-leaseback?",
    options: [
      "Recognise the whole gain on the building immediately in profit or loss and derecognise the asset",
      "Recognise no gain and no right-of-use asset, keeping the building on the statement of financial position",
      "Defer the entire gain on the building and release it to profit or loss over the lease term",
      "Recognise a right-of-use asset at the proportion of the previous carrying amount that relates to the right retained, and recognise gain only on the rights transferred to the buyer-lessor",
    ],
    correct: 3,
    explanation:
      "When the transfer is a sale, the seller-lessee measures the right-of-use asset it retains at the proportion of the former carrying amount that relates to the right retained, so it recognises gain only on the portion of rights transferred to the buyer-lessor. Recognising the whole gain overstates profit; recognising no gain and keeping the asset ignores the sale; and deferring and spreading the whole gain reflects the old (pre-IFRS 16) sale-and-leaseback approach.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR2-B-09",
    paper: "SBR",
    area: "B",
    type: "number",
    stem: "On the commencement of a lease, Brackenford Co measures the lease liability at $200,000. It also makes a lease payment of $15,000 on the commencement date, incurs initial direct costs of $4,000, and estimates the present value of dismantling and restoration costs at $10,000. It received a lease incentive of $6,000 from the lessor. Under IFRS 16, what is the initial carrying amount of the right-of-use asset, in $?",
    numericAnswer: 223000,
    unit: "$",
    tolerance: 0,
    explanation:
      "The right-of-use asset = initial lease liability + payments made at/before commencement + initial direct costs + estimated dismantling/restoration costs - lease incentives received. So $200,000 + $15,000 + $4,000 + $10,000 - $6,000 = $223,000. Incentives reduce the asset (they are subtracted, not added), and dismantling and initial direct costs are added.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR2-B-10",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Under IAS 12, the TAX BASE of an asset is:",
    options: [
      "The amount that will be deductible for tax purposes against future taxable economic benefits derived from the asset",
      "The carrying amount of the asset in the financial statements",
      "The original cost of the asset less accumulated accounting depreciation",
      "The fair value of the asset at the reporting date",
    ],
    correct: 0,
    explanation:
      "The tax base of an asset is the amount deductible for tax against future taxable benefits from that asset (for an asset whose benefits are not taxable, the tax base equals the carrying amount). It is a tax concept, so it is not the accounting carrying amount, not cost less accounting depreciation, and not fair value — those are financial-reporting measures.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR2-B-11",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "An asset has a carrying amount of $120,000 and a tax base of $90,000. Under IAS 12, this gives rise to:",
    options: [
      "A deductible temporary difference and a deferred tax asset",
      "A taxable temporary difference and a deferred tax liability",
      "A permanent difference with no deferred tax consequences",
      "No temporary difference because both figures relate to the same asset",
    ],
    correct: 1,
    explanation:
      "For an asset, carrying amount ($120,000) greater than tax base ($90,000) creates a taxable temporary difference of $30,000 and therefore a deferred tax LIABILITY (more tax will be payable in future as the extra carrying amount is recovered). A deductible difference and deferred tax asset arise when carrying amount is below tax base; this is a temporary, not permanent, difference; and the two figures differing is exactly what creates the difference.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-B-12",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Which statement about IAS 12 deferred tax is correct?",
    options: [
      "Deferred tax is always measured using the tax rate that applied when the temporary difference first arose",
      "A deferred tax asset is recognised in full irrespective of the availability of future taxable profits",
      "Deferred tax on a revaluation surplus is recognised, and the related tax is charged to other comprehensive income to match where the surplus is recognised",
      "Deferred tax balances are discounted to their present value",
    ],
    correct: 2,
    explanation:
      "Deferred tax follows the item it relates to: tax on a revaluation surplus (recognised in OCI) is itself recognised in OCI. Deferred tax is measured at the rate expected to apply when the difference reverses (enacted or substantively enacted), not the rate when it arose. A deferred tax asset is recognised only to the extent that future taxable profit is probable. IAS 12 explicitly prohibits discounting of deferred tax.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR2-B-13",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Under IAS 37, a provision is recognised only when ALL of the following conditions are met:",
    options: [
      "There is a possible obligation, an outflow is merely possible, and the amount can be estimated",
      "The directors intend to incur the expenditure and have announced it to staff internally",
      "There is a present obligation, an outflow of benefits is remote, and a reliable estimate can be made",
      "There is a present obligation (legal or constructive) arising from a past event, a probable outflow of economic benefits, and a reliable estimate of the amount can be made",
    ],
    correct: 3,
    explanation:
      "A provision requires a present obligation from a past event, a probable outflow, and a reliable estimate. A 'possible' obligation or 'possible' outflow describes a contingent liability (disclosed, not provided). A mere internal intention is not an obligation (a constructive obligation needs a valid expectation raised in others). If the outflow is remote, nothing is recognised or even disclosed.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-B-14",
    paper: "SBR",
    area: "B",
    type: "number",
    stem: "Cranmoor Co revalues an item of property, plant and equipment upward. After the revaluation the carrying amount is $500,000 and the tax base is $360,000. The applicable tax rate is 25%. Under IAS 12, what is the deferred tax LIABILITY arising, in $?",
    numericAnswer: 35000,
    unit: "$",
    tolerance: 0,
    explanation:
      "The taxable temporary difference is carrying amount less tax base = $500,000 - $360,000 = $140,000. Deferred tax liability = $140,000 x 25% = $35,000. Because the difference arises on a revaluation, the deferred tax charge is recognised in other comprehensive income (against the revaluation surplus), but the LIABILITY recognised is $35,000.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR2-B-15",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Under IAS 37, a CONTINGENT LIABILITY is:",
    options: [
      "A possible obligation whose existence depends on uncertain future events, or a present obligation not recognised because an outflow is not probable or cannot be reliably measured — it is disclosed, not recognised",
      "Always recognised as a provision in the statement of financial position",
      "A present obligation with a probable outflow that can be reliably measured",
      "An asset whose existence is virtually certain to be confirmed",
    ],
    correct: 0,
    explanation:
      "A contingent liability is either a possible obligation confirmed by uncertain future events, or a present obligation failing the recognition tests (outflow not probable or not reliably measurable); it is disclosed (unless remote), not recognised. A present obligation with a probable, measurable outflow is a PROVISION (so it is recognised). A virtually certain inflow describes a recognised asset, not a contingent liability.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR2-B-16",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Dunhollow Co owns a building that it rents out to independent third parties to earn rentals and for capital appreciation; it is not owner-occupied. Under IFRS, this building is:",
    options: [
      "Property, plant and equipment under IAS 16, depreciated over its useful life",
      "Investment property under IAS 40, which may be measured using either the cost model or the fair value model",
      "Inventory under IAS 2, held at the lower of cost and net realisable value",
      "A non-current asset held for sale under IFRS 5",
    ],
    correct: 1,
    explanation:
      "Property held to earn rentals and/or for capital appreciation, rather than for use in production or administration, is investment property under IAS 40, measured using the cost model or the fair value model. It is not owner-occupied PPE under IAS 16, not inventory held for sale in the ordinary course of business, and not held for sale under IFRS 5 (which needs an active plan to sell in its current condition).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-B-17",
    paper: "SBR",
    area: "B",
    type: "number",
    stem: "Eshford Co enters into a contract with a customer for a total price of $120,000, comprising two distinct performance obligations: Product A (standalone selling price $90,000) and Service B (standalone selling price $60,000). Under IFRS 15, how much of the transaction price is allocated to Product A, in $?",
    numericAnswer: 72000,
    unit: "$",
    tolerance: 0,
    explanation:
      "Allocate the transaction price in proportion to standalone selling prices. Total standalone selling price = $90,000 + $60,000 = $150,000. Product A share = $120,000 x ($90,000 / $150,000) = $120,000 x 0.60 = $72,000. (Service B receives the remaining $48,000.)",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-B-18",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Under the IAS 40 FAIR VALUE model for investment property, which statement is correct?",
    options: [
      "The property is depreciated over its useful life and tested for impairment each year",
      "Changes in fair value are recognised in other comprehensive income and accumulated in a revaluation surplus",
      "The property is not depreciated, and gains or losses arising from changes in its fair value are recognised in profit or loss for the period",
      "Fair value gains are taken to a revaluation surplus within equity, exactly as under the IAS 16 revaluation model",
    ],
    correct: 2,
    explanation:
      "Under the IAS 40 fair value model the property is remeasured to fair value at each reporting date, it is NOT depreciated, and fair value changes go to profit or loss. This differs from the IAS 16 revaluation model, where increases go to OCI/revaluation surplus and the asset is still depreciated — so the options routing gains to OCI or a revaluation surplus, or depreciating the asset, are incorrect for IAS 40 fair value.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR2-B-19",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Fenwick Co receives a government grant to help fund the purchase of qualifying plant. Under IAS 20, which treatment is NOT permitted?",
    options: [
      "Deducting the grant from the carrying amount of the asset (the net presentation)",
      "Presenting the grant as deferred income and releasing it to profit or loss over the asset's useful life",
      "Recognising the grant in profit or loss on a systematic basis over the periods in which the related costs are recognised",
      "Crediting the entire grant directly to retained earnings when it is received, bypassing profit or loss altogether",
    ],
    correct: 3,
    explanation:
      "IAS 20 requires grants to be recognised in profit or loss on a systematic basis matching the related costs; for asset grants this is achieved either by netting the grant against the asset's carrying amount or by using a deferred income approach released over the asset's life. Crediting the whole grant straight to retained earnings bypasses profit or loss entirely and is not permitted.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-B-20",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Under IAS 38, expenditure incurred in the RESEARCH phase of an internal project must be:",
    options: [
      "Recognised as an expense when it is incurred",
      "Capitalised as an intangible asset in all circumstances",
      "Capitalised only where the overall project is expected to be profitable",
      "Recognised as goodwill on the statement of financial position",
    ],
    correct: 0,
    explanation:
      "Research expenditure is always expensed as incurred because the entity cannot yet demonstrate that a future economic benefit will arise. Only DEVELOPMENT costs may be capitalised, and only when all the specified criteria are met. Research can never be capitalised, and internally generated goodwill is explicitly prohibited from recognition.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR2-B-21",
    paper: "SBR",
    area: "B",
    type: "number",
    stem: "Garrowby Co has a legal obligation to decommission an offshore platform in exactly 5 years' time, at an estimated cost of $2,000,000. An appropriate discount rate is 6%. Under IAS 37, at what amount should the decommissioning provision be recognised today, to the nearest $?",
    numericAnswer: 1494516,
    unit: "$",
    tolerance: 1000,
    explanation:
      "Where the effect of the time value of money is material, the provision is the present value of the expected expenditure. Discount factor = 1 / 1.06^5 = 1 / 1.338226 = 0.747258. Provision = $2,000,000 x 0.747258 = $1,494,516 (to the nearest $). The unwinding of the discount is later charged as a finance cost.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR2-B-22",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Under IAS 38, development costs are capitalised only if the entity can demonstrate all of a set of criteria. Which of the following is one of those required criteria?",
    options: [
      "That the project has already generated revenue during the current period",
      "That the entity has the intention and ability to complete the asset and to use or sell it, and can measure the development expenditure reliably",
      "That the directors have formally approved a marketing budget for the finished product",
      "That the intangible asset's fair value can be measured using a quoted price in an active market",
    ],
    correct: 1,
    explanation:
      "The recognition criteria (often remembered as PIRATE) include probable future economic benefits, intention to complete, resources/ability to complete, technical feasibility, ability to use or sell, and reliable measurement of expenditure. Prior revenue generation, an approved marketing budget and a quoted fair value are not conditions for capitalising development costs.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-B-23",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "A cash-generating unit (CGU) that contains goodwill is impaired. Under IAS 36, the impairment loss is allocated:",
    options: [
      "Pro rata across all assets of the unit, including goodwill, simultaneously",
      "First to the other assets of the unit pro rata, and only then to goodwill",
      "First to reduce the goodwill of the unit to nil, then to the other assets of the unit pro rata on the basis of their carrying amounts, subject to the floors for individual assets",
      "Entirely to the current assets of the unit such as inventory and receivables",
    ],
    correct: 2,
    explanation:
      "IAS 36 allocates a CGU impairment first to goodwill (writing it to nil), then pro rata to the other assets by carrying amount. No individual asset is written below the highest of its fair value less costs of disposal, its value in use, or zero. Allocating simultaneously, to other assets before goodwill, or only to current assets all breach that order and the floor rule.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR2-B-24",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Under IAS 36, the RECOVERABLE AMOUNT of an asset is:",
    options: [
      "The asset's carrying amount in the financial statements",
      "The asset's fair value less costs of disposal only",
      "The lower of the asset's value in use and its fair value less costs of disposal",
      "The higher of the asset's fair value less costs of disposal and its value in use",
    ],
    correct: 3,
    explanation:
      "Recoverable amount is the HIGHER of fair value less costs of disposal and value in use — the entity is assumed to choose the more beneficial way of recovering the asset. It is not the carrying amount (which is compared against recoverable amount), not fair value alone, and taking the LOWER of the two would overstate impairment.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR2-B-25",
    paper: "SBR",
    area: "B",
    type: "number",
    stem: "A cash-generating unit has a carrying amount of $2,400,000, which includes goodwill of $400,000. Its fair value less costs of disposal is $1,800,000 and its value in use is $1,950,000. Under IAS 36, what is the total impairment loss for the CGU, in $?",
    numericAnswer: 450000,
    unit: "$",
    tolerance: 0,
    explanation:
      "Recoverable amount is the higher of fair value less costs of disposal ($1,800,000) and value in use ($1,950,000), i.e. $1,950,000. Impairment loss = carrying amount - recoverable amount = $2,400,000 - $1,950,000 = $450,000. This loss is allocated first against the $400,000 of goodwill, with the remaining $50,000 spread pro rata across the other assets.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR2-B-26",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Under IAS 2, inventories are measured at:",
    options: [
      "The lower of cost and net realisable value",
      "The lower of cost and fair value less costs to sell",
      "The higher of cost and net realisable value",
      "Current replacement cost at the reporting date",
    ],
    correct: 0,
    explanation:
      "IAS 2 measures inventory at the lower of cost and net realisable value (estimated selling price less costs to complete and sell). Net realisable value is an entity-specific value and is not the same as fair value less costs to sell. Taking the HIGHER of cost and NRV would overstate inventory, and replacement cost is not the IAS 2 basis for ordinary inventory.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-B-27",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Under IAS 41, a biological asset (for example a dairy herd) is generally measured at:",
    options: [
      "Historical cost less accumulated depreciation and impairment",
      "Fair value less costs to sell, with changes in that measurement recognised in profit or loss",
      "Net realisable value at the reporting date",
      "Value in use based on discounted future cash flows",
    ],
    correct: 1,
    explanation:
      "IAS 41 measures biological assets at fair value less costs to sell (unless fair value cannot be reliably measured on initial recognition), with gains and losses in profit or loss. Agricultural produce at the point of harvest is measured the same way and then falls under IAS 2. Historical cost, net realisable value and value in use are not the IAS 41 measurement basis.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-B-28",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Hartcliffe Co grants its employees share appreciation rights (SARs) that will be settled in CASH based on the increase in the company's share price. Under IFRS 2, this is a cash-settled share-based payment, which means that:",
    options: [
      "A fixed expense is measured at the grant date and is never subsequently remeasured",
      "The corresponding credit is recognised within equity rather than as a liability",
      "A liability is recognised and remeasured to fair value at each reporting date and at settlement, with changes recognised in profit or loss",
      "No expense is recognised at all until the cash is finally paid to employees",
    ],
    correct: 2,
    explanation:
      "A cash-settled share-based payment creates a LIABILITY that is remeasured to fair value at each reporting date and at settlement, with all changes in profit or loss. Fixing the expense at grant date with no remeasurement, and crediting equity, both describe EQUITY-settled treatment. An expense accrues over the vesting period as services are received, not only when cash is paid.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR2-B-29",
    paper: "SBR",
    area: "B",
    type: "number",
    stem: "Ingleby Co grants 500 share options to each of its 200 employees, vesting after 3 years of continuous service. The fair value of each option at the grant date is $8. At the end of year 1, the company expects 90% of the employees to remain in service until the options vest. Under IFRS 2, what is the equity-settled expense to be recognised for year 1, in $?",
    numericAnswer: 240000,
    unit: "$",
    tolerance: 0,
    explanation:
      "Total options expected to vest = 200 employees x 500 options x 90% = 90,000 options. Total expected cost at grant-date fair value = 90,000 x $8 = $720,000. This is spread over the 3-year vesting period, so the year 1 expense = $720,000 x 1/3 = $240,000. Equity-settled awards use the grant-date fair value and are not remeasured for share-price changes.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-B-30",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Under IAS 21, the FUNCTIONAL CURRENCY of an entity is:",
    options: [
      "Always the currency of the country in which the entity is legally incorporated",
      "A currency the entity may select freely purely for reporting convenience",
      "The presentation currency chosen by the group for its consolidated statements",
      "The currency of the primary economic environment in which the entity operates",
    ],
    correct: 3,
    explanation:
      "Functional currency is the currency of the primary economic environment in which the entity operates — determined by factors such as the currency that mainly influences sales prices and costs. It is not automatically the currency of incorporation, cannot be chosen freely for convenience, and is distinct from the presentation currency, which an entity may choose but which does not change the functional currency.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR2-B-31",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Under IAS 21, at the reporting date, which items are retranslated using the CLOSING rate?",
    options: [
      "Monetary items, such as foreign currency payables, receivables and cash balances",
      "Non-monetary items that are measured at historical cost",
      "All items, both monetary and non-monetary, without exception",
      "Only the equity items of the entity",
    ],
    correct: 0,
    explanation:
      "At each reporting date monetary items are retranslated at the closing rate, with exchange differences in profit or loss. Non-monetary items carried at historical cost stay at the transaction-date (historical) rate; non-monetary items at fair value use the rate at the date fair value was measured. It is therefore incorrect to retranslate all items, or only equity, at the closing rate.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-B-32",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "After the reporting date but before the financial statements are authorised for issue, Jarrow Co's board declares an ordinary dividend, and separately a major customer that owed a balance at the year end becomes insolvent. Under IAS 10, the correct treatment is:",
    options: [
      "Both events are adjusting events and both are recognised in the financial statements",
      "The customer insolvency is an adjusting event (adjust the receivable/allowance); the dividend declared after the reporting date is a non-adjusting event, not recognised as a liability but disclosed",
      "Both events are non-adjusting events and neither is recognised",
      "The dividend is an adjusting event and the customer insolvency is a non-adjusting event",
    ],
    correct: 1,
    explanation:
      "The customer's insolvency provides evidence about a receivable's recoverability at the year end, so it is an adjusting event. A dividend declared after the reporting date does not create a present obligation at the year end, so it is non-adjusting: it is disclosed but not recognised as a liability. Treating both as adjusting, both as non-adjusting, or reversing the two is incorrect.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR2-B-33",
    paper: "SBR",
    area: "B",
    type: "number",
    stem: "Kelbrook Co has a functional currency of the US dollar. On 1 November it buys goods on credit for EUR 500,000 when the spot rate is EUR 1 = USD 1.10. The payable is still outstanding at the year end of 31 December, when the rate is EUR 1 = USD 1.18. Under IAS 21, what exchange LOSS is recognised in profit or loss on the payable, in $?",
    numericAnswer: 40000,
    unit: "$",
    tolerance: 0,
    explanation:
      "The payable is a monetary item, so it is retranslated at the closing rate. Initial value = EUR 500,000 x 1.10 = $550,000; year-end value = EUR 500,000 x 1.18 = $590,000. The liability has increased by $590,000 - $550,000 = $40,000, which is an exchange LOSS recognised in profit or loss (a stronger euro makes the euro payable more expensive in dollars).",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR2-B-34",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Under IFRS 5, a non-current asset is classified as HELD FOR SALE when:",
    options: [
      "Management has a general intention to sell the asset at some unspecified point in the future",
      "The asset is temporarily idle but expected to return to use",
      "Its carrying amount will be recovered principally through a sale transaction rather than continuing use, the sale is highly probable, and the asset is available for immediate sale in its present condition",
      "The asset has been fully depreciated to its residual value",
    ],
    correct: 2,
    explanation:
      "Held-for-sale classification requires that recovery is principally through sale, the sale is highly probable (management committed, active programme to find a buyer, marketed at a reasonable price, sale expected within 12 months) and the asset is available for immediate sale as it is. A vague future intention, temporary idleness, or being fully depreciated do not meet these conditions.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-B-35",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Once classified as held for sale under IFRS 5, a non-current asset (or disposal group) is measured at:",
    options: [
      "The lower of its carrying amount and fair value less costs to sell, and it is no longer depreciated",
      "Fair value, with any gains taken directly to equity",
      "The higher of carrying amount and recoverable amount, and it continues to be depreciated",
      "Value in use based on discounted future cash flows only",
    ],
    correct: 0,
    explanation:
      "On classification as held for sale, the asset is measured at the lower of its carrying amount and fair value less costs to sell, and depreciation ceases (because value is recovered through sale, not use). It is not simply remeasured to fair value with gains to equity, is not held at the higher of carrying amount and recoverable amount, and is not measured at value in use.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR2-B-36",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Under IAS 8, a change in an accounting ESTIMATE (for example revising the useful life of an asset) is accounted for:",
    options: [
      "Retrospectively, by restating the comparative amounts of prior periods",
      "Prospectively, in the current period and, where relevant, future periods affected by the change",
      "As the correction of a prior period error",
      "Directly in equity, with no effect on profit or loss",
    ],
    correct: 1,
    explanation:
      "A change in accounting estimate is applied prospectively — it affects the current and, if relevant, future periods only. Retrospective restatement is used for changes in accounting POLICY, and retrospective restatement of comparatives is used to correct prior period ERRORS. An estimate change flows through profit or loss (or the related asset), not directly to equity.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR2-B-37",
    paper: "SBR",
    area: "B",
    type: "number",
    stem: "Under IAS 36, an asset is expected to generate net cash inflows of $300,000 in year 1, $300,000 in year 2 and $200,000 in year 3, with no residual value. The appropriate discount rate is 10%. What is the asset's value in use, to the nearest $?",
    numericAnswer: 670925,
    unit: "$",
    tolerance: 200,
    explanation:
      "Value in use is the present value of the future cash flows. Year 1: 300,000 / 1.10 = 272,727. Year 2: 300,000 / 1.21 = 247,934. Year 3: 200,000 / 1.331 = 150,264. Total = 272,727 + 247,934 + 150,264 = $670,925 (to the nearest $).",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR2-B-38",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Under IAS 8, a material PRIOR PERIOD ERROR discovered in the current period is corrected by:",
    options: [
      "Adjusting the current year's profit or loss only, with no restatement of prior periods",
      "A prospective adjustment spread over the current and future periods",
      "Retrospectively restating the comparative amounts for the prior period(s) in which the error occurred, or restating opening balances if the error is earlier than the comparatives presented",
      "Disclosing the error in the notes only, with no adjustment to any reported figures",
    ],
    correct: 2,
    explanation:
      "A material prior period error is corrected by retrospective restatement of the comparatives for the affected prior period(s), or by restating the opening balances of the earliest period presented if the error is older. Putting the whole correction through the current year's profit, applying it prospectively, or disclosing without adjusting would all misstate the corrected figures.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-B-39",
    paper: "SBR",
    area: "B",
    type: "mcq",
    stem: "Under IFRS 15, the distinction between a CONTRACT ASSET and a RECEIVABLE is that:",
    options: [
      "They are identical and the two terms may be used interchangeably",
      "A contract asset is always presented as a liability of the entity",
      "A receivable is only recognised after the related cash has been collected from the customer",
      "A receivable is an unconditional right to consideration (only the passage of time is required before payment is due), whereas a contract asset is a right to consideration that is conditional on something other than the passage of time, such as future performance",
    ],
    correct: 3,
    explanation:
      "A receivable is an unconditional right to consideration (only time must pass), while a contract asset is a conditional right — typically the entity has performed but the right to payment still depends on further performance. The two are therefore not interchangeable, a contract asset is an asset not a liability, and a receivable is recognised when the right becomes unconditional, not after cash is received.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR2-B-40",
    paper: "SBR",
    area: "B",
    type: "number",
    stem: "Under IAS 16, Larkhill Co buys a machine for $180,000. It has an estimated residual value of $30,000 and a useful life of 5 years, and is depreciated on a straight-line basis. What is the annual depreciation charge, in $?",
    numericAnswer: 30000,
    unit: "$",
    tolerance: 0,
    explanation:
      "Straight-line depreciation = (cost - residual value) / useful life = ($180,000 - $30,000) / 5 = $150,000 / 5 = $30,000 per year. The depreciable amount excludes the residual value, so dividing the full $180,000 by 5 (which would give $36,000) would be incorrect.",
    marks: 2,
    difficulty: "easy",
  },
]
