import type { AccaQuestion } from "@/lib/acca-content"

/*
 * AA bank wave 8b part 1 — 38 verified originals (2026-07-13).
 * Blueprint: A10 B16 C12; difficulty 11 easy / 17 medium / 10 hard.
 * All mcq, marks 2. Every scenario is invented (original client and firm
 * names, none reused from earlier waves) and every distractor encodes a
 * nameable student error. Answers verified against the IESBA/ACCA Code
 * (threats, contingent fees, gifts, family relationships, confidentiality,
 * management responsibilities), ISA 210, ISQM 1 / ISA 220 (Revised),
 * ISA 240/300/315/320/330, ISA 402, ISA 510, ISA 570, ISA 610 and ISA 265
 * before writing. Correct answers balanced 10/9/9/10 across positions.
 */

export const AA_WAVE3A: AccaQuestion[] = [
  /* ───────────── Area A — Audit framework & regulation (10) ───────────── */
  {
    id: "AA3-A-01",
    paper: "AA",
    area: "A",
    type: "mcq",
    stem: "Croyde & Tate has been offered the external audit of Gorsewood Energy Ltd on the basis that the audit fee will be calculated as 4% of Gorsewood's final audited profit. How should the firm respond?",
    options: [
      "Accept — an advocacy threat arises but it can be reduced with safeguards",
      "Accept, provided the fee basis is disclosed to those charged with governance",
      "Decline the proposed fee basis — contingent fees for audit engagements are prohibited because the self-interest threat cannot be reduced to an acceptable level",
      "Accept, provided the percentage is capped at 5% of profit",
    ],
    correct: 2,
    explanation:
      "A fee that depends on the audited result gives the auditor a direct stake in the numbers — a SELF-INTEREST threat so severe that the Code simply PROHIBITS contingent fees for audit work; no safeguard is adequate. It is not advocacy (no client position is being promoted), disclosure to governance cannot cure a prohibition, and there is no percentage cap in the Code — 'capped contingent fee' is an invented rule.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AA3-A-02",
    paper: "AA",
    area: "A",
    type: "mcq",
    stem: "Fennick & Rowe lends one of its audit supervisors to Alderbeck Foods Ltd, an audit client, for three months to cover the financial controller's sick leave, during which she will help prepare the month-end management accounts. Which threat arises and what safeguard is required?",
    options: [
      "Self-review threat — the loaned staff member must not assume management responsibilities and must not later be part of the team auditing any work she performed",
      "Familiarity threat — the secondment is acceptable provided it lasts less than twelve months",
      "No threat arises provided Alderbeck pays a market rate for the secondment",
      "Intimidation threat — the firm should resign from the audit immediately",
    ],
    correct: 0,
    explanation:
      "If firm staff produce accounting records that the firm then audits, the firm is checking its OWN work — a SELF-REVIEW threat. The safeguards are that the loaned individual takes no management responsibility and is excluded from auditing that work. Familiarity concerns close relationships, and the invented 'twelve-month rule' does not exist; charging a market fee addresses none of it (the threat is about the work, not the price); and intimidation involves pressure, which is absent — resignation is an over-reaction.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA3-A-03",
    paper: "AA",
    area: "A",
    type: "mcq",
    stem: "The board of Silbourne Ltd is proposing a shareholder resolution to remove Marsh & Elden as auditor before the end of its term, following a disagreement over a provision. Which statement about the auditor's rights is correct?",
    options: [
      "Marsh & Elden can veto the resolution, because removal requires the auditor's consent",
      "Marsh & Elden must leave quietly and has no right to communicate with the shareholders",
      "Marsh & Elden is automatically entitled to compensation for the unexpired portion of its term",
      "Marsh & Elden may make written representations for circulation to the shareholders and may attend and speak at the general meeting at which its removal is considered",
    ],
    correct: 3,
    explanation:
      "Shareholders may remove an auditor by resolution at any time, but the auditor has protective RIGHTS: to receive notice, to make written representations that are circulated to members, and to attend and speak at the meeting — so shareholders hear the auditor's side of any disagreement. The auditor has no veto (that would entrench the auditor against the members who appoint them), the 'silent exit' answer destroys the very safeguard the law creates, and compensation is a contractual matter, never automatic.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA3-A-04",
    paper: "AA",
    area: "A",
    type: "mcq",
    stem: "Who ordinarily appoints the external auditor of Quillstone Ltd each year, and who may fill a casual vacancy arising when the auditor resigns mid-term?",
    options: [
      "The finance director appoints in both cases",
      "The shareholders (members) ordinarily appoint by resolution; the directors may fill a casual vacancy until the next general meeting",
      "The audit committee appoints in both cases, with no shareholder involvement",
      "The national audit regulator appoints in both cases",
    ],
    correct: 1,
    explanation:
      "The auditor reports TO the shareholders, so it is the SHAREHOLDERS who ordinarily appoint (and reappoint) the auditor by resolution; the directors' power is limited to appointing the first auditor and filling a casual vacancy until the members can vote. The finance director appointing the person who audits their own figures would destroy independence; the audit committee only RECOMMENDS the appointment; and regulators oversee auditors but do not appoint them to companies.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AA3-A-05",
    paper: "AA",
    area: "A",
    type: "mcq",
    stem: "Hartwell & Odum has audited Brindmore Textiles Ltd for six years. During the current year Brindmore was acquired by a new parent company and changed its financial reporting framework. Regarding the engagement letter, ISA 210 indicates the firm should:",
    options: [
      "Assess whether the terms need to be revised — a change of ownership and of reporting framework are exactly the circumstances that call for a revised engagement letter",
      "Do nothing, because an engagement letter is only ever issued once, on first appointment",
      "Reissue the identical letter, because the terms of an engagement can never be changed",
      "Issue the new letter after the auditor's report is signed, as a record of the work performed",
    ],
    correct: 0,
    explanation:
      "On recurring audits ISA 210 does not demand a fresh letter every year, but it DOES require the auditor to consider whether circumstances make revision necessary — and a change in ownership, senior management or the reporting framework are the textbook triggers, so a revised letter should be issued here. 'Once and never again' misses that assessment entirely; 'identical letter' defeats the purpose of revising terms that no longer fit; and the letter is agreed BEFORE work begins — it sets the terms, it does not record history.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA3-A-06",
    paper: "AA",
    area: "A",
    type: "mcq",
    stem: "Larkfell & Co is updating its quality management policies. Which statement correctly distinguishes ISQM 1 from ISA 220 (Revised)?",
    options: [
      "ISQM 1 applies only to firms that audit listed entities; other firms follow ISA 220 alone",
      "ISA 220 requires the firm to design a system of quality management, while ISQM 1 deals with the individual audit engagement",
      "ISQM 1 requires the FIRM to design and operate a risk-based system of quality management; ISA 220 applies quality management at the level of the individual engagement, with the engagement partner taking overall responsibility for quality on each audit",
      "ISQM 1 requires an engagement quality review to be performed on every audit engagement",
    ],
    correct: 2,
    explanation:
      "The split is firm versus engagement: ISQM 1 makes the FIRM establish a risk-based system of quality management (governance and leadership, ethics, acceptance and continuance, engagement performance, resources, information and communication, monitoring and remediation), while ISA 220 (Revised) makes the ENGAGEMENT PARTNER responsible for quality on each individual audit. Option 2 states this exactly backwards — the classic slip. ISQM 1 applies to ALL firms performing audits, not just listed-entity auditors, and engagement quality reviews (governed by ISQM 2) are required for listed entities and certain other engagements, not for every audit.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AA3-A-07",
    paper: "AA",
    area: "A",
    type: "mcq",
    stem: "During the audit of Vessmore Trading Ltd, Ockley & Frayne identifies transactions giving rise to a suspicion of money laundering. Which statement about the firm's duty of confidentiality is correct?",
    options: [
      "Client information may never be disclosed without Vessmore's written consent",
      "The suspicion must be reported to the relevant authority without obtaining the client's consent — an OBLIGATORY disclosure — and the firm must not tip off the client",
      "The firm should first raise the suspicion with Vessmore's finance director and disclose only if he agrees",
      "The firm should describe the suspicion in the auditor's report so that shareholders are informed",
    ],
    correct: 1,
    explanation:
      "Confidentiality is a fundamental principle but it is NOT absolute: where the law requires disclosure — money laundering reporting is the prime example — the auditor MUST report to the relevant authority, needs no client consent, and commits a criminal offence of TIPPING OFF by alerting the client. Option 1 treats confidentiality as absolute; option 3 is textbook tipping off dressed up as courtesy; and the auditor's report is a reporting vehicle for the OPINION, never the channel for money laundering suspicions.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AA3-A-08",
    paper: "AA",
    area: "A",
    type: "mcq",
    stem: "The audit manager on the Duneshall Retail plc engagement has just married Duneshall's finance director. What threats arise and what should Crenwick & Halden do?",
    options: [
      "No action is needed provided the couple agree not to discuss the audit at home",
      "An advocacy threat arises; the audit fee should be increased to compensate",
      "A self-review threat arises; the manager should review her own working papers more carefully",
      "Familiarity and self-interest threats arise from the close personal relationship; the manager must be removed from the engagement",
    ],
    correct: 3,
    explanation:
      "An immediate family member in a key financial position at the client creates FAMILIARITY (too trusting of the spouse's work) and SELF-INTEREST (the household benefits from the client's success) threats so significant that the individual must come OFF the team — a private promise not to talk shop is unenforceable and no safeguard at all. Advocacy is about promoting the client's position (and raising the fee makes independence worse, not better), and self-review requires the firm to audit its own prior work, which is not what a marriage creates.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AA3-A-09",
    paper: "AA",
    area: "A",
    type: "mcq",
    stem: "A shareholder of Ilverton plc complains that the auditors 'should have checked every single transaction and certified that the accounts are completely accurate'. This belief is best described as:",
    options: [
      "Part of the EXPECTATION GAP — the difference between what the public believes auditors do and the reasonable assurance an audit actually provides",
      "Correct — an audit provides absolute assurance that the financial statements contain no misstatement",
      "Correct — auditors are required by the ISAs to test 100% of transactions",
      "A deficiency in Ilverton's system of internal control",
    ],
    correct: 0,
    explanation:
      "The expectation gap is the mismatch between public perception (auditors check everything and 'certify' accuracy) and reality (REASONABLE assurance that the statements are free from MATERIAL misstatement, based on testing samples). Absolute assurance is impossible because of inherent limitations — judgement, sampling, and the nature of evidence; nothing in the ISAs requires 100% testing; and a shareholder's misunderstanding is a perception problem, not a control deficiency inside the company.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA3-A-10",
    paper: "AA",
    area: "A",
    type: "mcq",
    stem: "Jessam & Cole provides several services to Kentmore Leisure plc, a listed audit client. Which of the following would involve assuming a MANAGEMENT RESPONSIBILITY and is therefore prohibited?",
    options: [
      "Delivering a technical training course on new IFRS requirements to Kentmore's finance staff",
      "Performing a review of Kentmore's interim financial statements",
      "Approving and releasing the weekly supplier payment run while Kentmore's finance director is on annual leave",
      "Presenting the audit findings to Kentmore's audit committee each year",
    ],
    correct: 2,
    explanation:
      "Authorising transactions — deciding that payments should be made and releasing them — is a MANAGEMENT RESPONSIBILITY, and the Code prohibits the firm from ever assuming management responsibilities for an audit client because no safeguard can reduce the resulting threats. Generic training is permissible (it transfers knowledge, it does not make decisions), an interim review is an audit-related assurance service, and presenting findings to the audit committee is part of the audit itself — students often over-extend the prohibition to these benign services while missing the genuinely fatal one.",
    marks: 2,
    difficulty: "hard",
  },

  /* ───────────── Area B — Planning & risk assessment (16) ───────────── */
  {
    id: "AA3-B-01",
    paper: "AA",
    area: "B",
    type: "mcq",
    stem: "Ravensmoor Hotels plc has an internal audit department whose work the external auditor wishes to use. Which factors does ISA 610 require the external auditor to evaluate before using that work?",
    options: [
      "The size of the internal audit department and the cost savings available to the external auditor",
      "The extent to which the function's organisational status supports its objectivity, its level of competence, and whether it applies a systematic and disciplined approach, including quality control",
      "Whether the department reports directly to the finance director, which would confirm its independence",
      "Whether the internal audit staff hold the same professional qualifications as the external audit team",
    ],
    correct: 1,
    explanation:
      "ISA 610's three-part test is OBJECTIVITY (who does the function report to, are there conflicting responsibilities), COMPETENCE (training, expertise, resources) and a SYSTEMATIC AND DISCIPLINED APPROACH (methodologies and quality control). Department size and fee savings are commercial considerations, not evaluation criteria; reporting to the finance director UNDERMINES objectivity rather than confirming it (internal audit should report to the audit committee); and identical qualifications to the external team is not the standard — appropriate competence is.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA3-B-02",
    paper: "AA",
    area: "B",
    type: "mcq",
    stem: "The external auditor of Tarnwell Logistics plc plans to use internal auditors to provide DIRECT ASSISTANCE, working under the external auditor's direction, supervision and review. Which task must NOT be assigned to them?",
    options: [
      "Performing test counts while attending the year-end inventory count",
      "Vouching a sample of repairs and maintenance invoices to supporting documentation",
      "Casting and cross-casting the trade payables listing",
      "Evaluating the reasonableness of the directors' judgemental warranty provision, which has been assessed as a significant risk",
    ],
    correct: 3,
    explanation:
      "Where direct assistance is permitted at all, ISA 610 forbids assigning work that involves SIGNIFICANT JUDGEMENTS or relates to HIGHER assessed risks of material misstatement — evaluating a judgemental provision flagged as a significant risk fails on both counts and must stay with the external team. Test counts, vouching and casting are low-judgement, mechanical procedures that CAN be assigned under supervision; treating all delegation as banned (or none) misses the standard's calibrated middle ground.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AA3-B-03",
    paper: "AA",
    area: "B",
    type: "mcq",
    stem: "Wexcombe Retail Ltd outsources its entire payroll to Paycrest Services, a service organisation. The auditor intends to RELY on controls operating at Paycrest. Under ISA 402, which report from Paycrest's service auditor provides the evidence needed?",
    options: [
      "A TYPE 2 report, because it covers the description, design AND operating effectiveness of Paycrest's controls over a period",
      "A TYPE 1 report, because it is issued as at a specific date close to the year end",
      "Either report, because both provide evidence of operating effectiveness",
      "Neither — the auditor must always visit and test the service organisation in person",
    ],
    correct: 0,
    explanation:
      "The distinction is what each report proves: a TYPE 1 report covers the DESCRIPTION and DESIGN of controls at a point in time only, so it can support risk assessment but says nothing about whether controls actually OPERATED; a TYPE 2 report adds tests of OPERATING EFFECTIVENESS over a period — exactly what reliance requires. 'Either report' ignores that only type 2 tests operation, and a personal visit is one possible response, not a universal requirement — the whole point of ISA 402 reports is to avoid every user auditor descending on the bureau.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AA3-B-04",
    paper: "AA",
    area: "B",
    type: "mcq",
    stem: "Which of the following conditions at Mossbray Engineering Ltd is MOST likely to cast significant doubt on the company's ability to continue as a going concern?",
    options: [
      "Gross margin improved from 30% to 33% during the year",
      "The company replaced its ERP system shortly after the year end",
      "The company is in arrears on its bank loan repayments and key suppliers have moved it onto cash-on-delivery terms",
      "Staff turnover in the marketing department increased during the year",
    ],
    correct: 2,
    explanation:
      "Loan arrears and suppliers withdrawing credit are classic ISA 570 FINANCIAL indicators: the company cannot meet debts as they fall due and its liquidity is being squeezed further by cash-on-delivery terms. An improving margin points the OTHER way; a system upgrade is an operational event, not a solvency signal (a common over-reach); and marketing staff turnover, unlike the loss of key management, has no direct bearing on the entity's survival.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AA3-B-05",
    paper: "AA",
    area: "B",
    type: "mcq",
    stem: "The audit team of Yarrowfield Stores plc uses audit data analytics on the full year's sales ledger at the planning stage. Which statement correctly describes the benefit?",
    options: [
      "Analysing every transaction eliminates sampling risk, so no further audit procedures will be needed",
      "Analytics can profile 100% of a population to highlight unusual items, patterns and outliers, sharpening risk identification — but flagged items still require investigation and the auditor's judgement",
      "Using data analytics removes the need to obtain an understanding of internal control",
      "Responsibility for the conclusions drawn passes to the software provider",
    ],
    correct: 1,
    explanation:
      "The genuine benefit of data analytics at planning is COVERAGE: whole-population profiling directs attention to anomalies a sample might miss. But it identifies WHERE to look — the flagged items must still be investigated and evaluated, so 'no further procedures' is exactly wrong (and interrogating a full population is not the same as auditing it). ISA 315's requirement to understand internal control stands regardless of tooling, and responsibility for audit conclusions can never be outsourced to a software vendor.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA3-B-06",
    paper: "AA",
    area: "B",
    type: "mcq",
    stem: "Two months before its year end, Nettlecombe Insurance plc suffered a ransomware attack that encrypted parts of its policy administration system and exposed customer data. Which audit risk should the auditor identify at the planning stage?",
    options: [
      "Detection risk has increased, because client IT incidents raise the auditor's own risk",
      "No audit risk arises, because the breach occurred before the year end and has been contained",
      "Control risk has fallen, because the attack proves the IT team actively monitors its systems",
      "Provisions or contingent liability disclosures for regulatory fines and customer claims may be incomplete, and the integrity of data processed around the attack may be compromised",
    ],
    correct: 3,
    explanation:
      "A data breach creates possible obligations — regulatory penalties, customer compensation — so the risk is UNDERSTATED provisions or missing contingent liability disclosure, plus doubt over the completeness and accuracy of transactions processed while systems were compromised (and reduced reliance on IT controls). Detection risk is set by the AUDITOR in response, it does not rise because of client events; 'contained before year end' ignores that the obligating event has already happened; and suffering a successful attack is evidence of control WEAKNESS, not strength.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA3-B-07",
    paper: "AA",
    area: "B",
    type: "mcq",
    stem: "The audit of Birchmoor Ltd (31 December year end) includes an interim visit in October and a final visit in February. Which procedure is BEST suited to the INTERIM visit?",
    options: [
      "Documenting the sales system and testing controls over transactions recorded in the first nine months",
      "Circularising customers to confirm year-end receivables balances",
      "Reviewing subsequent events up to the date of the auditor's report",
      "Obtaining the year-end bank confirmation letter",
    ],
    correct: 0,
    explanation:
      "Interim work covers what does NOT depend on the year-end position: understanding and documenting systems, testing controls over the period to date, and early substantive work on transactions. A receivables circularisation confirms balances AT the year end, the bank letter confirms the year-end balance, and subsequent events review runs right up to the report date in February — all three are final-visit procedures by definition. Matching procedures to the wrong visit is a routine planning-question error.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AA3-B-08",
    paper: "AA",
    area: "B",
    type: "mcq",
    stem: "At the October interim audit of Eldwick Manufacturing Ltd, controls over purchases were tested and found to be operating effectively. For the auditor to rely on those controls for the full year to 31 December, ISA 330 requires the auditor to:",
    options: [
      "Do nothing further — controls tested once during the year are proven for the whole year",
      "Re-perform all of the interim tests in full at the final audit",
      "Obtain additional evidence covering the remaining November–December period, for example by testing controls over that period and establishing whether the system has changed since the interim visit",
      "Abandon controls reliance and test the last two months substantively — tests of controls cannot span a year end",
    ],
    correct: 2,
    explanation:
      "Interim controls evidence has a shelf life: ISA 330 requires the auditor to bridge the REMAINING PERIOD by determining what has changed and obtaining additional evidence (further tests of controls over November–December, or other procedures) before relying for the full year. 'Tested once, proven all year' ignores that controls can deteriorate or change; repeating EVERYTHING wastes the interim work the standard is designed to preserve; and there is no rule forcing a switch to substantive testing — that is an invented prohibition.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA3-B-09",
    paper: "AA",
    area: "B",
    type: "mcq",
    stem: "Umberleigh Media Ltd reports a small loss of $0.1m this year after three years of highly volatile profits; revenue has been stable at around $40m. In setting overall materiality, the auditor should:",
    options: [
      "Calculate materiality as 5% of the $0.1m loss",
      "Set materiality at zero because the company is loss-making",
      "Postpone setting materiality until the final audit visit, when results are certain",
      "Choose a more stable benchmark — such as a percentage of revenue or total assets, or a normalised average profit — because this year's result is not representative",
    ],
    correct: 3,
    explanation:
      "ISA 320 requires an APPROPRIATE benchmark, and profit before tax fails when it is volatile or near zero: 5% of a $0.1m loss gives materiality of $5,000 against a $40m business — absurdly low and mechanically applied. The right response is a stable benchmark (0.5–1% of revenue, 1–2% of total assets) or a normalised profit figure. Materiality of zero is conceptually meaningless (everything would be material), and materiality must be set at PLANNING to scope the work — deferring it defeats its purpose.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AA3-B-10",
    paper: "AA",
    area: "B",
    type: "mcq",
    stem: "Pindarow Ltd's accounts department consists of a single bookkeeper who has unrestricted system access, is never required to take annual leave, and whose work is not reviewed by anyone. In terms of the ISA 240 fraud triangle, this situation represents:",
    options: [
      "Incentive or pressure to commit fraud",
      "Opportunity to commit fraud",
      "Rationalisation of fraud",
      "Evidence that a fraud has actually occurred",
    ],
    correct: 1,
    explanation:
      "The fraud triangle's three conditions are incentive/pressure (a reason to commit fraud), OPPORTUNITY (circumstances that allow it — weak oversight, unrestricted access, no enforced leave), and rationalisation (an attitude that justifies it). Unsupervised, unlimited access is pure OPPORTUNITY. Nothing in the scenario shows a motive (incentive) or a justifying attitude (rationalisation), and a weakness that WOULD allow fraud is not evidence that fraud HAS happened — jumping from risk factor to conclusion abandons professional skepticism in the other direction.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AA3-B-11",
    paper: "AA",
    area: "B",
    type: "mcq",
    stem: "Regardless of the assessed level of risk, which procedures must the auditor of Calverdon plc perform in EVERY audit to respond to the risk of management override of controls?",
    options: [
      "Test the appropriateness of journal entries, review accounting estimates for bias, and evaluate the business rationale of significant transactions outside the normal course of business",
      "Circularise every customer whose balance exceeds materiality",
      "Attend every inventory count held by the company during the year",
      "Engage a forensic specialist to review the year's transactions",
    ],
    correct: 0,
    explanation:
      "ISA 240 treats management override as a significant risk in ALL audits and mandates three responses in every engagement: journal entry testing (especially unusual or period-end journals), reviewing estimates for management bias, and evaluating significant unusual transactions. Circularisations and count attendance are ordinary substantive procedures triggered by the balances involved, not by the override risk, and a forensic specialist is engaged only where fraud findings warrant it — none of the three is an automatic, universal requirement.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA3-B-12",
    paper: "AA",
    area: "B",
    type: "mcq",
    stem: "Which of the following would the auditor of Hobwick Pharmaceuticals Ltd consider when obtaining an UNDERSTANDING of the entity and its environment under ISA 315?",
    options: [
      "The wording of the opinion paragraph to be used in the auditor's report",
      "The content of the written representations to be requested from the directors",
      "The regulatory approval regime for new drugs and the intensity of competition in the pharmaceutical industry",
      "The sample sizes to be used in year-end substantive testing",
    ],
    correct: 2,
    explanation:
      "ISA 315's understanding covers industry, regulatory and other EXTERNAL factors, the nature of the entity, its accounting policies, objectives, strategies and performance measures — for a pharmaceutical company, the drug approval regime and competitive pressure are exactly the point, because they shape where misstatements are likely. The opinion wording and written representations belong to the COMPLETION and REPORTING stages, and sample sizes are the RESPONSE to assessed risk, decided after the understanding is obtained — putting outputs before inputs reverses the audit process.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AA3-B-13",
    paper: "AA",
    area: "B",
    type: "mcq",
    stem: "Which of the following transactions at Strathmell Ltd should the auditor treat as giving rise to a SIGNIFICANT RISK requiring special audit consideration?",
    options: [
      "Routine monthly payroll processed through a long-established, unchanged system",
      "Straight-line depreciation charged on the same basis as in prior years",
      "Purchases of raw materials at market prices from long-standing, unrelated suppliers",
      "The sale of a warehouse to a company owned by the chief executive's brother, at a price well above market value",
    ],
    correct: 3,
    explanation:
      "A RELATED PARTY transaction outside the normal course of business — an asset sale to the CEO's brother's company at an off-market price — bears every hallmark of a significant risk: non-routine, judgemental, and susceptible to management involvement and misstatement of both the transaction and its disclosure. Routine payroll, unchanged depreciation and arm's-length purchases are exactly the ROUTINE, non-complex transactions ISA 315 says are LESS likely to give rise to significant risks — students who label everything 'significant' lose the discrimination the question tests.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA3-B-14",
    paper: "AA",
    area: "B",
    type: "mcq",
    stem: "Planning analytics at Ashdale Components Ltd show receivables collection days rising from 45 to 82, while revenue and customer credit terms were unchanged. Which risk should the auditor plan to address?",
    options: [
      "Completeness of revenue — sales may not have been recorded",
      "Valuation of receivables — customers are paying much more slowly, so the loss allowance may be understated",
      "Existence of inventory — goods may have been stolen from the warehouse",
      "Rights and obligations — the receivables may have been factored to a finance company",
    ],
    correct: 1,
    explanation:
      "Collection days nearly doubling on unchanged terms means customers are paying far more slowly — ageing debts whose RECOVERABILITY is in doubt, so the risk is VALUATION of receivables (an inadequate allowance for expected losses). Unrecorded sales would push receivables days DOWN, not up (wrong direction); inventory existence is a different balance the ratio says nothing about; and factoring REMOVES receivables from the ledger, which would also shorten apparent collection days — each distractor fails the arithmetic of the ratio.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA3-B-15",
    paper: "AA",
    area: "B",
    type: "mcq",
    stem: "Which of the following is a benefit of audit planning under ISA 300 for the audit of Withersea Ltd?",
    options: [
      "It helps the auditor devote appropriate attention to important areas, identify and resolve potential problems on a timely basis, and organise the engagement so it is performed effectively and efficiently",
      "It guarantees that all frauds affecting the financial statements will be detected",
      "It removes the need to direct and supervise junior members of the engagement team",
      "It fixes the audit approach so that it cannot be changed once fieldwork begins",
    ],
    correct: 0,
    explanation:
      "ISA 300 lists planning's benefits: focus on important areas, timely identification of problems, a properly organised engagement, selection of a suitably skilled team, and a basis for direction, supervision and review. No audit — planned or not — GUARANTEES detecting all fraud (reasonable assurance only); planning is the FOUNDATION for supervision, not a substitute for it; and planning is continual and iterative — the strategy and plan are UPDATED as findings emerge, never locked.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AA3-B-16",
    paper: "AA",
    area: "B",
    type: "mcq",
    stem: "Gantrell Ltd is a new audit client; the predecessor auditor, Moxon & Pryce, gave professional clearance and issued an unmodified opinion last year. Under ISA 510, how should the incoming auditor obtain assurance over the OPENING balances?",
    options: [
      "Rely on the prior year's unmodified audit opinion — no further work is required",
      "Require Gantrell to restate all comparative figures before accepting the engagement",
      "Review Moxon & Pryce's working papers where possible, check that closing balances were correctly brought forward under consistent policies, and perform current-year procedures — such as testing subsequent collection of opening receivables — that also evidence the opening position",
      "Automatically qualify the audit opinion because the opening balances were audited by another firm",
    ],
    correct: 2,
    explanation:
      "ISA 510 requires the incoming auditor to obtain evidence that opening balances do not contain misstatements affecting the current period: reviewing the predecessor's working papers, confirming correct brought-forward figures and consistent accounting policies, and using current-year work (after-date cash for opening receivables, this year's count worked back for opening inventory). A predecessor's opinion alone is NOT sufficient evidence; demanding restatement assumes an error nobody has found; and a change of auditor never triggers automatic qualification — the opinion is modified only if sufficient evidence proves unobtainable.",
    marks: 2,
    difficulty: "hard",
  },

  /* ───────────── Area C — Internal control (12) ───────────── */
  {
    id: "AA3-C-01",
    paper: "AA",
    area: "C",
    type: "mcq",
    stem: "Which of the following is NOT one of the components of internal control identified in ISA 315?",
    options: [
      "The control environment",
      "The entity's risk assessment process",
      "The entity's process to monitor the system of internal control",
      "The external audit function",
    ],
    correct: 3,
    explanation:
      "ISA 315's five components are: the control environment, the entity's risk assessment process, the information system and communication, control activities, and the entity's process to monitor the system of internal control. EXTERNAL audit sits entirely OUTSIDE the entity's system — it examines internal control but is not part of it. The trap is conflating internal audit (which can form part of the MONITORING component) with external audit, which never belongs to the client's system.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA3-C-02",
    paper: "AA",
    area: "C",
    type: "mcq",
    stem: "The board of Ostenbury plc publishes a code of conduct, runs annual ethics training for all staff, and consistently disciplines breaches, setting a strong 'tone at the top'. Which component of internal control does this describe?",
    options: [
      "Control activities",
      "The control environment",
      "Monitoring of controls",
      "The information system",
    ],
    correct: 1,
    explanation:
      "Governance attitudes, integrity, ethical values and 'tone at the top' are the CONTROL ENVIRONMENT — the foundation on which all other components rest. Control activities are specific procedures over transactions (authorisations, reconciliations); monitoring is the ongoing evaluation of whether controls keep working; and the information system is how transactions are captured and reported. Students often mislabel anything the board does as 'monitoring' — the board's culture-setting role is environment, not evaluation.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AA3-C-03",
    paper: "AA",
    area: "C",
    type: "mcq",
    stem: "At Ambrell Ltd the auditor traces a single sales transaction from the customer order through dispatch and invoicing to its posting in the ledger. What is the purpose of this WALKTHROUGH?",
    options: [
      "To confirm the auditor's understanding of how the system operates and that the documented controls have actually been implemented",
      "To provide sufficient evidence that the controls operated effectively throughout the period",
      "To act as a substitute for substantive procedures over revenue",
      "To detect any fraud that occurred in the sales cycle during the year",
    ],
    correct: 0,
    explanation:
      "A walkthrough follows ONE transaction end-to-end to verify the auditor's understanding of the system and that controls exist and have been IMPLEMENTED — it supports risk assessment. One transaction can never prove controls operated effectively ALL YEAR (that requires tests of controls over a representative sample of the period) — the single most common confusion; it tests process, not balances, so it substitutes for nothing substantive; and one traced sale has essentially no power to detect fraud across a cycle.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA3-C-04",
    paper: "AA",
    area: "C",
    type: "mcq",
    stem: "The auditor of Verlow Ltd has identified a SIGNIFICANT deficiency in internal control. Under ISA 265, the auditor must:",
    options: [
      "Describe the deficiency in the auditor's report so that shareholders are informed",
      "Qualify the audit opinion until the deficiency is remedied",
      "Communicate the deficiency in WRITING to those charged with governance on a timely basis",
      "Report the deficiency only if management specifically requests a written report",
    ],
    correct: 2,
    explanation:
      "ISA 265 requires SIGNIFICANT deficiencies to be communicated IN WRITING to those charged with governance on a timely basis (and to management at an appropriate level). Control deficiencies are reported privately to governance, not published in the auditor's report; a deficiency does not, of itself, misstate the financial statements, so the OPINION is unaffected — qualifying is a category error; and the duty is the auditor's own, not conditional on anyone requesting it.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA3-C-05",
    paper: "AA",
    area: "C",
    type: "mcq",
    stem: "Which of the following deficiencies at Ninebanks Ltd is MOST likely to be assessed as a SIGNIFICANT deficiency in internal control?",
    options: [
      "The $150 petty cash float is reconciled quarterly rather than monthly",
      "Two purchase invoices in the auditor's sample were filed out of date order",
      "The stationery cupboard is left unlocked outside office hours",
      "The financial controller can post journal entries without any review or approval, and also prepares the financial statements",
    ],
    correct: 3,
    explanation:
      "Significance under ISA 265 turns on the LIKELIHOOD and potential MAGNITUDE of misstatement and the susceptibility to fraud: unreviewed journal access in the hands of the person who also prepares the financial statements is a direct management-override route capable of misstating ANY balance — clearly significant. A $150 float, filing order and stationery security all fail the magnitude test by orders of magnitude; picking them treats every weakness as equal, which is precisely the judgement the standard (and the exam) requires you to make.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AA3-C-06",
    paper: "AA",
    area: "C",
    type: "mcq",
    stem: "Oxcroft Trading Ltd wants to ensure that only valid, properly authorised payments leave its bank account. Which control BEST achieves this objective?",
    options: [
      "A monthly bank reconciliation performed by the cashier",
      "Online payments set up by one employee and released by a second, more senior employee after reviewing the supporting documentation",
      "Filing all payment confirmations in date order",
      "Sequentially numbering petty cash vouchers",
    ],
    correct: 1,
    explanation:
      "Dual authorisation — set-up by one person, independent review and release by another — PREVENTS invalid payments before the money leaves, which is exactly the stated objective. A bank reconciliation is a DETECTIVE control (it finds problems after the fact) and is weakened further here by being done by the cashier who handles the cash; orderly filing is record-keeping, not a control over validity; and numbering petty cash vouchers supports completeness of a trivial fund, not authorisation of bank payments. Match the control to the objective and to prevention versus detection.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AA3-C-07",
    paper: "AA",
    area: "C",
    type: "mcq",
    stem: "Whitlow Ltd is a small company with a simple purchases system. Which of the following is an ADVANTAGE of documenting the system using narrative notes?",
    options: [
      "They are quick to prepare and easy for the whole audit team to follow when the system is simple",
      "They automatically highlight missing controls in the system",
      "They are the clearest method for large, complex systems with many document flows",
      "They provide evidence that the controls operated effectively during the year",
    ],
    correct: 0,
    explanation:
      "Narrative notes suit SIMPLE systems: fast to write, no special skill needed, easy for anyone to read. Highlighting missing or weak controls is the strength of QUESTIONNAIRES (ICQs/ICEQs), not free-text notes; for large, complex systems narratives become long and unwieldy — FLOWCHARTS show multi-stream document flows far more clearly; and no documentation method, however good, is evidence of operating effectiveness — only testing provides that. Each wrong option credits narrative notes with another technique's advantage.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA3-C-08",
    paper: "AA",
    area: "C",
    type: "mcq",
    stem: "In assessing the controls of Radbourne plc, the audit team debates whether to use an internal control questionnaire (ICQ) or an internal control evaluation questionnaire (ICEQ). Which statement correctly distinguishes the two?",
    options: [
      "An ICEQ lists desirable controls and asks whether each one is present",
      "An ICQ asks whether specific errors or frauds could occur and go undetected",
      "An ICQ asks whether desirable controls EXIST, whereas an ICEQ asks whether the system as a whole would PREVENT or DETECT specific errors or frauds",
      "The two documents are identical apart from their titles",
    ],
    correct: 2,
    explanation:
      "An ICQ works control-by-control — 'is there a credit check on new customers?' — so it confirms EXISTENCE of controls but can miss the bigger picture. An ICEQ works risk-by-risk — 'could goods be dispatched but not invoiced?' — evaluating whether the system overall prevents or detects each key error, which is why its questions are called control or key questions. Options 1 and 2 state the definitions exactly backwards (the standard exam trap), and the two documents differ in design and purpose, not just name.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AA3-C-09",
    paper: "AA",
    area: "C",
    type: "mcq",
    stem: "Which of the following is an inherent LIMITATION of Ederline Ltd's system of internal control, however well the system is designed?",
    options: [
      "Controls guarantee that the financial statements are free from material misstatement",
      "Automated controls are incapable of processing transactions incorrectly",
      "Segregation of duties eliminates the risk of fraud entirely",
      "Controls can be circumvented by collusion between employees or overridden by management",
    ],
    correct: 3,
    explanation:
      "Internal control provides only REASONABLE assurance because of inherent limitations: COLLUSION defeats segregation of duties, MANAGEMENT can override controls, humans make errors, controls are designed for routine (not one-off) transactions, and cost constrains design. The other three options are the opposite of limitations — overconfident claims: no system guarantees clean financial statements, automated controls fail if programmed wrongly or fed bad standing data, and segregation only reduces (never eliminates) fraud risk, precisely because of collusion.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AA3-C-10",
    paper: "AA",
    area: "C",
    type: "mcq",
    stem: "Fallowdene plc's internal audit department performs rolling reviews of controls at each branch, reports on whether they continue to operate as intended, and follows up agreed actions. Which component of internal control does this activity represent?",
    options: [
      "Control activities",
      "Monitoring of the system of internal control",
      "The entity's risk assessment process",
      "The control environment",
    ],
    correct: 1,
    explanation:
      "Ongoing and periodic evaluation of whether controls are present and functioning — internal audit's branch reviews being the classic example — is the MONITORING component. Control activities are the day-to-day procedures being reviewed, not the review of them; the risk assessment process is how the ENTITY identifies business risks, not how it checks its controls; and the control environment is the governance culture that underpins everything. Distinguishing 'operating the controls' from 'checking the controls still work' is the point of the question.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA3-C-11",
    paper: "AA",
    area: "C",
    type: "mcq",
    stem: "Grimsbury Mills Ltd inputs weekly timesheets into its payroll application in batches. Which APPLICATION control best ensures that ALL timesheets are input (completeness of input)?",
    options: [
      "Batch control totals — agreeing the number of timesheets and total hours input to pre-computed totals for each batch",
      "Password restrictions over access to the payroll application",
      "Supervisor authorisation of overtime before timesheets are submitted",
      "Daily back-up of the payroll data files",
    ],
    correct: 0,
    explanation:
      "Batch totals directly test COMPLETENESS of input: if the count of documents or the hash total of hours input does not agree to the pre-computed control total, something is missing or duplicated. Passwords are an ACCESS control (an IT general control — and about who gets in, not whether everything went in); overtime authorisation addresses VALIDITY/occurrence, not completeness, and happens before input; and back-ups are a general control protecting data that has ALREADY been processed. Tie the control to the specific input objective.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA3-C-12",
    paper: "AA",
    area: "C",
    type: "mcq",
    stem: "Harkstead Foods Ltd wants assurance that ALL goods received before the year end are recorded as liabilities in the correct period. Which control BEST achieves this objective?",
    options: [
      "Suppliers are paid only after their monthly statements have been agreed to the ledger",
      "Purchase invoices are matched to authorised purchase orders before being posted",
      "Purchase orders above $5,000 require authorisation by a departmental head",
      "Goods received notes are sequentially numbered and regularly reviewed for items not yet matched to an invoice, with unmatched GRNs accrued at the period end",
    ],
    correct: 3,
    explanation:
      "The objective is COMPLETENESS of liabilities: the danger is goods received for which no invoice has yet been recorded. Sequentially numbered GRNs plus a regular unmatched-GRN review — with an accrual for anything still unmatched at the year end — catches exactly that gap. Agreeing supplier statements before payment helps detect ledger errors but only for suppliers who send statements, and it is payment-focused and late; invoice-to-order matching tests that recorded purchases are VALID (the opposite direction); and order authorisation controls spending, not recording. Completeness controls must start from the goods, not the invoice.",
    marks: 2,
    difficulty: "hard",
  },
]
