import type { AccaQuestion } from "@/lib/acca-content"

/*
 * FR question bank — wave 2 (45 verified original questions, 2026-07-10).
 * Blueprint: A7 B14 C8 D7 E9; 25/45/30 difficulty; every distractor is a
 * nameable student error. Merged into QUESTIONS in acca-content.ts.
 */

export const FR_WAVE2: AccaQuestion[] = [
  /* ───────────── Area A — conceptual & regulatory framework (7) ───────────── */
  {
    id: "FR2-A-01",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "According to the Conceptual Framework, which TWO qualitative characteristics are FUNDAMENTAL to useful financial information?",
    options: [
      "Relevance and faithful representation",
      "Comparability and verifiability",
      "Timeliness and understandability",
      "Prudence and consistency",
    ],
    correct: 0,
    explanation:
      "The Conceptual Framework names relevance and faithful representation as the two fundamental characteristics. Comparability, verifiability, timeliness and understandability are only ENHANCING characteristics — a classic mix-up — and prudence/consistency are not listed as characteristics at all.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR2-A-02",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "Under the Conceptual Framework, a faithful representation is one that is:",
    options: [
      "Relevant, comparable and timely",
      "Prudent, verifiable and understandable",
      "Complete, neutral and free from error",
      "Complete, prudent and material",
    ],
    correct: 2,
    explanation:
      "Faithful representation has three components: completeness, neutrality and freedom from error. The distractors mix in relevance-related and enhancing characteristics; prudence supports neutrality but is not itself one of the three components.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR2-A-03",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "Which of the following is the Conceptual Framework's definition of a liability?",
    options: [
      "An expected outflow of economic benefits that is probable and can be measured reliably",
      "A present obligation of the entity to transfer an economic resource as a result of past events",
      "A commitment to transfer resources in the future once a contract has been signed",
      "A legally enforceable debt owed to a third party",
    ],
    correct: 1,
    explanation:
      "The current Framework defines a liability as a present obligation to transfer an economic resource as a result of past events. 'Probable outflow + reliable measurement' is the superseded definition, a future commitment lacks a PAST event, and obligations can be constructive as well as legal.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR2-A-04",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "Under the Conceptual Framework, an asset or liability is recognised in the financial statements when:",
    options: [
      "An inflow or outflow of benefits is probable and its cost can be measured reliably",
      "Recognition provides users with relevant information and a faithful representation, at a cost that does not outweigh the benefit",
      "It is virtually certain that economic benefits will flow to or from the entity",
      "Management intends to hold the item for more than one accounting period",
    ],
    correct: 1,
    explanation:
      "The current Framework's recognition criteria are that recognition must give RELEVANT information and a FAITHFUL REPRESENTATION (subject to the cost constraint). 'Probable + reliably measurable' is the OLD framework's test that many students still quote; 'virtually certain' is a contingent-asset threshold, not a recognition criterion.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR2-A-05",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "Kelvane Co 'sells' inventory with a carrying amount of $400,000 to a bank for $400,000 cash, and is obliged to repurchase it in two years for $484,000. Kelvane retains physical custody of the goods. How should the arrangement be reported?",
    options: [
      "Recognise revenue of $400,000 and derecognise the inventory",
      "Keep the inventory on the statement of financial position and recognise a $400,000 loan, with the $84,000 recognised as finance cost over two years",
      "Derecognise the inventory and recognise a $84,000 gain immediately",
      "Treat the goods as held on consignment for the bank",
    ],
    correct: 1,
    explanation:
      "In substance this is a secured loan, not a sale: Kelvane keeps the risks and rewards and must repurchase at cost plus an effective 10% p.a. interest. Recognising revenue (or a gain) follows the legal form rather than the economic substance — the classic sale-and-repurchase trap.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR2-A-06",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "Which measurement basis is defined as 'the price that would be received to sell an asset in an orderly transaction between market participants at the measurement date'?",
    options: ["Value in use", "Current cost", "Fair value", "Historical cost"],
    correct: 2,
    explanation:
      "This is the definition of fair value — an exit price based on market participants. Value in use is entity-specific discounted cash flows, current cost is an entry (replacement) value, and historical cost is the original transaction amount.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR2-A-07",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "Which of the following is accounted for as a change in accounting ESTIMATE (applied prospectively) rather than a change in accounting policy?",
    options: [
      "Changing inventory valuation from FIFO to weighted average cost",
      "Changing the depreciation method of plant from straight-line to reducing balance",
      "Adopting the revaluation model for property previously held under the cost model",
      "Correcting the omission of a material accrual from last year's statements",
    ],
    correct: 1,
    explanation:
      "A change in depreciation method reflects a new pattern of consumption of benefits, so IAS 8/IAS 16 treat it as a change in ESTIMATE applied prospectively. FIFO-to-AVCO and cost-to-revaluation are changes in POLICY, and an omitted accrual is a prior-period ERROR corrected retrospectively.",
    marks: 2,
    difficulty: "hard",
  },

  /* ───────────── Area B — accounting for transactions, IFRS (14) ───────────── */
  {
    id: "FR2-B-01",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Ashden Co's head office cost $800,000 and has accumulated depreciation of $200,000. It is revalued for the first time to $750,000. What is recognised in other comprehensive income?",
    options: [
      "A loss of $50,000",
      "A gain of $750,000",
      "A gain of $550,000",
      "A gain of $150,000",
    ],
    correct: 3,
    explanation:
      "The surplus is measured against CARRYING AMOUNT: $750,000 − ($800,000 − $200,000) = $150,000, taken to OCI/revaluation surplus. Comparing with original cost gives the bogus $50,000 loss; $750,000 treats the whole valuation as the gain; $550,000 wrongly deducts accumulated depreciation from the new valuation.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR2-B-02",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Plant cost $900,000 with a 10-year life and nil residual value. After exactly 4 years, the remaining useful life is revised to 5 years with a residual value of $40,000. What is the depreciation charge for year 5?",
    options: ["$90,000", "$108,000", "$100,000", "$86,000"],
    correct: 2,
    explanation:
      "Changes in estimate are applied prospectively to carrying amount: ($900,000 − 4 × $90,000 − $40,000) ÷ 5 = ($540,000 − $40,000) ÷ 5 = $100,000. $90,000 keeps the original charge, $108,000 forgets the residual value, and $86,000 wrongly recomputes from original cost.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR2-B-03",
    paper: "FR",
    area: "B",
    type: "number",
    stem: "On 1 April 20X5 Torvale Co borrowed $3,000,000 at 8% specifically to build a new warehouse; construction started the same day and continued to the 31 December year end. Surplus funds were temporarily invested, earning $20,000 during construction. Under IAS 23, what amount of borrowing costs is capitalised in the year, in $?",
    numericAnswer: 160000,
    unit: "$",
    tolerance: 0,
    explanation:
      "IAS 23 capitalises interest incurred during construction LESS investment income on the temporary investment of specific borrowings: $3,000,000 × 8% × 9/12 = $180,000 − $20,000 = $160,000. Forgetting to deduct the $20,000 income is the classic trap.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR2-B-04",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Merion Co spent the following on a new product this year: research $100,000; development before the IAS 38 capitalisation criteria were met $60,000; development after the criteria were met $200,000; staff training to operate the new process $40,000. How much is capitalised as an intangible asset?",
    options: ["$260,000", "$200,000", "$360,000", "$240,000"],
    correct: 1,
    explanation:
      "Only development expenditure incurred AFTER the IAS 38 criteria are all met is capitalised: $200,000. $260,000 wrongly includes pre-criteria development, $360,000 capitalises all R&D, and $240,000 adds training costs, which IAS 38 always expenses.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR2-B-05",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Quorra Co sells a machine bundled with two years of technical support for $100,000. Sold separately, the machine's standalone selling price is $90,000 and the support is $30,000. Under IFRS 15, how much revenue is recognised when the machine is delivered?",
    options: ["$90,000", "$100,000", "$75,000", "$70,000"],
    correct: 2,
    explanation:
      "IFRS 15 allocates the transaction price to each performance obligation by RELATIVE standalone selling price: $100,000 × 90/120 = $75,000. $90,000 fails to allocate any of the discount to the machine, $100,000 recognises the whole price upfront, and $70,000 pushes the entire discount onto the machine (a residual approach).",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR2-B-06",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Brayford Co runs an online marketplace, selling goods owned by third-party suppliers who set the prices and bear inventory risk. Brayford keeps a 15% commission. Gross sales through the site were $400,000 this year. What revenue should Brayford recognise?",
    options: ["$400,000", "$340,000", "$460,000", "$60,000"],
    correct: 3,
    explanation:
      "Brayford is an AGENT under IFRS 15 (it never controls the goods), so revenue is only its commission: 15% × $400,000 = $60,000. $400,000 reports gross as if principal, $340,000 reports the amount remitted to suppliers, and $460,000 double-counts gross sales plus commission.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR2-B-07",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Selwick Co leases a machine for 4 years at $60,000 per annum payable in arrears. The interest rate implicit in the lease is 7% and the 4-year annuity factor at 7% is 3.39. Selwick also paid initial direct costs of $6,600. At what amount is the right-of-use asset initially recognised?",
    options: ["$210,000", "$203,400", "$240,000", "$246,600"],
    correct: 0,
    explanation:
      "IFRS 16 measures the right-of-use asset at the initial lease liability PLUS initial direct costs: ($60,000 × 3.39) + $6,600 = $203,400 + $6,600 = $210,000. $203,400 omits the direct costs, while $240,000 and $246,600 use undiscounted payments.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR2-B-08",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "A lease liability stands at $200,000 at the start of the year. The rate implicit in the lease is 10% and the annual payment of $60,000 is made in arrears on the last day of the year. What is the lease liability at the year end?",
    options: ["$140,000", "$220,000", "$160,000", "$154,000"],
    correct: 2,
    explanation:
      "With payments in arrears, interest accrues on the full opening balance first: $200,000 + (10% × $200,000) − $60,000 = $160,000. $140,000 forgets the interest, $220,000 forgets the payment, and $154,000 wrongly deducts the payment before charging interest (an in-advance pattern).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR2-B-09",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Norlox Co sells goods with a one-year warranty. If ALL products sold this year had minor defects, repairs would cost $100,000; if all had major defects, repairs would cost $400,000. Experience shows 80% of goods will have no defects, 15% minor and 5% major. What warranty provision is required under IAS 37?",
    options: ["$400,000", "$35,000", "$0", "$500,000"],
    correct: 1,
    explanation:
      "For a large population, IAS 37 measures the provision at EXPECTED VALUE: (15% × $100,000) + (5% × $400,000) = $35,000. $0 wrongly uses the single most likely outcome, $400,000 provides for the worst case, and $500,000 simply adds both repair totals.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR2-B-10",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Halveston Co's year end is 31 December 20X5 and its financial statements are authorised for issue on 31 March 20X6. Under IAS 10, which of the following is an ADJUSTING event?",
    options: [
      "A court case in progress at 31 December was settled in February, confirming Halveston's obligation at the year end",
      "The market value of Halveston's equity investments fell sharply in January",
      "A warehouse was destroyed by fire in February",
      "The directors declared a final dividend in March",
    ],
    correct: 0,
    explanation:
      "An adjusting event provides evidence of conditions that EXISTED at the reporting date — the settlement confirms the year-end obligation. The market fall, the fire and the post-year-end dividend all arose after the year end, so they are non-adjusting (disclosed if material).",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR2-B-11",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Denford Co issues $500,000 6% loan notes for net proceeds of $470,000 after issue costs. The effective interest rate is 8%. What finance cost is recognised in profit or loss for the first year?",
    options: ["$30,000", "$40,000", "$28,200", "$37,600"],
    correct: 3,
    explanation:
      "Under IFRS 9 amortised cost, the finance cost is the effective rate applied to the opening carrying amount: 8% × $470,000 = $37,600. $30,000 charges only the cash coupon, $40,000 applies the effective rate to the nominal value, and $28,200 applies the coupon rate to net proceeds.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR2-B-12",
    paper: "FR",
    area: "B",
    type: "number",
    stem: "At the year end, Ostley Co's plant has a carrying amount of $450,000 and a tax base of $350,000. The income tax rate is 25%. Under IAS 12, what deferred tax LIABILITY arises, in $?",
    numericAnswer: 25000,
    unit: "$",
    tolerance: 0,
    explanation:
      "Carrying amount above tax base creates a TAXABLE temporary difference: ($450,000 − $350,000) × 25% = $25,000 deferred tax liability. Reporting the $100,000 difference itself, or applying 25% to the carrying amount, are the common slips.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR2-B-13",
    paper: "FR",
    area: "B",
    type: "number",
    stem: "On the first day of the year, Grenbar Co received a government grant of $90,000 towards plant that cost $300,000 and has a 6-year useful life with nil residual value. Grenbar uses the deferred income method. What grant income is recognised in profit or loss for the year, in $?",
    numericAnswer: 15000,
    unit: "$",
    tolerance: 0,
    explanation:
      "IAS 20 releases the grant to profit or loss over the periods that benefit — here the asset's 6-year life: $90,000 ÷ 6 = $15,000 per year. Crediting the whole grant on receipt, or taking it straight to equity, is not permitted.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR2-B-14",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Pellworth Co had 1,000,000 ordinary shares in issue on 1 January and made a 1-for-4 bonus issue on 1 July. Profit attributable to ordinary shareholders for the year was $600,000. What is basic EPS under IAS 33?",
    options: ["60.0 cents", "53.3 cents", "80.0 cents", "48.0 cents"],
    correct: 3,
    explanation:
      "A bonus issue adds no resources, so IAS 33 treats the 250,000 bonus shares as in issue for the WHOLE year: $600,000 ÷ 1,250,000 = 48.0c. 60.0c ignores the bonus, 53.3c wrongly time-apportions it from 1 July, and 80.0c deducts the bonus shares instead of adding them.",
    marks: 2,
    difficulty: "hard",
  },

  /* ───────────── Area C — analysing & interpreting (8) ───────────── */
  {
    id: "FR2-C-01",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Extracts from Varden Co: profit before interest and tax $240,000; profit after tax $150,000; equity $800,000; non-current borrowings $400,000. What is return on capital employed (ROCE)?",
    options: ["30.0%", "20.0%", "12.5%", "18.75%"],
    correct: 1,
    explanation:
      "ROCE = PBIT ÷ (equity + non-current borrowings) = $240,000 ÷ $1,200,000 = 20%. 30.0% divides by equity only, 12.5% uses post-tax profit over capital employed, and 18.75% is return on equity (PAT ÷ equity).",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR2-C-02",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Marbeck Co has loan notes of $600,000 and total equity of $900,000. What is its gearing, measured as debt ÷ (debt + equity)?",
    options: ["66.7%", "150.0%", "40.0%", "60.0%"],
    correct: 2,
    explanation:
      "Gearing = $600,000 ÷ ($600,000 + $900,000) = 40%. 66.7% is the debt/equity version (the wrong formula for the measure asked), 150% inverts it to equity/debt, and 60% is the equity ratio, equity ÷ (debt + equity).",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR2-C-03",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Tresago Co's current assets of $600,000 comprise inventory $200,000, receivables $250,000 and cash $150,000. Current liabilities are $250,000. What is the quick (acid-test) ratio?",
    options: ["1.6", "2.4", "0.8", "1.0"],
    correct: 0,
    explanation:
      "The quick ratio excludes inventory: ($600,000 − $200,000) ÷ $250,000 = 1.6. 2.4 is the current ratio (inventory not excluded), 0.8 divides only inventory by current liabilities, and 1.0 wrongly excludes cash as well as inventory.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR2-C-04",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "A toy retailer deliberately has a 31 January year end, just after its stock is cleared in the January sales. When comparing it with a retailer that has an October year end, which distortion is most likely?",
    options: [
      "Its inventory holding period will look unusually long",
      "There is no distortion because ratios are unaffected by the choice of year end",
      "Its gross profit margin will be understated by the low year-end inventory",
      "Its inventory holding period (based on closing inventory) will look unusually short",
    ],
    correct: 3,
    explanation:
      "Ratios built on a CLOSING balance are distorted when the year end sits at a seasonal low — inventory days will look artificially short. Believing year-end choice is neutral ignores this, and gross margin uses full-period totals, not year-end balances.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR2-C-05",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Part-way through the year, Lynmore Co revalues its properties significantly UPWARDS for the first time. All else being equal, the most likely effect on this year's ratios is:",
    options: [
      "ROCE increases and gearing decreases",
      "ROCE decreases and gearing (debt ÷ debt + equity) decreases",
      "ROCE decreases and gearing increases",
      "Both ROCE and gearing increase",
    ],
    correct: 1,
    explanation:
      "The revaluation surplus increases equity, so capital employed rises (and depreciation rises), cutting ROCE; the larger equity also cuts gearing. Students who assume 'higher assets = better ratios' pick an increase in ROCE, and those who forget the surplus sits in equity get gearing moving the wrong way.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR2-C-06",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Redwick Co has ROCE of 20% and an operating profit margin of 8%. Using the standard ratio relationship, what is its net asset turnover?",
    options: ["0.4 times", "1.6 times", "2.5 times", "12.0 times"],
    correct: 2,
    explanation:
      "ROCE = operating margin × asset turnover, so turnover = 20% ÷ 8% = 2.5 times. 0.4 divides the wrong way round, 1.6 multiplies the two percentages, and 12.0 simply subtracts one from the other.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR2-C-07",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Year on year, Corvale Co's gross profit margin ROSE from 30% to 33% but its operating profit margin FELL from 12% to 9%. Which is the most likely explanation?",
    options: [
      "Operating expenses (distribution and administrative costs) grew faster than revenue",
      "Cost of sales increased as a percentage of revenue",
      "Selling prices were cut to win market share",
      "Finance costs on new borrowings increased sharply",
    ],
    correct: 0,
    explanation:
      "A higher gross margin with a lower operating margin points to costs BETWEEN gross and operating profit — operating expenses outpacing revenue. Higher cost of sales or price-cutting would have reduced the gross margin, and finance costs sit BELOW operating profit so cannot explain the fall.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR2-C-08",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Extracts from Jorlan Co: profit before tax $420,000; finance costs $60,000; income tax expense $84,000. What is Jorlan's interest cover?",
    options: ["7.0 times", "5.6 times", "0.125 times", "8.0 times"],
    correct: 3,
    explanation:
      "Interest cover = profit BEFORE interest and tax ÷ finance costs = ($420,000 + $60,000) ÷ $60,000 = 8. 7.0 forgets to add the finance costs back to PBT, 5.6 uses post-tax profit ($336,000), and 0.125 inverts the ratio.",
    marks: 2,
    difficulty: "medium",
  },

  /* ───────────── Area D — preparation of single-entity statements (7) ───────────── */
  {
    id: "FR2-D-01",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Fenwood Co's draft figures ($'000): opening inventory 50; purchases 400; closing inventory 70. Depreciation of production plant of $30,000 is to be charged to cost of sales. What is cost of sales, in $'000?",
    options: ["410", "380", "450", "350"],
    correct: 0,
    explanation:
      "Cost of sales = 50 + 400 − 70 + 30 = $410,000. 380 omits the production depreciation, 450 swaps opening and closing inventory, and 350 deducts the depreciation instead of adding it.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR2-D-02",
    paper: "FR",
    area: "D",
    type: "number",
    stem: "Osmere Co's trial balance at 31 December shows rent PAID of $48,000. This includes $12,000 paid on 1 November covering the three months November to January. What rent expense should appear in profit or loss for the year, in $?",
    numericAnswer: 44000,
    unit: "$",
    tolerance: 0,
    explanation:
      "One month of the $12,000 (January = $4,000) is a prepayment at the year end, so the expense = $48,000 − $4,000 = $44,000. Charging the full cash paid, or accruing $4,000 instead of prepaying it, are the usual errors.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR2-D-03",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Calbray Co's receivables ledger shows $250,000 before writing off an irrecoverable balance of $10,000. A loss allowance of 5% of remaining receivables is required; the existing allowance brought forward is $8,000. What total charge appears in profit or loss?",
    options: ["$22,000", "$14,000", "$4,000", "$22,500"],
    correct: 1,
    explanation:
      "Write-off $10,000 + increase in allowance (5% × $240,000 = $12,000, less $8,000 b/f = $4,000) = $14,000. $22,000 charges the full new allowance ignoring the balance brought forward, $4,000 forgets the write-off, and $22,500 computes 5% before deducting the write-off.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR2-D-04",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Werrindale Co estimates its current year income tax at $90,000. Last year's liability was settled for $6,000 MORE than provided, and the deferred tax liability must increase by $15,000. What is the income tax expense in profit or loss?",
    options: ["$90,000", "$96,000", "$99,000", "$111,000"],
    correct: 3,
    explanation:
      "Tax expense = current estimate $90,000 + prior-year UNDER-provision $6,000 + increase in deferred tax $15,000 = $111,000. $90,000 ignores both adjustments, $96,000 omits the deferred tax movement, and $99,000 treats the under-provision as an over-provision and deducts it.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR2-D-05",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "During the year, Hollim Co recognised a $60,000 gain on revaluing its head office (no previous revaluation losses). In the statement of profit or loss and other comprehensive income, this gain is presented:",
    options: [
      "In other comprehensive income",
      "Within profit or loss as other income",
      "It is not presented in this statement at all — only in the statement of changes in equity",
      "As a deduction from depreciation expense",
    ],
    correct: 0,
    explanation:
      "First-time revaluation gains bypass profit or loss and are reported in OTHER COMPREHENSIVE INCOME (accumulating in the revaluation surplus). Putting the gain in P/L overstates profit; the SOCIE shows the surplus movement too, but the gain must still appear in OCI.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR2-D-06",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Stanmoor Co ($'000): profit before tax 300; finance costs 10; depreciation 80; profit on disposal of plant 20; increase in inventories 30; decrease in receivables 25; increase in payables 15. What is cash generated from operations, in $'000?",
    options: ["370", "350", "380", "420"],
    correct: 2,
    explanation:
      "Starting from PBT: 300 + 10 (finance cost) + 80 (depreciation) − 20 (profit on disposal) − 30 (inventory up) + 25 (receivables down) + 15 (payables up) = $380,000. 370 forgets the finance-cost add-back, 350 treats the payables increase as an outflow, and 420 adds the disposal profit instead of deducting it.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR2-D-07",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Braleigh Co ($'000): retained earnings brought forward 500; profit for the year 120; dividends paid 40; gain on property revaluation 60. What are retained earnings carried forward, in $'000?",
    options: ["640", "620", "520", "580"],
    correct: 3,
    explanation:
      "Retained earnings = 500 + 120 − 40 = $580,000; the revaluation gain accumulates in the SEPARATE revaluation surplus, not retained earnings. 640 wrongly adds the revaluation gain, 620 forgets the dividend, and 520 deducts the revaluation gain.",
    marks: 2,
    difficulty: "medium",
  },

  /* ───────────── Area E — consolidated financial statements (9) ───────────── */
  {
    id: "FR2-E-01",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Pandale Co pays $900,000 for 80% of Serrick Co when the fair value of Serrick's identifiable net assets is $800,000 (carrying amount $700,000). Group policy measures NCI at its proportionate share of net assets; the fair value of the NCI at that date was $210,000. What is goodwill?",
    options: ["$310,000", "$340,000", "$260,000", "$100,000"],
    correct: 2,
    explanation:
      "Proportionate NCI = 20% × $800,000 = $160,000, so goodwill = $900,000 + $160,000 − $800,000 = $260,000. $310,000 uses the fair-value NCI despite the stated policy, $340,000 uses carrying amounts instead of fair values, and $100,000 omits the NCI from the calculation.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR2-E-02",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Pravena Co acquires 75% of Skerrith Co for $1,200,000, measuring NCI at its fair value of $300,000. Skerrith's net assets have a carrying amount of $1,000,000, but its land is worth $100,000 more than book value. What is goodwill?",
    options: ["$500,000", "$400,000", "$375,000", "$100,000"],
    correct: 1,
    explanation:
      "Net assets are consolidated at FAIR value ($1,100,000): goodwill = $1,200,000 + $300,000 − $1,100,000 = $400,000. $500,000 ignores the land uplift, $375,000 wrongly uses proportionate NCI (25% × $1,100,000) when fair-value NCI was required, and $100,000 forgets the NCI entirely.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR2-E-03",
    paper: "FR",
    area: "E",
    type: "number",
    stem: "During the year, Parbold Co sold goods to its subsidiary for $120,000 at a mark-up of 25% ON COST. Half of these goods remain in the subsidiary's inventory at the year end. What unrealised profit is eliminated on consolidation, in $?",
    numericAnswer: 12000,
    unit: "$",
    tolerance: 0,
    explanation:
      "With a 25% mark-up on cost, profit in the sale = $120,000 × 25/125 = $24,000; only the half still in inventory is unrealised: $12,000. Using 25% of the selling price ($30,000 basis) or adjusting for all the goods sold are the standard traps.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR2-E-04",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "A 70%-owned subsidiary sold goods to its parent at a profit, and some of those goods remain in the parent's inventory at the year end. On consolidation, the unrealised profit adjustment:",
    options: [
      "Reduces the subsidiary's profit, so the NCI share of profit is also reduced",
      "Reduces the parent's profit, leaving the NCI unaffected",
      "Is not required because the sale was made at arm's-length prices",
      "Is added to goodwill on acquisition",
    ],
    correct: 0,
    explanation:
      "The PURP is always deducted from the SELLER's profit — here the subsidiary — so the NCI takes its 30% share of the reduction. Adjusting the parent instead misidentifies the seller, and intra-group profit must be eliminated regardless of the price charged.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR2-E-05",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Pellam Co acquired Sindon Co on 1 October 20X5. For the year to 31 December 20X5 (accruing evenly), revenue was: Pellam $1,000,000; Sindon $600,000. After acquisition, Sindon sold goods to Pellam for $30,000. What is consolidated revenue for 20X5?",
    options: ["$1,570,000", "$1,150,000", "$1,600,000", "$1,120,000"],
    correct: 3,
    explanation:
      "Only POST-acquisition results are consolidated: $1,000,000 + ($600,000 × 3/12) − $30,000 intra-group = $1,120,000. $1,570,000 consolidates Sindon's full year, $1,150,000 forgets the intra-group elimination, and $1,600,000 makes both errors.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR2-E-06",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Sarnwell Co, an 80%-owned subsidiary, reports profit for the year of $240,000. Consolidation adjustments: extra depreciation of $30,000 on a fair-value uplift to Sarnwell's plant, and unrealised profit of $10,000 on goods Sarnwell sold to its parent. What profit is attributable to the NCI?",
    options: ["$48,000", "$42,000", "$40,000", "$46,000"],
    correct: 2,
    explanation:
      "NCI share is based on the subsidiary's ADJUSTED profit: ($240,000 − $30,000 − $10,000) × 20% = $40,000. $48,000 uses the unadjusted profit, $42,000 deducts only the fair-value depreciation, and $46,000 deducts only the PURP.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR2-E-07",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Ivorden Co bought 30% of Amberly Co (an associate) for $300,000. Since acquisition, Amberly has made total profits of $200,000 and Ivorden has received dividends of $10,000 from Amberly. Under the equity method, at what amount is the investment carried?",
    options: ["$350,000", "$360,000", "$300,000", "$500,000"],
    correct: 0,
    explanation:
      "Equity method: cost + share of post-acquisition profits − dividends RECEIVED = $300,000 + (30% × $200,000) − $10,000 = $350,000. $360,000 forgets to deduct the dividend, $300,000 leaves the associate at cost, and $500,000 adds 100% of the associate's profit.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR2-E-08",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Under IFRS 10, an investor controls an investee when it has:",
    options: [
      "Power over the investee, exposure to variable returns, and the ability to use its power to affect those returns",
      "Ownership of more than half of the investee's shares, in all circumstances",
      "The contractual right to appoint at least one director to the board",
      "The power to participate in the investee's financial and operating policy decisions",
    ],
    correct: 0,
    explanation:
      "IFRS 10 defines control by three elements: power, variable returns and the link between them. A majority shareholding is only a common INDICATOR (control can exist without it), one board seat does not give power, and 'power to participate' is the definition of significant influence over an associate.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR2-E-09",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Prescot Co owns 75% of Selhurst Co. Retained earnings: Prescot $800,000; Selhurst $300,000 now and $180,000 at acquisition. During the year Prescot sold goods to Selhurst, and $10,000 of unrealised profit remains in Selhurst's closing inventory. What are consolidated retained earnings?",
    options: ["$890,000", "$910,000", "$1,015,000", "$880,000"],
    correct: 3,
    explanation:
      "Group retained earnings = parent's $800,000 + 75% × post-acquisition ($300,000 − $180,000 = $120,000) − PURP $10,000 (parent is the seller) = $880,000. $890,000 forgets the PURP, $910,000 takes 100% of post-acquisition profits, and $1,015,000 uses Selhurst's TOTAL retained earnings instead of post-acquisition only.",
    marks: 2,
    difficulty: "hard",
  },
]
