import type { Flashcard } from "@/lib/acca-flashcards"

/* Flashcard wave 3 — AA/FM/MA to revision depth (2026-07-10). */
export const FLASHCARDS_WAVE3: Flashcard[] = [
  /* ── AA — Audit & Assurance (50) ────────────────────────────── */

  /* AA A — Audit framework & regulation (8) */
  { id: "AA-FC3-01", paper: "AA", area: "A", front: "The five elements every assurance engagement needs", back: "A three-party relationship (practitioner, responsible party, intended users); an appropriate subject matter; suitable criteria to judge it against; sufficient appropriate evidence; a written assurance report." },
  { id: "AA-FC3-02", paper: "AA", area: "A", front: "How the conclusion is worded: reasonable vs limited assurance", back: "Reasonable assurance uses POSITIVE wording ('in our opinion, the statements give a true and fair view'). Limited assurance uses NEGATIVE wording ('nothing has come to our attention that causes us to believe...')." },
  { id: "AA-FC3-03", paper: "AA", area: "A", front: "Which body issues ISAs?", back: "The IAASB — the International Auditing and Assurance Standards Board, operating under IFAC. National regulators may adopt or adapt them." },
  { id: "AA-FC3-04", paper: "AA", area: "A", front: "The statutory rights of an external auditor", back: "Access to the company's books and records at all times; to require information and explanations from officers; to receive notice of, attend and speak at general meetings on matters that concern them as auditor." },
  { id: "AA-FC3-05", paper: "AA", area: "A", front: "The five threats to auditor objectivity — one example each", back: "Self-interest (fee dependence, shares in the client); self-review (auditing figures the firm prepared); advocacy (defending the client in a dispute); familiarity (long association, family ties); intimidation (threats of dismissal or litigation)." },
  { id: "AA-FC3-06", paper: "AA", area: "A", front: "The fee-dependence rule for a public interest entity", back: "If total fees from one PIE client exceed 15% of the firm's total fee income for two consecutive years, disclose to those charged with governance and arrange an independent review of the engagement." },
  { id: "AA-FC3-07", paper: "AA", area: "A", front: "Main functions of an audit committee", back: "Monitor the integrity of the financial statements; review internal controls and internal audit; recommend the external auditor's appointment and fees; monitor auditor independence (including non-audit services); oversee whistleblowing arrangements." },
  { id: "AA-FC3-08", paper: "AA", area: "A", front: "The expectation gap — three common public misconceptions", back: "That auditors prepare the financial statements; that they certify the accounts as 100% accurate; that an audit is designed to find ALL fraud. In fact the auditor gives reasonable assurance on statements prepared by management." },

  /* AA B — Planning & risk assessment (10) */
  { id: "AA-FC3-09", paper: "AA", area: "B", front: "Common benchmark ranges for overall materiality", back: "½–1% of revenue; 5–10% of profit before tax; 1–2% of total assets. A starting point only — the figure is always a matter of professional judgement, adjusted for qualitative factors." },
  { id: "AA-FC3-10", paper: "AA", area: "B", front: "Performance materiality — what and why?", back: "An amount set BELOW overall materiality, used when testing, to reduce the risk that uncorrected and undetected misstatements in aggregate exceed materiality for the statements as a whole." },
  { id: "AA-FC3-11", paper: "AA", area: "B", front: "The two stages where analytical procedures are COMPULSORY", back: "As risk assessment procedures at planning, and in the overall review at completion. Using them as substantive procedures mid-audit is optional." },
  { id: "AA-FC3-12", paper: "AA", area: "B", front: "Audit strategy vs audit plan", back: "The strategy sets the overall scope, timing and direction (deadlines, team, materiality, key risk areas). The plan converts it into detailed instructions: the nature, timing and extent of specific procedures." },
  { id: "AA-FC3-13", paper: "AA", area: "B", front: "Interim audit vs final audit — typical work at each", back: "Interim (during the year): document systems, tests of controls, substantive work on transactions to date. Final (after year end): year-end balances, completion of substantive procedures, subsequent events, going concern, the report." },
  { id: "AA-FC3-14", paper: "AA", area: "B", front: "ISA 240 — the two types of fraud, and who bears primary responsibility", back: "Fraudulent financial reporting and misappropriation of assets. Primary responsibility for prevention and detection sits with MANAGEMENT and those charged with governance; the auditor gives reasonable assurance the statements are free from material fraud-based misstatement." },
  { id: "AA-FC3-15", paper: "AA", area: "B", front: "Professional scepticism", back: "A questioning mind, alert to conditions indicating possible misstatement, and a critical assessment of evidence — neither assuming management is dishonest nor assuming unquestioned honesty." },
  { id: "AA-FC3-16", paper: "AA", area: "B", front: "The three risk assessment procedures for understanding the entity", back: "Enquiries of management and others; analytical procedures; observation and inspection. Prior-period knowledge and client acceptance information also feed in." },
  { id: "AA-FC3-17", paper: "AA", area: "B", front: "Inherent and control risk are assessed as HIGH — what must happen to detection risk?", back: "It must be driven LOW to keep audit risk acceptable: more substantive work, larger samples, more experienced staff, more work at the year end rather than the interim, less reliance on controls." },
  { id: "AA-FC3-18", paper: "AA", area: "B", front: "The quality test for audit documentation", back: "An experienced auditor with no previous connection to the audit should be able to understand the procedures performed, the results and evidence obtained, and the significant judgements and conclusions reached." },

  /* AA C — Internal control (10) */
  { id: "AA-FC3-19", paper: "AA", area: "C", front: "The five components of internal control (ISA 315)", back: "Control environment; the entity's risk assessment process; the information system and communication; control activities; monitoring of controls." },
  { id: "AA-FC3-20", paper: "AA", area: "C", front: "The five main types of control activity", back: "Authorisation and approvals; reconciliations; verifications; physical/logical controls over assets and access; segregation of duties." },
  { id: "AA-FC3-21", paper: "AA", area: "C", front: "Inherent limitations of ANY internal control system", back: "Human error; collusion between employees; management override; controls designed only for routine transactions; cost of a control exceeding its benefit. This is why controls reduce, but never eliminate, risk." },
  { id: "AA-FC3-22", paper: "AA", area: "C", front: "Segregation of duties — the three functions to keep apart", back: "Authorisation of a transaction, custody of the related asset, and recording in the accounting records. One person holding two or more makes fraud easier to commit and conceal." },
  { id: "AA-FC3-23", paper: "AA", area: "C", front: "What does a walkthrough test prove — and what doesn't it prove?", back: "Tracing one transaction end-to-end confirms the auditor's understanding of the system and that controls are designed and implemented. It is NOT a test of operating effectiveness — that needs tests of controls over a period." },
  { id: "AA-FC3-24", paper: "AA", area: "C", front: "How are significant control deficiencies reported?", back: "In writing to those charged with governance (the report to management / management letter), typically stating each deficiency, its implication, and a recommendation. The letter is a by-product of the audit, not an objective of it." },
  { id: "AA-FC3-25", paper: "AA", area: "C", front: "General IT controls vs application controls", back: "General: the environment all systems run in — access security, program change controls, backups, disaster recovery. Application: controls inside a specific process — input edit checks, batch totals, sequence checks, exception reports." },
  { id: "AA-FC3-26", paper: "AA", area: "C", front: "Test data vs audit software (CAATs)", back: "Test data: the AUDITOR'S dummy transactions are run through the CLIENT'S system to check its controls (e.g. does it reject an invalid code?). Audit software: the auditor's own programs interrogate the client's REAL data files (recalculate, stratify, extract exceptions)." },
  { id: "AA-FC3-27", paper: "AA", area: "C", front: "Sequence-checking of goods despatch notes and matching them to invoices addresses which risk?", back: "Completeness of revenue — goods leaving without ever being invoiced. A gap in the GDN sequence, or a GDN with no matching invoice, is the exception to chase." },
  { id: "AA-FC3-28", paper: "AA", area: "C", front: "Payroll controls against 'ghost employees'", back: "Segregate HR (maintains the personnel master file) from payroll processing; require authorised documentation for all starters and leavers; review exception reports of employees with matching bank details; periodic headcount checks." },

  /* AA D — Audit evidence (12) */
  { id: "AA-FC3-29", paper: "AA", area: "D", front: "The six assertions for CLASSES OF TRANSACTIONS", back: "Occurrence; completeness; accuracy; cut-off; classification; presentation. (Memory hook: did it happen, is it all there, right amount, right period, right account, properly disclosed.)" },
  { id: "AA-FC3-30", paper: "AA", area: "D", front: "The assertions for ACCOUNT BALANCES at the period end", back: "Existence; rights and obligations; completeness; accuracy, valuation and allocation; classification; presentation." },
  { id: "AA-FC3-31", paper: "AA", area: "D", front: "Trap: a receivables circularisation primarily tests which assertion?", back: "EXISTENCE (and rights and obligations) — the customer confirms the debt is genuine. It gives weak evidence on VALUATION: a customer can agree a balance it will never manage to pay." },
  { id: "AA-FC3-32", paper: "AA", area: "D", front: "Evidence reliability — the rankings", back: "Auditor-generated beats third-party evidence, which beats client-generated; client evidence is stronger when the related controls are strong; written beats oral; original documents beat copies or scans." },
  { id: "AA-FC3-33", paper: "AA", area: "D", front: "The seven procedure types for gathering evidence (ISA 500)", back: "Inspection (of records or assets); observation; external confirmation; recalculation; reperformance; analytical procedures; enquiry. Enquiry alone is rarely sufficient." },
  { id: "AA-FC3-34", paper: "AA", area: "D", front: "Positive vs negative confirmation — and when negative is acceptable", back: "Positive: reply requested in every case. Negative: reply only if the balance is disputed — acceptable only when risk is low, controls are effective, items are small and numerous, and there is no reason customers would ignore the request." },
  { id: "AA-FC3-35", paper: "AA", area: "D", front: "Why must the auditor attend the inventory count?", back: "To evaluate management's count instructions, observe that they are followed, perform test counts, and note damaged or slow-moving items (feeding valuation). Attendance evidences existence and completeness of inventory." },
  { id: "AA-FC3-36", paper: "AA", area: "D", front: "Trap: tracing items FROM the inventory records TO the warehouse floor tests…", back: "EXISTENCE — does what is recorded actually exist? The opposite direction (floor to records) tests COMPLETENESS. The starting point determines the assertion." },
  { id: "AA-FC3-37", paper: "AA", area: "D", front: "Written representations — how reliable, and when dated?", back: "The LEAST reliable form of evidence: they complement other evidence but never substitute for it (obtainable-elsewhere evidence must still be obtained). Dated as near as practicable to, but not after, the auditor's report." },
  { id: "AA-FC3-38", paper: "AA", area: "D", front: "The bank confirmation letter — the process rules", back: "Sent by the AUDITOR (with the client's written authority) and returned directly to the auditor by the bank. Covers account balances, loans, security given, and facilities — strong third-party written evidence." },
  { id: "AA-FC3-39", paper: "AA", area: "D", front: "How is revenue cut-off tested?", back: "Take goods despatch notes raised immediately before and after the year end and trace each to the sales invoice and ledger, checking the sale sits in the correct period — pre-year-end despatches in this year, post-year-end despatches in the next." },
  { id: "AA-FC3-40", paper: "AA", area: "D", front: "The main sample-selection methods", back: "Random (every item an equal chance); systematic (every nth item from a random start); monetary unit (probability proportional to value); haphazard (no conscious bias); block (contiguous items — weakest). Statistical sampling requires random selection and probability theory." },

  /* AA E — Review & reporting (10) */
  { id: "AA-FC3-41", paper: "AA", area: "E", front: "What does an UNMODIFIED opinion actually say?", back: "That the financial statements give a true and fair view (or present fairly, in all material respects) and are prepared, in all material respects, in accordance with the applicable financial reporting framework. Not a guarantee of accuracy or future viability." },
  { id: "AA-FC3-42", paper: "AA", area: "E", front: "Opinion matrix — MISSTATEMENT that is material but NOT pervasive", back: "Qualified opinion: 'except for the matter described in the basis for qualified opinion section, the financial statements give a true and fair view.' Example: one incorrectly valued warehouse in an otherwise fair set of accounts." },
  { id: "AA-FC3-43", paper: "AA", area: "E", front: "Opinion matrix — MISSTATEMENT that is material AND pervasive", back: "Adverse opinion: the financial statements do NOT give a true and fair view. Example: consolidation of subsidiaries omitted, or accounts prepared on a going concern basis when the entity is clearly not one." },
  { id: "AA-FC3-44", paper: "AA", area: "E", front: "Opinion matrix — INABILITY TO OBTAIN EVIDENCE, material but not pervasive", back: "Qualified opinion ('except for the possible effects of...'). Example: unable to observe one location's inventory count with no alternative procedures available, while the rest of the audit is clean." },
  { id: "AA-FC3-45", paper: "AA", area: "E", front: "Opinion matrix — INABILITY TO OBTAIN EVIDENCE, material AND pervasive", back: "Disclaimer of opinion: 'we do not express an opinion on the financial statements.' Example: accounting records destroyed, or management blocks access to most of the evidence." },
  { id: "AA-FC3-46", paper: "AA", area: "E", front: "When is a matter 'pervasive' (ISA 705)?", back: "Any of: its effects are not confined to specific elements of the statements; if confined, they represent a substantial proportion of the statements; or it concerns disclosures fundamental to users' understanding." },
  { id: "AA-FC3-47", paper: "AA", area: "E", front: "Emphasis of matter vs other matter paragraph", back: "Emphasis of matter: draws attention to something appropriately DISCLOSED IN the statements (e.g. a major uncertainty) that is fundamental to understanding them. Other matter: something NOT in the statements but relevant to the audit or report. Neither modifies the opinion." },
  { id: "AA-FC3-48", paper: "AA", area: "E", front: "Key audit matters (ISA 701) — who, what, and one thing they are not", back: "Required for LISTED entities: the matters of most significance in the audit, selected from those communicated to governance, with how the audit addressed each. KAMs are NOT a substitute for a modified opinion or a going concern section." },
  { id: "AA-FC3-49", paper: "AA", area: "E", front: "Going concern reporting — the three outcomes", back: "Material uncertainty ADEQUATELY disclosed → unmodified opinion + 'Material Uncertainty Related to Going Concern' section. Disclosure INADEQUATE → qualified or adverse opinion. Going concern basis WRONGLY used → adverse opinion." },
  { id: "AA-FC3-50", paper: "AA", area: "E", front: "Subsequent events — the auditor's active vs passive duty", back: "Between the year end and the report date: an ACTIVE duty to perform procedures (enquiries, minutes, later management accounts). After the report is signed but before issue: no duty to search, but if a matter comes to light, discuss with management and consider amendment." },

  /* ── FM — Financial Management (50) ─────────────────────────── */

  /* FM A — FM function & environment (8) */
  { id: "FM-FC3-01", paper: "FM", area: "A", front: "The three key decisions of financial management", back: "Investment (which projects/assets), financing (debt vs equity, long vs short term) and dividend (distribute or retain). Each is a risk-return trade-off aimed at maximising shareholder wealth." },
  { id: "FM-FC3-02", paper: "FM", area: "A", front: "Why is profit maximisation NOT the corporate objective?", back: "Profit is short-term, manipulable by accounting choices, ignores risk, ignores the timing of cash and ignores capital invested. The objective is maximising SHAREHOLDER WEALTH — driven by cash flows, time and risk." },
  { id: "FM-FC3-03", paper: "FM", area: "A", front: "Total shareholder return (TSR)", back: "(P1 − P0 + dividend per share) ÷ P0 — the capital gain plus dividend for the period, as a percentage of the opening share price." },
  { id: "FM-FC3-04", paper: "FM", area: "A", front: "Two ways to align managers with shareholders — and the catch", back: "Performance-related pay tied to EPS growth or TSR, and share option schemes. Catch: both can encourage short-termism or manipulation of the measure rather than genuine value creation." },
  { id: "FM-FC3-05", paper: "FM", area: "A", front: "Money markets vs capital markets", back: "Money markets: short-term (under a year) instruments — treasury bills, commercial paper, certificates of deposit. Capital markets: long-term finance — shares and bonds, raised on stock exchanges." },
  { id: "FM-FC3-06", paper: "FM", area: "A", front: "Three services financial intermediaries provide", back: "Aggregation (pooling many small deposits into large loans), maturity transformation (borrowing short, lending long) and risk pooling/diversification across many borrowers." },
  { id: "FM-FC3-07", paper: "FM", area: "A", front: "The treasury function — its four core areas", back: "Cash and liquidity management, short- and long-term funding, working capital management, and risk management (currency and interest rate). Centralising it brings netting, bulk borrowing rates and specialist expertise." },
  { id: "FM-FC3-08", paper: "FM", area: "A", front: "Fiscal vs monetary policy", back: "Fiscal: government taxation and spending decisions. Monetary: the central bank's control of interest rates and the money supply. Both shift demand, inflation and the cost of business finance." },

  /* FM B — Investment appraisal (12) */
  { id: "FM-FC3-09", paper: "FM", area: "B", front: "Payback period — two strengths, two flaws", back: "Strengths: simple, and favours early cash recovery (useful under liquidity pressure). Flaws: ignores all cash flows after payback, and ignores the time value of money (unless discounted payback is used)." },
  { id: "FM-FC3-10", paper: "FM", area: "B", front: "ARR (accounting rate of return) for a project", back: "Average annual accounting PROFIT ÷ average investment × 100, where average investment = (initial cost + residual value) ÷ 2. The only appraisal method based on profits rather than cash." },
  { id: "FM-FC3-11", paper: "FM", area: "B", front: "IRR by linear interpolation — the formula", back: "IRR ≈ L + [NPVL ÷ (NPVL − NPVH)] × (H − L), where L and H are the lower and higher rates tried and NPVL, NPVH their NPVs. An estimate only — the NPV curve is not a straight line." },
  { id: "FM-FC3-12", paper: "FM", area: "B", front: "NPV and IRR rank mutually exclusive projects differently — which wins?", back: "NPV. It measures the absolute wealth added at the cost of capital, and its reinvestment assumption (at the cost of capital) is more realistic than IRR's (at the IRR itself)." },
  { id: "FM-FC3-13", paper: "FM", area: "B", front: "When can a project have MULTIPLE IRRs?", back: "When cash flows are non-conventional (they change sign more than once — e.g. outflow, inflows, then a big closure cost). Up to one IRR per sign change; fall back on NPV." },
  { id: "FM-FC3-14", paper: "FM", area: "B", front: "Equivalent annual cost (EAC) — formula and use", back: "EAC = PV of costs over one replacement cycle ÷ annuity factor for the cycle length. Compare cycles of different lengths and choose the LOWEST EAC — the optimum replacement interval." },
  { id: "FM-FC3-15", paper: "FM", area: "B", front: "Real vs nominal (money) cash flows — the consistency rule", back: "Discount NOMINAL cash flows (inflated) at the NOMINAL rate; discount REAL cash flows at the REAL rate. Fisher links them: (1 + nominal) = (1 + real) × (1 + inflation)." },
  { id: "FM-FC3-16", paper: "FM", area: "B", front: "Tax-allowable depreciation in NPV — what is the cash flow?", back: "The TAX SAVED: allowance × tax rate. The allowance itself is not a cash flow. Time the saving with the tax payment — one year later if tax is paid in arrears; a balancing allowance or charge arises on disposal." },
  { id: "FM-FC3-17", paper: "FM", area: "B", front: "Working capital in an NPV — the two rules", back: "Only the INCREMENTAL change in working capital each year is a cash flow (not the cumulative total), and the whole investment is recovered as an inflow at the end of the project. It attracts no tax effects." },
  { id: "FM-FC3-18", paper: "FM", area: "B", front: "Sensitivity analysis — the margin formula", back: "Sensitivity = NPV ÷ PV of the cash flow under test × 100%. It shows the % change in that variable that turns NPV to zero — the SMALLEST percentage marks the most critical variable." },
  { id: "FM-FC3-19", paper: "FM", area: "B", front: "Single-period capital rationing with DIVISIBLE projects", back: "Rank by profitability index (PV of inflows ÷ initial outlay, or equivalently NPV per $1 invested) and work down until the budget is spent. Indivisible projects instead need trial combinations for the highest total NPV." },
  { id: "FM-FC3-20", paper: "FM", area: "B", front: "Hard vs soft capital rationing", back: "Hard: the limit is imposed externally — lenders or markets will not supply funds. Soft: the limit is internal management policy (e.g. a fixed capital budget). Soft rationing is by far the more common." },

  /* FM C — Working capital management (10) */
  { id: "FM-FC3-21", paper: "FM", area: "C", front: "The core trade-off in working capital management", back: "Liquidity vs profitability. Hold more current assets and you are safer but earn less; run leaner and returns rise with the risk of running out of cash or stock." },
  { id: "FM-FC3-22", paper: "FM", area: "C", front: "Aggressive vs conservative working capital FUNDING", back: "Split current assets into permanent and fluctuating. Matching: fund permanent with long-term finance, fluctuating with short-term. Aggressive: short-term funds finance some permanent assets (cheap, risky). Conservative: long-term funds finance some fluctuating assets (safe, costly)." },
  { id: "FM-FC3-23", paper: "FM", area: "C", front: "Symptoms of overtrading", back: "Rapid revenue growth on a thin capital base: inventory and receivables days stretching, cash draining, and heavy reliance on payables and overdraft. A profitable business can still fail this way — growth outruns funding." },
  { id: "FM-FC3-24", paper: "FM", area: "C", front: "Annualised cost of offering an early settlement discount", back: "[100 ÷ (100 − d)]^(365/t) − 1, where d = discount % and t = days of payment acceleration. Compare with the overdraft rate: if the annualised cost exceeds it, the discount is expensive finance." },
  { id: "FM-FC3-25", paper: "FM", area: "C", front: "The Baumol cash model", back: "Q = √(2 × F × T ÷ r): F = fixed cost per security sale, T = annual cash requirement, r = interest lost by holding cash. EOQ logic applied to cash — assumes cash is used at a steady, predictable rate." },
  { id: "FM-FC3-26", paper: "FM", area: "C", front: "Miller-Orr — the spread formula", back: "Spread = 3 × [¾ × transaction cost × variance of daily cash flows ÷ daily interest rate]^(1/3). Upper limit = lower limit + spread; the lower limit is set by management." },
  { id: "FM-FC3-27", paper: "FM", area: "C", front: "Miller-Orr — the return point and the mechanics", back: "Return point = lower limit + (spread ÷ 3). Cash hits the UPPER limit → buy securities to fall back to the return point; hits the LOWER limit → sell securities to rise to it. Designed for unpredictable cash flows." },
  { id: "FM-FC3-28", paper: "FM", area: "C", front: "Factoring WITH recourse vs WITHOUT recourse", back: "With recourse: the client keeps the bad-debt risk — the factor hands uncollected debts back. Without recourse: the factor bears the bad-debt risk, so its fee is higher." },
  { id: "FM-FC3-29", paper: "FM", area: "C", front: "Factoring vs invoice discounting", back: "Factoring: the factor advances cash AND runs the sales ledger and collections — customers usually know. Invoice discounting: purely a confidential loan secured on invoices; the company keeps its own credit control." },
  { id: "FM-FC3-30", paper: "FM", area: "C", front: "Where should a short-term cash surplus be parked?", back: "Low-risk, liquid instruments: treasury bills, bank deposits, certificates of deposit, short-dated gilts. Security and liquidity outrank yield for temporary surpluses." },

  /* FM D — Business finance & cost of capital (12) */
  { id: "FM-FC3-31", paper: "FM", area: "D", front: "The WACC formula — spelled out", back: "WACC = [E ÷ (E + D)] × ke + [D ÷ (E + D)] × kd(1 − T), using MARKET values of equity and debt, with kd(1 − T) the after-tax cost of debt." },
  { id: "FM-FC3-32", paper: "FM", area: "D", front: "The CAPM equation", back: "E(ri) = Rf + βi × (E(rm) − Rf): risk-free rate plus beta times the equity risk premium. Beta measures the share's systematic risk relative to the market (market beta = 1)." },
  { id: "FM-FC3-33", paper: "FM", area: "D", front: "Systematic vs unsystematic risk — which does CAPM price?", back: "Systematic (market-wide) risk cannot be diversified away and is what CAPM rewards via beta. Unsystematic (company-specific) risk disappears in a well-diversified portfolio, so the market pays no premium for it." },
  { id: "FM-FC3-34", paper: "FM", area: "D", front: "Ungearing an equity beta — the asset beta formula", back: "βa = βe × E ÷ [E + D(1 − T)] (assuming debt beta is zero). The asset beta strips out financial risk, leaving pure business risk — ready to regear to another capital structure." },
  { id: "FM-FC3-35", paper: "FM", area: "D", front: "Cost of IRREDEEMABLE debt", back: "kd = i(1 − T) ÷ P0: annual interest net of tax relief, divided by the current ex-interest market price. Market price — never nominal value." },
  { id: "FM-FC3-36", paper: "FM", area: "D", front: "Cost of REDEEMABLE debt", back: "The IRR of the bond's cash flows: market price out at time 0, then interest × (1 − T) each year and the redemption amount at maturity. No single-line formula — interpolate." },
  { id: "FM-FC3-37", paper: "FM", area: "D", front: "Cost of preference shares", back: "kp = fixed dividend ÷ ex-div market price. NO tax adjustment — preference dividends, unlike interest, are not tax-deductible." },
  { id: "FM-FC3-38", paper: "FM", area: "D", front: "When is the existing WACC a valid project discount rate?", back: "When the project has the SAME business risk as existing operations, is small relative to the company, and leaves the capital structure (gearing) broadly unchanged. Otherwise build a project-specific rate." },
  { id: "FM-FC3-39", paper: "FM", area: "D", front: "Project-specific discount rate — the three-step routine", back: "1) Take a proxy company's equity beta from the project's industry. 2) Ungear it to the asset beta, then REGEAR to your own capital structure. 3) Put the regeared beta through CAPM for the project cost of equity." },
  { id: "FM-FC3-40", paper: "FM", area: "D", front: "Traditional view vs M&M (with tax) on gearing", back: "Traditional: WACC is U-shaped — an optimal gearing level exists. M&M with corporate tax: the interest tax shield makes WACC FALL continuously as gearing rises — pushed to its logical end, borrow as much as possible (ignoring bankruptcy costs)." },
  { id: "FM-FC3-41", paper: "FM", area: "D", front: "Pecking order theory", back: "Firms prefer retained earnings first, then debt, and new equity only as a last resort — driven by issue costs and the signal a share issue sends (managers issue equity when they think it is overvalued)." },
  { id: "FM-FC3-42", paper: "FM", area: "D", front: "Operating gearing — measure and meaning", back: "Contribution ÷ PBIT (driven by the fixed/variable cost mix). High fixed costs make profit swing sharply with volume — high operating gearing means high business risk, before any borrowing is considered." },

  /* FM E — Valuations & risk management (8) */
  { id: "FM-FC3-43", paper: "FM", area: "E", front: "P/E valuation of an unlisted company", back: "Equity value = maintainable post-tax earnings × P/E ratio, using a LISTED proxy's P/E cut by a discount (often 30-40%) for the shares being unmarketable." },
  { id: "FM-FC3-44", paper: "FM", area: "E", front: "When is an asset-based valuation useful — and its blind spot?", back: "Useful as a floor price, for asset-rich businesses, or in liquidation/break-up. Blind spot: it ignores unrecorded intangibles and future earning power — so it undervalues most going concerns." },
  { id: "FM-FC3-45", paper: "FM", area: "E", front: "Two ways to estimate dividend growth g", back: "Historic extrapolation: g = (latest dividend ÷ dividend n years ago)^(1/n) − 1. Gordon's growth model: g = r × b — the return on reinvested funds times the retention rate." },
  { id: "FM-FC3-46", paper: "FM", area: "E", front: "Market value of irredeemable debt", back: "P0 = annual interest ÷ investors' required PRE-TAX return (i ÷ kd). Value to investors ignores the company's tax relief — that belongs in the company's cost of debt, not the price." },
  { id: "FM-FC3-47", paper: "FM", area: "E", front: "The three forms of market efficiency", back: "Weak: prices reflect all PAST price data — charting fails. Semi-strong: prices reflect all PUBLIC information — fundamental analysis of published data fails; prices react to announcements. Strong: prices reflect ALL information, even private — insider trading could not win (rarely true in practice)." },
  { id: "FM-FC3-48", paper: "FM", area: "E", front: "Transaction vs translation vs economic currency risk", back: "Transaction: real cash gains/losses on settling foreign-currency deals — the one usually hedged. Translation: paper effects of consolidating foreign subsidiaries. Economic: long-term shift in competitive position and PV of future cash flows from exchange-rate movements." },
  { id: "FM-FC3-49", paper: "FM", area: "E", front: "Money market hedge for a FOREIGN CURRENCY RECEIPT — the steps", back: "1) Borrow the foreign currency NOW (the receipt's present value at the foreign borrowing rate). 2) Convert to home currency at today's SPOT rate. 3) Deposit at the home rate. The customer's payment later repays the foreign loan — the rate is locked in today." },
  { id: "FM-FC3-50", paper: "FM", area: "E", front: "Interest rate parity — the forward rate", back: "Forward = spot × (1 + interest rate of the counter/variable currency) ÷ (1 + interest rate of the base currency). The higher-interest currency trades at a forward DISCOUNT — no free lunch from depositing abroad." },

  /* ── MA — Management Accounting (50) ────────────────────────── */

  /* MA A — Cost accounting fundamentals (9) */
  { id: "MA-FC3-01", paper: "MA", area: "A", front: "Direct vs indirect cost — and what prime cost is", back: "Direct costs are traceable to a specific cost unit (materials in the product, labour making it); indirect costs (overheads) are not. Prime cost = total of ALL direct costs." },
  { id: "MA-FC3-02", paper: "MA", area: "A", front: "Production cost vs period cost", back: "Production costs attach to units made and sit in inventory until sold. Period costs (admin, selling, distribution) hit profit in the period incurred, whatever happens to output." },
  { id: "MA-FC3-03", paper: "MA", area: "A", front: "Stepped fixed cost and semi-variable cost — one example each", back: "Stepped fixed: constant within a range then jumps — e.g. a supervisor's salary added for every 20 workers. Semi-variable: fixed element plus a variable element — e.g. a phone bill with line rental plus call charges." },
  { id: "MA-FC3-04", paper: "MA", area: "A", front: "In the cost equation y = a + bx, what are a and b?", back: "a = total FIXED cost (the intercept); b = VARIABLE cost per unit (the slope); x = activity level; y = total cost." },
  { id: "MA-FC3-05", paper: "MA", area: "A", front: "Cost centre vs cost unit — and composite cost units", back: "A cost centre is a location or function costs are gathered in (a department, a machine). A cost unit is the thing costed (one product, one job). Services use composite units: cost per tonne-kilometre, per patient-day, per passenger-mile." },
  { id: "MA-FC3-06", paper: "MA", area: "A", front: "Attributes of good management information", back: "Relevant to the decision, accurate enough, complete, timely, understandable, targeted at the right user, and worth more than it costs to produce." },
  { id: "MA-FC3-07", paper: "MA", area: "A", front: "Data vs information; primary vs secondary data", back: "Data are raw unprocessed facts; information is data processed to be meaningful for a decision. Primary data are collected first-hand for the purpose; secondary data already exist (government statistics, trade journals) — cheaper but less tailored." },
  { id: "MA-FC3-08", paper: "MA", area: "A", front: "The controllability idea in responsibility accounting", back: "Each manager is reported on the costs and revenues THEY can influence. Charging a production supervisor with apportioned head-office rent tells you nothing about the supervisor." },
  { id: "MA-FC3-09", paper: "MA", area: "A", front: "Trap: output doubles — what happens to fixed cost per unit and variable cost per unit?", back: "Fixed cost per unit HALVES (same total spread over more units); variable cost per unit stays CONSTANT. Totals behave the other way round: fixed total constant, variable total doubles." },

  /* MA B — Costing techniques (12) */
  { id: "MA-FC3-10", paper: "MA", area: "B", front: "Trap: prices are rising — FIFO or AVCO gives the higher profit?", back: "FIFO. It charges the older, cheaper receipts to cost of sales, leaving the newer, dearer items in closing inventory — so cost of sales is lower and both profit and inventory value are higher." },
  { id: "MA-FC3-11", paper: "MA", area: "B", front: "The EOQ formula", back: "EOQ = √(2 × Co × D ÷ Ch): Co = cost of placing one order, D = annual demand, Ch = cost of holding one unit for a year." },
  { id: "MA-FC3-12", paper: "MA", area: "B", front: "What is true about costs AT the EOQ?", back: "Total annual ordering cost equals total annual holding cost: (D ÷ Q) × Co = (Q ÷ 2) × Ch. The formula is simply the quantity where those two curves cross." },
  { id: "MA-FC3-13", paper: "MA", area: "B", front: "Reorder level", back: "Maximum usage × maximum lead time (with constant usage and lead time: usage × lead time). Order when inventory falls to this level so it cannot run out before the delivery arrives." },
  { id: "MA-FC3-14", paper: "MA", area: "B", front: "Over- or under-absorbed overhead — the calculation", back: "Absorbed overhead = OAR × ACTUAL activity. Compare with actual overhead incurred: absorbed > actual = over-absorption; absorbed < actual = under-absorption. Two things drive it: spending off budget, activity off budget." },
  { id: "MA-FC3-15", paper: "MA", area: "B", front: "Trap: overhead was OVER-absorbed — add to profit or subtract?", back: "ADD. Over-absorption means units were charged with MORE overhead than was actually spent, so profit was understated — credit the excess back to the income statement." },
  { id: "MA-FC3-16", paper: "MA", area: "B", front: "Two causes of UNDER-absorption", back: "Actual overheads came in above budget, and/or actual activity (hours or units) came in below budget. Either way, too little overhead was charged into production." },
  { id: "MA-FC3-17", paper: "MA", area: "B", front: "Absorption vs marginal profit — the reconciliation", back: "Difference = change in inventory (units) × fixed production OAR per unit. Inventory RISES → absorption profit is higher (fixed overhead carried forward in inventory); inventory FALLS → marginal profit is higher; no change → identical profits." },
  { id: "MA-FC3-18", paper: "MA", area: "B", front: "Process costing: how are normal and abnormal losses valued?", back: "Normal (expected) loss: at SCRAP value only — its cost is absorbed by good output. Abnormal loss: at FULL cost per unit, written off to the income statement. Abnormal gain: same valuation, credited instead." },
  { id: "MA-FC3-19", paper: "MA", area: "B", front: "The equivalent units proforma — four steps", back: "1) Account for the physical units. 2) Convert to equivalent units per cost element (completed units + closing WIP × % complete). 3) Cost per EU = costs ÷ equivalent units, element by element. 4) Value finished output and closing WIP." },
  { id: "MA-FC3-20", paper: "MA", area: "B", front: "FIFO vs weighted average in process costing — the difference", back: "FIFO counts only work done THIS period (opening WIP needs just its completion work) and keeps opening WIP costs separate. Weighted average pools opening WIP costs with the period's costs and averages over all units." },
  { id: "MA-FC3-21", paper: "MA", area: "B", front: "Joint products vs by-products — the accounting split", back: "Joint products (both significant in value): apportion joint costs, by physical units or by sales value at split-off. By-product (incidental): not costed — its net proceeds usually reduce the joint process cost." },

  /* MA C — Budgeting (9) */
  { id: "MA-FC3-22", paper: "MA", area: "C", front: "The principal budget factor", back: "The constraint that limits the entity's activity — usually sales demand, sometimes a scarce resource. Its budget is prepared FIRST and every other functional budget hangs off it." },
  { id: "MA-FC3-23", paper: "MA", area: "C", front: "Production budget (units) — the formula", back: "Budgeted sales units + closing finished goods inventory − opening finished goods inventory." },
  { id: "MA-FC3-24", paper: "MA", area: "C", front: "Materials USAGE budget vs materials PURCHASES budget", back: "Usage = production units × material per unit. Purchases = usage + closing raw material inventory − opening raw material inventory. Two different budgets — the inventory movement is the gap." },
  { id: "MA-FC3-25", paper: "MA", area: "C", front: "Fixed, flexible and flexed budgets", back: "Fixed: one activity level, set in advance. Flexible: designed up front to adjust with activity. Flexed: the original budget RESTATED at the actual activity level after the event — the basis for variance analysis." },
  { id: "MA-FC3-26", paper: "MA", area: "C", front: "Two classic cash budget adjustments students miss", back: "Exclude every non-cash item (depreciation above all), and lag receipts and payments by the credit period — a March credit sale on 60-day terms is May cash." },
  { id: "MA-FC3-27", paper: "MA", area: "C", front: "The four components of a time series", back: "Trend (long-run direction), seasonal variation (regular within-year pattern), cyclical variation (multi-year economic swings), residual/random variation (unexplained noise)." },
  { id: "MA-FC3-28", paper: "MA", area: "C", front: "Additive vs multiplicative seasonal models", back: "Additive: forecast = trend + seasonal amount (fixed units). Multiplicative: forecast = trend × seasonal index (a percentage) — the better fit when the seasonal swing grows with the trend." },
  { id: "MA-FC3-29", paper: "MA", area: "C", front: "What do r and r² tell you in regression?", back: "r (correlation coefficient, −1 to +1) measures the strength and direction of the linear relationship. r² (coefficient of determination) is the proportion of the variation in y explained by x — r = 0.9 means r² = 81%." },
  { id: "MA-FC3-30", paper: "MA", area: "C", front: "Six purposes of budgeting", back: "Planning, coordination between functions, communication of targets, motivation of managers, control by comparing actuals, and performance evaluation. (Plus authorisation of spending.)" },

  /* MA D — Standard costing & variances (12) */
  { id: "MA-FC3-31", paper: "MA", area: "D", front: "What sits on a standard cost card?", back: "For one unit: standard quantity and price of each material, standard hours and rate for each grade of labour, variable overhead per hour, and (under absorption costing) the fixed overhead absorption rate — building up to standard cost per unit." },
  { id: "MA-FC3-32", paper: "MA", area: "D", front: "The four types of standard", back: "Ideal (perfect conditions — demotivating), attainable (challenging but achievable — best for motivation), current (based on today's conditions — perpetuates waste), basic (unchanged over years — only good for trends)." },
  { id: "MA-FC3-33", paper: "MA", area: "D", front: "The total materials cost variance splits into…", back: "PRICE variance (paid more or less per kg than standard) plus USAGE variance (used more or fewer kg than standard for the actual output). Together they explain the whole gap." },
  { id: "MA-FC3-34", paper: "MA", area: "D", front: "Trap: material inventory is held at STANDARD cost — price variance on quantity bought or used?", back: "On the quantity PURCHASED, at the point of purchase. (Usage variance is always on the quantity USED.) Only if inventory were held at actual cost would the price variance be based on usage." },
  { id: "MA-FC3-35", paper: "MA", area: "D", front: "The labour cost variance splits — and the idle time subtlety", back: "Rate variance (on hours PAID) plus efficiency variance (on hours WORKED). Where idle time is separated, it is (hours paid − hours worked) × standard rate, always adverse — and efficiency is then measured on working hours only." },
  { id: "MA-FC3-36", paper: "MA", area: "D", front: "Variable overhead EXPENDITURE variance", back: "(Actual hours worked × standard variable overhead rate) − actual variable overhead incurred. Positive = favourable: the overhead cost per hour ran below standard." },
  { id: "MA-FC3-37", paper: "MA", area: "D", front: "Variable overhead EFFICIENCY variance", back: "(Standard hours for actual output − actual hours worked) × standard variable overhead rate. It mirrors labour efficiency — variable overhead is assumed to vary with hours worked." },
  { id: "MA-FC3-38", paper: "MA", area: "D", front: "Splitting the fixed overhead VOLUME variance", back: "Capacity: (actual hours worked − budgeted hours) × standard fixed OAR per hour — did we work more hours than planned? Efficiency: (standard hours for actual output − actual hours) × OAR per hour — did we produce quickly in those hours?" },
  { id: "MA-FC3-39", paper: "MA", area: "D", front: "The total fixed overhead variance equals what familiar figure?", back: "The over- or under-absorbed overhead: (actual output × OAR) − actual fixed overhead. Its two components are the expenditure variance and the volume variance." },
  { id: "MA-FC3-40", paper: "MA", area: "D", front: "The standard costing operating statement — the skeleton", back: "Budgeted profit → adjust for sales volume variance → standard profit on actual sales → adjust for sales price variance → then add favourable and deduct adverse cost variances → actual profit." },
  { id: "MA-FC3-41", paper: "MA", area: "D", front: "How can one decision cause OPPOSITE variances? Give the classic example", back: "Buying cheaper, lower-grade material: a FAVOURABLE price variance, but ADVERSE material usage and labour efficiency variances as more is wasted and work slows. Variances must be read together, not in isolation." },
  { id: "MA-FC3-42", paper: "MA", area: "D", front: "Four causes of an ADVERSE labour efficiency variance", back: "Untrained or inexperienced staff; poor-quality materials slowing the work; machine breakdowns and disruptions; low morale — or simply an unrealistically tight standard." },

  /* MA E — Performance measurement (8) */
  { id: "MA-FC3-43", paper: "MA", area: "E", front: "Labour EFFICIENCY (productivity) ratio", back: "Standard hours for actual output ÷ actual hours worked × 100. Above 100% = working faster than standard." },
  { id: "MA-FC3-44", paper: "MA", area: "E", front: "CAPACITY ratio", back: "Actual hours worked ÷ budgeted hours × 100. Above 100% = more hours were worked than the budget planned." },
  { id: "MA-FC3-45", paper: "MA", area: "E", front: "PRODUCTION VOLUME ratio — and its link to the other two", back: "Standard hours for actual output ÷ budgeted hours × 100. It equals efficiency ratio × capacity ratio ÷ 100 — output can beat budget through longer hours, faster work, or both." },
  { id: "MA-FC3-46", paper: "MA", area: "E", front: "The four responsibility centres and what each manager answers for", back: "Cost centre: costs only. Revenue centre: revenues only. Profit centre: costs and revenues. Investment centre: profit AND the capital invested — so ROI/RI apply only here." },
  { id: "MA-FC3-47", paper: "MA", area: "E", front: "Trap: division ROI 20%; new project returns 15%; cost of capital 10% — what happens?", back: "An ROI-judged manager REJECTS it (it drags 20% down) even though it beats the 10% cost of capital and adds wealth. Judge with residual income and the project shows positive RI — RI is the goal-congruent measure." },
  { id: "MA-FC3-48", paper: "MA", area: "E", front: "Quick calculation: profit $80,000, capital employed $500,000, cost of capital 12% — the residual income?", back: "RI = 80,000 − (500,000 × 12%) = 80,000 − 60,000 = $20,000 positive. Positive RI = the division earns more than the capital charge." },
  { id: "MA-FC3-49", paper: "MA", area: "E", front: "Three types of benchmarking", back: "Internal (against another unit in the same organisation), competitive (against a direct rival), functional/best-practice (against the best performer of the same PROCESS in any industry — e.g. a hospital studying an airline's turnaround times)." },
  { id: "MA-FC3-50", paper: "MA", area: "E", front: "Why balance financial measures with non-financial ones?", back: "Financial measures alone are backward-looking and breed short-termism (cut training, delay maintenance, still hit this year's profit). Non-financial indicators — quality, delivery, customer satisfaction — signal FUTURE financial results." },
]
