import type { WrittenQuestion } from "@/lib/acca-written"

/*
 * Scholify — FM (F9, Financial Management) written questions, wave 3 (W3).
 *
 * FM's Section C is two 20-mark constructed-response questions that pair a
 * calculation with a discussion — and the marks live in the discussion. These
 * 15 questions target exactly that: the reasoning, the assumptions and the
 * interpretation, not the arithmetic. Every scenario, company, person and
 * figure is INVENTED; all technical content is drawn from the public FM
 * syllabus only. No ACCA, Kaplan or BPP material is reproduced. Each carries a
 * rubric of marking points (~1 mark each) for the AI Examiner.
 */

export const WRITTEN_W3_FM: WrittenQuestion[] = [
  // ═══════════ A — Financial management function (2) ═══════════
  {
    id: "FM-W-01",
    paper: "FM",
    area: "A",
    topic: "Objectives, agency and reward schemes",
    stem: "Calvert Interiors plc is a listed furniture manufacturer. Its board is paid a bonus based solely on the growth in reported earnings per share over each 12-month period. In the last year the directors closed a promising design studio to cut costs, deferred a major machinery upgrade, and funded a share buy-back with new debt. EPS rose by 14% and the bonuses were paid in full, but the share price fell by 9% over the same period. A large institutional shareholder has written to the chair complaining that 'management and owners are pulling in opposite directions'. Explain the agency problem illustrated by these events, and evaluate whether the board's reward scheme is likely to encourage goal congruence. (10 marks)",
    maxMarks: 10,
    rubric: [
      "The primary financial objective of a listed company is the maximisation of shareholder wealth, measured by dividends plus capital growth in the share price.",
      "The agency problem arises because the directors (agents) manage the company on behalf of the shareholders (principals) but have their own objectives, and there is asymmetric information between them.",
      "The falling share price alongside rising EPS shows the market has judged that shareholder wealth has been destroyed even though the bonus metric improved.",
      "EPS is an accounting measure of profit, not of wealth: it ignores risk, ignores the timing of cash flows and can be increased by actions that damage long-run value.",
      "Closing the design studio and deferring the machinery upgrade are examples of short-termism — boosting current earnings by sacrificing future cash flows.",
      "The debt-funded buy-back reduces the share count and so mechanically raises EPS, but it also raises gearing and therefore financial risk borne by shareholders.",
      "A single-metric, annual, all-or-nothing bonus rewards manipulation of the metric rather than performance, so it does not align managers with owners.",
      "Better designed schemes tie reward to longer-term wealth: share options or share awards vesting over several years, or performance conditions based on total shareholder return.",
      "Recognises that share-based reward can itself distort behaviour (e.g. encouraging excessive risk-taking to lift the option value), so conditions and clawback matter.",
      "Concludes with a recommendation: redesign the scheme around multi-year, cash-flow or TSR-based measures, supported by other goal-congruence mechanisms such as non-executive scrutiny, disclosure and the discipline of the market for corporate control.",
    ],
  },
  {
    id: "FM-W-02",
    paper: "FM",
    area: "A",
    topic: "Not-for-profit objectives and value for money",
    stem: "Northmoor Community Health Trust is a publicly funded body providing walk-in clinics. It cannot measure success by profit or share price, and its board is under pressure from its funding department to 'demonstrate value for money'. The chief executive proposes to cut the cost per patient visit by hiring less experienced clinical staff and reducing appointment lengths. Explain why the objectives of a not-for-profit organisation differ from those of a listed company, and discuss how the value-for-money framework should be applied to assess the chief executive's proposal. (9 marks)",
    maxMarks: 9,
    rubric: [
      "A not-for-profit organisation does not have shareholders and does not exist to maximise wealth, so shareholder wealth maximisation is not an available objective.",
      "Its objective is to provide the best possible service within the resources (funding) available, satisfying multiple stakeholders whose aims may conflict.",
      "Objectives are typically non-financial and hard to quantify, and there is often no market price for the output, which makes performance measurement difficult.",
      "Value for money is therefore assessed through the three Es: economy, efficiency and effectiveness.",
      "Economy is obtaining the required inputs at the lowest cost consistent with the required quality — hiring cheaper staff improves economy only if quality is maintained.",
      "Efficiency is the relationship between inputs and outputs — more patient visits per hour of clinician time improves efficiency.",
      "Effectiveness is the extent to which the organisation achieves its objectives — here, whether patients actually get better.",
      "Identifies the flaw in the proposal: it improves economy and apparent efficiency (cost per visit falls) while risking a fall in effectiveness through misdiagnosis, repeat visits and poorer health outcomes.",
      "Recommends that performance be judged on a balanced set of measures covering all three Es, including outcome and quality indicators, rather than on cost per visit alone.",
    ],
  },

  // ═══════════ B — Investment appraisal (4) ═══════════
  {
    id: "FM-W-03",
    paper: "FM",
    area: "B",
    topic: "Payback, ARR and the case for NPV",
    stem: "Vellmore Packaging Ltd is choosing between two capital projects of equal initial cost. The finance director screens projects using payback period and accounting rate of return only, and has rejected Project Harrier — which has a long payback but very large cash inflows in years 5 to 9 — in favour of Project Kestrel, which pays back in under two years but generates little thereafter. A newly qualified accountant argues that net present value should be the primary decision rule. Explain the limitations of payback and ARR as investment appraisal methods, and discuss why NPV is theoretically superior. (10 marks)",
    maxMarks: 10,
    rubric: [
      "Payback measures the time taken for cumulative cash inflows to recover the initial investment, and is used as a simple screening device.",
      "Payback ignores all cash flows arising after the payback date — which is precisely why Project Harrier's large years 5 to 9 inflows were discarded.",
      "Payback ignores the time value of money (in its basic form) and gives no measure of the absolute return or value created.",
      "The payback target period is set arbitrarily, so the decision rule has no theoretical basis, and its bias towards early cash flows encourages short-termism.",
      "ARR (return on capital employed) is based on accounting profits, not cash flows, so it is affected by accounting policies such as the depreciation method chosen.",
      "ARR ignores the time value of money and the size and life of the project, and the target rate against which it is compared is again arbitrary.",
      "NPV discounts all relevant future cash flows at the cost of capital, so it accounts for the whole life of the project and for the time value of money.",
      "Recognises that a positive NPV means the project is expected to increase shareholder wealth by that amount in today's terms, and so should be accepted — subject to the reliability of the cash-flow estimates.",
      "NPV is absolute, so NPVs are additive, which makes it appropriate for ranking and for choosing between competing projects.",
      "Concludes by advising that NPV should be the primary rule, with payback retained only as a secondary liquidity/risk screen and the Harrier decision revisited.",
    ],
  },
  {
    id: "FM-W-04",
    paper: "FM",
    area: "B",
    topic: "Relevant cash flows, tax and inflation",
    stem: "Ashgrove Robotics Ltd is appraising a new assembly line. The draft appraisal prepared by a junior analyst includes: a share of head office rent apportioned to the project, the £180,000 already spent on a feasibility study, annual depreciation of the machine, and interest on the loan that will fund it. All cash flows have been stated at today's prices and discounted at the company's money (nominal) cost of capital of 11%. Corporation tax and tax-allowable depreciation have been ignored. Explain which items in the draft appraisal are not relevant cash flows and why, and explain how tax and inflation should be dealt with correctly in the NPV calculation. (11 marks)",
    maxMarks: 11,
    rubric: [
      "A relevant cash flow is a future, incremental cash flow that arises as a direct result of the decision.",
      "The apportioned head office rent is not relevant because it is an existing fixed cost that will be incurred whether or not the project goes ahead — only incremental overheads are included.",
      "The £180,000 feasibility study is a sunk cost: it has already been incurred and cannot be changed by the decision, so it must be excluded.",
      "Depreciation is not a cash flow — it is an accounting allocation — and must be added back or excluded entirely.",
      "Interest on the project loan is excluded from the cash flows because the cost of finance is already reflected in the discount rate; including it would double-count the financing cost.",
      "Opportunity costs (such as the contribution lost from the displaced use of a resource) are relevant and should be included even though no cash changes hands directly.",
      "Tax should be dealt with by charging corporation tax on the net operating cash flows and separately claiming the tax savings on tax-allowable depreciation (capital allowances), with any balancing allowance or charge on disposal.",
      "The timing of tax must be applied consistently — either in the same year as the cash flow or one year in arrears, as the scenario specifies.",
      "The golden consistency rule: money (nominal) cash flows must be discounted at the money cost of capital, and real (current-price) cash flows at the real cost of capital.",
      "The draft breaches this rule by discounting current-price cash flows at the money rate of 11%, which understates the NPV; the analyst must either inflate the cash flows to money terms or deflate the discount rate.",
      "The real and money rates are linked by the Fisher effect — (1 + money) = (1 + real) x (1 + inflation) — and specific inflation rates should be applied where different cash flows inflate at different rates.",
    ],
  },
  {
    id: "FM-W-05",
    paper: "FM",
    area: "B",
    topic: "Asset replacement and equivalent annual cost",
    stem: "Trentbank Couriers Ltd operates a fleet of delivery vans. Each van can be kept for one, two or three years before being sold, and the running costs rise sharply with age while the resale value falls. The fleet manager wants to know how often the vans should be replaced and proposes simply choosing the cycle with the lowest total present value of costs. Explain why comparing the total present value of costs across cycles of different lengths gives a misleading answer, and explain how the equivalent annual cost method resolves this and what assumptions it relies on. (8 marks)",
    maxMarks: 8,
    rubric: [
      "The asset replacement decision balances rising maintenance and running costs against falling resale value as the asset ages.",
      "Comparing total present value of costs directly is misleading because the cycles cover different lengths of time, so they are not like-for-like — a one-year cycle will almost always show the lowest total cost.",
      "The equivalent annual cost converts the present value of costs of each replacement cycle into an equivalent constant annual cash flow, putting all cycles on a common annual basis.",
      "It is calculated by dividing the PV of the costs of one cycle by the annuity factor for the number of years in that cycle.",
      "Recognises that the optimal replacement cycle is the one with the LOWEST equivalent annual cost, and that this is the cycle the fleet manager should adopt.",
      "The method assumes the asset is replaced in perpetuity by an identical asset with the same cash-flow pattern.",
      "It also assumes no changes in technology, no inflation in the cost structure (or that all costs inflate uniformly), and an unchanged operating requirement.",
      "Concludes that these assumptions are unlikely to hold exactly — for example if electric vans change the cost profile — so the answer should be treated as a guide and revisited when the operating environment changes.",
    ],
  },
  {
    id: "FM-W-06",
    paper: "FM",
    area: "B",
    topic: "Capital rationing and risk in appraisal",
    stem: "Halverstone Foods Ltd has identified five positive-NPV projects but its board has fixed the capital budget for next year at £6 million, which is not enough to fund them all. The finance director proposes ranking the projects by NPV and accepting them in order until the budget is exhausted. One director also asks how the board should allow for the fact that the projected cash flows for the two overseas projects are 'a lot less certain than the domestic ones'. Explain how a company should select projects under single-period capital rationing, distinguishing hard and soft rationing, and explain how risk and uncertainty can be reflected in investment appraisal. (10 marks)",
    maxMarks: 10,
    rubric: [
      "Capital rationing exists where a company cannot fund all the positive-NPV projects available to it.",
      "Hard rationing is imposed externally by the capital markets — lenders and investors are unwilling to supply further funds, perhaps because the company is small, unlisted or highly geared.",
      "Soft rationing is imposed internally by management, for example a fixed budget, a desire to avoid new equity or debt, or a wish to make divisions compete for funds.",
      "Ranking simply by absolute NPV is wrong under rationing because it ignores how much of the scarce capital each project consumes.",
      "For divisible projects, rank by the profitability index (NPV per £1 of the limiting capital invested) and accept in that order until the budget is exhausted, taking a fraction of the marginal project.",
      "For indivisible projects the PI ranking may not give the optimal answer, so the combinations of whole projects that fit within the budget must be tested and the combination with the highest total NPV selected.",
      "Risk means the possible outcomes and their probabilities can be estimated; uncertainty means the outcomes themselves cannot be reliably predicted, which is the position for the overseas projects.",
      "Sensitivity analysis measures the percentage change in a variable that would reduce the NPV to zero, showing which variables the decision is most exposed to — but it changes one variable at a time and attaches no probabilities.",
      "Expected values combine outcomes with their probabilities, but the resulting figure is an average that may never actually occur and is only as good as the probability estimates.",
      "Concludes that the board should apply PI ranking within the £6m budget, subject the overseas projects to sensitivity analysis, and treat a positive NPV as a signal to accept only where the underlying cash-flow estimates are reliable.",
    ],
  },

  // ═══════════ C — Working capital management (3) ═══════════
  {
    id: "FM-W-07",
    paper: "FM",
    area: "C",
    topic: "Cash operating cycle and overtrading",
    stem: "Merrow Fabrications Ltd has grown revenue by 55% in 18 months by winning large contracts on generous credit terms. Inventory and receivables days have both lengthened sharply, the overdraft is permanently at its limit, suppliers are being paid later and later, and the company has funded two new machines out of the overdraft. Profit margins are thin but positive. The managing director is baffled: 'We are more profitable than ever, so why can we never pay anyone?' Explain what the cash operating cycle measures and how it is built up, and discuss whether Merrow is overtrading and what should be done about it. (10 marks)",
    maxMarks: 10,
    rubric: [
      "The cash operating cycle is the length of time between paying a supplier for goods and receiving the cash from the customer for the resulting sale.",
      "It is built up as inventory holding days plus receivables collection days less payables payment days.",
      "The longer the cycle, the more working capital investment must be financed, so a lengthening cycle absorbs cash even while the company reports profits.",
      "Explains the managing director's confusion: profit is an accounting measure recognised on sale, whereas cash is only received when the customer pays — a profitable company can still run out of cash.",
      "Overtrading (undercapitalisation) is rapid growth in sales without a matching increase in long-term finance to support the growing working capital investment.",
      "The symptoms present at Merrow are classic: rapid revenue growth, rising inventory and receivables days, stretched payables, a permanently used overdraft and thin margins.",
      "Using a short-term overdraft to fund long-term assets (the two machines) breaches the matching principle and worsens the liquidity position.",
      "The consequence of continued overtrading is insolvency — the company can fail despite being profitable, if suppliers or the bank withdraw support.",
      "Remedies include raising additional long-term finance (equity or a term loan) to replace the overdraft funding of the machines and support working capital.",
      "Further remedies: tighten credit control and collection, reduce inventory days, consider slowing sales growth or improving margins, and negotiate the credit terms offered on new contracts rather than buying revenue with credit.",
    ],
  },
  {
    id: "FM-W-08",
    paper: "FM",
    area: "C",
    topic: "Inventory (EOQ) and receivables policy",
    stem: "Dunhaven Tools Ltd holds large inventories of steel components and is reviewing its ordering policy using the economic order quantity model. Its supplier has offered a bulk discount for orders above a stated size. Separately, the sales director wants to offer customers a '2% discount for payment within 10 days, otherwise net 45 days' settlement discount to speed up collections; the company currently finances its receivables on an overdraft costing 9% a year. Explain the trade-off the EOQ model resolves and the assumptions on which it rests, and explain how the company should decide whether the proposed settlement discount is worth offering. (9 marks)",
    maxMarks: 9,
    rubric: [
      "Inventory management involves a trade-off between ordering costs (which fall as order size rises) and holding costs (which rise as order size rises).",
      "The EOQ is the order quantity that minimises the total of ordering and holding costs; at that point the two cost curves are equal.",
      "The model assumes constant and known demand, a constant purchase price with no discounts, constant ordering and holding costs, zero lead time (or a known constant lead time) and no stockouts.",
      "Where a bulk discount is offered, the EOQ formula alone is insufficient: the total cost (purchase cost plus ordering cost plus holding cost) must be recomputed at the EOQ and at each discount threshold, and the lowest total cost chosen.",
      "These restrictive assumptions rarely hold in practice, which is why some companies move to just-in-time purchasing, shifting the emphasis to supplier reliability rather than buffer stock.",
      "For the settlement discount, the cost to the company is the discount given up on the sales value in exchange for receiving the cash earlier.",
      "That cost should be annualised and compared with the annual cost of the finance the company would save — here the 9% overdraft rate.",
      "Recognises the decision rule: offer the discount only if its annualised cost is less than the cost of financing the receivables for the period saved, i.e. below 9%.",
      "Notes the wider factors the calculation ignores: the risk that customers take the discount and still pay late, the effect on customer goodwill and demand, and the reduction in irrecoverable debts and administration costs from faster collection.",
    ],
  },
  {
    id: "FM-W-09",
    paper: "FM",
    area: "C",
    topic: "Cash management models and payables policy",
    stem: "Ravensdale Media Ltd holds a large, idle cash balance in its current account. The treasurer knows the company's net cash outflow for the coming year with reasonable confidence and wants to hold most of the money in short-dated investments, transferring cash back only as needed. A colleague argues that the company's cash flows are actually erratic and unpredictable, so a different model is required. The board is separately considering deliberately paying its suppliers 30 days beyond the agreed terms to conserve cash. Explain how the Baumol and Miller-Orr models help a company manage its cash balance and when each is appropriate, and discuss the risks of the proposed payables policy. (9 marks)",
    maxMarks: 9,
    rubric: [
      "Companies hold cash for transactions, precautionary and speculative motives, but idle cash earns a poor return, so there is a trade-off between liquidity and return.",
      "The Baumol model treats cash like inventory: it balances the transaction cost of each transfer from investments into cash against the interest income forgone on the cash held.",
      "It gives an optimal transfer size, and so applies where cash usage is steady and predictable — which fits the treasurer's description of a known, even outflow.",
      "The Miller-Orr model is designed for cash flows that fluctuate randomly: it sets an upper limit and a lower limit, with a return point between them.",
      "Under Miller-Orr the company only acts when the balance hits a limit — investing surplus cash back down to the return point at the upper limit, and selling investments to restore it at the lower limit.",
      "The spread between the limits widens with the variability (variance) of cash flows and with transaction costs, and narrows as interest rates rise.",
      "Recognises that the colleague is right that Miller-Orr is the appropriate model where cash flows are erratic, but that both models rest on simplifying assumptions and ignore the possibility of forecasting cash flows directly.",
      "Trade payables are a source of free short-term finance if taken within agreed terms, but deliberately paying 30 days late is not free.",
      "Concludes that the payables policy is risky: it damages supplier relationships, may forfeit settlement discounts, can lead to loss of credit, stricter terms or withdrawal of supply, and is itself a classic warning sign of overtrading to lenders and credit agencies.",
    ],
  },

  // ═══════════ D — Business finance & cost of capital (4) ═══════════
  {
    id: "FM-W-10",
    paper: "FM",
    area: "D",
    topic: "Equity vs debt and rights issues",
    stem: "Calthorpe Engineering plc, a listed company with modest gearing, needs £40 million to fund a new plant. The finance director has proposed a 1-for-5 rights issue at a 20% discount to the current market price. Two directors object: one says the discount 'gives away value to existing shareholders at the expense of the company', and the other says the company should simply borrow the money because 'debt is cheaper than equity'. Evaluate the relative merits of raising the finance by debt and by equity, and explain the effect of the proposed rights issue on shareholders, addressing the first director's objection. (10 marks)",
    maxMarks: 10,
    rubric: [
      "Debt carries a lower required return than equity because lenders rank ahead of shareholders on liquidation and usually have security, so they bear less risk.",
      "Interest is also tax-deductible, so the effective cost of debt to the company is the after-tax cost — this is why debt appears 'cheaper'.",
      "However, debt introduces fixed interest commitments and repayment obligations, increasing financial risk and the volatility of earnings available to shareholders.",
      "Debt may also carry restrictive covenants (e.g. on gearing or dividends) and require security, limiting the company's future flexibility.",
      "Equity carries no obligation to pay dividends and no repayment date, so it does not increase the risk of financial distress, but it is more expensive and dividends are not tax-deductible.",
      "A rights issue is an offer of new shares to existing shareholders in proportion to their existing holdings, which preserves their proportionate ownership and avoids dilution of control.",
      "The theoretical ex-rights price is a weighted average of the pre-issue market value and the funds raised, so the share price falls after the issue purely because more shares now exist.",
      "Answers the first director's objection: the discount does not transfer value away from the company, because a shareholder who takes up the rights buys new shares cheaply and exactly offsets the fall in the value of the existing holding — the shareholder is (in theory) no better or worse off.",
      "A shareholder who does not wish to subscribe can sell the rights (nil paid) and receive the value of the discount in cash, so no shareholder is forced to lose out; the discount only exists to ensure the issue is taken up if the price moves.",
      "Concludes with a recommendation that considers the company's current gearing, the stability of its cash flows, the size of the sum relative to the company, the availability of security and the effect on the WACC.",
    ],
  },
  {
    id: "FM-W-11",
    paper: "FM",
    area: "D",
    topic: "SME finance gap and Islamic finance",
    stem: "Fenmark Bio Ltd is an unlisted six-year-old company developing laboratory instruments. It has strong growth prospects but few tangible assets, a short trading record and volatile cash flows. Its bank has refused a term loan. The founder is exploring venture capital, a business angel and, having a large customer base in the Gulf, wonders whether Islamic finance could help. Explain why small and medium-sized entities such as Fenmark face a 'finance gap', and describe the sources of finance that could realistically be available to it, including the principles that distinguish Islamic finance from conventional debt. (10 marks)",
    maxMarks: 10,
    rubric: [
      "The finance gap is the difficulty SMEs face in raising the finance they need, both in the amount available and in the range of sources open to them.",
      "SMEs cannot access the capital markets: a stock market listing or a public bond issue is not practicable given their size and cost.",
      "Lenders face greater information asymmetry with an unlisted company — there is no market price, less public information and a short track record, so risk assessment is costly.",
      "Fenmark's specific problems are a lack of tangible assets to offer as security, volatile cash flows and unproven technology, which is exactly why the bank refused the loan.",
      "Venture capital provides equity for high-growth, high-risk companies, but the VC will demand a large equity stake, board representation and a clear exit route (trade sale or flotation) within a few years.",
      "A business angel is a wealthy individual investing smaller amounts, typically with fewer formal conditions but also bringing experience and contacts.",
      "Other realistic sources include retained earnings, leasing or hire purchase of equipment (secured on the asset itself), invoice financing or factoring against receivables, crowdfunding and government-backed loan guarantee schemes.",
      "Islamic finance prohibits riba — the payment or receipt of interest — so returns cannot be a predetermined charge for the use of money.",
      "Instead, Islamic finance is based on the sharing of risk and reward and on an underlying tangible asset or trade, with the provider taking a genuine interest in the venture rather than simply lending.",
      "Explains at least two instruments in outline: Mudaraba (the finance provider supplies capital and shares in profits, with losses borne by the provider) and Musharaka (a partnership in which both parties contribute capital and share profits and losses), plus Murabaha (cost-plus sale) or Ijara (leasing) as asset-based alternatives to a loan.",
    ],
  },
  {
    id: "FM-W-12",
    paper: "FM",
    area: "D",
    topic: "CAPM, DVM and the WACC as a discount rate",
    stem: "Ledbury Chemicals plc has calculated its cost of equity in two ways: the dividend growth model, using historical dividend growth over the last five years, gives 11.8%; the capital asset pricing model, using the company's equity beta, gives 13.4%. The finance director has combined the higher figure with the after-tax cost of the company's existing loan notes to produce a WACC of 10.2%, and now intends to use 10.2% to appraise the company's proposed move into pharmaceutical manufacturing — an entirely new business for the group, to be funded largely by new debt. Interpret the difference between the two cost-of-equity figures, and evaluate whether the existing WACC is an appropriate discount rate for the proposed project. (11 marks)",
    maxMarks: 11,
    rubric: [
      "The dividend valuation/growth model derives the cost of equity from the current share price, the expected dividend and the expected future growth rate in dividends.",
      "Its weakness is that it is highly sensitive to the growth estimate, and using historical growth assumes the past is a reliable guide to the future — which may not hold.",
      "The DVM also assumes dividends grow at a constant rate in perpetuity, and it cannot easily be applied to a company that pays no dividend.",
      "CAPM derives the cost of equity from the risk-free rate plus a premium for the systematic risk of the company's shares, measured by the equity beta.",
      "CAPM assumes investors hold well-diversified portfolios so that only systematic risk is rewarded; unsystematic risk is diversified away and earns no return.",
      "CAPM's inputs are also estimates — the beta is derived from historical share price data, and the risk-free rate and market risk premium must be assumed — so the two models can legitimately differ; the difference is a measure of estimation uncertainty, not evidence that one is 'wrong'.",
      "The WACC is only a valid discount rate where the new project has the same BUSINESS RISK as the company's existing operations.",
      "The move into pharmaceutical manufacturing is an entirely new business, so its business risk differs from the existing chemicals operations and the existing WACC is not appropriate.",
      "The WACC also assumes the project does not change the company's capital structure (financial risk); funding it largely with new debt would raise gearing, so this condition is breached too.",
      "The correct approach is a risk-adjusted, project-specific discount rate: take an equity beta from a company already operating in pharmaceuticals (a proxy company), ungear it to an asset beta to strip out that company's financial risk, then regear it to Ledbury's capital structure and use CAPM to find a project-specific cost of equity.",
      "Concludes that discounting a higher-risk project at the existing 10.2% WACC would overstate its NPV and could lead the board to accept a project that does not in fact increase shareholder wealth.",
    ],
  },
  {
    id: "FM-W-13",
    paper: "FM",
    area: "D",
    topic: "Capital structure theories and gearing",
    stem: "The board of Ormsby Textiles plc is debating how far it should increase gearing. The finance director claims that 'because debt is cheaper than equity, every extra pound of debt lowers our WACC and raises the value of the company — so we should gear up as far as the banks will let us'. The chief executive is uneasy and has asked for an explanation of what theory actually says. Discuss the traditional view and the Modigliani-Miller propositions (with and without tax) on the relationship between capital structure, WACC and firm value, and advise the board on the finance director's claim. (11 marks)",
    maxMarks: 11,
    rubric: [
      "Gearing measures the proportion of debt in the capital structure; increasing it substitutes cheaper debt for more expensive equity.",
      "The traditional view holds that as gearing rises from zero, the WACC initially falls because the cheaper debt outweighs the modest increase in the cost of equity.",
      "Under the traditional view, beyond an optimal level of gearing the cost of equity rises steeply and the cost of debt begins to rise too, so the WACC turns upward — implying an optimal capital structure at the minimum WACC, which maximises firm value.",
      "Modigliani and Miller, without tax, argue that in a perfect capital market the WACC and the value of the firm are unaffected by capital structure.",
      "This is because the benefit of cheaper debt is exactly offset by the rise in the cost of equity: shareholders demand a higher return to compensate for the increased financial risk they bear.",
      "MM's no-tax model rests on strong assumptions — perfect and frictionless capital markets, no transaction or bankruptcy costs, personal borrowing on the same terms as corporate borrowing, and no taxes.",
      "With corporate tax, MM conclude that because interest is tax-deductible, gearing creates a tax shield, so WACC falls continuously and firm value rises with gearing — implying a theoretical optimum of nearly 100% debt.",
      "Recognises that the finance director's claim is essentially MM-with-tax taken literally, and that in the real world it fails.",
      "In practice, high gearing brings bankruptcy and financial distress costs (lost customers and suppliers, forced asset sales, higher borrowing costs) and agency costs (restrictive covenants that constrain management).",
      "There may also be a limit to the tax shield if the company has insufficient taxable profits to relieve the interest.",
      "Advises the board to reject the 'gear up as far as possible' proposal: the practical position lies between the theories, with a broad range of gearing within which the WACC is fairly flat, and the appropriate level depends on the stability of Ormsby's cash flows, its asset backing, its industry norms and its debt capacity.",
    ],
  },

  // ═══════════ E — Business valuations & risk (2) ═══════════
  {
    id: "FM-W-14",
    paper: "FM",
    area: "E",
    topic: "Valuing an unlisted company; market efficiency",
    stem: "Brookhill Cereals plc is planning a cash bid for Wrenfield Mills Ltd, an unlisted family-owned miller. Wrenfield's directors have valued the company at the net book value of its assets. Brookhill's finance team has instead produced three figures: an earnings-based value using the P/E ratio of a listed miller, a dividend-based value using the dividend valuation model, and a discounted free cash flow value which is by far the highest of the three. The board also expects Brookhill's own share price to react as soon as the bid is announced. Evaluate the valuation methods used, explaining which is most appropriate for Wrenfield and why, and explain what the expected share price reaction implies about the efficiency of the market in Brookhill's shares. (12 marks)",
    maxMarks: 12,
    rubric: [
      "Asset-based valuations value the company as the sum of its net assets, on a net book value, net realisable value or replacement cost basis.",
      "Net book value is the weakest basis: it reflects historical accounting figures and depreciation policy, not current value, and it ignores internally generated goodwill, brands and the workforce.",
      "An asset basis therefore sets only a floor value (a minimum the seller should accept), and is most relevant to an asset-stripping buyer or a company being wound up.",
      "The P/E method values the company by applying a suitable P/E ratio to its maintainable post-tax earnings, and so does capture the value of the business as a going concern.",
      "The listed miller's P/E must be discounted before it is applied to Wrenfield, because Wrenfield's shares are unlisted and therefore less marketable and less liquid; adjustments may also be needed for differences in growth, risk and accounting policies.",
      "The dividend valuation model values a share as the present value of its future dividends, which makes it appropriate for a minority stake but not for the purchase of a controlling interest, since the buyer will control the dividend policy.",
      "The DVM is also unreliable for an unlisted family company, whose dividend policy may be driven by the family's tax and income needs rather than by earnings.",
      "The discounted free cash flow method values the company as the present value of the future free cash flows the business is expected to generate, discounted at a risk-adjusted cost of capital — theoretically the soundest method because it is based on cash and reflects timing and risk.",
      "Recognises that the DCF figure is the highest precisely because it captures expected future growth and any synergies, but that it is highly sensitive to the forecast cash flows, the assumed growth rate and the discount rate chosen — so the figure is only as reliable as those assumptions.",
      "Advises that free cash flow valuation is the most appropriate basis for Brookhill's bid for control, with the asset value as a floor and the adjusted P/E value as a cross-check, and that the price finally paid will be negotiated somewhere between the two parties' valuations.",
      "In a semi-strong form efficient market, share prices reflect all publicly available information, so Brookhill's share price will move immediately and without bias on the announcement of the bid.",
      "Draws the implication for the board: they cannot mislead an efficient market with the accounting presentation of the deal — the price will move on the market's view of whether the price paid exceeds the value created, so overpaying for Wrenfield will be punished at once by a fall in Brookhill's own share price.",
    ],
  },
  {
    id: "FM-W-15",
    paper: "FM",
    area: "E",
    topic: "Interest rate and currency risk management",
    stem: "Solberg Instruments plc has two exposures. It has just agreed a £12 million floating-rate loan and fears that interest rates will rise before the first reset date. It has also won a contract that will produce a receipt of US$5 million in six months' time, and the finance director is worried about the sterling value of that receipt. A colleague suggests doing nothing on the dollar receipt, arguing that 'purchasing power parity means the exchange rate will just adjust anyway'. Explain the nature of the two exposures Solberg faces, describe the hedging techniques available for each, and evaluate the colleague's argument. (12 marks)",
    maxMarks: 12,
    rubric: [
      "The floating-rate loan gives Solberg interest rate risk: a rise in market rates increases the interest cost and reduces profit and cash flow.",
      "The dollar receipt gives Solberg transaction risk — the risk that the sterling value of a contracted foreign-currency cash flow changes between the transaction date and the settlement date.",
      "Distinguishes transaction risk from translation risk (the accounting effect of restating foreign assets and liabilities) and economic risk (the effect of exchange rate movements on the long-run value of the business).",
      "Interest rate risk can be hedged internally by matching floating-rate assets against floating-rate liabilities, or by smoothing the mix of fixed and floating borrowing.",
      "A forward rate agreement fixes the interest rate on a notional loan for a future period, with a cash settlement compensating for the difference between the FRA rate and the actual rate.",
      "An interest rate swap allows Solberg to exchange its floating-rate interest commitment for a fixed-rate one with a counterparty, and can also exploit differences in the parties' comparative borrowing advantage.",
      "Interest rate futures and options (including collars and caps) are alternatives: an option gives the right but not the obligation to fix the rate, so it protects against an adverse move while leaving the benefit of a favourable one, at the cost of a premium.",
      "The dollar receipt can be hedged internally by netting against dollar payments, invoicing in sterling (which shifts the risk to the customer), or leading and lagging.",
      "A forward contract fixes the exchange rate at which the US$5 million will be sold in six months — it is binding, has no premium, and removes uncertainty completely.",
      "A money market hedge replicates the forward: borrow dollars now in an amount that, with interest, equals the receipt, convert the dollars to sterling at today's spot rate and place the sterling on deposit, repaying the dollar loan from the receipt.",
      "A currency option gives the right but not the obligation to sell the dollars at a fixed rate; it costs a premium but allows Solberg to abandon the option and take the spot rate if sterling weakens — valuable where the receipt is uncertain.",
      "Evaluates the colleague's argument: purchasing power parity predicts that the currency of the country with higher inflation will weaken, and interest rate parity (which drives the forward rate) links the forward premium/discount to the interest rate differential — but these hold only on average and in the long run, they say nothing about the rate on the specific settlement date in six months, and they cannot protect a single contracted cash flow. Concludes that Solberg should hedge, most simply with a forward contract, rather than leave the exposure open.",
    ],
  },
]
