import type { AccaQuestion } from "@/lib/acca-content"

/* LW bank wave 5 — 60 verified originals (English variant, 2026-07-10).
 * Spread: A×8, B×24 (contract-weighted), C×8, D×20 (company-weighted).
 * Difficulty 21/27/12 (easy/medium/hard). Every distractor is a nameable
 * student confusion; explanations teach rule + trap + landmark case. */

export const LW_WAVE2: AccaQuestion[] = [
  /* ───────────── Area A — Essential elements of the legal system ───────────── */
  {
    id: "LW2-A-01",
    paper: "LW",
    area: "A",
    type: "mcq",
    stem: "A new Act of Parliament conflicts with a rule laid down in an earlier Court of Appeal decision. Which source of law prevails?",
    options: [
      "The earlier case, because judicial precedent binds Parliament",
      "The Act of Parliament — legislation is the supreme source of English law",
      "Neither, until the Supreme Court decides which should apply",
      "The earlier case, unless the Act is confirmed by referendum",
    ],
    correct: 1,
    explanation:
      "Under parliamentary sovereignty, an Act of Parliament overrides inconsistent case law: courts must apply the statute. The trap is inverting the hierarchy — precedent binds courts, never Parliament, and no court approval or referendum is needed for an Act to take effect.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "LW2-A-02",
    paper: "LW",
    area: "A",
    type: "mcq",
    stem: "A civil claim is tried at first instance in the High Court. To which court would the losing party normally appeal first?",
    options: [
      "The Supreme Court",
      "The Crown Court",
      "The County Court",
      "The Court of Appeal (Civil Division)",
    ],
    correct: 3,
    explanation:
      "Appeals from the High Court normally lie to the Court of Appeal (Civil Division), and only then (with permission) to the Supreme Court. Traps: jumping straight to the Supreme Court skips a tier ('leapfrog' appeals are exceptional); the Crown Court is a criminal court; the County Court is below the High Court, and appeals go up, not down.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "LW2-A-03",
    paper: "LW",
    area: "A",
    type: "mcq",
    stem: "A statute makes it an offence to obstruct a member of the armed forces 'in the vicinity of' a protected site. Dev obstructs a soldier while standing inside the site itself. A literal reading would acquit him, which the court considers absurd. Which rule of interpretation lets the court read 'in the vicinity of' as including 'in'?",
    options: [
      "The literal rule",
      "The ejusdem generis rule",
      "The golden rule",
      "The mischief rule",
    ],
    correct: 2,
    explanation:
      "The golden rule lets a court depart from the ordinary meaning of words where a literal reading produces an absurd result — exactly what happened in Adler v George, on which this scenario is modelled. The literal rule would produce the absurdity; the mischief rule asks what defect the Act was passed to cure (a different starting point); ejusdem generis is a rule for construing general words following a list.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "LW2-A-04",
    paper: "LW",
    area: "A",
    type: "mcq",
    stem: "When a court applies the MISCHIEF rule of statutory interpretation, its primary question is:",
    options: [
      "What defect or gap in the previous law was the statute passed to remedy?",
      "What is the ordinary dictionary meaning of the words used?",
      "Does a literal reading of the words produce an absurd result?",
      "What outcome would Parliament prefer if it legislated today?",
    ],
    correct: 0,
    explanation:
      "The mischief rule (from Heydon's Case) directs the court to the state of the law before the Act, the 'mischief' the Act was designed to suppress, and the remedy Parliament intended. The dictionary-meaning option describes the literal rule; the absurd-result option describes the golden rule; guessing what Parliament would want today goes beyond even the purposive approach.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "LW2-A-05",
    paper: "LW",
    area: "A",
    type: "mcq",
    stem: "Deciding a contract dispute, a High Court judge remarks that had the facts involved a sale of land instead, she would have decided differently. In a later land case, that remark is:",
    options: [
      "Ratio decidendi, and binding on lower courts",
      "Ratio decidendi, but only persuasive",
      "Obiter dicta, and binding on lower courts",
      "Obiter dicta, and persuasive only",
    ],
    correct: 3,
    explanation:
      "Only the ratio decidendi — the legal principle necessary for the actual decision — binds later courts. Comments on hypothetical facts are obiter dicta and merely persuasive. The classic trap is treating everything a judge says as binding: judges' asides, however senior the judge, do not create binding precedent.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "LW2-A-06",
    paper: "LW",
    area: "A",
    type: "mcq",
    stem: "A County Court judge avoids following an otherwise binding Court of Appeal precedent by showing that the material facts of the case before her are significantly different. This technique is called:",
    options: [
      "Overruling",
      "Reversing",
      "Distinguishing",
      "Disapproving",
    ],
    correct: 2,
    explanation:
      "Distinguishing means declining to apply a precedent because the material facts differ — the only escape route open to a lower court. Overruling is a higher court depriving an earlier precedent of authority in a different, later case; reversing is an appeal court changing the decision in the SAME case; disapproving is criticism without removing the precedent's force. Confusing overruling with reversing is the classic exam error.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "LW2-A-07",
    paper: "LW",
    area: "A",
    type: "mcq",
    stem: "In a civil action for breach of contract, the claimant must prove the case to which standard?",
    options: [
      "On the balance of probabilities",
      "Beyond reasonable doubt",
      "To the unanimous satisfaction of a jury",
      "By clear and convincing evidence",
    ],
    correct: 0,
    explanation:
      "Civil claims are proved on the balance of probabilities (more likely than not). 'Beyond reasonable doubt' is the CRIMINAL standard — the most common mix-up. Civil trials are normally heard by a judge alone, not a jury, and 'clear and convincing evidence' is an American standard with no place in English civil procedure.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "LW2-A-08",
    paper: "LW",
    area: "A",
    type: "mcq",
    stem: "A government minister makes a statutory instrument that goes beyond the powers conferred by the enabling (parent) Act. What can a court do about it?",
    options: [
      "Nothing — courts cannot question any form of legislation",
      "Declare the instrument void as ultra vires the parent Act",
      "Amend the parent Act so the instrument becomes valid",
      "Suspend the instrument until Parliament re-enacts it as an Act",
    ],
    correct: 1,
    explanation:
      "Delegated legislation, unlike an Act of Parliament, can be challenged by judicial review and declared void if it exceeds the powers in the parent Act (ultra vires). The trap is over-extending parliamentary sovereignty: courts cannot strike down Acts, but they CAN strike down delegated legislation. Courts also cannot amend Acts — only Parliament can.",
    marks: 2,
    difficulty: "medium",
  },

  /* ───────────── Area B — The law of obligations: contract ───────────── */
  {
    id: "LW2-B-01",
    paper: "LW",
    area: "B",
    type: "mcq",
    stem: "FitFuel Ltd advertises: 'We will pay £500 to anyone who completes our 30-day nutrition plan and fails to feel more energetic. £5,000 has been deposited with our bank to show our sincerity.' Priya completes the plan, feels no better, and claims the £500. FitFuel argues the advert was mere marketing. The best analysis is:",
    options: [
      "The advert was an invitation to treat, so no contract was ever formed",
      "Priya cannot claim because she never notified FitFuel that she was accepting before she performed",
      "The advert was a unilateral offer which Priya accepted by completing the plan, so she is entitled to £500",
      "The advert was mere sales puff, showing no intention to be bound",
    ],
    correct: 2,
    explanation:
      "An advert promising payment on performance of stated conditions is a unilateral OFFER, accepted by performing — Carlill v Carbolic Smoke Ball Co. The bank deposit rebuts any 'mere puff' argument, exactly as in Carlill. Traps: treating every advert as an invitation to treat (that applies to bilateral sale adverts, e.g. Partridge v Crittenden), and requiring prior communication of acceptance — in unilateral offers the offeror waives that requirement.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "LW2-B-02",
    paper: "LW",
    area: "B",
    type: "mcq",
    stem: "A supermarket mistakenly labels a £300 coffee machine at £30 on the shelf. Marco takes it to the till and insists the store must sell it to him at £30. Legally:",
    options: [
      "The shelf display is an invitation to treat; Marco makes the offer at the till, which the store may refuse",
      "The display is an offer which Marco accepted by picking the machine up",
      "A binding contract formed at £30 the moment Marco entered the store",
      "The store must honour the shelf price because displayed prices are always contractually binding",
    ],
    correct: 0,
    explanation:
      "Goods on display are an invitation to treat: the customer offers to buy at the till and the retailer is free to accept or reject — Pharmaceutical Society of GB v Boots (shelves) and Fisher v Bell (window displays). The trap is treating the display as an offer; if it were, picking up goods would form contracts and pricing errors would be irreversibly binding.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "LW2-B-03",
    paper: "LW",
    area: "B",
    type: "mcq",
    stem: "Selma offers to sell her van to Tom for £10,000. Tom replies, 'I'll give you £8,500.' Selma refuses. Two days later Tom says, 'Fine — I accept your £10,000 offer.' Selma no longer wants to sell. Is there a contract?",
    options: [
      "Yes — Tom accepted the original offer within a reasonable time",
      "Yes — a counter-offer merely suspends the original offer until withdrawn",
      "No — Tom's counter-offer of £8,500 terminated the original offer, so there was nothing left to accept",
      "No — acceptance of an offer to sell a vehicle must be in writing",
    ],
    correct: 2,
    explanation:
      "A counter-offer kills the original offer — Hyde v Wrench. Tom's £8,500 reply destroyed the £10,000 offer, so his later 'acceptance' was really a new offer Selma could refuse. Traps: thinking the counter-offer merely 'suspends' the original, and inventing writing requirements — simple contracts for goods need no particular form. Contrast a mere request for information (Stevenson v McLean), which does NOT destroy the offer.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "LW2-B-04",
    paper: "LW",
    area: "B",
    type: "mcq",
    stem: "Hana posts an offer to sell equipment to Blake, stating that he may reply by post. Blake posts his acceptance on Monday. On Wednesday, before the letter arrives, Hana sells the equipment to someone else. Blake's letter arrives on Thursday. When, if at all, was a contract formed with Blake?",
    options: [
      "Never — acceptance is effective only when the offeror actually receives it",
      "On Monday, when Blake posted the acceptance, even though it arrived later",
      "Never — Hana revoked the offer by selling to someone else before the letter arrived",
      "On Thursday, when the letter of acceptance was delivered",
    ],
    correct: 1,
    explanation:
      "Where post is a contemplated means of acceptance, the postal rule applies: acceptance is complete on POSTING — Adams v Lindsell. The contract formed Monday, so Wednesday's sale put Hana in breach. Traps: applying the receipt rule (that governs instantaneous communications), and treating an uncommunicated act (selling elsewhere) as revocation — revocation is effective only when it reaches the offeree before acceptance.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "LW2-B-05",
    paper: "LW",
    area: "B",
    type: "mcq",
    stem: "Rana telephones the offeror to accept an offer, but the line drops mid-sentence and the offeror hears nothing. Rana does nothing further, believing that 'acceptance takes effect when it is sent'. Is there a contract?",
    options: [
      "Yes — a contract formed the moment Rana spoke the words of acceptance",
      "Yes — the offeror's subsequent silence amounts to acceptance",
      "No — acceptance by telephone is never valid; acceptance must be written",
      "No — with instantaneous communications, acceptance takes effect only when it is actually received by the offeror",
    ],
    correct: 3,
    explanation:
      "The postal rule does NOT apply to instantaneous communications (telephone, telex, and by extension email): acceptance must actually be communicated — Entores v Miles Far East Corp. Rana knew the line failed and should have tried again. Traps: applying the postal 'effective when sent' rule to instantaneous media, and treating silence as acceptance — it cannot be (Felthouse v Bindley).",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "LW2-B-06",
    paper: "LW",
    area: "B",
    type: "mcq",
    stem: "On Monday, Gita offers her workshop to Femi, promising (without payment) to keep the offer open until Friday. On Wednesday she sells it to another buyer. On Thursday, Priti — a mutual business contact whom Femi knows to be reliable — tells Femi about the sale. On Friday, Femi purports to accept. Is there a contract with Femi?",
    options: [
      "Yes — a revocation is effective only if communicated by the offeror personally",
      "Yes — the promise to keep the offer open until Friday was binding on Gita",
      "No — Femi learned of the revocation from a reliable source before he accepted",
      "No — an offer can never be accepted on the last day of its stated period",
    ],
    correct: 2,
    explanation:
      "Revocation is effective once it reaches the offeree, even via a reliable third party — Dickinson v Dodds. And a bare promise to hold an offer open binds no one unless the offeree gives consideration for it (an option). Traps: insisting revocation must come from the offeror personally, and treating a gratuitous 'firm offer' as binding — without consideration it is not.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "LW2-B-07",
    paper: "LW",
    area: "B",
    type: "mcq",
    stem: "While her neighbour is away, Amara voluntarily repairs his storm-damaged fence. On returning, the grateful neighbour promises her £100 'for what you did', but never pays. Can Amara enforce the promise?",
    options: [
      "No — her work was past consideration, which is no consideration for the later promise",
      "No — £100 is too small an amount to count as consideration",
      "Yes — consideration need not be adequate, so the promise binds",
      "Yes — promises made in gratitude are always enforceable",
    ],
    correct: 0,
    explanation:
      "Consideration must be given in return for the promise; an act already completed before the promise is PAST consideration and cannot support it — Re McArdle. Traps: reaching for 'sufficiency not adequacy' (that rule governs the VALUE of consideration, not its timing), and its mirror image — thinking small sums fail for inadequacy. Note the narrow exception where the act was done at the promisor's request with payment understood (Lampleigh v Braithwait).",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "LW2-B-08",
    paper: "LW",
    area: "B",
    type: "mcq",
    stem: "A main contractor, at risk of a late-completion penalty to its client, freely promises its joinery subcontractor an extra £8,000 to finish the existing agreed work on time. The subcontractor finishes on time; the contractor avoids the penalty but refuses the extra payment. Is the promise enforceable?",
    options: [
      "No — performing an existing contractual duty can never amount to consideration",
      "Yes — the contractor obtained a practical benefit and the promise was not extracted by duress",
      "No — a variation of a construction contract must be in writing",
      "Yes, but only if the promise was executed as a deed",
    ],
    correct: 1,
    explanation:
      "Williams v Roffey Bros: where a promise of extra payment for performing an existing duty confers a practical benefit on the promisor (here, avoiding the penalty) and is not obtained by economic duress, it is supported by consideration. The trap is applying Stilk v Myrick as an absolute bar — Roffey qualified it. No writing or deed is needed for a supported promise.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "LW2-B-09",
    paper: "LW",
    area: "B",
    type: "mcq",
    stem: "Zoe is owed £10,000 by a customer. Facing his pleas of hardship, she agrees in a signed letter to accept £6,000 'in full and final settlement'. He pays the £6,000 on the original due date, at the original place, in cash. May Zoe later sue for the £4,000 balance?",
    options: [
      "No — the signed agreement to accept less is itself a binding contract",
      "No — accepting any part payment automatically discharges the whole debt",
      "Yes, but only if she first returns the £6,000",
      "Yes — part payment of a debt is not consideration for a promise to forgo the balance",
    ],
    correct: 3,
    explanation:
      "Under the rule in Pinnel's Case, confirmed in Foakes v Beer, paying less than is due, as and when due, gives the creditor nothing new — so her promise to take less is unsupported by consideration and she may claim the balance. Traps: thinking a signed settlement needs no consideration, or that part payment discharges the debt. It would differ if he paid early, elsewhere, or added something — or if promissory estoppel applied.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "LW2-B-10",
    paper: "LW",
    area: "B",
    type: "mcq",
    stem: "Two companies, whose managing directors are old friends, sign a distribution agreement. When sued on it, one argues there was no intention to create legal relations because of the friendship. In a commercial agreement of this kind:",
    options: [
      "There is no contract unless intention is expressly recited in the document",
      "Intention is presumed absent — commercial parties must prove they meant to be bound",
      "Intention to be bound is presumed, and is rebutted only by clear words such as an 'honour clause'",
      "The domestic presumption applies because the individuals are friends",
    ],
    correct: 2,
    explanation:
      "Commercial agreements carry a strong presumption of intention to create legal relations, rebuttable only by clear words — e.g. the 'binding in honour only' clause in Rose & Frank v Crompton. The domestic presumption (no intention, Balfour v Balfour) applies to social/family arrangements between the PARTIES, not to companies whose directors happen to be friends.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "LW2-B-11",
    paper: "LW",
    area: "B",
    type: "mcq",
    stem: "An actor engaged for a twelve-week theatre season fails, without excuse, to appear for the entire opening week of performances. The producer wishes to end the engagement and hire a replacement. The actor's obligation to perform is best classified as:",
    options: [
      "A condition — its breach goes to the root of the contract, so the producer may terminate and claim damages",
      "A warranty — the producer may claim damages but must keep the actor on",
      "No breach at all — the contract was frustrated by his absence",
      "An anticipatory breach which the producer must ignore until the season ends",
    ],
    correct: 0,
    explanation:
      "Missing the performances themselves goes to the root of the contract — a breach of CONDITION, allowing termination plus damages, as in Poussard v Spiers (singer missing opening nights). Contrast Bettini v Gye, where missing only rehearsals breached a mere warranty (damages only). Frustration requires an outside event beyond the parties' control, not a party's own default; and a victim of breach need never wait — nor is this anticipatory, since performance was already due.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "LW2-B-12",
    paper: "LW",
    area: "B",
    type: "mcq",
    stem: "A charter contract states the vessel will be 'in every way fitted for ordinary cargo service'. Minor engine faults are found and repaired within a few days of a two-year charter; the charterer nonetheless purports to terminate. The most likely legal outcome is:",
    options: [
      "The term is a condition, so any breach of it, however trivial, justified termination",
      "The term is innominate: as the breach did not deprive the charterer of substantially the whole benefit of the contract, only damages are available",
      "The term is a warranty, so the contract ended automatically on breach",
      "The defects discharged the contract by frustration",
    ],
    correct: 1,
    explanation:
      "A broadly-worded seaworthiness undertaking is an INNOMINATE term — Hong Kong Fir Shipping v Kawasaki. The remedy depends on the gravity of the breach's consequences: only a breach depriving the innocent party of substantially the whole benefit justifies termination. Traps: forcing every term into condition/warranty; and remember breach never ends a contract 'automatically' — the innocent party must elect. Frustration needs a supervening outside event, not a defect at delivery.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "LW2-B-13",
    paper: "LW",
    area: "B",
    type: "mcq",
    stem: "A guest checks in and pays at a hotel reception desk. In her bedroom she later finds a notice: 'The hotel accepts no liability for property lost or stolen from rooms.' Her laptop is stolen through the hotel's negligence. Can the hotel rely on the notice?",
    options: [
      "Yes — the notice was displayed prominently in the room",
      "Yes — guests are deemed to accept a hotel's standard terms",
      "No — the notice was not incorporated, because it came to her attention only after the contract was made at reception",
      "No — but only because she never signed the notice",
    ],
    correct: 2,
    explanation:
      "An exclusion clause binds only if incorporated BEFORE or AT the time of contracting. The contract formed at reception; the bedroom notice came too late — Olley v Marlborough Court. Traps: thinking prominence cures late notice (reasonable notice matters, but timing comes first), and thinking a signature is essential — unsigned terms can be incorporated by timely notice, and signed documents bind even unread (L'Estrange v Graucob).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "LW2-B-14",
    paper: "LW",
    area: "B",
    type: "mcq",
    stem: "A contract between two businesses contains a clause: 'The warehouse operator excludes all liability for death, personal injury or damage to goods, howsoever caused, including negligence.' Under the Unfair Contract Terms Act 1977:",
    options: [
      "The whole clause is valid because both parties are businesses",
      "The clause is fully valid if it was individually negotiated",
      "The whole clause is automatically void, including as to damage to goods",
      "The exclusion of liability for death and personal injury caused by negligence is void; the exclusion for damage to goods stands only if it satisfies the reasonableness test",
    ],
    correct: 3,
    explanation:
      "UCTA 1977 s2(1): liability for death or personal injury resulting from negligence can NEVER be excluded. Other loss or damage from negligence (s2(2)) can be excluded only so far as the clause is reasonable. Traps: assuming B2B contracts escape UCTA entirely (UCTA is precisely the B2B regime — consumers now have the CRA 2015), and striking down the whole clause — the property-damage limb survives if reasonable.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "LW2-B-15",
    paper: "LW",
    area: "B",
    type: "mcq",
    stem: "An events company hires a historic hall for a gala. A week before the event, the hall is destroyed by an accidental electrical fire that is nobody's fault. What is the effect on the contract?",
    options: [
      "It is discharged by frustration — both parties are excused from further performance",
      "The hall's owner is liable in damages for breach because performance became impossible",
      "The contract continues and the hirer must still pay the full hire fee",
      "The contract is void ab initio for common mistake",
    ],
    correct: 0,
    explanation:
      "A supervening event, without fault of either party, that destroys the subject matter frustrates the contract — Taylor v Caldwell (the burnt music hall). Both sides are discharged from future obligations (with financial adjustment under the Law Reform (Frustrated Contracts) Act 1943). Traps: calling faultless impossibility a 'breach', and confusing frustration (event AFTER formation) with common mistake (facts wrong AT formation).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "LW2-B-16",
    paper: "LW",
    area: "B",
    type: "mcq",
    stem: "A courier is late delivering a replacement drive shaft to a mill, which stands idle for a week. The mill loses (i) its ordinary operating profit for the week and (ii) an exceptionally lucrative government contract it had never mentioned to the courier. The mill may recover:",
    options: [
      "Nothing — economic losses are never recoverable in contract",
      "The ordinary lost profit, but not the exceptional contract it never told the courier about",
      "All of its losses, including the exceptional contract, because the courier factually caused them",
      "Only nominal damages, because the mill should simply have used a different courier",
    ],
    correct: 1,
    explanation:
      "Hadley v Baxendale: damages cover (1) losses arising naturally from the breach and (2) unusual losses only if the special circumstances were known to both parties when contracting. Ordinary downtime profit falls in limb 1; the undisclosed exceptional contract fails limb 2 (compare Victoria Laundry v Newman). Traps: 'caused it, so pays for it' ignores remoteness; and note the claimant must also mitigate — take reasonable steps to reduce loss — but mitigation does not reduce recovery to nil here.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "LW2-B-17",
    paper: "LW",
    area: "B",
    type: "mcq",
    stem: "A soprano walks out of her contract halfway through an opera run. The opera house asks the court for an order of specific performance compelling her to sing the remaining nights. The court will most likely:",
    options: [
      "Grant specific performance, because the loss from cancelled nights is hard to quantify",
      "Grant specific performance, because she is in deliberate breach",
      "Refuse it — the courts do not order specific performance of contracts for personal services",
      "Refuse it, leaving the opera house with no remedy at all",
    ],
    correct: 2,
    explanation:
      "Specific performance is an equitable, discretionary remedy granted only where damages are inadequate — and never to compel personal services, which would amount to forced labour and require constant supervision. The opera house still has damages (so 'no remedy' is wrong), and deliberateness of breach does not unlock the remedy. Contrast contracts for land, where each plot is unique and specific performance is routine.",
    marks: 2,
    difficulty: "medium",
  },

  /* ───────────── Area B — The law of obligations: tort ───────────── */
  {
    id: "LW2-B-18",
    paper: "LW",
    area: "B",
    type: "mcq",
    stem: "In a novel situation, the three-stage test from Caparo Industries v Dickman for whether a duty of care exists in negligence asks whether there is:",
    options: [
      "Foreseeability of harm, proximity between the parties, and fairness/justice/reasonableness in imposing a duty",
      "A duty of care, a breach of that duty, and resulting damage",
      "Proximity, but-for causation, and remoteness of damage",
      "Foreseeability of harm, breach of duty, and dishonest intent",
    ],
    correct: 0,
    explanation:
      "Caparo's three stages are foreseeability, proximity, and whether imposing a duty is fair, just and reasonable. The classic mix-up is reciting the elements of the whole TORT (duty, breach, damage) when asked about the duty stage alone; causation and remoteness belong to the damage inquiry, and dishonesty is irrelevant — negligence needs no intent.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "LW2-B-19",
    paper: "LW",
    area: "B",
    type: "mcq",
    stem: "A learner driver on her third lesson mounts the kerb and injures a pedestrian. In assessing breach of duty, she is judged against:",
    options: [
      "The standard of a careful learner driver, allowing for her inexperience",
      "The objective standard of a reasonably competent qualified driver",
      "No standard — learner drivers cannot be liable in negligence",
      "The standard of the most skilled professional driver available",
    ],
    correct: 1,
    explanation:
      "The standard of care is objective: a learner is held to the standard of a reasonably competent driver — Nettleship v Weston. The law does not lower the bar for inexperience (nor raise it to perfection). The nameable trap is subjectivising the standard ('she did her incompetent best'); doing one's best is no defence if it falls below the reasonable person's standard.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "LW2-B-20",
    paper: "LW",
    area: "B",
    type: "mcq",
    stem: "A hospital doctor negligently refuses to examine a patient who arrives seriously ill and sends him home. The patient dies hours later of a rare poisoning that no available treatment could have cured in time. A negligence claim for the death will most likely:",
    options: [
      "Succeed — the doctor's breach of duty is by itself enough for liability",
      "Succeed — hospitals are strictly liable for deaths on their premises",
      "Fail — casualty doctors owe no duty of care to unexamined patients",
      "Fail — the breach did not cause the death, because the patient would have died even with proper treatment",
    ],
    correct: 3,
    explanation:
      "Negligence requires the breach to CAUSE the loss: applying the but-for test, the patient would have died anyway, so causation fails — Barnett v Chelsea & Kensington Hospital, on which this is modelled. Traps: stopping the analysis at breach ('careless, therefore liable'), and inventing strict liability. A duty WAS owed (the hospital opened its doors to him) — the claim fails at causation, not duty.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "LW2-B-21",
    paper: "LW",
    area: "B",
    type: "mcq",
    stem: "A contractor negligently lets solvent leak into a dock. Expert evidence shows some pollution damage was foreseeable, but the solvent unexpectedly ignited, causing extensive fire damage of a kind no reasonable person would have foreseen. On remoteness in negligence, the contractor is liable for:",
    options: [
      "Only kinds of damage that were reasonably foreseeable — though not necessarily their full extent",
      "All damage directly caused by the leak, however unforeseeable in kind",
      "Only damage the contractor actually foresaw at the time",
      "Nothing — remoteness rules apply only in contract, not tort",
    ],
    correct: 0,
    explanation:
      "The Wagon Mound: in negligence, a defendant is liable only for damage of a reasonably foreseeable KIND; once the kind is foreseeable, the full extent need not be (and the 'eggshell skull' rule means you take your victim as found). Trap 1 is the old Re Polemis 'direct consequences' test, which Wagon Mound displaced. Trap 2 is making the test subjective — it asks what was reasonably foreseeable, not what the defendant actually foresaw.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "LW2-B-22",
    paper: "LW",
    area: "B",
    type: "mcq",
    stem: "A contractor negligently severs a power cable, cutting electricity to a metal works. Molten metal in the furnace at the time is ruined (and its profit lost), and the works also loses the profit on four further melts it simply could not process during the outage. In negligence, the works can recover:",
    options: [
      "All of the losses, because they all flowed from one negligent act",
      "The damage to the melt in progress and the profit on that melt, but not the profit on the melts it merely could not carry out",
      "Nothing, because financial losses are never recoverable in tort",
      "Only the profits on the four lost melts, as they are the larger loss",
    ],
    correct: 1,
    explanation:
      "Spartan Steel v Martin: physical damage and financial loss consequent on it are recoverable, but PURE economic loss (profit lost without any damage to the claimant's property) generally is not in negligence. Traps: 'one act, all losses' ignores the pure-economic-loss bar; conversely 'no economic loss ever' overstates it — loss consequent on physical damage IS recoverable. The Hedley Byrne misstatement route is the main exception, and it does not apply to careless acts like this.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "LW2-B-23",
    paper: "LW",
    area: "B",
    type: "mcq",
    stem: "A finance director asks her company's long-standing accountants whether a customer is creditworthy before extending it a large trade credit line. The accountants carelessly say yes, knowing exactly why she is asking; the customer collapses and the company loses the money. Can the company recover this purely financial loss from the accountants in tort?",
    options: [
      "No — pure economic loss can never be recovered in negligence",
      "No — liability for careless statements can arise only in contract",
      "Yes — a special relationship arose: the accountants assumed responsibility, knowing their advice would be relied on for a specific purpose",
      "Yes — anyone who ever relies on a professional's published advice may sue the author",
    ],
    correct: 2,
    explanation:
      "Hedley Byrne v Heller: a negligent misstatement causing pure economic loss is actionable where there is a special relationship — an assumption of responsibility by an adviser who knows the identity of the recipient, the purpose of the advice, and the likely reliance. Traps: over-applying the pure-economic-loss bar (misstatement is its key exception), and over-extending the duty to the world at large — Caparo v Dickman confines it to known recipients and purposes.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "LW2-B-24",
    paper: "LW",
    area: "B",
    type: "mcq",
    stem: "A tanker driver, while transferring petrol to underground tanks at a filling station, lights a cigarette and discards the match, causing an explosion. His employer had strictly forbidden smoking on duty. Is the employer vicariously liable for the damage?",
    options: [
      "No — smoking was for the driver's own comfort, not the employer's business",
      "No — the express prohibition took the act outside the employment",
      "The driver alone is liable, because employees always bear their own torts",
      "Yes — the driver was doing his job (delivering petrol), merely in a negligent and unauthorised manner",
    ],
    correct: 3,
    explanation:
      "An employer is vicariously liable for torts committed in the course of employment, including an authorised task done in an unauthorised or forbidden WAY — Century Insurance v NI Road Transport Board, the source of this scenario. Traps: treating a prohibition as automatically removing liability (it restricts the mode, not the sphere, of employment — compare Rose v Plenty), and confusing this with a 'frolic of his own', where the employee abandons the job entirely. The driver remains personally liable too, but the claimant may pursue the employer.",
    marks: 2,
    difficulty: "medium",
  },

  /* ───────────── Area C — Employment law ───────────── */
  {
    id: "LW2-C-01",
    paper: "LW",
    area: "C",
    type: "mcq",
    stem: "A tribunal is deciding whether Layla, a delivery rider, is an employee or an independent contractor. Which single factor points MOST strongly towards her being an employee?",
    options: [
      "The company controls when, where and precisely how she must perform the work",
      "She is paid gross, with no tax deducted at source",
      "She uses some of her own equipment",
      "She invoices the company monthly for her hours",
    ],
    correct: 0,
    explanation:
      "Under the multiple (economic reality) test from Ready Mixed Concrete v Minister of Pensions, control over how, when and where work is done is a core indicator of employment, alongside personal service and mutuality of obligation. Gross pay, own equipment and invoicing all point the OTHER way (self-employment) — the trap is picking a factor consistent with contractor status. No single label decides it, but control is the strongest employment pointer offered.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "LW2-C-02",
    paper: "LW",
    area: "C",
    type: "mcq",
    stem: "Omar's contract with a courier firm gives him an unrestricted right to send any qualified substitute to do his rounds, which he regularly exercises. In deciding his employment status, this points to Omar being:",
    options: [
      "An employee, because he works regular hours",
      "An employee, because tribunals ignore substitution clauses",
      "Self-employed, because he is highly paid",
      "Self-employed — an unrestricted right of substitution is inconsistent with the personal service an employment contract requires",
    ],
    correct: 3,
    explanation:
      "An employment contract requires personal service. A genuine, unrestricted (and actually used) right to send a substitute is inconsistent with employee status — Ready Mixed Concrete. Traps: tribunals ignore only SHAM substitution clauses that do not reflect reality, not genuine ones; and pay level or regular hours are weak factors that cannot outweigh the absence of personal service.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "LW2-C-03",
    paper: "LW",
    area: "C",
    type: "mcq",
    stem: "Nadia's contract entitles her to three months' notice. Her employer dismisses her on the spot, with no notice or payment in lieu, for a reason that is not gross misconduct. Her common-law claim is:",
    options: [
      "Unfair dismissal — any dismissal without notice is automatically unfair",
      "A redundancy payment claim",
      "Wrongful dismissal — a claim for damages for the unworked notice period",
      "Constructive dismissal — the dismissal was constructed by the employer",
    ],
    correct: 2,
    explanation:
      "Wrongful dismissal is the COMMON-LAW claim for dismissal in breach of contract — typically without proper notice — and damages are essentially the pay for the notice period. Traps: confusing it with UNFAIR dismissal, the separate statutory claim about the reason for and fairness of dismissal; and misusing 'constructive dismissal', which is where the EMPLOYEE resigns in response to the employer's repudiatory breach.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "LW2-C-04",
    paper: "LW",
    area: "C",
    type: "mcq",
    stem: "Which of the following is NOT capable of being a potentially fair reason for dismissal under the unfair dismissal legislation?",
    options: [
      "The employee's misconduct",
      "Redundancy",
      "A statutory restriction that makes continued employment unlawful",
      "The employee's membership of an independent trade union",
    ],
    correct: 3,
    explanation:
      "The potentially fair reasons are: capability/qualifications, conduct, redundancy, statutory illegality, and 'some other substantial reason'. Dismissal for trade union membership (like dismissal for pregnancy or whistleblowing) is AUTOMATICALLY UNFAIR — the opposite of a fair reason. The trap is assuming any business-related reason can be argued as fair: some reasons are excluded outright, whatever procedure was followed.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "LW2-C-05",
    paper: "LW",
    area: "C",
    type: "mcq",
    stem: "Without consultation or contractual right, an employer tells Priya her salary is being halved from next month. She resigns immediately and claims she was dismissed. Her best claim is:",
    options: [
      "Constructive dismissal — the employer committed a repudiatory breach entitling her to resign and treat herself as dismissed",
      "None — she resigned voluntarily, so there was no dismissal",
      "Wrongful dismissal only — constructive dismissal requires the employer to use the word 'dismissed'",
      "Redundancy — her role ceased to exist when she left",
    ],
    correct: 0,
    explanation:
      "Constructive dismissal arises where the employer commits a repudiatory breach (unilaterally halving pay is a textbook example) and the employee resigns promptly in response — Western Excavating v Sharp. Traps: treating any resignation as voluntary (the resignation IS the dismissal when it responds to repudiation, provided she does not delay and affirm), and thinking dismissal requires the employer's words. Redundancy is irrelevant — the job still exists.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "LW2-C-06",
    paper: "LW",
    area: "C",
    type: "mcq",
    stem: "A manufacturer permanently closes one of its two factories because orders have collapsed, and dismisses the staff who worked there. The dismissals are best characterised as:",
    options: [
      "Unfair dismissal, because the employees did nothing wrong",
      "Redundancy — the requirement for employees to do work of that kind at that place has ceased or diminished",
      "Constructive dismissal, because the employer took the decision alone",
      "Frustration of the employment contracts",
    ],
    correct: 1,
    explanation:
      "Redundancy covers business closure, closure of the employee's workplace, or a diminished requirement for employees to do work of a particular kind — a factory closure is the paradigm case, and it is a potentially fair reason for dismissal (with a statutory redundancy payment). Traps: equating 'blameless employee' with 'unfair dismissal' (redundancy is fair if genuine and fairly handled), and misusing constructive dismissal — no employee resigned in response to a breach here.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "LW2-C-07",
    paper: "LW",
    area: "C",
    type: "mcq",
    stem: "An employer catches a warehouse supervisor stealing high-value stock, and dismisses him on the spot without notice or payment in lieu. Is the dismissal WRONGFUL?",
    options: [
      "Yes — dismissal without notice is always a breach of contract",
      "Yes — gross misconduct permits dismissal only with a payment in lieu of notice",
      "No — gross misconduct is a repudiatory breach by the employee, entitling the employer to dismiss summarily without notice",
      "No — theft renders the employment contract void from the beginning",
    ],
    correct: 2,
    explanation:
      "Wrongful dismissal means dismissal in breach of contract. Gross misconduct (e.g. theft) is a repudiatory breach BY THE EMPLOYEE, which the employer may accept by summary dismissal — so no notice is due and the dismissal is not wrongful. Traps: 'no notice = wrongful' ignores the summary-dismissal exception; and the contract is not void ab initio — it is terminated for repudiation from that point. Note unfair dismissal is analysed separately: even a thief must get a fair procedure.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "LW2-C-08",
    paper: "LW",
    area: "C",
    type: "mcq",
    stem: "An employment tribunal upholds an employee's unfair dismissal claim. Which of the following is NOT a remedy the tribunal can award?",
    options: [
      "Reinstatement in the same job",
      "Re-engagement in a comparable role",
      "Compensation (a basic award plus a compensatory award)",
      "Punitive damages to punish the employer's conduct",
    ],
    correct: 3,
    explanation:
      "The unfair dismissal remedies are reinstatement, re-engagement, and compensation (basic award calculated like a redundancy payment, plus a compensatory award for actual loss). Tribunals do not award punitive damages — compensation is loss-based, not punishment. The trap is importing punitive/exemplary damages from other legal systems; they have no place in the unfair dismissal regime.",
    marks: 2,
    difficulty: "easy",
  },

  /* ───────────── Area D — Company law & corporate governance ───────────── */
  {
    id: "LW2-D-01",
    paper: "LW",
    area: "D",
    type: "mcq",
    stem: "The board of Kestrel Ltd allows Marcus to act as managing director for a year — signing deals and running operations — although he was never formally appointed to that role. He signs a supply contract that Kestrel now wants to escape, arguing he had no authority. Is Kestrel bound?",
    options: [
      "No — Marcus had no actual authority, and actual authority is all that matters",
      "Yes — the company held him out as managing director, giving him apparent authority on which the supplier relied",
      "Yes — every director automatically has unlimited authority to bind the company",
      "No — apparent authority can only be created by the agent's own statements about his role",
    ],
    correct: 1,
    explanation:
      "Freeman & Lockyer v Buckhurst Park Properties: where the principal (the board) represents, by words or conduct, that a person has authority, and a third party relies on that representation, the company is bound by the agent's APPARENT (ostensible) authority. Traps: stopping at actual authority — apparent authority binds despite its absence; and the representation must come from the PRINCIPAL — an agent cannot self-certify his own authority.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "LW2-D-02",
    paper: "LW",
    area: "D",
    type: "mcq",
    stem: "The partners of a vehicle-repair firm privately agree that only the senior partner may order parts. Ignoring this, a junior partner orders £4,000 of car parts from a supplier who knows nothing of the restriction. Is the firm bound to pay?",
    options: [
      "Yes — the order was of a kind within the usual course of the firm's business, and the supplier neither knew of the restriction nor doubted his authority",
      "No — the internal restriction removed the partner's authority as against everyone",
      "Yes, but only if all the partners unanimously ratify the order",
      "No — a partner is not an agent of the firm and cannot bind it",
    ],
    correct: 0,
    explanation:
      "Partnership Act 1890 s5: every partner is an agent of the firm, and acts done in carrying on business of the usual kind in the usual way bind the firm — UNLESS the partner had no authority AND the third party knew it (or did not know or believe he was a partner). Car parts are squarely usual business for a repair firm. Traps: thinking private internal limits bind innocent outsiders, and denying the statutory agency of partners altogether. Ratification is unnecessary where s5 already binds the firm.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "LW2-D-03",
    paper: "LW",
    area: "D",
    type: "mcq",
    stem: "Farah is admitted as a new partner to an established ordinary partnership that already owes substantial trade debts. As regards those existing debts, Farah is:",
    options: [
      "Liable for all the firm's debts whenever incurred, because partnership liability is unlimited",
      "Liable for pre-admission debts, but only up to the amount of capital she contributed",
      "Not liable for debts incurred before she became a partner, unless she agrees to assume them",
      "Not liable for any of the firm's debts, because incoming partners enjoy a two-year grace period",
    ],
    correct: 2,
    explanation:
      "Partnership Act 1890 s17: an incoming partner is not liable to creditors for anything done before she became a partner (though she can agree to take on old debts). 'Unlimited liability' describes the EXTENT of liability for debts incurred while a partner — the trap is stretching it backwards in time. The capital-contribution cap belongs to limited partners/LLP members, and the 'grace period' is invented. Note the mirror rule: a RETIRING partner stays liable for debts incurred before retirement.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "LW2-D-04",
    paper: "LW",
    area: "D",
    type: "mcq",
    stem: "Which of the following statements about a limited liability partnership (LLP) formed under the Limited Liability Partnerships Act 2000 is correct?",
    options: [
      "It is a body corporate with separate legal personality, and its members' liability is limited",
      "Its members are jointly liable without limit for its debts, like partners in an ordinary partnership",
      "It cannot sue or be sued in its own name",
      "It is exempt from filing accounts with the Registrar of Companies",
    ],
    correct: 0,
    explanation:
      "An LLP is a body corporate: it has separate legal personality, owns its own property, sues and is sued in its own name, and its members' liability is limited. The price of that limited liability is DISCLOSURE — LLPs must file accounts at Companies House, unlike ordinary partnerships. The trap is treating an LLP like an ordinary partnership with a new name: structurally it is far closer to a company (though taxed like a partnership).",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "LW2-D-05",
    paper: "LW",
    area: "D",
    type: "mcq",
    stem: "Ivo is the sole shareholder and sole director of Ivo Joinery Ltd, which owes a timber merchant £20,000 it cannot pay. The company was properly formed and run without fraud. The merchant sues Ivo personally for the debt. The claim will:",
    options: [
      "Succeed — a one-person company is legally the same person as its owner",
      "Succeed — shareholders impliedly guarantee their company's trade debts",
      "Fail — but only because the debt is below the threshold for personal claims",
      "Fail — the company is a separate legal person, so its debts are its own and not the shareholder's",
    ],
    correct: 3,
    explanation:
      "Salomon v Salomon & Co Ltd: a validly incorporated company — even one owned and run by a single person — is a legal person distinct from its members, and its creditors must look to the company. A member's exposure is limited to any amount unpaid on shares. Traps: the 'one-person company = the owner' fallacy that Salomon itself buried, and imagining shareholders guarantee company debts (they do so only if they actually sign a personal guarantee).",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "LW2-D-06",
    paper: "LW",
    area: "D",
    type: "mcq",
    stem: "Hugo is bound by a valid covenant not to solicit his former employer's customers. He immediately forms Hugo Sales Ltd, owned by his wife on paper but run by him, and uses it to solicit those very customers. If the former employer sues, the court is most likely to:",
    options: [
      "Refuse to intervene — separate corporate personality is absolute in all circumstances",
      "Grant relief against both Hugo and the company — the company was interposed as a mere façade to evade Hugo's existing obligation",
      "Order the company to be dissolved automatically",
      "Hold the covenant void, since restraints of trade are always unenforceable",
    ],
    correct: 1,
    explanation:
      "Gilford Motor Co v Horne: where a company is a mere façade or device to evade an existing legal obligation, the court may pierce the veil (analysed in Prest v Petrodel as the narrow 'evasion' principle) and grant an injunction against both the individual and the company. Traps: treating Salomon as absolute — evasion by sham is the recognised exception; and over-reading restraint of trade — reasonable covenants protecting legitimate interests are enforceable. Courts restrain the abuse; they do not 'automatically dissolve' companies.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "LW2-D-07",
    paper: "LW",
    area: "D",
    type: "mcq",
    stem: "Aster plc has just been registered as a public company. Before it may lawfully commence business or borrow, it must obtain:",
    options: [
      "A listing on the London Stock Exchange",
      "A register of at least 50 shareholders",
      "A trading certificate from the Registrar, confirming its allotted share capital is at least the £50,000 authorised minimum",
      "Unanimous shareholder approval of its business plan",
    ],
    correct: 2,
    explanation:
      "A newly registered plc cannot trade or borrow until the Registrar issues a trading certificate (CA 2006 s761), confirming allotted share capital of at least the £50,000 authorised minimum (at least one-quarter paid up plus any premium). Traps: confusing 'public company' with 'listed company' — a plc MAY offer shares to the public but need not be listed; there is no minimum number of shareholders; and shareholders do not approve business plans.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "LW2-D-08",
    paper: "LW",
    area: "D",
    type: "mcq",
    stem: "The articles of Brindle Ltd state that Rafiq shall be the company's solicitor for life. Rafiq is also a shareholder. When the board instructs a different firm, Rafiq sues the company relying on the articles. He will:",
    options: [
      "Lose — under s33 CA 2006 the articles bind the company and him only in his capacity as a MEMBER, not in his outside capacity as solicitor",
      "Win — the articles are a contract enforceable by every person named in them",
      "Win — because he is a member, he can enforce any provision the articles contain",
      "Lose — because articles of association are never contractual in effect",
    ],
    correct: 0,
    explanation:
      "Section 33 CA 2006 makes the articles a statutory contract between the company and its members — but only in respect of MEMBERSHIP rights (Hickman v Kent Sheep-Breeders). Rights conferred in an outsider capacity (solicitor, promoter, employee) are unenforceable via the articles: Eley v Positive Life, where the claimant, exactly like Rafiq, was ALSO a member and still lost — membership does not convert an outsider right into a membership right. The articles are certainly contractual — just limited in scope.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "LW2-D-09",
    paper: "LW",
    area: "D",
    type: "mcq",
    stem: "Before NovaTech Ltd is incorporated, its promoter Dara signs a contract with a supplier 'for and on behalf of NovaTech Ltd'. The company is incorporated a month later but refuses to honour the contract. Who, if anyone, is liable to the supplier?",
    options: [
      "The company — it became bound by ratifying the contract on incorporation",
      "No one — the contract is a nullity because the company did not exist",
      "The company alone, but only once the supplier re-invoices it after incorporation",
      "Dara personally — the company cannot ratify a pre-incorporation contract; only a fresh contract (novation) after incorporation can bind it",
    ],
    correct: 3,
    explanation:
      "Under CA 2006 s51 (reflecting Kelner v Baxter), a person who contracts for a company not yet formed is personally liable, subject to contrary agreement. A company cannot ratify a contract made before it existed — ratification requires the principal to have existed with capacity at the time. To move the obligation to the company, the parties must make a NEW contract (novation) after incorporation. The trap is 'ratify on incorporation' — legally impossible for a non-existent principal.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "LW2-D-10",
    paper: "LW",
    area: "D",
    type: "mcq",
    stem: "Sable Ltd made a healthy profit this year, but has larger accumulated realised losses brought forward. It also carries a large unrealised surplus from revaluing its warehouse. May it lawfully pay a cash dividend?",
    options: [
      "Yes — a dividend may be paid whenever the current year is profitable",
      "No — dividends may be paid only out of accumulated REALISED profits less accumulated realised losses, which here are negative",
      "Yes — the revaluation surplus is a reserve available for distribution",
      "No — private limited companies are not permitted to pay dividends",
    ],
    correct: 1,
    explanation:
      "CA 2006 s830: distributions may only be made out of accumulated realised profits less accumulated realised losses. One good year cannot outweigh larger brought-forward realised losses, and an UNREALISED revaluation surplus is not distributable as a cash dividend. Traps: the 'current-year profit is enough' fallacy, and treating unrealised reserves as distributable. (Public companies face a further net-asset test under s831.)",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "LW2-D-11",
    paper: "LW",
    area: "D",
    type: "mcq",
    stem: "Wren Ltd, a private company, wishes to buy back shares from a retiring founder, but its distributable profits (plus any proceeds of a fresh share issue) fall short of the price. Can the buy-back lawfully proceed?",
    options: [
      "Yes — a private company may make a payment out of CAPITAL for the shortfall, supported by a directors' statement of solvency and a special resolution",
      "No — a company may never purchase its own shares in any circumstances",
      "Yes — a simple board resolution alone authorises a buy-back out of capital",
      "No — only a public company may use capital to buy back its own shares",
    ],
    correct: 0,
    explanation:
      "Buy-backs are normally funded from distributable profits or a fresh issue (capital maintenance), but a PRIVATE company may make a 'permissible capital payment' for the shortfall under CA 2006 — requiring a directors' statement of solvency (with auditor support), a special resolution, and publicity so creditors can object. Traps: the outdated blanket ban on own-share purchases; skipping the safeguards with a bare board decision; and inverting the rule — it is public companies that CANNOT use capital this way.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "LW2-D-12",
    paper: "LW",
    area: "D",
    type: "mcq",
    stem: "To secure a loan, Hollis Trading Ltd grants its bank a charge over 'all present and future stock-in-trade', expressly remaining free to buy and sell stock in the ordinary course of business. This charge is best classified as:",
    options: [
      "A fixed charge, because it is created by a written debenture",
      "A fixed charge, because stock is tangible property",
      "A floating charge — it hovers over a changing class of assets which the company may deal with until the charge crystallises",
      "A legal mortgage over the company's premises",
    ],
    correct: 2,
    explanation:
      "A floating charge has the classic three features (Re Yorkshire Woolcombers): it covers a class of present and future assets, the class changes in the ordinary course of business, and the company remains free to deal with the assets until crystallisation (e.g. on liquidation or default). Traps: classifying by document type or by whether the asset is tangible — what matters is the freedom to deal. Priority note: a fixed charge ranks ahead of a floating charge, and floating-charge realisations are subject to preferential creditors and the prescribed part.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "LW2-D-13",
    paper: "LW",
    area: "D",
    type: "mcq",
    stem: "The board of Delta Ltd is voting on buying a warehouse. Director Sam knows the seller is a company wholly owned by his wife, but says nothing and votes in favour. Which duty under the Companies Act 2006 has Sam most clearly breached?",
    options: [
      "None — the interest belongs to his wife, not to him",
      "The s177 duty to declare the nature and extent of his interest in a proposed transaction with the company",
      "Only the s174 duty to exercise reasonable care, skill and diligence",
      "None, provided the warehouse was bought at a fair market price",
    ],
    correct: 1,
    explanation:
      "CA 2006 s177 requires a director to declare the nature and extent of any direct OR INDIRECT interest in a proposed transaction with the company before it is entered into — an interest through a spouse's company is a classic indirect interest. Traps: 'it's my wife's interest, not mine' (connected-person interests count), reframing a disclosure breach as mere carelessness under s174, and the 'fair price' defence — the duty is to DISCLOSE, and a fair price does not cure silence.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "LW2-D-14",
    paper: "LW",
    area: "D",
    type: "mcq",
    stem: "Under s172 of the Companies Act 2006, a director's core duty is to:",
    options: [
      "Act in the way they consider, in good faith, would be most likely to promote the success of the company for the benefit of its members as a whole, having regard to wider factors such as employees, suppliers and the environment",
      "Maximise the current year's dividend above all other considerations",
      "Act primarily in the interests of the company's employees",
      "Guarantee that every decision they take benefits the company's creditors",
    ],
    correct: 0,
    explanation:
      "Section 172 is a subjective, good-faith duty to promote the company's success for the benefit of the MEMBERS as a whole, while having regard to the listed factors (long term, employees, suppliers/customers, community and environment, reputation, fairness between members). Traps: reducing it to short-term dividend maximisation; promoting the 'have regard' factors (like employees) into the primary beneficiaries; and creditors — their interests take priority only as insolvency approaches, not in every decision.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "LW2-D-15",
    paper: "LW",
    area: "D",
    type: "mcq",
    stem: "Mira holds 20% of a small quasi-partnership company. The majority remove her as director, stop all dividends, and pay themselves large salaries instead. Her most appropriate course of action is to:",
    options: [
      "Petition to wind the company up — the only remedy available to an aggrieved minority",
      "Sue the directors personally for damages for 'unfair prejudice'",
      "Bring a derivative claim in her own name to recover her own losses",
      "Petition under s994 CA 2006 for unfair prejudice; the usual order is that the majority (or the company) buy her shares at a fair value",
    ],
    correct: 3,
    explanation:
      "Exclusion from management plus diversion of profits in a quasi-partnership is the paradigm s994 unfair prejudice petition, and the court's usual order is a purchase of the petitioner's shares at a fair value. Traps: just-and-equitable winding up exists but is a drastic last resort, not 'the only remedy'; s994 relief is an order about the COMPANY'S affairs, not personal damages against directors; and a derivative claim vindicates the COMPANY'S loss in the company's name — the wrong vehicle for personal minority prejudice.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "LW2-D-16",
    paper: "LW",
    area: "D",
    type: "mcq",
    stem: "The directors of Quayside Ltd, honestly hoping for a turnaround, keep trading for a year after the point when they should have realised there was no reasonable prospect of avoiding insolvent liquidation, and creditor losses deepen. In the ensuing liquidation, their most likely exposure is:",
    options: [
      "Fraudulent trading, because the company kept incurring debts it could not pay",
      "Wrongful trading — no dishonesty is required; it is enough that they ought to have concluded insolvent liquidation was unavoidable and failed to take every step to minimise creditor losses",
      "None — limited liability protects directors from all personal claims",
      "The criminal offence of insider dealing",
    ],
    correct: 1,
    explanation:
      "Wrongful trading (Insolvency Act 1986 s214) is a CIVIL liability requiring no dishonesty: directors may be ordered to contribute to the company's assets if they continued past the point of no return without taking every step to minimise creditor losses. Fraudulent trading (s213; also a crime under CA 2006 s993) requires actual DISHONEST intent to defraud — absent here, since they honestly hoped to recover. Traps: confusing the two, and hiding behind limited liability, which protects MEMBERS as such, not directors from their own statutory liability.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "LW2-D-17",
    paper: "LW",
    area: "D",
    type: "mcq",
    stem: "A fundamentally viable company is in temporary cash-flow difficulty and is being pressed by creditors. Which insolvency procedure is designed, as its FIRST objective, to rescue the company as a going concern, protected by a statutory moratorium on creditor actions?",
    options: [
      "Administration",
      "Compulsory liquidation",
      "Members' voluntary liquidation",
      "Striking off the register",
    ],
    correct: 0,
    explanation:
      "Administration's statutory purpose hierarchy starts with rescuing the company as a going concern, and the moratorium freezes creditor actions to give the administrator breathing space. Traps: liquidation (compulsory or voluntary) is terminal — assets are realised, distributed, and the company dissolved, not rescued; a MEMBERS' voluntary liquidation is available only to SOLVENT companies whose directors make a declaration of solvency; and striking off simply removes a company from the register — it rescues nothing.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "LW2-D-18",
    paper: "LW",
    area: "D",
    type: "mcq",
    stem: "In which order do the three classic stages of money laundering occur?",
    options: [
      "Integration, placement, layering",
      "Layering, integration, placement",
      "Placement, layering, integration",
      "Placement, integration, layering",
    ],
    correct: 2,
    explanation:
      "Placement first introduces the criminal cash into the financial system (e.g. bank deposits through a cash business); layering then obscures its origin through chains of transfers and transactions; integration finally returns the funds to the launderer as apparently legitimate wealth (e.g. property purchases). The trap is any ordering that puts integration before the money has been placed and disguised — integration is by definition the final step.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "LW2-D-19",
    paper: "LW",
    area: "D",
    type: "mcq",
    stem: "Tara, a finance manager at a listed plc, learns through her job that an unannounced takeover bid for her employer is imminent. Before the announcement, she buys shares in the company through her broker and profits when the bid becomes public. Tara has most likely committed:",
    options: [
      "No offence — she invested her own money at her own risk",
      "A civil regulatory breach only, which can never be prosecuted criminally",
      "An offence only if she also tipped off another person",
      "The criminal offence of insider dealing — dealing in price-affected securities while in possession of inside information obtained as an insider",
    ],
    correct: 3,
    explanation:
      "Under the Criminal Justice Act 1993 Part V, an individual who has inside information as an insider (e.g. through her employment) and deals in price-affected securities commits the criminal offence of insider dealing. Traps: 'own money, own risk' is irrelevant — the wrong is exploiting unpublished price-sensitive information; the CJA offence is CRIMINAL (imprisonable), not merely regulatory; and dealing is itself an offence — encouraging another to deal and disclosing the information are separate additional offences, not prerequisites.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "LW2-D-20",
    paper: "LW",
    area: "D",
    type: "mcq",
    stem: "A sales agent engaged by Vireo Ltd pays a customer's procurement manager £5,000 to steer a contract to Vireo. Vireo's board knew nothing of the payment, and the company has no anti-bribery policies or training of any kind. Under the Bribery Act 2010, Vireo Ltd:",
    options: [
      "Is liable only if the board expressly authorised the bribe",
      "May be guilty of the s7 corporate offence of failing to prevent bribery by an associated person; having ADEQUATE PROCEDURES in place would have been a complete defence",
      "Cannot be liable — only the individual agent can ever be prosecuted",
      "Is not liable because bribery offences apply only to foreign public officials",
    ],
    correct: 1,
    explanation:
      "Bribery Act 2010 s7 makes a commercial organisation strictly liable when an associated person (employee OR agent) bribes another to obtain business for it — no board knowledge or authorisation is needed. The only defence is proving the organisation had ADEQUATE PROCEDURES to prevent bribery, which Vireo plainly lacked. Traps: requiring board complicity (that is the older identification doctrine s7 was designed to bypass); and confining bribery to foreign public officials — that is the separate s6 offence, alongside the general s1 (bribing) and s2 (being bribed) offences.",
    marks: 2,
    difficulty: "medium",
  },
]
