import type { TopicBrief } from "@/lib/acca-briefs"
import { SBR_BRIEFS } from "@/lib/acca-briefs-sbr"

const old = (area: string) => SBR_BRIEFS.find((item) => item.paper === "SBR" && item.area === area)!
const make = (area: string, title: string, concept: string, structure: string, example: string, traps: string): TopicBrief => ({ paper: "SBR", area, title, minutes: 6, sections: [{ kind: "concept", heading: "Reporting lens", body: concept }, { kind: "structure", heading: "Response structure", body: structure }, { kind: "example", heading: "Applied scenario", body: example }, { kind: "traps", heading: "Common failures", body: traps }] })

export const SBR_OFFICIAL_BRIEFS: TopicBrief[] = [
  make("A", "Fundamental ethical and professional principles", "Ethical corporate reporting requires integrity, objectivity, competence and due care under pressure. Evaluate both the reporting judgement and the consequences for stewardship, users and the public interest.", "Identify pressure and ethical threats.\nApply the reporting requirement and economic substance.\nEvaluate bias and stakeholder consequences.\nRecommend documentation, challenge and escalation.", "Management wants a material impairment indicator omitted to preserve bonuses. Challenge the estimate, document evidence, refuse misleading reporting and escalate through governance channels.", "Listing principles without applying facts.\nTreating technical compliance as sufficient.\nIgnoring consequences and escalation."),
  { ...old("A"), area: "B", title: "The financial reporting framework" },
  make("C", "Reporting financial performance", "Apply professional judgement to recognition, measurement, presentation and disclosure across transactions, including revenue, assets, instruments, leases, benefits, tax, provisions and fair value.", "Identify the relevant economic rights and obligations.\nApply recognition and measurement.\nCalculate the statement effect.\nEvaluate presentation, disclosure and user consequences.", "For a complex contract, identify performance obligations and timing before calculating revenue; then explain the effect on profit, assets and investor interpretation.", "Quoting a standard without application.\nIgnoring estimates and uncertainty.\nStopping at a journal entry."),
  { ...old("C"), area: "D", title: "Financial statements of groups of entities" },
  make("E", "Interpret financial and non-financial information", "Interpretation starts with the stakeholder and business model, adjusts for accounting choices and group boundaries, and evaluates earnings quality, segments, commentary and sustainability information.", "Define stakeholder decision.\nEstablish context and comparability.\nCalculate relevant indicators.\nExplain causes, limitations and non-financial evidence.\nReach a supported conclusion.", "A revaluation lowers both ROCE and gearing without changing cash. Explain the policy distortion before judging performance or risk.", "Producing ratios without interpretation.\nIgnoring accounting-policy effects.\nTreating non-financial disclosure as decoration."),
  make("F", "Changes and potential changes in regulation", "Evaluate how new standards and contemporary issues change recognition, measurement or disclosure and whether information becomes more useful. Apply IFRS S1/S2 and distinguish the ISSB investor lens from ESRS double materiality.", "Identify the reporting issue and affected users.\nApply existing or new requirements.\nEvaluate benefits, costs, uncertainty and comparability.\nExplain connectivity with financial statements.", "For climate risk, connect governance and scenario disclosures to useful life, impairment, provisions and investor assessment of future cash flows.", "Describing developments without evaluation.\nTreating sustainability reports as disconnected.\nClaiming ISSB and ESRS are identical."),
  make("G", "Employability and technology skills", "Use the digital workspace to find, validate, manipulate and present evidence efficiently. Technical quality includes traceable calculations and a response designed for its stakeholder.", "Map stakeholder, verb, output and exhibits.\nValidate dates, units and definitions.\nPrepare labelled linked workings.\nReconcile totals.\nPresent effects, uncertainty and advice.", "Where acquisition dates conflict, verify the basis, show controlled assumptions, adjust the consolidated statement and explain investor consequences.", "Random exhibit reading.\nHard-coded unexplained totals.\nGeneric essays and unstated uncertainty."),
]
