import type { AccaQuestion } from "@/lib/acca-content"

/*
 * TX-UK bank wave 3a — areas A+B, 68 verified originals (FA2024/25 basis, 2026-07-10).
 *
 * Tax basis (UK FA2024/25-style figures, always restated in the stem where a
 * threshold matters so questions test METHOD, not memorised numbers):
 *   - Personal allowance £12,570, tapered £1 per £2 of adjusted net income over £100,000
 *   - Basic rate band £37,700; rates 20% / 40% / 45%
 *   - Savings starting rate band £5,000 at 0%; personal savings allowance £1,000 / £500
 *   - Dividend allowance £500; dividend rates 8.75% / 33.75% / 39.35%
 *   - Official rate of interest 2.25%; car fuel benefit base £27,800
 *   - AIA £1,000,000; WDA 18% main pool / 6% special rate; new zero-emission cars 100% FYA
 *   - NIC: Class 1 primary 8% (£12,570–£50,270) then 2%; secondary 13.8% above £9,100;
 *     Class 1A 13.8%; Class 4 6% (£12,570–£50,270) then 2%; compulsory Class 2 abolished
 *   - CGT annual exempt amount £3,000; shares/other gains 10%/20%, residential 18%/24%;
 *     BADR 10% with £1,000,000 lifetime limit; chattels £6,000 rule with 5/3 cap
 *
 * Every question is ORIGINAL (aligned to the public syllabus only) and every
 * distractor encodes a nameable student error, spelled out in the explanation.
 */

export const TX_WAVE2A: AccaQuestion[] = [
  /* ───────────── Area A — Income tax & NIC ───────────── */
  /* Employment income & benefits */
  {
    id: "TX2-A-01", paper: "TX", area: "A", type: "number",
    stem: "Amara is provided with a company car for the whole of 2024/25. The car has a list price of £30,000 and the relevant CO2-based benefit percentage is 25%. Amara made a capital contribution of £4,000 towards the cost of the car when it was first provided. What is her car benefit for 2024/25 in £?",
    numericAnswer: 6500,
    unit: "£",
    explanation: "Capital contributions (capped at £5,000) reduce the LIST PRICE, and £4,000 is within the cap: (£30,000 − £4,000) × 25% = £6,500. Answering £7,500 ignores the contribution entirely; deducting the £4,000 from the computed benefit instead of the list price (£7,500 − £4,000 = £3,500) is the other classic error.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-A-02", paper: "TX", area: "A", type: "number",
    stem: "Ben was first provided with a company car on 6 August 2024, so it was available to him for exactly eight months of 2024/25. The car has a list price of £24,000 and a benefit percentage of 30%. What is Ben's car benefit for 2024/25 in £?",
    numericAnswer: 4800,
    unit: "£",
    explanation: "The benefit is time-apportioned for the period the car was unavailable: £24,000 × 30% × 8/12 = £4,800. Answering £7,200 means the time apportionment was forgotten.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-A-03", paper: "TX", area: "A", type: "mcq",
    stem: "Carla has a company car (benefit percentage 20%) and her employer pays for ALL her fuel, including private fuel, throughout 2024/25. Assume a fuel benefit base figure of £27,800. Carla reimbursed her employer £600, covering roughly half of her private fuel. What is her fuel benefit for 2024/25?",
    options: ["£4,960", "£nil", "£5,560", "£6,160"],
    correct: 2,
    explanation: "Fuel benefit = £27,800 × 20% = £5,560. A PARTIAL reimbursement of private fuel gives NO reduction — only full reimbursement of all private fuel eliminates the benefit. £4,960 deducts the £600 (partial contributions do not reduce the fuel benefit, unlike the car benefit); £nil assumes any reimbursement removes the benefit; £6,160 wrongly adds the £600.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-A-04", paper: "TX", area: "A", type: "number",
    stem: "Dev's employer lent him £20,000 on 6 April 2024 and the loan was outstanding throughout 2024/25. Dev pays interest at 1% per annum. Assume an official rate of interest of 2.25%. What is Dev's taxable beneficial loan benefit for 2024/25 in £?",
    numericAnswer: 250,
    unit: "£",
    explanation: "The loan exceeds the £10,000 de minimis, so a benefit arises on the shortfall of interest paid below the official rate: £20,000 × (2.25% − 1%) = £250. Answering £450 (2.25% with no deduction) forgets the interest actually paid is deducted.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-A-05", paper: "TX", area: "A", type: "mcq",
    stem: "Elif's employer lent her £8,000 interest-free on 6 April 2024, and this was her only employer loan, outstanding throughout 2024/25. Assume an official rate of interest of 2.25%. What is her taxable benefit for 2024/25?",
    options: ["£180", "£nil", "£225", "£80"],
    correct: 1,
    explanation: "No taxable benefit arises where total employer loans never exceed £10,000 at any time in the year. £180 (£8,000 × 2.25%) ignores the £10,000 de minimis; £225 applies the official rate to the £10,000 limit itself; £80 applies an invented 1% rate.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-A-06", paper: "TX", area: "A", type: "number",
    stem: "Farid lives in a house provided by his employer throughout 2024/25 (not job-related). The house has an annual value of £4,000 and cost the employer £95,000 two years before it was first provided to Farid. Farid pays his employer rent of £1,000 a year. Assume an official rate of interest of 2.25% and an expensive-accommodation threshold of £75,000. What is Farid's total accommodation benefit for 2024/25 in £?",
    numericAnswer: 3450,
    unit: "£",
    explanation: "Basic charge = annual value £4,000. Additional (expensive accommodation) charge = (£95,000 − £75,000) × 2.25% = £450. Rent paid by the employee is deducted: £4,000 + £450 − £1,000 = £3,450. Common errors: forgetting the additional charge (£3,000) or applying 2.25% to the full £95,000 (£2,137 addition).",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-A-07", paper: "TX", area: "A", type: "mcq",
    stem: "Which of the following benefits provided by an employer to an employee is EXEMPT from income tax?",
    options: [
      "Private medical insurance",
      "Gym membership at a local gym paid for by the employer",
      "A company car available for private use",
      "One mobile phone provided for the employee's use",
    ],
    correct: 3,
    explanation: "One mobile phone per employee is a specifically exempt benefit. Private medical insurance is taxable (cost to employer), external gym membership is taxable (only on-site sports facilities are exempt), and private use of a company car is taxable under the CO2-based rules.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-A-08", paper: "TX", area: "A", type: "mcq",
    stem: "Under the trivial benefits exemption (benefit must cost £50 or less, not be cash or a cash voucher, and not be a reward for services), which of the following is EXEMPT?",
    options: [
      "Flowers costing £45 given to an employee on her birthday",
      "A hamper costing £60 given to an employee at Christmas",
      "A £45 store voucher given for hitting a sales target",
      "£40 in cash given to an employee as a small thank-you",
    ],
    correct: 0,
    explanation: "The £45 birthday flowers meet all three conditions. The £60 hamper fails the £50 cost limit (the WHOLE benefit is then taxable, not just the excess); the £45 voucher fails because it rewards services rendered; cash can never be a trivial benefit.",
    marks: 2, difficulty: "medium",
  },
  /* Trading profit adjustments */
  {
    id: "TX2-A-09", paper: "TX", area: "A", type: "number",
    stem: "Grace, a sole trader, has a net profit of £80,000 for the year after charging: depreciation £6,000; her own salary £20,000; staff entertaining £1,500; and gifts of food hampers to customers £800. Capital allowances for the year are £4,000. What is her tax-adjusted trading profit in £?",
    numericAnswer: 102800,
    unit: "£",
    explanation: "Add back depreciation £6,000, the owner's salary £20,000 (drawings, not an expense) and the customer hampers £800 (gifts of food are always disallowed). Staff entertaining is ALLOWABLE, so no adjustment. Then deduct capital allowances: £80,000 + £26,800 − £4,000 = £102,800. Adding back the £1,500 staff entertaining (giving £104,300) is the classic error.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-A-10", paper: "TX", area: "A", type: "mcq",
    stem: "In computing a sole trader's tax-adjusted trading profit, which of the following expenses is ALLOWABLE?",
    options: [
      "Entertaining customers at a hospitality event",
      "The proprietor's own drawings",
      "The cost of the annual staff party",
      "Legal fees on the purchase of new freehold premises",
    ],
    correct: 2,
    explanation: "Staff entertaining (including the annual party) is allowable for the business. Customer entertaining is specifically disallowed, drawings are an appropriation of profit not an expense, and legal fees on buying premises are capital in nature.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-A-11", paper: "TX", area: "A", type: "mcq",
    stem: "A trader makes gifts to customers during the year. Which of the following gifts is an ALLOWABLE deduction from trading profit?",
    options: [
      "Bottles of wine costing £20 each, carrying the business logo",
      "Desk diaries costing £35 each, carrying a conspicuous business logo",
      "Food hampers costing £45 each, carrying the business logo",
      "Watches costing £80 each, carrying the business logo",
    ],
    correct: 1,
    explanation: "Customer gifts are allowable only if they cost £50 or less per person per year, carry a conspicuous advertisement, and are NOT food, drink, tobacco or vouchers. The diaries meet every condition. The wine and hampers fail the food/drink test despite the logo and low cost; the watches exceed the £50 limit.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-A-12", paper: "TX", area: "A", type: "number",
    stem: "Hana, a sole trader, has a net profit per accounts of £50,000. During the year she took goods for her own use which cost £400 and would normally sell for £600 — no entry was made in the accounts. Motor expenses of £2,000 were charged in full, but 30% of her mileage was private. What is her tax-adjusted trading profit in £?",
    numericAnswer: 51200,
    unit: "£",
    explanation: "Goods for own use with no entry made are added back at full MARKET VALUE (£600), not cost. Private motoring is added back: £2,000 × 30% = £600. Adjusted profit = £50,000 + £600 + £600 = £51,200. Adding back only the £400 cost of the goods (£51,000) is the classic error.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-A-13", paper: "TX", area: "A", type: "mcq",
    stem: "Which of the following legal and professional fees is ALLOWABLE in computing trading profit?",
    options: [
      "Legal fees on the purchase of a freehold warehouse",
      "Architect's fees for designing an extension to the shop",
      "Legal fees on the grant of a new 20-year lease of premises",
      "Legal fees on the renewal of an existing 10-year lease of premises",
    ],
    correct: 3,
    explanation: "Fees for RENEWING a short lease (50 years or less) are allowable by concession. Fees on the GRANT of a new lease are capital and disallowed, as are fees connected with acquiring or improving capital assets (the warehouse purchase and the extension).",
    marks: 2, difficulty: "hard",
  },
  /* Capital allowances */
  {
    id: "TX2-A-14", paper: "TX", area: "A", type: "number",
    stem: "Iris prepares accounts for the year ended 5 April 2025. The main pool brought forward is £20,000, and during the year she bought machinery for £120,000. Assume an annual investment allowance of £1,000,000 and a main pool WDA of 18%. What are her maximum capital allowances for the year in £?",
    numericAnswer: 123600,
    unit: "£",
    explanation: "The machinery is fully covered by the AIA (£120,000 < £1,000,000). The brought-forward pool gets the WDA: £20,000 × 18% = £3,600. Total = £120,000 + £3,600 = £123,600. Applying 18% to the new machinery as well (£25,200 total) forgets the AIA.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-A-15", paper: "TX", area: "A", type: "number",
    stem: "Jack's business buys a second-hand car for £18,000 during its 12-month accounting period. The car has CO2 emissions of 45 g/km. Assume cars with emissions of 1–50 g/km join the main pool (WDA 18%) and cars over 50 g/km join the special rate pool (WDA 6%). What is the maximum capital allowance on the car for the period in £?",
    numericAnswer: 3240,
    unit: "£",
    explanation: "Cars NEVER qualify for the AIA. At 45 g/km the car joins the main pool: £18,000 × 18% = £3,240. Answering £18,000 claims AIA on a car; £1,080 (6%) puts it in the special rate pool despite emissions being 50 g/km or below.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-A-16", paper: "TX", area: "A", type: "number",
    stem: "During its 12-month period a business buys: machinery £80,000; a delivery van £25,000; and a car (CO2 30 g/km) £20,000. Assume an annual investment allowance of £1,000,000. What is the MAXIMUM amount on which the AIA can be claimed in £?",
    numericAnswer: 105000,
    unit: "£",
    explanation: "The AIA covers plant and machinery including vans, but never cars: £80,000 + £25,000 = £105,000. The low-emission car instead receives an 18% WDA in the main pool. Including the car (£125,000) is the classic error — low emissions do not make a car AIA-eligible.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-A-17", paper: "TX", area: "A", type: "number",
    stem: "Kofi's business prepares accounts for a NINE-month period. During the period it buys a car for £30,000 with CO2 emissions of 120 g/km. Assume cars over 50 g/km join the special rate pool with a WDA of 6% per annum. What is the maximum capital allowance on the car for the period in £?",
    numericAnswer: 1350,
    unit: "£",
    explanation: "The WDA is scaled for a short period: £30,000 × 6% × 9/12 = £1,350. Answering £1,800 forgets to time-apportion; £4,050 (18% × 9/12) uses the main pool rate despite the high emissions.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-A-18", paper: "TX", area: "A", type: "mcq",
    stem: "A business buys a NEW zero-emission (0 g/km) car for £40,000 during its 12-month accounting period. Assume new zero-emission cars qualify for a 100% first year allowance, the main pool WDA is 18% and the special rate WDA is 6%. What is the maximum allowance in the year of purchase?",
    options: ["£40,000", "£7,200", "£2,400", "£nil"],
    correct: 0,
    explanation: "New zero-emission cars qualify for a 100% first year allowance: £40,000. £7,200 (18%) treats it as an ordinary main pool car — that treatment applies to SECOND-HAND zero-emission cars; £2,400 (6%) puts it in the special rate pool; £nil confuses cars getting no AIA with getting no allowances at all.",
    marks: 2, difficulty: "medium",
  },
  /* Basis of assessment */
  {
    id: "TX2-A-19", paper: "TX", area: "A", type: "mcq",
    stem: "Under the tax year basis of assessment applying from 2024/25, Lena has traded for many years preparing accounts to 31 December. On what profits is she assessed for 2024/25?",
    options: [
      "The profits of the year ended 31 December 2024 (current year basis)",
      "9/12 of the year ended 31 December 2024 plus 3/12 of the year ended 31 December 2025",
      "The profits of the year ended 31 December 2025",
      "The 12 months to 5 April 2025, but only if she elects for this treatment",
    ],
    correct: 1,
    explanation: "The tax year basis assesses the profits ARISING in the tax year itself (6 April 2024 – 5 April 2025), apportioning accounting periods: 9/12 of YE 31.12.24 (April–December 2024) + 3/12 of YE 31.12.25 (January–March 2025). Option (a) is the abolished current year basis; the apportionment is automatic, not elective.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-A-20", paper: "TX", area: "A", type: "number",
    stem: "Milo starts to trade on 1 January 2025 and prepares his first accounts for the 12 months to 31 December 2025, showing a profit of £36,000 accruing evenly. Under the tax year basis (treating 31 March as equivalent to 5 April), what is his assessable trading profit for 2024/25 in £?",
    numericAnswer: 9000,
    unit: "£",
    explanation: "2024/25 assesses the profits arising from 1 January 2025 to 5 April 2025 — three months: £36,000 × 3/12 = £9,000. Assessing the full £36,000 confuses this with the old opening-year rules; £nil wrongly defers everything to 2025/26.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-A-21", paper: "TX", area: "A", type: "mcq",
    stem: "Nina begins trading as a sole trader on 1 February 2025. In which tax year is she FIRST assessed on her trading profits?",
    options: ["2023/24", "2025/26", "2024/25", "She may elect for either 2024/25 or 2025/26"],
    correct: 2,
    explanation: "The tax year 2024/25 runs from 6 April 2024 to 5 April 2025, so a trade starting on 1 February 2025 is first assessed in 2024/25 (on the profits arising up to 5 April 2025). There is no election to defer the first assessment.",
    marks: 2, difficulty: "easy",
  },
  /* Pensions */
  {
    id: "TX2-A-22", paper: "TX", area: "A", type: "number",
    stem: "Omar has taxable income (after his personal allowance) of £60,000, all non-savings income. During 2024/25 he paid £8,000 (net) into a personal pension scheme. Assume a basic rate band of £37,700 and rates of 20% and 40%. What is his income tax liability for 2024/25 in £?",
    numericAnswer: 14460,
    unit: "£",
    explanation: "A net contribution of £8,000 is grossed up: £8,000 × 100/80 = £10,000. The basic rate band is extended to £37,700 + £10,000 = £47,700. Tax: £47,700 × 20% = £9,540, plus (£60,000 − £47,700) × 40% = £4,920. Total £14,460. Extending the band by only the net £8,000 gives £14,860; ignoring the pension entirely gives £16,460.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-A-23", paper: "TX", area: "A", type: "mcq",
    stem: "In 2024/25 Priya has relevant earnings (trading profit) of £30,000 and dividend income of £50,000. What is the MAXIMUM gross personal pension contribution on which she can obtain tax relief? (Assume an annual allowance of £60,000.)",
    options: ["£30,000", "£80,000", "£60,000", "£3,600"],
    correct: 0,
    explanation: "Tax-relievable contributions are limited to the HIGHER of £3,600 and 100% of relevant earnings — here £30,000. Dividends are NOT relevant earnings, so £80,000 is wrong; £60,000 confuses the annual allowance (which caps total inputs before a charge) with the relief limit; £3,600 is only the floor for those with low or no earnings.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-A-24", paper: "TX", area: "A", type: "mcq",
    stem: "Quentin contributes to his employer's occupational pension scheme, which operates under 'net pay arrangements'. How does Quentin obtain tax relief on his contributions?",
    options: [
      "Basic rate relief is given at source and higher rate relief is claimed by extending the basic rate band",
      "Relief is given as a tax reducer at 20% of the contribution",
      "Relief must be claimed through his self-assessment tax return",
      "Contributions are deducted from gross pay before income tax is calculated under PAYE",
    ],
    correct: 3,
    explanation: "Under net pay arrangements, occupational contributions are deducted from gross salary BEFORE PAYE is applied, giving full relief at the employee's marginal rate automatically. Option (a) describes relief at source, which applies to PERSONAL pension schemes; pension relief is not a tax reducer, and no separate claim is needed.",
    marks: 2, difficulty: "easy",
  },
  /* NIC */
  {
    id: "TX2-A-25", paper: "TX", area: "A", type: "number",
    stem: "Rosa is employed at an annual salary of £55,270 for 2024/25. Assume employee (primary) Class 1 NIC is charged at 8% on earnings between £12,570 and £50,270, and 2% above £50,270. What is Rosa's Class 1 NIC for the year in £?",
    numericAnswer: 3116,
    unit: "£",
    explanation: "8% × (£50,270 − £12,570) = 8% × £37,700 = £3,016, plus 2% × (£55,270 − £50,270) = £100. Total £3,116. Charging 8% on the whole excess over £12,570 (£3,416) misses the 2% upper band; charging on the full salary from £nil (£4,422) misses the primary threshold.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-A-26", paper: "TX", area: "A", type: "number",
    stem: "Sam Ltd pays its only employee (a director) a salary of £29,100 for 2024/25, and the employment allowance is NOT available. Assume employer (secondary) Class 1 NIC is charged at 13.8% on earnings above £9,100. What is the employer's Class 1 NIC for the year in £?",
    numericAnswer: 2760,
    unit: "£",
    explanation: "13.8% × (£29,100 − £9,100) = 13.8% × £20,000 = £2,760. Using the employee threshold of £12,570 gives £2,281 — the secondary threshold (£9,100) is lower than the primary one; there is no upper limit for employer NIC.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-A-27", paper: "TX", area: "A", type: "number",
    stem: "In 2024/25 Tara's employer provides her with taxable benefits totalling £5,000. Assume Class 1A NIC is charged at 13.8%. How much Class 1A NIC is payable (by the employer) in £?",
    numericAnswer: 690,
    unit: "£",
    explanation: "Class 1A is payable by the EMPLOYER only, at 13.8% on taxable benefits: £5,000 × 13.8% = £690. Employees never pay NIC on benefits; using the employee rate of 8% (£400) confuses Class 1A with primary Class 1.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-A-28", paper: "TX", area: "A", type: "number",
    stem: "Umar is self-employed with a trading profit of £42,570 for 2024/25. Assume Class 4 NIC is charged at 6% on profits between £12,570 and £50,270, and 2% above £50,270. What is Umar's Class 4 NIC for the year in £?",
    numericAnswer: 1800,
    unit: "£",
    explanation: "Profits are below the upper limit, so: 6% × (£42,570 − £12,570) = 6% × £30,000 = £1,800. Charging 6% on the full £42,570 (£2,554) forgets the lower profits limit; using 8% (£2,400) applies the employee Class 1 rate.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-A-29", paper: "TX", area: "A", type: "mcq",
    stem: "Which statement about Class 2 NIC for 2024/25 is CORRECT?",
    options: [
      "Class 2 is charged at 6% of trading profits above £12,570",
      "Compulsory Class 2 has been abolished; traders with low profits may pay it voluntarily to protect benefit entitlement",
      "All self-employed traders must pay Class 2 at a flat weekly rate regardless of profits",
      "Class 2 is payable by the employer on behalf of the trader",
    ],
    correct: 1,
    explanation: "From 2024/25, self-employed traders no longer pay compulsory Class 2 (those with profits over the small profits threshold still get contributory benefit entitlement automatically); low-profit traders may pay Class 2 voluntarily. The 6% percentage charge is Class 4, not Class 2; the flat weekly compulsory charge is the abolished old rule; the self-employed have no employer.",
    marks: 2, difficulty: "easy",
  },
  /* Administration: self-assessment & PAYE (examiner-flagged weak spot) */
  {
    id: "TX2-A-30", paper: "TX", area: "A", type: "mcq",
    stem: "Vera will file her 2024/25 self-assessment tax return ONLINE. By what date must the return normally be submitted?",
    options: ["31 October 2025", "31 December 2025", "31 January 2026", "5 April 2026"],
    correct: 2,
    explanation: "Online returns are due by 31 January following the end of the tax year — 31 January 2026 for 2024/25. 31 October 2025 is the deadline for PAPER returns; the other dates have no filing significance.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-A-31", paper: "TX", area: "A", type: "mcq",
    stem: "Wei started receiving rental income for the first time in 2024/25. He has never completed a tax return and HMRC have not issued him a notice to file. By what date must Wei NOTIFY HMRC of his chargeability to income tax for 2024/25?",
    options: ["5 October 2025", "31 January 2026", "31 October 2025", "6 April 2025"],
    correct: 0,
    explanation: "A taxpayer with a new source of income must notify HMRC of chargeability within six months of the end of the tax year — by 5 October 2025. 31 January 2026 is the online filing/payment date (a common mix-up); 31 October 2025 is the paper filing deadline.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-A-32", paper: "TX", area: "A", type: "number",
    stem: "Xander's income tax and Class 4 NIC payable through self-assessment for 2023/24 (his 'relevant amount') was £8,000, none of it collected at source. What is the amount of EACH payment on account for 2024/25, due on 31 January 2025 and 31 July 2025, in £?",
    numericAnswer: 4000,
    unit: "£",
    explanation: "Each payment on account is 50% of the prior year's relevant amount: £8,000 × 50% = £4,000. Answering £8,000 pays the whole prior-year amount twice; POAs are never based on estimated current-year figures unless a claim to reduce is made.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-A-33", paper: "TX", area: "A", type: "number",
    stem: "Yara's 2024/25 liabilities are: income tax payable through self-assessment £10,000, Class 4 NIC £2,000 and capital gains tax £3,000. She made two payments on account of £4,500 each for 2024/25. What balancing payment is due on 31 January 2026 in £?",
    numericAnswer: 6000,
    unit: "£",
    explanation: "Payments on account cover income tax and Class 4 only: (£10,000 + £2,000) − £9,000 = £3,000. CGT is NEVER paid through POAs, so the full £3,000 is added to the balancing payment: £3,000 + £3,000 = £6,000. Deducting the POAs from the total including CGT gives £6,000 too — but netting POAs against CGT first and answering £3,000 misses that CGT falls due in full on 31 January.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-A-34", paper: "TX", area: "A", type: "mcq",
    stem: "Zack's 2024/25 online return was due on 31 January 2026 but he filed it on 15 February 2026. All his tax had already been paid on time. What late-filing penalty is charged?",
    options: ["£nil, because no tax was outstanding", "£100", "£10 per day from 1 February", "5% of the tax due"],
    correct: 1,
    explanation: "An immediate FIXED penalty of £100 applies the day the return is late — it is due even if no tax is outstanding or a repayment is due. Daily £10 penalties only start once the return is more than 3 months late; the 5% tax-geared penalty applies at 6 months.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-A-35", paper: "TX", area: "A", type: "mcq",
    stem: "Ana filed her 2024/25 online return (due 31 January 2026) eight months late. The tax outstanding at the filing date was £4,000. Assume the penalty regime: £100 fixed; £10 per day for up to 90 days once over 3 months late; and at 6 months, the greater of 5% of the tax due and £300. What are her total late-FILING penalties?",
    options: ["£1,000", "£1,200", "£400", "£1,300"],
    correct: 3,
    explanation: "£100 fixed + £900 maximum daily penalties (90 × £10) + the 6-month penalty of the GREATER of 5% × £4,000 = £200 and £300, i.e. £300. Total £1,300. £1,200 uses the £200 instead of the £300 minimum; £1,000 omits the 6-month penalty; £400 is just £100 + 5% of the tax.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-A-36", paper: "TX", area: "A", type: "mcq",
    stem: "Bella's balancing payment of £6,000 for 2024/25 was due on 31 January 2026 but she paid it on 17 March 2026 (45 days late). Assume a 5% penalty applies to tax unpaid more than 30 days after the due date. Ignoring interest, what late-PAYMENT penalty is charged?",
    options: ["£nil — only interest is charged", "£150", "£300", "£600"],
    correct: 2,
    explanation: "Tax still unpaid more than 30 days after the due date attracts a 5% penalty: £6,000 × 5% = £300 (interest runs in addition from the due date). £nil confuses penalties with interest; £600 applies 10%; £150 halves the penalty for no reason. Note payments on ACCOUNT never attract late-payment penalties, only interest.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-A-37", paper: "TX", area: "A", type: "mcq",
    stem: "By what date must an employer provide each employee with a form P60 for the tax year 2024/25?",
    options: ["31 May 2025", "6 July 2025", "19 April 2025", "31 January 2026"],
    correct: 0,
    explanation: "The P60 (end-of-year summary of pay and tax) must be given to employees by 31 May following the tax year. 6 July is the P11D (benefits) deadline; 19 April relates to final PAYE payments; 31 January is the self-assessment date.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-A-38", paper: "TX", area: "A", type: "mcq",
    stem: "By what date must an employer submit forms P11D (reporting employees' taxable benefits) for the tax year 2024/25?",
    options: ["22 July 2025", "31 May 2025", "19 April 2025", "6 July 2025"],
    correct: 3,
    explanation: "P11Ds are due by 6 July following the tax year. 22 July 2025 is the deadline for paying the associated Class 1A NIC electronically (a classic mix-up); 31 May is the P60 deadline.",
    marks: 2, difficulty: "medium",
  },
  /* Income tax computation — savings & dividends */
  {
    id: "TX2-A-39", paper: "TX", area: "A", type: "number",
    stem: "In 2024/25 Cai's taxable income (after the personal allowance) is £2,000 of non-savings income and £6,000 of savings income. Assume a £5,000 savings starting rate band at 0% (reduced by non-savings taxable income) and a £1,000 personal savings allowance for basic rate taxpayers. What is Cai's income tax liability in £?",
    numericAnswer: 800,
    unit: "£",
    explanation: "Non-savings: £2,000 × 20% = £400. The starting rate band left is £5,000 − £2,000 = £3,000 of savings at 0%; the next £1,000 is covered by the PSA at 0%; the remaining £2,000 × 20% = £400. Total £800. Taxing all £6,000 of savings at 20% (£1,600 of savings tax) misses both nil-rate amounts; forgetting that non-savings income eats into the £5,000 starting rate band leaves no savings taxed at all, giving only £400.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-A-40", paper: "TX", area: "A", type: "number",
    stem: "Dara's only taxable income for 2024/25, after the personal allowance, is £10,500 of dividends, all within the basic rate band. Assume a dividend allowance of £500 and a basic dividend rate of 8.75%. What is Dara's income tax liability in £?",
    numericAnswer: 875,
    unit: "£",
    explanation: "The first £500 is covered by the dividend allowance (taxed at 0%): (£10,500 − £500) × 8.75% = £875. Taxing the full £10,500 gives £919 (forgot the allowance); using 20% (£2,000) applies the non-savings rate to dividends.",
    marks: 2, difficulty: "medium",
  },

  /* ───────────── Area B — Chargeable gains ───────────── */
  /* Computation & rates */
  {
    id: "TX2-B-01", paper: "TX", area: "B", type: "number",
    stem: "Ed sells an investment property (never his residence) for £50,000, incurring estate agent and legal fees of £1,000 on the sale. He bought it for £30,000 and later spent £5,000 building a permanent extension. What is his chargeable gain in £?",
    numericAnswer: 14000,
    unit: "£",
    explanation: "Gain = net proceeds − cost − enhancement expenditure: £50,000 − £1,000 − £30,000 − £5,000 = £14,000. Forgetting the disposal costs gives £15,000; forgetting the enhancement gives £19,000.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-B-02", paper: "TX", area: "B", type: "number",
    stem: "In 2024/25 Fern has taxable gains of £20,000 (after the annual exempt amount) on quoted shares. Her taxable income leaves £10,000 of her basic rate band unused. Assume CGT rates on such gains of 10% within the basic rate band and 20% above it. What is her CGT liability in £?",
    numericAnswer: 3000,
    unit: "£",
    explanation: "£10,000 falls within the remaining basic rate band at 10% = £1,000; the other £10,000 is taxed at 20% = £2,000. Total £3,000. Taxing everything at 20% (£4,000) ignores the unused band; everything at 10% (£2,000) ignores that the band runs out.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-B-03", paper: "TX", area: "B", type: "number",
    stem: "Gus, a higher rate taxpayer, makes a gain of £43,000 in 2024/25 on the sale of a buy-to-let residential flat — his only disposal. Assume an annual exempt amount of £3,000 and a higher CGT rate on residential property gains of 24%. What is his CGT liability in £?",
    numericAnswer: 9600,
    unit: "£",
    explanation: "(£43,000 − £3,000) × 24% = £9,600. Using the 20% non-residential rate gives £8,000 — residential property gains carry their own higher rates; forgetting the annual exempt amount gives £10,320.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-B-04", paper: "TX", area: "B", type: "mcq",
    stem: "In 2024/25 Hope has chargeable gains of £10,000, a current-year capital loss of £2,000 and capital losses brought forward of £9,000. Assume an annual exempt amount of £3,000. How much of the BROUGHT-FORWARD loss is used in 2024/25?",
    options: ["£8,000", "£5,000", "£9,000", "£nil"],
    correct: 1,
    explanation: "Current-year losses must be set off in full first: £10,000 − £2,000 = £8,000. Brought-forward losses are then used only to bring net gains DOWN TO the annual exempt amount: £8,000 − £3,000 = £5,000 used, leaving £4,000 to carry forward. Using £8,000 wastes the AEA; £9,000 uses the whole loss unnecessarily; £nil confuses the ordering rules.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-B-05", paper: "TX", area: "B", type: "mcq",
    stem: "Ivan bought shares for £8,000. When they were worth £20,000 he transferred them to his wife Jana. What is Jana's base cost for a future disposal?",
    options: ["£8,000", "£20,000", "£12,000", "£nil"],
    correct: 0,
    explanation: "Transfers between spouses take place at NO GAIN/NO LOSS: Jana inherits Ivan's original cost of £8,000. £20,000 wrongly uses market value at the date of the gift (the rule for gifts to anyone else); £12,000 is the deferred gain, not a base cost.",
    marks: 2, difficulty: "easy",
  },
  /* Chattels */
  {
    id: "TX2-B-06", paper: "TX", area: "B", type: "number",
    stem: "Kira sells an antique painting (a non-wasting chattel) for gross proceeds of £9,000. She bought it for £2,000. What is her chargeable gain in £?",
    numericAnswer: 5000,
    unit: "£",
    explanation: "Proceeds exceed £6,000 while cost is below it, so the gain is capped by the marginal rule at 5/3 × (gross proceeds − £6,000) = 5/3 × £3,000 = £5,000. This is lower than the actual gain of £7,000, so £5,000 applies. Answering £7,000 forgets the 5/3 cap.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-B-07", paper: "TX", area: "B", type: "mcq",
    stem: "Liam bought an antique clock (a non-wasting chattel) for £8,000 and sold it for £3,000. What is his allowable capital loss?",
    options: ["£5,000", "£nil", "£2,000", "£3,000"],
    correct: 2,
    explanation: "Where a chattel costing more than £6,000 is sold for less than £6,000, proceeds are DEEMED to be £6,000: loss = £6,000 − £8,000 = £2,000. £5,000 uses actual proceeds (the classic error); £nil wrongly treats the clock as exempt; £3,000 is just the proceeds figure.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-B-08", paper: "TX", area: "B", type: "mcq",
    stem: "Which of the following disposals by an individual is EXEMPT from capital gains tax?",
    options: [
      "An antique table sold for £10,000",
      "A painting sold for £8,000",
      "Jewellery sold for £7,000",
      "A racehorse sold for £15,000",
    ],
    correct: 3,
    explanation: "A racehorse is a WASTING chattel (predictable life of 50 years or less) and is exempt regardless of value. The table, painting and jewellery are non-wasting chattels sold for more than £6,000, so they are chargeable (subject to the 5/3 marginal rule).",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-B-09", paper: "TX", area: "B", type: "mcq",
    stem: "Mona bought a porcelain vase (a non-wasting chattel) for £1,000 and sold it for £5,500. What is the CGT treatment of the disposal?",
    options: [
      "Exempt, because both cost and gross proceeds are £6,000 or less",
      "A chargeable gain of £4,500 arises",
      "Proceeds are deemed to be £6,000, giving a gain of £5,000",
      "Exempt, because a vase is a wasting chattel",
    ],
    correct: 0,
    explanation: "Where a non-wasting chattel is BOTH bought and sold for £6,000 or less, the disposal is exempt. £4,500 ignores the exemption; the deemed-£6,000-proceeds rule applies only to LOSSES on chattels costing over £6,000; a vase does not waste — it has a life over 50 years.",
    marks: 2, difficulty: "easy",
  },
  /* Part disposals */
  {
    id: "TX2-B-10", paper: "TX", area: "B", type: "number",
    stem: "Noor bought 10 hectares of land for £30,000. She sells 4 hectares for £50,000 when the remaining 6 hectares are worth £70,000. What is her chargeable gain on the part disposal in £?",
    numericAnswer: 37500,
    unit: "£",
    explanation: "Cost is apportioned by A/(A + B) where A = proceeds of the part sold and B = market value of the remainder: £30,000 × 50,000/(50,000 + 70,000) = £12,500. Gain = £50,000 − £12,500 = £37,500. Apportioning the cost by AREA instead (4/10 × £30,000 = £12,000, gain £38,000) is the classic error — the statutory formula uses values, not acreage.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-B-11", paper: "TX", area: "B", type: "mcq",
    stem: "In the part-disposal cost apportionment formula A/(A + B), what do A and B represent?",
    options: [
      "A = the original cost of the part sold; B = the original cost of the part retained",
      "A = the market value of the part retained; B = the proceeds of the part sold",
      "A = the gross proceeds of the part sold; B = the market value of the part retained",
      "A = the area of land sold; B = the area of land retained",
    ],
    correct: 2,
    explanation: "The allowable cost is: original cost × A/(A + B), where A is the GROSS consideration for the part disposed of and B is the market value of what remains. Original cost is never split directly (that is what the formula computes), and physical area is irrelevant — the split follows value.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-B-12", paper: "TX", area: "B", type: "number",
    stem: "Omar bought land for £50,000. He sells part of it for gross proceeds of £30,000, incurring disposal costs of £2,000, when the market value of the land retained is £90,000. What is his chargeable gain in £?",
    numericAnswer: 15500,
    unit: "£",
    explanation: "Apportioned cost = £50,000 × 30,000/(30,000 + 90,000) = £12,500 (the formula uses GROSS proceeds, and disposal costs are deducted in full from the part sold, not apportioned). Gain = £30,000 − £2,000 − £12,500 = £15,500. Using net proceeds of £28,000 in the formula gives an apportioned cost of £11,864 and the wrong gain.",
    marks: 2, difficulty: "hard",
  },
  /* PRR + letting relief */
  {
    id: "TX2-B-13", paper: "TX", area: "B", type: "number",
    stem: "Pia sells her house realising a gain of £80,000. She owned it for 240 months: she occupied it as her main residence for the first 180 months, then left it EMPTY until sale (the absence does not qualify as deemed occupation). Assume the final 9 months of ownership always qualify for relief. What is her private residence relief in £?",
    numericAnswer: 63000,
    unit: "£",
    explanation: "Qualifying months = 180 actual + 9 final months = 189 (the final 9 do not overlap the occupation period here). PRR = £80,000 × 189/240 = £63,000, leaving £17,000 chargeable. Using only 180 months gives £60,000 (forgot the final-period exemption); exempting the whole gain ignores the 60-month non-qualifying absence.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-B-14", paper: "TX", area: "B", type: "number",
    stem: "Throughout his entire period of ownership, Raj occupied 60% of his house as his main residence and let the other 40% to a lodger who lived in the property with him. He sells the house realising a gain of £120,000. Assume letting relief (available because the letting was in shared occupancy) is the lowest of the PRR given, the gain attributable to the letting, and £40,000. What is the chargeable gain in £?",
    numericAnswer: 8000,
    unit: "£",
    explanation: "PRR = £120,000 × 60% = £72,000. Gain attributable to letting = £48,000. Letting relief = lowest of £72,000, £48,000 and £40,000 = £40,000. Chargeable gain = £120,000 − £72,000 − £40,000 = £8,000. Taking letting relief as the full £48,000 (giving £nil) forgets the £40,000 cap.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-B-15", paper: "TX", area: "B", type: "mcq",
    stem: "Sara owned her house for 100 months. She lived in it as her main residence for the first 60 months, then left it empty (no deemed occupation applies) until it was sold. Assuming the final 9 months of ownership always qualify, how many months qualify for private residence relief?",
    options: ["60", "69", "100", "78"],
    correct: 1,
    explanation: "60 months of actual occupation + the final 9 months = 69. Answering 60 forgets the final-period exemption; 100 wrongly exempts the whole ownership; 78 uses the pre-2020 18-month final period.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-B-16", paper: "TX", area: "B", type: "mcq",
    stem: "Tom was absent from his main residence for various periods, each preceded AND followed by a period of actual occupation. Which of the following absences does NOT qualify in full as deemed occupation for private residence relief?",
    options: [
      "Two years spent living with a relative, for no particular reason",
      "Four years required to work elsewhere in the UK",
      "Six years employed abroad",
      "Five years travelling the world",
    ],
    correct: 3,
    explanation: "Deemed occupation covers: up to 3 years for ANY reason; up to 4 years where required to work elsewhere in the UK; and ANY period employed abroad — all sandwiched by actual occupation. Five years travelling exceeds the 3-year any-reason limit (only 3 of the 5 years would qualify), so it does not qualify in full.",
    marks: 2, difficulty: "medium",
  },
  /* Rollover relief */
  {
    id: "TX2-B-17", paper: "TX", area: "B", type: "mcq",
    stem: "A sole trader sells a business asset at a gain and reinvests the proceeds. Which of the following REPLACEMENT assets does NOT qualify for rollover relief?",
    options: [
      "Shares in an unquoted trading company",
      "A freehold factory to be used in the trade",
      "Fixed (immovable) plant and machinery",
      "Goodwill purchased with a new business",
    ],
    correct: 0,
    explanation: "Rollover relief requires reinvestment in qualifying BUSINESS assets: land and buildings used in the trade, fixed plant and machinery, and (for individuals) goodwill. Shares never qualify — buying shares in a trading company is an investment, not a qualifying business asset (gift holdover or other reliefs may apply to shares instead).",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-B-18", paper: "TX", area: "B", type: "number",
    stem: "Uma sells a factory used in her trade for £200,000, realising a gain of £50,000. Ten months later she buys a replacement factory for £180,000 and claims rollover relief. What gain remains chargeable at the time of the disposal in £?",
    numericAnswer: 20000,
    unit: "£",
    explanation: "Where proceeds are only partly reinvested, the gain chargeable now is the LOWER of the full gain and the proceeds NOT reinvested: £200,000 − £180,000 = £20,000. The remaining £30,000 is rolled over, reducing the new factory's base cost to £150,000. Answering £nil assumes full deferral despite the £20,000 kept back; £50,000 forgets relief is available at all.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-B-19", paper: "TX", area: "B", type: "mcq",
    stem: "To obtain rollover relief, within what period (relative to the date of disposal of the old asset) must the replacement business asset be acquired?",
    options: [
      "Within 12 months after the disposal only",
      "From 3 years before to 1 year after the disposal",
      "From 12 months before to 36 months after the disposal",
      "Within 4 years after the end of the tax year of disposal",
    ],
    correct: 2,
    explanation: "The reinvestment window runs from one year BEFORE to three years AFTER the disposal. Option (b) reverses the two limbs — a classic error; the others are invented periods.",
    marks: 2, difficulty: "easy",
  },
  /* Gift holdover relief */
  {
    id: "TX2-B-20", paper: "TX", area: "B", type: "number",
    stem: "Victor gifts a workshop used in his trade to his son when it is worth £100,000. Victor bought it for £40,000. They jointly claim gift holdover relief for the full gain. What is the son's base cost for a future disposal in £?",
    numericAnswer: 40000,
    unit: "£",
    explanation: "The gift is deemed to occur at market value, giving a gain of £60,000, all held over. The son's base cost = £100,000 − £60,000 held over = £40,000 (in effect he inherits Victor's cost). Answering £100,000 uses market value and forgets the holdover reduces the base cost.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-B-21", paper: "TX", area: "B", type: "number",
    stem: "Wendy sells a qualifying business asset to her daughter for £50,000 when its market value is £100,000. Wendy's cost was £30,000 and gift holdover relief is claimed. What gain is chargeable on Wendy AT THE DATE OF SALE in £?",
    numericAnswer: 20000,
    unit: "£",
    explanation: "On a sale at undervalue, the excess of ACTUAL proceeds over cost is chargeable immediately: £50,000 − £30,000 = £20,000. Only the balance of the full £70,000 gain (£50,000) is held over. Answering £nil holds over everything (only correct for an outright gift); £70,000 ignores the relief entirely.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-B-22", paper: "TX", area: "B", type: "mcq",
    stem: "Which of the following lifetime gifts qualifies for gift holdover relief?",
    options: [
      "A buy-to-let residential flat gifted to a nephew",
      "Shares in an unquoted trading company gifted to a daughter",
      "A 1% holding of quoted shares in an investment company gifted to a son",
      "A gift of £50,000 in cash to a friend",
    ],
    correct: 1,
    explanation: "Gift holdover relief applies to business assets, including unquoted trading company shares (and quoted shares only where the donor holds 5%+ in a trading company). The buy-to-let is an investment property, the quoted investment-company shares fail both the trading and the 5% tests, and cash is not a chargeable asset — there is no gain to hold over.",
    marks: 2, difficulty: "easy",
  },
  /* Business asset disposal relief */
  {
    id: "TX2-B-23", paper: "TX", area: "B", type: "number",
    stem: "Xena sells her entire sole-trader business, which she has owned and run for five years, realising qualifying gains of £400,000 — her only disposals in 2024/25. She has made no previous claims for business asset disposal relief. Assume an annual exempt amount of £3,000 and a BADR rate of 10%. What is her CGT liability in £?",
    numericAnswer: 39700,
    unit: "£",
    explanation: "The gains qualify for BADR (whole business owned 2+ years, within the £1,000,000 lifetime limit). CGT = (£400,000 − £3,000) × 10% = £39,700. Forgetting the annual exempt amount gives £40,000; using 20% (£79,400) misses the relief.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-B-24", paper: "TX", area: "B", type: "mcq",
    stem: "Which of the following disposals of SHARES qualifies for business asset disposal relief?",
    options: [
      "A 3% holding held by an employee for three years",
      "A 10% holding held for five years by an investor who has never worked for the company",
      "A 5% holding held by an employee for one year",
      "A 5% holding in a trading company held by a director for two years",
    ],
    correct: 3,
    explanation: "BADR on shares requires ALL of: at least a 5% holding (of shares and votes), the claimant is an officer or employee, the company is the claimant's personal trading company, and the conditions are met for 2 years to disposal. The 3% holding fails the 5% test, the non-employee investor fails the officer/employee test, and one year fails the 2-year test.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-B-25", paper: "TX", area: "B", type: "mcq",
    stem: "Yusuf has previously used £700,000 of his business asset disposal relief lifetime limit. In 2024/25 he realises a further qualifying gain of £500,000. Assume a lifetime limit of £1,000,000 and that he is a higher rate taxpayer. How much of the 2024/25 gain is taxed at the 10% BADR rate?",
    options: ["£300,000", "£500,000", "£1,000,000", "£nil"],
    correct: 0,
    explanation: "The lifetime limit remaining is £1,000,000 − £700,000 = £300,000, so only £300,000 is taxed at 10%; the excess £200,000 is taxed at the normal 20% rate. £500,000 forgets the earlier claims; £nil wrongly treats the limit as already exhausted; £1,000,000 is the limit itself, not the relieved amount.",
    marks: 2, difficulty: "hard",
  },
  /* Share matching rules */
  {
    id: "TX2-B-26", paper: "TX", area: "B", type: "number",
    stem: "Zoe bought 1,000 shares in Ash plc for £3,000 in 2015 and another 1,000 shares for £5,000 in 2019. In 2024/25 she sells 500 shares for £4,500 (no other transactions in the shares). What is her chargeable gain in £?",
    numericAnswer: 2500,
    unit: "£",
    explanation: "Both purchases sit in the share pool: 2,000 shares, cost £8,000. Cost of 500 sold = £8,000 × 500/2,000 = £2,000. Gain = £4,500 − £2,000 = £2,500. Matching against only the 2015 purchase at £3 per share (FIFO, gain £3,000) or only the 2019 purchase at £5 (gain £2,000) ignores pooled averaging.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-B-27", paper: "TX", area: "B", type: "number",
    stem: "Aled holds 2,000 shares in Bryn plc in his share pool at a cost of £6,000. On 15 May 2024 he sells 1,000 shares for £5 each. On 30 May 2024 he buys 400 shares for £4.50 each. What is his total chargeable gain on the disposal in £?",
    numericAnswer: 1400,
    unit: "£",
    explanation: "Match first with the purchase in the FOLLOWING 30 days: 400 shares — proceeds 400 × £5 = £2,000 less cost £1,800 = £200. The remaining 600 come from the pool: cost £6,000 × 600/2,000 = £1,800; proceeds £3,000; gain £1,200. Total £1,400. Taking all 1,000 from the pool (gain £2,000) ignores the 30-day rule, which exists to block 'bed and breakfasting'.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-B-28", paper: "TX", area: "B", type: "mcq",
    stem: "Cerys's share pool contains 2,000 shares in Dee plc at a cost of £8,000. The company makes a 1-for-2 bonus issue. What is the position of her share pool immediately afterwards?",
    options: [
      "3,000 shares at a cost of £12,000",
      "2,000 shares at a cost of £8,000",
      "3,000 shares at a cost of £8,000",
      "The bonus shares are a separate acquisition at market value on the issue date",
    ],
    correct: 2,
    explanation: "Bonus shares are added to the pool at NIL cost: 2,000 + 1,000 = 3,000 shares, cost unchanged at £8,000 (average cost per share falls). £12,000 invents cost for free shares; leaving the pool at 2,000 shares ignores the issue; bonus shares are never treated as a fresh acquisition at market value (that error also breaks the matching rules).",
    marks: 2, difficulty: "easy",
  },
]
