import type { AccaQuestion } from "@/lib/acca-content"

export const SBL_OFFICIAL_QUESTIONS: AccaQuestion[] = [
  { id: "SBL-A-O01", paper: "SBL", area: "A", type: "mcq", stem: "A chief executive publicly invites challenge but privately penalises managers who raise bad news. What is the most important leadership consequence?", options: ["A stronger control environment", "A speak-up culture in form but not substance", "Greater strategic agility", "Clearer accountability"], correct: 1, explanation: "Culture follows observed behaviour and incentives. Penalising challenge defeats the stated tone and suppresses information needed for ethical leadership and sound decisions.", marks: 2, difficulty: "medium" },
  { id: "SBL-A-O02", paper: "SBL", area: "A", type: "mcq", stem: "Which response best demonstrates responsible leadership after discovering a profitable product creates serious public harm?", options: ["Conceal the evidence until regulation changes", "Consider only short-term shareholder return", "Pause, investigate transparently and balance stakeholder impacts in the public interest", "Delegate the decision to marketing"], correct: 2, explanation: "Responsible leadership protects long-term value and public trust by confronting evidence, considering affected stakeholders and acting transparently rather than externalising harm.", marks: 2, difficulty: "easy" },
  { id: "SBL-A-O03", paper: "SBL", area: "A", type: "mcq", stem: "During urgent strategic change, when is a directive leadership style most defensible?", options: ["Whenever the leader dislikes consultation", "During an immediate safety crisis requiring coordinated action, followed by review and engagement", "For every innovation decision", "When suppressing professional scepticism"], correct: 1, explanation: "Style should fit circumstances. A genuine time-critical crisis can require direction, but sustainable change still needs explanation, participation and learning once immediate danger is controlled.", marks: 2, difficulty: "medium" },
  { id: "SBL-F-O01", paper: "SBL", area: "F", type: "mcq", stem: "Management receives a monthly dashboard, but definitions change between divisions and exceptions are not escalated. What is the primary control weakness?", options: ["Too much external audit", "Management information is not reliable or actionable", "Excessive segregation of duties", "Overcapitalisation"], correct: 1, explanation: "Control depends on consistent, timely information and defined escalation. Inconsistent measures and unreported exceptions prevent management from monitoring objectives and risk.", marks: 2, difficulty: "medium" },
  { id: "SBL-F-O02", paper: "SBL", area: "F", type: "mcq", stem: "Which feature most supports internal-audit independence?", options: ["The head of internal audit reports only to the finance director", "The audit committee approves appointment, scope and access", "Operational managers may delete findings", "Internal audit owns the controls it reviews"], correct: 1, explanation: "Functional accountability to an independent audit committee protects scope, access and reporting from management interference. Internal audit should not design and own controls it later assures.", marks: 2, difficulty: "easy" },
  { id: "SBL-F-O03", paper: "SBL", area: "F", type: "mcq", stem: "A control report lists a failed reconciliation but gives no owner, deadline or residual risk. What is missing?", options: ["More raw data only", "Accountable remediation and risk-focused follow-up", "A new corporate strategy", "An unmodified audit opinion"], correct: 1, explanation: "Effective reporting converts a finding into action by identifying significance, ownership, due date and follow-up; otherwise management cannot ensure remediation.", marks: 2, difficulty: "medium" },
  { id: "SBL-G-O01", paper: "SBL", area: "G", type: "mcq", stem: "A strategic proposal has a positive NPV but breaches debt covenants and depends on an untested tax assumption. What is the strongest board advice?", options: ["Accept because NPV is positive", "Reject all positive-NPV projects", "Validate assumptions and financing capacity before a conditional decision", "Ignore covenant effects because they are non-cash"], correct: 2, explanation: "Financial value is necessary but not sufficient. The adviser should test assumptions, financing and covenant consequences and present a conditional recommendation aligned with risk capacity.", marks: 2, difficulty: "hard" },
  { id: "SBL-G-O02", paper: "SBL", area: "G", type: "number", stem: "A transformation requires an initial investment of $2.0m and is expected to generate present-value benefits of $2.6m. What is its net present value in $m?", numericAnswer: 0.6, unit: "$m", tolerance: 0.01, explanation: "NPV = present value of benefits $2.6m − investment $2.0m = positive $0.6m. Strategic, implementation and financing risks still require evaluation.", marks: 2, difficulty: "easy" },
  { id: "SBL-G-O03", paper: "SBL", area: "G", type: "mcq", stem: "Which measure best exposes whether revenue growth is creating shareholder value rather than merely increasing scale?", options: ["Revenue alone", "A value measure incorporating operating return and cost of capital", "Headcount", "Number of board meetings"], correct: 1, explanation: "Value creation requires returns above the capital charge. Revenue or scale alone can grow while economic value is destroyed.", marks: 2, difficulty: "medium" },
  { id: "SBL-H-O01", paper: "SBL", area: "H", type: "mcq", stem: "A transformation has executive sponsorship but employees do not understand why it is needed or how roles will change. What should leadership do first?", options: ["Increase the project budget", "Build a change narrative and two-way stakeholder engagement", "Replace every employee", "Remove benefit measures"], correct: 1, explanation: "Change needs a credible case, stakeholder understanding and feedback. Sponsorship without engagement does not address uncertainty, capability or resistance.", marks: 2, difficulty: "medium" },
  { id: "SBL-H-O02", paper: "SBL", area: "H", type: "mcq", stem: "Which document establishes project purpose, scope, governance, responsibilities, milestones, resources and principal risks at initiation?", options: ["A marketing brochure", "A project initiation document", "An auditor's report", "A dividend voucher"], correct: 1, explanation: "The project initiation document creates an agreed baseline for governance and control, including scope, roles, plan, resources and risks.", marks: 2, difficulty: "easy" },
  { id: "SBL-H-O03", paper: "SBL", area: "H", type: "mcq", stem: "A project is on time and budget but the promised customer-retention benefit is not measured. What governance improvement is most important?", options: ["Declare success immediately", "Assign benefit ownership and track post-implementation outcomes", "Stop reporting risks", "Expand scope without approval"], correct: 1, explanation: "Delivery outputs do not prove strategic benefits. Named benefit owners and post-implementation measurement are needed to establish whether value was realised.", marks: 2, difficulty: "medium" },
  { id: "SBL-J-O01", paper: "SBL", area: "J", type: "mcq", stem: "An SBL task asks for a board briefing note. Which response format is most professional?", options: ["A generic essay", "Purposeful headings, prioritised analysis, evidence-linked recommendations and concise conclusion", "Copied exhibit text", "Unlabeled calculations only"], correct: 1, explanation: "The response should fit the recipient and purpose, synthesise rather than copy evidence, and lead to specific commercially grounded action.", marks: 2, difficulty: "easy" },
  { id: "SBL-J-O02", paper: "SBL", area: "J", type: "mcq", stem: "What is the best first step when navigating a large digital SBL exhibit set?", options: ["Read randomly", "Map each requirement to relevant exhibits, role, verb and output", "Copy every number", "Draft before identifying the decision"], correct: 1, explanation: "Requirement-led exhibit mapping reduces omission and overload and focuses analysis on the role, decision and requested deliverable.", marks: 2, difficulty: "medium" },
  { id: "SBL-J-O03", paper: "SBL", area: "J", type: "mcq", stem: "A spreadsheet exhibit conflicts with a director's narrative. What demonstrates appropriate digital judgement?", options: ["Ignore the spreadsheet", "Accept the director's seniority as proof", "Reconcile definitions and periods, quantify the conflict and flag uncertainty", "Average the two claims"], correct: 2, explanation: "Professional digital work validates comparable bases, investigates inconsistency and communicates uncertainty rather than choosing a convenient source.", marks: 2, difficulty: "hard" },
]
