import type { WrittenQuestion } from "@/lib/acca-written"

/*
 * Scholify — ACCA written (constructed-response) questions, set S1.
 *
 * 30 discursive questions for the Strategic Professional Essentials papers:
 * SBL (Strategic Business Leader) and SBR (Strategic Business Reporting).
 * Each carries a rubric of marking points the AI Examiner awards ~1 mark each.
 * All content is ORIGINAL — invented companies and figures, original prose,
 * built only on the public syllabus. No ACCA/Kaplan/BPP material reproduced.
 */

export const WRITTEN_S1: WrittenQuestion[] = [
  /* ═════════════ SBL — Strategic Business Leader (15) ═════════════ */

  /* ── Area A — Leadership & responsible business ── */
  {
    id: "SBL-W3-01",
    paper: "SBL",
    area: "A",
    topic: "CSR & the triple bottom line",
    stem: "Kettering Apparel is a fast-fashion retailer criticised in the media for poor conditions in its supplier factories and for the volume of textile waste it generates. Its board is considering adopting a responsible-business strategy. Advise the board on what corporate social responsibility and the triple bottom line mean for Kettering, and on the benefits and costs of pursuing such a strategy. (8 marks)",
    maxMarks: 8,
    rubric: [
      "Corporate social responsibility means the company accepts responsibility for its impact on all stakeholders and society, going beyond legal minimums and short-term profit.",
      "The triple bottom line evaluates performance across three dimensions: economic (profit), social (people) and environmental (planet).",
      "Economic: a responsible strategy can protect long-term revenue and brand value and reduce the risk of boycotts, litigation and regulatory penalties.",
      "Social: improving factory working conditions and supply-chain labour standards addresses the criticism and strengthens employee and community relations.",
      "Environmental: reducing textile waste and using sustainable materials or circular practices can cut material and energy costs and meet rising consumer expectations.",
      "A responsible strategy can improve access to capital, as investors increasingly screen for environmental, social and governance performance.",
      "Costs and risks: higher input and compliance costs, short-term margin pressure, and accusations of greenwashing if claims are not substantiated.",
      "Professional skills — commercial acumen: advice is grounded in Kettering's specific issues (factory conditions, waste, fast-fashion brand risk) and balances the commercial case against the cost and credibility of change.",
    ],
  },
  {
    id: "SBL-W3-02",
    paper: "SBL",
    area: "A",
    topic: "Rebuilding an ethical culture",
    stem: "Ashcombe Bank has been fined after a mis-selling scandal in which front-line staff sold unsuitable products to hit aggressive individual sales targets. A newly appointed chief executive wants to rebuild an ethical culture. Advise the chief executive on the actions needed to embed a stronger ethical culture across the bank. (8 marks)",
    maxMarks: 8,
    rubric: [
      "Culture is the shared values, beliefs and norms that shape how things are done, and here an unethical culture was reinforced by aggressive sales targets.",
      "Tone at the top: leaders must visibly model ethical behaviour, as employees take their cues from what management rewards and tolerates.",
      "Revise incentives: pay and bonus schemes based purely on sales volume drove the mis-selling, so rewards should be rebalanced towards customer outcomes and compliance.",
      "Establish and communicate a clear code of ethics or conduct, supported by training that makes the expected behaviours concrete for front-line staff.",
      "Introduce safe whistleblowing channels so concerns can be raised without fear of reprisal, with protection for those who speak up.",
      "Align monitoring and controls — mystery shopping, complaint analysis and consistent disciplinary follow-through — so breaches are detected and sanctioned.",
      "Governance: the board, via the audit or risk committee, should oversee culture, set the ethical tone and hold management accountable through metrics and reporting.",
      "Professional skills — commercial acumen: the answer links each action to the scandal's specific cause (target-driven mis-selling) and recognises that culture change requires sustained consistency, not a one-off statement.",
    ],
  },
  {
    id: "SBL-W3-03",
    paper: "SBL",
    area: "A",
    topic: "Integrated reporting <IR>",
    stem: "Longridge Utilities faces pressure from investors and community groups who say its annual report tells them little about how it creates value over the long term. The board is considering adopting integrated reporting. Advise the board on what integrated reporting involves and on its benefits and challenges for Longridge. (7 marks)",
    maxMarks: 7,
    rubric: [
      "Integrated reporting explains how an organisation creates value over the short, medium and long term, linking strategy, governance, performance and prospects.",
      "It is built around six capitals the business uses and affects: financial, manufactured, intellectual, human, social and relationship, and natural.",
      "An integrated report shows the connectivity between these capitals and the organisation's business model and value-creation process.",
      "Benefit: it gives investors and stakeholders a broader, more forward-looking view than the financial statements alone, aiding capital-allocation decisions.",
      "Benefit: preparing it encourages integrated thinking internally, breaking down silos and improving strategic decisions and resource use.",
      "Challenge: it requires new data, systems and management effort, involves judgement over what is material, and disclosing strategy carries competitive risk.",
      "Professional skills — commercial acumen: advice is tailored to a utility's stakeholder profile (regulators, communities, natural capital) and weighs the reporting benefits against the cost and effort of adoption.",
    ],
  },

  /* ── Area B — Governance ── */
  {
    id: "SBL-W3-04",
    paper: "SBL",
    area: "B",
    topic: "Audit committee — role & composition",
    stem: "Halvorsen Manufacturing is establishing an audit committee for the first time ahead of a planned listing. Explain the appropriate composition of the audit committee and the main responsibilities it should discharge. (6 marks)",
    maxMarks: 6,
    rubric: [
      "The audit committee should be composed of independent non-executive directors, with at least one member having recent and relevant financial experience.",
      "It oversees the integrity of the financial statements and reviews significant financial reporting judgements and estimates.",
      "It monitors the effectiveness of the company's internal control and risk management systems.",
      "It oversees the internal audit function, to which internal audit should report, protecting its independence from executive management.",
      "It manages the external auditor relationship — recommending appointment or removal, agreeing fees and audit scope, and reviewing auditor independence and effectiveness.",
      "It reviews the arrangements by which staff can raise concerns (whistleblowing) and reports to the board on how it has discharged its responsibilities.",
    ],
  },
  {
    id: "SBL-W3-05",
    paper: "SBL",
    area: "B",
    topic: "Designing executive remuneration",
    stem: "Shareholders of Tidewell plc are angry that its executive directors received large annual bonuses in a year when long-term performance and the share price declined. Advise the remuneration committee on how to design a directors' remuneration package that better aligns executives' interests with those of shareholders. (8 marks)",
    maxMarks: 8,
    rubric: [
      "The agency problem: directors (agents) may pursue their own interests, so remuneration should align their interests with those of the shareholders (principals).",
      "A package typically blends fixed elements (basic salary, benefits, pension) with variable performance-related pay (an annual bonus and long-term incentives).",
      "Performance measures should be linked to long-term value creation — such as total shareholder return, EPS growth or ROCE — not just short-term sales or profit.",
      "Long-term incentive plans, such as share awards or options vesting over several years, encourage a longer time horizon and aid retention.",
      "Deferral and clawback (malus) provisions allow reward to be withheld or recovered if performance proves unsustainable or misconduct later emerges.",
      "The remuneration committee of independent non-executive directors should set pay, so executives do not determine their own remuneration.",
      "Pay should be benchmarked and proportionate, avoiding excessive awards that damage stakeholder relations and provoke a shareholder revolt.",
      "Professional skills — commercial acumen: proposals directly fix Tidewell's failure (bonuses paid despite poor long-term results) by tying reward to sustained performance with deferral and clawback.",
    ],
  },
  {
    id: "SBL-W3-06",
    paper: "SBL",
    area: "B",
    topic: "Principles-based vs rules-based governance",
    stem: "Estcourt plc is listed in a jurisdiction that operates a 'comply or explain' governance code and is now seeking a secondary listing in a jurisdiction with detailed, legally enforceable governance rules. Compare the principles-based and rules-based approaches to corporate governance and explain the implications of the new listing for Estcourt. (6 marks)",
    maxMarks: 6,
    rubric: [
      "A principles-based ('comply or explain') approach sets broad principles of good governance that companies apply, explaining publicly where and why they depart from them.",
      "A rules-based approach sets detailed legal requirements that must be complied with, with penalties for breach (for example, Sarbanes-Oxley-style regulation).",
      "Principles-based is flexible and lets companies tailor governance to their size and circumstances, discouraging a mechanical 'box-ticking' mentality.",
      "Its weakness is that explanations can be used to justify persistent non-compliance, and enforcement relies on shareholder pressure and market discipline.",
      "Rules-based provides clarity, comparability and enforceable minimum standards, but can be costly to comply with and can encourage compliance in form rather than substance.",
      "Estcourt will have to meet the stricter mandatory rules of the new jurisdiction (such as management certification of internal controls) rather than relying on 'explain', increasing its compliance cost and director accountability.",
    ],
  },

  /* ── Area C — Strategy ── */
  {
    id: "SBL-W3-07",
    paper: "SBL",
    area: "C",
    topic: "BCG portfolio analysis",
    stem: "Crayford Group has four divisions: Division W leads a fast-growing market; Division X dominates a mature, low-growth market and throws off cash; Division Y has a small share of a booming market; and Division Z has a small share of a declining market. Using the Boston Consulting Group matrix, analyse Crayford's portfolio and advise the board on how it should treat each division. (7 marks)",
    maxMarks: 7,
    rubric: [
      "The BCG matrix plots business units by market growth rate and relative market share to guide portfolio and investment decisions.",
      "Stars (high growth, high share), such as Division W: leaders in growing markets that need investment to maintain position and may become future cash cows.",
      "Cash cows (low growth, high share), such as Division X: generate strong cash with little further investment, and should be milked to fund other units.",
      "Question marks (high growth, low share), such as Division Y: need heavy investment to build share with an uncertain outcome, so the board must decide whether to invest or divest.",
      "Dogs (low growth, low share), such as Division Z: generate little and tie up resources, so are usually harvested or divested.",
      "The aim is a balanced portfolio in which cash cows fund stars and selected question marks, sustaining future growth.",
      "Professional skills — analysis: the model is applied to Crayford's specific divisions, and its limitations noted (a simplistic two-factor view that ignores synergies and the difficulty of defining the market).",
    ],
  },
  {
    id: "SBL-W3-08",
    paper: "SBL",
    area: "C",
    topic: "Value chain analysis",
    stem: "Nettleford Furniture makes premium handcrafted furniture but is unsure where its true sources of competitive advantage lie. Explain how Porter's value chain could be used to help Nettleford identify sources of competitive advantage. (7 marks)",
    maxMarks: 7,
    rubric: [
      "Porter's value chain disaggregates the firm into the activities that create value, to locate sources of cost advantage or differentiation.",
      "Primary activities directly create and deliver the product: inbound logistics, operations, outbound logistics, marketing and sales, and service.",
      "Support activities enable the primary ones: firm infrastructure, human resource management, technology development, and procurement.",
      "The margin is the difference between the total value created and the cost of performing the activities.",
      "Analysing the cost and value of each activity shows where Nettleford can cut cost or enhance differentiation — for example superior craftsmanship in operations or strong after-sales service.",
      "Managing the linkages between activities, and links to suppliers' and customers' value chains (the value system), is itself a source of advantage.",
      "Professional skills — analysis: the framework is applied to Nettleford's actual furniture-making activities to pinpoint concrete advantages rather than listed generically.",
    ],
  },
  {
    id: "SBL-W3-09",
    paper: "SBL",
    area: "C",
    topic: "Ansoff's growth matrix",
    stem: "Wrenfield Dairy has a strong brand but its home market is mature and growth has stalled. The board is weighing several growth options. Using Ansoff's matrix, evaluate the growth directions open to Wrenfield and recommend, with reasons, a suitable direction. (8 marks)",
    maxMarks: 8,
    rubric: [
      "Ansoff's matrix considers growth through combinations of existing or new products and existing or new markets, with risk rising as the firm moves further from what it knows.",
      "Market penetration (existing products, existing markets): the lowest-risk option — growing share through pricing, promotion or loyalty — but limited in Wrenfield's mature market.",
      "Market development (existing products, new markets): for example exporting or targeting new customer segments, with moderate risk from unfamiliar markets.",
      "Product development (new products, existing markets): for example new dairy lines that leverage the existing brand and customer base, with risk from development and launch.",
      "Diversification (new products, new markets): the highest-risk option, as the firm lacks experience of both the product and the market.",
      "Related diversification shares links (technology, customers, distribution) with the existing business, whereas unrelated diversification does not and is the riskiest of all.",
      "A recommendation should reflect Wrenfield's mature home market, favouring market or product development over unrelated diversification unless its capabilities support more.",
      "Professional skills — commercial acumen: options are evaluated against Wrenfield's capabilities and risk appetite, ending in a justified, case-specific recommendation rather than a recital of the model.",
    ],
  },

  /* ── Area D — Risk & control ── */
  {
    id: "SBL-W3-10",
    paper: "SBL",
    area: "D",
    topic: "Embedding enterprise risk management",
    stem: "Garrowby plc manages risk in separate silos, with each department handling its own risks and no overall view at board level. The board wants to introduce an embedded, enterprise-wide approach to risk. Advise the board on how enterprise risk management should be embedded and on the role of risk appetite. (7 marks)",
    maxMarks: 7,
    rubric: [
      "Enterprise risk management is an integrated, entity-wide approach to identifying, assessing and managing risk, replacing fragmented silo management.",
      "The board is responsible for determining the nature and extent of the risk it is willing to take to achieve its objectives — the organisation's risk appetite.",
      "Risks should be considered in aggregate across the entity, recognising interdependencies between risks that silo management misses.",
      "Clear responsibilities help — for example a risk committee and a risk function, with the 'three lines' model separating operational management, risk and compliance oversight, and internal audit assurance.",
      "Risk management should be embedded in strategy, day-to-day operations and the culture, not treated as a separate compliance exercise.",
      "A risk register and regular reporting keep the board informed, with risks monitored against appetite and tolerances and escalated when limits are breached.",
      "Professional skills — commercial acumen: the advice addresses Garrowby's specific weakness (siloed risk) and links embedding ERM to better, appetite-consistent strategic decisions.",
    ],
  },
  {
    id: "SBL-W3-11",
    paper: "SBL",
    area: "D",
    topic: "Reputational risk & crisis response",
    stem: "Marlowe Toys has discovered a safety defect in its best-selling product and faces a large recall, with an angry backlash already building on social media. Advise the board on the nature of the reputational risk it faces and on how it should respond to and manage that risk. (7 marks)",
    maxMarks: 7,
    rubric: [
      "Reputational risk is the risk of losing stakeholder trust and damaging the brand, which can reduce sales, share price and access to finance.",
      "It often arises as a secondary consequence of another event — here a product-safety failure — and social media can amplify it very rapidly.",
      "Immediate crisis response: act quickly and transparently, with a prompt recall, honest communication and clear priority given to customer safety over short-term cost.",
      "Take responsibility and remedy: apologise where warranted, compensate affected customers, and fix the root cause to prevent recurrence.",
      "Stakeholder communication: a coordinated plan delivering consistent messages to customers, regulators, employees, investors and the media.",
      "Prevention and preparedness: strengthen quality control and supplier oversight, monitor social media, and maintain a tested crisis-management and business-continuity plan.",
      "Professional skills — commercial acumen: advice is grounded in Marlowe's recall, weighing the cost of a swift, generous response against the far larger long-term cost of lost trust.",
    ],
  },
  {
    id: "SBL-W3-12",
    paper: "SBL",
    area: "D",
    topic: "Internal control after a fraud",
    stem: "At Pelham Retail, a single store manager embezzled cash takings over two years without being detected. The manager handled the cash, recorded the sales and performed the reconciliations. Recommend the internal control improvements Pelham should make to prevent a recurrence. (8 marks)",
    maxMarks: 8,
    rubric: [
      "A sound system of internal control helps safeguard assets, ensure reliable records, promote operational efficiency and support compliance.",
      "Segregation of duties: no one person should control a whole transaction, yet here the same manager held custody of cash, recorded it and reconciled it, which enabled the fraud.",
      "Authorisation and approval controls: transactions such as refunds and write-offs should require independent approval within defined limits.",
      "Reconciliations and independent checks: regular, independently reviewed cash and bank reconciliations would have detected the missing cash far sooner.",
      "Physical controls over cash: secure handling, banking takings intact and promptly, and restricting access reduce the opportunity for theft.",
      "Monitoring: exception reporting, surprise cash counts and internal audit visits provide detective controls and act as a deterrent.",
      "People controls: rotation of duties and mandatory holidays make it harder for one person to conceal a long-running fraud.",
      "Professional skills — commercial acumen: recommendations target the specific weaknesses that let one manager steal undetected for two years, balanced against the cost of controls for a single retail store.",
    ],
  },

  /* ── Area E — Technology, data & professional/ethical judgement ── */
  {
    id: "SBL-W3-13",
    paper: "SBL",
    area: "E",
    topic: "Tucker's five-question ethics model",
    stem: "To win a large overseas contract, an agent tells Sedgemoor Engineering that a 'facilitation payment' must be made to a foreign government official. Using Tucker's five-question model, evaluate whether Sedgemoor should make the payment. (6 marks)",
    maxMarks: 6,
    rubric: [
      "Tucker's model tests a proposed decision against five questions: is it profitable, legal, fair, right and sustainable?",
      "Profitable: the contract would boost short-term profit, but the payment itself is a cost and the risk of penalties could outweigh any gain.",
      "Legal: facilitation payments and bribes are illegal under most anti-bribery laws (often with extraterritorial reach), so the decision fails the legal test.",
      "Fair: bribery distorts competition and is unfair to honest competitors and to the country's citizens.",
      "Right: it breaches the fundamental principle of integrity and the company's own ethical standards, so it is not the right thing to do.",
      "Sustainable: reliance on bribery is not sustainable — it exposes the firm to prosecution, reputational damage and continued extortion — so, failing the tests, the payment should be refused.",
    ],
  },
  {
    id: "SBL-W3-14",
    paper: "SBL",
    area: "E",
    topic: "AAA ethical decision model",
    stem: "An accountant at Corvenden Chemicals discovers that a plant is discharging waste above its permitted limits, and senior management wants the breach concealed. Using the American Accounting Association decision model, explain how the accountant should work through this dilemma. (7 marks)",
    maxMarks: 7,
    rubric: [
      "The American Accounting Association model works through seven steps to reach an ethical decision.",
      "Establish the facts of the case — here, the actual level and legality of the discharges and exactly what management knows.",
      "Identify the ethical issues involved — public safety and environmental harm, honesty of reporting, and legal compliance versus loyalty to the employer.",
      "Identify the norms, principles and values that bear on the decision — integrity, professional behaviour and the duty to act in the public interest.",
      "Identify the alternative courses of action — for example stay silent, raise it internally, use a whistleblowing channel, or report externally.",
      "Match the alternatives against the values and principles, which shows that concealment breaches integrity and the public-interest duty.",
      "Assess the consequences of each option and reach a decision — typically escalate internally first and, if unresolved, report to the regulator to protect the public interest.",
    ],
  },
  {
    id: "SBL-W3-15",
    paper: "SBL",
    area: "E",
    topic: "Blockchain for supply-chain traceability",
    stem: "Ironbridge Foods wants to improve the traceability of ingredients across its supply chain so that it can prove provenance and respond faster to contamination scares. The board has asked whether blockchain could help. Advise the board on how blockchain works and on its benefits and risks for Ironbridge. (8 marks)",
    maxMarks: 8,
    rubric: [
      "A blockchain is a distributed ledger — a shared, replicated record of transactions maintained across many participants rather than by a single central party.",
      "Records are grouped into cryptographically linked blocks, making entries effectively tamper-evident and immutable once they are added.",
      "Benefit: end-to-end traceability — each step in the food supply chain can be recorded and verified, helping prove provenance and speed up contamination recalls.",
      "Benefit: trust and efficiency — a single shared version of the truth reduces disputes and reconciliation and reliance on intermediaries, and smart contracts can automate payments on delivery.",
      "Risk: significant cost and complexity to implement, and the technology is still relatively immature with uncertain standards and scalability.",
      "Risk: it requires supply-chain partners to cooperate and adopt it, and the ledger is only as reliable as the data entered ('garbage in, garbage out').",
      "Risk: energy use, data-privacy and governance questions, and integration with existing systems must all be managed.",
      "Professional skills — commercial acumen: advice is tailored to Ironbridge's traceability problem, weighing genuine supply-chain benefits against cost, partner adoption and technology maturity rather than hyping the technology.",
    ],
  },

  /* ═════════════ SBR — Strategic Business Reporting (15) ═════════════ */

  /* ── Area A — Fundamental ethical & professional principles ── */
  {
    id: "SBR-W3-01",
    paper: "SBR",
    area: "A",
    topic: "Ethics — uncorrected prior-period error",
    stem: "During the audit of Kessler Textiles, the finance director discovers that inventory was systematically overstated by $2.4m in the prior year because of a costing error. The chief executive, whose bonus and a bank covenant both depend on reported profit, refuses to restate. Discuss the ethical and reporting issues and the actions the finance director should take. (6 marks)",
    maxMarks: 6,
    rubric: [
      "A material prior-period error must be corrected retrospectively under IAS 8 by restating the comparative amounts (or opening balances if the error is earlier), not by adjusting current-year profit.",
      "Refusing to restate means the financial statements are materially misstated and do not give a faithful representation of the position and performance.",
      "The finance director faces a self-interest and intimidation threat from the chief executive but must uphold integrity and objectivity under the ACCA Code of Ethics.",
      "Concealing the error to protect the chief executive's bonus or a loan covenant would be dishonest, misleads users, and could amount to fraud.",
      "The finance director should quantify the error, gather evidence and formally raise it with the audit committee or those charged with governance.",
      "If management still refuses to correct it, the accountant should seek professional or legal advice and, as a last resort, consider resignation and any required reporting to the appropriate authority.",
    ],
  },
  {
    id: "SBR-W3-02",
    paper: "SBR",
    area: "A",
    topic: "Ethics — inducements & confidential information",
    stem: "Ferrandez is a management accountant at listed Voltaic plc. A supplier bidding for a major contract has offered him a lavish, all-expenses holiday. Separately, he has learned of an unannounced profit warning, and a close friend has asked him for advice on whether to buy Voltaic shares. Discuss the ethical threats and the actions Ferrandez should take. (6 marks)",
    maxMarks: 6,
    rubric: [
      "Accepting the holiday creates a self-interest threat and could be seen as an inducement that impairs his objectivity in awarding the contract.",
      "The value and intent of the offer matter — a trivial, clearly inconsequential gift may be acceptable, but a lavish holiday intended to influence him should be declined.",
      "He should disclose the offer to his employer, follow any gifts and hospitality policy, and not take part in the supplier-selection decision if he is compromised.",
      "The unannounced profit warning is price-sensitive confidential information, and the confidentiality principle prohibits using it for personal advantage or that of a third party.",
      "Advising the friend to trade, or trading himself, would be insider dealing — illegal and a breach of both confidentiality and integrity.",
      "He should keep the information confidential and not act on it, remembering that the duty of confidentiality continues outside work and after the employment ends.",
    ],
  },
  {
    id: "SBR-W3-03",
    paper: "SBR",
    area: "A",
    topic: "Ethics — aggressive revenue cut-off",
    stem: "At Halloran Software the sales director is pressing the accountant to recognise, in the year just ended, revenue on software licences signed in December even though customer access is only granted the following January. Meeting the annual target would trigger sales commissions. Discuss the reporting and ethical issues and the accountant's proper response. (5 marks)",
    maxMarks: 5,
    rubric: [
      "Under IFRS 15, revenue is recognised only when (or as) a performance obligation is satisfied by transferring control of the goods or services to the customer.",
      "If access and control transfer in January, recognising the revenue in December is premature and overstates the current year — a cut-off error.",
      "The pressure reflects a self-interest threat linked to targets and commissions, and deliberately misstating cut-off breaches integrity and objectivity.",
      "The accountant must apply professional scepticism, obtain evidence of the date access is granted, and recognise the revenue in the correct period.",
      "If pressured to proceed, the accountant should escalate to the audit committee and refuse to record revenue that does not meet the IFRS 15 criteria.",
    ],
  },

  /* ── Area B — The financial reporting framework ── */
  {
    id: "SBR-W3-04",
    paper: "SBR",
    area: "B",
    topic: "Measurement bases in the Conceptual Framework",
    stem: "The directors of Dunmore Holdings are reviewing which measurement bases to apply to different assets and liabilities. Explain the measurement bases identified in the IASB Conceptual Framework and the factors that influence the selection of a measurement basis. (6 marks)",
    maxMarks: 6,
    rubric: [
      "The Conceptual Framework identifies two broad categories of measurement basis: historical cost and current value.",
      "Historical cost measures an asset or liability using information derived from the transaction price, updated over time for depreciation, impairment or the effect of payments.",
      "Current value measures using information updated to the measurement date, and includes fair value, value in use (for assets) or fulfilment value (for liabilities), and current cost.",
      "Fair value is the price to sell an asset, or transfer a liability, in an orderly transaction between market participants, reflecting market rather than entity-specific assumptions.",
      "A basis is selected to provide relevant information that faithfully represents, considering the nature of the item and how it contributes to future cash flows.",
      "Selection also weighs the variability of the value and the cost constraint — the benefits of the information must justify the cost of providing it.",
    ],
  },
  {
    id: "SBR-W3-05",
    paper: "SBR",
    area: "B",
    topic: "Substance over form — sale and repurchase",
    stem: "Alderway Distillery has 'sold' a quantity of maturing whisky stock to a bank for $8m and has agreed to buy it back in three years' time for a fixed $9.6m. Alderway retains the risks and rewards of the stock throughout. Explain, applying the principle of substance over form, how this arrangement should be accounted for. (6 marks)",
    maxMarks: 6,
    rubric: [
      "Faithful representation requires transactions to be accounted for according to their economic substance, not merely their legal form.",
      "Although the arrangement is legally structured as a sale, the fixed repurchase price and Alderway's retention of the risks and rewards indicate the whisky has not truly been sold.",
      "The substance is a secured financing arrangement (in effect a loan), so no revenue should be recognised on the transfer.",
      "The inventory remains on Alderway's statement of financial position, because it retains control and the risks and rewards of ownership.",
      "The $8m received is recognised as a financial liability rather than as revenue.",
      "The $1.6m difference between the sale and repurchase prices is a finance cost, accrued over the three years using the effective interest method.",
    ],
  },
  {
    id: "SBR-W3-06",
    paper: "SBR",
    area: "B",
    topic: "IAS 8 — policy change, estimate change or error",
    stem: "The directors of Marston Retail are unsure how to account for three matters: a switch from the cost model to the revaluation model for property; a revision to the estimated useful lives of their vehicles; and the discovery of a material understatement of expenses in the previous year's accounts. Explain, under IAS 8, how each should be treated. (6 marks)",
    maxMarks: 6,
    rubric: [
      "A change in accounting policy is a change in the specific principles or bases applied (such as moving from the cost model to the revaluation model), permitted only if required by an IFRS or if it gives more relevant and reliable information.",
      "A change in accounting policy is normally applied retrospectively, adjusting the opening balance of each affected component of equity and restating the comparatives as if the policy had always applied.",
      "A change in accounting estimate is an adjustment to the carrying amount of an asset or liability arising from new information, such as revising the vehicles' useful lives.",
      "A change in accounting estimate is applied prospectively — in the current and future periods — with no restatement of comparatives.",
      "A prior-period error is an omission or misstatement arising from a failure to use, or the misuse of, reliable information that was available when the statements were authorised — here the understated expenses.",
      "A material prior-period error is corrected retrospectively by restating the comparative amounts, or the opening balances if the error predates the comparatives presented.",
    ],
  },

  /* ── Area C — Reporting the performance of a range of entities ── */
  {
    id: "SBR-W3-07",
    paper: "SBR",
    area: "C",
    topic: "IAS 36 — impairment of a CGU with goodwill",
    stem: "One of Braithwaite Logistics' depots, which was acquired as a business and to which goodwill has been allocated, is showing clear indicators of impairment. Explain how the impairment of this cash-generating unit should be tested and how any resulting impairment loss is allocated. (7 marks)",
    maxMarks: 7,
    rubric: [
      "An impairment loss arises when the carrying amount of an asset or cash-generating unit exceeds its recoverable amount.",
      "Recoverable amount is the higher of fair value less costs of disposal and value in use.",
      "Value in use is the present value of the future cash flows expected from the asset or unit, discounted at a pre-tax rate reflecting current market assessments.",
      "Goodwill cannot generate cash flows independently, so it is tested for impairment as part of the cash-generating unit to which it has been allocated.",
      "An impairment loss for a cash-generating unit is allocated first to reduce the carrying amount of any goodwill in the unit.",
      "Any remaining loss is then allocated to the other assets of the unit pro rata on the basis of their carrying amounts.",
      "No individual asset is written down below the highest of its own fair value less costs of disposal, its value in use, or zero, and an impairment of goodwill is never subsequently reversed.",
    ],
  },
  {
    id: "SBR-W3-08",
    paper: "SBR",
    area: "C",
    topic: "IFRS 16 — lessor accounting",
    stem: "Camborne Plant Hire leases out heavy equipment under a range of contracts and is unsure how, as a lessor, it should classify and account for them. Explain how a lessor classifies leases under IFRS 16 and how it accounts for a finance lease and an operating lease. (6 marks)",
    maxMarks: 6,
    rubric: [
      "A lessor classifies each lease at inception as either a finance lease or an operating lease.",
      "A finance lease is one that transfers substantially all the risks and rewards incidental to ownership of the asset, whereas an operating lease does not.",
      "Indicators of a finance lease include transfer of ownership by the end of the term, a bargain purchase option, a term covering the major part of the asset's economic life, or the present value of lease payments amounting to substantially all of the asset's fair value.",
      "For a finance lease, the lessor derecognises the underlying asset and recognises a receivable equal to the net investment in the lease.",
      "Finance income is recognised over the lease term so as to give a constant periodic rate of return on the net investment in the lease.",
      "For an operating lease, the lessor keeps the asset on its statement of financial position, continues to depreciate it, and recognises the lease income on a straight-line basis over the term.",
    ],
  },
  {
    id: "SBR-W3-09",
    paper: "SBR",
    area: "C",
    topic: "IAS 20 — government grants",
    stem: "Trelawney Renewables has received a $5m government grant towards the construction of a solar plant and a separate grant that subsidises the wages of newly hired staff. Explain how these government grants should be recognised and presented under IAS 20, and how a grant that becomes repayable is treated. (6 marks)",
    maxMarks: 6,
    rubric: [
      "A government grant is recognised only when there is reasonable assurance that the entity will comply with the attached conditions and that the grant will be received.",
      "Grants are recognised in profit or loss on a systematic basis over the periods in which the entity recognises the related costs the grant is intended to compensate.",
      "A grant is not credited directly to equity.",
      "An asset-related grant, such as the solar plant grant, is presented either as deferred income released to profit or loss over the asset's life, or by deducting it from the asset's carrying amount so that depreciation is reduced.",
      "An income-related grant, such as the wage subsidy, is presented either as other income or as a deduction from the related expense.",
      "If a grant becomes repayable it is treated as a change in estimate — repayment is applied first against any unamortised deferred income, with any excess recognised immediately in profit or loss.",
    ],
  },

  /* ── Area D — Financial statements of groups ── */
  {
    id: "SBR-W3-10",
    paper: "SBR",
    area: "D",
    topic: "IAS 28 — associates & the equity method",
    stem: "Pemberton plc has acquired 30% of the ordinary shares of Oakfield Ltd and has obtained a seat on Oakfield's board. Explain why Oakfield is likely to be an associate and how it should be accounted for in Pemberton's consolidated financial statements. (6 marks)",
    maxMarks: 6,
    rubric: [
      "An associate is an entity over which the investor has significant influence — the power to participate in the financial and operating policy decisions, but not control or joint control.",
      "Significant influence is presumed where the investor holds 20% or more of the voting power unless clearly demonstrated otherwise, and the board seat here supports its existence.",
      "An associate is accounted for using the equity method in the consolidated financial statements.",
      "The investment is initially recognised at cost and then increased or decreased by the investor's share of the associate's post-acquisition profit or loss and other comprehensive income.",
      "The investor's share of the associate's profit is recognised in the consolidated statement of profit or loss, while dividends received reduce the carrying amount of the investment.",
      "Losses are recognised only until the investment is reduced to nil (unless the investor has further obligations); the investment is tested for impairment, and unrealised profits on transactions with the associate are eliminated to the extent of the investor's interest.",
    ],
  },
  {
    id: "SBR-W3-11",
    paper: "SBR",
    area: "D",
    topic: "IFRS 10 — loss of control of a subsidiary",
    stem: "Winterbourne Group owns 80% of a subsidiary and sells three-quarters of that holding, leaving it with a 20% interest over which it no longer has control. Explain how the group should account for the loss of control of the subsidiary, and how any gain or loss on disposal is determined. (7 marks)",
    maxMarks: 7,
    rubric: [
      "When a parent loses control of a subsidiary, it derecognises the subsidiary's assets and liabilities (including goodwill) at their carrying amounts at the date control is lost.",
      "It derecognises the carrying amount of any non-controlling interest in the former subsidiary at that date.",
      "It recognises the fair value of the consideration received on the disposal.",
      "Any interest retained in the former subsidiary is remeasured to its fair value at the date control is lost.",
      "That fair value becomes the initial carrying amount for subsequently accounting for the retained interest as an associate, joint venture or financial asset.",
      "A gain or loss on disposal is recognised in profit or loss, being the difference between the proceeds plus the fair value of the retained interest and the net assets derecognised less the non-controlling interest derecognised.",
      "Amounts previously recognised in other comprehensive income in relation to the subsidiary are reclassified to profit or loss, or transferred to retained earnings, on the same basis as if the related assets and liabilities had been disposed of directly.",
    ],
  },
  {
    id: "SBR-W3-12",
    paper: "SBR",
    area: "D",
    topic: "NCI measurement — full vs partial goodwill",
    stem: "Marchmont plc has acquired 75% of Ravensmoor Ltd and must decide how to measure the non-controlling interest at acquisition. Explain the two methods of measuring non-controlling interest permitted by IFRS 3 and the effect each has on goodwill and the consolidated financial statements. (6 marks)",
    maxMarks: 6,
    rubric: [
      "At acquisition, IFRS 3 allows the non-controlling interest to be measured either at fair value or at its proportionate share of the subsidiary's identifiable net assets.",
      "Measuring the non-controlling interest at fair value produces the 'full goodwill' method, under which goodwill includes the portion attributable to the non-controlling interest.",
      "Measuring it at the proportionate share produces the 'partial goodwill' method, under which only the parent's share of goodwill is recognised.",
      "Goodwill is the excess of the consideration transferred plus the non-controlling interest plus any previously held interest over the fair value of the identifiable net assets acquired.",
      "The full goodwill method reports higher goodwill and a higher non-controlling interest in the consolidated statement of financial position than the partial method.",
      "The choice affects goodwill impairment: under the partial method the goodwill must be grossed up before comparing with recoverable amount, whereas under full goodwill the whole loss is simply allocated between the parent and the non-controlling interest.",
    ],
  },

  /* ── Area E — Interpretation & current developments ── */
  {
    id: "SBR-W3-13",
    paper: "SBR",
    area: "E",
    topic: "Sustainability reporting — IFRS S1 and S2",
    stem: "Investors in Cindercote plc are pressing the board for more consistent and comparable information about the company's exposure to climate change. Discuss how the ISSB's sustainability reporting standards address this demand, and the benefits and challenges of such reporting. (6 marks)",
    maxMarks: 6,
    rubric: [
      "The ISSB issued IFRS S1 (general sustainability-related disclosures) and IFRS S2 (climate-related disclosures) to meet investor demand for consistent, comparable information.",
      "Their objective is to provide information about sustainability-related risks and opportunities that is useful to primary users in making resource-allocation decisions — an investor, enterprise-value focus.",
      "Disclosures are structured around four pillars: governance, strategy, risk management, and metrics and targets, aligned with the former TCFD framework.",
      "IFRS S2 requires disclosure of climate-related physical and transition risks and of information such as Scope 1, Scope 2 and, where material, Scope 3 greenhouse gas emissions.",
      "Benefits include reduced greenwashing, greater comparability across entities, a potentially lower cost of capital and better-informed stakeholders.",
      "Challenges include measurement uncertainty (particularly Scope 3 emissions), the cost and data systems required, assurance of non-financial information, and achieving connectivity with the financial statements.",
    ],
  },
  {
    id: "SBR-W3-14",
    paper: "SBR",
    area: "E",
    topic: "Interpretation — accounting policy choice & ratios",
    stem: "An analyst is comparing two retailers: Sattherwaite plc, which owns most of its stores and revalues its property, and Kirkland plc, which leases its stores and holds property at historical cost. Explain how these accounting policy choices affect the comparability of the two companies' financial statements and ratios. (6 marks)",
    maxMarks: 6,
    rubric: [
      "Accounting policy choices and estimates reduce comparability between entities, so ratios must be interpreted with care.",
      "IFRS 16 brings most leases on to the statement of financial position as a right-of-use asset and a lease liability, which increases reported gearing and reduces interest cover.",
      "Lease expense is split into depreciation and interest, so operating profit and EBITDA are higher than under the former operating-lease rental treatment, distorting trend and peer comparisons.",
      "Revaluing property increases asset carrying amounts and equity, lowering gearing and return on capital employed, whereas a company using historical cost appears more geared but reports a higher return on capital employed.",
      "Different estimates — useful lives, depreciation methods and impairment assumptions — change reported profit and asset values and hence margins and returns.",
      "An analyst should adjust for the policy differences, read the notes on accounting policies and estimates, and remain alert to management bias and to non-GAAP or alternative performance measures when comparing the two companies.",
    ],
  },
  {
    id: "SBR-W3-15",
    paper: "SBR",
    area: "E",
    topic: "Goodwill — impairment-only vs amortisation debate",
    stem: "The directors of Harrowgate plc have observed that the goodwill recognised on several past acquisitions has never been written down, and question whether the current accounting for goodwill is useful. Critically discuss the debate over whether purchased goodwill should be tested only for impairment or should instead be amortised. (6 marks)",
    maxMarks: 6,
    rubric: [
      "Under IFRS 3 and IAS 36, purchased goodwill is not amortised but is tested for impairment at least annually.",
      "Critics argue that impairment losses are often recognised too little, too late, because management optimism and the headroom created by internally generated goodwill shield acquired goodwill from write-down.",
      "The impairment-only approach is costly and highly judgemental, relying on cash-flow forecasts and discount rates that are difficult to verify.",
      "Reintroducing amortisation would give a systematic and less subjective charge and better match goodwill's cost to the periods that benefit, though the choice of useful life would be arbitrary.",
      "Supporters of impairment-only argue that amortisation is itself an arbitrary charge that gives investors little useful information and blurs acquired with internally generated goodwill.",
      "Enhanced disclosure — about the subsequent performance of acquisitions and the assumptions used in impairment tests — is proposed as a way to improve accountability without necessarily changing the measurement model.",
    ],
  },
]
