import type { AccaQuestion } from "@/lib/acca-content"

/*
 * SBL bank wave S1 part B (areas C, D, E)
 * Blueprint: C30 D30 E20 = 80 MCQs, all 2 marks, 4 options each.
 * Difficulty mix: 22 easy / 38 medium / 20 hard.
 * Correct-answer positions balanced 20/20/20/20 across indices 0/1/2/3.
 * Date: 2026-07-13.
 * Originality & accuracy: 100% original scenarios, org names and prose — no
 * ACCA/Kaplan/BPP text reproduced; public SBL syllabus only. Every distractor
 * encodes a nameable conceptual error explained in the rationale. Framework
 * details verified: COSO internal control's five components (control
 * environment, risk assessment, control activities, information &
 * communication, monitoring activities); the four TARA responses (transfer,
 * avoid, reduce, accept); the big-data 'Vs' (volume, velocity, variety,
 * veracity); and SBL's five professional skills (communication, commercial
 * acumen, analysis, scepticism, evaluation).
 */

export const SBL_WAVE1B: AccaQuestion[] = [
  /* ══════════════ AREA C — Risk & control (30) ══════════════ */

  {
    id: "SBL3-C-01", paper: "SBL", area: "C", type: "mcq",
    stem: "The board of Harlenby Group is agreeing a statement of its 'risk appetite'. Which of the following best defines risk appetite?",
    options: [
      "The maximum loss the group could suffer if every identified risk crystallised simultaneously",
      "A ranked list of every risk the group has identified during the year",
      "The amount and type of risk the group is willing to accept in pursuit of its objectives",
      "The statistical probability that any given risk will occur within the next year",
    ],
    correct: 2,
    explanation: "Risk appetite is the level and nature of risk an organisation chooses to take on to meet its goals. Option 0 describes maximum exposure or a worst-case loss, not the chosen appetite; option 1 describes the risk register; option 3 describes the likelihood of a single risk, a component of assessment rather than appetite.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "SBL3-C-02", paper: "SBL", area: "C", type: "mcq",
    stem: "How does 'risk capacity' differ from 'risk appetite'?",
    options: [
      "Risk capacity is the maximum risk an organisation can bear given its resources, whereas appetite is how much risk it chooses to take",
      "Risk capacity and risk appetite are simply two names for the same board-set limit",
      "Risk appetite should always exceed risk capacity in a fast-growing company",
      "Risk capacity is fixed by regulators and has no bearing on strategy",
    ],
    correct: 0,
    explanation: "Capacity is the objective ceiling set by resources such as capital and liquidity; appetite is the subjective choice made within that ceiling. Option 1 wrongly conflates the two; option 2 is unsound because a prudent appetite sits within capacity, not above it; option 3 wrongly treats capacity as a purely regulatory notion divorced from strategy.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-C-03", paper: "SBL", area: "C", type: "mcq",
    stem: "A risk register shows a risk with high gross likelihood that falls to low likelihood after controls are applied. The 'residual (net) risk' is:",
    options: [
      "The level of risk before any controls are applied",
      "The gross risk plus the cost of operating the controls",
      "The portion of the risk transferred to insurers",
      "The risk that remains after existing controls and responses have been applied",
    ],
    correct: 3,
    explanation: "Residual (net) risk is what is left once controls and responses are in place. Option 0 defines gross (inherent) risk; option 1 invents a meaningless total by adding control cost to risk; option 2 describes only the transferred element, which is one response, not the residual position.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-C-04", paper: "SBL", area: "C", type: "mcq",
    stem: "Marrowfield Co takes out insurance and outsources a hazardous process to a specialist contractor. Under the TARA framework, this is an example of which response?",
    options: ["Avoid", "Transfer", "Reduce", "Accept"],
    correct: 1,
    explanation: "Shifting the financial consequences of a risk to a third party (insurer or contractor) is transfer. Avoid means withdrawing from the activity altogether; reduce means adding controls to lower likelihood or impact; accept means retaining the risk without further action.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "SBL3-C-05", paper: "SBL", area: "C", type: "mcq",
    stem: "A board concludes that a proposed venture in a politically unstable region carries risk far beyond its appetite, and it decides not to proceed with the project at all. Which TARA response is this?",
    options: ["Reduce", "Avoid", "Transfer", "Accept"],
    correct: 1,
    explanation: "Declining to undertake the activity entirely is avoidance. Reduce would keep the venture but add controls; transfer would keep it but pass consequences to a third party; accept would keep it and retain the risk — none of which fits a decision to withdraw completely.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-C-06", paper: "SBL", area: "C", type: "mcq",
    stem: "A risk has been assessed as low likelihood and low impact, and any mitigation would cost more than the expected benefit. Which TARA response is most appropriate?",
    options: [
      "Reduce, by installing additional controls regardless of their cost",
      "Transfer, by arranging a bespoke insurance policy",
      "Avoid, by ceasing the activity that gives rise to the risk",
      "Accept and monitor the risk, since the cost of control would exceed the benefit",
    ],
    correct: 3,
    explanation: "For a low/low risk where control is not cost-effective, acceptance with monitoring is the proportionate response. Option 0 ignores cost-benefit; option 1 pays a premium to transfer a trivial exposure; option 2 discards a viable activity for a minor risk — all disproportionate reactions.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "SBL3-C-07", paper: "SBL", area: "C", type: "mcq",
    stem: "What is the primary purpose of a risk register?",
    options: [
      "To provide a central record of identified risks, their assessment, owners and agreed responses",
      "To act as a statutory return filed with the stock exchange each year",
      "To record the insurance premiums paid during the accounting period",
      "To schedule the internal audit team's annual leave",
    ],
    correct: 0,
    explanation: "A risk register is the working document that captures identified risks, their likelihood/impact, owners and responses, and supports monitoring. Option 1 confuses it with a regulatory filing; option 2 describes an insurance ledger; option 3 is unrelated to risk management.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "SBL3-C-08", paper: "SBL", area: "C", type: "mcq",
    stem: "A risk 'heat map' plots each risk on two axes. Those two axes are:",
    options: [
      "Cost of control against benefit of control",
      "Gross risk against net risk",
      "Likelihood (probability) against impact (consequence)",
      "Strategic risk against operational risk",
    ],
    correct: 2,
    explanation: "A heat map positions risks by their likelihood and their impact so the board can prioritise the high/high quadrant. Option 0 describes a control cost-benefit analysis; option 1 compares two states of the same risk, not the mapping axes; option 3 lists two categories of risk rather than the assessment dimensions.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-C-09", paper: "SBL", area: "C", type: "mcq",
    stem: "What is the key distinction between a board risk committee and an audit committee?",
    options: [
      "The risk committee sets risk appetite and oversees the whole risk management framework, while the audit committee focuses on financial reporting integrity, controls and the audit process",
      "The audit committee sets risk appetite while the risk committee approves the financial statements",
      "Both committees must be composed entirely of executive directors",
      "The risk committee removes the need for an external audit",
    ],
    correct: 0,
    explanation: "The risk committee owns oversight of the risk framework and appetite; the audit committee concentrates on reporting integrity, internal control and audit. Option 1 reverses their roles; option 2 is wrong because both should be staffed by independent non-executive directors; option 3 is false — external audit remains a separate statutory function.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-C-10", paper: "SBL", area: "C", type: "mcq",
    stem: "What is the primary role of a board risk committee?",
    options: [
      "To prepare the annual financial statements",
      "To negotiate the external auditor's fee",
      "To oversee the organisation's risk management framework and advise the board on risk appetite",
      "To set the remuneration of the executive directors",
    ],
    correct: 2,
    explanation: "A risk committee oversees how risk is identified, assessed and managed and advises the board on appetite and tolerance. Option 0 is a management/finance function; option 1 is typically an audit-committee matter; option 3 is the remuneration committee's responsibility.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "SBL3-C-11", paper: "SBL", area: "C", type: "mcq",
    stem: "Which statement best characterises enterprise risk management (ERM) as opposed to traditional 'silo' risk management?",
    options: [
      "ERM assesses each department's risks in isolation to keep responsibility local",
      "ERM takes a portfolio, entity-wide view of risk, integrated with strategy and recognising how risks interact",
      "ERM is concerned only with insurable hazard risks",
      "ERM transfers all responsibility for managing risk to the internal audit function",
    ],
    correct: 1,
    explanation: "ERM is an integrated, organisation-wide approach that links risk to strategy and considers correlations across the portfolio. Option 0 describes exactly the silo approach ERM is meant to replace; option 2 wrongly narrows ERM to hazard risk; option 3 confuses ownership (the board and management) with assurance (internal audit).",
    marks: 2, difficulty: "hard",
  },
  {
    id: "SBL3-C-12", paper: "SBL", area: "C", type: "mcq",
    stem: "Under a sound governance structure, ultimate responsibility for risk management rests with:",
    options: [
      "The internal audit function",
      "The external auditors",
      "The risk management department alone",
      "The board of directors",
    ],
    correct: 3,
    explanation: "The board is ultimately accountable for the effectiveness of risk management and internal control, even where activities are delegated. Internal audit provides assurance, not ownership; external auditors are independent of management; and a risk department supports but does not carry ultimate board-level accountability.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-C-13", paper: "SBL", area: "C", type: "mcq",
    stem: "Which of the following is NOT one of the five components of the COSO internal control framework?",
    options: [
      "Control environment",
      "Risk assessment",
      "Control activities",
      "Corporate strategy formulation",
    ],
    correct: 3,
    explanation: "The five COSO internal control components are control environment, risk assessment, control activities, information and communication, and monitoring activities. Strategy formulation is a governance/strategic-management activity, not a control component, so it is the odd one out.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-C-14", paper: "SBL", area: "C", type: "mcq",
    stem: "In the COSO framework, the 'control environment' refers to:",
    options: [
      "The physical premises where the accounting records are stored",
      "The set of standards, processes and structures — including integrity, ethical values and tone at the top — that provide the foundation for internal control",
      "The external economic conditions affecting the business",
      "The software environment used to run the general ledger",
    ],
    correct: 1,
    explanation: "The control environment is the ethical tone and governance foundation on which the other components rest. Option 0 takes 'environment' literally as premises; option 2 describes external macro conditions; option 3 confuses it with an IT system rather than the organisation's culture and standards.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "SBL3-C-15", paper: "SBL", area: "C", type: "mcq",
    stem: "Pellworth Co introduces monthly bank reconciliations, payment authorisation limits and segregation of duties over its cash cycle. In COSO terms these are examples of:",
    options: [
      "The control environment",
      "Risk assessment",
      "Control activities",
      "Monitoring activities",
    ],
    correct: 2,
    explanation: "Reconciliations, authorisation limits and segregation of duties are the specific policies and procedures that mitigate risks — control activities. The control environment is the overarching culture; risk assessment identifies and evaluates risks; monitoring activities check that controls keep working over time.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "SBL3-C-16", paper: "SBL", area: "C", type: "mcq",
    stem: "What is the primary role of an internal audit function?",
    options: [
      "To provide independent assurance that risk management, control and governance processes operate effectively",
      "To express an opinion on whether the financial statements give a true and fair view",
      "To prepare the monthly management accounts",
      "To approve the company's dividend policy",
    ],
    correct: 0,
    explanation: "Internal audit gives independent, objective assurance and consulting on the effectiveness of risk, control and governance. Option 1 is external audit's statutory role; option 2 is an operational finance task that would compromise internal audit's independence; option 3 is a board decision.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-C-17", paper: "SBL", area: "C", type: "mcq",
    stem: "Which of the following is a key difference between internal and external audit?",
    options: [
      "Internal auditors are appointed by shareholders, whereas external auditors are appointed by management",
      "External audit reports to shareholders on the financial statements, whereas internal audit reports to the audit committee/board on risk and control",
      "Only internal auditors are required to be independent of the company",
      "Internal audit's scope is fixed by statute, while external audit's scope is chosen by management",
    ],
    correct: 1,
    explanation: "The core distinction is the audience and remit: external audit serves shareholders on the accounts; internal audit serves the board/audit committee on risk and control. Option 0 reverses the appointment routes; option 2 is wrong because external auditors must be independent too; option 3 reverses which scope is statutory and which is management-influenced.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-C-18", paper: "SBL", area: "C", type: "mcq",
    stem: "Under good corporate governance, an audit committee should be composed of:",
    options: [
      "Independent non-executive directors",
      "Executive directors only",
      "The external audit partners",
      "A group that includes the chief executive and finance director",
    ],
    correct: 0,
    explanation: "An audit committee should consist of independent non-executive directors so it can oversee management and the auditors objectively. Option 1 destroys independence; option 2 confuses those who are audited/appointed with those who oversee; option 3 places the very executives being monitored on the committee, creating a self-review conflict.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "SBL3-C-19", paper: "SBL", area: "C", type: "mcq",
    stem: "The head of internal audit at Verrindale Co is asked to design and implement the controls for a new sales system, and later to audit those same controls. What is the main threat this creates?",
    options: [
      "Intimidation, because operational staff may pressure the auditor",
      "Advocacy, because the auditor would be promoting the company's interests",
      "Familiarity, because the auditor has worked with the staff for years",
      "Self-review, because the auditor would be assessing controls they designed themselves",
    ],
    correct: 3,
    explanation: "Auditing work you performed yourself is a classic self-review threat that undermines objectivity. Intimidation involves pressure or threats; advocacy involves championing a position; familiarity arises from close relationships — none of which is the central issue when the auditor reviews their own design work.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "SBL3-C-20", paper: "SBL", area: "C", type: "mcq",
    stem: "The primary purpose of a business continuity plan (BCP) is to:",
    options: [
      "Eliminate all operational risk from the business",
      "Guarantee the organisation will never suffer a disruptive incident",
      "Enable the organisation to maintain or quickly resume critical operations after a disruptive event",
      "Remove the need for the organisation to carry insurance cover",
    ],
    correct: 2,
    explanation: "A BCP is about resilience and recovery — keeping or restoring critical activities when disruption strikes. Option 0 overstates the aim, since risk cannot be fully eliminated; option 1 promises the impossible; option 3 wrongly treats a BCP as a substitute for insurance rather than a complement to it.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-C-21", paper: "SBL", area: "C", type: "mcq",
    stem: "In business continuity planning, the 'recovery time objective' (RTO) is:",
    options: [
      "The maximum acceptable amount of data loss, measured as a period of time",
      "The elapsed time since the last full backup was taken",
      "The target maximum duration allowed to restore a critical process after a disruption",
      "The total capital cost of building a disaster recovery site",
    ],
    correct: 2,
    explanation: "RTO is the targeted time within which a critical process must be recovered. Option 0 describes the recovery point objective (RPO), which concerns tolerable data loss; option 1 is simply backup age; option 3 is a cost figure, unrelated to the timing target.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-C-22", paper: "SBL", area: "C", type: "mcq",
    stem: "The three elements of the 'fraud triangle' are:",
    options: [
      "Planning, execution and concealment",
      "Detection, prevention and correction",
      "Skill, resources and time",
      "Opportunity, incentive/pressure and rationalisation",
    ],
    correct: 3,
    explanation: "The fraud triangle explains why individuals commit fraud: opportunity, incentive or pressure, and rationalisation. Option 0 describes stages of committing a fraud, not its drivers; option 1 lists categories of control; option 2 lists generic resources, none of which forms the recognised model.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "SBL3-C-23", paper: "SBL", area: "C", type: "mcq",
    stem: "An accounts clerk facing large personal debts works in a role where no segregation of duties exists over cash. The absence of segregation of duties most directly represents which element of the fraud triangle?",
    options: [
      "Opportunity",
      "Incentive/pressure",
      "Rationalisation",
      "Detection",
    ],
    correct: 0,
    explanation: "A control weakness such as missing segregation of duties creates the opportunity to commit and conceal fraud. The personal debts are the incentive/pressure; rationalisation would be the clerk's self-justification for acting; detection is not an element of the triangle at all.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "SBL3-C-24", paper: "SBL", area: "C", type: "mcq",
    stem: "Which of the following is primarily a fraud DETECTION control rather than a prevention control?",
    options: [
      "Segregation of duties over cash handling",
      "Regular independent bank reconciliations that flag unexplained differences",
      "Requiring dual authorisation for payments above a threshold",
      "Pre-employment vetting of finance staff",
    ],
    correct: 1,
    explanation: "Independent reconciliations detect anomalies after transactions occur, so they are detective controls. Segregation of duties, dual authorisation and pre-employment vetting all operate before or during a transaction to stop fraud happening, making them preventive controls.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-C-25", paper: "SBL", area: "C", type: "mcq",
    stem: "A confidential whistleblowing hotline primarily helps an organisation by:",
    options: [
      "Providing a safe channel for staff to report suspected wrongdoing, improving early detection of fraud and misconduct",
      "Removing the need for an internal audit function",
      "Guaranteeing that anonymity can never be breached under any circumstances",
      "Transferring legal liability for any fraud onto individual employees",
    ],
    correct: 0,
    explanation: "Whistleblowing arrangements surface concerns early through a trusted, confidential route, aiding detection and deterrence. Option 1 wrongly treats it as a substitute for internal audit; option 2 overstates the confidentiality guarantee; option 3 misrepresents its purpose, which is not to shift legal liability.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-C-26", paper: "SBL", area: "C", type: "mcq",
    stem: "At Cadmoor Co, reports to the whistleblowing line are received and investigated by the same operational managers whose departments are most often the subject of the complaints. What is the main weakness of this arrangement?",
    options: [
      "The line is too expensive to operate",
      "Employees are likely to report too many trivial matters",
      "The company is legally required to publish every report it receives",
      "Reports lack independent handling, so genuine concerns about those managers may be suppressed and staff will lose trust in the channel",
    ],
    correct: 3,
    explanation: "Letting the potential subjects investigate complaints against themselves removes independence and deters honest reporting. Cost (option 0) and over-reporting (option 1) are not the core governance flaw here, and option 2 invents a publication requirement that does not exist.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "SBL3-C-27", paper: "SBL", area: "C", type: "mcq",
    stem: "In the 'three lines of defence' model, which function forms the THIRD line?",
    options: [
      "Operational management, which owns and manages risk day to day",
      "Internal audit, providing independent assurance",
      "The risk and compliance functions that oversee and challenge risk",
      "The external auditors appointed by shareholders",
    ],
    correct: 1,
    explanation: "The third line is internal audit, giving independent assurance over the first two lines. Operational management is the first line; risk and compliance oversight is the second line; the external auditors sit outside the three-lines model entirely.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "SBL3-C-28", paper: "SBL", area: "C", type: "mcq",
    stem: "Which statement best reflects good practice in risk reporting to the board?",
    options: [
      "Only risks that have already crystallised should be reported",
      "Risk reports should exclude emerging risks to avoid alarming the directors",
      "Reporting should be regular and forward-looking, covering both current and emerging risks against appetite",
      "Risk should be formally reported to the board only once every three years",
    ],
    correct: 2,
    explanation: "Effective risk reporting is timely, forward-looking and set against the board's appetite so directors can act. Option 0 is purely backward-looking; option 1 hides exactly the emerging risks the board needs to see; option 3 is far too infrequent for meaningful oversight.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-C-29", paper: "SBL", area: "C", type: "mcq",
    stem: "When assessing a portfolio of risks at entity level, why can it be misleading to evaluate each risk purely in isolation?",
    options: [
      "Because assessing risks individually always overstates total exposure",
      "Because risks never interact with one another in practice",
      "Because regulators prohibit the assessment of individual risks",
      "Because risks can be correlated — several may crystallise together or compound one another, so aggregate exposure can exceed the sum of separately-assessed risks",
    ],
    correct: 3,
    explanation: "Correlation and compounding mean the whole can be riskier than the sum of the parts, which is a key reason for an entity-wide ERM view. Option 0 wrongly assumes isolation always overstates (it can understate); option 1 denies interaction; option 2 invents a non-existent prohibition.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "SBL3-C-30", paper: "SBL", area: "C", type: "mcq",
    stem: "A firewall that blocks unauthorised network access before it can occur is an example of which type of control?",
    options: [
      "Detective",
      "Corrective",
      "Preventive",
      "Directive",
    ],
    correct: 2,
    explanation: "A firewall stops the unwanted event happening, so it is preventive. A detective control identifies incidents after they occur; a corrective control restores the position once an incident has happened; a directive control encourages a desired outcome, such as a policy or instruction.",
    marks: 2, difficulty: "medium",
  },

  /* ══════════════ AREA D — Technology, data & innovation (30) ══════════════ */

  {
    id: "SBL3-D-01", paper: "SBL", area: "D", type: "mcq",
    stem: "'Big data' is commonly described using the 'Vs'. Which set correctly names four of them?",
    options: [
      "Volume, velocity, variety and veracity",
      "Value, volume, version and validity",
      "Velocity, volatility, virtue and volume",
      "Variety, vision, veracity and value",
    ],
    correct: 0,
    explanation: "The core big-data characteristics are volume, velocity, variety and veracity (with value sometimes added). The other options mix in invented or unrelated terms such as version, volatility, virtue and vision, none of which is a recognised defining characteristic.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "SBL3-D-02", paper: "SBL", area: "D", type: "mcq",
    stem: "A social-media analytics platform must process millions of posts arriving every second. The fact that the data streams in at very high speed illustrates which 'V' of big data?",
    options: [
      "Volume",
      "Velocity",
      "Variety",
      "Veracity",
    ],
    correct: 1,
    explanation: "Velocity refers to the speed at which data is generated and must be processed. Volume is the sheer quantity of data; variety is the mix of formats (text, image, video); veracity is the trustworthiness of the data — none of which captures 'speed'.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-D-03", paper: "SBL", area: "D", type: "mcq",
    stem: "In the context of big data, 'veracity' refers to:",
    options: [
      "The sheer quantity of data collected",
      "The trustworthiness, accuracy and reliability of the data",
      "The speed at which the data is generated",
      "The range of different data formats involved",
    ],
    correct: 1,
    explanation: "Veracity is about how far the data can be trusted and relied upon for decisions. Option 0 describes volume; option 2 describes velocity; option 3 describes variety — the three other Vs, none of which addresses data quality.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "SBL3-D-04", paper: "SBL", area: "D", type: "mcq",
    stem: "The four commonly cited types of data analytics, in increasing order of sophistication, are:",
    options: [
      "Predictive, prescriptive, descriptive, diagnostic",
      "Diagnostic, descriptive, prescriptive, predictive",
      "Descriptive, diagnostic, predictive, prescriptive",
      "Prescriptive, predictive, diagnostic, descriptive",
    ],
    correct: 2,
    explanation: "The progression runs descriptive (what happened) → diagnostic (why) → predictive (what will happen) → prescriptive (what to do). The other options scramble this sequence, for example placing prescriptive or predictive before the descriptive and diagnostic foundations they build upon.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-D-05", paper: "SBL", area: "D", type: "mcq",
    stem: "An airline's system not only forecasts next month's passenger demand but also recommends the specific fares and seat allocations that will maximise revenue. The recommendation step is an example of:",
    options: [
      "Descriptive analytics",
      "Diagnostic analytics",
      "Predictive analytics",
      "Prescriptive analytics",
    ],
    correct: 3,
    explanation: "Recommending the optimal course of action is prescriptive analytics. Forecasting demand is predictive; describing past demand would be descriptive; explaining why demand moved would be diagnostic. Only prescriptive analytics tells the airline what to do.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "SBL3-D-06", paper: "SBL", area: "D", type: "mcq",
    stem: "A dashboard summarising last quarter's sales by region and by product is primarily an example of:",
    options: [
      "Descriptive analytics — summarising what has happened",
      "Predictive analytics — forecasting what will happen",
      "Prescriptive analytics — recommending what action to take",
      "Diagnostic analytics — explaining why it happened",
    ],
    correct: 0,
    explanation: "Reporting historical results is descriptive analytics. It does not forecast the future (predictive), recommend actions (prescriptive), or explain the underlying causes (diagnostic); it simply describes what has already occurred.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-D-07", paper: "SBL", area: "D", type: "mcq",
    stem: "Analysing data to understand WHY sales fell in a particular region is best described as:",
    options: [
      "Diagnostic analytics",
      "Descriptive analytics",
      "Predictive analytics",
      "Prescriptive analytics",
    ],
    correct: 0,
    explanation: "Investigating causes — the 'why' — is diagnostic analytics. Descriptive analytics only reports that sales fell; predictive analytics forecasts future sales; prescriptive analytics recommends what to do about it.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "SBL3-D-08", paper: "SBL", area: "D", type: "mcq",
    stem: "Which of the following best describes machine learning?",
    options: [
      "Software that follows a fixed set of hand-coded rules that never change",
      "Systems that learn patterns from data and improve their performance on a task without being explicitly programmed for every rule",
      "The physical robots used on a manufacturing production line",
      "A method of encrypting data for secure transmission",
    ],
    correct: 1,
    explanation: "Machine learning derives patterns from data and improves with experience rather than being fully rule-coded. Option 0 describes traditional deterministic programming; option 2 confuses software learning with physical robotics; option 3 describes encryption, an unrelated concept.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-D-09", paper: "SBL", area: "D", type: "mcq",
    stem: "Robotic process automation (RPA) is most suitable for:",
    options: [
      "Making creative strategic decisions on behalf of the board",
      "Removing the need for any internal controls",
      "Automating high-volume, repetitive, rule-based tasks such as data entry and reconciliations",
      "Physically assembling products on a factory line",
    ],
    correct: 2,
    explanation: "RPA excels at structured, repetitive, rule-based digital tasks. It cannot make judgement-based strategic decisions (option 0); it does not replace the need for controls (option 1) and in fact needs its own controls; and it is software, not physical assembly machinery (option 3).",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-D-10", paper: "SBL", area: "D", type: "mcq",
    stem: "A bank trains an AI model to approve loans using ten years of historical lending decisions. Applicants from one particular district are subsequently rejected at a disproportionate rate. What is the most likely governance concern?",
    options: [
      "The model runs too slowly to be commercially useful",
      "The model is too transparent about how it reaches decisions",
      "The cost of cloud storage for the model will be excessive",
      "Algorithmic bias — the model has learned and perpetuated bias present in the historical training data",
    ],
    correct: 3,
    explanation: "Models trained on biased historical data can reproduce and entrench discrimination — algorithmic bias. Processing speed (option 0) and storage cost (option 2) are operational, not the ethical/governance issue; and excessive transparency (option 1) would help, not harm, so it is not the concern.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "SBL3-D-11", paper: "SBL", area: "D", type: "mcq",
    stem: "A key benefit of cloud computing for a growing business is:",
    options: [
      "It removes all cyber-security risk from the organisation",
      "It guarantees that data can never be lost",
      "Scalable, on-demand computing resources paid for as an operating expense rather than a large upfront capital cost",
      "It eliminates the need for any internet connection",
    ],
    correct: 2,
    explanation: "Cloud provides elastic, pay-as-you-go capacity that turns capital spending into operating cost. Option 0 is false — cloud introduces its own security considerations; option 1 overstates resilience; option 3 is the opposite of the truth, since cloud services depend on connectivity.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "SBL3-D-12", paper: "SBL", area: "D", type: "mcq",
    stem: "A company subscribes to a ready-to-use accounting application that is hosted, maintained and updated entirely by the provider and accessed over the internet. This is an example of:",
    options: [
      "Infrastructure as a Service (IaaS)",
      "Software as a Service (SaaS)",
      "Platform as a Service (PaaS)",
      "On-premise licensing",
    ],
    correct: 1,
    explanation: "Consuming a finished application over the internet is Software as a Service. IaaS provides raw compute and storage the customer configures; PaaS provides a platform on which the customer builds its own applications; on-premise licensing means installing and running software on the company's own hardware.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-D-13", paper: "SBL", area: "D", type: "mcq",
    stem: "The 'Internet of Things' (IoT) refers to:",
    options: [
      "A network of physical devices embedded with sensors and connectivity that collect and exchange data",
      "A social network used exclusively by technology companies",
      "The complete set of websites reachable through a search engine",
      "A category of accounting software for inventory management",
    ],
    correct: 0,
    explanation: "IoT describes everyday physical objects fitted with sensors and network connections that gather and share data. Option 1 invents a niche social network; option 2 describes the indexed web; option 3 confuses IoT with a specific software category — none captures connected physical devices.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-D-14", paper: "SBL", area: "D", type: "mcq",
    stem: "The three core objectives of information security are commonly summarised as:",
    options: [
      "Cost, integrity and availability",
      "Confidentiality, integration and accuracy",
      "Control, insurance and authorisation",
      "Confidentiality, integrity and availability",
    ],
    correct: 3,
    explanation: "The security 'CIA triad' is confidentiality, integrity and availability. The other options swap in plausible but incorrect terms — cost, integration, accuracy, control, insurance, authorisation — none of which is part of the recognised triad.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "SBL3-D-15", paper: "SBL", area: "D", type: "mcq",
    stem: "Staff at Torrandale Co receive an email appearing to come from the CEO, urgently asking them to transfer funds to a new supplier account. This social-engineering attempt is best described as:",
    options: [
      "A distributed denial-of-service (DDoS) attack",
      "A ransomware infection",
      "An SQL injection",
      "A phishing attack (specifically spear-phishing / CEO fraud)",
    ],
    correct: 3,
    explanation: "Deceiving staff with a spoofed trusted-sender email to trigger a payment is phishing, here targeted CEO-fraud. A DDoS floods systems to make them unavailable; ransomware encrypts data for a ransom; SQL injection exploits a database query flaw — none of which involves impersonating the CEO by email.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "SBL3-D-16", paper: "SBL", area: "D", type: "mcq",
    stem: "Which is the most effective combination of measures to reduce the risk of staff falling for phishing attacks?",
    options: [
      "Regular security-awareness training combined with multi-factor authentication",
      "Increasing the marketing budget",
      "Storing all corporate data on a single unencrypted server",
      "Disabling the internal audit function",
    ],
    correct: 0,
    explanation: "Training reduces the human vulnerability and multi-factor authentication limits the damage if credentials are compromised — a strong, complementary pairing. Marketing spend is irrelevant; a single unencrypted server increases exposure; and removing internal audit weakens assurance rather than improving security.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-D-17", paper: "SBL", area: "D", type: "mcq",
    stem: "A 'disintermediation' business model creates value by:",
    options: [
      "Adding extra layers of wholesalers between the producer and the customer",
      "Charging customers a fixed annual licence fee for physical goods",
      "Removing intermediaries so producers deal directly with customers, often via a digital platform",
      "Outsourcing all production to a single external supplier",
    ],
    correct: 2,
    explanation: "Disintermediation cuts out middlemen so producers reach customers directly, frequently online. Option 0 describes re-intermediation, the opposite; option 1 describes a subscription/licensing model; option 3 describes outsourcing production, which is unrelated to shortening the distribution chain.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-D-18", paper: "SBL", area: "D", type: "mcq",
    stem: "'Disruptive innovation' typically describes:",
    options: [
      "A minor upgrade to an existing premium product aimed at existing customers",
      "An innovation that starts in a simpler or cheaper form and eventually displaces established market leaders",
      "Any new product that fails commercially in the market",
      "A government regulation that bans an existing technology",
    ],
    correct: 1,
    explanation: "Disruptive innovation usually begins at the low end or in a new market and moves upmarket to overtake incumbents. Option 0 describes sustaining innovation for existing customers; option 2 confuses disruption with mere failure; option 3 describes a regulatory action, not an innovation.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "SBL3-D-19", paper: "SBL", area: "D", type: "mcq",
    stem: "Applying Porter's thinking, an information system is most likely to deliver sustainable competitive advantage when it:",
    options: [
      "Is bought off-the-shelf and is identical to competitors' systems",
      "Reconfigures the value chain or raises buyers' switching costs in ways rivals find hard and costly to imitate",
      "Is simply the most expensive system available, regardless of fit",
      "Automates a task without changing the firm's cost or differentiation position",
    ],
    correct: 1,
    explanation: "Advantage is sustainable when the system changes cost or differentiation in ways competitors cannot easily copy — for example by locking in customers. Option 0 offers nothing distinctive; option 3 delivers no strategic shift; option 2 confuses high spend with advantage.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "SBL3-D-20", paper: "SBL", area: "D", type: "mcq",
    stem: "In Porter's value chain, an investment in a data-analytics platform used across procurement, operations and marketing is best viewed as:",
    options: [
      "A primary activity only, affecting one stage of the chain",
      "Irrelevant to the value chain",
      "A means of increasing costs with no linkage benefit",
      "A support activity (technology development/infrastructure) that can strengthen linkages across several primary activities",
    ],
    correct: 3,
    explanation: "Technology development is a support activity that can enhance and connect multiple primary activities. Option 0 wrongly confines it to a single primary activity; option 1 ignores its cross-cutting role; option 2 dismisses the very linkage benefits that make such investment valuable.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-D-21", paper: "SBL", area: "D", type: "mcq",
    stem: "Digital transformation is best understood as:",
    options: [
      "Buying new laptops for the finance team",
      "Moving the company's paper files into a single PDF archive",
      "Fundamentally rethinking business models, processes and customer experience using digital technology",
      "Replacing the external auditors with software",
    ],
    correct: 2,
    explanation: "Digital transformation is a strategic reshaping of how the organisation operates and creates value using technology. Options 0 and 1 are narrow, tactical IT purchases or digitising documents — not transformation — and option 3 misapplies the term to an unrelated audit function.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-D-22", paper: "SBL", area: "D", type: "mcq",
    stem: "The Chief Information Officer (CIO) is primarily responsible for:",
    options: [
      "Leading the organisation's information technology strategy and systems",
      "Auditing and expressing an opinion on the financial statements",
      "Setting the company's dividend policy",
      "Managing the company's physical property portfolio",
    ],
    correct: 0,
    explanation: "The CIO leads IT strategy, systems and infrastructure in support of business objectives. Option 1 is the external auditor's role; option 2 is a board decision; option 3 is a facilities/property function, none of which is the CIO's core remit.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "SBL3-D-23", paper: "SBL", area: "D", type: "mcq",
    stem: "An organisation appoints a Chief Digital Officer (CDO) alongside its existing CIO. The CDO's distinctive focus is typically to:",
    options: [
      "Drive digital transformation of business models and customer experience, rather than run day-to-day IT infrastructure",
      "Take over responsibility for the statutory external audit",
      "Replace the CIO's team and personally manage server maintenance",
      "Prepare the consolidated financial statements",
    ],
    correct: 0,
    explanation: "A CDO champions strategic digital change and customer-facing innovation, complementing the CIO's stewardship of core IT. Option 1 confuses the role with audit; option 2 reduces a strategic role to operational IT maintenance; option 3 is a finance-function task unrelated to the CDO.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "SBL3-D-24", paper: "SBL", area: "D", type: "mcq",
    stem: "A Gantt chart is most useful in project management for:",
    options: [
      "Calculating the net present value of the project",
      "Identifying the presence of the fraud triangle in the project team",
      "Displaying project activities against a timeline, showing their durations and how they overlap",
      "Ranking potential suppliers by their price",
    ],
    correct: 2,
    explanation: "A Gantt chart is a bar chart of activities plotted against time, showing durations and overlaps to help schedule and monitor a project. Option 0 is an appraisal technique; option 1 relates to fraud risk; option 3 is a procurement comparison — none is the chart's purpose.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-D-25", paper: "SBL", area: "D", type: "mcq",
    stem: "In network (critical path) analysis, the 'critical path' is:",
    options: [
      "The cheapest sequence of activities in the project",
      "The path containing the most activities, regardless of their durations",
      "Any path that can be delayed without affecting the project",
      "The longest sequence of dependent activities, which determines the minimum project duration",
    ],
    correct: 3,
    explanation: "The critical path is the longest chain of dependent activities and therefore sets the shortest possible project duration; any delay on it delays the whole project. Option 0 confuses time with cost; option 1 counts activities rather than duration; option 2 describes a path with float, the opposite of critical.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-D-26", paper: "SBL", area: "D", type: "mcq",
    stem: "An activity in a project network has a float (slack) of five days. This means:",
    options: [
      "The activity lies on the critical path",
      "The activity can be delayed by up to five days without delaying overall project completion",
      "The activity must start exactly five days early",
      "The project as a whole will finish five days late",
    ],
    correct: 1,
    explanation: "Float is the amount by which a non-critical activity can slip without pushing back the project end date. Option 0 is wrong because critical-path activities have zero float; option 2 misreads float as a scheduling requirement; option 3 wrongly assumes the delay flows straight through to the finish date.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "SBL3-D-27", paper: "SBL", area: "D", type: "mcq",
    stem: "'Fintech' refers to:",
    options: [
      "Traditional bank branches that operate without any technology",
      "A specific type of statutory financial statement",
      "Technology-enabled innovation in financial services, such as mobile payments and peer-to-peer lending",
      "A government tax levied on technology firms",
    ],
    correct: 2,
    explanation: "Fintech is the use of technology to deliver and reshape financial services. Option 0 describes traditional banking, the incumbent fintech disrupts; option 1 confuses it with financial reporting; option 3 invents a tax — neither reflects the meaning of fintech.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "SBL3-D-28", paper: "SBL", area: "D", type: "mcq",
    stem: "Which of the following is the clearest example of fintech disrupting a traditional service?",
    options: [
      "A peer-to-peer lending platform matching borrowers and lenders directly, bypassing banks",
      "A bank extending the opening hours of its branches",
      "A company issuing paper cheques to pay its suppliers",
      "A firm moving its ledgers from one spreadsheet file to another",
    ],
    correct: 0,
    explanation: "A peer-to-peer platform uses technology to disintermediate banks from lending — classic fintech disruption. Longer branch hours (option 1) is incremental; paper cheques (option 2) are the traditional method being disrupted; and swapping spreadsheets (option 3) is a trivial internal change, not disruption.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-D-29", paper: "SBL", area: "D", type: "mcq",
    stem: "A distributed ledger (blockchain) provides assurance over recorded transactions mainly because:",
    options: [
      "A single central administrator can edit past records whenever needed",
      "Transactions are recorded across many nodes and cryptographically linked, so retrospective tampering is evident and very difficult",
      "It stores all of the data on one company-owned server",
      "It guarantees that every transaction recorded is commercially profitable",
    ],
    correct: 1,
    explanation: "Distribution across nodes plus cryptographic linking makes the record tamper-evident and hard to alter after the fact, which is the source of trust. Option 0 describes central mutability, the opposite of a blockchain's strength; option 2 describes centralised storage; option 3 confuses record integrity with commercial outcome.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "SBL3-D-30", paper: "SBL", area: "D", type: "mcq",
    stem: "Under good data-governance practice, personal customer data should be:",
    options: [
      "Shared freely with any third party in order to maximise revenue",
      "Retained indefinitely regardless of the purpose for which it was gathered",
      "Collected in the largest possible quantity for unspecified future use",
      "Collected for specified, legitimate purposes, kept accurate and secure, and retained no longer than necessary",
    ],
    correct: 3,
    explanation: "Sound data governance follows principles of purpose limitation, accuracy, security and storage limitation. Option 0 breaches confidentiality and lawful-sharing rules; option 1 breaches retention limits; option 2 breaches data minimisation — each contradicts recognised data-protection principles.",
    marks: 2, difficulty: "medium",
  },

  /* ══════════════ AREA E — Professional skills (20) ══════════════ */

  {
    id: "SBL3-E-01", paper: "SBL", area: "E", type: "mcq",
    stem: "In SBL, a proportion of marks reward professional skills. Which list correctly names the five professional skills assessed?",
    options: [
      "Leadership, teamwork, numeracy, planning and ethics",
      "Reading, writing, speaking, listening and counting",
      "Governance, strategy, risk, finance and technology",
      "Communication, commercial acumen, analysis, scepticism and evaluation",
    ],
    correct: 3,
    explanation: "The five SBL professional skills are communication, commercial acumen, analysis, scepticism and evaluation. Option 0 lists general competencies; option 1 lists basic literacy activities; option 2 lists syllabus knowledge areas — none matches the assessed professional skills.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "SBL3-E-02", paper: "SBL", area: "E", type: "mcq",
    stem: "Demonstrating the professional skill of COMMUNICATION in an answer mainly means:",
    options: [
      "Writing as many words as possible on the topic",
      "Conveying information clearly and persuasively in a format, tone and structure appropriate to the audience and purpose",
      "Using as much technical jargon as possible to sound expert",
      "Copying the scenario text verbatim into the answer",
    ],
    correct: 1,
    explanation: "Communication is judged on clarity, appropriate format and audience awareness, not length. Option 0 mistakes volume for quality; option 2 confuses jargon with clear expression; option 3 reproduces the scenario instead of communicating a message to the reader.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-E-03", paper: "SBL", area: "E", type: "mcq",
    stem: "You are asked to draft 'briefing notes for the chair to use when addressing shareholders at the AGM'. The strongest demonstration of the communication skill is to:",
    options: [
      "Use a clear briefing-note format with headings and concise points, pitched for a lay shareholder audience and avoiding unexplained technical jargon",
      "Write a detailed technical memorandum packed with accounting-standard references for the shareholders",
      "Produce an unstructured stream containing every fact from the scenario",
      "Reply in the form of a personal email addressed to the examiner",
    ],
    correct: 0,
    explanation: "Good communication matches format and language to the audience — here, accessible briefing notes for shareholders. Option 1 pitches at the wrong technical level; option 2 lacks structure and selection; option 3 uses an inappropriate format and wrong recipient, ignoring the requirement.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "SBL3-E-04", paper: "SBL", area: "E", type: "mcq",
    stem: "The professional skill of COMMERCIAL ACUMEN is best demonstrated by:",
    options: [
      "Reciting textbook models without reference to the specific organisation",
      "Ignoring the organisation's resource constraints when recommending action",
      "Showing awareness of the organisation's context and using judgement to identify practical, realistic options that recognise real-world constraints and opportunities",
      "Always recommending the cheapest possible option, regardless of strategy",
    ],
    correct: 2,
    explanation: "Commercial acumen is practical business judgement grounded in the organisation's real situation. Option 0 is generic and context-free; option 1 ignores feasibility; option 3's fixation on lowest cost overlooks strategic value — none reflects genuine commercial awareness.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-E-05", paper: "SBL", area: "E", type: "mcq",
    stem: "Which recommendation best shows commercial acumen?",
    options: [
      "Adopt every strategic model in the syllabus simultaneously",
      "Prioritise the two initiatives that fit the company's limited budget and skills, and sequence them realistically",
      "Recommend an option that the company clearly cannot afford",
      "Refuse to make any recommendation at all",
    ],
    correct: 1,
    explanation: "Prioritising and sequencing within real constraints shows practical business judgement. Option 0 is unfocused and unrealistic; option 2 ignores affordability; option 3 dodges the decision the board needs, none of which demonstrates commercial acumen.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "SBL3-E-06", paper: "SBL", area: "E", type: "mcq",
    stem: "The professional skill of ANALYSIS requires a candidate to:",
    options: [
      "Break information down, examine relationships within it, and draw out what the data means for the organisation",
      "List facts from the scenario without interpreting them",
      "State a conclusion with no supporting reasoning",
      "Focus only on reproducing memorised definitions",
    ],
    correct: 0,
    explanation: "Analysis means decomposing information and interpreting its significance. Option 1 merely restates facts; option 2 asserts a conclusion without the analytical work behind it; option 3 substitutes rote recall for genuine examination of the scenario.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-E-07", paper: "SBL", area: "E", type: "mcq",
    stem: "What best distinguishes the professional skill of EVALUATION from the skill of ANALYSIS?",
    options: [
      "Evaluation means summarising the scenario, while analysis means ignoring it",
      "They are identical skills given two different names",
      "Analysis breaks down and examines information, whereas evaluation weighs the merits and drawbacks to reach a balanced, justified judgement",
      "Evaluation means agreeing with management, while analysis means disagreeing with them",
    ],
    correct: 2,
    explanation: "Analysis examines and interprets; evaluation goes further to weigh options and reach a reasoned judgement. Option 0 mischaracterises both; option 1 wrongly treats them as the same; option 3 confuses evaluation with a stance for or against management rather than balanced judgement.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "SBL3-E-08", paper: "SBL", area: "E", type: "mcq",
    stem: "Professional SCEPTICISM, as rewarded in SBL, is best described as:",
    options: [
      "Assuming that management is always dishonest",
      "Accepting all information provided without question",
      "Avoiding any challenge in order to preserve good working relationships",
      "A questioning mindset that probes assumptions, seeks corroborating evidence and does not accept assertions at face value",
    ],
    correct: 3,
    explanation: "Scepticism is an evidence-seeking, questioning attitude. Option 0 overreaches into presumed dishonesty; option 1 is credulity, the opposite of scepticism; option 2 avoids the very challenge scepticism requires. Only option 3 captures a balanced questioning mindset.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-E-09", paper: "SBL", area: "E", type: "mcq",
    stem: "Which of the following responses shows a LACK of professional scepticism?",
    options: [
      "Asking for evidence to support the sales forecast",
      "Cross-checking a claim against independent data",
      "Accepting the CEO's optimistic projection as fact without seeking any supporting evidence",
      "Questioning an assumption that appears unrealistic",
    ],
    correct: 2,
    explanation: "Taking a projection at face value with no corroboration is exactly the absence of scepticism. Options 0, 1 and 3 all involve seeking evidence, corroborating claims or challenging assumptions — behaviours that demonstrate, rather than lack, professional scepticism.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "SBL3-E-10", paper: "SBL", area: "E", type: "mcq",
    stem: "Management asserts that a new product will 'definitely capture 40% of the market in its first year'. A sceptical adviser would first:",
    options: [
      "Include the 40% figure in the plan unchanged",
      "Reject the entire project outright as dishonest",
      "Double the figure to make the plan more ambitious",
      "Ask what evidence and assumptions support the 40% and test them against market data and competitor behaviour",
    ],
    correct: 3,
    explanation: "Scepticism means probing the basis for a bold claim before relying on it. Option 0 accepts it uncritically; option 1 leaps to rejection without evidence; option 2 replaces one unsupported figure with another. Only option 3 tests the assertion against evidence.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-E-11", paper: "SBL", area: "E", type: "mcq",
    stem: "A board keeps investing more money in a clearly failing project, reasoning that it has 'already spent so much to get this far'. This reasoning reflects:",
    options: [
      "Professional scepticism being correctly applied",
      "Sunk-cost bias, which sound analysis should challenge by focusing only on future costs and benefits",
      "Strong commercial acumen",
      "Effective evaluation of the options",
    ],
    correct: 1,
    explanation: "Throwing good money after bad because of past spend is the sunk-cost fallacy; decisions should rest on incremental future costs and benefits. Option 0 is the opposite of what is happening; options 2 and 3 misdescribe biased reasoning as good judgement or evaluation.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "SBL3-E-12", paper: "SBL", area: "E", type: "mcq",
    stem: "Which answer best demonstrates the professional skill of EVALUATION?",
    options: [
      "Weighing the advantages and disadvantages of the proposal and reaching a reasoned, balanced conclusion",
      "Listing only the advantages of the proposal",
      "Stating a conclusion with no discussion of any drawbacks",
      "Describing the proposal in detail but offering no judgement",
    ],
    correct: 0,
    explanation: "Evaluation weighs pros and cons and lands on a justified conclusion. Option 1 is one-sided; option 2 gives a verdict without support; option 3 stops at description without the judgement that evaluation demands.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-E-13", paper: "SBL", area: "E", type: "mcq",
    stem: "A recommendation stating 'on balance the benefits outweigh the risks because..., though management should monitor X' primarily demonstrates the skill of:",
    options: [
      "Evaluation",
      "Data entry",
      "Rote memorisation",
      "Avoidance of any conclusion",
    ],
    correct: 0,
    explanation: "Weighing benefits against risks and reaching a qualified, justified conclusion is evaluation. Option 1 is a clerical task; option 2 is recall of facts; option 3 is the opposite of what the recommendation does, since it clearly reaches a conclusion.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "SBL3-E-14", paper: "SBL", area: "E", type: "mcq",
    stem: "When structuring written advice for a board, the most effective approach is to:",
    options: [
      "Present unstructured paragraphs with no headings so that directors are forced to read everything",
      "Use clear headings and a logical flow, lead with the key message, and support recommendations with reasoning tailored to the board's decision",
      "Bury the recommendation in the final sentence with no supporting justification",
      "Provide only raw data tables and leave the board to work out the implications",
    ],
    correct: 1,
    explanation: "Board advice should be structured, lead with the message and justify recommendations for the decision at hand. Option 0 makes the reader work unnecessarily; option 2 hides the recommendation; option 3 abdicates the adviser's role of interpreting the data.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-E-15", paper: "SBL", area: "E", type: "mcq",
    stem: "A recommendation relies on a single quarter of sales data drawn from just one region. The most professionally sceptical treatment of this data is to:",
    options: [
      "Present the resulting conclusion as certain and fully reliable",
      "Discard all quantitative analysis as inherently useless",
      "Confidently extrapolate the quarter's figures to every region",
      "Acknowledge the data's limitations — a small sample, a short period and a single region — and caveat the conclusion accordingly",
    ],
    correct: 3,
    explanation: "Recognising and flagging data limitations before relying on a conclusion is sound scepticism. Option 0 overstates reliability; option 1 over-reacts by rejecting all data; option 2 (extrapolating) ignores the very limitations that should temper the conclusion.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "SBL3-E-16", paper: "SBL", area: "E", type: "mcq",
    stem: "A 'balanced' recommendation to the board should:",
    options: [
      "Present only the single option that the adviser personally prefers",
      "Avoid mentioning any risks so that the board feels confident",
      "Set out the realistic options with their pros, cons and risks before making a justified recommendation",
      "Leave the decision entirely open, offering no recommendation at all",
    ],
    correct: 2,
    explanation: "Balanced advice considers alternatives and their downsides, then still gives a clear, justified recommendation. Option 0 is one-sided; option 1 conceals risk the board must weigh; option 3 fails to give the guidance the board is seeking.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "SBL3-E-17", paper: "SBL", area: "E", type: "mcq",
    stem: "Good communication means tailoring content to the audience. A report intended for non-financial operational managers should:",
    options: [
      "Be written entirely in accounting-standard terminology",
      "Assume the readers have deep technical knowledge of financial reporting",
      "Contain only numbers, with no accompanying explanation",
      "Explain the financial implications in plain language that is relevant to the managers' decisions",
    ],
    correct: 3,
    explanation: "Effective communication pitches technical content at the audience's level and links it to their decisions. Options 0 and 1 assume expertise the readers lack; option 2 gives figures without the interpretation non-financial managers need to act.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "SBL3-E-18", paper: "SBL", area: "E", type: "mcq",
    stem: "Professional scepticism differs from mere suspicion because it:",
    options: [
      "Assumes that everyone the adviser deals with is lying",
      "Means refusing ever to trust any piece of information",
      "Is an evidence-based questioning attitude rather than a presumption of dishonesty",
      "Requires accepting every claim in order to remain polite",
    ],
    correct: 2,
    explanation: "Scepticism questions and seeks evidence without presuming bad faith, which is what separates it from suspicion. Options 0 and 1 describe suspicion or distrust taken to an extreme; option 3 describes credulity, the opposite failing.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "SBL3-E-19", paper: "SBL", area: "E", type: "mcq",
    stem: "An analyst gathers only the market data that supports the strategy the CEO already favours and sets aside evidence pointing the other way. This behaviour is an example of:",
    options: [
      "Sound evaluation of the evidence",
      "Confirmation bias, which undermines objective analysis and professional scepticism",
      "Strong commercial acumen",
      "Effective communication to the board",
    ],
    correct: 1,
    explanation: "Selectively favouring evidence that confirms a preferred view is confirmation bias, and it corrodes both objective analysis and scepticism. Option 0 mislabels biased selection as sound evaluation; options 2 and 3 attach unrelated skill names to what is in fact a reasoning flaw.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "SBL3-E-20", paper: "SBL", area: "E", type: "mcq",
    stem: "A strong answer that recommends an ambitious expansion demonstrates commercial acumen best when it:",
    options: [
      "Tests the plan against the organisation's actual resources, capabilities and market realities before recommending a feasible way forward",
      "Ignores whether the company can fund or staff the expansion",
      "Recommends expansion simply because a competitor has recently done so",
      "Assumes unlimited resources so that the plan appears bold and impressive",
    ],
    correct: 0,
    explanation: "Commercial acumen grounds ambition in feasibility — resources, capabilities and market conditions. Option 1 ignores funding and staffing constraints; option 2 is imitation without judgement; option 3 relies on unrealistic assumptions, so none reflects sound business judgement.",
    marks: 2, difficulty: "hard",
  },
]
