import type { AccaQuestion } from "@/lib/acca-content"
/* PM bank wave 8a — +75 toward 300 (2026-07-12). */
export const PM_WAVE3A: AccaQuestion[] = [
  /* ═══════════ AREA A — Specialist cost & management accounting (18) ═══════════ */
  {
    id: "PM3-A-01", paper: "PM", area: "A", type: "mcq",
    stem: "Marden Co makes R (20,000 units) and S (2,000 units), each needing 1 direct labour hour per unit. Overheads of $220,000 are driven entirely by production runs: R uses 10 runs and S uses 45. Overheads are currently absorbed on labour hours. By how much per unit is Product S UNDERCOSTED by the current system compared with ABC?",
    options: ["$8", "$10", "$80", "$90"],
    correct: 2,
    explanation: "Traditional charge = $220,000 ÷ 22,000 hrs = $10 per unit for both products. ABC: $220,000 ÷ 55 runs = $4,000 per run; S bears 45 × $4,000 = $180,000 ÷ 2,000 = $90. Undercosting = $90 − $10 = $80 — the high-volume product R cross-subsidises low-volume, run-intensive S. $90 is S's ABC cost (not the difference), $10 is the traditional charge, and $8 is R's overcosting per unit ($10 − $2).",
    marks: 2, difficulty: "hard",
  },
  {
    id: "PM3-A-02", paper: "PM", area: "A", type: "mcq",
    stem: "When designing an ABC system, which cost driver is most appropriate for the materials-handling cost pool?",
    options: ["Machine hours", "Units produced", "Factory floor area occupied", "Number of material movements"],
    correct: 3,
    explanation: "A driver must have a cause-and-effect link with the activity: handling cost is caused each time material is moved. Machine hours and units are volume measures that ignore how often material is shifted, and floor area is a basis for apportioning rent-type costs, not a driver of handling activity.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "PM3-A-03", paper: "PM", area: "A", type: "mcq",
    stem: "Which of the following is an example of activity-based MANAGEMENT (ABM), as opposed to activity-based costing?",
    options: [
      "Calculating a cost-driver rate for each activity cost pool",
      "Re-apportioning service-centre costs to production cost centres",
      "Reporting each activity's cost in the monthly management pack",
      "Redesigning the production layout to eliminate material movements identified as non-value-adding",
    ],
    correct: 3,
    explanation: "ABM uses the insight from ABC to act — eliminating or improving non-value-added activities to cut cost and improve customer value. Calculating driver rates and reporting activity costs are ABC measurement steps, and service-centre re-apportionment is traditional absorption costing, not ABM.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM3-A-04", paper: "PM", area: "A", type: "number",
    stem: "Trelow Co's goods-receiving cost pool is $54,000, driven by 180 supplier deliveries in total. Product G (3,000 units) requires 45 deliveries. Under ABC, what is the receiving cost per unit of Product G, in $?",
    numericAnswer: 4.5, unit: "$",
    explanation: "Rate = $54,000 ÷ 180 = $300 per delivery; G bears 45 × $300 = $13,500 ÷ 3,000 units = $4.50. Absorbing the pool over total units, or dividing the pool by G's units alone, are the classic driver errors.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "PM3-A-05", paper: "PM", area: "A", type: "mcq",
    stem: "A new product has a target cost gap of $8.00 per unit. The design team proposes: substituting a cheaper component with identical functionality (saves $3.20); simplifying assembly (saves $2.75); renegotiating material prices (saves $1.30); and raising the planned selling price by $2.00. Consistent with target costing principles, what gap remains after all VALID actions?",
    options: ["$0.75", "Nil — the gap is fully closed", "$4.80", "$8.00"],
    correct: 0,
    explanation: "Valid gap-closing actions reduce cost without reducing customer value: $3.20 + $2.75 + $1.30 = $7.25, leaving $8.00 − $7.25 = $0.75. Raising the price is not a valid action — the price is set by the market, so counting the $2.00 (giving 'nil') abandons the discipline. $4.80 applies only the first action, and $8.00 wrongly rejects all the actions.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM3-A-06", paper: "PM", area: "A", type: "mcq",
    stem: "Halvern Co will invest $2,000,000 to make a new product and requires a return of 15% per year on the investment. Annual sales will be 25,000 units at a market price of $42. The current design implies a cost of $33 per unit. What is the target cost gap per unit?",
    options: ["$3.00", "$9.00", "$12.00", "$30.00"],
    correct: 0,
    explanation: "Required annual profit = 15% × $2,000,000 = $300,000, i.e. $12 per unit; target cost = $42 − $12 = $30; gap = $33 − $30 = $3.00. $9.00 compares price with current cost and forgets the required return, $12.00 is the required profit itself, and $30.00 is the target cost, not the gap.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "PM3-A-07", paper: "PM", area: "A", type: "mcq",
    stem: "A product's expected lifetime cost is $2,400,000. By the end of the design stage, decisions taken will have COMMITTED 80% of that total, although only 5% will actually have been INCURRED. How much cost is committed but not yet incurred at the end of design?",
    options: ["$120,000", "$480,000", "$1,800,000", "$1,920,000"],
    correct: 2,
    explanation: "Committed = 80% × $2.4m = $1,920,000; incurred = 5% × $2.4m = $120,000; committed but not yet spent = $1,800,000. This is why cost-reduction effort must focus on design. $1,920,000 is total committed cost, $120,000 is the cash incurred, and $480,000 is the 20% still uncommitted.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM3-A-08", paper: "PM", area: "A", type: "number",
    stem: "A product's lifetime estimates are: R&D $180,000; marketing $120,000; production of 40,000 units at a variable cost of $9 per unit; end-of-life disposal $60,000. All units sell at an average price of $20. What is the total LIFE-CYCLE PROFIT, in $?",
    numericAnswer: 80000, unit: "$",
    explanation: "Revenue = 40,000 × $20 = $800,000. Life-cycle costs = 180,000 + 120,000 + 360,000 + 60,000 = $720,000. Profit = $80,000. Omitting R&D or disposal overstates lifetime profitability — the whole point of life-cycle costing.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM3-A-09", paper: "PM", area: "A", type: "mcq",
    stem: "Two products pass through one bottleneck. E: price $60, materials $20, variable labour $16, bottleneck time 0.5 hours. F: price $44, materials $26, variable labour $2, bottleneck time 0.25 hours. How do the rankings compare under throughput accounting versus marginal-costing contribution per bottleneck hour?",
    options: [
      "E ranks first under throughput accounting, but F ranks first on contribution per bottleneck hour",
      "E ranks first under both approaches",
      "F ranks first under both approaches",
      "F ranks first under throughput accounting, but E ranks first on contribution per bottleneck hour",
    ],
    correct: 0,
    explanation: "Throughput (price − materials only) per hour: E = $40 ÷ 0.5 = $80; F = $18 ÷ 0.25 = $72 → E first. Contribution (also deducting variable labour) per hour: E = $24 ÷ 0.5 = $48; F = $16 ÷ 0.25 = $64 → F first. The clash arises because throughput accounting treats labour as fixed; labour-light F looks better only when labour is deducted.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "PM3-A-10", paper: "PM", area: "A", type: "mcq",
    stem: "A factory's cost per bottleneck hour is $60. A new product needs 0.2 bottleneck hours per unit and has a material cost of $18 per unit. What minimum selling price gives a throughput accounting ratio of at least 1.0?",
    options: ["$12", "$30", "$60", "$78"],
    correct: 1,
    explanation: "TPAR = 1 when throughput per hour equals $60, i.e. throughput per unit = $60 × 0.2 = $12, so price = $18 + $12 = $30. $12 is the required throughput but forgets to add back material, $78 adds a full hour's cost to material (ignoring the 0.2 hours), and $60 is the hourly factory cost, not a price.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM3-A-11", paper: "PM", area: "A", type: "mcq",
    stem: "Next month's plan requires: machine group 1 — 15,000 hours (12,500 available); machine group 2 — 9,500 hours (10,000 available); assembly — 10,400 hours (8,000 available). Which resource is the PRIMARY bottleneck?",
    options: [
      "Machine group 1, because its shortfall of 2,500 hours is the largest in absolute terms",
      "Machine group 2, because it has the largest available capacity",
      "The assembly line, because its required hours exceed availability by the greatest percentage",
      "Machine group 1 and assembly jointly, because both are overloaded to the same degree",
    ],
    correct: 2,
    explanation: "Compare utilisation ratios: group 1 = 120%, group 2 = 95%, assembly = 10,400 ÷ 8,000 = 130% — assembly is the most overloaded resource and paces the whole plant. Ranking by absolute hours short (2,500 vs 2,400) ignores relative capacity, group 2 has spare capacity, and the two overloads are not equal in proportion.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "PM3-A-12", paper: "PM", area: "A", type: "mcq",
    stem: "Under the theory of constraints, idle time at a NON-bottleneck resource is best viewed as:",
    options: [
      "A problem that should be eliminated by producing more components for inventory",
      "Acceptable, because producing faster than the bottleneck's pace merely builds work-in-progress",
      "Evidence that the resource is actually the bottleneck",
      "Something that always reduces the throughput accounting ratio",
    ],
    correct: 1,
    explanation: "Output is set by the bottleneck: running non-bottleneck resources flat out just piles up WIP without adding a single unit of saleable throughput, so some idle time there is expected and acceptable. 'Keeping busy' by building inventory is the classic dysfunctional response; a true bottleneck would have no idle time.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "PM3-A-13", paper: "PM", area: "A", type: "mcq",
    stem: "Rendal Co's environmental costs this year were: staff environmental training $8,000; effluent sampling and testing $5,000; disposal of contaminated waste captured by its filters $12,000; decontaminating a chemical spill inside the plant $9,000; a regulator's fine for river pollution $30,000. What is the total of the INTERNAL FAILURE costs?",
    options: ["$51,000", "$26,000", "$21,000", "$12,000"],
    correct: 2,
    explanation: "Internal failure costs deal with contamination caught BEFORE release: filtered-waste disposal $12,000 + in-plant spill clean-up $9,000 = $21,000. Training is prevention, effluent testing is detection, and the fine is an external failure cost ($51,000 wrongly adds the fine; $26,000 wrongly adds the testing; $12,000 misses the spill).",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM3-A-14", paper: "PM", area: "A", type: "mcq",
    stem: "Which of the following is an environmental PREVENTION cost?",
    options: [
      "Reprocessing a batch contaminated during production",
      "A fine imposed by the environmental regulator",
      "Redesigning a process to eliminate the use of a toxic solvent",
      "Laboratory testing of effluent samples",
    ],
    correct: 2,
    explanation: "Prevention costs are incurred to stop environmental damage arising in the first place — redesigning the process removes the hazard at source. Reprocessing a contaminated batch is internal failure, the fine is external failure, and effluent testing is a detection (appraisal) cost.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "PM3-A-15", paper: "PM", area: "A", type: "mcq",
    stem: "Verlan Co's waste-treatment cost of $96,000 is driven by kilograms of hazardous waste (8,000 kg in total). Product H (4,000 units) generates 3,200 kg; other products total 12,000 units. Under environmental ABC, the waste-treatment cost per unit of H is:",
    options: ["$6.00", "$9.60", "$12.00", "$24.00"],
    correct: 1,
    explanation: "Rate = $96,000 ÷ 8,000 kg = $12 per kg; H bears 3,200 × $12 = $38,400 ÷ 4,000 units = $9.60. $6.00 is the blanket charge over all 16,000 units — hiding H's true environmental burden; $12.00 splits the pool 50:50 between H and the rest; $24.00 charges the whole pool to H.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM3-A-16", paper: "PM", area: "A", type: "mcq",
    stem: "Ferndale Bank applies ABC to its 40,000 customer accounts. Pools: transaction processing $300,000 (600,000 transactions); branch visits $180,000 (90,000 visits). Its 10,000 'premier' accounts generate 150,000 transactions and 60,000 visits. The ABC cost per premier account is:",
    options: ["$7.50", "$12.00", "$48.00", "$19.50"],
    correct: 3,
    explanation: "Rates: $0.50 per transaction and $2.00 per visit. Premier: (150,000 × $0.50) + (60,000 × $2.00) = $75,000 + $120,000 = $195,000 ÷ 10,000 = $19.50. $7.50 counts transactions only, $12.00 is the blanket cost per account ($480,000 ÷ 40,000) which hides premier accounts' heavy branch usage, and $48.00 charges both entire pools to premier accounts.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "PM3-A-17", paper: "PM", area: "A", type: "mcq",
    stem: "Target costing is MOST useful in which situation?",
    options: [
      "When the firm can pass any cost increase on to customers through cost-plus contract terms",
      "When a competitive market effectively fixes the selling price before the product is designed",
      "When each product is a unique one-off job priced after the work is completed",
      "When the product is in the decline stage of its life cycle",
    ],
    correct: 1,
    explanation: "Target costing works from a market-given price backwards to an allowable cost while the design can still be changed — ideal for price-taker firms launching products into competitive markets. Cost-plus environments remove the price constraint, one-off jobs are priced after costs are known, and by decline the design freedom has gone.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "PM3-A-18", paper: "PM", area: "A", type: "mcq",
    stem: "A product passes through three machines. Unit times and weekly hours: M1 — 0.2 hours (1,200 hours available); M2 — 0.3 hours (1,500 hours); M3 — 0.25 hours (1,400 hours). If M2's available hours are DOUBLED, which resource becomes the bottleneck?",
    options: [
      "Machine 3, because its maximum output of 5,600 units is then the lowest",
      "Machine 2 remains the bottleneck",
      "Machine 1, because it has the fewest available hours",
      "There is no longer any bottleneck",
    ],
    correct: 0,
    explanation: "Maximum outputs: M1 = 1,200 ÷ 0.2 = 6,000; M2 = 1,500 ÷ 0.3 = 5,000 (current bottleneck); M3 = 1,400 ÷ 0.25 = 5,600. Doubling M2 lifts it to 10,000 units, so the constraint shifts to M3 at 5,600. Judging by raw hours available (M1) ignores unit processing times, and elevating one bottleneck always exposes the next one.",
    marks: 2, difficulty: "hard",
  },
]
