import type{AccaQuestion}from"@/lib/acca-content";export const AAA_OFFICIAL_QUESTIONS:AccaQuestion[]=[
{id:"AAA-F-O01",paper:"AAA",area:"F",type:"mcq",stem:"Which feature distinguishes a limited assurance conclusion from reasonable assurance?",options:["No evidence is obtained","A negative-form conclusion supported by a lower, but meaningful, level of assurance","Absolute assurance","It is always an audit"],correct:1,explanation:"Limited assurance involves sufficient appropriate evidence for a meaningful but lower assurance level and ordinarily uses a negative-form conclusion.",marks:2,difficulty:"easy"},
{id:"AAA-F-O02",paper:"AAA",area:"F",type:"mcq",stem:"Before accepting a sustainability assurance engagement, what is most important?",options:["Marketing value only","Suitable criteria, intended users, subject-matter measurability, competence, ethics and evidence access","The client's preferred conclusion","Financial materiality only"],correct:1,explanation:"Acceptance requires an appropriate assurance precondition, resources and ethics; sustainability information may also involve impact materiality and specialist evidence.",marks:2,difficulty:"medium"},
{id:"AAA-F-O03",paper:"AAA",area:"F",type:"mcq",stem:"In due diligence, the practitioner's work is primarily shaped by:",options:["The statutory audit opinion","The purchaser's purpose, agreed scope and identified deal risks","Management's annual report format","ISA 700 only"],correct:1,explanation:"Due diligence is a specific assignment whose scope and reporting follow the commissioning party's information needs and agreed terms.",marks:2,difficulty:"medium"},
{id:"AAA-G-O01",paper:"AAA",area:"G",type:"mcq",stem:"What is a principal audit-quality risk from using opaque AI tools?",options:["Faster processing","Unreviewable logic, biased data or automation bias undermining professional judgement","More documentation","Lower sample size automatically"],correct:1,explanation:"Audit quality depends on validated tools, reliable data, explainability appropriate to use and sceptical human review rather than uncritical reliance.",marks:2,difficulty:"medium"},
{id:"AAA-G-O02",paper:"AAA",area:"G",type:"mcq",stem:"Why does sustainability assurance create distinctive evidence challenges?",options:["It never uses estimates","Forward-looking estimates, immature systems, multiple criteria and value-chain data can increase uncertainty","It is identical to cash auditing","No controls are needed"],correct:1,explanation:"Sustainability information can involve estimates, external data and developing control systems, requiring careful criteria, materiality, expertise and evidence evaluation.",marks:2,difficulty:"medium"},
{id:"AAA-G-O03",paper:"AAA",area:"G",type:"mcq",stem:"A major global disruption occurs after audit planning. What should the engagement team do?",options:["Keep the plan unchanged","Reassess risks, materiality implications, going concern, estimates, evidence access and reporting","Withdraw automatically","Ignore non-financial effects"],correct:1,explanation:"Audit planning is iterative; major events require renewed risk assessment and responsive procedures and conclusions.",marks:2,difficulty:"easy"},
{id:"AAA-H-O01",paper:"AAA",area:"H",type:"mcq",stem:"Which response best demonstrates professional scepticism when management's forecast conflicts with market evidence?",options:["Accept management expertise","Investigate the inconsistency, test assumptions and seek corroboration","Average the claims","Remove going-concern work"],correct:1,explanation:"Scepticism means an enquiring mind, critical evidence assessment and appropriate challenge while remaining objective.",marks:2,difficulty:"easy"},
{id:"AAA-H-O02",paper:"AAA",area:"H",type:"mcq",stem:"What makes an audit risk evaluation commercially aware without compromising independence?",options:["Helping management achieve profit","Understanding business model, incentives and external pressures to design relevant audit responses","Reducing work for fees","Advocating the client"],correct:1,explanation:"Commercial acumen improves understanding and recommendations but does not replace the auditor's independent public-interest role.",marks:2,difficulty:"medium"},
{id:"AAA-H-O03",paper:"AAA",area:"H",type:"mcq",stem:"A report to those charged with governance should primarily be:",options:["Generic ISA quotations","Concise, prioritised, evidence-based and clear about consequences and action","An audit programme","Unstructured notes"],correct:1,explanation:"Professional communication adapts technical evidence to the recipient and purpose without ambiguity.",marks:2,difficulty:"easy"},
{id:"AAA-I-O01",paper:"AAA",area:"I",type:"mcq",stem:"What is the best first step when navigating multiple audit exhibits?",options:["Read randomly","Map requirements to client, assertion, period and relevant exhibits","Copy every figure","Draft the opinion"],correct:1,explanation:"Requirement-led navigation focuses evidence collection and prevents omission.",marks:2,difficulty:"easy"},
{id:"AAA-I-O02",paper:"AAA",area:"I",type:"mcq",stem:"Which digital working-paper feature best supports review?",options:["Unexplained copied data","Clear purpose, source, procedure, result, exception and conclusion","Hidden assumptions","No cross-references"],correct:1,explanation:"A reviewable working paper shows what was tested, why, evidence obtained, exceptions and the conclusion reached.",marks:2,difficulty:"easy"},
{id:"AAA-I-O03",paper:"AAA",area:"I",type:"mcq",stem:"When an analytics exception list is very large, the auditor should:",options:["Assume every item is misstated","Validate the routine, stratify exceptions, investigate relevant items and evaluate the population effect","Delete it","Rely on colour coding"],correct:1,explanation:"Digital analytics requires validated logic and sceptical evaluation; exceptions are leads, not conclusions.",marks:2,difficulty:"medium"}];
