import type { AccaQuestion } from "@/lib/acca-content"

/**
 * AFM bank wave S1 part B (areas C, D, E)
 *
 * Blueprint:
 *   - Area C (Acquisitions & mergers): 35 questions
 *   - Area D (Corporate reconstruction & reorganisation): 25 questions
 *   - Area E (Treasury & advanced risk management): 30 questions
 *   - Difficulty: 27 easy / 40 medium / 23 hard
 *   - Type mix: 60 mcq / 30 number
 *   - Marks: 2 each
 *
 * Authored 2026-07-13. 100% original: all names and figures invented for
 * Scholify. Public AFM syllabus scope only; no ACCA/Kaplan/BPP text reproduced.
 *
 * NOTE: every computation in this file was re-solved digit-by-digit before
 * being committed. Numeric questions state all inputs, unit and rounding, and
 * hedging items (futures contracts, swap net cost, money-market hedge) show
 * full workings in the explanation.
 *
 * Correct-option distribution across the 60 mcqs: index 0 x15, 1 x15, 2 x15, 3 x15.
 */

export const AFM_WAVE1B: AccaQuestion[] = [
  // ==========================================================================
  // AREA C - Acquisitions & mergers (35)
  // ==========================================================================
  {
    id: "AFM3-C-01",
    paper: "AFM",
    area: "C",
    type: "number",
    stem: "Brightwater Utilities has total assets of $560m and total liabilities of $210m in its statement of financial position. On a net asset (book value) basis, what is the value of equity? Answer in $m.",
    numericAnswer: 350,
    unit: "$m",
    tolerance: 0.5,
    explanation: "Net asset (book) value of equity = total assets - total liabilities = 560 - 210 = $350m. This asset-based figure is normally treated as a floor for going-concern valuation.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-C-02",
    paper: "AFM",
    area: "C",
    type: "mcq",
    stem: "Cedarhold Foods has forecast maintainable earnings of $40m. A comparable listed peer trades on a P/E ratio of 12. On a P/E basis, what is the estimated equity value of Cedarhold?",
    options: [
      "$480m",
      "$52m",
      "$3.33m",
      "$4,800m",
    ],
    correct: 0,
    explanation: "P/E valuation: value = earnings x P/E = 40 x 12 = $480m (correct). '$52m' adds earnings and P/E (40 + 12) instead of multiplying. '$3.33m' divides earnings by P/E (40 / 12) - that inverts the relationship. '$4,800m' multiplies by 120, a factor-of-ten decimal error.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-C-03",
    paper: "AFM",
    area: "C",
    type: "mcq",
    stem: "Marlowe Logistics has maintainable earnings of $30m. Investors require an earnings yield of 10%. Using the earnings-yield method, what is the estimated equity value?",
    options: [
      "$3m",
      "$300m",
      "$30m",
      "$333m",
    ],
    correct: 1,
    explanation: "Earnings-yield valuation: value = earnings / earnings yield = 30 / 0.10 = $300m (correct). '$3m' multiplies (30 x 0.10) instead of dividing. '$30m' uses earnings as the value and forgets to capitalise at all. '$333m' divides by a wrong 9% yield (30 / 0.09).",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-C-04",
    paper: "AFM",
    area: "C",
    type: "number",
    stem: "Pennygate Retail expects to pay a dividend next year (D1) of $0.24 per share. Its cost of equity is 11% and dividends are expected to grow at a constant 3% per year. Using the dividend valuation (Gordon growth) model, what is the value per share? Answer in $ to 2 decimal places.",
    numericAnswer: 3.0,
    unit: "$",
    tolerance: 0.02,
    explanation: "Gordon growth model: P0 = D1 / (ke - g) = 0.24 / (0.11 - 0.03) = 0.24 / 0.08 = $3.00. D1 is already next year's dividend, so no further growth adjustment is needed.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-C-05",
    paper: "AFM",
    area: "C",
    type: "mcq",
    stem: "Ashcombe Media has just paid a dividend (D0) of $0.20 per share. Dividends grow at 4% per year and its cost of equity is 9%. Using the dividend valuation model, what is the value per share?",
    options: [
      "$4.00",
      "$1.60",
      "$4.16",
      "$2.31",
    ],
    correct: 2,
    explanation: "Because D0 has just been paid, next year's dividend must be grown: D1 = 0.20 x 1.04 = 0.208. P0 = D1 / (ke - g) = 0.208 / (0.09 - 0.04) = 0.208 / 0.05 = $4.16 (correct). '$4.00' uses D0 not D1 in the numerator (0.20 / 0.05). '$1.60' divides by (ke + g) = 0.13. '$2.31' divides by ke alone (0.208 / 0.09) instead of ke - g.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-C-06",
    paper: "AFM",
    area: "C",
    type: "mcq",
    stem: "Delford Engineering expects free cash flow to the firm (FCFF) next year of $50m, growing at 2% in perpetuity. Its WACC is 9% and the market value of its debt is $200m. Using the FCFF method, what is the value of equity?",
    options: [
      "$714m",
      "$555m",
      "$914m",
      "$514m",
    ],
    correct: 3,
    explanation: "Enterprise value = FCFF1 / (WACC - g) = 50 / (0.09 - 0.02) = 50 / 0.07 = $714.29m. Equity = EV - debt = 714.29 - 200 = $514m (correct). '$714m' stops at enterprise value and forgets to deduct debt. '$555m' ignores growth (50 / 0.09). '$914m' adds debt instead of subtracting it (714 + 200).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-C-07",
    paper: "AFM",
    area: "C",
    type: "number",
    stem: "Hal-Rowan plc expects free cash flow to equity (FCFE) next year of $36m, growing at 4% in perpetuity. Its cost of equity is 12%. Using the FCFE method, what is the value of equity? Answer in $m.",
    numericAnswer: 450,
    unit: "$m",
    tolerance: 1,
    explanation: "FCFE discounts directly to equity at the cost of equity: equity value = FCFE1 / (ke - g) = 36 / (0.12 - 0.04) = 36 / 0.08 = $450m. No debt is deducted because FCFE is already the cash flow available to shareholders.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-C-08",
    paper: "AFM",
    area: "C",
    type: "mcq",
    stem: "Norwood plc (value $800m) plans to acquire Stellan Ltd (value $300m). The combined entity is estimated to be worth $1,250m. What is the value of the synergy created by the merger?",
    options: [
      "$150m",
      "$450m",
      "$950m",
      "$1,100m",
    ],
    correct: 0,
    explanation: "Synergy = combined value - (acquirer + target standalone) = 1,250 - (800 + 300) = 1,250 - 1,100 = $150m (correct). '$450m' deducts only the acquirer (1,250 - 800). '$950m' deducts only the target (1,250 - 300). '$1,100m' is merely the sum of standalone values with no synergy calculation.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-C-09",
    paper: "AFM",
    area: "C",
    type: "mcq",
    stem: "Which statement about the form of consideration in an acquisition is correct?",
    options: [
      "A cash offer dilutes the acquirer's existing shareholders' control, while a share exchange leaves it unchanged.",
      "A share-for-share exchange dilutes the acquirer's existing shareholders' control, whereas a cash offer leaves their proportionate control unchanged.",
      "An earn-out transfers full control to the seller immediately at completion.",
      "A share exchange has no effect on either the acquirer's gearing or its control structure.",
    ],
    correct: 1,
    explanation: "Correct: issuing new shares to target holders dilutes existing owners' control, whereas paying cash does not change the existing share register. Option A reverses the two - cash does not dilute control. The earn-out option is wrong: an earn-out defers part of the consideration and does not hand control to the seller. The last option is wrong because issuing shares changes control and can reduce gearing.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-C-10",
    paper: "AFM",
    area: "C",
    type: "number",
    stem: "Kestrel plc offers to acquire Talbrook Ltd on the basis of 3 new Kestrel shares for every 5 Talbrook shares. Talbrook has 40m shares in issue. How many new Kestrel shares must be issued? Answer in millions of shares.",
    numericAnswer: 24,
    unit: "m shares",
    tolerance: 0.1,
    explanation: "New shares issued = Talbrook shares x exchange ratio = 40m x 3/5 = 40m x 0.6 = 24m shares.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-C-11",
    paper: "AFM",
    area: "C",
    type: "mcq",
    stem: "Vantor plc raises $400m of new debt to fund a cash bid. Before the bid its debt was $600m and the market value of its equity was $1,500m (unchanged by the deal). What is Vantor's post-bid gearing measured as debt / (debt + equity)?",
    options: [
      "28.6%",
      "66.7%",
      "40.0%",
      "21.1%",
    ],
    correct: 2,
    explanation: "Post-bid debt = 600 + 400 = 1,000; equity = 1,500. Gearing = 1,000 / (1,000 + 1,500) = 1,000 / 2,500 = 40.0% (correct). '28.6%' is pre-bid gearing (600 / 2,100), ignoring the new debt. '66.7%' computes debt/equity (1,000 / 1,500), not debt/(debt+equity). '21.1%' takes only the new debt over the new total (400 / 1,900).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-C-12",
    paper: "AFM",
    area: "C",
    type: "mcq",
    stem: "Which of the following is a pre-bid (pre-emptive) takeover defence rather than a post-bid defence?",
    options: [
      "Seeking a white knight to make a friendlier offer.",
      "Launching a Pac-Man counter-bid for the hostile bidder.",
      "Selling off the target's crown-jewel assets.",
      "A poison pill that issues cheap rights to existing holders once a hostile stake is crossed.",
    ],
    correct: 3,
    explanation: "A poison pill is put in place in advance and triggers automatically, making it a pre-emptive defence (correct). A white knight, a Pac-Man counter-bid and a crown-jewels disposal are all reactive measures deployed only after a hostile bid has been launched, so they are post-bid defences.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-C-13",
    paper: "AFM",
    area: "C",
    type: "number",
    stem: "Oakmere plc pays $360m to acquire Renwick Ltd, which has an independent standalone value of $300m. The total synergy from the combination is estimated at $120m. How much of that synergy is retained by Oakmere's shareholders (i.e. synergy less the premium paid)? Answer in $m.",
    numericAnswer: 60,
    unit: "$m",
    tolerance: 0.5,
    explanation: "Premium paid to target holders = price - standalone value = 360 - 300 = $60m. Synergy retained by the acquirer = total synergy - premium = 120 - 60 = $60m. The remaining $60m of synergy is captured by target shareholders via the premium.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-C-14",
    paper: "AFM",
    area: "C",
    type: "mcq",
    stem: "Ardent plc has earnings of $80m and 100m shares. It acquires Bryce Ltd (earnings $30m) by issuing 1 new Ardent share for every 4 Bryce shares; Bryce has 80m shares. Assuming no synergy, what is the combined group's earnings per share?",
    options: [
      "$0.92",
      "$1.10",
      "$0.55",
      "$0.80",
    ],
    correct: 0,
    explanation: "New shares issued = 80m x 1/4 = 20m. Combined earnings = 80 + 30 = $110m. Combined shares = 100 + 20 = 120m. EPS = 110 / 120 = $0.92 (correct). '$1.10' uses only Ardent's 100m shares. '$0.55' double-counts shares (110 / 200). '$0.80' is Ardent's standalone EPS, ignoring the merger.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM3-C-15",
    paper: "AFM",
    area: "C",
    type: "mcq",
    stem: "Under a typical City Code-style takeover framework, at what shareholding level is an acquirer normally obliged to make a mandatory cash offer to all remaining shareholders?",
    options: [
      "10%",
      "30%",
      "50%",
      "75%",
    ],
    correct: 1,
    explanation: "A holding reaching 30% is the customary mandatory-bid trigger, requiring an offer to all shareholders at the highest price paid (correct). 10% is too low and carries only disclosure duties. 50% is the point of majority control but the mandatory-offer rule bites earlier, at 30%. 75% is typically the level for special resolutions / de-listing, not the mandatory-offer trigger.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-C-16",
    paper: "AFM",
    area: "C",
    type: "number",
    stem: "Fenwick plc (market capitalisation $900m) acquires Gorse Ltd (market capitalisation $400m) entirely with shares. The present value of synergies is $180m and there is no cash leakage. What is the estimated combined market value? Answer in $m.",
    numericAnswer: 1480,
    unit: "$m",
    tolerance: 1,
    explanation: "Because the deal is share-financed there is no cash outflow, so combined value = acquirer + target + PV of synergies = 900 + 400 + 180 = $1,480m.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-C-17",
    paper: "AFM",
    area: "C",
    type: "mcq",
    stem: "Larkhill plc is worth $1,000m (50m shares at $20 each). It acquires Mowbray Ltd (standalone value $300m) by issuing 20m new shares. The combined entity, including synergy, is worth $1,450m. What is the value of the shares received by Mowbray's shareholders after the merger?",
    options: [
      "$300m",
      "$400m",
      "$414m",
      "$580m",
    ],
    correct: 2,
    explanation: "Post-merger total shares = 50 + 20 = 70m; post-merger price = 1,450 / 70 = $20.714. Value to Mowbray holders = 20m x 20.714 = $414m (correct). '$300m' is Mowbray's pre-merger standalone value, ignoring re-rating. '$400m' values the new shares at the old $20 price, ignoring synergy. '$580m' uses the pre-issue count of 50m (20/50 x 1,450) instead of the post-issue 70m.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM3-C-18",
    paper: "AFM",
    area: "C",
    type: "mcq",
    stem: "In which circumstance is an earn-out structure for consideration most appropriate?",
    options: [
      "When the acquirer wants to maximise its immediate gearing.",
      "When the target's future cash flows are highly certain and stable.",
      "When the acquirer has surplus cash and wants a clean, immediate exit for the sellers.",
      "When there is significant uncertainty over the target's future earnings and the seller will remain to run the business.",
    ],
    correct: 3,
    explanation: "An earn-out ties part of the price to future performance, which suits uncertain earnings and keeps the seller-manager incentivised (correct). Maximising gearing points to a debt-funded cash bid, not an earn-out. Highly certain cash flows remove the need for a contingent payment. Wanting a clean immediate exit points to an up-front cash offer, the opposite of an earn-out.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-C-19",
    paper: "AFM",
    area: "C",
    type: "number",
    stem: "On a break-up (realisable) basis, Trentmoor Ltd's assets have a book value of $500m, but inventory must be written down by $30m and receivables by $20m. Liabilities are $150m. What is the realisable value of equity? Answer in $m.",
    numericAnswer: 300,
    unit: "$m",
    tolerance: 0.5,
    explanation: "Realisable assets = 500 - 30 - 20 = $450m. Realisable equity = realisable assets - liabilities = 450 - 150 = $300m.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-C-20",
    paper: "AFM",
    area: "C",
    type: "mcq",
    stem: "Which valuation approach normally provides a 'floor' (minimum) value for a company that is expected to continue as a going concern?",
    options: [
      "Net asset (book) value.",
      "Free cash flow to the firm.",
      "Price/earnings-based value.",
      "The dividend valuation model.",
    ],
    correct: 0,
    explanation: "Net asset value typically sets a floor because a going concern should be worth at least the value of its underlying net assets (correct). FCFF, P/E and the dividend valuation model are all forward-looking, earnings- or cash-flow-based methods that usually produce higher figures reflecting future value, so they are not floor measures.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-C-21",
    paper: "AFM",
    area: "C",
    type: "mcq",
    stem: "Sable plc acquires Verity Ltd for $300m in cash. Verity's standalone value is $250m and the present value of synergies is $90m. What is the NPV of the acquisition to Sable's shareholders?",
    options: [
      "$90m",
      "$40m",
      "-$50m",
      "$340m",
    ],
    correct: 1,
    explanation: "NPV to acquirer = (target standalone + synergy) - cash paid = (250 + 90) - 300 = $40m (correct); equivalently synergy - premium = 90 - 50 = 40. '$90m' counts the full synergy but ignores the $50m premium. '-$50m' counts only the premium and ignores synergy. '$340m' is the total value acquired with no deduction of the price paid.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM3-C-22",
    paper: "AFM",
    area: "C",
    type: "number",
    stem: "After acquiring a competitor, Brookvale Group expects combined maintainable earnings of $110m. The market is expected to apply a P/E ratio of 14 to the enlarged group. What is the estimated value of the combined equity? Answer in $m.",
    numericAnswer: 1540,
    unit: "$m",
    tolerance: 1,
    explanation: "Combined equity value = combined earnings x applied P/E = 110 x 14 = $1,540m.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-C-23",
    paper: "AFM",
    area: "C",
    type: "mcq",
    stem: "Calder plc expects FCFF next year of $60m in perpetuity (no growth). Its WACC is 10%, its debt is $250m and it holds surplus cash of $50m. What is the value of Calder's equity?",
    options: [
      "$600m",
      "$300m",
      "$400m",
      "$850m",
    ],
    correct: 2,
    explanation: "Enterprise value = 60 / 0.10 = $600m. Equity = EV - debt + cash = 600 - 250 + 50 = $400m (correct). '$600m' is enterprise value, forgetting net debt. '$300m' subtracts cash instead of adding it (600 - 250 - 50). '$850m' adds debt rather than subtracting it (600 + 250).",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM3-C-24",
    paper: "AFM",
    area: "C",
    type: "mcq",
    stem: "Which of the following is a core principle of takeover regulation?",
    options: [
      "The bidder may buy out minority holders at any price it chooses.",
      "The target's directors may frustrate a bid without shareholder approval.",
      "Advisers may deal on inside bid information provided it is not published.",
      "All shareholders of the same class must be treated equally and given the same information.",
    ],
    correct: 3,
    explanation: "Equal treatment of, and equal information for, shareholders of the same class is a fundamental takeover principle (correct). Allowing any price to minorities breaches the equal-treatment rule. Directors generally cannot take frustrating action without shareholder approval. Dealing on inside information is insider dealing and is prohibited, not permitted for advisers.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-C-25",
    paper: "AFM",
    area: "C",
    type: "number",
    stem: "Millbrook plc has a share price of $5.00. Its next dividend (D1) is expected to be $0.30 and dividends grow at a constant 4% per year. Using the dividend growth model, what is the implied cost of equity? Answer as a percentage to 1 decimal place.",
    numericAnswer: 10,
    unit: "%",
    tolerance: 0.1,
    explanation: "Rearranging the dividend growth model: ke = D1 / P0 + g = 0.30 / 5.00 + 0.04 = 0.06 + 0.04 = 0.10 = 10.0%.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-C-26",
    paper: "AFM",
    area: "C",
    type: "mcq",
    stem: "A high-P/E acquirer (P/E 20) buys a low-P/E target (P/E 10) in a share exchange, producing combined earnings of $150m. Which statement about 'P/E bootstrapping' is correct?",
    options: [
      "If the market keeps applying the acquirer's high P/E to the enlarged earnings, reported EPS can rise but no real value is created without genuine synergies.",
      "Acquiring a low-P/E target always destroys shareholder value.",
      "EPS bootstrapping guarantees a permanently higher share price.",
      "A high-P/E firm should only ever acquire other high-P/E firms.",
    ],
    correct: 0,
    explanation: "Correct: the EPS uplift is a mechanical mixing effect; it becomes real value only if the market sustains the higher rating, which it will not do indefinitely without genuine synergies. It is not true that buying a low-P/E target always destroys value (it can add value with synergies), that bootstrapping guarantees a permanently higher price (the market corrects), or that a high-P/E firm should buy only high-P/E firms (low-P/E targets are often the accretive ones).",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM3-C-27",
    paper: "AFM",
    area: "C",
    type: "mcq",
    stem: "A share-for-share exchange is most likely to DILUTE the acquirer's earnings per share when:",
    options: [
      "the target has a lower P/E ratio than the acquirer.",
      "the target is acquired on a higher P/E ratio than the acquirer's own P/E.",
      "the acquirer pays entirely in cash.",
      "synergies substantially exceed the premium paid.",
    ],
    correct: 1,
    explanation: "Paying a higher P/E than your own in shares means you issue relatively more shares per unit of acquired earnings, diluting EPS (correct). A lower target P/E is accretive, not dilutive. A pure cash deal issues no new shares, so it cannot dilute EPS through share issuance. Large synergies raise combined earnings and tend to be accretive.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-C-28",
    paper: "AFM",
    area: "C",
    type: "number",
    stem: "Redwing plc is bidding for Coppice Ltd, which has a standalone equity value of $280m. The present value of synergies expected from the combination is $70m. What is the maximum price Redwing can pay without destroying value for its own shareholders? Answer in $m.",
    numericAnswer: 350,
    unit: "$m",
    tolerance: 0.5,
    explanation: "Maximum justifiable price = target standalone value + PV of synergies = 280 + 70 = $350m. Paying more than this transfers more than the whole synergy to the target's shareholders and destroys value for the acquirer.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM3-C-29",
    paper: "AFM",
    area: "C",
    type: "mcq",
    stem: "Hartwell plc pays $330m for a target with a standalone value of $270m. Total synergies are $100m. What percentage of the synergy is captured by Hartwell's (the acquirer's) shareholders?",
    options: [
      "60%",
      "100%",
      "40%",
      "18%",
    ],
    correct: 2,
    explanation: "Premium to target = 330 - 270 = $60m, so target holders capture 60/100 = 60% of the synergy and the acquirer keeps 100 - 60 = $40m = 40% (correct). '60%' is the target's share, not the acquirer's. '100%' wrongly assumes the acquirer keeps all synergy. '18%' divides the premium by the price (60 / 330), which is not a synergy split.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM3-C-30",
    paper: "AFM",
    area: "C",
    type: "mcq",
    stem: "Which is the most commonly cited reason that acquisitions fail to deliver their expected value?",
    options: [
      "The offer was made in cash rather than shares.",
      "Regulatory approval was granted for the deal.",
      "The target had audited financial statements.",
      "Poor post-merger integration, culture clash and overestimated synergies.",
    ],
    correct: 3,
    explanation: "Weak integration, cultural conflict and over-optimistic synergy estimates are the classic causes of acquisition underperformance (correct). The form of consideration, obtaining regulatory clearance and the existence of audited accounts are not, in themselves, reasons that deals destroy value.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-C-31",
    paper: "AFM",
    area: "C",
    type: "number",
    stem: "Selwyn plc has a share price of $8.00 and offers 2 Selwyn shares for every 3 shares of the target. What is the value of the consideration offered per target share? Answer in $ to 2 decimal places.",
    numericAnswer: 5.33,
    unit: "$",
    tolerance: 0.02,
    explanation: "Value offered per target share = exchange ratio x acquirer share price = (2/3) x 8.00 = 0.6667 x 8.00 = $5.33.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-C-32",
    paper: "AFM",
    area: "C",
    type: "mcq",
    stem: "Which of the following is a REVENUE synergy rather than a cost synergy?",
    options: [
      "Cross-selling the target's products to the acquirer's existing customer base.",
      "Eliminating duplicated head-office and finance functions.",
      "Closing overlapping distribution depots.",
      "Obtaining bulk purchasing discounts from combined procurement.",
    ],
    correct: 0,
    explanation: "Cross-selling raises the combined group's sales, so it is a revenue synergy (correct). Removing duplicate head-office functions, closing overlapping depots and securing bulk-purchasing discounts all reduce costs, so they are cost synergies.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM3-C-33",
    paper: "AFM",
    area: "C",
    type: "mcq",
    stem: "A company has an earnings yield of 8%. What is the implied price/earnings (P/E) ratio?",
    options: [
      "8.0",
      "12.5",
      "0.08",
      "92.0",
    ],
    correct: 1,
    explanation: "P/E is the reciprocal of earnings yield: 1 / 0.08 = 12.5 (correct). '8.0' just repeats the yield as if it were the P/E. '0.08' leaves the yield as a decimal. '92.0' subtracts the yield from 100 (100 - 8), which has no meaning here.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-C-34",
    paper: "AFM",
    area: "C",
    type: "number",
    stem: "Estimate free cash flow to the firm for Wexley plc for the coming year given: operating profit (EBIT) $120m; tax rate 25%; depreciation $20m; capital expenditure $30m; increase in working capital $10m. Answer in $m.",
    numericAnswer: 70,
    unit: "$m",
    tolerance: 0.5,
    explanation: "FCFF = EBIT x (1 - t) + depreciation - capex - increase in working capital = 120 x 0.75 + 20 - 30 - 10 = 90 + 20 - 30 - 10 = $70m.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM3-C-35",
    paper: "AFM",
    area: "C",
    type: "mcq",
    stem: "During a hostile bid, a target's directors announce a surprise special dividend and an asset revaluation. This is best described as:",
    options: [
      "a mandatory offer.",
      "a reverse takeover.",
      "a bid defence which, in many jurisdictions, requires shareholder approval to avoid breaching frustrating-action rules.",
      "a scheme of arrangement.",
    ],
    correct: 2,
    explanation: "Actions taken to make the target less attractive or more expensive are defensive and are typically caught by frustrating-action rules requiring shareholder approval (correct). A mandatory offer is a bidder obligation, not a defensive action. A reverse takeover is where a smaller/private company gains a listing via a larger one. A scheme of arrangement is a court-approved mechanism to implement a takeover, not a surprise defensive tactic.",
    marks: 2,
    difficulty: "medium",
  },

  // ==========================================================================
  // AREA D - Corporate reconstruction & reorganisation (25)
  // ==========================================================================
  {
    id: "AFM3-D-01",
    paper: "AFM",
    area: "D",
    type: "mcq",
    stem: "What best describes a debt-for-equity swap in a financial reconstruction?",
    options: [
      "Shareholders inject cash to repay all outstanding debt.",
      "Gearing increases because more debt is issued.",
      "Interest cover falls as interest obligations rise.",
      "Lenders exchange some of their debt for shares, cutting gearing and interest cost but diluting existing shareholders.",
    ],
    correct: 3,
    explanation: "A debt-for-equity swap converts lender claims into shares, reducing debt and interest but diluting existing owners (correct). It does not require shareholders to inject cash. It reduces gearing rather than increasing it, and it improves - not worsens - interest cover because interest obligations fall.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-D-02",
    paper: "AFM",
    area: "D",
    type: "number",
    stem: "Harrowfield Ltd has debt of $500m and equity (book value) of $200m. As part of a reconstruction, $150m of debt is swapped into equity. What is the post-swap gearing measured as debt / (debt + equity)? Answer as a percentage to 1 decimal place.",
    numericAnswer: 50,
    unit: "%",
    tolerance: 0.5,
    explanation: "After the swap: debt = 500 - 150 = $350m; equity = 200 + 150 = $350m. Gearing = 350 / (350 + 350) = 350 / 700 = 50.0%.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-D-03",
    paper: "AFM",
    area: "D",
    type: "mcq",
    stem: "What is the purpose of the Altman Z-score?",
    options: [
      "To predict the likelihood of corporate failure/bankruptcy.",
      "To value the synergies in a proposed merger.",
      "To set a company's optimal dividend policy.",
      "To compute the weighted average cost of capital.",
    ],
    correct: 0,
    explanation: "The Altman Z-score combines several financial ratios into a single index used to predict the probability of corporate failure (correct). It does not value merger synergies, set dividend policy or calculate WACC.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-D-04",
    paper: "AFM",
    area: "D",
    type: "mcq",
    stem: "A manufacturing company has an Altman Z-score of 1.5. Under the original model, this places it in which zone?",
    options: [
      "The safe zone - low probability of failure.",
      "The distress zone - high probability of failure.",
      "The grey/uncertain zone.",
      "The growth zone.",
    ],
    correct: 1,
    explanation: "In the original manufacturing model, a Z-score below about 1.8 signals the distress zone with a high probability of failure (correct). The safe zone is above ~3.0 and the grey zone lies between ~1.8 and 3.0; 1.5 is below both. 'Growth zone' is not a category in the model.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-D-05",
    paper: "AFM",
    area: "D",
    type: "number",
    stem: "Using the original Altman model Z = 1.2X1 + 1.4X2 + 3.3X3 + 0.6X4 + 1.0X5, compute the Z-score for a company with X1 = 0.10, X2 = 0.20, X3 = 0.15, X4 = 0.50 and X5 = 1.10. Answer to 2 decimal places.",
    numericAnswer: 2.3,
    unit: "",
    tolerance: 0.05,
    explanation: "Z = 1.2(0.10) + 1.4(0.20) + 3.3(0.15) + 0.6(0.50) + 1.0(1.10) = 0.12 + 0.28 + 0.495 + 0.30 + 1.10 = 2.295, which rounds to 2.30. This lies in the grey zone (between ~1.8 and 3.0).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-D-06",
    paper: "AFM",
    area: "D",
    type: "mcq",
    stem: "Which statement best describes a leveraged buy-out (LBO)?",
    options: [
      "An acquisition financed entirely by a rights issue to existing shareholders.",
      "An acquisition undertaken only by the target's existing management team.",
      "An acquisition financed predominantly by debt secured on the target's own assets and cash flows, to boost equity returns.",
      "An acquisition that reduces the target's gearing to near zero.",
    ],
    correct: 2,
    explanation: "An LBO uses a high proportion of debt, secured on the target, to amplify equity returns (correct). It is not funded by a rights issue. Management-only participation describes an MBO, a subset of buy-outs but not the definition of an LBO. And an LBO raises gearing sharply rather than reducing it.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-D-07",
    paper: "AFM",
    area: "D",
    type: "mcq",
    stem: "A management buy-out (MBO) is best defined as:",
    options: [
      "an external buyer installing an entirely new management team.",
      "a demerger of a subsidiary to existing shareholders.",
      "a rights issue used to refinance debt.",
      "the existing management team acquiring the business they run, usually with private-equity or debt backing.",
    ],
    correct: 3,
    explanation: "An MBO is the incumbent managers buying the business they already run, typically backed by private equity and debt (correct). An external buyer bringing in new managers is a management buy-in (MBI). A demerger and a refinancing rights issue are different transactions entirely.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-D-08",
    paper: "AFM",
    area: "D",
    type: "number",
    stem: "A private-equity fund buys Ferndale Ltd for $500m, financed by $150m of equity and $350m of debt. After four years it sells the business for $700m, by which time the debt has been paid down to $200m. What is the money multiple (exit equity value / initial equity)? Answer to 2 decimal places.",
    numericAnswer: 3.33,
    unit: "x",
    tolerance: 0.05,
    explanation: "Exit equity value = sale price - remaining debt = 700 - 200 = $500m. Money multiple = exit equity / initial equity = 500 / 150 = 3.33x.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM3-D-09",
    paper: "AFM",
    area: "D",
    type: "mcq",
    stem: "Which of the following best describes a demerger (spin-off)?",
    options: [
      "Distributing shares in a subsidiary to existing shareholders so it becomes a separate listed company, with no cash changing hands.",
      "Selling a division outright to a third party for cash.",
      "Selling shares in a subsidiary to the public for cash while retaining control.",
      "Buying back the company's own shares from the market.",
    ],
    correct: 0,
    explanation: "In a spin-off/demerger the parent hands shares in the subsidiary to its own shareholders, creating a separate company without raising cash (correct). Selling a division for cash is a sell-off (trade sale). Selling subsidiary shares to the public for cash while keeping control is an equity carve-out. Repurchasing shares is a buy-back.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-D-10",
    paper: "AFM",
    area: "D",
    type: "mcq",
    stem: "How does an equity carve-out differ from a pure spin-off?",
    options: [
      "A carve-out raises no cash for the parent.",
      "In a carve-out the parent sells a minority stake in the subsidiary to the public for cash, retaining control.",
      "A carve-out gives the whole subsidiary to a competitor.",
      "A carve-out is identical to a share buy-back.",
    ],
    correct: 1,
    explanation: "An equity carve-out is a partial IPO: the parent sells a minority stake to the market for cash while keeping control (correct). It does raise cash (unlike a pure spin-off, which does not). It does not transfer the whole subsidiary to a competitor, and it is not a share buy-back.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-D-11",
    paper: "AFM",
    area: "D",
    type: "number",
    stem: "Ilminster plc has 60m shares trading at $4.00. To raise cash to repay debt it makes a 1-for-3 rights issue at $2.80 per share. What is the theoretical ex-rights price (TERP)? Answer in $ to 2 decimal places.",
    numericAnswer: 3.7,
    unit: "$",
    tolerance: 0.02,
    explanation: "New shares = 60m x 1/3 = 20m; rights cash = 20m x 2.80 = $56m. TERP = (existing value + rights cash) / total shares = (60 x 4.00 + 56) / (60 + 20) = (240 + 56) / 80 = 296 / 80 = $3.70.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-D-12",
    paper: "AFM",
    area: "D",
    type: "mcq",
    stem: "A financial reconstruction scheme should be accepted only if:",
    options: [
      "it maximises the directors' bonuses.",
      "gearing is increased.",
      "the expected value to each key stakeholder group under the scheme exceeds what they would receive on liquidation.",
      "all debt is converted to equity regardless of value.",
    ],
    correct: 2,
    explanation: "The decision test is whether each stakeholder group is better off under the scheme than on liquidation (correct). Directors' bonuses are irrelevant to the test. Increasing gearing is not a goal in itself, and converting all debt to equity 'regardless of value' ignores the stakeholder comparison that actually governs acceptance.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM3-D-13",
    paper: "AFM",
    area: "D",
    type: "mcq",
    stem: "On liquidation, which of the following claims ranks LAST and is paid only if funds remain after all others?",
    options: [
      "Fixed-charge (secured) creditors.",
      "Preferential creditors.",
      "Unsecured creditors.",
      "Ordinary shareholders.",
    ],
    correct: 3,
    explanation: "Ordinary shareholders are residual claimants and rank last (correct). Fixed-charge secured creditors rank first, followed by preferential creditors, then unsecured creditors - all ahead of ordinary shareholders.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-D-14",
    paper: "AFM",
    area: "D",
    type: "number",
    stem: "On liquidation, Garrowby Ltd realises $180m from its assets. Secured creditors ($80m) are paid first, then preferential creditors ($10m) and liquidation costs ($5m). Unsecured creditors are owed $170m in total. How many cents in the $ do unsecured creditors receive? Answer in cents per $.",
    numericAnswer: 50,
    unit: "cents per $",
    tolerance: 1,
    explanation: "Funds left for unsecured creditors = 180 - 80 - 10 - 5 = $85m. Payout ratio = 85 / 170 = 0.50, i.e. 50 cents in the $.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM3-D-15",
    paper: "AFM",
    area: "D",
    type: "mcq",
    stem: "What is usually the main strategic rationale for unbundling (divestment)?",
    options: [
      "To remove a poorly-fitting or underperforming division so the market values the focused businesses more highly, reversing a conglomerate discount.",
      "To let management build a larger empire.",
      "To raise gearing purely for its own sake.",
      "To avoid having to publish financial statements.",
    ],
    correct: 0,
    explanation: "Unbundling sharpens focus and can unlock value hidden by a conglomerate discount (correct). Empire-building is the opposite motive; raising gearing for its own sake is not a rationale; and unbundling has nothing to do with avoiding financial reporting obligations.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-D-16",
    paper: "AFM",
    area: "D",
    type: "mcq",
    stem: "Before a debt-for-equity swap, Bramwell Ltd has EBIT of $60m and interest of $40m. After the swap, annual interest falls to $25m. What is the new interest cover?",
    options: [
      "1.5x",
      "2.4x",
      "0.42x",
      "2.0x",
    ],
    correct: 1,
    explanation: "Interest cover = EBIT / interest = 60 / 25 = 2.4x (correct). '1.5x' is the pre-swap cover (60 / 40). '0.42x' inverts the ratio (25 / 60). '2.0x' uses an incorrect $30m interest figure.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-D-17",
    paper: "AFM",
    area: "D",
    type: "number",
    stem: "Denholm plc has 45m shares and makes a 1-for-5 rights issue at $3.20 per share. Issue costs are $0.8m. What are the NET funds raised? Answer in $m.",
    numericAnswer: 28,
    unit: "$m",
    tolerance: 0.1,
    explanation: "New shares = 45m x 1/5 = 9m. Gross proceeds = 9m x 3.20 = $28.8m. Net proceeds = 28.8 - 0.8 = $28.0m.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-D-18",
    paper: "AFM",
    area: "D",
    type: "mcq",
    stem: "Which unbundling method raises cash for the parent company?",
    options: [
      "A pure spin-off/demerger.",
      "A share split.",
      "A sell-off (trade sale of a division for cash).",
      "A bonus issue.",
    ],
    correct: 2,
    explanation: "A sell-off is a trade sale of a division in exchange for cash (correct). A pure spin-off distributes shares to existing holders and raises no cash. A share split and a bonus issue merely re-denominate or capitalise reserves and bring in no external funds.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-D-19",
    paper: "AFM",
    area: "D",
    type: "mcq",
    stem: "In a leveraged buy-out capital structure, mezzanine finance:",
    options: [
      "ranks ahead of senior secured debt.",
      "is the cheapest form of finance in the structure.",
      "is identical to ordinary equity.",
      "ranks between senior debt and equity, carrying higher interest and often equity warrants.",
    ],
    correct: 3,
    explanation: "Mezzanine sits between senior debt and equity in priority and reward, typically paying a high coupon plus equity warrants (correct). It ranks behind, not ahead of, senior secured debt; it is more expensive, not cheaper, than senior debt; and it is not the same as ordinary equity because it has debt-like features and higher priority.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM3-D-20",
    paper: "AFM",
    area: "D",
    type: "number",
    stem: "As part of a reconstruction, a lender agrees to swap $120m of debt for new equity issued at an agreed price of $2.40 per share. How many new shares are issued to the lender? Answer in millions of shares.",
    numericAnswer: 50,
    unit: "m shares",
    tolerance: 0.5,
    explanation: "New shares = debt swapped / issue price = 120 / 2.40 = 50m shares.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-D-21",
    paper: "AFM",
    area: "D",
    type: "mcq",
    stem: "A company's Altman Z-score falls from 3.2 to 1.5 over two years. What does this indicate?",
    options: [
      "It has moved from the safe zone into the distress zone; failure risk has risen sharply.",
      "Its solvency has improved.",
      "There has been no meaningful change in its risk.",
      "It is now effectively bankruptcy-proof.",
    ],
    correct: 0,
    explanation: "A fall from 3.2 (safe) to 1.5 (distress) signals a sharp rise in failure risk (correct). A falling Z-score means deteriorating, not improving, solvency; the change is large, not negligible; and a low score means higher, not lower, bankruptcy risk.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM3-D-22",
    paper: "AFM",
    area: "D",
    type: "mcq",
    stem: "A financial reconstruction primarily changes:",
    options: [
      "only the company's product range.",
      "the capital structure (mix of debt and equity), without necessarily changing operations.",
      "the factory layout.",
      "nothing of substance.",
    ],
    correct: 1,
    explanation: "A financial reconstruction reshapes the funding mix - debt, equity, and their terms - to restore viability, and need not alter operations (correct). Changing the product range or factory layout are operational (business) reconstruction matters, and 'nothing of substance' is plainly wrong.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-D-23",
    paper: "AFM",
    area: "D",
    type: "number",
    stem: "An LBO of Marchmont Ltd is priced at $600m and financed by $420m of debt and $180m of equity. What is the debt-to-equity ratio at entry? Answer to 2 decimal places.",
    numericAnswer: 2.33,
    unit: "x",
    tolerance: 0.05,
    explanation: "Debt-to-equity = debt / equity = 420 / 180 = 2.33x (i.e. 233%).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-D-24",
    paper: "AFM",
    area: "D",
    type: "mcq",
    stem: "After a reconstruction, Thornbury Ltd's projected equity is worth $260m, to be shared between existing shareholders (40%) and swapped-in lenders (60%). Existing shareholders' equity was worth $80m as a going concern but nil on liquidation. What value do existing shareholders receive under the scheme?",
    options: [
      "$80m",
      "$156m",
      "$104m",
      "$260m",
    ],
    correct: 2,
    explanation: "Existing shareholders' share = 260 x 40% = $104m (correct), which exceeds both their $80m going-concern value and their nil liquidation value, so they are better off. '$80m' is the pre-scheme going-concern value. '$156m' is the lenders' 60% share (260 x 0.60). '$260m' is the whole equity, not the shareholders' portion.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM3-D-25",
    paper: "AFM",
    area: "D",
    type: "mcq",
    stem: "Which is a qualitative warning sign of impending corporate failure under an Argenti-style model?",
    options: [
      "A rising Altman Z-score.",
      "Improving interest cover.",
      "A strong and growing cash position.",
      "An autocratic CEO combined with a weak board and poor financial controls.",
    ],
    correct: 3,
    explanation: "Argenti's model emphasises management and system defects - such as a dominant CEO, a passive board and weak controls - as early failure signals (correct). A rising Z-score, improving interest cover and a strengthening cash position are all signs of improving, not deteriorating, health.",
    marks: 2,
    difficulty: "medium",
  },

  // ==========================================================================
  // AREA E - Treasury & advanced risk management (30)
  // ==========================================================================
  {
    id: "AFM3-E-01",
    paper: "AFM",
    area: "E",
    type: "mcq",
    stem: "What is a forward rate agreement (FRA) used for?",
    options: [
      "To fix an interest rate on a notional loan or deposit for a future period, hedging interest-rate risk.",
      "To exchange one currency for another at today's spot rate.",
      "To buy equity index options.",
      "To eliminate all credit risk on a loan.",
    ],
    correct: 0,
    explanation: "An FRA fixes the interest rate for a future notional borrowing or deposit period, hedging interest-rate movements (correct). It is not a spot currency exchange, not an equity-option product, and it does not remove credit risk.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-E-02",
    paper: "AFM",
    area: "E",
    type: "number",
    stem: "A borrower fixes interest on a notional $10,000,000 for a 6-month period using a 3-9 FRA at 5.0%. At settlement the 6-month reference rate is 6.5%. How much does the FRA pay the borrower? Answer in $.",
    numericAnswer: 75000,
    unit: "$",
    tolerance: 100,
    explanation: "Because the reference rate (6.5%) exceeds the FRA rate (5.0%), the borrower receives the difference. Payment = (6.5% - 5.0%) x 6/12 x $10,000,000 = 1.5% x 0.5 x 10,000,000 = 0.0075 x 10,000,000 = $75,000. This offsets the higher interest paid on the underlying loan.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-E-03",
    paper: "AFM",
    area: "E",
    type: "mcq",
    stem: "A treasurer expects to BORROW in three months and fears interest rates will rise. Using interest-rate futures, the treasurer should:",
    options: [
      "buy (go long) interest-rate futures now.",
      "sell (go short) interest-rate futures now.",
      "buy currency futures.",
      "take no action, as futures cannot hedge borrowing.",
    ],
    correct: 1,
    explanation: "Interest-rate futures prices fall as rates rise, so a borrower fearing higher rates sells (shorts) futures to gain when prices fall, offsetting higher borrowing cost (correct). Buying futures would lose money if rates rise. Currency futures hedge FX, not interest-rate, risk. Doing nothing leaves the exposure unhedged.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-E-04",
    paper: "AFM",
    area: "E",
    type: "mcq",
    stem: "An interest-rate cap (a borrower's option) allows a borrower to:",
    options: [
      "lock in a single fixed rate with no premium payable.",
      "guarantee a minimum deposit rate.",
      "set a maximum interest rate while still benefiting if rates fall, in return for paying a premium.",
      "avoid paying any premium at all.",
    ],
    correct: 2,
    explanation: "A cap sets a ceiling on borrowing cost yet lets the borrower gain if rates fall, in exchange for a premium (correct). Locking a single fixed rate with no premium describes a swap or FRA, not an option. Guaranteeing a minimum deposit rate is a floor, used by a depositor. And a cap does require a premium, so 'avoid paying any premium' is wrong.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-E-05",
    paper: "AFM",
    area: "E",
    type: "number",
    stem: "A treasurer wants to hedge a $24,000,000 borrowing for 3 months using 3-month interest-rate futures with a contract size of $1,000,000. How many futures contracts are required? Answer as a whole number of contracts.",
    numericAnswer: 24,
    unit: "contracts",
    tolerance: 0.5,
    explanation: "Number of contracts = (loan amount / contract size) x (loan period / contract period) = (24,000,000 / 1,000,000) x (3 months / 3 months) = 24 x 1 = 24 contracts. The duration factor is 1 because the 3-month loan matches the 3-month contract.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-E-06",
    paper: "AFM",
    area: "E",
    type: "mcq",
    stem: "In futures hedging, what is 'basis'?",
    options: [
      "The premium paid on an interest-rate option.",
      "The tick value of one futures contract.",
      "The notional principal underlying the contract.",
      "The difference between the futures price and the spot (cash) price, which converges to zero at expiry.",
    ],
    correct: 3,
    explanation: "Basis is the gap between the futures and spot prices; it narrows to zero as the contract approaches expiry (correct). It is not an option premium, not the tick value, and not the notional principal - those are separate concepts.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-E-07",
    paper: "AFM",
    area: "E",
    type: "mcq",
    stem: "A three-month interest-rate future has a contract size of $1,000,000. One tick is 0.01% (one basis point). What is the value of one tick?",
    options: [
      "$25",
      "$100",
      "$12.50",
      "$250",
    ],
    correct: 0,
    explanation: "Tick value = contract size x tick size x (3/12) = 1,000,000 x 0.0001 x 0.25 = $25 (correct). '$100' omits the 3/12 time factor. '$12.50' uses half a basis point. '$250' is a factor-of-ten error on the tick size.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-E-08",
    paper: "AFM",
    area: "E",
    type: "number",
    stem: "A treasurer shorts 20 three-month interest-rate futures (contract size $1,000,000) at a price of 95.00. Rates rise and the futures price falls to 94.20. One tick is 0.01% and is worth $25 per contract. What is the total gain on the futures position? Answer in $.",
    numericAnswer: 40000,
    unit: "$",
    tolerance: 100,
    explanation: "Price movement = 95.00 - 94.20 = 0.80, i.e. 0.80 / 0.01 = 80 ticks. As the treasurer is short and the price fell, this is a gain. Gain per contract = 80 ticks x $25 = $2,000. Total gain = 20 contracts x $2,000 = $40,000.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-E-09",
    paper: "AFM",
    area: "E",
    type: "mcq",
    stem: "A borrower who buys an interest-rate cap and simultaneously sells an interest-rate floor has created:",
    options: [
      "a straddle.",
      "a collar, which lowers the net premium cost but gives up the benefit of rates falling below the floor.",
      "a pure cap with unlimited downside benefit.",
      "a currency swap.",
    ],
    correct: 1,
    explanation: "Buying a cap and selling a floor is a collar; the premium received on the floor offsets the cap premium, but the borrower forgoes gains if rates fall below the floor (correct). A straddle is a different option combination; a pure cap keeps all downside benefit (but costs a full premium); and a currency swap is unrelated to interest-rate options.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-E-10",
    paper: "AFM",
    area: "E",
    type: "mcq",
    stem: "In a plain-vanilla interest-rate swap, a company can:",
    options: [
      "exchange one currency's principal for another.",
      "buy exposure to an equity index.",
      "exchange floating-rate interest payments for fixed-rate (or vice versa) on a notional principal.",
      "eliminate the obligation to repay principal.",
    ],
    correct: 2,
    explanation: "An interest-rate swap exchanges fixed for floating interest streams on a notional amount, without exchanging principal (correct). Exchanging principal in different currencies is a currency swap; gaining equity-index exposure is an equity swap; and a swap does not remove the underlying obligation to repay principal.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-E-11",
    paper: "AFM",
    area: "E",
    type: "number",
    stem: "Aldgate plc has borrowed at a fixed 6.0% but wants floating-rate exposure. It enters a swap under which it pays LIBOR and receives 5.7% fixed. Expressed as a spread over LIBOR, what is Aldgate's net floating borrowing cost? Answer as the number of percentage points added to LIBOR, to 1 decimal place.",
    numericAnswer: 0.3,
    unit: "% over LIBOR",
    tolerance: 0.01,
    explanation: "Net cost = interest paid on the loan + swap leg paid - swap leg received = 6.0% (to the bank) + LIBOR (in the swap) - 5.7% (received in the swap) = LIBOR + (6.0% - 5.7%) = LIBOR + 0.3%. So Aldgate's effective floating cost is LIBOR + 0.3 percentage points.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM3-E-12",
    paper: "AFM",
    area: "E",
    type: "mcq",
    stem: "Company X can borrow fixed at 5% or floating at LIBOR+0.3%. Company Y can borrow fixed at 7% or floating at LIBOR+1.3%. What is the total potential gain available from an interest-rate swap based on comparative advantage?",
    options: [
      "3.0%",
      "2.0%",
      "0.5%",
      "1.0%",
    ],
    correct: 3,
    explanation: "Fixed-rate differential = 7% - 5% = 2%. Floating-rate differential = (LIBOR+1.3%) - (LIBOR+0.3%) = 1%. Total swap gain = difference between the two differentials = 2% - 1% = 1.0% (correct). '3.0%' adds them; '2.0%' takes only the fixed differential; '0.5%' halves the answer prematurely (the split between parties comes later).",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM3-E-13",
    paper: "AFM",
    area: "E",
    type: "mcq",
    stem: "A forward exchange contract:",
    options: [
      "locks in an exchange rate today for a currency transaction on a fixed future date.",
      "gives the right, but not the obligation, to exchange currency.",
      "is settled daily through a margin account.",
      "exchanges only interest, not principal.",
    ],
    correct: 0,
    explanation: "A forward fixes today the rate for a currency exchange to settle on a set future date, and it is binding (correct). The right-but-not-obligation feature describes a currency option. Daily margin settlement describes exchange-traded futures. Exchanging only interest describes an interest-rate swap.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-E-14",
    paper: "AFM",
    area: "E",
    type: "number",
    stem: "A UK firm will RECEIVE $2,000,000 in 3 months. The spot rate is $1.2500/GBP. The 3-month US interest rate is 4% per year (1% for the period) and the 3-month UK rate is 2% per year (0.5% for the period). Using a money-market hedge, what GBP amount is locked in? Answer in GBP.",
    numericAnswer: 1592079,
    unit: "GBP",
    tolerance: 500,
    explanation: "To hedge a USD receipt: (1) borrow the present value of the USD now = 2,000,000 / 1.01 = $1,980,198.02; (2) convert at spot to GBP = 1,980,198.02 / 1.2500 = GBP 1,584,158.42; (3) deposit GBP for 3 months at 0.5% = 1,584,158.42 x 1.005 = GBP 1,592,079. The USD receipt in 3 months repays the USD borrowing, leaving the locked-in GBP deposit maturity.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM3-E-15",
    paper: "AFM",
    area: "E",
    type: "mcq",
    stem: "To hedge a future USD PAYMENT using the money market, a GBP-based firm should:",
    options: [
      "borrow USD now and hold it until the payment date.",
      "deposit the present value of the USD now (buying USD at spot, funded by borrowing GBP) so the deposit matures to exactly the USD owed.",
      "sell USD forward only.",
      "take no action, as the money market cannot hedge payments.",
    ],
    correct: 1,
    explanation: "For a USD payment, the firm buys USD now and deposits the present value so it grows to the exact sum owed, funding this by borrowing GBP (correct). Borrowing USD is the technique for hedging a USD receipt, not a payment. Selling USD forward is a forward-market hedge, not a money-market hedge. Taking no action leaves the exposure open.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-E-16",
    paper: "AFM",
    area: "E",
    type: "mcq",
    stem: "A euro-based firm hedges a $6,250,000 receipt using USD futures with a contract size of $125,000. How many contracts are needed?",
    options: [
      "500 contracts",
      "5 contracts",
      "50 contracts",
      "40 contracts",
    ],
    correct: 2,
    explanation: "Contracts = exposure / contract size = 6,250,000 / 125,000 = 50 contracts (correct). '500' multiplies by ten (decimal error). '5' divides by 1,250,000 (a factor-of-ten error the other way). '40' uses an incorrect $156,250 contract size.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM3-E-17",
    paper: "AFM",
    area: "E",
    type: "number",
    stem: "A US firm must PAY EUR 5,000,000 in two months and hedges by buying euro futures (contract size EUR 125,000) at a futures price of $1.1000/EUR. At settlement the futures price is $1.1250/EUR. What is the gain on the futures position? Answer in $.",
    numericAnswer: 125000,
    unit: "$",
    tolerance: 500,
    explanation: "Contracts = 5,000,000 / 125,000 = 40. Notional hedged = 40 x 125,000 = EUR 5,000,000. Price movement in the firm's favour (it is long euro futures and the euro rose) = 1.1250 - 1.1000 = $0.0250 per euro. Gain = 5,000,000 x $0.0250 = $125,000, which offsets the higher cost of buying euros in the spot market.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM3-E-18",
    paper: "AFM",
    area: "E",
    type: "mcq",
    stem: "A currency option is generally preferable to a forward contract when:",
    options: [
      "the cash flow is certain and the firm simply wants the cheapest hedge.",
      "the firm wants to pay no premium at all.",
      "daily margining is a requirement.",
      "there is uncertainty over whether the underlying transaction will occur, and the firm wants downside protection while keeping the upside.",
    ],
    correct: 3,
    explanation: "Options suit uncertain or contingent exposures because they protect the downside yet let the firm walk away and keep any favourable move (correct). If the cash flow is certain and cost is the priority, a forward (no premium) is usually cheaper. Wanting to pay no premium points away from options. Daily margining is a feature of futures, not a reason to choose options.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-E-19",
    paper: "AFM",
    area: "E",
    type: "mcq",
    stem: "A currency swap involves:",
    options: [
      "exchanging principal and interest obligations in one currency for those in another, often to obtain cheaper foreign funding and hedge long-term exposure.",
      "a single spot conversion of one currency into another.",
      "exchanging fixed for floating interest in the same currency only.",
      "buying a call option on a foreign currency.",
    ],
    correct: 0,
    explanation: "A currency swap exchanges principal and interest streams denominated in different currencies, useful for cheaper cross-border funding and long-term hedging (correct). A single spot conversion is a spot FX deal, not a swap. Fixed-for-floating in one currency is an interest-rate swap. Buying a call is a currency option.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-E-20",
    paper: "AFM",
    area: "E",
    type: "number",
    stem: "A trading portfolio has a 1-day 95% value at risk (VaR) of $400,000. Assuming independent, identically distributed daily returns, what is the 16-day 95% VaR (scale by the square root of time)? Answer in $.",
    numericAnswer: 1600000,
    unit: "$",
    tolerance: 1000,
    explanation: "VaR scales with the square root of the time horizon: 16-day VaR = 1-day VaR x sqrt(16) = 400,000 x 4 = $1,600,000.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-E-21",
    paper: "AFM",
    area: "E",
    type: "mcq",
    stem: "A portfolio has a 1-day 99% value at risk (VaR) of $250,000. What does this mean?",
    options: [
      "The portfolio will lose exactly $250,000 every day.",
      "There is a 1% chance the portfolio loses more than $250,000 over one day.",
      "The maximum possible loss on the portfolio is $250,000.",
      "There is a 99% chance the portfolio loses $250,000.",
    ],
    correct: 1,
    explanation: "A 99% 1-day VaR of $250,000 means that on only 1 day in 100 would losses be expected to exceed $250,000 (correct). It is not a fixed daily loss, it is not an absolute maximum (losses in the tail can be larger), and it is not a 99% chance of losing that exact amount.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM3-E-22",
    paper: "AFM",
    area: "E",
    type: "mcq",
    stem: "A portfolio has a 1-day VaR of $100,000. Assuming i.i.d. returns, what is the 4-day VaR?",
    options: [
      "$400,000",
      "$100,000",
      "$200,000",
      "$50,000",
    ],
    correct: 2,
    explanation: "VaR scales by the square root of time: 4-day VaR = 100,000 x sqrt(4) = 100,000 x 2 = $200,000 (correct). '$400,000' multiplies by 4 instead of sqrt(4). '$100,000' applies no scaling. '$50,000' divides by sqrt(4).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-E-23",
    paper: "AFM",
    area: "E",
    type: "number",
    stem: "A trader has written (sold) call options over 100,000 shares. The option delta is 0.40. To create a delta-neutral hedge, how many shares must the trader buy? Answer in shares.",
    numericAnswer: 40000,
    unit: "shares",
    tolerance: 100,
    explanation: "A short call position loses as the share price rises, at a rate of delta per share. To hedge, buy delta x number of shares underlying the options = 0.40 x 100,000 = 40,000 shares. Holding 40,000 shares offsets the delta of the written calls, making the combined position delta-neutral.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM3-E-24",
    paper: "AFM",
    area: "E",
    type: "mcq",
    stem: "The delta of an option measures:",
    options: [
      "the rate of time decay of the option.",
      "the sensitivity of the option value to changes in volatility.",
      "the sensitivity of the option value to changes in interest rates.",
      "the sensitivity of the option value to a small change in the price of the underlying asset.",
    ],
    correct: 3,
    explanation: "Delta is the rate of change of the option value with respect to the underlying asset price (correct). Time decay is theta, sensitivity to volatility is vega, and sensitivity to interest rates is rho.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-E-25",
    paper: "AFM",
    area: "E",
    type: "mcq",
    stem: "A key objective of a corporate treasury risk-management policy is to:",
    options: [
      "identify and manage financial risks (interest, currency, liquidity) within board-approved limits, rather than to speculate.",
      "maximise trading profits through active speculation.",
      "avoid all hedging in order to save costs.",
      "ignore currency exposure because it nets off over time.",
    ],
    correct: 0,
    explanation: "Treasury exists to identify and control financial risk within board-approved limits, not to speculate (correct). Speculating for profit, avoiding all hedging to cut cost, and ignoring currency exposure all breach the risk-management remit of a properly governed treasury function.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-E-26",
    paper: "AFM",
    area: "E",
    type: "number",
    stem: "The spot rate is $1.3000/GBP. The 12-month US interest rate is 3% and the 12-month UK rate is 5%. Using interest rate parity, what is the 12-month forward rate ($ per GBP)? Answer to 4 decimal places.",
    numericAnswer: 1.2752,
    unit: "$/GBP",
    tolerance: 0.002,
    explanation: "Interest rate parity: forward = spot x (1 + interest rate of price currency) / (1 + interest rate of base currency) = 1.3000 x (1.03 / 1.05) = 1.3000 x 0.980952 = $1.2752/GBP. The higher-interest currency (GBP) trades at a forward discount.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-E-27",
    paper: "AFM",
    area: "E",
    type: "mcq",
    stem: "As an option approaches expiry, all else being equal, its time value:",
    options: [
      "increases steadily.",
      "decays towards zero, with the rate of decay accelerating; this is captured by theta.",
      "is unaffected by the passage of time.",
      "becomes negative for call options.",
    ],
    correct: 1,
    explanation: "Time value erodes as expiry nears, and the decay accelerates - measured by theta (correct). Time value does not increase as expiry approaches, it is certainly affected by time, and it cannot go negative; at worst it falls to zero.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM3-E-28",
    paper: "AFM",
    area: "E",
    type: "mcq",
    stem: "The risk that the home-currency value of a specific future foreign-currency cash flow changes before it is settled is called:",
    options: [
      "translation risk.",
      "economic risk.",
      "transaction risk.",
      "credit risk.",
    ],
    correct: 2,
    explanation: "Transaction risk is the exposure of a committed foreign-currency cash flow to exchange-rate moves before settlement (correct). Translation risk affects the reported value of foreign assets/liabilities on consolidation; economic risk concerns the long-run effect of exchange rates on competitiveness; credit risk is the risk of counterparty default.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM3-E-29",
    paper: "AFM",
    area: "E",
    type: "number",
    stem: "In June a treasurer expects to borrow $30,000,000 for 3 months in September and fears rising rates. She hedges with 3-month interest-rate futures (contract size $1,000,000), selling at a price of 94.50. In September the futures price is 93.90. One tick is 0.01%, worth $25 per contract. What is the total gain on the futures hedge? Answer in $.",
    numericAnswer: 45000,
    unit: "$",
    tolerance: 100,
    explanation: "Contracts = (30,000,000 / 1,000,000) x (3/3) = 30. Price fall = 94.50 - 93.90 = 0.60 = 60 ticks. Because the treasurer sold (shorted) and the price fell, this is a gain. Gain = 30 contracts x 60 ticks x $25 = 30 x 1,500 = $45,000, offsetting the extra interest on the September borrowing.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM3-E-30",
    paper: "AFM",
    area: "E",
    type: "mcq",
    stem: "Basis risk in a futures hedge arises because:",
    options: [
      "options always carry a premium.",
      "forward contracts are customised to each counterparty.",
      "interest-rate swaps involve no exchange of principal.",
      "the futures price and the underlying spot price may not move exactly together, so a hedge closed out before expiry is imperfect.",
    ],
    correct: 3,
    explanation: "Basis risk is the danger that the basis (futures minus spot) does not behave as expected before expiry, leaving an imperfect hedge (correct). Option premiums, the customisation of forwards, and the no-principal feature of swaps are characteristics of other instruments and are not the source of futures basis risk.",
    marks: 2,
    difficulty: "medium",
  },
]
