import type { WrittenQuestion } from "@/lib/acca-written"

/*
 * FR · Section C constructed-response questions, first file.
 *
 * ── What this replaces ──────────────────────────────────────────
 * The loader previously served FIFTY Section C questions generated by completeFrSectionC,
 * every one of them the same scenario with the numbers moved — "$X of revenue, $Y of
 * operating profit, an unrecorded adjustment of $Z; prepare a 20-mark response" — and all
 * fifty sharing a single twenty-point generic rubric that named no standard, no figure and
 * no user. A rubric that fits fifty different questions marks none of them.
 *
 * ── The real exam, and the size of the bank ──────────────────────
 * FR's Section C is TWO constructed responses of 20 marks — 40 of the 100 marks, and where
 * the paper is passed or failed. Six would be exactly three disjoint mock sittings, which is
 * the structural minimum and far too shallow for practice: a learner who had worked three
 * mocks would have nothing left, and the AI Examiner nothing left to mark. So the bank is
 * FIFTEEN across this file and its companion.
 *
 * ── What the examiner actually sets ─────────────────────────────
 * One of the two questions is normally a PREPARATION — a single entity from a trial balance,
 * a consolidation, or a statement of cash flows — and the other an INTERPRETATION. The bank
 * is weighted to match, and every question names the USER it is answered for, because the
 * conclusion marks depend on it.
 *
 * Every figure was verified by script before authoring. Each rubric names the specific
 * standard, figure or judgement the mark is for, so the AI Examiner can award or withhold it
 * on evidence rather than on impression.
 *
 * Original Scholify content. No ACCA or Kaplan question is reproduced.
 */

const Q01: WrittenQuestion = {
  id: "FRW-01",
  paper: "FR",
  area: "D",
  chapter: "FR-24",
  topic: "Preparing single-entity financial statements from a trial balance",
  maxMarks: 20,
  stem:
    "The following balances were extracted from the records of Sanderling Co at 31 December 20X6.\n\n" +
    "                                                Dr $           Cr $\n" +
    "  Revenue                                                  13,200,000\n" +
    "  Cost of sales                                7,900,000\n" +
    "  Operating expenses                           2,050,000\n" +
    "  Finance costs paid                              45,000\n" +
    "  Plant and equipment at cost                  5,400,000\n" +
    "  Accumulated depreciation, plant                          1,620,000\n" +
    "  Land at cost                                 3,000,000\n" +
    "  Inventory at 31 December 20X6                1,140,000\n" +
    "  Trade receivables                            1,860,000\n" +
    "  Cash and cash equivalents                      310,000\n" +
    "  Trade payables                                             980,000\n" +
    "  7% loan notes (issued 1 July 20X6)                       2,500,000\n" +
    "  Equity shares of $1 each                                 2,500,000\n" +
    "  Retained earnings at 1 January 20X6                        905,000\n\n" +
    "The following matters require adjustment.\n\n" +
    "(i)   Plant and equipment is depreciated at 12% of cost, charged to cost of sales. Land is not depreciated.\n" +
    "(ii)  Inventory includes items costing $95,000 with a net realisable value of $61,000.\n" +
    "(iii) Loan note interest is payable half-yearly; the only payment made in the year is the $45,000 shown.\n" +
    "(iv)  Operating expenses include $70,000 paid in December for an insurance policy covering the whole of 20X7.\n" +
    "(v)   The land was revalued to $3,450,000 at 31 December 20X6 and Sanderling adopts the revaluation model for land.\n" +
    "(vi)  Income tax for the year is estimated at $390,000.\n\n" +
    "Required:\n\n" +
    "(a) Prepare Sanderling Co's statement of profit or loss and other comprehensive income for the year ended 31 December 20X6. (10 marks)\n\n" +
    "(b) Prepare Sanderling Co's statement of financial position as at 31 December 20X6. (10 marks)",
  rubric: [
    "(a) Cost of sales working: $7,900,000 + depreciation of $5,400,000 × 12% = $648,000 + the inventory write-down of $95,000 − $61,000 = $34,000, giving $8,582,000. Award separately for the depreciation and for the write-down (3 marks).",
    "(a) Gross profit $13,200,000 − $8,582,000 = $4,618,000 (1 mark).",
    "(a) Operating expenses $2,050,000 − $70,000 prepayment = $1,980,000. Credit for identifying the prepayment as relating wholly to 20X7 (2 marks).",
    "(a) Finance costs: the loan notes were issued on 1 July so six months' interest accrues — $2,500,000 × 7% × 6/12 = $87,500. The charge is $87,500 and an accrual of $42,500 is required. Credit for pro-rating from the issue date and for the accrual (2 marks).",
    "(a) Profit before tax = $4,618,000 − $1,980,000 − $87,500 = $2,550,500; tax $390,000; profit for the year $2,160,500 (1 mark).",
    "(a) Other comprehensive income: the land revaluation surplus of $3,450,000 − $3,000,000 = $450,000, presented as an item that will NOT be reclassified to profit or loss. Total comprehensive income $2,610,500. No credit for putting the surplus in profit or loss (1 mark).",
    "(b) Non-current assets: land at the revalued $3,450,000; plant at $5,400,000 − $1,620,000 − $648,000 = $3,132,000. Total $6,582,000 (2 marks).",
    "(b) Current assets: inventory $1,140,000 − $34,000 = $1,106,000; receivables and prepayments $1,860,000 + $70,000 = $1,930,000; cash $310,000. Total $3,346,000 (2 marks).",
    "(b) Equity: share capital $2,500,000; revaluation surplus $450,000; retained earnings $905,000 + $2,160,500 = $3,065,500. Total equity $6,015,500. Credit for showing the revaluation surplus as a separate component (2 marks).",
    "(b) Non-current liabilities: 7% loan notes $2,500,000 (1 mark).",
    "(b) Current liabilities: trade payables $980,000; accrued loan interest $42,500; current tax $390,000. Total $1,412,500 (2 marks).",
    "(b) The statement balances: total assets $9,928,000 = total equity and liabilities $6,015,500 + $2,500,000 + $1,412,500 = $9,928,000. Award for a coherent statement that balances, or for one whose imbalance is confined to a single identified adjustment (1 mark).",
    "Presentation: the two statements set out in recognisable IAS 1 format, workings shown for cost of sales, depreciation, finance costs and the current/non-current split, and each figure traceable to a working.",
  ],
}

const Q02: WrittenQuestion = {
  id: "FRW-02",
  paper: "FR",
  area: "D",
  chapter: "FR-26",
  topic: "Preparing a consolidated statement of financial position",
  maxMarks: 20,
  stem:
    "Gannet Co acquired 800,000 of the 1,000,000 $1 equity shares of Petrel Co on 1 January 20X6. The consideration was $1,450,000 in cash together with a share exchange of three Gannet shares for every five Petrel shares acquired. Gannet's shares have a nominal value of $1 and a market value of $6.40 at the acquisition date. Gannet also paid $95,000 of professional fees, which it has debited to its investment account.\n\n" +
    "At 1 January 20X6 Petrel's equity comprised share capital of $1,200,000 and retained earnings of $2,100,000. Petrel's factory had a fair value $600,000 above its carrying amount, with a remaining useful life of ten years at that date; Petrel has made no adjustment in its own records.\n\n" +
    "At 31 December 20X6:\n" +
    "  Petrel's retained earnings were $2,900,000\n" +
    "  Gannet's own retained earnings were $6,200,000\n" +
    "  Gannet's records showed $310,000 receivable from Petrel; Petrel's showed $250,000 payable, the difference being cash Petrel sent on 30 December which Gannet had not received\n" +
    "  Gannet had sold goods to Petrel during the year for $900,000 at a margin of 25%, of which one third remained in Petrel's inventory\n\n" +
    "Gannet measures non-controlling interests at their proportionate share of the subsidiary's net assets. Goodwill is not impaired.\n\n" +
    "Required:\n\n" +
    "(a) Calculate the consideration transferred, and state how the professional fees should have been treated. (4 marks)\n\n" +
    "(b) Prepare the net assets working for Petrel and calculate goodwill arising on the acquisition. (7 marks)\n\n" +
    "(c) Calculate the non-controlling interest and group retained earnings at 31 December 20X6. (6 marks)\n\n" +
    "(d) Explain the adjustments required for the intra-group balance and the intra-group trading, stating the effect of each on the consolidated statement of financial position. (3 marks)",
  rubric: [
    "(a) Shares issued: 800,000 × 3/5 = 480,000, valued at Gannet's market price of $6.40 = $3,072,000. Plus cash $1,450,000. CONSIDERATION TRANSFERRED $4,522,000 (2 marks).",
    "(a) The $95,000 of professional fees must be EXPENSED, not included in consideration or in the investment. Debiting them to the investment inflates goodwill by $95,000 and overstates profit by the same. Credit for identifying both the treatment and the effect (2 marks).",
    "(b) Net assets at acquisition: share capital $1,200,000 + retained earnings $2,100,000 + factory uplift $600,000 = $3,900,000 (2 marks).",
    "(b) Net assets at the reporting date: $1,200,000 + $2,900,000 + the uplift NET of one year's extra depreciation ($600,000 − $60,000 = $540,000) = $4,640,000. Post-acquisition movement $740,000. Credit specifically for netting the extra depreciation in the closing column (3 marks).",
    "(b) Goodwill = $4,522,000 consideration + NCI at acquisition (20% × $3,900,000 = $780,000) − $3,900,000 = $1,402,000 (2 marks).",
    "(c) NCI at 31 December 20X6 = $780,000 + 20% × $740,000 = $928,000. Credit for using the post-acquisition movement AFTER the extra depreciation (3 marks).",
    "(c) Group retained earnings = Gannet's own $6,200,000 + 80% × $740,000 = $6,792,000, LESS the unrealised profit of $900,000 × 1/3 × 25% = $75,000, because GANNET was the seller. So $6,717,000. Credit for the 80% share, for excluding Petrel's pre-acquisition reserves, and for charging the whole unrealised profit against group reserves (3 marks).",
    "(d) Intra-group balance: the $60,000 is cash in transit, recorded in the RECEIVING company — Gannet — so its cash rises $60,000 and its receivable falls to $250,000. The agreeing $250,000 is then eliminated from group receivables and payables. Net effect: cash up $60,000, receivables down $310,000, payables down $250,000, net assets unchanged (2 marks).",
    "(d) Intra-group trading: group inventory is reduced by the $75,000 of unrealised profit. Because Gannet sold, the whole reduction falls on group retained earnings and the NCI bears none of it — had Petrel sold, it would have reduced Petrel's closing net assets and been shared 80/20 (1 mark).",
    "Credit for the discipline of the two-column net assets working, and for stating that consolidated share capital is GANNET's alone.",
    "No credit for including the $95,000 of fees in consideration, for carrying the fair value uplift at $600,000 in the closing column, or for including Petrel's pre-acquisition retained earnings in group reserves.",
  ],
}

const Q03: WrittenQuestion = {
  id: "FRW-03",
  paper: "FR",
  area: "D",
  chapter: "FR-25",
  topic: "Preparing and interpreting a statement of cash flows",
  maxMarks: 20,
  stem:
    "Curlew Co reports profit before tax of $3,400,000 for the year ended 31 December 20X6. The following information is relevant.\n\n" +
    "  Depreciation charge for the year                       $1,150,000\n" +
    "  Gain on disposal of plant                                 $70,000\n" +
    "  Finance costs charged                                    $310,000\n" +
    "  Increase in inventory                                    $180,000\n" +
    "  Increase in trade receivables                            $240,000\n" +
    "  Increase in trade payables                               $160,000\n" +
    "  PPE carrying amount: opening $8,200,000, closing $9,800,000\n" +
    "  Carrying amount of plant disposed of                     $340,000\n" +
    "  Current tax: opening $420,000, closing $505,000, charge $860,000\n" +
    "  Interest payable: opening $55,000, closing $80,000\n" +
    "  Retained earnings: opening $4,900,000, closing $6,340,000\n" +
    "  Proceeds from a share issue during the year              $800,000\n" +
    "  New long-term borrowings raised                        $1,200,000\n\n" +
    "There were no revaluations during the year. Curlew's directors are concerned that, despite a record profit, the bank overdraft has increased.\n\n" +
    "Required:\n\n" +
    "(a) Prepare Curlew Co's statement of cash flows for the year ended 31 December 20X6, using the indirect method. (14 marks)\n\n" +
    "(b) Using your statement, explain to the directors why a record profit has been accompanied by a deterioration in the bank position. (6 marks)",
  rubric: [
    "(a) Operating reconciliation: $3,400,000 + $1,150,000 depreciation − $70,000 gain on disposal + $310,000 finance costs − $180,000 inventory − $240,000 receivables + $160,000 payables = CASH GENERATED FROM OPERATIONS $4,530,000. Award for the add-backs, for deducting the GAIN, and for the three working capital signs (5 marks).",
    "(a) Interest paid: $55,000 + $310,000 − $80,000 = $285,000 (1 mark).",
    "(a) Tax paid: $420,000 + $860,000 − $505,000 = $775,000 (1 mark).",
    "(a) Net cash from operating activities $4,530,000 − $285,000 − $775,000 = $3,470,000 (1 mark).",
    "(a) PPE additions: $9,800,000 − $8,200,000 + $1,150,000 + $340,000 = $3,090,000, shown as an outflow (2 marks).",
    "(a) Proceeds on disposal: $340,000 carrying amount + $70,000 gain = $410,000 (1 mark).",
    "(a) Net cash used in investing activities $(3,090,000) + $410,000 = $(2,680,000) (1 mark).",
    "(a) Dividends paid: $4,900,000 + profit after tax ($3,400,000 − $860,000 = $2,540,000) − $6,340,000 = $1,100,000 (1 mark).",
    "(a) Financing: share issue $800,000 + new borrowings $1,200,000 − dividends $1,100,000 = $900,000. Net increase in cash $3,470,000 − $2,680,000 + $900,000 = $1,690,000 (1 mark).",
    "(b) Note the apparent contradiction and resolve it honestly: on these figures cash INCREASED by $1,690,000, so the overdraft's deterioration cannot be explained by the year's cash flows alone. Full credit for a candidate who identifies that the arithmetic does not support the directors' premise and asks what else changed — for example a movement in short-term borrowings excluded from cash equivalents, or a timing effect within the year rather than at the two reporting dates (2 marks).",
    "(b) Working capital absorbed $260,000 net ($180,000 + $240,000 − $160,000), so growth is tying cash up in inventory and receivables. Sustained, this is the overtrading pattern, and it is the first thing to monitor (1 mark).",
    "(b) Investment of $3,090,000 exceeded depreciation of $1,150,000 by a wide margin, so the entity is expanding capacity rather than replacing it — funded partly from operations and partly from the $2,000,000 raised in financing (1 mark).",
    "(b) Dividends of $1,100,000 were paid, representing 43% of profit after tax, at the same time as heavy investment. Credit for observing that the combination of expansion and a substantial distribution is what tightens a cash position even in a profitable year (1 mark).",
    "(b) Conclusion for the directors: profit and cash are different measures, and the statement of cash flows shows the year's cash movement was positive. If the overdraft has nonetheless risen, ask for month-by-month cash information, since a statement covering twelve months conceals the position at every date except the two ends (1 mark).",
  ],
}

const Q04: WrittenQuestion = {
  id: "FRW-04",
  paper: "FR",
  area: "C",
  chapter: "FR-31",
  topic: "Interpreting performance for a prospective acquirer",
  maxMarks: 20,
  stem:
    "You are advising the board of Dunlin Co, which is considering acquiring the whole of Fulmar Co. Fulmar's summarised results are:\n\n" +
    "                                    20X6           20X5\n" +
    "  Revenue                      $24,000,000    $19,500,000\n" +
    "  Operating profit              $3,100,000     $2,760,000\n" +
    "  Finance costs                   $620,000       $240,000\n" +
    "  Profit before tax             $2,480,000     $2,520,000\n" +
    "  Inventory                     $3,600,000     $2,400,000\n" +
    "  Trade receivables             $4,100,000     $2,700,000\n" +
    "  Trade payables                $2,900,000     $2,300,000\n" +
    "  Equity                       $10,300,000     $9,400,000\n" +
    "  Long-term borrowings          $7,200,000     $4,000,000\n\n" +
    "Cost of sales was $16,800,000 in 20X6 and $13,300,000 in 20X5. Capital employed is equity plus long-term borrowings.\n\n" +
    "Fulmar's directors explain that in 20X6 the company won two large contracts by tendering below its usual margin, that both customers negotiated 60-day payment terms, and that a new distribution centre was commissioned in August 20X6, funded by borrowings.\n\n" +
    "Required:\n\n" +
    "(a) Calculate, for both years, ROCE, operating profit margin, asset turnover, inventory days, receivables days, gearing (debt to equity) and interest cover. (7 marks)\n\n" +
    "(b) Using your calculations and the information provided, analyse Fulmar Co's performance and position for the board of Dunlin Co. (10 marks)\n\n" +
    "(c) State THREE items of further information you would request before advising on the acquisition, with a reason for each. (3 marks)",
  rubric: [
    "(a) ROCE: 20X6 $3,100,000/$17,500,000 = 17.7%; 20X5 $2,760,000/$13,400,000 = 20.6% (1 mark).",
    "(a) Operating margin: 12.9% against 14.2% (1 mark).",
    "(a) Asset turnover: 1.37 times against 1.46 times (1 mark).",
    "(a) Inventory days: $3,600,000/$16,800,000 × 365 = 78.2 days against $2,400,000/$13,300,000 × 365 = 65.9 days (1 mark).",
    "(a) Receivables days: 62.4 days against 50.5 days (1 mark).",
    "(a) Gearing (debt/equity): 69.9% against 42.6% (1 mark).",
    "(a) Interest cover: 5.0 times against 11.5 times (1 mark).",
    "(b) Revenue grew 23.1% but margin fell 1.3 points, consistent with the two contracts tendered below normal margin. At 20X6 revenue that concession cost roughly $312,000 of operating profit — so the volume must be worth more than that, and on these figures it is, since operating profit still rose $340,000 (2 marks).",
    "(b) ROCE fell 2.9 points, and decomposing it shows BOTH components moved: margin down and asset turnover down from 1.46 to 1.37. The turnover fall is consistent with the distribution centre being commissioned in August — a full balance sheet against five months of the revenue it will eventually support. Credit for the decomposition and for the timing explanation (3 marks).",
    "(b) Working capital has deteriorated materially: inventory days up 12 and receivables days up 12, against payables days up only about 4 ($2,900,000/$16,800,000 × 365 = 63.0 against 63.1 — essentially unchanged). Growth is being financed by the entity rather than by its suppliers (2 marks).",
    "(b) Gearing rose from 42.6% to 69.9% and interest cover more than halved from 11.5 to 5.0 times. For an ACQUIRER this matters twice over: the borrowings will come with the company, and the interest cover trend shows how quickly the position moved in one year (2 marks).",
    "(b) Conclusion for the board: Fulmar is growing and remains profitable, but the QUALITY of that growth has fallen — lower margin, longer working capital cycle, and a funding structure transformed in twelve months. The acquisition may still be attractive, but the price should reflect that the recent revenue growth was bought with margin and with balance sheet capacity rather than earned. Credit for a supported conclusion addressed to the acquirer's decision (1 mark).",
    "(c) CASH FLOW information and forecasts — the working capital deterioration means operating cash flow is probably far below operating profit, and an acquirer inherits the cash position, not the profit (1 mark).",
    "(c) The DURATION and terms of the two large contracts — if they are one-off, the revenue base is not what 20X6 suggests, and customer concentration is itself a risk (1 mark).",
    "(c) A comparator or industry averages, the notes for accounting policies and non-recurring items, the projected return on the distribution centre, existing covenants on the borrowings, and any contingent liabilities or commitments. Any THREE well-reasoned requests, one mark each up to the total available (1 mark).",
    "No credit for computing ratios without narrative, for generic causes not drawn from the scenario, or for a conclusion that summarises the ratios without addressing the acquisition decision.",
  ],
}

const Q05: WrittenQuestion = {
  id: "FRW-05",
  paper: "FR",
  area: "B",
  chapter: "FR-13",
  topic: "Applying IFRS 16, IFRS 15 and IAS 37 to a set of transactions",
  maxMarks: 20,
  stem:
    "Wheatear Co is finalising its financial statements for the year ended 31 December 20X6. Four matters are outstanding.\n\n" +
    "(1) On 1 January 20X6 Wheatear leased specialist equipment for four years, with annual payments of $65,000 in arrears. The rate implicit in the lease is 9% and the four-year annuity factor at 9% is 3.240. Wheatear incurred $7,500 of legal costs. The equipment's useful life is seven years and ownership does not transfer.\n\n" +
    "(2) On 1 October 20X6 Wheatear supplied a customer with machinery and a three-year maintenance contract for a single price of $840,000. It sells the machinery separately for $760,000 and equivalent three-year maintenance for $190,000. Control of the machinery passed on 1 October 20X6.\n\n" +
    "(3) Wheatear has a contract to supply 20,000 units at $14 each. Following a rise in input prices the unavoidable cost of production is now $19 a unit. Wheatear may cancel on payment of a penalty of $78,000. A machine used only for this contract has a carrying amount of $40,000 and would be worthless if the contract were cancelled.\n\n" +
    "(4) On 8 January 20X7, before the financial statements were authorised, a customer owing $260,000 at the year end entered administration; $45,000 is expected to be recovered. On 20 January 20X7 a warehouse with a carrying amount of $1,900,000 was destroyed by fire.\n\n" +
    "Required:\n\n" +
    "For each of the four matters, explain the required accounting treatment and calculate the amounts to be recognised in the financial statements for the year ended 31 December 20X6. (20 marks)",
  rubric: [
    "(1) Lease liability = $65,000 × 3.240 = $210,600. Right-of-use asset = $210,600 + $7,500 initial direct costs = $218,100. Credit for the two figures being DIFFERENT (2 marks).",
    "(1) Depreciation over the shorter of the four-year lease term and the seven-year useful life, ownership not transferring: $218,100 ÷ 4 = $54,525. Finance cost $210,600 × 9% = $18,954. Closing liability $210,600 + $18,954 − $65,000 = $164,554 (3 marks).",
    "(1) Credit for stating that there is no lessee classification test under IFRS 16 and that the only routes off balance sheet are the short-term and low-value exemptions, neither of which applies here (1 mark).",
    "(2) Two performance obligations: the machinery and the maintenance. Standalone selling prices total $950,000, so the machinery is allocated $840,000 × $760,000/$950,000 = $672,000 and the maintenance $840,000 × $190,000/$950,000 = $168,000 (3 marks).",
    "(2) Revenue recognised in 20X6: the whole $672,000 for the machinery on transfer of control, plus three months of the maintenance — $168,000 × 3/36 = $14,000. Total $686,000, with a contract liability of $154,000 (2 marks).",
    "(2) Credit for identifying the maintenance as satisfied OVER TIME because the customer simultaneously receives and consumes the benefit, and for allocating on relative STANDALONE SELLING PRICES rather than on the contract's own split (1 mark).",
    "(3) The contract is onerous: unavoidable costs of 20,000 × $19 = $380,000 exceed revenue of 20,000 × $14 = $280,000, a loss of $100,000 if fulfilled (1 mark).",
    "(3) IMPAIR THE DEDICATED ASSET FIRST: the machine's carrying amount of $40,000 is written off, since it would be worthless on cancellation and its value in use is bound up in a loss-making contract. Credit specifically for taking impairment before the provision — omitting this step double counts or understates the total charge (2 marks).",
    "(3) The provision is the LEAST NET COST OF EXITING: the lower of the $100,000 cost of fulfilling and the $78,000 penalty, so $78,000. Total charge $40,000 impairment + $78,000 provision = $118,000. No credit for providing the full $100,000 where a cheaper exit exists (2 marks).",
    "(4) The customer's administration is an ADJUSTING event: it confirms the receivable's recoverability AT the reporting date. Write the receivable down from $260,000 to $45,000, a charge of $215,000 (2 marks).",
    "(4) The fire is a NON-ADJUSTING event: the warehouse existed and was intact at 31 December 20X6, so no write-down is made. Disclose the nature of the event and an estimate of its financial effect, being material. Credit for the correct classification of BOTH events and for the reason in each case (1 mark).",
    "Presentation: each matter dealt with under its own heading, the standard identified, the treatment explained BEFORE the figures, and workings shown.",
  ],
}

const Q06: WrittenQuestion = {
  id: "FRW-06",
  paper: "FR",
  area: "D",
  chapter: "FR-29",
  topic: "A group with a subsidiary and an associate",
  maxMarks: 20,
  stem:
    "Shoveler Co has two investments.\n\n" +
    "It acquired 75% of Pochard Co on 1 April 20X6 for $5,600,000 in cash. At that date Pochard's share capital was $2,000,000 and its retained earnings $3,200,000. Pochard's brand, which it had generated internally and could not recognise, had a fair value of $700,000 with an estimated remaining life of seven years.\n\n" +
    "It acquired 40% of Teal Co on 1 January 20X6 for $2,800,000, obtaining significant influence through two seats on Teal's board. For the year ended 31 December 20X6 Teal reported profit after tax of $1,150,000 and paid dividends of $400,000. Shoveler sold goods to Teal during the year for $500,000 at a margin of 30%, of which Teal still held one half at the year end.\n\n" +
    "For the year ended 31 December 20X6 Pochard's profit after tax was $1,600,000, accruing evenly. Shoveler measures non-controlling interests at their proportionate share of net assets. Neither goodwill nor the investment in Teal is impaired.\n\n" +
    "Required:\n\n" +
    "(a) Calculate the goodwill arising on the acquisition of Pochard Co. (6 marks)\n\n" +
    "(b) Calculate the amounts relating to Pochard Co that appear in the consolidated statement of profit or loss for the year ended 31 December 20X6, and the non-controlling interest's share. (5 marks)\n\n" +
    "(c) Calculate the carrying amount of the investment in Teal Co at 31 December 20X6 and the share of its profit presented in the consolidated statement of profit or loss. (5 marks)\n\n" +
    "(d) Explain why Pochard is consolidated line by line while Teal is not, and state the effect of holding Teal on the group's reported operating margin. (4 marks)",
  rubric: [
    "(a) Net assets at acquisition: share capital $2,000,000 + retained earnings at 1 April 20X6 + the brand at its fair value of $700,000. Retained earnings at acquisition = $3,200,000 as given (2 marks).",
    "(a) The BRAND is recognised on consolidation at its $700,000 fair value even though Pochard could not recognise it, because IFRS 3 requires identifiable intangibles acquired in a business combination to be recognised separately. Credit for this point specifically — omitting the brand is the commonest error in the question (2 marks).",
    "(a) Net assets acquired $5,900,000. Goodwill = $5,600,000 + NCI at acquisition (25% × $5,900,000 = $1,475,000) − $5,900,000 = $1,175,000 (2 marks).",
    "(b) Pochard is consolidated for NINE months from 1 April: profit after tax $1,600,000 × 9/12 = $1,200,000 (1 mark).",
    "(b) Amortisation of the brand: $700,000 ÷ 7 years = $100,000 a year, pro-rated for nine months = $75,000, charged in the consolidated statement of profit or loss. Credit for the pro-rating (2 marks).",
    "(b) Pochard's adjusted post-acquisition profit = $1,200,000 − $75,000 = $1,125,000. NCI share = 25% × $1,125,000 = $281,250 (2 marks).",
    "(c) Share of Teal's profit = 40% × $1,150,000 = $460,000, presented as a single line after operating profit (1 mark).",
    "(c) Unrealised profit on sales to Teal: $500,000 × 1/2 × 30% = $75,000, of which only the GROUP's share is eliminated — 40% × $75,000 = $30,000. Credit specifically for eliminating only the group's share; eliminating the full $75,000 is the subsidiary treatment (2 marks).",
    "(c) Carrying amount = $2,800,000 cost + $460,000 share of profit − dividend received (40% × $400,000 = $160,000) − $30,000 unrealised profit = $3,070,000. Credit for treating the dividend as a REDUCTION of the investment rather than as income (2 marks).",
    "(d) Pochard is CONTROLLED, so the group directs the use of its assets and presenting them as the group's own is a faithful representation. Teal is only subject to SIGNIFICANT INFLUENCE — the group participates in policy decisions without controlling them — so adding Teal's assets would assert a control the group does not have. The equity method reports the group's interest in Teal's net assets as one figure instead (2 marks).",
    "(d) Effect on operating margin: Teal's PROFIT is included, through the $460,000 line, but NONE of its revenue enters the denominator. So a margin computed on profit before tax is OVERSTATED. Margins should be computed on operating profit, before the associate's line, and the basis stated. Credit for identifying the distortion and for the remedy (2 marks).",
    "No credit for consolidating Teal's revenue and expenses, for recognising the Teal dividend as income, or for omitting the brand from Pochard's net assets acquired.",
  ],
}

const Q07: WrittenQuestion = {
  id: "FRW-07",
  paper: "FR",
  area: "B",
  chapter: "FR-08",
  topic: "Non-current assets: cost, revaluation, impairment and held for sale",
  maxMarks: 20,
  stem:
    "Bittern Co is finalising its financial statements for the year ended 31 December 20X6. The following matters relate to its non-current assets.\n\n" +
    "(1) A production line was completed during the year. Costs were: materials and labour $2,400,000; an allocation of general administrative overhead $180,000; site preparation $130,000; testing $60,000; and staff training $75,000. Proceeds of $40,000 were received from selling output produced during testing. Bittern borrowed $1,800,000 at 8% specifically to fund construction, which ran from 1 March to 31 October 20X6; the loan was drawn on 1 January 20X6 and surplus funds earned $12,000 of interest in January and February.\n\n" +
    "(2) Bittern's head office was carried at a revalued $4,800,000 at 31 December 20X5, with a revaluation surplus of $700,000 attributable to it. Its remaining useful life at that date was 30 years. At 31 December 20X6 its fair value has fallen to $3,900,000.\n\n" +
    "(3) A machine with a carrying amount of $920,000 has been damaged. It could be sold for $560,000 with disposal costs of $25,000, or retained to generate net cash inflows of $180,000 a year for five years; the five-year annuity factor at 10% is 3.791.\n\n" +
    "(4) On 1 September 20X6 the board committed to selling a surplus warehouse, began actively marketing it at a reasonable price and expects to complete within six months. It remains available for immediate sale. Its carrying amount at 1 September was $1,450,000 and its fair value less costs to sell is $1,320,000. It was being depreciated at $60,000 a year.\n\n" +
    "Required:\n\n" +
    "For each of the four matters, explain the required treatment and calculate the amounts recognised. (20 marks)",
  rubric: [
    "(1) Cost includes materials and labour $2,400,000, site preparation $130,000 and testing $60,000. EXCLUDES the general administrative overhead $180,000 (not directly attributable) and staff training $75,000 (the benefit attaches to employees the entity does not control) (2 marks).",
    "(1) The $40,000 of proceeds from testing output goes to PROFIT OR LOSS and does NOT reduce cost — the 2020 amendment to IAS 16. Deducting it is the superseded treatment (2 marks).",
    "(1) Capitalised borrowing costs: capitalisation runs 1 March to 31 October, EIGHT months: $1,800,000 × 8% × 8/12 = $96,000. The $12,000 of investment income was earned in January and February, BEFORE the capitalisation period began, so it is not deducted — it is investment income in profit or loss (3 marks).",
    "(1) Total cost $2,400,000 + $130,000 + $60,000 + $96,000 = $2,686,000. The remaining loan interest of $144,000 − $96,000 = $48,000 is expensed (1 mark).",
    "(2) Carrying amount before revaluation: $4,800,000 − ($4,800,000 ÷ 30 = $160,000) = $4,640,000. The fall to $3,900,000 is $740,000 (2 marks).",
    "(2) Allocation: the revaluation surplus attributable to THIS asset is $700,000, so $700,000 goes to other comprehensive income, extinguishing the surplus, and the remaining $40,000 is charged to PROFIT OR LOSS. Credit for the ordering and for the asset-specific limit — a surplus on another property could not absorb any of it (3 marks).",
    "(3) Recoverable amount is the HIGHER of fair value less costs of disposal ($560,000 − $25,000 = $535,000) and value in use ($180,000 × 3.791 = $682,380), so $682,380 (2 marks).",
    "(3) Impairment loss $920,000 − $682,380 = $237,620, charged to profit or loss. Depreciation thereafter is based on $682,380 over the remaining useful life. No credit for using the lower measure, which would give $385,000 (2 marks).",
    "(4) The warehouse meets the held for sale criteria at 1 September: available for immediate sale in its present condition, management committed, actively marketed at a reasonable price, and a sale expected within one year (1 mark).",
    "(4) Depreciation is charged UP TO 1 September — eight months at $60,000 a year = $40,000 — and then CEASES. Carrying amount at classification $1,450,000 − $40,000 = $1,410,000 (1 mark).",
    "(4) Measured at the lower of carrying amount and fair value less costs to sell: $1,320,000, giving an impairment of $90,000. Presented separately as a CURRENT asset, not offset against any associated liabilities, and the comparative statement of financial position is NOT restated (1 mark).",
    "Presentation: each matter under its own heading with the standard identified, the treatment explained before the figures, and every figure supported by a visible working.",
  ],
}

const Q08: WrittenQuestion = {
  id: "FRW-08",
  paper: "FR",
  area: "C",
  chapter: "FR-32",
  topic: "Interpreting consolidated statements after an acquisition",
  maxMarks: 20,
  stem:
    "You are reporting to the shareholders' committee of Avocet Group. The group acquired a subsidiary, Ruff Co, on 1 May 20X6, and holds a 35% associate acquired several years ago. Summarised group results:\n\n" +
    "                                    20X6           20X5\n" +
    "  Revenue                      $31,000,000    $24,000,000\n" +
    "  Operating profit              $3,720,000     $3,120,000\n" +
    "  Share of profit of associate    $540,000       $480,000\n" +
    "  Finance costs                   $780,000       $420,000\n" +
    "  Profit before tax             $3,480,000     $3,180,000\n" +
    "  Total assets                 $27,400,000    $19,800,000\n" +
    "  of which goodwill             $3,900,000     $1,100,000\n" +
    "  Equity                       $13,600,000    $11,900,000\n" +
    "  Non-controlling interest      $1,700,000              —\n" +
    "  Long-term borrowings          $8,900,000     $4,600,000\n\n" +
    "Ruff contributed $5,200,000 of revenue and $520,000 of operating profit in the eight months since acquisition. The associate's own revenue is not consolidated. Capital employed is equity, including non-controlling interest, plus long-term borrowings.\n\n" +
    "Required:\n\n" +
    "(a) Calculate revenue growth, organic revenue growth, ROCE and operating profit margin for both years, and gearing at both dates. (8 marks)\n\n" +
    "(b) Analyse the group's performance and position, dealing specifically with the effects of the acquisition and of the associate. (9 marks)\n\n" +
    "(c) Explain THREE limitations of your analysis. (3 marks)",
  rubric: [
    "(a) Revenue growth: ($31,000,000 − $24,000,000)/$24,000,000 = 29.2% (1 mark).",
    "(a) Organic revenue growth: ($31,000,000 − $5,200,000 − $24,000,000)/$24,000,000 = 7.5% (2 marks).",
    "(a) ROCE: 20X6 $3,720,000/($13,600,000 + $1,700,000 + $8,900,000 = $24,200,000) = 15.4%; 20X5 $3,120,000/$16,500,000 = 18.9% (2 marks).",
    "(a) Operating margin: 12.0% against 13.0% (1 mark).",
    "(a) Gearing (debt/equity including NCI): $8,900,000/$15,300,000 = 58.2% against $4,600,000/$11,900,000 = 38.7% (2 marks).",
    "(b) Nearly three quarters of the reported revenue growth was ACQUIRED: 29.2% reported against 7.5% organic. And the distortion continues into 20X7, when Ruff will be consolidated for twelve months rather than eight, adding roughly $2,600,000 of further 'growth' with no change in activity (2 marks).",
    "(b) ROCE fell 3.5 points. Two acquisition effects contribute: goodwill of $2,800,000 was added to capital employed and generates no separately identifiable return, and Ruff's whole balance sheet is consolidated against only EIGHT months of its results. Ruff's own contribution — $520,000 of operating profit on $5,200,000 of revenue, a 10.0% margin — is also below the group's, which explains part of the margin dilution (3 marks).",
    "(b) The ASSOCIATE distorts any margin computed on profit before tax. Its $540,000 of profit is included while none of its revenue is, so a 'net margin' of $3,480,000/$31,000,000 = 11.2% mixes an associate-inclusive numerator with an associate-exclusive denominator. Margins must be computed on OPERATING profit, and the basis stated (2 marks).",
    "(b) Gearing rose from 38.7% to 58.2% and finance costs from $420,000 to $780,000, consistent with debt-funded acquisition. Note for the committee that Ruff's own borrowings are consolidated IN FULL even though the group owns less than all of it — the NCI of $1,700,000 shows the group does not own the whole of the acquired equity. And $3,900,000 of the $27,400,000 of total assets is goodwill, which provides no security to a lender (2 marks).",
    "(c) The mid-year acquisition makes the two years non-comparable on every balance-sheet-based ratio, and the effect persists into 20X7 (1 mark).",
    "(c) No cash flow information is given, so it is impossible to say whether the acquired profit is converting into cash, or how the acquisition was funded in cash terms (1 mark).",
    "(c) Any further well-reasoned limitation: only two years of data; no comparator or industry averages; no segmental information to separate Ruff's performance from the rest; policy differences between Ruff and the group before alignment; and no information on commitments or contingencies (1 mark).",
    "No credit for quoting the 29.2% growth without splitting it, for computing margins on profit before tax without noting the associate, or for treating high gearing as evidence the parent borrowed the money.",
  ],
}

export const FR_WRITTEN_KIT: WrittenQuestion[] = [Q01, Q02, Q03, Q04, Q05, Q06, Q07, Q08]
