import type { AccaQuestion } from "@/lib/acca-content"

export const FM_OFFICIAL_QUESTIONS: AccaQuestion[] = [
  { id: "FM-B-O01", paper: "FM", area: "B", type: "mcq", stem: "Which monetary-policy action would normally be expected to reduce aggregate demand?", options: ["A reduction in policy interest rates", "An increase in policy interest rates", "A reduction in income tax", "An increase in government capital spending"], correct: 1, explanation: "Higher policy rates tend to increase borrowing costs, discourage consumption and investment, and reduce aggregate demand. Tax cuts and higher public spending are expansionary fiscal actions.", marks: 2, difficulty: "easy" },
  { id: "FM-B-O02", paper: "FM", area: "B", type: "mcq", stem: "What is the central economic role of a financial intermediary?", options: ["Eliminate all investment risk", "Channel funds from surplus units to deficit units while transforming maturity and risk", "Set fiscal policy", "Guarantee that security prices are correct"], correct: 1, explanation: "Banks and other intermediaries connect savers and borrowers and transform maturity, liquidity and risk; they cannot remove all risk or set government fiscal policy.", marks: 2, difficulty: "medium" },
  { id: "FM-B-O03", paper: "FM", area: "B", type: "mcq", stem: "Which instrument is most characteristic of the money market?", options: ["An ordinary share", "A 20-year corporate bond", "A short-term negotiable certificate of deposit", "A freehold property"], correct: 2, explanation: "Money markets provide short-term liquidity and trade short-dated instruments such as treasury bills and certificates of deposit. Shares and long-term bonds belong to capital markets.", marks: 2, difficulty: "easy" },
  { id: "FM-H-O01", paper: "FM", area: "H", type: "mcq", stem: "A spreadsheet NPV model contains cash flows in B5:B9 and discount factors in C5:C9. Which approach creates the clearest audit trail?", options: ["Type the NPV as a fixed number", "Use =SUMPRODUCT(B5:B9,C5:C9) and label the inputs", "Hide all formulas", "Round each cash flow before entering it"], correct: 1, explanation: "A labeled SUMPRODUCT preserves the relationship between cash flows and discount factors and recalculates transparently when assumptions change.", marks: 2, difficulty: "easy" },
  { id: "FM-H-O02", paper: "FM", area: "H", type: "mcq", stem: "When comparing two financing scenarios digitally, what is the strongest modelling control?", options: ["Use different units in each scenario", "Separate assumptions from formulas and apply a reconciliation or reasonableness check", "Overwrite the base case", "Present only the preferred answer"], correct: 1, explanation: "Separated assumptions, consistent units and visible checks make scenarios repeatable and reviewable and reduce the risk of hidden hard-coded changes.", marks: 2, difficulty: "medium" },
  { id: "FM-H-O03", paper: "FM", area: "H", type: "mcq", stem: "Which presentation is most useful to a board deciding whether to accept an investment?", options: ["An unlabeled spreadsheet screenshot", "NPV alone with no assumptions", "A concise recommendation supported by NPV, key assumptions, sensitivity and major non-financial risks", "Every intermediate calculation without a conclusion"], correct: 2, explanation: "Decision-useful communication states a recommendation, quantifies value, exposes important assumptions and uncertainty, and acknowledges relevant non-financial considerations.", marks: 2, difficulty: "medium" },
]
