import type { AccaQuestion } from "@/lib/acca-content"

/*
 * SBR bank wave S1 part B (areas C, D, E) — 85 verified original questions.
 * Date authored: 2026-07-13.
 * Blueprint: C40 D30 E15; difficulty 22 easy / 40 medium / 23 hard;
 *   70 mcq + 15 number (all numeric items sit in areas C and D).
 * Every distractor is a nameable technical error; every explanation names why
 * each wrong option is wrong AND states the correct IFRS treatment. Every
 * computation was re-solved digit-by-digit from the stem and every IFRS rule
 * verified against the public SBR syllabus. All company names and figures are
 * invented — no ACCA/Kaplan/BPP material is reproduced.
 */

export const SBR_WAVE1B: AccaQuestion[] = [
  /* ═══════════════ AREA C — Groups & business combinations (40) ═══════════════
     IFRS 10 control · IFRS 3 goodwill/consideration · step & piecemeal deals ·
     disposals & loss of control · IAS 28 associates · IFRS 11 joint arrangements ·
     intra-group eliminations (PURP, loans, dividends, PPE) · FV adjustments &
     depreciation · vertical/D-shaped groups · IAS 21 foreign subsidiaries. */

  {
    id: "SBR3-C-01",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "Under IFRS 10, an investor controls an investee only when it has ALL of which combination of elements?",
    options: [
      "Power over the investee, exposure or rights to variable returns, and the ability to use its power to affect those returns",
      "Ownership of more than 50% of the ordinary shares and a majority of the board seats",
      "Power over the investee and the right to appoint the external auditors",
      "Exposure to variable returns and at least one seat on the board of directors",
    ],
    correct: 0,
    explanation:
      "IFRS 10 defines control as three simultaneous elements: power, exposure/rights to variable returns, and the ability to use power to affect those returns. Option 2 confuses control with a mechanical majority-shareholding rule — control is substance-based and can exist below 50% or be absent above it. Options 3 and 4 each isolate a single element and add rights (auditor appointment, one board seat) that do not by themselves confer power.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR3-C-02",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "Panthera Co holds 45% of the voting shares of Serval Co. The other 55% is spread among several thousand shareholders, none holding more than 1%, and historically very few attend or vote at general meetings. Under IFRS 10, Panthera most likely:",
    options: [
      "Does not control Serval, because it holds fewer than 50% of the votes",
      "Controls Serval through de facto power, because its holding is dominant relative to the widely dispersed remainder",
      "Has only significant influence and must equity account for Serval as an associate",
      "Must treat Serval as a joint venture because control is shared with the other shareholders",
    ],
    correct: 1,
    explanation:
      "IFRS 10 recognises de facto control: a holding well below 50% can give power when the remaining votes are widely dispersed and passive, so the investor can direct the relevant activities in practice. Option 1 applies the mechanical 50% test IFRS 10 rejects. Option 3 (associate) understates a relationship that is control, not mere influence. Option 4 wrongly implies a contractual sharing of control — there is no joint arrangement here.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR3-C-03",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "Under IFRS 3, goodwill arising on a business combination is measured as:",
    options: [
      "Consideration transferred less the fair value of the subsidiary's identifiable net assets at acquisition",
      "Consideration transferred plus the carrying amount of the non-controlling interest, less the book value of net assets acquired",
      "Consideration transferred, plus the amount of any non-controlling interest, plus the fair value of any previously held equity interest, less the fair value of identifiable net assets acquired",
      "The excess of the fair value of identifiable net assets acquired over the consideration transferred",
    ],
    correct: 2,
    explanation:
      "IFRS 3 goodwill = consideration transferred + NCI + fair value of any previously held interest − fair value of identifiable net assets acquired. Option 1 omits both NCI and any prior interest (it is correct only for an outright 100% cash purchase). Option 2 wrongly uses the carrying amount of NCI and the book value (not fair value) of net assets. Option 4 describes a bargain purchase (negative goodwill), not goodwill.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR3-C-04",
    paper: "SBR",
    area: "C",
    type: "number",
    stem: "On 1 January 20X5 Aldermore Co acquired 80% of Brightwater Co for cash of $960,000. The non-controlling interest was measured at its acquisition-date fair value of $220,000 (the full/fair value method). The fair value of Brightwater's identifiable net assets at that date was $1,050,000. What is the goodwill on acquisition, in $?",
    numericAnswer: 130000,
    unit: "$",
    tolerance: 0,
    explanation:
      "Full-method goodwill = consideration + NCI at fair value − FV of identifiable net assets = 960,000 + 220,000 − 1,050,000 = $130,000. Using only the parent's 80% share of net assets, or omitting the NCI, would give the proportionate figure and misstate goodwill.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR3-C-05",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "A parent chooses to measure the non-controlling interest at its proportionate share of the subsidiary's identifiable net assets, rather than at fair value. Compared with the fair value method, this choice will:",
    options: [
      "Increase both goodwill and the non-controlling interest",
      "Have no effect on goodwill because goodwill is a parent-only figure",
      "Increase goodwill but leave the non-controlling interest unchanged",
      "Reduce both goodwill and the non-controlling interest recognised at acquisition",
    ],
    correct: 3,
    explanation:
      "Under the proportionate method NCI excludes any goodwill attributable to it, so both the NCI figure and total goodwill are lower than under the fair value method. Options 1 and 3 have the direction of the goodwill effect wrong (the proportionate method lowers, not raises, goodwill). Option 2 is false — the NCI measurement choice directly changes goodwill because NCI is a component of the goodwill calculation.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-C-06",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "The fair value of identifiable net assets acquired exceeds the total of consideration transferred plus non-controlling interest. Under IFRS 3, the acquirer should:",
    options: [
      "Reassess the identification and measurement of the assets, liabilities and consideration, and recognise any remaining excess as a gain in profit or loss",
      "Recognise the excess as negative goodwill and amortise it to profit or loss over its useful life",
      "Credit the excess directly to a capital reserve within equity",
      "Deduct the excess from the carrying amount of the acquired non-current assets on a pro-rata basis",
    ],
    correct: 0,
    explanation:
      "IFRS 3 requires the acquirer first to re-check that all assets/liabilities/consideration are correctly identified and measured; any genuine remaining excess (a bargain purchase) is recognised immediately as a gain in profit or loss. Option 2 applies the old amortisation approach IFRS 3 abolished. Option 3 (a reserve) and Option 4 (writing the excess against non-current assets) are both superseded methods no longer permitted.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-C-07",
    paper: "SBR",
    area: "C",
    type: "number",
    stem: "On 1 April 20X6 Camborne Co acquired 75% of Delabole Co for cash of $600,000. Camborne measures the non-controlling interest at its proportionate share of Delabole's identifiable net assets. The fair value of those net assets at acquisition was $700,000. What is the goodwill on acquisition, in $?",
    numericAnswer: 75000,
    unit: "$",
    tolerance: 0,
    explanation:
      "Proportionate-method goodwill = consideration + (NCI% × FV of net assets) − FV of net assets = 600,000 + (25% × 700,000) − 700,000 = 600,000 + 175,000 − 700,000 = $75,000. Equivalently: 600,000 − (75% × 700,000) = 600,000 − 525,000 = $75,000.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-C-08",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "Escombe Co incurred $40,000 of legal and due-diligence fees and $15,000 of costs to issue the shares used as consideration in acquiring a subsidiary. Under IFRS 3, these amounts are treated as:",
    options: [
      "Acquisition-related fees expensed to profit or loss; share-issue costs deducted from equity (share premium)",
      "Both added to the cost of the investment and hence to goodwill",
      "Both expensed to profit or loss as incurred",
      "Acquisition-related fees capitalised into goodwill; share-issue costs expensed",
    ],
    correct: 0,
    explanation:
      "IFRS 3 requires acquisition-related costs (legal, advisory, due diligence) to be expensed as incurred; costs of issuing equity instruments are accounted for under IAS 32 as a deduction from equity (share premium). Option 2 wrongly capitalises both into goodwill (the pre-IFRS 3 approach). Option 3 misses that share-issue costs go against equity, not profit or loss. Option 4 reverses the correct treatment of the two cost types.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR3-C-09",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "As part of acquiring a subsidiary, Fettercairn Co agrees to pay the former owners an additional $2m in two years if a profit target is met. At acquisition the fair value of this contingent consideration is $1.4m. Under IFRS 3, the contingent consideration is:",
    options: [
      "Ignored until payment becomes probable, then recognised as a liability",
      "Recognised at the undiscounted maximum of $2m as part of consideration",
      "Recognised at its acquisition-date fair value of $1.4m as part of the consideration transferred",
      "Recognised as a provision measured at the best estimate of the expenditure under IAS 37",
    ],
    correct: 2,
    explanation:
      "IFRS 3 requires contingent consideration to be measured at its acquisition-date fair value ($1.4m) and included in consideration transferred. Option 1 (wait until probable) applies IAS 37 recognition, which IFRS 3 overrides for contingent consideration. Option 2 uses the undiscounted maximum rather than fair value. Option 4 also wrongly imports IAS 37; the item is measured at fair value under IFRS 3, and if classified as a financial liability is later remeasured through profit or loss.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-C-10",
    paper: "SBR",
    area: "C",
    type: "number",
    stem: "Grampian Co owns 80% of Hartfell Co, giving a 20% non-controlling interest measured at fair value of $220,000 at acquisition. Since acquisition Hartfell has earned post-acquisition retained profits of $150,000, but a fair value uplift to plant has generated additional post-acquisition depreciation of $10,000 (charged against those profits in the consolidation). What is the non-controlling interest to be shown in the consolidated statement of financial position, in $?",
    numericAnswer: 248000,
    unit: "$",
    tolerance: 0,
    explanation:
      "Closing NCI = NCI at acquisition (fair value) + NCI% × post-acquisition change in net assets = 220,000 + 20% × (150,000 − 10,000) = 220,000 + 20% × 140,000 = 220,000 + 28,000 = $248,000. The extra fair value depreciation must reduce post-acquisition profits before applying the NCI percentage.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-C-11",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "An investor already holds a 30% associate interest and then buys a further 40%, obtaining control. Under IFRS 3, the previously held 30% interest is:",
    options: [
      "Carried forward at its equity-accounted carrying amount, with no gain or loss",
      "Added to the new consideration at its original cost when computing goodwill",
      "Written off in full against consolidated retained earnings on the date control is obtained",
      "Remeasured to fair value at the date control is obtained, with any resulting gain or loss recognised in profit or loss",
    ],
    correct: 3,
    explanation:
      "In a step acquisition achieving control, IFRS 3 requires the previously held interest to be remeasured to fair value at the date control is obtained, with the gain or loss taken to profit or loss; that fair value then forms part of the goodwill calculation. Option 1 wrongly keeps the equity-accounted amount. Option 2 uses original cost, ignoring remeasurement. Option 3 (writing it off) has no basis in IFRS 3.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-C-12",
    paper: "SBR",
    area: "C",
    type: "number",
    stem: "Innerleithen Co held a 30% associate interest in Jedburgh Co with an equity-accounted carrying amount of $250,000. On 1 July 20X7 it acquired a further 40% and obtained control; the fair value of the original 30% interest at that date was $310,000. What gain on the previously held interest is recognised in profit or loss under IFRS 3, in $?",
    numericAnswer: 60000,
    unit: "$",
    tolerance: 0,
    explanation:
      "On achieving control the previously held interest is remeasured to fair value with the difference to profit or loss: gain = fair value − carrying amount = 310,000 − 250,000 = $60,000. This $310,000 fair value (not the $250,000 carrying amount) is then used in the goodwill calculation.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-C-13",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "A parent that already controls a subsidiary sells a further block of shares to the non-controlling interest but retains control. Under IFRS 10, this transaction is accounted for as:",
    options: [
      "An equity transaction between owners, adjusting the carrying amounts of NCI and parent equity with no gain or loss to profit or loss",
      "A partial disposal generating a gain or loss recognised in profit or loss",
      "A remeasurement of the retained interest to fair value with the difference to other comprehensive income",
      "A reduction of goodwill by the proportion of shares sold",
    ],
    correct: 0,
    explanation:
      "IFRS 10 treats changes in a parent's ownership interest that do not result in loss of control as transactions with owners in their capacity as owners (equity transactions): NCI and parent equity are adjusted, and any difference between consideration and the NCI adjustment goes to equity, not profit or loss. Option 2 wrongly books a P/L gain. Option 3 applies loss-of-control mechanics. Option 4 incorrectly derecognises goodwill, which is not touched while control is retained.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-C-14",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "Kilmarnock Co sells enough of its holding in a subsidiary to lose control, but keeps a small equity stake. Under IFRS 10, the retained interest is:",
    options: [
      "Kept at its previous consolidated carrying amount within the group figures",
      "Remeasured to fair value at the date control is lost, and that fair value is used in calculating the gain or loss on disposal",
      "Measured at the parent's share of the subsidiary's net assets on the disposal date",
      "Recorded at the original cost of the shares retained",
    ],
    correct: 1,
    explanation:
      "On loss of control IFRS 10 requires the retained interest to be remeasured to fair value at that date; this fair value is included in computing the disposal gain or loss and becomes the initial carrying amount of the retained investment (as an associate, financial asset, etc.). Option 1 fails to remeasure. Option 3 uses a net-asset share rather than fair value. Option 4 reverts to original cost, ignoring the remeasurement IFRS 10 requires.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR3-C-15",
    paper: "SBR",
    area: "C",
    type: "number",
    stem: "During the year Lomond Co (the parent) sold goods to its subsidiary Moffat Co for $80,000, earning a gross margin of 25% on the selling price. At the year end, half of these goods remain in Moffat's inventory. What is the provision for unrealised profit to be eliminated on consolidation, in $?",
    numericAnswer: 10000,
    unit: "$",
    tolerance: 0,
    explanation:
      "Unrealised profit is the profit on goods still held within the group. Goods remaining = 50% × 80,000 = 40,000; at a 25% margin the profit within them = 40,000 × 25% = $10,000. Because the parent is the seller, this reduces group retained earnings and inventory. (A 25% margin is profit on selling price — using it as a mark-up on cost would be the classic error.)",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR3-C-16",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "Under IAS 28, an investor is presumed to have significant influence over an investee when it holds:",
    options: [
      "More than 50% of the voting power, unless another party has control",
      "Any equity interest, provided the investor supplies management services",
      "20% or more of the voting power, unless it can be clearly demonstrated that this is not the case",
      "Between 5% and 20% of the voting power in a listed entity",
    ],
    correct: 2,
    explanation:
      "IAS 28 sets a rebuttable presumption of significant influence at 20% or more of the voting power, unless clearly demonstrated otherwise (and significant influence can exist below 20% through, e.g., board representation). Option 1 describes control, not significant influence. Option 2 ignores the voting-power test entirely. Option 4 invents a 5–20% band that IAS 28 does not use.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR3-C-17",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "Under the equity method for an associate, the investor's share of the associate's profit for the year is:",
    options: [
      "Consolidated line-by-line into group revenue and expenses",
      "Recognised only when the associate declares a dividend",
      "Recognised as a single line in profit or loss and added to the carrying amount of the investment",
      "Credited directly to a revaluation surplus within equity",
    ],
    correct: 2,
    explanation:
      "The equity method recognises the investor's share of the associate's profit as one line in profit or loss and increases the investment's carrying amount by the same share (dividends received then reduce the carrying amount). Option 1 describes full consolidation, which does not apply to associates. Option 2 is the cost method's dividend basis, not the equity method. Option 3/4-style crediting to a revaluation surplus is wrong — the share of profit passes through profit or loss.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-C-18",
    paper: "SBR",
    area: "C",
    type: "number",
    stem: "Nairn Co owns 70% of Oban Co. During the year Oban (the subsidiary) sold goods to Nairn for $60,000 at a mark-up of 20% on cost. At the year end, 60% of these goods remain unsold in Nairn's inventory. What is the unrealised profit to be eliminated on consolidation, in $?",
    numericAnswer: 6000,
    unit: "$",
    tolerance: 0,
    explanation:
      "Goods remaining = 60% × 60,000 = 36,000. With a 20% mark-up on cost, profit = 36,000 × 20/120 = $6,000. Because the goods are within the group at the year end this profit is unrealised and is eliminated in full against inventory and against the seller's (the subsidiary's) profit — a share of which is then borne by the NCI.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-C-19",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "Two parties share control of an arrangement, and each has rights only to the net assets of the arrangement, which is structured through a separate legal entity. Under IFRS 11, the arrangement is:",
    options: [
      "A joint venture, accounted for using the equity method",
      "A joint operation, with each party recognising its share of assets, liabilities, revenue and expenses",
      "A subsidiary of whichever party contributed the most capital",
      "An associate, because control is shared rather than exclusive",
    ],
    correct: 0,
    explanation:
      "IFRS 11 classifies a joint arrangement giving the parties rights to the net assets as a joint venture, accounted for by the equity method. Option 2 describes a joint operation (rights to individual assets/obligations for liabilities), which is not the case here. Option 3 is wrong because control is shared, not held by one party. Option 4 confuses shared control (joint control) with significant influence (associate).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-C-20",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "In a joint operation under IFRS 11, each joint operator accounts for:",
    options: [
      "A single investment line measured using the equity method",
      "Its share of the assets, liabilities, revenue and expenses relating to its interest in the operation",
      "The full assets and liabilities of the operation, with a non-controlling interest for the other parties",
      "A financial asset measured at fair value through profit or loss",
    ],
    correct: 1,
    explanation:
      "In a joint operation the operators have rights to the assets and obligations for the liabilities, so each recognises its share of assets, liabilities, revenue and expenses. Option 1 is the joint-venture (equity) treatment. Option 3 wrongly applies subsidiary-style full consolidation with an NCI. Option 4 treats the interest as an ordinary financial asset, ignoring the joint-operation rules.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-C-21",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "A parent has lent $200,000 to its wholly owned subsidiary, recorded as a receivable in the parent and a payable in the subsidiary. On consolidation, this intra-group loan is:",
    options: [
      "Shown as a receivable of the group with a matching non-controlling interest",
      "Reclassified as goodwill",
      "Eliminated in full, so neither the receivable nor the payable appears in the consolidated statement of financial position",
      "Netted against group retained earnings",
    ],
    correct: 2,
    explanation:
      "Intra-group balances are eliminated in full on consolidation because the group cannot owe money to itself; both the $200,000 receivable and payable disappear. Option 1 wrongly retains the balance and misuses NCI. Option 2 has no basis — an intra-group loan is not goodwill. Option 4 confuses balance-sheet elimination with an adjustment to retained earnings.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR3-C-22",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "A partly owned subsidiary pays a dividend during the year. In the consolidated financial statements:",
    options: [
      "The whole dividend is shown as group income",
      "The dividend is added to consolidated goodwill",
      "The dividend is eliminated entirely and does not affect group profit at all",
      "The parent's share is eliminated against the parent's investment income, and the non-controlling interest's share reduces the NCI",
    ],
    correct: 3,
    explanation:
      "On consolidation the parent's share of the subsidiary's dividend is eliminated against the parent's recorded investment income (it is internal), while the NCI's share is a real outflow to outside owners and reduces the NCI in equity. Option 1 double-counts income already reflected via consolidation of the subsidiary's profit. Option 2 has no basis. Option 3 is wrong because the NCI portion is not simply eliminated — it reduces the NCI balance.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-C-23",
    paper: "SBR",
    area: "C",
    type: "number",
    stem: "Perth Co owns 70% of Quorn Co. Perth's own retained earnings are $800,000. Quorn's post-acquisition retained earnings are $200,000. A fair value uplift to Quorn's buildings at acquisition has produced additional post-acquisition depreciation of $15,000 (not yet reflected in Quorn's own figures). Perth sold goods to Quorn and $10,000 of unrealised profit remains in inventory (Perth is the seller). What are the consolidated retained earnings attributable to the parent, in $?",
    numericAnswer: 919500,
    unit: "$",
    tolerance: 0,
    explanation:
      "Group retained earnings = parent's RE − PURP (seller is parent) + parent's share of adjusted post-acquisition RE of the subsidiary. Adjusted sub post-acq RE = 200,000 − 15,000 extra depreciation = 185,000; parent's 70% share = 129,500. So group RE = 800,000 − 10,000 + 129,500 = $919,500. The PURP hits the parent in full because the parent made the sale; the fair value depreciation reduces the subsidiary's post-acquisition profits before the 70% share.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR3-C-24",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "When goods are sold at a profit from a subsidiary UP to the parent and remain in inventory at the year end, the unrealised profit adjustment:",
    options: [
      "Is shared between group retained earnings and the non-controlling interest, because the selling company (the subsidiary) generated the profit",
      "Falls entirely on the parent's retained earnings, because the parent holds the inventory",
      "Is ignored, because the goods have left the subsidiary",
      "Increases goodwill by the amount of the unrealised profit",
    ],
    correct: 0,
    explanation:
      "Unrealised profit is charged against the company that made the sale. Where the subsidiary is the seller (upstream sale), the elimination reduces the subsidiary's profit and is therefore shared between group retained earnings and the NCI in the profit-sharing ratio. Option 2 wrongly loads it all onto the parent (that is the treatment for a downstream sale). Option 3 ignores unrealised profit still held in the group. Option 4 has no basis — PURP does not touch goodwill.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-C-25",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "At acquisition, a subsidiary's plant had a fair value $80,000 above its carrying amount, with a remaining useful life of 8 years. In the consolidated financial statements after acquisition, the group must:",
    options: [
      "Recognise the $80,000 uplift but ignore any effect on depreciation",
      "Recognise the $80,000 fair value uplift and charge additional depreciation of $10,000 per year against post-acquisition profit",
      "Add the $80,000 to goodwill and leave the subsidiary's own depreciation unchanged",
      "Revalue the plant to fair value only in the year of disposal",
    ],
    correct: 1,
    explanation:
      "Fair value adjustments become part of the consolidated carrying amount and are depreciated over remaining useful life: 80,000 ÷ 8 = $10,000 extra depreciation each year, reducing post-acquisition profit (and the NCI's share where relevant). Option 1 recognises the uplift but omits the consequential depreciation. Option 3 misclassifies the uplift as goodwill. Option 4 defers recognition entirely, which is not permitted.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-C-26",
    paper: "SBR",
    area: "C",
    type: "number",
    stem: "On 31 December 20X8 Rannoch Co sold its entire 90% holding in Skye Co for cash of $1,400,000, thereby losing control. At the disposal date the consolidated carrying amount of Skye's identifiable net assets was $1,300,000, goodwill relating to Skye (measured under the fair value method) was $120,000, and the non-controlling interest stood at $150,000. What is the group gain or loss on disposal recognised in profit or loss, in $ (enter a positive number for a gain)?",
    numericAnswer: 130000,
    unit: "$",
    tolerance: 0,
    explanation:
      "Group gain on loss of control = proceeds + NCI derecognised − net assets derecognised − goodwill derecognised = 1,400,000 + 150,000 − 1,300,000 − 120,000 = $130,000 gain. Adding back the NCI and removing goodwill are essential steps; omitting the NCI or the goodwill would misstate the gain.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR3-C-27",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "Tummel Co owns 80% of Unst Co, and Unst owns 75% of Voe Co (a sub-subsidiary acquired after Tummel gained control of Unst). What is the effective interest of Tummel's group in Voe, and how is Voe consolidated?",
    options: [
      "75% effective interest; Voe is equity accounted as an associate",
      "80% effective interest; Voe is proportionally consolidated",
      "60% effective interest; Voe is fully consolidated with a 40% non-controlling interest",
      "55% effective interest; Voe is fully consolidated with a 45% non-controlling interest",
    ],
    correct: 2,
    explanation:
      "The group controls Unst, and Unst controls Voe, so the group controls Voe and consolidates it in full. The effective interest is 80% × 75% = 60%, leaving a 40% non-controlling interest (the 20% direct outside interest in Unst plus the 25% direct outside interest in Voe, combined). Option 1 wrongly treats Voe as an associate despite indirect control. Option 2 uses proportional consolidation (not permitted for subsidiaries) and the wrong percentage. Option 4's 55%/45% arithmetic is simply incorrect.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR3-C-28",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "In a mixed (D-shaped) group, parent Wick Co directly owns 60% of Yarrow Co and also directly owns 20% of Zeal Co, while Yarrow owns a further 50% of Zeal. Zeal is controlled by the group. What is the group's effective interest in Zeal?",
    options: [
      "70%, being 20% direct plus 50% indirect",
      "50%, being only the interest held through Yarrow",
      "80%, being 60% plus 20%",
      "50%, being 20% direct plus 60% × 50% = 30% indirect",
    ],
    correct: 3,
    explanation:
      "In a D-shaped group the effective interest is the direct holding plus the group's share of the indirect holding: 20% direct + (60% × 50%) indirect = 20% + 30% = 50%. Option 1 adds the full 50% indirect stake without applying the 60% group share of Yarrow. Option 2 ignores the direct 20% holding. Option 3 wrongly adds the 20% Zeal stake to the 60% Yarrow stake, which measure different companies.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR3-C-29",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "When translating the financial statements of a foreign subsidiary into the group's presentation currency under IAS 21, which rates are used?",
    options: [
      "Assets and liabilities at the closing rate; income and expenses at the rate at the transaction dates (or an average as an approximation)",
      "All items at the closing rate at the reporting date",
      "All items at the historical rate on the acquisition date",
      "Assets and liabilities at the average rate; income and expenses at the closing rate",
    ],
    correct: 0,
    explanation:
      "IAS 21 translates a foreign operation's assets and liabilities at the closing rate and its income and expenses at the rates ruling on the transaction dates (an average rate is a common approximation). Option 2 wrongly applies the closing rate to income and expenses. Option 3 fixes everything at a historical rate, ignoring exchange movements. Option 4 swaps the two rates around.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-C-30",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "The exchange differences arising on translating a foreign subsidiary's financial statements into the group's presentation currency are:",
    options: [
      "Recognised in profit or loss as a foreign exchange gain or loss for the year",
      "Recognised in other comprehensive income and accumulated in a separate component of equity (translation reserve)",
      "Adjusted against goodwill so that goodwill absorbs all currency movements",
      "Ignored until the foreign subsidiary is disposed of",
    ],
    correct: 1,
    explanation:
      "Under IAS 21 the exchange differences on translating a foreign operation are recognised in other comprehensive income and accumulated in a translation reserve; they are reclassified to profit or loss only on disposal of the operation. Option 1 wrongly routes them through profit or loss. Option 3 puts all movements into goodwill, which is not how the reserve works. Option 4 defers recognition entirely, contradicting the OCI requirement.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-C-31",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "Goodwill arising on the acquisition of a foreign subsidiary is, under IAS 21:",
    options: [
      "Fixed at the exchange rate on the acquisition date and never retranslated",
      "Translated at the average rate for each subsequent period",
      "Treated as an asset of the foreign operation and retranslated at the closing rate at each reporting date, with differences to other comprehensive income",
      "Translated at the parent's functional-currency rate because goodwill belongs to the parent",
    ],
    correct: 2,
    explanation:
      "IAS 21 treats goodwill on a foreign acquisition as an asset of the foreign operation, so it is expressed in the foreign functional currency and retranslated at the closing rate each period, with the resulting difference going to OCI (the translation reserve). Option 1 freezes goodwill at the historical rate, which IAS 21 prohibits. Option 2 uses the average rate rather than the closing rate. Option 4 wrongly treats goodwill as a parent-currency asset.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR3-C-32",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "There are indications that an investment in an associate accounted for using the equity method may be impaired. Under IAS 28 and IAS 36, the entity should:",
    options: [
      "Test only the goodwill notionally included in the investment for impairment separately",
      "Ignore impairment because the equity method already reflects the associate's results",
      "Recognise its share of the associate's own impairment losses only, with no test of the investment itself",
      "Test the entire carrying amount of the investment for impairment as a single asset, comparing it with its recoverable amount",
    ],
    correct: 3,
    explanation:
      "IAS 28 requires the whole equity-accounted investment (including any notional goodwill within it) to be tested as a single asset under IAS 36 when impairment indicators exist, comparing carrying amount with recoverable amount. Option 1 wrongly separates the goodwill for a standalone test. Option 2 assumes the equity method removes the need for an impairment test — it does not. Option 3 only picks up the associate's internal impairments and skips the required test of the investment itself.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-C-33",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "A subsidiary uses accounting policies that differ from the group's, and its reporting date is three months before the parent's. For consolidation, the group must:",
    options: [
      "Adjust the subsidiary's figures to uniform group accounting policies and use financial statements to the same reporting date (or adjust for significant transactions in the gap, subject to the 3-month limit)",
      "Consolidate the subsidiary's own figures unchanged, because policy choice is a subsidiary-level decision",
      "Exclude the subsidiary from consolidation until its reporting date is aligned",
      "Consolidate only the subsidiary's assets and liabilities, omitting its profit or loss",
    ],
    correct: 0,
    explanation:
      "IFRS 10 requires uniform accounting policies across the group and coterminous reporting dates; where dates differ by no more than three months, the subsidiary's statements are used with adjustments for significant intervening transactions. Option 2 keeps non-uniform policies, which is not allowed. Option 3 wrongly excludes a controlled entity. Option 4 has no basis — the whole of the subsidiary's results are consolidated.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR3-C-34",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "A parent acquires a subsidiary part-way through the year. In the consolidated statement of profit or loss, the subsidiary's results are:",
    options: [
      "Included for the whole year, with a deduction for pre-acquisition profits shown as a non-controlling interest",
      "Time-apportioned so that only the post-acquisition portion of the subsidiary's income and expenses is consolidated",
      "Excluded entirely in the year of acquisition and consolidated only from the next full year",
      "Included in full, because control existed at the reporting date",
    ],
    correct: 1,
    explanation:
      "Only results earned after control is obtained belong to the group, so the subsidiary's income and expenses are time-apportioned (assuming they accrue evenly) and consolidated from the acquisition date. Option 1 wrongly consolidates the whole year and mislabels pre-acquisition profit as NCI. Option 3 ignores the subsidiary until the next year, understating group results. Option 4 consolidates the full year regardless of when control began.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-C-35",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "A parent owns 80% of a subsidiary. The subsidiary issues new shares to third parties, and the parent does not take up any, so the parent's interest falls to 60% but it retains control. Under IFRS 10, this deemed disposal (dilution) is:",
    options: [
      "Recognised as a gain or loss on disposal in profit or loss based on the fall from 80% to 60%",
      "Treated as a loss of control, requiring the subsidiary to be deconsolidated",
      "Accounted for as an equity transaction, adjusting NCI and parent equity with any difference recognised directly in equity",
      "Ignored, because no shares were sold by the parent",
    ],
    correct: 2,
    explanation:
      "A dilution that leaves control intact is a change in ownership without loss of control, so IFRS 10 treats it as an equity transaction: the NCI is increased and parent equity adjusted, with any difference taken to equity rather than profit or loss. Option 1 wrongly books a P/L gain/loss. Option 2 assumes loss of control, which has not happened. Option 4 ignores the change, but the shift in the ownership split must still be reflected in equity.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR3-C-36",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "In the consolidated statement of financial position, the non-controlling interest is presented:",
    options: [
      "As a non-current liability, because it is owed to outside parties",
      "Within goodwill, because it arose on acquisition",
      "As a deduction from group retained earnings",
      "Within equity, separately from the equity attributable to the owners of the parent",
    ],
    correct: 3,
    explanation:
      "IFRS 10 requires the NCI to be presented within equity but separately from the equity attributable to the owners of the parent. Option 1 wrongly classifies it as a liability — the NCI is an ownership interest, not an obligation. Option 2 confuses it with goodwill. Option 3 nets it against retained earnings, whereas it must be shown as a distinct equity component.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR3-C-37",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "A parent sold an item of plant to its subsidiary during the year at a profit of $30,000. At the year end the asset has a remaining life of 5 years and the subsidiary has charged a full year's depreciation on the higher, intra-group cost. On consolidation the group should:",
    options: [
      "Eliminate the $30,000 unrealised profit but add back $6,000 of excess depreciation, giving a net reduction of $24,000 in group profit and carrying amount",
      "Eliminate only the $30,000 profit and leave depreciation unadjusted",
      "Leave the transfer unadjusted because the asset is now used by the subsidiary",
      "Add the $30,000 profit to goodwill and depreciate it over 5 years",
    ],
    correct: 0,
    explanation:
      "Intra-group transfers of non-current assets require the unrealised profit to be removed ($30,000) and the excess depreciation charged on that profit to be reversed: 30,000 ÷ 5 = $6,000. The net adjustment reduces group profit and the asset's carrying amount by $30,000 − $6,000 = $24,000. Option 2 forgets the excess-depreciation reversal, over-eliminating. Option 3 ignores the unrealised profit entirely. Option 4 wrongly capitalises the profit as goodwill.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR3-C-38",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "A parent sells part of its holding in a subsidiary so that it loses control but retains a 30% interest over which it has significant influence. Following the disposal, the retained interest is:",
    options: [
      "Continued to be consolidated line-by-line as before",
      "Accounted for as an associate under the equity method, using its fair value at the date control was lost as the deemed cost",
      "Measured at the parent's original cost of the shares retained",
      "Classified as a financial asset at fair value through other comprehensive income with no further income recognition",
    ],
    correct: 1,
    explanation:
      "When a subsidiary becomes an associate, the group stops consolidating and applies the equity method; the fair value of the retained interest at the date control is lost (used in computing the disposal gain) becomes the deemed cost of the associate. Option 1 keeps full consolidation despite the loss of control. Option 3 reverts to historical cost, ignoring the fair value remeasurement. Option 4 wrongly treats a 30% significant-influence interest as a passive FVOCI financial asset.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR3-C-39",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "At acquisition a subsidiary's land had a fair value $100,000 above its tax base, and the tax base is unaffected by the fair value adjustment. The tax rate is 25%. Under IAS 12, on consolidation the group recognises:",
    options: [
      "No deferred tax, because the fair value adjustment is only a consolidation entry",
      "A deferred tax asset of $25,000, reducing goodwill",
      "A deferred tax liability of $25,000 as part of the identifiable net assets, which increases goodwill",
      "A current tax charge of $25,000 in profit or loss in the year of acquisition",
    ],
    correct: 2,
    explanation:
      "A fair value uplift with no change to the tax base creates a taxable temporary difference; IAS 12 requires a deferred tax liability of 100,000 × 25% = $25,000 to be recognised among the acquired identifiable net assets. Because this reduces net assets acquired, it increases goodwill. Option 1 wrongly ignores deferred tax on fair value adjustments. Option 2 has the wrong sign (a liability, not an asset) and the wrong goodwill effect. Option 4 treats a deferred difference as current tax payable now.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR3-C-40",
    paper: "SBR",
    area: "C",
    type: "mcq",
    stem: "IFRS 12 Disclosure of Interests in Other Entities primarily requires an entity to disclose information that enables users to evaluate:",
    options: [
      "The fair value of every individual asset held by each subsidiary",
      "Only the names and countries of incorporation of its subsidiaries",
      "The nature of, and risks associated with, its interests in subsidiaries, joint arrangements, associates and unconsolidated structured entities, and the effects of those interests",
      "The tax base of each investment for deferred tax purposes",
    ],
    correct: 2,
    explanation:
      "IFRS 12 requires disclosures about the nature of, and risks associated with, interests in subsidiaries, joint arrangements, associates and unconsolidated structured entities, and the effects of those interests on the financial statements. Option 1 demands asset-by-asset fair values that IFRS 12 does not require. Option 2 covers only a fragment (basic identification). Option 4 relates to IAS 12 deferred tax, not the scope of IFRS 12.",
    marks: 2,
    difficulty: "medium",
  },

  /* ═══════════ AREA D — Financial instruments & employee benefits (30) ═══════════
     IFRS 9 classification (business model & SPPI), ECL 3-stage model,
     derecognition, hedge accounting, embedded derivatives · IAS 32 liability vs
     equity & compound instruments · IAS 19 DC vs DB, remeasurements, net interest,
     past service cost, asset ceiling. */

  {
    id: "SBR3-D-01",
    paper: "SBR",
    area: "D",
    type: "mcq",
    stem: "Under IFRS 9, the three classification categories for financial assets are:",
    options: [
      "Amortised cost; fair value through other comprehensive income; fair value through profit or loss",
      "Held to maturity; loans and receivables; available for sale",
      "Trading; hedging; held for collection",
      "Cost; fair value; net realisable value",
    ],
    correct: 0,
    explanation:
      "IFRS 9 classifies financial assets as amortised cost, fair value through OCI (FVOCI), or fair value through profit or loss (FVTPL). Option 2 lists the old IAS 39 categories, which IFRS 9 replaced. Option 3 mixes purposes and invented labels. Option 4 lists measurement bases that are not the IFRS 9 categories.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR3-D-02",
    paper: "SBR",
    area: "D",
    type: "mcq",
    stem: "Under IFRS 9, a debt instrument is measured at amortised cost only if which two conditions are both met?",
    options: [
      "The instrument is quoted in an active market and management intends to hold it to maturity",
      "The business model is to hold the asset to collect contractual cash flows, and those cash flows are solely payments of principal and interest on the principal (the SPPI test)",
      "The asset is expected to be sold within twelve months and its fair value can be measured reliably",
      "The instrument is an equity investment and management elects the OCI presentation",
    ],
    correct: 1,
    explanation:
      "Amortised cost requires both the 'hold to collect' business model and cash flows that are solely payments of principal and interest (the SPPI test). Option 1 uses the old held-to-maturity 'intention' criterion, not the business-model/SPPI framework. Option 3 describes an asset held for sale, pointing to fair value, not amortised cost. Option 4 concerns equity instruments, which fail SPPI and cannot be at amortised cost.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-D-03",
    paper: "SBR",
    area: "D",
    type: "number",
    stem: "Riverford Bank holds a loan asset with a gross carrying amount of $2,000,000 that is performing (stage 1). The 12-month probability of default is 2% and the loss given default is 40%. Under the IFRS 9 expected credit loss model, what is the 12-month expected credit loss allowance, in $?",
    numericAnswer: 16000,
    unit: "$",
    tolerance: 0,
    explanation:
      "For a stage 1 asset the allowance is the 12-month ECL = exposure × probability of default × loss given default = 2,000,000 × 2% × 40% = $16,000. Using lifetime PD (stage 2/3) or omitting the LGD would overstate the loss for a performing asset.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR3-D-04",
    paper: "SBR",
    area: "D",
    type: "mcq",
    stem: "In applying the SPPI test under IFRS 9, 'interest' consists principally of:",
    options: [
      "Any return the issuer is contractually able to pay, including returns linked to the issuer's profits",
      "The return demanded by equity investors for the risk they bear",
      "Consideration for the time value of money and for the credit risk associated with the principal outstanding during a particular period",
      "The coupon rate stated on the instrument, regardless of what it compensates for",
    ],
    correct: 2,
    explanation:
      "Under IFRS 9, interest is consideration for the time value of money and credit risk (and may include other basic lending risks and a profit margin) on the principal outstanding. Option 1 would fail SPPI because profit-linked returns are not basic lending returns. Option 2 describes an equity return, not interest. Option 4 confuses the label 'coupon' with the substance test IFRS 9 actually applies.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-D-05",
    paper: "SBR",
    area: "D",
    type: "mcq",
    stem: "For an investment in equity shares not held for trading, IFRS 9 permits an entity to make an irrevocable election at initial recognition to present changes in fair value in:",
    options: [
      "Profit or loss, with subsequent recycling to OCI on disposal",
      "Retained earnings directly, bypassing both profit or loss and OCI",
      "A revaluation surplus that is reclassified to profit or loss when the shares are sold",
      "Other comprehensive income, with no subsequent reclassification of those gains or losses to profit or loss",
    ],
    correct: 3,
    explanation:
      "IFRS 9 allows an irrevocable election, at initial recognition, to present fair value changes on such equity investments in OCI; those amounts are never reclassified to profit or loss, though the balance may be transferred within equity on disposal. Option 1 reverses the presentation and wrongly recycles. Option 2 bypasses OCI, which the election specifically uses. Option 3 wrongly recycles the OCI gains to profit or loss.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR3-D-06",
    paper: "SBR",
    area: "D",
    type: "mcq",
    stem: "Under IFRS 9, an entity reclassifies financial assets between measurement categories:",
    options: [
      "Whenever management changes its intention for an individual asset",
      "Only when the entity changes its business model for managing financial assets, applied prospectively from the reclassification date",
      "Freely at each reporting date to minimise volatility in profit or loss",
      "Never, because reclassification is prohibited by IFRS 9",
    ],
    correct: 1,
    explanation:
      "IFRS 9 permits reclassification of financial assets only when the entity changes its business model for managing them — an expected-to-be-infrequent event — and it is applied prospectively from the reclassification date. Option 1 uses individual intention, which does not trigger reclassification. Option 3 (free reclassification to manage earnings) is prohibited. Option 4 overstates the rule; reclassification is restricted, not banned.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR3-D-07",
    paper: "SBR",
    area: "D",
    type: "number",
    stem: "On 1 January 20X7 Selworthy Co purchased a bond for $940,000, including transaction costs. The bond has a face value of $1,000,000, pays annual interest of 4% ($40,000) on 31 December, and has an effective interest rate of 6%. The bond is held under a business model to collect contractual cash flows. What is its amortised cost carrying amount at 31 December 20X7, in $?",
    numericAnswer: 956400,
    unit: "$",
    tolerance: 0,
    explanation:
      "Amortised cost rolls forward at the effective rate: opening 940,000 + interest income (940,000 × 6% = 56,400) − cash received (40,000) = 940,000 + 56,400 − 40,000 = $956,400. Using the 4% coupon rather than the 6% effective rate for interest income would understate the carrying amount.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-D-08",
    paper: "SBR",
    area: "D",
    type: "mcq",
    stem: "A derivative that is not designated in a hedging relationship is measured under IFRS 9 at:",
    options: [
      "Amortised cost, because it has contractual cash flows",
      "Cost less impairment",
      "Fair value through profit or loss",
      "Fair value through other comprehensive income",
    ],
    correct: 2,
    explanation:
      "Free-standing derivatives fail the SPPI test and are held for trading by default, so IFRS 9 measures them at fair value through profit or loss unless designated in a qualifying hedge. Option 1 (amortised cost) is unavailable because derivatives do not have SPPI cash flows. Option 2 (cost less impairment) is not an IFRS 9 category for derivatives. Option 4 (FVOCI) requires either the debt FVOCI conditions or the equity election, neither of which applies to a stand-alone derivative.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-D-09",
    paper: "SBR",
    area: "D",
    type: "mcq",
    stem: "Under the IFRS 9 expected credit loss model, a financial asset that has NOT suffered a significant increase in credit risk since initial recognition (stage 1) carries a loss allowance measured at:",
    options: [
      "Lifetime expected credit losses, with interest on the net carrying amount",
      "Nil, because no default has yet occurred",
      "12-month expected credit losses, with interest calculated on the gross carrying amount",
      "The full contractual amount receivable",
    ],
    correct: 2,
    explanation:
      "Stage 1 assets carry a 12-month ECL allowance and interest revenue is calculated on the gross carrying amount. Option 1 describes stage 2/3 (lifetime ECL; net-basis interest applies only in stage 3). Option 2 wrongly waits for an actual default — ECL is forward-looking. Option 4 confuses the loss allowance with the gross receivable itself.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-D-10",
    paper: "SBR",
    area: "D",
    type: "mcq",
    stem: "When a financial asset suffers a significant increase in credit risk since initial recognition but is not yet credit-impaired, IFRS 9 requires the entity to:",
    options: [
      "Continue measuring the allowance at 12-month expected credit losses",
      "Derecognise the asset immediately",
      "Suspend all interest income until the asset recovers",
      "Move the asset to stage 2 and measure the loss allowance at lifetime expected credit losses, while still recognising interest on the gross carrying amount",
    ],
    correct: 3,
    explanation:
      "On a significant increase in credit risk the asset moves to stage 2: the allowance steps up to lifetime ECL, but because the asset is not yet credit-impaired, interest is still recognised on the gross carrying amount. Option 1 leaves it at the stage 1 measure. Option 2 wrongly derecognises a still-performing asset. Option 3 suspends interest, which only changes (to a net basis) in stage 3, and interest is not suspended.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-D-11",
    paper: "SBR",
    area: "D",
    type: "number",
    stem: "On 1 January 20X6 Tavistock Co issued convertible bonds with a total face value and proceeds of $5,000,000. The bonds carry a 5% annual coupon (paid each 31 December), are redeemable at par after three years, and are convertible into shares at the holders' option. The market rate for similar non-convertible debt is 8%. The relevant 8% discount factors are 0.926 (year 1), 0.857 (year 2) and 0.794 (year 3). Under IAS 32, what is the equity component recognised on issue, to the nearest $?",
    numericAnswer: 385750,
    unit: "$",
    tolerance: 100,
    explanation:
      "IAS 32 measures the liability component as the present value of the cash flows discounted at the market rate for equivalent non-convertible debt, then treats the equity component as the residual. Coupons = 5% × 5,000,000 = 250,000 per year; PV of coupons = 250,000 × (0.926 + 0.857 + 0.794) = 250,000 × 2.577 = 644,250; PV of redemption = 5,000,000 × 0.794 = 3,970,000; liability = 644,250 + 3,970,000 = 4,614,250. Equity component = 5,000,000 − 4,614,250 = $385,750.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR3-D-12",
    paper: "SBR",
    area: "D",
    type: "mcq",
    stem: "Under IAS 32, an issuer classifies a preference share as a financial liability rather than equity when:",
    options: [
      "The shares are called 'preference' shares in the legal documentation",
      "The issuer has a contractual obligation to deliver cash, for example a mandatory redemption at a fixed date or mandatory fixed dividends",
      "The shares carry no voting rights",
      "The dividend rate is fixed rather than variable",
    ],
    correct: 1,
    explanation:
      "IAS 32 classifies an instrument as a liability where there is a contractual obligation to deliver cash or another financial asset (e.g. mandatory redemption or mandatory dividends); substance, not legal form, governs. Option 1 relies on the legal name, which is irrelevant. Option 3 (no voting rights) does not determine liability/equity classification. Option 4 (a fixed dividend rate) alone is not decisive — what matters is whether payment is obligatory.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-D-13",
    paper: "SBR",
    area: "D",
    type: "mcq",
    stem: "A compound financial instrument, such as a convertible bond, is accounted for by the issuer under IAS 32 by:",
    options: [
      "Splitting it into a liability component and an equity component, presented separately",
      "Classifying the entire instrument as a liability until conversion",
      "Classifying the entire instrument as equity because conversion into shares is possible",
      "Measuring the whole instrument at fair value through profit or loss",
    ],
    correct: 0,
    explanation:
      "IAS 32 requires the issuer to split a compound instrument into its liability and equity components at issue and present them separately. Option 2 ignores the equity conversion option embedded in the instrument. Option 3 wrongly classifies an obligation to pay coupons/principal as equity. Option 4 applies whole-instrument fair value measurement that IAS 32's split-accounting model does not use.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR3-D-14",
    paper: "SBR",
    area: "D",
    type: "mcq",
    stem: "An entity assessing whether to derecognise a financial asset under IFRS 9 has transferred the asset but retained substantially all its risks and rewards. IFRS 9 requires the entity to:",
    options: [
      "Derecognise the asset in full because legal title has passed",
      "Derecognise the asset and recognise a gain or loss for the difference",
      "Apply the continuing-involvement approach in all cases regardless of control",
      "Continue to recognise the asset in full and treat any proceeds received as a liability",
    ],
    correct: 3,
    explanation:
      "IFRS 9 derecognition first tests the transfer of risks and rewards: if the entity retains substantially all risks and rewards, the asset is NOT derecognised and any proceeds are recognised as a financial liability. Option 1 relies on legal title, which is not the IFRS 9 test. Option 2 derecognises despite retained risks and rewards. Option 3 jumps to continuing involvement, which applies only when risks and rewards are neither transferred nor retained and control is retained.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR3-D-15",
    paper: "SBR",
    area: "D",
    type: "number",
    stem: "At 1 January 20X8 Ullswater Co's defined benefit plan showed a net defined benefit liability of $600,000. The discount rate determined by reference to high quality corporate bonds is 5% per annum. Under IAS 19, what is the net interest on the net defined benefit liability charged to profit or loss for the year, in $?",
    numericAnswer: 30000,
    unit: "$",
    tolerance: 0,
    explanation:
      "IAS 19 net interest = discount rate × opening net defined benefit liability (asset) = 5% × 600,000 = $30,000, recognised in profit or loss. The single net-interest figure replaces the separate 'interest cost' and 'expected return on assets' of the old standard.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR3-D-16",
    paper: "SBR",
    area: "D",
    type: "mcq",
    stem: "A host contract is a financial liability measured at amortised cost, and it contains an embedded derivative. Under IFRS 9, the embedded derivative is separated and accounted for as a stand-alone derivative when:",
    options: [
      "The host contract is denominated in a foreign currency",
      "The embedded feature increases the interest rate payable",
      "The entity wishes to reduce volatility in profit or loss",
      "Its economic characteristics and risks are not closely related to those of the host, it meets the definition of a derivative, and the whole contract is not measured at fair value through profit or loss",
    ],
    correct: 3,
    explanation:
      "For a non-financial-asset host, IFRS 9 separates an embedded derivative when it is not closely related to the host, meets the derivative definition, and the combined contract is not already at FVTPL. Option 1 (foreign currency) is not, by itself, the separation test. Option 2 describes a feature that is often closely related to a debt host and so not separated. Option 3 states a motive, not the technical criteria. (Note: embedded derivatives in financial-asset hosts are not separated — the whole asset is classified using the business-model/SPPI tests.)",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR3-D-17",
    paper: "SBR",
    area: "D",
    type: "mcq",
    stem: "In a fair value hedge that qualifies for hedge accounting under IFRS 9, the gain or loss on the hedging instrument and the hedging gain or loss on the hedged item are:",
    options: [
      "Both recognised in profit or loss, so that they offset",
      "Both deferred in other comprehensive income until the hedged item affects profit or loss",
      "Recognised in profit or loss for the instrument but in OCI for the hedged item",
      "Recognised in OCI for the instrument but in profit or loss for the hedged item",
    ],
    correct: 0,
    explanation:
      "In a fair value hedge, both the change in fair value of the hedging instrument and the hedging adjustment to the hedged item go to profit or loss, so the offsetting effect is visible there. Option 2 describes a cash flow hedge, not a fair value hedge. Options 3 and 4 split the two amounts across profit or loss and OCI, which would destroy the intended matching.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-D-18",
    paper: "SBR",
    area: "D",
    type: "mcq",
    stem: "In a cash flow hedge that qualifies for hedge accounting under IFRS 9, the effective portion of the gain or loss on the hedging instrument is:",
    options: [
      "Recognised immediately in profit or loss",
      "Recognised in other comprehensive income and accumulated in a cash flow hedge reserve, later reclassified to profit or loss when the hedged cash flows affect profit or loss",
      "Adjusted against the carrying amount of the hedged forecast transaction in all cases",
      "Ignored until the hedge is discontinued",
    ],
    correct: 1,
    explanation:
      "In a cash flow hedge the effective portion is recognised in OCI (a cash flow hedge reserve) and reclassified to profit or loss when the hedged transaction affects profit or loss (or, for a hedge of a forecast asset/liability, may adjust the initial carrying amount). Option 1 recognises the effective portion immediately in P/L, which is the fair value hedge treatment. Option 3 overstates the basis-adjustment rule (it is not applied in all cases). Option 4 ignores the effective portion entirely.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-D-19",
    paper: "SBR",
    area: "D",
    type: "number",
    stem: "For its defined benefit plan, Wensleydale Co reports the following for the year: current service cost $300,000; past service cost from a plan amendment $50,000; net interest on the net defined benefit liability $30,000; and a net remeasurement loss of $40,000. Under IAS 19, what total amount is charged to PROFIT OR LOSS for the year, in $?",
    numericAnswer: 380000,
    unit: "$",
    tolerance: 0,
    explanation:
      "IAS 19 recognises service cost (current + past) and net interest in profit or loss, while remeasurements go to other comprehensive income. P/L charge = 300,000 + 50,000 + 30,000 = $380,000. The $40,000 remeasurement loss is excluded because it is presented in OCI and is not reclassified to profit or loss.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-D-20",
    paper: "SBR",
    area: "D",
    type: "mcq",
    stem: "The key distinction between a defined contribution plan and a defined benefit plan under IAS 19 is that:",
    options: [
      "In a defined contribution plan the employer's obligation is limited to its agreed contributions, whereas in a defined benefit plan the employer bears the actuarial and investment risk of providing the promised benefits",
      "A defined contribution plan is funded, whereas a defined benefit plan is always unfunded",
      "A defined benefit plan is used only by listed entities",
      "A defined contribution plan requires an actuarial valuation each year, whereas a defined benefit plan does not",
    ],
    correct: 0,
    explanation:
      "In a defined contribution plan the employer's obligation is fixed at the agreed contributions and the employee bears the investment risk; in a defined benefit plan the employer promises a benefit and therefore bears the actuarial and investment risk. Option 2 wrongly ties the distinction to funding status. Option 3 invents an entity-type restriction. Option 4 reverses reality — it is the defined benefit plan that needs actuarial valuation.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR3-D-21",
    paper: "SBR",
    area: "D",
    type: "mcq",
    stem: "Under IAS 19, remeasurements of the net defined benefit liability (asset) — such as actuarial gains and losses and the return on plan assets excluding amounts in net interest — are:",
    options: [
      "Recognised in profit or loss as they arise",
      "Recognised in other comprehensive income and reclassified to profit or loss when the benefits are paid",
      "Recognised in other comprehensive income and not subsequently reclassified to profit or loss",
      "Spread over the remaining working lives of employees using the corridor approach",
    ],
    correct: 2,
    explanation:
      "IAS 19 requires remeasurements to be recognised in OCI and NOT reclassified to profit or loss (though the balance may be transferred within equity). Option 1 wrongly routes them through profit or loss. Option 2 correctly uses OCI but wrongly adds a prohibited recycling step. Option 4 revives the corridor/spreading approach, which the current IAS 19 abolished.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-D-22",
    paper: "SBR",
    area: "D",
    type: "mcq",
    stem: "Under IAS 19, net interest on the net defined benefit liability (asset) is determined by:",
    options: [
      "Applying the expected long-term rate of return on plan assets to the plan assets, and a separate discount rate to the obligation",
      "Applying the entity's incremental borrowing rate to the obligation only",
      "Applying an actuary's assumed salary growth rate to the net liability",
      "Applying the discount rate used to measure the obligation to the net defined benefit liability (asset), both determined at the start of the period",
    ],
    correct: 3,
    explanation:
      "IAS 19 computes net interest by applying the discount rate (the high-quality corporate bond rate used for the obligation) to the net defined benefit liability or asset, both measured at the start of the annual period. Option 1 uses a separate expected return on assets, which the current standard removed in favour of a single net-interest approach. Option 2 uses an incremental borrowing rate on the obligation only. Option 3 wrongly uses a salary-growth assumption as the interest rate.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR3-D-23",
    paper: "SBR",
    area: "D",
    type: "number",
    stem: "For Ambleside Co's defined benefit obligation for the year: opening present value $2,400,000; current service cost $300,000; interest cost $120,000; benefits paid $150,000; and the actuary's closing present value of the obligation is $2,760,000. Under IAS 19, what is the actuarial remeasurement loss on the obligation for the year, in $ (enter a positive number for a loss)?",
    numericAnswer: 90000,
    unit: "$",
    tolerance: 0,
    explanation:
      "The remeasurement (actuarial) gain or loss is the balancing figure on the obligation. Expected closing obligation = 2,400,000 + 300,000 (service) + 120,000 (interest) − 150,000 (benefits) = 2,670,000. Actual closing = 2,760,000, so the obligation is $2,760,000 − $2,670,000 = $90,000 higher than expected: an actuarial LOSS of $90,000, recognised in OCI.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR3-D-24",
    paper: "SBR",
    area: "D",
    type: "mcq",
    stem: "An entity improves the benefits under its defined benefit plan, creating past service cost. Under IAS 19, this past service cost is:",
    options: [
      "Recognised as an expense in profit or loss at the earlier of when the plan amendment occurs and when related restructuring costs are recognised — i.e. immediately, not spread",
      "Spread over the employees' remaining vesting period on a straight-line basis",
      "Recognised in other comprehensive income as a remeasurement",
      "Deferred and recognised only when the improved benefits are actually paid",
    ],
    correct: 0,
    explanation:
      "IAS 19 requires past service cost to be recognised immediately in profit or loss at the earlier of the plan amendment/curtailment date and the date related restructuring costs are recognised — it is not spread over a vesting period. Option 2 revives the old spreading approach. Option 3 wrongly classifies it as a remeasurement (OCI) item; it is part of service cost in P/L. Option 4 defers it to the payment date, which the standard does not permit.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-D-25",
    paper: "SBR",
    area: "D",
    type: "mcq",
    stem: "A defined benefit plan is in surplus (assets exceed the obligation). Under IAS 19, the asset ceiling requires the net defined benefit asset to be measured as the lower of the surplus and:",
    options: [
      "The total contributions the employer has paid into the plan to date",
      "The present value of any economic benefits available in the form of refunds from the plan or reductions in future contributions (the asset ceiling)",
      "Zero, because a pension surplus can never be recognised as an asset",
      "The fair value of the plan assets at the reporting date",
    ],
    correct: 1,
    explanation:
      "IAS 19 caps the net defined benefit asset at the present value of economic benefits available as refunds or reductions in future contributions — the asset ceiling — to avoid recognising a surplus the entity cannot access. Option 1 uses cumulative contributions, which is irrelevant to recoverability. Option 3 wrongly bans recognition of any surplus. Option 4 uses the plan assets' fair value alone, ignoring the obligation and the recoverability test.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR3-D-26",
    paper: "SBR",
    area: "D",
    type: "mcq",
    stem: "Under IAS 19, an employer's accounting for a defined contribution plan for a period is to:",
    options: [
      "Recognise an actuarially determined obligation for the promised future benefits",
      "Recognise a net interest charge on the plan assets and obligation",
      "Recognise remeasurement gains and losses in other comprehensive income",
      "Recognise the contributions payable in exchange for service in the period as an expense (and as a liability to the extent unpaid, or an asset if prepaid)",
    ],
    correct: 3,
    explanation:
      "For a defined contribution plan the employer simply recognises the contributions payable for the period's service as an expense, with a liability for any unpaid amount or an asset for any prepayment. Options 1, 2 and 3 all describe defined benefit accounting (an actuarial obligation, net interest, and remeasurements in OCI), none of which applies to a defined contribution plan where the employer's obligation is limited to its contributions.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR3-D-27",
    paper: "SBR",
    area: "D",
    type: "number",
    stem: "For Buttermere Co's defined benefit plan assets for the year: opening fair value $2,000,000; interest income at the discount rate $100,000; contributions paid in $200,000; benefits paid out $150,000; and the closing fair value of plan assets per the trustees is $2,230,000. Under IAS 19, what is the remeasurement gain on plan assets (the return excluding amounts already in net interest) for the year, in $ (enter a positive number for a gain)?",
    numericAnswer: 80000,
    unit: "$",
    tolerance: 0,
    explanation:
      "The remeasurement on plan assets is the balancing figure. Expected closing assets = 2,000,000 + 100,000 (interest income) + 200,000 (contributions) − 150,000 (benefits) = 2,150,000. Actual closing = 2,230,000, so the assets returned $2,230,000 − $2,150,000 = $80,000 more than the interest income already recognised: a remeasurement GAIN of $80,000, recognised in OCI.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR3-D-28",
    paper: "SBR",
    area: "D",
    type: "mcq",
    stem: "A curtailment of a defined benefit plan (for example, a significant reduction in the number of employees covered) is accounted for under IAS 19 as:",
    options: [
      "A remeasurement recognised in other comprehensive income",
      "Past service cost recognised in profit or loss when the curtailment occurs",
      "A prior-period adjustment restating the opening obligation",
      "A change in accounting estimate spread over future service periods",
    ],
    correct: 1,
    explanation:
      "IAS 19 treats the effect of a curtailment as past service cost, recognised in profit or loss at the date the curtailment occurs (alongside any related settlement gain or loss). Option 1 wrongly classifies it as an OCI remeasurement. Option 3 treats it as a prior-period error, which it is not. Option 4 spreads it over future periods, contrary to the immediate-recognition rule for past service cost and curtailments.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-D-29",
    paper: "SBR",
    area: "D",
    type: "mcq",
    stem: "An entity designates a foreign-currency borrowing as a hedge of its net investment in a foreign operation. Under IFRS 9, the effective portion of the exchange gain or loss on the borrowing is:",
    options: [
      "Recognised in other comprehensive income and accumulated in the foreign currency translation reserve, and reclassified to profit or loss on disposal of the foreign operation",
      "Recognised immediately in profit or loss to offset the translation of the net investment",
      "Deducted from the carrying amount of the goodwill of the foreign operation",
      "Deferred indefinitely in equity and never reclassified",
    ],
    correct: 0,
    explanation:
      "A net investment hedge is accounted for like a cash flow hedge: the effective portion goes to OCI (the translation reserve) and is reclassified to profit or loss when the foreign operation is disposed of, offsetting the recycled translation differences. Option 1 recognises it immediately in P/L, which would not match the OCI translation of the net investment. Option 3 adjusts goodwill, which is not the mechanism. Option 4 wrongly denies the reclassification that occurs on disposal.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR3-D-30",
    paper: "SBR",
    area: "D",
    type: "mcq",
    stem: "Coniston Co sells its trade receivables to a factor but guarantees to reimburse the factor for any irrecoverable balances (a with-recourse arrangement). Under IFRS 9, Coniston should:",
    options: [
      "Derecognise the receivables in full and recognise a gain on sale, because legal title has transferred",
      "Recognise the cash received as revenue in profit or loss",
      "Continue to recognise the receivables and treat the cash received from the factor as a liability, because it has retained substantially all the credit risk",
      "Reclassify the receivables as an investment measured at fair value through profit or loss",
    ],
    correct: 2,
    explanation:
      "Because Coniston retains substantially all the risks and rewards (it bears the credit risk through the recourse guarantee), IFRS 9 does not permit derecognition; the receivables stay on the balance sheet and the cash received is recognised as a liability. Option 1 derecognises based on legal title, ignoring the retained credit risk. Option 2 wrongly treats financing proceeds as revenue. Option 4 invents a reclassification with no basis in the derecognition rules.",
    marks: 2,
    difficulty: "medium",
  },

  /* ═══════════ AREA E — Interpretation & current issues (15) ═══════════
     analysis for a user, ratios in a group context, effect of accounting choices
     on ratios, IFRS 8 segments, IAS 24 related parties, sustainability (IFRS S1/S2),
     management commentary, IASB agenda, earnings management / quality of earnings. */

  {
    id: "SBR3-E-01",
    paper: "SBR",
    area: "E",
    type: "mcq",
    stem: "When interpreting financial statements for a particular user, the most important starting point is to:",
    options: [
      "Identify the specific user and their information needs, because different users (e.g. a lender versus a potential acquirer) focus on different aspects of performance and position",
      "Calculate every possible ratio so that nothing is missed",
      "Compare the entity only against the prior year, ignoring competitors",
      "Rely solely on the profit figure, since it summarises performance",
    ],
    correct: 0,
    explanation:
      "Effective analysis is user-driven: a lender emphasises liquidity, gearing and cash cover, whereas a potential acquirer focuses on sustainable earnings and synergies, so the analysis is tailored to the user's decision. Option 2 produces undirected ratio-sheets without insight. Option 3 ignores essential benchmarking against comparators and the wider sector. Option 4 over-relies on a single, easily distorted number and ignores position, cash flows and risk.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR3-E-02",
    paper: "SBR",
    area: "E",
    type: "mcq",
    stem: "When calculating profitability ratios such as operating margin from consolidated financial statements that include a subsidiary acquired part-way through the year, the analyst should remember that:",
    options: [
      "The subsidiary's full-year results are included, so ratios are directly comparable with the prior year",
      "Consolidated revenue and profit include the subsidiary only from the acquisition date, so year-on-year comparisons can be distorted and trends must be interpreted with care",
      "The subsidiary is excluded from the consolidated income statement in the year of acquisition",
      "Non-controlling interests should be added back to revenue before computing the margin",
    ],
    correct: 1,
    explanation:
      "Only post-acquisition results are consolidated, so consolidated revenue and profit jump partway through the year; comparisons with a prior year that excluded the subsidiary can mislead unless this is recognised. Option 1 wrongly assumes a full year is included. Option 3 wrongly excludes the subsidiary entirely from the year of acquisition. Option 4 confuses the equity split (NCI) with revenue — NCI does not change consolidated revenue.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-E-03",
    paper: "SBR",
    area: "E",
    type: "mcq",
    stem: "An entity switches from the cost model to the revaluation model for its properties, increasing their carrying amount. Other things equal, the immediate effect on return on capital employed (ROCE) and the gearing ratio (debt/equity) is:",
    options: [
      "ROCE rises and gearing rises",
      "ROCE and gearing are both unaffected because revaluation is a non-cash adjustment",
      "ROCE rises and gearing is unchanged",
      "ROCE falls (larger capital employed) and gearing falls (larger equity via the revaluation surplus)",
    ],
    correct: 3,
    explanation:
      "The revaluation surplus increases equity, so capital employed rises — lowering ROCE, all else equal — and equity rises, lowering the debt/equity gearing ratio. So both ROCE and gearing fall. Option 1 has both directions wrong. Option 2 wrongly claims no effect, ignoring that recognised carrying amounts and equity both change. Option 3 wrongly leaves gearing unchanged, overlooking the boost to equity from the revaluation surplus.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-E-04",
    paper: "SBR",
    area: "E",
    type: "mcq",
    stem: "Under IFRS 8 Operating Segments, the segment information disclosed is based on:",
    options: [
      "The management approach — the components regularly reviewed by the chief operating decision maker to allocate resources and assess performance",
      "Statutory business classes prescribed by the standard",
      "Geographical regions only",
      "The legal-entity structure of the group",
    ],
    correct: 0,
    explanation:
      "IFRS 8 uses the management approach: operating segments are the components whose results are regularly reviewed by the chief operating decision maker to allocate resources and assess performance, reported on the same basis as internal reporting. Option 2 imposes prescribed classes that IFRS 8 deliberately avoids. Option 3 restricts segments to geography, whereas segments may be by product, service or region. Option 4 uses the legal structure, which need not match how the business is managed.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR3-E-05",
    paper: "SBR",
    area: "E",
    type: "mcq",
    stem: "An entity historically kept significant assets and the related finance off its statement of financial position. If those arrangements were instead recognised on the balance sheet, the most likely effect on the analyst's assessment would be:",
    options: [
      "Lower gearing and higher interest cover, making the entity look less risky",
      "No effect on any ratio, because off-balance-sheet items are always disclosed in the notes",
      "Higher return on assets, because assets are unchanged while profit rises",
      "Higher gearing and lower return on assets, revealing risk and asset intensity that the off-balance-sheet treatment had concealed",
    ],
    correct: 3,
    explanation:
      "Bringing previously off-balance-sheet assets and finance on-balance-sheet raises reported debt (higher gearing) and increases the asset base (lower return on assets), exposing risk and capital intensity that were hidden. Option 1 has the gearing direction backwards. Option 2 wrongly claims note disclosure removes all ratio effects — recognition changes the primary statements and the ratios drawn from them. Option 3 ignores the increase in recognised assets that depresses return on assets.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR3-E-06",
    paper: "SBR",
    area: "E",
    type: "mcq",
    stem: "Under IAS 24 Related Party Disclosures, which of the following is a related party of a reporting entity?",
    options: [
      "A supplier that provides a large proportion of the entity's purchases but has no other connection",
      "A customer that accounts for a major share of the entity's revenue",
      "A bank that has lent money to the entity on normal commercial terms",
      "A member of the entity's key management personnel, and close members of that person's family",
    ],
    correct: 3,
    explanation:
      "IAS 24 identifies key management personnel (those with authority and responsibility for planning, directing and controlling the entity) and close members of their families as related parties. Options 1, 2 and 3 describe ordinary trading or financing counterparties — a major supplier, a major customer, or a lender on normal terms — which economic dependence alone does not make related parties under IAS 24.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-E-07",
    paper: "SBR",
    area: "E",
    type: "mcq",
    stem: "IAS 24 requires that relationships between a parent and its subsidiaries be disclosed:",
    options: [
      "Only when there have been transactions between them during the period",
      "Only if the amounts involved exceed a quantitative materiality threshold set in the standard",
      "Irrespective of whether there have been transactions between those related parties",
      "Only in the parent's separate financial statements, never in the consolidated statements",
    ],
    correct: 2,
    explanation:
      "IAS 24 requires disclosure of parent–subsidiary relationships regardless of whether transactions have taken place between them, because the control relationship itself is information users need. Option 1 wrongly conditions disclosure on transactions occurring. Option 2 invents a quantitative threshold that IAS 24 does not set for the relationship disclosure. Option 4 wrongly confines the disclosure to the separate statements.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR3-E-08",
    paper: "SBR",
    area: "E",
    type: "mcq",
    stem: "Which of the following is the strongest warning sign, to an analyst assessing the quality of earnings, that reported profit may be of low quality?",
    options: [
      "Operating cash flows growing broadly in line with reported operating profit over several years",
      "A steady, conservative revenue recognition policy applied consistently",
      "Profit growth driven mainly by one-off gains and by cash flows persistently lagging well behind reported profit",
      "Segment results that reconcile clearly to the consolidated totals",
    ],
    correct: 2,
    explanation:
      "Low-quality earnings are signalled where reported profit is inflated by non-recurring gains and where operating cash flows persistently fall short of reported profit, suggesting aggressive accruals or revenue recognition. Options 1 and 4 (cash flow tracking profit; segment results reconciling cleanly) are signs of higher, not lower, quality. Option 2 (a consistent, conservative revenue policy) also supports earnings quality rather than undermining it.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR3-E-09",
    paper: "SBR",
    area: "E",
    type: "mcq",
    stem: "The IFRS Sustainability Disclosure Standards issued by the International Sustainability Standards Board are, in outline:",
    options: [
      "IFRS S1, a single standard covering only climate-related disclosures",
      "IFRS S1 setting out general requirements for disclosure of sustainability-related financial information, and IFRS S2 addressing climate-related disclosures specifically",
      "A replacement for IFRS Accounting Standards in the primary financial statements",
      "Guidance that applies only to entities in the energy and mining sectors",
    ],
    correct: 1,
    explanation:
      "IFRS S1 sets general requirements for disclosing sustainability-related financial information that could affect an entity's prospects, and IFRS S2 provides the specific climate-related disclosure requirements. Option 1 wrongly describes S1 as climate-only. Option 3 misstates their status — they complement, not replace, IFRS Accounting Standards. Option 4 wrongly limits them to particular sectors; they are general-purpose sustainability standards.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-E-10",
    paper: "SBR",
    area: "E",
    type: "mcq",
    stem: "The IFRS Practice Statement on Management Commentary is best described as:",
    options: [
      "Non-mandatory guidance providing a framework for a narrative report that gives context to the financial statements, covering matters such as strategy, resources, risks and future prospects",
      "A mandatory IFRS Accounting Standard that must be complied with for the financial statements to be IFRS-compliant",
      "A standard prescribing the exact format and line items of the statement of profit or loss",
      "A requirement to disclose forecast financial statements audited to the same standard as historical statements",
    ],
    correct: 0,
    explanation:
      "The Management Commentary Practice Statement is non-mandatory guidance offering a framework for narrative reporting — strategy, resources, principal risks, performance and prospects — to give context to the financial statements. Option 2 wrongly makes it a mandatory standard. Option 3 confuses it with presentation standards for the primary statements. Option 4 wrongly implies audited forecasts; management commentary is narrative context, not audited prospective financial statements.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBR3-E-11",
    paper: "SBR",
    area: "E",
    type: "mcq",
    stem: "An analyst compares two groups: one consolidates a 55%-owned entity as a subsidiary, the other equity accounts a 45%-owned entity as an associate. Compared with equity accounting, full consolidation of a similar entity will tend to:",
    options: [
      "Reduce reported revenue and total assets because only the net investment is shown",
      "Have no effect on any ratio because group profit attributable to the parent is the same under both methods",
      "Show a single net line for both revenue and assets, improving comparability",
      "Increase reported revenue, assets and liabilities (grossing up the statements), so ratios such as asset turnover and gearing differ even where the underlying economics are similar",
    ],
    correct: 3,
    explanation:
      "Full consolidation grosses up revenue, assets and liabilities (with an NCI in equity), whereas the equity method shows only a single net investment and a share of profit; so gearing, asset turnover and margins are not directly comparable across the two presentations even for similar underlying interests. Option 1 describes the equity method's effect, not consolidation's. Option 2 wrongly claims ratios are unaffected — the gross-up changes many of them. Option 3 describes the equity method (single net lines), the opposite of full consolidation.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR3-E-12",
    paper: "SBR",
    area: "E",
    type: "mcq",
    stem: "Which of the following best reflects a current issue on the IASB's agenda relevant to SBR?",
    options: [
      "Reintroducing the last-in-first-out (LIFO) method for inventories under IAS 2",
      "Requiring all entities to prepare accounts on a break-up basis",
      "Improving the connectivity between financial statements and sustainability-related financial disclosures, and enhancing the structure and content of the primary financial statements",
      "Abolishing the requirement for a statement of cash flows",
    ],
    correct: 2,
    explanation:
      "Current developments include improving connectivity between financial reporting and sustainability disclosures and enhancing the presentation and structure of the primary financial statements. Option 1 is contrary to IAS 2, which prohibits LIFO. Option 2 misstates the going-concern basis, which remains the default. Option 4 is implausible — the cash flow statement remains a required primary statement, not a candidate for abolition.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-E-13",
    paper: "SBR",
    area: "E",
    type: "mcq",
    stem: "Under IFRS 8, an operating segment is generally a REPORTABLE segment (requiring separate disclosure) if it meets any of the quantitative thresholds, namely that its:",
    options: [
      "Revenue is at least 5% of the combined revenue of all operating segments",
      "Reported revenue, absolute profit or loss, or assets is 10% or more of the respective combined total for all operating segments",
      "Revenue exceeds that of every other segment, so that only the largest segment is reportable",
      "Assets exceed 25% of total group assets",
    ],
    correct: 1,
    explanation:
      "IFRS 8 sets 10% thresholds: a segment is reportable if its revenue, the absolute amount of its reported profit or loss, or its assets is 10% or more of the relevant combined total, and reportable segments must together cover at least 75% of external revenue. Option 1 uses 5%, the wrong percentage. Option 3 wrongly reduces reporting to only the single largest segment. Option 4 uses a 25% assets test that IFRS 8 does not apply.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBR3-E-14",
    paper: "SBR",
    area: "E",
    type: "mcq",
    stem: "An entity brings forward the recognition of revenue on long-term contracts and books it earlier and more aggressively than in prior years. From a quality-of-earnings perspective, an analyst should be most concerned that:",
    options: [
      "The change makes the statement of financial position more conservative",
      "Reported profit may be boosted now while receivables and contract assets rise and operating cash conversion weakens, so current earnings may not be sustainable or backed by cash",
      "The change has no effect on ratios because revenue recognition is only a timing matter",
      "The change will reduce reported profit and therefore understate performance",
    ],
    correct: 1,
    explanation:
      "Aggressive, earlier revenue recognition can inflate current profit while contract assets and receivables build up and cash conversion deteriorates, signalling earnings that may not be sustainable or cash-backed — a classic quality-of-earnings red flag. Option 1 wrongly frames aggressive recognition as conservative. Option 3 dismisses timing effects, but the shift changes profit, receivables and cash-based ratios in the period. Option 4 has the direction wrong — aggressive recognition boosts, not reduces, current profit.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBR3-E-15",
    paper: "SBR",
    area: "E",
    type: "mcq",
    stem: "Two comparable entities incur similar development expenditure. Entity A capitalises development costs meeting the IAS 38 criteria; Entity B expenses all such costs (arguing the criteria are not met). Compared with Entity B, Entity A will tend to report:",
    options: [
      "Lower assets and lower profit in the year of the expenditure, because capitalised costs are written off immediately",
      "Identical ratios, because IAS 38 removes all choice in this area",
      "Lower gearing only, with no effect on profit or asset ratios",
      "Higher assets and higher profit in the year of the expenditure, but lower profits in later years as the capitalised costs are amortised — so ROCE and margins are not directly comparable between the two",
    ],
    correct: 3,
    explanation:
      "Capitalising development costs raises assets and defers the expense, so Entity A shows higher assets and higher current profit than Entity B, but bears amortisation in later years; consequently ROCE, margins and asset turnover are not directly comparable across the two. Option 1 has the direction backwards (capitalising defers, not accelerates, the charge). Option 2 wrongly claims no choice — meeting the criteria and judgement about them create divergence. Option 3 ignores the profit and asset effects, limiting the impact wrongly to gearing.",
    marks: 2,
    difficulty: "hard",
  },
]
