import type { StudyChapter } from "@/lib/acca-study-content"

/*
 * MA · Area D — Standard costing & variances.
 * Original, syllabus-aligned rich chapter. One reconciling scenario (Product
 * Zeta) runs through every worked variance and the operating statement, so the
 * numbers tie out end to end. No ACCA/Kaplan/BPP text.
 */

export const MA_D: StudyChapter = {
  paper: "MA",
  area: "D",
  title: "Standard costing & variances",
  minutes: 17,
  intro: "A budget tells you what should have happened. The actual accounts tell you what did. Variance analysis is the bridge between them — the tool that turns \"we missed profit by $1,010\" into a list of named, fixable reasons.",
  outcomes: [
    "Explain what a standard cost is and distinguish the four types of standard",
    "Calculate material, labour and variable overhead variances and split each into its causes",
    "Calculate fixed overhead expenditure and volume variances, and split volume into capacity and efficiency",
    "Calculate sales price and sales volume variances valued at standard profit",
    "Build an operating statement that reconciles budgeted profit to actual profit",
    "Interpret variances, spot interdependence and judge which ones to investigate",
  ],
  sections: [
    {
      id: "standards",
      heading: "Standard costs and the standard cost card",
      blocks: [
        { kind: "text", md: "A **standard cost** is a carefully pre-set estimate of what one unit of output *should* cost, built up from expected quantities and expected prices. Set it once, and every actual result has something to be measured against. The whole of variance analysis is just the gap between this standard and reality, sliced into pieces you can act on." },
        { kind: "text", md: "The standards are collected on a **standard cost card** — a per-unit recipe. Here is the card for our worked example throughout this chapter, a product called **Zeta**." },
        { kind: "table", caption: "Standard cost card — one unit of Zeta", head: ["Element", "Quantity", "Rate", "Standard cost"], rows: [
          ["Direct materials", "4 kg", "$3.00 / kg", "$12.00"],
          ["Direct labour", "2 hours", "$8.00 / hr", "$16.00"],
          ["Variable overhead", "2 hours", "$2.00 / hr", "$4.00"],
          ["Fixed overhead", "2 hours", "$5.00 / hr", "$10.00"],
          ["Standard cost", "", "", "$42.00"],
          ["Standard selling price", "", "", "$60.00"],
          ["Standard profit", "", "", "$18.00"],
        ] },
        { kind: "text", md: "Overheads are **absorbed on labour hours** here: each unit takes 2 standard hours, so it carries 2 hours of variable overhead and 2 hours of fixed overhead. The budget is **1,000 units**, which is **2,000 standard hours** and **$10,000** of budgeted fixed overhead (2,000 hrs × $5)." },
        { kind: "text", md: "Not every standard is set to the same ambition. There are **four types**, and the choice changes how motivating — and how fair — the resulting variances are." },
        { kind: "diagram", diagram: {
          type: "cards",
          title: "The four types of standard",
          caption: "Most businesses use attainable standards — tough but reachable.",
          data: {
            items: [
              { title: "Ideal", sub: "Perfect conditions: no waste, no idle time, no breakdowns. Almost always unattainable — can demotivate." },
              { title: "Attainable", sub: "Efficient but realistic: allows for normal waste and downtime. The usual, motivating choice." },
              { title: "Current", sub: "Based on conditions right now — useful when circumstances are temporarily abnormal." },
              { title: "Basic", sub: "Left unchanged for years. Good for spotting long-run trends, poor for day-to-day control." },
            ],
          },
        } },
        { kind: "callout", tone: "rule", title: "Flex before you compare", md: "You never compare actual cost against the *original* budget. You first **flex** the budget — rebuild it at the **actual output** — so you compare like with like. Zeta made 1,100 units, so the yardstick is the standard cost of 1,100 units, not 1,000." },
        { kind: "diagram", diagram: {
          type: "flow",
          title: "The standard costing control cycle",
          caption: "Variances are step 4 of a loop that ends by feeding back into the standards.",
          data: {
            steps: [
              { label: "Set standards", sub: "Cost & price per unit" },
              { label: "Record actuals", sub: "What really happened" },
              { label: "Flex the budget", sub: "Rebuild at actual output" },
              { label: "Compute variances", sub: "Standard vs actual" },
              { label: "Investigate", sub: "Significant? Controllable?" },
              { label: "Act & revise", sub: "Correct or update standards" },
            ],
          },
        } },
      ],
    },
    {
      id: "mat-lab",
      heading: "Material and labour variances",
      blocks: [
        { kind: "text", md: "Every **cost** variance answers two separate questions: did we pay the wrong **price**, and did we use the wrong **quantity**? Keeping those apart is the heart of the technique — a favourable price can hide an adverse usage, and only splitting them reveals it." },
        { kind: "callout", tone: "key", title: "Sign convention", md: "A cost variance is **Favourable (F)** when actual cost is **less** than standard, and **Adverse (A)** when it is **more**. Do the subtraction as *(standard − actual)*: a positive answer is F, a negative answer is A. Never trust the raw sign alone — always label F or A in words." },
        { kind: "formula", name: "Material price variance", expr: "(Standard price − Actual price) × Actual quantity purchased", note: "($3.00 − $2.80) × 4,500 kg = $900 Favourable. Zeta paid $0.20/kg less than standard. Actual price = $12,600 ÷ 4,500 = $2.80." },
        { kind: "formula", name: "Material usage variance", expr: "(Standard quantity for actual output − Actual quantity used) × Standard price", note: "(4,400 − 4,500) kg × $3.00 = $300 Adverse. Standard quantity for output = 1,100 units × 4 kg = 4,400 kg." },
        { kind: "example", title: "Worked example — material variances", scenario: "Zeta's standard is 4 kg at $3/kg. In the period the company made 1,100 units and bought and used 4,500 kg costing $12,600 in total ($2.80/kg). Analyse the total material variance into price and usage.", steps: [
          { label: "Standard cost of actual output", detail: "1,100 units × 4 kg × $3 = $13,200 — what the materials should have cost." },
          { label: "Total material variance", detail: "$13,200 standard − $12,600 actual = $600 Favourable overall." },
          { label: "Price element", detail: "($3.00 − $2.80) × 4,500 kg = $900 Favourable — cheaper material." },
          { label: "Usage element", detail: "(4,400 − 4,500) × $3.00 = $300 Adverse — used 100 kg more than standard." },
          { label: "Reconcile", detail: "$900 F − $300 A = $600 F — exactly the total." },
        ], result: "Total material variance $600 F = $900 F price + $300 A usage. The cheap material may have caused the extra usage — a classic interdependence to flag." },
        { kind: "text", md: "Labour works the same way, but with a twist: **hours paid** and **hours worked** can differ because of **idle time** (people paid but unable to work — a breakdown, a stock-out). The **rate** variance uses **hours paid**; the **efficiency** variance uses **hours worked**; and the gap between them is the **idle time** variance, which is **always adverse**." },
        { kind: "formula", name: "Labour rate variance", expr: "(Standard rate − Actual rate) × Actual hours paid", note: "($8.00 − $8.20) × 2,300 hrs = $460 Adverse. Actual rate = $18,860 ÷ 2,300 = $8.20/hr. Uses hours PAID." },
        { kind: "formula", name: "Idle time variance", expr: "Idle hours × Standard rate  (always Adverse)", note: "50 idle hrs × $8.00 = $400 Adverse. Paid for hours that produced nothing." },
        { kind: "formula", name: "Labour efficiency variance", expr: "(Standard hours for actual output − Actual hours worked) × Standard rate", note: "(2,200 − 2,250) hrs × $8.00 = $400 Adverse. Standard hours = 1,100 × 2 = 2,200. Uses hours WORKED." },
        { kind: "example", title: "Worked example — labour variances", scenario: "Zeta's standard is 2 hrs at $8/hr. For 1,100 units the company paid for 2,300 hours costing $18,860, of which 50 hours were idle (a machine breakdown), so 2,250 hours were actually worked.", steps: [
          { label: "Standard cost of actual output", detail: "1,100 × 2 × $8 = $17,600 standard labour cost." },
          { label: "Rate", detail: "($8.00 − $8.20) × 2,300 paid = $460 Adverse — paid $0.20/hr over standard." },
          { label: "Idle time", detail: "50 × $8.00 = $400 Adverse — always adverse." },
          { label: "Efficiency", detail: "(2,200 − 2,250) × $8.00 = $400 Adverse — the 2,250 worked hours produced only 2,200 standard hours of output." },
          { label: "Reconcile", detail: "$460 A + $400 A + $400 A = $1,260 A = $18,860 − $17,600. Ties to the total." },
        ], result: "Total labour variance $1,260 A = $460 rate + $400 idle time + $400 efficiency — all adverse." },
      ],
      check: {
        q: "Zeta's standard usage for the actual output is 4,400 kg; 4,500 kg was actually used; the standard price is $3/kg. What is the material USAGE variance?",
        options: [
          "$300 Adverse",
          "$300 Favourable",
          "$900 Favourable",
          "$1,500 Adverse",
        ],
        correct: 0,
        explain: "Usage = (standard qty for output − actual qty) × standard price = (4,400 − 4,500) × $3 = −$300, i.e. $300 Adverse. It is valued at the STANDARD price ($3), never the actual price — the price effect is captured separately in the price variance. Using more than standard is adverse.",
      },
    },
    {
      id: "overheads",
      heading: "Overhead variances",
      blocks: [
        { kind: "text", md: "**Variable overhead** behaves like a mini-labour cost: it varies with hours worked, so it splits into a spending (**expenditure/rate**) variance and an **efficiency** variance, both valued at the standard variable rate of $2/hr." },
        { kind: "formula", name: "Variable overhead expenditure variance", expr: "(Standard rate − Actual rate) × Actual hours worked", note: "($2.00 − $2.20) × 2,250 = $450 Adverse. Actual rate = $4,950 ÷ 2,250 = $2.20/hr." },
        { kind: "formula", name: "Variable overhead efficiency variance", expr: "(Standard hours for actual output − Actual hours worked) × Standard rate", note: "(2,200 − 2,250) × $2.00 = $100 Adverse. Same hours gap as labour efficiency, priced at the variable OH rate." },
        { kind: "text", md: "**Fixed overhead** is different in kind — it does **not** vary with activity, so there is no \"usage\" of it in the normal sense. Under **absorption costing** we still charge it to units at $10 each, and two things can go wrong: we might **spend** the wrong amount (**expenditure** variance) or **make** the wrong number of units so the fixed cost is over- or under-absorbed (**volume** variance)." },
        { kind: "formula", name: "Fixed overhead expenditure variance", expr: "Budgeted fixed overhead − Actual fixed overhead", note: "$10,000 − $10,400 = $400 Adverse. Spent $400 more than budgeted, regardless of output." },
        { kind: "formula", name: "Fixed overhead volume variance", expr: "(Actual output − Budgeted output) × Standard fixed OH per unit", note: "(1,100 − 1,000) × $10 = $1,000 Favourable. Made 100 more units than budget, so absorbed $1,000 more fixed OH." },
        { kind: "text", md: "The **volume** variance can be split further, because output can beat budget in two ways: by **working more hours** (capacity) or by **working those hours more efficiently** (efficiency). Both are measured in hours and priced at the standard fixed overhead absorption rate of **$5/hr**." },
        { kind: "formula", name: "Fixed overhead capacity variance", expr: "(Actual hours worked − Budgeted hours) × Standard OAR", note: "(2,250 − 2,000) × $5 = $1,250 Favourable. Worked 250 more hours than the 2,000 budgeted — more capacity used." },
        { kind: "formula", name: "Fixed overhead efficiency variance", expr: "(Standard hours for actual output − Actual hours worked) × Standard OAR", note: "(2,200 − 2,250) × $5 = $250 Adverse. Capacity $1,250 F + efficiency $250 A = $1,000 F volume." },
        { kind: "example", title: "Worked example — overhead variances", scenario: "Zeta absorbs overhead on labour hours: variable $2/hr, fixed $5/hr. Budget = 1,000 units (2,000 hrs, $10,000 fixed OH). Actual = 1,100 units, 2,250 hours worked, variable OH $4,950, fixed OH $10,400.", steps: [
          { label: "Var OH expenditure", detail: "($2.00 − $2.20) × 2,250 = $450 Adverse." },
          { label: "Var OH efficiency", detail: "(2,200 − 2,250) × $2.00 = $100 Adverse. Total variable OH variance = $550 A." },
          { label: "Fixed OH expenditure", detail: "$10,000 − $10,400 = $400 Adverse." },
          { label: "Fixed OH volume", detail: "(1,100 − 1,000) × $10 = $1,000 Favourable. Total fixed OH variance = $400 A + $1,000 F = $600 F." },
          { label: "Volume, split", detail: "Capacity (2,250 − 2,000) × $5 = $1,250 F; efficiency (2,200 − 2,250) × $5 = $250 A → net $1,000 F. Checks out." },
        ], result: "Variable OH $550 A ($450 + $100). Fixed OH $600 F: absorbed $11,000 (1,100 × $10) against $10,400 spent — over-absorbed by $600 because output beat budget." },
      ],
      check: {
        q: "Budgeted output was 1,000 units; actual output was 1,100 units; the standard fixed overhead is $10 per unit. What is the fixed overhead VOLUME variance?",
        options: [
          "$1,000 Adverse",
          "$1,000 Favourable",
          "$400 Adverse",
          "Nil — fixed costs have no volume variance",
        ],
        correct: 1,
        explain: "Volume = (actual − budgeted output) × standard fixed OH per unit = (1,100 − 1,000) × $10 = $1,000 Favourable. Making MORE units than budget absorbs more fixed overhead than planned, which is favourable. (Note the volume variance exists only under absorption costing — under marginal costing there is just the expenditure variance.)",
      },
    },
    {
      id: "sales",
      heading: "Sales variances",
      blocks: [
        { kind: "text", md: "Cost variances explain why costs differed. **Sales** variances explain why *revenue and margin* differed. There are two: selling at the wrong **price**, and selling the wrong **volume**. The subtle part is what the volume variance is valued at." },
        { kind: "formula", name: "Sales price variance", expr: "(Actual price − Standard price) × Actual units sold", note: "($58 − $60) × 1,100 = $2,200 Adverse. Sold at $2 below the standard price on every unit." },
        { kind: "formula", name: "Sales volume profit variance", expr: "(Actual units sold − Budgeted units sold) × Standard profit per unit", note: "(1,100 − 1,000) × $18 = $1,800 Favourable. Under absorption costing it is valued at standard PROFIT, not selling price." },
        { kind: "callout", tone: "warn", title: "Value volume at profit, not price", md: "The commonest sales-variance error is valuing the volume difference at the **selling price** ($60) or at **contribution**. Under **absorption costing** the sales volume variance is (units difference) × **standard profit** per unit ($18). Selling 100 extra units gains 100 × $18 = $1,800 of standard profit, not $6,000 of revenue." },
        { kind: "example", title: "Worked example — sales variances", scenario: "Zeta's standard selling price is $60 and standard profit is $18/unit. Budgeted sales were 1,000 units. Actual sales were 1,100 units at $58 each.", steps: [
          { label: "Price", detail: "($58 − $60) × 1,100 = $2,200 Adverse — sold cheaper than standard." },
          { label: "Volume", detail: "(1,100 − 1,000) × $18 = $1,800 Favourable — sold 100 more units, each carrying $18 standard profit." },
          { label: "Net sales effect", detail: "$1,800 F − $2,200 A = $400 Adverse net from the sales side." },
        ], result: "Sales price $2,200 A + sales volume $1,800 F. The price cut may itself have driven the extra volume — another interdependence worth naming." },
      ],
    },
    {
      id: "operating-statement",
      heading: "The operating statement",
      blocks: [
        { kind: "text", md: "Individually the variances are diagnostics. Assembled, they form the **operating statement** — a single schedule that starts at **budgeted profit** and walks, variance by variance, to the **actual profit**. It is the proof that your analysis is complete: if it reconciles, every dollar of the profit difference is accounted for." },
        { kind: "text", md: "The walk has a natural order. Start with **budgeted profit** ($18,000 = 1,000 units × $18). Adjust for the **sales volume** variance to reach the **standard profit on actual sales** ($19,800 = 1,100 × $18). Then subtract the **sales price** variance and every **cost** variance to land on actual profit." },
        { kind: "table", caption: "Operating statement — reconciling budgeted profit to actual profit ($)", head: ["Item", "F $", "A $", "Profit $"], rows: [
          ["Budgeted profit", "", "", "18,000"],
          ["Sales volume variance", "1,800", "", ""],
          ["Standard profit on actual sales", "", "", "19,800"],
          ["Sales price variance", "", "2,200", ""],
          ["Cost variances:", "", "", ""],
          ["  Material price", "900", "", ""],
          ["  Material usage", "", "300", ""],
          ["  Labour rate", "", "460", ""],
          ["  Labour idle time", "", "400", ""],
          ["  Labour efficiency", "", "400", ""],
          ["  Variable overhead expenditure", "", "450", ""],
          ["  Variable overhead efficiency", "", "100", ""],
          ["  Fixed overhead expenditure", "", "400", ""],
          ["  Fixed overhead volume", "1,000", "", ""],
          ["Total variances", "3,700", "4,710", "(1,010)"],
          ["Actual profit", "", "", "16,990"],
        ] },
        { kind: "text", md: "The favourable column totals **$3,700** and the adverse column **$4,710**, a net **$1,010 Adverse**. So $18,000 − $1,010 = **$16,990** actual profit. Prove it directly: revenue 1,100 × $58 = $63,800, less actual costs (materials $12,600 + labour $18,860 + variable OH $4,950 + fixed OH $10,400 = $46,810) = **$16,990**. The statement reconciles." },
        { kind: "diagram", diagram: {
          type: "waterfall",
          title: "Profit bridge — budgeted $18,000 to actual $16,990",
          caption: "Favourable variances lift the bar, adverse variances (shown negative) pull it down.",
          data: {
            unit: "$",
            items: [
              { label: "Budgeted profit", value: 18000, kind: "start" },
              { label: "Sales volume", value: 1800, kind: "delta" },
              { label: "Sales price", value: -2200, kind: "delta" },
              { label: "Material price", value: 900, kind: "delta" },
              { label: "Material usage", value: -300, kind: "delta" },
              { label: "Labour rate", value: -460, kind: "delta" },
              { label: "Labour idle time", value: -400, kind: "delta" },
              { label: "Labour efficiency", value: -400, kind: "delta" },
              { label: "Var OH expenditure", value: -450, kind: "delta" },
              { label: "Var OH efficiency", value: -100, kind: "delta" },
              { label: "Fixed OH expenditure", value: -400, kind: "delta" },
              { label: "Fixed OH volume", value: 1000, kind: "delta" },
              { label: "Actual profit", value: 16990, kind: "total" },
            ],
          },
        } },
        { kind: "callout", tone: "tip", md: "Under **marginal costing** the statement starts from budgeted **contribution**, the sales volume variance is valued at standard **contribution**, and there is **no fixed overhead volume variance** — fixed overhead appears only as its expenditure variance." },
      ],
      check: {
        q: "The operating statement shows favourable variances of $3,700 and adverse variances of $4,710, starting from a budgeted profit of $18,000. What is the actual profit?",
        options: [
          "$26,410",
          "$16,990",
          "$19,010",
          "$15,290",
        ],
        correct: 1,
        explain: "Net variance = $3,700 F − $4,710 A = $1,010 Adverse. Adverse variances reduce profit, so actual profit = $18,000 − $1,010 = $16,990. Adding the favourable and adverse totals ($26,410) or netting the wrong way are the classic traps.",
      },
    },
    {
      id: "interpretation",
      heading: "Interpretation and interdependence",
      blocks: [
        { kind: "text", md: "A variance is a **question, not a verdict**. \"$460 adverse labour rate\" doesn't tell you someone did wrong — it tells you where to look. The real skill is reading the *pattern*: which variances are large, which are controllable, and how they connect." },
        { kind: "text", md: "The single most important idea is **interdependence**: one decision can trigger opposite variances elsewhere. Buying cheaper material (favourable price) that is poor quality causes **more waste** (adverse usage) and **slower work** (adverse labour efficiency). Judging the buyer on the price variance alone would reward exactly the decision that hurt overall profit." },
        { kind: "diagram", diagram: {
          type: "compare",
          title: "Why a variance arises — read the cause, not just the sign",
          caption: "The same variance can be good news or a warning; investigate the reason.",
          data: {
            leftTitle: "Favourable — but check why",
            rightTitle: "Adverse — but check why",
            rows: [
              { aspect: "Material price", left: "Bulk discount, cheaper supplier, market price fall", right: "Rush order, supplier price rise, small uneconomic batches" },
              { aspect: "Material usage", left: "Higher-grade input, skilled staff, less waste", right: "Poor-quality material, untrained staff, faulty machines" },
              { aspect: "Labour efficiency", left: "Skilled workers, better methods, high morale", right: "Idle time, weak supervision, low-grade materials" },
              { aspect: "Sales volume", left: "Strong demand, good marketing, a price cut", right: "Weak demand, lost customers, stock-outs" },
            ],
          },
        } },
        { kind: "callout", tone: "key", title: "Which variances to investigate?", md: "You cannot chase everything. Investigate a variance when it is **significant** (large in size or as a % of standard), **controllable** by a manager, part of an **adverse trend**, and worth more to fix than the cost of investigating. A tiny one-off adverse variance is usually noise." },
        { kind: "text", md: "Finally, treat the standards themselves with suspicion. A run of adverse variances across every product may mean the workforce is failing — or it may mean the **standard is out of date** (a wage rise, a permanent price change). Variance analysis feeds back into step 1 of the control cycle: sometimes the fix is to revise the standard, not the behaviour." },
      ],
    },
  ],
  examTraps: [
    { trap: "Using actual hours worked in the labour RATE variance.", fix: "The rate variance uses hours PAID (you are paid for idle hours too). Only the efficiency variance uses hours worked." },
    { trap: "Valuing the material price variance on the standard quantity.", fix: "Price variance is on the ACTUAL quantity purchased/used — you overpaid on every unit you actually bought, not on the standard allowance." },
    { trap: "Reading a negative number straight off as favourable.", fix: "For costs, F means actual is LESS than standard. Always compute (standard − actual) and label F or A in words before trusting the sign." },
    { trap: "Valuing the sales volume variance at selling price or contribution under absorption costing.", fix: "Under absorption costing it is (units difference) × standard PROFIT per unit. Contribution is used only under marginal costing." },
    { trap: "Calculating a fixed overhead volume variance under marginal costing.", fix: "It exists only under absorption costing. Under marginal costing fixed overhead has an expenditure variance only — no volume, capacity or efficiency split." },
  ],
  keyTerms: [
    { term: "Standard cost", def: "A pre-set estimate of what one unit of output should cost, built from expected quantities and prices; the benchmark for variance analysis." },
    { term: "Attainable standard", def: "A standard set at an efficient but realistic level, allowing for normal waste and downtime — the usual, motivating choice." },
    { term: "Flexed budget", def: "The original budget rebuilt at the actual level of output, so actual results are compared like with like." },
    { term: "Idle time variance", def: "Idle hours × standard rate; the cost of paying labour that could not work. Always adverse." },
    { term: "Fixed overhead volume variance", def: "(Actual − budgeted output) × standard fixed OH per unit; the over- or under-absorption caused by making a different volume than budgeted. Absorption costing only." },
    { term: "Operating statement", def: "A reconciliation that walks from budgeted profit to actual profit through every sales and cost variance." },
  ],
  summary: [
    "A standard cost card sets the per-unit benchmark; flex the budget to actual output before comparing, and choose an attainable standard.",
    "Split each cost variance into price/rate and quantity/efficiency: material price uses actual quantity, labour rate uses hours paid, efficiency uses hours worked, and idle time is always adverse.",
    "Fixed overhead splits into an expenditure variance (budget − actual) and, under absorption costing only, a volume variance that further splits into capacity and efficiency.",
    "Sales variances are price (actual − standard price × units) and volume (units difference × standard profit under absorption costing).",
    "The operating statement reconciles budgeted profit to actual profit — for Zeta, $18,000 − $1,010 net adverse = $16,990 — and interdependence means you must read the cause behind each variance, not just its sign.",
  ],
}
