import type { AccaQuestion } from "@/lib/acca-content"

/*
 * LW (F4) — Corporate and Business Law, GLOBAL variant: authored objective bank.
 *
 * Written because LW-Global previously shipped no authored questions at all: its
 * bank was 342 of 350 derived recall prompts, so its diagnostic was 84% glossary
 * retrieval and its Exam Readiness Score measured almost nothing. Global is also
 * the DEFAULT LW variant, so that was the default experience.
 *
 * These follow the real LW-GLO syllabus (A–H) rather than the UK variant: Area B
 * is international sale of goods under the CISG and Area C is transport and
 * payment, where UK LW has the law of obligations and employment law.
 *
 * Authoring standard, matching the rest of the bank:
 *   · Applied wherever the syllabus allows — a scenario and a conclusion, not a
 *     definition lookup. Recall-only items are confined to the "easy" tier.
 *   · Distractors are TARGETED MISCONCEPTIONS: the answer a candidate reaches by
 *     applying the wrong rule, the wrong party or the wrong threshold. A random
 *     off-topic option teaches nothing and inflates the mastery model.
 *   · Every explanation names the rule AND, where there is one, the classic error.
 *
 * Original wording throughout: aligned to the published syllabus, never a
 * reproduction of ACCA exam material.
 */

const q = (
  id: string,
  area: string,
  difficulty: AccaQuestion["difficulty"],
  stem: string,
  options: string[],
  correct: number,
  explanation: string,
): AccaQuestion => ({
  id: `lw-glo-${id}`,
  paper: "LW",
  area,
  type: "mcq",
  stem,
  options,
  correct,
  explanation,
  marks: 2,
  difficulty,
})

export const LW_GLOBAL_QUESTIONS: AccaQuestion[] = [
  /* ── A · Essential elements of legal systems ─────────────────── */
  q("a1", "A", "easy",
    "In a civil law legal system, what is the primary source of law?",
    [
      "Binding precedent set by senior courts",
      "Comprehensive codes and enacted legislation",
      "Custom recorded by professional bodies",
      "Decisions of arbitral tribunals",
    ], 1,
    "Civil law systems treat codified legislation as the primary source; earlier judgments are persuasive but not binding. Choosing binding precedent describes a common law system — the classic confusion between the two traditions."),
  q("a2", "A", "easy",
    "Which outcome distinguishes arbitration from mediation?",
    [
      "Arbitration produces a decision the parties are bound to accept",
      "Arbitration is always conducted in public",
      "Arbitration cannot be agreed before a dispute arises",
      "Arbitration must be conducted by a serving judge",
    ], 0,
    "An arbitral tribunal issues a binding award; a mediator only facilitates a settlement the parties choose to accept. Arbitration is normally private, is usually agreed in advance by a contract clause, and does not require a judge."),
  q("a3", "A", "medium",
    "A supplier in one state and a buyer in another disagree about which country's courts may hear their dispute. Which body of law addresses that question?",
    [
      "Public international law",
      "Private international law",
      "The law of the seller's state only",
      "Criminal law of the forum state",
    ], 1,
    "Private international law (conflict of laws) determines jurisdiction and the applicable law in cross-border disputes. Public international law governs relations between states and international organisations, not commercial parties."),
  q("a4", "A", "medium",
    "What is the practical significance of the New York Convention for a business trading internationally?",
    [
      "It creates a single global commercial court",
      "It harmonises the substantive law of sale of goods",
      "It supports recognition and enforcement of arbitral awards across signatory states",
      "It removes the need for any dispute resolution clause",
    ], 2,
    "The Convention's value is enforcement: an award obtained in one signatory state can generally be recognised and enforced in another. Harmonising sale-of-goods law is the CISG's role, not the Convention's."),
  q("a5", "A", "hard",
    "Two parties' contract contains a valid arbitration clause. One party nevertheless issues court proceedings on the same dispute. What is the court in a signatory state most likely to do?",
    [
      "Hear the case, because access to the courts cannot be excluded by contract",
      "Refer the parties to arbitration and stay its own proceedings",
      "Declare the whole contract void for ousting its jurisdiction",
      "Hear the case only if the claimant is the weaker party",
    ], 1,
    "A court in a signatory state will normally give effect to the parties' agreement by staying proceedings and referring them to arbitration. The clause allocates the forum; it does not unlawfully oust jurisdiction, and it does not invalidate the contract."),
  q("a6", "A", "hard",
    "A UNCITRAL Model Law differs from an international convention principally because a Model Law:",
    [
      "Binds every UN member state automatically on adoption by the Commission",
      "Takes effect in a state only if that state enacts it into national law",
      "Applies only to disputes between states",
      "Cannot be modified by the enacting state",
    ], 1,
    "A Model Law is a template: it has no force until a state legislates it, and the state may adapt it. A convention binds states that ratify it. Assuming a Model Law is automatically binding is the classic error."),

  /* ── B · International business transactions (CISG) ──────────── */
  q("b1", "B", "easy",
    "The CISG applies, in principle, to a contract for the sale of goods where:",
    [
      "The parties have their places of business in different Contracting States",
      "The goods physically cross at least two borders",
      "The contract is written in English",
      "Both parties are companies rather than individuals",
    ], 0,
    "Application turns on the parties' places of business being in different Contracting States, not on the goods' route, the contract language, or corporate status."),
  q("b2", "B", "easy",
    "Which sale falls OUTSIDE the scope of the CISG?",
    [
      "A commercial sale of industrial components",
      "A sale of goods bought for personal, family or household use",
      "A sale of raw materials between manufacturers",
      "A sale of packaged food between trading companies",
    ], 1,
    "Consumer sales are expressly excluded, as are sales by auction, and sales of ships, aircraft and electricity. The other options are ordinary commercial sales within scope."),
  q("b3", "B", "medium",
    "A buyer posts a letter accepting an offer. Under the CISG, when does the acceptance become effective?",
    [
      "When the letter is posted",
      "When the acceptance reaches the offeror",
      "When the buyer decides to accept",
      "When the goods are dispatched",
    ], 1,
    "The CISG uses a receipt rule: acceptance is effective when the indication of assent reaches the offeror. Applying a postal rule — effective on posting — is the classic error carried over from some domestic systems."),
  q("b4", "B", "medium",
    "Under the CISG, a breach is fundamental where it:",
    [
      "Causes any measurable financial loss",
      "Substantially deprives the other party of what it was entitled to expect under the contract",
      "Involves late performance of any obligation",
      "Is committed deliberately rather than negligently",
    ], 1,
    "The test is the seriousness of the deprivation, judged against the parties' contractual expectations and foreseeability — not the size of the loss, the type of term, or the breaching party's state of mind."),
  q("b5", "B", "hard",
    "A seller fails to deliver on the agreed date. The buyer notifies the seller of a reasonable additional period for delivery; the seller fails to deliver within it. Under the CISG, the buyer may:",
    [
      "Only claim damages, because the original delay was not fundamental",
      "Declare the contract avoided",
      "Do nothing until the delay itself becomes fundamental",
      "Require the seller to pay a statutory penalty",
    ], 1,
    "Fixing an additional period and seeing it expire without delivery entitles the buyer to avoid the contract, even where the original delay was not itself fundamental. The CISG provides no statutory penalty, and damages are not the buyer's only route."),
  q("b6", "B", "hard",
    "A buyer claims damages for breach. Which limitation applies to the recoverable amount under the CISG?",
    [
      "Damages are capped at the contract price in every case",
      "Damages exclude loss of profit",
      "Damages are limited to loss the party in breach foresaw or ought to have foreseen when the contract was concluded",
      "Damages are limited to expenditure actually incurred",
    ], 2,
    "Recovery is limited by foreseeability measured at the time of contracting, and is further reduced where the injured party failed to take reasonable steps to mitigate. Loss of profit is expressly recoverable, and there is no automatic cap at the contract price."),

  /* ── C · Transportation and payment in international trade ───── */
  q("c1", "C", "easy",
    "Under an FOB term, at what point does risk in the goods pass to the buyer?",
    [
      "When the contract is signed",
      "When the goods are placed on board the vessel",
      "When the goods arrive at the destination port",
      "When the buyer pays the price",
    ], 1,
    "FOB passes risk when the goods are placed on board at the named port of shipment. Risk passing on arrival describes a delivered term such as DAP or DDP — the classic mix-up."),
  q("c2", "C", "easy",
    "Under a documentary credit, the issuing bank's undertaking is to pay:",
    [
      "Once the buyer confirms the goods are satisfactory",
      "Against presentation of documents that comply with the credit",
      "Only after the goods clear customs",
      "Whenever the seller demands payment",
    ], 1,
    "The bank pays against complying documents. The credit is independent of the underlying sale contract, so the buyer's satisfaction with the goods and their customs status are irrelevant to the bank's obligation."),
  q("c3", "C", "medium",
    "Which feature distinguishes a bill of lading from a sea waybill?",
    [
      "A bill of lading may operate as a document of title to the goods",
      "A bill of lading is issued by the buyer",
      "A bill of lading is evidence of insurance cover",
      "A bill of lading cannot evidence the contract of carriage",
    ], 0,
    "A bill of lading can transfer rights to the goods, which is what makes it usable as security and in documentary credits. A sea waybill evidences carriage and receipt but is not a document of title."),
  q("c4", "C", "medium",
    "Which pair correctly identifies the trade terms imposing the MINIMUM and MAXIMUM obligations on the seller?",
    [
      "Minimum FOB; maximum CIF",
      "Minimum EXW; maximum DDP",
      "Minimum DDP; maximum EXW",
      "Minimum CIF; maximum FCA",
    ], 1,
    "Under EXW the seller merely makes the goods available at its own premises; under DDP the seller bears cost and risk to the named destination, including import clearance. Reversing the two is the classic error."),
  q("c5", "C", "hard",
    "A seller presents documents under a documentary credit. The goods themselves conform to the contract, but one presented document is inconsistent with the credit's terms. The bank:",
    [
      "Must pay, because the goods conform",
      "Is entitled to refuse to pay",
      "Must pay half the credit amount",
      "Must pay once the carrier confirms shipment",
    ], 1,
    "Strict compliance governs: the bank deals in documents, not goods, so a discrepancy entitles it to refuse. The seller's remedy for conforming goods lies against the buyer under the sale contract, not against the bank."),
  q("c6", "C", "hard",
    "Under a CIF contract, the seller must arrange and pay for insurance. When does risk pass to the buyer?",
    [
      "On delivery of the goods at the destination port",
      "When the goods are placed on board at the port of shipment",
      "When the insurance policy is issued",
      "When the buyer accepts the documents",
    ], 1,
    "CIF splits cost from risk: the seller pays cost, freight and insurance, but risk passes on shipment. Assuming that because the seller pays to the destination it also bears risk to the destination is the classic CIF error — the insurance exists precisely because the buyer carries the risk in transit."),

  /* ── D · Formation and constitution of business organisations ── */
  q("d1", "D", "easy",
    "What is the principal legal consequence of incorporating a company?",
    [
      "The company becomes a legal person separate from its members",
      "The members become jointly liable for all company debts",
      "The company's contracts must be signed by every shareholder",
      "The company's profits belong directly to the directors",
    ], 0,
    "Incorporation creates a separate legal person that owns its own assets, incurs its own liabilities and contracts in its own name. Member liability is limited to amounts unpaid on their shares."),
  q("d2", "D", "easy",
    "In a general partnership, the partners' liability for the firm's debts is:",
    [
      "Limited to their capital contributions",
      "Unlimited",
      "Limited to one year's profit share",
      "Borne by the managing partner alone",
    ], 1,
    "General partners have unlimited liability for partnership debts. Limited liability requires a different vehicle, such as a limited liability partnership or a company."),
  q("d3", "D", "medium",
    "A company allows a manager to place supply orders for two years without ever granting formal authority. The manager places a further order and the company refuses to pay. The supplier can most likely enforce the contract on the basis of:",
    [
      "The manager's actual authority",
      "Apparent authority created by the company's conduct",
      "Ratification by the supplier",
      "The manager's personal guarantee",
    ], 1,
    "A principal that holds someone out as authorised is bound by apparent (ostensible) authority, even without a formal grant. Actual authority is absent on these facts, and ratification is something only the principal can do."),
  q("d4", "D", "medium",
    "An agent exceeds their authority. The principal later approves the transaction. What is the effect?",
    [
      "The contract remains unenforceable against the principal",
      "The principal is bound as from the date of the original act",
      "The agent alone remains liable",
      "A new contract must be executed to bind the principal",
    ], 1,
    "Ratification is retrospective: the principal is treated as bound from the time of the unauthorised act. No fresh contract is needed."),
  q("d5", "D", "hard",
    "A sole shareholder incorporates a company purely to place assets beyond the reach of an existing personal creditor. A court asked to make the shareholder liable is most likely to:",
    [
      "Refuse, because separate legal personality is absolute",
      "Look behind the corporate form because it is being used to evade an existing obligation",
      "Wind the company up automatically",
      "Treat every company in the group as one entity as a matter of course",
    ], 1,
    "Separate personality is the rule, but courts will look behind the corporate form where it is a mere façade used to evade an existing legal obligation. Treating group companies as one entity is not a general principle — that is the classic overstatement."),
  q("d6", "D", "hard",
    "How does a limited liability partnership differ from a general partnership?",
    [
      "It has no separate legal personality",
      "It is a separate legal person and its members' liability is limited",
      "It cannot carry on a profession",
      "Its members must all be companies",
    ], 1,
    "An LLP combines a separate legal personality and limited member liability with internal flexibility resembling a partnership. A general partnership, by contrast, is not a separate legal person in most systems and its partners are personally liable."),

  /* ── E · Capital and the financing of companies ──────────────── */
  q("e1", "E", "easy",
    "Which right most typically attaches to a preference share rather than an ordinary share?",
    [
      "A residual claim on surplus assets after all other claims",
      "A fixed dividend paid in priority to ordinary dividends",
      "An automatic right to appoint a director",
      "A guaranteed increase in dividend each year",
    ], 1,
    "Preference shares carry a fixed dividend paid ahead of ordinary dividends and usually priority on a return of capital, but ordinarily no residual participation. The residual claim is what ordinary shares carry."),
  q("e2", "E", "easy",
    "A floating charge differs from a fixed charge because, until crystallisation, the company may:",
    [
      "Deal freely with the assets in the ordinary course of business",
      "Ignore the lender's security entirely",
      "Sell the assets only with the lender's written consent",
      "Grant no further security of any kind",
    ], 0,
    "A floating charge hovers over a class of changing assets, leaving the company free to trade with them until an event crystallises the charge onto the assets then held. Needing consent for each dealing describes a fixed charge."),
  q("e3", "E", "medium",
    "A fixed charge and a later floating charge are both granted over the same asset. On enforcement, priority ordinarily goes to:",
    [
      "The floating charge, because it was created later",
      "The fixed charge",
      "Both equally",
      "Whichever lender demands payment first",
    ], 1,
    "A fixed charge attaches to the identified asset on creation and so ranks ahead of a floating charge over the same asset, even one created later. Later creation does not improve a floating charge's rank."),
  q("e4", "E", "medium",
    "What distinguishes a bonus issue from a rights issue?",
    [
      "A bonus issue raises new cash from existing members",
      "A bonus issue capitalises reserves and raises no new cash",
      "A bonus issue must be offered to the public",
      "A bonus issue reduces the company's issued share capital",
    ], 1,
    "A bonus issue converts reserves into share capital and brings in no new funds; a rights issue offers new shares for cash, usually pre-emptively to existing members. Both increase issued share capital."),
  q("e5", "E", "hard",
    "Why is the capital maintenance principle significant to a company's creditors?",
    [
      "It guarantees creditors will be repaid in full",
      "It restricts the return of contributed capital to members outside permitted procedures",
      "It requires the company to hold its capital in cash",
      "It prevents the company from borrowing",
    ], 1,
    "Contributed capital is treated as a buffer for creditors, so returning it to members is restricted to permitted procedures such as a properly conducted reduction of capital. It is not a repayment guarantee, and there is no requirement to hold capital in cash."),
  q("e6", "E", "hard",
    "A company grants a charge over its assets but the charge is never registered within the prescribed period. The usual consequence is that the charge is:",
    [
      "Valid against everyone, registration being merely administrative",
      "Void against a liquidator, administrator and other creditors, while the debt itself remains payable",
      "Converted automatically into a fixed charge",
      "Void, extinguishing the underlying debt as well",
    ], 1,
    "Non-registration costs the lender its security against a liquidator, administrator and competing creditors, leaving it an unsecured claim — but the loan itself is still owed. Assuming the debt disappears with the security is the classic error."),

  /* ── F · Management, administration and regulation ───────────── */
  q("f1", "F", "easy",
    "To whom do a director's general duties primarily run?",
    [
      "The company",
      "The majority shareholder personally",
      "The company's largest customer",
      "The directors as a group",
    ], 0,
    "Directors owe their duties to the company as a separate legal person. That is why an individual shareholder generally cannot sue for a wrong done to the company."),
  q("f2", "F", "easy",
    "Which majority is ordinarily required for a special resolution?",
    [
      "A simple majority of more than 50%",
      "At least 75%",
      "Unanimity",
      "At least 90%",
    ], 1,
    "A special resolution requires at least 75% of votes cast and is used for constitutional changes; an ordinary resolution needs a simple majority of more than 50%."),
  q("f3", "F", "medium",
    "A director has a personal interest in a contract the board is about to approve. The director's primary obligation is to:",
    [
      "Resign from the board",
      "Declare the nature and extent of the interest",
      "Sell the personal interest before the meeting",
      "Say nothing unless another director asks",
    ], 1,
    "The duty is to declare the nature and extent of the interest so the board can deal with it properly. Resignation or disposal is not required, and silence is a breach."),
  q("f4", "F", "medium",
    "What does an auditor's report on a company's financial statements express?",
    [
      "A guarantee that the statements contain no misstatement",
      "An opinion on whether the statements give a true and fair view",
      "An assurance that the company will remain solvent",
      "A valuation of the company's shares",
    ], 1,
    "The auditor expresses a reasonable-assurance opinion on whether the statements give a true and fair view. It is not a guarantee of accuracy, a solvency assurance, or a valuation — reading it as a guarantee is the expectation gap."),
  q("f5", "F", "hard",
    "A director learns of a business opportunity while acting for the company, resigns, and takes the opportunity personally. The likely legal outcome is that the director:",
    [
      "Owes nothing, because the resignation ended all duties",
      "Must account to the company for the profit made",
      "May keep the profit if the company could not have afforded the opportunity",
      "Commits a criminal offence punishable by fine",
    ], 1,
    "A director who exploits an opportunity that came to them through the office must account for the resulting profit; resigning first does not cure the conflict, and the company's inability to take it up is generally no defence. The liability is civil, not criminal."),
  q("f6", "F", "hard",
    "A company removes a director by ordinary resolution after the required special notice. The director also has a service contract with two years left to run. What is the position?",
    [
      "The removal is invalid while the service contract subsists",
      "The removal is effective, but the director may claim for breach of the service contract",
      "The director must be reinstated on request",
      "The service contract automatically transfers to another company",
    ], 1,
    "Removal from office and the employment relationship are separate: the removal stands, while the contract may give rise to a damages claim. Treating the service contract as blocking removal is the classic error."),

  /* ── G · Insolvency law ──────────────────────────────────────── */
  q("g1", "G", "easy",
    "Which feature identifies a members' voluntary liquidation?",
    [
      "The directors make a declaration that the company is solvent",
      "It follows a court order on a creditor's petition",
      "It is commenced by a secured creditor",
      "It can only be used where the company is insolvent",
    ], 0,
    "A members' voluntary liquidation is a solvent wind-up begun by the members and supported by a declaration of solvency. A creditors' voluntary liquidation is used where the company is insolvent, and compulsory liquidation follows a court order."),
  q("g2", "G", "easy",
    "What is the primary objective of an administration?",
    [
      "Rescuing the company as a going concern",
      "Distributing assets to members",
      "Prosecuting the directors",
      "Selling the company's assets at the highest price regardless of outcome",
    ], 0,
    "The administrator's hierarchy of objectives starts with rescuing the company as a going concern, then a better result for creditors as a whole than liquidation, and only then realising property for secured or preferential creditors."),
  q("g3", "G", "medium",
    "In a liquidation, which claim is met FIRST out of the assets subject to a floating charge?",
    [
      "The floating charge holder",
      "Preferential debts",
      "Ordinary unsecured creditors",
      "Members' capital",
    ], 1,
    "Preferential debts rank ahead of floating charge realisations, and a prescribed part is then set aside for unsecured creditors. Members rank last, after all creditors are paid."),
  q("g4", "G", "medium",
    "How does a compulsory liquidation begin?",
    [
      "By a resolution of the members",
      "By a court order following a petition",
      "By the directors filing a notice at the registry",
      "By a secured creditor appointing a receiver",
    ], 1,
    "Compulsory liquidation requires a court order made on a petition, commonly by an unpaid creditor. Members' resolutions begin voluntary liquidations, and appointing a receiver is enforcement of security, not liquidation."),
  q("g5", "G", "hard",
    "A director continues to trade and incur credit at a point when there is no reasonable prospect of avoiding insolvent liquidation. Which liability is most directly engaged?",
    [
      "Fraudulent trading, requiring proof of dishonesty",
      "Wrongful trading, which can require a personal contribution to the company's assets",
      "No liability, because the company is a separate legal person",
      "Automatic disqualification without any court involvement",
    ], 1,
    "Wrongful trading is the civil liability that arises without any need to prove dishonesty: the test is what the director knew or ought to have concluded. Fraudulent trading requires intent to defraud, which is much harder to establish."),
  q("g6", "G", "hard",
    "A company in liquidation has assets of 100 subject only to a floating charge. Preferential debts are 30 and the floating charge secures 90. Ignoring the prescribed part and costs, how much does the floating charge holder receive?",
    [
      "90",
      "70",
      "100",
      "30",
    ], 1,
    "Preferential debts of 30 are paid first out of the floating charge assets, leaving 70 for the charge holder against its 90 claim; the 20 shortfall ranks as unsecured. Answering 90 pays the charge holder in full and wrongly subordinates the preferential creditors."),

  /* ── H · Corporate fraudulent and criminal behaviour ─────────── */
  q("h1", "H", "easy",
    "Which sequence describes the recognised stages of money laundering?",
    [
      "Layering, placement, integration",
      "Placement, layering, integration",
      "Integration, placement, layering",
      "Placement, integration, layering",
    ], 1,
    "Criminal property is first placed into the financial system, then layered through transactions to disguise its origin, and finally integrated so it appears legitimate."),
  q("h2", "H", "easy",
    "Insider dealing is best described as dealing in securities while:",
    [
      "Holding a large shareholding in the company",
      "In possession of price-sensitive information that is not public",
      "Employed by the company in any capacity",
      "Acting on a published analyst recommendation",
    ], 1,
    "The wrong lies in using inside information — precise, price-sensitive and not public. Merely holding shares, being an employee, or trading on published research is not the offence."),
  q("h3", "H", "medium",
    "An accountant in the regulated sector suspects a client of money laundering and makes the required report. The accountant then tells the client about the report. Which offence is committed?",
    [
      "Failure to disclose",
      "Tipping off",
      "No offence, since the report was properly made",
      "Insider dealing",
    ], 1,
    "Disclosing that a report has been made, where that is likely to prejudice an investigation, is tipping off. Failure to disclose would be the offence had no report been made at all."),
  q("h4", "H", "medium",
    "Which element must be present for the offence of bribery in a commercial context?",
    [
      "An advantage intended to induce improper performance of a function",
      "A payment exceeding a fixed statutory amount",
      "Payment made in cash",
      "Actual financial loss to a third party",
    ], 0,
    "The essence is an advantage offered, promised or given to induce improper performance of a relevant function. There is no minimum amount, no requirement that it be cash, and no need to prove loss."),
  q("h5", "H", "hard",
    "Which statement correctly contrasts fraudulent trading with wrongful trading?",
    [
      "Both require proof of dishonesty",
      "Fraudulent trading requires intent to defraud and may be criminal; wrongful trading needs no dishonesty and is civil",
      "Wrongful trading requires intent to defraud; fraudulent trading does not",
      "Neither can result in personal liability for a director",
    ], 1,
    "Fraudulent trading turns on intent to defraud and can attract criminal as well as civil liability. Wrongful trading is civil only and is established on what the director knew or ought to have concluded, without any dishonesty — which is why it is the more commonly pursued claim."),
  q("h6", "H", "hard",
    "A company's employee pays a bribe to win a contract. The company had no anti-bribery procedures at all. The company's exposure is best described as:",
    [
      "None, because the employee acted personally",
      "Potential corporate liability, since having no adequate preventive procedures removes the usual defence",
      "Limited to returning the profit on the contract",
      "Dependent on whether the directors knew of the payment",
    ], 1,
    "Corporate liability for failing to prevent bribery is met by showing adequate procedures were in place; with none, that defence is unavailable. Director knowledge is not required, and exposure is not confined to disgorging the profit."),
]
