import type { AccaQuestion } from "@/lib/acca-content"

/*
 * AAA bank wave S1 part A (areas A,B,C) — 80 verified originals (2026-07-13).
 * Blueprint: A20 B35 C25; difficulty 22 easy / 38 medium / 20 hard.
 * All mcq, 4 options, marks 2. Correct-position balance: index 0/1/2/3 each
 * correct exactly 20 times across the 80 questions.
 *
 * ORIGINALITY: every firm/client name and scenario is invented for Scholify;
 * nothing is reproduced from ACCA, Kaplan or BPP material — only the public
 * AAA (P7) syllabus outline is used.
 * STANDARDS ACCURACY: ethical-threat classifications, the PIE fee-dependence
 * (15%) and key-audit-partner rotation (7 years on / 5 off) rules, and the
 * ISQM 1 / ISQM 2 / ISA 220 detail were verified against the IESBA Code and
 * the IAASB quality-management suite before writing. Every distractor is a
 * nameable error and each explanation cites the governing standard/rule.
 */

export const AAA_WAVE1A: AccaQuestion[] = [
  /* ═══════════ Area A — Regulatory environment (20) ═══════════ */
  {
    id: "AAA2-A-01",
    paper: "AAA",
    area: "A",
    type: "mcq",
    stem: "Which body is responsible for issuing the International Standards on Auditing (ISAs)?",
    options: [
      "The Public Interest Oversight Board (PIOB)",
      "The ACCA",
      "The International Auditing and Assurance Standards Board (IAASB)",
      "The International Ethics Standards Board for Accountants (IESBA)",
    ],
    correct: 2,
    explanation:
      "The IAASB, an independent standard-setting board supported by IFAC, develops and issues the ISAs. The PIOB oversees the standard-setting process in the public interest but does not write the standards; the ACCA is a professional membership body and does not set ISAs; and IESBA issues the international ethics code, not the auditing standards.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AAA2-A-02",
    paper: "AAA",
    area: "A",
    type: "mcq",
    stem: "What best describes the role of the International Federation of Accountants (IFAC)?",
    options: [
      "The global organisation for the accountancy profession that supports independent standard-setting boards such as the IAASB and IESBA",
      "A national regulator that inspects individual audit files for listed companies",
      "The board that issues the international ethics code for professional accountants",
      "A government agency that licenses audit firms in each country",
    ],
    correct: 0,
    explanation:
      "IFAC is the global body for the profession; it supports the independent boards (IAASB, IESBA) that set international auditing and ethics standards. It is not a national inspection regulator (that role sits with bodies such as national oversight authorities), it is not itself the ethics board (that is IESBA), and it does not license firms (a domestic regulatory function).",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AAA2-A-03",
    paper: "AAA",
    area: "A",
    type: "mcq",
    stem: "During the audit of Calderby Traders Ltd, the audit manager forms a suspicion that a director is laundering the proceeds of tax evasion through the company. Under the money laundering regulations, what should the auditor do?",
    options: [
      "Confront the director and require the arrangement to cease before continuing",
      "Make a suspicious activity report to the firm's money laundering reporting officer without alerting the client",
      "Resign from the engagement and disclose the reason to the incoming auditor",
      "Qualify the audit opinion so that shareholders are warned",
    ],
    correct: 1,
    explanation:
      "The correct response is an internal report to the MLRO (who reports on to the authorities) while avoiding any tipping-off. Confronting the director risks committing the tipping-off offence; resigning and disclosing the reason to a successor would breach confidentiality and could also tip off; and modifying the audit opinion is not the mechanism for reporting money laundering.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-A-04",
    paper: "AAA",
    area: "A",
    type: "mcq",
    stem: "In the context of the money laundering regulations, what is the offence of 'tipping off'?",
    options: [
      "Failing to appoint a money laundering reporting officer within the firm",
      "Accepting a cash payment above the regulatory threshold from a client",
      "Failing to retain customer due diligence records for the required period",
      "Disclosing to a suspected launderer that a report has been, or is to be, made in a way that may prejudice any investigation",
    ],
    correct: 3,
    explanation:
      "Tipping off is disclosing that a suspicious activity report has been (or will be) made where that disclosure could prejudice an investigation. The other options are separate compliance failings — no MLRO appointed, breaching cash-handling limits, and inadequate record retention — but none of them is the tipping-off offence.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-A-05",
    paper: "AAA",
    area: "A",
    type: "mcq",
    stem: "ISA 250 distinguishes laws and regulations that have a direct effect on the determination of material amounts and disclosures. For such laws, what is the auditor's responsibility?",
    options: [
      "Only to inquire of management whether the entity has complied",
      "To obtain sufficient appropriate audit evidence about compliance with those laws and regulations",
      "There is no responsibility because compliance is solely a management matter",
      "To report every instance to regulators regardless of materiality",
    ],
    correct: 1,
    explanation:
      "For laws with a direct effect on material figures (for example, tax and pension law), ISA 250 requires the auditor to obtain sufficient appropriate evidence about compliance. Mere inquiry is insufficient for direct-effect laws; the auditor is not free of responsibility; and automatic reporting of every instance to regulators is not required and would ignore materiality and confidentiality considerations.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AAA2-A-06",
    paper: "AAA",
    area: "A",
    type: "mcq",
    stem: "For laws and regulations that do NOT have a direct effect on the financial statements but where non-compliance may be material (for example, operating licences or environmental rules), what does ISA 250 require the auditor to do?",
    options: [
      "Audit compliance in full, exactly as for direct-effect laws",
      "Take no action because such laws are outside the scope of the audit",
      "Perform specified procedures to help identify non-compliance that may materially affect the financial statements, such as inquiry of management and inspecting correspondence with regulators",
      "Report to those charged with governance only if the client agrees to it",
    ],
    correct: 2,
    explanation:
      "For indirect-effect laws, ISA 250 requires limited, specified procedures — chiefly inquiry of management/TCWG and inspecting any correspondence with licensing or regulatory authorities. The auditor does not audit compliance in full as with direct-effect laws, cannot simply ignore these laws, and communication of identified non-compliance to TCWG is not conditional on client consent.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-A-07",
    paper: "AAA",
    area: "A",
    type: "mcq",
    stem: "Which additional reporting requirement applies to the auditor's report of a listed entity that does not apply to most unlisted companies?",
    options: [
      "The report must communicate key audit matters (ISA 701)",
      "The report must guarantee that the entity is a going concern",
      "The report must express an opinion on the effectiveness of internal control in every jurisdiction",
      "The report may be signed only in the name of the individual partner, never the firm",
    ],
    correct: 0,
    explanation:
      "ISA 701 requires the communication of key audit matters in the auditor's report of listed entities. Auditors never guarantee going concern; there is no general requirement to opine on the effectiveness of internal control across jurisdictions in an ISA audit; and reports are normally signed in the name of the firm (and often the engagement partner), not the partner alone.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-A-08",
    paper: "AAA",
    area: "A",
    type: "mcq",
    stem: "Under ISA 260, the auditor of a listed company communicates certain matters to those charged with governance. Which of the following is specifically required to be communicated?",
    options: [
      "A guarantee that no fraud exists within the entity",
      "The fee the firm intends to charge in the following year",
      "The directors' recommended remuneration for the coming year",
      "A statement that the engagement team and firm have complied with relevant ethical requirements regarding independence",
    ],
    correct: 3,
    explanation:
      "For listed entities, ISA 260 requires the auditor to communicate a statement about compliance with independence requirements, including relationships and safeguards. Auditors cannot guarantee the absence of fraud; the next year's fee is not a required ISA 260 communication; and recommending directors' remuneration is a governance matter, not an audit communication.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AAA2-A-09",
    paper: "AAA",
    area: "A",
    type: "mcq",
    stem: "Under a typical corporate governance code, what is a principal responsibility of the audit committee in relation to the external auditor?",
    options: [
      "To prepare the financial statements for the external auditor to check",
      "To perform the external auditor's substantive testing to reduce fees",
      "To set the salaries of the executive directors without board involvement",
      "To make recommendations on the appointment, reappointment and removal of the external auditor and to monitor the auditor's independence",
    ],
    correct: 3,
    explanation:
      "The audit committee oversees the external audit relationship: recommending appointment/removal and monitoring independence and effectiveness. Preparing the financial statements is management's role; the committee does not perform the audit itself; and executive remuneration is dealt with by a remuneration committee, not the audit committee.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-A-10",
    paper: "AAA",
    area: "A",
    type: "mcq",
    stem: "What is meant by the 'audit expectation gap'?",
    options: [
      "The gap between the planned and actual audit fee for an engagement",
      "The difference between what the public believes auditors do and what auditors are actually required to do",
      "The period of time between the year end and the date of the auditor's report",
      "The difference between a company's book value and its market value",
    ],
    correct: 1,
    explanation:
      "The expectation gap is the difference between public perception of the auditor's role (for example, detecting all fraud or guaranteeing solvency) and the auditor's actual responsibilities under the standards. The other options describe a fee variance, the reporting timeline, and a valuation difference — none of which is the expectation gap.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AAA2-A-11",
    paper: "AAA",
    area: "A",
    type: "mcq",
    stem: "Which measure is most likely to help narrow the audit expectation gap?",
    options: [
      "Expanded auditor's reports that explain the scope of the audit and describe key audit matters",
      "Auditors guaranteeing the arithmetical accuracy of the accounts",
      "Removing the going concern assessment from the audit entirely",
      "Reducing the auditor's report to a single sentence to keep it simple",
    ],
    correct: 0,
    explanation:
      "More informative, expanded reports (including KAM and clearer descriptions of responsibilities) help users understand what the audit does and does not provide, narrowing the gap. Guaranteeing accuracy misstates the nature of assurance, removing going concern would widen the gap, and cutting the report to one sentence would reduce transparency.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-A-12",
    paper: "AAA",
    area: "A",
    type: "mcq",
    stem: "What is a 'transnational audit'?",
    options: [
      "Any audit that is performed jointly by more than one firm",
      "The audit of any company that buys or sells goods overseas",
      "An audit of financial statements that are, or may be, relied upon outside the entity's home jurisdiction — for example for cross-border listing, lending or investment",
      "An audit that is conducted in a language other than the auditor's own",
    ],
    correct: 2,
    explanation:
      "A transnational audit is one where the financial statements may be relied upon outside the home country, such as for a cross-border listing or financing. It is not defined by joint firms, by the client merely trading abroad, or by the language used; the defining feature is cross-border reliance on the statements.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AAA2-A-13",
    paper: "AAA",
    area: "A",
    type: "mcq",
    stem: "Which body exists to promote consistent, high-quality standards of practice among firms that perform transnational audits?",
    options: [
      "The Forum of Firms and its Transnational Auditors Committee",
      "The World Bank",
      "The IESBA acting alone",
      "The local tax authority in each country",
    ],
    correct: 0,
    explanation:
      "The Forum of Firms, through its Transnational Auditors Committee, promotes consistent, high-quality audit practices for firms performing transnational audits. The World Bank is a development institution, IESBA sets ethics standards rather than governing transnational-audit practice, and tax authorities have no such remit.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AAA2-A-14",
    paper: "AAA",
    area: "A",
    type: "mcq",
    stem: "Which statement best describes the structure of the ACCA/IESBA Code of Ethics?",
    options: [
      "A rules-based approach that lists every prohibited act exhaustively",
      "A voluntary set of guidelines with no enforcement",
      "An approach that applies only to partners and not to other staff",
      "A principles-based conceptual framework requiring accountants to identify, evaluate and address threats to the fundamental principles",
    ],
    correct: 3,
    explanation:
      "The Code uses a principles-based conceptual framework: identify threats, evaluate their significance, and apply safeguards or decline where threats cannot be reduced to an acceptable level. It is not an exhaustive rulebook, it is enforceable for members, and it applies to all professional accountants, not just partners.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-A-15",
    paper: "AAA",
    area: "A",
    type: "mcq",
    stem: "Which of the following is NOT one of the five fundamental principles in the IESBA/ACCA Code of Ethics?",
    options: [
      "Integrity",
      "Confidentiality",
      "Independence",
      "Professional behaviour",
    ],
    correct: 2,
    explanation:
      "The five fundamental principles are integrity, objectivity, professional competence and due care, confidentiality, and professional behaviour. Independence is not itself a fundamental principle — it is a requirement applied to assurance and audit engagements to support objectivity. Students often wrongly list independence as a principle.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AAA2-A-16",
    paper: "AAA",
    area: "A",
    type: "mcq",
    stem: "Under ISA 260, which of the following is a 'significant finding from the audit' that should be communicated to those charged with governance?",
    options: [
      "The detailed audit programme and sample sizes for every account",
      "Significant difficulties encountered during the audit and significant matters discussed with management",
      "The personal opinions of each junior about the client's staff",
      "The fees charged by competitor audit firms in the sector",
    ],
    correct: 1,
    explanation:
      "ISA 260 requires communication of significant findings, including significant difficulties encountered and significant matters discussed with management. The full audit programme is not required to be shared, juniors' personal opinions of staff are not audit findings, and competitors' fees are irrelevant to the ISA 260 communication.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-A-17",
    paper: "AAA",
    area: "A",
    type: "mcq",
    stem: "In the audit quality debate, what is the main purpose of an independent audit inspection regime (for example, a national audit oversight body reviewing firms)?",
    options: [
      "To prepare the financial statements of listed companies on the firm's behalf",
      "To set the audit fees charged to listed clients",
      "To inspect audit engagements and firms' quality management systems in order to protect the public interest and drive quality improvement",
      "To provide audit firms with a legal defence against shareholder claims",
    ],
    correct: 2,
    explanation:
      "Independent inspection regimes review engagements and firm-wide quality systems to protect the public interest and promote improvement. They do not prepare financial statements, do not set fees, and inspection is a regulatory oversight function, not a shield against negligence claims.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AAA2-A-18",
    paper: "AAA",
    area: "A",
    type: "mcq",
    stem: "As part of customer due diligence under the money laundering regulations, what must an audit firm do before accepting a new client?",
    options: [
      "Audit the client's most recent tax return",
      "Identify and verify the identity of the client and its beneficial owners",
      "Guarantee that the client is not involved in money laundering",
      "Report every prospective client to the police as a precaution",
    ],
    correct: 1,
    explanation:
      "Customer due diligence requires identifying and verifying the client and its beneficial owners and understanding the nature of the business. It does not require auditing the tax return, no firm can guarantee a client is clean, and blanket reporting of all clients would be both unnecessary and improper.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AAA2-A-19",
    paper: "AAA",
    area: "A",
    type: "mcq",
    stem: "During the audit of Restrode Group plc, the auditor identifies non-compliance with law that involves senior management and possibly some of those charged with governance. What does ISA 250 indicate the auditor should do?",
    options: [
      "Ignore the matter because compliance is management's responsibility",
      "Report the matter only to the management who are implicated",
      "Resign from the engagement immediately without any further consideration",
      "Communicate to the next higher level of authority, such as the audit committee, and where all levels are implicated consider legal advice and whether to withdraw from the engagement",
    ],
    correct: 3,
    explanation:
      "Where those normally receiving the communication are themselves involved, ISA 250 directs the auditor to escalate to a higher authority (for example, the audit committee) and, where no higher authority exists or all are complicit, to consider obtaining legal advice and possibly withdrawing. Ignoring it, reporting only to those implicated, or resigning reflexively without proper consideration are all inappropriate.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AAA2-A-20",
    paper: "AAA",
    area: "A",
    type: "mcq",
    stem: "Under a typical corporate governance code, how should the board of a listed company be structured?",
    options: [
      "With an appropriate balance of executive and independent non-executive directors, and separation of the chair and chief executive roles",
      "With only executive directors so that decisions can be made quickly",
      "With the chief executive also acting as chair to concentrate leadership",
      "Without an audit committee in order to reduce governance costs",
    ],
    correct: 0,
    explanation:
      "Codes emphasise a balanced board with sufficient independent non-executive directors and a separation of the chair and CEO roles to avoid concentration of power. A board of only executives lacks independence, combining chair and CEO concentrates power inappropriately, and removing the audit committee would weaken oversight of financial reporting and the auditor.",
    marks: 2,
    difficulty: "medium",
  },

  /* ═══════════ Area B — Professional & ethical considerations (35) ═══════════ */
  {
    id: "AAA2-B-01",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "The engagement partner on the audit of Halverton plc, a listed client, holds a direct shareholding in the company. Which threat arises and what action is required?",
    options: [
      "Self-interest threat; the financial interest must be eliminated (the shares disposed of) or the individual removed from the engagement",
      "Familiarity threat; it is sufficient to rotate the partner after seven years",
      "Advocacy threat; the firm may continue provided the client gives consent",
      "Self-review threat; the interest can be addressed by using a separate audit team",
    ],
    correct: 0,
    explanation:
      "A direct financial interest in an audit client is a self-interest threat, and for a partner on the engagement it is so significant that the interest must be eliminated or the individual removed — no lesser safeguard is adequate. It is not a familiarity, advocacy or self-review threat, and separate teams or client consent do not resolve a partner's direct shareholding.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AAA2-B-02",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "Merridge & Co performed a valuation of a material intangible asset for its audit client and that valuation is now recognised in the financial statements the firm must audit. Which threat is created?",
    options: [
      "Advocacy threat",
      "Self-review threat",
      "Intimidation threat",
      "Familiarity threat",
    ],
    correct: 1,
    explanation:
      "Auditing a figure the firm itself produced is a self-review threat: the firm may be reluctant to challenge its own valuation. It is not advocacy (promoting the client's position), intimidation (pressure or threats), or familiarity (close personal relationships); it is the classic self-review situation.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AAA2-B-03",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "Denholm Audit LLP has been asked by its audit client to act as promoter of a new share issue, actively marketing the client's shares to potential investors. Which threat is created?",
    options: [
      "Self-interest threat",
      "Familiarity threat",
      "Advocacy threat",
      "Self-review threat",
    ],
    correct: 2,
    explanation:
      "Promoting or marketing a client's shares means taking the client's side and championing its position, which is an advocacy threat and is generally incompatible with auditor objectivity. It is not primarily self-interest, familiarity or self-review; the defining feature is that the firm would be advocating for the client.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-B-04",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "A partner has served as the key audit partner on the audit of Ansley plc, a listed public interest entity, for eight consecutive years. Which threat arises and what is the specific rule?",
    options: [
      "Self-interest threat; no action is required if the client is satisfied",
      "Advocacy threat; the position is acceptable if the client gives consent",
      "Intimidation threat; the matter is resolved by adding a review safeguard",
      "Familiarity (long association) threat; for a PIE the key audit partner must rotate off after a maximum of seven years, with a cooling-off period of five years",
    ],
    correct: 3,
    explanation:
      "Long association creates a familiarity (and self-interest) threat. For a PIE the IESBA Code caps the key audit partner at seven cumulative years, followed by a five-year cooling-off period; eight years therefore breaches the rotation rule. The other options misclassify the threat and ignore the mandatory rotation requirement.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AAA2-B-05",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "The finance director of Corbrey Ltd tells the audit engagement partner that the firm will be dismissed unless it accepts an aggressive revenue recognition policy the partner considers inappropriate. Which threat is this?",
    options: [
      "Familiarity threat",
      "Intimidation threat",
      "Self-review threat",
      "Advocacy threat",
    ],
    correct: 1,
    explanation:
      "A threat of dismissal used to pressure the auditor into accepting an inappropriate treatment is an intimidation threat. It is not familiarity (closeness), self-review (auditing own work), or advocacy (promoting the client); the coercive pressure is the hallmark of intimidation.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AAA2-B-06",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "The total fees receivable from Oakworth plc, a listed public interest entity, have exceeded 15% of the audit firm's total fees for two consecutive years. What does the IESBA Code require?",
    options: [
      "No action, provided the client is happy with the service",
      "The firm must resign from the engagement immediately",
      "Disclose the position to those charged with governance and arrange an independent (pre- or post-issuance) review of the engagement, and consider whether continued dependence is acceptable",
      "Reduce the fee to zero to remove the dependence",
    ],
    correct: 2,
    explanation:
      "Where fees from a PIE exceed 15% of total firm fees for two consecutive years, the Code requires disclosure to those charged with governance and an independent review (a pre-issuance or post-issuance quality review), together with consideration of whether the relationship can continue. Immediate resignation is not mandated at that point, doing nothing ignores the self-interest threat, and charging nothing is not a real safeguard.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-B-07",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "A client offers to pay the audit fee as a percentage of the increase in reported profit for the year. Is a contingent fee acceptable for an audit engagement?",
    options: [
      "Yes, provided the client agrees to it in writing",
      "Yes, but only for non-listed clients",
      "Yes, if it is first approved by those charged with governance",
      "No — contingent fees for an audit engagement are prohibited because they create an unacceptable self-interest threat to objectivity",
    ],
    correct: 3,
    explanation:
      "Contingent fees for an audit are prohibited: linking the fee to the audit outcome creates an unacceptable self-interest threat to objectivity. Written agreement, restricting it to non-listed clients, or governance approval do not make an audit contingent fee acceptable.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-B-08",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "What is meant by 'lowballing' in the context of tendering for audit work?",
    options: [
      "Setting the audit fee so low that it may not cover the cost of performing a quality audit, in order to win the engagement",
      "Charging the client a fee that is contingent on the audit outcome",
      "Deliberately overstating fees in order to inflate the firm's revenue",
      "Billing a client for services that were never actually performed",
    ],
    correct: 0,
    explanation:
      "Lowballing is quoting an artificially low fee to win an engagement, with the risk that quality is compromised or the firm later pressures for other work. The other options describe contingent fees, revenue overstatement, and fraudulent billing respectively — none of which is lowballing.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AAA2-B-09",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "Which non-assurance service is prohibited when provided to a public interest entity audit client?",
    options: [
      "Preparing a factual tax compliance return where the amounts are not material and are reviewed and approved by management",
      "Attending the audit committee meeting to discuss the audit findings",
      "Designing and implementing the financial reporting IT system that generates the client's financial statements",
      "Performing the statutory audit of a subsidiary within the group",
    ],
    correct: 2,
    explanation:
      "Designing or implementing the IT system that produces the financial statements is prohibited for a PIE audit client because the firm would later be auditing the output of a system it built — an unacceptable self-review (and management) threat. Routine tax compliance reviewed by management, attending audit committee meetings, and auditing a subsidiary are not, of themselves, prohibited.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AAA2-B-10",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "Which statement about providing bookkeeping/accounting services to an audit client is correct?",
    options: [
      "Such services are always permitted for any audit client",
      "They are permitted for public interest entities provided safeguards are applied",
      "They are permitted for any client so long as the fee is small",
      "They are prohibited for public interest entities; for non-PIEs they may be permitted only where the work is routine or mechanical, management makes all judgements, and appropriate safeguards are applied",
    ],
    correct: 3,
    explanation:
      "Preparing the accounting records/financial statements is prohibited for PIE audit clients because of the self-review threat. For a non-PIE it may be acceptable only where the work is routine/mechanical, management retains responsibility for all judgements, and safeguards are used. The other statements overstate what is permitted.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-B-11",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "An advisory firm is asked to act for two clients that are competing to acquire the same target company. How should the firm respond?",
    options: [
      "A conflict of interest arises; the firm should identify it and may act for both only with the informed consent of each client and safeguards such as separate teams and information barriers",
      "There is no conflict because the two clients are separate legal entities",
      "The firm must accept both engagements without any disclosure to the clients",
      "The firm must always decline both engagements in every circumstance",
    ],
    correct: 0,
    explanation:
      "Acting for competing bidders creates a conflict of interest. The Code permits acting only where the firm can manage the conflict with safeguards (separate teams, information barriers, confidentiality) and obtains the informed consent of the affected parties. There plainly is a conflict, undisclosed acceptance is improper, and an absolute prohibition is not the required position where the conflict can be properly managed.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AAA2-B-12",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "In which circumstance may a professional accountant disclose confidential client information without the client's consent?",
    options: [
      "Whenever a competitor firm requests the information",
      "Where there is a legal or professional right or duty to disclose, for example to comply with legal proceedings or money-laundering and regulatory requirements",
      "Never — confidentiality is absolute and admits no exceptions",
      "Whenever disclosure would financially benefit the accountant",
    ],
    correct: 1,
    explanation:
      "Confidentiality yields where there is a legal or professional right or duty to disclose — for example a court order, statutory reporting such as money laundering, or defending against a claim. Disclosure to competitors or for the accountant's own gain is never justified, and confidentiality is not absolute; recognised exceptions exist.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-B-13",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "Which of the following is a legitimate means by which an audit firm may limit its professional liability?",
    options: [
      "Excluding all liability for negligence to any third party by means of a notice on the firm's website",
      "Refusing to sign the auditor's report until liability is waived",
      "Backdating the engagement letter to before the work began",
      "Agreeing a liability limitation (liability cap) with the client where permitted by law, provided it is fair and reasonable and, for a listed company, approved by shareholders",
    ],
    correct: 3,
    explanation:
      "A liability limitation agreement/cap is a recognised way to limit liability where law allows, subject to it being fair and reasonable and (for listed companies) approved by shareholders. A blanket website exclusion, withholding the report to extract a waiver, and backdating the engagement letter are all improper or ineffective.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AAA2-B-14",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "What is the primary purpose of an engagement letter?",
    options: [
      "To set out and confirm the terms of the engagement — its scope, the respective responsibilities of the auditor and management, and the reporting to be provided",
      "To guarantee that the auditor will issue an unmodified opinion",
      "To fix the audit fee for the next ten years",
      "To transfer all of the auditor's legal liability to the client",
    ],
    correct: 0,
    explanation:
      "The engagement letter records the agreed terms — scope, responsibilities, and the form of reporting — helping to manage expectations and reduce misunderstandings. It cannot guarantee a particular opinion, does not fix fees for a decade, and does not transfer the auditor's liability to the client.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AAA2-B-15",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "Under ISA 210, which of the following is a precondition for accepting an audit engagement?",
    options: [
      "The client must pay the entire fee in advance",
      "Management must use an acceptable financial reporting framework and agree to its responsibilities (the 'premise' on which the audit is conducted)",
      "The auditor must guarantee in advance that a clean opinion will be issued",
      "The previous auditor must consent to the change of appointment",
    ],
    correct: 1,
    explanation:
      "ISA 210 preconditions require an acceptable financial reporting framework and management's agreement to the premise (its responsibilities for the statements, internal control, and providing access/information). Advance payment, a guaranteed opinion, and the prior auditor's consent are not ISA 210 preconditions.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AAA2-B-16",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "Before accepting a new audit client, what should the firm assess as part of client screening?",
    options: [
      "Only whether the proposed fee is high enough to be profitable",
      "Only the geographical location of the client's head office",
      "The client's integrity, the firm's competence and resources, its independence, and any money-laundering red flags",
      "Whether the client is likely to recommend the firm to other businesses",
    ],
    correct: 2,
    explanation:
      "Acceptance procedures address client integrity, the firm's competence and available resources, independence and ethical threats, and money-laundering due diligence. Considering only fee profitability, only location, or the client's referral value ignores the substance of a proper acceptance decision.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-B-17",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "A prospective new audit client refuses to permit the incoming firm to contact the outgoing auditor for professional clearance. What should the incoming firm do?",
    options: [
      "Treat the refusal as a serious concern and, absent a satisfactory explanation, decline the appointment",
      "Contact the outgoing auditor secretly without the client's knowledge",
      "Accept the engagement immediately without any communication",
      "Report the client to the audit regulator for refusing consent",
    ],
    correct: 0,
    explanation:
      "A refusal to allow professional clearance is a warning sign; without a satisfactory explanation the incoming firm should normally decline. Contacting the outgoing auditor without consent would breach confidentiality, accepting with no inquiry ignores a red flag, and reporting the client to the regulator is not warranted merely because consent was refused.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AAA2-B-18",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "Which statement correctly reflects the position on advertising by professional accountancy firms?",
    options: [
      "Advertising by firms is entirely prohibited",
      "Advertising is permitted but must not be false, misleading or in bad taste, and must not make disparaging references to competitors",
      "Advertising may promise guaranteed tax savings to attract clients",
      "Advertising may make unverified comparisons with named competing firms",
    ],
    correct: 1,
    explanation:
      "Advertising is allowed provided it is honest, truthful, not misleading, in good taste, and does not disparage competitors. It is not banned outright, must not guarantee outcomes such as tax savings, and must not make unsubstantiated comparisons with named competitors.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-B-19",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "The prior year's audit fee from Palgrave Ltd remains unpaid as the firm is about to sign the current year's auditor's report. What is the position?",
    options: [
      "There is no ethical threat because the fee relates to a previous year",
      "It creates an advocacy threat requiring the firm to promote the client's interests",
      "It creates a self-interest threat similar to a loan; the firm should seek payment before issuing the report and consider whether it can continue to act",
      "It creates an intimidation threat that requires the firm to resign immediately",
    ],
    correct: 2,
    explanation:
      "Significant overdue fees are akin to the client owing the firm a loan, creating a self-interest threat to objectivity. The firm should generally obtain payment before issuing the report and evaluate whether it can continue. It is not free of threat, is not an advocacy threat, and immediate resignation is not the automatic response.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AAA2-B-20",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "A member of the audit team is offered expensive hospitality and a gift by the audit client. What is the appropriate position?",
    options: [
      "Any gift is acceptable so long as it is below a fixed monetary limit",
      "It is acceptable provided the team member discloses it to the client",
      "It is acceptable only where the client is not a listed company",
      "Gifts and hospitality should be declined unless they are trivial and inconsequential, because they create self-interest and familiarity threats",
    ],
    correct: 3,
    explanation:
      "Gifts and hospitality that are more than trivial and inconsequential create self-interest and familiarity threats and should be declined. There is no simple monetary safe-harbour, disclosing to the client does not remove the threat, and the principle applies regardless of whether the client is listed.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-B-21",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "A firm is asked by a company (audited by another firm) to give a second opinion on the appropriate accounting treatment of a transaction. How should it proceed?",
    options: [
      "It must refuse to give a second opinion in all cases",
      "It may provide the opinion but should seek the company's permission to consult the existing auditor to ensure it has all the relevant facts",
      "It should provide the opinion without any communication with the existing auditor",
      "It should report the existing auditor to the professional body",
    ],
    correct: 1,
    explanation:
      "Giving a second opinion creates a risk of an ill-informed conclusion; the firm should seek permission to communicate with the existing auditor to obtain full facts, and decline if permission is refused and it cannot otherwise be satisfied. An outright refusal is not required, giving the opinion with no inquiry is unsafe, and reporting the existing auditor is unwarranted.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AAA2-B-22",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "A senior audit manager has been part of the engagement team for a non-listed (non-PIE) audit client for nine years. What is the correct treatment of the resulting familiarity threat?",
    options: [
      "The manager must rotate off immediately because a mandatory seven-year rule applies to all staff on every audit",
      "No action is ever needed for non-PIE clients regardless of the length of association",
      "Evaluate the significance of the threat and apply safeguards such as rotating senior personnel or arranging an independent review; mandatory rotation is not imposed by rule for non-PIEs, but the threat must still be addressed",
      "The manager must resign from the firm to remove the threat",
    ],
    correct: 2,
    explanation:
      "Long association with a non-PIE creates a familiarity/self-interest threat that must be evaluated and addressed with safeguards (rotation of senior staff, independent review), even though the fixed rotation rules apply specifically to PIE key audit partners. It is wrong to claim a universal seven-year rule for all staff, wrong to say non-PIEs need no action, and resignation from the firm is not the remedy.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-B-23",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "An audit firm is asked to provide internal audit services to a public interest entity that it also audits externally. What is the position?",
    options: [
      "It is always permitted with no restriction",
      "It is permitted provided the client gives its consent",
      "It is permitted so long as the fee for the internal audit work is immaterial",
      "It is prohibited for a PIE where the internal audit services relate to internal controls over financial reporting or to amounts or disclosures material to the financial statements, because of the self-review threat",
    ],
    correct: 3,
    explanation:
      "Providing internal audit services to a PIE audit client is prohibited where the work relates to controls over financial reporting or to material amounts/disclosures, as the firm would review its own internal audit output. Client consent and an immaterial fee do not overcome the self-review threat in these circumstances.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AAA2-B-24",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "An audit firm is asked to help its public interest entity audit client recruit a new chief financial officer. What does the Code permit?",
    options: [
      "For a PIE, searching for or recommending candidates for a director or key management position that has significant influence over the accounting records or financial statements is prohibited; the firm may, in limited situations, only review a shortlist the client has itself prepared",
      "The firm may recruit and select the CFO on the client's behalf, for any client",
      "Recruiting for the role is permitted for any client provided the firm does not make the final hiring decision",
      "Recruitment services are prohibited for all clients, including even reviewing a job specification",
    ],
    correct: 0,
    explanation:
      "Recruiting for a director or key management role that could significantly influence the accounting records or financial statements of a PIE is prohibited, because a familiarity/self-interest threat would arise from auditing figures produced by someone the firm placed; only limited activities such as reviewing a client-prepared shortlist may be acceptable. Selecting the CFO, doing so for any client, and an absolute ban on all recruitment activity all misstate the rule.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AAA2-B-25",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "A member of the audit team accepts a personal loan from an audit client that is a bank. What is the correct position?",
    options: [
      "There is never any threat because banks routinely make loans",
      "It is acceptable provided the engagement partner gives approval",
      "It is acceptable only if the loan is made by the client bank in the ordinary course of business under normal lending terms and procedures; otherwise a self-interest threat arises that must be eliminated",
      "It requires the team member to resign from the firm",
    ],
    correct: 2,
    explanation:
      "A loan from a client that is a lending institution is acceptable only if made under normal commercial terms and procedures; a loan on preferential terms creates a self-interest threat that must be eliminated. The blanket 'no threat' view is wrong, partner approval does not cure preferential terms, and resignation from the firm is not the remedy.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-B-26",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "The spouse of the engagement partner has just been appointed finance director of an audit client. Which threat arises and what action is required?",
    options: [
      "Advocacy threat; the firm may continue if the client gives consent",
      "Self-review threat; the position is resolved by using a separate audit team",
      "Intimidation threat; documenting the relationship is a sufficient safeguard",
      "Self-interest and familiarity threat; the partner must be removed from the engagement, as a close family member holds a position able to influence the financial statements",
    ],
    correct: 3,
    explanation:
      "A close family member in a role with significant influence over the financial statements creates self-interest and familiarity threats so significant that the partner must be removed from the engagement. It is not an advocacy, self-review or intimidation threat, and consent, separate teams or documentation are not adequate safeguards for this situation.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-B-27",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "A firm derives 18% of its total fees from a single non-listed (non-PIE) client for two consecutive years. Which statement is correct?",
    options: [
      "The specific 15% safeguards — disclosure to those charged with governance and an independent review — are required for PIE clients; for a non-PIE the firm must still evaluate and address the self-interest/intimidation threat from fee dependence, but those particular mandatory safeguards are not triggered by the 15% figure",
      "The 15% rule and its mandatory safeguards apply identically to all clients, PIE or not",
      "There is no threat from fee dependence for any type of client",
      "Fee dependence above 15% for a non-PIE requires the firm to resign immediately",
    ],
    correct: 0,
    explanation:
      "The specific 15%/two-year mandatory safeguards (disclosure to TCWG and an independent review) apply to PIE audit clients. For a non-PIE the firm must still identify and address the self-interest and intimidation threats that fee dependence creates, but the fixed 15% mechanism is not automatically triggered. Claiming the rule is identical for all clients, that there is no threat, or that resignation is mandatory all misstate the position.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AAA2-B-28",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "The fundamental principle of integrity requires a professional accountant to be:",
    options: [
      "Technically up to date and competent in all areas of practice",
      "Straightforward and honest in all professional and business relationships",
      "Careful to keep all client information secret at all times",
      "Compliant with the letter of every applicable law and regulation",
    ],
    correct: 1,
    explanation:
      "Integrity means being straightforward and honest in all professional and business relationships. Being technically competent describes professional competence and due care, keeping information secret describes confidentiality, and complying with laws relates most closely to professional behaviour — none of which is the definition of integrity.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AAA2-B-29",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "An audit firm is asked to act as an expert witness supporting its audit client's position in litigation, where the amounts in dispute are material to the financial statements. What is the appropriate response?",
    options: [
      "An advocacy (and self-interest) threat arises that is likely too significant for an audit client where the amounts are material, so the firm should decline the assignment",
      "There is no threat because acting as an expert witness is an independent role",
      "The only threat is self-review, which can be managed by using a separate team",
      "It creates a familiarity threat that can be reduced with routine safeguards",
    ],
    correct: 0,
    explanation:
      "Supporting the client's position in litigation over material amounts is advocacy — the firm would be taking the client's side — and threatens objectivity to a degree that ordinarily requires the firm to decline for an audit client. Acting as an expert witness is not a neutral role here, the threat is not self-review, and it is more than a routine familiarity threat.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-B-30",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "Which statement about the duty of confidentiality is correct?",
    options: [
      "The duty ends as soon as the professional engagement is completed",
      "The duty of confidentiality continues even after the professional relationship with the client has ended",
      "Confidential information may be used freely to benefit a subsequent new client",
      "Confidentiality applies only to written information, not to information obtained verbally",
    ],
    correct: 1,
    explanation:
      "Confidentiality continues after the engagement or relationship ends; information acquired must not be disclosed or used improperly even for a new client. The duty does not lapse on completion, information cannot be exploited for another client's benefit, and it applies to all client information, whether written or oral.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-B-31",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "A firm proposes to give tax advice to a public interest entity audit client. In which situation is providing the tax advice prohibited?",
    options: [
      "In every situation, because all tax services are banned for audit clients",
      "Only where the client is unwilling to pay a separate fee for the advice",
      "Where the effectiveness of the tax advice depends on a particular accounting treatment or presentation in the financial statements, there is reasonable doubt about its appropriateness, and the effect on the statements would be material",
      "Only where the local tax authority has not pre-approved the arrangement",
    ],
    correct: 2,
    explanation:
      "Tax advice becomes prohibited for a PIE audit client where its effectiveness depends on a particular accounting treatment/presentation about which there is reasonable doubt and the effect on the financial statements would be material — a self-review and advocacy concern. Not all tax services are banned, the fee arrangement is not the test, and tax-authority pre-approval is irrelevant to the ethics position.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AAA2-B-32",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "A firm is asked to underwrite and promote the sale of shares in its audit client as part of a corporate finance assignment. Which threat is created?",
    options: [
      "Self-review threat, which can be managed by using a separate team",
      "Familiarity threat, which is resolved by rotating the engagement partner",
      "Intimidation threat, which is addressed by documenting the arrangement",
      "Advocacy threat; promoting or dealing in an audit client's shares is generally not permitted where the amounts are material",
    ],
    correct: 3,
    explanation:
      "Underwriting or promoting a client's shares means acting in the client's cause, an advocacy threat that is generally incompatible with independence for an audit client where material. It is not primarily a self-review, familiarity or intimidation threat, so the safeguards suggested in the other options do not fit.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-B-33",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "The fundamental principle of objectivity requires a professional accountant to:",
    options: [
      "Not allow bias, conflict of interest or the undue influence of others to override professional or business judgements",
      "Be honest and straightforward in all dealings",
      "Maintain professional knowledge and skill at the required level",
      "Refrain from disclosing client information to third parties",
    ],
    correct: 0,
    explanation:
      "Objectivity means not allowing bias, conflict of interest or undue influence to override professional judgement. Being honest describes integrity, maintaining knowledge and skill describes professional competence and due care, and non-disclosure describes confidentiality — so only the first option defines objectivity.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AAA2-B-34",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "An audit client asks the firm to second a member of staff to work temporarily in the client's finance function. What is the correct position?",
    options: [
      "Such a secondment is always permitted with no restriction",
      "Such a secondment is never permitted under any circumstances",
      "A secondment into a management or decision-making role creates self-review and management threats and is not acceptable; a short-term loan of staff who do not take management decisions may be acceptable with safeguards, where the client directs the work and retains responsibility",
      "It is permitted only where the firm agrees to waive the audit fee for the year",
    ],
    correct: 2,
    explanation:
      "A loan of staff is problematic where the individual would perform a management role or make decisions, creating self-review and management threats; a genuinely short-term, non-managerial secondment may be acceptable with safeguards and client direction and responsibility. The 'always permitted' and 'never permitted' positions are both wrong, and waiving the fee is not the relevant safeguard.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-B-35",
    paper: "AAA",
    area: "B",
    type: "mcq",
    stem: "A firm accepts an engagement that requires specialist expertise in a complex financial instrument that the firm does not possess and cannot readily obtain. Which fundamental principle is most directly threatened?",
    options: [
      "Confidentiality",
      "Professional competence and due care",
      "Integrity",
      "Professional behaviour",
    ],
    correct: 1,
    explanation:
      "Accepting work the firm is not competent to perform threatens the principle of professional competence and due care, which requires accepting only work the firm can carry out with appropriate skill. It is not principally a confidentiality, integrity or professional-behaviour issue, though poor work could ultimately damage the firm's reputation.",
    marks: 2,
    difficulty: "easy",
  },

  /* ═══════════ Area C — Quality management (25) ═══════════ */
  {
    id: "AAA2-C-01",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "To what does ISQM 1 apply?",
    options: [
      "A firm's system of quality management for audits and reviews of financial statements and other assurance and related services engagements",
      "The quality control of a single audit engagement only",
      "The internal controls operated by the audit client",
      "The audit of listed companies only",
    ],
    correct: 0,
    explanation:
      "ISQM 1 governs the firm-wide system of quality management covering audits, reviews and other assurance and related services engagements. It is not limited to a single engagement (that is ISA 220), it does not address the client's own controls, and it is not confined to listed-company audits.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AAA2-C-02",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "Which approach does ISQM 1 require a firm to take in operating its system of quality management?",
    options: [
      "A fixed checklist approach with identical policies imposed on every firm",
      "A risk-based approach in which the firm establishes quality objectives, identifies and assesses quality risks, and designs and implements responses",
      "A rules-based approach that mandates the same detailed procedures for all firms regardless of size",
      "A voluntary approach with no requirement to document the system",
    ],
    correct: 1,
    explanation:
      "ISQM 1 is built on a risk-based approach: set quality objectives, identify and assess quality risks, and design responses tailored to the firm's nature and circumstances. It is deliberately not a one-size-fits-all checklist or an identical rulebook for every firm, and the system must be documented, not voluntary.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-C-03",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "Which of the following is one of the components of a firm's system of quality management under ISQM 1?",
    options: [
      "Preparing the client's financial statements on its behalf",
      "Determining the audit opinion for each engagement",
      "Governance and leadership",
      "Deciding the composition of the client's board of directors",
    ],
    correct: 2,
    explanation:
      "Governance and leadership is one of the eight components of ISQM 1 (alongside the risk assessment process, ethics, acceptance and continuance, engagement performance, resources, information and communication, and monitoring and remediation). Preparing client statements, setting audit opinions, and choosing the client's board are not components of the firm's QM system.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-C-04",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "What does ISQM 2 deal with?",
    options: [
      "The firm's overall system of quality management",
      "Compliance with ethical requirements only",
      "The acceptance and continuance of client relationships",
      "Engagement quality reviews — the appointment and eligibility of the engagement quality reviewer and the performance of the review",
    ],
    correct: 3,
    explanation:
      "ISQM 2 addresses engagement quality reviews: the eligibility and appointment of the engagement quality reviewer and how the review is performed and documented. The firm-wide system is ISQM 1, ethics is only one component of ISQM 1, and acceptance and continuance is likewise an ISQM 1 component, not the subject of ISQM 2.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AAA2-C-05",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "When is an engagement quality review (EQR) required?",
    options: [
      "For every audit engagement the firm performs",
      "For audits of listed entities, and for any other engagement where the firm's risk assessment (or law or regulation) determines that an EQR is a necessary response to quality risks",
      "Only where the client specifically requests one",
      "Never for a private company under any circumstances",
    ],
    correct: 1,
    explanation:
      "An EQR is required for listed-entity audits and for other engagements the firm identifies (through its risk assessment) or that law/regulation specifies as requiring one. It is not mandatory for every engagement, it is not dependent on a client request, and it is not universally excluded for private companies where the firm's risk assessment calls for it.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AAA2-C-06",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "What is the role of the engagement quality reviewer under ISQM 2?",
    options: [
      "To prepare the client's financial statements for the engagement team",
      "To sign the auditor's report in place of the engagement partner",
      "To perform an objective evaluation of the significant judgements made and the conclusions reached by the engagement team, completed before the auditor's report is dated",
      "To re-perform the entire audit from planning to completion",
    ],
    correct: 2,
    explanation:
      "The engagement quality reviewer objectively evaluates the significant judgements and conclusions of the team, and this must be completed before the report is dated. The reviewer does not prepare the statements, does not replace the engagement partner as signatory, and does not re-perform the whole audit.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-C-07",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "Which statement about the eligibility of an engagement quality reviewer is correct?",
    options: [
      "The reviewer must be the engagement partner on the same engagement",
      "Anyone within the firm may act as reviewer regardless of their role on the engagement",
      "The reviewer must be a member of the engagement team so as to understand the client fully",
      "The reviewer must be objective and not a member of the engagement team, must have sufficient competence, authority and time, and a cooling-off period applies before a former engagement partner may act as reviewer",
    ],
    correct: 3,
    explanation:
      "The reviewer must be objective and independent of the engagement team, suitably competent, and have the authority and time to perform the review; a cooling-off period applies before a former engagement partner can serve as reviewer. The reviewer cannot be the engagement partner or a team member, and eligibility is not unrestricted.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-C-08",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "What does ISA 220 (Revised) deal with?",
    options: [
      "Quality management at the level of the individual audit engagement",
      "The firm-wide system of quality management",
      "The conduct of engagement quality reviews only",
      "Money laundering reporting obligations",
    ],
    correct: 0,
    explanation:
      "ISA 220 addresses quality management at the level of the individual audit engagement, including the engagement partner's responsibilities. The firm-wide system is ISQM 1, engagement quality reviews are ISQM 2, and money laundering is covered by separate regulation, not ISA 220.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AAA2-C-09",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "Under ISA 220, what is the position on the engagement partner's overall responsibility for quality?",
    options: [
      "The partner may fully delegate responsibility for quality to the audit manager",
      "The partner is responsible only for signing the auditor's report",
      "The partner remains responsible for managing and achieving quality on the engagement, including its direction, supervision and review, and must be sufficiently and appropriately involved throughout",
      "The partner is responsible for the firm's entire ISQM 1 system",
    ],
    correct: 2,
    explanation:
      "ISA 220 makes the engagement partner responsible for managing and achieving quality on the engagement, being sufficiently and appropriately involved and directing, supervising and reviewing the work. Overall responsibility cannot be fully delegated, it is not limited to signing the report, and the partner is not responsible for the whole firm-wide ISQM 1 system.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AAA2-C-10",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "What does the monitoring and remediation component of ISQM 1 involve?",
    options: [
      "It is an optional activity that firms may choose to omit",
      "It involves only the inspection of a sample of completed engagements",
      "It is performed by the audit client rather than the firm",
      "Ongoing and periodic monitoring of the whole quality management system, evaluating findings, identifying deficiencies, investigating their root causes, and taking remedial action",
    ],
    correct: 3,
    explanation:
      "Monitoring and remediation is a mandatory component covering the whole system: monitoring activities, evaluating findings, identifying deficiencies, investigating root causes, and remediating. It is not optional, it is broader than inspecting completed files alone, and it is performed by the firm, not the client.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-C-11",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "What is root cause analysis in the context of a firm's quality management system?",
    options: [
      "Investigating why a deficiency occurred — its underlying cause rather than just the symptom — so that effective remedial action can be taken",
      "Identifying which junior member of staff made the error so they can be blamed",
      "Simply recording the number of errors found during monitoring",
      "Deciding to ignore issues that appear to be one-off occurrences",
    ],
    correct: 0,
    explanation:
      "Root cause analysis seeks the underlying reason a deficiency arose so that remediation addresses the real cause, not just the symptom. It is not about blaming an individual, not merely a count of errors, and it deliberately does not dismiss issues as one-offs without understanding why they happened.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AAA2-C-12",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "What is a 'network firm'?",
    options: [
      "Any firm that the audit firm has ever contacted or corresponded with",
      "A firm belonging to a larger structure aimed at co-operation, that shares one or more of a common brand name, a common system of quality control, or significant professional resources",
      "Any accountancy firm operating in the same city as the audit firm",
      "A group company of the audit client",
    ],
    correct: 1,
    explanation:
      "A network firm belongs to a larger structure aimed at co-operation and sharing, for example, a common brand, quality control system, or significant professional resources. Mere contact, geographic proximity, or being a client group company does not make a firm a network firm.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-C-13",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "Why do network firm relationships matter when assessing an audit firm's independence?",
    options: [
      "They have no effect on the audit firm's independence",
      "Only the signing partner's personal independence is relevant, not the network's",
      "Networks are relevant only because they share fee income between member firms",
      "Independence requirements extend across the network, so a network firm's interests in, or relationships with, the audit client — for example providing prohibited services — can impair the audit firm's independence",
    ],
    correct: 3,
    explanation:
      "Independence must be considered across the whole network: a network firm holding a prohibited interest in, or providing a prohibited service to, the audit client can impair the independence of the audit firm itself. It is wrong to say networks are irrelevant, that only the signing partner matters, or that fee-sharing is the only relevant issue.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AAA2-C-14",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "Which of the following is an element of an effective system of quality management?",
    options: [
      "A culture set by leadership ('tone at the top') that demonstrates the firm's commitment to quality",
      "Maximising the number of clients accepted regardless of risk",
      "Minimising documentation in order to save time and cost",
      "Delegating responsibility for quality entirely to junior members of staff",
    ],
    correct: 0,
    explanation:
      "An effective system depends on leadership setting a culture committed to quality (the tone at the top). Accepting all clients regardless of risk, cutting documentation to save time, and pushing responsibility for quality onto juniors all undermine quality rather than support it.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-C-15",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "What is the purpose of the acceptance and continuance component within ISQM 1?",
    options: [
      "To maximise the firm's fee income by taking on as many engagements as possible",
      "To provide reasonable assurance that the firm only accepts or continues engagements where it can act ethically, is competent, has the resources, and has considered the integrity of the client",
      "To ensure the firm never resigns from an existing client",
      "To prepare the engagement letter and nothing further",
    ],
    correct: 1,
    explanation:
      "Acceptance and continuance exists so the firm takes on and retains only engagements it can perform ethically and competently, with adequate resources and after considering client integrity. It is not about maximising fees, does not prevent resignation where continuance is inappropriate, and is broader than preparing an engagement letter.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-C-16",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "The resources component of ISQM 1 addresses which of the following?",
    options: [
      "Only the human resources (audit staff) available to the firm",
      "Only the fee budget available for each engagement",
      "Human, technological and intellectual resources, and the appropriate use of service providers, needed to operate the system and perform engagements",
      "Only the firm's office premises and physical facilities",
    ],
    correct: 2,
    explanation:
      "The resources component covers human, technological and intellectual resources and the use of service providers. It is not limited to staff alone, to the fee budget, or to physical premises; all types of resource needed to operate the system and perform quality engagements are within scope.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AAA2-C-17",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "What does the information and communication component of ISQM 1 require?",
    options: [
      "The firm to obtain, generate and communicate quality-related information internally and externally, including with network firms and other relevant external parties",
      "The firm to advertise its services to prospective clients",
      "The firm to publish each audit opinion it issues",
      "The firm to keep all quality-related information secret within the engagement team",
    ],
    correct: 0,
    explanation:
      "Information and communication requires the firm to obtain, generate and share quality-related information both internally and, where relevant, externally (for example with network firms and service providers). It is not about advertising, publishing opinions, or restricting information within one team.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AAA2-C-18",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "Under ISQM 1, how is a 'deficiency' in the system of quality management identified?",
    options: [
      "It is any error, however small, found in an individual audit file",
      "It exists where a quality objective was not achieved, a quality risk was not identified or properly assessed, or a response was not designed or operating effectively, such that the system may fail to provide reasonable assurance the objectives are met",
      "It arises only when a client submits a formal complaint",
      "It arises only where an auditor's report is issued after the deadline",
    ],
    correct: 1,
    explanation:
      "A deficiency exists where an objective is not achieved, a risk is not identified/assessed, or a response is missing or not operating — alone or with others creating a risk that the system fails to provide reasonable assurance. A minor file error, a client complaint, or a late report is not, of itself, the ISQM 1 definition of a deficiency.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-C-19",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "How often does ISQM 1 require the firm to evaluate its system of quality management?",
    options: [
      "Once every five years",
      "Only when a significant problem comes to light",
      "At least annually — the individual with ultimate responsibility must evaluate the system and conclude whether it provides reasonable assurance that its objectives are being achieved",
      "Only when the firm is inspected by an external regulator",
    ],
    correct: 2,
    explanation:
      "ISQM 1 requires an evaluation of the system at least annually, with the individual assigned ultimate responsibility concluding whether the system provides reasonable assurance the objectives are achieved. A five-yearly review, an event-driven-only review, or reliance on external inspection would not meet the standard's requirement.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AAA2-C-20",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "Which statement about consultation on difficult or contentious matters is correct?",
    options: [
      "Consultation should be avoided because it slows the engagement down",
      "Consultation is only appropriate for junior members of the team",
      "Undertaking consultation removes the engagement partner's responsibility for the matter",
      "Appropriate consultation on difficult or contentious matters should take place, with the conclusions agreed and implemented; it supports quality but does not remove the engagement partner's overall responsibility",
    ],
    correct: 3,
    explanation:
      "Consultation on difficult or contentious matters is part of engagement performance: the firm should facilitate it, agree and implement conclusions, and document them — but the engagement partner retains overall responsibility. Avoiding consultation, confining it to juniors, or treating it as removing the partner's responsibility are all incorrect.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AAA2-C-21",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "A difference of opinion arises within the engagement team about a significant judgement. How should it be handled?",
    options: [
      "The most senior person present should simply overrule the others to save time",
      "The disagreement should be ignored so the audit can be completed on schedule",
      "The existence of the disagreement means the auditor's report can never be issued",
      "It should be dealt with and resolved in accordance with the firm's policies and procedures, and the auditor's report should not be dated until the matter is resolved",
    ],
    correct: 3,
    explanation:
      "Differences of opinion must be addressed and resolved following the firm's policies, and the report must not be dated until resolution. Overruling to save time, ignoring the disagreement, or treating it as a permanent bar to issuing any report are all inappropriate responses.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-C-22",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "How does ISQM 1 apply to a small firm with a less complex practice?",
    options: [
      "Small firms are exempt from ISQM 1 altogether",
      "ISQM 1 is scalable: a less complex firm may need fewer and less formal policies and procedures, but it must still meet all of the standard's objectives and follow the risk-based approach",
      "Small firms must apply exactly the same detailed procedures as the largest global networks",
      "Small firms need only comply with ISA 220 and can disregard ISQM 1",
    ],
    correct: 1,
    explanation:
      "ISQM 1 is scalable to the firm's nature and circumstances: a smaller, less complex firm may use fewer and less formal policies, but it must still achieve all the objectives via the risk-based approach. There is no exemption, no requirement to copy the largest networks' procedures, and ISA 220 does not replace ISQM 1.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AAA2-C-23",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "What does the governance and leadership component of ISQM 1 require regarding responsibility for the system?",
    options: [
      "Responsibility for quality rests with the audit client",
      "No individual needs to be assigned responsibility, as quality is a collective matter",
      "Ultimate responsibility and accountability for the system must be assigned to a specific individual (for example the CEO or managing partner), and operational responsibility must also be assigned",
      "Responsibility rests solely with the junior auditors performing fieldwork",
    ],
    correct: 2,
    explanation:
      "Governance and leadership requires assigning ultimate responsibility and accountability for the system to a named individual, with operational responsibility also assigned to appropriate people. Responsibility does not rest with the client, cannot be left unassigned, and does not sit with junior fieldwork staff.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AAA2-C-24",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "What is the overall objective of a firm's system of quality management under ISQM 1?",
    options: [
      "To provide the firm with reasonable assurance that it and its personnel fulfil their responsibilities in accordance with professional standards and legal and regulatory requirements, and that engagement reports issued are appropriate in the circumstances",
      "To guarantee that no audit performed by the firm will ever fail",
      "To maximise the firm's profitability across all engagements",
      "To remove the need for any quality procedures at the individual engagement level",
    ],
    correct: 0,
    explanation:
      "The objective of ISQM 1 is reasonable assurance that the firm and its people meet their responsibilities under standards and law and that reports issued are appropriate. It does not guarantee that no audit fails (reasonable, not absolute, assurance), it is not about maximising profit, and it complements rather than replaces engagement-level procedures (ISA 220).",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AAA2-C-25",
    paper: "AAA",
    area: "C",
    type: "mcq",
    stem: "Following root cause analysis, a firm concludes that a monitoring finding reflects a systemic deficiency in its quality management system. What does ISQM 1 require next?",
    options: [
      "No action is needed if only one engagement appears to have been affected",
      "The firm should conceal the deficiency to protect its reputation",
      "The firm need only retrain the individual who was involved in the affected engagement",
      "The firm must design and implement remedial actions that respond to the identified root cause, and then evaluate whether those actions have been effective; remediation may need to address the whole system, not just a single engagement",
    ],
    correct: 3,
    explanation:
      "Where a deficiency is systemic, the firm must design and implement remedial action addressing the root cause and evaluate its effectiveness, potentially across the whole system rather than one engagement. Doing nothing because only one file was affected, concealing the issue, or merely retraining one individual would fail to address a systemic root cause.",
    marks: 2,
    difficulty: "hard",
  },
]
