import type { AccaQuestion } from "@/lib/acca-content"

/* FM bank wave 4 — 70 verified originals (2026-07-10).
 * Blueprint: A8 B18 C15 D17 E12; difficulty 20/32/18; every distractor is a
 * nameable student error. All computations re-solved from the stem before
 * inclusion. Merged into QUESTIONS in acca-content.ts.
 */

export const FM_WAVE2: AccaQuestion[] = [
  /* ───────────── Area A — Financial management function (8) ───────────── */
  {
    id: "FM2-A-01",
    paper: "FM",
    area: "A",
    type: "mcq",
    stem: "Which measure most DIRECTLY reflects whether a listed company has achieved its objective of maximising shareholder wealth over a period?",
    options: [
      "Growth in profit before tax",
      "Total shareholder return (dividends received plus share price growth)",
      "Growth in total revenue",
      "Growth in the book value of net assets",
    ],
    correct: 1,
    explanation:
      "Shareholder wealth is delivered as dividends plus capital gains, so total shareholder return measures it directly. Accounting profit, revenue and book net assets are internal accounting measures — they ignore the timing of cash flows, risk and the market's valuation, so growth in any of them can occur while shareholder wealth falls.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM2-A-02",
    paper: "FM",
    area: "A",
    type: "mcq",
    stem: "Which of the following remuneration arrangements is MOST likely to reduce the agency problem between the directors and the shareholders of a listed company?",
    options: [
      "A high fixed salary with no performance element",
      "An annual cash bonus linked to current-year accounting profit",
      "Share options that vest only after several years of service",
      "Allowing the directors to set their own performance targets",
    ],
    correct: 2,
    explanation:
      "Share options with a multi-year vesting period tie the directors' personal wealth to the long-term share price, aligning them with shareholders. A fixed salary gives no incentive to perform (a common wrong answer — removing incentives does not remove the agency conflict), a profit-linked annual bonus encourages short-termism and profit manipulation, and self-set targets worsen the conflict.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM2-A-03",
    paper: "FM",
    area: "A",
    type: "mcq",
    stem: "A public hospital is assessed on a value-for-money basis using the 'three Es'. Which of the following correctly describes EFFICIENCY?",
    options: [
      "Acquiring resources of appropriate quality at the lowest cost",
      "Achieving the organisation's stated objectives",
      "Spending no more than the budget allocated for the year",
      "The quantity of output achieved relative to the resources consumed",
    ],
    correct: 3,
    explanation:
      "Efficiency is the relationship between outputs and the inputs used to produce them. Acquiring inputs cheaply is ECONOMY, achieving objectives is EFFECTIVENESS — students routinely swap these three — and merely staying within budget is none of the three Es.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM2-A-04",
    paper: "FM",
    area: "A",
    type: "mcq",
    stem: "Which of the following is a benefit of financial intermediation provided by a bank to small savers?",
    options: [
      "Maturity transformation: many short-term deposits are pooled to fund long-term lending, while each saver keeps access to their cash",
      "Guaranteeing that the businesses the bank lends to cannot default",
      "Removing all investment risk from the saver",
      "Ensuring savers always earn more than the rate of inflation",
    ],
    correct: 0,
    explanation:
      "Intermediaries offer maturity transformation, aggregation of small deposits and risk pooling (diversification across many borrowers). Risk pooling reduces — it does not eliminate — risk, and no intermediary can guarantee borrowers won't default or that returns will beat inflation; each of those distractors overstates pooling into a guarantee.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-A-05",
    paper: "FM",
    area: "A",
    type: "mcq",
    stem: "Which of the following is an instrument of MONETARY policy rather than fiscal policy?",
    options: [
      "An increase in government infrastructure spending",
      "A change in the central bank's policy interest rate",
      "A cut in the rate of corporation tax",
      "An increase in the rate of sales tax",
    ],
    correct: 1,
    explanation:
      "Monetary policy works through interest rates, the money supply and exchange rates, set by the central bank. Government spending and taxation (corporation tax, sales tax) are fiscal policy — the classic error is labelling any tax change 'monetary' because it affects money in people's pockets.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM2-A-06",
    paper: "FM",
    area: "A",
    type: "mcq",
    stem: "A company's share price was $5.00 at the start of the year and $5.40 at the end. A dividend of $0.20 per share was paid during the year. What was the total shareholder return for the year?",
    options: ["8.0%", "4.0%", "12.0%", "11.1%"],
    correct: 2,
    explanation:
      "Total shareholder return = (capital gain + dividend) ÷ opening price = (0.40 + 0.20) ÷ 5.00 = 12.0%. 8.0% is the capital gain alone, 4.0% is the dividend yield alone, and 11.1% comes from dividing by the CLOSING price of $5.40 — the return must be measured on the price at the start of the period.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-A-07",
    paper: "FM",
    area: "A",
    type: "mcq",
    stem: "A company has a stated objective of growing earnings per share by at least 8% per year on average. EPS three years ago was 50.0c and the latest EPS is 66.55c. What is the average annual compound growth rate achieved?",
    options: ["10.0%", "11.0%", "33.1%", "7.4%"],
    correct: 0,
    explanation:
      "Growth over three years is 66.55 ÷ 50.0 = 1.331, and 1.331^(1/3) = 1.10, so compound growth is 10.0% per year — the target was met. 11.0% divides the total 33.1% growth by 3 (arithmetic, not compound), 33.1% is the un-annualised total, and 7.4% takes the fourth root because there are four EPS figures — but four observations span only THREE growth periods.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-A-08",
    paper: "FM",
    area: "A",
    type: "mcq",
    stem: "A listed company announces a major expansion financed entirely by new borrowing. Which stakeholder conflict does this decision raise MOST directly?",
    options: [
      "Customers versus suppliers, because expansion changes product prices",
      "Employees versus the government, because more staff will be hired",
      "Directors versus auditors, because gearing affects the audit opinion",
      "Shareholders versus existing lenders, because higher gearing increases the default risk borne by debt already in issue",
    ],
    correct: 3,
    explanation:
      "Issuing substantial new debt raises financial risk for EXISTING lenders (their claims become riskier without compensation) while shareholders capture the upside — a direct wealth-transfer conflict, which is why loan agreements contain restrictive covenants. The other pairings are not directly created by a gearing decision.",
    marks: 2,
    difficulty: "hard",
  },

  /* ───────────── Area B — Investment appraisal (18) ───────────── */
  {
    id: "FM2-B-01",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "A company is appraising a new product using NPV. Which of the following should be INCLUDED in the project cash flows?",
    options: [
      "Straight-line depreciation on the new machine",
      "The $30,000 market research already commissioned and paid for",
      "Lost contribution from an existing product whose sales the new product will cannibalise",
      "An apportionment of existing head-office overheads",
    ],
    correct: 2,
    explanation:
      "Relevant cash flows are future, incremental cash flows. Lost contribution on an existing product is an opportunity cost caused by the decision, so it is included. Depreciation is not a cash flow, market research already paid is a sunk cost, and apportioned existing overheads do not change in total because of the project.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM2-B-02",
    paper: "FM",
    area: "B",
    type: "number",
    stem: "A project requires an investment of $60,000 and generates net cash inflows of $20,000 in year 1, $25,000 in year 2 and $30,000 in year 3. Assuming cash flows accrue evenly during the year, what is the payback period, in years?",
    numericAnswer: 2.5,
    unit: "years",
    tolerance: 0.05,
    explanation:
      "Cumulative inflows: $45,000 after two years, leaving $15,000 of the $60,000 to recover. Year 3 brings $30,000, so payback = 2 + 15,000 ÷ 30,000 = 2.5 years. The trap is averaging the inflows (60,000 ÷ 25,000 = 2.4 years) — with uneven flows you must work cumulatively.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM2-B-03",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "A project costs $50,000 and returns $22,000 per year for three years. The cost of capital is 10% (discount factors: year 1 = 0.909, year 2 = 0.826, year 3 = 0.751). Assuming cash flows accrue evenly, what is the DISCOUNTED payback period?",
    options: ["2.3 years", "2.7 years", "3.0 years", "2.5 years"],
    correct: 1,
    explanation:
      "Discounted inflows: 19,998 + 18,172 = 38,170 after two years, leaving 11,830 to recover from year 3's PV of 16,522, so discounted payback = 2 + 11,830/16,522 ≈ 2.7 years. 2.3 years is the SIMPLE payback (50,000/22,000) — forgetting to discount; 3.0 years wrongly rounds up to a full year despite the even-accrual assumption; 2.5 years has no basis in the figures.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-B-04",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "A machine costs $200,000 and will be sold for $20,000 after four years. Total net cash inflows over the four years are $320,000. Using average annual accounting profit and AVERAGE investment, what is the project's ROCE (ARR)?",
    options: ["31.8%", "17.5%", "38.9%", "72.7%"],
    correct: 0,
    explanation:
      "Total depreciation = 200,000 − 20,000 = 180,000, so total profit = 320,000 − 180,000 = 140,000, i.e. 35,000 per year. Average investment = (200,000 + 20,000) ÷ 2 = 110,000. ROCE = 35,000 ÷ 110,000 = 31.8%. 17.5% uses the INITIAL investment; 38.9% wrongly averages (cost − scrap) ÷ 2 = 90,000, forgetting scrap is ADDED in the average; 72.7% uses average cash inflow of 80,000 instead of profit.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-B-05",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "A company's nominal (money) cost of capital is 12.35% and general inflation is expected to be 5% per year. Using the Fisher relationship, what is the real cost of capital?",
    options: ["7.35%", "17.35%", "17.97%", "7.00%"],
    correct: 3,
    explanation:
      "Fisher: (1 + nominal) = (1 + real)(1 + inflation), so real = 1.1235 ÷ 1.05 − 1 = 7.00%. 7.35% simply subtracts the inflation rate (the most common error), 17.35% adds it, and 17.97% multiplies 1.1235 × 1.05 instead of dividing. Real cash flows (current-price terms) must be discounted at this 7% real rate.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-B-06",
    paper: "FM",
    area: "B",
    type: "number",
    stem: "A machine costing $100,000 attracts 25% reducing-balance tax-allowable depreciation. The tax rate is 20%, payable in the same year as the profits it relates to. What is the tax saving from capital allowances in YEAR 2, in $?",
    numericAnswer: 3750,
    unit: "$",
    tolerance: 1,
    explanation:
      "Year 1 allowance = 25% × 100,000 = 25,000, leaving a written-down value of 75,000. Year 2 allowance = 25% × 75,000 = 18,750, so the year 2 tax saving = 18,750 × 20% = $3,750. The classic error is taking 25% of the ORIGINAL cost every year ($5,000 saving) — reducing balance applies the rate to the written-down value.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-B-07",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "Sales of a project are $200,000 per year in CURRENT price terms and will inflate at 4% per year. What figure should appear as year 2 sales revenue in a nominal (money terms) NPV evaluation?",
    options: ["$208,000", "$216,320", "$216,000", "$200,000"],
    correct: 1,
    explanation:
      "Nominal year 2 sales = 200,000 × 1.04² = $216,320. $208,000 applies only ONE year of inflation (a year-numbering slip), $216,000 uses simple interest (4% × 2 = 8%) instead of compounding, and $200,000 leaves the flows in real terms — which would only be correct if you then discounted at the REAL rate.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM2-B-08",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "An analyst builds an NPV model in which cash flows are inflated at their specific inflation rates, but discounts them at the company's REAL cost of capital. What is the effect on the calculated NPV?",
    options: [
      "The NPV is overstated, because inflation is included in the cash flows but excluded from the discount rate",
      "The NPV is understated, because the real rate is too high for money cash flows",
      "The NPV is correct, because the Fisher effect makes the two approaches equivalent",
      "The NPV equals zero, because inflation cancels out",
    ],
    correct: 0,
    explanation:
      "Consistency is the rule: nominal (inflated) flows must be discounted at the NOMINAL rate; real flows at the real rate. Discounting inflated flows at the lower real rate under-discounts them, overstating NPV. The Fisher equivalence (option C) only holds when each approach is applied consistently — mixing them is exactly what breaks it.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM2-B-09",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "In current price terms a project earns sales of $100,000 and cash costs of $40,000 in year 1. Sales inflate at 5% per year and costs at 3% per year. Tax is 20%, payable in the year the flow arises. What is the year 1 NOMINAL after-tax cash flow?",
    options: ["$63,800", "$48,000", "$51,040", "$50,400"],
    correct: 2,
    explanation:
      "Inflate each flow at its OWN rate: sales 100,000 × 1.05 = 105,000; costs 40,000 × 1.03 = 41,200; net 63,800; after tax 63,800 × 0.80 = $51,040. $63,800 forgets tax, $48,000 forgets inflation entirely (60,000 × 0.8), and $50,400 inflates the costs at the general 5% rate instead of their specific 3% rate.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM2-B-10",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "A project has an NPV of +$8,000 at a discount rate of 10% and an NPV of −$4,000 at 20%. Using linear interpolation, what is the best estimate of the project's IRR?",
    options: ["13.3%", "15.0%", "26.7%", "16.7%"],
    correct: 3,
    explanation:
      "IRR ≈ 10% + [8,000 ÷ (8,000 + 4,000)] × (20% − 10%) = 10% + 6.7% = 16.7%. 13.3% puts the NEGATIVE NPV in the numerator, 15.0% just takes the midpoint of the two rates ignoring the NPV sizes, and 26.7% adds the interpolated fraction to 20% instead of to the lower rate.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-B-11",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "Two mutually exclusive projects are appraised at a 10% cost of capital. Project P: NPV $50,000, IRR 18%. Project Q: NPV $64,000, IRR 15%. Which project should be chosen, and why?",
    options: [
      "P, because its IRR is higher",
      "Q, because a higher NPV adds more to shareholder wealth",
      "P, because its IRR exceeds the cost of capital by the larger margin",
      "Either, because both have positive NPVs and IRRs above 10%",
    ],
    correct: 1,
    explanation:
      "For mutually exclusive projects the NPV rule decides: NPV measures the absolute addition to shareholder wealth, so Q ($64,000) is chosen. IRR is a percentage that ignores project scale and can conflict with NPV — following the higher IRR (options A and C) is the classic error. 'Either' ignores that only one can be taken.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-B-12",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "A machine costs $24,000, lasts three years and has running costs of $6,000 per year. The cost of capital is 10% and the 3-year annuity factor is 2.487. What is the machine's equivalent annual cost (EAC)?",
    options: ["$12,974", "$9,650", "$15,650", "$14,000"],
    correct: 2,
    explanation:
      "PV of costs = 24,000 + 6,000 × 2.487 = 38,922. EAC = 38,922 ÷ 2.487 = $15,650. $12,974 divides the PV by the 3-year LIFE instead of the annuity factor (ignoring the time value of money), $14,000 spreads the capital cost straight-line (24,000 ÷ 3 + 6,000), and $9,650 annualises the capital cost but forgets the running costs.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM2-B-13",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "Machine X costs $20,000, lasts two years, running costs $4,000/yr. Machine Y costs $30,000, lasts three years, running costs $3,000/yr. Cost of capital 10% (annuity factors: 2 years = 1.736, 3 years = 2.487). Which machine should be chosen for continuous replacement?",
    options: [
      "Y, because its equivalent annual cost of about $15,063 is below X's $15,521",
      "X, because its PV of costs of $26,944 is below Y's $37,461",
      "X, because it has the lower capital cost",
      "Y, because its costs are spread over more years, so each year bears less",
    ],
    correct: 0,
    explanation:
      "X: PV = 20,000 + 4,000 × 1.736 = 26,944; EAC = 26,944 ÷ 1.736 ≈ $15,521. Y: PV = 30,000 + 3,000 × 2.487 = 37,461; EAC = 37,461 ÷ 2.487 ≈ $15,063. Y wins on EAC. Comparing raw PVs (option B) is the classic unequal-lives error — a shorter life always looks cheaper in PV terms. Option D reaches the right machine by invalid reasoning: spreading over more years is not the test, the EAC is.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-B-14",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "Capital at time 0 is limited to $100,000. Three divisible projects (constant returns to scale): A costs $40,000, NPV $12,000; B costs $60,000, NPV $15,000; C costs $50,000, NPV $14,000. What is the maximum total NPV achievable?",
    options: ["$26,000", "$41,000", "$26,200", "$28,500"],
    correct: 3,
    explanation:
      "Rank by profitability index (NPV ÷ outlay): A 0.30, C 0.28, B 0.25. Take A ($40k, NPV 12,000) and C ($50k, NPV 14,000), then invest the remaining $10k in one-sixth of B for NPV 2,500 — total $28,500. $26,200 ranks by ABSOLUTE NPV (B first), $26,000 refuses fractional projects despite divisibility, and $41,000 takes all three, ignoring the capital limit.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM2-B-15",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "SOFT capital rationing arises when:",
    options: [
      "Banks and investors refuse to provide further funds to the company",
      "Management imposes an internal limit on the capital expenditure budget",
      "Projects cannot be undertaken in fractions",
      "The government restricts lending across the economy",
    ],
    correct: 1,
    explanation:
      "Soft rationing is a self-imposed, internal limit (e.g. to control growth or avoid diluting control); hard rationing is imposed by the EXTERNAL capital market — options A and D describe hard rationing, and swapping the two labels is the standard error. Indivisibility (option C) is a separate issue affecting how rationing problems are solved, not a cause of rationing.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM2-B-16",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "In a lease-versus-buy evaluation, the cash flows of the two financing methods should be discounted at:",
    options: [
      "The company's weighted average cost of capital",
      "The cost of equity",
      "The after-tax cost of borrowing",
      "The risk-free rate of return",
    ],
    correct: 2,
    explanation:
      "Lease vs buy is a FINANCING decision between two low-risk debt-like alternatives, so the comparator rate is the after-tax cost of borrowing (interest is tax-deductible). Using the WACC or cost of equity confuses the financing decision with the separate INVESTMENT decision, which is appraised first at a rate reflecting project risk.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-B-17",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "A project has an NPV of $15,000. The PV of sales revenue is $250,000, the PV of variable costs is $150,000 and the initial investment is $85,000. What is the sensitivity of the decision to the SELLING PRICE?",
    options: ["6.0%", "15.0%", "10.0%", "17.6%"],
    correct: 0,
    explanation:
      "Sensitivity = NPV ÷ PV of the flow under test = 15,000 ÷ 250,000 = 6.0%: selling prices only need to fall 6% (with volumes unchanged) to wipe out the NPV. 15.0% wrongly divides by the PV of CONTRIBUTION (100,000) — that is the sensitivity to volume, not price; 10.0% divides by variable costs; 17.6% divides by the initial investment.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-B-18",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "Which of the following is a LIMITATION of sensitivity analysis in project appraisal?",
    options: [
      "It cannot be applied to NPV calculations",
      "It requires a full probability distribution for every input variable",
      "It always understates the risk of a project",
      "It changes one variable at a time and says nothing about how LIKELY each change is",
    ],
    correct: 3,
    explanation:
      "Sensitivity analysis flexes each variable in isolation, ignoring interdependence between variables, and attaches no probabilities to the changes — so it identifies critical variables but does not measure risk. Requiring probability distributions describes SIMULATION, not sensitivity analysis; and it applies naturally to NPV.",
    marks: 2,
    difficulty: "easy",
  },

  /* ───────────── Area C — Working capital management (15) ───────────── */
  {
    id: "FM2-C-01",
    paper: "FM",
    area: "C",
    type: "mcq",
    stem: "Annual credit sales are $730,000 and cost of sales (all on credit) is $365,000. Inventory is $60,000, trade receivables $90,000 and trade payables $40,000. What is the cash operating cycle (365-day year)?",
    options: ["145 days", "65 days", "55 days", "110 days"],
    correct: 1,
    explanation:
      "Inventory days = 60,000/365,000 × 365 = 60; receivables days = 90,000/730,000 × 365 = 45; payables days = 40,000/365,000 × 365 = 40. Cycle = 60 + 45 − 40 = 65 days. 145 ADDS payables days instead of subtracting; 55 muddles the signs (60 − 45 + 40); 110 computes receivables days on cost of sales instead of sales (giving 90 days).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-C-02",
    paper: "FM",
    area: "C",
    type: "number",
    stem: "A company has annual credit sales of $1,095,000 and trade receivables of $120,000. Using a 365-day year, what is the receivables collection period, in days?",
    numericAnswer: 40,
    unit: "days",
    tolerance: 0.5,
    explanation:
      "Receivables days = receivables ÷ credit sales × 365 = 120,000 ÷ 1,095,000 × 365 = 40 days. Remember to use CREDIT sales as the denominator — using cost of sales (a common slip carried over from the inventory-days formula) would distort the answer.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM2-C-03",
    paper: "FM",
    area: "C",
    type: "mcq",
    stem: "Customers currently pay in 60 days. A 2% discount is offered for payment within 10 days. What is the annual equivalent (compound) cost to the company of offering the discount?",
    options: ["2.0%", "14.6%", "15.9%", "13.1%"],
    correct: 2,
    explanation:
      "The company gives up 2% of the invoice to receive 98% of it 50 days early, so the cost per period is 2/98 = 2.04%, compounded over 365/50 = 7.3 periods: (1 + 2/98)^7.3 − 1 ≈ 15.9%. 14.6% annualises SIMPLE-interest style (2% × 365/50), 13.1% compounds over the full 60 days instead of the 50 days actually saved, and 2.0% is not annualised at all. Compare 15.9% with the overdraft rate to decide.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM2-C-04",
    paper: "FM",
    area: "C",
    type: "mcq",
    stem: "Annual credit sales are $3,650,000 and receivables days are 60. A factor (non-recourse services excluded) would cut receivables days to 45 for a fee of 1% of sales, and save $20,000 of administration costs. The overdraft rate is 8%. What is the net annual result?",
    options: [
      "A net cost of $4,500, so reject the factor",
      "A net cost of $24,500, so reject the factor",
      "A net cost of $16,500, so reject the factor",
      "A net benefit of $31,500, so appoint the factor",
    ],
    correct: 0,
    explanation:
      "Receivables fall from 3,650,000 × 60/365 = 600,000 to 45/365 × 3,650,000 = 450,000, a $150,000 reduction saving 150,000 × 8% = $12,000 of interest. Fee = 1% × 3,650,000 = $36,500. Net = 36,500 − 20,000 − 12,000 = $4,500 net cost — reject. $24,500 forgets the admin savings, $16,500 forgets the interest saving, and $31,500 wrongly computes the interest saving on the ENTIRE old receivables balance rather than the reduction.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM2-C-05",
    paper: "FM",
    area: "C",
    type: "number",
    stem: "Annual demand is 40,000 units, the cost of placing an order is $25 and the cost of holding one unit for a year is $0.50. Using the EOQ model, what is the economic order quantity, in units?",
    numericAnswer: 2000,
    unit: "units",
    tolerance: 1,
    explanation:
      "EOQ = √(2 × Co × D ÷ Ch) = √(2 × 25 × 40,000 ÷ 0.50) = √4,000,000 = 2,000 units. Watch the two classic slips: forgetting the 2 in the numerator, and putting the HOLDING cost in the numerator with the ORDER cost in the denominator.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-C-06",
    paper: "FM",
    area: "C",
    type: "mcq",
    stem: "Demand is 20,000 units/yr, ordering cost $25/order, holding cost $4/unit/yr, purchase price $10. The EOQ is 500 units. A supplier offers a 1% discount on orders of 1,000 units or more (holding cost unchanged). What is the net annual effect of ordering 1,000 units instead of the EOQ?",
    options: [
      "A net cost increase of $500",
      "A net saving of $2,000",
      "A net saving of $2,500",
      "A net saving of $1,500",
    ],
    correct: 3,
    explanation:
      "At EOQ 500: ordering 40 × 25 = 1,000; holding 250 × 4 = 1,000. At 1,000 units: ordering 20 × 25 = 500 (saves 500); holding 500 × 4 = 2,000 (costs 1,000 more); discount saves 1% × 200,000 = 2,000. Net saving = 2,000 + 500 − 1,000 = $1,500 — take the discount. $2,000 counts the discount only; $2,500 ignores the rise in holding cost; a $500 cost increase ignores the discount itself.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM2-C-07",
    paper: "FM",
    area: "C",
    type: "mcq",
    stem: "Under the Miller-Orr cash management model, a company has set a lower limit of $20,000 and calculated a spread of $30,000. To what level should the cash balance be RETURNED when it hits a limit?",
    options: ["$35,000", "$30,000", "$40,000", "$10,000"],
    correct: 1,
    explanation:
      "Return point = lower limit + spread ÷ 3 = 20,000 + 10,000 = $30,000 (the upper limit is 20,000 + 30,000 = $50,000). $35,000 uses the midpoint (lower + spread/2) — Miller-Orr deliberately sits the return point in the LOWER third because holding cash has an opportunity cost; $40,000 adds two-thirds of the spread; $10,000 is the spread ÷ 3 alone, forgetting the lower limit.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-C-08",
    paper: "FM",
    area: "C",
    type: "number",
    stem: "A company needs $2,000,000 of cash per year, drawn evenly from short-term investments earning 4% per year. Each sale of investments costs $25. Using the Baumol model, what is the optimal amount to transfer each time, in $?",
    numericAnswer: 50000,
    unit: "$",
    tolerance: 10,
    explanation:
      "Baumol mirrors the EOQ: Q = √(2 × 25 × 2,000,000 ÷ 0.04) = √2,500,000,000 = $50,000. The interest rate is the 'holding cost' of idle cash — the common error is using 4 instead of 0.04, which understates Q by a factor of 10.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-C-09",
    paper: "FM",
    area: "C",
    type: "mcq",
    stem: "Which of the following describes an AGGRESSIVE working capital financing policy?",
    options: [
      "Short-term funds finance all fluctuating current assets and part of the permanent current assets",
      "Long-term funds finance all current assets, including seasonal peaks",
      "The maturity of the finance is matched to the life of each asset",
      "Large buffer holdings of cash and inventory are maintained",
    ],
    correct: 0,
    explanation:
      "An aggressive policy pushes cheap but risky short-term finance below the fluctuating layer into PERMANENT current assets, boosting profitability at the cost of refinancing risk. Option B is the conservative policy, option C is matching, and option D describes a conservative INVESTMENT (asset level) policy rather than a financing policy — a frequently blurred distinction.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM2-C-10",
    paper: "FM",
    area: "C",
    type: "mcq",
    stem: "Under the matching (maturity-matching) approach to financing working capital:",
    options: [
      "All current assets are financed by overdraft",
      "Permanent current assets are financed short-term to save cost",
      "Long-term finance funds non-current assets AND permanent current assets, while short-term finance funds fluctuating current assets",
      "Equity finances current assets and debt finances non-current assets",
    ],
    correct: 2,
    explanation:
      "Matching aligns the maturity of finance with the life of the asset: permanent assets (including the permanent core of current assets) get long-term finance; only the fluctuating layer is financed short-term. Financing permanent current assets short-term (option B) is the AGGRESSIVE policy, and options A and D do not describe maturity matching at all.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM2-C-11",
    paper: "FM",
    area: "C",
    type: "mcq",
    stem: "Which combination of symptoms MOST clearly indicates that a company is overtrading (under-capitalised)?",
    options: [
      "Falling revenue with rising cash balances",
      "Rapid revenue growth financed by a rising overdraft, with falling current and quick ratios",
      "Low gearing, stable sales and long payables days",
      "Rising profit margins and shortening receivables days",
    ],
    correct: 1,
    explanation:
      "Overtrading is growth outrunning long-term funding: sales, inventory and receivables balloon while the cash to fund them comes from short-term borrowing, so liquidity ratios deteriorate even though the business is profitable. The other combinations show surplus liquidity or stability — the trap is equating overtrading with over-EXPANSION of debt generally rather than with under-capitalised growth.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM2-C-12",
    paper: "FM",
    area: "C",
    type: "mcq",
    stem: "A supplier offers terms of 1.5% discount for payment within 15 days, otherwise net 45 days. What is the annual equivalent (compound) cost of REFUSING the discount and paying on day 45?",
    options: ["1.5%", "18.3%", "12.2%", "20.2%"],
    correct: 3,
    explanation:
      "Refusing the discount means paying 1.5/98.5 = 1.52% more for 30 extra days' credit (day 15 to day 45): (1 + 1.5/98.5)^(365/30) − 1 ≈ 20.2%. If this exceeds the overdraft rate, borrow and take the discount. 18.3% is the simple annualisation (1.5% × 365/30), 12.2% spreads the cost over the full 45 days instead of the 30 days of extra credit, and 1.5% is not annualised.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-C-13",
    paper: "FM",
    area: "C",
    type: "number",
    stem: "Annual credit sales are $7,300,000. Tighter credit control will cut receivables days from 50 to 35 with no loss of sales. The overdraft rate is 10%. What is the annual interest saving, in $?",
    numericAnswer: 30000,
    unit: "$",
    tolerance: 10,
    explanation:
      "Sales per day = 7,300,000 ÷ 365 = 20,000, so receivables fall by 15 × 20,000 = $300,000; the interest saving is 300,000 × 10% = $30,000. The saving is earned on the REDUCTION in receivables, not the whole balance — computing 10% of the new or old total is the standard error.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-C-14",
    paper: "FM",
    area: "C",
    type: "mcq",
    stem: "A company uses 400 units of a component per week. The supplier's lead time is 3 weeks and a buffer (safety) inventory of 500 units is held. At what inventory level should a new order be placed?",
    options: ["1,700 units", "1,200 units", "900 units", "2,100 units"],
    correct: 0,
    explanation:
      "Reorder level = demand during the lead time + buffer = (400 × 3) + 500 = 1,700 units. 1,200 forgets the buffer, 900 adds one week's demand to the buffer instead of the full lead time, and 2,100 uses four weeks (adding an extra week 'to be safe' — the buffer already covers that).",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM2-C-15",
    paper: "FM",
    area: "C",
    type: "mcq",
    stem: "Which of the following actions would REDUCE a company's cash operating cycle?",
    options: [
      "Offering customers a longer credit period to boost sales",
      "Increasing buffer inventories to improve availability",
      "Negotiating a longer credit period from suppliers",
      "Paying suppliers earlier to qualify for settlement discounts",
    ],
    correct: 2,
    explanation:
      "Cycle = inventory days + receivables days − payables days, so LENGTHENING payables days shrinks the cycle. Longer customer credit and higher inventories both extend it. Paying suppliers early SHORTENS payables days and so lengthens the cycle — the discount may still be financially worthwhile, but the question asks about the cycle, a distinction the exam loves.",
    marks: 2,
    difficulty: "easy",
  },

  /* ───────────── Area D — Business finance & cost of capital (17) ───────────── */
  {
    id: "FM2-D-01",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "Which of the following statements about convertible loan notes is correct?",
    options: [
      "Holders are obliged to convert them into shares at maturity",
      "They usually carry a lower coupon than straight debt because the conversion option has value",
      "Conversion takes place at the company's option",
      "They must always be secured on the company's assets",
    ],
    correct: 1,
    explanation:
      "The embedded option to convert into equity is valuable to investors, so they accept a lower interest rate than on otherwise-identical straight debt. Conversion is at the HOLDER's option, not compulsory and not the issuer's choice — the two most common confusions — and security is a commercial negotiation, not a requirement.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM2-D-02",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "A company announces a 1-for-4 rights issue at $3.00 per share. The current (cum-rights) share price is $4.00. What is the theoretical ex-rights price (TERP)?",
    options: ["$3.80", "$3.50", "$3.20", "$4.00"],
    correct: 0,
    explanation:
      "TERP = (4 × 4.00 + 1 × 3.00) ÷ 5 = 19.00 ÷ 5 = $3.80: four existing shares at the cum-rights price plus one new share at the issue price, averaged over five. $3.50 is the unweighted average of the two prices, $3.20 swaps the weights (four at $3.00, one at $4.00), and $4.00 assumes the price is unaffected by the discounted issue.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-D-03",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "A company's share price is $5.30 CUM-DIV, with a dividend of $0.30 per share about to be paid. It announces a 1-for-3 rights issue at $4.00. What is the theoretical ex-rights price?",
    options: ["$4.98", "$4.50", "$4.75", "$4.25"],
    correct: 2,
    explanation:
      "TERP calculations use the EX-DIV price: 5.30 − 0.30 = 5.00. TERP = (3 × 5.00 + 1 × 4.00) ÷ 4 = 19.00 ÷ 4 = $4.75. $4.98 forgets to deduct the dividend just about to be paid — the examiner's favourite trap here; $4.50 is the simple average of $5.00 and $4.00; $4.25 swaps the weights.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM2-D-04",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "A 1-for-5 rights issue is priced at $2.50 when the ex-div share price is $3.10, giving a TERP of $3.00. What is the theoretical value of the right attached to each EXISTING share?",
    options: ["$0.50", "$0.60", "$0.083", "$0.10"],
    correct: 3,
    explanation:
      "The value of a right per NEW share is TERP − issue price = 3.00 − 2.50 = $0.50; since five existing shares are needed for one new share, the right per existing share = 0.50 ÷ 5 = $0.10. $0.50 forgets the final division, $0.60 uses the cum-rights price ($3.10 − $2.50) instead of TERP, and $0.083 divides by six (total shares) instead of five (existing shares per right).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-D-05",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "An investor holds 900 shares priced at $3.00 cum-rights. A 1-for-3 rights issue at $2.20 gives a TERP of $2.80. If the investor SELLS all her rights at their theoretical value, what happens to her total wealth (shares plus cash)?",
    options: [
      "It is unchanged in theory",
      "It falls by $180, because the share price drops to the TERP",
      "It rises by $180 from the sale proceeds",
      "It rises by $540",
    ],
    correct: 0,
    explanation:
      "Rights value per new share = 2.80 − 2.20 = $0.60; she can sell rights over 300 new shares for $180. Shares afterwards: 900 × 2.80 = $2,520; plus $180 cash = $2,700 = 900 × $3.00, her starting wealth — selling rights compensates exactly for the price fall. Option B counts the price fall but ignores the sale proceeds; option C counts the proceeds but ignores the price fall; $540 wrongly applies the $0.60 right value to all 900 existing shares.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-D-06",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "According to Miller and Modigliani's dividend irrelevance theory (perfect capital markets, no taxes or transaction costs), the value of a company is determined by:",
    options: [
      "The proportion of earnings paid out as dividends",
      "Its investment (earnings-generating) decisions, not the pattern of its dividends",
      "The information content that dividend changes signal to the market",
      "Shareholders' preference for dividends now over capital gains later",
    ],
    correct: 1,
    explanation:
      "M&M argue that in a perfect market value comes from the earning power of assets; a shareholder wanting cash can manufacture a 'home-made dividend' by selling shares, so payout policy is irrelevant. Signalling (C) and bird-in-the-hand preference (D) are REAL-WORLD arguments AGAINST irrelevance — quoting them as part of M&M's theory is the classic mix-up.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-D-07",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "Under pecking order theory, in what order do companies prefer to raise finance?",
    options: [
      "New equity, then debt, then retained earnings",
      "Debt, then retained earnings, then new equity",
      "Whichever source is cheapest at the time, in strict cost order",
      "Retained earnings, then debt, then new equity as a last resort",
    ],
    correct: 3,
    explanation:
      "Pecking order theory (driven by issue costs and information asymmetry) says firms use internal funds first, then debt, and issue new equity only as a last resort — a new share issue can signal that managers think the shares are overvalued. Option C describes a target/trade-off style optimisation, which is precisely what pecking order theory says firms do NOT do.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-D-08",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "A company has 4 million shares trading at $3.75. The book value of equity is $8 million. It also has a $5 million bank loan costing 8% before tax. The cost of equity is 11% and the tax rate is 25%. What is the WACC?",
    options: ["9.08%", "8.50%", "9.75%", "10.25%"],
    correct: 2,
    explanation:
      "Use MARKET values: equity = 4m × 3.75 = $15m; debt = $5m. After-tax Kd = 8% × 0.75 = 6%. WACC = (15/20 × 11%) + (5/20 × 6%) = 8.25% + 1.5% = 9.75%. 9.08% uses the $8m BOOK value of equity in the weights, 10.25% forgets the tax relief on debt, and 8.50% is the unweighted average of 11% and 6%.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM2-D-09",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "The after-tax cash flows of a redeemable loan note (current market price, after-tax interest, redemption value) give an NPV of +$4.00 at 5% and −$2.00 at 7% per $100 nominal. What is the best estimate of the after-tax cost of debt?",
    options: ["6.3%", "6.0%", "5.7%", "7.0%"],
    correct: 0,
    explanation:
      "The cost of redeemable debt is the IRR of its after-tax flows. Interpolating: 5% + [4 ÷ (4 + 2)] × (7% − 5%) = 5% + 1.33% ≈ 6.3%. 6.0% just takes the midpoint of the rates, 5.7% puts the wrong NPV in the numerator, and 7.0% divides by the NET of the NPVs (4 − 2) instead of the total range (4 + 2).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-D-10",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "A company has just paid a dividend of 20c per share. It retains 40% of earnings and earns a 15% return on reinvested funds. The cost of equity is 11%. Using the dividend growth model with Gordon's growth approximation, what is the share's value?",
    options: ["$4.00", "$4.24", "$1.93", "$10.90"],
    correct: 1,
    explanation:
      "g = b × r = 0.40 × 15% = 6%. P0 = D0(1 + g) ÷ (Ke − g) = 20 × 1.06 ÷ (0.11 − 0.06) = 21.2 ÷ 0.05 = 424c = $4.24. $4.00 forgets to grow the dividend just paid (uses D0 not D1), $1.93 divides by Ke instead of (Ke − g), and $10.90 computes growth with the PAYOUT ratio (0.6 × 15% = 9%), shrinking the denominator to 2%.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM2-D-11",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "A company paid a dividend of 20.00c per share three years ago; the most recent dividend was 23.15c. What is the average annual dividend growth rate for use in the dividend growth model?",
    options: ["15.8%", "5.3%", "5.0%", "3.7%"],
    correct: 2,
    explanation:
      "Growth over three years = 23.15 ÷ 20.00 = 1.157625 = 1.05³, so g = 5.0% per year (compound). 5.3% divides the total 15.8% rise by 3 (arithmetic mean), 15.8% is not annualised at all, and 3.7% takes the FOURTH root because there are four dividends — but four dividends span only three growth periods.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-D-12",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "The risk-free rate is 4%, the expected return on the market portfolio is 10%, and a share's equity beta is 1.2. Using the CAPM, what is the cost of equity?",
    options: ["7.2%", "12.0%", "16.0%", "11.2%"],
    correct: 3,
    explanation:
      "Ke = Rf + β(E(Rm) − Rf) = 4% + 1.2 × (10% − 4%) = 4% + 7.2% = 11.2%. 16.0% multiplies beta by the full MARKET RETURN instead of the market premium (4 + 1.2 × 10), 12.0% is 1.2 × 10 with no risk-free rate, and 7.2% is the risk premium alone without adding Rf back.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM2-D-13",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "A quoted proxy company has an equity beta of 1.5 and is financed by debt and equity in the ratio 1:3 by market value. The tax rate is 25% and its debt can be assumed risk-free. What is the proxy's ASSET (ungeared) beta?",
    options: ["1.20", "1.13", "1.88", "1.50"],
    correct: 0,
    explanation:
      "βa = βe × E ÷ [E + D(1 − t)] = 1.5 × 3 ÷ [3 + 1 × 0.75] = 1.5 × 3/3.75 = 1.20. 1.13 ignores the tax adjustment (1.5 × 3/4), 1.88 REGEARS instead of degearing (multiplying by 3.75/3), and 1.50 makes no adjustment at all — but an equity beta includes the proxy's financial risk, which must be stripped out.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM2-D-14",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "An asset beta of 0.90 has been derived from a proxy company. The investing company is financed by debt:equity of 1:2 (market values) and pays tax at 20%. The risk-free rate is 5% and the equity risk premium is 5%. What cost of equity should be used for the new project?",
    options: ["9.5%", "11.3%", "11.8%", "6.3%"],
    correct: 1,
    explanation:
      "Regear: βe = βa × [E + D(1 − t)] ÷ E = 0.90 × (2 + 1 × 0.8)/2 = 0.90 × 1.4 = 1.26. Then Ke = 5% + 1.26 × 5% = 11.3%. 9.5% forgets to regear (uses the asset beta directly), 11.8% regears but ignores the tax shield (β = 0.9 × 3/2 = 1.35), and 6.3% is 1.26 × 5% without adding the risk-free rate.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM2-D-15",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "When appraising a project in a NEW industry, why must a proxy company's equity beta be degeared and then regeared before use in the CAPM?",
    options: [
      "Because the asset beta contains financial risk that must be removed",
      "Because CAPM measures total risk, which differs between companies",
      "Because the proxy's equity beta reflects the PROXY's gearing, which must be replaced with the investing company's own gearing",
      "To convert the project's unsystematic risk into systematic risk",
    ],
    correct: 2,
    explanation:
      "An equity beta bundles the proxy's business risk with the proxy's FINANCIAL risk. Degearing strips out the proxy's gearing to isolate pure business risk (the asset beta); regearing then adds back the investing company's own financial risk. Option A reverses the definitions — the ASSET beta is the one free of financial risk; CAPM prices only systematic risk, so B and D are wrong.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-D-16",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "Which statement is consistent with Miller and Modigliani's capital structure theory WITH corporate tax?",
    options: [
      "The WACC is constant at all levels of gearing",
      "The WACC falls continuously as gearing rises, because of the tax relief on debt interest, so the theoretical optimum is maximum debt",
      "The WACC falls at first and then rises, giving an optimal gearing level at moderate debt",
      "The cost of equity falls as gearing increases",
    ],
    correct: 1,
    explanation:
      "With tax-deductible interest, every extra unit of debt adds a tax shield, so company value rises and WACC falls as gearing increases — the theoretical conclusion is to gear up as far as possible (in practice limited by bankruptcy costs). Option A is M&M WITHOUT tax, option C is the traditional view, and the cost of equity RISES with gearing in every theory.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM2-D-17",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "A company's irredeemable loan notes carry a 6% coupon and trade at $80 per $100 nominal (ex interest). The tax rate is 25%. What is the after-tax cost of this debt?",
    options: ["7.5%", "4.5%", "6.0%", "5.6%"],
    correct: 3,
    explanation:
      "After-tax Kd = coupon × (1 − t) ÷ market price = 6 × 0.75 ÷ 80 = 4.5 ÷ 80 = 5.6%. 7.5% forgets the tax relief (6/80), 4.5% divides the after-tax interest by the NOMINAL value of $100 instead of the market price, and 6.0% is just the coupon rate — the cost of debt is a market-based yield, not the coupon.",
    marks: 2,
    difficulty: "medium",
  },

  /* ───────────── Area E — Business valuations & risk (12) ───────────── */
  {
    id: "FM2-E-01",
    paper: "FM",
    area: "E",
    type: "mcq",
    stem: "An unlisted company reports earnings after tax of $500,000, which include a one-off gain of $100,000 on a property disposal. A comparable listed company trades on a P/E of 12, and a 25% discount is applied for unlisted status. What is the valuation?",
    options: ["$3.6 million", "$4.5 million", "$4.8 million", "$6.0 million"],
    correct: 0,
    explanation:
      "Use MAINTAINABLE earnings: 500,000 − 100,000 = 400,000. Adjusted P/E = 12 × 0.75 = 9. Value = 400,000 × 9 = $3.6m. $4.5m applies the discounted P/E to unadjusted earnings (forgetting the one-off gain), $4.8m removes the one-off but forgets the unlisted discount, and $6.0m makes neither adjustment.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM2-E-02",
    paper: "FM",
    area: "E",
    type: "mcq",
    stem: "A company's non-current assets have a book value of $5.0m (replacement cost $6.2m, net realisable value $4.4m). Current assets are $1.8m and total liabilities $2.6m. What is the company's asset-based valuation on a NET REALISABLE VALUE basis?",
    options: ["$4.2 million", "$5.4 million", "$3.6 million", "$6.2 million"],
    correct: 2,
    explanation:
      "NRV basis = 4.4 + 1.8 − 2.6 = $3.6m — the break-up floor value for a seller. $4.2m uses book values (5.0 + 1.8 − 2.6), $5.4m uses replacement cost (the buyer's ceiling, 6.2 + 1.8 − 2.6), and $6.2m forgets to deduct the liabilities. Matching the basis to the question is the key discipline here.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM2-E-03",
    paper: "FM",
    area: "E",
    type: "mcq",
    stem: "A company generated free cash flow to the firm of $1.2m in the year just ended, expected to grow at 3% per year indefinitely. The WACC is 11% and the market value of its debt is $3.45m. What is the value of the company's EQUITY?",
    options: ["$15.45 million", "$12.00 million", "$11.55 million", "$15.00 million"],
    correct: 1,
    explanation:
      "Value of the FIRM = FCF1 ÷ (WACC − g) = 1.2 × 1.03 ÷ (0.11 − 0.03) = 1.236 ÷ 0.08 = $15.45m. Equity = 15.45 − 3.45 = $12.00m. $15.45m stops at firm value, forgetting that FCFF discounted at WACC values debt AND equity; $11.55m forgets to grow the just-ended cash flow (15.00 − 3.45); $15.00m makes both errors.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-E-04",
    paper: "FM",
    area: "E",
    type: "mcq",
    stem: "A company's share price adjusts rapidly and accurately as soon as its results are publicly announced, but insiders can still profit from unpublished information. With which form of market efficiency is this consistent?",
    options: ["Weak form", "Semi-strong form", "Strong form", "The market is inefficient"],
    correct: 1,
    explanation:
      "Semi-strong efficiency means prices reflect all PUBLICLY available information — so prices move instantly on announcements, yet unpublished (inside) information can still earn abnormal returns. Under STRONG form even insiders could not profit; weak form covers only past price history. Students often pick strong form because the reaction is 'fast' — speed is not the test, the information set is.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM2-E-05",
    paper: "FM",
    area: "E",
    type: "mcq",
    stem: "If the stock market is efficient in the SEMI-STRONG form, which investor could consistently earn abnormal returns?",
    options: [
      "A chartist analysing past share price patterns",
      "An analyst studying published financial statements",
      "A director dealing on price-sensitive information not yet announced",
      "An investor buying an index-tracking fund",
    ],
    correct: 2,
    explanation:
      "Semi-strong prices already impound all public information, so technical analysis (past prices are public) and fundamental analysis of published accounts cannot systematically beat the market. Only UNPUBLISHED inside information lies outside the semi-strong information set — which is why insider dealing is both profitable and illegal. Index tracking earns the market return, not an abnormal one.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-E-06",
    paper: "FM",
    area: "E",
    type: "number",
    stem: "A US company will receive €500,000 from a customer in three months. It hedges with a forward contract at a three-month forward rate of $1.10 per €1. How many dollars will it receive in three months, in $?",
    numericAnswer: 550000,
    unit: "$",
    tolerance: 10,
    explanation:
      "The forward contract locks in €500,000 × 1.10 = $550,000 regardless of where spot moves. Watch the quote direction: at $ per €, you MULTIPLY a euro amount by the rate; dividing (giving $454,545) is the classic slip when the quote convention is misread.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM2-E-07",
    paper: "FM",
    area: "E",
    type: "mcq",
    stem: "A US company will receive €1,050,000 in one year. Spot rate: $1.2000 per €1. Interest rates: euro borrowing 5%, euro deposit 3%; dollar deposit 4%, dollar borrowing 6%. Using a money-market hedge, how many dollars will it have in one year?",
    options: ["$1,248,000", "$1,310,400", "$1,200,000", "$1,272,233"],
    correct: 0,
    explanation:
      "Borrow euros now so the receipt repays the loan: 1,050,000 ÷ 1.05 = €1,000,000. Convert at spot: × 1.2000 = $1,200,000. Place on dollar DEPOSIT at 4%: × 1.04 = $1,248,000. $1,310,400 borrows the full €1,050,000 without discounting, $1,200,000 forgets to invest the dollars for the year, and $1,272,233 borrows the euros at the 3% DEPOSIT rate — you borrow at the borrowing rate and deposit at the deposit rate.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM2-E-08",
    paper: "FM",
    area: "E",
    type: "mcq",
    stem: "A US company must pay CHF 525,000 in one year. Spot: CHF 1.2500 per $1; one-year forward: CHF 1.2250 per $1. The company can borrow dollars at 8% and deposit Swiss francs at 5%. Which hedge is cheaper, and at what one-year dollar cost?",
    options: [
      "Money-market hedge, costing $432,000",
      "Money-market hedge, costing $400,000",
      "Forward contract, costing $420,000",
      "Forward contract, costing $428,571",
    ],
    correct: 3,
    explanation:
      "Forward: 525,000 ÷ 1.2250 = $428,571 in one year. Money market: deposit 525,000 ÷ 1.05 = CHF 500,000 now, buying it costs 500,000 ÷ 1.25 = $400,000 today, financed by borrowing at 8% → $432,000 in one year. The forward is cheaper by about $3,400. Option A picks the DEARER hedge; option B compares today's $400,000 with a future cost, forgetting the borrowing interest; option C converts at SPOT instead of the forward rate.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM2-E-09",
    paper: "FM",
    area: "E",
    type: "mcq",
    stem: "The spot rate is $1.2000 per €1. One-year interest rates are 6% in the US and 3% in the eurozone. Using interest rate parity, what is the one-year forward rate ($ per €1)?",
    options: ["$1.2350", "$1.1660", "$1.2720", "$1.2000"],
    correct: 0,
    explanation:
      "Interest rate parity: F = S × (1 + i_$) ÷ (1 + i_€) = 1.2000 × 1.06 ÷ 1.03 = $1.2350 — the high-interest currency (the dollar) trades at a forward DISCOUNT. $1.1660 inverts the ratio (1.03/1.06), $1.2720 applies only the dollar rate, and $1.2000 assumes forward equals spot, which would allow risk-free covered arbitrage.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-E-10",
    paper: "FM",
    area: "E",
    type: "mcq",
    stem: "A UK parent's eurozone subsidiary is profitable, but when its euro net assets are retranslated into sterling at the year-end rate, the group reports a loss on the retranslation. Which type of currency risk is this?",
    options: ["Transaction risk", "Economic risk", "Translation risk", "Interest rate risk"],
    correct: 2,
    explanation:
      "Retranslating a foreign subsidiary's net assets for consolidation is TRANSLATION risk — a paper (accounting) effect with no immediate cash flow, so it is generally not hedged with cash instruments. Transaction risk involves actual settlement of a foreign-currency receivable/payable; economic risk is the longer-term effect of exchange rates on competitiveness and value.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM2-E-11",
    paper: "FM",
    area: "E",
    type: "mcq",
    stem: "A company will borrow $10 million in three months' time for a six-month period, and buys a 3-9 FRA at 5%. At settlement the market rate is 6.5%. What is the company's NET effective interest cost for the six months?",
    options: ["$325,000", "$500,000", "$175,000", "$250,000"],
    correct: 3,
    explanation:
      "The FRA locks the rate at 5%: actual interest = 10m × 6.5% × 6/12 = $325,000, but the bank compensates (6.5% − 5%) × 10m × 6/12 = $75,000, leaving a net cost of $250,000 = 10m × 5% × 6/12. $325,000 ignores the FRA receipt, $500,000 forgets the 6/12 period adjustment, and $175,000 deducts the $75,000 compensation from the already-net $250,000 — double counting it.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM2-E-12",
    paper: "FM",
    area: "E",
    type: "mcq",
    stem: "Which of the following statements about a plain vanilla interest rate swap is correct?",
    options: [
      "The notional principal is exchanged at the start and returned at the end",
      "A swap removes all interest rate risk without any counterparty risk",
      "A swap is an option: the company can walk away if rates move favourably",
      "The parties exchange fixed-rate for floating-rate interest obligations on a notional principal, which itself is never exchanged",
    ],
    correct: 3,
    explanation:
      "In an interest rate swap only the interest flows (usually netted) change hands; the principal is purely notional. Exchanging principal (option A) happens in CURRENCY swaps — a favourite mix-up. A swap is a binding obligation, not an option (that would be a swaption), and it carries counterparty risk while converting, not eliminating, exposure.",
    marks: 2,
    difficulty: "medium",
  },
]
