import type { WrittenQuestion } from "@/lib/acca-written"

/*
 * Scholify — ACCA written (constructed-response) questions, set 2.
 *
 * Strategic Professional Options: AFM (Advanced Financial Management) and
 * APM (Advanced Performance Management). These are "advise the board /
 * critique the proposal" discursive questions marked per valid point.
 * Every scenario, company and figure below is INVENTED. All prose is
 * original and syllabus-aligned — no ACCA/Kaplan/BPP material reproduced.
 */

export const WRITTEN_S2: WrittenQuestion[] = [
  // ───────────────────────────── AFM ─────────────────────────────
  {
    id: "AFM-W-01",
    paper: "AFM",
    area: "A",
    topic: "Role of the senior financial adviser & ethics",
    stem: "Northwind Logistics plc is preparing a bid for a rival. The finance director has asked you, as senior adviser, to present only the most optimistic set of cash-flow forecasts to the board because he is personally due a bonus if the acquisition completes. Advise the board on the ethical and governance issues this request raises and how they should be managed. (7 marks)",
    maxMarks: 7,
    rubric: [
      "The adviser faces a conflict between professional objectivity and pressure from a director with a personal financial interest.",
      "Presenting only optimistic forecasts breaches the fundamental principles of integrity and objectivity.",
      "It also undermines professional competence and due care — the board should see a balanced range of outcomes and sensitivities.",
      "The finance director's bonus creates a self-interest threat and a clear conflict of interest that should be disclosed.",
      "Directors have a fiduciary duty to act in the interests of the company and all shareholders, not to enrich one individual.",
      "Safeguards: present a full range of scenarios (base, optimistic, pessimistic) with key assumptions and sensitivities transparent.",
      "The adviser should document the request and, if pressure persists, escalate to the audit committee or non-executive directors, and consider withdrawing.",
    ],
  },
  {
    id: "AFM-W-02",
    paper: "AFM",
    area: "B",
    topic: "APV — assumptions and limitations",
    stem: "Calder Renewables Ltd has valued a new project using the Adjusted Present Value (APV) approach. Explain the circumstances in which APV is more appropriate than a WACC-based NPV, and discuss the key assumptions and limitations the board should be aware of when interpreting the APV figure. (8 marks)",
    maxMarks: 8,
    rubric: [
      "APV separates the base-case NPV (project financed entirely by equity) from the value of the financing side-effects.",
      "It is preferable to WACC-NPV when the capital structure or debt level changes materially over the project's life.",
      "The base-case is discounted at the ungeared (asset) cost of equity, found by ungearing the firm's or a proxy's beta.",
      "Financing effects are added: principally the present value of the tax shield on debt interest.",
      "Other financing effects can include issue costs and any subsidised or cheap loan benefits.",
      "Limitation: the tax shield is often discounted at the cost of debt (or Kd), and the choice of discount rate for the shield is debatable.",
      "Assumption: the debt capacity / debt schedule must be estimated, and tax rates and the firm's ability to use the shield are assumed stable.",
      "Limitation: ungearing betas relies on proxy companies and the Modigliani–Miller assumptions (e.g. debt is risk-free, no financial distress costs).",
    ],
  },
  {
    id: "AFM-W-03",
    paper: "AFM",
    area: "C",
    topic: "Real options — expansion option intuition",
    stem: "Meridian Pharma plc is considering a small loss-making pilot plant that would give it the right, but not the obligation, to build a full-scale facility in three years if the drug is approved. A junior analyst rejected the pilot on a straight NPV basis. Explain why a real-options perspective may justify the pilot, and advise the board on the limitations of applying option pricing here. (8 marks)",
    maxMarks: 8,
    rubric: [
      "The pilot creates a follow-on (expansion / call) option — the right but not the obligation to invest later.",
      "A straight NPV ignores the value of managerial flexibility to expand only if conditions are favourable.",
      "The option has value because of uncertainty: greater volatility in the future payoff raises the option's value.",
      "Mapping to Black–Scholes: the PV of the full facility's cash flows is the underlying asset, the build cost is the exercise price.",
      "Time to expiry is the period the option can be deferred (three years); the risk-free rate and volatility complete the inputs.",
      "So a negative base NPV can be outweighed by the option premium the pilot buys, justifying the pilot.",
      "Limitation: Black–Scholes assumptions (constant volatility, lognormal returns, a single exercise date) fit real assets poorly.",
      "Limitation: volatility of the underlying is hard to estimate, and the option may not be exclusive — competitors may also expand.",
    ],
  },
  {
    id: "AFM-W-04",
    paper: "AFM",
    area: "E",
    topic: "Business valuation — critique of a method",
    stem: "The board of Tolbrook Software plc has received an offer valuing the company on a simple net-asset (book value) basis. Tolbrook is a fast-growing firm whose main assets are its development team and its customer relationships. Critique the appropriateness of the net-asset valuation used and advise the board on more suitable approaches. (7 marks)",
    maxMarks: 7,
    rubric: [
      "Net-asset (book value) valuation reflects historical accounting cost, not the future earning potential of the business.",
      "For a knowledge-based, high-growth firm most value lies in intangibles — people, brand, customer relationships — often unrecognised on the balance sheet.",
      "Book values are distorted by accounting policies (depreciation, non-capitalised R&D) and ignore internally generated goodwill.",
      "Net-asset value therefore sets a floor / liquidation value and will materially understate a going concern like Tolbrook.",
      "An income-based approach — discounted free cash flow — better captures future growth and is more appropriate here.",
      "Market-based multiples (e.g. P/E or EV/EBITDA of comparable listed software firms) provide a useful cross-check.",
      "The board should reject the offer as a starting anchor and negotiate on a DCF/earnings basis, disclosing key value drivers.",
    ],
  },
  {
    id: "AFM-W-05",
    paper: "AFM",
    area: "D",
    topic: "Acquisition — synergy and defensive strategy",
    stem: "Aldermann Foods plc has made a hostile bid for Greenfield Organics plc, claiming large cost synergies. Advise Greenfield's board on how they should evaluate the claimed synergies and outline the defensive tactics available to them. (7 marks)",
    maxMarks: 7,
    rubric: [
      "Synergies should be quantified as the value of the combined entity less the sum of the two firms' standalone values.",
      "Distinguish revenue synergies (cross-selling, wider distribution) from cost synergies (economies of scale, removing duplication).",
      "Claimed synergies should be scrutinised for realism, timing and the integration costs needed to achieve them.",
      "The board should assess whether the bid price captures value that belongs to Greenfield's own shareholders.",
      "Defensive tactic: issue a defence document rejecting the offer and revaluing assets / restating prospects to show under-valuation.",
      "Seek a white knight (a friendlier alternative bidder) or arrange a management buyout.",
      "Other defences: appeal to regulators/competition authorities, or a poison-pill/pac-man type response subject to takeover rules and directors' duties.",
    ],
  },
  {
    id: "AFM-W-06",
    paper: "AFM",
    area: "E",
    topic: "Currency risk — hedging strategy advice",
    stem: "Corvel Instruments plc, a UK exporter, will receive US$8 million in four months. The treasurer is unsure whether to hedge with a forward contract, a money-market hedge or currency options. Advise the treasurer on the factors that should determine the choice, and explain the key trade-off options offer. (7 marks)",
    maxMarks: 7,
    rubric: [
      "A forward contract locks in a fixed rate now, giving certainty but no ability to benefit if the spot rate moves favourably.",
      "A money-market hedge borrows/deposits in the two currencies to fix the outcome using current spot and interest rates.",
      "By interest-rate parity, forward and money-market hedges usually give very similar results.",
      "Currency options give the right but not the obligation to transact, capping downside while retaining upside.",
      "The key trade-off: options require an up-front premium, so they cost more but preserve favourable movements.",
      "Choice factors: the firm's risk appetite, certainty of the underlying cash flow, and the cost/availability of each instrument.",
      "If the receipt is uncertain (e.g. a contingent contract), options are often preferred because they need not be exercised.",
    ],
  },
  {
    id: "AFM-W-07",
    paper: "AFM",
    area: "E",
    topic: "Interest-rate risk — critique of a hedge",
    stem: "The treasurer of Halden Utilities plc has hedged a future £20 million borrowing by buying interest-rate futures, arguing this 'guarantees' the borrowing cost. Critique this description of the hedge and advise the board on the residual risks that remain. (6 marks)",
    maxMarks: 6,
    rubric: [
      "For a future borrowing the risk is that interest rates rise, so the treasurer should be selling (going short) futures, not buying — the described position looks incorrect.",
      "A futures hedge does not 'guarantee' the cost because of basis risk — the gap between futures and cash market rates may not move perfectly together.",
      "Basis risk means the hedge is unlikely to be perfectly effective and some rate exposure remains.",
      "There is also a rounding/quantity mismatch: futures are standardised contract sizes, so the hedge cannot exactly match £20 million.",
      "The maturity of the futures may not coincide with the borrowing date, adding further imperfection.",
      "Futures require margin (initial and variation), creating a liquidity/cash-flow risk the board should be aware of.",
    ],
  },
  {
    id: "AFM-W-08",
    paper: "AFM",
    area: "D",
    topic: "Financial reconstruction — assessment",
    stem: "Pentland Steel plc is in financial distress with high gearing and looming interest payments it cannot meet. Management has proposed a reconstruction scheme converting part of the debt into equity. Advise the affected lenders and shareholders on how they should assess whether to accept the scheme. (8 marks)",
    maxMarks: 8,
    rubric: [
      "The central test is whether each party is better off under the scheme than under the alternative — usually liquidation.",
      "Estimate the amount each class of stakeholder would recover in a liquidation, respecting the order of priority.",
      "Compare that with the value each would hold after the reconstruction as a going concern.",
      "For lenders, converting debt to equity reduces their fixed claim but gives upside if recovery succeeds — assess the trade-off.",
      "Debt-to-equity conversion reduces gearing and the interest burden, improving the chance of survival.",
      "Shareholders face dilution as new equity is issued to former lenders, reducing their proportional ownership.",
      "The scheme is only viable if the underlying business can generate sustainable future cash flows — assess the business plan.",
      "Practical factors: each class must approve, and the plan must be credible to suppliers, customers and remaining lenders.",
    ],
  },
  {
    id: "AFM-W-09",
    paper: "AFM",
    area: "B",
    topic: "Cost of capital — critique of a calculation",
    stem: "An analyst at Brennan Textiles plc has appraised a project in a new, higher-risk overseas market using the company's existing WACC. Critique the use of the existing WACC here and advise on a more appropriate discount rate. (7 marks)",
    maxMarks: 7,
    rubric: [
      "The existing WACC reflects the risk of the company's current activities and current capital structure.",
      "Using it for a project of different business risk will misprice the project — here it would understate the required return.",
      "The correct approach is a risk-adjusted rate reflecting the project's own systematic (business) risk.",
      "Identify proxy companies operating in the target market/industry and take their equity betas.",
      "Ungear the proxy beta to remove their financial risk, then regear to Brennan's own capital structure.",
      "Use the regeared beta in CAPM to derive a project-specific cost of equity, then a project-specific WACC.",
      "Country/political risk and currency risk may need reflecting in the cash flows or an additional risk premium.",
    ],
  },
  {
    id: "AFM-W-10",
    paper: "AFM",
    area: "C",
    topic: "Investment appraisal — Monte Carlo & sensitivity",
    stem: "The board of Selwyn Mining plc has been given a single NPV figure for a large project. Advise the board on the value of supplementing this with sensitivity analysis and simulation (Monte Carlo), and discuss the limitations of these techniques. (7 marks)",
    maxMarks: 7,
    rubric: [
      "A single NPV hides the uncertainty in the underlying assumptions and gives false precision.",
      "Sensitivity analysis shows how much each variable can change before NPV becomes zero, highlighting the key drivers.",
      "It helps the board focus management attention and control on the most critical variables.",
      "Limitation of sensitivity analysis: it changes one variable at a time and ignores correlations and probabilities.",
      "Monte Carlo simulation assigns probability distributions to variables and produces a distribution of NPV outcomes.",
      "This gives an expected NPV, the probability of a negative NPV and a fuller picture of risk.",
      "Limitations of simulation: it needs reliable distributions and correlations, is complex, and does not itself give a decision rule.",
    ],
  },
  {
    id: "AFM-W-11",
    paper: "AFM",
    area: "E",
    topic: "Treasury — role and centralisation",
    stem: "Larkspur Group plc operates in twelve countries with each subsidiary managing its own cash and borrowing. The board is considering setting up a centralised treasury function. Advise the board on the benefits and drawbacks of centralising treasury. (7 marks)",
    maxMarks: 7,
    rubric: [
      "Centralisation allows netting of intra-group balances, reducing the number and cost of external transactions.",
      "Surplus cash in one subsidiary can offset deficits in another, cutting overall borrowing and interest cost.",
      "Pooling gives greater bargaining power with banks and access to better rates and cheaper finance.",
      "Specialist treasury expertise (hedging, investment) can be concentrated, improving risk management.",
      "It gives the group a consolidated view of currency and interest-rate exposures to hedge on a net basis.",
      "Drawback: local knowledge of markets, banks and regulations may be lost, and local managers demotivated.",
      "Drawback: tax, exchange-control and transfer-pricing rules across jurisdictions can complicate cash movement.",
    ],
  },
  {
    id: "AFM-W-12",
    paper: "AFM",
    area: "E",
    topic: "Free cash flow to firm — interpreting an estimate",
    stem: "In valuing Ashcombe Retail plc, an adviser has estimated free cash flow to the firm (FCFF) and grown it at a constant 6% forever to derive a terminal value that is 80% of the total valuation. Critique the reliance on this terminal value and advise the board on interpreting the result. (7 marks)",
    maxMarks: 7,
    rubric: [
      "Free cash flow to the firm is the cash available to all providers of finance before financing flows.",
      "A large share of value in the terminal value is normal, but 80% makes the valuation very sensitive to the terminal assumptions.",
      "The perpetuity growth rate cannot exceed the long-run growth rate of the economy — 6% forever is likely too high.",
      "The terminal value is highly sensitive to the gap between the discount rate and the growth rate — a small change moves value greatly.",
      "The constant-growth assumption ignores the competitive life cycle; abnormal growth cannot persist indefinitely.",
      "The board should test the valuation against a range of growth and discount rates (sensitivity) and cross-check with multiples.",
      "The result should be treated as one estimate within a range, not a precise figure, given the assumptions involved.",
    ],
  },
  {
    id: "AFM-W-13",
    paper: "AFM",
    area: "A",
    topic: "Dividend policy — advising the board",
    stem: "Fenwick Beverages plc has historically paid a stable, growing dividend but now has a large, value-creating investment programme that would require cutting the dividend. Advise the board on the factors to consider before changing the dividend policy. (6 marks)",
    maxMarks: 6,
    rubric: [
      "In a perfect market (Modigliani–Miller) dividend policy is irrelevant, but market imperfections mean it matters in practice.",
      "The signalling effect: a dividend cut may be read by the market as bad news and depress the share price.",
      "The clientele effect: existing shareholders may have chosen the firm for its stable income and could sell if it changes.",
      "If the investment projects have a positive NPV, retaining cash to fund them can create more value than paying it out.",
      "Consider the cost of external finance versus retained earnings — retention avoids issue costs.",
      "The board should communicate the strategy clearly, perhaps phasing the change or using a scrip alternative to manage expectations.",
    ],
  },
  {
    id: "AFM-W-14",
    paper: "AFM",
    area: "D",
    topic: "MBO financing — evaluation",
    stem: "The management team of Rowntree Plastics, a division of a larger group, wants to buy the division in a management buy-out (MBO) funded largely by debt. Advise the management team on the key issues in financing and structuring the buy-out. (7 marks)",
    maxMarks: 7,
    rubric: [
      "An MBO is typically highly geared, so future cash flows must be reliable enough to service and repay the debt.",
      "High gearing raises financial risk and the cost of financial distress if trading weakens.",
      "The team will usually need a mix of finance: their own equity, private-equity/venture-capital equity, and layers of debt.",
      "Mezzanine finance (subordinated debt with higher return, sometimes with equity warrants) often bridges the gap.",
      "A fair price must be negotiated with the vendor group, who may have an information advantage or conflict.",
      "Providers of equity will want an exit route (trade sale or flotation) within a defined horizon and a target return.",
      "Management incentives, warranties, and control/covenants imposed by lenders and investors must be agreed.",
    ],
  },
  {
    id: "AFM-W-15",
    paper: "AFM",
    area: "A",
    topic: "Impact of environmental/social factors on strategy",
    stem: "Kestrel Energy plc is deciding whether to invest heavily in renewable generation or continue with lower-cost fossil-fuel assets. Advise the board on how environmental, social and governance (ESG) considerations should influence this strategic financial decision. (7 marks)",
    maxMarks: 7,
    rubric: [
      "Purely financial NPV may favour fossil assets short-term, but ESG factors affect long-term value and risk.",
      "Regulatory and carbon-pricing risk could turn fossil assets into stranded assets, reducing their future cash flows.",
      "Reputation and customer/employee expectations increasingly reward credible environmental strategy.",
      "Access to finance is affected: many investors and lenders now screen on ESG, lowering the cost of capital for green projects.",
      "The board has a stewardship duty to a wider set of stakeholders, not only short-term shareholder returns.",
      "ESG risks and opportunities should be built into the cash flows and discount rate rather than treated as an add-on.",
      "Transparent ESG reporting and integrated reporting help communicate the strategy and support the valuation.",
    ],
  },

  // ───────────────────────────── APM ─────────────────────────────
  {
    id: "APM-W-01",
    paper: "APM",
    area: "A",
    topic: "Performance management & strategy alignment",
    stem: "Verano Hotels plc has grown by acquisition and now runs three hotel brands with very different strategies, yet head office measures all of them against the same set of financial targets. Advise the board on why the performance management system may be failing to support strategy. (7 marks)",
    maxMarks: 7,
    rubric: [
      "Performance measures should be derived from, and support, each unit's specific strategy — a single set cannot fit three different strategies.",
      "Uniform financial targets ignore differences in market position, life-cycle stage and competitive basis of each brand.",
      "A budget/luxury/mid-market split competes on different critical success factors (price, service, occupancy) needing different KPIs.",
      "Purely financial targets are lagging indicators and encourage short-termism at the expense of longer-term drivers.",
      "The system risks dysfunctional behaviour: managers optimise the common metric rather than their own strategy.",
      "Non-financial measures (guest satisfaction, staff retention, quality) should be tailored to each brand's value proposition.",
      "The board should cascade strategy into brand-specific objectives and measures, e.g. via a balanced scorecard per unit.",
    ],
  },
  {
    id: "APM-W-02",
    paper: "APM",
    area: "C",
    topic: "Balanced scorecard — recommendation",
    stem: "Delmark Clinics plc, a chain of private healthcare centres, currently reports only monthly profit and revenue. The board wants a broader view of performance. Recommend the balanced scorecard as a framework and explain how its perspectives would apply to Delmark. (8 marks)",
    maxMarks: 8,
    rubric: [
      "The balanced scorecard measures performance across four perspectives, balancing financial and non-financial measures.",
      "Financial perspective: 'how do we look to shareholders?' — e.g. profit margin, revenue growth, return on capital for Delmark.",
      "Customer perspective: 'how do customers see us?' — e.g. patient satisfaction, waiting times, repeat/referral rates.",
      "Internal business process perspective: 'what must we excel at?' — e.g. clinical outcomes, infection rates, appointment utilisation.",
      "Learning and growth (innovation) perspective: 'can we continue to improve?' — e.g. staff training, retention, new treatment adoption.",
      "The perspectives are linked by cause and effect: better learning drives better processes, which drive customer and then financial results.",
      "It reduces the danger of over-focusing on short-term profit at the expense of the drivers of future performance.",
      "Measures should be limited in number and clearly tied to Delmark's strategy to avoid overload.",
    ],
  },
  {
    id: "APM-W-03",
    paper: "APM",
    area: "D",
    topic: "Divisional performance — ROI vs RI",
    stem: "Ashworth Industries plc appraises its divisional managers solely on return on investment (ROI). A manager has just rejected a project earning 14% because her division's current ROI is 18%, even though the group cost of capital is 10%. Critique the use of ROI here and advise the board on a better measure. (7 marks)",
    maxMarks: 7,
    rubric: [
      "ROI is divisional profit expressed as a percentage of divisional capital employed.",
      "The rejected project earns 14%, above the 10% cost of capital, so it is value-adding for the group.",
      "But it would lower the division's average ROI from 18%, so an ROI-appraised manager rejects it — a dysfunctional decision.",
      "This shows ROI can cause goal incongruence between the division and the group.",
      "Residual income (RI) is divisional profit less a charge for capital (capital employed × cost of capital).",
      "Under RI the project gives a positive residual income, so the manager would correctly accept it.",
      "The board should appraise managers on RI (or economic value added) to align divisional and group interests, while noting RI's absolute-measure drawback for comparing different-sized divisions.",
    ],
  },
  {
    id: "APM-W-04",
    paper: "APM",
    area: "D",
    topic: "Economic value added (EVA) — evaluation",
    stem: "The board of Tidewell Manufacturing plc is considering replacing residual income with Economic Value Added (EVA) to assess divisional performance. Explain how EVA differs from residual income and evaluate whether it would improve performance measurement at Tidewell. (8 marks)",
    maxMarks: 8,
    rubric: [
      "EVA is after-tax net operating profit (NOPAT) less a capital charge (invested capital × WACC).",
      "Like residual income it charges for the cost of capital, but it uses adjusted 'economic' figures rather than accounting figures.",
      "Adjustments add back and capitalise value-building spend such as R&D, advertising and training, treating them as assets.",
      "Non-cash items (e.g. accounting depreciation, provisions) and goodwill are adjusted to better reflect economic reality.",
      "This reduces the incentive to cut discretionary long-term spending to boost short-term profit — a benefit for Tidewell.",
      "EVA aligns managerial decisions with shareholder value creation, since positive EVA means returns exceed the cost of capital.",
      "Drawback: the adjustments are numerous, subjective and complex, and EVA remains an absolute measure biased toward large divisions.",
      "It is still based partly on historical/accounting data and can encourage short-termism if capital charges deter long-payback projects.",
    ],
  },
  {
    id: "APM-W-05",
    paper: "APM",
    area: "C",
    topic: "Building block model — service business",
    stem: "Marlowe & Grant is a professional services firm whose partners feel its current profit-only measures are unfair on staff and ignore service quality. Recommend Fitzgerald and Moon's 'building block' model and explain how its dimensions, standards and rewards would apply to the firm. (8 marks)",
    maxMarks: 8,
    rubric: [
      "The building block model was designed specifically for performance measurement in service businesses.",
      "It has three building blocks: dimensions, standards and rewards.",
      "Dimensions are the areas of performance measured — split into results (competitiveness and financial performance)...",
      "...and determinants (quality, flexibility, resource utilisation and innovation) which drive the results.",
      "For Marlowe & Grant, dimensions could include client win rate, fee income, service quality and staff flexibility.",
      "Standards should be owned by those measured, fair (achievable), and controllable by them to motivate.",
      "Rewards should be clear (understood), motivating and controllable — linked to standards staff can influence.",
      "Applying it addresses the partners' concerns by adding quality and staff-related measures and fair, controllable targets.",
    ],
  },
  {
    id: "APM-W-06",
    paper: "APM",
    area: "C",
    topic: "Performance pyramid — recommendation",
    stem: "Halloran Engineering plc finds that its operational shop-floor measures seem disconnected from its corporate strategy. Recommend the Lynch and Cross performance pyramid as a framework and explain how it would link operations to strategy at Halloran. (7 marks)",
    maxMarks: 7,
    rubric: [
      "The performance pyramid links corporate strategy at the top to day-to-day operations at the base.",
      "At the apex is the corporate vision, which is translated down through the organisation.",
      "At the business-unit level, objectives are set for market (external) and financial (internal) performance.",
      "At the business-operating-system level these become customer satisfaction, flexibility and productivity.",
      "At the base (departments/work centres) they become quality, delivery, cycle time and waste.",
      "The left side of the pyramid reflects external effectiveness (customer focus); the right side internal efficiency.",
      "Applying it lets Halloran trace each shop-floor measure up to a strategic objective, closing the operations–strategy gap.",
    ],
  },
  {
    id: "APM-W-07",
    paper: "APM",
    area: "D",
    topic: "Behavioural consequences of targets",
    stem: "Since introducing aggressive individual sales targets with large bonuses, Petra Telecom plc has seen rising revenue but a surge in customer complaints and mis-selling allegations. Discuss the behavioural consequences of the target and bonus system and advise the board on how to address them. (7 marks)",
    maxMarks: 7,
    rubric: [
      "Rewarding a single dimension (sales volume) encourages managers to maximise that measure at the expense of others.",
      "This is dysfunctional behaviour / 'tunnel vision' — focusing narrowly on what is measured and rewarded.",
      "Aggressive individual bonuses can drive gaming and unethical behaviour such as mis-selling.",
      "It illustrates that 'what gets measured gets done' — the system rewards the wrong outcomes.",
      "Customer satisfaction and complaint rates should be built into the reward system to balance volume.",
      "Targets should be balanced across quality and quantity, and possibly include team-based measures to discourage self-interest.",
      "The board should also review the ethics/culture and controls, not just the metrics, and set achievable, fair targets to reduce gaming.",
    ],
  },
  {
    id: "APM-W-08",
    paper: "APM",
    area: "D",
    topic: "Corporate failure — Altman Z-score",
    stem: "An analyst has flagged that Crossley Retail plc has a low Altman Z-score. The finance director dismisses this, saying 'it's only a ratio model'. Explain what the Z-score measures and advise the board on its usefulness and limitations for predicting corporate failure. (7 marks)",
    maxMarks: 7,
    rubric: [
      "The Altman Z-score is a quantitative model combining several financial ratios into a single score.",
      "It weights ratios covering profitability, liquidity/working capital, gearing/solvency and efficiency (e.g. asset turnover).",
      "A score below a lower threshold signals a high probability of failure; above an upper threshold signals safety, with a grey zone between.",
      "It is useful as an early-warning, objective screen that summarises several dimensions in one figure.",
      "Limitation: it is based on historical financial statements which may be out of date or manipulated.",
      "Limitation: the original coefficients were derived from a specific sample (US manufacturers) and may not fit a UK retailer.",
      "It ignores qualitative and non-financial warning signs, so should complement — not replace — wider analysis such as Argenti's model.",
    ],
  },
  {
    id: "APM-W-09",
    paper: "APM",
    area: "D",
    topic: "Corporate failure — Argenti's A-score",
    stem: "Whitmore Foods plc appears financially sound, but a non-executive director is worried about weak governance and an autocratic chief executive. Explain how Argenti's A-score model assesses failure risk and advise the board on why it may add insight beyond the financial ratios. (7 marks)",
    maxMarks: 7,
    rubric: [
      "Argenti's A-score is a qualitative model that sees failure as a process, not a single event.",
      "It scores three stages: defects, mistakes and symptoms.",
      "Defects include management weaknesses — an autocratic chief executive, a weak/non-independent board, poor accounting information.",
      "Mistakes that follow the defects include high gearing (overtrading debt), overtrading, and a big risky project ('the big project').",
      "Symptoms then appear: financial deterioration, creative accounting, declining morale and non-financial signs.",
      "Because it captures management and governance quality, it flags risks the financial ratios alone would miss — relevant to Whitmore's concern.",
      "Limitation: scoring is subjective and judgemental, so it should be used alongside quantitative models such as the Z-score.",
    ],
  },
  {
    id: "APM-W-10",
    paper: "APM",
    area: "B",
    topic: "Transfer pricing — advising on method",
    stem: "At Barwick Chemicals plc, the supplying division sells an intermediate product both externally and to another division. The two divisional managers are in dispute over the transfer price. Advise the board on the principles that should govern the transfer price and the goal-congruence issues involved. (7 marks)",
    maxMarks: 7,
    rubric: [
      "A transfer price should encourage divisional decisions that are also in the best interest of the group as a whole (goal congruence).",
      "It should also allow fair measurement of each division's performance and preserve divisional autonomy.",
      "The general economic rule is transfer at marginal (variable) cost plus any opportunity cost to the supplying division.",
      "When there is a competitive external market and no spare capacity, the external market price is the appropriate transfer price.",
      "When the supplying division has spare capacity, marginal cost is the relevant floor and market price the ceiling — negotiation sets it between.",
      "Cost-plus prices based on full cost can transfer inefficiencies and distort decisions, so are less satisfactory.",
      "The board should ensure the method chosen does not cause a division to reject transfers that benefit the group overall.",
    ],
  },
  {
    id: "APM-W-11",
    paper: "APM",
    area: "A",
    topic: "External factors — environmental & stakeholder",
    stem: "Ferndale Apparel plc measures performance almost entirely on cost and margin, but faces growing pressure over supply-chain labour conditions and environmental impact. Advise the board on why its performance management system should reflect environmental and social factors. (7 marks)",
    maxMarks: 7,
    rubric: [
      "A cost-and-margin focus ignores stakeholders (employees, communities, regulators, pressure groups) who affect long-term success.",
      "Environmental and social failures create reputational, legal and financial risks that harm future performance.",
      "Sustainability is increasingly a critical success factor influencing customer and investor decisions.",
      "Measures such as environmental footprint, supplier audit results and labour standards should be integrated into the system.",
      "This can be embedded via a sustainability-adapted balanced scorecard or a separate sustainability perspective.",
      "Environmental management accounting can identify and control hidden environmental costs currently in overheads.",
      "Reporting these measures (e.g. integrated reporting) improves transparency and accountability to stakeholders.",
    ],
  },
  {
    id: "APM-W-12",
    paper: "APM",
    area: "D",
    topic: "Budgeting style & behaviour",
    stem: "Osborne Foods plc imposes budgets from head office with no input from operating managers, who complain the targets are unrealistic and demotivating. Discuss the behavioural effects of this budgeting approach and advise the board on the merits of participative budgeting. (7 marks)",
    maxMarks: 7,
    rubric: [
      "Imposed (top-down) budgets can be seen as unfair and unrealistic, reducing managers' commitment and motivation.",
      "Lack of participation lowers acceptance and can lead managers to disown targets they had no part in setting.",
      "Participative (bottom-up) budgeting involves managers, improving ownership, morale and goal congruence.",
      "It draws on operational managers' local knowledge, improving the accuracy and realism of the budget.",
      "A drawback of participation is budgetary slack — managers building in easy targets to protect themselves.",
      "Overly tough imposed targets can also cause dysfunctional behaviour and manipulation of results.",
      "A negotiated approach, with head-office guidance plus manager input, often balances realism, control and motivation.",
    ],
  },
  {
    id: "APM-W-13",
    paper: "APM",
    area: "B",
    topic: "Activity-based & strategic management accounting",
    stem: "Kellerman Components plc uses a traditional absorption-costing system that spreads overheads on labour hours. Its high-volume simple products look unprofitable while complex low-volume products look very profitable. Advise the board on whether activity-based costing would give better information for performance management. (7 marks)",
    maxMarks: 7,
    rubric: [
      "Traditional absorption costing spreads overheads using a volume-based measure such as labour hours.",
      "This over-costs high-volume simple products and under-costs low-volume complex products when overheads are not volume-driven.",
      "Activity-based costing traces overheads to activities and assigns them via cost drivers that reflect what causes the cost.",
      "Complex low-volume products consume more support activities (set-ups, inspections, handling) per unit than volume implies.",
      "ABC would likely reveal the complex products are less profitable and the simple ones more profitable than currently shown.",
      "Better cost information supports pricing, product-mix and performance decisions and highlights non-value-adding activities.",
      "Drawback: ABC is costly and complex to implement and maintain, so the benefit must justify the cost.",
    ],
  },
  {
    id: "APM-W-14",
    paper: "APM",
    area: "D",
    topic: "Divisional autonomy & controllability",
    stem: "Rushmore Group plc holds each divisional manager fully accountable for their division's return on investment, including head-office cost allocations and interest on group debt. A manager argues this is unfair. Advise the board on the controllability principle and how divisional performance should be assessed. (6 marks)",
    maxMarks: 6,
    rubric: [
      "The controllability principle says managers should be assessed only on items they can control or significantly influence.",
      "Apportioned head-office costs and group interest are not controllable by a divisional manager, so including them is unfair.",
      "Distinguish evaluating the manager from evaluating the division as an economic unit — different measures suit each.",
      "For the manager, use a controllable profit / controllable ROI or RI excluding uncontrollable allocations.",
      "For the division, a fuller measure including allocated costs may be appropriate to judge the investment itself.",
      "Charging uncontrollable costs demotivates managers and can distort behaviour, so the board should separate the two purposes.",
    ],
  },
  {
    id: "APM-W-15",
    paper: "APM",
    area: "C",
    topic: "Benchmarking & critical review of a KPI set",
    stem: "The board of Langton Fitness plc benchmarks its clubs only against last year's own figures, and its main KPI is 'number of new memberships sold'. Critique this benchmarking approach and set of measures, and advise the board on improvements. (7 marks)",
    maxMarks: 7,
    rubric: [
      "Benchmarking only against its own prior year (internal, historical) ignores how competitors and best practice are performing.",
      "External/competitive benchmarking against rival clubs or industry best practice would set more demanding, relevant targets.",
      "A single KPI (new memberships sold) is too narrow and encourages tunnel vision on acquisition.",
      "It ignores member retention and churn, which are usually more important to a subscription business's long-term value.",
      "It also ignores quality, utilisation, cost and customer satisfaction measures that drive sustainable performance.",
      "Focusing on new sales alone may encourage discounting or over-selling that harms profitability and reputation.",
      "The board should adopt a balanced set of measures (retention, satisfaction, revenue per member, cost) benchmarked externally.",
    ],
  },
]
