import type { WrittenQuestion } from "@/lib/acca-written"

/*
 * Scholify — ACCA Strategic Professional written questions, set 3 (S3).
 *
 * ATX (Advanced Taxation, UK — FA2024 for 2024/25) and AAA (Advanced Audit
 * and Assurance) constructed-response questions for the AI Examiner. Every
 * scenario, name and figure is INVENTED; all technical content is drawn from
 * the public syllabus only. No ACCA, Kaplan or BPP material is reproduced.
 * Each carries a rubric of marking points (~1 mark each).
 */

export const WRITTEN_S3: WrittenQuestion[] = [
  // ============================ ATX (15) ============================
  {
    id: "ATX-W-01",
    paper: "ATX",
    area: "B",
    topic: "Incorporation of a sole trader",
    stem: "Priya Nadar runs a profitable graphic-design business as a sole trader, currently making tax-adjusted trading profits of around £110,000 a year, all of which she needs to draw for living costs. She is considering transferring the business to a new company, Nadar Studio Ltd, in which she would be the sole director-shareholder. Advise Priya on the main tax implications of incorporating her business and the factors that determine whether incorporation would be tax-efficient for her. (8 marks)",
    maxMarks: 8,
    rubric: [
      "As a sole trader Priya pays income tax on the full trading profit at rates up to 45% plus Class 4 (and Class 2) NIC, regardless of how much she withdraws.",
      "Once incorporated, the company pays corporation tax on its profits (main rate 25%, small profits rate 19%, with marginal relief between £50,000 and £250,000).",
      "Priya is then taxed personally only on the salary and dividends she extracts, so profits retained in the company are not immediately taxed on her.",
      "A tax-efficient extraction mix is typically a small salary (to preserve NIC record and use the personal allowance) plus dividends taxed at 8.75%/33.75%/39.35% after the £500 dividend allowance.",
      "Because Priya needs to draw substantially all the profit, much of the benefit of deferral is lost and total tax on extracted profit may exceed the sole-trade position once double taxation (CT then dividend tax) is considered.",
      "Transferring chargeable business assets (e.g. goodwill) is a disposal for CGT, but incorporation relief (s162 TCGA 1992) or gift relief (s165) can defer the gain.",
      "Incorporation brings extra compliance and cost: company accounts, corporation tax returns, PAYE for any salary, and possible loss of cash-basis simplicity.",
      "Conclusion should weigh her need to extract all profit (favours staying a sole trader) against benefits such as limited liability and flexibility of profit extraction.",
    ],
  },
  {
    id: "ATX-W-02",
    paper: "ATX",
    area: "B",
    topic: "Profit extraction — salary vs dividend",
    stem: "Kesler Instruments Ltd is an owner-managed company whose sole shareholder-director, Tom Kesler, wants to withdraw a further £40,000 of company profit for the 2024/25 tax year. His other income already uses his personal allowance and keeps him within the basic rate band with about £8,000 of basic rate band remaining. Advise Tom on the tax and NIC consequences of extracting the £40,000 as additional salary compared with extracting it as a dividend, and recommend the more tax-efficient route. (7 marks)",
    maxMarks: 7,
    rubric: [
      "Additional salary is deductible for the company, reducing its corporation tax, whereas a dividend is paid out of post-tax profit and gives the company no deduction.",
      "Salary attracts employee Class 1 NIC (currently 8% then 2% above the upper earnings limit) and employer Class 1 NIC at 13.8%.",
      "Salary is taxed as employment income at Tom's marginal rate (basic 20% then higher 40% once the basic rate band is used).",
      "A dividend carries no NIC for either the company or Tom.",
      "Dividends are taxed after the £500 dividend allowance at 8.75% (basic), 33.75% (higher) and 39.35% (additional rate).",
      "Because dividends avoid all NIC and are taxed at lower dividend rates, extraction by dividend is generally more tax-efficient overall than salary for an owner-manager.",
      "Recommendation: extract the £40,000 mainly as a dividend, though a small salary can still be worthwhile to use any remaining allowances and preserve NIC/state-pension entitlement.",
    ],
  },
  {
    id: "ATX-W-03",
    paper: "ATX",
    area: "B",
    topic: "Employment vs self-employment",
    stem: "Delta Rail Ltd engages Marcus Vane to carry out signalling inspections. Marcus works set hours at Delta's depot, uses Delta's equipment, is paid a fixed monthly amount, cannot send a substitute and does no similar work for anyone else. Delta treats him as self-employed and pays him gross. Advise Delta on the factors that determine whether Marcus is employed or self-employed, and explain the tax consequences for Delta if HMRC successfully argues that he is in fact an employee. (7 marks)",
    maxMarks: 7,
    rubric: [
      "Employment status is decided on the overall picture, not on the label the parties use.",
      "Key indicators of employment include: an obligation of personal service with no genuine right to provide a substitute.",
      "The presence of control by the engager over what, how, when and where the work is done.",
      "Mutuality of obligation — the engager must offer work and the worker must accept it.",
      "Other factors point the same way: use of the engager's equipment, fixed regular pay, integration into the business and no financial risk borne by the worker.",
      "On these facts (control, no substitution, fixed pay, exclusivity) Marcus is likely to be an employee.",
      "If reclassified, Delta becomes liable to account for PAYE income tax and employee and employer Class 1 NIC on the payments, plus interest and possible penalties for failing to operate PAYE.",
    ],
  },
  {
    id: "ATX-W-04",
    paper: "ATX",
    area: "C",
    topic: "Business asset disposal relief",
    stem: "Ingrid Holt is planning to sell her 8% shareholding in Verano Ceramics Ltd, an unquoted trading company where she has worked full-time as operations manager for the last four years and has held the shares throughout that period. She expects a gain of about £600,000 and has made no previous claims for business asset disposal relief (BADR). Explain the conditions Ingrid must satisfy to claim BADR on the disposal, and the effect a successful claim would have on the CGT payable. (7 marks)",
    maxMarks: 7,
    rubric: [
      "BADR applies to a qualifying disposal of shares in a company that is the individual's personal trading company (or holding company of a trading group).",
      "A personal company requires the shareholder to hold at least 5% of the ordinary share capital and voting rights — Ingrid's 8% satisfies this.",
      "The individual must also be an officer or employee of the company — Ingrid qualifies as operations manager.",
      "These conditions (and the trading status) must be met throughout the two years ending on the date of disposal — her four-year holding meets this.",
      "A successful claim taxes the qualifying gain at a flat rate of 10%.",
      "Relief is subject to a lifetime limit of £1 million of qualifying gains; her £600,000 gain is within the limit and she has made no earlier claims.",
      "The claim must be made by the first anniversary of 31 January following the tax year of disposal.",
    ],
  },
  {
    id: "ATX-W-05",
    paper: "ATX",
    area: "C",
    topic: "Gift relief (holdover) on business assets",
    stem: "Harold Frayne wishes to give his entire holding of shares in Frayne Joinery Ltd, an unquoted trading company, to his daughter Cara so she can take over the business. The shares stand at a substantial gain over their original cost. Harold has been told he can 'hold over' the gain. Explain how gift relief (s165 TCGA 1992) would apply to this gift, the conditions that must be met, and its effect on both Harold and Cara. (6 marks)",
    maxMarks: 6,
    rubric: [
      "Gift relief allows the chargeable gain arising on a gift (or sale at undervalue) to be held over rather than taxed immediately.",
      "It is available on gifts of qualifying business assets, including shares in an unquoted trading company — Frayne Joinery Ltd qualifies.",
      "A joint claim (election) by both the donor and the donee is required.",
      "The effect is that no CGT is payable by Harold at the time of the gift on the held-over element of the gain.",
      "The held-over gain is deducted from Cara's base cost, so her acquisition cost is the market value at the gift date less the held-over gain.",
      "The gain is therefore deferred and taxed on Cara when she later disposes of the shares (subject to any relief she can then claim).",
    ],
  },
  {
    id: "ATX-W-06",
    paper: "ATX",
    area: "C",
    topic: "Principal private residence relief",
    stem: "Lena Brackett is selling a house she owned for ten years and is unsure how much of the gain is exempt. For the first two years she lived in it as her only home; she was then required by her employer to work abroad for three years, after which she returned and lived in it again for two years before letting it out to tenants for the final three years up to sale. Explain how principal private residence (PPR) relief applies to Lena's gain, identifying which periods of ownership are exempt. (7 marks)",
    maxMarks: 7,
    rubric: [
      "PPR relief exempts the gain relating to periods an individual occupied the property as their only or main residence.",
      "The initial two years of actual occupation are exempt.",
      "The final two years of letting: only the last 9 months of ownership are automatically treated as exempt regardless of use.",
      "The three years working abroad can be a period of deemed occupation, as any period of absence while working overseas in employment is treated as occupation.",
      "Deemed-occupation periods require actual occupation of the property both before and after the absence — met here because she lived in it before going abroad and after returning.",
      "The two years of actual occupation after returning are also exempt.",
      "The remaining part of the final letting period (beyond the last 9 months) is not covered by occupation, so that proportion of the gain is chargeable, subject to any residential-letting relief that may apply.",
    ],
  },
  {
    id: "ATX-W-07",
    paper: "ATX",
    area: "C",
    topic: "Incorporation relief (s162)",
    stem: "Owen Castellan is transferring his entire sole-trade landscaping business, including chargeable assets standing at a gain, to a newly formed company wholly in exchange for shares. He wants to know how incorporation relief works and whether he can choose not to apply it. Explain the operation and conditions of incorporation relief under s162 TCGA 1992, and how the relief would affect the base cost of Owen's shares. (6 marks)",
    maxMarks: 6,
    rubric: [
      "Incorporation relief defers the chargeable gains arising when a business is transferred to a company.",
      "It applies automatically where a person transfers a business as a going concern, together with all its assets (cash may be excluded), wholly or partly in exchange for shares.",
      "The gain deferred is restricted to the proportion of consideration taken in shares; any consideration taken in cash or other form does not attract the relief.",
      "Where the whole consideration is shares, the entire gain is deferred.",
      "The deferred gain is deducted from the base cost of the shares received, so the gain crystallises on a later disposal of those shares.",
      "Owen can elect for incorporation relief not to apply (for example to use an annual exempt amount or business asset disposal relief), the election being made within the statutory time limit.",
    ],
  },
  {
    id: "ATX-W-08",
    paper: "ATX",
    area: "D",
    topic: "Lifetime gifts, PETs and taper relief",
    stem: "Reginald Poole made an outright cash gift of £400,000 to his son in June 2020. He had made no earlier lifetime gifts. Reginald died in September 2024. His executors are unsure whether and how the June 2020 gift is charged to inheritance tax. Explain the IHT treatment of this lifetime gift, including the effect of the nil rate band, annual exemptions and taper relief. (7 marks)",
    maxMarks: 7,
    rubric: [
      "An outright gift to another individual is a potentially exempt transfer (PET) at the time it is made.",
      "A PET becomes exempt if the donor survives seven years; here Reginald died within seven years, so the gift becomes chargeable.",
      "The annual exemption of £3,000 for 2020/21 (and the £3,000 brought forward from the previous year, if unused) can reduce the chargeable value.",
      "The chargeable amount is set against the nil rate band (£325,000) available at death before any tax is charged.",
      "IHT is charged at 40% on the amount of the failed PET exceeding the available nil rate band.",
      "Taper relief reduces the tax (not the transfer value) because death occurred more than three but less than seven years after the gift.",
      "For a gift made four to five years before death, taper relief reduces the tax payable by 40%.",
    ],
  },
  {
    id: "ATX-W-09",
    paper: "ATX",
    area: "D",
    topic: "Business property relief",
    stem: "Marta Selwood owns several assets she expects to leave on death: her 100% holding in an unquoted trading company (owned 8 years), a 3% holding in a quoted company (owned 10 years), a portfolio of let residential properties, and a large cash deposit. She wants to know which assets will attract business property relief (BPR) for inheritance tax. Explain the conditions for BPR and, applying them, indicate the likely rate of relief on each asset. (7 marks)",
    maxMarks: 7,
    rubric: [
      "BPR reduces the value transferred of qualifying business (relevant) property for IHT purposes.",
      "The property must generally have been owned for at least two years before the transfer — Marta meets this on the relevant holdings.",
      "Unquoted trading company shares qualify for 100% relief, so her 100% trading company holding attracts 100% BPR.",
      "A minority holding in a quoted company does not qualify (relief for quoted shares needs a controlling holding), so the 3% quoted holding gets no relief.",
      "The relief is denied for businesses consisting wholly or mainly of dealing in or holding investments, so the let residential property portfolio does not qualify.",
      "Cash held as an investment (an excepted asset) is not relevant business property and attracts no relief.",
      "Only the trading company shares therefore attract BPR (at 100%); the other assets remain fully chargeable.",
    ],
  },
  {
    id: "ATX-W-10",
    paper: "ATX",
    area: "D",
    topic: "CGT and IHT interaction on a lifetime gift",
    stem: "Bernard Ashcombe is considering giving his holding of shares in Ashcombe Tools Ltd, an unquoted trading company, to his daughter during his lifetime. The shares stand at a large capital gain and also carry significant value for inheritance tax. Explain how both capital gains tax and inheritance tax can apply to the same lifetime gift, and how the available reliefs interact so that Bernard understands the combined position. (8 marks)",
    maxMarks: 8,
    rubric: [
      "A lifetime gift of the shares is a disposal at market value for CGT, potentially producing a chargeable gain for Bernard.",
      "The same gift is a transfer of value for IHT — as a gift to an individual it is a potentially exempt transfer (PET).",
      "For CGT, gift relief (s165) is available because the shares are in an unquoted trading company, allowing the gain to be held over.",
      "If gift relief is claimed, no CGT arises now and the held-over gain reduces the daughter's base cost.",
      "For IHT, the PET is exempt if Bernard survives seven years from the gift.",
      "If Bernard dies within seven years, the PET becomes chargeable, but business property relief may reduce the transfer value (potentially to nil for qualifying unquoted trading shares held two years).",
      "The same asset can therefore be relieved from both taxes — gift relief deferring the CGT and BPR reducing the IHT.",
      "Advice should note the interaction: BPR could be lost if the daughter no longer holds qualifying business property at Bernard's death, exposing the gift to IHT even though CGT was deferred.",
    ],
  },
  {
    id: "ATX-W-11",
    paper: "ATX",
    area: "E",
    topic: "Corporation tax — marginal relief and associated companies",
    stem: "Halvard Systems Ltd expects taxable total profits of £180,000 for its year ended 31 March 2025. Its director is unsure of the rate of corporation tax that will apply and has heard that other companies he controls could affect the position. Explain how the corporation tax rate and marginal relief operate for the year, and how associated companies affect the calculation. (6 marks)",
    maxMarks: 6,
    rubric: [
      "For the financial year 2024 the main rate of corporation tax is 25% and the small profits rate is 19%.",
      "The small profits rate applies where augmented profits do not exceed the lower limit of £50,000 and the main rate applies above the upper limit of £250,000.",
      "Where profits fall between the limits (as here, £180,000), the main rate applies but marginal relief reduces the effective rate.",
      "Marginal relief is computed using the standard fraction of 3/200 applied to the difference between the upper limit and augmented profits, scaled by the ratio of taxable total profits to augmented profits.",
      "The £50,000 and £250,000 limits are divided by the number of associated companies plus one.",
      "So if Halvard has associated companies, the limits are reduced, making it more likely the profits fall above the upper limit and are taxed fully at 25%.",
    ],
  },
  {
    id: "ATX-W-12",
    paper: "ATX",
    area: "E",
    topic: "Group relief and chargeable gains groups",
    stem: "Meridian Holdings Ltd owns 90% of Trading Sub A Ltd and 80% of Trading Sub B Ltd; Sub A in turn owns 85% of Sub C Ltd. One group company has trading losses while others are profitable, and the group is planning to move a chargeable asset between two of the companies as part of a reorganisation. Explain how group relief for losses and the no gain/no loss treatment for chargeable assets apply within this group, including the ownership thresholds involved. (7 marks)",
    maxMarks: 7,
    rubric: [
      "Group relief allows a company to surrender current-period trading losses (and certain other amounts) to another group company to set against its profits.",
      "A group relief group requires a 75% relationship: one company is a 75% subsidiary of another, or both are 75% subsidiaries of a third.",
      "The 75% test looks at direct and indirect ownership of ordinary share capital, plus entitlement to profits and assets on a winding up.",
      "For indirect holdings the effective interest is multiplied through the chain (e.g. 90% x 85% for Sub C via Sub A) and must still meet the relevant threshold.",
      "A capital gains group exists where each company is a 75% direct subsidiary and the top company has an effective interest of over 50% in each member.",
      "Chargeable assets transferred between members of a capital gains group are treated as transferred on a no gain/no loss basis (s171 TCGA 1992).",
      "This means no chargeable gain arises on the intra-group transfer; the gain is deferred until the asset leaves the group.",
    ],
  },
  {
    id: "ATX-W-13",
    paper: "ATX",
    area: "E",
    topic: "Degrouping charge",
    stem: "Two years ago, Calder Group transferred a warehouse to its subsidiary Fenwick Ltd on a no gain/no loss basis within the capital gains group. Calder Group now plans to sell the entire shareholding in Fenwick Ltd to an unconnected buyer, with the warehouse still owned by Fenwick. Explain the degrouping charge that may arise on this sale and how it is dealt with for tax purposes. (6 marks)",
    maxMarks: 6,
    rubric: [
      "A degrouping charge can arise when a company leaves a capital gains group still owning an asset transferred to it intra-group in the previous six years.",
      "Fenwick Ltd received the warehouse on a no gain/no loss basis and is now leaving the group within six years, so the charge is triggered.",
      "The company leaving is treated as having sold and immediately reacquired the asset at its market value at the date of the original intra-group transfer.",
      "The resulting gain (or loss) is computed by reference to that deemed disposal.",
      "Under the current rules the degrouping gain is added to the consideration for the disposal of the shares in the leaving company (Fenwick).",
      "Where the substantial shareholding exemption applies to the share disposal, the degrouping gain added to the proceeds can effectively be exempt.",
    ],
  },
  {
    id: "ATX-W-14",
    paper: "ATX",
    area: "E",
    topic: "Residence, overseas move and double tax relief",
    stem: "Selina Ortega, previously UK resident for many years, is moving overseas to take up full-time employment abroad. She will keep a UK house and expects to make several return visits during the year. She will also continue to receive some UK rental income and some foreign employment income. Advise Selina on how her UK residence status is determined and how double taxation relief could apply to income taxed in both countries. (7 marks)",
    maxMarks: 7,
    rubric: [
      "UK residence for a tax year is determined by the statutory residence test (SRT).",
      "The SRT is applied in order: the automatic overseas tests first, then the automatic UK tests, then the sufficient ties test.",
      "An individual can be automatically non-UK resident if, broadly, they work full-time overseas and spend fewer than the permitted number of days in the UK.",
      "If not conclusively decided by the automatic tests, the sufficient ties test combines the number of UK ties with the number of days spent in the UK.",
      "Relevant ties include a family tie, accommodation tie, work tie, 90-day tie and (for leavers) a country tie.",
      "If she remains UK resident, she is in principle taxable on worldwide income; UK-source rental income remains taxable in the UK regardless of residence.",
      "Double taxation relief prevents the same income being taxed twice — by treaty relief or unilateral credit relief, giving credit for overseas tax up to the UK tax on the same income (the lower of the two).",
    ],
  },
  {
    id: "ATX-W-15",
    paper: "ATX",
    area: "E",
    topic: "Ethics — avoidance, evasion and adviser duties",
    stem: "A new client, Dominic Vale, asks your firm to prepare his tax return. He proposes deliberately omitting a large amount of cash rental income 'because it can't be traced', and separately asks whether an artificial scheme he read about could legitimately reduce his tax. Discuss the ethical and professional issues raised, distinguishing tax avoidance from tax evasion, and explain the adviser's duties in responding. (7 marks)",
    maxMarks: 7,
    rubric: [
      "Tax evasion is illegal — deliberately concealing income or providing false information to reduce tax; omitting the cash rental income is evasion.",
      "Tax avoidance is arranging affairs within the law to reduce tax, though artificial or aggressive schemes may be challenged and are contrary to the profession's ethical standards.",
      "The adviser must act with integrity and objectivity and comply with the fundamental principles and the profession's standards for tax planning.",
      "The adviser must not be associated with the deliberate omission of income; to do so could make the firm complicit and give rise to legal and professional sanctions.",
      "The adviser should explain to the client that the income must be declared and decline to act if the client insists on omitting it.",
      "Under the money laundering regulations, the proceeds of tax evasion are criminal property; the firm's nominated officer (MLRO) may need to make a suspicious activity report to the authorities.",
      "The adviser must not 'tip off' the client that a report has been or may be made, and should consider ceasing to act.",
    ],
  },

  // ============================ AAA (15) ============================
  {
    id: "AAA-W-01",
    paper: "AAA",
    area: "D",
    topic: "Audit risk identification",
    stem: "You are planning the audit of Torvane Logistics plc for the year ending 31 December 2025. During the year the company acquired a competitor, adopted a new revenue-recognition system for its subscription contracts, capitalised significant development costs on a new tracking platform, and breached a bank covenant that was later renegotiated. Directors' bonuses are based on reported profit. Identify and explain FOUR audit risks arising from this scenario. (8 marks)",
    maxMarks: 8,
    rubric: [
      "The acquisition raises risk around correct accounting for the business combination, including identification and fair valuation of assets, liabilities and goodwill.",
      "The new revenue-recognition system and subscription contracts create risk that revenue is recognised in the wrong period or measured incorrectly (allocation over the contract term).",
      "Capitalised development costs risk being recognised when the strict criteria for capitalisation are not met, overstating assets and profit.",
      "The covenant breach indicates possible going concern or liquidity issues that must be properly assessed and disclosed.",
      "Profit-based directors' bonuses create an incentive to manipulate results, increasing the risk of management bias and fraud.",
      "Overall this raises the risk of material misstatement and points to a higher assessed risk requiring more persuasive audit evidence.",
      "The new system may also give rise to control risk if data was migrated or controls were not operating throughout the period.",
      "For each risk the response should link the scenario feature to the specific financial-statement assertion affected (e.g. existence, valuation, cut-off, completeness).",
    ],
  },
  {
    id: "AAA-W-02",
    paper: "AAA",
    area: "D",
    topic: "Auditing accounting estimates (ISA 540)",
    stem: "Brackwell Insurance Ltd carries a large provision for outstanding claims, estimated by management using actuarial assumptions about claim frequency and average settlement values. Explain the audit procedures you would perform to obtain sufficient appropriate audit evidence over this accounting estimate in accordance with ISA 540 (Revised) Auditing Accounting Estimates. (7 marks)",
    maxMarks: 7,
    rubric: [
      "Obtain an understanding of how management makes the estimate, including the method, assumptions and data used.",
      "Evaluate whether the method and the significant assumptions are appropriate and consistent with the applicable financial reporting framework.",
      "Test the reliability and accuracy of the underlying data used in the estimate (e.g. historical claims records).",
      "Assess whether the assumptions (claim frequency and average settlement value) are reasonable by reference to external and industry data.",
      "Consider using an auditor's expert to evaluate the actuarial assumptions and methodology.",
      "Review the outcome of prior-period estimates against actual settlements to assess management's estimation accuracy (retrospective review) and any indicators of management bias.",
      "Evaluate whether disclosures about estimation uncertainty are adequate, and perform a 'stand-back' assessment of whether the estimate is reasonable or misstated.",
    ],
  },
  {
    id: "AAA-W-03",
    paper: "AAA",
    area: "E",
    topic: "Going concern (ISA 570)",
    stem: "During the completion of the audit of Halden Manufacturing Ltd, you note the company has net current liabilities, has lost its largest customer, and is in negotiation to refinance a loan that falls due three months after the year end. Management has prepared cash flow forecasts supporting the going concern basis. Explain the audit procedures you would perform in relation to the going concern assumption, and how your reporting would be affected by the outcome. (8 marks)",
    maxMarks: 8,
    rubric: [
      "Evaluate management's assessment of going concern, covering at least twelve months from the date of the financial statements.",
      "Obtain and review the cash flow forecasts and assess the reasonableness of the underlying assumptions.",
      "Perform sensitivity analysis on the forecasts to test the impact of plausible downside scenarios (e.g. slower sales after losing the customer).",
      "Obtain evidence about the status of the loan refinancing, such as correspondence with the bank or draft facility agreements.",
      "Obtain written representations from management on their plans and the feasibility of those plans.",
      "If the going concern basis is appropriate but a material uncertainty exists and is adequately disclosed, issue an unmodified opinion with a 'Material Uncertainty Related to Going Concern' section.",
      "If the material uncertainty is not adequately disclosed, the opinion is modified (qualified or adverse) because of the misstatement.",
      "If the going concern basis is inappropriate but the statements are prepared on that basis, an adverse opinion is required.",
    ],
  },
  {
    id: "AAA-W-04",
    paper: "AAA",
    area: "D",
    topic: "Group audits (ISA 600)",
    stem: "Your firm is the group auditor of Camberwell Group plc, which has several subsidiaries, two of which are audited by other unrelated firms (component auditors) in overseas jurisdictions. Explain the responsibilities of the group engagement team when component auditors are involved, and the procedures required to obtain sufficient appropriate audit evidence over the components in accordance with ISA 600. (7 marks)",
    maxMarks: 7,
    rubric: [
      "The group engagement partner retains sole responsibility for the group audit opinion, even where component auditors are involved.",
      "The group team must obtain an understanding of the group, its components and their environment, and identify significant components.",
      "The group team must evaluate whether the component auditors are competent and independent and understand the relevant ethical and professional requirements.",
      "The group team should be involved in the component auditors' risk assessment and communicate its requirements clearly (e.g. via group instructions and materiality levels for components).",
      "For significant components, the group team determines the type of work to be performed and remains involved in that work.",
      "The group team should review the component auditors' documentation on significant matters and evaluate the adequacy of their work.",
      "The group team performs procedures on the consolidation process, including consolidation adjustments and elimination of intra-group balances and transactions.",
    ],
  },
  {
    id: "AAA-W-05",
    paper: "AAA",
    area: "D",
    topic: "Auditing financial instruments",
    stem: "Ferrisdale Capital Ltd holds a portfolio of complex financial instruments, including derivatives and unlisted equity investments measured at fair value, some of which have no observable market price. Explain the audit risks and the procedures you would perform to obtain sufficient appropriate audit evidence over the valuation of these financial instruments. (7 marks)",
    maxMarks: 7,
    rubric: [
      "Complex and illiquid instruments carry high valuation risk because fair value relies on models and unobservable inputs (Level 3 inputs).",
      "Confirm the existence and terms of the instruments directly with counterparties or custodians.",
      "For instruments with observable prices, agree the fair value to reliable external market data at the year end.",
      "For instruments valued using models, evaluate the appropriateness of the valuation model and the reasonableness of the inputs and assumptions.",
      "Consider using an auditor's expert to assist in evaluating complex valuations.",
      "Assess management's competence, and the design and operation of controls over the valuation process.",
      "Evaluate whether the disclosures on fair value hierarchy, valuation techniques and estimation uncertainty comply with the reporting framework.",
    ],
  },
  {
    id: "AAA-W-06",
    paper: "AAA",
    area: "B",
    topic: "Ethical threat — self-review",
    stem: "Your firm audits Pelham Retail Ltd and has been asked by the client to also prepare the company's financial statements and calculate its tax provision, because the finance team is short-staffed. Pelham is not a public interest entity. Evaluate the ethical threats created by accepting this additional work and explain the safeguards that could be applied. (6 marks)",
    maxMarks: 6,
    rubric: [
      "Preparing the financial statements and the tax provision that the firm will later audit creates a self-review threat.",
      "There may also be a management threat if the firm takes on responsibilities that are properly those of management.",
      "The firm must not assume management responsibilities; management must accept responsibility for the amounts and make all significant judgements.",
      "Safeguards include using separate teams (different personnel) for the preparation work and the audit.",
      "An independent review of the audit work by a partner or professional not involved in the other engagement.",
      "If the threats cannot be reduced to an acceptable level, the firm should decline the non-audit work (stricter rules apply to public interest entities).",
    ],
  },
  {
    id: "AAA-W-07",
    paper: "AAA",
    area: "B",
    topic: "Ethical threat — fee dependence",
    stem: "Your firm has audited Adair Foods Ltd for several years. The audit and non-audit fees from Adair have grown so that they now represent about 18% of the firm's total annual fee income, and the audit partner is a personal friend of Adair's finance director who has offered the partner a weekend at his holiday villa. Evaluate the ethical threats present and recommend appropriate safeguards. (6 marks)",
    maxMarks: 6,
    rubric: [
      "High recurring fees from one client create a self-interest threat because the firm becomes financially dependent on retaining the client.",
      "Where total fees from a client regularly exceed the relevant proportion of the firm's income, the code requires action (e.g. review and, for listed clients, a lower threshold applies).",
      "The close personal friendship between the partner and the finance director creates a familiarity threat.",
      "The offer of a weekend at the villa is a gift/hospitality that creates a self-interest and familiarity threat and, unless trivial and inconsequential, should be declined.",
      "Safeguards include reducing dependence on the client, an independent (engagement quality) review of the audit, and consulting a professional body.",
      "Rotating the audit partner would reduce the familiarity threat, and the hospitality should not be accepted.",
    ],
  },
  {
    id: "AAA-W-08",
    paper: "AAA",
    area: "E",
    topic: "Audit opinion — misstatement (ISA 705)",
    stem: "You are completing the audit of Nordholt Engineering Ltd. Management has refused to write down obsolete inventory that is clearly overstated by an amount you consider material but not pervasive to the financial statements as a whole. All other areas of the audit are satisfactory. Explain, with reference to ISA 705, the type of audit opinion you would issue and why, and briefly contrast this with the opinion that would be appropriate if the effect were pervasive. (6 marks)",
    maxMarks: 6,
    rubric: [
      "The overstated inventory is a misstatement — the financial statements contain an error the directors will not correct.",
      "The auditor has obtained sufficient evidence; this is a disagreement (material misstatement), not a limitation on scope.",
      "Because the misstatement is material but not pervasive, a qualified ('except for') opinion is appropriate.",
      "The report includes a 'Basis for Qualified Opinion' section explaining the matter and, where practicable, quantifying the financial effect.",
      "If the misstatement were both material and pervasive to the financial statements as a whole, an adverse opinion would be required.",
      "An adverse opinion states that the financial statements do not give a true and fair view (are not fairly presented).",
    ],
  },
  {
    id: "AAA-W-09",
    paper: "AAA",
    area: "E",
    topic: "Audit opinion — scope limitation (ISA 705)",
    stem: "During the audit of Westmere Trading Ltd, you were unable to attend the year-end inventory count because you were appointed after the year end, and there are no alternative procedures that allow you to verify the inventory quantities. Inventory is a very significant balance and central to the financial statements. Explain, with reference to the ISA 705 opinion matrix, the appropriate audit opinion, and how your conclusion would differ if inventory were only a small part of the statements. (6 marks)",
    maxMarks: 6,
    rubric: [
      "This is an inability to obtain sufficient appropriate audit evidence (a limitation on the scope of the audit), not a misstatement.",
      "The auditor must consider whether the possible effects of the undetected misstatement are material and whether they are pervasive.",
      "Because inventory is very significant and central, the possible effects are both material and pervasive.",
      "A material and pervasive inability to obtain evidence leads to a disclaimer of opinion.",
      "With a disclaimer, the auditor does not express an opinion on the financial statements.",
      "If inventory were only a small part of the statements (material but not pervasive), a qualified 'except for' opinion would instead be appropriate.",
    ],
  },
  {
    id: "AAA-W-10",
    paper: "AAA",
    area: "E",
    topic: "Key audit matters (ISA 701)",
    stem: "Your firm audits Crestline plc, a listed company, and the engagement partner is finalising the auditor's report. Explain what key audit matters (KAM) are, how the auditor determines them under ISA 701, and how they are reported. Explain also how a KAM differs from a modification to the audit opinion. (6 marks)",
    maxMarks: 6,
    rubric: [
      "Key audit matters are those matters that, in the auditor's professional judgement, were of most significance in the audit of the current period's financial statements.",
      "They are selected from matters communicated with those charged with governance.",
      "The auditor considers areas of higher assessed risk of material misstatement, significant judgements and the effect of significant events or transactions.",
      "KAM are reported in a separate section of the auditor's report, describing the matter and how it was addressed in the audit.",
      "Communicating KAM is required for listed entities and does not change the audit opinion.",
      "A KAM is not a modification of the opinion — it provides additional information about the audit, whereas a modification (qualified, adverse or disclaimer) changes the opinion because of a misstatement or lack of evidence.",
    ],
  },
  {
    id: "AAA-W-11",
    paper: "AAA",
    area: "E",
    topic: "Subsequent events (ISA 560)",
    stem: "After the reporting date but before the auditor's report on Lindqvist Retail Ltd was signed, a major customer went into liquidation owing a material balance, and a fire destroyed an uninsured warehouse. Explain the auditor's responsibilities for subsequent events under ISA 560 and how each of these two events should be treated in the financial statements. (6 marks)",
    maxMarks: 6,
    rubric: [
      "The auditor must perform procedures to obtain sufficient evidence that events occurring between the reporting date and the date of the auditor's report requiring adjustment or disclosure are identified.",
      "An adjusting event provides evidence of conditions that existed at the reporting date.",
      "The customer liquidation provides evidence that the receivable was likely irrecoverable at the year end, so it is an adjusting event and the receivable should be written down.",
      "A non-adjusting event reflects conditions arising after the reporting date.",
      "The warehouse fire arose after the year end and is a non-adjusting event, so no adjustment is made but material non-adjusting events should be disclosed.",
      "The auditor should assess whether management has appropriately adjusted or disclosed each event and consider the impact on the auditor's report if they have not.",
    ],
  },
  {
    id: "AAA-W-12",
    paper: "AAA",
    area: "C",
    topic: "Quality management (ISQM 1 / ISA 220)",
    stem: "A trainee at your firm asks how audit quality is maintained both across the firm and on an individual engagement. Explain the purpose of a system of quality management under ISQM 1 and the responsibilities for quality on an individual audit engagement under ISA 220 (Revised), including the role of an engagement quality review. (6 marks)",
    maxMarks: 6,
    rubric: [
      "ISQM 1 requires the firm to design, implement and operate a system of quality management using a risk-based approach.",
      "The firm sets quality objectives, identifies and assesses quality risks, and designs responses to those risks.",
      "The system covers areas such as governance and leadership, relevant ethical requirements, acceptance and continuance of engagements, engagement performance, resources and information/communication, with ongoing monitoring and remediation.",
      "Under ISA 220 the engagement partner is responsible for the overall quality of the individual audit engagement.",
      "The engagement partner ensures the team has appropriate competence, complies with ethical requirements, and that sufficient appropriate evidence supports the opinion, with appropriate direction, supervision and review.",
      "An engagement quality review is an objective evaluation of the significant judgements and conclusions by a reviewer not on the engagement team, required for listed entities and other higher-risk engagements before the report is issued.",
    ],
  },
  {
    id: "AAA-W-13",
    paper: "AAA",
    area: "D",
    topic: "Audit procedures — revenue recognition",
    stem: "Oakbridge Software Ltd sells multi-year software licences bundled with support services, and recognises a large part of the total contract price as revenue on delivery of the licence. You have assessed revenue recognition as a significant risk. Explain the audit procedures you would perform to obtain sufficient appropriate audit evidence that revenue is recognised appropriately. (7 marks)",
    maxMarks: 7,
    rubric: [
      "Obtain an understanding of the revenue streams and the terms of the bundled contracts (licence plus support).",
      "For a sample of contracts, inspect the agreements to identify the separate performance obligations and the total transaction price.",
      "Evaluate whether management has appropriately allocated the transaction price between the licence and the support services on a relative stand-alone selling price basis.",
      "Assess whether revenue for each obligation is recognised at the right time — at a point in time for the licence and over time for the support services.",
      "Perform cut-off testing around the year end to ensure revenue is recorded in the correct period.",
      "Recalculate deferred revenue and agree it to supporting documentation.",
      "Perform analytical procedures comparing revenue and margins with prior periods and expectations, investigating unusual movements, and consider the risk of management override or bias.",
    ],
  },
  {
    id: "AAA-W-14",
    paper: "AAA",
    area: "B",
    topic: "Money laundering and NOCLAR",
    stem: "During the audit of Vantor Trading Ltd, the audit team discovers what appears to be a deliberate scheme by management to disguise payments that may represent proceeds of crime, and evidence suggesting the company has not complied with environmental laws. Explain the audit firm's responsibilities regarding money laundering and the auditor's responsibilities under the framework for non-compliance with laws and regulations (NOCLAR). (7 marks)",
    maxMarks: 7,
    rubric: [
      "The firm must have policies and procedures to guard against being used for money laundering, including client due diligence and record keeping.",
      "The firm must appoint a Money Laundering Reporting Officer (nominated officer) to receive internal reports.",
      "Where a team member has knowledge or suspicion of money laundering, an internal report must be made and, where appropriate, a suspicious activity report submitted to the authorities.",
      "The auditor must not 'tip off' the client that a report has been or may be made, as tipping off is a criminal offence.",
      "Under NOCLAR, on identifying suspected non-compliance the auditor should obtain an understanding of the matter and discuss it with management or those charged with governance.",
      "The auditor should evaluate the implications for the financial statements (e.g. provisions or disclosures) and for the audit opinion, and consider whether to report to an appropriate authority.",
      "The auditor documents the matter and considers the impact on the ability to continue the engagement.",
    ],
  },
  {
    id: "AAA-W-15",
    paper: "AAA",
    area: "E",
    topic: "Due diligence and prospective financial information",
    stem: "Your firm has been asked by Kestrel Ventures Ltd to perform a due diligence review of a target company it intends to acquire, and to provide an assurance report on the target's profit forecast that will support the acquisition. Explain the purpose and nature of a due diligence engagement, and the matters to consider when reporting on prospective financial information. (6 marks)",
    maxMarks: 6,
    rubric: [
      "Due diligence is an investigation of a target business to help the acquirer make an informed decision and identify risks before the acquisition.",
      "It typically covers financial, commercial, tax and legal matters, verifying the target's assets, liabilities, profitability and any hidden liabilities.",
      "A due diligence engagement usually provides limited (negative) assurance rather than the reasonable assurance given in a statutory audit.",
      "Prospective financial information (the profit forecast) is based on assumptions about future events and is inherently uncertain, so it cannot be verified as fact.",
      "The practitioner evaluates whether the assumptions underlying the forecast provide a reasonable basis and are consistent, and whether the forecast is properly prepared on those assumptions.",
      "The assurance report should include a caveat that actual results are likely to differ from the forecast because events and circumstances frequently do not occur as expected.",
    ],
  },
]
