import type { AccaQuestion } from "@/lib/acca-content"
export const ATX_OFFICIAL_QUESTIONS:AccaQuestion[]=[
{id:"ATX-B-O01",paper:"ATX",area:"B",type:"mcq",stem:"A lifetime gift creates a capital gain and is also a chargeable transfer for IHT. What is the correct advisory approach?",options:["Consider each tax independently","Evaluate CGT and IHT together, including available reliefs and later death consequences","Ignore IHT until death","Choose the lowest immediate CGT only"],correct:1,explanation:"ATX requires evaluation of interacting taxes and timing. A relief that defers CGT may affect base cost, while IHT treatment and survival period change the overall result.",marks:2,difficulty:"medium"},
{id:"ATX-B-O02",paper:"ATX",area:"B",type:"mcq",stem:"When comparing incorporation with remaining unincorporated, which evidence is essential?",options:["Corporation tax alone","Total tax, NIC, extraction, gains, future disposal and commercial facts","VAT alone","The client's preferred label"],correct:1,explanation:"The adviser evaluates interacting business and owner taxes across the intended lifecycle, alongside commercial and cash-flow consequences.",marks:2,difficulty:"medium"},
{id:"ATX-B-O03",paper:"ATX",area:"B",type:"mcq",stem:"Why can the lowest headline tax liability be the wrong course?",options:["Tax never matters","It may ignore timing, loss of relief, compliance, cash flow and commercial risk","HMRC chooses automatically","Only ethics matters"],correct:1,explanation:"Advice should compare relevant taxes, timing and non-tax consequences, not optimise a single isolated figure.",marks:2,difficulty:"easy"},
{id:"ATX-C-O01",paper:"ATX",area:"C",type:"mcq",stem:"What distinguishes legitimate tax planning from evasion?",options:["Planning conceals facts","Planning applies law to disclosed facts; evasion dishonestly misstates or conceals","They are identical","Planning requires no evidence"],correct:1,explanation:"Legitimate planning uses available rules transparently. Evasion is illegal dishonesty and must never be recommended.",marks:2,difficulty:"easy"},
{id:"ATX-C-O02",paper:"ATX",area:"C",type:"mcq",stem:"A relief saves tax but locks funds into an unsuitable investment. What should the adviser recommend?",options:["Invest because tax falls","Evaluate investment risk, liquidity and client objectives before any recommendation","Ignore suitability","Maximise relief at any cost"],correct:1,explanation:"Tax is one factor. Commercially sound planning must suit the client's objectives, risk capacity, liquidity and legal requirements.",marks:2,difficulty:"medium"},
{id:"ATX-C-O03",paper:"ATX",area:"C",type:"mcq",stem:"What is the best way to present two planning alternatives?",options:["State only tax saved","Compare assumptions, tax by type and timing, cash effects, conditions, risks and recommendation","Hide uncertainty","Choose the most complex"],correct:1,explanation:"Decision-useful planning makes assumptions and conditions explicit and compares total consequences.",marks:2,difficulty:"easy"},
{id:"ATX-D-O01",paper:"ATX",area:"D",type:"mcq",stem:"A client refuses to correct a material error in a submitted return. What should the adviser do?",options:["Ignore it","Explain obligations and consequences, cease acting if unresolved and consider reporting duties without tipping off","Alter records secretly","Help conceal it"],correct:1,explanation:"The adviser must follow professional and legal obligations, protect confidentiality within its exceptions, avoid association with false information and consider withdrawal and reporting.",marks:2,difficulty:"hard"},
{id:"ATX-D-O02",paper:"ATX",area:"D",type:"mcq",stem:"Which communication is most appropriate for a client choosing a business vehicle?",options:["A list of rates","A clear comparison of relevant tax and commercial consequences, assumptions, deadlines and recommendation","Technical jargon only","An unexplained computation"],correct:1,explanation:"ATX requires advice appropriate to the intended recipient, supported by relevant calculations and clear action.",marks:2,difficulty:"easy"},
{id:"ATX-D-O03",paper:"ATX",area:"D",type:"mcq",stem:"Management supplies an optimistic valuation that drives a relief claim. What demonstrates scepticism?",options:["Accept it","Challenge assumptions, seek support and explain uncertainty and exposure","Increase it","Omit the valuation"],correct:1,explanation:"Professional judgement requires sufficient evidence and transparent treatment of uncertainty.",marks:2,difficulty:"medium"},
{id:"ATX-E-O01",paper:"ATX",area:"E",type:"mcq",stem:"Before combining tax figures from several exhibits, what should be validated?",options:["Font","Tax year, person/entity, units, dates and whether figures are gross or net","Colour only","Largest number"],correct:1,explanation:"Digital tax work begins with controlled evidence; mixed years or bases can invalidate an otherwise accurate computation.",marks:2,difficulty:"easy"},
{id:"ATX-E-O02",paper:"ATX",area:"E",type:"mcq",stem:"Which spreadsheet structure best supports tax advice?",options:["Hard-coded answer","Labelled assumptions, separate computations by tax and timing, and a reconciled summary","Hidden workings","No units"],correct:1,explanation:"Transparent workings allow review, amendment and comparison of alternatives.",marks:2,difficulty:"easy"},
{id:"ATX-E-O03",paper:"ATX",area:"E",type:"mcq",stem:"A client letter should translate spreadsheet results into:",options:["More formulae","Clear liabilities, due dates, conditions, risks and actions","Raw exhibits","Unqualified certainty"],correct:1,explanation:"Digital output must become professional, recipient-appropriate advice.",marks:2,difficulty:"easy"},]
