import type { AccaQuestion } from "@/lib/acca-content"

/* FR bank wave 8a — +75 toward 300 (2026-07-12). */
export const FR_WAVE4A: AccaQuestion[] = [
  /* ───────────── Area A — conceptual & regulatory framework (10) ───────────── */
  {
    id: "FR4-A-01",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "Which of the following is the Conceptual Framework's definition of an ASSET?",
    options: [
      "A present economic resource controlled by the entity as a result of past events",
      "A resource from which future economic benefits are expected to flow, provided the flow is probable and can be measured reliably",
      "A physical or financial resource legally owned by the entity",
      "Any item of expenditure expected to generate revenue in future periods",
    ],
    correct: 0,
    explanation:
      "The current Framework defines an asset as a present economic resource controlled by the entity as a result of past events, where an economic resource is a right with the potential to produce economic benefits. 'Probable flow + reliable measurement' is the SUPERSEDED definition; control matters, not legal ownership (e.g. leased assets); and expenditure alone does not create an asset.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR4-A-02",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "According to the Conceptual Framework, the PRIMARY users of general purpose financial reports are:",
    options: [
      "The entity's management and directors",
      "Existing and potential investors, lenders and other creditors",
      "Tax authorities and financial regulators",
      "All stakeholders with any interest in the entity, weighted equally",
    ],
    correct: 1,
    explanation:
      "The Framework identifies existing and potential investors, lenders and other creditors — those who cannot demand information directly — as the primary users. Management has internal access so is NOT a primary user (a classic trap); regulators and tax authorities have their own information powers; and while others may find reports useful, they are not the target audience.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-A-03",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "Torbrook Co's net assets were $900,000 at 1 January and $1,150,000 at 31 December. During the year the owners introduced capital of $80,000 and dividends of $30,000 were paid. General prices rose 6% in the year. Under MONEY (nominal) financial capital maintenance, what is profit for the year?",
    options: [
      "$200,000",
      "$250,000",
      "$146,000",
      "$170,000",
    ],
    correct: 0,
    explanation:
      "Money financial capital maintenance: profit = closing net assets 1,150 − opening 900 − capital introduced 80 + dividends 30 = $200,000. $250,000 ignores transactions with owners; $146,000 deducts the 6% inflation adjustment on opening capital ($54,000) — that is REAL capital maintenance; $170,000 forgets to add back the dividends.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-A-04",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "Under the Conceptual Framework, an entity should DERECOGNISE an asset when:",
    options: [
      "The asset becomes fully depreciated",
      "The asset's fair value falls below its carrying amount",
      "The entity loses control of all or part of the asset",
      "The asset is no longer used in the entity's main operations",
    ],
    correct: 2,
    explanation:
      "Derecognition normally occurs when the entity loses control of all or part of the recognised asset (for liabilities, when it no longer has a present obligation). Full depreciation does not remove an asset still controlled and in use; a fall in fair value triggers impairment testing, not derecognition; and idle assets remain recognised while controlled.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-A-05",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "Shortly before its 31 December year end, Marwell Co's directors resolved to cease trading and liquidate the company within three months of the year end. There is no realistic alternative. How should the 31 December financial statements be prepared?",
    options: [
      "On the going concern basis, because the company was still trading at the year end",
      "On a basis other than going concern (e.g. break-up values), with disclosure of that basis",
      "On the going concern basis, with the intention to liquidate treated as a non-adjusting event",
      "No financial statements are required once liquidation has been decided",
    ],
    correct: 1,
    explanation:
      "Going concern assumes the entity will continue in operation for the foreseeable future. Where management intends to liquidate and has no realistic alternative, the statements must be prepared on ANOTHER basis, with that basis disclosed. Trading at the year-end date is irrelevant to the forward-looking assessment; the decision is not a mere non-adjusting event; and statutory reporting obligations continue.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR4-A-06",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "Which statement about measurement bases in the Conceptual Framework is correct?",
    options: [
      "Value in use reflects entity-specific assumptions, whereas fair value reflects the assumptions of market participants",
      "Fair value reflects entity-specific assumptions, whereas value in use reflects market participants' assumptions",
      "Historical cost is a current value measurement basis",
      "Current cost is the price that would be received to sell the asset today",
    ],
    correct: 0,
    explanation:
      "Value in use is an entity-specific current value — the present value of the cash flows THE ENTITY expects from using the asset — while fair value is a market-based exit price using market participants' assumptions. The second option reverses the two; historical cost is not a current value basis; and current cost is an entry (replacement) value, not an exit price.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-A-07",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "Delfern Co bought a machine two years ago for $240,000 (8-year life, nil residual, straight line). An identical new machine would now cost $288,000. What is the machine's carrying amount at the end of year 2 measured at CURRENT COST?",
    options: [
      "$216,000",
      "$180,000",
      "$288,000",
      "$252,000",
    ],
    correct: 0,
    explanation:
      "Current cost restates the asset at the cost of an equivalent asset today, adjusted for the consumption to date: $288,000 × 6/8 = $216,000. $180,000 is the HISTORICAL cost carrying amount (240,000 × 6/8); $288,000 ignores the two years of use consumed; $252,000 deducts only one year's depreciation (288,000 × 7/8).",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR4-A-08",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "Within the international regulatory system, what is the role of the trustees of the IFRS Foundation?",
    options: [
      "To draft and issue IFRS Accounting Standards",
      "To oversee the standard-setting bodies, appoint their members and secure funding — without deciding technical content",
      "To issue interpretations where divergent practice has emerged",
      "To enforce the application of IFRS in each jurisdiction",
    ],
    correct: 1,
    explanation:
      "The trustees govern the IFRS Foundation: they appoint and oversee the IASB (and IFRS Interpretations Committee) and raise funding, but have no role in the technical content of standards. Issuing standards is the IASB's job, interpretations are the IFRS Interpretations Committee's, and enforcement rests with national regulators — the Foundation has no enforcement powers.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR4-A-09",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "Quarleigh Co has a $400,000 loan from Bank A and a $250,000 deposit with Bank B. The directors want to present a single net borrowing of $150,000 'to show the true position'. Which statement is correct?",
    options: [
      "Offsetting is acceptable because both balances are financial instruments",
      "Offsetting is acceptable because the directors intend to use the deposit to repay the loan",
      "The balances must be presented gross: there is no legal right of set-off, and offsetting would obscure rather than represent the substance",
      "The balances may be netted provided the effect is disclosed in the notes",
    ],
    correct: 2,
    explanation:
      "Assets and liabilities are reported separately unless offsetting is required or permitted by a standard — which needs (for financial instruments) a legally enforceable right of set-off and intention to settle net. Balances with DIFFERENT banks carry no such right, so netting misstates liquidity and gearing. Intention alone is insufficient, both being financial instruments is irrelevant, and disclosure cannot legitimise a faulty presentation.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR4-A-10",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "Which of the following meets the Conceptual Framework's definition of INCOME?",
    options: [
      "Cash received from issuing new ordinary shares",
      "A gain arising on the upward revaluation of a property",
      "Cash received from a new five-year bank loan",
      "Cash collected from an existing trade receivable",
    ],
    correct: 1,
    explanation:
      "Income is an increase in assets (or decrease in liabilities) that increases equity, OTHER than contributions from owners — a revaluation gain qualifies even though it is reported in OCI rather than profit. A share issue is a contribution from owners; a loan increases assets and liabilities equally (no equity change); collecting a receivable merely swaps one asset for another.",
    marks: 2,
    difficulty: "medium",
  },

  /* ───────────── Area B — accounting for transactions (30) ───────────── */
  {
    id: "FR4-B-01",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Arlingham Co bought raw materials with a list price of $200,000, subject to a 5% trade discount. It also paid import duties of $12,000, transport of the materials to its warehouse of $8,000, storage of finished goods awaiting sale of $6,000 and abnormal wastage of $4,000. Under IAS 2, what is the cost of the inventory?",
    options: [
      "$210,000",
      "$216,000",
      "$214,000",
      "$230,000",
    ],
    correct: 0,
    explanation:
      "IAS 2 cost = purchase price net of trade discount (200,000 − 10,000) + import duties 12,000 + carriage inwards 8,000 = $210,000. Storage of FINISHED goods and abnormal waste are expensed. $216,000 wrongly includes the storage; $214,000 wrongly includes the abnormal wastage; $230,000 ignores the trade discount and includes both excluded costs.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-B-02",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Belmayne Co's closing inventory comprises three product lines ($'000): Line 1 cost 40, NRV 55; Line 2 cost 30, NRV 22; Line 3 cost 25, NRV 27. Under IAS 2, at what amount is total inventory measured, in $'000?",
    options: [
      "87",
      "95",
      "104",
      "65",
    ],
    correct: 0,
    explanation:
      "IAS 2 applies lower of cost and NRV ITEM BY ITEM (or by similar groups): 40 + 22 + 25 = 87. 95 compares AGGREGATE cost (95) with aggregate NRV (104) — offsetting Line 2's loss against other lines' unrealised gains is not allowed; 104 values everything at NRV; 65 writes the loss-making Line 2 down to nil instead of to its NRV of 22.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-B-03",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Carnforth Co buys an aircraft for $6,000,000, comprising engines $2,400,000 (8-year life), cabin interior $600,000 (5-year life) and the remaining airframe $3,000,000 (20-year life). All have nil residual values. Under IAS 16, what is the total depreciation charge for the first year?",
    options: [
      "$570,000",
      "$300,000",
      "$750,000",
      "$1,200,000",
    ],
    correct: 0,
    explanation:
      "IAS 16 requires each significant component to be depreciated separately: engines 2,400/8 = 300; interior 600/5 = 120; airframe 3,000/20 = 150; total $570,000. $300,000 depreciates the whole cost over the airframe's 20-year life; $750,000 uses the engines' 8-year life for everything; $1,200,000 uses the shortest (5-year) life for the whole aircraft.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-B-04",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Draycott Co's ship must be overhauled every four years. Its cost on 1 January 20X1 included $80,000 attributed to the first overhaul, depreciated over the four-year cycle. On 1 January 20X4 — a year early — a new overhaul was carried out at a cost of $120,000. What TOTAL charge relating to overhauls appears in profit or loss for the year ended 31 December 20X4?",
    options: [
      "$50,000",
      "$30,000",
      "$120,000",
      "$20,000",
    ],
    correct: 0,
    explanation:
      "Under IAS 16 the new inspection cost is capitalised as a component and the remaining carrying amount of the OLD inspection is derecognised. Old component: 80,000 × 1/4 remaining = 20,000 written off; new component depreciation: 120,000/4 = 30,000; total $50,000. $30,000 forgets the derecognition loss; $120,000 expenses the overhaul outright instead of capitalising it; $20,000 counts only the derecognition.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR4-B-05",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Ellonby Co's property has a carrying amount of $500,000, which includes a previously recognised revaluation surplus of $60,000 on that property. It is now revalued to $410,000. How much of the $90,000 deficit is charged to PROFIT OR LOSS?",
    options: [
      "$30,000",
      "$90,000",
      "Nil",
      "$60,000",
    ],
    correct: 0,
    explanation:
      "Under IAS 16 a revaluation decrease is first taken to OCI to the extent of any existing surplus on THAT asset ($60,000), with only the excess ($90,000 − 60,000 = $30,000) charged to profit or loss. $90,000 sends the whole deficit to P/L, ignoring the surplus; nil assumes the whole deficit can hide in OCI; $60,000 reverses the split.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR4-B-06",
    paper: "FR",
    area: "B",
    type: "number",
    stem: "Farrowden Co finances construction from its GENERAL borrowings: a 10% loan of $2,000,000 and an 8% loan of $6,000,000, both outstanding all year. Expenditure of $1,200,000 on a qualifying asset was incurred on 1 April, and the year end is 31 December. Under IAS 23, what borrowing costs are capitalised for the year, in $?",
    numericAnswer: 76500,
    unit: "$",
    explanation:
      "The capitalisation rate is the weighted average of general borrowings: (2m × 10% + 6m × 8%) ÷ 8m = 680,000 ÷ 8,000,000 = 8.5%. Capitalise 1,200,000 × 8.5% × 9/12 = $76,500. Traps: using a simple average of 9% (81,000 for 9 months), or forgetting to time-apportion from 1 April (102,000).",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR4-B-07",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "On 1 January 20X1 Gisburn Co received a government grant of $100,000 towards plant with a 10-year life, using the deferred income method ($10,000 released each year). On 1 January 20X4 Gisburn breached the grant conditions and must repay the full $100,000. Under IAS 20, what is charged to profit or loss on the repayment?",
    options: [
      "$30,000",
      "$100,000",
      "Nil",
      "$70,000",
    ],
    correct: 0,
    explanation:
      "Repayment of an income-type grant is set first against the remaining deferred income balance (100,000 − 3 × 10,000 = 70,000), with the excess of $30,000 — the income already released in 20X1–20X3 — expensed immediately. $100,000 expenses the whole repayment, ignoring the deferred income balance; nil assumes the balance absorbs everything; $70,000 expenses the balance and nets the rest the wrong way round.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR4-B-08",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Which of the following is recognised as an INTANGIBLE ASSET in the financial statements?",
    options: [
      "A customer list acquired as part of a business combination",
      "A brand generated internally through years of successful trading",
      "Staff training costs for a newly installed IT system",
      "An advertising campaign expected to build customer loyalty",
    ],
    correct: 0,
    explanation:
      "IAS 38 permits recognition of intangibles ACQUIRED in a business combination (identifiable and measurable at fair value), including customer lists. Internally generated brands are expressly prohibited; training costs are expensed because the entity cannot control its staff's future services; and advertising expenditure is expensed as incurred despite hoped-for future benefits.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR4-B-09",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Before its year end, Harwicke Co's board approved, announced and began implementing a detailed plan to close a division. Expected costs are: redundancy payments $300,000; retraining staff being redeployed $50,000; rebranding/marketing of the continuing business $40,000; penalty to terminate the closed site's supply contract $60,000. Under IAS 37, what restructuring provision is recognised?",
    options: [
      "$360,000",
      "$450,000",
      "$300,000",
      "$410,000",
    ],
    correct: 0,
    explanation:
      "A restructuring provision includes only DIRECT expenditures necessarily entailed by the restructuring and not associated with ongoing activities: redundancies 300,000 + contract termination penalty 60,000 = $360,000. Retraining/relocating continuing staff and marketing relate to the FUTURE conduct of the business and are excluded. $450,000 includes everything; $300,000 misses the termination penalty; $410,000 wrongly adds the retraining.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-B-10",
    paper: "FR",
    area: "B",
    type: "number",
    stem: "Inglemoor Co recognised a decommissioning provision at its present value of $400,000 at 1 January, discounted at 6%. There were no changes to the estimated cash flows during the year. What finance cost from unwinding the discount is recognised in profit or loss for the year, in $?",
    numericAnswer: 24000,
    unit: "$",
    explanation:
      "As the settlement date approaches, the discounted provision is 'unwound': 400,000 × 6% = $24,000, presented as a FINANCE COST, not an operating expense. The provision rises to $424,000. Common errors: adding the unwinding to the asset (only the initial estimate and changes in estimate adjust the asset) or ignoring the unwinding entirely.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR4-B-11",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Jorvale Co sells machines for $110,000, a price that includes a statutory one-year warranty against existing defects AND an optional three-year servicing plan that customers could buy separately. Standalone selling prices are $108,000 (machine with statutory warranty) and $12,000 (servicing plan). Under IFRS 15, what revenue is recognised when the machine is delivered?",
    options: [
      "$99,000",
      "$110,000",
      "$108,000",
      "$98,000",
    ],
    correct: 0,
    explanation:
      "The statutory ASSURANCE warranty is not a performance obligation (it is an IAS 37 provision), but the servicing plan is a SERVICE-type warranty — a separate performance obligation. Allocate on relative standalone prices: 110,000 × 108/120 = $99,000 on delivery; $11,000 is deferred over the service period. $110,000 ignores the service obligation; $108,000 uses the standalone price instead of allocating the discount; $98,000 deducts the plan's full standalone price (residual method misuse).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-B-12",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Kelsford Co has manufactured goods that its customer has asked it to store until the customer's new warehouse is ready (a bill-and-hold arrangement). Under IFRS 15, which of the following is NOT a required condition for recognising revenue before physical delivery?",
    options: [
      "There is a substantive reason for the arrangement, such as the customer's request",
      "The goods are identified separately as belonging to the customer",
      "The goods are ready for physical transfer to the customer",
      "The customer has paid the full contract price",
    ],
    correct: 3,
    explanation:
      "IFRS 15's bill-and-hold criteria are: a substantive reason for the arrangement; the goods separately identified as the customer's; ready for immediate transfer; and the seller unable to use or redirect them. Full payment is NOT a criterion — revenue recognition depends on transfer of control, not cash collection. The other three options are all genuine requirements.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-B-13",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Lynthorpe Co grants a customer a three-year licence over its accounting software. The software is fully functional when transferred and Lynthorpe has no obligation to update it or otherwise change its functionality during the licence period. Under IFRS 15, when is the licence revenue recognised?",
    options: [
      "At the point in time when the licence period begins and the customer can use the software",
      "Evenly over the three-year licence period",
      "Over the period the customer actually uses the software",
      "When the licence fee is received in cash",
    ],
    correct: 0,
    explanation:
      "This is a RIGHT TO USE the entity's IP as it exists at the grant date — the software's utility does not depend on Lynthorpe's continuing activities — so revenue is recognised at a point in time. Spreading over three years applies only to a RIGHT TO ACCESS licence (where the IP changes over the term, e.g. with mandatory updates); actual usage is not the IFRS 15 criterion here; and cash receipt never drives recognition.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR4-B-14",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "On 1 January 20X5 Merrivale Co delivered a machine to a customer, with the price of $121,000 payable on 31 December 20X6. The contract contains a significant financing component; an appropriate discount rate is 10%. What is recognised for the year ended 31 December 20X5?",
    options: [
      "Revenue $100,000 and interest income $10,000",
      "Revenue $121,000 and no interest income",
      "Revenue $100,000 and interest income $21,000",
      "Revenue $110,000 and interest income $11,000",
    ],
    correct: 0,
    explanation:
      "Revenue is measured at the cash selling price: 121,000 ÷ 1.10² = $100,000 on delivery. The receivable then accretes interest: 100,000 × 10% = $10,000 in 20X5 (and $11,000 in 20X6). Recognising $121,000 ignores the financing component; $21,000 books both years' interest at once; $110,000/$11,000 discounts for only one year despite the two-year credit period.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR4-B-15",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Norbeck Co sold 1,000 units at $90 each (cost $60 each) with a right of return. Using the expected value method it estimates 4% of units will be returned for a full refund. Under IFRS 15, what is recognised at the point of sale?",
    options: [
      "Revenue $86,400 and a refund liability $3,600",
      "Revenue $90,000 and a provision for returns of $2,400",
      "Revenue $90,000 and no liability",
      "Revenue $86,400 and a refund liability $2,400",
    ],
    correct: 0,
    explanation:
      "Revenue is recognised only for goods NOT expected to be returned: 960 × $90 = $86,400, with a refund liability for the expected refunds of 40 × $90 = $3,600 (plus a right-to-recover asset at cost). Measuring the liability at cost ($2,400) confuses the refund owed with the asset recovered; recognising the full $90,000 ignores the variable consideration constraint entirely.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-B-16",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Ollerton Co leases a store for five years. Payments are: a fixed rental of $50,000 per year; an annual uplift linked to the consumer price index; plus 1% of the store's sales each year. Under IFRS 16, which payments are included in the INITIAL lease liability?",
    options: [
      "Only the fixed rentals of $50,000 per year",
      "The fixed rentals plus the index-linked amounts measured using the index at commencement",
      "All three elements, with sales estimated for the lease term",
      "The fixed rentals plus the expected sales-based amounts",
    ],
    correct: 1,
    explanation:
      "The lease liability includes fixed payments and variable payments that depend on an INDEX OR RATE, initially measured using the index at commencement. Variable payments linked to SALES or usage are excluded and expensed as incurred. Option A wrongly drops the index-linked element; options C and D wrongly capitalise performance-based payments, which IFRS 16 excludes because they are avoidable and not liability-like at commencement.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-B-17",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Pemberwick Co enters a five-year lease at $40,000 per annum payable IN ADVANCE, the first payment made on the commencement date. The rate implicit in the lease is 8% (4-year annuity factor 3.31; 5-year annuity factor 3.99). What is the lease liability at commencement?",
    options: [
      "$132,400",
      "$172,400",
      "$159,600",
      "$200,000",
    ],
    correct: 0,
    explanation:
      "With payments in advance, the first $40,000 is paid at commencement, so the liability is the present value of the remaining FOUR payments: 40,000 × 3.31 = $132,400. $172,400 adds the first payment — that is the right-of-use ASSET (132,400 + 40,000); $159,600 discounts five payments as if paid in arrears (40,000 × 3.99); $200,000 fails to discount at all.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR4-B-18",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Quandon Co recognises a right-of-use asset of $240,000 under a four-year lease of a machine. Ownership of the machine transfers to Quandon at the end of the lease. The machine's total useful life is eight years, with an estimated residual value of $40,000. What is the annual depreciation charge?",
    options: [
      "$25,000",
      "$30,000",
      "$60,000",
      "$50,000",
    ],
    correct: 0,
    explanation:
      "Because ownership transfers at the end of the lease, IFRS 16 requires depreciation over the asset's USEFUL LIFE, not the lease term, and a residual value can be recognised: (240,000 − 40,000)/8 = $25,000. $30,000 ignores the residual value; $60,000 depreciates over the four-year lease term; $50,000 uses the lease term with the residual value.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-B-19",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Under IFRS 9, which of the following debt investments is measured at AMORTISED COST?",
    options: [
      "Government bonds held to collect the contractual interest and principal, whose cash flows are solely payments of principal and interest",
      "Corporate bonds managed by both collecting contractual cash flows and selling bonds to manage liquidity",
      "Loan notes acquired for short-term resale to profit from price movements",
      "A convertible bond held to collect its contractual cash flows to maturity",
    ],
    correct: 0,
    explanation:
      "Amortised cost requires BOTH a hold-to-collect business model AND cash flows that are solely payments of principal and interest (SPPI) — option A meets both. 'Collect and sell' leads to FVOCI; held-for-trading is FVTPL; and a convertible bond FAILS the SPPI test (the conversion option is an equity return), so it is FVTPL despite the hold-to-collect intention.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-B-20",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Ravenhall Co made an irrevocable election to measure a long-term equity investment (not held for trading) at fair value through other comprehensive income. Which statement is correct?",
    options: [
      "Fair value changes go to OCI and are never reclassified to profit or loss, while dividends are recognised in profit or loss",
      "Fair value changes go to OCI and are reclassified to profit or loss when the shares are sold",
      "Both fair value changes and dividends are recognised in OCI",
      "Fair value changes go to profit or loss and dividends to OCI",
    ],
    correct: 0,
    explanation:
      "Under the IFRS 9 FVOCI election for equities, fair value movements stay in OCI permanently — NO recycling on disposal (any transfer is within equity) — while dividend income is recognised in profit or loss. Recycling on sale confuses this with the FVOCI treatment of DEBT instruments; the other options misplace dividends or fair value changes.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR4-B-21",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Selcott Co holds corporate bonds measured at amortised cost. Since initial recognition the issuer's credit risk has increased SIGNIFICANTLY, although no default has occurred and the bonds are not yet credit-impaired. Under IFRS 9, the loss allowance is measured at:",
    options: [
      "12-month expected credit losses",
      "Lifetime expected credit losses",
      "Nil, until objective evidence of an incurred loss exists",
      "The full carrying amount of the bonds",
    ],
    correct: 1,
    explanation:
      "IFRS 9's general model moves from 12-month ECL (stage 1) to LIFETIME ECL (stage 2) when credit risk has increased significantly since initial recognition — default is not required. 12-month ECL applies only while no significant increase has occurred; waiting for an incurred loss is the superseded IAS 39 approach; writing off the full amount is only appropriate when there is no reasonable expectation of recovery.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-B-22",
    paper: "FR",
    area: "B",
    type: "number",
    stem: "On 1 January 20X4 Thornbeck Co bought loan notes for $460,000 (nominal value $500,000, 5% coupon paid annually in arrears) to hold to maturity; cash flows are solely principal and interest. The effective interest rate is 8%. What is the carrying amount of the investment at 31 December 20X5, after two full years, in $?",
    numericAnswer: 484544,
    unit: "$",
    explanation:
      "Amortised cost rolls forward at the effective rate: year 1: 460,000 + (460,000 × 8%) − 25,000 coupon = 471,800; year 2: 471,800 + (471,800 × 8% = 37,744) − 25,000 = $484,544. Traps: applying 8% to the nominal $500,000, deducting a coupon of 8% instead of 5% × nominal, or holding the asset at cost and taking only the coupon to income.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR4-B-23",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Ullswick Co has unused tax losses of $800,000 to carry forward. Budgets provide convincing evidence of future taxable profits of only $600,000 against which the losses can be used before they expire. The tax rate is 25%. Under IAS 12, what deferred tax asset is recognised?",
    options: [
      "$150,000",
      "$200,000",
      "$50,000",
      "Nil",
    ],
    correct: 0,
    explanation:
      "A deferred tax asset for unused losses is recognised only to the extent future taxable profit is PROBABLE: 600,000 × 25% = $150,000. $200,000 recognises the full loss (800,000 × 25%) without the probability restriction; $50,000 taxes the unusable portion (200,000 × 25%) instead of the usable one; nil is wrong because $600,000 of profits is supported by convincing evidence.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-B-24",
    paper: "FR",
    area: "B",
    type: "number",
    stem: "At its year end Varley Co has a warranty provision of $120,000. Warranty costs are deductible for tax purposes only when they are actually paid. The tax rate is 30%. Under IAS 12, what deferred tax ASSET arises from the provision, in $?",
    numericAnswer: 36000,
    unit: "$",
    explanation:
      "The provision's carrying amount is $120,000 but its tax base is nil (the future deduction of $120,000 leaves nothing taxable), creating a DEDUCTIBLE temporary difference of $120,000 and a deferred tax asset of 120,000 × 30% = $36,000. The classic error is treating this as a deferred tax liability — a liability whose settlement brings future tax deductions produces an asset, not a liability.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR4-B-25",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Under IAS 21, which of the following is a PRIMARY indicator of an entity's functional currency?",
    options: [
      "The currency that mainly influences the selling prices of its goods and services",
      "The currency in which it pays dividends to its parent",
      "The presentation currency chosen by its parent for the consolidated financial statements",
      "The currency in which its accounting records happen to be maintained",
    ],
    correct: 0,
    explanation:
      "Functional currency is the currency of the primary economic environment: the key indicators are the currency that mainly influences SALES PRICES and the currency of labour, material and other operating costs. Dividend flows and financing are only secondary considerations; the parent's presentation currency is a free choice with no bearing on the subsidiary's economics; and bookkeeping convenience determines nothing.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-B-26",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "On 1 October Wexbridge Co (functional currency: dollar) bought plant priced at 480,000 francs when the rate was 4.0 francs = $1, paying half immediately; the balance remains payable at the 31 December year end, when the rate is 3.2 francs = $1. What exchange difference is recognised in profit or loss for the year?",
    options: [
      "A loss of $15,000",
      "A loss of $30,000",
      "A gain of $15,000",
      "Nil",
    ],
    correct: 0,
    explanation:
      "Only MONETARY items are retranslated at the closing rate. The payable of 240,000 francs was $60,000 at 4.0 and is $75,000 at 3.2 — the franc has strengthened, so the liability grows by a $15,000 LOSS. The plant is non-monetary and stays at $120,000. A $30,000 loss retranslates the full purchase price including the half already settled; a gain misreads the direction (fewer francs per dollar = stronger franc); nil wrongly treats the payable as non-monetary.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR4-B-27",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Yarwell Co had 800,000 ordinary shares in issue on 1 January. On 1 April it issued 200,000 shares at full market price, and on 1 July it made a 1-for-4 bonus issue. Profit attributable to ordinary shareholders for the year was $475,000. What is basic EPS under IAS 33?",
    options: [
      "40.0 cents",
      "38.0 cents",
      "50.0 cents",
      "47.5 cents",
    ],
    correct: 0,
    explanation:
      "The full-price issue is weighted from its date; the bonus issue is treated as if in issue for ALL periods (factor 1.25 applied back to 1 January): (800,000 × 1.25 × 3/12) + (1,000,000 × 1.25 × 3/12) + (1,250,000 × 6/12) = 250,000 + 312,500 + 625,000 = 1,187,500. EPS = 475,000 ÷ 1,187,500 = 40.0c. 38.0c divides by year-end shares (1,250,000); 50.0c ignores the bonus adjustment (950,000); 47.5c divides by 1,000,000, ignoring the bonus shares entirely.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR4-B-28",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Zelworth Co vacated its head office (held under the IAS 16 cost model, carrying amount $300,000) and let it to tenants, transferring it to investment property. Zelworth uses the IAS 40 fair value model; fair value at the transfer date is $380,000. How is the $80,000 difference treated?",
    options: [
      "Recognised in profit or loss as a fair value gain",
      "Treated as an IAS 16 revaluation: recognised in other comprehensive income and held in a revaluation surplus",
      "Credited directly to retained earnings",
      "Ignored: the property continues at $300,000 until sold",
    ],
    correct: 1,
    explanation:
      "On a transfer from owner-occupied property to investment property at fair value, IAS 40 requires the difference AT THE DATE OF CHANGE OF USE to be treated under IAS 16 — an $80,000 revaluation gain in OCI. Only SUBSEQUENT fair value movements go to profit or loss under the fair value model — taking this first uplift to P/L is the classic trap; direct-to-retained-earnings bypasses OCI; and continuing at cost contradicts the fair value model.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR4-B-29",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Under IAS 24, which of the following is a RELATED PARTY of Hollowbeck Co?",
    options: [
      "A company controlled by the spouse of Hollowbeck's chief executive",
      "A customer that accounts for 40% of Hollowbeck's revenue",
      "The bank that provides most of Hollowbeck's loan finance",
      "A supplier with which Hollowbeck has a ten-year exclusive contract",
    ],
    correct: 0,
    explanation:
      "Key management personnel and their CLOSE FAMILY are related parties, and so is any entity those persons control — the CEO's spouse's company qualifies. IAS 24 explicitly states that significant customers, suppliers, providers of finance and others with whom an entity merely transacts significant volumes of business are NOT related parties simply because of the resulting economic dependence.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR4-B-30",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Under IFRS 8, two operating segments may be AGGREGATED into a single reportable segment only when:",
    options: [
      "They have similar economic characteristics and are similar in areas such as products, production processes, customer types, distribution methods and regulatory environment",
      "Each falls below all of the 10% quantitative thresholds",
      "They report to the same segment manager",
      "The directors consider that separate disclosure would damage the entity's competitive position",
    ],
    correct: 0,
    explanation:
      "Aggregation requires BOTH similar economic characteristics (e.g. similar long-term margins) AND similarity in the five listed areas. Falling below the 10% tests makes a segment non-reportable individually but does not itself justify aggregation with a dissimilar segment; a shared manager is irrelevant; and IFRS 8 provides no competitive-harm exemption from segment disclosure.",
    marks: 2,
    difficulty: "medium",
  },

  /* ───────────── Area C — analysing & interpreting (12) ───────────── */
  {
    id: "FR4-C-01",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Aldenham Co's revenue grew 20% this year. During the year it raised selling prices by 8% in line with inflation and acquired a subsidiary on 1 July that contributed to consolidated revenue from that date. Which statement about the 20% revenue trend is correct?",
    options: [
      "It shows a 20% increase in the group's underlying trading volumes",
      "Underlying like-for-like growth is lower than 20%: price inflation and the part-year acquisition must be stripped out before drawing conclusions",
      "The acquisition can be ignored because it was only consolidated from 1 July",
      "Inflation can be ignored because financial statements are prepared in money terms",
    ],
    correct: 1,
    explanation:
      "Headline revenue growth mixes three things: volume, price and changes in group composition. Removing the 8% price effect and the acquired subsidiary's post-acquisition revenue could leave little or no organic volume growth. The part-year effect is exactly why the acquisition DISTORTS the comparison (and will distort next year's too); and comparing money amounts across periods of inflation is the pitfall, not a defence.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-C-02",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Brimscombe Co, an ice-cream producer, prepares interim financial statements for the six months to 30 June, when most of its annual sales occur. The most meaningful comparison for its interim revenue is with:",
    options: [
      "Half of the current year's budgeted annual revenue",
      "The revenue for the six months to 30 June of the PRIOR year",
      "Half of the prior year's actual annual revenue",
      "The revenue of the immediately preceding six months to 31 December",
    ],
    correct: 1,
    explanation:
      "For a seasonal business, the only like-for-like benchmark is the CORRESPONDING interim period of the prior year, which covers the same seasonal pattern. Halving an annual figure assumes revenue accrues evenly (it does not); and comparing the summer half-year with the preceding winter half-year confuses seasonality with performance change.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR4-C-03",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Caldermoor group's overseas subsidiary reported exactly the same local-currency revenue and profit as last year, but the subsidiary's currency weakened significantly against the group's presentation currency. All else being equal, what happens to the GROUP figures?",
    options: [
      "Reported group revenue and profit both fall, but profit margin percentages are largely unaffected",
      "Reported group revenue falls and group profit margins fall sharply",
      "There is no effect, because the subsidiary's performance is unchanged in its own currency",
      "Group revenue is unaffected because revenue is translated at the closing rate",
    ],
    correct: 0,
    explanation:
      "The subsidiary's income and expenses are translated at (average) rates, so a weaker currency shrinks its contribution to group revenue AND profit proportionately — money amounts and trends are distorted, but ratios such as margin % are broadly preserved because numerator and denominator shrink together. Local performance being unchanged does not stop the translated amounts falling; and results are translated at average, not closing, rates.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR4-C-04",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Danemere Co reports operating profit of $260,000 on revenue of $2,000,000. Operating profit includes a $40,000 gain on the disposal of a property and $60,000 of one-off restructuring costs. What is the UNDERLYING operating margin, adjusted for non-recurring items?",
    options: [
      "14%",
      "13%",
      "11%",
      "16%",
    ],
    correct: 0,
    explanation:
      "Underlying operating profit = 260,000 − 40,000 disposal gain + 60,000 one-off costs = 280,000, giving 280/2,000 = 14%. 13% is the unadjusted margin; 11% removes the gain but forgets to add back the restructuring costs; 16% adds back the costs but leaves the disposal gain in. Stripping BOTH one-offs is what makes year-on-year comparison meaningful.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR4-C-05",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Elverstone Co reports ($'000): operating profit 300 (after charging depreciation 120 and amortisation 30); finance costs 30; income tax 60. What is its EBITDA, in $'000?",
    options: [
      "450",
      "420",
      "300",
      "480",
    ],
    correct: 0,
    explanation:
      "EBITDA = operating profit + depreciation + amortisation = 300 + 120 + 30 = 450 (finance costs and tax are already below operating profit). 420 omits the amortisation; 300 is operating profit itself; 480 wrongly adds back finance costs that operating profit never included. Remember EBITDA's limits: it is not defined by IFRS, ignores the real cost of consuming capital assets, and is NOT a cash flow measure (it ignores working capital movements).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-C-06",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Fernacre Co reports revenue of $1,095,000 and cost of sales of $730,000. Inventory was $110,000 at 1 January and $90,000 at 31 December. Using the YEAR-END inventory and a 365-day year, what is the inventory holding period?",
    options: [
      "45 days",
      "50 days",
      "30 days",
      "8 days",
    ],
    correct: 0,
    explanation:
      "Inventory days = closing inventory ÷ cost of sales × 365 = 90/730 × 365 = 45 days. 50 days uses AVERAGE inventory (100/730 × 365) — valid but not what was asked; 30 days divides by revenue instead of cost of sales, mismatching a cost-based numerator with a selling-price denominator; 8 is the inventory TURNOVER ratio (730/90 = 8.1 times) misquoted as days.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR4-C-07",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Gathorne Co's revenue is $876,000, of which $146,000 are cash sales made in its trade counter shop; the rest are credit sales. Year-end trade receivables are $100,000. Using a 365-day year, what is the most meaningful receivables collection period?",
    options: [
      "50 days",
      "42 days",
      "250 days",
      "7 days",
    ],
    correct: 0,
    explanation:
      "Receivables arise only from CREDIT sales of 876 − 146 = $730,000, so 100/730 × 365 = 50 days. 42 days (100/876 × 365) dilutes the ratio with cash sales, understating how slowly credit customers actually pay; 250 days divides by the cash sales figure; 7 is the receivables turnover (730/100 = 7.3 times) misread as days.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR4-C-08",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Harleston Co reports ($'000): revenue 1,000; purchases 730; opening inventory 80; closing inventory 30 (so cost of sales is 780); year-end trade payables 120. Using purchases and a 365-day year, what is the trade payables payment period?",
    options: [
      "60 days",
      "56 days",
      "44 days",
      "6 days",
    ],
    correct: 0,
    explanation:
      "Payables days = payables ÷ credit PURCHASES × 365 = 120/730 × 365 = 60 days — purchases are what created the payables. 56 days uses cost of sales (120/780 × 365), distorted here by the inventory run-down; 44 days uses revenue; 6 is the payables turnover (730/120 ≈ 6.1 times) confused with days.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-C-09",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Immingholt Co has loan notes of $600,000 and equity of $900,000, so gearing measured as debt ÷ (debt + equity) is 40%. It then revalues its properties upwards by $300,000 for the first time. What is gearing immediately after the revaluation?",
    options: [
      "33.3%",
      "40%",
      "50%",
      "66.7%",
    ],
    correct: 0,
    explanation:
      "The revaluation surplus increases equity to $1,200,000 with debt unchanged: 600/(600 + 1,200) = 33.3%. Gearing falls with NO change in borrowings or cash — a key reason to check for revaluations when comparing gearing across companies. 40% forgets the surplus is part of equity; 50% computes debt ÷ equity (a different definition); 66.7% inverts the ratio (equity ÷ capital employed).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-C-10",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "During the year Jerringham Co sold a major line of business, presented as a discontinued operation under IFRS 5. Which statement about analysing Jerringham's performance trend is correct?",
    options: [
      "The prior-year statement of profit or loss comparatives are restated to present the discontinued operation separately, so continuing-operations trends remain comparable",
      "No comparatives are restated, so this year and last year cannot be compared",
      "The prior-year statement of financial position is also restated to show the disposed assets as held for sale",
      "The discontinued operation's results are removed from both years entirely",
    ],
    correct: 0,
    explanation:
      "IFRS 5 requires the SPL comparatives to be re-presented so that discontinued operations appear as a single line in both years — analysts can therefore track continuing operations on a like-for-like basis. The SOFP comparative is NOT restated (held-for-sale classification applies only from the classification date) — a frequent trap; and the discontinued results are re-presented, not deleted.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR4-C-11",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "At the start of the year Kelbrooke Co's plant had a carrying amount of $400,000 with five years of remaining life (straight line, nil residual). The directors reassessed the remaining life as EIGHT years. By how much does this change increase the current year's operating profit compared with the previous basis?",
    options: [
      "$30,000",
      "$50,000",
      "$80,000",
      "Nil, because the change is applied retrospectively",
    ],
    correct: 0,
    explanation:
      "This is a change in accounting ESTIMATE, applied prospectively: the charge falls from 400/5 = $80,000 to 400/8 = $50,000, boosting profit by $30,000 — with no change in underlying trading or cash flow, so profit trends need care. $50,000 quotes the new charge rather than the difference; $80,000 quotes the old charge; retrospective application would be for a change in accounting POLICY or an error, not an estimate.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-C-12",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Lostwithie Co's shares trade at $5.00. Its most recent annual dividend was 35 cents per share and its basic EPS is 50 cents. What is the dividend YIELD?",
    options: [
      "7.0%",
      "10.0%",
      "14.3%",
      "70.0%",
    ],
    correct: 0,
    explanation:
      "Dividend yield = dividend per share ÷ market price = 0.35/5.00 = 7.0%. 10.0% is the EARNINGS yield (0.50/5.00); 14.3 is price ÷ dividend (the inverse, analogous to a 'dividend P/E'); 70.0% is the payout ratio (dividend ÷ EPS), which measures distribution policy, not the investor's income return on price.",
    marks: 2,
    difficulty: "easy",
  },

  /* ───────────── Area D — preparation of financial statements (11) ───────────── */
  {
    id: "FR4-D-01",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Which line item appears in a statement of profit or loss classified by FUNCTION of expense but NOT in one classified by nature of expense?",
    options: [
      "Cost of sales",
      "Revenue",
      "Finance costs",
      "Employee benefits expense",
    ],
    correct: 0,
    explanation:
      "The function format groups expenses by purpose — cost of sales, distribution costs, administrative expenses — whereas the nature format lists raw materials, employee benefits, depreciation, etc. Revenue and finance costs appear under BOTH formats; employee benefits expense is the reverse trap — it is a NATURE caption, absorbed into the functional lines under the function format.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR4-D-02",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Milverton Co's records show ($'000): salaries of sales staff 120; depreciation of delivery vehicles 40; advertising 60; head-office rent 90; carriage inwards 25; carriage outwards 35. What total should be classified as DISTRIBUTION COSTS, in $'000?",
    options: [
      "255",
      "280",
      "220",
      "345",
    ],
    correct: 0,
    explanation:
      "Distribution costs = sales staff salaries 120 + delivery vehicle depreciation 40 + advertising 60 + carriage OUTWARDS 35 = 255. Carriage INWARDS is part of the cost of inventory (cost of sales) and head-office rent is administrative. 280 wrongly adds carriage inwards; 220 omits carriage outwards; 345 sweeps in the head-office rent.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-D-03",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Under IAS 1, items of other comprehensive income must be grouped by whether they may later be reclassified to profit or loss. Which of the following OCI items MAY be reclassified (recycled) to profit or loss in a future period?",
    options: [
      "Exchange differences on translating a foreign operation",
      "Gains on revaluation of property, plant and equipment under IAS 16",
      "Fair value gains on equity investments designated at FVOCI",
      "Fair value gains on investment property under the IAS 40 fair value model",
    ],
    correct: 0,
    explanation:
      "Translation differences on a foreign operation are recycled to profit or loss when the operation is disposed of. IAS 16 revaluation surpluses are NEVER recycled (any transfer goes straight to retained earnings within equity), nor are FVOCI-equity gains under the irrevocable election. IAS 40 fair value gains are not OCI at all — they go directly to profit or loss.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-D-04",
    paper: "FR",
    area: "D",
    type: "number",
    stem: "Norcombe Co is preparing its statement of cash flows using the DIRECT method. Revenue for the year was $940,000; trade receivables were $110,000 at 1 January and $130,000 at 31 December. What cash was received from customers during the year, in $?",
    numericAnswer: 920000,
    unit: "$",
    explanation:
      "Cash from customers = revenue + opening receivables − closing receivables = 940,000 + 110,000 − 130,000 = $920,000. Receivables ROSE by $20,000, meaning $20,000 of this year's sales is still uncollected. The classic error is adding the increase (giving 960,000) — remember an increase in receivables ABSORBS cash.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR4-D-05",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Ottermead Co reports ($'000): cost of sales 600; inventory b/f 80 and c/f 95; trade payables b/f 70 and c/f 60. For the direct-method statement of cash flows, what cash was PAID to suppliers, in $'000?",
    options: [
      "625",
      "610",
      "615",
      "595",
    ],
    correct: 0,
    explanation:
      "First derive purchases: 600 + closing inventory 95 − opening inventory 80 = 615. Then cash paid = purchases + opening payables 70 − closing payables 60 = 625 (payables FELL, so extra cash went out). 610 applies the payables movement directly to cost of sales, skipping the inventory step; 615 stops at purchases, ignoring the payables movement; 595 flips both working capital movements.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR4-D-06",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "While preparing its 20X5 statements, Pellingham Co discovered that fictitious sales of $70,000 had been recorded in 20X4; the related income tax effect is $17,500 (rate 25%). Retained earnings at 1 January 20X5 were previously reported as $840,000. Under IAS 8, what restated opening retained earnings figure appears in the 20X5 statement of changes in equity?",
    options: [
      "$787,500",
      "$770,000",
      "$840,000",
      "$892,500",
    ],
    correct: 0,
    explanation:
      "A material prior-period error is corrected RETROSPECTIVELY: opening retained earnings are restated by the after-tax effect: 840,000 − 70,000 + 17,500 = $787,500, with the 20X4 comparatives also restated. $770,000 ignores the tax saving; $840,000 puts the correction through 20X5 profit instead (double-counting the error's reversal in the trend); $892,500 adjusts in the wrong direction.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR4-D-07",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Quintrell Co has: interest for the year on its 6% $500,000 loan notes; unwinding of the discount on a provision of $8,000; ordinary dividends paid of $20,000; and $12,000 of the loan interest qualifies for capitalisation under IAS 23. What is the FINANCE COSTS line in profit or loss?",
    options: [
      "$26,000",
      "$38,000",
      "$46,000",
      "$58,000",
    ],
    correct: 0,
    explanation:
      "Loan interest 30,000 (6% × 500,000) + unwinding of discount 8,000 − interest capitalised into the qualifying asset 12,000 = $26,000. Equity dividends are a distribution reported in the statement of changes in equity, never a finance cost. $38,000 forgets to remove the capitalised interest; $46,000 wrongly adds the dividends; $58,000 makes both errors.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-D-08",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Redgrave Co's draft accounts show gross profit of $400,000 on revenue of $1,000,000. It is then discovered that $50,000 of depreciation on PRODUCTION plant was charged to administrative expenses instead of cost of sales. What is the effect of correcting the error?",
    options: [
      "Gross profit falls to $350,000 (margin 35%), but profit from operations is unchanged",
      "Both gross profit and profit from operations fall by $50,000",
      "Neither gross profit nor profit from operations changes",
      "Gross profit is unchanged but profit from operations falls by $50,000",
    ],
    correct: 0,
    explanation:
      "Reclassifying the depreciation moves $50,000 from administrative expenses into cost of sales: gross profit falls to $350,000 (35% margin), while total expenses — and therefore operating profit — are unchanged. The other options treat a reclassification as if it created or removed an expense: it only changes WHERE the cost sits, which matters for margin analysis but not for the bottom line.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-D-09",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Sablewick Co has a bank loan repayable in five years, but at 31 December it breached a covenant, entitling the bank to demand immediate repayment. In February, before the financial statements were authorised for issue, the bank formally waived its right for twelve months. Under IAS 1, the loan is presented at 31 December as:",
    options: [
      "A current liability, because at the reporting date Sablewick had no right to defer settlement for at least twelve months",
      "A non-current liability, because the waiver was received before the statements were authorised",
      "A non-current liability, because the directors always expected the breach to be waived",
      "Half current and half non-current",
    ],
    correct: 0,
    explanation:
      "Classification depends on rights EXISTING AT THE REPORTING DATE: the breach made the loan repayable on demand, so it is current; a waiver obtained after the year end is a non-adjusting event (disclosed, not applied). Only a waiver granted ON OR BEFORE the reporting date preserves non-current classification; expectations are irrelevant; and there is no basis to split the balance.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR4-D-10",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Tarraby Co reports: profit for the year $210,000; gain on revaluation of PPE $45,000; fall in fair value of an equity investment held at FVOCI $15,000; ordinary dividends paid $30,000. What is TOTAL comprehensive income for the year?",
    options: [
      "$240,000",
      "$210,000",
      "$270,000",
      "$195,000",
    ],
    correct: 0,
    explanation:
      "Total comprehensive income = profit 210,000 + revaluation gain 45,000 − FVOCI loss 15,000 = $240,000. Dividends are transactions with owners and never enter comprehensive income. $210,000 ignores OCI (or wrongly nets off the dividend); $270,000 ADDS the FVOCI loss instead of deducting it; $195,000 takes the loss but leaves the revaluation gain out.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-D-11",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Under IAS 7, which of the following qualifies as a CASH EQUIVALENT?",
    options: [
      "A government bond acquired two months before its maturity date",
      "Listed equity shares held for short-term trading",
      "A fixed deposit with nine months to maturity when placed",
      "A trade receivable due for settlement within 30 days",
    ],
    correct: 0,
    explanation:
      "Cash equivalents are short-term, highly liquid investments readily convertible to known amounts of cash with insignificant risk of value change — normally maturing within about THREE MONTHS OF ACQUISITION. A two-month bond qualifies. Equities are excluded however liquid (value risk); a nine-month deposit fails the short-maturity test; receivables are working capital, not investments.",
    marks: 2,
    difficulty: "easy",
  },

  /* ───────────── Area E — consolidated financial statements (12) ───────────── */
  {
    id: "FR4-E-01",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Umberleigh Co owns 80% of Skenfrith Co, with NCI measured at its PROPORTIONATE share of net assets. Goodwill is impaired by $50,000 during the year. How is the impairment allocated in the consolidated statements?",
    options: [
      "All $50,000 reduces profit attributable to the owners of the parent; the NCI is unaffected",
      "$40,000 is allocated to the owners of the parent and $10,000 to the NCI",
      "All $50,000 is allocated against the non-controlling interest",
      "The impairment is recognised in other comprehensive income",
    ],
    correct: 0,
    explanation:
      "Under the proportionate method the goodwill recognised is entirely the PARENT'S — none is attributed to the NCI — so any impairment falls wholly on the owners of the parent. Sharing it 80/20 is the treatment under the FAIR VALUE (full goodwill) method; allocating it all to the NCI has no basis; and impairment losses are recognised in profit or loss, not OCI.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-E-02",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Varleton Co owns 75% of Stanhoe Co and measured the NCI at FAIR VALUE at acquisition. Goodwill relating to Stanhoe is impaired by $60,000. By how much does the impairment reduce the non-controlling interest?",
    options: [
      "$15,000",
      "Nil",
      "$60,000",
      "$45,000",
    ],
    correct: 0,
    explanation:
      "With NCI at fair value, goodwill is the FULL goodwill of the subsidiary, so an impairment is shared in the profit-sharing ratio: 25% × 60,000 = $15,000 against the NCI. Nil would be correct only under the proportionate method; $60,000 charges the whole loss to the NCI; $45,000 is the PARENT'S 75% share.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR4-E-03",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Wetherfold Co owns 80% of Skiplam Co. During the year Skiplam paid a total ordinary dividend of $100,000. In the CONSOLIDATED financial statements, what appears in respect of this dividend?",
    options: [
      "$20,000, shown as a deduction in the NCI column of the consolidated statement of changes in equity",
      "$100,000 of investment income in the consolidated statement of profit or loss",
      "$80,000 of investment income in the consolidated statement of profit or loss",
      "$100,000 deducted from consolidated retained earnings as dividends paid",
    ],
    correct: 0,
    explanation:
      "The parent's $80,000 share is intra-group and eliminated in full (it is not group income — the group cannot earn income from itself). Only the $20,000 paid OUTSIDE the group to the non-controlling shareholders survives, deducted from the NCI in the SOCE (and shown under financing in the cash flow statement). Any figure retained as investment income double counts profits already consolidated line by line.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-E-04",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Yarnfield Co owns 70% of Sedgeholm Co. Revaluation surpluses: Yarnfield $200,000; Sedgeholm $130,000 now, of which $50,000 existed at acquisition. What revaluation surplus appears in the consolidated statement of financial position (attributable to owners of the parent), in $?",
    options: [
      "$256,000",
      "$330,000",
      "$291,000",
      "$280,000",
    ],
    correct: 0,
    explanation:
      "Like retained earnings, other components of equity are consolidated as: parent's balance + parent's share of the subsidiary's POST-ACQUISITION movement: 200,000 + 70% × (130,000 − 50,000) = $256,000. The $50,000 pre-acquisition surplus is part of the net assets acquired (inside goodwill). $330,000 adds the full surplus; $291,000 takes 70% of the whole $130,000; $280,000 adds the entire post-acquisition movement without the NCI share.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR4-E-05",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Zellwood Co paid $250,000 for 30% of its associate Ashmoor Co. Since acquisition, Zellwood's share of Ashmoor's profits has been $40,000 and Zellwood has received dividends of $10,000 from Ashmoor. At the year end the investment's recoverable amount is $255,000. What impairment loss is recognised?",
    options: [
      "$25,000",
      "Nil",
      "$35,000",
      "$15,000",
    ],
    correct: 0,
    explanation:
      "The equity-method carrying amount is cost 250,000 + share of profits 40,000 − dividends received 10,000 = 280,000; impairment = 280,000 − 255,000 = $25,000, tested on the investment AS A SINGLE ASSET. Nil compares recoverable amount with original cost; $35,000 forgets that dividends reduce the carrying amount; $15,000 deducts the dividends twice.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR4-E-06",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Alderbrook Co (retained earnings $2,000,000) owns 80% of Silvermount Co (retained earnings $900,000 now; $500,000 at acquisition). Cumulative extra depreciation on fair-value uplifts is $50,000; $30,000 of profit on goods ALDERBROOK sold to Silvermount remains in inventory; cumulative goodwill impairment is $60,000, with NCI measured at FAIR VALUE. What are consolidated retained earnings, in $'000?",
    options: [
      "2,202",
      "2,232",
      "2,190",
      "2,208",
    ],
    correct: 0,
    explanation:
      "Parent 2,000 − PUP 30 (parent is the seller, so it bears all of it) + 80% × (900 − 500 − 50 = 350) = 280 − parent's share of impairment 80% × 60 = 48 → 2,000 − 30 + 280 − 48 = 2,202. 2,232 forgets the PUP; 2,190 charges the FULL impairment to the parent (that is the proportionate-NCI treatment); 2,208 wrongly shares the parent's own PUP with the NCI (80% × 30).",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR4-E-07",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Two years ago Bramwell Co acquired 75% of Skellorn Co. At acquisition, Skellorn's plant (remaining life then 10 years) had a fair value $200,000 above its carrying amount; Skellorn has not adjusted its own books. PPE carrying amounts are now: Bramwell $3,000,000; Skellorn $1,200,000. What is consolidated PPE, in $?",
    options: [
      "$4,360,000",
      "$4,400,000",
      "$4,200,000",
      "$4,160,000",
    ],
    correct: 0,
    explanation:
      "Consolidated PPE = 3,000 + 1,200 + fair-value uplift 200 − two years' extra depreciation (200/10 × 2 = 40) = $4,360,000 — 100% of the subsidiary's assets are consolidated regardless of the 75% holding. $4,400,000 omits the extra depreciation on the uplift; $4,200,000 ignores the fair-value adjustment altogether; $4,160,000 charges the depreciation but forgets to add the uplift itself.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-E-08",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Calverleigh Co lent $400,000 at 8% to its 75%-owned subsidiary for the whole year. Finance costs for the year: Calverleigh $50,000; subsidiary $90,000 (including the intra-group interest). What are consolidated finance costs?",
    options: [
      "$108,000",
      "$140,000",
      "$116,000",
      "$76,000",
    ],
    correct: 0,
    explanation:
      "Intra-group interest of 400,000 × 8% = 32,000 is eliminated IN FULL (with the parent's matching finance income): 50,000 + 90,000 − 32,000 = $108,000. $140,000 makes no elimination; $116,000 eliminates only the parent's 75% share (intra-group balances and transactions are never scaled by ownership percentage); $76,000 deducts the interest twice.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-E-09",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Danesmoor Co owns 60% of Swinbrook Co. Swinbrook's profit for the year is $200,000 and it recognised a $50,000 revaluation gain in OCI. Consolidation adjustments: extra depreciation on fair-value uplifts $20,000; unrealised profit of $10,000 on goods SWINBROOK sold to Danesmoor still in inventory. What TOTAL comprehensive income is attributable to the NCI?",
    options: [
      "$88,000",
      "$68,000",
      "$100,000",
      "$96,000",
    ],
    correct: 0,
    explanation:
      "Adjusted profit = 200 − 20 − 10 = 170 (the PUP is deducted from the SELLER, Swinbrook); adjusted TCI = 170 + 50 = 220; NCI share = 40% × 220 = $88,000. $68,000 omits the subsidiary's OCI from the NCI allocation; $100,000 skips both consolidation adjustments (40% × 250); $96,000 forgets the extra depreciation (40% × 240).",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR4-E-10",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Eskholme Co pays $1,000,000 for 80% of Stavenholt Co, measuring NCI at its proportionate share of net assets. Stavenholt's net assets have a book value of $700,000, and it owns an internally generated brand (unrecognised in its own books) with a reliable fair value of $100,000. What is goodwill, in $'000?",
    options: [
      "360",
      "440",
      "200",
      "300",
    ],
    correct: 0,
    explanation:
      "In a business combination, IFRS 3 recognises the subsidiary's identifiable intangibles even if internally generated, so fair value of net assets = 700 + 100 = 800. Goodwill = 1,000 + NCI (20% × 800 = 160) − 800 = 360. 440 uses book net assets (1,000 + 140 − 700); 200 compares consideration with net assets but omits the NCI (1,000 − 800); 300 omits the NCI and the brand (1,000 − 700).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR4-E-11",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "In a consolidated statement of financial position, the share capital figure comprises:",
    options: [
      "The share capital of the parent only",
      "The share capital of the parent plus that of all subsidiaries",
      "The parent's share capital plus the group's percentage of each subsidiary's share capital",
      "The share capital of the parent plus the post-acquisition share capital of subsidiaries",
    ],
    correct: 0,
    explanation:
      "The consolidated statements are prepared for the shareholders OF THE PARENT, so only the parent's share capital (and share premium) is presented. The subsidiary's share capital is part of the net assets acquired: the group's share is subsumed in the goodwill calculation and the rest sits within the NCI — adding it again double counts.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR4-E-12",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Which of the following investments should Farndale Co account for as an ASSOCIATE?",
    options: [
      "A 22% shareholding in Greylake Co, together with a seat on Greylake's five-member board",
      "A 55% shareholding carrying majority voting rights in Hazelwick Co",
      "A 10% shareholding in Ivenholt Co with no board representation or other rights",
      "A 50% interest in Jesmond Co under a contract requiring unanimous consent of both investors for all key decisions",
    ],
    correct: 0,
    explanation:
      "Significant influence is presumed at 20%+ of voting power, reinforced here by board representation — an associate, equity accounted under IAS 28. 55% with majority votes gives CONTROL (a subsidiary, consolidated); 10% with no other rights is a simple IFRS 9 financial asset; contractually agreed unanimous consent over relevant decisions indicates JOINT control (a joint arrangement), not significant influence.",
    marks: 2,
    difficulty: "easy",
  },
]
