import type { AccaQuestion } from "@/lib/acca-content"
/*
 * APM bank wave S1 part A (areas A, B).
 *
 * Blueprint: Area A (Strategic planning & control) = 40 questions;
 *            Area B (Performance management systems & design) = 35 questions.
 *            Difficulty split 22 easy / 34 medium / 19 hard.
 *            Type split 62 mcq / 13 number.
 *            Correct-option positions across the 62 mcq: 0→16, 1→16, 2→15, 3→15.
 * Authored 2026-07-13. 100% original — invented company names and figures,
 * aligned to the public ACCA APM (P5) syllabus; no ACCA/Kaplan/BPP material reproduced.
 * NOTE: every computation below was re-solved digit-by-digit; workings are shown
 * in each numeric explanation (throughput, transfer price, cost of quality in full).
 */
export const APM_WAVE1A: AccaQuestion[] = [
  /* ═══════════ AREA A — Strategic planning & control ═══════════ */

  /* ── Strategic environment: PEST, five forces, value chain ── */
  {
    id: "APM2-A-01", paper: "APM", area: "A", type: "mcq",
    stem: "Zentara Co is analysing its macro-environment. It notes that central-bank interest rates have risen sharply, raising its borrowing costs. In a PEST analysis, this factor is classified as:",
    options: ["Political", "Economic", "Social", "Technological"],
    correct: 1,
    explanation: "Interest rates are a macro-economic variable, so this is an Economic factor. Political covers government/legislative action, Social covers demographic and lifestyle trends, and Technological covers innovation and process change — none of which describes an interest-rate movement.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "APM2-A-02", paper: "APM", area: "A", type: "mcq",
    stem: "In Porter's five forces model, the threat of new entrants to an industry is REDUCED by:",
    options: [
      "High capital requirements and strong economies of scale",
      "Low customer switching costs",
      "A large number of equally sized competitors",
      "Undifferentiated commodity products",
    ],
    correct: 0,
    explanation: "High capital needs and scale economies are barriers to entry, so they lower the threat of new entrants. Low switching costs make it easier for entrants to win customers (raises threat); many equal competitors describes rivalry, not entry; undifferentiated products make entry easier, not harder.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "APM2-A-03", paper: "APM", area: "A", type: "mcq",
    stem: "Under Porter's five forces, the bargaining power of suppliers to Halvern Co is HIGH when:",
    options: [
      "The industry has many alternative suppliers",
      "Inputs are standardised and easily substituted",
      "A few suppliers dominate and switching costs for buyers are high",
      "Buyers can easily integrate backwards into supply",
    ],
    correct: 2,
    explanation: "Supplier power is high when suppliers are concentrated and buyers face high switching costs. Many alternative suppliers and easily substituted inputs both weaken supplier power, and the ability of buyers to integrate backwards is a threat that reduces supplier power.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-A-04", paper: "APM", area: "A", type: "mcq",
    stem: "In Porter's value chain, which of the following is a SUPPORT activity rather than a primary activity?",
    options: ["Operations", "Outbound logistics", "Procurement", "Marketing and sales"],
    correct: 2,
    explanation: "Procurement is one of the four support activities (with firm infrastructure, HR management and technology development). Operations, outbound logistics and marketing and sales are all primary activities that directly create and deliver the product.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-A-05", paper: "APM", area: "A", type: "mcq",
    stem: "In Porter's value chain, the 'margin' is best described as:",
    options: [
      "The mark-up added only by the final retailer",
      "The total cost of the support activities",
      "The difference between two competitors' selling prices",
      "The difference between the total value created and the total cost of performing the value activities",
    ],
    correct: 3,
    explanation: "Margin is total value (what customers will pay) less the total cost of all value activities. A retailer-only mark-up ignores the whole chain, support-activity cost is only one component, and a gap between competitors' prices is a market comparison, not the chain's margin.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "APM2-A-06", paper: "APM", area: "A", type: "mcq",
    stem: "Bramwell Co identifies that new carbon-emissions legislation will force costly changes to its factories. In a PEST analysis this factor is classified as:",
    options: ["Political/legal", "Economic", "Social", "Technological"],
    correct: 0,
    explanation: "Legislation is an act of government, so it is a Political/legal factor. Economic covers market variables such as inflation, Social covers attitudes and demographics, and Technological covers new production methods — the trigger here is a new law, not any of those.",
    marks: 2, difficulty: "medium",
  },

  /* ── Mission, objectives, CSFs & KPIs ── */
  {
    id: "APM2-A-07", paper: "APM", area: "A", type: "mcq",
    stem: "Which statement best distinguishes a mission statement from an objective?",
    options: [
      "A mission statement sets a specific quantified target for the next 12 months",
      "A mission statement expresses the organisation's overriding purpose and reason for existing",
      "A mission statement lists the detailed tasks each department must complete",
      "A mission statement is a legally required disclosure in the financial statements",
    ],
    correct: 1,
    explanation: "A mission conveys the broad, enduring purpose of the organisation. A quantified 12-month figure describes an objective/target, a list of departmental tasks describes operational plans, and there is no statutory requirement to publish a mission — those options confuse mission with lower-level or unrelated concepts.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-A-08", paper: "APM", area: "A", type: "mcq",
    stem: "Which statement correctly describes the relationship between critical success factors (CSFs) and key performance indicators (KPIs)?",
    options: [
      "CSFs and KPIs are just two names for the same thing",
      "A KPI is a broad area of the business, and a CSF is its single numerical measure",
      "KPIs are the measures that show whether the CSFs are being achieved",
      "CSFs are only relevant to not-for-profit organisations",
    ],
    correct: 2,
    explanation: "CSFs are the few areas where the business must excel; KPIs are the quantified measures that track them. They are not synonyms; the second option reverses the definitions (a CSF is the broad area, the KPI is the measure); and CSFs apply to all organisations, not only not-for-profits.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "APM2-A-09", paper: "APM", area: "A", type: "mcq",
    stem: "Delmeria Co's critical success factor is 'high customer satisfaction'. Which of the following is the most appropriate KPI for that CSF?",
    options: [
      "The total number of employees",
      "The book value of non-current assets",
      "The number of board meetings held",
      "The percentage of orders delivered on time and the customer complaint rate",
    ],
    correct: 3,
    explanation: "On-time delivery and complaint rates directly measure customer satisfaction. Employee headcount, asset book value and board-meeting counts are internal or governance metrics that reveal nothing about how satisfied customers are.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-A-10", paper: "APM", area: "A", type: "number",
    stem: "Marden Co reports operating profit of $630,000 earned from capital employed of $3,500,000. Calculate the return on capital employed (ROCE), in %, to one decimal place.",
    numericAnswer: 18, unit: "%", tolerance: 0.1,
    explanation: "ROCE = operating profit ÷ capital employed = $630,000 ÷ $3,500,000 = 0.18 = 18.0%. Using revenue instead of capital employed, or profit after tax, would give a different (incorrect) ratio.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-A-11", paper: "APM", area: "A", type: "mcq",
    stem: "A well-set objective is often described as 'SMART'. What does SMART stand for?",
    options: [
      "Specific, Measurable, Achievable, Relevant, Time-bound",
      "Strategic, Managerial, Accurate, Realistic, Timely",
      "Simple, Meaningful, Actionable, Reliable, Tested",
      "Sustainable, Modern, Ambitious, Robust, Targeted",
    ],
    correct: 0,
    explanation: "SMART = Specific, Measurable, Achievable, Relevant, Time-bound. The other options are plausible-sounding but incorrect word substitutions that are not the recognised SMART criteria for objective-setting.",
    marks: 2, difficulty: "easy",
  },

  /* ── Budgeting approaches ── */
  {
    id: "APM2-A-12", paper: "APM", area: "A", type: "mcq",
    stem: "Which of the following is the main criticism of incremental budgeting?",
    options: [
      "It requires every activity to be justified from a zero base each year",
      "It builds in and perpetuates past inefficiencies and slack",
      "It cannot be prepared using a spreadsheet",
      "It is only suitable for rapidly changing environments",
    ],
    correct: 1,
    explanation: "Incremental budgeting starts from last year's figures, so any waste already in the base is carried forward. Justifying from a zero base describes ZBB (not incremental); the spreadsheet claim is false; and incremental budgeting actually suits STABLE, not rapidly changing, environments.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-A-13", paper: "APM", area: "A", type: "mcq",
    stem: "In zero-based budgeting (ZBB), a 'decision package' is:",
    options: [
      "A budget carried forward unchanged from the prior year",
      "A fixed cash reserve held for emergencies",
      "A description of an activity with its costs and benefits, prepared so it can be ranked for funding",
      "A statistical forecast of next year's sales demand",
    ],
    correct: 2,
    explanation: "A decision package documents an activity's costs and benefits so managers can rank and fund it. An unchanged carried-forward budget is incremental budgeting, a cash reserve is a contingency, and a sales forecast is a planning input — none is a ZBB decision package.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "APM2-A-14", paper: "APM", area: "A", type: "number",
    stem: "Under incremental budgeting, Corvale Co takes last year's marketing budget of $250,000, uplifts it by 6% for inflation, and then adds a further $40,000 for a one-off product launch. What is next year's marketing budget, in $?",
    numericAnswer: 305000, unit: "$", tolerance: 1,
    explanation: "Uplifted base = $250,000 × 1.06 = $265,000; add the $40,000 launch cost = $305,000. Adding the 6% to the $40,000 as well, or forgetting the launch cost, would misstate the figure.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-A-15", paper: "APM", area: "A", type: "mcq",
    stem: "A rolling (continuous) budget is best described as a budget that:",
    options: [
      "Is fixed for five years with no revision",
      "Is prepared only when a significant variance arises",
      "Is set once at the start of the year and never changed",
      "Is continuously updated by adding a further period as each one expires",
    ],
    correct: 3,
    explanation: "A rolling budget always looks the same distance ahead: as one period ends, another is added. A fixed five-year plan and a 'never changed' annual budget are the opposite (static) approach, and a budget prepared only on variances is not a budgeting cycle at all.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-A-16", paper: "APM", area: "A", type: "mcq",
    stem: "Which statement best describes activity-based budgeting (ABB)?",
    options: [
      "It builds budgets from expected activity volumes and their cost drivers",
      "It simply adds a fixed percentage to last year's totals",
      "It sets every budget to zero and justifies all costs from scratch",
      "It abolishes budgets entirely in favour of rolling forecasts",
    ],
    correct: 0,
    explanation: "ABB budgets the cost of activities using planned volumes of their cost drivers. Adding a percentage to last year is incremental budgeting, justifying from zero is ZBB, and abolishing budgets is the beyond-budgeting philosophy — none is ABB.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-A-17", paper: "APM", area: "A", type: "mcq",
    stem: "Which statement best captures the 'beyond budgeting' philosophy?",
    options: [
      "It tightens central control by adding more detailed annual budgets",
      "It replaces fixed annual targets with relative goals, rolling forecasts and devolved authority",
      "It is simply zero-based budgeting under a different name",
      "It removes all forms of financial planning from the organisation",
    ],
    correct: 1,
    explanation: "Beyond budgeting drops the rigid annual budget in favour of relative/benchmarked targets, rolling forecasts and decentralised decision-making. It loosens rather than tightens central control, is distinct from ZBB, and replaces — not abolishes — planning.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "APM2-A-18", paper: "APM", area: "A", type: "mcq",
    stem: "Which of the following is a genuine advantage of zero-based budgeting?",
    options: [
      "It is quicker and cheaper to prepare than incremental budgeting",
      "It guarantees that total costs will fall every year",
      "It allocates resources to activities according to need and priority, challenging slack",
      "It removes the need for any managerial judgement",
    ],
    correct: 2,
    explanation: "ZBB forces every activity to justify its resources, so funding follows priority and slack is challenged. It is actually slower and costlier than incremental budgeting, it does not guarantee cost reductions, and it requires MORE managerial judgement, not less.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "APM2-A-19", paper: "APM", area: "A", type: "number",
    stem: "Ashcombe Co runs a rolling budget. The original annual budget of $960,000 was spread evenly over 12 months. After the first quarter, the remaining nine months are re-forecast 5% higher than originally budgeted. What is the revised budget for the remaining nine months, in $?",
    numericAnswer: 756000, unit: "$", tolerance: 1,
    explanation: "Original nine-month portion = $960,000 × 9/12 = $720,000; re-forecast up 5% = $720,000 × 1.05 = $756,000. Applying the 5% to the full year ($960,000 × 1.05) or to only the quarter already spent would give the wrong revision.",
    marks: 2, difficulty: "medium",
  },

  /* ── Forecasting & planning models ── */
  {
    id: "APM2-A-20", paper: "APM", area: "A", type: "mcq",
    stem: "In classical time-series analysis, a series is typically decomposed into which components?",
    options: [
      "Fixed, variable, semi-variable and stepped",
      "Prevention, appraisal, internal and external",
      "Political, economic, social and technological",
      "Trend, seasonal variation, cyclical variation and random",
    ],
    correct: 3,
    explanation: "A time series is broken into trend, seasonal, cyclical and random (residual) components. The other options are cost-behaviour patterns, quality-cost categories and PEST factors respectively — none of which are the components of a time series.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "APM2-A-21", paper: "APM", area: "A", type: "number",
    stem: "The first batch of a new product took 200 labour hours. An 80% learning curve applies (cumulative average time falls to 80% each time cumulative output doubles). What is the total labour time for the first 4 batches, in hours?",
    numericAnswer: 512, unit: "hours", tolerance: 1,
    explanation: "Cumulative average per batch: 1 batch = 200; at 2 batches = 200 × 0.8 = 160; at 4 batches = 160 × 0.8 = 128. Total for 4 batches = 4 × 128 = 512 hours. Using 200 × 0.8 × 0.8 as a total (256) forgets to multiply the cumulative average by the 4 batches.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "APM2-A-22", paper: "APM", area: "A", type: "number",
    stem: "Using the high-low method, total overhead cost was $84,000 at an activity level of 6,000 units and $108,000 at 10,000 units. What is the estimated variable cost per unit, in $?",
    numericAnswer: 6, unit: "$", tolerance: 0.01,
    explanation: "Variable cost per unit = change in cost ÷ change in units = ($108,000 − $84,000) ÷ (10,000 − 6,000) = $24,000 ÷ 4,000 = $6.00. Dividing total cost by total units ($108,000 ÷ 10,000 = $10.80) wrongly treats all cost as variable.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-A-23", paper: "APM", area: "A", type: "mcq",
    stem: "Which statement about the learning curve is correct?",
    options: [
      "It applies where work is labour-intensive and repetitive, and levels off once a steady state is reached",
      "It applies mainly to highly automated, machine-paced production",
      "It continues to reduce time per unit indefinitely with no limit",
      "It affects material costs but has no effect on labour time",
    ],
    correct: 0,
    explanation: "The learning effect occurs in labour-intensive, repetitive work and stops when a steady state is reached. It does not apply to machine-paced automation, it does not fall forever, and it is a labour-time (not material-cost) phenomenon.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-A-24", paper: "APM", area: "A", type: "mcq",
    stem: "Which statement best reflects the use of big data in strategic forecasting and planning?",
    options: [
      "Big data guarantees perfectly accurate forecasts",
      "Larger, richer datasets can improve forecasts but bring risks of poor data quality and spurious correlations",
      "Big data removes the need for any managerial judgement",
      "Big data is only about volume; velocity and variety are irrelevant",
    ],
    correct: 1,
    explanation: "More and richer data can sharpen forecasts, but veracity problems and false correlations can mislead. Big data never guarantees accuracy, it augments rather than replaces judgement, and its defining features explicitly include velocity and variety, not just volume.",
    marks: 2, difficulty: "hard",
  },

  /* ── Benchmarking ── */
  {
    id: "APM2-A-25", paper: "APM", area: "A", type: "mcq",
    stem: "Novakron Co compares its performance directly against its closest rival in the same industry. This is an example of:",
    options: ["Internal benchmarking", "Functional benchmarking", "Competitive benchmarking", "Generic benchmarking"],
    correct: 2,
    explanation: "Comparing against a direct rival in the same industry is competitive benchmarking. Internal benchmarking compares units within the same organisation, functional benchmarking compares a specific function against a leader in any sector, and generic benchmarking compares broad processes across unrelated industries.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "APM2-A-26", paper: "APM", area: "A", type: "mcq",
    stem: "Which of the following is a valid limitation of benchmarking?",
    options: [
      "It always guarantees a sustainable competitive advantage",
      "It requires no effort to gather comparative data",
      "Benchmarking data is always freely and accurately available",
      "It can lead to catching up rather than leapfrogging, and comparators may not be truly comparable",
    ],
    correct: 3,
    explanation: "Benchmarking targets existing best practice, so it risks only closing the gap while rivals move on, and the comparator may differ in scale or context. The other options overstate its benefits — it does not guarantee advantage, and reliable comparative data is often hard and costly to obtain.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-A-27", paper: "APM", area: "A", type: "mcq",
    stem: "A board is warned about the dangers of over-relying on benchmarking. Which warning is valid?",
    options: [
      "Copied practices may not suit the firm's own strategy and can breed complacency",
      "It always reveals the exact steps needed to become market leader",
      "It removes the need to understand the firm's own internal processes",
      "It is only ever useful in manufacturing and never in services",
    ],
    correct: 0,
    explanation: "Practices lifted from another firm may clash with your strategy, and simply matching others can breed complacency. Benchmarking shows what others achieve, not the exact route to leadership; it still requires deep understanding of internal processes; and it is widely used in services as well as manufacturing.",
    marks: 2, difficulty: "hard",
  },

  /* ── Business integration: McKinsey 7S, Ferreira & Otley, Otley's framework ── */
  {
    id: "APM2-A-28", paper: "APM", area: "A", type: "mcq",
    stem: "In the McKinsey 7S model, which of the following is a 'soft' element?",
    options: ["Strategy", "Shared values", "Structure", "Systems"],
    correct: 1,
    explanation: "The soft elements are shared values, skills, staff and style. Strategy, structure and systems are the three 'hard' elements, which are easier to define and change than the soft, culture-based ones.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "APM2-A-29", paper: "APM", area: "A", type: "mcq",
    stem: "In the McKinsey 7S model, which element sits at the centre, linking all the others?",
    options: ["Systems", "Style", "Shared values", "Staff"],
    correct: 2,
    explanation: "Shared values (originally 'superordinate goals') sit at the centre and connect the other six S's. Systems (processes), style (leadership approach) and staff (people) are each surrounding elements, not the central one.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-A-30", paper: "APM", area: "A", type: "mcq",
    stem: "What is the Ferreira and Otley framework?",
    options: [
      "A method for calculating divisional transfer prices",
      "A budgeting technique that replaces zero-based budgeting",
      "A model of the product life cycle",
      "An extended framework of twelve questions for analysing the design and use of performance management systems",
    ],
    correct: 3,
    explanation: "Ferreira and Otley's framework poses twelve questions covering the design and use of a performance management system. It is not a transfer-pricing method, a budgeting technique or a life-cycle model — those options describe unrelated tools.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "APM2-A-31", paper: "APM", area: "A", type: "mcq",
    stem: "Otley's original performance-management framework is built around five central questions. These concern:",
    options: [
      "Objectives, strategies and plans, targets, rewards, and information feedback loops",
      "Political, economic, social, technological and legal factors",
      "Prevention, appraisal, internal failure, external failure and conformance",
      "Strategy, structure, systems, staff and style",
    ],
    correct: 0,
    explanation: "Otley's five questions ask about objectives, the strategies/plans to achieve them, the targets set, the rewards attached, and the information feedback used. The other options are PESTEL factors, quality-cost categories and McKinsey 7S elements respectively.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "APM2-A-32", paper: "APM", area: "A", type: "mcq",
    stem: "Which statement best reflects good integration of a performance management system with strategy?",
    options: [
      "Performance measures should be chosen independently of the strategy",
      "An effective system links strategy to operational measures and supports feedback and learning",
      "Financial measures alone are sufficient for strategic control",
      "Performance frameworks are only relevant to manufacturing firms",
    ],
    correct: 1,
    explanation: "A well-integrated system cascades strategy into operational measures and feeds results back for learning and adjustment. Choosing measures independently of strategy breaks that link, financial measures alone miss key non-financial drivers, and such frameworks apply to all sectors, not just manufacturing.",
    marks: 2, difficulty: "hard",
  },

  /* ── Stakeholders in planning ── */
  {
    id: "APM2-A-33", paper: "APM", area: "A", type: "mcq",
    stem: "Mendelow's stakeholder matrix maps stakeholders on which two dimensions?",
    options: ["Cost and benefit", "Risk and return", "Power and level of interest", "Price and quality"],
    correct: 2,
    explanation: "Mendelow's matrix plots stakeholders by their power and their level of interest, guiding how each group should be managed. Cost/benefit, risk/return and price/quality are unrelated pairings from other areas of analysis.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "APM2-A-34", paper: "APM", area: "A", type: "mcq",
    stem: "In Mendelow's matrix, stakeholders with HIGH power and HIGH interest should be:",
    options: ["Given minimal effort", "Kept informed", "Kept satisfied", "Managed closely as key players"],
    correct: 3,
    explanation: "High power and high interest identifies the key players, who must be managed closely. Minimal effort is for low-power/low-interest groups, 'keep informed' is for high-interest/low-power groups, and 'keep satisfied' is for high-power/low-interest groups.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-A-35", paper: "APM", area: "A", type: "mcq",
    stem: "Why must stakeholder analysis inform strategic planning?",
    options: [
      "Because different stakeholder groups often have conflicting objectives that planning must balance",
      "Because all stakeholders always share identical objectives",
      "Because only shareholders' objectives matter in strategic planning",
      "Because stakeholder analysis is irrelevant to performance management",
    ],
    correct: 0,
    explanation: "Groups such as shareholders, employees and communities frequently pull in different directions, so plans must reconcile competing aims. It is false that stakeholders always agree, that only shareholders matter, or that stakeholder analysis is irrelevant — each ignores real conflicts of interest.",
    marks: 2, difficulty: "hard",
  },

  /* ── Environmental & sustainability management accounting ── */
  {
    id: "APM2-A-36", paper: "APM", area: "A", type: "mcq",
    stem: "Environmental management accounting (EMA) is best described as:",
    options: [
      "A legal requirement to publish a separate environmental audit",
      "The identification, collection and analysis of physical and monetary environmental information for internal decision-making",
      "A tax levied on carbon emissions",
      "A marketing technique used only for green branding",
    ],
    correct: 1,
    explanation: "EMA gathers both physical flows (energy, water, waste) and monetary environmental data to support internal decisions. It is not a mandatory published audit, not a carbon tax, and not merely a branding exercise — those options confuse EMA with compliance, taxation and marketing.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "APM2-A-37", paper: "APM", area: "A", type: "mcq",
    stem: "Using categories analogous to quality costs, the cost of cleaning up land contaminated by a firm's past operations, incurred after the damage has occurred, is an example of an environmental:",
    options: ["Prevention cost", "Appraisal (detection) cost", "External failure cost", "Design cost"],
    correct: 2,
    explanation: "Clean-up after contamination has occurred is an environmental failure cost arising outside the process, i.e. external failure. Prevention costs stop damage before it happens, appraisal/detection costs monitor for it, and design costs are incurred up-front — none matches remediation after the fact.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-A-38", paper: "APM", area: "A", type: "mcq",
    stem: "In environmental management accounting, input/output (mass balance) analysis is a technique that:",
    options: [
      "Sets transfer prices between divisions",
      "Ranks decision packages for funding",
      "Calculates the labour learning curve",
      "Records material inputs and balances them against outputs of finished product and waste",
    ],
    correct: 3,
    explanation: "Input/output analysis applies the principle that what comes in must come out, tracing materials into product versus waste to reveal the cost of inefficiency. Transfer pricing, decision-package ranking and learning-curve calculation are unrelated techniques from other syllabus areas.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "APM2-A-39", paper: "APM", area: "A", type: "mcq",
    stem: "The 'triple bottom line' approach to sustainability measures performance across which three dimensions?",
    options: [
      "Profit, people and planet — economic, social and environmental performance",
      "Past, present and future budgets",
      "Prevention, appraisal and failure costs",
      "Political, economic and social factors",
    ],
    correct: 0,
    explanation: "The triple bottom line reports economic (profit), social (people) and environmental (planet) performance. The other options describe budget periods, quality-cost categories and part of a PEST analysis — none is the triple bottom line.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-A-40", paper: "APM", area: "A", type: "mcq",
    stem: "Which of the following is a recognised environmental management accounting technique that assigns environmental costs to material, system and delivery/disposal 'flows'?",
    options: ["Zero-based budgeting", "Flow cost accounting", "The learning curve model", "Mendelow's matrix"],
    correct: 1,
    explanation: "Flow cost accounting tracks environmental costs through material, system and delivery/disposal flows to highlight waste. Zero-based budgeting is a budgeting method, the learning curve models labour time, and Mendelow's matrix maps stakeholders — none is an EMA costing technique.",
    marks: 2, difficulty: "hard",
  },

  /* ═══════════ AREA B — Performance management systems & design ═══════════ */

  /* ── Feedback vs feedforward control ── */
  {
    id: "APM2-B-01", paper: "APM", area: "B", type: "mcq",
    stem: "Feedforward control involves:",
    options: [
      "Comparing a forecast of future results with the plan and acting before the event",
      "Comparing actual past results with the budget after the event",
      "Ignoring variances until the year end",
      "Setting the budget equal to last year's actual results",
    ],
    correct: 0,
    explanation: "Feedforward control compares a forecast against the plan and takes corrective action in advance. Comparing actual past results with budget is feedback control, deferring variances to year end is poor control, and copying last year's actuals is an incremental budgeting method — none is feedforward.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "APM2-B-02", paper: "APM", area: "B", type: "mcq",
    stem: "Which of the following is an example of feedforward control?",
    options: [
      "A variance report comparing last month's actual and budgeted costs",
      "A cash forecast predicting a future shortfall, prompting action now",
      "A year-end profit statement",
      "A reconciliation of the bank statement to the cash book",
    ],
    correct: 1,
    explanation: "A forecast that reveals a future problem and triggers action beforehand is feedforward. A variance report and a year-end profit statement both look backward (feedback), and a bank reconciliation is a control over records, not a forward-looking forecast.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-B-03", paper: "APM", area: "B", type: "mcq",
    stem: "Double-loop feedback differs from single-loop feedback because it:",
    options: [
      "Simply corrects deviations to keep to the existing plan",
      "Uses two separate variance reports every period",
      "Questions whether the plan and its underlying assumptions are still appropriate, not just correcting to plan",
      "Only ever applies to financial data",
    ],
    correct: 2,
    explanation: "Double-loop feedback challenges the plan and its assumptions themselves, allowing objectives to change. Merely correcting deviations to the existing plan is single-loop; the 'two reports' idea misreads the term; and the concept applies to both financial and non-financial information.",
    marks: 2, difficulty: "medium",
  },

  /* ── Impact of IT: big data, dashboards, analytics, ERP/BI ── */
  {
    id: "APM2-B-04", paper: "APM", area: "B", type: "mcq",
    stem: "The characteristics of big data are most commonly summarised as:",
    options: [
      "Price, place, promotion and product",
      "Plan, do, check and act",
      "Strategy, structure and systems",
      "Volume, velocity and variety",
    ],
    correct: 3,
    explanation: "Big data is typically characterised by volume, velocity and variety (sometimes with veracity added). The other options are the marketing mix, the plan-do-check-act cycle and three McKinsey 7S elements — none describes big data.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "APM2-B-05", paper: "APM", area: "B", type: "mcq",
    stem: "Analytics that recommend the best course of action to take are known as:",
    options: ["Prescriptive analytics", "Descriptive analytics", "Diagnostic analytics", "Historical reporting"],
    correct: 0,
    explanation: "Prescriptive analytics goes beyond describing or explaining data to recommend what to do. Descriptive analytics reports what happened, diagnostic analytics explains why it happened, and historical reporting simply presents past results — none recommends an action.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-B-06", paper: "APM", area: "B", type: "mcq",
    stem: "A key risk of relying heavily on big data analytics for performance decisions is that:",
    options: [
      "It always reduces the cost of information systems",
      "Spurious correlations and poor data quality can drive misleading decisions",
      "It removes the need for any data security controls",
      "It automatically guarantees regulatory compliance",
    ],
    correct: 1,
    explanation: "Large datasets can throw up coincidental correlations, and poor-quality data leads to poor decisions. Big data does not necessarily cut IT costs, it heightens rather than removes the need for security, and it certainly does not guarantee compliance by itself.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "APM2-B-07", paper: "APM", area: "B", type: "mcq",
    stem: "The main purpose of a performance dashboard is to:",
    options: [
      "Replace the general ledger",
      "Store all transaction data securely",
      "Present key performance measures visually for quick monitoring and decision-making",
      "Automatically prepare the statutory financial statements",
    ],
    correct: 2,
    explanation: "A dashboard displays selected KPIs visually so managers can monitor performance at a glance. It does not replace the ledger, it is a presentation layer rather than the secure data store, and it does not produce statutory accounts.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "APM2-B-08", paper: "APM", area: "B", type: "mcq",
    stem: "An enterprise resource planning (ERP) system is best described as:",
    options: [
      "A spreadsheet used only by the finance team",
      "A tool solely for external financial reporting",
      "A standalone payroll package",
      "An integrated suite that shares a single database across business functions",
    ],
    correct: 3,
    explanation: "An ERP system integrates functions such as finance, HR, production and sales around one shared database. It is far more than a finance spreadsheet, is not limited to external reporting, and is not a standalone single-function package like payroll.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-B-09", paper: "APM", area: "B", type: "mcq",
    stem: "Business intelligence (BI) systems primarily:",
    options: [
      "Gather and analyse data to produce insight that supports management decisions",
      "Only record double-entry bookkeeping transactions",
      "Replace the need for any business strategy",
      "Are used exclusively for filing tax returns",
    ],
    correct: 0,
    explanation: "BI systems collect, analyse and present data as insight for decision-making. They are not mere bookkeeping engines, they support (not replace) strategy, and they are not confined to tax compliance.",
    marks: 2, difficulty: "medium",
  },

  /* ── Sources & management information; information quality ── */
  {
    id: "APM2-B-10", paper: "APM", area: "B", type: "mcq",
    stem: "Which of the following is an EXTERNAL source of management information?",
    options: [
      "The company's own payroll records",
      "Published competitor and market data",
      "The firm's internal fixed asset register",
      "The company's own production logs",
    ],
    correct: 1,
    explanation: "Competitor and market data originate outside the organisation, so they are external sources. Payroll records, the fixed asset register and production logs are all generated inside the business, making them internal sources.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "APM2-B-11", paper: "APM", area: "B", type: "mcq",
    stem: "For information to be useful for management control, it should be:",
    options: [
      "Voluminous and highly detailed regardless of the decision",
      "Delayed until fully complete, even if it is then too late to act",
      "Relevant, accurate, timely and understandable",
      "Restricted to financial data only",
    ],
    correct: 2,
    explanation: "Good information is relevant, accurate, timely and understandable (among other qualities). Excess volume causes overload, information delayed until too late loses its value, and useful control information includes non-financial as well as financial data.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-B-12", paper: "APM", area: "B", type: "mcq",
    stem: "Which of the following is a genuine threat to the quality of management information from a newly implemented system?",
    options: [
      "Better integration always improves data quality automatically",
      "Producing more reports always leads to better decisions",
      "Faster processing removes the need for data validation",
      "Poor-quality input data undermines the outputs (garbage in, garbage out)",
    ],
    correct: 3,
    explanation: "If the data entered is inaccurate, even a sophisticated system produces flawed outputs. Integration does not fix data automatically, more reports can cause overload rather than better decisions, and faster processing makes validation more important, not redundant.",
    marks: 2, difficulty: "hard",
  },

  /* ── Cost & management accounting for performance: ABC/ABM, target, lifecycle, throughput, quality ── */
  {
    id: "APM2-B-13", paper: "APM", area: "B", type: "mcq",
    stem: "Activity-based management (ABM) uses activity-based cost information mainly to:",
    options: [
      "Manage activities to improve efficiency, customer value and profitability",
      "Prepare the statutory cash flow statement",
      "Set statutory tax allowances",
      "Calculate the labour learning curve",
    ],
    correct: 0,
    explanation: "ABM applies ABC data to manage and improve activities, enhancing value and profit. It is not a method of preparing cash flow statements, it has nothing to do with statutory tax allowances, and it is unrelated to learning-curve calculations.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "APM2-B-14", paper: "APM", area: "B", type: "number",
    stem: "Quillon Co's machine set-up cost pool is $90,000, driven by a total of 60 set-ups. Product G requires 20 set-ups to produce 5,000 units. Under activity-based costing, what is the set-up cost per unit of Product G, in $?",
    numericAnswer: 6, unit: "$", tolerance: 0.01,
    explanation: "Cost per set-up = $90,000 ÷ 60 = $1,500. Product G's set-up cost = 20 × $1,500 = $30,000; per unit = $30,000 ÷ 5,000 = $6.00. Absorbing the whole pool over G's units, or charging all 60 set-ups to G, would overstate the cost.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-B-15", paper: "APM", area: "B", type: "mcq",
    stem: "Operational activity-based management (operational ABM) focuses on:",
    options: [
      "Choosing which products and customers the firm should serve",
      "Performing activities more efficiently to reduce their cost (doing things right)",
      "Setting the group's transfer pricing policy",
      "Publishing the annual report",
    ],
    correct: 1,
    explanation: "Operational ABM is about doing things right — improving the efficiency and cost of existing activities. Choosing products and customers is strategic ABM (doing the right things), while transfer pricing policy and annual reporting are unrelated to ABM.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "APM2-B-16", paper: "APM", area: "B", type: "number",
    stem: "A new device will sell at a market-driven price of $50 per unit. The company requires a profit margin of 30% of the selling price. What is the target cost per unit, in $?",
    numericAnswer: 35, unit: "$", tolerance: 0.01,
    explanation: "Target cost = selling price − required profit = $50 − (30% × $50) = $50 − $15 = $35. The margin is a percentage of selling price, so dividing $50 by 1.30 ($38.46) is the classic error of treating it as a mark-up on cost.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "APM2-B-17", paper: "APM", area: "B", type: "mcq",
    stem: "Having identified a target cost gap, a company normally closes it by:",
    options: [
      "Increasing the selling price above the market price",
      "Ignoring the required profit margin",
      "Using value engineering and redesign to reduce the expected cost to the target",
      "Adding the gap to the budget as slack",
    ],
    correct: 2,
    explanation: "The cost gap is closed by re-engineering the product and process to cut cost down to the target. Raising price above the market price would lose sales, ignoring the margin defeats the purpose, and building the gap into the budget as slack simply accepts the excess cost.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-B-18", paper: "APM", area: "B", type: "number",
    stem: "A product's expected lifetime costs are: research and development $520,000; variable production cost $18 per unit for 40,000 units; marketing $160,000; and end-of-life disposal $100,000. What is the life-cycle cost per unit, in $?",
    numericAnswer: 37.5, unit: "$", tolerance: 0.1,
    explanation: "Total life-cycle cost = $520,000 + (40,000 × $18) + $160,000 + $100,000 = $520,000 + $720,000 + $160,000 + $100,000 = $1,500,000; per unit = $1,500,000 ÷ 40,000 = $37.50. Omitting R&D or disposal costs would understate the true lifetime unit cost.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-B-19", paper: "APM", area: "B", type: "mcq",
    stem: "The recognised phases of a product's life cycle are:",
    options: [
      "Prevention, appraisal, internal failure and external failure",
      "Plan, do, check and act",
      "Political, economic, social and technological",
      "Introduction, growth, maturity and decline",
    ],
    correct: 3,
    explanation: "A product passes through introduction, growth, maturity and decline. The other options list the quality-cost categories, the PDCA improvement cycle and the PEST factors respectively — none is the product life cycle.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "APM2-B-20", paper: "APM", area: "B", type: "number",
    stem: "A product sells for $90 per unit and has a direct material cost of $30 per unit. Each unit uses 0.5 hours on the bottleneck resource. Using throughput accounting, what is the throughput return per bottleneck hour, in $?",
    numericAnswer: 120, unit: "$", tolerance: 0.1,
    explanation: "Throughput per unit = selling price − material cost = $90 − $30 = $60. Return per bottleneck hour = $60 ÷ 0.5 hours = $120. Throughput deducts only material (not labour or overhead), and the divisor must be bottleneck time, not total processing time.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-B-21", paper: "APM", area: "B", type: "number",
    stem: "A product earns throughput of $48 per unit and uses 0.4 bottleneck hours per unit. The factory's operating expenses (total factory cost) are $80 per bottleneck hour. What is the throughput accounting ratio (TPAR), to two decimal places?",
    numericAnswer: 1.5, unit: "ratio", tolerance: 0.01,
    explanation: "Return per bottleneck hour = $48 ÷ 0.4 = $120. TPAR = return per factory hour ÷ cost per factory hour = $120 ÷ $80 = 1.50. Dividing throughput per unit ($48) by the cost per hour, or inverting the ratio, would give the wrong answer.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "APM2-B-22", paper: "APM", area: "B", type: "mcq",
    stem: "A throughput accounting ratio (TPAR) greater than 1 indicates that:",
    options: [
      "The product's throughput per bottleneck hour exceeds its factory cost per bottleneck hour, so it is worth producing",
      "The product is making a loss and should be dropped",
      "The material cost exceeds the selling price",
      "The bottleneck has been eliminated",
    ],
    correct: 0,
    explanation: "A TPAR above 1 means throughput per bottleneck hour is greater than operating cost per bottleneck hour, so the product earns more than it costs to run the factory time — worth producing. A ratio below 1 (not above) signals a loss; material exceeding selling price would give negative throughput; and the ratio does not measure whether a bottleneck exists.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "APM2-B-23", paper: "APM", area: "B", type: "number",
    stem: "Verdiga Co incurs the following quality-related costs: quality training $40,000; inspection of finished goods $55,000; reworking defects found before dispatch $30,000; and customer warranty claims $75,000. What is the total cost of conformance (prevention plus appraisal), in $?",
    numericAnswer: 95000, unit: "$", tolerance: 1,
    explanation: "Cost of conformance = prevention + appraisal. Prevention = quality training $40,000; appraisal = inspection $55,000; total = $40,000 + $55,000 = $95,000. Rework ($30,000) is internal failure and warranty claims ($75,000) are external failure — both are costs of NON-conformance and are excluded here.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "APM2-B-24", paper: "APM", area: "B", type: "mcq",
    stem: "In the four categories of quality cost, the cost of inspecting and testing incoming raw materials is classified as:",
    options: ["A prevention cost", "An appraisal cost", "An internal failure cost", "An external failure cost"],
    correct: 1,
    explanation: "Inspection and testing to check whether quality standards are met are appraisal costs. Prevention costs stop defects arising in the first place, internal failure costs arise from defects found before dispatch, and external failure costs arise after goods reach the customer.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "APM2-B-25", paper: "APM", area: "B", type: "mcq",
    stem: "The cost of handling customer warranty claims for faulty goods already delivered is classified as:",
    options: ["A prevention cost", "An appraisal cost", "An external failure cost", "An internal failure cost"],
    correct: 2,
    explanation: "A defect discovered by the customer after delivery gives rise to an external failure cost, such as a warranty claim. Prevention and appraisal are costs of conformance incurred before failure, and internal failure applies only to defects caught before the goods leave the business.",
    marks: 2, difficulty: "medium",
  },

  /* ── Transfer pricing & divisionalisation ── */
  {
    id: "APM2-B-26", paper: "APM", area: "B", type: "number",
    stem: "Division A of Trentwood Co makes a component with a variable cost of $18 per unit. It has NO spare capacity and can sell every unit externally at $30. From a goal-congruent viewpoint, what is the minimum transfer price Division A should accept, in $?",
    numericAnswer: 30, unit: "$", tolerance: 0.01,
    explanation: "Minimum transfer price = marginal cost + opportunity cost. Marginal cost = $18; opportunity cost of transferring internally = lost external contribution = $30 − $18 = $12; so minimum = $18 + $12 = $30 (equal to the external price when at full capacity). Ignoring the opportunity cost would wrongly give $18.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-B-27", paper: "APM", area: "B", type: "number",
    stem: "Division B of Trentwood Co takes the transferred component, does further processing, and sells the finished product for $50 per unit, incurring its own additional variable cost of $9 per unit. Division B cannot buy the component from any outside supplier. What is the maximum transfer price Division B would be willing to pay, in $?",
    numericAnswer: 41, unit: "$", tolerance: 0.01,
    explanation: "With no external supply, the maximum a buying division will pay equals its net marginal revenue = final selling price − own additional variable cost = $50 − $9 = $41. Above $41 the further processing would not cover its own cost. Using the $50 selling price alone ignores Division B's own $9 cost.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "APM2-B-28", paper: "APM", area: "B", type: "mcq",
    stem: "The general economic rule for setting a minimum transfer price is:",
    options: [
      "Full absorption cost plus a standard mark-up",
      "The external market price in every situation",
      "Whatever price the buying division is willing to pay",
      "Marginal cost plus any opportunity cost to the transferring division",
    ],
    correct: 3,
    explanation: "The minimum transfer price is marginal cost plus the transferring division's opportunity cost (which is zero when spare capacity exists). Full cost plus mark-up can distort decisions, market price only applies where a perfect external market exists, and 'whatever the buyer will pay' describes the maximum, not the minimum.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-B-29", paper: "APM", area: "B", type: "mcq",
    stem: "Why can a transfer price set at full cost plus a mark-up lead to dysfunctional decisions?",
    options: [
      "It converts the supplying division's fixed costs and profit into an apparent variable cost to the buying division, distorting group-optimal decisions",
      "It is always exactly equal to marginal cost",
      "It can never be calculated in practice",
      "It is identical to a market-based transfer price",
    ],
    correct: 0,
    explanation: "Full cost plus mark-up makes the supplier's fixed cost and profit look like a variable cost to the buyer, so the buyer may reject internally beneficial trades. It is not equal to marginal cost, it is readily calculable, and it is not the same as a market-based price.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "APM2-B-30", paper: "APM", area: "B", type: "mcq",
    stem: "Which of the following is a genuine benefit of divisionalisation?",
    options: [
      "It always eliminates goal congruence problems",
      "It improves local decision speed and manager motivation through delegated authority",
      "It removes the need for any head-office control",
      "It guarantees that total group costs will fall",
    ],
    correct: 1,
    explanation: "Delegating authority to divisions speeds up local decisions and motivates managers who control their own results. Divisionalisation can actually worsen goal congruence, still requires head-office control, and does not guarantee lower total costs (it can add duplication).",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-B-31", paper: "APM", area: "B", type: "mcq",
    stem: "A division whose manager is held accountable for profit AND for the investment in the division's assets is a:",
    options: ["Cost centre", "Revenue centre", "Investment centre", "Discretionary cost centre"],
    correct: 2,
    explanation: "Accountability for both profit and the asset investment defines an investment centre (evaluated by measures such as ROI and residual income). A cost centre is responsible only for costs, a revenue centre only for revenues, and a discretionary cost centre only for a spending budget.",
    marks: 2, difficulty: "easy",
  },

  /* ── Human & behavioural impact of performance measures ── */
  {
    id: "APM2-B-32", paper: "APM", area: "B", type: "mcq",
    stem: "Rewarding divisional managers solely on short-term reported profit is likely to cause:",
    options: [
      "Perfect goal congruence with long-term strategy",
      "Excessive long-term investment",
      "Reduced attention to reported profit",
      "Short-termism, such as cutting research or maintenance to boost current profit",
    ],
    correct: 3,
    explanation: "Tying rewards only to short-term profit encourages managers to sacrifice the future — for example cutting R&D or maintenance to lift this year's figure. It does not create goal congruence, it discourages (not encourages) long-term investment, and managers would focus more, not less, on reported profit.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-B-33", paper: "APM", area: "B", type: "mcq",
    stem: "The maxim 'what gets measured gets managed' can have a dysfunctional effect because:",
    options: [
      "Managers may focus only on measured targets and game them, neglecting important unmeasured factors",
      "It guarantees that all organisational objectives are met",
      "Measurement removes all bias from managers' decisions",
      "Only financial measures can ever be manipulated",
    ],
    correct: 0,
    explanation: "When only certain things are measured, managers may concentrate on and manipulate those measures while ignoring important areas that are not measured (tunnel vision). Measurement does not guarantee all objectives are met, does not remove bias, and both financial and non-financial measures can be gamed.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "APM2-B-34", paper: "APM", area: "B", type: "mcq",
    stem: "Allowing managers to participate in setting their own budgets can:",
    options: [
      "Guarantee tighter budgets in every case",
      "Improve motivation and acceptance but risk the building-in of budgetary slack",
      "Remove the need for any senior review of budgets",
      "Always reduce the accuracy of forecasts",
    ],
    correct: 1,
    explanation: "Participation tends to raise commitment and acceptance, but managers may negotiate easy targets, creating slack. It does not guarantee tighter budgets, it does not remove the need for senior review, and participation often improves — rather than always reduces — forecast accuracy.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "APM2-B-35", paper: "APM", area: "B", type: "mcq",
    stem: "The controllability principle states that a manager should be:",
    options: [
      "Held responsible for all divisional costs without exception",
      "Evaluated only on total group-wide profit",
      "Judged solely on non-financial measures",
      "Assessed only on the costs and revenues that they can significantly influence",
    ],
    correct: 3,
    explanation: "Under the controllability principle, managers are judged only on items they can significantly influence, which improves fairness and motivation. Holding them responsible for all costs (including uncontrollable ones), for total group profit, or for non-financial measures alone all breach that principle.",
    marks: 2, difficulty: "hard",
  },
]
