import type { AccaQuestion } from "@/lib/acca-content"

/** Original questions closing MA official Area B coverage gaps. */
export const MA_OFFICIAL_QUESTIONS: AccaQuestion[] = [
  { id: "MA-B-O01", paper: "MA", area: "B", type: "mcq", stem: "A company divides customers into retail, wholesale and government groups, then randomly samples within each group. Which method is used?", options: ["Cluster sampling", "Stratified sampling", "Systematic sampling", "Quota sampling"], correct: 1, explanation: "The population is divided into relevant strata and a random sample is drawn within each. Cluster sampling would select whole groups rather than sample inside every group.", marks: 2, difficulty: "easy" },
  { id: "MA-B-O02", paper: "MA", area: "B", type: "mcq", stem: "Which data item is ORDINAL?", options: ["Department name", "Customer satisfaction: poor, fair, good, excellent", "Number of returns", "Delivery time in minutes"], correct: 1, explanation: "The satisfaction categories have a meaningful order but the gaps are not measurable equal intervals. Department is nominal, returns are discrete and time is continuous.", marks: 2, difficulty: "easy" },
  { id: "MA-B-O03", paper: "MA", area: "B", type: "mcq", stem: "A dataset is strongly positively skewed by a few exceptionally large values. Which average is generally least distorted by those extremes?", options: ["Arithmetic mean", "Median", "Range", "Variance"], correct: 1, explanation: "The median depends on position and is robust to extreme values. The mean is pulled toward the large observations; range and variance are dispersion measures.", marks: 2, difficulty: "medium" },
  { id: "MA-B-O04", paper: "MA", area: "B", type: "mcq", stem: "The correlation coefficient between advertising spend and sales is +0.92. Which conclusion is justified?", options: ["Advertising definitely causes sales", "There is a strong positive linear association in the observed data", "92% of sales are caused by advertising", "There is no relationship"], correct: 1, explanation: "A coefficient near +1 indicates strong positive linear association, not causation. The coefficient of determination would be r squared, not r itself.", marks: 2, difficulty: "medium" },
  { id: "MA-B-O05", paper: "MA", area: "B", type: "mcq", stem: "For a fitted regression, r = −0.80. What is the coefficient of determination?", options: ["−80%", "−64%", "64%", "80%"], correct: 2, explanation: "r² = (−0.80)² = 0.64 or 64%. Squaring removes the sign; r² describes explained variation associated with the fitted linear relationship.", marks: 2, difficulty: "medium" },
  { id: "MA-B-O06", paper: "MA", area: "B", type: "mcq", stem: "A forecast uses trend × seasonal index. Which time-series model is being used?", options: ["Additive", "Multiplicative", "High-low", "Simple random sampling"], correct: 1, explanation: "Multiplicative seasonality applies a proportion or index to trend. An additive model adds or subtracts a seasonal amount.", marks: 2, difficulty: "easy" },
  { id: "MA-B-O07", paper: "MA", area: "B", type: "mcq", stem: "A project returns $4,000 with probability 0.25 and $12,000 with probability 0.75. What is its expected value?", options: ["$6,000", "$8,000", "$10,000", "$12,000"], correct: 2, explanation: "Expected value = 0.25 × $4,000 + 0.75 × $12,000 = $1,000 + $9,000 = $10,000. It is a probability-weighted average, not a guaranteed outcome.", marks: 2, difficulty: "easy" },
  { id: "MA-B-O08", paper: "MA", area: "B", type: "mcq", stem: "A price rises from 80 in the base period to 92. What is the simple price index, with base 100?", options: ["87.0", "92.0", "112.0", "115.0"], correct: 3, explanation: "Index = current ÷ base × 100 = 92 ÷ 80 × 100 = 115.", marks: 2, difficulty: "easy" },
  { id: "MA-B-O09", paper: "MA", area: "B", type: "mcq", stem: "Which statement correctly distinguishes Laspeyres and Paasche price indices?", options: ["Laspeyres uses current quantities; Paasche uses base quantities", "Laspeyres uses base quantities; Paasche uses current quantities", "Both are always unweighted", "Paasche cannot compare prices"], correct: 1, explanation: "Laspeyres fixes base-period quantities as weights; Paasche uses current-period quantities.", marks: 2, difficulty: "hard" },
  { id: "MA-B-O10", paper: "MA", area: "B", type: "mcq", stem: "Which is a spreadsheet CONTROL rather than merely a spreadsheet feature?", options: ["A chart", "A SUM formula", "Locked formula cells with input validation and independent review", "Changing font colour"], correct: 2, explanation: "Protection, validation and review reduce unauthorised change and input or logic error. Formulas and charts provide functionality but are not sufficient controls by themselves.", marks: 2, difficulty: "medium" },
  { id: "MA-B-O11", paper: "MA", area: "B", type: "mcq", stem: "Transaction records stored in fixed database fields are which kind of big data?", options: ["Structured", "Semi-structured only", "Unstructured", "Inferential"], correct: 0, explanation: "Fixed fields and defined relationships are structured data. Free-form audio or text is unstructured; tagged formats such as JSON are commonly semi-structured.", marks: 2, difficulty: "easy" },
  { id: "MA-B-O12", paper: "MA", area: "B", type: "mcq", stem: "Which limitation is specific to the high-low method?", options: ["It cannot estimate a linear cost", "It uses only two activity observations and may be distorted if either is unusual", "It requires every observation", "It proves causation"], correct: 1, explanation: "High-low deliberately uses only the highest and lowest activity observations, ignoring the rest. An outlier or structural difference at either point can distort the estimate.", marks: 2, difficulty: "medium" },
]

