import type { AccaQuestion } from "@/lib/acca-content"
/* PM bank wave 3a — areas A+B, 70 verified originals (2026-07-10). */
export const PM_WAVE2A: AccaQuestion[] = [
  /* ═══════════ AREA A — Specialist cost & management accounting ═══════════ */

  /* ── ABC costing ── */
  {
    id: "PM2-A-01", paper: "PM", area: "A", type: "mcq",
    stem: "Brontley Co makes two products. Product X: 5,000 units made in 25 production runs. Product Y: 10,000 units made in 15 production runs. Set-up costs of $120,000 are driven by the number of production runs. Under ABC, what is the set-up cost per unit of Product X?",
    options: ["$8.00", "$9.00", "$12.00", "$15.00"],
    correct: 3,
    explanation: "Rate = $120,000 ÷ 40 runs = $3,000 per run; X gets 25 × $3,000 = $75,000 ÷ 5,000 units = $15.00. $8.00 absorbs on units (volume, not the driver), $9.00 uses Y's 15 runs, and $12.00 splits the pool 50:50 between products instead of by driver count.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-A-02", paper: "PM", area: "A", type: "mcq",
    stem: "In which situation is ABC most likely to produce product costs materially different from traditional absorption costing?",
    options: [
      "When direct costs form the great majority of total product cost",
      "When overheads are high and products consume support activities in different proportions to their production volumes",
      "When all products are produced in identical batch sizes with identical complexity",
      "When overheads are almost entirely driven by production volume",
    ],
    correct: 1,
    explanation: "ABC differs from absorption costing when large overheads are driven by non-volume factors (set-ups, orders, inspections) consumed unevenly across products. If overheads are small, volume-driven, or consumed in proportion to volume, both systems give similar answers.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "PM2-A-03", paper: "PM", area: "A", type: "mcq",
    stem: "Kelver Co's quality inspection cost pool is $45,600 and 380 inspections are performed in total. Product P (4,000 units) requires 50 inspections; Product Q (12,000 units) requires 330. Under ABC, what is the inspection cost per unit of Product P?",
    options: ["$1.50", "$2.85", "$9.90", "$11.40"],
    correct: 0,
    explanation: "Rate = $45,600 ÷ 380 = $120 per inspection; P bears 50 × $120 = $6,000 ÷ 4,000 units = $1.50. $2.85 absorbs the pool over total units, $9.90 uses Q's 330 inspections, and $11.40 charges the whole pool to P alone.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-A-04", paper: "PM", area: "A", type: "mcq",
    stem: "In an ABC hierarchy of activities, machine set-up costs incurred once for each production run are best classified as:",
    options: ["Unit-level costs", "Facility-sustaining costs", "Batch-level costs", "Product-sustaining costs"],
    correct: 2,
    explanation: "Set-ups happen once per batch/run, so cost varies with the number of runs, not units — a batch-level activity. Calling them unit-level wrongly assumes they rise with every unit; product-sustaining costs (e.g. design updates) support a product line regardless of batches.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "PM2-A-05", paper: "PM", area: "A", type: "mcq",
    stem: "Dunmar Co has two overhead pools: set-ups $60,000 (40 set-ups in total) and materials handling $80,000 (500 moves in total). Product Z: 2,000 units, 12 set-ups, 150 moves, 2,500 direct labour hours. Total direct labour hours are 8,750. What is Z's overhead cost per unit under ABC?",
    options: ["$9.00", "$20.00", "$21.00", "$35.00"],
    correct: 2,
    explanation: "Set-ups: 12 × ($60,000/40) = $18,000; handling: 150 × ($80,000/500) = $24,000; total $42,000 ÷ 2,000 = $21.00. $9.00 forgets the handling pool, $20.00 is the labour-hour absorption answer (2,500 × $16 ÷ 2,000), and $35.00 splits each pool equally between the two products.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "PM2-A-06", paper: "PM", area: "A", type: "mcq",
    stem: "Which of the following is a genuine limitation of activity-based costing?",
    options: [
      "Collecting and maintaining cost driver data can be costly and time-consuming",
      "It is less accurate than a single blanket overhead rate",
      "It cannot be applied to service businesses",
      "It ignores overhead costs entirely",
    ],
    correct: 0,
    explanation: "ABC's main practical drawback is the cost and effort of identifying activities and measuring drivers. It is generally more (not less) accurate than a blanket rate, works well in services (which are overhead-heavy), and exists precisely to assign overheads.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "PM2-A-07", paper: "PM", area: "A", type: "mcq",
    stem: "Ordering costs of $27,000 are driven by purchase orders. Product L: 900 units, 150 orders. Product M: 3,600 units, 300 orders. Under ABC, the ordering cost per unit of Product L is:",
    options: ["$6.00", "$10.00", "$15.00", "$20.00"],
    correct: 1,
    explanation: "Rate = $27,000 ÷ 450 orders = $60; L bears 150 × $60 = $9,000 ÷ 900 = $10.00. $6.00 absorbs the pool over the 4,500 total units, $15.00 splits the pool equally between products, and $20.00 uses M's 300 orders by mistake.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-A-08", paper: "PM", area: "A", type: "mcq",
    stem: "Nexon Co currently absorbs all overhead on machine hours. Product V accounts for 5% of machine hours but 40% of set-ups and 35% of purchase orders, which drive most overhead. If Nexon switches to ABC, V's reported unit cost will most likely:",
    options: [
      "Fall, because low-volume products are always cheaper under ABC",
      "Stay the same, because total overhead is unchanged",
      "Fall, because V's share of machine hours is small",
      "Rise, because V consumes support activities out of proportion to its machine hours",
    ],
    correct: 3,
    explanation: "ABC reassigns overhead by activity consumption, so a product using 40% of set-ups but only 5% of machine hours has been undercosted and its cost rises. Total overhead being unchanged does not keep each product's share unchanged, and a small machine-hour share is exactly why it was undercosted before.",
    marks: 2, difficulty: "hard",
  },

  /* ── Target costing ── */
  {
    id: "PM2-A-09", paper: "PM", area: "A", type: "number",
    stem: "A new fitness tracker will be launched at a market-driven price of $60. The company requires a profit margin of 25% of the selling price. What is the target cost per unit, in $?",
    numericAnswer: 45, unit: "$",
    explanation: "Target cost = price − required profit = $60 − (25% × $60) = $45. The margin is a percentage of the selling price, not a markup on cost — dividing $60 by 1.25 ($48) is the classic error.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "PM2-A-10", paper: "PM", area: "A", type: "mcq",
    stem: "Ostrell Co will sell a smart doorbell at $120 and requires a margin of 30% of the selling price. The current estimated production cost is $97 per unit. What is the target cost gap per unit?",
    options: ["$4.69", "$13.00", "$23.00", "$36.00"],
    correct: 1,
    explanation: "Target cost = $120 × 70% = $84; gap = $97 − $84 = $13.00. $4.69 treats 30% as a markup on cost ($120 ÷ 1.3 = $92.31), $23.00 is price minus current cost (forgetting the required profit), and $36.00 is the required profit itself, not the gap.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-A-11", paper: "PM", area: "A", type: "mcq",
    stem: "A company has identified a target cost gap on a new product. Which action is most consistent with the target costing philosophy for closing the gap?",
    options: [
      "Raise the planned selling price until the gap disappears",
      "Reduce the required profit margin to whatever the current cost allows",
      "Use value engineering to redesign out features customers do not value",
      "Reclassify some variable costs as fixed so they are excluded from the unit cost",
    ],
    correct: 2,
    explanation: "In target costing the price is set by the market and the profit is required by shareholders, so the cost must come down — typically through value engineering of the design before production. Raising the price or trimming the margin abandons the discipline, and reclassifying costs changes nothing real.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-A-12", paper: "PM", area: "A", type: "mcq",
    stem: "Pravik Co will sell a product at $88 per unit and requires a return of 25% on cost (a markup). What is the target cost per unit?",
    options: ["$63.00", "$66.00", "$70.40", "$110.00"],
    correct: 2,
    explanation: "With a 25% markup on cost, price = cost × 1.25, so target cost = $88 ÷ 1.25 = $70.40. $66.00 wrongly treats 25% as a margin on the selling price, $63.00 subtracts $25 as an absolute amount, and $110.00 multiplies by 1.25 instead of dividing.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "PM2-A-13", paper: "PM", area: "A", type: "mcq",
    stem: "Which sequence correctly describes the target costing process?",
    options: [
      "Set the market selling price, deduct the required profit, then engineer the product to the resulting cost",
      "Estimate the production cost, add the required profit, then set the selling price",
      "Set the required profit, add competitor prices, then average the two",
      "Estimate the production cost, deduct the required profit, then set the selling price",
    ],
    correct: 0,
    explanation: "Target costing starts from the outside in: market price first, profit deducted, cost engineered to fit. Option B is cost-plus pricing — the exact opposite mindset — and the others are muddles of the two.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "PM2-A-14", paper: "PM", area: "A", type: "mcq",
    stem: "A new appliance is expected to sell 40,000 units over its life at $25 each. The company requires a total lifetime profit of $160,000. The current design has an estimated cost of $22.50 per unit. What is the target cost gap per unit?",
    options: ["$1.50", "$2.50", "$4.00", "$21.00"],
    correct: 0,
    explanation: "Target cost per unit = ($1,000,000 revenue − $160,000 profit) ÷ 40,000 = $21.00; gap = $22.50 − $21.00 = $1.50. $2.50 compares price with current cost (ignoring required profit), $4.00 is the required profit per unit, and $21.00 is the target cost itself, not the gap.",
    marks: 2, difficulty: "hard",
  },

  /* ── Life-cycle costing ── */
  {
    id: "PM2-A-15", paper: "PM", area: "A", type: "mcq",
    stem: "At which stage of a product's life cycle is the largest proportion of its total lifetime cost typically committed (locked in)?",
    options: [
      "The decline stage, when disposal costs are paid",
      "The maturity stage, when volumes peak",
      "The growth stage, when capacity is expanded",
      "The design and development stage, before production begins",
    ],
    correct: 3,
    explanation: "Around 70–90% of lifetime costs are committed by design decisions (materials, technology, process) made before launch, even though the cash is spent later. Confusing when costs are incurred with when they are committed is the classic trap.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "PM2-A-16", paper: "PM", area: "A", type: "number",
    stem: "A product's expected lifetime figures are: development $360,000; variable production cost $15 per unit for 50,000 units; marketing $190,000; end-of-life decommissioning $50,000. What is the life-cycle cost per unit, in $?",
    numericAnswer: 27, unit: "$",
    explanation: "Total = $360,000 + (50,000 × $15) + $190,000 + $50,000 = $1,350,000; ÷ 50,000 units = $27. Life-cycle costing includes every phase — omitting development or decommissioning understates the true unit cost.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-A-17", paper: "PM", area: "A", type: "mcq",
    stem: "Qorix Co expects the following for a new gadget: development $250,000; manufacturing 20,000 units at $8 variable cost each; marketing and distribution $90,000; end-of-life disposal $40,000. The life-cycle cost per unit is:",
    options: ["$8.00", "$14.50", "$25.00", "$27.00"],
    correct: 3,
    explanation: "Total = $250,000 + $160,000 + $90,000 + $40,000 = $540,000 ÷ 20,000 = $27.00. $8.00 is manufacturing cost only, $14.50 omits development, and $25.00 omits the end-of-life disposal cost.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-A-18", paper: "PM", area: "A", type: "mcq",
    stem: "Which set of characteristics best describes the maturity stage of the product life cycle?",
    options: [
      "Heavy R&D spending, no revenue, negative cash flow",
      "Sales at their peak, intense price competition, focus on cost control and defending market share",
      "Rapidly accelerating sales growth and falling unit costs as capacity builds",
      "Falling sales and a decision point about withdrawal and disposal costs",
    ],
    correct: 1,
    explanation: "Maturity means the market is saturated: volumes peak, competitors fight on price, and management focuses on efficiency and retention. Option A describes development, C growth, and D decline.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-A-19", paper: "PM", area: "A", type: "mcq",
    stem: "A product's lifetime costs are: development $400,000; variable production $12 per unit for 30,000 units; fixed production cash costs $140,000; decommissioning $60,000. What minimum average selling price over the life cycle is needed to break even on a life-cycle basis?",
    options: ["$12.00", "$18.67", "$30.00", "$32.00"],
    correct: 3,
    explanation: "Total life-cycle cost = $400,000 + $360,000 + $140,000 + $60,000 = $960,000 ÷ 30,000 = $32.00. $12.00 covers only variable cost, $18.67 excludes development, and $30.00 excludes decommissioning — all understate the price needed over the whole life.",
    marks: 2, difficulty: "hard",
  },

  /* ── Throughput accounting ── */
  {
    id: "PM2-A-20", paper: "PM", area: "A", type: "mcq",
    stem: "Under throughput accounting, which costs are treated as truly variable with production?",
    options: [
      "Direct material costs only",
      "Direct materials and direct labour",
      "All production costs except depreciation",
      "Prime cost plus variable overheads",
    ],
    correct: 0,
    explanation: "Throughput accounting assumes that in the short term only direct material varies with output; labour and overheads are treated as fixed 'total factory costs'. Deducting labour as well is the marginal-costing habit that gives the wrong throughput figure.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "PM2-A-21", paper: "PM", area: "A", type: "number",
    stem: "A product sells for $80 with a direct material cost of $32 per unit, and each unit needs 0.4 hours on the bottleneck resource. What is the throughput return per bottleneck hour, in $?",
    numericAnswer: 120, unit: "$",
    explanation: "Throughput per unit = $80 − $32 = $48; per bottleneck hour = $48 ÷ 0.4 = $120. Divide by bottleneck time, not total processing time, and deduct only material — not labour or overhead.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-A-22", paper: "PM", area: "A", type: "mcq",
    stem: "Hivern Co's product sells at $50 with material cost $20 and direct labour of $10 per unit. Each unit takes 0.25 hours on the bottleneck; the bottleneck runs for 960 hours. Total factory costs (labour plus overheads) are $86,400, and total machine hours across all processes are 1,600. The throughput accounting ratio (TPAR) is:",
    options: ["0.75", "0.89", "1.33", "2.22"],
    correct: 2,
    explanation: "Return per bottleneck hour = ($50 − $20) ÷ 0.25 = $120; cost per bottleneck hour = $86,400 ÷ 960 = $90; TPAR = 120 ÷ 90 = 1.33. 0.75 inverts the ratio, 0.89 wrongly deducts labour from throughput, and 2.22 spreads factory cost over the 1,600 total machine hours instead of bottleneck hours.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-A-23", paper: "PM", area: "A", type: "mcq",
    stem: "A product's TPAR is 0.85. Which interpretation is correct?",
    options: [
      "The product is profitable but less so than others in the range",
      "The product's throughput return is less than the factory cost of the bottleneck time it uses, so it is currently loss-making in throughput terms",
      "The product should immediately be discontinued regardless of other considerations",
      "The bottleneck has 15% spare capacity",
    ],
    correct: 1,
    explanation: "TPAR below 1 means each bottleneck hour spent on the product generates less throughput than it costs to run. That signals a problem to fix (raise price, cut material cost, reduce bottleneck time) — not an automatic discontinuation, and it says nothing about spare capacity.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-A-24", paper: "PM", area: "A", type: "mcq",
    stem: "Two products pass through a bottleneck machine. P: price $60, material $24, bottleneck time 0.5 hours. Q: price $45, material $15, bottleneck time 0.2 hours. Bottleneck capacity is insufficient for full demand of both. Which product should be made first, and why?",
    options: [
      "P, because it has the higher throughput per unit ($36 vs $30)",
      "P, because it has the higher selling price",
      "Q, because it has the lower material cost",
      "Q, because it earns the higher throughput per bottleneck hour ($150 vs $72)",
    ],
    correct: 3,
    explanation: "With a bottleneck, rank by throughput per bottleneck hour: Q = $30 ÷ 0.2 = $150 vs P = $36 ÷ 0.5 = $72, so Q first. Ranking by throughput per unit, price, or material cost ignores how much scarce bottleneck time each unit consumes.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "PM2-A-25", paper: "PM", area: "A", type: "mcq",
    stem: "Vestra Co's only bottleneck has 2,000 hours available. Its single product sells for $90, has material cost $36 and direct labour of $10 per unit, and needs 0.4 bottleneck hours per unit. Demand is 6,000 units. Total factory costs are $216,000. What is the maximum throughput profit?",
    options: ["$4,000", "$54,000", "$108,000", "$270,000"],
    correct: 1,
    explanation: "Capacity = 2,000 ÷ 0.4 = 5,000 units (below the 6,000 demand); throughput = 5,000 × ($90 − $36) = $270,000; less factory costs $216,000 = $54,000. $108,000 uses demand and ignores the bottleneck, $270,000 forgets factory costs, and $4,000 wrongly deducts labour from throughput.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "PM2-A-26", paper: "PM", area: "A", type: "mcq",
    stem: "A product sells for $100 with material cost $40 and uses 0.5 bottleneck hours per unit; factory cost per bottleneck hour is $80 (TPAR = 1.5). Which single action increases TPAR the most?",
    options: [
      "Cut material cost per unit by 10%",
      "Increase output at a non-bottleneck process by 20%",
      "Reduce bottleneck time per unit from 0.5 to 0.4 hours",
      "Cut total factory costs by 10%",
    ],
    correct: 2,
    explanation: "Reducing bottleneck time lifts the return per bottleneck hour to $60 ÷ 0.4 = $150, giving TPAR 150/80 = 1.875, beating the material cut (128/80 = 1.60) and the cost cut (120/72 = 1.67). Producing more at a non-bottleneck just builds inventory and leaves TPAR unchanged.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-A-27", paper: "PM", area: "A", type: "mcq",
    stem: "Orpin Co's factory costs are direct labour $165,000 and production overheads $33,000; direct materials cost $72,000. The bottleneck resource has 5,500 hours available and total machine hours across all processes are 9,000. For TPAR purposes, the cost per factory hour is:",
    options: ["$22.00", "$30.00", "$36.00", "$49.09"],
    correct: 2,
    explanation: "Cost per factory hour = total factory costs (labour + overheads = $198,000) ÷ bottleneck hours 5,500 = $36.00. $22.00 divides by the 9,000 total machine hours instead of bottleneck hours, $30.00 omits overheads, and $49.09 wrongly includes direct materials in factory cost.",
    marks: 2, difficulty: "medium",
  },

  /* ── Environmental costing ── */
  {
    id: "PM2-A-28", paper: "PM", area: "A", type: "mcq",
    stem: "Which of the following is one of the recognised environmental management accounting techniques in the PM syllabus?",
    options: [
      "Input/output (mass balance) analysis",
      "Sensitivity analysis",
      "Balanced scorecard reporting",
      "Zero-based budgeting",
    ],
    correct: 0,
    explanation: "The four EMA techniques are input/output analysis, flow cost accounting, environmental activity-based costing and life-cycle costing. Sensitivity analysis, the balanced scorecard and ZBB are general PM tools, not specifically environmental accounting techniques.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "PM2-A-29", paper: "PM", area: "A", type: "mcq",
    stem: "Using the standard environmental cost categories (prevention, detection, internal failure, external failure), a fine paid to the regulator for contaminating a local river is classified as:",
    options: [
      "A prevention cost",
      "A detection cost",
      "An internal failure cost",
      "An external failure cost",
    ],
    correct: 3,
    explanation: "External failure costs arise after contamination has been released into the environment — fines, clean-up and reputational remediation. Internal failure costs are incurred when waste is caught and dealt with before release; prevention and detection costs are incurred to avoid or find problems.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-A-30", paper: "PM", area: "A", type: "mcq",
    stem: "An input/output analysis shows 1,200 kg of material entering a process but only 950 kg leaving in good output. Material costs $8 per kg and waste disposal costs $3 per kg of waste. What is the total cost of the waste?",
    options: ["$750", "$2,000", "$2,750", "$3,600"],
    correct: 2,
    explanation: "Waste = 250 kg; cost = purchase cost lost 250 × $8 = $2,000 plus disposal 250 × $3 = $750, totalling $2,750. $2,000 forgets disposal, $750 forgets the material's purchase cost, and $3,600 charges disposal on all 1,200 kg of input rather than the waste.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-A-31", paper: "PM", area: "A", type: "mcq",
    stem: "An environmental management accounting technique that traces materials through the organisation and classifies costs into material, system, and delivery & disposal categories is known as:",
    options: [
      "Environmental life-cycle costing",
      "Flow cost accounting",
      "Environmental activity-based costing",
      "Sustainability variance analysis",
    ],
    correct: 1,
    explanation: "Flow cost accounting follows physical material flows and values them under material, system and delivery & disposal categories, making the cost of losses visible. Life-cycle costing spans time (cradle to grave) and environmental ABC assigns environmental overheads via drivers.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-A-32", paper: "PM", area: "A", type: "mcq",
    stem: "Halden Co spreads its $80,000 waste-disposal cost across all 40,000 units produced as general overhead. In reality the waste is caused entirely by Product D (8,000 units). By how much per unit is D's environmental cost understated under the blanket approach?",
    options: ["$2.00", "$8.00", "$10.00", "$12.00"],
    correct: 1,
    explanation: "D should bear $80,000 ÷ 8,000 = $10 per unit but is charged only $80,000 ÷ 40,000 = $2, an understatement of $8. This is why environmental costs hidden in general overheads distort product profitability — $10.00 is the correct charge, not the understatement, and $2.00 is the blanket charge itself.",
    marks: 2, difficulty: "hard",
  },

  /* ═══════════ AREA B — Decision-making techniques ═══════════ */

  /* ── CVP analysis ── */
  {
    id: "PM2-B-01", paper: "PM", area: "B", type: "mcq",
    stem: "Rilton Co sells a single product at $30 per unit with a variable cost of $18 per unit. Fixed costs are $84,000. The breakeven point in units is:",
    options: ["1,750", "2,800", "4,667", "7,000"],
    correct: 3,
    explanation: "Breakeven = fixed costs ÷ contribution per unit = $84,000 ÷ ($30 − $18) = 7,000 units. 2,800 divides by the selling price, 4,667 divides by the variable cost, and 1,750 divides by price plus variable cost (adding instead of subtracting).",
    marks: 2, difficulty: "easy",
  },
  {
    id: "PM2-B-02", paper: "PM", area: "B", type: "number",
    stem: "A product sells for $45. Costs per unit: direct materials $12, direct labour $8, variable overhead $5, fixed overhead absorbed $6. What is the contribution per unit, in $?",
    numericAnswer: 20, unit: "$",
    explanation: "Contribution = $45 − ($12 + $8 + $5) = $20. Fixed overhead absorbed per unit is excluded — deducting it too gives $14 and confuses contribution with profit.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "PM2-B-03", paper: "PM", area: "B", type: "mcq",
    stem: "Budgeted sales are 12,000 units and the breakeven point is 9,000 units. The margin of safety as a percentage is:",
    options: ["25.0%", "33.3%", "75.0%", "133.3%"],
    correct: 0,
    explanation: "Margin of safety = (12,000 − 9,000) ÷ 12,000 = 25%, expressed on budgeted sales. 33.3% divides the 3,000-unit cushion by breakeven sales instead, 75% is breakeven ÷ budget, and 133.3% is budget ÷ breakeven.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-B-04", paper: "PM", area: "B", type: "mcq",
    stem: "Selmore Co has fixed costs of $120,000 and a C/S (contribution-to-sales) ratio of 0.40. What sales revenue is needed to achieve a target profit of $60,000?",
    options: ["$72,000", "$150,000", "$300,000", "$450,000"],
    correct: 3,
    explanation: "Required revenue = (fixed costs + target profit) ÷ C/S ratio = $180,000 ÷ 0.40 = $450,000. $300,000 forgets the target profit (breakeven only), $150,000 covers only the profit, and $72,000 multiplies by the ratio instead of dividing.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-B-05", paper: "PM", area: "B", type: "number",
    stem: "Fenwick Co has fixed costs of $66,000 and a C/S ratio of 0.30. What is the breakeven sales revenue, in $?",
    numericAnswer: 220000, unit: "$",
    explanation: "Breakeven revenue = fixed costs ÷ C/S ratio = $66,000 ÷ 0.30 = $220,000. Multiplying by the ratio instead of dividing ($19,800) is the common slip.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-B-06", paper: "PM", area: "B", type: "mcq",
    stem: "Tarian Co sells two products in a constant revenue mix: A provides 60% of revenue with a C/S ratio of 0.45; B provides 40% with a C/S ratio of 0.30. Fixed costs are $156,000. The breakeven revenue is:",
    options: ["$346,667", "$400,000", "$416,000", "$520,000"],
    correct: 1,
    explanation: "Weighted C/S = (0.60 × 0.45) + (0.40 × 0.30) = 0.39, so breakeven = $156,000 ÷ 0.39 = $400,000. $416,000 uses a simple (unweighted) average of 0.375, while $346,667 and $520,000 use only A's or only B's ratio.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "PM2-B-07", paper: "PM", area: "B", type: "mcq",
    stem: "Which statement about multi-product CVP analysis is correct?",
    options: [
      "The breakeven point is the same whatever the sales mix, provided total revenue is unchanged",
      "Each product's individual breakeven point can simply be added to give the company breakeven point",
      "The calculated breakeven point is valid only for the assumed constant sales mix",
      "Multi-product breakeven cannot be calculated when products have different C/S ratios",
    ],
    correct: 2,
    explanation: "Multi-product CVP uses a weighted-average C/S ratio, which holds only while the mix stays constant — sell more of the low-margin product and breakeven rises. Individual breakevens cannot be added because fixed costs are shared, and different C/S ratios are exactly what the weighted average handles.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "PM2-B-08", paper: "PM", area: "B", type: "mcq",
    stem: "Corvale Co's product sells for $25 with a contribution of $15 per unit. Fixed costs are $90,000. How many units must be sold to earn a profit of $45,000?",
    options: ["3,000", "6,000", "9,000", "13,500"],
    correct: 2,
    explanation: "Units = (fixed costs + target profit) ÷ contribution = $135,000 ÷ $15 = 9,000. 6,000 ignores the target profit, 3,000 covers only the profit, and 13,500 divides by the $10 variable cost instead of the contribution.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-B-09", paper: "PM", area: "B", type: "mcq",
    stem: "Which of the following is a genuine limitation of conventional CVP (breakeven) analysis?",
    options: [
      "It assumes selling price and variable cost per unit are constant at all activity levels",
      "It cannot be used when fixed costs exist",
      "It can only be applied to service industries",
      "It requires knowledge of the profit-maximising price equation",
    ],
    correct: 0,
    explanation: "CVP assumes linearity — constant price, constant unit variable cost, fixed costs unchanged, and a constant mix — which rarely holds across wide output ranges. Fixed costs are central to the model, not a barrier, and no demand equation is needed.",
    marks: 2, difficulty: "easy",
  },

  /* ── Limiting factors & linear programming ── */
  {
    id: "PM2-B-10", paper: "PM", area: "B", type: "mcq",
    stem: "Melwood Co makes X (contribution $24/unit, 3 labour hours) and Y (contribution $20/unit, 2 labour hours). Maximum demand is 2,000 units of X and 3,000 units of Y; only 9,000 labour hours are available. What is the maximum total contribution?",
    options: ["$60,000", "$78,000", "$84,000", "$108,000"],
    correct: 2,
    explanation: "Rank by contribution per hour: Y $10 beats X $8, so make 3,000 Y (6,000 hrs, $60,000) then 1,000 X with the remaining 3,000 hrs ($24,000) = $84,000. $78,000 ranks by contribution per unit (X first), $108,000 ignores the labour limit, and $60,000 makes only Y.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "PM2-B-11", paper: "PM", area: "B", type: "mcq",
    stem: "Next period Ardley Co needs 10,000 kg of material (8,000 kg available), 4,500 labour hours (5,000 available) and 3,200 machine hours (3,000 available). Which resources are limiting factors?",
    options: [
      "Materials only",
      "Materials and machine hours",
      "Labour hours only",
      "All three resources",
    ],
    correct: 1,
    explanation: "A resource is limiting when requirements exceed availability: materials (10,000 > 8,000) and machine hours (3,200 > 3,000) are short, but labour has 500 spare hours. Comparing availability with requirement — not the absolute size of the numbers — is the test.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "PM2-B-12", paper: "PM", area: "B", type: "mcq",
    stem: "A product earns a contribution of $18 per unit and uses 4 kg of a scarce material. Its contribution per kg of the limiting factor is:",
    options: ["$0.22", "$4.50", "$18.00", "$72.00"],
    correct: 1,
    explanation: "Contribution per limiting-factor unit = $18 ÷ 4 kg = $4.50 per kg. $0.22 inverts the division (kg ÷ contribution), $18.00 is contribution per unit of product, and $72.00 multiplies instead of dividing.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-B-13", paper: "PM", area: "B", type: "mcq",
    stem: "In a linear programming problem, product A requires 2 machining hours per unit and product B requires 5. Only 4,000 machining hours are available. With x units of A and y units of B, the machining constraint is:",
    options: ["2x + 5y ≤ 4,000", "2x + 5y ≥ 4,000", "5x + 2y ≤ 4,000", "x + y ≤ 4,000"],
    correct: 0,
    explanation: "Hours used (2 per A, 5 per B) must not exceed 4,000, giving 2x + 5y ≤ 4,000. The ≥ version reverses the inequality, 5x + 2y swaps the coefficients between products, and x + y ignores the per-unit hour requirements.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-B-14", paper: "PM", area: "B", type: "mcq",
    stem: "Maximise contribution C = 8x + 6y subject to labour 2x + y ≤ 1,000, materials x + 2y ≤ 800, and x, y ≥ 0. What is the maximum contribution?",
    options: ["$2,400", "$4,000", "$4,400", "$6,000"],
    correct: 2,
    explanation: "At the intersection of the constraints, x = 400 and y = 200, giving C = $3,200 + $1,200 = $4,400 — higher than the single-product corners (500, 0) = $4,000 and (0, 400) = $2,400. $6,000 takes y = 1,000 from the labour line while ignoring the materials constraint (infeasible).",
    marks: 2, difficulty: "hard",
  },
  {
    id: "PM2-B-15", paper: "PM", area: "B", type: "mcq",
    stem: "At Jorvik Co's optimal plan, both constraints bind: labour 3x + 2y = 1,800 hours and material x + 2y = 1,000 kg, with contributions of $18 (X) and $14 (Y) per unit (optimum x = 400, y = 300). What is the shadow price of one labour hour?",
    options: ["$0.00", "$5.50", "$6.00", "$18.00"],
    correct: 1,
    explanation: "Add one labour hour and re-solve: 3x + 2y = 1,801 with x + 2y = 1,000 gives x = 400.5, y = 299.75, raising contribution by 18(0.5) + 14(−0.25) = $5.50 — the shadow price. $6.00 is merely X's contribution per labour hour ($18 ÷ 3), $18.00 is contribution per unit, and $0 would apply only to a non-binding constraint.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "PM2-B-16", paper: "PM", area: "B", type: "mcq",
    stem: "Which statement about shadow (dual) prices in linear programming is correct?",
    options: [
      "Every constraint in the problem has a positive shadow price",
      "The shadow price is the market price the company currently pays for the resource",
      "The shadow price includes an allowance for fixed costs",
      "The shadow price is the extra contribution earned from one additional unit of a binding (scarce) resource",
    ],
    correct: 3,
    explanation: "A shadow price is the increase in total contribution from relaxing a binding constraint by one unit; it also caps the premium worth paying above the normal resource cost. Non-binding constraints have a zero shadow price, and the figure is about contribution, not market price or fixed costs.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-B-17", paper: "PM", area: "B", type: "mcq",
    stem: "A constraint in an LP model is 2x + 3y ≤ 600 machine hours. The optimal solution is x = 90, y = 120. What is the slack on this constraint?",
    options: ["0 hours", "60 hours", "390 hours", "540 hours"],
    correct: 1,
    explanation: "Usage = 2(90) + 3(120) = 540 hours, so slack = 600 − 540 = 60 unused hours, meaning the constraint is non-binding. 540 is the usage rather than the slack, 390 wrongly subtracts the unit quantities (90 + 120) from 600, and 0 assumes the constraint binds.",
    marks: 2, difficulty: "medium",
  },

  /* ── Pricing decisions & strategies ── */
  {
    id: "PM2-B-18", paper: "PM", area: "B", type: "mcq",
    stem: "Demand for Lumen Co's product follows P = 120 − 0.02Q and marginal cost is constant at $48 per unit. Using MR = 120 − 0.04Q, the profit-maximising selling price is:",
    options: ["$48", "$60", "$84", "$120"],
    correct: 2,
    explanation: "Set MR = MC: 120 − 0.04Q = 48 gives Q = 1,800, then price from the demand curve: P = 120 − 0.02(1,800) = $84. $48 sets price equal to marginal cost, $60 maximises revenue (MR = 0) instead of profit, and $120 is the demand-curve intercept.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "PM2-B-19", paper: "PM", area: "B", type: "mcq",
    stem: "Market-skimming pricing is most appropriate when:",
    options: [
      "The product is genuinely innovative, early adopters' demand is price-inelastic, and entry barriers protect the position",
      "Demand is highly price-elastic and large economies of scale are available",
      "The market is mature with many close substitutes",
      "The company wants to deter new entrants by keeping margins low",
    ],
    correct: 0,
    explanation: "Skimming launches high to harvest the surplus of price-insensitive early adopters, then lowers price in stages — it needs novelty, inelastic demand and protection from fast copying. Elastic demand with scale economies and entry-deterrence describe penetration pricing.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "PM2-B-20", paper: "PM", area: "B", type: "mcq",
    stem: "The main objective of a penetration pricing strategy for a new product is to:",
    options: [
      "Recover research and development costs as quickly as possible",
      "Signal premium quality through a high launch price",
      "Maximise short-term unit profit margins",
      "Set a low launch price to win market share rapidly and discourage competitors from entering",
    ],
    correct: 3,
    explanation: "Penetration pricing sacrifices early margin for volume, share and scale economies, raising the barrier for would-be entrants. Fast cost recovery and quality signalling are skimming rationales, and short-term margin maximisation is the opposite of penetration.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "PM2-B-21", paper: "PM", area: "B", type: "mcq",
    stem: "A product has a variable cost of $24 per unit and absorbs fixed overhead of $16 per unit. The company prices at full cost plus 25%. The selling price is:",
    options: ["$30.00", "$46.00", "$50.00", "$53.33"],
    correct: 2,
    explanation: "Full cost = $24 + $16 = $40; price = $40 × 1.25 = $50.00. $30.00 marks up the variable cost only, $46.00 adds 25% of the variable cost to full cost, and $53.33 treats 25% as a margin on the selling price ($40 ÷ 0.75).",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-B-22", paper: "PM", area: "B", type: "mcq",
    stem: "For price discrimination between two markets to be effective and profitable, which condition is essential?",
    options: [
      "The markets can be kept separate and buyers in the cheap market cannot resell to the expensive one",
      "Both markets must have identical price elasticities of demand",
      "Unit variable cost must differ between the two markets",
      "The product must be a commodity with many identical substitutes",
    ],
    correct: 0,
    explanation: "Discrimination requires segments with different elasticities that can be kept apart — otherwise arbitrage (seepage) collapses the high price. Identical elasticities remove the reason to discriminate, and cost differences are not required (that would just be differential costing).",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-B-23", paper: "PM", area: "B", type: "mcq",
    stem: "At $20 Farrow Co sells 10,000 units; each $1 price cut adds 2,000 units of demand. Variable cost is $9 per unit and fixed costs are unaffected. Which price maximises profit?",
    options: ["$15", "$16", "$17", "$20"],
    correct: 2,
    explanation: "Contribution peaks at $17: 16,000 × $8 = $128,000, versus $126,000 at both $18 and $16. $15 maximises revenue rather than contribution, $16 cuts one step past the peak, and $20 wrongly assumes the highest unit margin means the highest total profit.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "PM2-B-24", paper: "PM", area: "B", type: "mcq",
    stem: "A printer manufacturer sells its printers close to cost but earns high margins on the ink cartridges only its printers accept. This pricing approach is best described as:",
    options: [
      "Complementary product (captive product) pricing",
      "Price skimming on the printers",
      "Going-rate pricing",
      "Volume discounting",
    ],
    correct: 0,
    explanation: "Pricing the base product low and the tied consumable high is complementary/captive product pricing — profit is earned over the ownership cycle. Skimming would mean a high printer launch price, and going-rate pricing simply matches competitors.",
    marks: 2, difficulty: "easy",
  },

  /* ── Relevant costing & make-or-buy ── */
  {
    id: "PM2-B-25", paper: "PM", area: "B", type: "mcq",
    stem: "Grayling Co is deciding whether to accept a one-off contract. Which of the following is a relevant cost of the contract?",
    options: [
      "$12,000 of market research on the contract commissioned and paid for last month",
      "Depreciation of $6,000 on machinery already owned",
      "A $9,000 share of head-office costs apportioned to the contract",
      "$7,500 of extra part-time wages that will be paid only if the contract goes ahead",
    ],
    correct: 3,
    explanation: "Relevant costs are future incremental cash flows: the extra wages arise only if the contract is accepted. The market research is sunk, depreciation is a non-cash allocation, and apportioned head-office cost is not incremental.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "PM2-B-26", paper: "PM", area: "B", type: "number",
    stem: "A job needs 500 kg of material M. 200 kg are in inventory (bought at $4/kg); M is no longer used elsewhere and the stock could be sold for $2.50/kg. New M costs $5/kg. What is the relevant cost of material M for the job, in $?",
    numericAnswer: 2000, unit: "$",
    explanation: "Buy 300 kg at $5 = $1,500, plus the opportunity cost of the stock used, 200 × $2.50 = $500, totalling $2,000. The $4 historic price is sunk — pricing all 500 kg at $5 ($2,500) or using the $4 book value are the classic errors.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-B-27", paper: "PM", area: "B", type: "mcq",
    stem: "A contract needs 400 labour hours at a wage of $10 per hour. 250 hours can come from paid idle time; the other 150 hours must be diverted from work earning a contribution of $12 per hour (after labour cost). The relevant cost of labour is:",
    options: ["$1,500", "$3,300", "$4,000", "$8,800"],
    correct: 1,
    explanation: "Idle-time hours cost nothing extra (wages are paid anyway); diverted hours cost wage plus lost contribution: 150 × ($10 + $12) = $3,300. $4,000 charges the wage on all 400 hours, $1,500 forgets the lost contribution, and $8,800 applies the $22 opportunity rate to every hour.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-B-28", paper: "PM", area: "B", type: "mcq",
    stem: "Bexley Co needs 5,000 units of a component. Making it costs $18 per unit variable, plus $20,000 of fixed costs avoidable if production stops, plus $25,000 of apportioned head-office fixed costs. An outside supplier offers the component at $23 per unit. Bexley should:",
    options: [
      "Make — it is $5,000 cheaper than buying",
      "Make — it is $25,000 cheaper than buying",
      "Buy — it is $20,000 cheaper than making",
      "Buy — it is $5,000 cheaper than making",
    ],
    correct: 0,
    explanation: "Relevant cost to make = (5,000 × $18) + $20,000 avoidable fixed = $110,000 vs buying at $115,000, so making saves $5,000. Ignoring the avoidable fixed costs gives 'make saves $25,000'; including the unavoidable $25,000 apportionment gives 'buy saves $20,000'.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-B-29", paper: "PM", area: "B", type: "mcq",
    stem: "For a special order, Torvel Co needs: 800 kg of material in regular use (book value $5/kg, replacement cost $6/kg); 200 labour hours at $12/hour with the workforce at full capacity on work earning $9 contribution per hour (after labour); variable overhead of $3 per labour hour. Machine depreciation of $1,000 and apportioned fixed overhead of $1,500 have also been quoted. The minimum price for the order is:",
    options: ["$5,400", "$7,800", "$9,600", "$12,100"],
    correct: 2,
    explanation: "Minimum price = relevant cost: materials 800 × $6 = $4,800 (replacement, as they are in regular use) + labour 200 × ($12 + $9) = $4,200 + variable overhead $600 = $9,600. $7,800 omits the lost contribution, $5,400 treats labour as free because workers are already employed, and $12,100 adds the irrelevant depreciation and apportioned fixed overhead.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "PM2-B-30", paper: "PM", area: "B", type: "mcq",
    stem: "An opportunity cost is best defined as:",
    options: [
      "A cost that has already been incurred and cannot be recovered",
      "The benefit forgone from the next best alternative use of a resource",
      "A notional charge added to make departments aware of asset use",
      "A cost that will be incurred whichever option is chosen",
    ],
    correct: 1,
    explanation: "Opportunity cost is the contribution or benefit sacrificed by using a resource for one purpose instead of its best alternative — it is a real relevant cost even though no invoice exists. Option A is a sunk cost, C a notional cost, and D a committed/common cost.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "PM2-B-31", paper: "PM", area: "B", type: "mcq",
    stem: "A joint product can be sold at split-off for $40,000, or processed further at a cost of $15,000 and sold for $52,000. Joint costs of $30,000 have already been apportioned to it. What should the company do?",
    options: [
      "Process further — profit rises by $12,000",
      "Process further — profit rises by $7,000",
      "Sell at split-off — the company is better off by $15,000",
      "Sell at split-off — the company is better off by $3,000",
    ],
    correct: 3,
    explanation: "Compare incremental revenue ($52,000 − $40,000 = $12,000) with further processing cost ($15,000): processing loses $3,000, so sell at split-off. The $30,000 joint cost is sunk and irrelevant; the '$12,000 gain' answer ignores the further costs, and '$7,000' wrongly nets off the joint costs.",
    marks: 2, difficulty: "hard",
  },

  /* ── Risk & uncertainty ── */
  {
    id: "PM2-B-32", paper: "PM", area: "B", type: "mcq",
    stem: "A decision maker who selects the option whose worst possible outcome is the best of all the worst outcomes is applying which criterion?",
    options: ["Expected value", "Maximax", "Minimax regret", "Maximin"],
    correct: 3,
    explanation: "Maximin (best of the worst) reflects risk aversion or pessimism. Maximax picks the best best-case (optimist), minimax regret minimises the maximum opportunity loss, and expected value weights outcomes by probability for a risk-neutral decision maker.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "PM2-B-33", paper: "PM", area: "B", type: "number",
    stem: "A project's outcomes are: $20,000 profit with probability 0.3; $50,000 profit with probability 0.5; a $10,000 loss with probability 0.2. What is the expected value of the project, in $?",
    numericAnswer: 29000, unit: "$",
    explanation: "EV = (0.3 × 20,000) + (0.5 × 50,000) + (0.2 × −10,000) = 6,000 + 25,000 − 2,000 = $29,000. Forgetting the minus sign on the loss (giving $33,000) is the usual slip.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-B-34", paper: "PM", area: "B", type: "mcq",
    stem: "Harlan Co must choose one launch scale before demand is known (P(weak) = 0.7, P(strong) = 0.3). Payoffs in $000 — Small: 80 weak / 110 strong; Medium: 60 / 160; Large: 20 / 240. Under the maximin criterion, which option is chosen?",
    options: [
      "Small, because its worst outcome ($80,000) is the best of the worst outcomes",
      "Medium, because it has the highest expected value",
      "Large, because it offers the highest possible payoff",
      "Small if demand is weak, Large if demand is strong",
    ],
    correct: 0,
    explanation: "Maximin compares worst cases — 80, 60 and 20 — and picks Small. Medium is the expected-value choice (EV 90 vs 89 and 86) and Large the maximax choice, but neither is the maximin rule; choosing per demand state is impossible because the decision precedes knowledge of demand.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-B-35", paper: "PM", area: "B", type: "mcq",
    stem: "Payoffs in $000 for four projects under two states (P(S1) = 0.7, P(S2) = 0.3) — W: 45 / 160; X: 60 / 60; Y: 0 / 200; Z: 55 / 150. Under the minimax regret criterion, which project is selected?",
    options: ["Project W", "Project X", "Project Y", "Project Z"],
    correct: 0,
    explanation: "Regrets against the best in each state (60 in S1, 200 in S2) give maximum regrets of W 40, X 140, Y 60 and Z 50 — W minimises the maximum regret. X is the maximin choice, Y the maximax choice and Z the highest-EV choice (83.5), each answering a different criterion.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "PM2-B-36", paper: "PM", area: "B", type: "mcq",
    stem: "Two options with two states (P(S1) = 0.4, P(S2) = 0.6): Option A pays $100,000 / $40,000; Option B pays $30,000 / $90,000. What is the maximum amount worth paying for perfect information about the state?",
    options: ["$2,000", "$28,000", "$30,000", "$94,000"],
    correct: 1,
    explanation: "EV with perfect information = 0.4 × 100,000 + 0.6 × 90,000 = $94,000; best EV without = B at $66,000 (A is $64,000); EVPI = $28,000. $94,000 forgets to deduct the without-information EV, $30,000 deducts the inferior option's EV, and $2,000 is just the gap between the two options' EVs.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "PM2-B-37", paper: "PM", area: "B", type: "mcq",
    stem: "Selby Co must choose a launch. National: 0.6 chance of $200,000 profit, 0.4 chance of a $60,000 loss. Regional: 0.6 chance of $110,000, 0.4 chance of $30,000. Using expected values on the decision tree, what is the EV of the optimal decision?",
    options: ["$78,000", "$96,000", "$174,000", "$200,000"],
    correct: 1,
    explanation: "EV(National) = 0.6 × 200,000 − 0.4 × 60,000 = $96,000; EV(Regional) = 66,000 + 12,000 = $78,000; choose National at $96,000. $78,000 picks the safer branch (not the EV rule), $174,000 sums both branches instead of choosing one, and $200,000 takes the best payoff while ignoring probabilities.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "PM2-B-38", paper: "PM", area: "B", type: "mcq",
    stem: "Which statement identifies a key limitation of using expected values for decision-making?",
    options: [
      "Expected values cannot be calculated when probabilities are known",
      "Expected values always favour the riskiest option",
      "Expected values double-count outcomes that have high probabilities",
      "The EV is a long-run average that may never equal any actual outcome, making it unsuitable for one-off decisions",
    ],
    correct: 3,
    explanation: "EV weights outcomes by probability, so for a one-off decision the 'average' result (e.g. $29,000 from outcomes of $50,000 and −$10,000) may be impossible to achieve, and the spread (risk) is ignored. EV needs probabilities, is risk-neutral rather than risk-seeking, and involves no double-counting.",
    marks: 2, difficulty: "easy",
  },
]
