import type { AccaQuestion } from "@/lib/acca-content"

/*
 * AA bank wave 8b part 2 — 32 verified originals (2026-07-13).
 * Blueprint: D16 E16; difficulty 9 easy / 15 medium / 8 hard.
 * All mcq, marks 2. Every scenario is invented (original client names, none
 * reused from earlier waves) and every distractor is a nameable student
 * error. Opinion questions verified against the ISA 705 matrix: misstatement
 * material-not-pervasive → qualified, pervasive → adverse; insufficient
 * evidence material-not-pervasive → qualified, pervasive → disclaimer.
 */

export const AA_WAVE3B: AccaQuestion[] = [
  /* ───────────── Area D — Audit evidence (16) ───────────── */
  {
    id: "AA4-D-01",
    paper: "AA",
    area: "D",
    type: "mcq",
    stem: "The audit junior on Thackwell Joinery Ltd proposes to double the sample size of internally generated delivery dockets 'to make up for the fact that they are not very reliable'. Which statement about audit evidence is TRUE?",
    options: [
      "Sufficiency refers to the quality of evidence, so a bigger sample automatically improves it",
      "Sufficiency measures the QUANTITY of evidence and appropriateness its QUALITY (relevance and reliability) — obtaining more poor-quality evidence does not make it appropriate",
      "Doubling the sample size fully compensates for the low reliability of the documents",
      "Appropriateness measures how many relevant items have been examined",
    ],
    correct: 1,
    explanation:
      "ISA 500 splits the requirement in two: SUFFICIENCY is the measure of quantity, APPROPRIATENESS the measure of quality — relevance plus reliability. The two interact (higher quality can mean less is needed) but quantity can never cure a quality problem: a mountain of unreliable internal dockets is still unreliable. Options 1 and 4 simply swap the definitions, and option 3 is the junior's exact mistake restated.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AA4-D-02",
    paper: "AA",
    area: "D",
    type: "mcq",
    stem: "The auditor of Umberside Motors Ltd is concerned that trade payables at 31 March are UNDERSTATED. Which procedure best addresses this risk?",
    options: [
      "Select a sample of the largest recorded payables balances and vouch them to supplier invoices",
      "Circularise a sample of suppliers selected from the year-end payables ledger",
      "Recalculate the ageing of the payables ledger at the year end",
      "Review cash payments made after the year end and unmatched goods received notes, and trace them back to confirm the related liability was recorded at 31 March",
    ],
    correct: 3,
    explanation:
      "Unrecorded liabilities cannot be found by sampling what is already in the ledger — you must start OUTSIDE the recorded population. After-date payments and unmatched GRNs are exactly where hidden year-end liabilities surface, and tracing them back tests COMPLETENESS. Vouching recorded balances to invoices (option 1) and circularising ledger balances (option 2) test the existence direction, and re-ageing the ledger (option 3) says nothing about what is missing.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA4-D-03",
    paper: "AA",
    area: "D",
    type: "mcq",
    stem: "The auditor of Corngate Wholesale plc uses monetary unit sampling (MUS) to test the receivables ledger. Which statement about MUS is TRUE?",
    options: [
      "Each individual $1 in the population is a sampling unit, so higher-value balances have a proportionately greater chance of being selected",
      "Every customer balance has an equal chance of selection regardless of its value",
      "MUS is particularly effective at detecting understated and nil balances",
      "MUS is a non-statistical method because the auditor uses judgement to pick the items",
    ],
    correct: 0,
    explanation:
      "In MUS the sampling unit is the individual monetary unit, so a $500,000 balance is 100 times more likely to be hit than a $5,000 one — the method automatically biases selection towards high-value items, which is why it suits testing asset balances for OVERSTATEMENT. Equal chance per balance (option 2) describes simple random selection of items, not MUS. Its recognised WEAKNESS is understated, nil and negative balances (option 3 states the opposite), and MUS is a statistical technique (option 4).",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AA4-D-04",
    paper: "AA",
    area: "D",
    type: "mcq",
    stem: "The audit team of Ashfell Textiles Ltd is choosing how to select a sample of sales invoices for testing. Which selection method is LEAST likely to produce a representative sample?",
    options: [
      "Random selection using a random number generator",
      "Systematic selection of every 40th invoice from a random starting point",
      "Block selection — testing every invoice raised during the first week of June",
      "Monetary unit selection weighted by invoice value",
    ],
    correct: 2,
    explanation:
      "BLOCK selection takes a cluster of contiguous items, so the conclusion really only covers that block — one week in June tells you little about the other 51 weeks, and errors are rarely spread evenly through the year. Random, systematic (with a random start and no pattern in the population) and monetary unit selection all give every item, or every $1, a known chance of selection. Students pick block sampling in practice because it is quick — which is precisely why examiners flag it.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AA4-D-05",
    paper: "AA",
    area: "D",
    type: "mcq",
    stem: "The finance director of Perrancove Ltd refuses to allow the auditor to send a confirmation request to one major customer, saying the relationship is 'commercially sensitive'. Under ISA 505 the auditor should:",
    options: [
      "Accept the refusal without further work, because management controls contact with customers",
      "Inquire into the reasons for the refusal, evaluate whether they are valid, consider the implications for fraud risk, and perform alternative procedures on the balance",
      "Immediately qualify the audit opinion for a limitation of scope",
      "Send the confirmation request to the customer anyway, without telling management",
    ],
    correct: 1,
    explanation:
      "ISA 505 treats a management refusal as a red flag, not a full stop: the auditor asks WHY, assesses whether the reason is reasonable, considers what it means for the risk assessment (including fraud), and obtains the evidence another way (after-date cash, GDNs, invoices). Simply accepting the refusal abandons skepticism; qualifying IMMEDIATELY skips the alternative procedures that may resolve the issue; and confirming behind management's back breaches the auditor's duty of confidentiality to the client.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA4-D-06",
    paper: "AA",
    area: "D",
    type: "mcq",
    stem: "Which of the following BEST describes a substantive analytical procedure over the payroll expense of Glenrothan Ltd?",
    options: [
      "Building an independent expectation of total payroll from last year's cost, adjusted for starters, leavers and the 4% pay award, comparing it with the recorded figure and investigating any difference above a set threshold",
      "Inspecting a sample of monthly payroll runs for evidence of the finance director's authorisation",
      "Comparing each month's payroll to the previous month and accepting the figure if no month looks unusual",
      "Analytical procedures cannot be used as substantive evidence over payroll",
    ],
    correct: 0,
    explanation:
      "ISA 520 requires a proper substantive analytical procedure to have four steps: develop an INDEPENDENT, sufficiently precise expectation, define an acceptable difference, compare with the recorded amount, and investigate variances — the 'proof in total' in option 1. Inspecting authorisations (option 2) is a TEST OF CONTROLS, not analytical. Casual month-to-month scanning with no expectation or threshold (option 3) lacks the precision to count as substantive evidence. Payroll — predictable and formula-driven — is actually the classic candidate for this technique, so option 4 is backwards.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA4-D-07",
    paper: "AA",
    area: "D",
    type: "mcq",
    stem: "Silverbeck Insurance plc's financial statements include a significant claims provision estimated by management. Under ISA 540, which of the following is a VALID approach to auditing this estimate?",
    options: [
      "Accept the estimate because it has been formally approved by the board of directors",
      "Rely solely on a written representation that the provision is management's best estimate",
      "Ask management to remove the provision because its amount is inherently uncertain",
      "Develop the auditor's own point estimate or range from independent data and compare it with management's figure",
    ],
    correct: 3,
    explanation:
      "ISA 540 gives three response strategies: obtain evidence from events up to the auditor's report date, test how management made the estimate (data, methods, assumptions), or develop an AUDITOR'S OWN estimate or range — option 4. Board approval is management evidence about management's own number, not independent support. Written representations can never stand alone where better evidence should exist. And uncertainty is a reason to AUDIT an estimate carefully, never a reason to delete a liability that IAS 37 requires.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA4-D-08",
    paper: "AA",
    area: "D",
    type: "mcq",
    stem: "Maplecross Retail plc has an internal audit department that has already tested controls over the inventory cycle. The external auditor wishes to use this work under ISA 610. Which statement is TRUE?",
    options: [
      "Because internal audit reports to the audit committee, its work may be used without any evaluation",
      "Using internal audit's work transfers part of the responsibility for the audit opinion to the internal auditors",
      "The external auditor must evaluate internal audit's objectivity, competence and systematic, disciplined approach, re-perform some of the work, and remains solely responsible for the opinion",
      "Internal audit staff may determine materiality for the external audit provided they are supervised",
    ],
    correct: 2,
    explanation:
      "ISA 610 sets three gates — organisational status/OBJECTIVITY, COMPETENCE, and a SYSTEMATIC AND DISCIPLINED approach including quality control — and even then the external auditor must evaluate and re-perform some of the work relied on. Reporting lines to the audit committee help objectivity but do not waive the evaluation (option 1). Responsibility for the opinion is never shared (option 2), and significant judgements — materiality, risk assessment, opinion decisions — can never be handed to internal audit, supervised or not (option 4).",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AA4-D-09",
    paper: "AA",
    area: "D",
    type: "mcq",
    stem: "A material quantity of Farndon Chemicals Ltd's inventory is stored in a third-party bonded warehouse. Under ISA 501, the auditor should:",
    options: [
      "Request direct confirmation from the warehouse operator of the quantities and condition of inventory held and, where risk warrants it, attend or arrange an inspection of the third party's count",
      "Obtain a written representation from Farndon's management confirming the inventory exists",
      "Inspect the storage contract with the warehouse to verify the inventory balance",
      "Estimate the third-party inventory by extrapolating from the counts performed at Farndon's own sites",
    ],
    correct: 0,
    explanation:
      "ISA 501 is specific: for material inventory held by third parties, obtain DIRECT confirmation from the custodian and/or perform inspection or other procedures (such as attending the third party's count or using another auditor's report on the custodian's controls) as risk dictates. A management representation is internal evidence and cannot substitute for available external evidence. The storage contract proves an arrangement exists, not what is physically on the shelves. Extrapolating from other sites is guesswork, not evidence about THIS inventory.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA4-D-10",
    paper: "AA",
    area: "D",
    type: "mcq",
    stem: "On Wexcombe Ltd's year-end bank reconciliation, the auditor agrees the outstanding lodgements and unpresented cheques to the January bank statement, checking how quickly each item cleared. The PRIMARY purpose of this procedure is to:",
    options: [
      "Test the completeness of revenue recorded in the year",
      "Confirm the reconciling items were genuine at the year end — items that take weeks to clear may indicate window dressing of the cash position",
      "Test the operating effectiveness of the client's monthly reconciliation control",
      "Verify the balance stated on the bank confirmation letter",
    ],
    correct: 1,
    explanation:
      "Reconciling items should clear within days of the year end. A lodgement that does not reach the bank until late January, or cheques unpresented for weeks, suggests the items were recorded before they really happened — WINDOW DRESSING to flatter cash and current ratios. The procedure is substantive work on the bank balance, not a test of the reconciliation CONTROL (option 3), it does not address revenue completeness (option 1), and the confirmation letter verifies the bank's own figure, which needs no help from the reconciliation (option 4).",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AA4-D-11",
    paper: "AA",
    area: "D",
    type: "mcq",
    stem: "Which procedure provides the BEST evidence that Ollerbrook Farms Ltd holds the RIGHTS to the freehold land included in its statement of financial position?",
    options: [
      "Physically inspecting the land and its boundaries",
      "Obtaining an independent surveyor's valuation of the land",
      "Reviewing the board minutes that approved the original purchase",
      "Inspecting the title deeds or land registry records showing the company as registered owner",
    ],
    correct: 3,
    explanation:
      "Rights and obligations are about OWNERSHIP, and for land the definitive evidence is the title deed or land registry entry naming the company. Physical inspection only proves the land EXISTS — the company could be occupying land it rents. A valuation addresses the VALUATION assertion, not who owns the asset. Board minutes show the purchase was authorised, but authorisation is not proof that legal title was ever obtained or is still held.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AA4-D-12",
    paper: "AA",
    area: "D",
    type: "mcq",
    stem: "Tannadyce Ltd is being sued by a former distributor and the claim may require a material provision. Under ISA 501, the most reliable procedure for obtaining evidence about the litigation is to:",
    options: [
      "Rely on the finance director's assessment of the likely outcome of the case",
      "Contact the company's external lawyers directly without informing the client",
      "Send, with management's permission, a letter of inquiry to the company's external lawyers asking them to communicate their assessment directly to the auditor",
      "Assume no provision is required because the case has not yet been decided",
    ],
    correct: 2,
    explanation:
      "ISA 501's answer to litigation and claims is DIRECT communication with the entity's external legal counsel — a letter of inquiry prepared by management (or requesting the lawyer respond to the auditor) with the response coming straight to the auditor, making it reliable external evidence. The FD's view is internal and self-interested. Approaching the lawyers without client consent breaches confidentiality — the lawyer could not respond anyway. And IAS 37 requires a provision whenever an outflow is probable and measurable; waiting for the verdict is not an option.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA4-D-13",
    paper: "AA",
    area: "D",
    type: "mcq",
    stem: "While testing a sample of repairs invoices at Brackenhurst Ltd, the audit senior examined an item containing a clear misstatement but failed to recognise it because she applied an inappropriate procedure. This is an example of:",
    options: [
      "Non-sampling risk",
      "Sampling risk",
      "Control risk",
      "Tolerable misstatement",
    ],
    correct: 0,
    explanation:
      "NON-SAMPLING risk is the risk of a wrong conclusion for reasons UNRELATED to sampling — using an inappropriate procedure, or misinterpreting the evidence in front of you, as here. SAMPLING risk arises only because a sample was tested instead of the whole population; the error item was actually examined, so sampling is not the problem. Control risk belongs to the client's system, not the auditor's work, and tolerable misstatement is a threshold, not a type of risk.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AA4-D-14",
    paper: "AA",
    area: "D",
    type: "mcq",
    stem: "Which statement about STATISTICAL sampling in the audit of Queldon Ltd is TRUE?",
    options: [
      "Haphazard selection may be used provided the results are evaluated using probability theory",
      "It involves random selection of the sample and the use of probability theory to evaluate the results, including measurement of sampling risk",
      "It removes the need for professional judgement in evaluating the results",
      "It always produces smaller sample sizes than non-statistical sampling",
    ],
    correct: 1,
    explanation:
      "A method is only statistical if BOTH conditions hold: random selection AND probability-based evaluation that measures sampling risk. Haphazard selection has no known selection probabilities, so bolting statistics onto it afterwards does not qualify (option 1). Judgement is still needed everywhere — setting parameters, evaluating the nature of errors found (option 3). And sample sizes may be larger or smaller than a judgemental approach; there is no guarantee either way (option 4).",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AA4-D-15",
    paper: "AA",
    area: "D",
    type: "mcq",
    stem: "The auditor of Harnwick Distribution Ltd selects a sample of purchase transactions recorded in the expense ledger and agrees each one back to the supplier invoice, goods received note and purchase order. Which assertion is being tested?",
    options: [
      "Completeness of purchases",
      "Cut-off of purchases",
      "Classification of purchases",
      "Occurrence of purchases",
    ],
    correct: 3,
    explanation:
      "Direction decides everything: starting from the RECORDED entries and vouching back to supporting documents asks 'did these recorded purchases actually happen?' — OCCURRENCE. Completeness runs the opposite way, from GRNs or orders INTO the ledger, asking whether anything is missing; picking completeness here is the classic direction-of-testing error. Cut-off would focus on transactions around the year end, and classification on whether the right expense account was used — neither is the point of this trace.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AA4-D-16",
    paper: "AA",
    area: "D",
    type: "mcq",
    stem: "In addition to confirming the year-end balances on Ledbrook Ltd's current accounts, the standard bank confirmation letter can provide audit evidence about:",
    options: [
      "The recoverability of Ledbrook's trade receivables",
      "The completeness of all liabilities owed by the company to any party",
      "Loans and overdraft facilities, security and charges over the company's assets, and guarantees given to the bank",
      "The accuracy of the client's year-end bank reconciliation",
    ],
    correct: 2,
    explanation:
      "The bank confirmation is a rich document: as well as balances it covers loans and their terms, undrawn facilities, SECURITY and charges the bank holds over assets (relevant to disclosure), guarantees, and other accounts — evidence for liabilities, rights and presentation. It says nothing about trade receivables, which are owed by customers, not the bank. It covers only liabilities TO THAT BANK, never 'all liabilities' (option 2 over-reaches). And the reconciliation is a client schedule the auditor tests separately — the bank has never seen it.",
    marks: 2,
    difficulty: "medium",
  },

  /* ───────────── Area E — Review & reporting (16) ───────────── */
  {
    id: "AA4-E-01",
    paper: "AA",
    area: "E",
    type: "mcq",
    stem: "Strathmuir plc faces a material uncertainty over going concern, but the going concern basis remains appropriate. The directors refuse to include ANY disclosure of the uncertainty in the notes. Which form of auditor's report is appropriate?",
    options: [
      "Unmodified opinion with a 'Material Uncertainty Related to Going Concern' section",
      "Unmodified opinion with an Emphasis of Matter paragraph describing the uncertainty",
      "A qualified or adverse opinion, because the omitted disclosure is a material misstatement of the financial statements",
      "A disclaimer of opinion, because the outcome of the uncertainty cannot be known",
    ],
    correct: 2,
    explanation:
      "The ISA 570 ladder turns on DISCLOSURE: adequately disclosed → unmodified opinion plus a MURGC section; NOT disclosed → the financial statements are materially misstated by omission, so the opinion is modified — qualified or, if the effects are pervasive, adverse. The MURGC section (option 1) is only available when the disclosure exists to point at. An EoM cannot patch a missing disclosure. A disclaimer sits on the evidence branch of ISA 705 — here the auditor knows exactly what is wrong.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA4-E-02",
    paper: "AA",
    area: "E",
    type: "mcq",
    stem: "The chairman's statement in Avoncrest plc's annual report claims revenue grew 40%, but the audited financial statements show growth of 12%. Management refuses to amend the chairman's statement. The financial statements themselves are fairly stated. Under ISA 720 the auditor should:",
    options: [
      "Issue an unmodified opinion and describe the uncorrected material misstatement of the other information in the Other Information section of the auditor's report",
      "Qualify the audit opinion because the annual report contains an error",
      "Add an Emphasis of Matter paragraph drawing attention to the chairman's statement",
      "Withhold the auditor's report until the chairman's statement is corrected",
    ],
    correct: 0,
    explanation:
      "The chairman's statement is OTHER INFORMATION — outside the audited financial statements — so the opinion, which covers only the financial statements, is NOT modified when the statements themselves are fair. ISA 720 requires the auditor to read the other information, seek correction of material misstatements and, if management refuses, report the uncorrected misstatement in the Other Information section (and consider TCWG and, in extreme cases, withdrawal). Qualifying punishes the wrong document; an EoM refers only to matters disclosed IN the financial statements; and the auditor has no general power to withhold the report.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA4-E-03",
    paper: "AA",
    area: "E",
    type: "mcq",
    stem: "Denholm Fabrics Ltd's prior-year financial statements were audited by a different firm, which issued an unmodified opinion. The incoming auditor wishes to make this clear to users of the current-year report. This is achieved through:",
    options: [
      "An Emphasis of Matter paragraph",
      "The Key Audit Matters section",
      "A qualified opinion in respect of the comparative figures",
      "An Other Matter paragraph stating that the prior period was audited by another auditor, the type of opinion issued and its date",
    ],
    correct: 3,
    explanation:
      "An OTHER MATTER paragraph communicates something relevant to users' understanding of the audit or the auditor's report that is NOT presented in the financial statements — a predecessor auditor's involvement is the textbook example. An Emphasis of Matter can only point to a matter appropriately disclosed IN the financial statements, so it is the wrong vehicle; the EoM/OM boundary is the most-tested distinction in ISA 706. KAM covers matters of most significance in the CURRENT audit, and nothing here justifies qualifying — the comparatives received a clean opinion.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA4-E-04",
    paper: "AA",
    area: "E",
    type: "mcq",
    stem: "The audit of Ryecart Ltd identified three uncorrected misstatements of $150,000, $140,000 and $130,000, all overstating profit. Materiality is $250,000. Under ISA 450 the auditor should:",
    options: [
      "Issue an unmodified opinion, because each misstatement is individually below materiality",
      "Request management to correct the misstatements; if they refuse, the opinion must be modified because the aggregate of $420,000 is material",
      "Ask management to correct only the largest misstatement, which brings the aggregate below materiality",
      "Report the three misstatements as Key Audit Matters instead of modifying the opinion",
    ],
    correct: 1,
    explanation:
      "ISA 450 requires misstatements to be evaluated individually AND IN AGGREGATE: $150k + $140k + $130k = $420,000, well above the $250,000 threshold — and all three push profit the same way. The auditor first asks management to correct; refusal leaves a material misstatement and forces a qualified (or adverse, if pervasive) opinion. Judging each error alone (option 1) is exactly the trap the standard exists to close. Correcting only the largest still leaves $270,000 uncorrected — above materiality, so option 3 fails on its own arithmetic. KAM is never a substitute for a modified opinion.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA4-E-05",
    paper: "AA",
    area: "E",
    type: "mcq",
    stem: "Analytical procedures performed near the END of the audit of Milbourne Foods Ltd are:",
    options: [
      "Required, to assess whether the financial statements as a whole are consistent with the auditor's understanding of the entity",
      "Optional, at the discretion of the engagement partner",
      "Performed only if analytical procedures were not used as substantive tests during fieldwork",
      "Designed to provide the primary substantive evidence over revenue",
    ],
    correct: 0,
    explanation:
      "ISA 520 makes final analytical procedures MANDATORY on every audit: near the end, the auditor stands back and checks that the financial statements hang together and match the picture built up during the audit — an inconsistency at this stage sends the team back for more work. Only their use as SUBSTANTIVE procedures during fieldwork is optional, which is the rule students misapply here. They run regardless of what was done during fieldwork, and they corroborate overall conclusions rather than serve as primary evidence for any single balance.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AA4-E-06",
    paper: "AA",
    area: "E",
    type: "mcq",
    stem: "The directors of Crayvale Ltd refuse to provide the written representation acknowledging their responsibility for the financial statements and confirming they have given the auditor all relevant information. Under ISA 580 the auditor should issue:",
    options: [
      "An unmodified opinion, because representations merely confirm evidence already held",
      "A qualified 'except for' opinion",
      "An adverse opinion",
      "A disclaimer of opinion",
    ],
    correct: 3,
    explanation:
      "ISA 580 is unusually absolute: if management refuses the representations about its RESPONSIBILITIES (for the financial statements, and for providing complete information and access), the auditor SHALL disclaim an opinion — the refusal poisons the reliability of every other representation and piece of client-provided evidence, so the doubt is pervasive by nature. That is why 'except for' understates it and why option 1 fails. Adverse is wrong because the auditor has not concluded the statements ARE misstated — the problem is inability to rely on the evidence, the disclaimer branch of the matrix.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AA4-E-07",
    paper: "AA",
    area: "E",
    type: "mcq",
    stem: "The auditor of Netherfold Ltd issues a qualified opinion because a material receivable has not been written down. Where in the auditor's report is the reason for the qualification described?",
    options: [
      "In an Emphasis of Matter paragraph placed at the end of the report",
      "In a 'Basis for Qualified Opinion' section immediately following the Opinion section, including quantification of the financial effects where practicable",
      "In the Key Audit Matters section",
      "In the directors' report accompanying the financial statements",
    ],
    correct: 1,
    explanation:
      "ISA 705 prescribes the architecture: the Opinion section comes first (headed 'Qualified Opinion'), immediately followed by a 'Basis for Qualified Opinion' section that describes the matter and quantifies its effects where practicable. An Emphasis of Matter can never be used to describe a disagreement — if the matter requires modification, EoM is prohibited for it. KAM explicitly excludes matters dealt with in the basis-for-modification section, and the directors' report is management's document, not part of the auditor's report at all.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AA4-E-08",
    paper: "AA",
    area: "E",
    type: "mcq",
    stem: "Three weeks after Skelwith Marine plc's financial statements were ISSUED, the auditor learns of a major fraud that existed at the year end and would have changed the auditor's report. Under ISA 560 the auditor should:",
    options: [
      "Do nothing — responsibility for the financial statements ended when they were issued",
      "Publicly withdraw the audit opinion without consulting management",
      "Discuss the matter with management, determine whether the financial statements need amendment and, if management fails to take steps to inform users, notify those charged with governance and take action to prevent reliance on the report",
      "Wait and correct the matter in next year's financial statements and auditor's report",
    ],
    correct: 2,
    explanation:
      "After issue the auditor has NO duty to search — but a known fact cannot be ignored. ISA 560's sequence: discuss with management, determine whether amendment is needed and how users will be informed; if the statements are revised, audit the amendment and issue a new or amended report; if management refuses to act, notify TCWG and take steps (usually with legal advice) to PREVENT RELIANCE on the report. 'No responsibility' confuses the absence of a search duty with the absence of any duty; unilateral public withdrawal skips the required steps; and deferring a known year-end fraud to next year leaves users relying on wrong statements for a year.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AA4-E-09",
    paper: "AA",
    area: "E",
    type: "mcq",
    stem: "Midway through the audit, the directors of Durnleigh Ltd inform the auditor that no work may be performed on the company's overseas revenue, which represents 55% of total revenue. Under ISA 705 the auditor should:",
    options: [
      "Accept the limitation, since the scope of the audit is set by the engagement letter agreed with management",
      "Issue an unmodified opinion and describe the restriction as a Key Audit Matter",
      "Issue an adverse opinion because revenue is materially misstated",
      "Request that management remove the limitation; if it stands, communicate with those charged with governance and, because the possible effects are pervasive, withdraw from the audit where practicable or disclaim an opinion",
    ],
    correct: 3,
    explanation:
      "A MANAGEMENT-IMPOSED limitation over 55% of revenue has possible effects that are both material and PERVASIVE. ISA 705 sets the escalation path: ask management to remove it, involve TCWG, attempt alternative procedures, and if the evidence gap remains, withdraw where practicable and legally possible — otherwise disclaim. Management cannot contractually shrink an audit below what the ISAs require (option 1). KAM never substitutes for dealing with a scope problem. Adverse is the wrong branch: the auditor has no evidence revenue IS misstated — the problem is not being allowed to look.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AA4-E-10",
    paper: "AA",
    area: "E",
    type: "mcq",
    stem: "Management of Rothgate Leisure Ltd has assessed going concern for a period of only nine months from the 31 December reporting date. Under ISA 570 the auditor should:",
    options: [
      "Ask management to extend its assessment to cover at least twelve months from the reporting date",
      "Accept the nine-month assessment provided no events casting doubt have been identified",
      "Ask management to extend the assessment to twelve months from the date of the auditor's report",
      "Immediately disclaim an opinion because the assessment period is too short",
    ],
    correct: 0,
    explanation:
      "ISA 570 requires the going concern assessment to cover the same period as the applicable framework — under IAS 1, at least TWELVE MONTHS FROM THE END OF THE REPORTING PERIOD — so a nine-month assessment is simply too short and management must be asked to extend it. Option 3 anchors the twelve months to the wrong date (a common muddle with guidance measured from approval or report dates). The absence of doubt so far does not shorten the required period. A disclaimer is only on the table if management REFUSES to extend and the auditor is left without sufficient evidence — not as an opening move.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA4-E-11",
    paper: "AA",
    area: "E",
    type: "mcq",
    stem: "An UNMODIFIED audit opinion on the financial statements of Hobsden Ltd means that, in the auditor's judgement:",
    options: [
      "The financial statements are completely free from all error",
      "The financial statements give a true and fair view (are presented fairly, in all material respects) in accordance with the applicable financial reporting framework",
      "The company is guaranteed to remain a going concern for the foreseeable future",
      "No fraud occurred at the company during the year",
    ],
    correct: 1,
    explanation:
      "The opinion is framed by MATERIALITY and REASONABLE assurance: the statements give a true and fair view in all MATERIAL respects under the applicable framework. It is never a certificate of total accuracy — immaterial errors may well remain (option 1). It offers no guarantee about the future (option 3): going concern work supports the basis of preparation, not the company's survival. And an audit obtains reasonable assurance about material misstatement, whether from fraud or error — it does not certify that no fraud of any size occurred (option 4).",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AA4-E-12",
    paper: "AA",
    area: "E",
    type: "mcq",
    stem: "Under ISA 701, how does the auditor of Varnley plc, a listed company, determine which matters to report as Key Audit Matters?",
    options: [
      "Every significant risk identified at planning is automatically reported as a KAM",
      "The audit committee selects the matters it wishes the auditor to report",
      "From the matters communicated to those charged with governance, the auditor identifies those requiring significant auditor attention, and from those selects the matters of MOST significance in the current audit",
      "All areas where misstatements were found during the audit are reported as KAM",
    ],
    correct: 2,
    explanation:
      "ISA 701 works as a funnel: start with matters COMMUNICATED TO TCWG → narrow to those requiring SIGNIFICANT AUDITOR ATTENTION (higher assessed risks and significant risks, significant judgements such as estimates, significant events or transactions) → select the matters of MOST significance. Significant risks are a strong input but the final step is judgement, not automation (option 1). The AUDITOR decides KAM, not the audit committee (option 2). And KAM reflects where audit effort was concentrated, not a list of errors found (option 4).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA4-E-13",
    paper: "AA",
    area: "E",
    type: "mcq",
    stem: "The auditor's report on the financial statements of Cotterstock plc is normally ADDRESSED to:",
    options: [
      "The shareholders (members) of the company",
      "The board of directors",
      "The audit committee",
      "The financial reporting regulator",
    ],
    correct: 0,
    explanation:
      "The audit exists to report to the OWNERS on the stewardship of those they appointed to run the company, so the report is addressed to the shareholders (members) as a body — as required by the engagement's terms and, typically, by law. The directors are the ones being reported ON, not to. The audit committee receives separate communications under ISA 260/265, and regulators may receive the report but are not its addressee. Confusing the report's addressee with its many readers is a simple mark lost.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AA4-E-14",
    paper: "AA",
    area: "E",
    type: "mcq",
    stem: "Ingleshaw Ltd's draft financial statements show a profit of $15,000; materiality is $600,000. The auditor finds a single $40,000 cut-off error which, if corrected, would turn the profit into a loss and breach the company's loan covenant. The directors refuse to adjust. The auditor should:",
    options: [
      "Take no action — $40,000 is far below the $600,000 materiality level",
      "Modify the opinion only if the misstatement exceeds the quantitative materiality threshold",
      "Treat the misstatement as material by NATURE, because it changes a profit into a loss and affects covenant compliance, and modify the opinion if it remains uncorrected",
      "Add an Emphasis of Matter paragraph highlighting the misstatement",
    ],
    correct: 2,
    explanation:
      "Materiality has a QUALITATIVE dimension: ISA 450 requires uncorrected misstatements to be judged by nature and circumstances as well as size. An error that flips a profit into a loss, or tips a loan covenant into breach, changes the decisions users make — so it is material despite being tiny against the quantitative threshold. Options 1 and 2 apply the number blindly, the exact error this question tests. An EoM can never be used to flag a misstatement — if the statements are wrong and uncorrected, the OPINION must carry the message.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AA4-E-15",
    paper: "AA",
    area: "E",
    type: "mcq",
    stem: "Which statement about the DATE of the auditor's report on Danecroft Ltd's financial statements is TRUE?",
    options: [
      "It is the date on which audit fieldwork commenced",
      "It is the date the auditor obtained sufficient appropriate evidence, and can be no earlier than the date those with authority approved the financial statements; active subsequent events procedures run up to this date",
      "It is the date the financial statements are issued to the shareholders",
      "It is whatever date management selects to meet the statutory filing deadline",
    ],
    correct: 1,
    explanation:
      "The report date marks the point at which the auditor had SUFFICIENT APPROPRIATE EVIDENCE — including evidence that the complete financial statements had been prepared and that those with recognised authority had taken responsibility for them (so it cannot precede approval). It also draws the ISA 560 line: active subsequent events procedures run TO this date; afterwards only a passive duty remains. Fieldwork start and issue dates are different milestones, and the date is a matter of audit fact — management has no say in it.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AA4-E-16",
    paper: "AA",
    area: "E",
    type: "mcq",
    stem: "The auditor of Kirdale Systems plc, a listed company, concludes that a DISCLAIMER of opinion is required. Which statement about the resulting auditor's report is TRUE?",
    options: [
      "The opinion section states that the financial statements are not fairly presented",
      "The disclaimer is confined to the affected balances and a normal opinion is given on the remainder",
      "No auditor's report is issued at all",
      "The report states that the auditor does not express an opinion on the financial statements, and no Key Audit Matters section is presented",
    ],
    correct: 3,
    explanation:
      "A disclaimer says the auditor CANNOT form an opinion — the report is still issued, but the opinion section states that, because of the significance of the matter in the basis section, the auditor does not express an opinion. ISA 705 also prohibits a KAM section when disclaiming (unless law requires it): describing 'key matters' of an audit that could not support any opinion would be contradictory. Option 1 describes an ADVERSE opinion — the other pervasive outcome, on the misstatement branch. Option 2 is a prohibited piecemeal opinion, and option 3 confuses disclaiming with not reporting.",
    marks: 2,
    difficulty: "medium",
  },
]
