import type { AccaQuestion } from "@/lib/acca-content"

/* FM bank wave 8b part 1 — 38 verified originals (2026-07-13).
 * Blueprint: A7 B16 C15; difficulty 10/17/11; 26 mcq / 12 number; every
 * distractor is a nameable student error. All computations re-solved from
 * the stem, digit by digit, before inclusion.
 */

export const FM_WAVE3A: AccaQuestion[] = [
  /* ───────────── Area A — Financial management function (7) ───────────── */
  {
    id: "FM3-A-01",
    paper: "FM",
    area: "A",
    type: "mcq",
    stem: "Kelbrook Co decides to fund a major new capital project entirely from retained earnings, cutting the dividend it would otherwise have paid. This illustrates the interdependence of which of the three key financial management decisions?",
    options: [
      "The investment and dividend decisions only",
      "The investment and financing decisions only",
      "All three: the investment, financing and dividend decisions",
      "The financing and dividend decisions only",
    ],
    correct: 2,
    explanation:
      "Choosing the project is the INVESTMENT decision; choosing retained earnings as the source of funds is the FINANCING decision (retentions are a source of equity finance); and cutting the payout is the DIVIDEND decision. Cash retained for investment cannot also be distributed, so all three decisions interact. Each wrong option drops one leg of the triangle — the commonest slip is forgetting that using retained earnings IS a financing choice.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM3-A-02",
    paper: "FM",
    area: "A",
    type: "mcq",
    stem: "The Bramfield Trust is a charity whose objective is to improve adult literacy. Under a value-for-money ('three Es') assessment, which performance measure assesses its EFFECTIVENESS?",
    options: [
      "The proportion of enrolled learners who reach the target reading standard within a year",
      "The cost per tutoring hour compared with the budgeted cost",
      "The number of tutoring hours delivered per paid tutor",
      "Keeping total spending within the year's donation income",
    ],
    correct: 0,
    explanation:
      "Effectiveness measures how far the organisation achieves its OBJECTIVES — here, learners actually becoming literate. Cost per tutoring hour tests ECONOMY (buying inputs cheaply), hours delivered per tutor tests EFFICIENCY (output per unit of input), and spending within income is financial control, which is none of the three Es. Swapping the three Es is the standard error.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM3-A-03",
    paper: "FM",
    area: "A",
    type: "mcq",
    stem: "Which of the following is an example of an AGENCY COST borne by the shareholders of a listed company?",
    options: [
      "Interest paid on the company's loan notes",
      "Fees paid to external auditors to monitor the directors' stewardship of the company",
      "The ordinary dividend paid to shareholders each year",
      "Import duties paid on raw materials",
    ],
    correct: 1,
    explanation:
      "Agency costs are the costs of the separation of ownership and control — chiefly MONITORING costs (audits, analysts, corporate governance compliance) incurred so that shareholders can check up on their agents, the directors. Loan interest is simply the cost of debt finance, a dividend is a return TO the owners (students confuse it with the 'cost of equity'), and import duties are an ordinary operating cost with no agency dimension.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM3-A-04",
    paper: "FM",
    area: "A",
    type: "mcq",
    stem: "The central bank raises interest rates sharply to curb inflation. Marleth Co is highly geared with floating-rate borrowings and earns most of its revenue from exports. Which combination of effects is Marleth Co MOST likely to experience?",
    options: [
      "Lower interest costs and stronger export demand",
      "Higher interest costs, offset by a weaker domestic currency that boosts export competitiveness",
      "Lower interest costs, but a stronger domestic currency that reduces export competitiveness",
      "Higher interest costs and a stronger domestic currency that reduces export competitiveness",
    ],
    correct: 3,
    explanation:
      "Floating-rate debt reprices immediately, so interest costs RISE. Higher domestic rates also attract international capital inflows, which APPRECIATE the currency and make exports dearer to foreign buyers — a double blow. Option B contains the classic error of assuming rate rises WEAKEN the currency (they normally strengthen it), and options A and C get the direction of the interest cost wrong for a floating-rate borrower.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM3-A-05",
    paper: "FM",
    area: "A",
    type: "mcq",
    stem: "Which of the following is the best example of financial DISintermediation?",
    options: [
      "A large company issues commercial paper directly to institutional investors instead of drawing on its bank overdraft",
      "A saver deposits cash with a bank, which lends it to a house buyer",
      "A bank pools many small deposits to make one large loan to a company",
      "A company factors its trade receivables to raise cash",
    ],
    correct: 0,
    explanation:
      "Disintermediation is borrowers and lenders dealing DIRECTLY, cutting out the financial intermediary — issuing commercial paper straight to investors replaces bank borrowing. A deposit funding a mortgage is intermediation itself, pooling small deposits is the intermediary function of aggregation, and factoring simply substitutes one intermediary (the factor) for another. The trap is labelling any 'new' financing method as disintermediation regardless of whether an intermediary remains.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM3-A-06",
    paper: "FM",
    area: "A",
    type: "mcq",
    stem: "Under the internal / connected / external classification of stakeholders, which pair are both CONNECTED stakeholders of Tarnwell Co?",
    options: [
      "Executive directors and factory employees",
      "The tax authority and the local community",
      "Shareholders and trade suppliers",
      "The environmental regulator and company managers",
    ],
    correct: 2,
    explanation:
      "Connected stakeholders have a contractual or financial link with the company without being part of it: shareholders, lenders, customers and suppliers. Directors and employees are INTERNAL stakeholders, while the tax authority, regulators and the community are EXTERNAL. Option D mixes an external stakeholder with an internal one — and the frequent error is filing shareholders as 'internal' because they own the company; ownership is a connection, not membership of management.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM3-A-07",
    paper: "FM",
    area: "A",
    type: "mcq",
    stem: "A government finances a large and persistent budget deficit by issuing substantial quantities of government bonds to the domestic capital market. Which effect on private-sector companies is MOST likely?",
    options: [
      "Their cost of borrowing falls, because more bonds are available for investors to buy",
      "Their cost of borrowing rises, as government demand for funds pushes up interest rates and 'crowds out' private investment",
      "Their corporation tax bills fall immediately, because borrowing replaces the need for taxation",
      "Their share prices rise, because government spending guarantees higher sales for all companies",
    ],
    correct: 1,
    explanation:
      "Heavy government borrowing competes with companies for the economy's limited pool of savings, bidding up interest rates; marginal private projects no longer cover their cost of capital and are 'crowded out'. Option A confuses the SUPPLY of bonds with the supply of funds — more bond issues absorb funds and push yields UP, not down. Deficit finance defers rather than removes taxation (option C), and any demand stimulus is neither guaranteed nor universal (option D).",
    marks: 2,
    difficulty: "hard",
  },

  /* ───────────── Area B — Investment appraisal (16) ───────────── */
  {
    id: "FM3-B-01",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "In investment appraisal, RISK differs from UNCERTAINTY in that risk:",
    options: [
      "Only exists for projects with lives longer than five years",
      "Refers only to the possibility of outcomes being worse than expected",
      "Cannot be quantified, whereas uncertainty can be",
      "Describes situations where the possible outcomes and their probabilities are known, so it can be quantified",
    ],
    correct: 3,
    explanation:
      "Risk exists where possible outcomes AND their probabilities can be estimated (e.g. from past experience), so techniques such as expected values apply; uncertainty is where probabilities cannot be assigned. Option C states the distinction exactly backwards — the most common error. Risk is two-sided (outcomes better OR worse than expected), so option B is wrong, and project life affects the DEGREE of uncertainty, not the definition (option A).",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM3-B-02",
    paper: "FM",
    area: "B",
    type: "number",
    stem: "Drayfield Co bought a machine for $80,000. Tax-allowable depreciation is available at 25% per year on a reducing-balance basis. No allowance is claimed in the year of disposal; a balancing adjustment is made instead. The machine will be sold at the end of year 3 for $30,000. What is the balancing ALLOWANCE arising on disposal, in $?",
    numericAnswer: 15000,
    unit: "$",
    tolerance: 1,
    explanation:
      "Year 1 allowance = 25% × 80,000 = 20,000 (written-down value 60,000); year 2 allowance = 25% × 60,000 = 15,000 (WDV 45,000). In the year of disposal no WDA is claimed, so the balancing allowance = WDV − sale proceeds = 45,000 − 30,000 = $15,000. Two classic slips: claiming a year 3 WDA first (WDV 33,750, giving a wrong balancing allowance of 3,750), and comparing proceeds with the ORIGINAL cost (80,000 − 30,000 = 50,000).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM3-B-03",
    paper: "FM",
    area: "B",
    type: "number",
    stem: "Vintori Co's real cost of capital is 6.0% per year and general inflation is expected to be 4.0% per year. Using the Fisher relationship, what is the nominal (money) cost of capital? Give your answer as a percentage to one decimal place.",
    numericAnswer: 10.2,
    unit: "%",
    tolerance: 0.1,
    explanation:
      "Fisher: (1 + money rate) = (1 + real rate) × (1 + inflation) = 1.06 × 1.04 = 1.1024, so the money rate = 10.24% ≈ 10.2%. Simply ADDING the two rates gives 10.0% — the standard error — because it ignores the cross-term (inflation compounding on the real return). Money cash flows must be discounted at this 10.2% money rate.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM3-B-04",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "A divisional manager of Quillan Co, whose annual bonus depends on divisional ROCE, rejects a project with a positive NPV because it would reduce the division's ROCE in its first two years. Which statement best describes this situation?",
    options: [
      "A dysfunctional decision: NPV measures the change in shareholder wealth, so the project should be accepted despite the short-term ROCE effect",
      "A correct decision, because ROCE is a percentage and therefore allows fairer comparison between projects than NPV",
      "A correct decision, because accounting profits are more reliable than estimated future cash flows",
      "A dysfunctional decision, because ROCE should have been calculated on initial rather than average investment",
    ],
    correct: 0,
    explanation:
      "A positive NPV adds to shareholder wealth, so rejection driven by a bonus metric is a dysfunctional (agency) outcome of performance measurement. Option B repeats the flawed 'percentages compare better' argument — relative measures ignore scale and wealth created; option C is backwards, since ROCE rests on subjective accounting profit and ignores the time value of money; option D raises a computational detail that would not remove the underlying conflict.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM3-B-05",
    paper: "FM",
    area: "B",
    type: "number",
    stem: "A project of Nemetra Co costs $90,000 at time 0 and generates net cash inflows of $40,000 per year for four years. The cost of capital is 10% (discount factors: year 1 = 0.909, year 2 = 0.826, year 3 = 0.751, year 4 = 0.683). Assuming cash flows accrue evenly during each year, what is the DISCOUNTED payback period, in years, to one decimal place?",
    numericAnswer: 2.7,
    unit: "years",
    tolerance: 0.05,
    explanation:
      "Discounted inflows: year 1 = 40,000 × 0.909 = 36,360; year 2 = 33,040 (cumulative 69,400); year 3 = 30,040. After two years $20,600 of the $90,000 remains, so discounted payback = 2 + 20,600 ÷ 30,040 = 2.69 ≈ 2.7 years. The trap is quoting the SIMPLE payback of 90,000 ÷ 40,000 = 2.25 years — discounting always lengthens payback.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM3-B-06",
    paper: "FM",
    area: "B",
    type: "number",
    stem: "Solvexa Co is appraising a project costing $60,000 with net pre-tax operating cash inflows of $30,000 per year for three years and no scrap value. Tax-allowable depreciation is available on a straight-line basis over the three years. Tax is 25%, payable in the same year as the profits to which it relates. The after-tax cost of capital is 10% (3-year annuity factor = 2.487). What is the project's NPV, to the nearest $?",
    numericAnswer: 8393,
    unit: "$",
    tolerance: 10,
    explanation:
      "Annual tax-allowable depreciation = 60,000 ÷ 3 = 20,000, so taxable profit = 30,000 − 20,000 = 10,000 and tax = 2,500 per year. After-tax cash flow = 30,000 − 2,500 = 27,500 per year (depreciation itself is not a cash flow). PV = 27,500 × 2.487 = 68,392.5, so NPV = 68,392.5 − 60,000 ≈ +$8,393. Common errors: taxing the full $30,000 (tax 7,500, NPV −$4,043) because the depreciation shield was forgotten, or deducting depreciation from the CASH flow as well as from taxable profit.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM3-B-07",
    paper: "FM",
    area: "B",
    type: "number",
    stem: "A project has an NPV of +$6,600 at a discount rate of 8% and an NPV of −$2,400 at 14%. Using linear interpolation, estimate the project's IRR. Give your answer as a percentage to one decimal place.",
    numericAnswer: 12.4,
    unit: "%",
    tolerance: 0.1,
    explanation:
      "IRR ≈ 8% + [6,600 ÷ (6,600 + 2,400)] × (14% − 8%) = 8% + 0.7333 × 6% = 8% + 4.4% = 12.4%. The denominator is the TOTAL swing in NPV (6,600 + 2,400 = 9,000): netting the NPVs instead (6,600 − 2,400 = 4,200) or simply taking the midpoint of the two rates (11.0%) are the two classic interpolation errors.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM3-B-08",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "A project of Harkwood Co has three possible outcomes: an NPV of −$20,000 with probability 0.3; an NPV of +$30,000 with probability 0.5; and an NPV of +$70,000 with probability 0.2. What is the expected NPV?",
    options: ["$30,000", "$26,667", "$23,000", "$29,000"],
    correct: 2,
    explanation:
      "Expected NPV = (−20,000 × 0.3) + (30,000 × 0.5) + (70,000 × 0.2) = −6,000 + 15,000 + 14,000 = $23,000. $30,000 is merely the single MOST LIKELY outcome, not the probability-weighted average; $26,667 is the unweighted mean of the three outcomes, ignoring the probabilities; $29,000 leaves the loss outcome out of the sum altogether — negative outcomes must be included with their sign.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM3-B-09",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "Brindale Co has $150,000 of capital available at time 0 and four INDIVISIBLE projects, none of which can be delayed or repeated: P costs $60,000 (NPV $24,000); Q costs $100,000 (NPV $35,000); R costs $50,000 (NPV $16,000); S costs $40,000 (NPV $12,000). What is the maximum total NPV achievable?",
    options: [
      "$51,000, by taking Q and R",
      "$52,000, by taking P, R and S",
      "$59,000, by taking P and Q",
      "$55,500, by taking P and 90% of Q",
    ],
    correct: 1,
    explanation:
      "With indivisible projects, test feasible combinations of the $150,000: P + R + S costs exactly 150,000 and yields 24,000 + 16,000 + 12,000 = $52,000 — the maximum. Q + R (also $150,000) yields only $51,000: starting greedily with Q, the highest ABSOLUTE NPV, is the classic error. P + Q costs $160,000 and breaches the limit, and taking 90% of Q wrongly treats an indivisible project as divisible — fractional investment is only valid when the question says projects are divisible.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM3-B-10",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "Feltonic Co needs a machine for three years. Buying costs $90,000 now, with resale proceeds of $10,000 at the end of year 3. Leasing costs $30,000 per year, payable at the end of each of years 1 to 3. Ignoring tax, and discounting at the 7% after-tax cost of borrowing (year 3 discount factor = 0.816; 3-year annuity factor = 2.624), which option should be chosen?",
    options: [
      "Lease, because its PV of cost is $78,720 against $81,840 for buying",
      "Buy, because its PV of cost is $81,840 against $90,000 for leasing",
      "Lease, because it saves $11,280 in present value terms",
      "Buy, because after three years the machine can be sold, whereas lease payments buy nothing",
    ],
    correct: 0,
    explanation:
      "Buy: PV = 90,000 − 10,000 × 0.816 = 90,000 − 8,160 = $81,840. Lease: PV = 30,000 × 2.624 = $78,720. Leasing is cheaper by $3,120. Option B compares the discounted buy cost with the UNDISCOUNTED lease total of $90,000; option C forgets the resale proceeds (90,000 − 78,720 = 11,280); option D relies on ownership intuition instead of the PV comparison — the resale value is already captured in the $81,840.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM3-B-11",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "A project of Lumeric Co has an NPV of $12,000. The PV of sales revenue is $200,000, the PV of variable costs is $104,000 and the initial investment is $48,000. To what percentage fall in sales VOLUME (with selling prices unchanged) is the investment decision just sensitive?",
    options: ["6.0%", "11.5%", "25.0%", "12.5%"],
    correct: 3,
    explanation:
      "A fall in volume loses sales AND saves variable costs, so it erodes CONTRIBUTION: PV of contribution = 200,000 − 104,000 = 96,000, and sensitivity = 12,000 ÷ 96,000 = 12.5%. 6.0% divides by the PV of sales (200,000) — that is the sensitivity to selling PRICE, where costs do not change; 11.5% divides by variable costs alone; 25.0% divides by the initial investment, which measures sensitivity to the capital cost, not volume.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM3-B-12",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "Why is the equivalent annual cost (EAC) method used when choosing between replacing a machine every two years and replacing it every three years?",
    options: [
      "Because it avoids the need to discount the cash flows",
      "Because it automatically incorporates inflation into the comparison",
      "Because comparing the PV of cost of a single cycle of each option is invalid when the cycles have different lengths; EAC converts each PV into a comparable cost per year",
      "Because the option with the lower total undiscounted cost should always be chosen",
    ],
    correct: 2,
    explanation:
      "A two-year cycle's PV covers two years of service and a three-year cycle's covers three, so the raw PVs are not comparable — the shorter cycle always looks cheaper. Dividing each PV by its own annuity factor gives the EAC, a like-for-like annual cost. EAC still requires discounting (option A), does nothing special about inflation (option B), and undiscounted totals ignore the time value of money entirely (option D).",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM3-B-13",
    paper: "FM",
    area: "B",
    type: "number",
    stem: "Cazelle Co operates a machine costing $45,000. If kept for two years it incurs running costs of $8,000 in year 1 and $12,000 in year 2, and is sold for $16,000 at the end of year 2. The cost of capital is 10% (discount factors: year 1 = 0.909, year 2 = 0.826; 2-year annuity factor = 1.736). What is the equivalent annual cost of the two-year replacement cycle, to the nearest $?",
    numericAnswer: 28207,
    unit: "$",
    tolerance: 15,
    explanation:
      "PV of one cycle's costs = 45,000 + 8,000 × 0.909 + (12,000 − 16,000) × 0.826 = 45,000 + 7,272 − 3,304 = $48,968 (the year 2 resale proceeds are netted against year 2 running costs). EAC = 48,968 ÷ 1.736 = $28,207. The classic slips are forgetting to DEDUCT the resale value (PV 62,184, EAC 35,820) and dividing the PV by the 2-year life instead of the annuity factor (24,484), which ignores the time value of money.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM3-B-14",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "A project's operating cash flows arise at each year end. Tax at 25% is payable ONE YEAR IN ARREARS, and tax-allowable depreciation is claimed against the profits of the year to which it relates. In an NPV evaluation, in which year should the cash-flow benefit of the YEAR 1 tax-allowable depreciation appear?",
    options: [
      "Year 1",
      "Year 2",
      "Time 0, because the asset is bought at time 0",
      "Spread evenly over the life of the project",
    ],
    correct: 1,
    explanation:
      "The year 1 allowance reduces year 1 taxable profits, but that tax is not PAID until year 2 (one year in arrears), so the cash saving lands in year 2. Placing it in year 1 forgets the lag — the most common timing error; time 0 confuses when the asset is bought with when tax relief flows; and allowances follow the tax computation year by year, they are not smoothed over the life of the project.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM3-B-15",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "A project's cash flows are estimated in CURRENT price terms. Selling prices will inflate at 7% per year and costs at 3% per year; general inflation is 4% and the money (nominal) cost of capital is 12.32%. Which evaluation approach is technically correct?",
    options: [
      "Inflate each cash flow at its own specific rate and discount at 12.32%",
      "Discount the current-price cash flows, uninflated, at the real rate of 8%",
      "Inflate all cash flows at the general rate of 4% and discount at 12.32%",
      "Inflate each cash flow at its own specific rate and discount at the real rate of 8%",
    ],
    correct: 0,
    explanation:
      "With DIFFERENT specific inflation rates, the only valid method is the money approach: inflate sales at 7% and costs at 3%, then discount the money flows at the money rate of 12.32%. The real-rate shortcut (option B, using 1.1232 ÷ 1.04 − 1 = 8%) is valid ONLY when every flow inflates at the general 4% rate — here it would misstate the changing real value of the margin. Option C inflates at the wrong (general) rate, and option D mixes money flows with a real rate, systematically overstating NPV.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM3-B-16",
    paper: "FM",
    area: "B",
    type: "mcq",
    stem: "Pindrove Co must choose ONE of two mutually exclusive, one-off projects. Project L has a certain NPV of $40,000. Project M has an NPV of +$100,000 with probability 0.5 and −$20,000 with probability 0.5. The directors are risk-averse. What is the best advice?",
    options: [
      "Take M, because expected NPV is the sole decision criterion and M's expected NPV is $40,000",
      "Take M, because its expected NPV of $50,000 exceeds L's $40,000",
      "Take L, because a certain outcome is always worth more than any risky project",
      "Take L: both projects have an expected NPV of $40,000, and for a one-off decision a risk-averse board prefers the outcome with no dispersion",
    ],
    correct: 3,
    explanation:
      "EV of M = (0.5 × 100,000) + (0.5 × −20,000) = $40,000, identical to L — so risk breaks the tie, and risk-averse directors take the certain $40,000. Expected values are averages that only materialise over MANY repetitions; in a one-off decision M actually delivers either +100,000 or −20,000, never 40,000, so EV cannot be the sole criterion (option A). Option B computes M's EV ignoring the loss outcome (0.5 × 100,000 = 50,000). Option C overreaches: certainty is not ALWAYS preferable — a risky project with a sufficiently higher EV could be, which is exactly why the equal-EV comparison matters here.",
    marks: 2,
    difficulty: "hard",
  },

  /* ───────────── Area C — Working capital management (15) ───────────── */
  {
    id: "FM3-C-01",
    paper: "FM",
    area: "C",
    type: "number",
    stem: "Werrick Co has annual credit sales of $2,190,000 and cost of sales of $1,460,000, all on credit. Year-end balances are: inventory $180,000, trade receivables $270,000 and trade payables $120,000. Using a 365-day year and year-end balances, what is the cash operating cycle, in days?",
    numericAnswer: 60,
    unit: "days",
    tolerance: 0.5,
    explanation:
      "Inventory days = 180,000 ÷ 1,460,000 × 365 = 45; receivables days = 270,000 ÷ 2,190,000 × 365 = 45; payables days = 120,000 ÷ 1,460,000 × 365 = 30. Cycle = 45 + 45 − 30 = 60 days. Two traps: ADDING payables days (giving 120) instead of subtracting, and computing receivables days on cost of sales rather than sales (inventory and payables use cost of sales; receivables use credit sales).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM3-C-02",
    paper: "FM",
    area: "C",
    type: "mcq",
    stem: "Which of the following describes a CONSERVATIVE working capital financing policy?",
    options: [
      "Short-term finance funds part of the permanent current assets",
      "The maturity of the finance is matched exactly to the life of each asset",
      "Long-term finance funds all permanent assets and most or all of the fluctuating current assets",
      "Current assets are kept at the minimum level possible",
    ],
    correct: 2,
    explanation:
      "A conservative FINANCING policy uses stable long-term funds not just for permanent assets but also for much of the fluctuating layer, minimising refinancing risk at the cost of paying long-term rates on sometimes-idle funds. Option A is the AGGRESSIVE policy, option B is the matching approach, and option D describes an aggressive INVESTMENT policy (the level of current assets held), not a financing policy — the two dimensions are routinely confused.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM3-C-03",
    paper: "FM",
    area: "C",
    type: "number",
    stem: "Torvale Co has annual credit sales of $4,380,000 and customers currently pay in 60 days. It proposes a 1.5% discount for payment within 20 days; 40% of customers (by sales value) are expected to take the discount, with the rest still paying at 60 days. Receivables are financed by an overdraft costing 9% per year. Using a 365-day year, what is the NET annual COST of offering the discount, in $?",
    numericAnswer: 9000,
    unit: "$",
    tolerance: 10,
    explanation:
      "Current receivables = 4,380,000 × 60/365 = $720,000. New: discount takers 40% × 4,380,000 = 1,752,000 × 20/365 = $96,000; non-takers 2,628,000 × 60/365 = $432,000; total $528,000. Receivables fall by $192,000, saving 192,000 × 9% = $17,280 of interest. Discount cost = 1.5% × 1,752,000 = $26,280 (only the TAKERS receive it — applying 1.5% to all sales gives 65,700 and is the classic error). Net cost = 26,280 − 17,280 = $9,000; another frequent slip is computing the interest saving on the whole old balance of 720,000 rather than the reduction.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM3-C-04",
    paper: "FM",
    area: "C",
    type: "mcq",
    stem: "What is the key difference between NON-RECOURSE and WITH-RECOURSE factoring?",
    options: [
      "Non-recourse factoring involves no advance of funds against receivables",
      "Under non-recourse factoring the factor bears the loss on irrecoverable debts, so its fee is higher",
      "Under with-recourse factoring the factor runs the sales ledger, but under non-recourse factoring it does not",
      "Non-recourse factoring must be disclosed to customers, whereas with-recourse factoring is always confidential",
    ],
    correct: 1,
    explanation:
      "Recourse defines who bears bad-debt risk: NON-recourse transfers it to the factor (effectively insurance, priced into a higher fee); with recourse, unpaid debts are passed back to the company. Advances of cash (option A) and sales-ledger administration (option C) are available under BOTH variants. Confidentiality (option D) distinguishes invoice DISCOUNTING from factoring, not recourse terms — a frequent mix-up.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM3-C-05",
    paper: "FM",
    area: "C",
    type: "number",
    stem: "Denholt Co uses 62,500 units of a component per year. Each order costs $32 to place and holding one unit for a year costs $4. Using the EOQ model (EOQ = √(2 × Co × D ÷ Ch)) and ignoring safety stock, what is the TOTAL annual cost of ordering plus holding inventory, in $?",
    numericAnswer: 4000,
    unit: "$",
    tolerance: 1,
    explanation:
      "EOQ = √(2 × 32 × 62,500 ÷ 4) = √1,000,000 = 1,000 units. Ordering cost = (62,500 ÷ 1,000) × 32 = 62.5 × 32 = $2,000; holding cost = (1,000 ÷ 2) × 4 = $2,000; total = $4,000. At the EOQ the two costs are always EQUAL — a built-in check. The usual errors are holding cost on the FULL order quantity rather than the average (giving 4,000 + 2,000 = 6,000) and reporting only one of the two components ($2,000).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM3-C-06",
    paper: "FM",
    area: "C",
    type: "mcq",
    stem: "Osmaline Co uses 36,000 units per year, bought at $8.00 per unit. Ordering costs are $50 per order and holding costs $1.60 per unit per year, giving an EOQ of 1,500 units. A supplier offers a 2% price discount on orders of at least 3,000 units, with the holding cost per unit unchanged. What is the net annual effect of ordering 3,000 units instead of the EOQ?",
    options: [
      "A net saving of $5,160, so the discount should be taken",
      "A net saving of $5,760, so the discount should be taken",
      "A net saving of $4,560, so the discount should be taken",
      "A net cost of $600, so the discount should be rejected",
    ],
    correct: 0,
    explanation:
      "At the EOQ of 1,500: ordering = 24 × 50 = 1,200; holding = 750 × 1.60 = 1,200 (total 2,400). At 3,000: ordering = 12 × 50 = 600 (saves 600); holding = 1,500 × 1.60 = 2,400 (costs 1,200 more); discount = 2% × 36,000 × 8.00 = 5,760. Net = 5,760 + 600 − 1,200 = $5,160 saving. $5,760 counts the discount but ignores the inventory-cost changes; $4,560 deducts the extra holding cost but forgets the ordering-cost saving; a $600 net cost compares only the inventory costs and omits the discount itself.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM3-C-07",
    paper: "FM",
    area: "C",
    type: "number",
    stem: "Grelling Co manages cash using the Miller-Orr model. The transaction cost of each sale or purchase of securities is $25, the variance of daily cash flows is $1,024,000 and the daily interest rate is 0.03%. Using Spread = 3 × [¾ × transaction cost × variance ÷ daily interest rate]^(1/3), what is the spread between the lower and upper limits, to the nearest $?",
    numericAnswer: 12000,
    unit: "$",
    tolerance: 50,
    explanation:
      "¾ × 25 × 1,024,000 = 19,200,000. Divide by the daily rate as a DECIMAL: 19,200,000 ÷ 0.0003 = 64,000,000,000. Cube root = 4,000 (4,000³ = 64 × 10⁹). Spread = 3 × 4,000 = $12,000. The two classic slips: using 0.03 instead of 0.0003 for the interest rate (which shrinks the answer by a factor of 100^(1/3) ≈ 4.64), and forgetting the final multiplication by 3, which leaves $4,000.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM3-C-08",
    paper: "FM",
    area: "C",
    type: "mcq",
    stem: "Which assumption of the Baumol cash management model MOST limits its practical usefulness?",
    options: [
      "It assumes cash can never be invested in interest-bearing securities",
      "It assumes the transaction cost of selling securities is zero",
      "It assumes cash inflows are perfectly unpredictable",
      "It assumes cash is used up at a constant, perfectly predictable rate over the period",
    ],
    correct: 3,
    explanation:
      "Baumol transplants the EOQ's steady-demand assumption to cash: outflows occur at a constant, known rate, which real cash flows rarely follow — Miller-Orr was developed precisely to handle irregular flows. Option A is backwards (the model EXISTS because idle cash could otherwise earn interest), option B is wrong because the transaction cost is a key input, and option C describes Miller-Orr's premise, not Baumol's.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM3-C-09",
    paper: "FM",
    area: "C",
    type: "mcq",
    stem: "Halvern Co is profitable but severely overtrading: sales have doubled within a year, and inventory, receivables and the overdraft have all risen sharply. Which action would MOST directly address the problem?",
    options: [
      "Negotiate a higher overdraft limit to fund continued rapid growth",
      "Offer customers even longer credit terms to accelerate sales growth further",
      "Raise long-term finance, such as a share issue, to fund the higher permanent working capital, and slow the rate of growth",
      "Pay suppliers more quickly to protect supply lines",
    ],
    correct: 2,
    explanation:
      "Overtrading is growth outrunning the long-term capital base, so the remedies are to inject long-term funds and/or restrain growth. Extending the overdraft merely deepens the reliance on short-term finance that defines the problem; longer customer credit inflates receivables and makes the cycle worse; and paying suppliers faster consumes scarce cash — payables are one of the few things propping up liquidity.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM3-C-10",
    paper: "FM",
    area: "C",
    type: "mcq",
    stem: "Compared with its industry peers, Kirlowe Co holds much lower inventories and grants much shorter customer credit for the same level of sales. Which working capital policy is this, and what is its main risk?",
    options: [
      "An aggressive INVESTMENT policy; it raises profitability but risks stockouts and lost sales from customers denied credit",
      "A conservative investment policy; it reduces the risk of obsolete inventory",
      "An aggressive FINANCING policy; short-term borrowings may not be renewed",
      "A matching policy; asset lives are aligned with the maturity of the finance",
    ],
    correct: 0,
    explanation:
      "The LEVEL of current assets held is the investment dimension: running lean inventory and tight credit is aggressive investment — less capital tied up boosts returns, but stockouts and refused credit can drive customers away. Option B reverses the label (conservative means HIGH buffers). Options C and D confuse the investment policy with the FINANCING policy — how current assets are funded is a separate decision not described in the scenario.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM3-C-11",
    paper: "FM",
    area: "C",
    type: "number",
    stem: "Yarrowdale Co makes credit purchases of $1,825,000 per year and pays its suppliers after 48 days on average. Using a 365-day year, what is its average trade payables balance, in $?",
    numericAnswer: 240000,
    unit: "$",
    tolerance: 10,
    explanation:
      "Payables = credit purchases × days ÷ 365 = 1,825,000 × 48 ÷ 365 = 5,000 per day × 48 = $240,000. This simply rearranges the payables-days ratio; the common slip is dividing by 48 and multiplying by 365 (upside down), which gives an impossible balance far larger than annual purchases.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM3-C-12",
    paper: "FM",
    area: "C",
    type: "mcq",
    stem: "Morvath Co has credit sales of $2,920,000 per year and receivables days of 50, financed by a 9% overdraft. A factor offers a NON-RECOURSE service: fee 1.5% of sales; receivables days fall to 40; the factor advances 80% of receivables at 11% interest, with the remainder overdraft-financed; administration savings of $18,000 per year; and bad debts of 0.5% of sales, currently written off by Morvath, are eliminated. Using a 365-day year, what is the net annual result?",
    options: [
      "A net cost of $23,720",
      "A net cost of $9,120",
      "A net cost of $11,200",
      "A net cost of $3,360",
    ],
    correct: 1,
    explanation:
      "Receivables: now 2,920,000 × 50/365 = 400,000; with the factor 2,920,000 × 40/365 = 320,000. New financing cost = (80% × 320,000) × 11% + (20% × 320,000) × 9% = 28,160 + 5,760 = 33,920, against 400,000 × 9% = 36,000 now — an interest saving of 2,080. Fee = 1.5% × 2,920,000 = 43,800; savings = 18,000 admin + 14,600 bad debts + 2,080 interest = 34,680. Net cost = 43,800 − 34,680 = $9,120. $23,720 omits the bad-debt saving (pricing it as a WITH-recourse deal); $11,200 ignores the interest workings entirely; $3,360 computes the interest saving as 36,000 − 28,160, forgetting the overdraft cost of the unadvanced 20%.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM3-C-13",
    paper: "FM",
    area: "C",
    type: "number",
    stem: "Opaline Co has annual credit sales of $1,460,000, a contribution-to-sales ratio of 25% and receivables days of 30. Relaxing credit terms to 60 days is expected to raise sales by 10%, with ALL customers then paying at 60 days. Receivables are financed by a 10% overdraft and are valued at sales value. Using a 365-day year, what is the NET annual benefit of the change, in $?",
    numericAnswer: 22100,
    unit: "$",
    tolerance: 10,
    explanation:
      "Current receivables = 1,460,000 × 30/365 = $120,000. New sales = 1,460,000 × 1.10 = 1,606,000, so new receivables = 1,606,000 × 60/365 = $264,000 — an increase of $144,000, costing 144,000 × 10% = $14,400 in interest. Extra contribution = 146,000 × 25% = $36,500. Net benefit = 36,500 − 14,400 = $22,100. Watch two slips: computing new receivables on the OLD sales figure (240,000, understating the financing cost), and crediting the full $146,000 of extra SALES rather than the 25% contribution they generate.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM3-C-14",
    paper: "FM",
    area: "C",
    type: "mcq",
    stem: "Compared with financing working capital using long-term debt, financing it with a bank overdraft is generally:",
    options: [
      "More expensive but lower-risk, because the bank cannot withdraw the facility",
      "Cheaper and lower-risk, which is why companies should maximise overdraft use",
      "More expensive and higher-risk, so overdrafts should never be used",
      "Cheaper, because interest is paid only on the amount outstanding and short-term rates are typically below long-term rates, but higher-risk, because the facility is repayable on demand",
    ],
    correct: 3,
    explanation:
      "This is the classic risk-return trade-off in funding policy: overdrafts are flexible and usually cheaper (interest only on the fluctuating balance drawn, at typically lower short-term rates) but can be withdrawn or called at short notice, creating refinancing risk. Option A gets both halves wrong — an overdraft IS repayable on demand; option B ignores the risk side entirely; option C swings to the opposite extreme, ignoring that overdrafts are ideal for the fluctuating layer of current assets.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM3-C-15",
    paper: "FM",
    area: "C",
    type: "mcq",
    stem: "Under the Miller-Orr cash management model, which of the following changes would INCREASE the spread between the lower and upper limits?",
    options: [
      "A rise in the daily interest rate available on short-term investments",
      "A fall in the transaction cost of buying and selling securities",
      "An increase in the variance of the company's daily cash flows",
      "A management decision to raise the lower limit",
    ],
    correct: 2,
    explanation:
      "Spread = 3 × [¾ × transaction cost × variance ÷ interest rate]^(1/3): more VOLATILE cash flows (higher variance) widen the limits so the company is not constantly trading securities. A higher interest rate sits in the denominator and NARROWS the spread (idle cash costs more), and lower transaction costs also narrow it (rebalancing becomes cheap). Raising the lower limit shifts BOTH limits upwards but leaves the spread itself unchanged — position and width are set independently.",
    marks: 2,
    difficulty: "medium",
  },
]
