import type { Flashcard } from "@/lib/acca-flashcards"

/* Flashcard wave 4 — BT/LW to revision depth (2026-07-10). */
export const FLASHCARDS_WAVE4: Flashcard[] = [
  /* ── BT — Business and Technology (50) ──────────────────────── */

  /* BT A — Business organisation & environment (12) */
  { id: "BT-FC3-01", paper: "BT", area: "A", front: "Mendelow: a stakeholder has HIGH power but LOW interest — the strategy?", back: "Keep satisfied — meet their key needs so they stay passive, but don't drown them in detail. If their interest awakens they become key players." },
  { id: "BT-FC3-02", paper: "BT", area: "A", front: "Mendelow: HIGH interest but LOW power — the strategy?", back: "Keep informed — communicate openly (they can lobby and influence the powerful), but they need not drive decisions." },
  { id: "BT-FC3-03", paper: "BT", area: "A", front: "Internal, connected and external stakeholders — one example of each", back: "Internal: employees and management. Connected: shareholders, customers, suppliers, lenders (a contractual link). External: government, local community, pressure groups." },
  { id: "BT-FC3-04", paper: "BT", area: "A", front: "Mintzberg's five organisational building blocks", back: "Strategic apex (top management), middle line, operating core (the doers), technostructure (standard-setters: planners, accountants), support staff (services like IT, catering)." },
  { id: "BT-FC3-05", paper: "BT", area: "A", front: "Tall vs flat organisation — spans and chains", back: "Tall: many levels, NARROW spans of control, long scalar chain, slower decisions. Flat: few levels, WIDE spans, shorter chain, more delegation." },
  { id: "BT-FC3-06", paper: "BT", area: "A", front: "The matrix structure — its core trade-off", back: "Staff report to both a functional and a product/project manager: better coordination and flexibility, at the price of dual authority, conflicting priorities and slower conflict resolution." },
  { id: "BT-FC3-07", paper: "BT", area: "A", front: "Porter's value chain — the five PRIMARY activities", back: "Inbound logistics, operations, outbound logistics, marketing & sales, service. (Support: firm infrastructure, HRM, technology development, procurement.)" },
  { id: "BT-FC3-08", paper: "BT", area: "A", front: "Movement along vs shift of the demand curve", back: "A change in the good's OWN price moves you along the curve. Anything else (income, tastes, prices of substitutes/complements) shifts the whole curve." },
  { id: "BT-FC3-09", paper: "BT", area: "A", front: "Four types of unemployment", back: "Frictional (between jobs), seasonal, cyclical (deficient demand in a downturn), structural (industry decline leaves skills stranded)." },
  { id: "BT-FC3-10", paper: "BT", area: "A", front: "Fiscal vs monetary policy", back: "Fiscal: government spending, taxation and borrowing. Monetary: interest rates, money supply and exchange rates — typically operated through the central bank." },
  { id: "BT-FC3-11", paper: "BT", area: "A", front: "Demand-pull vs cost-push inflation", back: "Demand-pull: total demand outruns capacity and prices are bid up. Cost-push: rising input costs (wages, energy, imports) are passed on as higher prices." },
  { id: "BT-FC3-12", paper: "BT", area: "A", front: "Centralisation — the one-line case for and against", back: "For: consistent decisions, tighter control, economies of scale. Against: slower response, overloaded top management, demotivated junior managers." },

  /* BT B — People in organisations (13) */
  { id: "BT-FC3-13", paper: "BT", area: "B", front: "Herzberg: hygiene factors vs motivators", back: "Hygiene (pay, conditions, company policy, supervision, job security) only PREVENT dissatisfaction. Motivators (achievement, recognition, the work itself, responsibility, advancement) create satisfaction. More pay ≠ more motivation." },
  { id: "BT-FC3-14", paper: "BT", area: "B", front: "Maslow's hierarchy — the order, bottom to top", back: "Physiological → safety → social (belonging) → esteem → self-actualisation. A satisfied need stops motivating; the next level up takes over." },
  { id: "BT-FC3-15", paper: "BT", area: "B", front: "McGregor's Theory X vs Theory Y", back: "Two ASSUMPTIONS managers hold about workers — X: people dislike work and need coercion and control; Y: people seek responsibility and self-direction. They describe the manager's mindset, not the workers." },
  { id: "BT-FC3-16", paper: "BT", area: "B", front: "Belbin's Plant — in one line", back: "The creative ideas-generator who solves difficult problems — but may be weak on detail and communication. Every team needs one; two tend to clash." },
  { id: "BT-FC3-17", paper: "BT", area: "B", front: "Belbin: Monitor-Evaluator vs Completer-Finisher", back: "Monitor-Evaluator: the sober, strategic judge of options — can lack drive. Completer-Finisher: the conscientious polisher who hunts errors and meets deadlines — inclined to worry and reluctant to delegate." },
  { id: "BT-FC3-18", paper: "BT", area: "B", front: "Tuckman: how do you tell STORMING from NORMING?", back: "Storming: open conflict as members contest roles, leadership and methods. Norming: the settling phase — agreed standards, roles and procedures emerge. Conflict then trust." },
  { id: "BT-FC3-19", paper: "BT", area: "B", front: "Blake & Mouton's managerial grid — the axes and the ideal", back: "Concern for PRODUCTION vs concern for PEOPLE, each scored 1-9. (9,9) 'team management' is the ideal; (1,9) country club, (9,1) task-driven, (1,1) impoverished, (5,5) middle-of-the-road." },
  { id: "BT-FC3-20", paper: "BT", area: "B", front: "The Ashridge four management styles — in order of increasing participation", back: "Tells (decides and announces) → sells (decides then persuades) → consults (asks before deciding) → joins (decides with the team)." },
  { id: "BT-FC3-21", paper: "BT", area: "B", front: "Handy's four cultures — match each to its structure", back: "Power (web around one boss — small entrepreneurial firms), role (bureaucracy of defined jobs), task (project/matrix teams, expertise rules), person (the organisation serves the individuals, e.g. a partnership of professionals)." },
  { id: "BT-FC3-22", paper: "BT", area: "B", front: "Vroom's expectancy theory — the equation", back: "Force (motivation) = valence × expectancy: how much the outcome is WANTED times how likely effort is believed to deliver it. Either factor at zero kills motivation." },
  { id: "BT-FC3-23", paper: "BT", area: "B", front: "Honey & Mumford's four learning styles", back: "Activist (learns by doing), reflector (observes and mulls), theorist (wants models and logic), pragmatist (wants tools to apply now)." },
  { id: "BT-FC3-24", paper: "BT", area: "B", front: "Coaching vs mentoring", back: "Coaching: a (usually senior) colleague develops specific job skills over the short term. Mentoring: a trusted adviser OUTSIDE the reporting line guides longer-term career and development." },
  { id: "BT-FC3-25", paper: "BT", area: "B", front: "Adair's action-centred leadership — the three overlapping needs", back: "Task, team and individual. The leader's job is to keep all three circles in balance — obsessing over the task starves the team and its members." },

  /* BT C — Governance, ethics & professional behaviour (12) */
  { id: "BT-FC3-26", paper: "BT", area: "C", front: "The five THREATS to the fundamental ethical principles", back: "Self-interest, self-review, advocacy, familiarity, intimidation." },
  { id: "BT-FC3-27", paper: "BT", area: "C", front: "When MAY (or must) an accountant disclose confidential information?", back: "When permitted by the client, required by law (e.g. a court order or money-laundering report), or where there is a professional right/duty in the public interest. Otherwise confidentiality survives even after the relationship ends." },
  { id: "BT-FC3-28", paper: "BT", area: "C", front: "Integrity vs objectivity — the distinction", back: "Integrity: being straightforward and honest — not being party to misleading information. Objectivity: not letting bias, conflicts of interest or undue influence override judgement." },
  { id: "BT-FC3-29", paper: "BT", area: "C", front: "Professional competence and due care — its two demands", back: "Attain AND MAINTAIN the knowledge and skill the work requires (CPD), and act diligently in line with technical and professional standards." },
  { id: "BT-FC3-30", paper: "BT", area: "C", front: "The audit committee — purpose in one line", back: "Non-executive oversight of financial reporting, internal control and internal audit, plus the relationship with (and independence of) the external auditor." },
  { id: "BT-FC3-31", paper: "BT", area: "C", front: "The remuneration committee — purpose and composition", back: "Sets executive directors' pay packages; staffed by independent NEDs so that no director decides their own remuneration." },
  { id: "BT-FC3-32", paper: "BT", area: "C", front: "The nomination committee — purpose in one line", back: "Keeps the board's size, balance and skills right: leads formal appointments and plans succession for board positions." },
  { id: "BT-FC3-33", paper: "BT", area: "C", front: "Executive vs non-executive directors", back: "Executives run the business day to day as employees; NEDs are outsiders on the board who challenge, scrutinise and monitor — independence is their value." },
  { id: "BT-FC3-34", paper: "BT", area: "C", front: "Why split the chairman and CEO roles?", back: "It divides running the BOARD from running the BUSINESS, so no single individual has unfettered power — a core governance principle." },
  { id: "BT-FC3-35", paper: "BT", area: "C", front: "Corporate governance — the classic (Cadbury) definition", back: "The system by which companies are directed and controlled — in the interests of shareholders and other stakeholders." },
  { id: "BT-FC3-36", paper: "BT", area: "C", front: "Carroll's CSR pyramid — the four layers, bottom up", back: "Economic (be profitable) → legal (obey the law) → ethical (do what is right beyond the law) → philanthropic (be a good corporate citizen)." },
  { id: "BT-FC3-37", paper: "BT", area: "C", front: "A conflict of interest arises — name two safeguards short of resignation", back: "Disclose it to those affected and obtain consent; use separate teams and information barriers; have an independent partner review the work. If the threat stays too high, decline or end the engagement." },

  /* BT D — Accounting, internal control & technology (13) */
  { id: "BT-FC3-38", paper: "BT", area: "D", front: "Teeming and lading — define it", back: "A cashier steals a customer's receipt, then hides the gap by crediting that account with a LATER customer's payment — rolling the shortfall forward indefinitely. Broken by segregation of duties and independent reconciliations." },
  { id: "BT-FC3-39", paper: "BT", area: "D", front: "The 'Vs' of big data", back: "Volume (scale), velocity (speed of arrival), variety (structured and unstructured forms) — plus veracity, the doubtful reliability of some of it." },
  { id: "BT-FC3-40", paper: "BT", area: "D", front: "Segregation of duties — what gets separated?", back: "Authorising a transaction, recording it, and custody of the related asset — kept in different hands so one person cannot both commit and conceal a fraud." },
  { id: "BT-FC3-41", paper: "BT", area: "D", front: "The three prerequisites for fraud", back: "Dishonesty (a person prepared to act), motivation (pressure or incentive), and opportunity (weak controls). Remove any one and the fraud fails." },
  { id: "BT-FC3-42", paper: "BT", area: "D", front: "The three stages of money laundering", back: "Placement (dirty cash enters the financial system), layering (transfers to disguise its origin), integration (it re-emerges as apparently legitimate wealth)." },
  { id: "BT-FC3-43", paper: "BT", area: "D", front: "Internal audit vs external audit", back: "Internal: reviews controls, risk and value for money, reports to management/the audit committee, scope set internally. External: an independent statutory opinion on the financial statements, reporting to the shareholders." },
  { id: "BT-FC3-44", paper: "BT", area: "D", front: "General vs application IT controls", back: "General: environment-wide controls (access rights, backups, change management, physical security). Application: built into ONE system's processing — input validation, batch totals, exception reports." },
  { id: "BT-FC3-45", paper: "BT", area: "D", front: "Phishing vs pharming", back: "Phishing: fraudulent messages lure the USER into surrendering credentials. Pharming: traffic is silently redirected to a counterfeit website — the user typed the right address and was hijacked anyway." },
  { id: "BT-FC3-46", paper: "BT", area: "D", front: "Robotic process automation (RPA) — one line", back: "Software 'robots' that follow rules to perform high-volume, repetitive clerical tasks (matching, posting, reconciling) — automating the process without changing the underlying systems." },
  { id: "BT-FC3-47", paper: "BT", area: "D", front: "Blockchain (distributed ledger) — one line", back: "A shared ledger replicated across many participants where validated blocks of transactions are cryptographically chained — so records are effectively tamper-evident with no central record-keeper." },
  { id: "BT-FC3-48", paper: "BT", area: "D", front: "The three-way match in a purchases system", back: "Purchase order + goods received note + supplier invoice are matched before payment — so the business only pays for what it ordered AND received, at the agreed price." },
  { id: "BT-FC3-49", paper: "BT", area: "D", front: "Prevent, detect, correct controls — one example of each", back: "Prevent: authorisation limits stop the error happening. Detect: reconciliations and exception reports find it afterwards. Correct: backups and contingency plans put it right." },
  { id: "BT-FC3-50", paper: "BT", area: "D", front: "Treasury function vs financial control function", back: "Treasury manages cash, funding, currency and investment of surpluses — forward-looking money management. Financial control records, reports and controls what has happened." },

  /* ── LW — Corporate and Business Law, ENG (50) ──────────────── */

  /* LW A — Essential elements of the legal system (11) */
  { id: "LW-FC3-01", paper: "LW", area: "A", front: "Criminal vs civil law — parties and standard of proof", back: "Criminal: the STATE prosecutes; guilt beyond reasonable doubt; sanction is punishment. Civil: individual sues individual; balance of probabilities; remedy compensates the claimant." },
  { id: "LW-FC3-02", paper: "LW", area: "A", front: "Common law vs equity — the practical difference in remedies", back: "Common law gives damages AS OF RIGHT; equitable remedies (specific performance, injunction, rescission) are DISCRETIONARY and refused where damages are adequate or the claimant acted unfairly." },
  { id: "LW-FC3-03", paper: "LW", area: "A", front: "Ratio decidendi vs obiter dicta", back: "Ratio: the legal reasoning essential to the decision — the binding part. Obiter: things said by the way (hypotheticals, dissents) — persuasive only." },
  { id: "LW-FC3-04", paper: "LW", area: "A", front: "Can the Supreme Court depart from its own previous decisions?", back: "Yes — since the Practice Statement 1966, when it appears right to do so. Its decisions still bind every lower court." },
  { id: "LW-FC3-05", paper: "LW", area: "A", front: "The three classic rules of statutory interpretation", back: "Literal rule: give words their plain meaning. Golden rule: depart from the literal meaning only to avoid absurdity. Mischief rule: ask what defect in the old law the statute set out to cure." },
  { id: "LW-FC3-06", paper: "LW", area: "A", front: "Delegated legislation — forms and why Parliament uses it", back: "Statutory instruments, byelaws, Orders in Council. It saves parliamentary time, uses specialist expertise and is quick to amend — controlled by parliamentary scrutiny and judicial review (ultra vires)." },
  { id: "LW-FC3-07", paper: "LW", area: "A", front: "Distinguishing, overruling, reversing — three ways to escape a precedent", back: "Distinguish: the material facts differ, so the precedent doesn't apply. Overrule: a higher court kills the precedent in a LATER, different case. Reverse: an appeal court changes the outcome of THE SAME case." },
  { id: "LW-FC3-08", paper: "LW", area: "A", front: "Human Rights Act 1998 — what can a court do with an incompatible statute?", back: "Interpret legislation compatibly with Convention rights so far as possible (s3); if impossible, a higher court may issue a declaration of incompatibility (s4) — the statute remains valid until Parliament changes it." },
  { id: "LW-FC3-09", paper: "LW", area: "A", front: "The main sources of English law", back: "Legislation (Acts and delegated legislation), case law (common law and equity built on precedent), and — historically — custom. Legislation prevails over case law." },
  { id: "LW-FC3-10", paper: "LW", area: "A", front: "Which civil courts hear a contract claim at first instance?", back: "County Court for smaller claims; High Court (King's Bench Division) for larger or complex ones. Claims are allocated to the small claims, fast, intermediate or multi-track by value and complexity." },
  { id: "LW-FC3-11", paper: "LW", area: "A", front: "Binding vs persuasive precedent — who binds whom?", back: "Only the RATIO of a HIGHER court (or the same court, subject to exceptions) binds. Lower courts, Privy Council decisions and obiter statements persuade but never bind." },

  /* LW B — The law of obligations (14) */
  { id: "LW-FC3-12", paper: "LW", area: "B", front: "The postal rule — and its limits", back: "Acceptance by post is complete when the letter is POSTED, even if it never arrives — Adams v Lindsell. Only for acceptance (never revocation), only where post is a reasonable means, and excluded by a term requiring actual notice." },
  { id: "LW-FC3-13", paper: "LW", area: "B", front: "Can an advert ever be an offer?", back: "Yes — a UNILATERAL offer to the whole world, accepted by performing the condition: Carlill v Carbolic Smoke Ball. Ordinary adverts of goods for sale remain invitations to treat." },
  { id: "LW-FC3-14", paper: "LW", area: "B", front: "Revocation of an offer — the two key rules", back: "Effective only when it REACHES the offeree (no postal rule: Byrne v Van Tienhoven), and it may be communicated by a reliable third party — Dickinson v Dodds. It must arrive before acceptance." },
  { id: "LW-FC3-15", paper: "LW", area: "B", front: "Counter-offer vs request for further information", back: "A counter-offer DESTROYS the original offer (Hyde v Wrench — £950 for the £1,000 farm). A mere enquiry about terms leaves it open for acceptance — Stevenson v McLean." },
  { id: "LW-FC3-16", paper: "LW", area: "B", front: "Consideration must be sufficient but need not be adequate — meaning?", back: "It must have SOME legal value, but the courts never weigh the bargain: three chocolate wrappers counted in Chappell v Nestlé. A bad deal is still a binding deal." },
  { id: "LW-FC3-17", paper: "LW", area: "B", front: "Past consideration — the rule and its exception", back: "An act done BEFORE the promise cannot support it — Re McArdle. Exception: an act done at the promisor's request, where payment was always understood — Lampleigh v Braithwait." },
  { id: "LW-FC3-18", paper: "LW", area: "B", front: "Is performing an existing contractual duty good consideration?", back: "Not by itself — Stilk v Myrick. It becomes good consideration if the promisee exceeds the duty (Hartley v Ponsonby) or the promisor gains a PRACTICAL BENEFIT without duress — Williams v Roffey." },
  { id: "LW-FC3-19", paper: "LW", area: "B", front: "Part payment of a debt — is the balance discharged?", back: "No: paying less can't satisfy the whole (Pinnel's Case; Foakes v Beer) — unless something different is given (early payment, goods), or promissory estoppel (High Trees) makes it inequitable to go back on the promise." },
  { id: "LW-FC3-20", paper: "LW", area: "B", front: "Intention to create legal relations — the two presumptions", back: "Domestic/social agreements: presumed NOT binding (Balfour v Balfour) — rebutted where spouses are separated (Merritt v Merritt). Commercial agreements: presumed binding unless clearly excluded." },
  { id: "LW-FC3-21", paper: "LW", area: "B", front: "Condition vs warranty — and the opera-singer cases", back: "Condition goes to the root: breach allows repudiation AND damages — Poussard v Spiers (missed opening night). Warranty is subsidiary: damages only — Bettini v Gye (missed rehearsals). Innominate terms are judged by the seriousness of the breach." },
  { id: "LW-FC3-22", paper: "LW", area: "B", front: "Exclusion clauses and UCTA 1977 — the absolute limit", back: "Liability for death or personal injury caused by NEGLIGENCE can never be excluded; exclusions for other loss stand only if reasonable — and the clause must first have been properly incorporated." },
  { id: "LW-FC3-23", paper: "LW", area: "B", front: "Remoteness of damage in contract — Hadley v Baxendale", back: "Recoverable losses: (1) those arising naturally in the usual course of things, and (2) unusual losses within BOTH parties' contemplation when contracting. The crankshaft carrier didn't know the mill stood idle — no lost profits." },
  { id: "LW-FC3-24", paper: "LW", area: "B", front: "The Caparo three-stage test for a duty of care", back: "Was the damage reasonably FORESEEABLE; was there sufficient PROXIMITY between the parties; is it FAIR, JUST AND REASONABLE to impose the duty? — Caparo v Dickman." },
  { id: "LW-FC3-25", paper: "LW", area: "B", front: "Negligent misstatement — when does a duty arise?", back: "Hedley Byrne v Heller: a SPECIAL RELATIONSHIP — the adviser has special skill, knows the advice will be relied on, and the claimant reasonably relies. (An effective disclaimer defeated the claim in the case itself.)" },

  /* LW C — Employment law (11) */
  { id: "LW-FC3-26", paper: "LW", area: "C", front: "The three tests for employee status", back: "Control (who directs how work is done), integration (is the person part of the organisation), and the multiple/economic-reality test — weighing personal service, mutual obligations and financial risk: Ready Mixed Concrete." },
  { id: "LW-FC3-27", paper: "LW", area: "C", front: "Why does employee vs self-employed status matter?", back: "Employees get statutory rights (unfair dismissal, redundancy pay), their employer is vicariously liable for their torts, deducts tax at source and gains implied duties — contractors get almost none of this." },
  { id: "LW-FC3-28", paper: "LW", area: "C", front: "Wrongful vs unfair dismissal", back: "Wrongful: a COMMON-LAW claim for breach of contract — usually dismissal without proper notice; damages only. Unfair: a STATUTORY claim about the reason and fairness of the dismissal, heard by a tribunal." },
  { id: "LW-FC3-29", paper: "LW", area: "C", front: "Qualifying period for ordinary unfair dismissal?", back: "Two years' continuous employment — but NO qualifying period where the reason is automatically unfair (e.g. pregnancy, whistleblowing, trade-union membership)." },
  { id: "LW-FC3-30", paper: "LW", area: "C", front: "The five potentially fair reasons for dismissal", back: "Capability or qualifications; conduct; redundancy; statutory illegality (continuing would break the law); some other substantial reason. The employer must also act reasonably in relying on the reason." },
  { id: "LW-FC3-31", paper: "LW", area: "C", front: "Constructive dismissal — what is it?", back: "The EMPLOYEE resigns in response to the employer's repudiatory breach (e.g. destroying mutual trust and confidence) and is treated as dismissed — Western Excavating v Sharp. Resign promptly or risk affirming the contract." },
  { id: "LW-FC3-32", paper: "LW", area: "C", front: "Remedies for unfair dismissal — in the tribunal's order", back: "Reinstatement (old job back), re-engagement (comparable job), or compensation — a basic award computed from age, service and weekly pay, plus a compensatory award for actual loss." },
  { id: "LW-FC3-33", paper: "LW", area: "C", front: "Redundancy — the three statutory situations", back: "The business closes; the employee's workplace closes; or the need for employees to do work of that kind ceases or diminishes. Two years' service qualifies for a statutory redundancy payment." },
  { id: "LW-FC3-34", paper: "LW", area: "C", front: "When is summary (no-notice) dismissal justified?", back: "Only for a fundamental breach by the employee — gross misconduct such as theft, violence or serious insubordination. Otherwise dismissal without notice is wrongful." },
  { id: "LW-FC3-35", paper: "LW", area: "C", front: "Implied duties of the EMPLOYEE", back: "Obey lawful and reasonable orders, exercise reasonable skill and care, and act in good faith (fidelity) — no secret profits, no misuse of confidential information." },
  { id: "LW-FC3-36", paper: "LW", area: "C", front: "Implied duties of the EMPLOYER", back: "Pay agreed remuneration, take reasonable care for the employee's health and safety, and not destroy mutual trust and confidence. (Generally no duty to PROVIDE work, only to pay.)" },

  /* LW D — Company law & corporate governance (14) */
  { id: "LW-FC3-37", paper: "LW", area: "D", front: "Fixed vs floating charge — the essential difference", back: "Fixed: attaches to a specific asset the company cannot deal with freely. Floating: hovers over a changing class (e.g. inventory) that the company trades normally — until crystallisation fixes it." },
  { id: "LW-FC3-38", paper: "LW", area: "D", front: "Charge priority — and the registration rule", back: "A fixed charge ranks ahead of a floating charge over the same assets even if created LATER. Charges must be registered at Companies House within 21 days or they are void against the liquidator and creditors." },
  { id: "LW-FC3-39", paper: "LW", area: "D", front: "When does a floating charge crystallise?", back: "On liquidation, the appointment of a receiver/administrator, cessation of business, or an event specified in the charge — it then fixes on the assets held at that moment." },
  { id: "LW-FC3-40", paper: "LW", area: "D", front: "When will courts lift the veil of incorporation?", back: "Where the company is a mere façade to evade an existing obligation: Gilford Motor v Horne (company formed to dodge a non-compete), Jones v Lipman (property shuffled into a company to escape specific performance). Also under statute (e.g. fraudulent trading)." },
  { id: "LW-FC3-41", paper: "LW", area: "D", front: "The s172 duty — state it", back: "To act in the way the director considers, in good faith, most likely to promote the SUCCESS of the company for the benefit of the MEMBERS as a whole — having regard to the long term, employees, suppliers and customers, community and environment, reputation, and fairness between members." },
  { id: "LW-FC3-42", paper: "LW", area: "D", front: "s174 duty of care, skill and diligence — the two-part standard", back: "That of a reasonably diligent person with (a) the knowledge and skill reasonably EXPECTED of someone in that role — the objective floor — and (b) the knowledge and skill that director ACTUALLY has — a subjective uplift, never a discount." },
  { id: "LW-FC3-43", paper: "LW", area: "D", front: "A director is interested in a proposed contract with the company — what must they do?", back: "Declare the nature and extent of the interest to the board BEFORE the company enters the transaction (s177 CA 2006). Ongoing conflicts of interest must otherwise be avoided or authorised (s175)." },
  { id: "LW-FC3-44", paper: "LW", area: "D", front: "Wrongful vs fraudulent trading", back: "Wrongful (IA 1986 s214): the director knew or OUGHT to have concluded insolvent liquidation was unavoidable and failed to take every step to minimise creditor losses — civil only. Fraudulent (s213): actual INTENT to defraud creditors — civil liability plus a criminal offence (CA 2006 s993)." },
  { id: "LW-FC3-45", paper: "LW", area: "D", front: "Ordinary vs special resolution", back: "Ordinary: simple majority (over 50% of votes cast) — e.g. removing a director. Special: at least 75% — e.g. changing the articles or the company name, reducing capital." },
  { id: "LW-FC3-46", paper: "LW", area: "D", front: "Public vs private company — four headline differences", back: "Plc: minimum £50,000 allotted share capital (quarter paid up), a trading certificate before trading, at least TWO directors and a qualified company secretary, and it may offer shares to the public. A private company needs none of these — and cannot make public offers." },
  { id: "LW-FC3-47", paper: "LW", area: "D", front: "Pre-incorporation contracts — who is liable?", back: "The company doesn't exist yet, so it cannot contract or later ratify: the PROMOTER is personally liable (CA 2006 s51; Kelner v Baxter). Escape routes: novation after incorporation, or an express exclusion of liability." },
  { id: "LW-FC3-48", paper: "LW", area: "D", front: "What profits can lawfully be distributed as dividends?", back: "Accumulated REALISED profits less accumulated REALISED losses (CA 2006 s830). A plc must additionally keep net assets at or above called-up share capital plus undistributable reserves (s831). Unlawful dividends are repayable by knowing members." },
  { id: "LW-FC3-49", paper: "LW", area: "D", front: "Removing a director against their will — the procedure", back: "Ordinary resolution of the members with SPECIAL NOTICE (28 days) to the company (CA 2006 s168). The director may make written representations and speak at the meeting — and a weighted-voting article (Bushell v Faith) can still defeat it." },
  { id: "LW-FC3-50", paper: "LW", area: "D", front: "Insider dealing — the offence in one line", back: "An individual with unpublished PRICE-SENSITIVE information from an inside source deals (or encourages dealing, or discloses the information) in price-affected securities — a criminal offence under the Criminal Justice Act 1993." },
]
