import type { WrittenQuestion } from "@/lib/acca-written"

/* Written bank wave 2 — FR/SBR/SBL/AA for the AI Examiner (2026-07-10).
 *
 * 24 scenario-based constructed-response questions: FR ×8, SBR ×8, SBL ×4,
 * AA ×4 (16-mark style: risks-and-responses, deficiencies-and-recommendations).
 * One awardable marking point per rubric line (rubric length = maxMarks).
 * All scenarios and companies are invented; no ACCA IP reproduced.
 */
export const WRITTEN_WAVE2: WrittenQuestion[] = [
  /* ───────────── FR — Financial Reporting (8) ───────────── */
  {
    id: "FR-W2-01",
    paper: "FR",
    area: "B",
    topic: "IAS 16 — revaluation with calculations",
    stem: "Keld Brewery Co bought its brewery building on 1 January 20X1 for $800,000, depreciating it straight-line over 40 years with a nil residual value under the cost model. On 1 January 20X5 the directors adopted the revaluation model and an independent valuer assessed the building at $900,000; its total useful life is unchanged. Explain, with calculations, how the revaluation and the year's depreciation are accounted for in the financial statements for the year ended 31 December 20X5, and how any future fall in the building's value would be treated. (8 marks)",
    maxMarks: 8,
    rubric: [
      "Depreciation under the cost model was $800,000 / 40 = $20,000 per year, so accumulated depreciation at 1 January 20X5 is 4 × $20,000 = $80,000.",
      "Carrying amount at the revaluation date is $800,000 − $80,000 = $720,000.",
      "The revaluation gain of $900,000 − $720,000 = $180,000 is recognised in other comprehensive income and accumulated in a revaluation surplus in equity, not in profit or loss.",
      "The revaluation model must be applied to the whole class of assets, and valuations kept sufficiently up to date.",
      "Depreciation for the year ended 31 December 20X5 is based on the revalued amount over the remaining life: $900,000 / 36 years = $25,000.",
      "An optional annual reserves transfer of the excess depreciation ($25,000 − $20,000 = $5,000) may be made from revaluation surplus to retained earnings.",
      "A future revaluation deficit on this building is taken to OCI against the $180,000 surplus first, with any excess charged to profit or loss.",
      "The revaluation surplus is never recycled through profit or loss — on disposal it is transferred directly to retained earnings within equity.",
    ],
  },
  {
    id: "FR-W2-02",
    paper: "FR",
    area: "B",
    topic: "IFRS 15 — bundled contract with calculations",
    stem: "Voltara Co manufactures backup power generators. On 1 October 20X7 it signed a $600,000 contract with a hospital covering: supply of a generator, its installation, and 24 months of servicing running from completion of installation. Voltara regularly sells each element separately at stand-alone selling prices of: generator $500,000, installation $50,000, servicing (24 months) $75,000. The generator was delivered and installation completed on 1 January 20X8, when the hospital paid the full contract price. Explain, with calculations, how much revenue Voltara recognises in the year ended 30 June 20X8 and how any balance is presented. (10 marks)",
    maxMarks: 10,
    rubric: [
      "The contract contains three distinct performance obligations — generator, installation and servicing — because the customer can benefit from each separately and each is separately identifiable in the contract.",
      "The $600,000 transaction price is allocated to the obligations on a relative stand-alone selling price basis; total stand-alone selling prices are $625,000.",
      "Generator: $600,000 × 500/625 = $480,000.",
      "Installation: $600,000 × 50/625 = $48,000.",
      "Servicing: $600,000 × 75/625 = $72,000.",
      "The generator and installation are satisfied at a point in time, so $480,000 + $48,000 = $528,000 is recognised on completed installation on 1 January 20X8.",
      "Servicing is satisfied over time because the hospital simultaneously receives and consumes the benefit, so its revenue is recognised straight-line over the 24 months.",
      "Servicing revenue for the year ended 30 June 20X8 is $72,000 × 6/24 = $18,000 (six months elapsed).",
      "Total revenue for the year is $480,000 + $48,000 + $18,000 = $546,000.",
      "The unearned servicing amount of $72,000 − $18,000 = $54,000 is a contract liability (deferred income), because cash was received in advance of performance.",
    ],
  },
  {
    id: "FR-W2-03",
    paper: "FR",
    area: "B",
    topic: "IAS 37 — provisions in a scenario",
    stem: "Bramble Kitchens Co has a year end of 31 December 20X6 and three outstanding matters. (1) A former employee is suing for unfair dismissal claiming $200,000; the company's lawyers estimate a 30% probability of losing. (2) On 10 December 20X6 the board approved a detailed formal plan to close its Harlow workshop and announced it to employees and customers before the year end; expected costs are redundancy payments $350,000, retraining staff who will be redeployed elsewhere $80,000, and operating losses up to the closure date $120,000. (3) The company gives a one-year warranty on fitted kitchens and, based on past claims experience, estimates the expected value of repair costs for units sold this year at $90,000. Explain, applying IAS 37, how each matter should be treated in the financial statements. (9 marks)",
    maxMarks: 9,
    rubric: [
      "A provision requires a present obligation (legal or constructive) from a past event, a probable outflow of economic benefits, and a reliable estimate.",
      "Court case: at 30% the outflow is possible but not probable, so no provision is recognised.",
      "The claim is a contingent liability — its nature and an estimate of the $200,000 exposure are disclosed, as the possibility is not remote.",
      "Closure: a constructive obligation exists because a detailed formal plan was approved and announced to those affected before the year end, creating a valid expectation.",
      "The restructuring provision includes only direct expenditures of the closure — the $350,000 redundancy costs are provided for.",
      "The $80,000 retraining relates to the continuing business, so it is excluded from the provision.",
      "The $120,000 future operating losses are not provided for — there is no present obligation for future losses.",
      "Warranty: the past event is the sale; across the population of kitchens an outflow is probable, so a provision of the expected value of $90,000 is recognised.",
      "Provisions are measured at the best estimate at the reporting date, discounted where the time value of money is material, and reviewed at each year end.",
    ],
  },
  {
    id: "FR-W2-04",
    paper: "FR",
    area: "C",
    topic: "Ratio analysis — performance & position",
    stem: "Solent Bikes Co, an e-bike retailer, shows the following for the years ended 31 March: revenue $20.0m (20X4) rising to $25.0m (20X5); gross margin 38% falling to 30%; operating margin 12% falling to 8%; receivables collection period 45 days rising to 68 days; gearing (debt/equity) 30% rising to 55%; interest cover 8 times falling to 3 times. Comment on the financial performance and position of Solent Bikes for the year ended 31 March 20X5, suggesting possible reasons for the changes. (10 marks)",
    maxMarks: 10,
    rubric: [
      "Revenue grew 25% ($20.0m to $25.0m), but the growth coincides with falling margins, suggesting it was bought through price discounting or a shift to lower-margin products.",
      "The gross margin fall from 38% to 30% indicates selling price cuts and/or input cost rises not passed on to customers.",
      "The operating margin fell 4 points against an 8-point gross margin fall, implying operating overheads grew more slowly than revenue (some cost control or economies of scale).",
      "Receivables days rising from 45 to 68 suggests credit terms were relaxed to stimulate sales, or that collections have deteriorated.",
      "Slower collection increases the risk of irrecoverable debts and puts pressure on operating cash flow and liquidity.",
      "Gearing rising from 30% to 55% indicates significant new borrowing, likely to fund the expansion behind the revenue growth.",
      "Interest cover falling from 8 to 3 times shows much less headroom to absorb profit falls or rate rises, increasing risk for lenders and of covenant breach.",
      "The combination of thinner margins and higher finance costs threatens future profitability and the company's capacity to pay dividends.",
      "Limitations: ratios use year-end balances, no industry benchmark or budget is given, and one year's movement may reflect one-off or seasonal factors.",
      "Conclusion: growth has been achieved at the cost of margin, credit risk and financial risk — management should monitor liquidity and collections closely.",
    ],
  },
  {
    id: "FR-W2-05",
    paper: "FR",
    area: "E",
    topic: "Goodwill & intra-group trading with calculations",
    stem: "On 1 January 20X6 Hazelmere Co acquired 80% of the equity shares of Sipworth Co for cash of $5.0m. The non-controlling interest at acquisition is measured at its fair value of $1.1m. The book value of Sipworth's net assets at that date was $5.0m; their fair value exceeded book value by $0.5m, relating entirely to land. During the year Sipworth sold goods to Hazelmere for $400,000 at a gross margin of 25%, and half of these goods remained in Hazelmere's inventory at 31 December 20X6. Explain, with calculations, the goodwill arising on acquisition and the adjustments required for the intra-group trading in the consolidated financial statements at 31 December 20X6. (10 marks)",
    maxMarks: 10,
    rubric: [
      "Goodwill = consideration transferred + non-controlling interest − fair value of the identifiable net assets acquired.",
      "The identifiable net assets are measured at fair value at acquisition: $5.0m + $0.5m land uplift = $5.5m.",
      "Goodwill = $5.0m + $1.1m − $5.5m = $0.6m.",
      "Measuring NCI at fair value is the full goodwill method, so the $0.6m includes the goodwill attributable to the NCI.",
      "Land is not depreciated, so the $0.5m fair value uplift creates no additional depreciation adjustment in the consolidated statements.",
      "Goodwill is not amortised but is tested for impairment at least annually, with any loss charged to profit or loss.",
      "The intra-group sale is eliminated in full: consolidated revenue and cost of sales are each reduced by $400,000.",
      "The unrealised profit in inventory (PURP) is $400,000 × 25% × 1/2 = $50,000.",
      "Consolidated inventory is reduced by the $50,000 PURP, increasing consolidated cost of sales.",
      "Because Sipworth (the subsidiary) is the seller, the PURP reduces Sipworth's profit, so the NCI share of profit falls by 20% × $50,000 = $10,000.",
    ],
  },
  {
    id: "FR-W2-06",
    paper: "FR",
    area: "B",
    topic: "IAS 38 — research & development",
    stem: "Aterna Agritech Co is developing crop-monitoring software. In the year ended 31 December 20X5 it spent: $150,000 on research evaluating alternative sensor technologies; $60,000 on development work before 1 May 20X5, the date on which technical feasibility and the other IAS 38 capitalisation criteria were first demonstrated; and $420,000 on development from 1 May 20X5 to the year end, throughout which all the criteria continued to be met. Commercial launch is expected next year. Explain how each element of the expenditure should be accounted for. (8 marks)",
    maxMarks: 8,
    rubric: [
      "Research expenditure is expensed as incurred, so the $150,000 is charged to profit or loss.",
      "Development expenditure is capitalised only from the date all the IAS 38 criteria are demonstrated.",
      "Criteria include technical feasibility of completing the asset, the intention to complete it, and the ability to use or sell it.",
      "Criteria also include probable future economic benefits (e.g. a market exists), adequate technical and financial resources to complete, and the ability to measure the expenditure reliably.",
      "The $60,000 incurred before 1 May 20X5 is expensed, and cannot be reinstated as an asset once the criteria are later met.",
      "The $420,000 incurred from 1 May 20X5 is capitalised as an intangible asset.",
      "Amortisation begins only when the asset is available for use (around next year's launch), over its useful life — so no amortisation is charged in 20X5.",
      "As an intangible not yet available for use, the capitalised development cost must be tested for impairment annually under IAS 36.",
    ],
  },
  {
    id: "FR-W2-07",
    paper: "FR",
    area: "B",
    topic: "IAS 10 — events after the reporting period",
    stem: "Marlin Foods Co has a year end of 31 December 20X4 and its financial statements will be authorised for issue on 15 March 20X5. Three events have occurred since the year end: (1) in February 20X5 a customer owing $180,000 at 31 December went into insolvent liquidation, with little prospect of recovery; (2) in January 20X5 a fire destroyed one of the company's warehouses, causing material uninsured losses; (3) in February 20X5 the directors declared a dividend in respect of 20X4. Explain, applying IAS 10, how each event should be treated in the 20X4 financial statements, and state the overriding exception concerning going concern. (8 marks)",
    maxMarks: 8,
    rubric: [
      "Adjusting events provide evidence of conditions that existed at the reporting date; non-adjusting events are indicative of conditions arising afterwards.",
      "The customer's liquidation is an adjusting event — it normally evidences that the receivable was already impaired at 31 December 20X4.",
      "The $180,000 receivable is written off (or fully allowed for), reducing both profit and trade receivables in the 20X4 statements.",
      "The warehouse fire is a non-adjusting event because the condition (the fire) arose after the reporting date.",
      "No adjustment is made for the fire, but as it is material its nature and an estimate of the financial effect are disclosed.",
      "The dividend declared in February 20X5 is not a liability at the reporting date, because no obligation existed at 31 December 20X4.",
      "The dividend is therefore not recognised, but is disclosed in the notes.",
      "Exception: if an event after the reporting date shows the going concern basis is no longer appropriate, the financial statements must be prepared on a different basis — not merely adjusted.",
    ],
  },
  {
    id: "FR-W2-08",
    paper: "FR",
    area: "D",
    topic: "IAS 7 — statement of cash flows items",
    stem: "Torfin Co prepares its statement of cash flows using the indirect method. During the year ended 31 December 20X6: depreciation charged was $340,000; plant with a carrying amount of $120,000 was sold for $150,000; trade receivables increased by $95,000; a share issue raised $500,000; interest of $60,000 was paid; and property, plant and equipment costing $700,000 was purchased for cash. Explain how each item is treated in the statement of cash flows. (6 marks)",
    maxMarks: 6,
    rubric: [
      "Depreciation of $340,000 is added back to profit in operating activities because it is a non-cash expense.",
      "The $30,000 profit on disposal ($150,000 − $120,000) is deducted from operating profit, and the $150,000 proceeds are shown as an investing inflow.",
      "The $95,000 increase in trade receivables is deducted in operating activities — those sales have not yet been collected in cash.",
      "The $500,000 share issue proceeds are a financing inflow.",
      "Interest paid of $60,000 is normally an operating outflow (IAS 7 also permits financing), applied consistently and disclosed separately.",
      "The $700,000 purchase of property, plant and equipment is an investing outflow.",
    ],
  },

  /* ───────────── SBR — Strategic Business Reporting (8) ───────────── */
  {
    id: "SBR-W2-01",
    paper: "SBR",
    area: "B",
    topic: "IAS 12 — deferred tax on revaluations & losses",
    stem: "Kestrel Marine Co (tax rate 25%) revalued its fleet of vessels upwards by $4m during the year; the tax base of the vessels is unaffected by the revaluation. Kestrel also has $6m of unused tax losses carried forward after several consecutive loss-making years, although it has just secured a large multi-year charter contract. Discuss, with calculations where relevant, the deferred tax consequences of the revaluation and of the unused tax losses. (8 marks)",
    maxMarks: 8,
    rubric: [
      "Deferred tax is recognised on temporary differences — differences between the carrying amount of an asset or liability and its tax base.",
      "The revaluation increases the vessels' carrying amount while the tax base is unchanged, creating a taxable temporary difference of $4m.",
      "A deferred tax liability of $4m × 25% = $1m is recognised.",
      "Because the revaluation gain was recognised in OCI, the related deferred tax is also charged to OCI, not profit or loss.",
      "Unused tax losses give rise to a potential deferred tax asset (a deductible amount against future profits).",
      "A deferred tax asset is recognised only to the extent it is probable that future taxable profit will be available to absorb the losses.",
      "Kestrel's history of losses means convincing other evidence is required — the new charter contract may provide it, considering any expiry dates of the losses and tax-planning opportunities.",
      "If recognition is supported, the asset is up to $6m × 25% = $1.5m (or a supportable portion), reassessed at each reporting date with the significant judgement disclosed.",
    ],
  },
  {
    id: "SBR-W2-02",
    paper: "SBR",
    area: "C",
    topic: "IFRS 3 — business combination achieved in stages",
    stem: "Orlan Group has held 30% of Petra Co for several years, equity-accounting it as an associate with a carrying amount of $8.2m. On 1 July 20X6 Orlan acquired a further 45% of Petra for $16m cash, obtaining control. At that date the fair value of the original 30% holding was $10.5m, the non-controlling interest is measured at its fair value of $6.8m, and the fair value of Petra's identifiable net assets was $28m. Discuss, with calculations, how this transaction is accounted for in Orlan's consolidated financial statements. (8 marks)",
    maxMarks: 8,
    rubric: [
      "Moving from significant influence to control is a business combination achieved in stages — the acquisition method is applied at the date control is obtained (1 July 20X6).",
      "Equity accounting for Petra ceases from 1 July 20X6.",
      "The previously held 30% interest is remeasured to its acquisition-date fair value of $10.5m.",
      "The remeasurement gain of $10.5m − $8.2m = $2.3m is recognised in profit or loss.",
      "Goodwill = consideration transferred + fair value of the previously held interest + NCI − fair value of identifiable net assets.",
      "Goodwill = $16m + $10.5m + $6.8m − $28m = $5.3m.",
      "Petra is consolidated line by line from 1 July 20X6, with a 25% non-controlling interest recognised (initially at its $6.8m fair value).",
      "Any amounts previously recognised in OCI in respect of the associate are accounted for as if the associate had been disposed of (reclassified to profit or loss or transferred within equity as the related standard requires).",
    ],
  },
  {
    id: "SBR-W2-03",
    paper: "SBR",
    area: "D",
    topic: "IAS 19 — defined benefit components & amendment",
    stem: "Halvard Engineering Co operates a defined benefit pension plan. During the year it amended the plan to grant improved benefits for past service, at a cost of $1.2m, and the actuary also reported a loss from changes in financial assumptions. Explain how the components of defined benefit cost are recognised under IAS 19, and how the plan amendment and the actuarial loss are treated. (8 marks)",
    maxMarks: 8,
    rubric: [
      "Current service cost — the increase in the obligation from employee service in the period — is recognised in profit or loss.",
      "Net interest is calculated by applying the discount rate (as at the start of the year) to the net defined benefit liability or asset, and is recognised in profit or loss.",
      "The discount rate is determined by reference to market yields on high-quality corporate bonds.",
      "Remeasurements — actuarial gains and losses and the return on plan assets excluding amounts in net interest — are recognised in other comprehensive income.",
      "Remeasurements are never reclassified (recycled) to profit or loss in later periods, so the actuarial loss from the assumption changes stays in OCI.",
      "The plan amendment gives rise to past service cost, recognised immediately in profit or loss at the earlier of when the amendment occurs and when related restructuring costs are recognised.",
      "The $1.2m past service cost is therefore expensed in full in the current year — it is not spread over future service.",
      "The statement of financial position shows the net defined benefit liability (present value of the obligation less the fair value of plan assets), with any surplus restricted by the asset ceiling.",
    ],
  },
  {
    id: "SBR-W2-04",
    paper: "SBR",
    area: "E",
    topic: "Alternative performance measures — investor view",
    stem: "Vantora plc headlines an 'adjusted EBITDA' in its annual report which excludes restructuring costs ($3m — the third consecutive year a restructuring charge has been excluded) and share-based payment expense ($2m, recurring annually). Adjusted EBITDA shows growth this year even though IFRS operating profit fell. Discuss the usefulness and the dangers of such alternative performance measures (APMs) from an investor's perspective, and what investors should expect of the company's disclosure. (8 marks)",
    maxMarks: 8,
    rubric: [
      "APMs can be useful: they can strip out genuinely one-off items, present management's view of underlying performance, and aid comparison of the core business over time.",
      "But APMs are not defined by IFRS, so they are not comparable across entities and their calculation can be changed from year to year.",
      "Excluding restructuring for a third consecutive year suggests the cost is effectively recurring, so its exclusion overstates 'underlying' performance.",
      "Share-based payment is a real, recurring cost of employing staff; excluding the $2m persistently flatters profit.",
      "The divergence — adjusted EBITDA growing while IFRS operating profit falls — risks obscuring deteriorating statutory performance and indicates possible impression management or bias.",
      "Investors should expect a clear reconciliation of the APM to the nearest IFRS measure, presented with no greater prominence than the statutory figures.",
      "Definitions should be consistent year on year with any changes explained — consistent with regulatory guidance (e.g. ESMA/IOSCO) and the directors' duty of neutral, faithful representation.",
      "Investors should anchor on statutory profit and cash flows, scrutinise each adjustment's justification, and challenge management where exclusions recur.",
    ],
  },
  {
    id: "SBR-W2-05",
    paper: "SBR",
    area: "B",
    topic: "IFRS 5 — held for sale & discontinued operations",
    stem: "On 1 November 20X6 the board of Ramio Group approved a plan to sell its logistics division — a separate major line of business — appointed a broker, and began actively marketing the division at a price the broker considers reasonable; completion is expected by June 20X7. At the 31 December 20X6 year end the division's carrying amount is $40m and its fair value less costs to sell is $36m. Discuss how the division should be classified, measured and presented in the 20X6 consolidated financial statements. (9 marks)",
    maxMarks: 9,
    rubric: [
      "A disposal group is classified as held for sale when it is available for immediate sale in its present condition and the sale is highly probable.",
      "Highly probable requires management commitment, an active programme to locate a buyer, marketing at a reasonable price and expected completion within 12 months — all evidenced here by the board approval, the broker appointment, active marketing and the June 20X7 timeline.",
      "A held-for-sale disposal group is measured at the lower of its carrying amount and fair value less costs to sell.",
      "An impairment loss of $40m − $36m = $4m is recognised in profit or loss.",
      "Depreciation and amortisation of the division's assets cease while it is classified as held for sale.",
      "In the statement of financial position the division's assets and its liabilities are each presented separately from other items (not offset against each other).",
      "The division is a discontinued operation because it is a separate major line of business being disposed of under a single co-ordinated plan.",
      "The statement of profit or loss presents a single amount comprising the post-tax result of the discontinued operation and the post-tax impairment/disposal loss, analysed further in the notes.",
      "Comparatives are re-presented for the profit or loss disclosure of the discontinued operation (but the prior-year statement of financial position is not restated).",
    ],
  },
  {
    id: "SBR-W2-06",
    paper: "SBR",
    area: "D",
    topic: "IAS 32 — liability vs equity; compound instruments",
    stem: "Corvid Co has issued two instruments. (1) $5m of 6% cumulative preference shares redeemable in cash at the option of the holder. (2) A $10m 4% convertible bond, repayable in three years, whose holders may elect on maturity to convert into a fixed number of ordinary shares instead of receiving cash; the market rate for a similar bond without conversion rights is 8%. Relevant 8% discount factors: 3-year cumulative (annuity) 2.577; 3-year single 0.794. Discuss, with calculations, how each instrument is classified and accounted for. (10 marks)",
    maxMarks: 10,
    rubric: [
      "Classification under IAS 32 follows substance: an instrument is a financial liability if the issuer has a contractual obligation to deliver cash that it cannot avoid.",
      "The preference shares are redeemable at the holder's option, so Corvid cannot avoid redemption — they are a financial liability despite their legal form as shares.",
      "The 6% preference dividends are therefore presented as a finance cost in profit or loss, not as distributions in equity.",
      "The convertible bond is a compound instrument: it is split into a liability component and an equity component at issue.",
      "The liability component is the present value of the contractual cash flows discounted at the 8% rate for an equivalent bond without conversion rights.",
      "Annual interest is $10m × 4% = $400,000, so the liability = $400,000 × 2.577 + $10,000,000 × 0.794 = approximately $8,971,000.",
      "The equity component is the residual: $10,000,000 − $8,971,000 = approximately $1,029,000, credited to equity and not subsequently remeasured.",
      "The liability is then measured at amortised cost using the 8% effective rate — year-1 finance cost is approximately $8,971,000 × 8% = $718,000 against a $400,000 cash coupon, so the liability accretes towards $10m.",
      "The liability/equity split is not revised even if the likelihood of conversion changes.",
      "The classification matters to users: treating the convertible wholly as equity or debt would distort gearing and interest cover; on conversion or redemption the equity component remains within equity (transferred between reserves).",
    ],
  },
  {
    id: "SBR-W2-07",
    paper: "SBR",
    area: "E",
    topic: "Ethics — pressured change of estimate",
    stem: "The finance director of Bexley Retail Co is under pressure from the chief executive to extend the useful lives of the company's store fit-outs from five years to twelve, which would cut the depreciation charge enough to avoid breaching a profit-based loan covenant. The company's own engineers report that fit-outs are physically replaced every five to six years. Discuss the accounting and ethical issues, and the actions the finance director should take. (8 marks)",
    maxMarks: 8,
    rubric: [
      "Useful life is an accounting estimate: IAS 8 permits a change, applied prospectively, only where it reflects a genuine new expectation of the asset's consumption.",
      "The engineers' evidence of a five-to-six-year replacement cycle contradicts twelve years, so the change lacks justification and would understate depreciation and overstate profit and assets.",
      "The motive — avoiding a covenant breach — indicates management bias, so the financial statements would not be neutral or a faithful representation.",
      "The pressure threatens the fundamental principles of integrity and objectivity, and creates intimidation and self-interest threats for the finance director.",
      "Lenders relying on misleading covenant compliance would suffer real detriment, exposing the company and the director to legal, regulatory and disciplinary consequences.",
      "The director should first assemble the evidence (the engineers' reports and replacement history) and seek to persuade the chief executive on technical grounds.",
      "If pressure persists, escalate to the audit committee/those charged with governance, consult ACCA's ethics helpline or take legal advice, and document all steps taken.",
      "As a last resort the director must refuse to be associated with misleading financial statements, considering resignation if the matter cannot be resolved.",
    ],
  },
  {
    id: "SBR-W2-08",
    paper: "SBR",
    area: "C",
    topic: "IAS 21 — translating a foreign subsidiary",
    stem: "Danholt Group presents its consolidated financial statements in dollars and owns 80% of Vireo Co, whose functional currency is the local currency of the country in which it operates. Goodwill arose on the acquisition of Vireo. Explain how Vireo's financial statements, and the goodwill, are translated for consolidation, where the resulting exchange differences are recognised, and what happens to those differences if Vireo is later sold. (8 marks)",
    maxMarks: 8,
    rubric: [
      "Functional currency is the currency of the primary economic environment in which an entity operates, and is determined separately for each group entity.",
      "Vireo's assets and liabilities are translated at the closing rate at each reporting date.",
      "Its income and expenses are translated at the rates at the transaction dates (an average rate is used as a practical approximation).",
      "The resulting exchange differences are recognised in other comprehensive income and accumulated in a separate translation reserve in equity.",
      "The non-controlling interest is allocated its 20% share of those exchange differences.",
      "Goodwill on the acquisition is treated as an asset of the foreign operation, so it is expressed in Vireo's functional currency and retranslated at the closing rate each year.",
      "Exchange differences arising on the goodwill are likewise recognised in OCI.",
      "On disposal of Vireo, the cumulative exchange differences attributable to the group are reclassified from equity to profit or loss as part of the gain or loss on disposal.",
    ],
  },

  /* ───────────── SBL — Strategic Business Leader (4) ─────────────
   * Professional-skills marks are built into each rubric. */
  {
    id: "SBL-W2-01",
    paper: "SBL",
    area: "B",
    topic: "Evaluating a strategic option (SAF)",
    stem: "Merevale Coaches operates regional bus routes and enjoys a strong regional brand. Its fleet averages 11 years old, it holds cash reserves of $12m, and the country faces a national shortage of qualified drivers. The board proposes launching an app-based intercity coach service between the three largest cities, requiring 25 new luxury coaches costing $15m plus a booking app; the plan forecasts breakeven in year three. The intercity market is dominated by Zipline, which holds around 70% market share and competes aggressively on price, while rail fares have just risen 9%. Using the suitability, acceptability and feasibility framework, evaluate the proposal and recommend a course of action to the board. (10 marks)",
    maxMarks: 10,
    rubric: [
      "Suitability — environment: the 9% rail fare rise creates an opportunity, as price-sensitive intercity travellers may switch to cheaper coach travel.",
      "Suitability — capabilities: Merevale has coach-operating expertise, but its brand strength is regional and it has no intercity or app-platform experience, so the strategy stretches beyond current strengths.",
      "Suitability — competition: Zipline's ~70% share and aggressive pricing mean Merevale would enter as a weak challenger against an entrenched price leader.",
      "Acceptability — returns: breakeven only in year three defers returns, which must be tested against shareholders' risk and return expectations.",
      "Acceptability — risk: a price war with Zipline could extend losses well beyond the forecast, and the $15m commitment exceeds the $12m cash reserves.",
      "Acceptability — stakeholders: existing regional passengers and employees may object if capital is diverted from the aging 11-year-old regional fleet to the new venture.",
      "Feasibility — funding: the $15m coaches plus app development exceed the $12m cash, so debt or leasing is needed, adding financial risk.",
      "Feasibility — resources: the national driver shortage undermines the ability to crew 25 additional coaches, a practical constraint on the whole plan.",
      "A justified recommendation that follows from the analysis — e.g. a lower-commitment entry such as piloting one route with leased coaches before full launch, or deferring and renewing the regional fleet first.",
      "Professional skills — commercial acumen: the answer roots its judgements in the case facts (quantifying the $3m funding gap, citing Zipline's 70% share, the driver shortage and fleet age) rather than reciting generic theory.",
    ],
  },
  {
    id: "SBL-W2-02",
    paper: "SBL",
    area: "A",
    topic: "Governance reform ahead of a listing",
    stem: "Fennimore Foods is a family-owned company preparing for a stock exchange listing. The founder is both chairman and chief executive; the board comprises the founder, two of his siblings as executive directors, and one 'non-executive' who is a family friend and also the company's largest packaging supplier. There are no board committees, and the internal audit function reports to the chief executive. Recommend, with reasons, the corporate governance changes Fennimore should make before listing. (8 marks)",
    maxMarks: 8,
    rubric: [
      "The combined chairman/chief executive role concentrates power in one person; the roles should be split, with the chairman leading the board and the CEO running the business.",
      "The current 'non-executive' is not independent — the material supplier relationship (and friendship) creates a conflict of interest, so he cannot provide objective challenge.",
      "Recruit genuinely independent non-executive directors; for a listed company, typically at least half the board (excluding the chair) should be independent NEDs.",
      "Establish an audit committee of independent NEDs to oversee financial reporting, internal control and the external auditor relationship.",
      "Establish remuneration and nomination committees so the family executives do not set their own pay or control board appointments.",
      "Internal audit should report to the audit committee rather than the chief executive, protecting its independence from the executives whose work it reviews.",
      "Introduce formal board processes expected of a listed company: documented appointment and succession procedures, induction and board evaluation, and investor-facing reporting and disclosure readiness.",
      "Professional skills — commercial acumen: recommendations are tied to the case facts (the supplier conflict, family dominance, listing investors' expectations) and acknowledge the practical sensitivities of reforming a family board.",
    ],
  },
  {
    id: "SBL-W2-03",
    paper: "SBL",
    area: "C",
    topic: "Cyber risk — identification & TARA responses",
    stem: "Medbird is an online pharmacy that stores customers' health records and card details. Its website runs on a legacy platform that is difficult to patch, it shares delivery data with a courier through a third-party API, and staff routinely use personal devices for work. Last year an employee fell for a phishing email, and the data-protection regulator can fine up to 4% of turnover for breaches. Identify the principal cyber-related risks facing Medbird and recommend responses using the TARA framework. (10 marks)",
    maxMarks: 10,
    rubric: [
      "Risk: a breach of sensitive health and card data could trigger regulatory fines of up to 4% of turnover and a severe loss of customer trust.",
      "Risk: the hard-to-patch legacy platform leaves known vulnerabilities open to hacking or ransomware, threatening service outages, lost sales and potential patient harm.",
      "Risk: the third-party courier API is a supply-chain attack vector and puts customer data beyond Medbird's direct control.",
      "Risk: personal devices plus the previous successful phishing attack indicate high exposure to credential theft and malware entering the network.",
      "Reduce: invest in technical controls — replace or patch the legacy platform, encrypt data, enforce multi-factor authentication, and monitor the network for intrusions.",
      "Reduce: run regular staff security training and phishing simulations, and introduce a device policy (managed devices or a controlled BYOD regime).",
      "Transfer: purchase cyber insurance, and use a PCI-compliant third-party payment processor so Medbird no longer holds card details itself.",
      "Avoid: practise data minimisation — stop collecting or retaining data that is not needed — and exit or replace third parties that cannot meet contractual security standards (with audit rights).",
      "Accept: retain only low-likelihood, low-impact residual risks within a board-approved risk appetite, supported by a tested incident-response and breach-notification plan.",
      "Professional skills — commercial acumen: prioritises responses by likelihood and impact for a health retailer specifically (patient data, the regulator's 4% fine power) and weighs the cost of controls against the exposure.",
    ],
  },
  {
    id: "SBL-W2-04",
    paper: "SBL",
    area: "D",
    topic: "AI adoption — benefits, risks & change",
    stem: "Lanternshield Insurance plans to deploy an AI chatbot and automated triage in its claims department, where about 40% of claims are simple and rules-based. Call-centre staff fear job cuts, a previous IT system rollout failed largely because of poor training and communication, and the insurance regulator requires that claims decisions be explainable to customers. Discuss the potential benefits and risks of the proposal, and recommend how the board should manage the implementation. (8 marks)",
    maxMarks: 8,
    rubric: [
      "Benefit: automating the ~40% of simple, rules-based claims cuts handling cost and time and enables 24/7 customer service.",
      "Benefit: consistent triage generates data that can reveal fraud patterns and customer trends, while human handlers are freed to focus on complex, higher-value claims.",
      "Risk: model errors or bias in claim decisions could produce unfair outcomes, complaints, and breach of the regulator's explainability requirement.",
      "Risk: customer experience — vulnerable or less digital customers may struggle with a chatbot, damaging the brand at the emotionally sensitive moment of a claim.",
      "Risk: workforce resistance — staff fear of job cuts, echoing the previous failed IT rollout, threatens morale, cooperation and loss of claims expertise.",
      "Change management: communicate a clear vision early, involve claims staff in designing the system, and commit to retraining and redeployment rather than surprise redundancies.",
      "Implementation: pilot on one claim type, keep a human-in-the-loop for edge cases and appeals, and establish model monitoring and algorithm governance that satisfies the regulator's explainability demand.",
      "Professional skills — commercial acumen: weighs the efficiency gains against the regulatory and reputational realities of insurance, explicitly using the case facts (the 40% simple-claims figure, the prior IT failure, the explainability rule).",
    ],
  },

  /* ───────────── AA — Audit and Assurance (4) ─────────────
   * 16-mark-style questions (risks & responses; deficiencies &
   * recommendations), scaled to 12–14 marks. */
  {
    id: "AA-W2-01",
    paper: "AA",
    area: "B",
    topic: "Audit risks & auditor's responses — new client",
    stem: "Your firm has been appointed auditor of Glasshouse Gyms Co, a chain of fitness clubs, for the year ending 30 September 20X6 — the firm's first year on the engagement. Members pay annual fees in advance. During the year the company built a new flagship club, capitalising materials, contractor costs and a share of its own employees' labour. It has a bank loan carrying a covenant based on annual profit. Gym equipment is heavily used but the depreciation lives assigned at purchase have never been revisited. The finance director resigned two months before the year end and has not been replaced. Describe SIX audit risks arising from this scenario, and the auditor's response to each. (12 marks)",
    maxMarks: 12,
    rubric: [
      "Risk: as a first-year audit, the firm lacks cumulative knowledge of the entity and opening balances may be misstated, increasing detection risk.",
      "Response: perform procedures on opening balances per ISA 510 (including review of the predecessor auditor's work where possible) and invest additional time understanding the entity and its environment.",
      "Risk: annual membership fees received in advance may be recognised as revenue on receipt rather than spread over the membership period, overstating revenue and understating deferred income.",
      "Response: test the revenue recognition policy — for a sample of memberships, recalculate the deferred portion by reference to the period covered, and test cut-off around the year end.",
      "Risk: the self-constructed flagship club may include over-capitalised costs (e.g. general overheads, abnormal costs or excessive own-labour allocations), overstating property, plant and equipment.",
      "Response: vouch a sample of capitalised costs to invoices and timesheets and confirm each meets the IAS 16 directly-attributable criteria, reviewing the capitalised account for items that should be expensed.",
      "Risk: the profit-based loan covenant gives management an incentive to overstate profit, creating bias across judgements and estimates.",
      "Response: apply heightened professional scepticism to judgemental areas, review the covenant calculation and headroom, and consider the implications of any breach for loan classification and going concern.",
      "Risk: heavily used gym equipment with unrevisited useful lives may be depreciated too slowly, overstating assets and understating the depreciation charge (with possible impairment).",
      "Response: assess the reasonableness of useful lives against actual replacement cycles and physical inspection, recompute depreciation on a sample, and review board minutes for equipment replacement plans.",
      "Risk: the finance director's departure two months before the year end leaves the year-end close in inexperienced hands, increasing the risk of error and weakening the control environment.",
      "Response: enquire who prepared the financial statements and assess their competence, and increase substantive testing of year-end journals, estimates and post-close adjustments.",
    ],
  },
  {
    id: "AA-W2-02",
    paper: "AA",
    area: "C",
    topic: "Control deficiencies & recommendations — purchases & payroll",
    stem: "You are auditing Pinefold Furniture Co and have documented its purchases and payroll systems. The storekeeper both raises purchase orders and receives the goods when delivered. Purchase orders can be placed for any value without approval. Goods received notes are filed but never matched to supplier invoices before payment. In payroll, a production supervisor alone adds new joiners to the payroll and sets their pay rates, overtime is paid on the supervisor's verbal say-so, and the payroll bank transfer is prepared and authorised by the same accounts clerk. Identify and explain SIX deficiencies in internal control, and provide a recommendation to address each. (12 marks)",
    maxMarks: 12,
    rubric: [
      "Deficiency: the storekeeper both orders and receives goods — with no segregation of duties, goods could be ordered for personal use or receiving errors concealed.",
      "Recommendation: segregate ordering from receiving — an independent purchasing function should raise orders based on approved requisitions, with the storekeeper only confirming receipt.",
      "Deficiency: purchase orders have no authorisation limits, so the company could commit to unauthorised or excessive expenditure.",
      "Recommendation: introduce an authorisation matrix with value thresholds (orders above set limits approved by a manager or director), enforced within the ordering system.",
      "Deficiency: goods received notes are not matched to supplier invoices, so invoices could be paid for goods never received or for incorrect quantities or prices.",
      "Recommendation: require a three-way match of purchase order, GRN and invoice before an invoice is posted for payment, with mismatches investigated and cleared.",
      "Deficiency: the supervisor alone adds joiners and sets pay rates, enabling fictitious ('ghost') employees or inflated rates to go undetected.",
      "Recommendation: all starters, leavers and rate changes should be authorised by HR (independent of payroll processing) with documented approval, and a monthly edit report of payroll changes reviewed by a manager.",
      "Deficiency: overtime is paid on verbal approval only, so unauthorised or fictitious overtime may be paid.",
      "Recommendation: require written or system-based authorisation of overtime by the department manager before payment, with overtime reports reviewed against production schedules.",
      "Deficiency: the same clerk prepares and authorises the payroll bank transfer, so errors or fraudulent payments would not be detected before funds leave the bank.",
      "Recommendation: impose dual authorisation of bank transfers — a second, senior signatory should agree the payment file to the approved payroll summary before release.",
    ],
  },
  {
    id: "AA-W2-03",
    paper: "AA",
    area: "B",
    topic: "Audit risks & auditor's responses — food manufacturer",
    stem: "You are planning the audit of Saffron Foods Co, a food manufacturer, for the year ended 31 December 20X6. Inventory is held at several third-party warehouses. Shortly after the year end, one product line was recalled following contamination discovered in December production. Revenue is stated after volume rebates and settlement discounts granted to supermarket customers under annual agreements. A major customer is known to be in financial difficulty, and directors' bonuses are based on revenue. A new inventory system went live mid-year with data migrated from the old system, and the year-end inventory count was performed two weeks before the year end with movements rolled forward. Describe SEVEN audit risks arising from this scenario, and the auditor's response to each. (14 marks)",
    maxMarks: 14,
    rubric: [
      "Risk: inventory at third-party warehouses is difficult to verify for existence and condition, so inventory may be misstated.",
      "Response: attend counts at a sample of third-party sites and/or obtain direct confirmation from the custodians per ISA 501, considering any controls (service auditor) reports available.",
      "Risk: the recall relates to contamination in December production, so year-end inventory of that line may need writing down below cost (NRV) and a provision for recall costs and claims may be required — an adjusting-event risk.",
      "Response: establish whether the contamination condition existed at the year end, test NRV write-downs of the affected line, and review correspondence and legal advice to assess the completeness of any IAS 37 provision.",
      "Risk: supermarket rebates and settlement discounts are variable consideration — if under-accrued or misestimated, revenue is overstated.",
      "Response: inspect the rebate agreements, recalculate the year-end rebate accruals, review post-year-end credit notes, and challenge management's IFRS 15 variable-consideration estimates.",
      "Risk: the receivable from the major customer in financial difficulty may be irrecoverable, so receivables are overstated if the loss allowance is inadequate.",
      "Response: review post-year-end cash receipts from that customer, inspect correspondence and available credit information, and evaluate the adequacy of the specific allowance.",
      "Risk: revenue-based directors' bonuses create an incentive to overstate revenue through cut-off manipulation or fictitious sales.",
      "Response: treat revenue with heightened scepticism (ISA 240's presumed fraud risk in revenue recognition), test cut-off either side of the year end, and test unusual or manual revenue journals.",
      "Risk: the mid-year system change and data migration may have introduced errors into inventory quantities and costs, and the new system's controls are unproven.",
      "Response: test the migration reconciliation between the old system's closing and the new system's opening balances, and evaluate IT general and application controls or extend substantive testing of inventory records.",
      "Risk: the count was held two weeks before the year end, so errors in the roll-forward of movements could misstate year-end inventory.",
      "Response: test the roll-forward by tracing goods received notes and despatch records between the count date and the year end, and assess the reliability of the count procedures themselves.",
    ],
  },
  {
    id: "AA-W2-04",
    paper: "AA",
    area: "C",
    topic: "Control deficiencies & recommendations — cash sales",
    stem: "Cobble Lane Coffee Co operates 30 coffee shops taking a high volume of cash sales. Till takings are not reconciled to the point-of-sale records daily, and any reconciliation is done by the barista who operated the till. Cash is banked weekly and in the meantime is kept in an unlocked drawer in each store office. Any barista can process a refund without authorisation. Store managers count the cash alone, no one reviews till void transactions, and bank reconciliations are prepared quarterly and are not reviewed. Identify and explain SIX deficiencies in internal control over cash, and provide a recommendation to address each. (12 marks)",
    maxMarks: 12,
    rubric: [
      "Deficiency: till takings are not reconciled daily to point-of-sale records by an independent person, so misappropriation or till errors would go undetected.",
      "Recommendation: a person who did not operate the till (e.g. the duty manager) should reconcile cash to the till's end-of-day report every day, with differences logged and investigated.",
      "Deficiency: cash is banked only weekly and held in an unlocked drawer, exposing the company to theft and potentially uninsured losses.",
      "Recommendation: bank takings daily (or use a cash-collection service) and hold cash in a safe with restricted access, setting a maximum cash-holding policy aligned to insurance limits.",
      "Deficiency: any barista can process refunds without authorisation, so fictitious refunds could be used to extract cash from the till.",
      "Recommendation: refunds should require supervisor authorisation (e.g. a manager code at the till) with a documented reason, and a weekly refund report reviewed by the store manager or area manager.",
      "Deficiency: store managers count cash alone, so there is no dual control and counts could be manipulated or errors missed.",
      "Recommendation: cash counts should be performed by two people who both sign the count sheet, supplemented by unannounced head-office spot checks.",
      "Deficiency: till void transactions are not reviewed, so sales could be voided after the customer pays and the cash taken, concealing theft.",
      "Recommendation: voids should require supervisor approval at the till, and an exception report of voids by store and operator should be reviewed regularly by the area manager.",
      "Deficiency: bank reconciliations are only quarterly and unreviewed, so errors or fraud such as unbanked takings could remain undetected for months.",
      "Recommendation: prepare bank reconciliations monthly and promptly, have them independently reviewed and signed off, and age and clear reconciling items.",
    ],
  },
]
