import type { WrittenQuestion } from "@/lib/acca-written"

/*
 * Scholify — ACCA written (constructed-response) questions, wave 3: PM.
 *
 * PM (Performance Management, F5) Section C is two 20-mark constructed-response
 * questions that mix computation with discussion — and the discussion is where
 * marks are won and lost. These 15 questions attack that discursive half:
 * interpret, evaluate, advise, recommend. Every scenario, company, person and
 * figure below is INVENTED; all technical content is drawn from the public
 * syllabus only. No ACCA, Kaplan or BPP material is reproduced.
 * Each carries a rubric of marking points (~1 mark each) for the AI Examiner.
 */

export const WRITTEN_W3_PM: WrittenQuestion[] = [
  // ── Area A — Specialist cost & management accounting techniques (3) ──
  {
    id: "PM-W-01",
    paper: "PM",
    area: "A",
    topic: "Activity-based costing — evaluation",
    stem: "Hollibrand Instruments makes three ranges of laboratory equipment. Its oldest range is a high-volume standard sensor made in long runs; its newest is a low-volume bespoke analyser made in short batches, each needing its own machine set-up, a separate quality inspection and dedicated purchasing effort. Overheads (now 62% of total cost) are absorbed on direct labour hours, and the standard sensor absorbs the largest share because it uses the most labour hours in total. The board is puzzled that the bespoke analyser appears highly profitable yet the company's overall margin keeps falling, and the finance director has proposed introducing activity-based costing. Evaluate the case for adopting ABC at Hollibrand, explaining how it would change the reported profitability of the two ranges and identifying the limitations the board should weigh. (10 marks)",
    maxMarks: 10,
    rubric: [
      "Absorbing overheads on direct labour hours assumes overhead is driven by volume, which is untrue where overhead is dominated by set-ups, inspections and purchasing effort.",
      "ABC traces overhead to activities, identifies a cost driver for each activity cost pool and charges products for the drivers they actually consume.",
      "Set-up, inspection and purchasing costs are batch-level costs: they are incurred per batch regardless of how many units are in the batch, so a labour-hour rate spreads them wrongly.",
      "Under ABC the bespoke analyser would absorb far more overhead because it consumes many set-ups, inspections and purchase orders per unit produced.",
      "The high-volume standard sensor would absorb less overhead, so ABC would reveal that it has been cross-subsidising the bespoke range — explaining why apparent product profitability and the falling overall margin are inconsistent.",
      "Better cost information improves pricing: the bespoke analyser may be under-priced, and ABC gives management a defensible basis for repricing, redesigning or withdrawing it.",
      "ABC also supports cost management, because knowing the driver of a cost (e.g. the number of set-ups) tells management what to change to reduce it.",
      "Limitation: ABC is costly and time-consuming to implement and maintain — activities must be analysed, drivers chosen and data collected that the existing system does not capture.",
      "Limitation: choosing a single driver per pool is still a simplification, and some costs (e.g. facility-level costs such as rent) remain arbitrary to allocate under any system.",
      "Limitation: ABC changes reported costs but not cash spent — the benefit is realised only if managers act on the new information, and it may be resisted by those whose products now look unprofitable.",
    ],
  },
  {
    id: "PM-W-02",
    paper: "PM",
    area: "A",
    topic: "Target costing & lifecycle costing",
    stem: "Verstrand Audio is designing a wireless speaker for a crowded consumer market. Market research indicates a maximum achievable selling price of $80 and the board requires a margin of 25% of the selling price. The current design is estimated to cost $68 per unit to produce. The design director has suggested the gap could be closed 'by launching at $95 and dropping the price later'. Verstrand's engineers expect the product to have a three-year life, with substantial development, marketing and end-of-life recycling costs on top of production cost. Explain how target costing should be applied to this product, evaluate the design director's suggestion, and explain how lifecycle costing would improve the decision. (9 marks)",
    maxMarks: 9,
    rubric: [
      "Target costing starts from the price the market will bear, not from the cost the company happens to incur: target cost = market selling price less the required profit margin.",
      "Here the required margin is 25% of $80, so the target cost is $60 per unit and the cost gap is $68 − $60 = $8 per unit.",
      "The cost gap must be closed by re-engineering the product or the process — value analysis, design simplification, cheaper components, fewer parts, negotiating with suppliers or redesigning the assembly process.",
      "The design director's suggestion is invalid: the selling price is determined by the market and competitors, so launching above the achievable price would simply lose volume — the price is a given, not the variable.",
      "Target costing is most effective at the DESIGN stage, because 70–90% of a product's lifetime cost is committed once the design is fixed, even though it is spent later.",
      "Lifecycle costing widens the cost base from production cost alone to all costs over the product's life — development, marketing, production, customer support and end-of-life recycling.",
      "The lifecycle cost per unit is total lifetime costs divided by total lifetime units, which for a short three-year life could be materially higher than the $68 production cost.",
      "Using the lifecycle cost rather than production cost in the target-cost comparison gives a truer cost gap, and prevents a product being launched that appears profitable but never recovers its development and disposal costs.",
      "Lifecycle costing also supports pricing over time and shows that costs incurred early (design) are the cheapest place to remove cost, reinforcing the target-costing discipline.",
    ],
  },
  {
    id: "PM-W-03",
    paper: "PM",
    area: "A",
    topic: "Throughput accounting & the theory of constraints",
    stem: "Callow Forge produces three metal components, all of which must pass through a single heat-treatment furnace which is the factory's bottleneck. The management accountant has calculated a throughput accounting ratio (TPAR) for each component: Component R 1.6, Component S 1.1 and Component T 0.85. The production manager, whose bonus depends on machine utilisation, has responded by running the (non-bottleneck) cutting machines at full capacity to 'improve efficiency', and inventory of part-finished components has risen sharply. Interpret the three TPARs, and advise Callow Forge on the actions that would genuinely improve its throughput performance. (9 marks)",
    maxMarks: 9,
    rubric: [
      "Throughput is sales revenue less direct material cost — in the very short term only material is treated as a truly variable cost, and all labour and overhead are fixed factory costs.",
      "The TPAR is the return per bottleneck (factory) hour divided by the cost per bottleneck hour, so it compares the throughput a product earns from an hour of the constraint with what an hour of the constraint costs.",
      "A TPAR above 1 means the product earns more per bottleneck hour than the factory costs to run for that hour, so Components R (1.6) and S (1.1) are worth producing.",
      "Component T's TPAR of 0.85 is below 1: it destroys value, because each bottleneck hour spent on it fails to cover the factory cost of that hour.",
      "Priority on the furnace should be given to the highest TPAR first — R, then S — with T made only if bottleneck capacity is left over after profitable demand is met, or dropped, repriced or redesigned.",
      "The production manager's action is dysfunctional: running non-bottleneck machines at full capacity cannot increase throughput, because output is limited by the furnace.",
      "The only result is a build-up of work-in-progress inventory, which ties up cash, incurs holding cost and hides quality problems — a classic consequence of rewarding utilisation rather than throughput.",
      "The bonus scheme should be redesigned to reward throughput (or on-time output) rather than machine utilisation, so the measure and the company's interest agree.",
      "TPAR can be improved by increasing throughput per bottleneck hour (raise price, reduce material cost, reduce the bottleneck time per unit) or by reducing total factory operating costs — not by producing more elsewhere.",
      "Applying the theory of constraints, management should exploit and elevate the furnace (e.g. extra shifts, faster set-ups, outsourcing heat treatment, buying a second furnace), remembering that once elevated the constraint will move somewhere else.",
    ],
  },

  // ── Area B — Decision-making techniques (4) ──
  {
    id: "PM-W-04",
    paper: "PM",
    area: "B",
    topic: "Relevant costing — one-off contract",
    stem: "Ashdale Fabrication has been invited to quote for a one-off contract. Its cost clerk, Nadia Rowntree, has prepared a quote that includes: (i) $9,000 of market research already commissioned and paid for on the customer's sector; (ii) material P, of which the required quantity is already in inventory, was bought for $4,000, is used continuously on other jobs and would cost $5,200 to replace today; (iii) material Q, of which the required quantity is in inventory at a cost of $3,000, has no other use in the business and could be sold as scrap for $700; (iv) 400 hours of skilled labour, which is fully employed on other work earning a contribution of $18 per hour after a labour cost of $22 per hour; (v) an apportionment of head-office overhead at 40% of labour cost; and (vi) depreciation of the machine that would be used. Explain, with reasons, the correct relevant-cost treatment of EACH of these six items, and explain the principles that determine whether a cost is relevant to this decision. (10 marks)",
    maxMarks: 10,
    rubric: [
      "A cost is relevant only if it is a FUTURE, INCREMENTAL CASH FLOW arising as a direct consequence of the decision to accept the contract.",
      "The $9,000 of market research is a sunk cost — already spent and unaffected by the decision — so it is irrelevant and must be excluded entirely.",
      "Material P is in regular use, so accepting the contract means it must be replaced; the relevant cost is its replacement cost of $5,200, not the $4,000 historic cost.",
      "Material Q has no alternative use, so its relevant cost is the benefit forgone by consuming it — the $700 scrap proceeds — and its $3,000 historic cost is sunk and irrelevant.",
      "(If material Q had an alternative use in the business, the relevant cost would be the higher of its scrap value and the value in that alternative use.)",
      "Skilled labour is at full capacity, so the relevant cost is the cash cost of the hours (400 × $22 = $8,800) plus the contribution lost from the work displaced (400 × $18 = $7,200), a total of $16,000.",
      "This opportunity cost is real even though no extra invoice arises — if labour had spare capacity and was paid anyway, the relevant cost would be nil.",
      "The apportioned head-office overhead is not incremental — it is an existing cost re-labelled — so it is irrelevant; only any genuinely incremental fixed cost caused by the contract would be included.",
      "Depreciation is an accounting allocation, not a cash flow, so it is always irrelevant; the relevant machine cost would be any incremental cash cost such as extra running cost or contribution lost from displaced use.",
      "The quote should be built up as the sum of the relevant costs, which is the minimum price at which Ashdale is no worse off; the price actually charged should also consider the market, competition and the effect on future business.",
    ],
  },
  {
    id: "PM-W-05",
    paper: "PM",
    area: "B",
    topic: "Limiting factors & linear programming",
    stem: "Penmarric Ceramics makes two glazed tile ranges, Aurora and Basalt, both of which use the same two constrained resources: kiln hours and a specialist clay. A linear programming model of next quarter's plan has produced an optimal solution in which both constraints are binding, with a shadow price of $9 per kiln hour and $4 per kg of clay. The plant manager asks: 'Why would we ever pay more than the $6 we currently pay for a kiln hour?' and 'Our budget shows spare packing capacity — surely that has a shadow price too?' The board is also considering whether to rely on the model for the whole of next year. Explain what a shadow price is and what it means for each of the two binding constraints, answer the plant manager's two questions, and discuss the limitations of relying on linear programming here. (10 marks)",
    maxMarks: 10,
    rubric: [
      "A shadow price (dual price) is the increase in total contribution that would result from having ONE more unit of a scarce resource, with everything else held constant.",
      "It therefore represents the maximum PREMIUM above the normal purchase price that is worth paying to obtain one extra unit of that resource.",
      "The $9 shadow price on kiln hours means an extra kiln hour would add $9 of contribution, so Penmarric could pay up to $6 + $9 = $15 in total for one extra hour and still be no worse off.",
      "The plant manager's first question is answered by that logic: the $6 is the normal cost already reflected in contribution, whereas the shadow price measures the contribution forgone because the resource has run out.",
      "In answer to the second question, a non-binding (slack) resource such as packing capacity has a shadow price of NIL — obtaining more of a resource that is not fully used adds no contribution.",
      "Shadow prices only hold within a limited range: once enough extra resource is obtained, another constraint becomes binding and the shadow price changes, so they cannot be extrapolated indefinitely.",
      "Limitation: linear programming assumes linearity — that selling price, variable cost per unit and resource usage per unit are constant at all volumes — which fails if discounts must be given to sell more or bulk-buying reduces material cost.",
      "Limitation: the model assumes the input data (contributions, resource availability, usage rates, demand) are known with certainty, when in practice they are estimates that may change over a full year.",
      "Limitation: the solution may require fractional units, which is unrealistic for indivisible products, and it ignores qualitative factors such as customer relationships, product-range credibility and staff morale.",
      "Recommendation: use the model as a planning tool for the coming quarter, re-run it with updated data (and sensitivity analysis) rather than relying on a single annual solution, and use the shadow prices to guide negotiation for extra kiln capacity and clay.",
    ],
  },
  {
    id: "PM-W-06",
    paper: "PM",
    area: "B",
    topic: "Pricing strategy",
    stem: "Sennfield Devices is about to launch a genuinely novel home health monitor for which there is currently no direct competitor, although two large rivals are known to be developing similar products and could enter the market within about 18 months. Sennfield's finance team has priced the product at full cost plus a 30% mark-up. The marketing director objects, arguing the company should choose between 'skimming' and 'penetration' pricing instead. Discuss the weaknesses of the cost-plus approach in this situation, explain market skimming and market penetration pricing, and recommend, with reasons, which strategy Sennfield should adopt. (9 marks)",
    maxMarks: 9,
    rubric: [
      "Cost-plus pricing is simple and ensures a margin, but it is inward-looking: it ignores what customers are willing to pay and what competitors charge.",
      "Cost-plus is circular for a new product, because the full cost per unit depends on the volume absorbed, and the volume depends on the price being set.",
      "It also depends on an arbitrary overhead absorption basis, so an unreliable cost figure produces an unreliable price — and no mark-up guarantees demand at that price.",
      "Market skimming sets a high initial price to exploit the willingness to pay of innovators and early adopters, then reduces the price over time as the market broadens.",
      "Skimming suits a product that is novel, differentiated and hard to copy quickly, and it recovers development costs early — but it invites competitors in by signalling high margins, and needs demand that is relatively price-inelastic at launch.",
      "Market penetration sets a low initial price to win volume and market share quickly, deterring entrants and exploiting economies of scale and the experience/learning effect.",
      "Penetration suits price-elastic mass markets, but it sacrifices early margin, may be hard to raise the price later, and can signal low quality for a premium health product.",
      "Recommendation: skimming is the better fit — the product is genuinely novel with no direct competitor, early adopters of health technology are typically less price-sensitive, and Sennfield can recover its development costs before rivals arrive.",
      "The recommendation should be qualified: Sennfield must plan a deliberate price-reduction path as the 18-month competitive window closes, and should invest in brand, patents and switching costs so that the high early price does not simply hand the mass market to the rivals.",
    ],
  },
  {
    id: "PM-W-07",
    paper: "PM",
    area: "B",
    topic: "Risk & uncertainty in decision-making",
    stem: "Larkmoor Events must choose ONE of three formats for a single annual festival: a small indoor format, a medium marquee format or a large open-air format. The profit of each depends on the weather, and the management accountant has built a payoff table with three weather states (poor, average, good) and has attached subjective probabilities to each. The owner, Ivo Larkmoor, has told the board: 'The company cannot survive a large loss — this is a one-off event, not something we run a hundred times.' Explain how the expected value, maximax, maximin and minimax regret criteria would each be applied to this payoff table, explain what each reveals about the decision-maker's attitude to risk, and advise which criterion is most appropriate for Larkmoor. (9 marks)",
    maxMarks: 9,
    rubric: [
      "Expected value multiplies each possible payoff by the probability of its weather state and sums them for each format, and the format with the highest EV is chosen.",
      "EV assumes the decision-maker is risk-NEUTRAL and, critically, that the decision is repeated many times so that the average outcome is actually achieved.",
      "EV also depends entirely on the reliability of the probabilities, which here are subjective estimates of the weather, and the EV itself may be a payoff that can never actually occur.",
      "Maximax selects the format with the highest possible payoff of all (the best of the best), reflecting an optimistic, risk-seeking decision-maker who ignores the downside.",
      "Maximin identifies the WORST payoff for each format and selects the format whose worst outcome is the best, reflecting a pessimistic, risk-averse decision-maker.",
      "Minimax regret first builds a regret (opportunity loss) table — for each weather state, the difference between the best payoff available in that state and the payoff of the chosen format — then selects the format with the lowest maximum regret.",
      "Minimax regret reflects a decision-maker who wants to avoid the pain of having made the wrong choice with hindsight, rather than one focused on the payoffs themselves.",
      "Because the festival is a genuine ONE-OFF, the long-run averaging that justifies expected value does not apply, so EV is a weak basis here.",
      "As Ivo has stated the company cannot survive a large loss, he is clearly risk-averse, so the maximin criterion (protecting against the worst outcome) is the most appropriate.",
      "Advice: use maximin as the primary criterion but present the full payoff table with sensitivity analysis, since no single criterion captures qualitative factors such as reputation, cancellation insurance or the option to reduce the downside by hiring the marquee on flexible terms.",
    ],
  },

  // ── Area C — Budgeting & control (4) ──
  {
    id: "PM-W-08",
    paper: "PM",
    area: "C",
    topic: "Budgeting systems — incremental vs ZBB",
    stem: "Threlkeld Housing Trust prepares its annual budget by taking last year's figures for each department and adding an inflation uplift. The new finance director has discovered that one department has for six years been budgeting for a mail-room function that is now barely used, and that departments routinely spend their full budget in the final month 'so it isn't cut next year'. She proposes replacing incremental budgeting with zero-based budgeting (ZBB) across all support departments. Explain the weaknesses of incremental budgeting that this scenario illustrates, describe how ZBB would operate at the Trust, and evaluate whether ZBB is an appropriate choice for it. (9 marks)",
    maxMarks: 9,
    rubric: [
      "Incremental budgeting takes the previous period's budget as the starting point and adjusts it, typically for inflation and known changes.",
      "Its central weakness is that it perpetuates past inefficiency: the redundant mail-room function has been funded for six years simply because it was in last year's budget and was never re-justified.",
      "It also encourages budget 'padding' and end-of-year spending sprees, because managers fear that any underspend will cut next year's allocation — exactly the behaviour observed at the Trust.",
      "Incremental budgeting is backward-looking and provides no incentive to find better ways of delivering an activity, so budgetary slack accumulates.",
      "Under ZBB every activity starts from a base of zero and must be justified afresh: managers prepare decision packages describing the activity, its cost, its benefits and the consequences of not doing it.",
      "Alternative levels of provision (and alternative ways of delivering the activity) are considered, and the decision packages are then ranked so that resources are allocated to the highest-value activities within the funds available.",
      "ZBB suits the Trust because its support departments are discretionary, service-type functions whose cost/benefit is judgemental — precisely where ZBB adds most value, and where a redundant mail room would be exposed immediately.",
      "As a not-for-profit trust with limited funds, ZBB helps demonstrate value for money to funders and directs scarce resources to activities that serve the objectives.",
      "Against this: ZBB is very time-consuming and costly in management time, needs skills managers may not have, and the ranking of decision packages is subjective and can become political.",
      "Recommendation: adopt ZBB but apply it selectively — for example on a rolling basis, covering a proportion of support departments each year — so the benefits are obtained without the full annual cost of the exercise.",
    ],
  },
  {
    id: "PM-W-09",
    paper: "PM",
    area: "C",
    topic: "Flexed budgets, rolling budgets & behavioural effects",
    stem: "Corvane Logistics sets a fixed annual budget each December and reports performance monthly by comparing actual results against that budget. This year, demand was far higher than planned, and the operations manager, Dermot Fay, received a control report showing a large adverse total cost variance and no bonus; he has complained that the report is 'meaningless' and that the targets, which were imposed on him by head office without discussion, are 'a fantasy in a market that changes every quarter'. Explain why the control report as prepared is not a fair basis for assessing Dermot's performance, explain how a rolling budget would help Corvane, and discuss the behavioural consequences of the way its budgets are currently set. (10 marks)",
    maxMarks: 10,
    rubric: [
      "Comparing actual costs at a HIGHER activity level against a budget prepared for a lower activity level compares unlike with unlike — some of the extra cost is simply the cost of doing more work.",
      "The budget must first be FLEXED: variable costs are restated at the actual level of activity, while fixed costs remain unchanged.",
      "Only after flexing does the remaining difference isolate genuine price and efficiency performance, which is what Dermot can actually be held responsible for.",
      "The difference between the original budget and the flexed budget is a volume effect, which for a logistics operation responding to customer demand is largely outside the operations manager's control.",
      "A rolling (continuous) budget is updated regularly — for example, as each quarter ends a new quarter is added, so a full twelve-month budget is always in place.",
      "Rolling budgets suit Corvane because its market changes every quarter: the budget is continuously revised for the latest conditions, so targets remain realistic and relevant rather than being based on assumptions made twelve months earlier.",
      "The main drawbacks are the extra time and cost of re-budgeting frequently, and the risk that a constantly moving target undermines the budget's value as a fixed benchmark for accountability.",
      "Behaviourally, targets imposed top-down without consultation give managers no ownership, are seen as unfair, and demotivate — exactly the reaction Dermot has had.",
      "Participative (bottom-up) budgeting improves acceptance, motivation and the quality of the estimates because operational managers have better information, though it risks managers building in budgetary slack to make targets easy to beat.",
      "Linking a bonus to a variance the manager did not cause damages motivation and can drive dysfunctional behaviour (e.g. refusing profitable extra work to protect the cost variance); performance should be assessed against a flexed, realistic budget with controllable items separated from uncontrollable ones.",
    ],
  },
  {
    id: "PM-W-10",
    paper: "PM",
    area: "C",
    topic: "Materials mix & yield variances",
    stem: "Aldergrove Feeds blends three ingredients into an animal feed. The ingredients are substitutable within limits, and the standard mix is fixed by the technical department. In the last quarter, the production supervisor bought a cheaper protein ingredient and increased its proportion in the blend. The quarter's variances were: materials price $28,000 favourable, materials mix $19,000 favourable, materials yield $31,000 adverse. Sales volume was also below budget, and the sales director reports a rise in customer complaints about product quality. Explain what the mix and yield variances measure and what causes them, interpret these three variances together as a single story, and recommend the action Aldergrove should take. (10 marks)",
    maxMarks: 10,
    rubric: [
      "The materials usage variance can be split into mix and yield only where the inputs are substitutable, as they are in a blending operation like Aldergrove's.",
      "The mix variance measures the effect on cost of using the inputs in proportions DIFFERENT from the standard mix, valuing the difference at standard prices.",
      "A favourable mix variance arises when a greater proportion of the cheaper input (and less of the more expensive input) is used than the standard mix specifies.",
      "The yield variance measures whether the total quantity of input used produced more or less OUTPUT than the standard says it should have — it is about the productivity of the materials as a whole.",
      "An adverse yield variance means the input consumed produced less output than standard: more raw material was needed per unit of finished feed, i.e. waste or loss increased.",
      "Reading the three variances together tells one story: buying a cheaper protein ingredient produced the favourable price variance, and using more of it produced the favourable mix variance.",
      "But the cheaper, lower-quality ingredient blended badly, so the yield fell — the $31,000 adverse yield variance more than wipes out the $19,000 favourable mix variance.",
      "The net effect on materials is still favourable overall ($28,000 + $19,000 − $31,000 = $16,000 favourable), which shows why the variances must never be evaluated in isolation: an apparent saving in one place caused a larger loss in another.",
      "The consequences extend beyond materials: the quality complaints and the shortfall in sales volume suggest the cheaper blend has damaged the product, so the true cost includes lost contribution and reputational damage not captured in any materials variance.",
      "Recommendation: revert to the technically specified mix (or have the technical department re-approve any change before it is made), hold the supervisor accountable for a decision taken outside their authority, and reform any incentive that rewards purchase price savings without regard to yield and quality.",
    ],
  },
  {
    id: "PM-W-11",
    paper: "PM",
    area: "C",
    topic: "Learning curves & planning vs operational variances",
    stem: "Marrowdene Marine began building a new class of small patrol boat this year. The standard labour time was set at the time taken to build the first boat, and no allowance was made for a learning effect, even though the workforce was known to be new to the design and a steady state would not be reached for many boats. The first control report shows a very large FAVOURABLE labour efficiency variance, and the production manager has claimed a bonus for 'exceptional productivity'. The finance director wants to reanalyse the variance into planning and operational elements. Explain how the learning effect should have been reflected in the standard, explain how splitting the variance into planning and operational elements would change the picture, and discuss the risks of allowing standards to be revised in this way. (10 marks)",
    maxMarks: 10,
    rubric: [
      "The learning curve effect means the cumulative average time per unit falls by a constant percentage each time cumulative output DOUBLES, as workers become more familiar with a repetitive new task.",
      "The standard time should therefore have been based on the expected cumulative average time over the planned output, derived from the learning curve, not on the time taken for the first unit.",
      "Because the standard ignored learning, it was far too generous, and workers beat it simply by learning — the favourable efficiency variance is an artefact of a wrong standard, not of exceptional performance.",
      "A planning variance measures the difference between the ORIGINAL standard and a revised (ex-post) standard that reflects what the standard should realistically have been.",
      "An operational variance measures the difference between that revised standard and the ACTUAL result, and is the part that the manager could genuinely influence.",
      "Reanalysing here would show a large favourable PLANNING variance (the standard-setting error in ignoring learning) and a much smaller — possibly adverse — operational variance.",
      "Responsibility follows the split: the planning variance belongs to whoever set the standard, and only the operational variance is a fair basis for judging the production manager or paying a bonus.",
      "Rewarding the manager for the total favourable variance would pay a bonus for a budgeting error, damaging the credibility of the whole standard-costing system.",
      "The learning effect also ends once the steady state is reached, so the standard must be updated again at that point or later variances will be misleading in the opposite direction.",
      "Risk: revising standards ex post is open to manipulation — a manager may reclassify a genuine operational failure as a 'planning' error to escape blame — so revisions must be genuinely uncontrollable, evidenced, and authorised independently of the manager being assessed.",
    ],
  },

  // ── Area D — Performance measurement & control (4) ──
  {
    id: "PM-W-12",
    paper: "PM",
    area: "D",
    topic: "ROI, residual income & EVA",
    stem: "Quillane Group has two investment centres. The Northgate division is mature, with old, heavily depreciated assets and a current ROI of 26%. The Seaton division is newly established with modern assets and a current ROI of 11%. The group's cost of capital is 13%, and divisional managers' bonuses depend on their division's ROI. Northgate's manager has just rejected an upgrade project expected to earn an ROI of 18%; Seaton's manager has accepted a project expected to earn 12%. The group finance director is considering replacing ROI with residual income (RI), and has also been advised to look at economic value added (EVA). Evaluate the behaviour of the two managers, explain how RI would change the decisions, and explain how EVA differs from RI. (10 marks)",
    maxMarks: 10,
    rubric: [
      "ROI expresses divisional profit as a percentage of divisional capital employed, which allows divisions of different sizes to be compared.",
      "Northgate's manager rejected a project earning 18% because accepting it would DILUTE the division's current ROI of 26% and reduce their bonus — even though 18% comfortably exceeds the group's 13% cost of capital.",
      "This is sub-optimal (dysfunctional) decision-making: a value-creating project was rejected because the performance measure, not the company's interest, drove the decision.",
      "Conversely, Seaton's manager accepted a project earning 12%, which is BELOW the 13% cost of capital and therefore destroys value, because it still raises the division's ROI of 11% and hence the bonus.",
      "Northgate's high ROI is also flattered by its old, heavily depreciated assets: accumulated depreciation shrinks the capital employed denominator, so ROI rises with asset age and discourages reinvestment and replacement.",
      "Residual income is divisional profit less a notional interest charge on the capital employed at the cost of capital, so it is an absolute money amount rather than a percentage.",
      "Under RI, any project earning MORE than the cost of capital produces a positive RI and increases the division's measure, so Northgate's manager would accept the 18% project — RI is goal-congruent.",
      "Equally, Seaton's 12% project produces a NEGATIVE residual income and would be rejected under RI, which is the correct decision for the group.",
      "RI's own weakness is that, as an absolute figure, it does not allow direct comparison between divisions of very different sizes, and it is sensitive to the cost of capital chosen.",
      "EVA is a refinement of RI: it uses an economic profit derived by adjusting accounting profit (for example adding back and capitalising expenditure with long-term benefit such as research or advertising, and using cash-based rather than accounting figures), and charges the WACC on the adjusted economic capital — reducing the short-termism that RI based on accounting profit can still encourage.",
    ],
  },
  {
    id: "PM-W-13",
    paper: "PM",
    area: "D",
    topic: "Transfer pricing",
    stem: "Brackmoor Industries has two profit centres. The Components division makes a valve with a variable cost of $30 per unit and sells it externally at $50; it currently has substantial spare capacity. The Assembly division needs the same valve and can buy an equivalent one from an outside supplier for $46. Head office has instructed Components to transfer internally at 'full cost plus 40%', which works out at $56 per valve. Assembly's manager, whose bonus depends on divisional profit, is refusing to buy internally and is placing orders with the outside supplier instead. Explain why the current transfer price is causing a decision that harms the group, determine and explain the range of transfer prices that would be acceptable to both divisions, and advise Brackmoor on how to set the price. (10 marks)",
    maxMarks: 10,
    rubric: [
      "A transfer price should promote goal congruence: it should lead divisional managers, acting in their own interest, to take the decision that is best for the group as a whole.",
      "At $56 the transfer price exceeds the $46 external price, so Assembly's manager rationally buys outside — but this decision is wrong for the group.",
      "From the group's point of view, buying externally costs $46 of real cash outflow, whereas making internally costs only the $30 variable cost, because Components has spare capacity and the fixed costs are incurred anyway.",
      "The group therefore loses $16 per valve on every unit Assembly buys outside — a clear example of a transfer price causing dysfunctional behaviour.",
      "The MINIMUM transfer price acceptable to the selling division is its marginal cost plus any contribution forgone on external sales displaced by the transfer.",
      "Because Components has spare capacity, no external sales are displaced, so no contribution is lost and the minimum acceptable price is simply the $30 marginal cost.",
      "The MAXIMUM the buying division will pay is the lower of the external market price and the net revenue it can earn from the item — here the $46 external purchase price.",
      "The acceptable range is therefore $30 to $46: any price within this range makes BOTH divisions better off trading internally, and the group better off by $16 per unit in total, with the split of that benefit determined by where in the range the price is set.",
      "The head-office rule of full cost plus 40% is inappropriate: full cost includes fixed overhead that is not incremental when spare capacity exists, so the mark-up is applied to a cost the group does not actually incur.",
      "Advice: set the price by negotiation within the $30–$46 range (or at marginal cost plus a fixed periodic lump sum so that Components still shows a profit), and if spare capacity later disappears the floor must rise to marginal cost plus the contribution lost on displaced external sales.",
    ],
  },
  {
    id: "PM-W-14",
    paper: "PM",
    area: "D",
    topic: "Non-financial measures & the balanced scorecard",
    stem: "Vantry & Cole is a professional design consultancy whose partners are assessed solely on chargeable hours billed and fee income. Utilisation has risen for three years, yet client retention has fallen, two senior designers have resigned citing burnout, and the firm has launched no new service line since 2023. A new managing partner proposes measuring performance using a balanced scorecard, and has been told that Fitzgerald and Moon's building block model was designed specifically for service businesses like theirs. Explain why relying solely on financial measures is failing Vantry & Cole, describe the four perspectives of the balanced scorecard with a suitable measure for each in this firm, and explain how the building block model would add to the scorecard. (10 marks)",
    maxMarks: 10,
    rubric: [
      "Financial measures such as fee income are backward-looking: they report the outcome of past decisions and give no warning of the causes of future decline.",
      "Financial measures are also easy to manipulate in the short term — partners can maximise billed hours by over-servicing existing clients while neglecting client relationships, staff development and innovation.",
      "The symptoms at Vantry & Cole (falling retention, burnout, no new services) are exactly the long-term damage a single short-term financial measure encourages, because what is not measured is not managed.",
      "Balanced scorecard — financial perspective: how do we look to shareholders/partners? A suitable measure is fee income growth or profit per partner.",
      "Balanced scorecard — customer perspective: how do customers see us? A suitable measure is the client retention rate or a client satisfaction score.",
      "Balanced scorecard — internal business process perspective: what must we excel at? A suitable measure is projects delivered on time and on budget, or the rate of reworked designs.",
      "Balanced scorecard — learning and growth perspective: can we continue to improve and create value? A suitable measure is staff turnover, training hours per employee, or the proportion of fees from services launched in the last two years.",
      "The scorecard's power is the causal chain between perspectives: investment in staff (learning and growth) improves processes, which improves client satisfaction, which ultimately drives financial results — so the perspectives must not be treated as four unrelated lists.",
      "Fitzgerald and Moon's building block model splits performance measures into DIMENSIONS (results: financial performance and competitiveness; determinants: quality, flexibility, resource utilisation and innovation), recognising that the determinants drive the results.",
      "It adds two further building blocks the scorecard does not address: STANDARDS (targets must have ownership, be achievable and be equitable between managers) and REWARDS (the reward scheme must be clear, motivating and based on controllable factors) — directly relevant to a firm whose reward scheme currently drives burnout.",
    ],
  },
  {
    id: "PM-W-15",
    paper: "PM",
    area: "D",
    topic: "Performance measurement in not-for-profit organisations",
    stem: "The Harrowfield Literacy Foundation is a charity funded by government grants and donations. It runs free reading classes for adults. Its trustees currently report only two figures: total expenditure and the number of classes delivered. A trustee has suggested the Foundation 'simply measure profit like a business'. The chief executive wants instead to report on value for money and to introduce measures of the Foundation's real impact. Explain why conventional profit-based performance measurement is inappropriate for the Foundation, explain how the value for money framework (the three Es) would be applied here with an example measure for each, and discuss the difficulties the Foundation will face in measuring its performance. (10 marks)",
    maxMarks: 10,
    rubric: [
      "A not-for-profit organisation does not exist to make a profit, so profit is not a measure of its success — the Foundation's objective is improved adult literacy, not a financial return.",
      "Its outputs (literacy gained) have no market price, and its income comes from grants and donations rather than from customers paying for the service, so a profit figure would be meaningless.",
      "Reporting only expenditure and classes delivered measures inputs and activity, not whether anything was achieved — a charity could deliver many classes that teach nobody to read.",
      "Value for money is therefore assessed through the three Es: economy, efficiency and effectiveness.",
      "ECONOMY is obtaining the required inputs at the lowest cost consistent with quality — for example, the average cost of hiring a classroom, or the cost per tutor hour compared with the market rate.",
      "EFFICIENCY is the relationship between inputs and outputs, i.e. output per unit of input — for example, the cost per learner enrolled, or the number of learners taught per tutor hour.",
      "EFFECTIVENESS is the extent to which the organisation achieves its objectives — for example, the proportion of learners who reach a defined reading standard, or who go on to employment or further study.",
      "Effectiveness is the most important of the three for the Foundation but also the hardest to measure, because the objective (improved literacy and its life effects) is qualitative and long-term.",
      "There is a real risk of conflict between the Es: driving down cost per learner (economy and efficiency) by using larger classes or cheaper tutors could reduce the proportion of learners who actually learn to read (effectiveness).",
      "Further difficulties: the Foundation has multiple stakeholders (funders, government, learners, donors) with different and sometimes conflicting objectives, outcomes are influenced by external factors outside its control, there is no market benchmark to compare against, and short-term measurable proxies may crowd out the long-term social impact that actually matters.",
    ],
  },
]
