import type { Flashcard } from "@/lib/acca-flashcards"

/*
 * Scholify — ACCA flashcards wave S3.
 *
 * ATX (Advanced Taxation, UK) and AAA (Advanced Audit & Assurance) memorisation
 * cards. ATX figures use UK Finance Act 2024 (FA2024/25). Cards are original and
 * syllabus-aligned; no verbatim ACCA/Kaplan/BPP text.
 */

export const FLASHCARDS_S3: Flashcard[] = [
  /* ===== ATX — Area A: Income tax & NIC advanced ===== */
  { id: "ATX-FC-01", paper: "ATX", area: "A", front: "Personal allowance & its taper (FA2024/25)", back: "PA is £12,570. Reduced by £1 for every £2 of adjusted net income above £100,000, so fully lost at £125,140." },
  { id: "ATX-FC-02", paper: "ATX", area: "A", front: "Income tax bands (non-savings, non-dividend, FA2024/25)", back: "Basic rate 20% to £37,700; higher rate 40% to £125,140; additional rate 45% above £125,140." },
  { id: "ATX-FC-03", paper: "ATX", area: "A", front: "Dividend allowance & dividend rates (FA2024/25)", back: "Dividend nil-rate band £500. Above it: 8.75% (basic), 33.75% (higher), 39.35% (additional)." },
  { id: "ATX-FC-04", paper: "ATX", area: "A", front: "Personal savings allowance (FA2024/25)", back: "£1,000 for basic-rate taxpayers, £500 for higher-rate, £0 for additional-rate. Starting rate band of £5,000 taxed at 0% where non-savings income is low." },
  { id: "ATX-FC-05", paper: "ATX", area: "A", front: "Class 1 employee NIC rates (FA2024/25)", back: "8% between the primary threshold (£12,570) and upper earnings limit (£50,270); 2% above the UEL." },
  { id: "ATX-FC-06", paper: "ATX", area: "A", front: "Class 1 employer (secondary) NIC (FA2024/25)", back: "13.8% on earnings above the secondary threshold of £9,100. Employment allowance of up to £5,000 may reduce the bill." },
  { id: "ATX-FC-07", paper: "ATX", area: "A", front: "Class 4 self-employed NIC (FA2024/25)", back: "6% on profits between £12,570 and £50,270; 2% above £50,270. Class 2 has effectively been removed but voluntary contributions preserve benefit entitlement." },
  { id: "ATX-FC-08", paper: "ATX", area: "A", front: "Pension annual allowance & taper (FA2024/25)", back: "Annual allowance £60,000, tapered by £1 for every £2 of adjusted income over £260,000, down to a minimum of £10,000. Unused allowance can be carried forward 3 years." },
  { id: "ATX-FC-09", paper: "ATX", area: "A", front: "Remittance basis charge for non-domiciled individuals", back: "£30,000 once UK-resident for 7 of the previous 9 tax years; £60,000 once resident for 12 of the previous 14 years. Automatic (no charge) if unremitted foreign income is under £2,000." },
  { id: "ATX-FC-10", paper: "ATX", area: "A", front: "Statutory residence test — automatic UK resident", back: "Resident if present 183+ days in the UK in the tax year, or the only home is in the UK, or full-time work in the UK. Otherwise apply automatic overseas tests, then the sufficient-ties test." },
  { id: "ATX-FC-11", paper: "ATX", area: "A", front: "Company car benefit — the calculation", back: "List price × CO2-based percentage (max 37%). Fuel benefit = £27,800 × the same percentage. Electric cars carry a 2% appropriate percentage in 2024/25." },
  { id: "ATX-FC-12", paper: "ATX", area: "A", front: "EIS & SEIS income tax relief (FA2024/25)", back: "EIS: 30% relief on up to £1m (or £2m if knowledge-intensive). SEIS: 50% relief on up to £200,000. Shares must be held 3 years; gains on disposal are exempt." },

  /* ===== ATX — Area B: Chargeable gains & IHT advanced ===== */
  { id: "ATX-FC-13", paper: "ATX", area: "B", front: "CGT annual exempt amount & main rates (FA2024/25)", back: "AEA £3,000. Rates: 10%/20% on most assets (basic/higher); residential property 18%/24%. BADR and Investors' Relief gains at 10%." },
  { id: "ATX-FC-14", paper: "ATX", area: "B", front: "BADR — rate and lifetime limit (FA2024/25)", back: "10% on qualifying gains, £1,000,000 lifetime limit; 2-year qualifying ownership of a trading business or 5%+ personal trading company." },
  { id: "ATX-FC-15", paper: "ATX", area: "B", front: "Investors' Relief — rate and limit", back: "10% on qualifying gains, separate £1,000,000 lifetime limit; newly-subscribed unlisted trading company shares held 3+ years by a non-employee." },
  { id: "ATX-FC-16", paper: "ATX", area: "B", front: "Gift holdover relief (s.165 / s.260)", back: "Defers the gain by reducing the donee's base cost. Available on gifts of business assets, unlisted trading shares, or any transfer immediately chargeable to IHT." },
  { id: "ATX-FC-17", paper: "ATX", area: "B", front: "Rollover (replacement of business assets) relief", back: "Gain on a disposed qualifying business asset is deferred against the cost of a replacement bought within 1 year before to 3 years after. Full deferral only if all proceeds reinvested." },
  { id: "ATX-FC-18", paper: "ATX", area: "B", front: "IHT nil rate band & residence nil rate band (FA2024/25)", back: "NRB £325,000; RNRB £175,000 for a home passing to direct descendants, tapered £1 for every £2 of estate over £2m." },
  { id: "ATX-FC-19", paper: "ATX", area: "B", front: "IHT rates on death", back: "40% on the estate above available nil bands; reduced to 36% if 10%+ of the net estate is left to charity. Lifetime chargeable transfers taxed at 20% (grossing up) when made." },
  { id: "ATX-FC-20", paper: "ATX", area: "B", front: "IHT taper relief on lifetime gifts", back: "Applies to tax on gifts made 3-7 years before death: 3-4 yrs 20%, 4-5 yrs 40%, 5-6 yrs 60%, 6-7 yrs 80% reduction. Only reduces tax, never the transfer value." },
  { id: "ATX-FC-21", paper: "ATX", area: "B", front: "IHT — the annual exemption and small gifts", back: "Annual exemption £3,000 per donor (one year's unused amount can be carried forward). Small gifts exemption £250 per recipient per year." },
  { id: "ATX-FC-22", paper: "ATX", area: "B", front: "Business Property Relief (BPR) rates", back: "100% on an unincorporated business or unquoted trading company shares; 50% on quoted controlling holdings and certain business assets. Two-year ownership required." },
  { id: "ATX-FC-23", paper: "ATX", area: "B", front: "IHT — transfer of unused nil rate band", back: "A surviving spouse/civil partner can claim the unused percentage of the first deceased's NRB and RNRB, potentially doubling the bands." },
  { id: "ATX-FC-24", paper: "ATX", area: "B", front: "Principal private residence (PPR) relief — final period", back: "The last 9 months of ownership are always exempt if the property was the main residence at some point. Letting relief now only applies to periods of shared occupation with the owner." },

  /* ===== ATX — Area C: Corporation tax advanced ===== */
  { id: "ATX-FC-25", paper: "ATX", area: "C", front: "Corporation tax rates & marginal relief (FA2024/25)", back: "Main rate 25% (profits over £250,000); small profits rate 19% (up to £50,000); marginal relief between, standard fraction 3/200." },
  { id: "ATX-FC-26", paper: "ATX", area: "C", front: "Marginal relief limits with associated companies", back: "The £50,000 and £250,000 limits are divided by the number of associated companies (including the company itself) and time-apportioned for short periods." },
  { id: "ATX-FC-27", paper: "ATX", area: "C", front: "Capital allowances — AIA & full expensing (FA2024/25)", back: "Annual Investment Allowance 100% on up to £1m of plant. Full expensing gives 100% first-year relief on new main-pool plant for companies; 50% FYA on special-rate additions." },
  { id: "ATX-FC-28", paper: "ATX", area: "C", front: "Writing down allowances — the pools", back: "Main pool 18% reducing balance; special rate pool (long-life, integral features, high-emission cars) 6% reducing balance." },
  { id: "ATX-FC-29", paper: "ATX", area: "C", front: "Group relief — the 75% test", back: "Trading losses can be surrendered where one company owns 75%+ of the other, or both are 75% subsidiaries of a common parent, based on ordinary share capital, profits and assets." },
  { id: "ATX-FC-30", paper: "ATX", area: "C", front: "Capital gains group — the definition", back: "A 75% effective and 50%+ direct chain relationship. Assets transfer at no gain/no loss; a s.171A election can reallocate gains and losses within the group." },
  { id: "ATX-FC-31", paper: "ATX", area: "C", front: "Substantial shareholding exemption (SSE)", back: "Gain on disposal of shares is exempt where a trading company/group held 10%+ of a trading company for 12 continuous months in the prior 6 years." },
  { id: "ATX-FC-32", paper: "ATX", area: "C", front: "Corporate loss relief — carry forward (post-2017)", back: "Trading losses carried forward can be set against total profits, subject to the £5m deductions allowance plus 50% of profits above it (the loss restriction)." },
  { id: "ATX-FC-33", paper: "ATX", area: "C", front: "R&D expenditure credit / SME merged scheme (FA2024/25)", back: "The merged RDEC scheme gives a taxable above-the-line credit of 20%. Loss-making R&D-intensive SMEs (qualifying R&D 30%+ of costs) get enhanced support." },
  { id: "ATX-FC-34", paper: "ATX", area: "C", front: "Corporate interest restriction (CIR)", back: "Net tax-interest deductions restricted to 30% of tax-EBITDA (fixed ratio), subject to a £2m de minimis. A group ratio method may permit more." },
  { id: "ATX-FC-35", paper: "ATX", area: "C", front: "Close company — loan to participator (s.455)", back: "A 33.75% tax charge on a loan to a participator, payable with the CT but refunded when the loan is repaid or written off. Write-off is taxed as a distribution on the participator." },
  { id: "ATX-FC-36", paper: "ATX", area: "C", front: "Corporation tax — payment dates", back: "Small companies: 9 months and 1 day after the period end. Large companies (profits over £1.5m): quarterly instalments; very large companies (over £20m) pay earlier instalments." },

  /* ===== ATX — Area D: VAT & stamp taxes ===== */
  { id: "ATX-FC-37", paper: "ATX", area: "D", front: "VAT registration & deregistration thresholds (FA2024/25)", back: "Compulsory registration once taxable turnover exceeds £90,000 (historic or expected). Voluntary deregistration if turnover falls below £88,000." },
  { id: "ATX-FC-38", paper: "ATX", area: "D", front: "VAT — the standard, reduced and zero rates", back: "Standard 20%; reduced 5% (e.g. domestic fuel); zero 0% (e.g. most food, children's clothing, books). Zero-rated is taxable; exempt supplies do not allow input recovery." },
  { id: "ATX-FC-39", paper: "ATX", area: "D", front: "VAT — the capital goods scheme", back: "Adjusts input VAT over time on land/buildings costing £250,000+ (10 intervals) and computers/aircraft/ships £50,000+ (5 intervals) as taxable-use proportion changes." },
  { id: "ATX-FC-40", paper: "ATX", area: "D", front: "VAT group registration", back: "Companies under common control (one controls the others, 51%+) may register as a single VAT group. Intra-group supplies are disregarded; the group is jointly and severally liable." },
  { id: "ATX-FC-41", paper: "ATX", area: "D", front: "VAT — transfer of a going concern (TOGC)", back: "Sale of a business as a going concern is outside the scope of VAT (no VAT charged) if the buyer is/registers for VAT and continues the same kind of business." },
  { id: "ATX-FC-42", paper: "ATX", area: "D", front: "VAT partial exemption de minimis", back: "Input VAT on exempt supplies is recoverable if it is under £625/month on average AND under 50% of total input VAT. Otherwise only the taxable proportion is recovered." },
  { id: "ATX-FC-43", paper: "ATX", area: "D", front: "VAT special accounting schemes", back: "Cash accounting (up to £1.35m turnover): account by cash flows. Annual accounting: one return, instalments. Flat rate scheme (up to £150,000): pay a fixed % of gross turnover." },
  { id: "ATX-FC-44", paper: "ATX", area: "D", front: "VAT default surcharge / penalty points", back: "The points-based regime: a penalty point for each late return; a £200 penalty once the threshold is reached. Late-payment penalties escalate with the delay after the due date." },
  { id: "ATX-FC-45", paper: "ATX", area: "D", front: "Stamp Duty Land Tax (SDLT) — non-residential rates", back: "Non-residential/mixed use: 0% to £150,000; 2% £150,001-£250,000; 5% above £250,000. Payable on UK land transactions within 14 days." },
  { id: "ATX-FC-46", paper: "ATX", area: "D", front: "SDLT — residential and the surcharges", back: "Progressive residential bands with a nil rate up to £250,000. A 3% surcharge applies to additional dwellings; a 2% surcharge for non-UK-resident buyers." },
  { id: "ATX-FC-47", paper: "ATX", area: "D", front: "Stamp duty / SDRT on shares", back: "Stamp Duty 0.5% on transfers of shares by stock transfer form (rounded up to the nearest £5); Stamp Duty Reserve Tax 0.5% on paperless (CREST) transfers. Exempt below £1,000 for SD." },
  { id: "ATX-FC-48", paper: "ATX", area: "D", front: "VAT — tax point (time of supply) rules", back: "Basic tax point is when goods are removed/made available or services performed. An earlier invoice or payment creates an actual tax point; an invoice within 14 days overrides the basic tax point." },

  /* ===== ATX — Area E: Tax planning & ethics ===== */
  { id: "ATX-FC-49", paper: "ATX", area: "E", front: "Tax avoidance vs tax evasion", back: "Avoidance uses legal means to reduce tax (may be challenged under anti-avoidance rules); evasion is illegal concealment or misrepresentation and is a criminal offence." },
  { id: "ATX-FC-50", paper: "ATX", area: "E", front: "The General Anti-Abuse Rule (GAAR)", back: "Allows HMRC to counteract tax advantages from arrangements that are abusive — those that cannot reasonably be regarded as a reasonable course of action (the 'double reasonableness' test)." },
  { id: "ATX-FC-51", paper: "ATX", area: "E", front: "Money laundering — the adviser's duty", back: "Suspicion of tax evasion or proceeds of crime must be reported to the MLRO/NCA via a Suspicious Activity Report. Tipping off the client is a criminal offence." },
  { id: "ATX-FC-52", paper: "ATX", area: "E", front: "Disclosure of errors — the professional response", back: "Advise the client to disclose the error to HMRC. If they refuse, cease to act, notify HMRC that you no longer act (without saying why), and consider a money-laundering report." },
  { id: "ATX-FC-53", paper: "ATX", area: "E", front: "Self-assessment — key filing dates (individuals)", back: "Paper return 31 October; online return 31 January after the tax year. Balancing payment and second payment on account also due 31 January and 31 July." },
  { id: "ATX-FC-54", paper: "ATX", area: "E", front: "HMRC penalties for inaccurate returns", back: "Behaviour-based: careless up to 30% of tax; deliberate up to 70%; deliberate and concealed up to 100%. Penalties reduced for unprompted disclosure." },
  { id: "ATX-FC-55", paper: "ATX", area: "E", front: "Record retention periods", back: "Businesses (including companies): keep records 6 years from the period end. Individuals in business: 5 years from 31 January filing date; non-business individuals: about 22 months." },
  { id: "ATX-FC-56", paper: "ATX", area: "E", front: "Incorporation vs remaining unincorporated — key tax driver", back: "Incorporation can save NIC and allow profit extraction by dividends, but triggers potential CGT on transfer (incorporation relief may defer) and adds administration and CT compliance." },
  { id: "ATX-FC-57", paper: "ATX", area: "E", front: "Profit extraction — salary vs dividends", back: "Salary is deductible for CT and builds NIC benefit entitlement but attracts NIC; dividends avoid NIC but are paid from post-CT profits and carry only a small dividend allowance." },
  { id: "ATX-FC-58", paper: "ATX", area: "E", front: "The 'badges of trade'", back: "Indicators of whether an activity is trading: profit-seeking motive, frequency of transactions, nature of the asset, changes to the asset, method of acquisition, finance, and length of ownership." },
  { id: "ATX-FC-59", paper: "ATX", area: "E", front: "Ethical conflict of interest — the safeguards", back: "Disclose the conflict, obtain informed consent, use separate engagement teams with information barriers, and have an independent reviewer. Decline or withdraw if the threat cannot be managed." },
  { id: "ATX-FC-60", paper: "ATX", area: "E", front: "Overseas expansion — branch vs subsidiary", back: "An overseas branch's profits are taxed in the UK (with double tax relief, or exempt if elected); a subsidiary is a separate entity taxed abroad, with UK tax on dividends usually exempt." },

  /* ===== AAA — Area A: Regulatory environment ===== */
  { id: "AAA-FC-01", paper: "AAA", area: "A", front: "Purpose of an audit (ISA 200 objective)", back: "To obtain reasonable assurance that the financial statements as a whole are free from material misstatement, whether from fraud or error, and to report and communicate accordingly." },
  { id: "AAA-FC-02", paper: "AAA", area: "A", front: "Reasonable vs limited assurance", back: "Reasonable assurance (audit): high but not absolute, positive opinion. Limited assurance (review): moderate, negative-form conclusion ('nothing has come to our attention')." },
  { id: "AAA-FC-03", paper: "AAA", area: "A", front: "The audit expectation gap", back: "The difference between what users believe auditors do (e.g. guarantee accuracy, detect all fraud) and the auditor's actual responsibilities. Managed by clear reporting and education." },
  { id: "AAA-FC-04", paper: "AAA", area: "A", front: "Who sets ISAs, and their authority", back: "The IAASB issues International Standards on Auditing. They are given force through national adoption/regulation; auditors must comply to state compliance with ISAs." },
  { id: "AAA-FC-05", paper: "AAA", area: "A", front: "Laws & regulations — ISA 250 categories", back: "Category 1: laws with a direct effect on the financial statements (obtain sufficient evidence). Category 2: laws central to operating the business (perform limited procedures to identify non-compliance)." },
  { id: "AAA-FC-06", paper: "AAA", area: "A", front: "Auditor's response to identified non-compliance (NOCLAR)", back: "Understand and evaluate the effect, discuss with management/TCWG, consider disclosure and reporting duties, document, and consider withdrawing if management fails to act." },
  { id: "AAA-FC-07", paper: "AAA", area: "A", front: "Money laundering — the auditor's obligations", back: "Appoint an MLRO, perform customer due diligence, keep records, train staff, and file Suspicious Activity Reports. Tipping off and failure to report are offences." },
  { id: "AAA-FC-08", paper: "AAA", area: "A", front: "Corporate governance — the audit committee's role", back: "A committee of independent non-executive directors that oversees financial reporting, recommends auditor appointment/removal, reviews auditor independence and monitors internal audit and controls." },
  { id: "AAA-FC-09", paper: "AAA", area: "A", front: "Auditor's rights on removal / resignation", back: "The auditor may require a general meeting, make written representations, and must issue a statement of circumstances relevant to members and creditors (or state there are none)." },
  { id: "AAA-FC-10", paper: "AAA", area: "A", front: "Laws & regulations — respective responsibilities", back: "Management is responsible for ensuring the entity complies with laws and regulations; the auditor's responsibility is limited to obtaining reasonable assurance the FS are free from material misstatement arising from non-compliance." },
  { id: "AAA-FC-11", paper: "AAA", area: "A", front: "Transnational audits & their significance", back: "Audits of entities whose securities trade across borders or that are significant internationally. They attract greater regulatory attention, so higher scrutiny of standards and independence." },
  { id: "AAA-FC-12", paper: "AAA", area: "A", front: "Public oversight of the audit profession", back: "Independent regulators (e.g. an FRC-type body) inspect audit quality, set standards, discipline firms and monitor the profession to protect the public interest." },

  /* ===== AAA — Area B: Professional & ethical ===== */
  { id: "AAA-FC-13", paper: "AAA", area: "B", front: "The five fundamental ethical principles", back: "Integrity, objectivity, professional competence and due care, confidentiality, and professional behaviour (IESBA Code)." },
  { id: "AAA-FC-14", paper: "AAA", area: "B", front: "The five categories of threat to independence", back: "Self-interest, self-review, advocacy, familiarity and intimidation." },
  { id: "AAA-FC-15", paper: "AAA", area: "B", front: "PIE fee dependence rule", back: "If total fees from a PIE exceed 15% of firm fees for two consecutive years, disclose to TCWG and apply a pre- or post-issuance review safeguard." },
  { id: "AAA-FC-16", paper: "AAA", area: "B", front: "Provision of non-assurance services to audit clients", back: "Prohibited where they create a self-review threat or involve management responsibility. For PIEs, many services (e.g. bookkeeping, valuations, internal audit affecting the FS) are banned outright." },
  { id: "AAA-FC-17", paper: "AAA", area: "B", front: "Contingent fees for audit or assurance engagements", back: "Prohibited. A fee contingent on the outcome creates a self-interest threat to objectivity that no safeguard can reduce to an acceptable level." },
  { id: "AAA-FC-18", paper: "AAA", area: "B", front: "Partner rotation for PIE audits", back: "The engagement partner and key audit partners must rotate off after a maximum of 7 years, with a cooling-off period (generally 5 years for the engagement partner) before returning." },
  { id: "AAA-FC-19", paper: "AAA", area: "B", front: "Gifts and hospitality from an audit client", back: "May only be accepted where trivial and inconsequential; anything more creates self-interest and familiarity threats and should be declined." },
  { id: "AAA-FC-20", paper: "AAA", area: "B", front: "Confidentiality — when disclosure is permitted", back: "When authorised by the client, required by law (e.g. court order), or there is a professional duty/right to disclose (e.g. money laundering, defending against a claim)." },
  { id: "AAA-FC-21", paper: "AAA", area: "B", front: "Conflicts of interest between two clients", back: "Notify both clients, obtain consent, use separate engagement teams and information barriers, and appoint an independent reviewer. Decline if objectivity cannot be safeguarded." },
  { id: "AAA-FC-22", paper: "AAA", area: "B", front: "Loans and financial interests in an audit client", back: "A direct financial interest, or a material indirect interest, held by the firm or team member is prohibited. Loans are only acceptable on normal commercial terms from a lending client." },
  { id: "AAA-FC-23", paper: "AAA", area: "B", front: "Advocacy threat — a typical example", back: "Promoting a client's position, such as acting for the client in litigation or promoting its shares. It compromises objectivity because the auditor becomes aligned with the client's interests." },
  { id: "AAA-FC-24", paper: "AAA", area: "B", front: "Engagement quality reviewer — independence requirement", back: "An EQR must be objective and not part of the engagement team. For PIEs the review is mandatory and completed before the report is signed." },

  /* ===== AAA — Area C: Quality management ===== */
  { id: "AAA-FC-25", paper: "AAA", area: "C", front: "ISQM 1 — the eight components of the system", back: "Governance & leadership; the firm's risk assessment process; relevant ethical requirements; acceptance & continuance; engagement performance; resources; information & communication; and the monitoring & remediation process." },
  { id: "AAA-FC-26", paper: "AAA", area: "C", front: "ISQM 1 — the risk-based approach", back: "The firm sets quality objectives, identifies and assesses quality risks, and designs responses. It is proactive and tailored to the firm rather than a fixed checklist." },
  { id: "AAA-FC-27", paper: "AAA", area: "C", front: "ISQM 2 — engagement quality reviews", back: "Deals with the appointment, eligibility and performance of the engagement quality reviewer. An EQR is required for listed/PIE audits and other engagements the firm determines." },
  { id: "AAA-FC-28", paper: "AAA", area: "C", front: "ISA 220 — quality management at engagement level", back: "The engagement partner takes overall responsibility for quality, ensures sufficient resources, direction, supervision and review, and confirms an EQR is performed where required." },
  { id: "AAA-FC-29", paper: "AAA", area: "C", front: "Client acceptance & continuance considerations", back: "Assess management integrity, the firm's competence and resources, independence and ethical threats, and money-laundering risk. Communicate with the predecessor auditor before accepting." },
  { id: "AAA-FC-30", paper: "AAA", area: "C", front: "Engagement letter — its purpose (ISA 210)", back: "Confirms the terms of engagement: the scope and objective, management's responsibilities, the auditor's responsibilities, the reporting framework and the form of reports. Reduces misunderstanding." },
  { id: "AAA-FC-31", paper: "AAA", area: "C", front: "Direction, supervision and review", back: "Direction: informing the team of responsibilities and risks. Supervision: tracking progress and addressing issues. Review: checking work is documented, sufficient and supports conclusions." },
  { id: "AAA-FC-32", paper: "AAA", area: "C", front: "Monitoring & remediation (ISQM 1)", back: "The firm monitors its quality system (including cyclical engagement inspections), evaluates deficiencies, investigates root causes, and designs remedial actions." },
  { id: "AAA-FC-33", paper: "AAA", area: "C", front: "Consultation and differences of opinion", back: "Difficult or contentious matters require consultation with those having appropriate expertise. Differences of opinion within the team or with the EQR must be resolved before the report is issued." },
  { id: "AAA-FC-34", paper: "AAA", area: "C", front: "Engagement documentation retention", back: "The final audit file must be assembled on a timely basis (ordinarily within 60 days of the report) and retained for the firm's minimum period (at least 5 years under ISQM 1)." },
  { id: "AAA-FC-35", paper: "AAA", area: "C", front: "Using the work of an auditor's expert (ISA 620)", back: "Evaluate the expert's competence, capabilities and objectivity, agree the scope, and assess whether the work is adequate. The auditor retains sole responsibility for the opinion." },
  { id: "AAA-FC-36", paper: "AAA", area: "C", front: "Group audits — the group engagement team's responsibility (ISA 600)", back: "The group team is responsible for the group opinion and directs component auditors' work. It cannot cite a component auditor to divide responsibility in the report." },

  /* ===== AAA — Area D: Planning & conducting the audit ===== */
  { id: "AAA-FC-37", paper: "AAA", area: "D", front: "Audit risk — the model", back: "Audit risk = inherent risk × control risk × detection risk. The auditor assesses the risk of material misstatement (inherent × control) and sets detection risk to reduce overall risk to acceptable." },
  { id: "AAA-FC-38", paper: "AAA", area: "D", front: "Materiality — its dual role (ISA 320)", back: "Set at planning to scope procedures and evaluate misstatements; based on a benchmark (e.g. 5% profit before tax, 1% revenue, 1-2% assets). Performance materiality is lower to allow for aggregation." },
  { id: "AAA-FC-39", paper: "AAA", area: "D", front: "Professional scepticism", back: "A questioning mind, alertness to conditions indicating possible misstatement, and critical assessment of evidence. Especially important for estimates, related parties and fraud risk." },
  { id: "AAA-FC-40", paper: "AAA", area: "D", front: "The financial statement assertions", back: "For transactions: occurrence, completeness, accuracy, cut-off, classification. For balances: existence, rights & obligations, completeness, accuracy/valuation & allocation." },
  { id: "AAA-FC-41", paper: "AAA", area: "D", front: "Fraud — respective responsibilities (ISA 240)", back: "Preventing and detecting fraud is the responsibility of TCWG and management. The auditor obtains reasonable assurance the FS are free from material misstatement due to fraud, maintaining scepticism." },
  { id: "AAA-FC-42", paper: "AAA", area: "D", front: "Significant / higher-risk areas requiring special attention", back: "Accounting estimates and fair values (ISA 540), related party transactions (ISA 550), and the presumption of a fraud risk in revenue recognition and management override of controls." },
  { id: "AAA-FC-43", paper: "AAA", area: "D", front: "Analytical procedures — the three uses", back: "Risk assessment (planning), substantive analytical procedures (evidence), and an overall review near the end to confirm the FS are consistent with the auditor's understanding." },
  { id: "AAA-FC-44", paper: "AAA", area: "D", front: "Sufficient appropriate audit evidence", back: "Sufficiency = quantity; appropriateness = quality (relevance and reliability). Reliability is higher when evidence is external, obtained directly, in documentary form, and from original documents." },
  { id: "AAA-FC-45", paper: "AAA", area: "D", front: "Auditing accounting estimates (ISA 540)", back: "Understand how management makes the estimate, evaluate the method, assumptions and data, and consider estimation uncertainty and possible management bias. Test outcome, re-estimate, or test the process." },
  { id: "AAA-FC-46", paper: "AAA", area: "D", front: "Reliance on internal audit / using internal auditors (ISA 610)", back: "Evaluate internal audit's objectivity, competence and systematic approach. The external auditor cannot use internal audit for judgemental or high-risk areas and remains solely responsible." },
  { id: "AAA-FC-47", paper: "AAA", area: "D", front: "Auditing a specialised entity (e.g. a bank or charity)", back: "Understand the specific regulatory framework, business risks and accounting (e.g. financial instruments, restricted funds). Tailor risks; specialist knowledge or an auditor's expert may be needed." },
  { id: "AAA-FC-48", paper: "AAA", area: "D", front: "Forensic audit vs statutory audit", back: "A forensic engagement investigates a specific issue (e.g. fraud, insurance claim) to produce evidence, often for court. It has a defined scope and is not designed to give an opinion on the FS as a whole." },

  /* ===== AAA — Area E: Completion, review & reporting ===== */
  { id: "AAA-FC-49", paper: "AAA", area: "E", front: "Going concern — auditor's response (ISA 570)", back: "Evaluate management's assessment (min. 12 months), consider mitigating factors and disclosures. If a material uncertainty is adequately disclosed, add a 'Material Uncertainty Related to Going Concern' section." },
  { id: "AAA-FC-50", paper: "AAA", area: "E", front: "Subsequent events — the two periods (ISA 560)", back: "Adjusting/non-adjusting events up to the date of the report: obtain evidence. After the report but before issue: no active duty, but act if facts become known that would have changed the report." },
  { id: "AAA-FC-51", paper: "AAA", area: "E", front: "Written representations — their role (ISA 580)", back: "Confirm management's responsibilities and support other evidence, especially for judgements. They are necessary but not sufficient on their own; a refusal to provide them may lead to a disclaimer." },
  { id: "AAA-FC-52", paper: "AAA", area: "E", front: "ISA 705 — the modification matrix", back: "Material misstatement, not pervasive → qualified 'except for'; pervasive → adverse. Insufficient evidence, not pervasive → qualified; pervasive → disclaimer." },
  { id: "AAA-FC-53", paper: "AAA", area: "E", front: "Emphasis of Matter vs Other Matter paragraph (ISA 706)", back: "Emphasis of Matter: draws attention to something correctly presented in the FS. Other Matter: refers to something not in the FS relevant to users' understanding. Neither modifies the opinion." },
  { id: "AAA-FC-54", paper: "AAA", area: "E", front: "Key Audit Matters (ISA 701)", back: "Matters of most significance in the audit, selected from those communicated to TCWG. Mandatory for listed entities; describe the matter and how it was addressed. KAMs are not a substitute for a modified opinion." },
  { id: "AAA-FC-55", paper: "AAA", area: "E", front: "Auditor's responsibility for 'Other Information' (ISA 720)", back: "Read the other information in the annual report for material inconsistency with the FS or the auditor's knowledge. If uncorrected, describe the material misstatement in an Other Information section." },
  { id: "AAA-FC-56", paper: "AAA", area: "E", front: "Communication with TCWG (ISA 260 / 265)", back: "Communicate the audit scope, significant findings, independence (for listed), and significant deficiencies in internal control (ISA 265) in writing on a timely basis." },
  { id: "AAA-FC-57", paper: "AAA", area: "E", front: "Overall review of financial statements at completion", back: "Perform final analytical procedures, evaluate uncorrected misstatements against materiality, review adequacy of disclosures, and conclude whether sufficient appropriate evidence supports the opinion." },
  { id: "AAA-FC-58", paper: "AAA", area: "E", front: "Reporting to a regulator / third parties — liability", back: "Auditors owe a duty of care primarily to the members as a body (Caparo). Liability to third parties arises only where proximity and reliance are established; disclaimers (Bannerman) help limit exposure." },
  { id: "AAA-FC-59", paper: "AAA", area: "E", front: "Review engagement vs agreed-upon procedures", back: "A review (ISRE 2400/2410) gives limited assurance with a negative conclusion. Agreed-upon procedures (ISRS 4400) give no assurance — only a factual report of findings for users to draw their own conclusions." },
  { id: "AAA-FC-60", paper: "AAA", area: "E", front: "Prospective financial information — the assurance report (ISAE 3400)", back: "Only limited assurance is possible because it concerns future events. The report states whether assumptions are a reasonable basis and whether the PFI is properly prepared on those assumptions." },
]
