import type { AccaQuestion } from "@/lib/acca-content"

/* MA bank wave 7 — +70 to 150 (2026-07-11). */
export const MA_WAVE3: AccaQuestion[] = [
  /* ───────── A — Cost accounting & classification (14) ───────── */
  {
    id: "MA3-A-01", paper: "MA", area: "A", type: "mcq",
    stem: "A graph plots cost per unit (vertical axis) against activity level (horizontal axis). The line starts high, falls steeply at first and then flattens, approaching — but never reaching — zero as activity rises. The graph shows:",
    options: ["Total fixed cost", "Fixed cost per unit", "Variable cost per unit", "Total variable cost"],
    correct: 1,
    explanation: "A constant total fixed cost spread over more and more units gives a falling per-unit curve that approaches zero — the classic hyperbola. Total fixed cost would be a horizontal line, variable cost PER UNIT is also horizontal (constant per unit), and total variable cost is a rising straight line from the origin.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA3-A-02", paper: "MA", area: "A", type: "mcq",
    stem: "A graph of TOTAL cost (vertical axis) against activity (horizontal axis) shows a straight line that starts at a positive value on the cost axis and slopes upwards to the right. The cost being graphed is:",
    options: ["A fixed cost", "A variable cost", "A semi-variable cost", "A stepped-fixed cost"],
    correct: 2,
    explanation: "A positive intercept means cost is incurred even at zero activity (the fixed element), and the upward slope adds a variable element per unit — together, a semi-variable cost. A pure fixed cost is horizontal, a pure variable cost passes through the origin, and a step cost rises in horizontal 'stairs', not a smooth line.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA3-A-03", paper: "MA", area: "A", type: "mcq",
    stem: "The RELEVANT RANGE is best described as the range of activity over which:",
    options: [
      "Total variable costs remain constant",
      "The company expects to make a profit",
      "Production capacity can be doubled without new investment",
      "Assumed cost behaviour patterns (e.g. constant total fixed costs and constant variable cost per unit) remain valid",
    ],
    correct: 3,
    explanation: "Cost behaviour assumptions are only reliable within the band of activity for which they were established — outside it, fixed costs may step up and unit variable costs may change (e.g. bulk discounts, overtime). Total variable cost changes WITH activity even inside the range, and the relevant range has nothing to do with profitability or doubling capacity.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA3-A-04", paper: "MA", area: "A", type: "number",
    stem: "Malden Co's total production costs were $48,600 at 9,000 units and $61,400 at 13,000 units. Both volumes lie within the relevant range. Using the high-low method, what is the expected TOTAL cost at 11,500 units, in $?",
    numericAnswer: 56600, unit: "$",
    explanation: "Variable cost per unit = (61,400 − 48,600) ÷ (13,000 − 9,000) = 12,800 ÷ 4,000 = $3.20. Fixed cost = 48,600 − (9,000 × 3.20) = $19,800 (check: 61,400 − 41,600 = 19,800). At 11,500 units: 19,800 + (11,500 × 3.20) = $56,600. Trap: stopping at the fixed or variable element, or averaging the two total costs (which ignores the different volumes).",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-A-05", paper: "MA", area: "A", type: "mcq",
    stem: "Purchase prices rose steadily throughout quarters 1 and 2. Inventory was built up during Q1, and ALL inventory had been sold by the end of Q2. Comparing FIFO with weighted average (AVCO), which statement is correct?",
    options: [
      "FIFO reports a higher profit in Q1 AND a higher cumulative profit over the two quarters",
      "FIFO reports a higher profit in Q1, but the cumulative profit over the two quarters is the same under both methods",
      "Profits are identical in each individual quarter under both methods",
      "FIFO reports a lower profit in Q1, but the cumulative profit over the two quarters is the same under both methods",
    ],
    correct: 1,
    explanation: "With rising prices and rising inventory, FIFO charges the older, cheaper units to cost of sales, so Q1 profit is HIGHER than AVCO. But valuation methods only shift profit BETWEEN periods: once all inventory is sold, total purchases charged to cost of sales are identical, so cumulative profit is the same. Thinking FIFO creates permanently higher profit is the classic error.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA3-A-06", paper: "MA", area: "A", type: "mcq",
    stem: "Ferring Co held 300 units of a component at $2.00 each. It then purchased 500 units at $2.20 each, and later issued 600 units to production. Using LIFO, the value of the issue is:",
    options: ["$1,260", "$1,275", "$1,300", "$1,320"],
    correct: 2,
    explanation: "LIFO issues the NEWEST units first: 500 × $2.20 + 100 × $2.00 = 1,100 + 200 = $1,300. $1,260 is FIFO (300 × $2.00 + 300 × $2.20), $1,275 is the weighted average (1,700 ÷ 800 = $2.125 × 600), and $1,320 prices the whole issue at the latest cost of $2.20.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-A-07", paper: "MA", area: "A", type: "number",
    stem: "Lancing Co held 400 kg of material at $3.00 per kg. It then purchased 600 kg at $3.50 per kg, and afterwards issued 700 kg to production. Using FIFO, what is the value of CLOSING inventory, in $?",
    numericAnswer: 1050, unit: "$",
    explanation: "FIFO issues the oldest first: the 700 kg issue takes all 400 kg at $3.00 plus 300 kg at $3.50. Closing inventory = the remaining 300 kg of the newer batch × $3.50 = $1,050. Trap: valuing the closing stock at the OLD price of $3.00 ($900) — under FIFO it is the LATEST purchases that remain — or blending prices, which is AVCO ($3.30 × 300 = $990).",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-A-08", paper: "MA", area: "A", type: "mcq",
    stem: "Gross wages of Shoreham Co's direct production workers were $50,000 for the period. This includes $2,000 of overtime premium (worked because of general production pressure) and $3,000 paid for idle time caused by a materials shortage. The DIRECT labour cost charged to work-in-progress is:",
    options: ["$45,000", "$47,000", "$48,000", "$50,000"],
    correct: 0,
    explanation: "General overtime premium and idle time are both treated as production OVERHEAD, not direct cost: 50,000 − 2,000 − 3,000 = $45,000. $47,000 removes only the idle time, $48,000 removes only the premium, and $50,000 charges everything direct — but neither the premium (not caused by any specific unit) nor idle hours (no output at all) can be traced to cost units.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-A-09", paper: "MA", area: "A", type: "mcq",
    stem: "Piecework employees at Angmering Co are paid $0.60 per unit, with a guaranteed minimum of $90 per DAY. On Monday, Riya produced 160 units; on Tuesday she produced 130 units. Her total pay for the two days is:",
    options: ["$174", "$180", "$186", "$264"],
    correct: 2,
    explanation: "Each day is tested separately against the guarantee: Monday 160 × $0.60 = $96 (above $90, so paid $96); Tuesday 130 × $0.60 = $78 (below $90, so the guarantee of $90 applies). Total = 96 + 90 = $186. $174 ignores the guarantee (290 × $0.60), $180 wrongly applies the guarantee to the two days combined ($174 < $180 so pays 2 × $90), and $264 adds the guarantee on top of piecework instead of substituting it.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-A-10", paper: "MA", area: "A", type: "mcq",
    stem: "Worthing Co uses between 400 and 600 kg of a material per day, and delivery lead time is between 4 and 6 days. To guarantee production never stops due to a stockout, the REORDER LEVEL should be:",
    options: ["1,600 kg", "2,400 kg", "2,500 kg", "3,600 kg"],
    correct: 3,
    explanation: "Reorder level = MAXIMUM usage × MAXIMUM lead time = 600 × 6 = 3,600 kg — the worst case that must be covered. 2,500 uses average usage × average lead time (risks a stockout half the time), 1,600 uses the minimums, and 2,400 mixes a maximum with a minimum.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-A-11", paper: "MA", area: "A", type: "mcq",
    stem: "Worthing Co's reorder level is 3,600 kg and its reorder quantity is 5,000 kg. Daily usage is between 400 and 600 kg and lead time is between 4 and 6 days. The MAXIMUM inventory level is:",
    options: ["5,000 kg", "6,100 kg", "7,000 kg", "8,600 kg"],
    correct: 2,
    explanation: "Maximum level = reorder level + reorder quantity − (MINIMUM usage × MINIMUM lead time) = 3,600 + 5,000 − (400 × 4) = 8,600 − 1,600 = 7,000 kg. The peak occurs when an order arrives after the LEAST possible inventory was consumed during the lead time. 8,600 forgets that deduction entirely, 6,100 deducts average usage × average lead time (2,500), and 5,000 is just the order quantity.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA3-A-12", paper: "MA", area: "A", type: "mcq",
    stem: "Steyning Co orders a component in batches of 400 units. The cost of holding one unit in inventory for a year is $3, and inventory is used evenly so the average holding is half a batch. The TOTAL annual holding cost is:",
    options: ["$600", "$1,200", "$12,000", "$24,000"],
    correct: 0,
    explanation: "Average inventory = Q ÷ 2 = 200 units, so annual holding cost = 200 × $3 = $600. $1,200 forgets to halve the batch (400 × $3), while $12,000 and $24,000 wrongly apply the $3 to annual demand figures rather than to the average number of units sitting in store.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA3-A-13", paper: "MA", area: "A", type: "mcq",
    stem: "Idle time of production workers caused by an unexpected machine breakdown is normally accounted for as:",
    options: [
      "A direct labour cost of the units being produced at the time",
      "An abnormal loss in the process account",
      "An administrative expense",
      "An indirect production cost (production overhead)",
    ],
    correct: 3,
    explanation: "Idle hours produce no output, so their cost cannot be traced to any cost unit — it is collected as production overhead and spread across all production. Charging it direct would overstate the cost of whatever happened to be in production; it is a labour-cost issue, not a process loss of units, and it belongs in production, not administration.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA3-A-14", paper: "MA", area: "A", type: "mcq",
    stem: "Carriage inwards paid on deliveries of raw materials from suppliers should be classified as:",
    options: [
      "Part of the cost of direct materials",
      "A production overhead",
      "A selling and distribution cost",
      "An administrative cost",
    ],
    correct: 0,
    explanation: "Carriage INWARDS is a cost of getting materials into a usable condition and location, so it is added to the direct material cost of those materials. The classic confusion is with carriage OUTWARDS (delivering goods to customers), which IS a selling and distribution cost; it is not a general factory overhead or an admin cost.",
    marks: 2, difficulty: "easy",
  },

  /* ───────── B — Costing techniques (10) ───────── */
  {
    id: "MA3-B-01", paper: "MA", area: "B", type: "mcq",
    stem: "Rustington Co's machining department is highly automated, with budgeted overheads of $180,000, 45,000 machine hours and only 12,000 direct labour hours. A job requires 6 machine hours and 2 labour hours. Using the MOST appropriate absorption basis, the overhead charged to the job is:",
    options: ["$8", "$24", "$30", "$90"],
    correct: 1,
    explanation: "In an automated department overheads are driven by machine time, so OAR = 180,000 ÷ 45,000 = $4 per machine hour; the job absorbs 6 × 4 = $24. $30 uses a labour-hour rate (180,000 ÷ 12,000 = $15 × 2) — inappropriate where labour is minor; $8 applies the machine rate to labour hours; $90 applies the labour rate to machine hours.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-B-02", paper: "MA", area: "B", type: "mcq",
    stem: "Poling Co absorbs NON-production (administrative) overheads into product costs at 20% of full production cost. A product has a full production cost of $150 per unit. Its total cost per unit for pricing purposes is:",
    options: ["$120", "$150", "$180", "$187.50"],
    correct: 2,
    explanation: "Admin overhead absorbed = 20% × 150 = $30, so total cost = 150 + 30 = $180. $187.50 treats the 20% as a proportion OF the final total (150 ÷ 0.8), confusing an absorption percentage with a margin; $150 ignores non-production overheads altogether; $120 deducts instead of adds. Note non-production overheads are added for pricing but are never included in inventory valuation.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-B-03", paper: "MA", area: "B", type: "mcq",
    stem: "A process had opening WIP of 500 units (40% complete for conversion) with conversion costs brought forward of $1,600. 2,000 units were started; conversion costs incurred in the period were $12,680. 2,200 units were completed, and closing WIP of 300 units is 60% complete for conversion. Using the WEIGHTED AVERAGE method, the conversion cost per equivalent unit is:",
    options: ["$5.71", "$5.82", "$6.00", "$6.49"],
    correct: 2,
    explanation: "Weighted average POOLS opening WIP cost with period cost: (1,600 + 12,680) ÷ (2,200 completed + 300 × 60% = 2,380 EU) = 14,280 ÷ 2,380 = $6.00. $5.82 is the FIFO answer (period costs only ÷ 2,180 EU after deducting opening WIP's 200 EU of prior work), $6.49 divides by completed units only, and $5.71 treats closing WIP as fully complete (÷ 2,500).",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA3-B-04", paper: "MA", area: "B", type: "mcq",
    stem: "A process had opening WIP of 400 units valued at $3,100. Costs added in the period were $22,100. 1,800 units were completed and transferred out; closing WIP of 500 units is 60% complete (costs are incurred evenly). Using the weighted average method, the value of units TRANSFERRED OUT is closest to:",
    options: ["$18,940", "$19,720", "$21,600", "$25,200"],
    correct: 2,
    explanation: "Total cost = 3,100 + 22,100 = $25,200. Equivalent units = 1,800 + (500 × 60%) = 2,100, so cost per EU = $12.00. Transferred out = 1,800 × 12 = $21,600 (closing WIP takes the remaining 300 × 12 = $3,600 — the account balances). $19,720 divides by 2,300 physical units, $18,940 ignores the opening WIP cost, and $25,200 gives ALL cost to output, leaving WIP valued at nil.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA3-B-05", paper: "MA", area: "B", type: "mcq",
    stem: "A joint process costing $60,000 yields two products at the split-off point: 8,000 kg of P (selling price $10/kg) and 4,000 kg of Q (selling price $5/kg). Using the PHYSICAL UNITS basis, the joint cost apportioned to P is:",
    options: ["$20,000", "$30,000", "$40,000", "$48,000"],
    correct: 2,
    explanation: "Physical basis apportions by weight of output: P gets 8,000 ÷ 12,000 × 60,000 = $40,000. $48,000 is the SALES VALUE basis (P's sales value 80,000 of 100,000 total) — a different, equally valid method but not the one asked for; $30,000 splits the cost equally; $20,000 is Q's physical share.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-B-06", paper: "MA", area: "B", type: "number",
    stem: "A joint process costing $45,000 produces 4,000 litres of product X (selling price $9 per litre at split-off) and 6,000 litres of product Y (selling price $4 per litre at split-off). Using the SALES VALUE basis, what joint cost is apportioned to X, in $?",
    numericAnswer: 27000, unit: "$",
    explanation: "Sales values at split-off: X = 4,000 × 9 = $36,000; Y = 6,000 × 4 = $24,000; total $60,000. X's share = 45,000 × 36,000/60,000 = $27,000. Trap: apportioning on volume (physical basis) gives X only 45,000 × 4/10 = $18,000 — the sales-value method deliberately loads more cost onto the product with more revenue-bearing capacity.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-B-07", paper: "MA", area: "B", type: "mcq",
    stem: "A process yields a main product and a small quantity of a BY-PRODUCT. The normal accounting treatment of the by-product's sales value is to:",
    options: [
      "Apportion joint costs to it in proportion to its sales value, like a joint product",
      "Recognise it as ordinary sales revenue with a full share of process cost",
      "Ignore it until the by-product is actually sold, then treat it as other income of the selling department",
      "Deduct it from the costs of the process, reducing the cost of the main product",
    ],
    correct: 3,
    explanation: "By-products are incidental, so no joint cost is apportioned to them; their (net realisable) sales value is credited against the process cost, cheapening the main product. Treating it like a joint product or giving it a full cost share overstates its significance — the defining difference between a joint product and a by-product is materiality of sales value.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA3-B-08", paper: "MA", area: "B", type: "mcq",
    stem: "Arun Buses wants a single cost unit for control purposes. Some routes carry many passengers short distances; others carry few passengers long distances. The MOST useful cost unit is cost per:",
    options: ["Kilometre travelled", "Passenger carried", "Bus per day", "Passenger-kilometre"],
    correct: 3,
    explanation: "A composite unit combines both dimensions of the service: carrying one passenger for one kilometre. Cost per km ignores how full the bus is, cost per passenger ignores journey length, and cost per bus-day ignores both — each single measure would make one type of route look artificially cheap or expensive.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA3-B-09", paper: "MA", area: "B", type: "mcq",
    stem: "A hospital ward has 30 beds and average occupancy of 80%. Annual ward costs are $547,500. Using a 365-day year, the cost per PATIENT-DAY is:",
    options: ["$50.00", "$62.50", "$1,500", "$18,250"],
    correct: 1,
    explanation: "Patient-days = 30 beds × 365 days × 80% occupancy = 8,760. Cost per patient-day = 547,500 ÷ 8,760 = $62.50. $50.00 ignores occupancy (divides by 10,950 available bed-days), $1,500 is the cost per calendar day for the whole ward, and $18,250 is the annual cost per bed — none reflects the service actually delivered.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-B-10", paper: "MA", area: "B", type: "mcq",
    stem: "Adur Co put 2,000 kg of material costing $9,700 into a process. Normal loss is 5% of input, and all losses are sold as scrap at $2 per kg. Actual output was 1,850 kg. The NET cost charged to the income statement in respect of the ABNORMAL LOSS is:",
    options: ["$100", "$150", "$250", "$750"],
    correct: 1,
    explanation: "Cost per kg = (9,700 − 100 × $2) ÷ (2,000 × 95%) = 9,500 ÷ 1,900 = $5.00. Expected output 1,900 vs actual 1,850 gives an abnormal loss of 50 kg, charged at full cost ($250) but partly offset by its scrap proceeds (50 × $2 = $100): net charge = $150. $250 forgets the scrap recovery on the abnormal units, $100 is only the scrap value, and $750 treats the entire 150 kg loss as abnormal.",
    marks: 2, difficulty: "hard",
  },

  /* ───────── C — Budgeting (9) ───────── */
  {
    id: "MA3-C-01", paper: "MA", area: "C", type: "mcq",
    stem: "Ashington Co forecasts sales demand of 20,000 units next year. Each unit needs 2 direct labour hours, 3 kg of material and 0.5 machine hours. Available next year: 36,000 labour hours, 66,000 kg of material and 12,000 machine hours. The PRINCIPAL BUDGET FACTOR is:",
    options: ["Sales demand", "Direct labour hours", "Raw materials", "Machine hours"],
    correct: 1,
    explanation: "Test each resource against demand: labour needs 20,000 × 2 = 40,000 hours but only 36,000 are available — a shortfall; materials (60,000 kg needed vs 66,000) and machine time (10,000 hours vs 12,000) are both sufficient. So labour, not demand, limits activity and its budget must be set first. Sales demand is only the principal budget factor when every resource can meet it.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-C-02", paper: "MA", area: "C", type: "number",
    stem: "Findon Co's credit sales were: April $80,000, May $90,000, June $100,000. Customers pay 30% in the month of sale (earning a 2% settlement discount), 45% one month after sale, and 22% two months after sale; 3% become irrecoverable. What are budgeted cash receipts for JUNE, in $?",
    numericAnswer: 87500, unit: "$",
    explanation: "June receipts = 30% × 100,000 × 98% (June sales, net of discount) + 45% × 90,000 (May sales) + 22% × 80,000 (April sales) = 29,400 + 40,500 + 17,600 = $87,500. Traps: forgetting the 2% discount applies ONLY to the prompt 30% slice, applying the lags to the wrong months' sales, or including the 3% irrecoverable portion — money that never arrives.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA3-C-03", paper: "MA", area: "C", type: "mcq",
    stem: "Bramber Co must set its production batch size before demand is known. A batch of 200 units gives a profit of $200 if demand is low and $900 if demand is high; a batch of 100 units gives a profit of $500 whatever demand turns out to be. P(low demand) = 0.4, P(high demand) = 0.6. Using EXPECTED VALUES, the company should choose:",
    options: [
      "The 100-unit batch, with an EV of $500",
      "The 200-unit batch, with an EV of $900",
      "The 200-unit batch, with an EV of $550",
      "The 200-unit batch, with an EV of $620",
    ],
    correct: 3,
    explanation: "EV(200) = 0.4 × 200 + 0.6 × 900 = 80 + 540 = $620, which beats EV(100) = $500 — so the payoff table points to the 200-unit batch. $900 picks the best single outcome rather than the probability-weighted average, and $550 is the unweighted mean of $200 and $900, ignoring the probabilities. (A risk-averse decision-maker might still prefer the certain $500 — EV is only a guide.)",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-C-04", paper: "MA", area: "C", type: "mcq",
    stem: "Each year, every manager at Storrington Co must justify ALL of their department's activities from a zero base, ranking them as 'decision packages' before any funds are allocated. This budgeting approach is:",
    options: ["Incremental budgeting", "Rolling budgeting", "Flexible budgeting", "Zero-based budgeting"],
    correct: 3,
    explanation: "Starting from zero and requiring every activity to be re-justified and ranked in decision packages is zero-based budgeting (ZBB) — powerful against budgetary slack but very time-consuming. Incremental budgeting does the opposite (last year plus an adjustment), rolling budgets are about continuous updating, and flexible budgets are about cost behaviour, not justification.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA3-C-05", paper: "MA", area: "C", type: "mcq",
    stem: "Henfield Tech operates in a fast-changing market. Each time a quarter ends, the budget is extended by adding a new quarter, so it always covers the next four quarters and is revised in the process. This is:",
    options: ["A rolling (continuous) budget", "A zero-based budget", "A fixed periodic budget", "A flexed budget"],
    correct: 0,
    explanation: "Adding a further period as each one expires, so the budget horizon 'rolls' forward and stays constantly up to date, defines a rolling budget — well suited to dynamic environments, at the cost of more frequent budgeting effort. A fixed periodic budget is set once for the year; ZBB is about justification from zero; a flexed budget restates costs for actual activity after the fact.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA3-C-06", paper: "MA", area: "C", type: "mcq",
    stem: "The first batch of a new product took 200 hours. An 80% learning curve applies (cumulative average time falls to 80% each time cumulative output doubles). The total time for batches 3 and 4 combined will be:",
    options: ["128 hours", "192 hours", "256 hours", "320 hours"],
    correct: 1,
    explanation: "Cumulative average: 1 batch = 200 hrs; 2 batches = 160 (total 320); 4 batches = 128 (total 512). Batches 3–4 = 512 − 320 = 192 hours. 256 wrongly assumes each of batches 3 and 4 takes the 128-hour average (the average includes the slower early batches), 320 assumes no further learning after batch 2, and 128 is the cumulative average itself, misread as the incremental time.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA3-C-07", paper: "MA", area: "C", type: "number",
    stem: "The first unit of a new product took 50 hours. A 90% learning curve applies. What is the CUMULATIVE AVERAGE time per unit when 8 units have been made, in hours?",
    numericAnswer: 36.45, unit: "hours", tolerance: 0.05,
    explanation: "Output doubles three times to reach 8 (1→2→4→8), so the cumulative average falls by 90% three times: 50 × 0.9 × 0.9 × 0.9 = 50 × 0.729 = 36.45 hours. Trap: applying 0.9 only once (45) or confusing the cumulative AVERAGE with the TOTAL time (8 × 36.45 = 291.6 hours) or the time for the 8th unit alone.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-C-08", paper: "MA", area: "C", type: "mcq",
    stem: "Using an ADDITIVE time series model, Ferndown Co's trend forecast for Q3 is 1,850 units. Seasonal variations are: Q2 +250 units, Q3 −150 units. The sales forecast for Q3 is:",
    options: ["1,700 units", "1,850 units", "2,000 units", "2,100 units"],
    correct: 0,
    explanation: "Additive model: forecast = trend + seasonal variation = 1,850 + (−150) = 1,700 units. 2,000 adds 150 instead of subtracting (the sign matters), 2,100 applies the wrong quarter's variation (Q2's +250), and 1,850 forgets the seasonal adjustment entirely — the trend alone is not the forecast.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-C-09", paper: "MA", area: "C", type: "mcq",
    stem: "Actual sales in Q2 were 46,000 units. The Q2 seasonal index is 115 (multiplicative model, average = 100). The SEASONALLY ADJUSTED (deseasonalised) sales figure — an estimate of the underlying trend — is:",
    options: ["39,100 units", "40,000 units", "46,000 units", "52,900 units"],
    correct: 1,
    explanation: "To remove seasonality, DIVIDE actual data by the index: 46,000 ÷ 1.15 = 40,000 units. 52,900 multiplies by 1.15 (that direction builds a forecast FROM the trend, the opposite operation), 39,100 subtracts 15% (46,000 × 0.85 — not the inverse of multiplying by 1.15), and 46,000 leaves the raw figure unadjusted.",
    marks: 2, difficulty: "medium",
  },

  /* ───────── D — Standard costing & variances (16) ───────── */
  {
    id: "MA3-D-01", paper: "MA", area: "D", type: "mcq",
    stem: "Amberley Co's direct workers were paid for 4,200 hours (total wages $39,900) but actually worked only 3,900 hours; the other 300 hours were idle. The standard rate is $9.00 per hour. The IDLE TIME variance is:",
    options: ["$2,100 adverse", "$2,700 adverse", "$2,700 favourable", "$2,850 adverse"],
    correct: 1,
    explanation: "Idle time variance = idle hours × STANDARD rate = 300 × $9.00 = $2,700 adverse (paid-for hours that produced nothing — always adverse). $2,850 uses the actual rate of $9.50 (39,900 ÷ 4,200), $2,100 is the labour RATE variance ((9.00 − 9.50) × 4,200) mislabelled, and idle time can never be favourable.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-D-02", paper: "MA", area: "D", type: "mcq",
    stem: "Pulborough Co's employees were paid for 5,000 hours, of which 200 were idle. Output was 2,500 units with a standard time of 2 hours per unit and a standard rate of $10 per hour. Where idle time is reported separately, the labour EFFICIENCY variance is:",
    options: ["$2,000 adverse", "Nil", "$2,000 favourable", "$4,000 favourable"],
    correct: 2,
    explanation: "When idle time is separated, efficiency compares standard hours with hours actually WORKED: standard = 2,500 × 2 = 5,000; worked = 5,000 − 200 = 4,800; variance = (5,000 − 4,800) × $10 = $2,000 favourable — the workers produced output faster than standard while working. 'Nil' uses hours PAID (5,000), burying the idle time; $4,000 double-counts the idle hours; adverse flips the direction.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA3-D-03", paper: "MA", area: "D", type: "mcq",
    stem: "To cut costs, Arundel Co replaced several experienced (higher-paid) production workers with trainees on lower hourly rates. The MOST LIKELY combined effect on the labour variances is:",
    options: [
      "A favourable rate variance and an adverse efficiency variance",
      "An adverse rate variance and a favourable efficiency variance",
      "Favourable rate and efficiency variances",
      "Adverse rate and efficiency variances",
    ],
    correct: 0,
    explanation: "Trainees are paid below the standard rate (favourable RATE variance) but work more slowly and make more mistakes than the standard assumes (adverse EFFICIENCY variance) — and possibly adverse material usage too. This interrelationship means the purchasing-style 'saving' on rates can cost more than it saves, which is why paired variances should be investigated together.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA3-D-04", paper: "MA", area: "D", type: "mcq",
    stem: "A worldwide shortage pushed the market price of Petworth Co's key raw material well above the level assumed when standards were set. Which variance DIRECTLY reflects this event?",
    options: [
      "An adverse material price variance",
      "An adverse material usage variance",
      "An adverse variable overhead expenditure variance",
      "A favourable material price variance",
    ],
    correct: 0,
    explanation: "Paying more per kg than standard is captured by the material PRICE variance — adverse, since actual price exceeds standard. Usage measures quantities consumed, not prices, and overhead expenditure relates to overhead spending. Note the cause is external (uncontrollable by the buyer), a reminder that an adverse variance is not automatically poor performance.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA3-D-05", paper: "MA", area: "D", type: "mcq",
    stem: "Midhurst Co bought and used 5,200 kg of material at a total cost of $23,920. Output was 1,000 units; the standard is 5 kg per unit at $4.80 per kg. The TOTAL material cost variance is:",
    options: ["$80 favourable", "$80 adverse", "$960 adverse", "$1,040 favourable"],
    correct: 0,
    explanation: "Total variance = standard cost of actual output − actual cost = (1,000 × 5 × 4.80 = 24,000) − 23,920 = $80 favourable. It splits into a $1,040 favourable price variance ((4.80 − 4.60) × 5,200) and a $960 adverse usage variance ((5,000 − 5,200) × 4.80) — quoting either component alone answers a different question, and $80 adverse flips the direction.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-D-06", paper: "MA", area: "D", type: "mcq",
    stem: "Bosham Co budgets fixed overheads of $80,000 and 10,000 labour hours. Actual hours worked were 10,400, and the standard hours of the output produced were 10,100. The fixed overhead CAPACITY variance is:",
    options: ["$800 favourable", "$2,400 adverse", "$3,200 adverse", "$3,200 favourable"],
    correct: 3,
    explanation: "OAR = 80,000 ÷ 10,000 = $8/hour. Capacity = (actual hours worked − budgeted hours) × rate = (10,400 − 10,000) × 8 = $3,200 FAVOURABLE — working more hours than budget creates capacity to absorb more overhead. $2,400 adverse is the efficiency variance ((10,100 − 10,400) × 8), $800 favourable is the total volume variance, and $3,200 adverse misreads extra hours as bad.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA3-D-07", paper: "MA", area: "D", type: "number",
    stem: "Selsey Co absorbs fixed overheads at $6 per labour hour. The standard hours for the output achieved were 8,700, and actual hours worked were 8,400. What is the value, in $, of the (favourable) fixed overhead EFFICIENCY variance?",
    numericAnswer: 1800, unit: "$",
    explanation: "Fixed overhead efficiency variance = (standard hours for output − actual hours worked) × OAR = (8,700 − 8,400) × $6 = $1,800 favourable: producing the output in fewer hours than standard means each hour worked 'earned' more absorbed overhead. Trap: using budgeted hours in the comparison — that belongs to the capacity variance, not efficiency.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA3-D-08", paper: "MA", area: "D", type: "mcq",
    stem: "Under standard absorption costing, the fixed overhead VOLUME variance can be subdivided into which two variances?",
    options: [
      "Capacity and efficiency",
      "Expenditure and efficiency",
      "Expenditure and capacity",
      "Rate and efficiency",
    ],
    correct: 0,
    explanation: "Volume variance = capacity variance (did we work more or fewer hours than budgeted?) + efficiency variance (did those hours produce output faster or slower than standard?). The expenditure variance is the OTHER half of the total fixed overhead variance — it sits alongside volume, not inside it — and 'rate' belongs to labour variances.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA3-D-09", paper: "MA", area: "D", type: "mcq",
    stem: "Cowfold Co uses standard MARGINAL costing. Budgeted sales were 6,000 units; actual sales were 5,600 units. Standard selling price is $30, standard variable cost $18, and standard profit $8 per unit. The sales VOLUME variance is:",
    options: ["$3,200 adverse", "$4,800 adverse", "$4,800 favourable", "$12,000 adverse"],
    correct: 1,
    explanation: "Under MARGINAL costing the volume shortfall is valued at standard CONTRIBUTION: (6,000 − 5,600) × (30 − 18) = 400 × $12 = $4,800 adverse. $3,200 uses standard PROFIT ($8) — correct only under absorption costing; $12,000 uses the full selling price; favourable is impossible when sales fall short of budget.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-D-10", paper: "MA", area: "D", type: "mcq",
    stem: "Slindon Co's standard variable overhead rate is $3 per labour hour. The standard hours for actual output were 4,500; actual hours worked were 4,700; actual variable overheads were $13,630. The variable overhead EFFICIENCY variance is:",
    options: ["$130 adverse", "$470 favourable", "$600 adverse", "$600 favourable"],
    correct: 2,
    explanation: "Efficiency = (standard hours − actual hours) × standard rate = (4,500 − 4,700) × $3 = $600 adverse: extra hours worked drag extra variable overhead with them. $470 favourable is the EXPENDITURE variance ((4,700 × 3) − 13,630) mislabelled, $130 adverse is the TOTAL variable overhead variance, and $600 favourable flips the direction.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-D-11", paper: "MA", area: "D", type: "number",
    stem: "Duncton Co reports a material price variance of $1,500 ADVERSE on the purchase of 6,000 kg. The standard price is $8.00 per kg. What was the ACTUAL price paid per kg, in $?",
    numericAnswer: 8.25, unit: "$", tolerance: 0.01,
    explanation: "Work backwards: price variance per kg = 1,500 ÷ 6,000 = $0.25, and ADVERSE means the actual price was ABOVE standard: 8.00 + 0.25 = $8.25 (check: (8.00 − 8.25) × 6,000 = −1,500). Trap: subtracting to get $7.75 — that would make the variance favourable — or dividing the variance by standard cost instead of by quantity.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA3-D-12", paper: "MA", area: "D", type: "mcq",
    stem: "Kirdford Co reports a material usage variance of $2,500 FAVOURABLE. The standard price is $5 per kg and the standard usage is 3 kg per unit. Actual usage was 14,500 kg. Actual OUTPUT for the period was:",
    options: ["4,667 units", "4,833 units", "5,000 units", "5,667 units"],
    correct: 2,
    explanation: "Favourable usage means the standard allowance EXCEEDED actual usage by 2,500 ÷ $5 = 500 kg, so standard quantity = 14,500 + 500 = 15,000 kg, and output = 15,000 ÷ 3 = 5,000 units. 4,667 subtracts the 500 kg (misreading 'favourable'), 4,833 ignores the variance entirely (14,500 ÷ 3), and 5,667 treats the $2,500 as if it were already in kg.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA3-D-13", paper: "MA", area: "D", type: "mcq",
    stem: "Nutbourne Co's operating statement shows: budgeted profit $100,000; sales volume variance $5,000 favourable; sales price variance $3,000 adverse; total cost variances $2,000 adverse. Actual profit for the period is:",
    options: ["$90,000", "$100,000", "$104,000", "$110,000"],
    correct: 1,
    explanation: "Reconcile with signs: 100,000 + 5,000 (F) − 3,000 (A) − 2,000 (A) = $100,000 — the favourable and adverse effects happen to cancel exactly. $110,000 adds every variance as if favourable, $90,000 subtracts them all, and $104,000 adds the adverse cost variance instead of subtracting it. Favourable variances increase profit; adverse variances decrease it.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-D-14", paper: "MA", area: "D", type: "mcq",
    stem: "Fittleworth Co values its raw material inventory at STANDARD cost. The material price variance should be calculated on:",
    options: [
      "The quantity purchased, at the time of purchase",
      "The quantity issued to production, at the time of issue",
      "The quantity in closing inventory only",
      "The quantity used in units actually sold",
    ],
    correct: 0,
    explanation: "If inventory is held at standard cost, any price difference must be stripped out as soon as the material arrives — so the price variance is based on the full quantity PURCHASED. Calculating it on issues is only appropriate when inventory is carried at actual cost; the earlier calculation also gives quicker feedback to the purchasing manager.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA3-D-15", paper: "MA", area: "D", type: "mcq",
    stem: "A production supervisor reports that machines repeatedly broke down during the period, leaving direct workers standing idle while paid. Which variance will MOST DIRECTLY capture the cost of these stoppages?",
    options: [
      "An adverse labour rate variance",
      "A favourable labour efficiency variance",
      "An adverse material price variance",
      "An adverse idle time variance",
    ],
    correct: 3,
    explanation: "Hours paid but not worked because of breakdowns are exactly what the idle time variance isolates (idle hours × standard rate, always adverse). The rate variance would only move if hourly PAY differed from standard, efficiency measures the pace of work during working hours, and material price is unrelated to stoppages.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA3-D-16", paper: "MA", area: "D", type: "mcq",
    stem: "Which of the following would explain a FAVOURABLE fixed overhead volume variance?",
    options: [
      "Actual fixed overhead expenditure was below budget",
      "Actual output exceeded budgeted output",
      "Actual output fell short of budgeted output",
      "Actual labour rates were below standard",
    ],
    correct: 1,
    explanation: "The volume variance compares actual output with budgeted output at the standard absorption rate — producing MORE than budget absorbs more fixed overhead, giving a favourable variance. Spending below budget drives the EXPENDITURE variance instead, output below budget would be adverse, and labour rates affect labour variances only.",
    marks: 2, difficulty: "easy",
  },

  /* ───────── E — Performance measurement (21) ───────── */
  {
    id: "MA3-E-01", paper: "MA", area: "E", type: "mcq",
    stem: "Tangmere Co budgeted 20,000 direct labour hours. Actual hours worked were 23,000, and the standard hours of the output produced were 20,700. The CAPACITY ratio is:",
    options: ["87.0%", "90.0%", "103.5%", "115.0%"],
    correct: 3,
    explanation: "Capacity ratio = actual hours worked ÷ budgeted hours = 23,000 ÷ 20,000 = 115% — the workforce put in more hours than planned. 90.0% is the EFFICIENCY ratio (20,700 ÷ 23,000), 103.5% is the PRODUCTION VOLUME ratio (20,700 ÷ 20,000), and 87.0% inverts the capacity fraction (20,000 ÷ 23,000).",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-E-02", paper: "MA", area: "E", type: "number",
    stem: "Yapton Co budgeted 8,000 direct labour hours for the period. The output actually produced represented 8,400 standard hours of work. What is the PRODUCTION VOLUME ratio, as a percentage?",
    numericAnswer: 105, unit: "%",
    explanation: "Production volume ratio = standard hours of output produced ÷ budgeted hours × 100 = 8,400 ÷ 8,000 = 105%: the business achieved 5% more production than planned. Trap: using actual hours WORKED in either position — those belong to the efficiency ratio (standard ÷ actual worked) and the capacity ratio (actual worked ÷ budgeted).",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-E-03", paper: "MA", area: "E", type: "mcq",
    stem: "Barnham Co's labour efficiency ratio is 96% and its capacity ratio is 110%. Its production volume ratio is:",
    options: ["87.3%", "103.0%", "105.6%", "206.0%"],
    correct: 2,
    explanation: "The ratios link multiplicatively: production volume = efficiency × capacity = 0.96 × 1.10 = 105.6% — because (standard hrs ÷ actual hrs) × (actual hrs ÷ budgeted hrs) = standard hrs ÷ budgeted hrs. 103.0% averages the two ratios, 206.0% adds them, and 87.3% divides efficiency by capacity — none respects the algebra.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-E-04", paper: "MA", area: "E", type: "mcq",
    stem: "A division currently earns an ROI of 18%. Its manager, whose bonus depends on divisional ROI, is offered a project with an expected return of 15%. The company's cost of capital is 12%. Which statement is correct?",
    options: [
      "The manager will accept the project, and acceptance is in the company's best interest",
      "The manager is likely to reject the project even though, at 15% versus a 12% cost of capital, the company would want it accepted",
      "The manager is likely to reject the project, and rejection is in the company's best interest",
      "Residual income would also signal rejection of the project",
    ],
    correct: 1,
    explanation: "The project's 15% return would DILUTE the division's 18% ROI, so an ROI-judged manager is motivated to reject it — yet it beats the 12% cost of capital, so it creates value for the company. This goal incongruence is ROI's classic flaw. Residual income would show a POSITIVE figure (15% − 12% on the outlay), correctly signalling acceptance — which is precisely why RI is often preferred.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA3-E-05", paper: "MA", area: "E", type: "number",
    stem: "A division earns an operating profit of $68,000 on capital employed of $400,000. Head office imputes an interest charge at 13% of capital employed. What is the division's RESIDUAL INCOME, in $?",
    numericAnswer: 16000, unit: "$",
    explanation: "RI = operating profit − (capital employed × imputed interest rate) = 68,000 − (400,000 × 13%) = 68,000 − 52,000 = $16,000. Traps: deducting 13% of PROFIT instead of 13% of capital (68,000 − 8,840 = $59,160), or reporting the $52,000 notional interest charge itself as the answer.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-E-06", paper: "MA", area: "E", type: "mcq",
    stem: "A division's annual profit has been constant for years, yet its ROI (based on the net book value of its assets) rises every year. The MOST likely explanation is that:",
    options: [
      "The division's assets are ageing, so accumulated depreciation keeps reducing capital employed",
      "The division is becoming genuinely more efficient each year",
      "Inflation is increasing the value of the asset base",
      "Profit margins are improving on stable sales",
    ],
    correct: 0,
    explanation: "With constant profit, a rising ROI must come from a shrinking denominator: depreciation reduces NBV each year, flattering ROI with no real improvement — and discouraging managers from replacing old assets (which would slash the ratio). Genuine efficiency or better margins would show up as rising PROFIT, and inflation raising the asset base would push ROI down, not up.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-E-07", paper: "MA", area: "E", type: "mcq",
    stem: "A division earns a profit of $100,000 on capital employed of $500,000 (ROI 20%). Its manager proposes scrapping equipment with a net book value of $50,000 that generates a profit of $8,000 a year (a 16% return). The company's cost of capital is 12%. The effect of the disposal is that divisional ROI:",
    options: [
      "Falls, so the manager will not proceed",
      "Rises to about 20.4% — but since the equipment earns 16%, above the 12% cost of capital, the disposal makes the company worse off",
      "Rises to about 22.2%, and the disposal also benefits the company",
      "Is unchanged, because both profit and capital employed fall",
    ],
    correct: 1,
    explanation: "New ROI = (100,000 − 8,000) ÷ (500,000 − 50,000) = 92,000 ÷ 450,000 ≈ 20.4%: shedding any asset earning below the CURRENT ROI lifts the ratio. But the asset returns 16%, above the 12% cost of capital, so the company loses value — an ROI-driven manager is rewarded for a harmful decision. 22.2% forgets to remove the asset's profit (100,000 ÷ 450,000), and the changes clearly do not cancel out.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA3-E-08", paper: "MA", area: "E", type: "number",
    stem: "Aldwick Co has revenue of $2,700,000 and capital employed of $1,800,000. What is its ASSET TURNOVER, in times?",
    numericAnswer: 1.5, unit: "times", tolerance: 0.01,
    explanation: "Asset turnover = revenue ÷ capital employed = 2,700,000 ÷ 1,800,000 = 1.5 times: each $1 of capital generates $1.50 of sales in the year. Trap: inverting the ratio (1,800 ÷ 2,700 = 0.67) or using profit instead of revenue in the numerator — profit ÷ capital employed is ROCE, a different ratio.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-E-09", paper: "MA", area: "E", type: "mcq",
    stem: "Felpham Co's ROCE is 15% and its asset turnover is 2.5 times. Its operating profit margin is:",
    options: ["6.0%", "12.5%", "16.7%", "37.5%"],
    correct: 0,
    explanation: "ROCE = margin × asset turnover, so margin = ROCE ÷ asset turnover = 15% ÷ 2.5 = 6.0% (check: 6% × 2.5 = 15%). 37.5% multiplies instead of divides, 12.5% subtracts the turnover from the ROCE, and 16.7% divides the ratios the wrong way round (2.5 ÷ 15).",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-E-10", paper: "MA", area: "E", type: "mcq",
    stem: "Bognor Co reports: revenue $400,000; cost of sales $260,000; operating expenses $60,000. Its GROSS PROFIT margin is:",
    options: ["20%", "35%", "53.8%", "65%"],
    correct: 1,
    explanation: "Gross profit = 400,000 − 260,000 = $140,000; margin = 140,000 ÷ 400,000 = 35% of REVENUE. 20% is the OPERATING profit margin ((140,000 − 60,000) ÷ 400,000) — a different ratio; 65% is cost of sales as a share of revenue; 53.8% is the mark-up (gross profit ÷ cost of sales), which uses the wrong denominator.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA3-E-11", paper: "MA", area: "E", type: "mcq",
    stem: "Pagham Co's current assets are: inventory $30,000, receivables $45,000, cash $5,000. Current liabilities are $40,000. Its QUICK (acid test) ratio is:",
    options: ["0.8", "1.13", "1.25", "2.0"],
    correct: 2,
    explanation: "Quick ratio excludes inventory (the least liquid current asset): (45,000 + 5,000) ÷ 40,000 = 1.25. 2.0 is the CURRENT ratio (80,000 ÷ 40,000 — inventory wrongly included), 1.13 also strips out the cash (45,000 ÷ 40,000), and 0.8 inverts the fraction (liabilities ÷ quick assets).",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-E-12", paper: "MA", area: "E", type: "mcq",
    stem: "Ford Co's cost of sales for the year was $730,000 and revenue was $990,000. Inventory was $60,000 at the start of the year and $120,000 at the end. Using AVERAGE inventory and a 365-day year, the inventory holding period is:",
    options: ["8 days", "33 days", "45 days", "60 days"],
    correct: 2,
    explanation: "Average inventory = (60,000 + 120,000) ÷ 2 = $90,000. Holding period = 90,000 ÷ 730,000 × 365 = 45 days. 60 days uses closing inventory only, 33 days divides by REVENUE instead of cost of sales (inventory is carried at cost, so cost of sales is the consistent base), and 8 is the inventory TURNOVER in times (730 ÷ 90) misread as days.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-E-13", paper: "MA", area: "E", type: "number",
    stem: "Clymping Co's credit sales for the year were $876,000 and year-end trade receivables were $96,000. Using a 365-day year, what is the receivables collection period, in days?",
    numericAnswer: 40, unit: "days",
    explanation: "Receivables days = receivables ÷ credit sales × 365 = 96,000 ÷ 876,000 × 365 = 40 days: customers take about 40 days to pay. Trap: inverting the fraction (876 ÷ 96 = 9.1 gives turnover in times, not days) or using total costs instead of credit sales as the denominator.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA3-E-14", paper: "MA", area: "E", type: "mcq",
    stem: "Walberton Co has an inventory holding period of 50 days, a receivables collection period of 40 days and a payables payment period of 35 days. Its cash operating cycle (working capital cycle) is:",
    options: ["25 days", "45 days", "55 days", "125 days"],
    correct: 2,
    explanation: "Cash cycle = inventory days + receivables days − payables days = 50 + 40 − 35 = 55 days: cash is tied up while goods sit in store and customers pay, but supplier credit funds part of that gap. 125 adds all three (treating payables as a further delay in receiving cash), 45 subtracts receivables instead of payables, and 25 subtracts inventory days.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-E-15", paper: "MA", area: "E", type: "mcq",
    stem: "Slinfold Co is financed by $400,000 of long-term debt and $600,000 of equity. Measuring gearing as debt ÷ (debt + equity), its gearing ratio is:",
    options: ["40%", "60%", "66.7%", "150%"],
    correct: 0,
    explanation: "Gearing = 400,000 ÷ (400,000 + 600,000) = 40% of total long-term capital is debt. 66.7% is the debt-to-EQUITY version of the ratio (400 ÷ 600) — a valid measure, but not the formula specified; 60% is the equity share mislabelled; 150% inverts debt-to-equity (600 ÷ 400).",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA3-E-16", paper: "MA", area: "E", type: "number",
    stem: "Warnham Co's operating profit (before interest and tax) for the year was $120,000 and its interest charge was $15,000. What is its INTEREST COVER, in times?",
    numericAnswer: 8, unit: "times",
    explanation: "Interest cover = profit before interest and tax ÷ interest = 120,000 ÷ 15,000 = 8 times — operating profit could fall to an eighth of its level before interest was no longer covered. Trap: using profit AFTER interest in the numerator (105,000 ÷ 15,000 = 7) or inverting the ratio (15 ÷ 120 = 0.125).",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA3-E-17", paper: "MA", area: "E", type: "mcq",
    stem: "A telephone customer-support centre wants a non-financial performance indicator of service QUALITY. The most suitable measure is:",
    options: [
      "The number of calls handled per operator per hour",
      "The average wage cost per operator",
      "Total operating cost of the centre per month",
      "The percentage of queries resolved on the first call",
    ],
    correct: 3,
    explanation: "First-call resolution measures whether the service actually solved the customer's problem — the essence of quality. Calls per hour measures PRODUCTIVITY (and can conflict with quality if staff rush calls), while wage cost and total cost are financial measures of input, saying nothing about how well customers were served.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA3-E-18", paper: "MA", area: "E", type: "mcq",
    stem: "A company's balanced scorecard includes two measures: average training days per employee, and the percentage of revenue earned from products launched in the last two years. These belong to which perspective?",
    options: [
      "Customer",
      "Internal business processes",
      "Financial",
      "Innovation and learning (learning and growth)",
    ],
    correct: 3,
    explanation: "Both measures ask 'can we continue to improve and create value?' — staff capability development and new-product success are the classic innovation/learning-and-growth indicators. Customer measures look at satisfaction and retention, internal process measures at operational quality and speed, and financial measures at returns to shareholders.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA3-E-19", paper: "MA", area: "E", type: "mcq",
    stem: "In value-for-money analysis for public sector bodies (the 'three Es'), ECONOMY means:",
    options: [
      "Maximising the output produced from a given quantity of inputs",
      "The extent to which the organisation's objectives are achieved",
      "Generating a surplus of income over expenditure",
      "Obtaining resources (inputs) of appropriate quality at the lowest cost",
    ],
    correct: 3,
    explanation: "Economy is about the terms on which INPUTS are acquired — suitable quality, minimum cost. Output-per-input is EFFICIENCY, and achieving objectives is EFFECTIVENESS: the three Es cover inputs, the input-output relationship, and outcomes respectively. Public bodies are not judged on surpluses, which is why the three Es replace profit measures.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA3-E-20", paper: "MA", area: "E", type: "mcq",
    stem: "A state school monitors three indicators: (1) cost per teaching hour delivered; (2) the pupil-to-teacher ratio; (3) the percentage of pupils achieving their target exam grades. Which indicator measures EFFECTIVENESS?",
    options: ["Indicator (3) only", "Indicator (1) only", "Indicator (2) only", "All three indicators"],
    correct: 0,
    explanation: "Effectiveness compares OUTCOMES with objectives — exam results against targets is exactly that. Cost per teaching hour gauges economy (the price of inputs), and the pupil-teacher ratio gauges efficiency (output stretched from staff resources). Treating all three as effectiveness blurs the distinct questions the three Es are designed to separate.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA3-E-21", paper: "MA", area: "E", type: "mcq",
    stem: "When evaluating the performance of a divisional MANAGER (rather than the division itself), which cost should be EXCLUDED?",
    options: [
      "Wages of divisional staff, negotiated by the divisional manager",
      "Materials purchased by the division's own buying team",
      "Power costs of machinery the manager chooses how to run",
      "Head office administrative costs apportioned to the division",
    ],
    correct: 3,
    explanation: "The controllability principle: a manager should be judged only on items they can influence. Apportioned head-office costs are set centrally and change nothing the manager does, so they belong in an assessment of the DIVISION's economic performance, not the manager's. Wages, materials and power usage are all within the manager's control.",
    marks: 2, difficulty: "easy",
  },
]
