import type { Flashcard } from "@/lib/acca-flashcards"

/*
 * Scholify — ACCA flashcards, set S1 (Strategic Professional Essentials).
 *
 * 120 memorisation cards: 60 for SBL (Strategic Business Leader) and
 * 60 for SBR (Strategic Business Reporting). Original, syllabus-aligned
 * facts, framework components, standards and thresholds that reward
 * spaced repetition. Spread ~12 cards across each paper's syllabus areas.
 */

export const FLASHCARDS_S1: Flashcard[] = [
  /* ============================ SBL ============================ */

  /* --- Area A: Leadership & governance --- */
  { id: "SBL-FC-01", paper: "SBL", area: "A", front: "Cadbury's definition of corporate governance", back: "\"The system by which companies are directed and controlled.\" It concerns the relationship between the board, shareholders and other stakeholders." },
  { id: "SBL-FC-02", paper: "SBL", area: "A", front: "Agency theory — the core relationship", back: "Shareholders (principals) delegate control of the company to directors (agents). Agency problems arise when agents pursue their own interests rather than the principals'." },
  { id: "SBL-FC-03", paper: "SBL", area: "A", front: "Agency costs — the three types", back: "Monitoring costs (e.g. audit and reporting), bonding costs (agents demonstrating alignment) and the residual loss (remaining divergence of interests despite the above)." },
  { id: "SBL-FC-04", paper: "SBL", area: "A", front: "The four roles of non-executive directors (Higgs)", back: "Strategy (contribute and challenge), Scrutiny (monitor executive performance), Risk (ensure controls are robust) and People (appoint, remove and set remuneration of executives)." },
  { id: "SBL-FC-05", paper: "SBL", area: "A", front: "The four principal board committees", back: "Nomination, remuneration, audit and risk committees — staffed wholly or mainly by independent non-executive directors." },
  { id: "SBL-FC-06", paper: "SBL", area: "A", front: "Unitary vs two-tier board structure", back: "Unitary: a single board of executives and NEDs sharing legal responsibility. Two-tier: a separate supervisory board (oversight, mainly NEDs) sitting above a management board (day-to-day running)." },
  { id: "SBL-FC-07", paper: "SBL", area: "A", front: "Rules-based vs principles-based governance", back: "Rules-based (e.g. US Sarbanes-Oxley): legally binding, box-ticking compliance. Principles-based (e.g. UK Code): broad principles applied with judgement on a \"comply or explain\" basis." },
  { id: "SBL-FC-08", paper: "SBL", area: "A", front: "\"Comply or explain\"", back: "A company either complies with a governance provision or publicly explains why it has departed from it — allowing flexibility while preserving transparency and accountability to shareholders." },
  { id: "SBL-FC-09", paper: "SBL", area: "A", front: "Insider vs outsider governance systems", back: "Insider: ownership concentrated in a few long-term holders (banks, families); e.g. Germany, Japan. Outsider: ownership dispersed among many external investors; e.g. UK, US." },
  { id: "SBL-FC-10", paper: "SBL", area: "A", front: "Separation of chairman and CEO — why", back: "Splitting the roles prevents unfettered power over both running the company (CEO) and running the board (chairman), improving balance, accountability and board effectiveness." },
  { id: "SBL-FC-11", paper: "SBL", area: "A", front: "Transaction cost theory (Williamson)", back: "Firms organise transactions to minimise costs. Managers may be opportunistic (bounded rationality, self-interest), so governance mechanisms are needed to safeguard the transactions of the firm." },
  { id: "SBL-FC-12", paper: "SBL", area: "A", front: "Purpose of an audit committee", back: "An independent NED committee that oversees financial reporting integrity, the external audit relationship, internal controls and internal audit — providing a buffer between management and auditors." },

  /* --- Area B: Strategy --- */
  { id: "SBL-FC-13", paper: "SBL", area: "B", front: "Porter's five forces", back: "Threat of new entrants, bargaining power of suppliers, bargaining power of buyers, threat of substitute products, and competitive rivalry among existing firms." },
  { id: "SBL-FC-14", paper: "SBL", area: "B", front: "Porter's three generic strategies", back: "Cost leadership, differentiation, and focus (cost focus or differentiation focus). Firms that fail to choose become \"stuck in the middle\"." },
  { id: "SBL-FC-15", paper: "SBL", area: "B", front: "Ansoff's product-market matrix", back: "Market penetration (existing product/existing market), product development (new product/existing market), market development (existing product/new market), diversification (new product/new market)." },
  { id: "SBL-FC-16", paper: "SBL", area: "B", front: "The BCG matrix — the four quadrants", back: "Stars (high growth/high share), cash cows (low growth/high share), question marks (high growth/low share) and dogs (low growth/low share)." },
  { id: "SBL-FC-17", paper: "SBL", area: "B", front: "PESTEL analysis", back: "Political, Economic, Social, Technological, Environmental (ecological) and Legal — a framework for scanning the macro-environment." },
  { id: "SBL-FC-18", paper: "SBL", area: "B", front: "Porter's value chain — the five primary activities", back: "Inbound logistics, operations, outbound logistics, marketing & sales, and service." },
  { id: "SBL-FC-19", paper: "SBL", area: "B", front: "Porter's value chain — the four support activities", back: "Firm infrastructure, human resource management, technology development, and procurement." },
  { id: "SBL-FC-20", paper: "SBL", area: "B", front: "Johnson, Scholes & Whittington — SAF test for strategy", back: "Suitability (does it address the strategic position?), Acceptability (returns, risk, stakeholder reactions?) and Feasibility (do we have the resources/capabilities?)." },
  { id: "SBL-FC-21", paper: "SBL", area: "B", front: "Strategic drift", back: "The gradual failure of a strategy to keep pace with a changing environment, so the organisation's position deteriorates until incremental change is no longer enough and transformational change is forced." },
  { id: "SBL-FC-22", paper: "SBL", area: "B", front: "Mendelow's matrix — the four stakeholder strategies", back: "High power/high interest: Key players (manage closely). High power/low interest: Keep satisfied. Low power/high interest: Keep informed. Low power/low interest: Minimal effort." },
  { id: "SBL-FC-23", paper: "SBL", area: "B", front: "The rational (logical) model of strategy", back: "Three stages: strategic analysis (understand position), strategic choice (generate, evaluate and select options), and strategic implementation (put the chosen strategy into action)." },
  { id: "SBL-FC-24", paper: "SBL", area: "B", front: "Bowman's strategy clock", back: "Eight competitive positions plotted on price versus perceived value — from \"low price/low value\" through hybrid and differentiation routes to uncompetitive high-price/low-value positions destined to fail." },

  /* --- Area C: Risk & control --- */
  { id: "SBL-FC-25", paper: "SBL", area: "C", front: "COSO ERM (2017) — the five components", back: "Governance & culture; Strategy & objective-setting; Performance; Review & revision; and Information, communication & reporting." },
  { id: "SBL-FC-26", paper: "SBL", area: "C", front: "Risk exposure — the formula", back: "Risk exposure = likelihood (probability of the event) × impact (size of the consequence if it occurs)." },
  { id: "SBL-FC-27", paper: "SBL", area: "C", front: "TARA — the four risk responses", back: "Transfer (share, e.g. insure), Avoid (terminate the activity), Reduce (treat/mitigate with controls) and Accept (tolerate/retain the risk)." },
  { id: "SBL-FC-28", paper: "SBL", area: "C", front: "The three lines of defence", back: "1st line: operational management owns and manages risk. 2nd line: risk and compliance functions oversee and set frameworks. 3rd line: internal audit gives independent assurance to the board." },
  { id: "SBL-FC-29", paper: "SBL", area: "C", front: "Risk appetite vs risk capacity", back: "Risk appetite: the amount of risk an entity is willing to seek or accept to pursue its objectives. Risk capacity: the maximum amount of risk it is actually able to bear." },
  { id: "SBL-FC-30", paper: "SBL", area: "C", front: "Gross (inherent) vs residual (net) risk", back: "Gross/inherent risk is the level of risk before any controls are applied; residual/net risk is what remains after controls have been put in place." },
  { id: "SBL-FC-31", paper: "SBL", area: "C", front: "The three broad categories of business risk", back: "Strategic risk (from strategy and the environment), operational risk (from internal processes, people and systems) and financial risk (from financing, credit, liquidity and market movements)." },
  { id: "SBL-FC-32", paper: "SBL", area: "C", front: "The fraud triangle", back: "Three conditions present when fraud occurs: Opportunity (weak controls), Motivation/pressure (an incentive or need), and Rationalisation (justifying the act to oneself)." },
  { id: "SBL-FC-33", paper: "SBL", area: "C", front: "Contents of a risk register", back: "For each risk: a description, the owner, likelihood and impact assessment, the gross and residual rating, the controls/response in place, and the action required." },
  { id: "SBL-FC-34", paper: "SBL", area: "C", front: "Enterprise Risk Management (ERM) — definition", back: "A firm-wide, integrated approach to identifying, assessing and managing all of an organisation's risks together (a \"portfolio\" view) and aligning risk-taking with strategy and appetite." },
  { id: "SBL-FC-35", paper: "SBL", area: "C", front: "Purpose of internal control (Turnbull view)", back: "To facilitate effective and efficient operations, ensure reliable internal and external reporting, and safeguard compliance with laws and regulations — thereby helping the entity meet its objectives." },
  { id: "SBL-FC-36", paper: "SBL", area: "C", front: "Risk mapping (the heat map)", back: "Plotting each risk on a grid of likelihood against impact to prioritise responses — high-likelihood/high-impact risks demand the most urgent management attention." },

  /* --- Area D: Technology, data & innovation --- */
  { id: "SBL-FC-37", paper: "SBL", area: "D", front: "Big data — the five Vs", back: "Volume (amount), Velocity (speed generated), Variety (structured and unstructured forms), Veracity (accuracy/reliability) and Value (usefulness once analysed)." },
  { id: "SBL-FC-38", paper: "SBL", area: "D", front: "The four types of data analytics", back: "Descriptive (what happened?), Diagnostic (why did it happen?), Predictive (what is likely to happen?) and Prescriptive (what should we do about it?)." },
  { id: "SBL-FC-39", paper: "SBL", area: "D", front: "Cloud computing — the three service models", back: "IaaS (Infrastructure as a Service), PaaS (Platform as a Service) and SaaS (Software as a Service)." },
  { id: "SBL-FC-40", paper: "SBL", area: "D", front: "The CIA triad of information security", back: "Confidentiality (only authorised access), Integrity (data is accurate and unaltered) and Availability (accessible when needed)." },
  { id: "SBL-FC-41", paper: "SBL", area: "D", front: "Disruptive innovation (Christensen)", back: "A cheaper, simpler product that first serves overlooked/low-end customers, then improves until it displaces established competitors — who ignored it because it initially underperformed on traditional measures." },
  { id: "SBL-FC-42", paper: "SBL", area: "D", front: "Blockchain / distributed ledger technology", back: "A decentralised, shared and immutable ledger where transactions are grouped into cryptographically linked blocks and validated across a network — no single trusted intermediary is required." },
  { id: "SBL-FC-43", paper: "SBL", area: "D", front: "Structured vs unstructured data", back: "Structured data is organised in a defined format (e.g. database rows and columns). Unstructured data has no predefined model (e.g. emails, images, social-media posts, video)." },
  { id: "SBL-FC-44", paper: "SBL", area: "D", front: "Business process reengineering (Hammer & Champy)", back: "The fundamental rethinking and radical redesign of business processes to achieve dramatic improvements in performance measures such as cost, quality, service and speed." },
  { id: "SBL-FC-45", paper: "SBL", area: "D", front: "The Internet of Things (IoT)", back: "A network of physical devices embedded with sensors and connectivity that collect and exchange data automatically, enabling real-time monitoring, automation and richer data capture." },
  { id: "SBL-FC-46", paper: "SBL", area: "D", front: "Artificial intelligence vs machine learning", back: "AI is the broad field of machines performing tasks that need human-like intelligence. Machine learning is a subset in which systems learn patterns from data and improve without being explicitly programmed." },
  { id: "SBL-FC-47", paper: "SBL", area: "D", front: "How e-business affects Porter's five forces", back: "The internet typically lowers entry barriers, increases buyer power (price transparency), widens substitutes and intensifies rivalry — generally eroding average industry profitability." },
  { id: "SBL-FC-48", paper: "SBL", area: "D", front: "Data governance", back: "The framework of policies, roles, standards and controls ensuring data is accurate, secure, consistent and used appropriately (including compliance with data-protection law) across the organisation." },

  /* --- Area E: Professional & ethical skills --- */
  { id: "SBL-FC-49", paper: "SBL", area: "E", front: "The five professional skills assessed in SBL", back: "Communication, Commercial acumen, Analysis, Scepticism and Evaluation." },
  { id: "SBL-FC-50", paper: "SBL", area: "E", front: "ACCA Code — the five fundamental principles", back: "Integrity, Objectivity, Professional competence & due care, Confidentiality, and Professional behaviour." },
  { id: "SBL-FC-51", paper: "SBL", area: "E", front: "The five threats to the fundamental principles", back: "Self-interest, Self-review, Advocacy, Familiarity and Intimidation threats." },
  { id: "SBL-FC-52", paper: "SBL", area: "E", front: "Kohlberg's three levels of moral development", back: "Pre-conventional (self-interest, avoiding punishment), Conventional (conforming to expectations and law) and Post-conventional (principled, based on universal ethical values)." },
  { id: "SBL-FC-53", paper: "SBL", area: "E", front: "Tucker's five-question ethical model", back: "Is the decision Profitable? Legal? Fair? Right? and Sustainable (environmentally sound)?" },
  { id: "SBL-FC-54", paper: "SBL", area: "E", front: "Carroll's CSR pyramid", back: "From the base up: Economic responsibilities (be profitable), Legal (obey the law), Ethical (do what is right) and Philanthropic (be a good corporate citizen)." },
  { id: "SBL-FC-55", paper: "SBL", area: "E", front: "Gray, Owen & Adams — seven positions on social responsibility", back: "Pristine capitalists, expedients, proponents of the social contract, social ecologists, socialists, radical feminists, and deep ecologists — ranging from pure shareholder focus to deep-green stances." },
  { id: "SBL-FC-56", paper: "SBL", area: "E", front: "Professional scepticism", back: "An attitude of a questioning mind, alertness to conditions that may indicate error or fraud, and a critical assessment of evidence — not simply accepting information at face value." },
  { id: "SBL-FC-57", paper: "SBL", area: "E", front: "Integrated reporting <IR> — the six capitals", back: "Financial, Manufactured, Intellectual, Human, Social & relationship, and Natural capital." },
  { id: "SBL-FC-58", paper: "SBL", area: "E", front: "The triple bottom line", back: "Measuring performance against three dimensions: People (social), Planet (environmental) and Profit (economic) — the \"3 Ps\".", },
  { id: "SBL-FC-59", paper: "SBL", area: "E", front: "The American Accounting Association (AAA) ethical decision model", back: "A seven-step model: establish the facts; identify the ethical issues; identify the norms/principles/values; identify alternative courses of action; match action to values; consider the consequences; and reach a decision." },
  { id: "SBL-FC-60", paper: "SBL", area: "E", front: "Confidentiality — when disclosure is permitted", back: "When authorised by the client, required by law (e.g. court order, money-laundering reporting), or where there is a professional duty/right to disclose and it is not prohibited by law." },

  /* ============================ SBR ============================ */

  /* --- Area A: Conceptual & regulatory framework --- */
  { id: "SBR-FC-01", paper: "SBR", area: "A", front: "The two fundamental qualitative characteristics", back: "Relevance and faithful representation. (Faithful representation means complete, neutral and free from error.)" },
  { id: "SBR-FC-02", paper: "SBR", area: "A", front: "The four enhancing qualitative characteristics", back: "Comparability, verifiability, timeliness and understandability." },
  { id: "SBR-FC-03", paper: "SBR", area: "A", front: "Definition of an asset (2018 Conceptual Framework)", back: "A present economic resource controlled by the entity as a result of past events. An economic resource is a right that has the potential to produce economic benefits." },
  { id: "SBR-FC-04", paper: "SBR", area: "A", front: "Definition of a liability (2018 Conceptual Framework)", back: "A present obligation of the entity to transfer an economic resource as a result of past events." },
  { id: "SBR-FC-05", paper: "SBR", area: "A", front: "The five elements of financial statements", back: "Assets, liabilities and equity (financial position); income and expenses (financial performance)." },
  { id: "SBR-FC-06", paper: "SBR", area: "A", front: "Measurement bases in the Conceptual Framework", back: "Historical cost, and current value — which comprises fair value, value in use (for assets) / fulfilment value (for liabilities), and current cost." },
  { id: "SBR-FC-07", paper: "SBR", area: "A", front: "IAS 8 — change in accounting policy vs estimate", back: "A change in accounting policy is applied retrospectively (restate comparatives). A change in accounting estimate is applied prospectively (current and future periods only)." },
  { id: "SBR-FC-08", paper: "SBR", area: "A", front: "IAS 8 — prior period errors", back: "Corrected retrospectively by restating the comparative figures, or the opening balances of the earliest period presented if the error is older." },
  { id: "SBR-FC-09", paper: "SBR", area: "A", front: "Recognition criteria (2018 Conceptual Framework)", back: "An item is recognised only if doing so provides users with relevant information and a faithful representation — subject to the cost constraint. (There is no longer a probability threshold.)" },
  { id: "SBR-FC-10", paper: "SBR", area: "A", front: "The two concepts of capital maintenance", back: "Financial capital maintenance (profit earned only if net assets in money/real terms exceed the opening amount) and physical capital maintenance (profit only if operating capability is maintained)." },
  { id: "SBR-FC-11", paper: "SBR", area: "A", front: "The going concern assumption", back: "Financial statements are prepared on the basis that the entity will continue in operation for the foreseeable future, with no intention or need to liquidate or curtail materially the scale of operations." },
  { id: "SBR-FC-12", paper: "SBR", area: "A", front: "Substance over form", back: "Transactions should be accounted for in accordance with their economic reality (substance), not merely their legal form — a key aspect of faithful representation." },

  /* --- Area B: Reporting the financial performance of entities --- */
  { id: "SBR-FC-13", paper: "SBR", area: "B", front: "IFRS 15 — the five-step revenue model", back: "1) Identify the contract; 2) Identify the performance obligations; 3) Determine the transaction price; 4) Allocate the price to the obligations; 5) Recognise revenue as each obligation is satisfied." },
  { id: "SBR-FC-14", paper: "SBR", area: "B", front: "IAS 16 — the two measurement models for PP&E", back: "The cost model (cost less accumulated depreciation and impairment) and the revaluation model (fair value at revaluation date less subsequent depreciation and impairment)." },
  { id: "SBR-FC-15", paper: "SBR", area: "B", front: "IAS 36 — recoverable amount", back: "The higher of (a) fair value less costs of disposal and (b) value in use. An impairment loss arises when carrying amount exceeds recoverable amount." },
  { id: "SBR-FC-16", paper: "SBR", area: "B", front: "IAS 37 — the three provision recognition criteria", back: "A present obligation (legal or constructive) from a past event; a probable outflow of economic resources; and a reliable estimate can be made of the amount." },
  { id: "SBR-FC-17", paper: "SBR", area: "B", front: "IFRS 16 — lessee accounting", back: "Recognise a right-of-use asset and a lease liability for almost all leases (exemptions: short-term leases of 12 months or less, and low-value assets)." },
  { id: "SBR-FC-18", paper: "SBR", area: "B", front: "IAS 38 — research vs development", back: "Research costs are expensed as incurred. Development costs are capitalised only if all the strict criteria (PIRATE: probable benefits, intention, resources, ability, technical feasibility, expenditure measurable) are met." },
  { id: "SBR-FC-19", paper: "SBR", area: "B", front: "IAS 12 — deferred tax", back: "Tax attributable to temporary differences — the difference between the carrying amount of an asset/liability and its tax base. Deferred tax is measured using tax rates expected when the item reverses." },
  { id: "SBR-FC-20", paper: "SBR", area: "B", front: "IFRS 5 — non-current assets held for sale", back: "Measured at the lower of carrying amount and fair value less costs to sell; depreciation ceases; presented separately from other assets." },
  { id: "SBR-FC-21", paper: "SBR", area: "B", front: "IAS 40 — investment property measurement", back: "After initial cost, choose either the cost model or the fair value model (as a policy for all investment property). Under the fair value model, gains/losses go to profit or loss and no depreciation is charged." },
  { id: "SBR-FC-22", paper: "SBR", area: "B", front: "IFRS 13 — the fair value hierarchy", back: "Level 1: quoted prices in active markets for identical assets/liabilities. Level 2: other observable inputs. Level 3: unobservable inputs (entity's own assumptions)." },
  { id: "SBR-FC-23", paper: "SBR", area: "B", front: "IAS 20 — accounting for government grants", back: "Recognised in profit or loss on a systematic basis over the periods matching the related costs. Grants relating to assets: either net off against the asset or treat as deferred income." },
  { id: "SBR-FC-24", paper: "SBR", area: "B", front: "IFRS 2 — equity-settled share-based payment", back: "Measured at the fair value of the goods/services or, for employees, the fair value of the equity instruments at grant date — charged to profit or loss over the vesting period, with a credit to equity." },

  /* --- Area C: Groups and consolidations --- */
  { id: "SBR-FC-25", paper: "SBR", area: "C", front: "Goodwill on acquisition — the formula", back: "Consideration transferred + NCI at acquisition + fair value of any previously held interest − fair value of identifiable net assets acquired." },
  { id: "SBR-FC-26", paper: "SBR", area: "C", front: "IFRS 10 — the three elements of control", back: "Power over the investee; exposure, or rights, to variable returns from involvement with it; and the ability to use that power to affect those returns." },
  { id: "SBR-FC-27", paper: "SBR", area: "C", front: "IFRS 3 — the two methods of measuring NCI", back: "At fair value (the \"full goodwill\" method) or at the NCI's proportionate share of the acquiree's identifiable net assets (the \"partial goodwill\" method)." },
  { id: "SBR-FC-28", paper: "SBR", area: "C", front: "IAS 28 — associates: definition and method", back: "An associate is an entity over which the investor has significant influence (presumed with 20%–50% of voting rights). Accounted for using the equity method." },
  { id: "SBR-FC-29", paper: "SBR", area: "C", front: "IFRS 11 — joint operation vs joint venture", back: "Joint operation: parties have rights to the assets and obligations for the liabilities — account for your own share of each. Joint venture: parties have rights to the net assets — use the equity method." },
  { id: "SBR-FC-30", paper: "SBR", area: "C", front: "PURP — provision for unrealised profit", back: "Profit on intra-group sales still held in closing inventory must be eliminated on consolidation — reduce inventory and the selling company's profit (adjust NCI if the seller is the subsidiary)." },
  { id: "SBR-FC-31", paper: "SBR", area: "C", front: "Bargain purchase (negative goodwill)", back: "Where net assets acquired exceed the consideration and NCI, first reassess the figures; any remaining excess is recognised immediately as a gain in profit or loss." },
  { id: "SBR-FC-32", paper: "SBR", area: "C", front: "Step acquisition achieving control", back: "Remeasure the previously held equity interest to fair value at the date control is obtained, recognising the gain or loss in profit or loss; then apply acquisition (goodwill) accounting." },
  { id: "SBR-FC-33", paper: "SBR", area: "C", front: "Disposal resulting in loss of control", back: "Derecognise the subsidiary's assets, liabilities and NCI; recognise the fair value of consideration received and any retained interest at fair value; the resulting gain or loss goes to profit or loss." },
  { id: "SBR-FC-34", paper: "SBR", area: "C", front: "Fair value adjustments at acquisition", back: "The subsidiary's identifiable assets and liabilities are brought in at fair value at the acquisition date; these adjustments (and their post-acquisition depreciation) flow through the consolidation and affect goodwill." },
  { id: "SBR-FC-35", paper: "SBR", area: "C", front: "Consolidation — basic mechanics", back: "Combine 100% of the parent's and subsidiary's assets, liabilities, income and expenses line by line; eliminate the investment against equity (creating goodwill); and remove all intra-group balances and transactions." },
  { id: "SBR-FC-36", paper: "SBR", area: "C", front: "Goodwill impairment and NCI", back: "Goodwill is tested for impairment annually (not amortised). Under the full goodwill method any impairment is split between the parent and NCI; under partial goodwill it is charged only to the parent's share." },

  /* --- Area D: Financial instruments & employee benefits --- */
  { id: "SBR-FC-37", paper: "SBR", area: "D", front: "IFRS 9 — the three classification categories for financial assets", back: "Amortised cost; Fair value through other comprehensive income (FVOCI); and Fair value through profit or loss (FVTPL)." },
  { id: "SBR-FC-38", paper: "SBR", area: "D", front: "IFRS 9 — the two tests for classifying financial assets", back: "The business model test (why the asset is held) and the contractual cash flow characteristics test — whether cash flows are solely payments of principal and interest (SPPI)." },
  { id: "SBR-FC-39", paper: "SBR", area: "D", front: "IFRS 9 — the impairment model", back: "The expected credit loss (ECL) model. Stage 1: 12-month ECL. Stages 2 & 3: lifetime ECL once credit risk has increased significantly (Stage 3 = credit-impaired)." },
  { id: "SBR-FC-40", paper: "SBR", area: "D", front: "IFRS 9 — the three types of hedge accounting", back: "Fair value hedge, cash flow hedge, and hedge of a net investment in a foreign operation." },
  { id: "SBR-FC-41", paper: "SBR", area: "D", front: "IAS 32 — liability vs equity classification", back: "An instrument is a financial liability if there is a contractual obligation to deliver cash or another financial asset; it is equity if it evidences a residual interest with no such obligation." },
  { id: "SBR-FC-42", paper: "SBR", area: "D", front: "Compound financial instruments — split accounting", back: "A convertible bond is split into a liability component (present value of cash flows at the market rate for similar non-convertible debt) and an equity component (the residual)." },
  { id: "SBR-FC-43", paper: "SBR", area: "D", front: "The effective interest rate method", back: "Amortised cost instruments accrue interest at the effective rate — the rate that discounts estimated future cash flows to the instrument's net carrying amount — spreading fees and discounts over its life." },
  { id: "SBR-FC-44", paper: "SBR", area: "D", front: "IAS 19 — defined contribution vs defined benefit plans", back: "Defined contribution: employer pays fixed contributions and bears no further obligation (charge the contribution to P/L). Defined benefit: employer promises a specified benefit and bears the actuarial and investment risk." },
  { id: "SBR-FC-45", paper: "SBR", area: "D", front: "IAS 19 — the three components of defined benefit cost", back: "Service cost (to profit or loss), net interest on the net defined benefit liability/asset (to profit or loss), and remeasurements (to other comprehensive income)." },
  { id: "SBR-FC-46", paper: "SBR", area: "D", front: "IAS 19 — the net defined benefit liability/asset", back: "Present value of the defined benefit obligation less the fair value of plan assets (an asset is capped by the \"asset ceiling\")." },
  { id: "SBR-FC-47", paper: "SBR", area: "D", front: "IAS 19 — treatment of remeasurements", back: "Remeasurements (actuarial gains/losses and the return on plan assets excluding net interest) are recognised in OCI and are NOT subsequently reclassified to profit or loss." },
  { id: "SBR-FC-48", paper: "SBR", area: "D", front: "IFRS 9 — derecognition of a financial asset", back: "Derecognise when the contractual rights to the cash flows expire, or when the asset is transferred and substantially all the risks and rewards of ownership pass to the transferee." },

  /* --- Area E: Interpretation & current issues --- */
  { id: "SBR-FC-49", paper: "SBR", area: "E", front: "Return on capital employed (ROCE)", back: "(Profit before interest and tax ÷ Capital employed) × 100%, where capital employed = total assets − current liabilities (or equity + non-current debt). A key measure of profitability/efficiency." },
  { id: "SBR-FC-50", paper: "SBR", area: "E", front: "Gearing ratio", back: "Debt ÷ (Debt + Equity), or Debt ÷ Equity. Measures financial risk — the proportion of the business financed by borrowing rather than equity." },
  { id: "SBR-FC-51", paper: "SBR", area: "E", front: "Current ratio and quick (acid-test) ratio", back: "Current ratio = current assets ÷ current liabilities. Quick ratio = (current assets − inventory) ÷ current liabilities. Both measure short-term liquidity." },
  { id: "SBR-FC-52", paper: "SBR", area: "E", front: "IAS 33 — basic earnings per share", back: "Profit or loss attributable to ordinary equity holders of the parent ÷ weighted average number of ordinary shares in issue during the period." },
  { id: "SBR-FC-53", paper: "SBR", area: "E", front: "IAS 33 — diluted EPS", back: "Adjusts basic EPS for the effect of all dilutive potential ordinary shares (e.g. convertibles, options), showing the worst-case reduction in EPS if they were converted/exercised." },
  { id: "SBR-FC-54", paper: "SBR", area: "E", front: "Interest cover", back: "Profit before interest and tax ÷ finance costs (interest). Shows how many times profit covers interest — a measure of the entity's ability to meet its debt-servicing obligations." },
  { id: "SBR-FC-55", paper: "SBR", area: "E", front: "Creative accounting / earnings management", back: "Using the flexibility in accounting rules (choice of policy, estimates, timing, off-balance-sheet structures) to present a more favourable picture than the underlying reality — undermining faithful representation." },
  { id: "SBR-FC-56", paper: "SBR", area: "E", front: "IFRS S1 and IFRS S2 (ISSB standards)", back: "IFRS S1: general requirements for disclosing sustainability-related financial information. IFRS S2: climate-related disclosures — both aimed at informing investors about sustainability risks and opportunities." },
  { id: "SBR-FC-57", paper: "SBR", area: "E", front: "IAS 24 — related party disclosures", back: "Requires disclosure of related party relationships and transactions (and outstanding balances), including key management personnel compensation — because such dealings may not be at arm's length." },
  { id: "SBR-FC-58", paper: "SBR", area: "E", front: "The IFRS for SMEs", back: "A simplified, standalone standard for small and medium-sized entities without public accountability — fewer disclosures and simpler recognition/measurement (e.g. goodwill amortised, all development costs expensed)." },
  { id: "SBR-FC-59", paper: "SBR", area: "E", front: "IAS 10 — adjusting vs non-adjusting events after the reporting period", back: "Adjusting events give evidence of conditions existing at the reporting date (adjust the figures). Non-adjusting events arise afterwards (disclose only, if material)." },
  { id: "SBR-FC-60", paper: "SBR", area: "E", front: "IAS 7 — the three categories in the statement of cash flows", back: "Operating activities, investing activities and financing activities." },
]
