import type { TopicBrief } from "@/lib/acca-briefs"
import { SBL_BRIEFS } from "@/lib/acca-briefs-sbl"

const old = (area: string) => SBL_BRIEFS.find((item) => item.paper === "SBL" && item.area === area)!
function make(area: string, title: string, concept: string, structure: string, example: string, traps: string): TopicBrief {
  return { paper: "SBL", area, title, minutes: 6, sections: [{ kind: "concept", heading: "Senior-adviser lens", body: concept }, { kind: "structure", heading: "Response structure", body: structure }, { kind: "example", heading: "Applied case", body: example }, { kind: "traps", heading: "Common failures", body: traps }] }
}

export const SBL_OFFICIAL_BRIEFS: TopicBrief[] = [
  make("A", "Leadership", "Leadership sets direction, culture and ethical boundaries through behaviour, incentives and decisions. Responsible leaders create sustainable organisational and public value, especially when short-term pressure makes ethical action difficult.", "Identify the leadership/culture issue.\nUse evidence of behaviour and incentives.\nEvaluate stakeholder and public-interest effects.\nRecommend proportionate action, ownership and follow-up.", "A chief executive asks for challenge but punishes bad news. Explain that observed consequences defeat the stated tone, weaken decisions and require protected speak-up routes plus changes to executive behaviour and reward.", "Listing leadership styles without applying context.\nTreating values statements as culture evidence.\nIgnoring public-interest and ethical consequences."),
  { ...old("A"), area: "B", title: "Governance and sustainability" },
  { ...old("B"), area: "C", title: "Strategy" },
  make("D", "Risk", "Risk advice connects objectives and options to uncertainty, appetite, capacity and response. The board must understand aggregate exposure and early warning—not merely keep a risk register.", "Define objective and exposure.\nAssess likelihood, impact, velocity and interdependence.\nCompare with appetite/capacity.\nRecommend avoid, reduce, transfer or accept with owner, indicator and escalation.", "A fast acquisition creates integration, cyber and liquidity risks that reinforce one another. Evaluate the combined downside and recommend staged gates rather than scoring each risk in isolation.", "Confusing risk with an existing problem.\nTreating heat-map scores as precise.\nRecommending controls without ownership or indicators."),
  { ...old("D"), area: "E", title: "Technology and data analytics" },
  make("F", "Organisational control and audit", "Control and assurance safeguard objectives and assets through accountable processes, reliable information, compliance, monitoring and independent challenge.", "State objective and risk.\nEvaluate design and operation of controls.\nAssess management information and escalation.\nClarify three-lines responsibilities and assurance.\nRecommend owner, deadline and follow-up.", "A dashboard changes definitions between divisions and suppresses exceptions. Recommend governed definitions, reconciled sources, thresholds, named escalation and independent review rather than another visual redesign.", "Equating internal audit with control ownership.\nReporting findings without cause and consequence.\nIgnoring information quality."),
  make("G", "Finance in planning and decision-making", "Board finance tests value, funding capacity, resilience and consequences. A positive valuation result is an input to strategic judgement, not an automatic decision.", "Quantify value and cash timing.\nChallenge assumptions and sensitivity.\nTest liquidity, financing and covenants.\nIntegrate tax, reporting, control and stakeholder effects.\nRecommend conditions and benefit ownership.", "A $2m platform has PV benefits of $2.6m: NPV $0.6m. Recommend staged approval only after testing adoption and covenant downside, with gates and a named benefit owner.", "Repeating management forecasts.\nRecommending solely from positive NPV.\nIgnoring implementation and financing capacity."),
  make("H", "Enabling success, change and projects", "Strategy is enabled by organisation, talent, innovation, change adoption and project governance. Delivery outputs matter only when stakeholders adopt them and benefits are realised.", "Define capability and change need.\nMap stakeholders and readiness.\nSet business case, governance and PID.\nControl scope, time, cost, risk and quality.\nTransfer ownership and measure benefits.", "A project is on time but retention benefit is unmeasured. Assign a benefit owner, define baseline/target and conduct a post-implementation review before calling it successful.", "Labelling all resistance obstruction.\nConfusing go-live with success.\nLeaving benefits without owners."),
  { ...old("E"), area: "I", title: "Professional skills" },
  make("J", "Other employability and digital skills", "SBL digital competence means navigating evidence efficiently and producing the requested professional deliverable with traceable analysis, not displaying software tricks.", "Map role, recipient, verb and output.\nLink requirements to exhibits.\nReconcile periods and definitions.\nUse controlled calculations and purposeful headings.\nCheck every requested action before submission.", "When a narrative conflicts with a spreadsheet, validate comparable bases, quantify the difference and explain uncertainty instead of selecting whichever source supports the preferred recommendation.", "Generic essays.\nCopying exhibits.\nUnexplained calculations.\nIgnoring contradictory evidence or the required format."),
]
