import type { Flashcard } from "@/lib/acca-flashcards"

const cards = (area: string, entries: Array<[string, string]>): Flashcard[] => entries.map(([front, back], index) => ({ id: `SBL-${area}-FC-${String(index + 1).padStart(2, "0")}`, paper: "SBL", area, front, back }))

export const SBL_OFFICIAL_FLASHCARDS: Flashcard[] = [
  ...cards("A", [["Responsible leadership", "Creates sustainable organisational and public value through ethical conduct, stakeholder awareness and accountable decisions."], ["Tone from the top", "The behavioural standard leaders communicate through decisions, incentives, challenge and consequences—not slogans."], ["Leadership style principle", "Fit style to context, capability and urgency while preserving ethical challenge and long-term engagement."], ["Culture evidence", "Observe behaviour, symbols, routines, controls and rewards; stated values alone are weak evidence."]]),
  ...cards("F", [["Three lines model", "Management owns risk/control; oversight functions support and monitor; internal audit provides independent assurance."], ["Internal-audit independence", "Functional access and accountability to the audit committee, with unrestricted scope, information and reporting."], ["Actionable control finding", "Condition, criterion, cause, consequence, recommendation, owner, deadline and follow-up."], ["Management-information quality", "Relevant, reliable, timely, comparable, understandable and linked to decisions and escalation."]]),
  ...cards("G", [["Strategic finance recommendation", "Combine value, funding capacity, assumptions, sensitivity, tax/reporting effects and strategic/non-financial risks."], ["Economic value creation", "Operating return creates value only to the extent it exceeds the required return/capital charge."], ["Scenario discipline", "Maintain a base case, specify changed assumptions and explain effects on value, liquidity and risk."], ["Finance transformation", "Redesign finance people, process, data and technology to improve insight, control and decision support—not automation alone."]]),
  ...cards("H", [["Project initiation document", "Agreed baseline covering purpose, scope, governance, roles, milestones, resources, risks and controls."], ["Benefit owner", "The accountable business person who ensures a promised outcome is measured and realised after delivery."], ["Change readiness", "Evidence that stakeholders understand the case, possess capability and capacity, and have support to adopt new ways of working."], ["Project constraint triangle", "Scope, time and cost interact; quality, risk and benefits must also be governed when one changes."]]),
  ...cards("J", [["Requirement mapping", "Identify role, recipient, task verb, output and relevant exhibits before drafting."], ["Professional digital response", "Use purposeful structure, traceable evidence, controlled calculations, prioritised analysis and specific recommendations."], ["Conflicting exhibits", "Reconcile definitions, periods and sources; quantify differences and state unresolved uncertainty."], ["Pre-seen discipline", "Understand the organisation and industry context, but answer using the requirement and live exhibits rather than rehearsed generic text."]]),
]
