import type { AccaQuestion } from "@/lib/acca-content"

/* MA bank wave 5 — 70 verified originals (2026-07-10). */
export const MA_WAVE2: AccaQuestion[] = [
  /* ───────── A — Cost accounting & classification (14) ───────── */
  {
    id: "MA2-A-01", paper: "MA", area: "A", type: "mcq",
    stem: "Bexley Joinery employs one production supervisor for every 12 assembly workers, hiring an extra supervisor each time headcount crosses that threshold. The supervisors' salary cost is best described as a:",
    options: ["Variable cost", "Fixed cost", "Semi-variable cost", "Step (stepped-fixed) cost"],
    correct: 3,
    explanation: "The cost is fixed over a range of activity, then jumps to a new fixed level when a threshold is crossed — a step cost. It is not variable (it does not rise with every extra worker), not purely fixed (it does change), and not semi-variable (there is no per-unit element on top of a fixed base).",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA2-A-02", paper: "MA", area: "A", type: "mcq",
    stem: "Which of the following is most likely to be classified as an INDIRECT production cost for a furniture manufacturer?",
    options: [
      "Timber used to make tables",
      "Wages of the machine operators",
      "Lubricating oil for factory machinery",
      "Fabric used to upholster chairs",
    ],
    correct: 2,
    explanation: "Indirect costs cannot be economically traced to a specific cost unit. Lubricating oil benefits production generally, so it is an indirect material (overhead). Timber and upholstery fabric are traceable direct materials, and machine operators' wages are direct labour.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA2-A-03", paper: "MA", area: "A", type: "number",
    stem: "Harrow Co's total production cost was $26,000 at an output of 4,000 units and $38,000 at 7,000 units. Using the high-low method, what is the TOTAL FIXED cost, in $?",
    numericAnswer: 10000, unit: "$",
    explanation: "Variable cost per unit = (38,000 − 26,000) ÷ (7,000 − 4,000) = $4. Fixed cost = total cost − variable cost at either level: 26,000 − (4,000 × 4) = $10,000 (check: 38,000 − 7,000 × 4 = 10,000). Trap: stopping at the $4 variable cost, or dividing total cost by units (which mixes fixed and variable elements).",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-A-04", paper: "MA", area: "A", type: "mcq",
    stem: "Pinner Co's output was 5,000 units (total cost $35,000) in March and 8,000 units (total cost $47,000) in April. Using the high-low method, the variable cost per unit is:",
    options: ["$4.00", "$5.88", "$6.31", "$7.00"],
    correct: 0,
    explanation: "Variable cost/unit = change in cost ÷ change in units = (47,000 − 35,000) ÷ (8,000 − 5,000) = $4.00. $5.88 is average cost at the high point (47,000 ÷ 8,000), $7.00 is average cost at the low point (35,000 ÷ 5,000), and $6.31 averages the two periods together — all wrongly include fixed costs in the unit rate.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-A-05", paper: "MA", area: "A", type: "mcq",
    stem: "Kembal Co held 100 units of a material at $5 each. It then purchased 200 units at $6 each, and later issued 250 units to production. Using FIFO, the value of the issue is:",
    options: ["$1,500", "$1,450", "$1,417", "$1,400"],
    correct: 3,
    explanation: "FIFO issues the oldest units first: 100 × $5 + 150 × $6 = 500 + 900 = $1,400. $1,450 is LIFO (200 × $6 + 50 × $5), $1,417 is the weighted average (1,700 ÷ 300 = $5.667 × 250), and $1,500 prices everything at the latest cost of $6.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-A-06", paper: "MA", area: "A", type: "number",
    stem: "Orpin Co had opening inventory of 200 kg of material at $4.00 per kg. It then purchased 300 kg at $4.50 per kg, and afterwards issued 350 kg to production. Using the weighted average (AVCO) method, what is the value of CLOSING inventory, in $?",
    numericAnswer: 645, unit: "$",
    explanation: "Weighted average after the purchase = (200 × 4.00 + 300 × 4.50) ÷ 500 = 2,150 ÷ 500 = $4.30/kg. Closing inventory = (500 − 350) × 4.30 = 150 × 4.30 = $645. Trap: valuing the closing 150 kg at the latest price of $4.50 ($675) or the opening price of $4.00 ($600) — AVCO blends all units in store.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-A-07", paper: "MA", area: "A", type: "mcq",
    stem: "Cheam Co uses 10,000 components a year. Each order placed costs $25 to process, and holding one component in inventory costs $2 per year. The economic order quantity (EOQ) is:",
    options: ["40 units", "354 units", "500 units", "707 units"],
    correct: 2,
    explanation: "EOQ = √(2 × Co × D ÷ Ch) = √(2 × 25 × 10,000 ÷ 2) = √250,000 = 500 units. 354 omits the '2' in the numerator, 40 swaps the order cost and holding cost, and 707 forgets to divide by the holding cost before taking the square root.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-A-08", paper: "MA", area: "A", type: "mcq",
    stem: "Which of the following labour costs should be treated as a DIRECT cost of a specific job?",
    options: [
      "Idle time of production workers caused by a machine breakdown",
      "Overtime premium worked at the specific request of a customer to complete that customer's job",
      "Overtime premium arising from general pressure of work",
      "The salary of the factory supervisor",
    ],
    correct: 1,
    explanation: "Overtime premium is normally an indirect cost — unless the overtime is worked at a customer's specific request, in which case the premium is traceable to (and charged direct to) that job. Idle time, general overtime premium and supervision are all production overheads.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA2-A-09", paper: "MA", area: "A", type: "number",
    stem: "Dana is paid a basic rate of $12 per hour for a 40-hour week, with overtime paid at time-and-a-half. Last week she worked 45 hours. What were her total gross wages for the week, in $?",
    numericAnswer: 570, unit: "$",
    explanation: "Basic: 40 × $12 = $480. Overtime: 5 hours × ($12 × 1.5) = 5 × $18 = $90. Total = $570. Traps: paying all 45 hours at the overtime rate of $18 ($810), or adding only the $6 premium on the 5 overtime hours to the 40-hour basic wage ($510) and forgetting the basic pay for those overtime hours.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA2-A-10", paper: "MA", area: "A", type: "mcq",
    stem: "Selwyn Co began the year with 500 employees and ended it with 540. During the year, 60 employees left and all were replaced. Using the average workforce, the labour turnover rate is closest to:",
    options: ["7.7%", "11.1%", "11.5%", "12.0%"],
    correct: 2,
    explanation: "Labour turnover = leavers who are replaced ÷ average workforce = 60 ÷ ((500 + 540) ÷ 2) = 60 ÷ 520 = 11.5%. 12.0% divides by opening headcount, 11.1% by closing headcount, and 7.7% wrongly uses the net change in employees (40) instead of the number who left.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-A-11", paper: "MA", area: "A", type: "mcq",
    stem: "In a cost accounting system, a COST CENTRE is best defined as:",
    options: [
      "A unit of product or service in relation to which costs are ascertained",
      "A production or service location, function or activity for which costs are accumulated",
      "The amount of expenditure attributable to a specific product",
      "A department whose manager is responsible for both costs and revenues",
    ],
    correct: 1,
    explanation: "A cost centre is a location, function or activity that collects costs (e.g. the maintenance department). The first option defines a cost unit, the third a cost object's cost, and the fourth a profit centre — classic definition mix-ups.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA2-A-12", paper: "MA", area: "A", type: "mcq",
    stem: "PRIME COST is the total of:",
    options: [
      "Direct materials + direct labour + direct expenses",
      "Direct materials + direct labour + production overheads",
      "Total production cost less selling and distribution costs",
      "All variable costs of the business",
    ],
    correct: 0,
    explanation: "Prime cost = all DIRECT costs: direct materials + direct labour + direct expenses. Adding production overheads gives full production cost, not prime cost; and prime cost is defined by traceability (direct), not by behaviour (variable) — some variable costs (e.g. variable overheads) are excluded.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA2-A-13", paper: "MA", area: "A", type: "mcq",
    stem: "Frome Co's total costs were $135,000 at 16,000 units and $170,000 at 22,000 units. Fixed costs increase by a one-off step of $5,000 when output exceeds 20,000 units. Using the high-low method, the variable cost per unit is:",
    options: ["$5.00", "$5.83", "$6.67", "$7.73"],
    correct: 0,
    explanation: "Remove the step first so both points sit on the same fixed-cost line: (170,000 − 5,000 − 135,000) ÷ (22,000 − 16,000) = 30,000 ÷ 6,000 = $5.00. $5.83 ignores the step, $6.67 adds the $5,000 instead of deducting it, and $7.73 is just average cost at the high point.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA2-A-14", paper: "MA", area: "A", type: "mcq",
    stem: "Grafton Co's factory telephone contract charges a fixed monthly line rental plus a rate per minute of calls made. This cost is best classified as:",
    options: ["Fixed", "Variable", "Semi-variable", "Stepped-fixed"],
    correct: 2,
    explanation: "A cost with a fixed element (rental) plus a variable element (per-minute charge) is semi-variable (mixed). It is not purely fixed or purely variable, and there is no threshold jump, so it is not a step cost.",
    marks: 2, difficulty: "easy",
  },

  /* ───────── B — Costing techniques (18) ───────── */
  {
    id: "MA2-B-01", paper: "MA", area: "B", type: "mcq",
    stem: "A machining department is highly automated: machine hours are far greater than direct labour hours. The most appropriate basis for absorbing the department's production overheads into products is:",
    options: ["A percentage of direct wages", "Machine hours", "Direct labour hours", "Number of units produced"],
    correct: 1,
    explanation: "The absorption base should reflect what drives the overheads. In an automated department (power, depreciation, maintenance) overheads follow machine time, so a machine-hour rate is best. Labour-based rates suit labour-intensive departments; a unit rate only works if all products are identical.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA2-B-02", paper: "MA", area: "B", type: "number",
    stem: "Datchet Co budgeted production overheads of $120,000 and 24,000 direct labour hours. Actual results were 25,000 labour hours worked and overheads incurred of $130,000. By how much were overheads UNDER-absorbed, in $?",
    numericAnswer: 5000, unit: "$",
    explanation: "OAR = 120,000 ÷ 24,000 = $5 per hour (always budget ÷ budget). Absorbed = ACTUAL hours × OAR = 25,000 × 5 = $125,000. Incurred $130,000 > absorbed $125,000, so under-absorption = $5,000. Trap: comparing actual overheads with the $120,000 budget ($10,000) — absorption works off actual activity, not the original budget.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-B-03", paper: "MA", area: "B", type: "mcq",
    stem: "Epping Co budgeted overheads of $90,000 for 30,000 machine hours. Actual overheads were $84,000 and actual machine hours were 29,000. Overheads for the period were:",
    options: ["$3,000 over-absorbed", "$3,000 under-absorbed", "$6,000 over-absorbed", "$6,000 under-absorbed"],
    correct: 0,
    explanation: "OAR = 90,000 ÷ 30,000 = $3/hour. Absorbed = 29,000 × 3 = $87,000 versus $84,000 incurred: absorbed exceeds incurred, so $3,000 OVER-absorbed. $3,000 under reverses the direction; the $6,000 options compare actual overheads with the original budget, which is not how over/under-absorption is measured.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-B-04", paper: "MA", area: "B", type: "mcq",
    stem: "Ludlow Co has two production departments, P1 (allocated overheads $100,000) and P2 ($80,000), and one service department, S ($40,000). S's costs are reapportioned 60% to P1 and 40% to P2. After reapportionment, P1's total overhead is:",
    options: ["$116,000", "$120,000", "$124,000", "$140,000"],
    correct: 2,
    explanation: "P1 = 100,000 + (60% × 40,000) = 100,000 + 24,000 = $124,000. $116,000 applies the wrong percentage (40%), $120,000 splits S equally instead of 60/40, and $140,000 dumps the entire service cost onto P1.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-B-05", paper: "MA", area: "B", type: "mcq",
    stem: "Marlow Co has production departments P1 and P2, plus Stores (overhead $30,000) and Maintenance ($20,000). Maintenance's costs are apportioned 40% to P1, 50% to P2 and 10% to Stores; Stores' costs are then apportioned 60% to P1 and 40% to P2. Using the step-down method (Maintenance first), the total service-department overhead reapportioned to P1 is:",
    options: ["$19,200", "$26,000", "$27,200", "$32,000"],
    correct: 2,
    explanation: "Step 1 — Maintenance $20,000: P1 gets 8,000, P2 10,000, Stores 2,000. Step 2 — Stores now holds 30,000 + 2,000 = $32,000: P1 gets 60% = 19,200. P1 total = 8,000 + 19,200 = $27,200. $26,000 ignores the inter-service transfer (8,000 + 60% × 30,000), $19,200 counts only the Stores share, and $32,000 is Stores' whole balance.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA2-B-06", paper: "MA", area: "B", type: "mcq",
    stem: "Rye Co produced 10,000 units and sold 9,000 in its first period. Fixed production overhead is absorbed at $6 per unit. Compared with marginal costing, the absorption costing profit for the period is:",
    options: [
      "$6,000 higher than the marginal costing profit",
      "$6,000 lower than the marginal costing profit",
      "Equal to the marginal costing profit",
      "$54,000 higher than the marginal costing profit",
    ],
    correct: 0,
    explanation: "Profit difference = change in inventory × fixed overhead per unit = (10,000 − 9,000) × $6 = $6,000. Inventory ROSE, so absorption costing carries $6,000 of fixed overhead forward in inventory and reports the HIGHER profit. The reverse holds when inventory falls; $54,000 wrongly multiplies units SOLD by the rate.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-B-07", paper: "MA", area: "B", type: "number",
    stem: "Tern Co's marginal costing profit for the period was $48,000. Opening finished-goods inventory was 2,000 units and closing inventory was 3,500 units. Fixed production overhead is absorbed at $4 per unit. What profit would absorption costing report, in $?",
    numericAnswer: 54000, unit: "$",
    explanation: "Inventory rose by 1,500 units, so absorption profit is HIGHER by 1,500 × $4 = $6,000: 48,000 + 6,000 = $54,000. Rule: absorption profit = marginal profit + (increase in inventory × fixed OAR per unit). Trap: subtracting the $6,000 (only correct when inventory falls), or using closing inventory alone (3,500 × 4).",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-B-08", paper: "MA", area: "B", type: "mcq",
    stem: "Under MARGINAL costing, finished goods inventory is valued at:",
    options: [
      "Prime cost only",
      "Variable production cost",
      "Full production cost including fixed production overhead",
      "Total cost including selling and administration overheads",
    ],
    correct: 1,
    explanation: "Marginal costing values inventory at variable PRODUCTION cost (direct materials, direct labour, direct expenses AND variable production overhead); fixed production overhead is a period cost. Prime cost wrongly excludes variable overhead; full production cost is the absorption costing valuation; non-production costs are never in inventory.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA2-B-09", paper: "MA", area: "B", type: "mcq",
    stem: "Severn Co put 1,000 kg of material costing a total of $4,600 into a process. Normal loss is 10% of input and loss units are sold as scrap at $1 per kg. There was no work-in-progress and actual output equalled expected output. The cost per kg of good output is:",
    options: ["$4.50", "$4.60", "$5.00", "$5.11"],
    correct: 2,
    explanation: "Cost per unit = (input cost − scrap value of NORMAL loss) ÷ EXPECTED output = (4,600 − 100 × $1) ÷ 900 = 4,500 ÷ 900 = $5.00. $5.11 forgets the scrap credit, $4.60 divides by input (1,000 kg) instead of expected output, and $4.50 makes both errors' hybrid — deducting scrap but still dividing by input.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-B-10", paper: "MA", area: "B", type: "mcq",
    stem: "Ouse Co input 5,000 litres costing $20,500 into a process. Normal loss is 20% of input, and losses are sold as scrap at $0.50 per litre. Actual output was 4,300 litres. At what value is the ABNORMAL GAIN recorded in the process account?",
    options: ["$1,538", "$1,500", "$1,350", "$1,230"],
    correct: 1,
    explanation: "Cost per litre = (20,500 − 1,000 × 0.50) ÷ (5,000 × 80%) = 20,000 ÷ 4,000 = $5.00. Abnormal gain = 4,300 − 4,000 = 300 litres, valued at the FULL cost per unit: 300 × $5 = $1,500. $1,350 wrongly nets off scrap ($4.50), $1,230 uses an input-based rate (20,500 ÷ 5,000), and $1,538 forgets the normal-loss scrap credit (20,500 ÷ 4,000).",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA2-B-11", paper: "MA", area: "B", type: "number",
    stem: "A process had no opening work-in-progress. 2,400 units were started; 2,000 were completed and transferred out, and 400 remained in closing WIP, 100% complete for materials and 25% complete for conversion. Conversion costs for the period were $16,800. What is the conversion cost per equivalent unit, in $?",
    numericAnswer: 8, unit: "$",
    explanation: "Equivalent units (conversion) = completed 2,000 + WIP 400 × 25% = 2,000 + 100 = 2,100 EU. Cost per EU = 16,800 ÷ 2,100 = $8.00. Trap: dividing by 2,400 physical units ($7.00) or by completed units only ($8.40) — WIP earns credit only for the work actually done on it.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA2-B-12", paper: "MA", area: "B", type: "mcq",
    stem: "A process had no opening WIP. 3,000 units were started; 2,600 were completed and 400 remain in closing WIP (100% complete for materials, 50% for conversion). Costs were: materials $15,000, conversion $14,000. The value of closing WIP is:",
    options: ["$4,000", "$3,000", "$2,933", "$2,000"],
    correct: 1,
    explanation: "Materials: 15,000 ÷ 3,000 EU = $5/EU. Conversion: 14,000 ÷ (2,600 + 400 × 50% = 2,800 EU) = $5/EU. WIP = 400 × 5 + 200 × 5 = 2,000 + 1,000 = $3,000. $2,933 divides conversion cost by 3,000 units (ignoring the degree of completion), $2,000 values materials only, and $4,000 treats WIP as fully complete for conversion.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA2-B-13", paper: "MA", area: "B", type: "mcq",
    stem: "Job costing is MOST appropriate for which of the following businesses?",
    options: ["An oil refinery", "A brewery", "An electricity generator", "A bespoke shopfitting contractor"],
    correct: 3,
    explanation: "Job costing suits work carried out to a customer's specific requirements, where each job is separately identifiable — like bespoke shopfitting. Refining, brewing and power generation produce continuous, homogeneous output, which calls for process (or service) costing.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA2-B-14", paper: "MA", area: "B", type: "number",
    stem: "Job 417 requires direct materials of $2,400 and 30 direct labour hours at $10 per hour. Overheads are absorbed at $20 per labour hour. The company sets prices to earn a profit MARGIN of 25% of the selling price. What price should be quoted for the job, in $?",
    numericAnswer: 4400, unit: "$",
    explanation: "Cost = 2,400 + (30 × 10) + (30 × 20) = 2,400 + 300 + 600 = $3,300. A 25% margin means cost is 75% of price, so price = 3,300 ÷ 0.75 = $4,400. Trap: adding 25% TO cost (a mark-up) gives 3,300 × 1.25 = $4,125 — margin divides by (1 − margin %), mark-up multiplies by (1 + mark-up %).",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA2-B-15", paper: "MA", area: "B", type: "mcq",
    stem: "A batch of 500 units incurs: machine set-up $200, direct materials $1,500, direct labour $800, and production overhead absorbed at 50% of direct labour cost. The production cost per unit is:",
    options: ["$4.60", "$5.00", "$5.80", "$7.30"],
    correct: 2,
    explanation: "Batch cost = 200 + 1,500 + 800 + (50% × 800 = 400) = $2,900; per unit = 2,900 ÷ 500 = $5.80. $5.00 omits the overhead, $4.60 counts only materials and labour, and $7.30 absorbs overhead on the whole prime-plus-set-up figure instead of on direct labour only.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-B-16", paper: "MA", area: "B", type: "mcq",
    stem: "The most appropriate cost unit for a hotel is:",
    options: ["An occupied room-night", "A hotel employee", "A room (regardless of occupancy)", "A kilogram of laundry processed"],
    correct: 0,
    explanation: "Service costing needs a composite cost unit reflecting the service actually sold — for a hotel that is one room occupied for one night. Employees and laundry are inputs, not outputs, and counting rooms regardless of occupancy ignores the activity level.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA2-B-17", paper: "MA", area: "B", type: "number",
    stem: "In one month, Calder Haulage made two deliveries: 10 tonnes carried 1,500 km, and 5 tonnes carried 3,000 km. Total operating costs for the month were $12,000. What is the cost per tonne-kilometre, in $?",
    numericAnswer: 0.4, unit: "$", tolerance: 0.01,
    explanation: "Tonne-km = (10 × 1,500) + (5 × 3,000) = 15,000 + 15,000 = 30,000. Cost per tonne-km = 12,000 ÷ 30,000 = $0.40. Trap: adding tonnes and kilometres separately (15 tonnes, 4,500 km) instead of multiplying load by distance for each journey — the composite unit captures both dimensions of the service.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-B-18", paper: "MA", area: "B", type: "mcq",
    stem: "Over-absorption of production overheads occurs when:",
    options: [
      "Actual overheads incurred exceed absorbed overheads",
      "Actual overheads incurred exceed budgeted overheads",
      "Budgeted overheads exceed actual overheads incurred",
      "Absorbed overheads exceed actual overheads incurred",
    ],
    correct: 3,
    explanation: "Over-absorption means more overhead was charged into production (actual activity × OAR) than was actually incurred — profit is adjusted UP. The comparison is absorbed vs incurred; comparisons with the original budget describe budget variances, not over/under-absorption.",
    marks: 2, difficulty: "easy",
  },

  /* ───────── C — Budgeting (18) ───────── */
  {
    id: "MA2-C-01", paper: "MA", area: "C", type: "mcq",
    stem: "The PRINCIPAL BUDGET FACTOR is best described as:",
    options: [
      "The largest single cost in the master budget",
      "The first budget approved by the board each year",
      "The factor that limits the organisation's activities, to which all other budgets must be geared",
      "The profit target set by senior management",
    ],
    correct: 2,
    explanation: "The principal budget factor (limiting factor) is whatever constrains activity — usually sales demand, sometimes a scarce resource. Its budget is prepared FIRST and everything else follows from it. It is a constraint, not a cost, an approval step or a target.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA2-C-02", paper: "MA", area: "C", type: "number",
    stem: "Walton Co budgets sales of 12,000 units next quarter. Opening finished-goods inventory is 1,500 units and the company wants closing inventory of 2,000 units. How many units must be PRODUCED?",
    numericAnswer: 12500, unit: "units",
    explanation: "Production = sales + closing inventory − opening inventory = 12,000 + 2,000 − 1,500 = 12,500 units. Trap: swapping the inventories (12,000 + 1,500 − 2,000 = 11,500) — you must MAKE the extra units you want on the shelf at the end, and you already have the opening units.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-C-03", paper: "MA", area: "C", type: "mcq",
    stem: "Frinton Co plans to produce 8,000 units, each requiring 3 kg of raw material. Opening raw material inventory is 2,000 kg and the required closing inventory is 3,000 kg. Budgeted material PURCHASES are:",
    options: ["29,000 kg", "25,000 kg", "24,000 kg", "23,000 kg"],
    correct: 1,
    explanation: "Usage = 8,000 × 3 = 24,000 kg. Purchases = usage + closing inventory − opening inventory = 24,000 + 3,000 − 2,000 = 25,000 kg. 23,000 swaps the inventories, 24,000 ignores inventory movements, and 29,000 adds both inventories instead of netting them.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-C-04", paper: "MA", area: "C", type: "mcq",
    stem: "Staines Co's budget for 10,000 units shows variable costs of $40,000 and fixed costs of $25,000. The budget flexed to an actual activity of 12,000 units shows total costs of:",
    options: ["$65,000", "$70,000", "$73,000", "$78,000"],
    correct: 2,
    explanation: "Flex only the variable element: variable = 40,000 × 12,000/10,000 = $48,000; fixed stays at $25,000; total $73,000. $78,000 flexes everything including fixed costs, $70,000 flexes the fixed costs instead of the variable, and $65,000 is the original unflexed budget.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-C-05", paper: "MA", area: "C", type: "mcq",
    stem: "A FLEXIBLE budget is best described as:",
    options: [
      "A budget prepared for a single planned level of activity",
      "A budget which, by recognising cost behaviour, is designed to change as the level of activity changes",
      "A budget covering cash receipts and payments only",
      "Last year's actual results uplifted for inflation",
    ],
    correct: 1,
    explanation: "A flexible budget separates fixed and variable costs so it can be restated ('flexed') to the actual activity level — making budget-versus-actual comparisons meaningful. A single-level budget is a fixed budget; the last option describes incremental budgeting.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA2-C-06", paper: "MA", area: "C", type: "number",
    stem: "Redhill Co collects 40% of each month's sales in cash in the month of sale, and the remaining 60% one month later; there are no irrecoverable debts. Sales were $50,000 in May and $60,000 in June. What are budgeted cash receipts for JUNE, in $?",
    numericAnswer: 54000, unit: "$",
    explanation: "June receipts = 40% of June sales + 60% of May sales = (0.40 × 60,000) + (0.60 × 50,000) = 24,000 + 30,000 = $54,000. Trap: applying both percentages to June's sales alone ($60,000), or lagging the wrong slice — the credit portion received in June relates to MAY's sales.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-C-07", paper: "MA", area: "C", type: "number",
    stem: "Hurst Co has fixed costs of $36,000 and a contribution-to-sales (C/S) ratio of 40%. What sales REVENUE is needed to break even, in $?",
    numericAnswer: 90000, unit: "$",
    explanation: "Breakeven revenue = fixed costs ÷ C/S ratio = 36,000 ÷ 0.40 = $90,000. Trap: multiplying instead of dividing (36,000 × 0.4 = 14,400), or dividing by the variable-cost ratio of 60% ($60,000) — the C/S ratio tells you how much of each sales dollar becomes contribution.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA2-C-08", paper: "MA", area: "C", type: "mcq",
    stem: "Delph Co sells a product at $20 per unit with a variable cost of $12 per unit. Fixed costs are $64,000. How many units must be sold to earn a target profit of $16,000?",
    options: ["4,000 units", "6,667 units", "8,000 units", "10,000 units"],
    correct: 3,
    explanation: "Units = (fixed costs + target profit) ÷ contribution per unit = (64,000 + 16,000) ÷ (20 − 12) = 80,000 ÷ 8 = 10,000. 8,000 is the breakeven point (target profit forgotten), 4,000 divides by the selling price, and 6,667 divides by the variable cost instead of the contribution.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-C-09", paper: "MA", area: "C", type: "mcq",
    stem: "Nairn Co budgets sales of 5,000 units; its breakeven point is 4,000 units. The margin of safety, as a percentage of budgeted sales, is:",
    options: ["20%", "25%", "80%", "125%"],
    correct: 0,
    explanation: "Margin of safety % = (budgeted sales − breakeven) ÷ BUDGETED sales = 1,000 ÷ 5,000 = 20%. 25% divides by the breakeven point instead, 80% is breakeven as a share of budget, and 125% is budget over breakeven — all mis-specify the denominator.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-C-10", paper: "MA", area: "C", type: "mcq",
    stem: "Machine hours are scarce. Product X earns contribution of $12 per unit and needs 3 machine hours per unit; product Y earns $10 per unit and needs 2 machine hours. To maximise profit, production should be concentrated first on:",
    options: [
      "X, because it earns the higher contribution per unit",
      "X, because it uses more machine hours per unit",
      "Y, because it earns the higher contribution per machine hour",
      "Y, because it has the higher selling price",
    ],
    correct: 2,
    explanation: "When one resource is scarce, rank by contribution per unit of the LIMITING FACTOR: X earns 12 ÷ 3 = $4 per hour; Y earns 10 ÷ 2 = $5 per hour — so make Y first. Ranking by contribution per unit (the classic trap) wrongly favours X, which ties up more of the scarce hours for each dollar earned.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA2-C-11", paper: "MA", area: "C", type: "mcq",
    stem: "Only 8,000 machine hours are available. Product X: contribution $8 per unit, 2 hours per unit, maximum demand 3,000 units. Product Y: contribution $6 per unit, 1 hour per unit, maximum demand 4,000 units. The maximum total contribution achievable is:",
    options: ["$48,000", "$40,000", "$36,000", "$24,000"],
    correct: 1,
    explanation: "Contribution per hour: X = $4, Y = $6, so make Y first: 4,000 units use 4,000 hours and earn $24,000. The remaining 4,000 hours make 2,000 units of X earning $16,000. Total = $40,000. $36,000 ranks by contribution per UNIT (X first), $48,000 ignores the hours limit and meets all demand, and $24,000 stops after Y.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA2-C-12", paper: "MA", area: "C", type: "mcq",
    stem: "A company's quarterly sales have risen steadily year after year for the past decade. In time series analysis, this underlying long-term movement is called:",
    options: ["The trend", "Seasonal variation", "Cyclical variation", "Random variation"],
    correct: 0,
    explanation: "The trend is the underlying long-term direction of the series. Seasonal variation repeats within each year (e.g. every Q4 peak), cyclical variation follows multi-year economic cycles, and random variation is one-off unpredictable noise.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-C-13", paper: "MA", area: "C", type: "mcq",
    stem: "Trend sales for Q4 are forecast at 2,400 units. Using a MULTIPLICATIVE model, the Q4 seasonal index is 115. The seasonally adjusted forecast for Q4 is:",
    options: ["2,087 units", "2,285 units", "2,515 units", "2,760 units"],
    correct: 3,
    explanation: "Multiplicative model: forecast = trend × seasonal index ÷ 100 = 2,400 × 1.15 = 2,760. 2,515 ADDS 115 (treating the index as an additive variation), 2,285 subtracts it, and 2,087 divides by 1.15 (that direction is used to remove seasonality from actual data, not to build a forecast).",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-C-14", paper: "MA", area: "C", type: "mcq",
    stem: "A material cost $80 per tonne when the relevant price index stood at 125. The index now stands at 150. The expected current cost per tonne is:",
    options: ["$66.67", "$96.00", "$105.00", "$120.00"],
    correct: 1,
    explanation: "Adjusted cost = 80 × 150 ÷ 125 = $96.00 (multiply by new index, divide by old). $66.67 inverts the ratio (80 × 125 ÷ 150), $105 just adds the 25-point index change as dollars, and $120 treats 150 as a multiplier of 1.5 as if the old index had been 100.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-C-15", paper: "MA", area: "C", type: "mcq",
    stem: "A materials price index currently stands at 120 (base year = 100). Which statement is correct?",
    options: [
      "Prices have risen by 120% since the base year",
      "Prices have fallen by 20% since the base year",
      "Base-year prices were 20% higher than current prices",
      "Prices have risen by 20% since the base year",
    ],
    correct: 3,
    explanation: "An index of 120 against a base of 100 means prices are 120% OF the base level — i.e. a 20% rise. Reading the index itself as the percentage change (120%) is the classic error; and note the asymmetry: current prices are 20% above base, but base prices are 16.7% (20/120) below current.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA2-C-16", paper: "MA", area: "C", type: "mcq",
    stem: "A project has three possible outcomes: profit of $10,000 (probability 0.3), profit of $20,000 (probability 0.5), and a LOSS of $5,000 (probability 0.2). The expected value of the project is:",
    options: ["$8,333", "$12,000", "$14,000", "$20,000"],
    correct: 1,
    explanation: "EV = Σ(probability × outcome) = 0.3 × 10,000 + 0.5 × 20,000 + 0.2 × (−5,000) = 3,000 + 10,000 − 1,000 = $12,000. $14,000 forgets the minus sign on the loss, $8,333 is a simple unweighted average of the three outcomes, and $20,000 just picks the most likely outcome.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-C-17", paper: "MA", area: "C", type: "mcq",
    stem: "Cell D4 of a spreadsheet contains the formula =$B$2*C4. When this formula is copied down to cell D5, it becomes:",
    options: ["=$B$2*C5", "=$B$3*C5", "=$B$2*C4", "=$B$3*C4"],
    correct: 0,
    explanation: "The $ signs make $B$2 an ABSOLUTE reference, so it does not move when copied; C4 is relative, so copying down one row shifts it to C5. Result: =$B$2*C5. If B2 also changed the reference would have needed no $ signs; if nothing changed, both would have been absolute.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA2-C-18", paper: "MA", area: "C", type: "mcq",
    stem: "For most companies, sales demand limits what the business can do. In that situation, which functional budget must be prepared FIRST?",
    options: ["The production budget", "The cash budget", "The materials purchases budget", "The sales budget"],
    correct: 3,
    explanation: "The budget for the principal budget factor is prepared first — when demand is the constraint, that is the sales budget. Production follows from sales (adjusted for inventory), purchases follow from production, and the cash budget is assembled near the end from all the others.",
    marks: 2, difficulty: "easy",
  },

  /* ───────── D — Standard costing & variances (12) ───────── */
  {
    id: "MA2-D-01", paper: "MA", area: "D", type: "mcq",
    stem: "A STANDARD COST is best defined as:",
    options: [
      "A planned (predetermined) unit cost, used as a benchmark against which actual costs are measured",
      "The average actual unit cost of recent periods",
      "The lowest unit cost the company has ever achieved",
      "A unit cost that must never be exceeded",
    ],
    correct: 0,
    explanation: "A standard cost is set in advance, based on expected prices and usage, and actual results are compared against it to compute variances. It is not a historical average (that would embed past inefficiency), not a record low (that is an ideal standard at best), and not a hard cap.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA2-D-02", paper: "MA", area: "D", type: "mcq",
    stem: "Trent Co purchased and used 4,000 kg of material at a total cost of $17,200. It produced 950 units; the standard is 4 kg per unit at $4.50 per kg. The material PRICE variance is:",
    options: ["$100 adverse", "$760 favourable", "$800 favourable", "$800 adverse"],
    correct: 2,
    explanation: "Actual price = 17,200 ÷ 4,000 = $4.30/kg. Price variance = (standard − actual price) × ACTUAL quantity bought = (4.50 − 4.30) × 4,000 = $800 favourable (paid less than standard). $760 wrongly uses the standard quantity (3,800 kg), $800 adverse flips the direction, and $100 adverse is the TOTAL material cost variance, not the price element.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-D-03", paper: "MA", area: "D", type: "number",
    stem: "Kelso Co produced 2,000 units. The standard is 3 kg of material per unit at a standard price of $5 per kg. Actual usage was 6,400 kg. What is the value of the ADVERSE material usage variance, in $?",
    numericAnswer: 2000, unit: "$",
    explanation: "Usage variance = (standard quantity for actual output − actual quantity) × STANDARD price = (2,000 × 3 − 6,400) × 5 = (6,000 − 6,400) × 5 = $2,000 adverse. Rule: usage is always valued at standard price so it isn't polluted by price effects — using an actual price here would double-count the price variance.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-D-04", paper: "MA", area: "D", type: "mcq",
    stem: "Mersey Co's employees worked and were paid for 5,500 hours at a total cost of $49,500. Output was 2,600 units; the standard is 2 hours per unit at $8.60 per hour. The labour RATE variance is:",
    options: ["$2,080 adverse", "$2,200 adverse", "$2,200 favourable", "$4,780 adverse"],
    correct: 1,
    explanation: "Actual rate = 49,500 ÷ 5,500 = $9.00. Rate variance = (standard − actual rate) × ACTUAL hours paid = (8.60 − 9.00) × 5,500 = $2,200 adverse. $2,080 wrongly uses standard hours (5,200), $2,200 favourable flips the sign, and $4,780 is the total labour cost variance (rate + efficiency combined).",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-D-05", paper: "MA", area: "D", type: "mcq",
    stem: "Avon Co produced 1,200 units. The standard is 2 hours per unit at $10 per hour. Actual hours worked were 2,300 and actual wages were $24,150. The labour EFFICIENCY variance is:",
    options: ["$2,000 favourable", "$1,050 favourable", "$1,000 favourable", "$1,000 adverse"],
    correct: 2,
    explanation: "Standard hours for output = 1,200 × 2 = 2,400. Efficiency = (2,400 − 2,300) × STANDARD rate $10 = $1,000 favourable (fewer hours than standard). $1,050 values the hours at the actual rate of $10.50 (24,150 ÷ 2,300) — efficiency is always at standard rate; $1,000 adverse flips the direction; $2,000 doubles the 100-hour saving.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-D-06", paper: "MA", area: "D", type: "mcq",
    stem: "Ribble Co incurred variable production overheads of $9,430 in a period when 4,100 labour hours were worked. The standard variable overhead rate is $2.20 per hour, and the standard hours for the output achieved were 4,300. The variable overhead EXPENDITURE variance is:",
    options: ["$410 adverse", "$410 favourable", "$440 favourable", "$30 favourable"],
    correct: 0,
    explanation: "Expenditure variance = (actual hours × standard rate) − actual cost = (4,100 × 2.20 = 9,020) − 9,430 = $410 ADVERSE: spending exceeded the flexed allowance for hours actually worked. $440 favourable is the efficiency variance ((4,300 − 4,100) × 2.20), and $30 favourable is the total variable overhead variance — the two elements must not be merged or mislabelled.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA2-D-07", paper: "MA", area: "D", type: "mcq",
    stem: "Tamar Co budgets fixed production overheads of $60,000 and output of 12,000 units. Actual output was 12,800 units and actual fixed overheads were $63,000. Under absorption costing, the fixed overhead VOLUME variance is:",
    options: ["$1,000 favourable", "$3,000 adverse", "$4,000 adverse", "$4,000 favourable"],
    correct: 3,
    explanation: "Standard rate = 60,000 ÷ 12,000 = $5/unit. Volume variance = (actual − budgeted output) × rate = (12,800 − 12,000) × 5 = $4,000 FAVOURABLE — extra output absorbs more fixed overhead. $3,000 adverse is the expenditure variance (63,000 − 60,000), and $1,000 favourable is the net over-absorption (64,000 absorbed − 63,000 incurred).",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA2-D-08", paper: "MA", area: "D", type: "mcq",
    stem: "Budgeted fixed production overheads were $45,000; actual fixed overheads incurred were $47,500; overheads absorbed into production were $46,000. The fixed overhead EXPENDITURE variance is:",
    options: ["$1,500 adverse", "$2,500 adverse", "$2,500 favourable", "$1,000 favourable"],
    correct: 1,
    explanation: "Expenditure variance = budgeted − actual fixed overheads = 45,000 − 47,500 = $2,500 adverse (spent more than budget). $1,500 adverse is the total under-absorption (47,500 − 46,000), $1,000 favourable is the volume variance (46,000 − 45,000), and the favourable version flips the direction.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA2-D-09", paper: "MA", area: "D", type: "mcq",
    stem: "Esk Co uses standard ABSORPTION costing. Budgeted sales were 4,000 units and actual sales 4,500 units. The standard selling price is $20, standard variable cost $12, and standard profit $6 per unit. The sales VOLUME variance is:",
    options: ["$3,000 adverse", "$3,000 favourable", "$4,000 favourable", "$10,000 favourable"],
    correct: 1,
    explanation: "Under absorption costing the volume variance is valued at standard PROFIT per unit: (4,500 − 4,000) × $6 = $3,000 favourable. $4,000 uses standard contribution ($8) — correct only under MARGINAL costing; $10,000 uses the selling price; adverse flips the direction even though sales beat budget.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA2-D-10", paper: "MA", area: "D", type: "mcq",
    stem: "Lagan Co budgeted to sell 1,800 units at a standard price of $50. It actually sold 2,000 units at $52 each. The sales PRICE variance is:",
    options: ["$14,000 favourable", "$4,000 adverse", "$3,600 favourable", "$4,000 favourable"],
    correct: 3,
    explanation: "Price variance = (actual − standard price) × ACTUAL units sold = (52 − 50) × 2,000 = $4,000 favourable. $3,600 wrongly uses budgeted volume (1,800), $14,000 is the total revenue difference (which bundles in the volume effect), and the adverse option flips the sign despite selling above standard price.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-D-11", paper: "MA", area: "D", type: "mcq",
    stem: "A purchasing manager switches to a cheaper, lower-grade material than the standard specifies. The MOST LIKELY combined effect on the material variances is:",
    options: [
      "A favourable price variance and an adverse usage variance",
      "An adverse price variance and a favourable usage variance",
      "Favourable price and usage variances",
      "Adverse price and usage variances",
    ],
    correct: 0,
    explanation: "Paying less than standard gives a favourable PRICE variance, but lower-grade material typically generates more waste and rejects, so MORE is used than standard — an adverse USAGE variance. This interrelationship is why variances should be investigated together, not judged one at a time.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA2-D-12", paper: "MA", area: "D", type: "mcq",
    stem: "Which of the following is a plausible cause of a FAVOURABLE labour efficiency variance?",
    options: [
      "Frequent machine breakdowns during the period",
      "Using less-experienced trainees than the standard assumes",
      "Employing more highly skilled workers than the standard grade",
      "Paying a higher hourly rate than standard",
    ],
    correct: 2,
    explanation: "Higher-skilled workers complete output in fewer hours than standard — a favourable efficiency variance (often paired with an adverse RATE variance, since they cost more per hour). Breakdowns and trainees slow production (adverse efficiency), and pay rates affect the rate variance, not efficiency.",
    marks: 2, difficulty: "easy",
  },

  /* ───────── E — Performance measurement (8) ───────── */
  {
    id: "MA2-E-01", paper: "MA", area: "E", type: "mcq",
    stem: "A divisional manager has authority over the division's costs and revenues, but all investment decisions are made by head office. The division is best classified as:",
    options: ["A cost centre", "A profit centre", "An investment centre", "A revenue centre"],
    correct: 1,
    explanation: "Responsibility should match authority: control over costs AND revenues (but not capital) makes it a profit centre. An investment centre additionally controls capital employed (so ROI/RI apply); a cost centre controls only costs; a revenue centre only revenues.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA2-E-02", paper: "MA", area: "E", type: "mcq",
    stem: "A division reports operating profit of $84,000 on revenue of $1,200,000. Total assets are $700,000 and current liabilities $100,000, giving capital employed of $600,000. The division's return on investment (ROI) is:",
    options: ["7.0%", "12.0%", "14.0%", "16.8%"],
    correct: 2,
    explanation: "ROI = operating profit ÷ capital employed = 84,000 ÷ 600,000 = 14.0%. 12.0% divides by total assets without deducting current liabilities, 7.0% is the profit MARGIN (profit ÷ revenue), and 16.8% deducts the current liabilities twice (÷ 500,000).",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-E-03", paper: "MA", area: "E", type: "mcq",
    stem: "A division earns an operating profit of $150,000 on capital employed of $1,000,000. The company's cost of capital is 12%. The division's RESIDUAL INCOME is:",
    options: ["$30,000", "$120,000", "$132,000", "$150,000"],
    correct: 0,
    explanation: "RI = operating profit − (capital employed × cost of capital) = 150,000 − (1,000,000 × 12%) = 150,000 − 120,000 = $30,000. $120,000 is just the imputed interest charge, $132,000 wrongly deducts 12% of PROFIT instead of 12% of capital, and $150,000 forgets the charge entirely.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-E-04", paper: "MA", area: "E", type: "mcq",
    stem: "Which of the following is NOT one of the four perspectives of the balanced scorecard?",
    options: ["Financial", "Customer", "Internal business processes", "Competitor"],
    correct: 3,
    explanation: "The balanced scorecard's four perspectives are financial, customer, internal business processes, and innovation/learning and growth. 'Competitor' is not one of them — competitor analysis belongs to strategic planning tools, not the scorecard framework.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA2-E-05", paper: "MA", area: "E", type: "mcq",
    stem: "Budgeted hours for the period were 10,000. Actual hours worked were 9,500, and the standard hours of output produced were 9,880. The labour EFFICIENCY ratio is:",
    options: ["95.0%", "96.2%", "98.8%", "104.0%"],
    correct: 3,
    explanation: "Efficiency ratio = standard hours produced ÷ actual hours worked = 9,880 ÷ 9,500 = 104.0% (output was produced faster than standard). 95.0% is the capacity ratio (actual ÷ budgeted hours), 98.8% is the production volume ratio (standard hours ÷ budgeted hours), and 96.2% inverts the efficiency fraction.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "MA2-E-06", paper: "MA", area: "E", type: "mcq",
    stem: "Which measure is most appropriate for assessing a company's short-term LIQUIDITY?",
    options: ["Return on capital employed", "Gearing ratio", "Current ratio", "Operating profit margin"],
    correct: 2,
    explanation: "Liquidity is the ability to meet short-term obligations, measured by the current ratio (current assets ÷ current liabilities) or the sharper quick/acid-test ratio. ROCE and margin measure profitability; gearing measures long-term financial risk (debt vs equity).",
    marks: 2, difficulty: "easy",
  },
  {
    id: "MA2-E-07", paper: "MA", area: "E", type: "mcq",
    stem: "In performance measurement for not-for-profit organisations (the 'three Es'), EFFICIENCY means:",
    options: [
      "Minimising the cost of inputs regardless of what is produced",
      "The relationship between the outputs produced and the resources (inputs) used to produce them",
      "The extent to which the organisation achieves its objectives",
      "Keeping total spending within the approved budget",
    ],
    correct: 1,
    explanation: "Efficiency is the output-to-input relationship — getting the most output per unit of resource. Minimising input cost alone is ECONOMY (which ignores output), and achieving objectives is EFFECTIVENESS. Staying within budget is compliance, not one of the three Es.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "MA2-E-08", paper: "MA", area: "E", type: "mcq",
    stem: "A company has an operating profit margin of 8% and an asset turnover of 1.5 times. Its return on capital employed (ROCE) is:",
    options: ["5.3%", "6.5%", "9.5%", "12.0%"],
    correct: 3,
    explanation: "ROCE = profit margin × asset turnover = 8% × 1.5 = 12.0% — the ratios multiply because (profit/sales) × (sales/capital employed) = profit/capital employed. 5.3% divides margin by turnover, 9.5% adds them, and 6.5% subtracts — none of which respects the algebraic link.",
    marks: 2, difficulty: "medium",
  },
]
