import type { TopicBrief } from "@/lib/acca-briefs"

function brief(
  area: string,
  title: string,
  concept: string,
  structure: string,
  example: string,
  traps: string,
): TopicBrief {
  return {
    paper: "LW",
    area,
    title,
    minutes: 7,
    sections: [
      { kind: "concept", heading: "Core legal logic", body: concept },
      { kind: "structure", heading: "Exam application map", body: structure },
      { kind: "example", heading: "Applied example", body: example },
      { kind: "traps", heading: "Classic traps", body: traps },
    ],
  }
}

export const LW_GLOBAL_BRIEFS: TopicBrief[] = [
  brief("A", "Essential elements of legal systems",
    "LW Global compares the legal traditions and institutions that support international commerce. Public international law regulates states and international organisations; private international law resolves jurisdiction and governing-law questions in cross-border private disputes. Arbitration produces a binding award, while mediation depends on voluntary agreement.",
    "First identify whether the issue is public or private. For a private dispute, separate jurisdiction, applicable law and enforcement. Then identify the relevant legal source or dispute process and explain its effect. When comparing systems, focus on sources of law, the role of judges and how rules are organised.",
    "Two companies from different states choose arbitration and a governing law in their contract. A dispute arises. Analyse the arbitration clause separately from the substantive law governing the sale, then consider recognition of the resulting award.",
    "Treating mediation as a binding judgment; confusing jurisdiction with governing law; assuming every judicial decision creates precedent in every system; or applying one domestic hierarchy to all legal traditions."),
  brief("B", "International business transactions",
    "The CISG supplies uniform rules for qualifying international sales. It addresses formation, seller and buyer obligations, risk, breach and remedies. A fundamental breach substantially deprives the other party of what it was entitled to expect and may justify avoidance; damages remain subject to foreseeability and mitigation.",
    "Confirm that the transaction and parties fall within the CISG and check whether it has been excluded. Establish offer and acceptance, identify each obligation and breach, test whether the breach is fundamental, then select damages, performance, price reduction or avoidance. Calculate loss only after applying foreseeability and mitigation.",
    "A seller delivers specialised machinery that cannot perform its disclosed purpose. The buyer promptly notifies the seller and replacement is impossible. Link conformity and notice to breach, test substantial deprivation, then evaluate avoidance and foreseeable loss.",
    "Assuming every breach permits avoidance; overlooking notice of non-conformity; confusing an invitation with a definite offer; or awarding losses that were unforeseeable or could reasonably have been reduced."),
  brief("C", "Transportation and payment in international trade",
    "Incoterms allocate delivery obligations, cost and risk but do not by themselves decide ownership or every contract issue. A bill of lading can evidence receipt, the carriage contract and control of goods. Under a documentary credit, banks deal with documents rather than the physical goods and honour a complying presentation.",
    "Identify the chosen trade term and named place, then locate delivery and transfer of risk. Analyse the carriage document and the parties entitled to claim. For payment, identify whether the method is open account, collection or credit; under a credit, compare each document with its terms using strict compliance.",
    "Goods are damaged after the seller delivers them at the point required by the chosen Incoterm. Determine when risk passed before deciding who bears accidental loss. A separate discrepancy in the invoice may still permit the issuing bank to refuse payment.",
    "Using Incoterms to decide title automatically; assuming the carrier always bears commercial risk; inspecting goods instead of documents under a credit; or treating a bank's role in documentary collection as a payment guarantee."),
  brief("D", "Formation and constitution of business organisations",
    "Agency permits an authorised agent to affect a principal's legal position. Organisations differ in personality, ownership, management and liability. Incorporation creates an entity distinct from members; the constitution allocates internal powers, while promoters must disclose conflicts arising during formation.",
    "Identify the organisation and whether it has separate personality. For agency, test actual authority, apparent authority and ratification. For formation, examine promoter duties, pre-incorporation dealings and registration. Then use the constitution to allocate power while protecting a third party who relied on represented authority.",
    "A company repeatedly allows its purchasing manager to negotiate contracts, then denies authority on an unusual purchase. Test the principal's representation and the supplier's reasonable reliance separately from any private restriction placed on the manager.",
    "Allowing an agent to create apparent authority personally; treating members as owners of company assets; assuming limited liability eliminates all personal liability; or assuming a future company can automatically ratify a pre-formation contract."),
  brief("E", "Capital and financing of companies",
    "Equity gives membership and a residual claim; debt creates contractual creditor rights. Share classes define economic and voting rights. Security strengthens a lender's claim, while capital-maintenance rules restrict distributions and returns of protected capital to safeguard creditors.",
    "Classify the instrument as equity or debt and identify its attached rights. For shares, analyse issue terms and variation of class rights. For borrowing, identify fixed or floating security and priority. For a distribution or capital transaction, identify the protected amount and apply the prescribed solvency, approval and disclosure safeguards.",
    "A company with cash but accumulated losses proposes a dividend. Cash availability is not the legal test: determine whether distributable profits exist under the applicable rules before considering approval and payment.",
    "Calling lenders members; treating a bonus issue as fresh finance; assuming all secured claims have identical priority; or using cash balance as a substitute for the distributable-profit test."),
  brief("F", "Management, administration and regulation",
    "Directors manage collectively and owe loyalty and care obligations to the company. Members exercise reserved constitutional powers. Governance, audit and disclosure systems make decision-makers accountable, while resolutions and meetings provide formal routes to valid organisational action.",
    "Identify the actor, source of power and beneficiary of the duty. Test proper purpose, conflicts, disclosure, care and approval or ratification. For a decision, identify whether it belongs to the board or members, then apply notice, quorum, voting and record requirements. Consider remedies only after establishing breach.",
    "A director diverts an opportunity learned through office to another business. Identify the conflict and unauthorised benefit even if the company could not itself exploit the opportunity, then consider disclosure, approval and remedies.",
    "Treating duties as owed individually to every shareholder; assuming disclosure automatically cures every conflict; confusing a board vote with a member resolution; or ignoring the constitution when allocating decision power."),
  brief("G", "Insolvency law",
    "Insolvency systems coordinate creditor claims when individual enforcement would destroy value. Liquidation realises assets and ends the entity; a rescue procedure seeks survival or a better collective result. Priority rules, security and challengeable pre-insolvency transactions determine distribution.",
    "Apply the cash-flow and balance-sheet indicators supplied by the question. Identify the available procedure and office-holder objective. Classify each creditor and security interest, challenge undervalue transactions or preferences where conditions are met, then distribute value in the stated statutory order.",
    "Shortly before insolvency, a company transfers an asset to a connected person for nominal value. Establish the relevant look-back conditions, value disparity and available defence before identifying restoration or contribution remedies.",
    "Assuming financial difficulty automatically means liquidation; paying unsecured creditors before higher-ranking claims; treating every pre-insolvency payment as a preference; or ignoring the purpose and defences attached to an avoidance rule."),
  brief("H", "Corporate fraudulent and criminal behaviour",
    "International business law combats fraud, bribery, laundering and market abuse through individual offences, organisational liability, reporting duties and preventive controls. Liability depends on the elements of the relevant rule; suspicion, knowledge, intention and failure-to-prevent standards must not be merged.",
    "Identify the conduct, actor, mental element and benefit. Decide whether liability is individual, organisational or both. For laundering, address customer due diligence, beneficial ownership, monitoring and suspicious reporting. For organisational prevention, connect the risk to proportionate policies, training, oversight and remediation.",
    "An intermediary requests an unexplained payment to secure a public contract. Do not label it automatically: identify the proposed advantage, intended influence, recipient and corporate connection, then assess escalation, refusal, documentation and preventive controls.",
    "Treating negligence as fraud; tipping off a customer after a suspicious report; equating tax avoidance automatically with criminal evasion; or assuming a written policy alone proves an effective compliance programme."),
]
