import type { AccaQuestion } from "@/lib/acca-content"

/* AFM bank wave S1 part A (areas A,B) — 60 verified originals (2026-07-13).
 * Blueprint: A20 B40; difficulty 17 easy / 27 medium / 16 hard; 40 mcq / 20 number.
 * Area A = Role of the senior financial adviser; Area B = Advanced investment appraisal.
 * 100% original: invented company names and figures, original prose, public AFM
 * syllabus only. Every distractor is a nameable student error and each explanation
 * both names why the wrong options fail and shows the correct calculation.
 * COMPUTATIONS: every numeric answer was re-solved digit-by-digit from the stem
 * before inclusion; Black-Scholes items show d1, d2, N(d1), N(d2) and the call value.
 * Correct-option distribution across the 40 mcq: index 0 x10, 1 x10, 2 x10, 3 x10.
 * Merged into QUESTIONS in acca-content.ts.
 */

export const AFM_WAVE1A: AccaQuestion[] = [
  /* ═══════════ Area A — Role of the senior financial adviser (20) ═══════════ */
  {
    id: "AFM2-A-01",
    paper: "AFM",
    area: "A",
    type: "mcq",
    stem: "The board of Harlwhere Group is setting the overriding objective for its senior financial management team. Which objective is MOST consistent with the role of the senior financial adviser to a listed company?",
    options: [
      "Maximising the accounting profit reported each financial year",
      "Minimising the total tax paid by the group each year",
      "Maximising the total sales revenue of the group",
      "Maximising the wealth of the ordinary shareholders",
    ],
    correct: 3,
    explanation:
      "The primary financial objective of a listed company is to maximise shareholder wealth, delivered through dividends and share-price growth. Maximising annual accounting profit ignores risk, timing of cash flows and the need for reinvestment; maximising revenue can destroy value if margins are negative; minimising tax is only one input to value, not the objective, and aggressive tax minimisation can carry reputational and legal risk.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM2-A-02",
    paper: "AFM",
    area: "A",
    type: "mcq",
    stem: "A senior financial adviser summarises the firm's strategy as three interrelated decisions. Which set correctly lists the three core decisions of corporate finance?",
    options: [
      "Pricing, marketing and production decisions",
      "Hedging, insurance and provisioning decisions",
      "Investment, financing and dividend decisions",
      "Audit, tax and compliance decisions",
    ],
    correct: 2,
    explanation:
      "Corporate finance rests on the investment decision (which projects to undertake), the financing decision (the mix of debt and equity used) and the dividend decision (how much cash to return to shareholders). Pricing/marketing/production are operational; hedging/insurance/provisioning are risk-management tasks that support but do not replace the three decisions; audit/tax/compliance are governance and stewardship functions, not the strategic finance decisions.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM2-A-03",
    paper: "AFM",
    area: "A",
    type: "mcq",
    stem: "Which statement best describes the DIVIDEND decision as considered by a senior financial adviser?",
    options: [
      "It determines the proportion of earnings returned to shareholders versus retained for reinvestment",
      "It determines the split between ordinary and preference share capital",
      "It determines which capital projects the firm should accept",
      "It determines the currency in which the firm reports its results",
    ],
    correct: 0,
    explanation:
      "The dividend decision balances cash returned to shareholders now against earnings retained to fund future investment. The split between ordinary and preference capital is a financing-mix question; choosing capital projects is the investment decision; reporting currency is an accounting-presentation matter. Only the first option captures the payout-versus-retention trade-off that defines the dividend decision.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM2-A-04",
    paper: "AFM",
    area: "A",
    type: "mcq",
    stem: "Under a dividend irrelevancy view (Modigliani-Miller, perfect markets, no taxes or transaction costs), how does a change in dividend policy affect shareholder wealth?",
    options: [
      "It has no effect, because investors can create 'home-made' dividends by selling shares",
      "It always increases wealth, because higher dividends signal confidence",
      "It always reduces wealth, because paying dividends starves the firm of cash",
      "It increases wealth only if the firm is highly geared",
    ],
    correct: 0,
    explanation:
      "In MM's perfect-market world, an investor who wants cash can sell shares and one who wants to reinvest can buy more, so dividend policy is irrelevant to wealth — total return is fixed by the investment decisions. The signalling argument (higher dividends signal confidence) relies on market imperfections and information asymmetry, so it is not the irrelevancy result; dividends do not automatically 'starve' a firm that can raise finance in a perfect market; and gearing is not the driver of dividend irrelevancy.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM2-A-05",
    paper: "AFM",
    area: "A",
    type: "mcq",
    stem: "Which situation is the clearest example of the AGENCY PROBLEM between senior managers and shareholders?",
    options: [
      "Shareholders disagreeing with each other over the level of dividend",
      "A supplier demanding earlier payment of invoices",
      "Directors pursuing large empire-building acquisitions that boost their status but reduce shareholder value",
      "A bank requiring a covenant limiting further borrowing",
    ],
    correct: 2,
    explanation:
      "The agency problem arises when managers (agents) act in their own interests rather than those of shareholders (principals); empire-building acquisitions that raise managers' status and pay while destroying shareholder value are the textbook case. Shareholder-to-shareholder disagreement is not a principal-agent conflict; a supplier's payment demand and a bank covenant are relationships with other stakeholders (trade creditors and lenders), not manager-versus-owner agency conflicts.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM2-A-06",
    paper: "AFM",
    area: "A",
    type: "mcq",
    stem: "Berrowmoor plc wants to reduce the agency conflict between its executives and shareholders. Which mechanism is MOST directly aligned with that aim?",
    options: [
      "Increasing the number of employees offered a workplace pension",
      "Switching the external auditor every year",
      "Extending supplier payment terms to improve short-term cash flow",
      "Granting executives share options that vest only after a multi-year performance period",
    ],
    correct: 3,
    explanation:
      "Multi-year, performance-vesting share options tie executives' personal wealth to the long-run share price, aligning them with shareholders. Employee pensions address workforce welfare, not the executive-shareholder conflict; extending supplier terms shifts a cost onto trade creditors and does nothing for alignment; annual auditor rotation can actually harm audit quality and continuity and is not an alignment mechanism.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM2-A-07",
    paper: "AFM",
    area: "A",
    type: "mcq",
    stem: "A senior financial adviser is weighing the interests of several stakeholder groups on a major restructuring. Which pairing correctly matches a stakeholder group to its PRIMARY financial interest?",
    options: [
      "Long-term lenders — maximising the firm's dividend payout",
      "Ordinary shareholders — the security of interest and principal repayments",
      "Employees — job security and continuity of remuneration",
      "Trade suppliers — growth in the firm's earnings per share",
    ],
    correct: 2,
    explanation:
      "Employees are primarily concerned with job security and continued pay. Long-term lenders care about the security of interest and capital, not the dividend (a high payout can even threaten them); ordinary shareholders — not lenders — care about returns and value, so option two swaps the two groups; trade suppliers care about being paid on time and continued orders, not EPS growth. Only the employees pairing is correct.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-A-08",
    paper: "AFM",
    area: "A",
    type: "mcq",
    stem: "A finance director is offered a personal 'introduction fee' by an investment bank if the firm awards that bank a large advisory mandate. From a professional-ethics standpoint, this is MOST accurately described as:",
    options: [
      "A legitimate business referral arrangement",
      "A conflict of interest and a possible inducement that should be declined and disclosed",
      "A normal cost of raising finance that can be capitalised",
      "A matter solely for the investment bank's compliance team",
    ],
    correct: 1,
    explanation:
      "A personal payment contingent on steering a mandate compromises the director's objectivity and integrity — it is a conflict of interest and an inducement that fundamental ethical principles require be declined and disclosed. Calling it a legitimate referral ignores that the benefit accrues personally, not to the firm; treating it as a capitalisable finance cost mischaracterises a bribe as a transaction cost; and responsibility does not sit solely with the bank — the director has an independent duty to act with integrity.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-A-09",
    paper: "AFM",
    area: "A",
    type: "mcq",
    stem: "Which of the following is the BEST example of good corporate governance in the finance function of a listed company?",
    options: [
      "The chief executive also chairing the board and the remuneration committee",
      "The finance director personally approving and releasing all major payments alone",
      "Setting executive bonuses solely on the current year's reported profit",
      "An audit committee of independent non-executive directors overseeing financial reporting and internal control",
    ],
    correct: 3,
    explanation:
      "An audit committee of independent non-executive directors provides objective oversight of financial reporting and internal control — a core governance safeguard. Combining the CEO and chair (and adding the remuneration committee chair) concentrates power and removes challenge; letting one person approve and release payments removes segregation of duties; basing bonuses only on current-year profit encourages short-termism and manipulation. Only the audit committee reflects good governance.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-A-10",
    paper: "AFM",
    area: "A",
    type: "mcq",
    stem: "An Integrated Report describes how an organisation creates value over time using the 'six capitals'. Which of the following is one of those six capitals?",
    options: [
      "Natural capital",
      "Deferred tax capital",
      "Working capital",
      "Share premium capital",
    ],
    correct: 0,
    explanation:
      "The Integrated Reporting framework's six capitals are financial, manufactured, intellectual, human, social-and-relationship, and natural capital — so natural capital is correct. Deferred tax and share premium are accounting balances, not IR capitals; working capital is a liquidity measure. Only natural capital belongs to the six-capitals model of value creation.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-A-11",
    paper: "AFM",
    area: "A",
    type: "mcq",
    stem: "What is the PRINCIPAL purpose of integrated reporting from the perspective of a senior financial adviser?",
    options: [
      "To replace the audited financial statements with a shorter narrative document",
      "To disclose the directors' personal tax positions",
      "To forecast the next period's share price for investors",
      "To explain how the organisation creates and preserves value over the short, medium and long term across financial and non-financial capitals",
    ],
    correct: 3,
    explanation:
      "Integrated reporting communicates how value is created, preserved or eroded over multiple time horizons across financial and non-financial capitals, giving providers of capital a fuller picture than the numbers alone. It complements rather than replaces the audited accounts; it is not a vehicle for directors' personal tax affairs; and it does not forecast share prices. Only the value-creation explanation captures the purpose of integrated reporting.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-A-12",
    paper: "AFM",
    area: "A",
    type: "mcq",
    stem: "During a bull market a senior manager keeps expanding an acquisition programme, dismissing warning signs and over-estimating the accuracy of their own forecasts. Which behavioural-finance bias does this MOST clearly illustrate?",
    options: [
      "Loss aversion",
      "Overconfidence bias",
      "Anchoring on the original purchase price",
      "Framing effect",
    ],
    correct: 1,
    explanation:
      "Systematically over-estimating the reliability of one's own judgement and forecasts is overconfidence bias, which typically leads to excessive risk-taking and value-destroying deals. Loss aversion is reluctance to realise losses; anchoring is fixating on an initial reference figure; framing is being swayed by how information is presented. The manager's inflated faith in their own forecasts points specifically to overconfidence.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM2-A-13",
    paper: "AFM",
    area: "A",
    type: "mcq",
    stem: "Investors ignore new fundamental information and instead buy a share simply because many other investors are buying it, driving the price above intrinsic value. Which behavioural-finance phenomenon is this?",
    options: [
      "Efficient arbitrage",
      "Home bias",
      "Herding",
      "Mental accounting",
    ],
    correct: 2,
    explanation:
      "Following the crowd and buying because others are buying, rather than on fundamentals, is herding, and it can push prices away from intrinsic value. Efficient arbitrage would correct mispricing, not cause it; home bias is over-weighting domestic assets; mental accounting is treating money differently by arbitrary category. The crowd-following behaviour described is herding.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-A-14",
    paper: "AFM",
    area: "A",
    type: "mcq",
    stem: "A central bank unexpectedly raises interest rates sharply. Holding other factors constant, how is this economic-environment change MOST likely to affect a firm's financial strategy?",
    options: [
      "The cost of debt falls, encouraging more borrowing",
      "Working-capital financing becomes cheaper",
      "Share prices rise because higher rates always signal growth",
      "The cost of capital rises, reducing the number of projects with a positive NPV",
    ],
    correct: 3,
    explanation:
      "Higher interest rates raise the cost of debt and, through it, the weighted average cost of capital, so fewer projects clear the higher hurdle rate and positive-NPV opportunities shrink. Rates rising means the cost of debt rises, not falls; higher rates typically depress, not lift, share prices as discount rates increase; and short-term financing becomes more, not less, expensive. Only the rise in the cost of capital is correct.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-A-15",
    paper: "AFM",
    area: "A",
    type: "mcq",
    stem: "A government introduces a new regulatory regime capping the gearing of banks and requiring higher capital buffers. For a senior financial adviser at an affected bank, the MOST direct financial-strategy consequence is:",
    options: [
      "The bank can freely increase its dividend because regulation improves confidence",
      "The bank may need to raise additional equity and reduce reliance on debt, lowering financial gearing",
      "The bank's tax charge falls automatically",
      "The regulation has no effect on the bank's cost of capital",
    ],
    correct: 1,
    explanation:
      "A cap on gearing plus higher capital buffers forces the bank to hold more equity and less debt, deleveraging its balance sheet and altering its financing decision. Tighter capital rules usually constrain, not free up, dividends; they do not automatically cut the tax charge; and shifting the debt/equity mix changes the weighted average cost of capital, so claiming no effect is wrong. Only the equity-raising/deleveraging consequence follows directly.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM2-A-16",
    paper: "AFM",
    area: "A",
    type: "mcq",
    stem: "Which statement best expresses how a firm's financial strategy should relate to its overall corporate strategy?",
    options: [
      "Financial strategy should support and enable the corporate strategy, ensuring funds are available for chosen investments on acceptable terms",
      "Financial strategy should be set entirely independently of corporate strategy",
      "Corporate strategy should be subordinated to whatever minimises this year's finance costs",
      "Financial strategy is only about preparing statutory accounts",
    ],
    correct: 0,
    explanation:
      "Financial strategy exists to enable the corporate strategy — securing the right quantity, cost and timing of finance for the investments the business chooses. Setting it independently of corporate goals risks funding the wrong things; subordinating corporate strategy to minimising short-term finance costs lets a secondary metric drive the business; and reducing financial strategy to statutory accounts confuses stewardship reporting with strategy. Only the enabling/supporting statement is correct.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-A-17",
    paper: "AFM",
    area: "A",
    type: "mcq",
    stem: "Which single measure most DIRECTLY reflects whether a listed company has increased shareholder wealth over a year?",
    options: [
      "Growth in reported revenue",
      "Total shareholder return (dividends received plus share-price appreciation)",
      "Growth in total assets on the statement of financial position",
      "The number of new products launched during the year",
    ],
    correct: 1,
    explanation:
      "Shareholder wealth is delivered as dividends plus capital gains, so total shareholder return measures it most directly. Revenue growth ignores costs, risk and cash timing; growth in total assets can reflect value-destroying spending or debt-funded expansion; product launches are an activity measure with no direct link to value. Only total shareholder return captures wealth created for owners.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM2-A-18",
    paper: "AFM",
    area: "A",
    type: "mcq",
    stem: "A public not-for-profit health authority cannot use shareholder-wealth maximisation as its objective. Which objective is MOST appropriate for its senior financial management?",
    options: [
      "Maximising earnings per share",
      "Maximising the market value of its equity",
      "Achieving value for money — economy, efficiency and effectiveness in delivering services",
      "Maximising the dividend paid to central government",
    ],
    correct: 2,
    explanation:
      "Not-for-profit and public bodies have no tradeable shares or profit motive, so they pursue value for money — the 'three Es' of economy, efficiency and effectiveness in service delivery. EPS and equity value require traded shares the body does not have; a health authority does not pay dividends to government. Only value for money fits a public not-for-profit entity.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM2-A-19",
    paper: "AFM",
    area: "A",
    type: "mcq",
    stem: "In a SEMI-STRONG form efficient market, share prices reflect:",
    options: [
      "Only the history of past share prices",
      "All information, including private insider information",
      "All publicly available information, including published accounts and announcements",
      "No information at all, so prices move randomly for no reason",
    ],
    correct: 2,
    explanation:
      "Semi-strong efficiency means prices fully reflect all publicly available information, so neither charting nor fundamental analysis of public data yields abnormal returns. Reflecting only past prices is the weak form; reflecting private/insider information as well is the strong form; and 'no information at all' misdescribes efficiency — prices move on information, they are just already impounded. Only the public-information option defines the semi-strong form.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM2-A-20",
    paper: "AFM",
    area: "A",
    type: "mcq",
    stem: "How can incorporating environmental, social and governance (ESG) considerations into financial strategy create long-term shareholder value?",
    options: [
      "By reducing reputational, regulatory and transition risks and opening access to lower-cost sustainable finance",
      "By always increasing short-term reported profit in the current year",
      "By allowing the firm to ignore financial returns entirely",
      "By guaranteeing a higher share price regardless of performance",
    ],
    correct: 0,
    explanation:
      "Managing ESG factors reduces reputational, regulatory and climate-transition risk and can unlock cheaper sustainability-linked finance, supporting long-term value. ESG investment often reduces near-term profit rather than always raising it; it does not license ignoring financial returns — value creation still matters; and nothing guarantees a higher share price irrespective of performance. Only the risk-reduction/finance-access option is defensible.",
    marks: 2,
    difficulty: "easy",
  },

  /* ═══════════ Area B — Advanced investment appraisal (40) ═══════════ */
  {
    id: "AFM2-B-01",
    paper: "AFM",
    area: "B",
    type: "mcq",
    stem: "When appraising a project, which of the following should be INCLUDED as a relevant cash flow?",
    options: [
      "Depreciation charged on the new machinery",
      "Market-research costs already incurred before the decision date",
      "Lost contribution from an existing product whose sales the new project will cannibalise",
      "An apportionment of existing head-office overhead that will not change",
    ],
    correct: 2,
    explanation:
      "Relevant cash flows are future, incremental cash flows caused by the decision, so lost contribution from cannibalised sales — an opportunity cost triggered by the project — is included. Depreciation is a non-cash accounting allocation; market-research already incurred is a sunk cost; and unchanged apportioned head-office overhead is not incremental. Only the lost contribution is a relevant cash flow.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM2-B-02",
    paper: "AFM",
    area: "B",
    type: "number",
    stem: "An investor requires a REAL return of 8% and expects general inflation of 4% over the project's life. Using the Fisher relationship, what is the equivalent MONEY (nominal) cost of capital, in %, to two decimal places?",
    numericAnswer: 12.32,
    unit: "%",
    tolerance: 0.1,
    explanation:
      "The Fisher relationship is (1 + money rate) = (1 + real rate)(1 + inflation). So 1 + money = 1.08 x 1.04 = 1.1232, giving a money rate of 0.1232 = 12.32%. The common error is simply adding the two rates (8% + 4% = 12%), which omits the cross-product term 0.08 x 0.04 = 0.0032 (0.32%).",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM2-B-03",
    paper: "AFM",
    area: "B",
    type: "mcq",
    stem: "According to Modigliani-Miller's Proposition I WITHOUT taxes, as a firm replaces equity with debt its weighted average cost of capital (WACC):",
    options: [
      "Remains constant, because the benefit of cheaper debt is offset by a rising cost of equity",
      "Falls continuously, because debt is always cheaper than equity",
      "Rises continuously, because debt increases bankruptcy risk",
      "Is undefined, because WACC cannot be calculated for a geared firm",
    ],
    correct: 0,
    explanation:
      "Without taxes, MM show that the total value of the firm — and hence its WACC — is independent of capital structure: as cheaper debt is added, the cost of equity rises exactly enough to leave WACC unchanged. Claiming WACC falls continuously ignores the rising cost of equity; the continuous-rise view is a bankruptcy-cost/traditional argument, not MM without taxes; and WACC is perfectly well defined for a geared firm. Only the constant-WACC answer is MM Proposition I without tax.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM2-B-04",
    paper: "AFM",
    area: "B",
    type: "number",
    stem: "Corveth plc buys a machine for $40m (t0), used for four years with no residual value. Money-terms operating net cash inflows are $15m per year (years 1-4). Corporation tax is 20%, paid in the same year as the related cash flow. Tax-allowable depreciation is straight-line at 25% per year, giving a tax saving each year. The money cost of capital is 12% (4-year annuity factor 3.037). Calculate the project NPV, in $m, to two decimal places.",
    numericAnswer: 2.52,
    unit: "$m",
    tolerance: 0.5,
    explanation:
      "After-tax operating cash flow = 15 x (1 - 0.20) = $12m per year. Tax-allowable depreciation = 40 x 25% = $10m per year, tax saving = 10 x 20% = $2m per year. Total annual after-tax cash flow = 12 + 2 = $14m for years 1-4. PV = 14 x 3.037 = $42.52m; NPV = 42.52 - 40 = $2.52m. The classic errors are forgetting the depreciation tax saving (NPV = 12 x 3.037 - 40 = -$3.55m) or taxing before deducting nothing at all (15 x 3.037 - 40 = +$5.56m).",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM2-B-05",
    paper: "AFM",
    area: "B",
    type: "mcq",
    stem: "The Adjusted Present Value (APV) method is MOST appropriate rather than a single WACC-based NPV when:",
    options: [
      "The project is small and does not change the firm's capital structure",
      "The project significantly changes the firm's capital structure or has project-specific financing side effects",
      "The firm has no debt in its capital structure",
      "The project's cash flows are certain and risk-free",
    ],
    correct: 1,
    explanation:
      "APV values the project as if all-equity financed (base case) and then adds the present value of financing side effects, so it is designed for situations where gearing changes materially or there are project-specific financing benefits (tax shields, subsidised loans, issue costs). A small project that leaves capital structure unchanged is fine for a constant-WACC NPV; an all-equity firm has no debt side effects to add; and risk-free certainty is irrelevant to the choice of method. Only the changing-capital-structure case calls for APV.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM2-B-06",
    paper: "AFM",
    area: "B",
    type: "number",
    stem: "As the first stage of an APV, Sondermere Ltd values a project as if all-equity financed. The initial outlay is $20m (t0) and after-tax operating cash flows are $6m per year for five years. The ungeared (all-equity) cost of equity is 11% (5-year annuity factor 3.696). Calculate the base-case NPV, in $m, to two decimal places.",
    numericAnswer: 2.18,
    unit: "$m",
    tolerance: 0.5,
    explanation:
      "The base-case NPV discounts the operating cash flows at the UNGEARED cost of equity (Keu = 11%), which reflects business risk only. PV of inflows = 6 x 3.696 = $22.18m; base-case NPV = 22.18 - 20 = $2.18m. The common error is discounting at the geared WACC instead of Keu, which would double-count the financing benefit that APV adds separately in stage two.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-B-07",
    paper: "AFM",
    area: "B",
    type: "mcq",
    stem: "In the Black-Scholes option-pricing model applied to a real option (e.g. an option to expand), if the VOLATILITY of the underlying project's value increases while all other inputs are unchanged, the value of the option will:",
    options: [
      "Decrease, because more volatility means more risk",
      "Stay the same, because volatility is not an input to the model",
      "Become negative, because the option can now expire worthless",
      "Increase, because greater volatility raises the chance of a large favourable outcome while the downside is capped",
    ],
    correct: 3,
    explanation:
      "An option's payoff is asymmetric: the holder gains from large favourable moves but the loss is limited to the premium, so higher volatility raises option value — volatility appears in d1 and d2 and pushes the call value up. It does not decrease value (that treats an option like a plain asset); volatility is very much an input (sigma); and an option value can fall to zero but is never negative. Only the increase is correct.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM2-B-08",
    paper: "AFM",
    area: "B",
    type: "number",
    stem: "To finance a project, Larkvane plc raises $40m of debt at a pre-tax interest rate of 6% per year, redeemable in full after five years. The corporation-tax rate is 25% and interest tax relief arises in the same year as the interest. The PV of the debt tax shield is found by discounting at the pre-tax cost of debt of 6% (5-year annuity factor 4.212). Calculate the present value of the tax shield, in $m, to two decimal places.",
    numericAnswer: 2.53,
    unit: "$m",
    tolerance: 0.5,
    explanation:
      "Annual interest = 40 x 6% = $2.4m; annual tax saving = 2.4 x 25% = $0.6m for five years. PV of the tax shield = 0.6 x 4.212 = $2.53m. A frequent error is discounting the $0.6m saving over an incorrect horizon, or applying the tax rate to the principal ($40m x 25% = $10m) as if the debt were perpetual, which overstates the shield for a five-year loan.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-B-09",
    paper: "AFM",
    area: "B",
    type: "mcq",
    stem: "A mining company holds the right, but not the obligation, to develop a second, larger mine in three years' time if the first mine proves successful. In real-option terms this is BEST described as:",
    options: [
      "An option to abandon (a put option)",
      "An option to expand / follow-on option (a call option)",
      "A forward contract to sell output",
      "An interest-rate swap",
    ],
    correct: 1,
    explanation:
      "A right (not obligation) to make a further investment if things go well is a follow-on or expansion option, which behaves like a call option on the value of the second project. An abandonment option is a put (the right to sell/exit); a forward contract is a binding obligation, not an option; and an interest-rate swap is a financing hedge, not a real investment option. Only the expansion-call description fits.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-B-10",
    paper: "AFM",
    area: "B",
    type: "number",
    stem: "Tavenholt plc must obtain $28.5m of NET finance for a project via a share issue. Issue costs are 5% of the GROSS amount raised. What gross amount must be raised, in $m, to two decimal places?",
    numericAnswer: 30.0,
    unit: "$m",
    tolerance: 0.2,
    explanation:
      "If issue costs are 5% of the gross amount G, the firm keeps 95% of G, so 0.95 x G = 28.5, giving G = 28.5 / 0.95 = $30.00m (issue costs = $1.50m). The common error is taking 5% of the net figure (28.5 x 1.05 = $29.93m), which wrongly applies the percentage to the net rather than the gross amount.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM2-B-11",
    paper: "AFM",
    area: "B",
    type: "mcq",
    stem: "In the Black-Scholes call formula c = Pa x N(d1) - Pe x N(d2) x e^(-rt), what does N(d2) most nearly represent?",
    options: [
      "The risk-neutral probability that the option will be exercised (finish in the money)",
      "The volatility of the underlying asset",
      "The risk-free rate of interest",
      "The intrinsic value of the option today",
    ],
    correct: 0,
    explanation:
      "N(d2) is the cumulative normal probability that d2 is not exceeded and, in the risk-neutral framework, approximates the probability that the option is exercised (finishes in the money); it therefore scales the present value of the exercise price paid. It is not volatility (that is sigma inside d1/d2), not the risk-free rate (that is r), and not the intrinsic value (which is Pa - Pe if positive). Only the exercise-probability interpretation is correct.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM2-B-12",
    paper: "AFM",
    area: "B",
    type: "number",
    stem: "Using Modigliani-Miller with taxes, a geared firm's cost of equity is Keg = Keu + (Keu - Kd)(1 - T)(D/E). For Pellworth plc, Keu = 12%, Kd = 7%, the tax rate T = 30% and the debt-to-equity ratio D/E = 0.5. Calculate the geared cost of equity Keg, in %, to two decimal places.",
    numericAnswer: 13.75,
    unit: "%",
    tolerance: 0.1,
    explanation:
      "Keg = 12 + (12 - 7)(1 - 0.30)(0.5) = 12 + 5 x 0.70 x 0.5 = 12 + 1.75 = 13.75%. The usual error is omitting the (1 - T) tax term, giving 12 + 5 x 0.5 = 14.50%, or inverting the gearing ratio and using E/D instead of D/E.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-B-13",
    paper: "AFM",
    area: "B",
    type: "mcq",
    stem: "Which theory is used to forecast the FUTURE SPOT exchange rate from the expected inflation differential between two countries?",
    options: [
      "The capital asset pricing model",
      "Purchasing power parity",
      "Interest rate parity",
      "The dividend growth model",
    ],
    correct: 1,
    explanation:
      "Purchasing power parity links expected future spot rates to the inflation differential — the currency of the higher-inflation country is expected to depreciate. Interest rate parity uses the INTEREST-rate differential to derive the forward rate, not the inflation-based spot forecast; the CAPM prices risky assets; and the dividend growth model values shares. Only PPP forecasts the future spot from inflation.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-B-14",
    paper: "AFM",
    area: "B",
    type: "number",
    stem: "A comparator company has an equity beta of 1.40 and a debt-to-equity ratio (D:E) of 0.40. The tax rate is 25% and debt is assumed to be risk-free (debt beta = 0). Using the standard ungearing formula, calculate the ASSET (ungeared) beta, to two decimal places.",
    numericAnswer: 1.08,
    unit: "",
    tolerance: 0.02,
    explanation:
      "With a debt beta of zero, asset beta = equity beta x E / [E + D(1 - T)] = 1.40 x 1 / [1 + 0.40 x (1 - 0.25)] = 1.40 / (1 + 0.30) = 1.40 / 1.30 = 1.077, i.e. 1.08. The common error is forgetting the (1 - T) factor, giving 1.40 / 1.40 = 1.00, or dividing by (1 + D/E) without the tax adjustment.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-B-15",
    paper: "AFM",
    area: "B",
    type: "mcq",
    stem: "A UK company appraises an overseas project. It can either (a) discount the foreign-currency cash flows at a foreign-currency discount rate and convert the resulting NPV at the spot rate, or (b) convert each year's foreign cash flow to sterling using forecast future spot rates and discount at a sterling rate. In a consistent, arbitrage-free set of assumptions these two approaches will give:",
    options: [
      "Materially different NPVs, so the higher one should always be chosen",
      "The foreign-currency method a higher NPV whenever the foreign currency is expected to weaken",
      "Different signs of NPV depending only on the spot rate used",
      "The same NPV, because interest rate parity links the discount rates and the exchange-rate forecasts",
    ],
    correct: 3,
    explanation:
      "When exchange-rate forecasts and discount rates are internally consistent (linked through interest rate parity), the home-currency and foreign-currency approaches give the SAME NPV — they are two routes to one value. They do not systematically differ, so you cannot 'pick the higher'; no method is inherently higher when a currency weakens once parity holds; and the NPV's sign is a property of the project, not merely of the spot rate chosen. Only the 'same NPV' answer is correct.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM2-B-16",
    paper: "AFM",
    area: "B",
    type: "number",
    stem: "A project's asset (ungeared) beta is 1.05. It will be financed at a target debt-to-equity ratio (D:E) of 0.60. The tax rate is 25% and debt is assumed risk-free (debt beta = 0). Using the standard regearing formula, calculate the project's EQUITY beta, to two decimal places.",
    numericAnswer: 1.52,
    unit: "",
    tolerance: 0.02,
    explanation:
      "Regearing: equity beta = asset beta x [1 + D(1 - T)/E] = 1.05 x [1 + 0.60 x (1 - 0.25)] = 1.05 x (1 + 0.45) = 1.05 x 1.45 = 1.5225, i.e. 1.52. The typical error is omitting the (1 - T) term (1.05 x 1.60 = 1.68) or ungearing again instead of regearing (dividing rather than multiplying).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-B-17",
    paper: "AFM",
    area: "B",
    type: "mcq",
    stem: "Why does a firm 'ungear' a comparator company's equity beta before using it to appraise a project?",
    options: [
      "To convert the beta into a standard deviation",
      "To add the comparator's tax losses to the calculation",
      "To strip out the comparator's financial risk, leaving a beta that reflects business risk only",
      "To increase the beta so the project looks riskier and is rejected",
    ],
    correct: 2,
    explanation:
      "An observed equity beta reflects both business risk and the comparator's own financial (gearing) risk. Ungearing removes the financial-risk element, leaving an asset beta driven by business risk alone, which can then be regeared to the appraising firm's own capital structure. It does not convert beta to a standard deviation, has nothing to do with importing tax losses, and is not a device to bias the project towards rejection. Only the 'strip out financial risk' explanation is correct.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-B-18",
    paper: "AFM",
    area: "B",
    type: "number",
    stem: "Using CAPM, a project's regeared equity beta is 1.52. The risk-free rate is 4% and the equity market risk premium (return on the market minus the risk-free rate) is 6%. Calculate the required cost of equity, in %, to two decimal places.",
    numericAnswer: 13.12,
    unit: "%",
    tolerance: 0.1,
    explanation:
      "CAPM: Ke = Rf + beta x (market risk premium) = 4 + 1.52 x 6 = 4 + 9.12 = 13.12%. The common error is multiplying the beta by the whole market return rather than the risk premium, or adding the premium without multiplying by beta (4 + 6 = 10%).",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM2-B-19",
    paper: "AFM",
    area: "B",
    type: "mcq",
    stem: "A US company expects to receive 315 million pesos from an overseas project at the end of year 1. The forecast year-1 exchange rate is 21 pesos per $1, and the company discounts dollar cash flows at 10%. What is the present value today of this receipt (year-1 discount factor at 10% = 0.909)?",
    options: [
      "$13.64m",
      "$15.00m",
      "$28.64m",
      "$6.61m",
    ],
    correct: 0,
    explanation:
      "Convert first: 315m pesos / 21 = $15m at the year-1 forecast rate. Then discount one year at 10%: 15 x 0.909 = $13.64m. $15.00m converts but forgets to discount; $28.64m and $6.61m both mishandle the conversion — inverting the peso-per-dollar rate or applying it more than once — so the dollar amount is already wrong before any discounting. Only $13.64m converts then discounts correctly.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM2-B-20",
    paper: "AFM",
    area: "B",
    type: "number",
    stem: "Using the Black-Scholes model to value a real option, Wrenmoor plc has: underlying project value Pa = $48m, exercise (investment) cost Pe = $50m, time to expiry t = 4 years, risk-free rate r = 5%, and volatility sigma = 25% (0.25). Calculate d1, to two decimal places. [d1 = (ln(Pa/Pe) + (r + 0.5 x sigma^2) x t) / (sigma x sqrt(t))]",
    numericAnswer: 0.57,
    unit: "",
    tolerance: 0.03,
    explanation:
      "sigma x sqrt(t) = 0.25 x sqrt(4) = 0.25 x 2 = 0.50. ln(Pa/Pe) = ln(48/50) = ln(0.96) = -0.0408. (r + 0.5 x sigma^2) x t = (0.05 + 0.5 x 0.0625) x 4 = (0.05 + 0.03125) x 4 = 0.08125 x 4 = 0.325. d1 = (-0.0408 + 0.325) / 0.50 = 0.2842 / 0.50 = 0.5684, i.e. 0.57. The common error is dropping the +0.5 x sigma^2 term or using sigma instead of sigma x sqrt(t) in the denominator.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM2-B-21",
    paper: "AFM",
    area: "B",
    type: "mcq",
    stem: "Under Modigliani-Miller WITH corporate taxes, as a firm increases its gearing (adds debt), the cost of equity and the WACC behave as follows:",
    options: [
      "Both the cost of equity and WACC stay constant",
      "The cost of equity rises with gearing, but WACC falls because of the debt tax shield",
      "The cost of equity falls and WACC rises",
      "Both rise together in equal proportion",
    ],
    correct: 1,
    explanation:
      "With taxes, adding debt still raises the cost of equity (equity holders bear more financial risk), but the tax deductibility of interest lowers the overall WACC as gearing rises, increasing firm value. The 'both constant' result is the no-tax MM case; the cost of equity does not fall with gearing; and WACC does not rise with gearing under MM-with-tax (that would be the traditional/bankruptcy-cost view at high gearing). Only 'cost of equity up, WACC down' matches MM with tax.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM2-B-22",
    paper: "AFM",
    area: "B",
    type: "number",
    stem: "Continuing the Wrenmoor real option (Pa = $48m, Pe = $50m, t = 4 years, r = 5%), from the normal-distribution tables N(d1) = 0.7157 and N(d2) = 0.5279. Using c = Pa x N(d1) - Pe x N(d2) x e^(-rt), calculate the value of the CALL (expansion) option, in $m, to two decimal places. Use e^(-0.05 x 4) = 0.8187.",
    numericAnswer: 12.74,
    unit: "$m",
    tolerance: 0.5,
    explanation:
      "d2 = d1 - sigma x sqrt(t) = 0.5684 - 0.50 = 0.0684, giving N(d1) = 0.7157 and N(d2) = 0.5279 as provided. c = 48 x 0.7157 - 50 x 0.5279 x 0.8187 = 34.3536 - 21.6105 = $12.74m. The common error is forgetting the e^(-rt) discount factor on the exercise-price term (48 x 0.7157 - 50 x 0.5279 = 34.35 - 26.40 = $7.96m), which overstates the deduction and understates the option value.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM2-B-23",
    paper: "AFM",
    area: "B",
    type: "mcq",
    stem: "Two bonds have the same yield and maturity, but Bond X has a higher Macaulay duration than Bond Y. If market interest rates rise, the price of Bond X will:",
    options: [
      "Fall by less than Bond Y's price, because higher duration means lower risk",
      "Be unaffected, because duration measures time, not price",
      "Rise, because higher-duration bonds gain when rates rise",
      "Fall by more than Bond Y's price, because higher duration means greater interest-rate sensitivity",
    ],
    correct: 3,
    explanation:
      "Duration measures the sensitivity of a bond's price to interest-rate changes: the higher the duration, the larger the price move for a given yield change, so Bond X falls MORE when rates rise. Higher duration means higher, not lower, risk; duration is precisely a price-sensitivity measure, so 'unaffected' is wrong; and bond prices fall (not rise) when rates rise. Only the 'falls by more' answer is correct.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM2-B-24",
    paper: "AFM",
    area: "B",
    type: "number",
    stem: "Wrenmoor also holds an option to ABANDON the same project (an American-style put approximated by put-call parity). Using p = c - Pa + Pe x e^(-rt), with the call value c = $12.74m, Pa = $48m, Pe = $50m and e^(-0.05 x 4) = 0.8187, calculate the value of the abandonment (put) option, in $m, to two decimal places.",
    numericAnswer: 5.68,
    unit: "$m",
    tolerance: 0.5,
    explanation:
      "Put-call parity: p = c - Pa + Pe x e^(-rt) = 12.74 - 48 + 50 x 0.8187 = 12.74 - 48 + 40.9365 = $5.68m. The common error is omitting the discount factor on Pe (12.74 - 48 + 50 = $14.74m), which treats the exercise price as undiscounted and grossly overstates the put value.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM2-B-25",
    paper: "AFM",
    area: "B",
    type: "mcq",
    stem: "What is the MAIN advantage of the Modified Internal Rate of Return (MIRR) over the ordinary IRR?",
    options: [
      "MIRR always gives a higher percentage than IRR",
      "MIRR does not require any estimate of the cost of capital",
      "MIRR assumes interim cash flows are reinvested at the cost of capital, and avoids the multiple-IRR problem",
      "MIRR ignores the time value of money, making it simpler",
    ],
    correct: 2,
    explanation:
      "MIRR reinvests interim cash flows at the firm's cost of capital (a more realistic assumption than IRR's implicit reinvestment at the IRR itself) and, because it produces a single figure, it avoids the multiple-IRR problem of projects with non-conventional cash flows. It does not always exceed IRR; it explicitly uses the cost of capital as the reinvestment/finance rate, so it is not free of that estimate; and it fully respects the time value of money. Only the reinvestment/single-rate answer is correct.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-B-26",
    paper: "AFM",
    area: "B",
    type: "number",
    stem: "The current spot rate is 20.00 pesos per $1. Expected annual inflation is 8% in the peso economy and 3% in the US. Using purchasing power parity, forecast the expected spot rate in one year, in pesos per $1, to two decimal places. [Future rate = spot x (1 + peso inflation) / (1 + US inflation)]",
    numericAnswer: 20.97,
    unit: "pesos",
    tolerance: 0.1,
    explanation:
      "PPP: future rate (pesos per $) = 20.00 x (1.08 / 1.03) = 20.00 x 1.048544 = 20.97 pesos per $1. The higher-inflation peso depreciates, so it takes MORE pesos to buy $1. The common error is inverting the ratio (20 x 1.03 / 1.08 = 19.07), which wrongly makes the high-inflation currency strengthen.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-B-27",
    paper: "AFM",
    area: "B",
    type: "mcq",
    stem: "Why might a company use a RISK-ADJUSTED (project-specific) discount rate rather than its single overall WACC to appraise a new project?",
    options: [
      "Because the project's business risk differs from that of the firm's existing operations",
      "Because project-specific rates are always lower and improve the NPV",
      "Because the WACC cannot be used for any project appraisal",
      "Because tax rules require a different rate for every project",
    ],
    correct: 0,
    explanation:
      "The firm's WACC reflects the risk of its EXISTING business; if a new project has different business (systematic) risk, discounting at the overall WACC misprices it, so a project-specific rate derived from a comparator's beta is more appropriate. Project-specific rates are not always lower — a riskier project needs a HIGHER rate; the WACC is perfectly usable when a project matches the firm's risk; and tax rules do not mandate a unique rate per project. Only the differing-business-risk reason is correct.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-B-28",
    paper: "AFM",
    area: "B",
    type: "number",
    stem: "The current spot rate is 20.00 pesos per $1. The one-year interest rate is 9% in the peso economy and 4% in the US. Using interest rate parity, calculate the one-year forward rate, in pesos per $1, to two decimal places. [Forward = spot x (1 + peso interest) / (1 + US interest)]",
    numericAnswer: 20.96,
    unit: "pesos",
    tolerance: 0.1,
    explanation:
      "IRP: forward rate (pesos per $) = 20.00 x (1.09 / 1.04) = 20.00 x 1.048077 = 20.96 pesos per $1. The higher-interest peso trades at a forward discount (more pesos per dollar). The common error is inverting the interest ratio (20 x 1.04 / 1.09 = 19.08) or using the inflation figures from a PPP question by mistake.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-B-29",
    paper: "AFM",
    area: "B",
    type: "mcq",
    stem: "In an APV appraisal, which of the following is a FINANCING side effect that would be added to (or deducted from) the base-case NPV?",
    options: [
      "The operating cash flows generated by selling the product",
      "The present value of the tax relief on the debt raised to finance the project",
      "The depreciation charged in the management accounts",
      "The change in the firm's ordinary sales revenue",
    ],
    correct: 1,
    explanation:
      "APV adds the present value of financing side effects — chiefly the debt interest tax shield, plus items such as issue costs and any subsidised-loan benefit — to the all-equity base-case NPV. Operating cash flows and sales revenue belong in the base case, not the financing adjustment; and depreciation is a non-cash accounting entry (only its tax effect matters, and that sits in the base case). Only the debt tax-relief PV is a financing side effect.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-B-30",
    paper: "AFM",
    area: "B",
    type: "number",
    stem: "A bond has three years to maturity, a 6% annual coupon on $100 par, is redeemed at par, and is priced at par ($100) to yield 6%. Cash flows are $6, $6 and $106. Calculate the Macaulay duration, in years, to two decimal places. [Discount at 6%: year-1 factor 0.9434, year-2 0.8900, year-3 0.8396.]",
    numericAnswer: 2.83,
    unit: "years",
    tolerance: 0.05,
    explanation:
      "PV of each cash flow: yr1 6 x 0.9434 = 5.660; yr2 6 x 0.8900 = 5.340; yr3 106 x 0.8396 = 89.001; total = 100.00. Time-weighted PVs: (1 x 5.660) + (2 x 5.340) + (3 x 89.001) = 5.660 + 10.680 + 267.003 = 283.343. Macaulay duration = 283.343 / 100.00 = 2.83 years. The common error is quoting the 3-year maturity as the duration, ignoring that the early coupons pull the weighted average below maturity.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM2-B-31",
    paper: "AFM",
    area: "B",
    type: "mcq",
    stem: "A project has a negative conventional NPV of -$2m but also carries a valuable option to expand later, worth $5m using Black-Scholes. Under the 'expanded (strategic) NPV' approach, the project's overall value is:",
    options: [
      "-$2m, because only the conventional NPV counts",
      "-$7m, because the option cost is added to the negative NPV",
      "$5m, because the option value replaces the NPV entirely",
      "+$3m, because expanded NPV = conventional NPV + value of the real option",
    ],
    correct: 3,
    explanation:
      "Expanded (strategic) NPV = conventional NPV + value of the embedded real option = -2 + 5 = +$3m, so a project that looks unattractive on a static NPV can be worthwhile once flexibility is valued. Using only the -$2m ignores the option; -$7m wrongly treats the option as a cost rather than a benefit; and $5m double-discards the base project instead of adding the two. Only +$3m applies expanded NPV correctly.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM2-B-32",
    paper: "AFM",
    area: "B",
    type: "number",
    stem: "A project has a present value of the return-phase cash inflows (PVR) of $14m and a present value of the investment-phase outflows (PVI) of $10m. The project life is 4 years and the reinvestment (cost of capital) rate is 10%. Using MIRR = [(PVR / PVI)^(1/n)] x (1 + re) - 1, calculate the MIRR, in %, to two decimal places.",
    numericAnswer: 19.65,
    unit: "%",
    tolerance: 0.1,
    explanation:
      "PVR / PVI = 14 / 10 = 1.40. (1.40)^(1/4) = 1.40^0.25 = 1.08776. Multiply by (1 + re) = 1.10: 1.08776 x 1.10 = 1.19653. MIRR = 1.19653 - 1 = 0.19653 = 19.65%. The common error is taking the fourth root of the wrong ratio, or forgetting to multiply by (1 + re) and subtract 1.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM2-B-33",
    paper: "AFM",
    area: "B",
    type: "mcq",
    stem: "When deriving a project-specific discount rate using CAPM, which beta should be regeared to the appraising firm's capital structure?",
    options: [
      "The appraising firm's own existing equity beta",
      "The comparator's equity beta, used without any adjustment",
      "The asset (ungeared) beta obtained by ungearing a comparator in the same business",
      "A beta of 1.0, because all projects have average market risk",
    ],
    correct: 2,
    explanation:
      "The correct process is to take a pure-play comparator's equity beta, ungear it to an asset beta (removing the comparator's financial risk), then regear that asset beta to the appraising firm's own capital structure. Using the appraising firm's existing equity beta imports the wrong business risk; using the comparator's equity beta unadjusted carries the comparator's gearing; and assuming beta = 1.0 ignores the project's actual systematic risk. Only regearing the ungeared comparator asset beta is correct.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "AFM2-B-34",
    paper: "AFM",
    area: "B",
    type: "number",
    stem: "Completing an APV, Sondermere Ltd has a base-case (all-equity) NPV of $5.0m, a present value of the debt tax shield of $1.2m, and issue costs on the financing of $0.8m. Calculate the Adjusted Present Value, in $m, to two decimal places.",
    numericAnswer: 5.4,
    unit: "$m",
    tolerance: 0.5,
    explanation:
      "APV = base-case NPV + PV of financing benefits - financing costs = 5.0 + 1.2 - 0.8 = $5.40m. The tax shield is a benefit (added) and issue costs are a cost (deducted). The common error is deducting the tax shield or adding the issue costs (5.0 - 1.2 + 0.8 = $4.60m), reversing both signs.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-B-35",
    paper: "AFM",
    area: "B",
    type: "mcq",
    stem: "Which of the following BEST describes economic (operating) exposure, as opposed to transaction exposure?",
    options: [
      "The long-term effect of exchange-rate changes on the present value of a firm's future operating cash flows and competitive position",
      "The risk on a specific foreign-currency receivable due in three months",
      "The effect of retranslating overseas subsidiaries' balances at the year-end rate",
      "The bid-offer spread charged by the bank on a spot deal",
    ],
    correct: 0,
    explanation:
      "Economic (operating) exposure is the longer-term impact of currency movements on the value of a firm's future operating cash flows and its competitive position, even where no specific contracted item exists. A three-month receivable is transaction exposure; retranslating subsidiary balances is translation (accounting) exposure; and a bid-offer spread is a dealing cost, not an exposure. Only the future-cash-flow/competitive-position answer describes economic exposure.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-B-36",
    paper: "AFM",
    area: "B",
    type: "number",
    stem: "Using Modigliani-Miller with taxes, the value of a geared firm equals the value of an equivalent ungeared firm plus the tax shield on debt: Vg = Vu + (T x D). An ungeared firm is worth $80m, the tax rate is 30%, and the geared version carries $25m of debt. Calculate the value of the geared firm, in $m, to two decimal places.",
    numericAnswer: 87.5,
    unit: "$m",
    tolerance: 0.5,
    explanation:
      "The present value of the perpetual debt tax shield is T x D = 0.30 x 25 = $7.5m, so Vg = Vu + T x D = 80 + 7.5 = $87.50m. The common error is adding the full debt (80 + 25 = $105m), ignoring that only the tax shield (not the debt principal) adds value in the MM-with-tax model.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "AFM2-B-37",
    paper: "AFM",
    area: "B",
    type: "mcq",
    stem: "In sensitivity analysis of a project's NPV, the 'sensitivity' of a single input variable is calculated as:",
    options: [
      "The standard deviation of the project's cash flows",
      "The NPV divided by the present value of the variable under review, expressed as a percentage",
      "The internal rate of return minus the cost of capital",
      "The probability that the project has a negative NPV",
    ],
    correct: 1,
    explanation:
      "Sensitivity of a variable = project NPV / present value of the flows relating to that variable, expressed as a percentage; it shows the % change in that variable that would reduce the NPV to zero. The standard deviation of cash flows is a risk (dispersion) measure, not a sensitivity; IRR minus cost of capital is a margin on the discount rate; and the probability of a negative NPV comes from simulation, not single-variable sensitivity. Only the NPV-over-PV-of-variable formula is correct.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-B-38",
    paper: "AFM",
    area: "B",
    type: "number",
    stem: "A US firm's overseas project generates 210 million pesos at the end of year 1. The forecast year-1 spot rate is 21 pesos per $1 and the firm discounts dollar cash flows at 10% (year-1 discount factor 0.909). Calculate the present value today of this cash flow, in $m, to two decimal places.",
    numericAnswer: 9.09,
    unit: "$m",
    tolerance: 0.5,
    explanation:
      "Convert at the year-1 forecast rate: 210m pesos / 21 = $10m. Discount one year at 10%: 10 x 0.909 = $9.09m. The common error is multiplying by 21 instead of dividing, or omitting the one-year discounting and reporting $10m.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-B-39",
    paper: "AFM",
    area: "B",
    type: "mcq",
    stem: "A senior adviser is integrating the financing decision into an investment appraisal. Which statement about a firm's debt capacity is CORRECT?",
    options: [
      "Debt capacity is irrelevant because firms can borrow unlimited amounts at the risk-free rate",
      "Taking on debt beyond the firm's debt capacity reduces WACC indefinitely with no downside",
      "A firm should always be 100% debt financed to maximise the tax shield",
      "Beyond a point, higher gearing raises the risk of financial distress, increasing both the cost of debt and the cost of equity and eventually raising WACC",
    ],
    correct: 3,
    explanation:
      "Once gearing rises past a prudent level, the probability of financial distress increases, lenders demand higher yields and equity holders demand higher returns, so beyond the optimum the WACC starts to rise — debt capacity is real and finite. Firms cannot borrow unlimited amounts at the risk-free rate; WACC does not fall indefinitely; and 100% debt financing ignores distress costs and the practical impossibility of an all-debt firm. Only the financial-distress answer is correct.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "AFM2-B-40",
    paper: "AFM",
    area: "B",
    type: "number",
    stem: "Havershaw plc is financed by equity of $60m with a cost of equity of 12%, and debt of $40m with a pre-tax cost of debt of 8%. The corporation-tax rate is 25%. Using market-value weights, calculate the after-tax WACC, in %, to two decimal places.",
    numericAnswer: 9.6,
    unit: "%",
    tolerance: 0.1,
    explanation:
      "Total capital = 60 + 40 = $100m, so weights are 0.60 equity and 0.40 debt. After-tax cost of debt = 8 x (1 - 0.25) = 6%. WACC = (0.60 x 12) + (0.40 x 6) = 7.2 + 2.4 = 9.60%. The common error is using the pre-tax cost of debt (0.60 x 12 + 0.40 x 8 = 10.4%), forgetting the tax relief on interest.",
    marks: 2,
    difficulty: "medium",
  },
]
