import type { Flashcard } from "@/lib/acca-flashcards"

/* Flashcard wave 5 — top-up: every paper ≥60 (2026-07-12). */
export const FLASHCARDS_WAVE5: Flashcard[] = [
  /* ── FA — Financial Accounting (+2) ─────────────────────────── */
  { id: "FA-FC4-01", paper: "FA", area: "F", front: "A 5-year bank loan has $10,000 falling due within the next 12 months — how is it presented?", back: "Split it: the $10,000 due within a year is a CURRENT liability; the rest stays non-current. Showing the whole loan as non-current overstates liquidity." },
  { id: "FA-FC4-02", paper: "FA", area: "G", front: "A $5,000 loan is outstanding between parent and subsidiary at the year end — consolidated treatment?", back: "Cancel the intragroup receivable against the intragroup payable in full. The group cannot owe money to itself, so neither balance appears in the consolidated statement of financial position." },

  /* ── FR — Financial Reporting (+1) ──────────────────────────── */
  { id: "FR-FC4-01", paper: "FR", area: "D", front: "Deriving cash paid for PPE additions in the statement of cash flows", back: "Cash additions = closing carrying amount + depreciation charged + carrying amount of disposals − revaluation gains − opening carrying amount. Reconstruct the PPE account — the balancing figure is the cash spent." },

  /* ── PM — Performance Management (+9) ───────────────────────── */
  { id: "PM-FC4-01", paper: "PM", area: "A", front: "The four categories of environmental costs", back: "Environmental PREVENTION costs (avoid pollution), environmental DETECTION/appraisal costs (monitoring, inspections), environmental INTERNAL failure costs (clean-up before release), environmental EXTERNAL failure costs (damage after release — fines, remediation, lost reputation)." },
  { id: "PM-FC4-02", paper: "PM", area: "A", front: "Trap: how is inventory valued in throughput accounting?", back: "At direct MATERIAL cost only — no labour or overhead is ever carried into inventory. This removes the incentive to over-produce just to absorb overheads." },
  { id: "PM-FC4-03", paper: "PM", area: "B", front: "When does linear programming replace key-factor (limiting-factor) analysis?", back: "When there are TWO OR MORE scarce resources. With a single constraint, rank by contribution per unit of the scarce resource; with several, formulate constraints and an objective function and solve graphically." },
  { id: "PM-FC4-04", paper: "PM", area: "B", front: "The value of perfect information", back: "EV WITH perfect information − EV of the best decision WITHOUT it. It is the maximum worth paying for a perfect forecast; imperfect information is worth less." },
  { id: "PM-FC4-05", paper: "PM", area: "B", front: "Three conditions for price discrimination to work", back: "The seller can identify distinct market segments; the segments have DIFFERENT price elasticities of demand; and resale between segments (seepage) can be prevented." },
  { id: "PM-FC4-06", paper: "PM", area: "C", front: "When does the learning-curve effect NOT apply?", back: "Where output is machine-paced, the process is not labour-intensive, production is intermittent (breaks destroy learning), the workforce changes constantly, or the product is mature and a steady state has been reached." },
  { id: "PM-FC4-07", paper: "PM", area: "C", front: "'Beyond budgeting' — the core idea", back: "Abandon the annual fixed budget in favour of ROLLING forecasts and RELATIVE targets (benchmarked against competitors and internal peers), with decision-making devolved to front-line managers." },
  { id: "PM-FC4-08", paper: "PM", area: "D", front: "CSF vs KPI — the distinction", back: "A critical success factor is an AREA where performance must be strong for the strategy to succeed (e.g. product quality). A key performance indicator is the MEASURE used to monitor it (e.g. % of units returned). One CSF usually drives several KPIs." },
  { id: "PM-FC4-09", paper: "PM", area: "D", front: "Transfer price set at full cost plus a mark-up — the danger?", back: "The seller's FIXED costs arrive at the buyer looking like VARIABLE costs, so the buying division may reject work that would benefit the group — and the seller has no incentive to control costs, since they are all passed on." },

  /* ── TX — Taxation, UK FA2024 (+3) ──────────────────────────── */
  { id: "TX-FC4-01", paper: "TX", area: "D", front: "VAT late-submission penalties — the points system", back: "One penalty point per late return. A quarterly filer reaching 4 points pays a £200 penalty, plus £200 for each further late return while at the threshold. Points expire after a 12-month period of full compliance (for quarterly returns)." },
  { id: "TX-FC4-02", paper: "TX", area: "E", front: "How is a lifetime gift VALUED for IHT?", back: "By the DIMINUTION in the donor's estate — the fall in value of what the donor holds — not the value received by the donee. Classic case: gifting 2% of shares that drops a holding from 51% (control) to 49% costs far more than 2% of the company's value." },
  { id: "TX-FC4-03", paper: "TX", area: "E", front: "The spouse/civil partner exemption for IHT", back: "Transfers between spouses/civil partners are exempt WITHOUT LIMIT, in lifetime and on death — restricted to £325,000 where a UK-domiciled person gives to a non-UK-domiciled spouse (unless the recipient elects to be treated as UK domiciled)." },

  /* ── AA — Audit & Assurance (+7) ────────────────────────────── */
  { id: "AA-FC4-01", paper: "AA", area: "A", front: "Gifts and hospitality offered by an audit client — the rule", back: "Accept only if the value is TRIVIAL AND INCONSEQUENTIAL. Anything more creates self-interest and familiarity threats that no safeguard can reduce — decline it." },
  { id: "AA-FC4-02", paper: "AA", area: "A", front: "The audit engagement letter — purpose and key contents", back: "Written confirmation of the terms of the engagement: the objective and scope of the audit, the auditor's and management's responsibilities, the reporting framework, and the expected form of the reports. It manages the expectation gap; reissue when terms or circumstances change." },
  { id: "AA-FC4-03", paper: "AA", area: "A", front: "The preconditions for an audit (ISA 210)", back: "1) The financial reporting framework is acceptable. 2) Management acknowledges its responsibility for preparing the statements, for internal control, and for giving the auditor access to all relevant information and people." },
  { id: "AA-FC4-04", paper: "AA", area: "B", front: "Items that are material by NATURE, whatever their size", back: "Transactions with directors and related parties, misstatements that turn a profit into a loss (or reverse a trend), amounts that breach loan covenants or regulatory thresholds, and inadequate or misleading descriptions of accounting policies." },
  { id: "AA-FC4-05", paper: "AA", area: "C", front: "Trap: testing the COMPLETENESS of trade payables — where do you start?", back: "OUTSIDE the ledger: from GRNs, supplier statements and post-year-end payments, tracing INTO the payables ledger to find unrecorded liabilities. Starting from the ledger only tests existence — payables misstatement risk is understatement." },
  { id: "AA-FC4-06", paper: "AA", area: "E", front: "Uncorrected misstatements at completion (ISA 450) — the routine", back: "Accumulate all misstatements above the 'clearly trivial' threshold, communicate them and request correction; assess whether the uncorrected total (individually or in aggregate) is material; obtain a written representation that management believes them immaterial. Material and uncorrected → modify the opinion." },
  { id: "AA-FC4-07", paper: "AA", area: "E", front: "The auditor's duty over 'other information' in the annual report (ISA 720)", back: "READ it and consider whether it is materially inconsistent with the financial statements or the auditor's knowledge. An uncorrected misstatement OF the other information is described in the report's Other Information section — the opinion itself is not modified." },

  /* ── FM — Financial Management (+7) ─────────────────────────── */
  { id: "FM-FC4-01", paper: "FM", area: "A", front: "Dividend yield and EPS — the formulas", back: "Dividend yield = dividend per share ÷ current share price × 100%. EPS = profit attributable to ordinary shareholders (after tax and preference dividends) ÷ number of ordinary shares." },
  { id: "FM-FC4-02", paper: "FM", area: "A", front: "Primary vs secondary capital markets", back: "Primary: NEW securities are issued and the company raises fresh funds. Secondary: EXISTING securities trade between investors — the company gets no cash, but the liquidity this provides is what makes investors willing to buy new issues." },
  { id: "FM-FC4-03", paper: "FM", area: "A", front: "Maximising vs satisficing objectives", back: "Maximising seeks the best possible outcome for one group (shareholder wealth). Satisficing seeks outcomes merely GOOD ENOUGH to keep each stakeholder group acceptable — the practical response to conflicting stakeholder objectives." },
  { id: "FM-FC4-04", paper: "FM", area: "C", front: "Assessing a NEW credit customer — the information sources", back: "Bank reference, trade references from existing suppliers, credit agency reports, the customer's published financial statements — then set a low initial credit limit and review it as the payment record builds." },
  { id: "FM-FC4-05", paper: "FM", area: "E", front: "Forward contract vs currency futures", back: "Forward: a tailored, over-the-counter bank contract for the exact amount and date — binding, no upfront cost, but no flexibility. Futures: standardised, exchange-traded contracts requiring margin — liquid and closed out before delivery, but standard sizes/dates leave basis risk." },
  { id: "FM-FC4-06", paper: "FM", area: "E", front: "When is a currency OPTION worth its premium?", back: "It is a right, not an obligation — so use it when the cash flow itself is uncertain (e.g. awaiting a tender result) or to keep the upside if rates move favourably. The certainty of forwards is cheaper; the option's flexibility is what the premium buys." },
  { id: "FM-FC4-07", paper: "FM", area: "E", front: "Purchasing power parity — the expected future spot rate", back: "Expected spot = current spot × (1 + inflation of the counter/variable currency) ÷ (1 + inflation of the base currency). The higher-inflation currency is expected to DEPRECIATE — the law of one price at work." },

  /* ── MA — Management Accounting (+6) ────────────────────────── */
  { id: "MA-FC4-01", paper: "MA", area: "A", front: "Strategic, tactical and operational information — the ladder", back: "Strategic: long-term, highly summarised, internal AND external sources, for senior management. Tactical: medium-term departmental control, for middle management. Operational: detailed, day-to-day transaction level, for supervisors." },
  { id: "MA-FC4-02", paper: "MA", area: "A", front: "The main sampling methods", back: "Random (every item an equal chance, needs a sampling frame); systematic (every nth item); stratified (split the population into groups, sample each in proportion); multistage; cluster (sample whole subgroups); quota (interviewer fills set quotas — non-random)." },
  { id: "MA-FC4-03", paper: "MA", area: "C", front: "Restating a cost to current prices with an index", back: "Restated cost = historical cost × (index NOW ÷ index WHEN the cost was incurred). The same logic deflates current figures back to base-year terms for a like-with-like trend." },
  { id: "MA-FC4-04", paper: "MA", area: "E", front: "Balanced scorecard — one typical measure per perspective", back: "Financial: ROCE or revenue growth. Customer: retention rate or complaints. Internal business process: defect rate or throughput time. Learning & growth: training hours or % revenue from new products." },
  { id: "MA-FC4-05", paper: "MA", area: "E", front: "Idle time ratio", back: "Idle hours ÷ total hours × 100%, where idle hours = hours paid for but not worked. A rising ratio flags poor scheduling, machine breakdowns or material shortages." },
  { id: "MA-FC4-06", paper: "MA", area: "E", front: "Non-financial performance measures for QUALITY", back: "Reject/defect rate, % of deliveries returned, warranty claims, customer complaints per 1,000 orders, and % of repeat business. They lead the financial results that poor quality eventually destroys." },

  /* ── BT — Business and Technology (+7) ──────────────────────── */
  { id: "BT-FC4-01", paper: "BT", area: "A", front: "SWOT analysis — which elements are internal and which external?", back: "Strengths and Weaknesses are INTERNAL (resources, capabilities). Opportunities and Threats are EXTERNAL (market, environment). The internal pair is what you are; the external pair is what you face." },
  { id: "BT-FC4-02", paper: "BT", area: "A", front: "Outsourcing vs a shared services centre", back: "Outsourcing: an external third party runs the function under contract. Shared services centre: one INTERNAL centre performs the function (finance, IT, HR) for the whole group. Both standardise and cut cost — the SSC keeps control and knowledge in-house." },
  { id: "BT-FC4-03", paper: "BT", area: "B", front: "The psychological contract — and its three types", back: "The unwritten mutual expectations between individual and organisation. Coercive: the individual complies unwillingly. Calculative: effort is exchanged for identifiable rewards. Cooperative: the individual identifies with the organisation's goals — the most motivating." },
  { id: "BT-FC4-04", paper: "BT", area: "C", front: "Rules-based vs principles-based governance codes", back: "Rules-based: legally binding requirements with sanctions for breach (e.g. US Sarbanes-Oxley). Principles-based: 'comply or explain' — follow the code or tell shareholders why not (e.g. the UK Corporate Governance Code)." },
  { id: "BT-FC4-05", paper: "BT", area: "C", front: "The triple bottom line", back: "Report performance on three Ps: PROFIT (economic), PEOPLE (social) and PLANET (environmental) — sustainability means delivering on all three, not just the financial one." },
  { id: "BT-FC4-06", paper: "BT", area: "D", front: "Cloud computing — two benefits and two risks", back: "Benefits: scalability with pay-as-you-use cost, and access from anywhere with automatic updates. Risks: data security and privacy in a third party's hands, and dependence on the provider and the internet connection." },
  { id: "BT-FC4-07", paper: "BT", area: "D", front: "Data protection — the core principles", back: "Personal data must be processed lawfully and fairly, collected for specified purposes, adequate and limited to what is needed, accurate, kept no longer than necessary, and held securely — with data subjects having rights of access and correction." },

  /* ── LW — Corporate and Business Law, ENG (+7) ──────────────── */
  { id: "LW-FC4-01", paper: "LW", area: "A", front: "The civil court hierarchy for precedent — top down", back: "Supreme Court → Court of Appeal → High Court → County Court. Each court binds those below it; the Court of Appeal also binds itself (subject to the Young v Bristol Aeroplane exceptions); County Court decisions bind no one." },
  { id: "LW-FC4-02", paper: "LW", area: "A", front: "The purposive approach to statutory interpretation", back: "Construe the words to give effect to the PURPOSE Parliament intended, rather than their strict literal meaning — the modern approach, especially for broadly drafted and human-rights legislation." },
  { id: "LW-FC4-03", paper: "LW", area: "A", front: "Intrinsic vs extrinsic aids to interpretation", back: "Intrinsic: within the Act itself — the long title, preamble, headings and definition sections. Extrinsic: outside it — dictionaries, the Interpretation Act 1978, and Hansard (allowed where legislation is ambiguous: Pepper v Hart)." },
  { id: "LW-FC4-04", paper: "LW", area: "C", front: "Statutory minimum notice periods", back: "Employer to employee: 1 week after one month's service, then 1 week per complete year of service from 2 to 12 years — capped at 12 weeks. Employee to employer: 1 week after one month, however long the service." },
  { id: "LW-FC4-05", paper: "LW", area: "C", front: "How is a statutory redundancy payment calculated?", back: "Per complete year of service (max 20 years), by age band: half a week's pay for years under age 22; one week for ages 22-40; one and a half weeks for ages 41+ — with a week's pay subject to a statutory cap." },
  { id: "LW-FC4-06", paper: "LW", area: "C", front: "Restraint of trade clauses in employment contracts — when enforceable?", back: "Prima facie VOID. Enforceable only if they protect a LEGITIMATE business interest (trade secrets, customer connections — never bare competition) AND are reasonable in duration, geographical area and scope." },
  { id: "LW-FC4-07", paper: "LW", area: "C", front: "Vicarious liability — when is the employer liable for an employee's tort?", back: "When the tort is committed IN THE COURSE OF EMPLOYMENT — including authorised acts done in a wrongful, even prohibited, way. Not for independent contractors, nor for an employee off on a 'frolic of their own'." },
]
