import type { AccaQuestion } from "@/lib/acca-content"

/* FR bank wave 6b — areas D-E, 45 verified originals (2026-07-10). */

export const FR_WAVE3B: AccaQuestion[] = [
  /* ───────────── Area D — preparation of financial statements (20) ───────────── */
  {
    id: "FR3-D-01",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Halden Co's year end is 31 December 20X4. Plant at cost on 1 January 20X4 was $600,000. On 1 April 20X4 it bought new plant for $120,000, and on 30 September 20X4 it sold plant that had cost $80,000. Depreciation is 20% per annum straight line, pro rata by month, charged up to the date of disposal. What is the depreciation charge for the year?",
    options: ["$144,000", "$122,000", "$134,000", "$140,000"],
    correct: 2,
    explanation:
      "Continuing plant ($600,000 − $80,000) × 20% = $104,000; disposed plant $80,000 × 20% × 9/12 = $12,000; addition $120,000 × 20% × 9/12 = $18,000. Total $134,000. $144,000 charges a full year on everything held at any point, $122,000 forgets to depreciate the disposed plant up to 30 September, and $140,000 charges a full year on the April addition.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-D-02",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Brelford Co bought a building for $720,000 on 1 January 20X0 (30-year life, nil residual). On 1 July 20X5 it was revalued for the first time to $735,000, with the total useful life unchanged. What is the depreciation charge for the year ended 31 December 20X5?",
    options: ["$27,000", "$24,000", "$30,000", "$15,000"],
    correct: 0,
    explanation:
      "Under IAS 16 the charge is split at the revaluation date: 6 months on the old basis ($720,000 ÷ 30 × 6/12 = $12,000), then the revalued $735,000 over the REMAINING 24.5 years ($30,000 p.a. × 6/12 = $15,000). Total $27,000. $24,000 ignores the revaluation entirely, $30,000 applies the new annual charge to the whole year, and $15,000 forgets the pre-revaluation six months.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-D-03",
    paper: "FR",
    area: "D",
    type: "number",
    stem: "Kembury Co had an electricity accrual of $9,000 brought forward at 1 January. Cash paid to the supplier during the year was $74,000, and at 31 December an estimated $12,000 was owed for November and December. What electricity expense appears in profit or loss for the year, in $?",
    numericAnswer: 77000,
    unit: "$",
    tolerance: 0,
    explanation:
      "Expense = cash paid − opening accrual reversed + closing accrual = $74,000 − $9,000 + $12,000 = $77,000. Adding the closing accrual without reversing the opening one gives $86,000, and reversing the adjustments the wrong way round gives $71,000 — both classic accruals slips.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-D-04",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "During the year ended 31 December 20X5, Tarnley Co paid an interim dividend of $30,000 in August. In February 20X6, before the financial statements were authorised for issue, the directors proposed a final dividend of $50,000. How are the dividends reported in the 20X5 financial statements?",
    options: [
      "$80,000 is deducted from retained earnings in the statement of changes in equity",
      "$30,000 is deducted in the statement of changes in equity; the $50,000 is disclosed in the notes only",
      "$30,000 is charged as an expense in profit or loss and $50,000 is a current liability",
      "$30,000 is deducted in the statement of changes in equity and $50,000 is a current liability",
    ],
    correct: 1,
    explanation:
      "Only dividends DECLARED by the year end are recognised; under IAS 10 a dividend proposed after the reporting date creates no obligation at 31 December, so the $50,000 is disclosure only. Deducting $80,000 recognises the proposed dividend too early, dividends are never a P/L expense, and there is no liability for the final dividend.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR3-D-05",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Vostell Co estimates its income tax for the current year at $120,000. The trial balance shows a $5,000 CREDIT balance on the current tax account (last year's liability was settled for less than provided). The deferred tax liability must fall from $48,000 to $41,000. What is the income tax expense in profit or loss?",
    options: ["$120,000", "$113,000", "$115,000", "$108,000"],
    correct: 3,
    explanation:
      "Expense = current estimate $120,000 − prior-year OVER-provision $5,000 − decrease in deferred tax $7,000 = $108,000 (IAS 12). $120,000 ignores both adjustments, $113,000 misses the over-provision, and $115,000 misses the deferred tax release. Adding both instead of deducting (treating them as an under-provision and an increase) would give $132,000.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-D-06",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Elsmore Co estimates income tax on this year's profits at $90,000. The deferred tax liability must rise from $22,000 to $30,000, and last year's tax was settled for exactly the amount provided. What CURRENT liability for income tax appears in the statement of financial position?",
    options: ["$90,000", "$98,000", "$120,000", "$8,000"],
    correct: 0,
    explanation:
      "The current tax liability is simply the year-end estimate of $90,000; deferred tax is presented separately as a NON-current liability. $98,000 is the P/L tax EXPENSE (90 + 8), a figure often put on the SFP by mistake; $120,000 adds the whole deferred balance; $8,000 is only the deferred movement.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR3-D-07",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "During the year Rangemoor Co sold its entire retail division, a separate major line of business. Under IFRS 5, how are the division's results presented in the consolidated statement of profit or loss?",
    options: [
      "Line by line (revenue, cost of sales, etc.) combined with the continuing operations",
      "As a single pre-tax amount, with the related tax included in the group's main tax charge",
      "As a single POST-tax amount comprising the division's post-tax result plus the post-tax gain or loss on disposal, with comparatives re-presented",
      "In other comprehensive income, as the division no longer belongs to the group",
    ],
    correct: 2,
    explanation:
      "IFRS 5 requires one post-tax line on the face for discontinued operations — trading result AND disposal gain/loss, both net of tax — and the prior year is re-presented on the same basis. Combining line by line buries the discontinued results in continuing figures, showing it pre-tax leaves tax in the wrong place, and the results are realised profit, not OCI.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-D-08",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Ashgale Co's discontinued division earned a pre-tax operating profit of $40,000 up to the disposal date and made a loss on disposal of the division of $65,000. Tax of $10,000 is charged on the operating profit and the disposal loss produces a tax saving of $15,000. What single amount is presented for discontinued operations?",
    options: ["Loss of $25,000", "Loss of $20,000", "Loss of $35,000", "Profit of $30,000"],
    correct: 1,
    explanation:
      "The IFRS 5 single line is fully post-tax: ($40,000 − $10,000) + (−$65,000 + $15,000) = $30,000 − $50,000 = a loss of $20,000. A $25,000 loss nets the PRE-tax figures, $35,000 taxes the profit but not the disposal loss, and $30,000 profit omits the disposal loss altogether.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-D-09",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Under IAS 33, which of the following must be presented on the FACE of the statement of profit or loss of a listed company?",
    options: [
      "Dividend per share for the year",
      "Basic EPS only; diluted EPS may be relegated to the notes",
      "EPS calculated on total comprehensive income",
      "Both basic and diluted EPS for profit attributable to the ordinary shareholders of the parent",
    ],
    correct: 3,
    explanation:
      "IAS 33 requires basic AND diluted EPS on the face of the statement, with equal prominence, based on profit attributable to ordinary equity holders. Dividend per share is not an IAS 33 face requirement, diluted EPS cannot be pushed to the notes, and EPS uses profit or loss, not total comprehensive income.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR3-D-10",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Corfield Co had 2,000,000 ordinary shares in issue on 1 January. On 1 July it made a 1-for-4 rights issue at $1.50 when the market price was $2.00 per share. What is the weighted average number of shares for basic EPS?",
    options: ["2,302,632", "2,250,000", "2,500,000", "2,368,421"],
    correct: 0,
    explanation:
      "TERP = (4 × $2.00 + $1.50) ÷ 5 = $1.90, so the bonus fraction 2.00/1.90 is applied to the PRE-rights period only: 2,000,000 × 2.00/1.90 × 6/12 + 2,500,000 × 6/12 = 1,052,632 + 1,250,000 = 2,302,632. 2,250,000 time-apportions with no bonus adjustment (treating rights like a full-price issue), 2,500,000 treats all shares as in issue all year (bonus-issue logic), and 2,368,421 applies the bonus fraction to the post-rights period as well.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-D-11",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Which of the following items appears in the statement of changes in equity but does NOT appear anywhere in the statement of profit or loss and other comprehensive income?",
    options: [
      "A gain on revaluation of property",
      "Profit for the year",
      "Dividends paid to ordinary shareholders",
      "Finance costs on loan notes",
    ],
    correct: 2,
    explanation:
      "Dividends are transactions with owners, so they appear ONLY in the SOCE. The revaluation gain is the trap: it appears in BOTH (in OCI, then carried into the SOCE reserve columns). Profit for the year likewise appears in both statements, and finance costs appear only in profit or loss.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR3-D-12",
    paper: "FR",
    area: "D",
    type: "number",
    stem: "Marwick Co ($'000): total equity at 1 January 2,400; profit for the year 310; gain on property revaluation 90; issue of 200,000 $1 shares at $1.60 each; dividends paid 120. Per the statement of changes in equity, what is total equity at 31 December, in $'000?",
    numericAnswer: 3000,
    unit: "$'000",
    tolerance: 0,
    explanation:
      "Closing equity = 2,400 + 310 (profit) + 90 (OCI) + 320 (share issue at FULL price: 200 nominal + 120 premium) − 120 (dividends) = $3,000,000. Recording the share issue at nominal value only (200) gives 2,880, and omitting the revaluation gain gives 2,910 — the two most common slips.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-D-13",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Under IAS 7, which of the following statements about the classification of interest and dividends in a (non-financial) company's statement of cash flows is correct?",
    options: [
      "Dividends paid must always be classified as operating activities",
      "Interest paid may be classified as either operating or financing activities, applied consistently from period to period",
      "Dividends received must always be classified as financing activities",
      "Interest received must always be classified as financing activities",
    ],
    correct: 1,
    explanation:
      "IAS 7 permits a CHOICE for interest and dividends (interest paid: operating or financing; dividends paid: financing or operating; interest/dividends received: operating or investing) provided it is applied consistently. The 'must always' options each impose a rule IAS 7 does not contain — and dividends received could never be financing, nor interest received.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-D-14",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "During the year Delverton Co acquired plant costing $500,000, paying $150,000 in cash with the balance financed by a lease. How is the acquisition reflected in the statement of cash flows?",
    options: [
      "Investing outflow of $500,000 and a financing inflow of $350,000",
      "Investing outflow of $500,000 only",
      "No amounts until the lease liability is fully repaid",
      "Investing outflow of $150,000; the $350,000 is a non-cash transaction (disclosed), with future lease payments split between financing (principal) and interest as paid",
    ],
    correct: 3,
    explanation:
      "IAS 7 reports only CASH flows: the $150,000 paid is investing, and the leased element is a non-cash transaction requiring disclosure, entering the statement only as the lease payments are made. Grossing up to $500,000 with a notional financing inflow (or showing $500,000 alone) invents cash that never moved.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-D-15",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Extracts from Norbray Co ($'000): PPE carrying amount b/f 1,800 and c/f 2,300; depreciation for the year 240; plant with a carrying amount of 60 was sold; property was revalued upwards by 100 during the year. All additions were bought for cash. What cash was paid to acquire PPE, in $'000?",
    options: ["500", "800", "700", "640"],
    correct: 2,
    explanation:
      "Reconstruct the PPE account: additions = 2,300 (c/f) − 1,800 (b/f) + 240 (depreciation) + 60 (disposal CA) − 100 (revaluation gain, a non-cash increase) = 700. 500 is the raw movement in carrying amount, 800 forgets to strip out the revaluation, and 640 omits the disposal.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-D-16",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Sallowfen Co ($'000): retained earnings b/f 950 and c/f 1,060; profit for the year 260; a transfer of 10 was made FROM the revaluation surplus TO retained earnings for excess depreciation. What dividends were paid during the year, in $'000?",
    options: ["160", "150", "170", "110"],
    correct: 0,
    explanation:
      "Retained earnings: 950 + 260 (profit) + 10 (transfer IN from revaluation surplus) − dividends = 1,060, so dividends = 160. 150 ignores the reserves transfer, 170 deducts the transfer instead of adding it, and 110 treats the raw movement in retained earnings as the dividend.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-D-17",
    paper: "FR",
    area: "D",
    type: "number",
    stem: "Extracts from Quillmarsh Co ($'000): current tax liability b/f 85 and c/f 95; deferred tax liability b/f 60 and c/f 68; income tax expense in profit or loss 150. What amount of tax was PAID during the year, in $'000?",
    numericAnswer: 132,
    unit: "$'000",
    tolerance: 0,
    explanation:
      "Tax paid = opening liabilities (85 + 60) + expense 150 − closing liabilities (95 + 68) = 132. Using only the current tax column gives 140, and reporting the P/L expense of 150 as the cash paid ignores the liability movements entirely — both frequent cash-flow errors.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-D-18",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Wexcombe Co ($'000): share capital b/f 500 and c/f 700; share premium b/f 220 and c/f 300. During the year it made a 1-for-10 bonus issue (capitalised from RETAINED earnings) followed by an issue of shares for cash. What cash was raised from the share issue, in $'000?",
    options: ["280", "230", "150", "200"],
    correct: 1,
    explanation:
      "The bonus issue added 50 to share capital (1/10 × 500) with NO cash. Cash issue: nominal 200 − 50 = 150, plus the full premium movement of 80 = 230. 280 treats the whole movement in capital plus premium as cash (ignoring the bonus), 150 forgets the premium, and 200 is just the share capital movement.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-D-19",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "Which of the following is reported under INVESTING activities in the statement of cash flows?",
    options: [
      "Repayment of the principal element of lease liabilities",
      "Interest paid on a loan taken out to buy plant",
      "Proceeds from an issue of ordinary shares",
      "Cash paid for development expenditure capitalised as an intangible asset",
    ],
    correct: 3,
    explanation:
      "Cash spent on a capitalised intangible is the acquisition of a long-term asset — investing (IAS 7). Lease principal repayments and share issues are FINANCING, and interest is operating or financing regardless of what the loan financed — the purpose of the borrowing does not drag interest into investing.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR3-D-20",
    paper: "FR",
    area: "D",
    type: "mcq",
    stem: "At the start of the year Lindop Co revalued a property with a carrying amount of $600,000 to $750,000; the remaining useful life is 25 years. Company policy is to make the annual reserves transfer permitted by IAS 16. What amount is transferred from the revaluation surplus to retained earnings for the year?",
    options: ["$6,000", "$30,000", "$24,000", "$150,000"],
    correct: 0,
    explanation:
      "The transfer is the EXCESS depreciation: charge on the revalued amount ($750,000 ÷ 25 = $30,000) less the historical-cost charge ($600,000 ÷ 25 = $24,000) = $6,000 per year. $30,000 transfers the whole new depreciation charge, $24,000 transfers the historical charge, and $150,000 releases the entire surplus immediately instead of over the asset's life.",
    marks: 2,
    difficulty: "medium",
  },

  /* ───────────── Area E — consolidated financial statements (25) ───────────── */
  {
    id: "FR3-E-01",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "On 1 January 20X5 Panrith Co acquired 80% of Selcombe Co, paying $500,000 cash immediately plus $363,000 payable on 1 January 20X7. Panrith's cost of capital is 10%. NCI is measured at its proportionate share of net assets; the fair value of Selcombe's identifiable net assets was $600,000. What is goodwill?",
    options: ["$383,000", "$320,000", "$200,000", "$350,000"],
    correct: 1,
    explanation:
      "Deferred consideration is discounted: $363,000 ÷ 1.10² = $300,000. Goodwill = ($500,000 + $300,000) + NCI (20% × $600,000 = $120,000) − $600,000 = $320,000. $383,000 uses the UNDISCOUNTED $363,000, $200,000 omits the NCI, and $350,000 discounts for only one year ($330,000).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-E-02",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Pilgrove Co acquired 75% of Stanwix Co for $900,000 cash plus a further $400,000 payable only if Stanwix hits a profit target in two years. The fair value of this contingent consideration at acquisition was $250,000. NCI is measured at its fair value of $310,000. Stanwix's identifiable net assets had a fair value of $1,100,000. What is goodwill?",
    options: ["$510,000", "$110,000", "$360,000", "$325,000"],
    correct: 2,
    explanation:
      "IFRS 3 includes contingent consideration at its acquisition-date FAIR VALUE, whether or not payment is probable: ($900,000 + $250,000) + $310,000 − $1,100,000 = $360,000. $510,000 uses the full potential $400,000, $110,000 leaves the contingent element out altogether, and $325,000 wrongly switches to proportionate NCI (25% × $1,100,000 = $275,000).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-E-03",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "A year after acquiring a subsidiary, Pilgrove Co's contingent consideration liability rises in fair value from $250,000 to $290,000 because the subsidiary's profit forecasts have improved (not because of new information about facts existing at the acquisition date). How is the $40,000 increase treated?",
    options: [
      "Charged as an expense in consolidated profit or loss",
      "Added to goodwill",
      "Debited directly to consolidated retained earnings",
      "Recognised in other comprehensive income",
    ],
    correct: 0,
    explanation:
      "Post-acquisition changes in the fair value of contingent consideration classified as a liability go to PROFIT OR LOSS. Only measurement-period adjustments reflecting acquisition-date facts adjust goodwill — the classic confusion. Equity and OCI have no role here.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-E-04",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Prydell Co pays $480,000 for 100% of Sorby Co, whose identifiable net assets have a fair value of $530,000. After reassessing the identification and measurement of the net assets, the figures are confirmed. How is the $50,000 difference treated in the consolidated financial statements?",
    options: [
      "Carried as negative goodwill in the statement of financial position and amortised",
      "Credited to a capital reserve within equity",
      "Deducted from the carrying amount of Sorby's non-current assets",
      "Recognised immediately as a gain in consolidated profit or loss",
    ],
    correct: 3,
    explanation:
      "This is a bargain purchase: after the mandatory reassessment, IFRS 3 requires the excess to be recognised at once as a GAIN in profit or loss. 'Negative goodwill' on the SFP is the pre-IFRS 3 treatment students still reach for; it is not parked in equity or netted against the assets acquired.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR3-E-05",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "On 1 January 20X5 Parlane Co recognised deferred consideration for a subsidiary at its present value of $400,000 ($484,000 payable on 31 December 20X6, discounted at 10%). What finance cost does this create in the consolidated statement of profit or loss for the year ended 31 December 20X5?",
    options: ["$48,400", "$40,000", "$42,000", "$Nil"],
    correct: 1,
    explanation:
      "The discount unwinds at 10% on the carrying amount: 10% × $400,000 = $40,000 finance cost, taking the liability to $440,000. $48,400 applies 10% to the FACE amount of $484,000, $42,000 spreads the total $84,000 straight-line over two years, and nil treats the liability as fixed at its initial value with no unwinding.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-E-06",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Prento Co acquired 60% of Silsden Co on 1 May 20X5; both have 31 December year ends. Cost of sales for 20X5 (accruing evenly): Prento $1,500,000; Silsden $720,000. Since acquisition, Silsden sold goods to Prento for $100,000 at a mark-up of 25% on cost; goods invoiced at $40,000 remained in Prento's inventory at the year end. What is consolidated cost of sales?",
    options: ["$1,880,000", "$1,988,000", "$1,888,000", "$2,128,000"],
    correct: 2,
    explanation:
      "Consolidate Silsden for 8 months only: $1,500,000 + ($720,000 × 8/12) − $100,000 intra-group + PURP $8,000 ($40,000 × 25/125) = $1,888,000. $1,880,000 forgets the PURP, $1,988,000 forgets the intra-group elimination, and $2,128,000 consolidates Silsden's full-year cost of sales despite the mid-year acquisition.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-E-07",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Pexley Co acquired 70% of Swinford Co on 1 September 20X5 for $980,000, measuring NCI at its fair value of $400,000. Swinford: share capital $500,000; retained earnings at 1 January 20X5 $340,000; profit for the year ended 31 December 20X5 $120,000, accruing evenly. What is goodwill?",
    options: ["$460,000", "$540,000", "$420,000", "$60,000"],
    correct: 0,
    explanation:
      "Net assets AT ACQUISITION = $500,000 + $340,000 + (8/12 × $120,000 = $80,000) = $920,000; goodwill = $980,000 + $400,000 − $920,000 = $460,000. $540,000 uses opening retained earnings with no profit to 1 September, $420,000 uses the full year's profit, and $60,000 omits the NCI.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-E-08",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "At 31 December, Pember Co shows a receivable of $86,000 due from its subsidiary Salton Co, while Salton shows a payable of only $70,000. The difference is a cheque for $16,000 that Salton posted on 30 December, banked by Pember in January. What consolidation adjustment is required?",
    options: [
      "Cancel $70,000 from both receivables and payables and leave $16,000 within group receivables",
      "Cancel $86,000 from both receivables and payables",
      "No adjustment, because the two balances will agree once the cheque clears",
      "Record cash in transit of $16,000, reduce the receivable to $70,000, then cancel $70,000 against $70,000",
    ],
    correct: 3,
    explanation:
      "In-transit items are adjusted to their DESTINATION first: Dr cash $16,000, Cr group receivables $16,000, after which the intra-group balances agree at $70,000 and cancel in full. Leaving $16,000 in receivables overstates group receivables and understates cash; cancelling $86,000 from both sides forces payables below what Salton owes; and no group balances with itself may remain, so 'no adjustment' fails.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-E-09",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Pargate Co sells goods to its 80%-owned subsidiary Skell Co at cost plus 20%. At the year end Pargate's receivable from Skell is $95,000 but Skell's payable is $80,000; the difference is goods in transit invoiced at $15,000. Skell's inventory also includes $36,000 (at invoice value) bought from Pargate. What TOTAL unrealised profit is eliminated on consolidation?",
    options: ["$6,000", "$8,500", "$10,200", "$2,500"],
    correct: 1,
    explanation:
      "The in-transit goods are brought into group inventory, so PURP is computed on $36,000 + $15,000 = $51,000 at invoice value: $51,000 × 20/120 = $8,500. $6,000 takes closing inventory only and misses the goods in transit, $10,200 applies 20% to the invoice price (margin/mark-up mix-up), and $2,500 adjusts the transit goods only.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-E-10",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Pelmar Co sells goods to its subsidiary at a margin of 25% ON SELLING PRICE. Goods purchased from Pelmar held in the subsidiary's inventory were $48,000 at 1 January and $64,000 at 31 December. What is the net effect of the unrealised profit adjustments on consolidated GROSS PROFIT for the year?",
    options: ["Decrease of $16,000", "Decrease of $28,000", "Decrease of $4,000", "Increase of $4,000"],
    correct: 2,
    explanation:
      "Opening PURP ($48,000 × 25% = $12,000) is realised this year and RELEASES to profit; closing PURP ($64,000 × 25% = $16,000) is deducted. Net effect = −16,000 + 12,000 = a $4,000 decrease. Taking the closing PURP only gives $16,000, ADDING both gives $28,000, and reversing the two signs turns the answer into a $4,000 increase.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-E-11",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "On 1 January 20X5 Pindar Co sold plant with a carrying amount of $72,000 to its wholly-owned subsidiary for $90,000. The plant had a remaining life of six years (straight line, nil residual). By what net amount are consolidated profit and PPE reduced at 31 December 20X5?",
    options: ["$15,000", "$18,000", "$12,000", "$3,000"],
    correct: 0,
    explanation:
      "Eliminate the $18,000 unrealised gain, then add back the excess depreciation the buyer charged on the inflated price: ($90,000 − $72,000) ÷ 6 = $3,000. Net adjustment $15,000. $18,000 ignores the depreciation unwind, $12,000 unwinds two years of excess depreciation after only one, and $3,000 adjusts the depreciation but leaves the gain in profit.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-E-12",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "On 1 July 20X5 Stiverton Co, a 75%-owned subsidiary, sold a machine to its parent at a profit of $24,000; the machine's remaining life was four years (straight line). The group's year end is 31 December 20X5. By how much does the PPE transfer reduce the profit attributable to the NCI for the year?",
    options: ["$6,000", "$4,500", "$Nil, because the adjustment is made against the parent's profit", "$5,250"],
    correct: 3,
    explanation:
      "The SELLER is the subsidiary, so the adjustment hits its profit: gain $24,000 less excess depreciation unwound for six months ($24,000 ÷ 4 × 6/12 = $3,000) = $21,000; NCI share 25% × $21,000 = $5,250. $6,000 ignores the depreciation unwind, $4,500 unwinds a full year despite the July transfer, and nil misattributes the adjustment to the parent (the buyer).",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-E-13",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Pavey Co acquires 80% of Sunder Co. The fair value of Sunder's identifiable net assets is $750,000 and the fair value of the NCI at acquisition is $170,000. How much HIGHER is goodwill if the NCI is measured at fair value rather than at its proportionate share of net assets?",
    options: ["$Nil — goodwill is identical under both methods", "$20,000", "$150,000", "$170,000"],
    correct: 1,
    explanation:
      "Proportionate NCI = 20% × $750,000 = $150,000. Consideration and net assets are unchanged, so goodwill differs only by the NCI figure: $170,000 − $150,000 = $20,000 — the NCI's share of goodwill recognised under the fair-value method. 'Identical' describes only the parent's share of goodwill; $150,000 and $170,000 are the NCI amounts themselves, not the difference.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-E-14",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Porthaven Co owns 75% of Seabrook Co, with NCI measured at its acquisition-date fair value of $260,000. Since acquisition, Seabrook's retained profits have grown by $200,000, cumulative extra depreciation on fair-value uplifts is $40,000, and $20,000 of profit on goods Seabrook sold to Porthaven remains in inventory. What is the NCI at the reporting date?",
    options: ["$310,000", "$305,000", "$295,000", "$300,000"],
    correct: 2,
    explanation:
      "NCI = $260,000 + 25% × adjusted post-acquisition profits ($200,000 − $40,000 FV depreciation − $20,000 upstream PURP = $140,000) = $295,000. $310,000 uses unadjusted profits, $305,000 misses the fair-value depreciation, and $300,000 misses the PURP (which belongs against the subsidiary as seller).",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-E-15",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Petherton Co (retained earnings $1,500,000) owns 70% of Saxmead Co (retained earnings now $700,000; at acquisition $400,000). Cumulative extra depreciation on fair-value adjustments is $60,000; $14,000 of profit on goods Petherton sold to Saxmead is in closing inventory; goodwill impairment to date is $30,000 (NCI at proportionate share). What are consolidated retained earnings, in $'000?",
    options: ["1,624", "1,638", "1,666", "1,633"],
    correct: 0,
    explanation:
      "Group RE = 1,500 + 70% × (700 − 400 − 60) − 14 (parent is the seller) − 30 (with proportionate NCI, ALL impairment hits the parent) = 1,500 + 168 − 44 = 1,624. 1,638 forgets the PURP, 1,666 misses the fair-value depreciation, and 1,633 charges only 70% of the impairment as if NCI were at fair value.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-E-16",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Ashworth Co owns 30% of its associate Brindle Co. During the year Ashworth sold goods to Brindle earning a profit of $15,000; ALL of these goods remain in Brindle's inventory at the year end. What unrealised profit is eliminated in the consolidated financial statements?",
    options: ["$Nil — an associate is outside the group, so no elimination is made", "$15,000", "$10,500", "$4,500"],
    correct: 3,
    explanation:
      "For transactions with an associate, only the INVESTOR'S SHARE of the unrealised profit is eliminated: 30% × $15,000 = $4,500. Eliminating $15,000 applies the full subsidiary-style adjustment, $10,500 removes the other shareholders' 70% instead of the investor's 30%, and nil ignores IAS 28's requirement despite the associate being outside the group.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-E-17",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Pentle Co owns 25% of its associate Arkley Co, whose profit for the year is $180,000. During the year Arkley sold goods to Pentle, and $24,000 of profit on those goods remains unrealised in Pentle's closing inventory. What 'share of profit of associate' does the group recognise?",
    options: ["$45,000", "$39,000", "$21,000", "$43,500"],
    correct: 1,
    explanation:
      "Adjust the associate's profit for the FULL upstream PURP first, then take the group's share: 25% × ($180,000 − $24,000) = $39,000. $45,000 ignores the PURP, $21,000 deducts the whole $24,000 from the 25% share (double-counting), and $43,500 strips out only 25% of the PURP before applying 25% again.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-E-18",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "At the year end Paxford Co has a trade receivable of $50,000 due from its associate. In the consolidated statement of financial position, this balance is:",
    options: [
      "Eliminated in full against the associate's payable",
      "Eliminated to the extent of the group's percentage holding",
      "Retained in full within consolidated trade receivables",
      "Reclassified as part of the investment in associate",
    ],
    correct: 2,
    explanation:
      "An associate is NOT part of the group, so balances with it are genuine third-party assets and are not eliminated — the receivable stays at $50,000. Full or proportionate elimination applies subsidiary logic to an equity-accounted investee, and trading balances are not folded into the investment carrying amount.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR3-E-19",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "In a consolidated statement of cash flows, a dividend paid by a partly-owned subsidiary to its non-controlling shareholders is:",
    options: [
      "Presented as a cash outflow, normally under financing activities",
      "Eliminated in full as an intra-group transaction",
      "Presented as an investing outflow, as it relates to the subsidiary investment",
      "Excluded, because it was paid by the subsidiary rather than the parent",
    ],
    correct: 0,
    explanation:
      "Cash leaving the group to OUTSIDE equity holders is a real group cash flow, normally shown under financing. Treating it as intra-group is the classic trap — only the dividend to the PARENT cancels. It is a distribution to owners, not investing, and 'paid by the subsidiary' does not stop it leaving the group.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR3-E-20",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Extracts from Pelworth group ($'000): non-controlling interests b/f 420 and c/f 465; total comprehensive income attributable to the NCI for the year 85. There were no changes in group structure or ownership percentages. What dividend was paid to the NCI during the year, in $'000?",
    options: ["45", "85", "130", "40"],
    correct: 3,
    explanation:
      "Reconstruct the NCI column: 420 + 85 (TCI) − dividend = 465, so the dividend to NCI = 40 — the figure that flows into the consolidated statement of cash flows. 45 is the raw movement in the NCI balance, 85 mistakes the TCI allocation for the dividend, and 130 adds the closing balance movement and TCI instead of balancing the column.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-E-21",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Prescombe Co sold its entire 80% holding in Sellick Co for $900,000. At the disposal date the consolidated financial statements included: Sellick's net assets $800,000; unimpaired goodwill $120,000; NCI $180,000. What gain or loss on disposal is reported in the CONSOLIDATED statement of profit or loss?",
    options: ["Loss of $20,000", "Gain of $160,000", "Gain of $280,000", "Gain of $140,000"],
    correct: 1,
    explanation:
      "Group gain = proceeds $900,000 + NCI derecognised $180,000 − (net assets $800,000 + goodwill $120,000) = $160,000. The $20,000 loss forgets to add back the NCI, $280,000 forgets to derecognise goodwill, and $140,000 compares proceeds with only 80% of the net assets while the consolidation carries 100%.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-E-22",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "On 30 September 20X5 Parbeck Co sold its entire holding in a subsidiary that was a separate major line of business; the group's year end is 31 December 20X5. How is the subsidiary reflected in the consolidated financial statements for 20X5?",
    options: [
      "Its full-year results are consolidated because it was a subsidiary at the start of the year",
      "It is excluded from the consolidated statements for the whole year",
      "Its results are consolidated up to 30 September and presented as a discontinued operation, together with the group gain or loss on disposal",
      "It is equity-accounted for the nine months to the disposal date",
    ],
    correct: 2,
    explanation:
      "Control determines consolidation: the subsidiary is consolidated UNTIL the date control is lost, and because it was a separate major line of business its results plus the disposal gain appear as a discontinued operation (IFRS 5 / IFRS 10). Full-year or zero consolidation ignores the disposal date, and equity accounting applies to associates, not controlled periods.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-E-23",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Which of the following movements would appear in the non-controlling interests column of a consolidated statement of changes in equity?",
    options: [
      "The NCI's share of total comprehensive income and dividends paid to the NCI",
      "Dividends paid to the parent's own shareholders",
      "Proceeds of a share issue made by the parent",
      "Goodwill impairment where the NCI is measured at its proportionate share of net assets",
    ],
    correct: 0,
    explanation:
      "The NCI column rolls forward with its share of TCI less dividends paid to NCI shareholders. Parent dividends and parent share issues belong in the columns attributable to the owners of the parent, and with PROPORTIONATE NCI, goodwill impairment is charged wholly against the parent, never the NCI column.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-E-24",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "During the year Palgrave Co paid $500,000 in cash to acquire 100% of a subsidiary whose assets at acquisition included cash of $80,000. In the consolidated statement of cash flows, the acquisition appears under investing activities as:",
    options: [
      "An outflow of $80,000",
      "An outflow of $500,000",
      "An outflow of $580,000",
      "An outflow of $420,000",
    ],
    correct: 3,
    explanation:
      "IAS 7 presents the acquisition NET of the cash acquired with the subsidiary: $500,000 − $80,000 = $420,000, because the group 'paid out' only the net cash. $500,000 shows the gross price, $580,000 wrongly ADDS the acquired cash, and $80,000 reports the acquired balance instead of the net payment.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR3-E-25",
    paper: "FR",
    area: "E",
    type: "mcq",
    stem: "Pinner Co acquired 90% of Solva Co, paying cash of $850,000 and incurring legal and due-diligence fees of $40,000. The fair value of Solva's identifiable net assets was $700,000 and NCI is measured at its proportionate share. What is goodwill?",
    options: ["$260,000", "$220,000", "$150,000", "$180,000"],
    correct: 1,
    explanation:
      "IFRS 3 EXPENSES acquisition-related costs, so consideration is $850,000 only: goodwill = $850,000 + NCI (10% × $700,000 = $70,000) − $700,000 = $220,000. $260,000 capitalises the fees into goodwill, $150,000 omits the NCI, and $180,000 nets the fees against the consideration instead of expensing them.",
    marks: 2,
    difficulty: "medium",
  },
]
