import type { AccaQuestion } from "@/lib/acca-content"

/* FA bank wave 7 — +70 to 150 (2026-07-11). */

export const FA_WAVE3: AccaQuestion[] = [
  /* ───────────── Area A — Context & purpose of financial reporting ───────────── */
  {
    id: "FA3-A-01",
    paper: "FA",
    area: "A",
    type: "mcq",
    stem: "Which user group of financial statements is MOST directly interested in an entity's ability to generate cash to repay borrowings and pay interest as it falls due?",
    options: ["Employees", "Lenders", "Customers", "The government"],
    correct: 1,
    explanation:
      "Lenders assess whether their principal and interest will be repaid, so cash-generating ability is their primary concern. Employees focus on job security and pay, customers on continuity of supply, and the government on tax and statistics — real interests, but not the one described.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA3-A-02",
    paper: "FA",
    area: "A",
    type: "mcq",
    stem: "The statement of cash flows is primarily designed to show:",
    options: [
      "The entity's profit or loss measured on the accruals basis",
      "The entity's financial position at a single point in time",
      "How the entity generated and used cash during the period",
      "The movements on each component of equity during the period",
    ],
    correct: 2,
    explanation:
      "The statement of cash flows reports cash generated and consumed, classified into operating, investing and financing activities. Accruals-based performance is the statement of profit or loss, position at a date is the statement of financial position, and equity movements belong to the statement of changes in equity.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA3-A-03",
    paper: "FA",
    area: "A",
    type: "mcq",
    stem: "At 1 May, Bramble Crafts has assets of $64,000 and liabilities of $21,500. During May the business makes a profit of $6,200 and the owner takes drawings of $2,700. There are no other capital transactions. What is capital at 31 May?",
    options: ["$42,500", "$46,000", "$51,400", "$39,000"],
    correct: 1,
    explanation:
      "Opening capital = 64,000 − 21,500 = 42,500; closing capital = 42,500 + 6,200 profit − 2,700 drawings = $46,000. $51,400 adds the drawings instead of deducting them, $39,000 reverses both adjustments, and $42,500 ignores the month's movements altogether.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-A-04",
    paper: "FA",
    area: "A",
    type: "mcq",
    stem: "In a limited liability company, who is PRIMARILY responsible for preparing the financial statements?",
    options: [
      "The external auditor",
      "The shareholders in general meeting",
      "The board of directors",
      "The financial reporting regulator",
    ],
    correct: 2,
    explanation:
      "Preparing the financial statements is a duty of the directors as part of their stewardship of the company. The auditor only expresses an opinion on statements the directors have prepared, shareholders receive and vote on them, and the regulator sets the rules rather than preparing anything.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-A-05",
    paper: "FA",
    area: "A",
    type: "mcq",
    stem: "Which of the following BEST matches the Conceptual Framework's definition of a liability?",
    options: [
      "A present obligation of the entity to transfer an economic resource as a result of past events",
      "A possible commitment the entity expects to enter into during the next financial year",
      "Any amount that is payable more than 12 months after the reporting date",
      "A resource controlled by the entity as a result of past events",
    ],
    correct: 0,
    explanation:
      "A liability needs a PRESENT obligation arising from PAST events to transfer an economic resource. A future intention has no past event, the 12-month test is about current/non-current CLASSIFICATION rather than definition, and 'a resource controlled by the entity' is the definition of an asset.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-A-06",
    paper: "FA",
    area: "A",
    type: "mcq",
    stem: "Which of the following is a characteristic of a sole trader business?",
    options: [
      "It is a legal entity separate from its owner",
      "It must publish its financial statements",
      "It is owned by shareholders",
      "Its owner is personally liable for all the business's debts",
    ],
    correct: 3,
    explanation:
      "A sole trader and the business are legally the same person, so the owner has unlimited personal liability. Separate legal personality, publication requirements and share ownership are all features of a limited company, not a sole trader.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA3-A-07",
    paper: "FA",
    area: "A",
    type: "mcq",
    stem: "Marlin Traders repays a $5,000 bank loan in full, together with $150 of interest that had already been recognised as an accrued liability. What is the effect on the accounting equation?",
    options: [
      "Assets decrease $5,000; liabilities decrease $5,000; capital decreases $150",
      "Assets decrease $5,150; liabilities decrease $5,000; capital decreases $150",
      "Assets and capital each decrease $5,150",
      "Assets decrease $5,150; liabilities decrease $5,150; capital is unchanged",
    ],
    correct: 3,
    explanation:
      "Bank falls by $5,150 and BOTH liabilities — the loan and the interest accrual — are settled, so liabilities also fall by $5,150; capital is untouched. Charging the interest to capital again double-counts an expense already recognised when the accrual was set up, and treating the repayment as a capital movement confuses a loan with owner's funds.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-A-08",
    paper: "FA",
    area: "A",
    type: "mcq",
    stem: "Which of the following BEST describes why the separation of ownership from control in a company creates the need for financial reporting?",
    options: [
      "Shareholders need information to assess how well the directors have managed the resources entrusted to them",
      "The directors need the financial statements in order to make day-to-day operating decisions",
      "Publishing financial statements eliminates the risk that directors act in their own interests",
      "Without financial statements a company would be unable to calculate its tax liability",
    ],
    correct: 0,
    explanation:
      "Because shareholders (owners) are not the managers, they rely on financial statements to judge the directors' stewardship. Directors already have internal management information, reporting reduces but cannot ELIMINATE self-interested behaviour, and tax computation is a by-product, not the underlying reason.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FA3-A-09",
    paper: "FA",
    area: "A",
    type: "mcq",
    stem: "Which of the following is NOT one of the elements of financial statements defined in the Conceptual Framework?",
    options: ["Equity", "Expenses", "Profit", "Liabilities"],
    correct: 2,
    explanation:
      "The five elements are assets, liabilities, equity, income and expenses. Profit is not an element — it is a TOTAL calculated as income less expenses, which is exactly why it appears among the distractors.",
    marks: 2,
    difficulty: "easy",
  },

  /* ───────────── Area B — Qualitative characteristics ───────────── */
  {
    id: "FA3-B-01",
    paper: "FA",
    area: "B",
    type: "mcq",
    stem: "Financial information is RELEVANT when:",
    options: [
      "It is free from all estimation uncertainty",
      "It is presented using the same accounting policies every year",
      "It has predictive value, confirmatory value, or both",
      "It has been verified by an external auditor",
    ],
    correct: 2,
    explanation:
      "Relevance means the information can make a difference to decisions — through predictive value, confirmatory value, or both. Freedom from error belongs to faithful representation, consistent policies support comparability, and audit verification relates to verifiability.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA3-B-02",
    paper: "FA",
    area: "B",
    type: "mcq",
    stem: "Reporting transactions in accordance with their economic substance rather than merely their legal form supports which qualitative characteristic?",
    options: ["Timeliness", "Understandability", "Comparability", "Faithful representation"],
    correct: 3,
    explanation:
      "A faithful representation depicts the SUBSTANCE of an economic phenomenon; reporting legal form alone when it differs from substance would not faithfully represent the transaction. Timeliness, understandability and comparability are enhancing characteristics with different meanings.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA3-B-03",
    paper: "FA",
    area: "B",
    type: "mcq",
    stem: "Grebe Ltd 'sells' a machine to a bank for $80,000 and is committed to repurchase it in two years' time for $80,000 plus amounts equivalent to interest. The machine never leaves Grebe's premises and Grebe continues to use it. To report the substance of this arrangement, Grebe should account for it as:",
    options: [
      "A sale, with any profit recognised immediately",
      "A secured loan of $80,000",
      "Revenue of $80,000 spread evenly over the two years",
      "A contingent liability disclosed in the notes only",
    ],
    correct: 1,
    explanation:
      "Grebe keeps the risks and rewards of the machine and pays what is effectively interest, so in substance this is borrowing secured on the asset. Recording a sale follows the legal form, spreading 'revenue' invents income that was never earned, and a firm repurchase commitment is an actual liability, not a contingent one.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-B-04",
    paper: "FA",
    area: "B",
    type: "mcq",
    stem: "Which statement about UNDERSTANDABILITY is correct?",
    options: [
      "Information should be classified, characterised and presented clearly, assuming users have a reasonable knowledge of business",
      "Complex items may be omitted if doing so makes the statements easier to read",
      "Every user, however inexperienced, must be able to understand each item in the financial statements",
      "Understandability is one of the two fundamental qualitative characteristics",
    ],
    correct: 0,
    explanation:
      "Understandability means clear classification and presentation for users with reasonable business knowledge who review information diligently. Omitting complex but relevant items would make statements incomplete and misleading, the Framework does not cater to every inexperienced user, and understandability is an ENHANCING characteristic, not a fundamental one.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA3-B-05",
    paper: "FA",
    area: "B",
    type: "mcq",
    stem: "Which statement about COMPARABILITY is correct?",
    options: [
      "Comparability means all entities must adopt identical accounting policies",
      "Consistent use of the same methods from period to period helps to achieve comparability",
      "Comparability requires reported figures to contain no estimates",
      "Comparability is one of the two fundamental qualitative characteristics",
    ],
    correct: 1,
    explanation:
      "Consistency (same methods, period to period) is a means of achieving comparability. Comparability is not UNIFORMITY — unlike things should not be forced to look alike; estimates are entirely compatible with comparable information; and comparability is an enhancing characteristic, not a fundamental one.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-B-06",
    paper: "FA",
    area: "B",
    type: "mcq",
    stem: "The directors of Osprey Ltd, wanting to smooth reported profits, deliberately overstate a provision in a successful year, planning to release it in a poorer year. Which quality of useful information is MOST directly violated?",
    options: ["Timeliness", "Verifiability", "Neutrality", "Understandability"],
    correct: 2,
    explanation:
      "Deliberately biasing figures to manipulate the profit trend breaches neutrality — depiction without bias — which is a component of faithful representation. The information may still be timely, capable of verification and understandable; the defect is the bias itself.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-B-07",
    paper: "FA",
    area: "B",
    type: "mcq",
    stem: "An item of information can be MATERIAL because of:",
    options: [
      "Its size relative to profit only",
      "Its nature only",
      "The preferences of individual users only",
      "Either its size or its nature, or both",
    ],
    correct: 3,
    explanation:
      "Materiality depends on the size AND/OR the nature of an item — a small illegal payment can be material despite its size, and a large routine balance is material by magnitude. Restricting the test to size alone or nature alone is incomplete, and materiality is judged by reference to users' decisions generally, not one user's preference.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA3-B-08",
    paper: "FA",
    area: "B",
    type: "mcq",
    stem: "Brant Ltd faces very high measurement uncertainty in estimating a legal provision, but the case is highly significant to users of its financial statements. According to the Conceptual Framework, Brant should:",
    options: [
      "Recognise nothing and disclose nothing until the uncertainty is resolved",
      "Recognise its best estimate and disclose the estimation uncertainty, because a clearly explained estimate can still be useful",
      "Recognise the maximum possible amount, in order to be prudent",
      "Delay publishing its financial statements until the court case concludes",
    ],
    correct: 1,
    explanation:
      "Measurement uncertainty does not prevent information being useful: a faithfully represented best ESTIMATE, with the uncertainty disclosed, serves users. Omitting the item damages completeness and relevance, recognising the maximum is asymmetric 'conservatism' that breaches neutrality, and delaying publication sacrifices timeliness.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FA3-B-09",
    paper: "FA",
    area: "B",
    type: "mcq",
    stem: "Under the accrual basis of accounting, the effects of transactions are recognised:",
    options: [
      "When they occur, in the periods to which they relate",
      "Only when cash is received or paid",
      "Only at the end of the reporting period",
      "Only once they have been approved by the auditor",
    ],
    correct: 0,
    explanation:
      "Accrual accounting recognises transactions when they occur and matches them to the periods to which they relate, regardless of cash timing. Cash-basis recognition is the opposite of accruals, year-end-only recognition confuses adjustments with the basis itself, and auditors approve nothing — they express an opinion.",
    marks: 2,
    difficulty: "easy",
  },

  /* ───────────── Area C — Double-entry & accounting systems ───────────── */
  {
    id: "FA3-C-01",
    paper: "FA",
    area: "C",
    type: "mcq",
    stem: "Goods previously bought on credit are returned to the supplier. In which book of prime entry is the return FIRST recorded?",
    options: [
      "The sales returns day book",
      "The purchase returns (returns outwards) day book",
      "The journal",
      "The cash book",
    ],
    correct: 1,
    explanation:
      "Returns of goods TO suppliers are listed in the purchase returns (returns outwards) day book. The sales returns day book records goods returned BY customers, the journal is for non-routine entries, and the cash book records only cash and bank transactions.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA3-C-02",
    paper: "FA",
    area: "C",
    type: "mcq",
    stem: "Linnet Studio runs its petty cash on the imprest system with a float of $150. At the month end, vouchers in the box total $118 and cash counted is $32. How much should be drawn from the bank to restore the imprest?",
    options: ["$32", "$150", "$118", "$268"],
    correct: 2,
    explanation:
      "Under the imprest system the top-up always equals the amount SPENT, evidenced by the vouchers: $118 (which restores 32 + 118 = the $150 float). $32 is the cash remaining, $150 would over-fill the box to $182, and $268 wrongly adds the float and the vouchers together.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA3-C-03",
    paper: "FA",
    area: "C",
    type: "mcq",
    stem: "For the month, Curlew Trading's sales day book shows: net sales $9,200, sales tax $1,840, gross total $11,040. Which posting to the general ledger is correct?",
    options: [
      "Dr Receivables control $11,040; Cr Sales $11,040",
      "Dr Receivables control $11,040; Cr Sales $9,200; Cr Sales tax $1,840",
      "Dr Receivables control $9,200; Cr Sales $9,200",
      "Dr Sales $9,200; Dr Sales tax $1,840; Cr Receivables control $11,040",
    ],
    correct: 1,
    explanation:
      "Customers owe the GROSS amount, so receivables control is debited $11,040; sales are credited NET of tax ($9,200) and the tax collected is credited to the sales tax account ($1,840). Crediting sales with the gross figure counts the tax as revenue, posting only the net understates the debt, and the last option reverses the entire entry.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-C-04",
    paper: "FA",
    area: "C",
    type: "mcq",
    stem: "Which of the following transactions would be recorded in the JOURNAL as its book of prime entry?",
    options: [
      "A cash purchase of stationery",
      "A credit sale of goods to a customer",
      "The correction of a posting error between two ledger accounts",
      "The return of goods by a credit customer",
    ],
    correct: 2,
    explanation:
      "The journal captures non-routine items — corrections of errors, year-end adjustments, write-offs. Cash purchases go through the cash book, credit sales through the sales day book, and customer returns through the sales returns day book.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA3-C-05",
    paper: "FA",
    area: "C",
    type: "number",
    stem: "At 1 June, Heron Stores owed the tax authority $2,300 of sales tax. During June it charged output tax of $5,900 on sales, suffered input tax of $3,450 on purchases, and paid $2,300 to the tax authority. How much sales tax is owed at 30 June, in $?",
    numericAnswer: 2450,
    unit: "$",
    explanation:
      "Closing balance = opening 2,300 + output tax 5,900 − input tax 3,450 − payment 2,300 = $2,450 owed. The traps are adding input tax instead of deducting it, or forgetting that the payment cleared the opening balance.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-C-06",
    paper: "FA",
    area: "C",
    type: "mcq",
    stem: "Which statement about the cash book is correct?",
    options: [
      "It is both a book of prime entry and the bank/cash ledger account within the double-entry system",
      "It is a book of prime entry only and sits outside the double-entry system",
      "It records credit sales and credit purchases",
      "It is a memorandum record, like the individual customer accounts in the receivables ledger",
    ],
    correct: 0,
    explanation:
      "The cash book is unusual: it serves as the book of prime entry for cash/bank transactions AND as the ledger account for bank and cash. Treating it as prime entry only or as a memorandum record misses its ledger role, and credit transactions are recorded in the day books, not the cash book.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA3-C-07",
    paper: "FA",
    area: "C",
    type: "mcq",
    stem: "Avocet Interiors, which is registered for sales tax, buys goods for resale on credit at a price of $2,400 plus recoverable sales tax of $480. Which double entry records the purchase?",
    options: [
      "Dr Purchases $2,880; Cr Payables $2,880",
      "Dr Purchases $2,400; Cr Payables $2,400",
      "Dr Purchases $2,880; Cr Payables $2,400; Cr Sales tax $480",
      "Dr Purchases $2,400; Dr Sales tax $480; Cr Payables $2,880",
    ],
    correct: 3,
    explanation:
      "A registered trader records purchases NET (the tax is recoverable, not a cost): Dr Purchases 2,400, Dr Sales tax 480, Cr Payables with the gross 2,880 owed to the supplier. Debiting purchases with the gross treats recoverable tax as a cost, ignoring the tax understates the payable, and the third option puts the tax on the wrong side.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-C-08",
    paper: "FA",
    area: "C",
    type: "mcq",
    stem: "Dunlin Ltd pays a supplier's invoice of $1,000 within the agreed discount period, taking a 2% settlement discount and paying $980. Which entries record the settlement in Dunlin's books?",
    options: [
      "Dr Payables $1,000; Cr Bank $980; Cr Discounts received $20",
      "Dr Payables $980; Cr Bank $980",
      "Dr Payables $1,000; Cr Bank $980; Cr Discounts allowed $20",
      "Dr Bank $980; Dr Discounts received $20; Cr Payables $1,000",
    ],
    correct: 0,
    explanation:
      "The full $1,000 debt is cleared: $980 leaves the bank and the $20 saved is income credited to discounts received. Debiting only $980 leaves a phantom $20 payable, discounts ALLOWED is the account for discounts given to customers, and the final option reverses the whole entry.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-C-09",
    paper: "FA",
    area: "C",
    type: "number",
    stem: "Wren Ltd's purchases day book for the year shows net credit purchases of $14,000 and sales tax of $2,800 (gross $16,800). Payments to credit suppliers were $15,200. Opening trade payables were $4,100 and there were no other transactions. What are closing trade payables, in $?",
    numericAnswer: 5700,
    unit: "$",
    explanation:
      "Suppliers are owed the GROSS amount, so closing payables = 4,100 + 16,800 − 15,200 = $5,700. The classic error is posting the NET $14,000 to the control account (giving $2,900) — but the sales tax on a credit purchase is owed to the supplier until the invoice is paid.",
    marks: 2,
    difficulty: "hard",
  },

  /* ───────────── Area D — Recording transactions & events ───────────── */
  {
    id: "FA3-D-01",
    paper: "FA",
    area: "D",
    type: "number",
    stem: "Plover Ltd bought a machine on 1 January 20X1 for $60,000 and depreciated it straight-line over 10 years with no residual value. On 1 January 20X4, after three years' use, the TOTAL remaining useful life is revised to 4 years. What is the depreciation charge for the year ended 31 December 20X4, in $?",
    numericAnswer: 10500,
    unit: "$",
    explanation:
      "A revised useful life is applied PROSPECTIVELY: carrying amount at 1 January 20X4 = 60,000 − (3 × 6,000) = 42,000, spread over the revised 4 remaining years = $10,500. The traps are restating past charges (changes in estimate are never retrospective) or dividing the original cost, rather than the carrying amount, by the new life.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-D-02",
    paper: "FA",
    area: "D",
    type: "mcq",
    stem: "Which of the following costs should be CAPITALISED as part of the cost of a new machine?",
    options: [
      "Repainting the factory wall behind the machine",
      "Delivery of the machine to the factory and its installation",
      "The first year's routine servicing under a maintenance contract",
      "The operators' wages once the machine enters production",
    ],
    correct: 1,
    explanation:
      "Costs directly attributable to bringing the asset to its location and working condition — delivery and installation — are capital expenditure. Repainting is maintenance of a different asset, and routine servicing and production wages are revenue expenditure of running the machine, not acquiring it.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA3-D-03",
    paper: "FA",
    area: "D",
    type: "mcq",
    stem: "At 1 January, Teasel Traders had an allowance for receivables of $2,000. During the year, debts of $900 were written off as irrecoverable. At 31 December the allowance required is $1,400. What is the TOTAL charge to profit or loss for the year for irrecoverable debts and the allowance?",
    options: ["$300", "$900", "$1,500", "$2,300"],
    correct: 0,
    explanation:
      "Charge = write-offs 900 + movement in allowance (1,400 − 2,000 = a DECREASE of 600) = $300. $900 ignores the allowance movement, $1,500 adds the $600 decrease instead of deducting it, and $2,300 charges the whole closing allowance again on top of the write-offs.",
    marks: 2,
    difficulty: "hard",
  },

  /* ───────────── Area E — Preparing a trial balance ───────────── */
  {
    id: "FA3-E-01",
    paper: "FA",
    area: "E",
    type: "mcq",
    stem: "Lapwing Ltd's receivables control account shows a balance of $34,600. It is then discovered that: (1) the sales day book was undercast by $1,000; (2) a contra of $650 against the payables ledger was never recorded; (3) discounts allowed of $240 were not posted to the control account. What is the corrected control account balance?",
    options: ["$34,710", "$35,190", "$36,490", "$32,710"],
    correct: 0,
    explanation:
      "Corrected balance = 34,600 + 1,000 (extra sales) − 650 (contra) − 240 (discounts allowed) = $34,710. $35,190 adds the discounts instead of deducting them, $36,490 adds all three items, and $32,710 deducts all three including the sales undercast.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-E-02",
    paper: "FA",
    area: "E",
    type: "mcq",
    stem: "The total of Siskin Supplies' receivables ledger list of balances is $27,890. Two errors are then found: a customer's CREDIT balance of $150 was listed as a debit balance, and a debit balance of $720 was omitted from the list entirely. What is the corrected total of the list of balances?",
    options: ["$28,460", "$28,610", "$27,590", "$28,310"],
    correct: 3,
    explanation:
      "A credit balance listed as a debit must be corrected by TWICE the amount (remove the wrong +150 and insert −150): 27,890 − 300 + 720 = $28,310. $28,460 adjusts by only $150, $28,610 fixes only the omission, and $27,590 fixes only the credit balance error.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FA3-E-03",
    paper: "FA",
    area: "E",
    type: "mcq",
    stem: "Which of the following errors would require an adjustment to the PAYABLES CONTROL ACCOUNT, rather than to the list of individual supplier balances?",
    options: [
      "A supplier's balance was omitted from the list of balances",
      "The purchases day book total for the month was overcast by $400",
      "An invoice was posted to the wrong supplier's personal account",
      "A supplier's balance of $890 was written on the list as $980",
    ],
    correct: 1,
    explanation:
      "The day book TOTAL is what gets posted to the control account, so an overcast total corrupts the control account itself. An omitted balance and a transposed balance are extraction errors in the list, and posting to the wrong personal account moves the amount between memorandum accounts without touching the control account.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-E-04",
    paper: "FA",
    area: "E",
    type: "mcq",
    stem: "After updating the cash book for bank charges and direct debits, Teal Traders' corrected cash book shows a debit balance of $3,240. Unpresented cheques total $820 and outstanding lodgements total $540. What balance should appear on the bank statement?",
    options: ["$2,960 in funds", "$4,600 in funds", "$3,520 in funds", "$1,880 in funds"],
    correct: 2,
    explanation:
      "Statement balance = corrected cash book 3,240 + unpresented cheques 820 (paid in the book, not yet through the bank) − outstanding lodgements 540 (in the book, not yet credited by the bank) = $3,520. $2,960 reverses both timing adjustments, $4,600 adds both, and $1,880 deducts both.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-E-05",
    paper: "FA",
    area: "E",
    type: "mcq",
    stem: "Redshank Ltd's bank statement shows an OVERDRAWN balance of $1,150. Unpresented cheques total $640 and outstanding lodgements total $890. There are no other differences. What balance should the corrected cash book show?",
    options: ["$900 overdrawn", "$1,400 overdrawn", "$900 in funds", "$1,400 in funds"],
    correct: 0,
    explanation:
      "Starting from the statement: −1,150 + 890 lodgements not yet credited − 640 cheques not yet presented = −900, i.e. $900 overdrawn. $1,400 overdrawn applies both adjustments the wrong way round, and the 'in funds' options lose track of the overdraft sign.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FA3-E-06",
    paper: "FA",
    area: "E",
    type: "mcq",
    stem: "Cash of $450 received from a credit customer was DEBITED to the customer's account in the receivables control and CREDITED to bank — a complete reversal of the correct entry. Which statement is true?",
    options: [
      "The trial balance totals will differ by $450",
      "The trial balance totals will differ by $900",
      "The trial balance still balances, but receivables are overstated by $450",
      "The trial balance still balances, but receivables are overstated by $900",
    ],
    correct: 3,
    explanation:
      "A complete reversal has equal debits and credits, so the trial balance still agrees — but the accounts are wrong by TWICE the amount: receivables should have fallen $450 and instead rose $450 (overstated $900), with bank understated $900. Thinking the trial balance disagrees, or adjusting by only one lot of $450, are the classic slips.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-E-07",
    paper: "FA",
    area: "E",
    type: "mcq",
    stem: "Which of the following errors WOULD cause the trial balance totals to disagree?",
    options: [
      "A credit sale completely omitted from all the books",
      "A cash payment for repairs debited to the machinery account",
      "Discounts allowed posted to the discounts allowed account but not recorded in the receivables control account",
      "A purchase invoice for $210 entered in the day book as $120",
    ],
    correct: 2,
    explanation:
      "A one-sided posting (debit made, credit missing) throws the totals out. Complete omission, an error of principle (repairs to machinery) and an error of original entry ($210 as $120) all keep debits equal to credits, so the trial balance still balances despite being wrong.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA3-E-08",
    paper: "FA",
    area: "E",
    type: "mcq",
    stem: "An electricity payment of $780 was correctly credited to bank, but was also CREDITED to the electricity expense account in error. A suspense account was opened for the trial balance difference. Which journal corrects the error?",
    options: [
      "Dr Electricity $1,560; Cr Suspense $1,560",
      "Dr Electricity $780; Cr Suspense $780",
      "Dr Suspense $1,560; Cr Electricity $1,560",
      "No suspense entry is needed, because the trial balance still balances",
    ],
    correct: 0,
    explanation:
      "Two credits of $780 and no debit leave debits $1,560 short, so suspense holds a $1,560 debit. The fix debits electricity $1,560 (cancelling the wrong $780 credit AND inserting the missing $780 debit) and credits suspense. Adjusting by one lot of $780 misses the doubling, reversing the journal misreads the suspense side, and the trial balance certainly does NOT balance here.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-E-09",
    paper: "FA",
    area: "E",
    type: "number",
    stem: "Corncrake Joinery's draft profit is $73,400. Three errors are then found: (1) $6,000 spent installing a new machine was charged to repairs — the machine should be depreciated at 10% straight-line for a full year; (2) closing inventory includes items at cost of $2,000 whose net realisable value is only $1,300; (3) a rent PREPAYMENT of $900 was treated as an accrual instead. What is the corrected profit, in $?",
    numericAnswer: 79900,
    unit: "$",
    explanation:
      "(1) Capitalising adds back 6,000 but charges 600 depreciation: +5,400. (2) Inventory written down to NRV: −700. (3) A prepayment booked as an accrual overstates the expense by TWICE the amount: +1,800. Corrected profit = 73,400 + 5,400 − 700 + 1,800 = $79,900. The traps: forgetting the depreciation on the capitalised cost, and adjusting the prepayment/accrual mix-up by only $900.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FA3-E-10",
    paper: "FA",
    area: "E",
    type: "mcq",
    stem: "Which of the following is NOT a purpose of maintaining a receivables control account?",
    options: [
      "It provides an overall check on the accuracy of postings to the individual customer accounts",
      "It helps to localise errors, making them quicker to find",
      "It provides a total receivables figure quickly for the trial balance",
      "It confirms that each individual customer's balance is free from error",
    ],
    correct: 3,
    explanation:
      "A control account checks TOTALS, so compensating errors within individual customer accounts can hide behind an agreeing control balance — it can never confirm each individual balance is correct. Checking overall accuracy, localising errors and supplying a quick total are all genuine purposes.",
    marks: 2,
    difficulty: "easy",
  },

  /* ───────────── Area F — Preparing basic financial statements ───────────── */
  {
    id: "FA3-F-01",
    paper: "FA",
    area: "F",
    type: "mcq",
    stem: "Kite Property receives rent from a tenant in advance. At the year end, $1,200 of the cash received relates to the following year. In Kite's statement of financial position this $1,200 is shown as:",
    options: [
      "A current asset (accrued income)",
      "A current liability (deferred income)",
      "An addition to rental income for the year",
      "A non-current liability",
    ],
    correct: 1,
    explanation:
      "Cash received before it is earned is DEFERRED income — an obligation to provide occupation next year, so a current liability. Accrued income is the opposite situation (earned but not yet received), recognising it as income overstates this year's profit, and it will be earned within 12 months, so it is not non-current.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA3-F-02",
    paper: "FA",
    area: "F",
    type: "number",
    stem: "During the year, Osier Estates received $10,400 in rent from tenants. At the start of the year tenants owed $800 (accrued income). At the end of the year tenants had paid $600 in advance and owed nothing. What rental income should be reported in profit or loss, in $?",
    numericAnswer: 9000,
    unit: "$",
    explanation:
      "Income earned = cash received 10,400 − opening accrued income 800 (earned LAST year, collected this year) − closing advance 600 (belongs to NEXT year) = $9,000. The classic error is adding the opening arrears or the closing advance instead of deducting them.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-F-03",
    paper: "FA",
    area: "F",
    type: "mcq",
    stem: "Gannet plc has 400,000 ordinary shares of $0.50 each in issue. It makes a 1-for-5 rights issue at $1.30 per share, which is fully taken up. Which entries record the issue?",
    options: [
      "Dr Bank $104,000; Cr Share capital $104,000",
      "Dr Bank $104,000; Cr Share capital $64,000; Cr Share premium $40,000",
      "Dr Bank $104,000; Cr Share capital $40,000; Cr Share premium $64,000",
      "Dr Share premium $40,000; Cr Share capital $40,000",
    ],
    correct: 2,
    explanation:
      "80,000 new shares (400,000 ÷ 5) raise 80,000 × $1.30 = $104,000 cash; nominal value 80,000 × $0.50 = $40,000 goes to share capital and the excess $64,000 to share premium. Crediting everything to share capital ignores the premium, the second option swaps the split, and the last is the entry for a BONUS issue, which raises no cash.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-F-04",
    paper: "FA",
    area: "F",
    type: "mcq",
    stem: "Where do ordinary dividends PAID during the year appear in a company's financial statements?",
    options: [
      "As an expense in the statement of profit or loss",
      "As a deduction in the statement of changes in equity",
      "As a current liability, whether or not they have been declared",
      "They are not recorded until the following year",
    ],
    correct: 1,
    explanation:
      "Dividends are a distribution of profit TO owners, not an expense of earning it, so they appear as a deduction from retained earnings in the statement of changes in equity. Expensing them misstates profit, and only dividends DECLARED but unpaid at the year end create a liability.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA3-F-05",
    paper: "FA",
    area: "F",
    type: "number",
    stem: "Bittern Hardware sells goods at a mark-up of 40% on cost. Sales for the year were $175,000, opening inventory was $14,000 and purchases were $130,000. A physical count values closing inventory at only $12,500, the difference being goods stolen. What was the COST of the goods stolen, in $?",
    numericAnswer: 6500,
    unit: "$",
    explanation:
      "Cost of goods sold = 175,000 ÷ 1.40 = 125,000 (mark-up ON COST, so divide by 1.4). Expected closing inventory = 14,000 + 130,000 − 125,000 = 19,000; goods stolen = 19,000 − 12,500 = $6,500. The fatal trap is treating 40% as a margin on sales (COS = 60% × sales), which gives the wrong shortfall.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FA3-F-06",
    paper: "FA",
    area: "F",
    type: "mcq",
    stem: "Which of the following items would NOT appear in a company's statement of changes in equity?",
    options: [
      "Total comprehensive income for the year",
      "Dividends paid to ordinary shareholders",
      "The proceeds of a new issue of ordinary shares",
      "Interest paid on a bank loan",
    ],
    correct: 3,
    explanation:
      "Loan interest is a finance cost in the statement of profit or loss — lenders are not owners, so it never touches equity. Comprehensive income, dividends and share issues are all movements in equity and belong in the statement of changes in equity.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA3-F-07",
    paper: "FA",
    area: "F",
    type: "mcq",
    stem: "Sorrel Ltd paid $5,600 for telephone costs during the year. An accrual of $300 was outstanding at the START of the year, and $450 was owed at the END of the year. What telephone expense should be reported in profit or loss?",
    options: ["$5,750", "$5,450", "$6,350", "$5,600"],
    correct: 0,
    explanation:
      "Expense = cash paid 5,600 − opening accrual 300 (last year's cost paid this year) + closing accrual 450 (this year's cost not yet paid) = $5,750. $5,450 reverses the two adjustments, $6,350 adds both accruals, and $5,600 ignores the accruals entirely.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-F-08",
    paper: "FA",
    area: "F",
    type: "mcq",
    stem: "Merganser Ltd's property, plant and equipment had a carrying amount of $80,000 at the start of the year and $95,000 at the end. The depreciation charge for the year was $12,000, and an asset with a carrying amount of $5,000 was sold during the year. All additions were paid in cash. How much cash was paid for additions to PPE?",
    options: ["$27,000", "$15,000", "$32,000", "$22,000"],
    correct: 2,
    explanation:
      "Closing CA = opening − depreciation − disposals + additions: 95,000 = 80,000 − 12,000 − 5,000 + A, so A = $32,000. $27,000 forgets the disposal, $22,000 deducts the disposal instead of adding it back, and $15,000 is just the movement in carrying amount, ignoring depreciation and the disposal.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FA3-F-09",
    paper: "FA",
    area: "F",
    type: "mcq",
    stem: "Trent plc issues REDEEMABLE preference shares, which it must buy back at a fixed date. How should these shares and their dividends be treated in the financial statements?",
    options: [
      "As equity, with dividends reported in the statement of changes in equity",
      "As a liability, with dividends treated as a finance cost in profit or loss",
      "As equity, with dividends treated as a finance cost in profit or loss",
      "As a liability, with dividends reported in the statement of changes in equity",
    ],
    correct: 1,
    explanation:
      "A mandatory redemption obligation makes the shares, in substance, debt: a liability whose 'dividends' are really interest — a finance cost. Treating them as equity follows legal form over substance, and the mixed options pair the classification with the wrong dividend treatment.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-F-10",
    paper: "FA",
    area: "F",
    type: "number",
    stem: "Quail Ltd estimated its tax liability for the year ended 31 December 20X4 at $12,000, which remained unpaid at that year end. During 20X5 the 20X4 liability was settled in full for $11,400. The estimated tax on 20X5 profits is $15,000. What tax charge appears in profit or loss for 20X5, in $?",
    numericAnswer: 14400,
    unit: "$",
    explanation:
      "Settling $12,000 for $11,400 reveals a $600 OVER-provision in 20X4, which is credited against this year's charge: 15,000 − 600 = $14,400. The traps are adding the $600 (as if it were an under-provision) or charging the full $15,000 and ignoring the prior-year adjustment.",
    marks: 2,
    difficulty: "medium",
  },

  /* ───────────── Area G — Simple consolidated financial statements ───────────── */
  {
    id: "FA3-G-01",
    paper: "FA",
    area: "G",
    type: "mcq",
    stem: "Under IFRS 10, control of an investee requires all of the following EXCEPT:",
    options: [
      "Power over the investee",
      "Exposure, or rights, to variable returns from involvement with the investee",
      "The ability to use power over the investee to affect the amount of those returns",
      "Ownership of more than 50% of the investee's ordinary shares",
    ],
    correct: 3,
    explanation:
      "Control has three elements: power, exposure to variable returns, and the ability to use that power to affect returns. A majority shareholding is the most COMMON way to obtain power, but it is neither necessary nor always sufficient — control can exist with less than 50%.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA3-G-02",
    paper: "FA",
    area: "G",
    type: "mcq",
    stem: "A parent acquires a subsidiary part-way through its financial year. The subsidiary's results are included in the consolidated statement of profit or loss:",
    options: [
      "For the full financial year, regardless of the acquisition date",
      "From the date of acquisition to the end of the reporting period",
      "Only from the start of the next financial year",
      "Only if the parent owns 100% of the shares",
    ],
    correct: 1,
    explanation:
      "The group reports only the results earned UNDER ITS CONTROL, i.e. from the acquisition date onward. Consolidating a full year includes pre-acquisition profits that the group never earned, waiting until next year omits results it did earn, and consolidation applies to all subsidiaries, not just wholly owned ones.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA3-G-03",
    paper: "FA",
    area: "G",
    type: "number",
    stem: "Petrel plc, with revenue of $600,000 for the year ended 31 December, acquired 90% of Stint Ltd on 1 October. Stint's revenue for the same full year was $240,000, accruing evenly over the year. There were no intra-group sales. What is consolidated revenue, in $?",
    numericAnswer: 660000,
    unit: "$",
    explanation:
      "Only Stint's POST-acquisition revenue is consolidated: 240,000 × 3/12 = 60,000, giving 600,000 + 60,000 = $660,000. Adding Stint's full $240,000, or taking 90% of its revenue (revenue is consolidated in FULL, with NCI dealt with in profit), are the classic errors.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-G-04",
    paper: "FA",
    area: "G",
    type: "mcq",
    stem: "Pike plc acquires 75% of Sole Ltd for $90,000 when the fair value of Sole's identifiable net assets is $100,000. The non-controlling interest is measured at its proportionate share of net assets. What is goodwill at acquisition?",
    options: ["$15,000", "$25,000", "$65,000", "A bargain purchase gain of $10,000"],
    correct: 0,
    explanation:
      "NCI = 25% × 100,000 = 25,000; goodwill = consideration 90,000 + NCI 25,000 − net assets 100,000 = $15,000. $25,000 is just the NCI figure, $65,000 SUBTRACTS the NCI instead of adding it, and the 'bargain purchase' answer compares 90,000 with 100,000 while forgetting the NCI entirely.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-G-05",
    paper: "FA",
    area: "G",
    type: "mcq",
    stem: "Siskin Ltd, an 80%-owned subsidiary of Pintail plc, sold goods to Pintail at a profit during the year. Some of the goods remain in Pintail's inventory at the year end. How is the unrealised profit dealt with on consolidation?",
    options: [
      "Reduce the parent's profit only, leaving the non-controlling interest unaffected",
      "Reduce the subsidiary's profit, so the non-controlling interest's share of profit also falls",
      "Make no adjustment, because the sale was within the group",
      "Increase consolidated inventory by the unrealised profit",
    ],
    correct: 1,
    explanation:
      "The SELLER made the unrealised profit — here the subsidiary — so the PURP reduces the subsidiary's profit, and the NCI bears its 20% share of the adjustment. Adjusting the parent gets the direction wrong, ignoring it overstates group profit and inventory, and the adjustment REDUCES inventory, never increases it.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-G-06",
    paper: "FA",
    area: "G",
    type: "mcq",
    stem: "Swift Ltd, a subsidiary of Plume plc, sold goods to Plume for $15,000 at a gross MARGIN of 20%. One third of the goods remain in Plume's inventory at the year end. What unrealised profit must be eliminated on consolidation?",
    options: ["$1,000", "$833", "$2,500", "$3,000"],
    correct: 0,
    explanation:
      "A 20% margin is measured on the SELLING price: profit in the transfer = 15,000 × 20% = 3,000, and one third is still held: $1,000. $833 treats the 20% as a mark-up on cost (15,000 ÷ 1.2), $3,000 eliminates profit on ALL the goods rather than those still held, and $2,500 is the mark-up-based profit on the full amount.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-G-07",
    paper: "FA",
    area: "G",
    type: "mcq",
    stem: "Perch plc owns 70% of Shad Ltd. At acquisition the non-controlling interest was measured at its fair value of $30,000. Since acquisition, Shad has made profits of $40,000 and paid no dividends; there are no other adjustments. What is the NCI in the consolidated statement of financial position?",
    options: ["$30,000", "$58,000", "$42,000", "$70,000"],
    correct: 2,
    explanation:
      "NCI at the reporting date = NCI at acquisition 30,000 + NCI share of post-acquisition profits (30% × 40,000 = 12,000) = $42,000. $30,000 forgets to update for post-acquisition profits, $58,000 gives the NCI the PARENT's 70% share, and $70,000 adds all of Shad's profits to the NCI.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FA3-G-08",
    paper: "FA",
    area: "G",
    type: "mcq",
    stem: "At the year end, Pochard plc's statement of financial position includes a $10,000 loan receivable from its wholly owned subsidiary, and the subsidiary shows the matching $10,000 loan payable. In the consolidated statement of financial position, these balances are:",
    options: [
      "Shown in full — the asset within receivables and the liability within payables",
      "Shown net as a single asset of $10,000",
      "Disclosed as a contingent liability",
      "Eliminated in full — the group cannot owe money to itself",
    ],
    correct: 3,
    explanation:
      "From the single-entity perspective, an intra-group loan is the group lending to itself, so both the asset and the liability are removed in full on consolidation. Showing them gross (or 'net' — which still leaves $10,000 in the accounts) overstates the group's position, and there is nothing contingent about it.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA3-G-09",
    paper: "FA",
    area: "G",
    type: "mcq",
    stem: "Pintola plc's cost of sales is $210,000 and its subsidiary Smew Ltd's is $90,000. During the year Pintola sold goods to Smew for $20,000, and at the year end Smew still held goods bought from Pintola containing unrealised profit of $2,000. What is consolidated cost of sales?",
    options: ["$280,000", "$300,000", "$282,000", "$278,000"],
    correct: 2,
    explanation:
      "Consolidated cost of sales = 210,000 + 90,000 − 20,000 intra-group purchases + 2,000 PURP = $282,000 (the PURP is ADDED to cost of sales to strip the profit out of closing inventory). $280,000 forgets the PURP, $278,000 deducts it instead of adding it, and $300,000 makes no intra-group elimination at all.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FA3-G-10",
    paper: "FA",
    area: "G",
    type: "mcq",
    stem: "Why are consolidated financial statements prepared?",
    options: [
      "Because the law treats the parent and its subsidiaries as one legal person",
      "Because they replace the subsidiaries' own individual financial statements",
      "To present the parent and its subsidiaries as a single economic entity, reflecting all resources under the parent's control",
      "To avoid having to eliminate intra-group transactions in the individual company accounts",
    ],
    correct: 2,
    explanation:
      "Consolidation applies the single ECONOMIC entity concept: users see all resources the parent controls, however the group is legally structured. The companies remain separate LEGAL persons, subsidiaries still prepare their own statements, and eliminating intra-group items is part of the process, not a way of avoiding it.",
    marks: 2,
    difficulty: "easy",
  },

  /* ───────────── Area H — Interpretation of financial statements ───────────── */
  {
    id: "FA3-H-01",
    paper: "FA",
    area: "H",
    type: "mcq",
    stem: "Rathmore Stores has revenue of $250,000, cost of sales of $170,000 and operating expenses of $30,000. What is the gross profit margin?",
    options: ["32%", "20%", "47.1%", "68%"],
    correct: 0,
    explanation:
      "Gross profit margin = (250,000 − 170,000) ÷ 250,000 = 32%. 20% is the OPERATING margin (after the $30,000 expenses), 47.1% is the mark-up on cost (80 ÷ 170), and 68% is cost of sales as a percentage of revenue.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA3-H-02",
    paper: "FA",
    area: "H",
    type: "mcq",
    stem: "In the return on capital employed (ROCE) ratio, capital employed is usually defined as:",
    options: [
      "Equity only",
      "Equity plus non-current liabilities (long-term debt)",
      "Current assets less current liabilities",
      "Total assets",
    ],
    correct: 1,
    explanation:
      "ROCE relates profit before interest and tax to ALL long-term funds — equity plus long-term borrowings. Equity alone is the denominator for return on equity, current assets less current liabilities is working capital, and total assets ignores the deduction of current liabilities.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA3-H-03",
    paper: "FA",
    area: "H",
    type: "mcq",
    stem: "Selborne Traders has gross credit purchases of $255,500 and purchase returns of $14,600. Cost of sales is $262,800 and trade payables at the year end are $33,000. What is the payables payment period, based on a 365-day year?",
    options: ["47 days", "46 days", "50 days", "7 days"],
    correct: 2,
    explanation:
      "Use NET credit purchases: 255,500 − 14,600 = 240,900; payables days = 33,000 ÷ 240,900 × 365 = 50 days. 47 days forgets to deduct the returns, 46 days uses cost of sales instead of purchases, and 7 is the payables TURNOVER in times, not a number of days.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-H-04",
    paper: "FA",
    area: "H",
    type: "mcq",
    stem: "A retailer's inventory holding period has risen from 40 days to 78 days while revenue and gross margin are broadly unchanged. What is the MOST likely explanation?",
    options: [
      "Inventory is being sold more quickly than before",
      "Obsolete or slow-moving inventory is building up in the warehouse",
      "Suppliers are being paid more slowly",
      "Customers are taking longer to pay for credit sales",
    ],
    correct: 1,
    explanation:
      "With sales steady, a near-doubling of inventory days means goods are sitting longer before sale — the signature of slow-moving or obsolete stock. Faster selling would REDUCE the period, supplier payment speed drives payables days, and customer payment speed drives receivables days.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-H-05",
    paper: "FA",
    area: "H",
    type: "mcq",
    stem: "Fairlead Ltd's revenue rose 15% during the year, but its gross profit margin fell from 38% to 31%. Which of the following is the MOST likely explanation?",
    options: [
      "Selling prices were reduced to win volume, without an equivalent reduction in cost per unit",
      "Administrative salaries increased during the year",
      "Interest costs rose after taking out a new loan",
      "Depreciation on head-office buildings increased",
    ],
    correct: 0,
    explanation:
      "Higher volume with a thinner gross margin points to price discounting (or unrecovered cost inflation) — a GROSS profit driver. Administrative salaries, loan interest and head-office depreciation all sit BELOW gross profit, so they cannot move the gross margin at all.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-H-06",
    paper: "FA",
    area: "H",
    type: "mcq",
    stem: "Kelso Ltd has revenue of $480,000, profit before interest and tax of $48,000 and capital employed of $320,000. What is its asset turnover?",
    options: ["0.67 times", "10%", "15%", "1.5 times"],
    correct: 3,
    explanation:
      "Asset turnover = revenue ÷ capital employed = 480,000 ÷ 320,000 = 1.5 times — each $1 of long-term funds generates $1.50 of sales. 0.67 inverts the fraction, 10% is the operating MARGIN (48 ÷ 480), and 15% is ROCE (48 ÷ 320).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-H-07",
    paper: "FA",
    area: "H",
    type: "mcq",
    stem: "Over the year, Marfield Ltd's current ratio rose from 1.8 to 2.4 while its quick (acid test) ratio fell from 1.1 to 0.8. Which movement explains BOTH changes?",
    options: [
      "Cash balances increased substantially",
      "Inventory levels rose substantially",
      "Trade payables fell sharply",
      "Trade receivables rose substantially",
    ],
    correct: 1,
    explanation:
      "Inventory is the only current asset INSIDE the current ratio but EXCLUDED from the quick ratio, so an inventory build-up is the only option consistent with the two ratios diverging. More cash, lower payables or higher receivables would each push BOTH ratios in the same direction.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA3-H-08",
    paper: "FA",
    area: "H",
    type: "mcq",
    stem: "Draymoor Ltd's operating profit margin improved from 10% to 12%, yet its ROCE fell from 20% to 18%. Which of the following explains this?",
    options: [
      "Gearing increased during the year",
      "The tax charge for the year increased",
      "Asset turnover fell — for example, major new assets are not yet generating their full revenue",
      "Interest rates on the company's borrowings rose",
    ],
    correct: 2,
    explanation:
      "ROCE = operating margin × asset turnover. Turnover must have fallen from 2.0 (20 ÷ 10) to 1.5 (18 ÷ 12) — typically heavy capital investment not yet producing sales. Gearing describes the FUNDING mix, and tax and interest sit below the PBIT figure used in ROCE, so none of them can reconcile the two ratios.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FA3-H-09",
    paper: "FA",
    area: "H",
    type: "mcq",
    stem: "Wexcombe Ltd reports profit after tax of $36,000, a tax charge of $12,000 and interest payable of $8,000. What is its interest cover?",
    options: ["7 times", "6 times", "4.5 times", "0.14 times"],
    correct: 0,
    explanation:
      "Interest cover = PBIT ÷ interest = (36,000 + 12,000 + 8,000) ÷ 8,000 = 7 times. 6 times adds back the tax but forgets the interest itself, 4.5 times divides profit AFTER tax by interest, and 0.14 inverts the ratio.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FA3-H-10",
    paper: "FA",
    area: "H",
    type: "mcq",
    stem: "Which of the following transactions would REDUCE a company's gearing ratio, measured as debt ÷ (debt + equity)?",
    options: [
      "A bonus issue of ordinary shares",
      "Issuing loan notes to finance new machinery",
      "A downward revaluation of property",
      "A rights issue of shares with the proceeds used to repay borrowings",
    ],
    correct: 3,
    explanation:
      "A rights issue raises equity AND the proceeds cut debt — both movements reduce gearing. A bonus issue merely reshuffles amounts within equity (total equity unchanged), new loan notes add debt, and a downward revaluation shrinks equity — the last two both INCREASE gearing.",
    marks: 2,
    difficulty: "easy",
  },
]
