import type { AccaQuestion } from "@/lib/acca-content"

/*
 * FA question bank — wave 2 (51 verified original questions, 2026-07-10).
 * Blueprint: areas balanced to ~10 each at 80 total; 30/45/25 difficulty;
 * every distractor is a nameable student error. Merged into QUESTIONS
 * in acca-content.ts.
 */

export const FA_WAVE2: AccaQuestion[] = [
  /* ───────────── Area A — Context & purpose of financial reporting ───────────── */
  {
    id: "FA2-A-01",
    paper: "FA",
    area: "A",
    type: "mcq",
    stem: "Which body is responsible for issuing IFRS Accounting Standards?",
    options: [
      "The IFRS Interpretations Committee",
      "The International Accounting Standards Board (IASB)",
      "The Financial Accounting Standards Board (FASB)",
      "ACCA",
    ],
    correct: 1,
    explanation:
      "The IASB issues IFRS Accounting Standards. The Interpretations Committee issues interpretations of standards, the FASB sets US GAAP, and ACCA is a professional body — none of them issue IFRS.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA2-A-02",
    paper: "FA",
    area: "A",
    type: "mcq",
    stem: "According to the IASB Conceptual Framework, the PRIMARY users of general purpose financial statements are:",
    options: [
      "The entity's management",
      "The tax authorities",
      "Existing and potential investors, lenders and other creditors",
      "The entity's employees",
    ],
    correct: 2,
    explanation:
      "The Framework identifies existing and potential investors, lenders and other creditors as the primary users. Management is not a primary user because it can obtain the information it needs internally; tax authorities and employees are other (secondary) users.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA2-A-03",
    paper: "FA",
    area: "A",
    type: "number",
    stem: "Kestrel Traders has total assets of $82,000 and capital (owner's equity) of $57,000. What are its total liabilities, in $?",
    numericAnswer: 25000,
    unit: "$",
    explanation:
      "Rearrange the accounting equation: Liabilities = Assets − Capital = 82,000 − 57,000 = $25,000. Adding instead of subtracting is the classic slip here.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA2-A-04",
    paper: "FA",
    area: "A",
    type: "mcq",
    stem: "Which statement BEST distinguishes financial accounting from management accounting?",
    options: [
      "Financial accounting reports to external users within a regulatory framework; management accounting serves internal decision-making",
      "Management accounting must comply with IFRS Accounting Standards; financial accounting need not",
      "Financial accounting is primarily forward-looking; management accounting records only past transactions",
      "Management accounting reports must be published annually to shareholders",
    ],
    correct: 0,
    explanation:
      "Financial accounting produces regulated statements for external users; management accounting is internal, unregulated and often forward-looking. The wrong options reverse which branch is regulated, reverse the time orientation, or attach the publication requirement to the wrong branch.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA2-A-05",
    paper: "FA",
    area: "A",
    type: "mcq",
    stem: "Riverton Bakery buys a delivery van for $12,000, paying a $3,000 deposit from its bank account and financing the remaining $9,000 with a loan. What is the effect on the accounting equation?",
    options: [
      "Assets increase $12,000; liabilities increase $12,000; capital unchanged",
      "Assets increase $9,000; liabilities increase $9,000; capital unchanged",
      "Assets increase $12,000; liabilities increase $9,000; capital increases $3,000",
      "Assets increase $9,000; liabilities unchanged; capital increases $9,000",
    ],
    correct: 1,
    explanation:
      "The van adds $12,000 to assets but the bank falls by $3,000, so assets rise by a net $9,000, matched by the $9,000 loan. Ignoring the bank payment, treating the deposit as capital introduced, or confusing the loan with owner's capital produce the wrong options.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA2-A-06",
    paper: "FA",
    area: "A",
    type: "mcq",
    stem: "Which of the following is an advantage of operating as a limited liability company rather than as a sole trader?",
    options: [
      "The company is not required to file financial statements",
      "The company's profits are not subject to tax",
      "The company ceases to exist when a shareholder sells their shares",
      "The shareholders' personal liability for the company's debts is limited",
    ],
    correct: 3,
    explanation:
      "Limited liability protects shareholders' personal assets. Companies actually face MORE filing requirements than sole traders, their profits are taxed, and a company has perpetual succession — it continues when shares change hands.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA2-A-07",
    paper: "FA",
    area: "A",
    type: "mcq",
    stem: "The report of a company's external auditor provides:",
    options: [
      "A guarantee that no fraud has occurred in the company",
      "An opinion on whether the financial statements give a true and fair view",
      "A guarantee that the company will continue as a going concern",
      "An assessment of how efficiently the directors have managed the company",
    ],
    correct: 1,
    explanation:
      "An audit gives reasonable assurance and an OPINION on the truth and fairness of the financial statements — not a guarantee. Treating the audit as a fraud guarantee, a going-concern guarantee, or a review of management performance are the classic misconceptions.",
    marks: 2,
    difficulty: "hard",
  },

  /* ───────────── Area B — Qualitative characteristics ───────────── */
  {
    id: "FA2-B-01",
    paper: "FA",
    area: "B",
    type: "mcq",
    stem: "Which of the following is an ENHANCING qualitative characteristic of useful financial information?",
    options: ["Relevance", "Faithful representation", "Understandability", "Prudence"],
    correct: 2,
    explanation:
      "The four enhancing characteristics are comparability, verifiability, timeliness and understandability. Relevance and faithful representation are the FUNDAMENTAL characteristics, and prudence is not a qualitative characteristic at all.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA2-B-02",
    paper: "FA",
    area: "B",
    type: "mcq",
    stem: "Which of the following is NOT a component of faithful representation?",
    options: ["Completeness", "Predictive value", "Neutrality", "Freedom from error"],
    correct: 1,
    explanation:
      "A faithful representation is complete, neutral and free from error. Predictive value belongs to RELEVANCE — mixing the components of the two fundamental characteristics is the trap.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA2-B-03",
    paper: "FA",
    area: "B",
    type: "mcq",
    stem: "Under the IASB Conceptual Framework, prudence means:",
    options: [
      "Deliberately understating assets and income to be on the safe side",
      "Recognising every possible future loss immediately, whether probable or not",
      "The exercise of caution when making judgements under conditions of uncertainty",
      "Always selecting the accounting policy that reports the lowest profit",
    ],
    correct: 2,
    explanation:
      "Prudence is caution under uncertainty and it SUPPORTS neutrality — it does not permit bias. Deliberate understatement, recognising improbable losses, or always choosing the lowest profit are asymmetric 'conservatism' errors the Framework rejects.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA2-B-04",
    paper: "FA",
    area: "B",
    type: "mcq",
    stem: "Ferndale Ltd changed its depreciation method this year and disclosed the nature and effect of the change in the notes. Which ENHANCING qualitative characteristic does this disclosure most directly support?",
    options: ["Timeliness", "Verifiability", "Faithful representation", "Comparability"],
    correct: 3,
    explanation:
      "Disclosing changes in accounting policy or method lets users compare results across periods, supporting comparability. Timeliness and verifiability are different enhancing characteristics, and faithful representation is fundamental, not enhancing.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA2-B-05",
    paper: "FA",
    area: "B",
    type: "mcq",
    stem: "\"Different knowledgeable and independent observers could reach consensus that a depiction is faithfully represented.\" This describes which qualitative characteristic?",
    options: ["Verifiability", "Relevance", "Comparability", "Understandability"],
    correct: 0,
    explanation:
      "Consensus among independent observers is the Framework's definition of verifiability. Relevance is about influencing decisions, comparability is about consistency across entities and periods, and understandability is about clear presentation.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA2-B-06",
    paper: "FA",
    area: "B",
    type: "mcq",
    stem: "According to the Conceptual Framework, the PERVASIVE constraint on the information that financial reporting can provide is:",
    options: ["Materiality", "Cost", "Timeliness", "Going concern"],
    correct: 1,
    explanation:
      "Cost is the pervasive constraint: the benefits of reporting information should justify the costs of providing it. Materiality is an aspect of relevance, timeliness is an enhancing characteristic, and going concern is the underlying assumption.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA2-B-07",
    paper: "FA",
    area: "B",
    type: "mcq",
    stem: "To publish its results sooner, Hazelmere Ltd uses significantly more estimates, some of which are later revised. This situation BEST illustrates a trade-off between:",
    options: [
      "Comparability and understandability",
      "Relevance and materiality",
      "Timeliness and faithful representation",
      "Neutrality and prudence",
    ],
    correct: 2,
    explanation:
      "Reporting earlier improves timeliness but heavier estimation reduces freedom from error, an element of faithful representation. Materiality is part of relevance and prudence supports neutrality, so neither pair can be traded off against each other.",
    marks: 2,
    difficulty: "hard",
  },

  /* ───────────── Area C — Double-entry & accounting systems ───────────── */
  {
    id: "FA2-C-01",
    paper: "FA",
    area: "C",
    type: "mcq",
    stem: "The owner of Willow Homeware takes goods that cost $300 from the business for personal use. What is the correct double entry?",
    options: [
      "Dr Purchases $300, Cr Drawings $300",
      "Dr Drawings $300, Cr Purchases $300",
      "Dr Drawings $300, Cr Sales $300",
      "Dr Wages $300, Cr Purchases $300",
    ],
    correct: 1,
    explanation:
      "Goods taken by the owner are drawings, removed at COST by crediting purchases. Reversing the entry, recording a 'sale' to the owner, or treating drawings as a wages expense are the standard errors.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA2-C-02",
    paper: "FA",
    area: "C",
    type: "mcq",
    stem: "During the year the rent account of Barton Cafe records debit entries totalling $3,600 and a credit entry of $400 for a refund received. What is the balance carried down on the account?",
    options: ["$3,200 debit", "$3,200 credit", "$4,000 debit", "$400 debit"],
    correct: 0,
    explanation:
      "Balance = 3,600 Dr − 400 Cr = $3,200 on the debit side, as expenses carry debit balances. Calling it a credit confuses the sides, $4,000 adds the refund instead of deducting it, and $400 mistakes the smaller side for the balance.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA2-C-03",
    paper: "FA",
    area: "C",
    type: "number",
    stem: "At 1 January, Orchid Design has net assets of $48,000. During the year the owner introduces $10,000 of new capital and takes drawings of $14,000. Profit for the year is $22,000. What are net assets at 31 December, in $?",
    numericAnswer: 66000,
    unit: "$",
    explanation:
      "Closing net assets = opening 48,000 + capital introduced 10,000 + profit 22,000 − drawings 14,000 = $66,000. The trap is adding drawings or subtracting the capital introduced.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA2-C-04",
    paper: "FA",
    area: "C",
    type: "mcq",
    stem: "A business keeps a trade receivables control account in the general ledger. The individual customer accounts in the receivables ledger are:",
    options: [
      "Part of the double-entry system, making the control account a memorandum record",
      "Credited whenever a credit sale is made to the customer",
      "Memorandum records that are not part of the double-entry system",
      "Updated only once a year, when the control account is reconciled",
    ],
    correct: 2,
    explanation:
      "The control account carries the double entry; the individual customer accounts are memorandum records. Reversing the two, crediting customers for sales (sales are DEBITED to customer accounts), or assuming annual updating are the common confusions.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA2-C-05",
    paper: "FA",
    area: "C",
    type: "mcq",
    stem: "Larkspur Supplies had opening trade receivables of $18,200. During the year: credit sales $96,400, cash received from credit customers $91,300, discounts allowed $1,200, irrecoverable debts written off $900. What are closing trade receivables?",
    options: ["$23,600", "$21,200", "$22,100", "$23,300"],
    correct: 1,
    explanation:
      "18,200 + 96,400 − 91,300 − 1,200 − 900 = $21,200; discounts allowed and write-offs both REDUCE receivables. $22,100 omits the write-off, $23,300 omits both deductions, and $23,600 adds discounts allowed instead of deducting them.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA2-C-06",
    paper: "FA",
    area: "C",
    type: "mcq",
    stem: "Marlow Ltd owes a supplier $2,600, and the same business is also a customer of Marlow owing $1,900. A contra (set-off) is agreed. What is the correct entry in Marlow's records?",
    options: [
      "Dr Payables control $1,900, Cr Receivables control $1,900",
      "Dr Receivables control $1,900, Cr Payables control $1,900",
      "Dr Payables control $2,600, Cr Receivables control $2,600",
      "Dr Payables control $700, Cr Receivables control $700",
    ],
    correct: 0,
    explanation:
      "A contra sets off the LOWER of the two balances ($1,900), reducing both the payable (debit) and the receivable (credit). Reversing the entry, using the payable balance of $2,600, or setting off only the $700 difference are the standard mistakes.",
    marks: 2,
    difficulty: "hard",
  },

  /* ───────────── Area D — Recording transactions & events ───────────── */
  {
    id: "FA2-D-01",
    paper: "FA",
    area: "D",
    type: "mcq",
    stem: "Brightwave Electronics buys 20 units at $6.00 each, then 30 units at $8.00 each, and then sells 25 units. Using the periodic weighted average cost (AVCO) method, what is the value of closing inventory?",
    options: ["$200", "$150", "$180", "$175"],
    correct: 2,
    explanation:
      "Weighted average = (20 × 6 + 30 × 8) ÷ 50 = $7.20, so 25 closing units × 7.20 = $180. $200 applies FIFO (all closing units at $8), $150 prices everything at the earliest $6, and $175 uses a simple unweighted average of the two prices.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA2-D-02",
    paper: "FA",
    area: "D",
    type: "mcq",
    stem: "A debt of $800 written off as irrecoverable last year is unexpectedly received in cash this year. The debit is to Bank. Which CREDIT entry completes the double entry?",
    options: [
      "Cr Trade receivables $800",
      "Cr Irrecoverable debts expense $800",
      "Cr Allowance for receivables $800",
      "Cr Sales revenue $800",
    ],
    correct: 1,
    explanation:
      "A recovered debt is credited to the irrecoverable debts expense account (reducing this year's expense). The receivable no longer exists — it was removed at write-off — and the recovery is neither part of the allowance nor a new sale.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA2-D-03",
    paper: "FA",
    area: "D",
    type: "mcq",
    stem: "Fenwick Manufacturing trades in a machine that cost $30,000 (accumulated depreciation $22,000) against a new machine with a list price of $45,000. The supplier gives a part-exchange allowance of $9,500 and the balance is paid from the bank. What is the result on disposal of the old machine?",
    options: [
      "Profit of $1,500",
      "Loss of $1,500",
      "Profit of $9,500",
      "Loss of $20,500",
    ],
    correct: 0,
    explanation:
      "The part-exchange allowance is the disposal proceeds: 9,500 − carrying amount (30,000 − 22,000 = 8,000) = $1,500 profit. Getting the direction backwards, treating the whole allowance as profit, or comparing the allowance with original COST rather than carrying amount give the other answers.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FA2-D-04",
    paper: "FA",
    area: "D",
    type: "number",
    stem: "Hartley Foods' cash book shows a debit balance of $2,450. The bank statement reveals bank charges of $65, a direct debit of $410 and a customer's dishonoured cheque of $220, none of which are recorded in the cash book. There are also outstanding lodgements of $1,500 and unpresented cheques of $900. What is the corrected cash book balance, in $?",
    numericAnswer: 1755,
    unit: "$",
    explanation:
      "Correct the cash book only for items it has missed: 2,450 − 65 − 410 − 220 = $1,755. Outstanding lodgements and unpresented cheques are timing differences that belong in the reconciliation to the bank statement, NOT in the cash book.",
    marks: 2,
    difficulty: "hard",
  },

  /* ───────────── Area E — Preparing a trial balance ───────────── */
  {
    id: "FA2-E-01",
    paper: "FA",
    area: "E",
    type: "mcq",
    stem: "Which of the following balances would appear on the DEBIT side of a trial balance?",
    options: [
      "Trade payables",
      "Carriage outwards",
      "Bank overdraft",
      "Accumulated depreciation",
    ],
    correct: 1,
    explanation:
      "Carriage outwards is an expense, so it carries a debit balance. Trade payables, a bank overdraft and accumulated depreciation are all credit balances that students commonly place on the wrong side.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA2-E-02",
    paper: "FA",
    area: "E",
    type: "mcq",
    stem: "A repair cost of $150 was debited to the motor expenses account instead of the repairs account. Both are expense accounts. This is an error of:",
    options: ["Principle", "Omission", "Commission", "Original entry"],
    correct: 2,
    explanation:
      "Posting to the wrong account of the SAME class (expense to expense) is an error of commission. An error of principle crosses classes (e.g. capital vs revenue expenditure), omission means the transaction was never recorded, and original entry means the wrong amount was used from the start.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA2-E-03",
    paper: "FA",
    area: "E",
    type: "mcq",
    stem: "A trial balance's debit column total is $500 less than the credit column total, and the difference is posted to a suspense account. It is then found that a discount allowed of $250 was credited to the discounts received account (the entry in the receivables account was made correctly). Which journal clears the suspense account?",
    options: [
      "Dr Suspense $500, Cr Discounts allowed $250, Cr Discounts received $250",
      "Dr Discounts allowed $500, Cr Suspense $500",
      "Dr Discounts allowed $250, Cr Suspense $250",
      "Dr Discounts allowed $250, Dr Discounts received $250, Cr Suspense $500",
    ],
    correct: 3,
    explanation:
      "A missing $250 debit plus a wrong $250 credit leaves debits $500 short, so suspense holds a $500 DEBIT; the fix debits both discount accounts and credits suspense $500. Reversing the journal misreads which side suspense sits on, and the $500 or $250 single-account versions correct only one of the two affected accounts.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FA2-E-04",
    paper: "FA",
    area: "E",
    type: "mcq",
    stem: "The draft accounts of Stanmore Interiors include closing inventory overstated by $3,000. What is the effect of correcting this error on profit for the year?",
    options: [
      "Profit decreases by $3,000",
      "Profit increases by $3,000",
      "No effect, as inventory appears only in the statement of financial position",
      "Profit decreases by $6,000",
    ],
    correct: 0,
    explanation:
      "Reducing closing inventory increases cost of sales, so profit falls by $3,000. Overstated closing inventory OVERSTATES profit (not the reverse), inventory affects both statements, and only the closing figure — not opening as well — needs adjusting, so doubling to $6,000 is wrong.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA2-E-05",
    paper: "FA",
    area: "E",
    type: "mcq",
    stem: "Rent of $370 was paid and correctly credited to the bank account, but was debited to the rent account as $730. What suspense account balance arises from this error?",
    options: [
      "$360 debit",
      "$730 credit",
      "$360 credit",
      "No suspense balance — this is an error of original entry",
    ],
    correct: 2,
    explanation:
      "Debits exceed credits by 730 − 370 = $360, so a $360 CREDIT is needed in suspense to balance. Choosing debit confuses the side, $730 assumes the whole entry failed, and an error of original entry would need the WRONG amount on both sides — here one side is correct, so the trial balance disagrees.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA2-E-06",
    paper: "FA",
    area: "E",
    type: "mcq",
    stem: "Which statement about the trial balance is correct?",
    options: [
      "It proves that no errors have been made in the ledger accounts",
      "It is a list of ledger balances used to check the arithmetic accuracy of the double entry",
      "It forms part of the double-entry system",
      "It must be published with the annual financial statements",
    ],
    correct: 1,
    explanation:
      "A trial balance is an internal arithmetic check listing all ledger balances. It cannot prove there are no errors (e.g. errors of principle or compensating errors still balance), it sits OUTSIDE the double entry as a memorandum, and it is never published.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA2-E-07",
    paper: "FA",
    area: "E",
    type: "number",
    stem: "Draft profit for Calder Logistics is $50,000. It is then found that: a wages accrual of $1,200 was omitted; an insurance prepayment of $800 was omitted; and the year's depreciation charge of $2,500 was posted twice in error. What is the corrected profit, in $?",
    numericAnswer: 52100,
    unit: "$",
    explanation:
      "Corrected profit = 50,000 − 1,200 (accrual adds expense) + 800 (prepayment removes expense) + 2,500 (remove the duplicated depreciation) = $52,100. The trap is getting the direction of each adjustment wrong — accruals cut profit, prepayments and reversed duplicates add it back.",
    marks: 2,
    difficulty: "hard",
  },

  /* ───────────── Area F — Preparing basic financial statements ───────────── */
  {
    id: "FA2-F-01",
    paper: "FA",
    area: "F",
    type: "mcq",
    stem: "Elm Street Books has opening inventory $8,000, purchases $54,000, carriage inwards $1,000 and closing inventory $6,000. What is cost of sales?",
    options: ["$53,000", "$57,000", "$56,000", "$69,000"],
    correct: 1,
    explanation:
      "Cost of sales = 8,000 + 54,000 + 1,000 − 6,000 = $57,000; carriage inwards is part of the cost of purchases. $53,000 swaps opening and closing inventory, $56,000 omits carriage inwards, and $69,000 adds closing inventory instead of deducting it.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA2-F-02",
    paper: "FA",
    area: "F",
    type: "mcq",
    stem: "A bank loan repayable in full 18 months after the reporting date should be presented in the statement of financial position as:",
    options: [
      "A current liability",
      "Part of equity",
      "A non-current liability",
      "A non-current asset",
    ],
    correct: 2,
    explanation:
      "Liabilities due more than 12 months after the reporting date are non-current. Calling it current misapplies the 12-month rule, borrowings are never equity, and a loan owed BY the entity is a liability, not an asset.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA2-F-03",
    paper: "FA",
    area: "F",
    type: "mcq",
    stem: "Maple Court Hotels has revenue $120,000, cost of sales $72,000, distribution costs $15,000 and administrative expenses $18,000. What is GROSS profit?",
    options: ["$48,000", "$15,000", "$33,000", "$30,000"],
    correct: 0,
    explanation:
      "Gross profit = revenue − cost of sales = 120,000 − 72,000 = $48,000; operating expenses come after it. $15,000 is the profit AFTER all operating expenses, while $33,000 and $30,000 wrongly deduct distribution costs or administrative expenses respectively.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA2-F-04",
    paper: "FA",
    area: "F",
    type: "number",
    stem: "Ashford Stores earns a gross profit margin of 25% on sales. Sales for the year were $200,000, opening inventory was $15,000 and purchases were $160,000. What is closing inventory, in $?",
    numericAnswer: 25000,
    unit: "$",
    explanation:
      "A 25% margin means cost of sales = 75% × 200,000 = 150,000, so closing inventory = 15,000 + 160,000 − 150,000 = $25,000. The trap is treating 25% as a mark-up on cost instead of a margin on sales.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA2-F-05",
    paper: "FA",
    area: "F",
    type: "mcq",
    stem: "Shortly after its year end, but before the financial statements are authorised for issue, a major credit customer of Redbrook Ltd (with a balance outstanding at the year end) goes into liquidation. How should this be treated?",
    options: [
      "As an adjusting event — the year-end receivable should be written down",
      "As a non-adjusting event requiring disclosure only",
      "It is not an event after the reporting period because it happened after the year end",
      "It should be ignored because the financial statements had already been drafted",
    ],
    correct: 0,
    explanation:
      "The liquidation provides evidence of the customer's condition AT the reporting date, so IAS 10 treats it as an adjusting event. Calling it non-adjusting misses that link, and events after the reporting period by definition occur after the year end — drafting is irrelevant; only authorisation for issue ends the window.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA2-F-06",
    paper: "FA",
    area: "F",
    type: "mcq",
    stem: "Glenmore plc has 200,000 ordinary shares of $0.50 each and a large share premium account. It makes a 1-for-4 bonus issue using the share premium account. What is the effect?",
    options: [
      "Share capital increases $25,000; bank increases $25,000",
      "Share capital increases $50,000; share premium decreases $50,000",
      "Share capital increases $25,000; share premium decreases $25,000",
      "Share premium increases $25,000; share capital decreases $25,000",
    ],
    correct: 2,
    explanation:
      "A bonus issue of 200,000 ÷ 4 = 50,000 shares × $0.50 nominal = $25,000 moves from share premium to share capital — no cash is received. Expecting cash confuses it with an issue at par, $50,000 uses the share COUNT as dollars, and the last option reverses the entry.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA2-F-07",
    paper: "FA",
    area: "F",
    type: "mcq",
    stem: "Talbot Ltd reports profit before tax of $60,000 after charging depreciation of $9,000. During the year inventory increased by $4,000, receivables decreased by $2,500 and payables decreased by $3,500. What is cash generated from operations?",
    options: ["$46,000", "$64,000", "$74,000", "$71,000"],
    correct: 1,
    explanation:
      "60,000 + 9,000 (add back depreciation) − 4,000 + 2,500 − 3,500 = $64,000. $46,000 deducts depreciation instead of adding it back, $74,000 reverses all three working-capital signs, and $71,000 treats the fall in payables as a cash inflow.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FA2-F-08",
    paper: "FA",
    area: "F",
    type: "number",
    stem: "Norbury Landscaping keeps incomplete records. Net assets were $30,000 at the start of the year and $41,000 at the end. During the year the owner introduced $5,000 of capital and took drawings of $8,000. What was profit for the year, in $?",
    numericAnswer: 14000,
    unit: "$",
    explanation:
      "Profit = increase in net assets − capital introduced + drawings = (41,000 − 30,000) − 5,000 + 8,000 = $14,000. The trap is reversing the signs — capital introduced is NOT profit, and drawings must be added back because they reduced net assets.",
    marks: 2,
    difficulty: "hard",
  },

  /* ───────────── Area G — Simple consolidated financial statements ───────────── */
  {
    id: "FA2-G-01",
    paper: "FA",
    area: "G",
    type: "mcq",
    stem: "Under IFRS 10, a parent must consolidate another entity as a subsidiary when it has:",
    options: [
      "Ownership of at least 20% of the entity's shares",
      "Control over the entity",
      "Significant influence over the entity",
      "Ownership of the majority of the entity's non-current assets",
    ],
    correct: 1,
    explanation:
      "Consolidation is driven by CONTROL, not a fixed shareholding. 20% and significant influence describe an associate (equity accounted), and owning another entity's assets is not the test at all.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA2-G-02",
    paper: "FA",
    area: "G",
    type: "mcq",
    stem: "Cedar plc holds 30% of the voting shares of Birch Ltd and exercises significant influence over it. In Cedar's consolidated financial statements, the investment in Birch is accounted for:",
    options: [
      "Using the equity method",
      "By full line-by-line consolidation",
      "At cost, with no further adjustment",
      "By adding 30% of each of Birch's assets and liabilities line by line",
    ],
    correct: 0,
    explanation:
      "Significant influence makes Birch an associate, accounted for using the equity method. Full consolidation is only for subsidiaries, cost accounting ignores the influence, and proportionate line-by-line consolidation is not permitted for associates.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA2-G-03",
    paper: "FA",
    area: "G",
    type: "mcq",
    stem: "Pearl plc acquires 80% of Shell Ltd for $100,000. The non-controlling interest at acquisition is measured at its fair value of $22,000, and the fair value of Shell's identifiable net assets is $105,000. What is goodwill at acquisition?",
    options: ["$16,000", "$22,000", "$17,000", "A bargain purchase gain of $5,000"],
    correct: 2,
    explanation:
      "Goodwill = consideration 100,000 + NCI 22,000 − net assets 105,000 = $17,000. $16,000 substitutes the 20% share of net assets for the given NCI fair value, $22,000 grabs the NCI figure itself, and the 'gain' answer forgets to include the NCI at all.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA2-G-04",
    paper: "FA",
    area: "G",
    type: "mcq",
    stem: "Pico plc owns 100% of Sarnia Ltd. At the year end Sarnia owes Pico $4,500 for goods supplied. Trade receivables are $50,000 in Pico's own accounts (including the $4,500) and $30,000 in Sarnia's. What are consolidated trade receivables?",
    options: ["$80,000", "$45,500", "$75,500", "$71,000"],
    correct: 2,
    explanation:
      "Add both companies' receivables and eliminate the intra-group balance once: 50,000 + 30,000 − 4,500 = $75,500. $80,000 forgets the elimination, $71,000 eliminates it twice, and $45,500 drops Sarnia's receivables entirely.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA2-G-05",
    paper: "FA",
    area: "G",
    type: "number",
    stem: "Panther plc (revenue $400,000) owns 100% of Snowdon Ltd (revenue $150,000). During the year Panther sold goods to Snowdon for $20,000. What is consolidated revenue, in $?",
    numericAnswer: 530000,
    unit: "$",
    explanation:
      "Consolidated revenue = 400,000 + 150,000 − 20,000 intra-group sales = $530,000. The group cannot report sales to itself — forgetting to eliminate the $20,000 is the classic error.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA2-G-06",
    paper: "FA",
    area: "G",
    type: "mcq",
    stem: "Pavo plc sold goods to its subsidiary Skua Ltd for $12,000 at a mark-up of 25% on cost. Half of these goods remain in Skua's inventory at the year end. What unrealised profit must be eliminated on consolidation?",
    options: ["$1,500", "$1,200", "$2,400", "$3,000"],
    correct: 1,
    explanation:
      "Cost = 12,000 ÷ 1.25 = 9,600, so profit in the transfer is 2,400, and half is still in inventory: $1,200. $2,400 adjusts for ALL the goods rather than those still held, while $1,500 and $3,000 treat the 25% mark-up as a margin on the selling price.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FA2-G-07",
    paper: "FA",
    area: "G",
    type: "mcq",
    stem: "Puffin plc owns 75% of Skylark Ltd. Puffin's retained earnings are $80,000. Skylark's retained earnings were $30,000 at acquisition and are $50,000 at the reporting date. What are consolidated retained earnings?",
    options: ["$95,000", "$130,000", "$117,500", "$100,000"],
    correct: 0,
    explanation:
      "Consolidated retained earnings = parent's 80,000 + group share of POST-acquisition growth: 75% × (50,000 − 30,000) = $95,000. $130,000 adds all of Skylark's earnings, $117,500 takes 75% of the TOTAL rather than the post-acquisition part, and $100,000 forgets to apply the 75% share.",
    marks: 2,
    difficulty: "hard",
  },

  /* ───────────── Area H — Interpretation of financial statements ───────────── */
  {
    id: "FA2-H-01",
    paper: "FA",
    area: "H",
    type: "mcq",
    stem: "Which of the following ratios is a measure of an entity's short-term liquidity?",
    options: [
      "Gross profit margin",
      "Gearing ratio",
      "Quick (acid test) ratio",
      "Asset turnover",
    ],
    correct: 2,
    explanation:
      "The quick ratio tests whether liquid assets cover current liabilities. Gross margin measures profitability, gearing measures long-term capital structure, and asset turnover measures efficiency — mixing up the ratio families is the trap.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FA2-H-02",
    paper: "FA",
    area: "H",
    type: "mcq",
    stem: "Dunmore Trading has inventory $18,000, trade receivables $22,000, cash at bank $5,000 and current liabilities $25,000. What is the quick (acid test) ratio?",
    options: ["1.8", "1.08", "0.88", "1.6"],
    correct: 1,
    explanation:
      "Quick ratio excludes inventory: (22,000 + 5,000) ÷ 25,000 = 1.08. 1.8 includes inventory (that is the CURRENT ratio), 0.88 omits the bank balance, and 1.6 includes inventory while omitting bank.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA2-H-03",
    paper: "FA",
    area: "H",
    type: "mcq",
    stem: "Bexley plc has long-term borrowings of $60,000 and equity of $140,000. Using debt ÷ (debt + equity), what is the gearing ratio?",
    options: ["30%", "42.9%", "70%", "233%"],
    correct: 0,
    explanation:
      "Gearing = 60,000 ÷ 200,000 = 30%. 42.9% divides debt by equity only (the debt/equity variant, not what was asked), 70% measures the EQUITY proportion, and 233% inverts the fraction.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FA2-H-04",
    paper: "FA",
    area: "H",
    type: "mcq",
    stem: "Grange Wholesale's receivables collection period rose from 34 days to 55 days while revenue stayed broadly flat. What is the MOST likely explanation?",
    options: [
      "Customers are paying more quickly than before",
      "Weakening credit control over collections from customers",
      "The company is taking longer to pay its own suppliers",
      "A higher proportion of sales are being made for cash",
    ],
    correct: 1,
    explanation:
      "A longer collection period with flat revenue means cash is being collected from credit customers more slowly — weakening credit control. Faster payment would SHORTEN the period, supplier payments affect PAYABLES days, and more cash sales would reduce receivables days, not raise them.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FA2-H-05",
    paper: "FA",
    area: "H",
    type: "number",
    stem: "Weststar Foods has an inventory holding period of 60 days, a receivables collection period of 48 days and a payables payment period of 40 days. What is its cash operating cycle, in days?",
    numericAnswer: 68,
    explanation:
      "Cash operating cycle = inventory days + receivables days − payables days = 60 + 48 − 40 = 68 days. The trap is adding payables days instead of deducting them — credit from suppliers SHORTENS the cycle.",
    marks: 2,
    difficulty: "hard",
  },
]
