import type { AccaQuestion } from "@/lib/acca-content"

export const TX_OFFICIAL_QUESTIONS: AccaQuestion[] = [
  { id: "TX-A-O01", paper: "TX", area: "A", type: "mcq", stem: "Who retains primary legal responsibility for an accurate self-assessment return when a tax agent prepares it?", options: ["The agent only", "The taxpayer", "The software provider", "ACCA"], correct: 1, explanation: "An agent may prepare and submit information, but the taxpayer retains responsibility for the return and tax obligations.", marks: 2, difficulty: "easy" },
  { id: "TX-A-O02", paper: "TX", area: "A", type: "mcq", stem: "Which behaviour is tax evasion?", options: ["Claiming an available statutory allowance", "Deliberately omitting taxable cash receipts", "Choosing between two lawful reliefs", "Making a pension contribution"], correct: 1, explanation: "Deliberately concealing taxable receipts is illegal evasion. Legitimate claims and choices are tax planning.", marks: 2, difficulty: "easy" },
  { id: "TX-A-O03", paper: "TX", area: "A", type: "mcq", stem: "Which factor is relevant when reducing a behaviour-based tax penalty?", options: ["The taxpayer's favourite accounting software", "Whether disclosure was prompted and its quality", "The taxpayer's job title", "Whether tax rates later fall"], correct: 1, explanation: "Prompted or unprompted disclosure and the quality of help, information and access affect mitigation within the statutory range.", marks: 2, difficulty: "medium" },
  { id: "TX-G-O01", paper: "TX", area: "G", type: "mcq", stem: "What is the first version-control check before using a tax computation template?", options: ["Font size", "Applicable Finance Act and tax year", "Number of worksheets", "Client logo"], correct: 1, explanation: "Rates, thresholds and rules are period-specific; the Finance Act and tax year are controlling metadata.", marks: 2, difficulty: "easy" },
  { id: "TX-G-O02", paper: "TX", area: "G", type: "mcq", stem: "Which presentation best supports review of a tax liability?", options: ["One unexplained total", "A labelled proforma with cross-referenced workings, rates and dates", "Hidden formulas", "Narrative without numbers"], correct: 1, explanation: "A conventional, labelled and cross-referenced computation makes the basis and arithmetic auditable.", marks: 2, difficulty: "easy" },
  { id: "TX-G-O03", paper: "TX", area: "G", type: "mcq", stem: "A tax advice point should normally conclude with what?", options: ["A generic definition", "The practical action and relevant deadline", "A copied rate table", "No conclusion"], correct: 1, explanation: "Professional advice applies the rule and ends with the required action, amount or deadline.", marks: 2, difficulty: "medium" },
]
