import type { AccaQuestion } from "@/lib/acca-content"

/* BT bank wave 5 — 60 verified originals (2026-07-10).
 * Areas: A ×14, B ×16, C ×16, D ×14 (slight weight to people + governance).
 * Difficulty 24/27/9 (~40/45/15). Every distractor encodes a nameable
 * student confusion; explanations teach the rule and the trap.
 */

export const BT_WAVE2: AccaQuestion[] = [
  /* ───────────── Area A — Business organisation & environment ───────────── */
  {
    id: "BT2-A-01", paper: "BT", area: "A", type: "mcq",
    stem: "A registered charity runs free literacy classes for adults. Which of the following best describes its PRIMARY objective?",
    options: [
      "Maximising the wealth of its shareholders",
      "Generating profits for distribution to its members",
      "Furthering its charitable purpose within the funds available",
      "Minimising the level of service provided in order to cut costs",
    ],
    correct: 2,
    explanation: "A not-for-profit organisation exists to further its purpose (its beneficiaries), constrained by funding. It has no shareholders (that is a company objective), it does not distribute surpluses to members, and cutting service defeats its purpose — value for money means economy, efficiency AND effectiveness.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "BT2-A-02", paper: "BT", area: "A", type: "mcq",
    stem: "Two graphic designers start trading together as an ordinary (unlimited) partnership. Which statement about their liability for business debts is correct?",
    options: [
      "Their liability is limited to the capital each has invested",
      "They are personally liable without limit for the partnership's debts",
      "Only the senior partner is liable for the debts",
      "Their liability is capped at a fixed statutory amount",
    ],
    correct: 1,
    explanation: "Ordinary partners have unlimited personal liability, jointly with the other partners. Liability limited to capital invested describes a limited COMPANY (a separate legal person) — the classic confusion. There is no 'senior partner only' rule and no statutory cap.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "BT2-A-03", paper: "BT", area: "A", type: "mcq",
    stem: "An engineering consultancy overlays project managers across its functional departments, so staff work for both a functional head and a project manager. What is the main ADVANTAGE of this matrix structure?",
    options: [
      "It gives every employee a single, clear line of command",
      "It reduces administrative overheads",
      "It eliminates interpersonal conflict within teams",
      "It improves coordination and communication across functional boundaries",
    ],
    correct: 3,
    explanation: "A matrix mixes skills across functions, improving coordination and flexibility on multi-disciplinary work. The traps are the matrix's WEAKNESSES stated as strengths: it breaks the single line of command (dual bosses), it usually INCREASES admin cost and management time, and dual authority tends to create conflict, not remove it.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-A-04", paper: "BT", area: "A", type: "mcq",
    stem: "In a matrix organisation, an analyst receives conflicting instructions from her functional head and her project manager. Which classical (Fayol) principle of management is being violated?",
    options: [
      "Unity of command",
      "Span of control",
      "Division of work",
      "Esprit de corps",
    ],
    correct: 0,
    explanation: "Unity of command says each employee should receive orders from only ONE boss — exactly what a matrix breaks. Span of control is about HOW MANY subordinates a manager has (a different confusion), division of work is specialisation, and esprit de corps is team spirit.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-A-05", paper: "BT", area: "A", type: "mcq",
    stem: "A company narrows each manager's span of control (fewer direct reports) while total headcount stays the same. What happens to the shape of its organisation structure?",
    options: [
      "It becomes flatter, with fewer levels of hierarchy",
      "It becomes taller, with more levels of hierarchy",
      "It stays exactly the same shape",
      "It automatically becomes more decentralised",
    ],
    correct: 1,
    explanation: "Narrow spans mean each manager supervises fewer people, so more managerial layers are needed for the same headcount — a TALL structure. Students often invert the relationship (flat goes with WIDE spans). Centralisation is a separate dimension: it is about where decisions are made, not the shape of the chart.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "BT2-A-06", paper: "BT", area: "A", type: "mcq",
    stem: "A pension fund holds 12% of a listed company's shares but rarely engages with management. Under Mendelow's matrix, how should the board treat this stakeholder?",
    options: [
      "Keep informed",
      "Keep satisfied",
      "Manage closely as a key player",
      "Minimal effort",
    ],
    correct: 1,
    explanation: "High power (a 12% vote) + low interest (rarely engages) = KEEP SATISFIED: if provoked, its interest could awaken with real force. 'Keep informed' is the LOW-power/high-interest quadrant — the classic mix-up. 'Key player' requires high power AND high interest; 'minimal effort' requires low on both.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-A-07", paper: "BT", area: "A", type: "mcq",
    stem: "A local residents' group campaigns loudly against a factory's expansion plans but has no shareholding, contract or legal authority. Under Mendelow's matrix, the appropriate strategy is to:",
    options: [
      "Apply minimal effort",
      "Manage them closely as key players",
      "Keep them satisfied",
      "Keep them informed",
    ],
    correct: 3,
    explanation: "High interest + low power = KEEP INFORMED: communicate and explain, because although they cannot block decisions directly, they can lobby and influence more powerful stakeholders. 'Keep satisfied' is the mirror quadrant (high power/LOW interest) — the standard confusion. They are too interested for minimal effort and too weak to be key players.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-A-08", paper: "BT", area: "A", type: "mcq",
    stem: "The central bank raises interest rates sharply, increasing a retailer's borrowing costs and dampening consumer spending. In a PESTEL analysis this is classified as which factor?",
    options: [
      "Economic",
      "Political",
      "Legal",
      "Technological",
    ],
    correct: 0,
    explanation: "Interest rates, inflation, exchange rates and consumer demand are ECONOMIC variables. The trap is 'Political' because a public institution acts — but PESTEL classifies by the NATURE of the impact (cost of money, demand), not by who caused it. Nothing here is a law or a technology.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "BT2-A-09", paper: "BT", area: "A", type: "mcq",
    stem: "A life-insurance company notes that the average age of the population in its home market is rising steadily. In PESTEL terms this trend is:",
    options: [
      "An economic factor",
      "A political factor",
      "A social factor",
      "An environmental factor",
    ],
    correct: 2,
    explanation: "Demographics — age structure, population growth, lifestyle — sit under SOCIAL. Students pick 'economic' because ageing affects spending and pensions, but the underlying driver is a population characteristic. 'Environmental' in PESTEL means ecology/climate, not the general surroundings.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-A-10", paper: "BT", area: "A", type: "mcq",
    stem: "Parliament enacts a statute imposing heavy fines on companies that mishandle customers' personal data. For a PESTEL analysis of an online retailer, this NEW statute is best classified as:",
    options: [
      "Technological, because it concerns data",
      "Legal",
      "Political, because parliament passed it",
      "Social",
    ],
    correct: 1,
    explanation: "An enacted statute that companies must comply with is a LEGAL factor. The two traps: 'technological' (the subject matter is data, but the factor is the LAW about it) and 'political' (political factors are government policy, stability and attitudes — once a rule is on the statute book with sanctions, it is legal).",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-A-11", paper: "BT", area: "A", type: "mcq",
    stem: "Which of the following is NOT one of Porter's five competitive forces?",
    options: [
      "Threat of substitute products",
      "Bargaining power of suppliers",
      "Threat of new entrants",
      "Bargaining power of employees",
    ],
    correct: 3,
    explanation: "The five forces are: competitive rivalry, threat of new entrants, threat of substitutes, bargaining power of BUYERS, and bargaining power of SUPPLIERS. 'Employees' is the invented option — students accept it because labour can be seen as a supplier, but it is not one of Porter's named forces.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "BT2-A-12", paper: "BT", area: "A", type: "mcq",
    stem: "Two established budget airlines repeatedly undercut each other's fares and copy each other's new routes. Which of Porter's five forces does this behaviour illustrate?",
    options: [
      "Competitive rivalry among existing firms",
      "Threat of substitutes",
      "Bargaining power of buyers",
      "Threat of new entrants",
    ],
    correct: 0,
    explanation: "Price wars and imitation between firms ALREADY in the industry are competitive rivalry. Substitutes would be a different way of meeting the need (e.g. rail travel); new entrants would be firms not yet in the market; buyer power is customers forcing prices down through their bargaining position, not firms competing.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "BT2-A-13", paper: "BT", area: "A", type: "mcq",
    stem: "A small dairy farmer sells 90% of her output to one national supermarket chain, which dictates prices and payment terms. From the FARMER'S perspective, which of Porter's forces does the supermarket's behaviour represent?",
    options: [
      "Bargaining power of suppliers",
      "Competitive rivalry",
      "Bargaining power of buyers",
      "Threat of substitutes",
    ],
    correct: 2,
    explanation: "The supermarket is the farmer's CUSTOMER, so its dominance is buyer power — high because purchases are concentrated in one buyer who could easily switch. The classic trap is 'supplier power' because the farmer IS a supplier: but the forces are always analysed from the perspective of the business doing the analysis, and the party squeezing her is a buyer.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "BT2-A-14", paper: "BT", area: "A", type: "mcq",
    stem: "A head-office team designs the standard costing procedures and quality manuals that every factory must follow, but produces no output itself. In Mintzberg's model of organisational building blocks, this team is part of the:",
    options: [
      "Operating core",
      "Technostructure",
      "Support staff",
      "Middle line",
    ],
    correct: 1,
    explanation: "The technostructure comprises analysts who STANDARDISE others' work — planners, systems designers, standard-setters. It is not the operating core (which does the productive work), not support staff (services like catering or legal that do not standardise anything — the subtle trap), and not the middle line (managers linking apex to core).",
    marks: 2, difficulty: "hard",
  },

  /* ───────────── Area B — People in organisations ───────────── */
  {
    id: "BT2-B-01", paper: "BT", area: "B", type: "mcq",
    stem: "Which of the following activities is most closely associated with LEADERSHIP, as distinct from management?",
    options: [
      "Preparing the departmental budget",
      "Monitoring actual results against the plan",
      "Creating and communicating a vision for change",
      "Scheduling the weekly staff rota",
    ],
    correct: 2,
    explanation: "Leadership is about direction, vision and inspiring commitment; management is about planning, organising and controlling within that direction. Budgets, monitoring and rotas are all classic MANAGEMENT (control/administration) activities — the trap is treating any senior activity as 'leadership'.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "BT2-B-02", paper: "BT", area: "B", type: "mcq",
    stem: "A warehouse manager times every task with a stopwatch, prescribes 'one best way' to perform each job, and pays workers per unit processed. Whose theory is he applying?",
    options: [
      "F.W. Taylor (scientific management)",
      "Elton Mayo (human relations)",
      "Frederick Herzberg (two-factor theory)",
      "Abraham Maslow (hierarchy of needs)",
    ],
    correct: 0,
    explanation: "Work study, the 'one best way' and piece-rate pay are the signature of Taylor's scientific management, which assumes workers are motivated mainly by money. Mayo is the opposite emphasis (social needs and attention), Herzberg separates hygiene factors from motivators, and Maslow ranks needs — none prescribe stopwatch-and-piece-rate methods.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-B-03", paper: "BT", area: "B", type: "mcq",
    stem: "In a famous series of studies, workers' productivity rose whether lighting was improved OR worsened, apparently because researchers were paying attention to them. Which theorist's work does this describe?",
    options: [
      "F.W. Taylor",
      "Victor Vroom",
      "Abraham Maslow",
      "Elton Mayo",
    ],
    correct: 3,
    explanation: "This is the Hawthorne effect from Mayo's studies: social factors and attention influenced output more than physical conditions, founding the human relations school. Taylor would predict output depends on method and pay (the opposite conclusion), Vroom's expectancy theory is about rational calculation, and Maslow proposed the needs hierarchy, not the Hawthorne experiments.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-B-04", paper: "BT", area: "B", type: "mcq",
    stem: "Rumours of redundancies are circulating and staff have become preoccupied with whether they will keep their jobs. In Maslow's hierarchy, which level of need is dominating their behaviour?",
    options: [
      "Physiological needs",
      "Safety (security) needs",
      "Esteem needs",
      "Self-actualisation",
    ],
    correct: 1,
    explanation: "Job security, stability and freedom from threat are SAFETY needs — the second level. Physiological needs (the base) are food, rest and shelter; picking it because it is 'the bottom of the pyramid' is the trap. Esteem is recognition and status; self-actualisation is fulfilling one's potential.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "BT2-B-05", paper: "BT", area: "B", type: "mcq",
    stem: "A firm raised all salaries by 10%. Complaints about pay stopped, but effort and engagement did not improve at all. How does Herzberg's two-factor theory explain this?",
    options: [
      "Salary is a motivator that was applied in the wrong amount",
      "Salary has low valence for these employees",
      "Salary is a hygiene factor: fixing it removes dissatisfaction but does not motivate",
      "Salary is an esteem need, so only recognition would have worked",
    ],
    correct: 2,
    explanation: "Herzberg classifies pay as a HYGIENE factor: getting it right prevents dissatisfaction, but only motivators (achievement, recognition, the work itself, responsibility, advancement) create positive motivation. Calling salary a motivator is the classic trap; 'valence' belongs to Vroom's theory and 'esteem needs' to Maslow — wrong framework, not just wrong answer.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-B-06", paper: "BT", area: "B", type: "mcq",
    stem: "According to Herzberg's two-factor theory, which of the following is a MOTIVATOR rather than a hygiene factor?",
    options: [
      "Pleasant working conditions",
      "Job security",
      "Fair company policy and administration",
      "Recognition for achievement",
    ],
    correct: 3,
    explanation: "Motivators relate to the CONTENT of the job: achievement, recognition, the work itself, responsibility, advancement and growth. Working conditions, job security and company policy all relate to the job's CONTEXT — hygiene factors whose absence causes dissatisfaction but whose presence does not motivate.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "BT2-B-07", paper: "BT", area: "B", type: "mcq",
    stem: "A salesperson is confident that extra effort will hit the bonus target, and trusts that the bonus will be paid — but she attaches no value to the bonus itself (she would rather have time off). What does Vroom's expectancy theory predict about her motivation?",
    options: [
      "It will be effectively zero, because the elements multiply and valence is zero",
      "It will be high, because expectancy is high",
      "It will be moderate, the average of the three elements",
      "It will be high, because the reward is guaranteed to be delivered",
    ],
    correct: 0,
    explanation: "Vroom: Force = Valence x Expectancy — the terms MULTIPLY, so if any element is zero, motivation is zero. The traps all treat the model as additive or as driven by one element alone: high expectancy cannot compensate for a worthless reward, there is no 'averaging', and a guaranteed but unvalued reward still motivates nobody.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "BT2-B-08", paper: "BT", area: "B", type: "mcq",
    stem: "A team member constantly produces highly original, unorthodox ideas but is poor at follow-through and communicates awkwardly. Which Belbin team role does this describe?",
    options: [
      "Shaper",
      "Plant",
      "Completer-Finisher",
      "Resource Investigator",
    ],
    correct: 1,
    explanation: "This is the Plant: the creative ideas generator, often introverted, weak on detail and communication. The Shaper drives the team through pressure (dynamism, not ideas); the Completer-Finisher is the detail-focused opposite of this profile; the Resource Investigator is the OTHER 'ideas' role, but sources ideas externally through contacts rather than generating them internally.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "BT2-B-09", paper: "BT", area: "B", type: "mcq",
    stem: "An outgoing team member is brilliant at developing external contacts and bringing back opportunities, but loses enthusiasm once initial excitement fades. Which Belbin role is this?",
    options: [
      "Plant",
      "Coordinator",
      "Teamworker",
      "Resource Investigator",
    ],
    correct: 3,
    explanation: "The Resource Investigator is the extroverted explorer of external contacts whose known weakness is losing interest after the initial burst. The trap is the Plant — the other 'ideas' role — but the Plant generates original ideas internally and is typically introverted. The Coordinator chairs and delegates; the Teamworker smooths relationships inside the team.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-B-10", paper: "BT", area: "B", type: "mcq",
    stem: "A team member is dynamic, thrives on pressure, and pushes the team past obstacles — but sometimes offends colleagues in the process. Which Belbin role does this describe?",
    options: [
      "Shaper",
      "Coordinator",
      "Implementer",
      "Monitor-Evaluator",
    ],
    correct: 0,
    explanation: "The Shaper is the challenging, driving role whose allowable weakness is provoking or offending others. The confusion is with the Coordinator, the OTHER leadership-flavoured role — but the Coordinator leads calmly by clarifying goals and delegating. The Implementer turns plans into action; the Monitor-Evaluator judges options dispassionately.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-B-11", paper: "BT", area: "B", type: "mcq",
    stem: "Two weeks after a project team is formed, members are openly arguing about roles, challenging the appointed leader and pushing their own agendas. Which Tuckman stage is the team in?",
    options: [
      "Forming",
      "Norming",
      "Storming",
      "Performing",
    ],
    correct: 2,
    explanation: "Open conflict over roles, leadership and ways of working is STORMING. Forming is the polite, cautious first stage (the trap: 'the team is new, so it must be forming' — but conflict has already broken out). Norming is when standards settle; performing is full productive maturity.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "BT2-B-12", paper: "BT", area: "B", type: "mcq",
    stem: "The conflict in a project team has died down: members have agreed ground rules and settled into roles, and cohesion is building — but output is not yet at full capacity. Which Tuckman stage is this?",
    options: [
      "Performing",
      "Norming",
      "Forming",
      "Adjourning",
    ],
    correct: 1,
    explanation: "Settling standards, roles and cohesion AFTER conflict is NORMING. The trap is 'performing' — but performing is only reached when the team is fully focused on delivering results at capacity, which the stem rules out. Forming precedes the conflict; adjourning is the break-up stage at the end.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-B-13", paper: "BT", area: "B", type: "mcq",
    stem: "In a 360-degree appraisal, an employee's performance feedback is gathered from:",
    options: [
      "The employee's own self-assessment only",
      "The line manager only",
      "An external assessment centre",
      "The manager, peers, subordinates and sometimes customers",
    ],
    correct: 3,
    explanation: "'360-degree' means feedback from all around the employee: superior, peers, direct reports, self, and sometimes customers. Manager-only is the traditional top-down appraisal; self-assessment alone and assessment centres are different techniques (assessment centres are mainly used for selection and development, not all-round appraisal).",
    marks: 2, difficulty: "easy",
  },
  {
    id: "BT2-B-14", paper: "BT", area: "B", type: "mcq",
    stem: "In systematic training, a 'training needs analysis' identifies:",
    options: [
      "The gap between the competences the job requires and those the employee currently has",
      "The list of courses employees would most like to attend",
      "The size of last year's training budget",
      "The employee's overall rating in the last appraisal",
    ],
    correct: 0,
    explanation: "A training need = required competence minus current competence; training is then designed to close the gap. Course wish-lists confuse wants with needs, budgets measure spend rather than need, and an appraisal rating may INPUT to the analysis but is not itself the identified gap.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-B-15", paper: "BT", area: "B", type: "mcq",
    stem: "A supervisor coordinates five clerks performing a simple, routine data-entry task where speed matters most. Which communication network will produce the fastest, most efficient results?",
    options: [
      "The all-channel network, because everyone can talk to everyone",
      "The circle, because information flows evenly",
      "The wheel, with the supervisor at the centre",
      "No network is faster than any other for simple tasks",
    ],
    correct: 2,
    explanation: "For SIMPLE tasks the centralised wheel is fastest: everything routes through the hub, minimising coordination time (at the cost of low satisfaction at the rim). The all-channel network is superior for COMPLEX problems — the reversal students make — but is slower for routine work. The circle is the slowest and least accurate of the classic networks.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "BT2-B-16", paper: "BT", area: "B", type: "mcq",
    stem: "A finance trainee's professional exam is eight weeks away: preparing is important but not yet urgent, while her inbox fills daily with urgent but trivial requests. According to time-management principles, what should she do with the exam preparation?",
    options: [
      "Deal with it only when it finally becomes urgent",
      "Schedule regular, protected time for it now, before it becomes urgent",
      "Delegate it, since it is not urgent",
      "Handle it immediately, ahead of every other task on the list",
    ],
    correct: 1,
    explanation: "Important/not-urgent tasks should be SCHEDULED — that is where planned, high-value work lives. Waiting until it is urgent is the firefighting trap; delegation suits urgent-but-UNIMPORTANT work (and you cannot delegate your own exam); and 'do immediately, ahead of everything' confuses importance with urgency in the other direction.",
    marks: 2, difficulty: "hard",
  },

  /* ─────── Area C — Governance, ethics & professional behaviour ─────── */
  {
    id: "BT2-C-01", paper: "BT", area: "C", type: "mcq",
    stem: "Why does the 'agency problem' arise mainly in large listed companies rather than in small owner-managed businesses?",
    options: [
      "Because listed companies employ far more staff",
      "Because listed companies pay more tax",
      "Because ownership (shareholders) is separated from control (directors)",
      "Because listed companies earn larger profits",
    ],
    correct: 2,
    explanation: "In a listed company, dispersed shareholders own the business but professional directors control it — the agents may pursue their own interests. In an owner-managed business, owner and manager are the same person, so no agency gap exists. Headcount, tax and profit levels are irrelevant to the concept.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "BT2-C-02", paper: "BT", area: "C", type: "mcq",
    stem: "Shareholders of a listed company bear the cost of an annual external audit partly so that directors' stewardship can be independently checked. In agency theory, this cost is an example of:",
    options: [
      "A monitoring cost incurred to reduce the agency problem",
      "An agency benefit",
      "A bonding cost incurred by the directors",
      "A residual loss",
    ],
    correct: 0,
    explanation: "Costs the PRINCIPAL bears to observe and verify the agent's behaviour (audits, reporting, board oversight) are monitoring costs. Bonding costs are the mirror image — incurred by the AGENT to reassure principals (the nameable trap). Residual loss is the value still lost despite monitoring and bonding; 'agency benefit' is not a term in the model.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-C-03", paper: "BT", area: "C", type: "mcq",
    stem: "A listed company appoints several directors who have no operational role and no other connection with the business. What is the PRIMARY contribution these non-executive directors (NEDs) make to governance?",
    options: [
      "Running day-to-day operations alongside the executives",
      "Providing independent scrutiny and challenge of executive decisions",
      "Representing the employees' interests on the board",
      "Guaranteeing that the company will remain profitable",
    ],
    correct: 1,
    explanation: "NEDs bring independent judgement: they scrutinise executive performance, challenge strategy and staff the key oversight committees. Running operations is precisely what they must NOT do (that is the executives' role); they are not employee representatives (a works-council confusion); and no director can guarantee profits.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-C-04", paper: "BT", area: "C", type: "mcq",
    stem: "Which of the following is a core responsibility of a listed company's AUDIT committee?",
    options: [
      "Overseeing the integrity of financial reporting and the relationship with the external auditor",
      "Setting the remuneration packages of executive directors",
      "Leading the process for appointing new directors",
      "Preparing the annual financial statements",
    ],
    correct: 0,
    explanation: "The audit committee (of independent NEDs) oversees financial reporting integrity, internal control and internal audit, and manages the external auditor relationship. Executive pay belongs to the REMUNERATION committee, appointments to the NOMINATION committee, and preparing the statements is MANAGEMENT'S job — the committee reviews, it does not prepare.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-C-05", paper: "BT", area: "C", type: "mcq",
    stem: "Best practice requires executive directors' pay to be set by a remuneration committee of independent non-executive directors. The MAIN reason is that this:",
    options: [
      "Ensures pay is set by the people who know market rates best",
      "Is cheaper than using pay consultants",
      "Prevents executives from setting their own pay — a clear conflict of interest",
      "Complies with a legal requirement that shareholders set pay directly",
    ],
    correct: 2,
    explanation: "Nobody should decide their own reward: an independent committee removes the self-interest conflict of executives fixing their own packages. NED market knowledge and cost are incidental, and the law does not require shareholders to set pay directly — shareholders typically get a VOTE on remuneration policy, which is different.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "BT2-C-06", paper: "BT", area: "C", type: "mcq",
    stem: "A listed company's board delegates the search for a new finance director, and longer-term board succession planning, to a committee. Which committee is this?",
    options: [
      "The audit committee",
      "The remuneration committee",
      "The risk committee",
      "The nomination committee",
    ],
    correct: 3,
    explanation: "The nomination committee leads board appointments and succession planning, recommending candidates to the full board. The audit committee oversees reporting and control, the remuneration committee sets executive pay, and a risk committee oversees risk appetite and management — students often blur the three statutory-style committees, so anchor each to its verb: audit = oversee reporting; remuneration = set pay; nomination = appoint.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-C-07", paper: "BT", area: "C", type: "mcq",
    stem: "A listed company is subject to a 'comply or explain' corporate governance code and chooses NOT to follow one of its provisions. What must the company do?",
    options: [
      "Nothing — such codes are voluntary and carry no obligations at all",
      "Comply anyway, because every provision of the code is legally binding",
      "Disclose the non-compliance and explain its reasons to shareholders",
      "Apply to delist from the stock exchange",
    ],
    correct: 2,
    explanation: "'Comply or explain' means a company may depart from a provision, but must disclose the departure and justify it, letting shareholders judge. The two traps are the extremes: treating the code as pure law (provisions are not statute) or as consequence-free (listing rules DO require the comply-or-explain statement). Delisting is never required.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "BT2-C-08", paper: "BT", area: "C", type: "mcq",
    stem: "A trainee accountant is instructed to sign a progress report that she knows materially overstates what has been completed. Signing it would most directly breach which fundamental ethical principle?",
    options: [
      "Integrity",
      "Objectivity",
      "Confidentiality",
      "Professional competence and due care",
    ],
    correct: 0,
    explanation: "Integrity requires being straightforward and honest, and not being associated with information known to be false or misleading — exactly this situation. Objectivity is about bias and conflicts of interest (no conflict is described), confidentiality about disclosing information, and competence about having the skills to do the work.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "BT2-C-09", paper: "BT", area: "C", type: "mcq",
    stem: "An accountant is scoring supplier tenders for a major contract. She realises one of the bidding companies is owned by her brother, but says nothing and continues scoring. Which fundamental principle is threatened?",
    options: [
      "Confidentiality",
      "Integrity",
      "Professional behaviour",
      "Objectivity",
    ],
    correct: 3,
    explanation: "A family connection to a bidder creates a conflict of interest that may bias her judgement — a threat to OBJECTIVITY, which requires freedom from bias and undue influence. The trap is 'integrity': she has not (yet) been dishonest; the issue is the unmanaged conflict, not a lie. Confidentiality and professional behaviour are not engaged by these facts.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-C-10", paper: "BT", area: "C", type: "mcq",
    stem: "At a party, a trainee accountant tells friends that a well-known client of his firm is about to announce a takeover that is not yet public. Which fundamental principle has he breached?",
    options: [
      "Objectivity",
      "Professional competence and due care",
      "Confidentiality",
      "Integrity",
    ],
    correct: 2,
    explanation: "Confidentiality prohibits disclosing information acquired through professional work without authority — including casual social disclosure, which is the most commonly examined form. No bias (objectivity), lack of skill (competence) or dishonesty to a party (integrity) is described; the wrong act is the disclosure itself.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "BT2-C-11", paper: "BT", area: "C", type: "mcq",
    stem: "A sole practitioner accepts a complex cross-border tax engagement despite having no experience in the area and no plan to obtain expert support. Which fundamental principle is most directly threatened?",
    options: [
      "Integrity",
      "Professional behaviour",
      "Confidentiality",
      "Professional competence and due care",
    ],
    correct: 3,
    explanation: "Competence and due care requires accountants to take on only work they can perform to the required standard — or to obtain appropriate expertise. Taking unfamiliar work with no support fails this directly. It only becomes an integrity issue if he misrepresents his ability; professional behaviour and confidentiality are not the primary principles engaged.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-C-12", paper: "BT", area: "C", type: "mcq",
    stem: "A qualified accountant, outside work and with no client involved, repeatedly behaves abusively at public industry events, attracting press coverage that reflects badly on accountants generally. Which fundamental principle does this engage?",
    options: [
      "Professional behaviour",
      "Objectivity",
      "Confidentiality",
      "Professional competence and due care",
    ],
    correct: 0,
    explanation: "Professional behaviour requires compliance with laws and regulations AND avoiding any conduct that discredits the profession — including conduct outside client work. The other principles do not fit: no bias in judgement (objectivity), no disclosure of information (confidentiality), and no question of technical skill (competence).",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-C-13", paper: "BT", area: "C", type: "mcq",
    stem: "A finance director tells the financial accountant that unless she reclassifies certain expenses as assets, she 'should start looking for another job'. In the ethical threats framework, this pressure is primarily:",
    options: [
      "A self-review threat",
      "A familiarity threat",
      "An intimidation threat",
      "An advocacy threat",
    ],
    correct: 2,
    explanation: "Actual or threatened pressure from another party — here, the threat of dismissal — is an INTIMIDATION threat. Students often label it self-interest because her job is at stake, but the defining feature is coercion by someone else. Self-review is checking one's own prior work; familiarity is closeness eroding scepticism; advocacy is promoting a client's position.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-C-14", paper: "BT", area: "C", type: "mcq",
    stem: "An internal auditor is assigned to review the purchasing controls of a department run by a close friend of fifteen years. He assures himself that his friend 'would never allow anything improper'. Which ethical threat is at work?",
    options: [
      "Advocacy threat",
      "Familiarity threat",
      "Self-review threat",
      "Intimidation threat",
    ],
    correct: 1,
    explanation: "A long, close relationship making him too sympathetic and insufficiently sceptical is the FAMILIARITY threat. It is not self-review (he is not checking his OWN previous work — the common mislabel), not advocacy (he is not promoting anyone's position), and no one is pressuring him (intimidation).",
    marks: 2, difficulty: "hard",
  },
  {
    id: "BT2-C-15", paper: "BT", area: "C", type: "mcq",
    stem: "A distinguishing obligation of the accountancy profession — compared with an ordinary trade — is its duty to act in:",
    options: [
      "The interests of the employer alone",
      "The interests of shareholders alone",
      "The public interest",
      "The financial interest of its own members",
    ],
    correct: 2,
    explanation: "Professional accountants accept responsibility to the PUBLIC interest — the wider community that relies on trustworthy financial information — not merely to an employer, a client, shareholders or themselves. This public-interest duty is why the profession is self-regulating with an ethical code.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "BT2-C-16", paper: "BT", area: "C", type: "mcq",
    stem: "Which of the following best defines corporate governance?",
    options: [
      "The system by which companies are directed and controlled",
      "The process of maximising short-term profit for shareholders",
      "The preparation of statutory accounts on time",
      "The day-to-day management of operations by executives",
    ],
    correct: 0,
    explanation: "The classic (Cadbury) definition: corporate governance is the system by which companies are DIRECTED and CONTROLLED — how power over the company is exercised and made accountable. It is broader than profit-seeking or compliance filing, and it sits ABOVE day-to-day management: governance oversees managers, it is not the managing itself.",
    marks: 2, difficulty: "easy",
  },

  /* ── Area D — Accounting, internal control & technology ── */
  {
    id: "BT2-D-01", paper: "BT", area: "D", type: "mcq",
    stem: "Each month, the finance team prepares cost-variance reports to help production managers control spending. This output is an example of:",
    options: [
      "Financial accounting",
      "Management accounting",
      "External auditing",
      "Treasury management",
    ],
    correct: 1,
    explanation: "Internal reports produced to help managers plan, control and decide are MANAGEMENT accounting — unregulated in format and forward/control-focused. Financial accounting produces statutory statements for EXTERNAL users (the classic confusion); external audit gives an opinion on those statements; treasury manages cash and funding.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "BT2-D-02", paper: "BT", area: "D", type: "mcq",
    stem: "A monthly bank reconciliation uncovers an unauthorised payment three weeks after it was made. In internal-control terms, the reconciliation is best described as a:",
    options: [
      "Preventive control",
      "Corrective control",
      "Physical control",
      "Detective control",
    ],
    correct: 3,
    explanation: "Reconciliations identify errors and irregularities AFTER they occur — detective controls. Students call any 'good' control preventive, but prevention stops the event happening in the first place (e.g. authorisation before payment). Corrective controls fix the consequences once found; physical controls restrict access to assets.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-D-03", paper: "BT", area: "D", type: "mcq",
    stem: "A company requires a manager's authorisation before any purchase order over $5,000 can be placed. This is an example of which type of internal control?",
    options: [
      "Detective control",
      "Preventive control",
      "Corrective control",
      "Compensating control",
    ],
    correct: 1,
    explanation: "Authorisation stops improper transactions BEFORE they happen — the definition of a preventive control. Detective controls (e.g. reconciliations) find problems after the event, corrective controls remedy them, and compensating controls make up for a weakness elsewhere in the system.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "BT2-D-04", paper: "BT", area: "D", type: "mcq",
    stem: "In a small company, one clerk raises purchase orders, receives the goods AND approves the supplier invoices for payment. Which internal control principle is missing?",
    options: [
      "Physical controls over assets",
      "Arithmetic and accounting checks",
      "Segregation of duties",
      "Personnel controls (recruitment vetting)",
    ],
    correct: 2,
    explanation: "One person handling ordering, receipt and approval end-to-end could order goods for himself and approve payment unnoticed — the risk that SEGREGATION OF DUTIES exists to prevent, by splitting stages of a transaction between people. Authorisation happens (he approves), so the failure is WHO approves, not whether approval exists; the other options address different risks.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "BT2-D-05", paper: "BT", area: "D", type: "mcq",
    stem: "For a fraud to occur, three conditions must generally be present. Which set correctly lists them?",
    options: [
      "Means, motive and alibi",
      "Greed, poverty and secrecy",
      "Collusion, pressure and weak auditing",
      "Dishonesty, opportunity and motive",
    ],
    correct: 3,
    explanation: "The BT model of fraud prerequisites is dishonesty (a person predisposed to act dishonestly), opportunity (weak controls allowing it) and motive (an incentive or pressure). 'Means, motive, alibi' is crime-fiction vocabulary; the other sets mix possible ingredients (collusion, pressure) with things that are neither necessary nor part of the model.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-D-06", paper: "BT", area: "D", type: "mcq",
    stem: "A company requires every finance employee to take at least two consecutive weeks' annual leave each year, with their duties performed by someone else in their absence. What is the main fraud-control purpose of this policy?",
    options: [
      "It prevents fraud by removing employees' motive",
      "It helps DETECT ongoing frauds that require continuous concealment, such as teeming and lading",
      "It is a corrective control that recovers losses already incurred",
      "It improves staff morale, reducing the temptation to steal",
    ],
    correct: 1,
    explanation: "Frauds like teeming and lading only survive while the fraudster continuously juggles the cover-up; forcing a substitute to perform the role exposes the scheme — a DETECTIVE mechanism. It does not remove motive or prevent a determined fraudster starting (prevention trap), recovers nothing (corrective trap), and any morale benefit is incidental, not the control objective.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "BT2-D-07", paper: "BT", area: "D", type: "mcq",
    stem: "A cashier steals a cheque received from customer A, then posts part of customer B's later receipt to A's account, and keeps rolling the shortfall forward to newer customers to hide it. This fraud is known as:",
    options: [
      "Teeming and lading",
      "Window dressing",
      "False invoicing",
      "Ghost employee (payroll) fraud",
    ],
    correct: 0,
    explanation: "Misappropriating customer receipts and concealing the theft by allocating LATER receipts to EARLIER accounts is teeming and lading. Window dressing manipulates the financial statements' appearance (not cash theft), false invoicing extracts payment against fictitious supplies, and ghost-employee fraud pays non-existent staff through payroll.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-D-08", paper: "BT", area: "D", type: "mcq",
    stem: "Which control would be MOST effective in preventing teeming and lading from starting in the first place?",
    options: [
      "Taking out fidelity insurance against employee theft",
      "Paying cashiers above-market salaries",
      "An annual visit by the external auditors",
      "Segregating cash receipt handling from posting to the receivables ledger",
    ],
    correct: 3,
    explanation: "Teeming and lading requires ONE person to both handle receipts and control the customer accounts used to hide the theft; segregating those duties removes the opportunity — prevention at source. Insurance is corrective (it compensates after loss), higher pay only weakens motive without closing the opportunity, and an annual external audit is an infrequent detective measure, not prevention.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "BT2-D-09", paper: "BT", area: "D", type: "mcq",
    stem: "An online store collected customers' email addresses solely for delivery notifications. It now keeps them indefinitely and uses them for unrelated third-party marketing. Which data protection principles is it breaching?",
    options: [
      "Accuracy and security",
      "Purpose limitation and storage limitation",
      "Lawful basis is irrelevant to marketing",
      "None — consent at collection covers all later uses",
    ],
    correct: 1,
    explanation: "Personal data must be used only for the purposes stated when collected (purpose limitation) and kept no longer than necessary for those purposes (storage limitation) — both breached here. The trap is thinking initial consent is a blank cheque for any future use: it is not. Accuracy and security are separate principles not described in the facts.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "BT2-D-10", paper: "BT", area: "D", type: "mcq",
    stem: "Unique user IDs, strong passwords and role-based permissions restricting who can view or amend the payroll system are examples of:",
    options: [
      "Logical access controls",
      "Physical access controls",
      "Output controls",
      "Corrective controls",
    ],
    correct: 0,
    explanation: "Software-enforced restrictions on system access — IDs, passwords, permission levels — are LOGICAL access controls. Physical access controls are tangible barriers (locked server rooms, swipe cards): the standard mix-up. Output controls govern distribution of reports; corrective controls fix problems after detection.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-D-11", paper: "BT", area: "D", type: "mcq",
    stem: "A supermarket's systems ingest and analyse point-of-sale transactions streaming in from hundreds of stores in real time. Which characteristic ('V') of big data does the real-time streaming BEST illustrate?",
    options: [
      "Volume",
      "Variety",
      "Veracity",
      "Velocity",
    ],
    correct: 3,
    explanation: "Velocity is the SPEED at which data is generated and must be processed — real-time streaming is its textbook illustration. The trap is Volume (there is certainly a lot of data, but the stem emphasises speed, not size). Variety refers to mixed data types and sources; veracity to the trustworthiness of the data.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "BT2-D-12", paper: "BT", area: "D", type: "mcq",
    stem: "A finance function is considering robotic process automation (RPA). Which task is the STRONGEST candidate for RPA?",
    options: [
      "Negotiating payment terms with a difficult key supplier",
      "High-volume, rule-based matching of supplier invoices to purchase orders",
      "Designing next year's business strategy",
      "Investigating a one-off, unstructured accounting discrepancy",
    ],
    correct: 1,
    explanation: "RPA excels at repetitive, high-volume tasks governed by clear rules — invoice matching is the classic case. The distractors all need human judgement, creativity or handling of unstructured novelty: negotiation, strategy design and one-off investigations are poor automation candidates precisely because no fixed rules describe them.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "BT2-D-13", paper: "BT", area: "D", type: "mcq",
    stem: "Staff receive an email that appears to come from the company's bank, asking them to click a link and 'confirm' their online banking login credentials. This attack is known as:",
    options: [
      "A denial-of-service attack",
      "A brute-force password attack",
      "Phishing",
      "A computer virus",
    ],
    correct: 2,
    explanation: "Deceptive messages impersonating a trusted party to trick users into revealing credentials are PHISHING — a social-engineering attack on people, not systems. Denial-of-service floods a system to make it unavailable, brute force tries passwords by repetition, and a virus is self-replicating malicious code; students often say 'virus' for any email threat.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "BT2-D-14", paper: "BT", area: "D", type: "mcq",
    stem: "The monthly board pack is thorough and error-free but consistently arrives three weeks after the month end — too late to influence the decisions it was meant to support. Which quality of good information is missing?",
    options: [
      "Accuracy",
      "Completeness",
      "Timeliness",
      "Cost-effectiveness",
    ],
    correct: 2,
    explanation: "Good information must arrive in time to be USED — information that is accurate but late loses its decision value. The stem deliberately confirms accuracy and completeness to force the distinction, and nothing suggests it costs more than the benefit it brings (cost-effectiveness).",
    marks: 2, difficulty: "medium",
  },
]
