import type { AccaQuestion } from "@/lib/acca-content"

export const PM_OFFICIAL_QUESTIONS: AccaQuestion[] = [
  { id: "PM-A-O01", paper: "PM", area: "A", type: "mcq", stem: "Which system is designed primarily to integrate finance, purchasing, inventory and operations around shared master data?", options: ["Transaction log", "ERP system", "Standalone spreadsheet", "Executive email"], correct: 1, explanation: "ERP integrates processes and data across functions. A transaction log records events but does not itself provide enterprise-wide integration.", marks: 2, difficulty: "easy" },
  { id: "PM-A-O02", paper: "PM", area: "A", type: "mcq", stem: "An analysis explains that delivery delays rose because a supplier changed and routing rules created congestion. Which analytical method is this?", options: ["Descriptive", "Diagnostic", "Predictive", "Prescriptive"], correct: 1, explanation: "Diagnostic analytics investigates why an observed result occurred. Descriptive reports what happened; predictive forecasts; prescriptive recommends action.", marks: 2, difficulty: "easy" },
  { id: "PM-A-O03", paper: "PM", area: "A", type: "mcq", stem: "Which control best protects a confidential performance dashboard using least privilege?", options: ["Give all managers administrator access", "Role-based access with authentication and logged review", "Email an unlocked copy monthly", "Hide the worksheet tabs"], correct: 1, explanation: "Role-based access, authentication and logs restrict and evidence access. Hidden tabs and emailed copies are weak controls.", marks: 2, difficulty: "medium" },
  { id: "PM-F-O01", paper: "PM", area: "F", type: "mcq", stem: "Which spreadsheet design provides the strongest audit trail?", options: ["Repeated hard-coded totals", "Inputs, workings and outputs separated with labelled formulas", "All formulas hidden", "One unlabeled worksheet"], correct: 1, explanation: "Separated, labelled inputs, workings and outputs let a reviewer trace and reproduce the calculation.", marks: 2, difficulty: "easy" },
  { id: "PM-F-O02", paper: "PM", area: "F", type: "mcq", stem: "A four-mark requirement asks for two implications of a variance. Which response is strongest?", options: ["A long definition of variance analysis", "Two scenario-linked points, each explaining cause and business consequence", "The variance number alone", "Four generic bullet headings"], correct: 1, explanation: "Application and consequence demonstrate analysis and make the available marks visible.", marks: 2, difficulty: "medium" },
  { id: "PM-F-O03", paper: "PM", area: "F", type: "mcq", stem: "What should be included in the final review of a digital PM response?", options: ["Only spelling", "Requirements, signs, units, formula logic, reconciliations and reasonableness", "Changing every formula to a value", "Removing all workings"], correct: 1, explanation: "A professional review checks technical completeness, presentation, traceability and reasonableness.", marks: 2, difficulty: "easy" },
]
