import type { AccaQuestion } from "@/lib/acca-content"

export const SBR_OFFICIAL_QUESTIONS: AccaQuestion[] = [
  { id: "SBR-A-O01", paper: "SBR", area: "A", type: "mcq", stem: "Management asks an accountant to omit a material climate-related impairment indicator to protect a bonus target. What is the best first response?", options: ["Comply because management prepares the statements", "Apply professional judgement, document the issue and challenge the proposed omission", "Wait until the external auditor finds it", "Omit it if no cash has yet been lost"], correct: 1, explanation: "The accountant must act with integrity and objectivity, assess the reporting requirements, document the evidence and challenge pressure to misstate corporate reports.", marks: 2, difficulty: "medium" },
  { id: "SBR-A-O02", paper: "SBR", area: "A", type: "mcq", stem: "Which consequence most directly follows from deliberately optimistic estimates used to overstate profit?", options: ["Improved faithful representation", "Reduced information risk for investors", "Misallocation of capital and loss of trust", "Automatic compliance with IFRS"], correct: 2, explanation: "Biased reporting can distort stakeholder decisions, undermine stewardship and trust, and expose the entity and professionals to regulatory and reputational consequences.", marks: 2, difficulty: "easy" },
  { id: "SBR-A-O03", paper: "SBR", area: "A", type: "mcq", stem: "A technically permitted presentation obscures a material transaction from users. What should an SBR answer emphasise?", options: ["Legal form alone", "Whether the report faithfully represents economic substance and serves users", "Management preference", "The absence of a numerical error only"], correct: 1, explanation: "Professional judgement goes beyond mechanical compliance and evaluates substance, neutrality, transparency and the information needs of primary users.", marks: 2, difficulty: "hard" },
  { id: "SBR-F-O01", paper: "SBR", area: "F", type: "mcq", stem: "Under IFRS Sustainability Disclosure Standards, which four content pillars organise disclosures about sustainability-related risks and opportunities?", options: ["Recognition, measurement, presentation, audit", "Governance, strategy, risk management, metrics and targets", "Profit, assets, liabilities, cash", "People, planet, profit, tax"], correct: 1, explanation: "IFRS S1 and IFRS S2 use governance, strategy, risk management, and metrics and targets as the core content architecture.", marks: 2, difficulty: "easy" },
  { id: "SBR-F-O02", paper: "SBR", area: "F", type: "mcq", stem: "What is the central purpose of IFRS S1?", options: ["To replace IFRS Accounting Standards", "To require decision-useful disclosure of sustainability-related risks and opportunities that could affect an entity's prospects", "To prescribe a single carbon tax", "To report only philanthropic spending"], correct: 1, explanation: "IFRS S1 establishes general requirements for sustainability-related financial disclosures useful to primary users when assessing prospects.", marks: 2, difficulty: "medium" },
  { id: "SBR-F-O03", paper: "SBR", area: "F", type: "mcq", stem: "Which comparison between ISSB Standards and ESRS is most defensible?", options: ["They are identical", "ISSB focuses on information material to investors, while ESRS also applies an impact-materiality perspective", "ESRS covers only cash flows", "ISSB prohibits climate disclosure"], correct: 1, explanation: "The regimes can overlap, but ESRS applies double materiality, including impacts on people and environment, while the ISSB baseline is oriented to investor decisions about enterprise prospects.", marks: 2, difficulty: "hard" },
  { id: "SBR-G-O01", paper: "SBR", area: "G", type: "mcq", stem: "What is the best first step when a spreadsheet adjustment and a narrative exhibit use different reporting dates?", options: ["Average the values", "Reconcile dates, definitions and entities before calculating", "Use the larger figure", "Ignore the narrative"], correct: 1, explanation: "Digital competence requires validating the basis of evidence before manipulating it; otherwise a polished calculation can be conceptually wrong.", marks: 2, difficulty: "medium" },
  { id: "SBR-G-O02", paper: "SBR", area: "G", type: "mcq", stem: "A requirement asks for advice to investors. Which response is most professional?", options: ["A list of standards", "A structured answer linking treatment, quantified effect and investor consequence", "Copied exhibit text", "Calculations without labels"], correct: 1, explanation: "Professional presentation connects technical analysis to the specified stakeholder, uses traceable workings and reaches a supported conclusion.", marks: 2, difficulty: "easy" },
  { id: "SBR-G-O03", paper: "SBR", area: "G", type: "mcq", stem: "When adjusting a consolidated statement in the exam spreadsheet, which practice best supports review?", options: ["Hard-code every total", "Use labelled, traceable workings and check that the statement remains internally consistent", "Hide assumptions", "Round before calculating"], correct: 1, explanation: "Clear labels, linked workings and reconciliation checks make adjustments accurate, reviewable and professionally presented.", marks: 2, difficulty: "medium" },
]
