/*
 * SBL bank wave S1 part A (areas A,B)
 * Paper: Strategic Business Leader (SBL)
 * Blueprint: Area A (Leadership & governance) 35, Area B (Strategy) 35 = 70 questions.
 *   Difficulty mix across 70: 20 easy / 32 medium / 18 hard (each area 10/16/9).
 *   Correct-option position balance across 70: index0 x18, index1 x18, index2 x17, index3 x17.
 * Date authored: 2026-07-13
 *
 * Originality & accuracy note: every organisation name and scenario in this file is
 * invented; no ACCA, Kaplan or BPP material is reproduced. Content is aligned only to the
 * public SBL syllabus. Every framework detail (Mendelow power-interest quadrants, the five
 * Porter forces, value-chain primary vs support activities, Ansoff/BCG/Bowman positions,
 * JSW suitability-acceptability-feasibility, Tucker's five questions, the AAA seven steps,
 * Kohlberg's three levels, Schein's three levels, Handy's four culture types, Carroll's
 * pyramid, the <IR> six capitals and UK Corporate Governance Code committee roles) was
 * verified for technical accuracy before writing. Each distractor encodes a nameable
 * conceptual error explained in teaching voice.
 */

import type { AccaQuestion } from "@/lib/acca-content"

export const SBL_WAVE1A: AccaQuestion[] = [
  /* ───── Area A — Leadership & governance (35) ───── */
  {
    id: "SBL2-A-01",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "Verano Retail plc is owned by thousands of shareholders but run by a salaried executive team. In agency theory, how is the relationship between the shareholders and the executives best described?",
    options: [
      "The executives are the principals and the shareholders are their agents.",
      "Both parties are joint principals, so no agency relationship exists.",
      "The shareholders are the principals and the executives are their agents.",
      "The shareholders are agents acting on behalf of the company's customers.",
    ],
    correct: 2,
    explanation:
      "In agency theory the principal delegates control to an agent: shareholders (principals) appoint directors (agents) to run the company for them. Reversing the roles misidentifies who delegates authority; the 'joint principals' option ignores the delegation that defines agency; and the customers option confuses stakeholders with the principal-agent relationship.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBL2-A-02",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "A company incorporated in the UK has a single board on which executive and non-executive directors sit together and share collective responsibility. What board structure is this?",
    options: [
      "A unitary board.",
      "A two-tier board.",
      "A supervisory board.",
      "A management board.",
    ],
    correct: 0,
    explanation:
      "A unitary board combines executive and non-executive directors on one board with collective legal responsibility, the model favoured in the UK. A two-tier structure (common in Germany) splits a supervisory board from a management board; naming only one of those tiers describes half of a structure the scenario explicitly rules out by placing everyone on a single board.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBL2-A-03",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "The UK Corporate Governance Code recommends a clear division of responsibilities at the head of a company. Which statement best reflects the principle behind separating the roles of chair and chief executive?",
    options: [
      "It ensures the chief executive can overrule the board whenever speed is required.",
      "It permits the same individual to hold both roles provided they are judged independent.",
      "It transfers responsibility for running the board to the external auditors.",
      "It prevents unfettered power residing with one person by separating running the board from running the business.",
    ],
    correct: 3,
    explanation:
      "The Code separates the chair (who runs the board) from the CEO (who runs the business) so no single person has unchallenged decision-making power. Allowing one person to hold both roles is exactly what the principle guards against; giving the CEO override power or handing board leadership to auditors both misstate where authority and monitoring should sit.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBL2-A-04",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "Which of the following is a core responsibility of a company's audit committee?",
    options: [
      "Setting the remuneration packages of the executive directors.",
      "Monitoring the integrity of the financial statements and overseeing the external auditor's independence.",
      "Leading the process for identifying and appointing new board members.",
      "Approving the company's annual marketing budget.",
    ],
    correct: 1,
    explanation:
      "The audit committee reviews the integrity of financial reporting, internal controls and risk, and oversees the external auditor's independence. Setting executive pay belongs to the remuneration committee and leading appointments to the nomination committee; approving a marketing budget is an operational management task, not a board-committee function.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-A-05",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "What is a primary purpose of appointing independent non-executive directors (NEDs) to a unitary board?",
    options: [
      "To take over day-to-day operational management from the executives.",
      "To guarantee that the company's share price rises every year.",
      "To provide independent judgement and constructively challenge the executive directors.",
      "To represent the interests of the company's single largest supplier.",
    ],
    correct: 2,
    explanation:
      "Independent NEDs bring objective external judgement and scrutinise and challenge executive decisions, strengthening board balance. Running daily operations is the executives' job; no director can guarantee share-price performance; and NEDs serve the company and its shareholders as a whole, not one supplier.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBL2-A-06",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "The remuneration committee of a listed company is designing pay for the executive directors. Which principle should guide it under good governance?",
    options: [
      "Executive pay should be set by the executives themselves to reflect their true worth.",
      "A significant proportion of pay should be linked to performance to align directors with long-term shareholder interests.",
      "Pay should be a fixed salary only, with no link to company performance.",
      "The committee should include executive directors so they can approve their own awards.",
    ],
    correct: 1,
    explanation:
      "Good governance links a meaningful share of executive reward to performance so incentives align with long-term shareholder value, with the committee staffed by independent NEDs. Letting executives set or approve their own pay creates an obvious conflict of interest, and a fixed-salary-only structure removes the alignment the committee exists to create.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-A-07",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "Which task falls within the remit of the nomination committee?",
    options: [
      "Reviewing the structure, size and composition of the board and leading the appointment of new directors.",
      "Determining the total remuneration package of the chief executive.",
      "Signing off the accuracy of the interim financial statements.",
      "Negotiating the terms of the company's bank borrowings.",
    ],
    correct: 0,
    explanation:
      "The nomination committee evaluates board balance and skills and leads the search for and recommendation of new appointments. Setting CEO pay is the remuneration committee's role, assuring the financial statements is the audit committee's, and negotiating debt is an operational treasury function, not a board-committee responsibility.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-A-08",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "Using Mendelow's power-interest matrix, a stakeholder with both high power and high interest in a strategic decision should be treated in which way?",
    options: [
      "Minimal effort.",
      "Kept informed.",
      "Kept satisfied.",
      "Managed closely as a key player.",
    ],
    correct: 3,
    explanation:
      "High power combined with high interest places a stakeholder in Mendelow's 'key players' quadrant, who must be managed closely and actively engaged. Minimal effort is for low-power/low-interest stakeholders, keep informed for low-power/high-interest, and keep satisfied for high-power/low-interest — each a different quadrant.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-A-09",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "A large institutional investor in Kestrel plc holds a major shareholding but has historically paid little attention to individual strategic proposals. Under Mendelow's matrix, how should the board manage this investor?",
    options: [
      "Manage them closely as a key player, involving them in every operational detail.",
      "Apply minimal effort, as they rarely engage with proposals.",
      "Keep them satisfied, because their high power could become active if their interest rises.",
      "Keep them informed only through general publications.",
    ],
    correct: 2,
    explanation:
      "The investor has high power (a major shareholding) but currently low interest, placing them in the 'keep satisfied' quadrant — their latent power means dissatisfaction could see them become active. Treating them as a key player overstates their current interest; minimal effort ignores their power; and 'keep informed' is the treatment for high-interest but low-power stakeholders.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBL2-A-10",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "Which of the following is an example of an internal stakeholder of a company?",
    options: [
      "A national government tax authority.",
      "An employee working in the company's operations team.",
      "A local community environmental pressure group.",
      "A trade supplier delivering raw materials.",
    ],
    correct: 1,
    explanation:
      "Employees are internal stakeholders — they work within and form part of the organisation. Tax authorities and community groups are external stakeholders, and suppliers are usually classified as connected stakeholders with a contractual link but sitting outside the organisation itself.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBL2-A-11",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "Under the Integrated Reporting <IR> Framework, an organisation reports on how it uses and affects several 'capitals'. Which of the following is one of the six capitals?",
    options: [
      "Natural capital.",
      "Political capital.",
      "Regulatory capital.",
      "Reputational capital.",
    ],
    correct: 0,
    explanation:
      "The six capitals in the <IR> Framework are financial, manufactured, intellectual, human, social and relationship, and natural. Political and regulatory capital are not part of the framework, and reputation, though important, is captured within social and relationship or intellectual capital rather than being a standalone capital.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-A-12",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "Tucker's five-question model gives a short test for the ethics of a business decision. Which of the following is one of the five questions?",
    options: [
      "Is it innovative?",
      "Is it popular with the media?",
      "Is it the cheapest option?",
      "Is it fair?",
    ],
    correct: 3,
    explanation:
      "Tucker asks whether a decision is profitable, legal, fair, right and sustainable; 'Is it fair?' is one of those five tests. Innovation, media popularity and cost minimisation are not part of the model, which deliberately balances profitability against legal, moral and environmental tests rather than commercial appeal.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-A-13",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "The American Accounting Association (AAA) model guides an accountant through an ethical dilemma. Which of the following best describes an early step in the model?",
    options: [
      "Immediately resign from the engagement before analysing anything.",
      "Establish the facts of the case.",
      "Calculate the tax saving arising from each option.",
      "Ask the client which outcome they would prefer.",
    ],
    correct: 1,
    explanation:
      "The AAA model begins by establishing the facts, then identifies the ethical issues, the relevant norms and principles, the alternative courses of action, the best option, the consequences and finally the decision. Resigning first skips the analysis, computing tax savings ignores the ethical dimension, and deferring to the client's preference abandons independent ethical judgement.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBL2-A-14",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "Kohlberg's theory of moral development identifies three broad levels of ethical reasoning. What are the three levels?",
    options: [
      "Legal, ethical and philanthropic.",
      "Artefacts, espoused values and basic assumptions.",
      "Pre-conventional, conventional and post-conventional.",
      "Self-interest, advocacy and intimidation.",
    ],
    correct: 2,
    explanation:
      "Kohlberg describes moral development moving through pre-conventional (self-interest, avoiding punishment), conventional (conforming to social and legal expectations) and post-conventional (universal ethical principles) levels. The other options belong to Carroll's CSR pyramid, Schein's model of culture and the ethical-threats taxonomy respectively.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-A-15",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "An accountant holds a significant number of shares in a company whose financial statements she is preparing. Which category of ethical threat does this create?",
    options: [
      "Self-interest threat.",
      "Advocacy threat.",
      "Intimidation threat.",
      "Familiarity threat.",
    ],
    correct: 0,
    explanation:
      "A financial interest such as a shareholding creates a self-interest threat, because the accountant could personally benefit from the numbers she reports. An advocacy threat arises from promoting a client's position, an intimidation threat from being pressured, and a familiarity threat from a close relationship — none of which is the driver where the issue is a personal financial stake.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBL2-A-16",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "Schein's model describes organisational culture as operating at three levels. Which of the following lists those three levels?",
    options: [
      "Power, role and task.",
      "Economic, legal and ethical.",
      "Suitability, acceptability and feasibility.",
      "Artefacts, espoused values and basic underlying assumptions.",
    ],
    correct: 3,
    explanation:
      "Schein distinguishes visible artefacts, espoused values (stated strategies and philosophies) and the deeper basic underlying assumptions that are taken for granted. The other options describe Handy's culture types, Carroll's CSR responsibilities and the JSW strategy-evaluation criteria — different frameworks entirely.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-A-17",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "In Handy's model of organisational culture, a small entrepreneurial firm is controlled tightly from the centre by a dominant founder, with few rules and rapid decisions radiating outward. Which culture type is this?",
    options: [
      "Role culture.",
      "Task culture.",
      "Power culture.",
      "Person culture.",
    ],
    correct: 2,
    explanation:
      "A power culture concentrates control in a central figure or small group, with influence radiating outward like a web and few procedural rules — typical of owner-dominated firms. A role culture is bureaucratic and rules-driven, a task culture is organised around project teams, and a person culture exists to serve the individuals within it.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-A-18",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "Which of the following is most clearly a symptom of poor corporate governance?",
    options: [
      "A board with a majority of independent non-executive directors.",
      "A dominant chief executive who also chairs the board and faces little challenge.",
      "An audit committee composed of independent NEDs.",
      "A clear separation between the roles of chair and chief executive.",
    ],
    correct: 1,
    explanation:
      "An unchallenged, dominant individual holding both the CEO and chair roles concentrates power and removes the checks good governance relies on — a classic governance weakness. The other options — independent NEDs, an independent audit committee and role separation — are all hallmarks of sound governance, not failures.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBL2-A-19",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "Shareholders incur costs in monitoring directors and aligning their behaviour with owners' interests. What are such costs known as in agency theory?",
    options: [
      "Agency costs.",
      "Sunk costs.",
      "Opportunity costs.",
      "Transaction costs.",
    ],
    correct: 0,
    explanation:
      "Agency costs arise from the separation of ownership and control, including monitoring directors and providing incentives to align their actions with shareholders. Sunk costs are unrecoverable past outlays, opportunity costs are benefits foregone from an alternative, and transaction costs relate to making an exchange — none captures the monitoring/alignment idea specific to the principal-agent problem.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-A-20",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "Under the UK Corporate Governance Code, which statement about the composition of the audit committee of a company that is not a smaller company is most accurate?",
    options: [
      "It should be chaired by the chief executive.",
      "It should consist mainly of executive directors.",
      "It may include the external audit engagement partner as a member.",
      "It should comprise at least three members, all independent non-executive directors.",
    ],
    correct: 3,
    explanation:
      "The Code expects the audit committee to have at least three members (two for a smaller company), all independent NEDs, to preserve objective oversight. A CEO chair or a committee of executives would undermine independence, and seating the external audit partner on the committee it oversees would be a direct conflict — the committee monitors the auditor, it does not include them.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBL2-A-21",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "What is the principal role of the chair of a company's board?",
    options: [
      "To manage the day-to-day running of the business.",
      "To lead the board and ensure its effectiveness.",
      "To act as the company's external auditor.",
      "To personally set the salaries of all staff.",
    ],
    correct: 1,
    explanation:
      "The chair leads the board, sets its agenda and ensures it operates effectively and receives accurate, timely information. Running the business day to day is the chief executive's responsibility; the external auditor is an independent outside party; and setting pay is a management or remuneration-committee matter, not the chair's personal role.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBL2-A-22",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "The term 'CEO duality' describes a situation that good governance codes generally discourage. What does it mean?",
    options: [
      "The company has two competing chief executives sharing the same role.",
      "The chief executive sits on two different companies' boards simultaneously.",
      "The same individual holds both the chief executive and the board chair positions.",
      "The chief executive is also employed by the company's external auditor.",
    ],
    correct: 2,
    explanation:
      "CEO duality means one person occupies both the chief executive and the chair roles, concentrating power in a way governance codes advise against. Two rival CEOs is not a recognised concept, sitting on multiple boards is a cross-directorship issue, and being employed by the auditor describes a different independence conflict altogether.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBL2-A-23",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "Which circumstance is most likely to compromise the independence of a non-executive director?",
    options: [
      "The NED was, until last year, a senior executive employed by the same company.",
      "The NED is a member of the audit committee.",
      "The NED asks challenging questions of the executive directors.",
      "The NED holds no shares in the company.",
    ],
    correct: 0,
    explanation:
      "Recent former employment by the company creates a familiarity and self-interest link that can undermine an NED's independence of judgement. Serving on the audit committee and challenging executives are exactly what independent NEDs are meant to do, and holding no shares generally supports rather than threatens independence.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-A-24",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "In a two-tier board structure of the kind found in Germany, what is the primary function of the supervisory board?",
    options: [
      "To manage the day-to-day operations of the business.",
      "To act as the company's independent external auditor.",
      "To prepare the financial statements for filing.",
      "To appoint, monitor and oversee the management board.",
    ],
    correct: 3,
    explanation:
      "In a two-tier system the supervisory board appoints and monitors the management board, providing oversight and representing shareholder (and often employee) interests, while the separate management board runs the business. Managing operations and preparing accounts are management-board functions, and auditing is performed by an independent external firm, not the supervisory board.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBL2-A-25",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "According to Mendelow's matrix, how should an organisation treat a stakeholder group with low power and low interest?",
    options: [
      "Keep them satisfied.",
      "Apply minimal effort.",
      "Manage them closely as key players.",
      "Keep them fully informed at all times.",
    ],
    correct: 1,
    explanation:
      "Low power combined with low interest places a stakeholder in the minimal-effort quadrant, requiring only limited monitoring. Keeping satisfied is for high-power/low-interest groups, managing closely for high-power/high-interest key players, and keeping informed for low-power/high-interest groups — none of which fits a group that is both uninterested and powerless.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-A-26",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "A community environmental group has strong interest in Solaris Energy's new plant but limited power to influence the decision. Under Mendelow's framework, the most appropriate approach is to:",
    options: [
      "Apply minimal effort, given their limited power.",
      "Manage them closely as key players.",
      "Keep them informed to reduce the risk they gain power by lobbying or forming coalitions.",
      "Keep them satisfied because of their high power.",
    ],
    correct: 2,
    explanation:
      "High interest but low power places the group in the 'keep informed' quadrant; engaging and informing them reduces the risk they build power through alliances or public campaigns. Minimal effort ignores their high interest, key-player treatment overstates their power, and 'keep satisfied' wrongly assumes they already hold significant power.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBL2-A-27",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "Carroll's pyramid of corporate social responsibility ranks four levels of responsibility. Which responsibility sits at the base of the pyramid as the foundation on which the others rest?",
    options: [
      "Economic responsibility — to be profitable.",
      "Philanthropic responsibility — to be a good corporate citizen.",
      "Legal responsibility — to obey the law.",
      "Ethical responsibility — to do what is right.",
    ],
    correct: 0,
    explanation:
      "Carroll places economic responsibility (being profitable) at the base, because a business must survive financially before it can meet the legal, ethical and philanthropic obligations built above it. Philanthropy sits at the top as discretionary, with legal and ethical responsibilities in between — so none of those forms the foundation.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-A-28",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "A key aim of an integrated report under the <IR> Framework is to explain which of the following?",
    options: [
      "Only the historical financial results for the year in isolation.",
      "How the organisation creates value over time across its financial and non-financial capitals.",
      "A detailed schedule of every employee's individual salary.",
      "The personal tax affairs of the individual directors.",
    ],
    correct: 1,
    explanation:
      "Integrated reporting communicates how an organisation creates and sustains value over the short, medium and long term using the six capitals, connecting financial and non-financial performance. Reporting historical financials alone misses the integrated, forward-looking value-creation story, while salary schedules and directors' personal tax are neither the focus nor the purpose of the report.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-A-29",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "Tucker's model tests whether a decision is legal, fair, right, sustainable and one further quality. Which is the fifth test?",
    options: [
      "Is it fashionable?",
      "Is it confidential?",
      "Is it complex?",
      "Is it profitable?",
    ],
    correct: 3,
    explanation:
      "Tucker's five tests are profitable, legal, fair, right and sustainable; profitability is the missing test here. Being fashionable, confidential or complex plays no part in the model, which pairs the commercial test of profitability with four moral and legal tests.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBL2-A-30",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "An audit senior has been the main contact on the same client engagement for over a decade and has become close friends with the client's finance director. Which ethical threat is most heightened?",
    options: [
      "Familiarity threat.",
      "Advocacy threat.",
      "Self-review threat.",
      "Intimidation threat.",
    ],
    correct: 0,
    explanation:
      "A long, close relationship with client staff creates a familiarity threat, where the auditor may become too sympathetic to the client's interests or too trusting of their representations. An advocacy threat comes from promoting the client's position, a self-review threat from checking one's own prior work, and an intimidation threat from being pressured — none of which is the core issue in a long, friendly association.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-A-31",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "A manager decides not to falsify a report solely because she is afraid of being caught and punished. In Kohlberg's terms, at which level of moral reasoning is she operating?",
    options: [
      "Post-conventional level.",
      "Conventional level.",
      "Pre-conventional level.",
      "Supra-conventional level.",
    ],
    correct: 2,
    explanation:
      "Acting only to avoid punishment is characteristic of Kohlberg's pre-conventional level, where morality is driven by self-interest and consequences to oneself. The conventional level is motivated by social approval and law, the post-conventional level by internalised universal principles, and 'supra-conventional' is not a level in the model.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBL2-A-32",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "A large, well-established government department operates through clearly defined job descriptions, rules, hierarchies and procedures. In Handy's model, which culture type does this represent?",
    options: [
      "Role culture.",
      "Power culture.",
      "Task culture.",
      "Person culture.",
    ],
    correct: 0,
    explanation:
      "A role culture is bureaucratic and built on rules, defined roles and hierarchy, typical of stable, large organisations such as government departments. A power culture centralises control with few rules, a task culture organises around project teams, and a person culture exists mainly to serve the professionals within it.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBL2-A-33",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "Why is an effective whistleblowing procedure considered an important element of good corporate governance?",
    options: [
      "It allows directors to award themselves higher bonuses.",
      "It removes the need for an external audit.",
      "It guarantees the company will never face any regulatory penalty.",
      "It provides a safe channel for employees to raise concerns about wrongdoing without fear of reprisal.",
    ],
    correct: 3,
    explanation:
      "Whistleblowing arrangements let employees report unethical or illegal behaviour confidentially and without retaliation, helping the board detect problems early. It has nothing to do with setting bonuses, does not replace the independent assurance an external audit provides, and cannot guarantee immunity from penalties — its value is early, safe disclosure.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-A-34",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "Meridian plc's board consists almost entirely of executive directors, with only one non-executive director who rarely attends. From a governance perspective, what is the most significant weakness of this structure?",
    options: [
      "The board is far too large to reach any decisions.",
      "There is insufficient independent challenge and oversight of executive decisions.",
      "The executives will lack the operational knowledge needed to run the company.",
      "The company will be legally prohibited from trading.",
    ],
    correct: 1,
    explanation:
      "A board dominated by executives with negligible independent input lacks the objective challenge and monitoring that independent NEDs provide, so executive decisions go largely unchecked. Board size is not the issue described, executives are precisely the people with operational knowledge, and such a structure is a governance weakness rather than an outright legal bar to trading.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBL2-A-35",
    paper: "SBL",
    area: "A",
    type: "mcq",
    stem: "The UK Corporate Governance Code operates on a 'comply or explain' basis. What does this mean?",
    options: [
      "Companies must comply with every provision and may never depart from any of them.",
      "Companies may ignore the Code entirely without any disclosure.",
      "Companies should comply with the Code's provisions or explain to shareholders why they have not.",
      "Only the external auditor decides whether the Code has been followed.",
    ],
    correct: 2,
    explanation:
      "'Comply or explain' means a company either follows the Code's provisions or discloses and justifies any departure, leaving shareholders to judge the explanation. It is deliberately not a rigid rulebook demanding absolute compliance, nor a free pass to ignore the Code silently, and it is the company (not the auditor) that must provide the explanation.",
    marks: 2,
    difficulty: "easy",
  },
  /* ───── Area B — Strategy (35) ───── */
  {
    id: "SBL2-B-01",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "The PESTEL framework is used to analyse the macro-environment. What do the letters of PESTEL stand for?",
    options: [
      "Product, Enterprise, Sales, Team, Efficiency, Logistics.",
      "Price, Employees, Systems, Tax, Ethics, Location.",
      "People, Efficiency, Structure, Technology, Economy, Law.",
      "Political, Economic, Social, Technological, Environmental, Legal.",
    ],
    correct: 3,
    explanation:
      "PESTEL stands for Political, Economic, Social, Technological, Environmental and Legal factors — the six categories of macro-environmental influence. The other options are invented expansions that mix internal and unrelated terms; PESTEL deliberately addresses external forces largely beyond the organisation's control.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBL2-B-02",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "How many competitive forces are included in Porter's model of industry analysis?",
    options: [
      "Four.",
      "Five.",
      "Six.",
      "Three.",
    ],
    correct: 1,
    explanation:
      "Porter's model comprises exactly five forces: threat of new entrants, bargaining power of suppliers, bargaining power of buyers, threat of substitutes and competitive rivalry. Four, six or three all miscount the framework, which is defined precisely by its five interacting forces.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBL2-B-03",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "In Porter's five forces, which factor tends to increase the bargaining power of buyers in an industry?",
    options: [
      "Buyers are few, large and purchase in high volumes, with low switching costs.",
      "There are many small buyers, each purchasing tiny quantities.",
      "Buyers face very high costs to switch to another supplier.",
      "The product is highly differentiated with no close substitutes.",
    ],
    correct: 0,
    explanation:
      "Buyer power rises when buyers are large, concentrated, buy in volume and can switch cheaply, giving them leverage over price and terms. Numerous small buyers, high switching costs and highly differentiated products with no alternatives all reduce buyer power by weakening the buyer's ability to walk away.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-B-04",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "In Porter's value chain, which of the following is a primary activity?",
    options: [
      "Human resource management.",
      "Procurement.",
      "Outbound logistics.",
      "Technology development.",
    ],
    correct: 2,
    explanation:
      "The primary activities are inbound logistics, operations, outbound logistics, marketing and sales, and service — so outbound logistics qualifies. Human resource management, procurement and technology development are all support activities that enable the primary chain rather than forming part of it.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-B-05",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "Which of the following is a support activity in Porter's value chain?",
    options: [
      "Operations.",
      "Marketing and sales.",
      "Inbound logistics.",
      "Firm infrastructure.",
    ],
    correct: 3,
    explanation:
      "Support activities are firm infrastructure, human resource management, technology development and procurement, so firm infrastructure is the correct choice. Operations, marketing and sales, and inbound logistics are all primary activities that directly create and deliver the product.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-B-06",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "In a SWOT analysis, which pairing correctly identifies an internal factor and an external factor?",
    options: [
      "Strengths are internal; opportunities are external.",
      "Strengths are external; threats are internal.",
      "Weaknesses are external; opportunities are internal.",
      "Threats are internal; weaknesses are external.",
    ],
    correct: 0,
    explanation:
      "In SWOT, strengths and weaknesses are internal to the organisation, while opportunities and threats arise from the external environment. The other options reverse this internal/external split, which is the core distinction the framework relies on.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBL2-B-07",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "A TOWS matrix extends SWOT to generate strategic options. What does an 'ST' (Strengths-Threats) strategy involve?",
    options: [
      "Using external opportunities to overcome internal weaknesses.",
      "Using internal strengths to counter or avoid external threats.",
      "Minimising internal weaknesses while avoiding external threats.",
      "Using internal strengths to exploit external opportunities.",
    ],
    correct: 1,
    explanation:
      "An ST strategy deploys the organisation's internal strengths to defend against or neutralise external threats. Using opportunities to fix weaknesses is a WO strategy, minimising weaknesses while avoiding threats is WT, and using strengths to seize opportunities is SO — each a different quadrant of the TOWS matrix.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBL2-B-08",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "The resource-based view argues that sustainable competitive advantage comes from resources that are valuable, rare and which have two further qualities. Under the VRIN criteria, what are the remaining two?",
    options: [
      "Inexpensive and abundant.",
      "Tangible and short-lived.",
      "Inimitable (hard to copy) and non-substitutable.",
      "Publicly available and easily transferable.",
    ],
    correct: 2,
    explanation:
      "VRIN resources are Valuable, Rare, Inimitable and Non-substitutable — the last two ensuring rivals cannot easily copy or replace the resource, which sustains advantage. Resources that are cheap, abundant, publicly available or easily transferable are precisely the kind competitors can readily obtain, so they cannot underpin lasting advantage.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-B-09",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "Hamel and Prahalad's concept of a 'core competence' is best described as:",
    options: [
      "Any activity the organisation happens to perform.",
      "The department with the largest headcount.",
      "A resource that is easily replicated by competitors.",
      "A distinctive capability that provides access to a range of markets and is hard for rivals to imitate.",
    ],
    correct: 3,
    explanation:
      "A core competence is a distinctive, hard-to-imitate capability that contributes disproportionately to customer value and can be leveraged across multiple markets. It is not merely any activity or the biggest department, and by definition it must be difficult for competitors to replicate — otherwise it would confer no lasting advantage.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-B-10",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "Under Porter's generic strategies, a firm that aims to become the lowest-cost producer across a broad market is pursuing which strategy?",
    options: [
      "Cost leadership.",
      "Differentiation.",
      "Focus.",
      "Diversification.",
    ],
    correct: 0,
    explanation:
      "Cost leadership seeks the lowest cost base across a broad market, enabling competitive pricing or higher margins. Differentiation competes on uniqueness rather than cost, focus targets a narrow segment, and diversification is an Ansoff growth direction rather than one of Porter's competitive strategies.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBL2-B-11",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "A cosmetics company invests heavily in brand image, product quality and packaging so that customers will pay a premium price. Which of Porter's generic strategies is it following?",
    options: [
      "Cost leadership.",
      "Differentiation.",
      "Cost focus.",
      "Being 'stuck in the middle'.",
    ],
    correct: 1,
    explanation:
      "Competing on brand, quality and distinctiveness to command a premium price across the market is a differentiation strategy. Cost leadership pursues the lowest cost instead, cost focus serves a narrow segment cheaply, and 'stuck in the middle' describes a firm that has failed to commit to any generic strategy — the opposite of this deliberate premium positioning.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-B-12",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "Porter warned that a firm which fails to achieve either cost leadership or differentiation, and does not focus on a niche, risks a particular outcome. What did he call this?",
    options: [
      "Achieving a hybrid advantage.",
      "Occupying a blue ocean.",
      "Reaching a strategic inflection point.",
      "Being 'stuck in the middle'.",
    ],
    correct: 3,
    explanation:
      "Porter argued that a firm pursuing neither a clear cost nor a clear differentiation advantage becomes 'stuck in the middle', lacking any distinctive edge and typically earning below-average returns. A hybrid advantage is Bowman's more optimistic idea, and blue ocean and strategic inflection points come from different theories, so none captures Porter's specific warning.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBL2-B-13",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "In Ansoff's matrix, selling more of an existing product to an existing market is which growth strategy?",
    options: [
      "Product development.",
      "Market development.",
      "Market penetration.",
      "Diversification.",
    ],
    correct: 2,
    explanation:
      "Market penetration means growing sales of existing products in existing markets, the lowest-risk quadrant of Ansoff's matrix. Product development introduces new products to existing markets, market development takes existing products into new markets, and diversification involves new products in new markets — each changing at least one variable that penetration holds constant.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBL2-B-14",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "A manufacturer of industrial pumps acquires a chain of coffee shops in a country where it has never operated. In Ansoff terms, this is an example of:",
    options: [
      "Diversification.",
      "Market penetration.",
      "Product development.",
      "Market development.",
    ],
    correct: 0,
    explanation:
      "Launching a new product (coffee shops) in a new market represents diversification, the highest-risk Ansoff quadrant because both variables change. Market penetration keeps product and market the same, product development keeps the market, and market development keeps the product — none matches a move that is new on both dimensions.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-B-15",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "In the BCG growth-share matrix, a business unit with high market share in a high-growth market is classified as:",
    options: [
      "A cash cow.",
      "A star.",
      "A dog.",
      "A question mark.",
    ],
    correct: 1,
    explanation:
      "High share in a high-growth market makes a unit a star — a market leader that usually needs continued investment to keep pace with growth. A cash cow has high share but low growth, a dog has low share and low growth, and a question mark has low share in a high-growth market.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-B-16",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "In the BCG matrix, which category typically generates strong positive cash flow that can be used to fund other business units?",
    options: [
      "Dog.",
      "Question mark.",
      "Star.",
      "Cash cow.",
    ],
    correct: 3,
    explanation:
      "A cash cow has high share in a low-growth market, so it earns substantial cash without needing heavy reinvestment, funding other units. Dogs generate little, question marks consume cash to build share, and stars often reinvest most of their earnings to sustain growth — so the cash cow is the classic net cash generator.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBL2-B-17",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "A business unit in the BCG matrix has a low market share in a rapidly growing market and consumes large amounts of cash. Which category is it, and what is the central strategic dilemma?",
    options: [
      "A question mark — the firm must decide whether to invest heavily to build share or to divest.",
      "A cash cow — the firm should simply harvest it for cash.",
      "A dog — the firm should always retain it for prestige.",
      "A star — no decision is required as it funds itself.",
    ],
    correct: 0,
    explanation:
      "Low share in a high-growth market is a question mark (problem child): it drains cash, so the firm must choose between backing it to become a star or divesting. Cash cows and dogs sit in low-growth markets, and a star already holds high share — so none poses the invest-or-divest dilemma unique to the question mark.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBL2-B-18",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "On Bowman's strategy clock, a 'hybrid' position offers customers low prices while also providing some differentiation. What must a firm achieve to sustain this position profitably?",
    options: [
      "The highest prices in the market regardless of value delivered.",
      "A deliberate reduction in the perceived value of its product.",
      "A low cost base, so it can fund differentiation while still charging low prices.",
      "Withdrawal from the market to avoid competition.",
    ],
    correct: 2,
    explanation:
      "The hybrid position combines low price with added value, which is only sustainable if the firm also achieves a genuinely low cost base to fund the differentiation without eroding margins. Charging the highest prices or cutting perceived value abandons the hybrid logic, and withdrawing from the market is not a competitive position at all.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBL2-B-19",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "On Bowman's strategy clock, a firm competing mainly on low price while accepting low perceived added value is at which kind of position?",
    options: [
      "A focused differentiation position charging premium prices.",
      "A low-price position, risking a price war unless it is also a cost leader.",
      "A position of no strategic value that always fails immediately.",
      "A monopoly-pricing position enjoying high margins.",
    ],
    correct: 1,
    explanation:
      "Competing chiefly on low price with modest added value is a low-price position, viable mainly for firms that are also cost leaders, otherwise margins collapse in price wars. Focused differentiation and monopoly pricing sit at the premium end of the clock, and low-price strategies are legitimate rather than doomed to instant failure.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBL2-B-20",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "A company wishes to enter a new market quickly and gain immediate access to an established brand and customer base. Which method of strategic development is most likely to achieve this fastest?",
    options: [
      "Purely organic (internal) growth built from scratch.",
      "A minority joint-venture stake carrying no control.",
      "Doing nothing and waiting for the market to come to it.",
      "Acquisition of an existing firm already in that market.",
    ],
    correct: 3,
    explanation:
      "Acquisition provides the fastest route to an established brand, customers and capabilities, because the firm buys a going concern rather than building one. Organic growth is inherently slower, a minority joint venture offers only partial access and control, and inaction is not a development method at all.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-B-21",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "Two airlines agree to share routes, coordinate schedules and honour each other's loyalty programmes while remaining independent companies. This is best described as:",
    options: [
      "A strategic alliance.",
      "A full merger into a single company.",
      "A hostile takeover.",
      "Vertical integration.",
    ],
    correct: 0,
    explanation:
      "Cooperating on routes and services while staying legally separate is a strategic alliance, a partnership that shares benefits without combining ownership. A merger would fuse the companies, a hostile takeover involves an unwanted acquisition, and vertical integration means owning different stages of the supply chain — none of which describes two independent firms simply collaborating.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBL2-B-22",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "Which of the following is a genuine advantage of organic (internal) growth over growth by acquisition?",
    options: [
      "It always delivers new capabilities faster than buying them in.",
      "It removes the need for any strategic planning.",
      "It avoids the culture-clash and integration risks that often follow acquisitions.",
      "It guarantees the firm will gain market leadership within a year.",
    ],
    correct: 2,
    explanation:
      "Organic growth builds capabilities internally, sidestepping the integration difficulties and culture clashes that frequently undermine acquisitions. It is typically slower, not faster, than acquisition; it still requires careful strategic planning; and no growth method can guarantee market leadership within a fixed period.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBL2-B-23",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "Mintzberg distinguished 'deliberate' strategy from 'emergent' strategy. What is an emergent strategy?",
    options: [
      "A strategy formally documented in a five-year plan before any action is taken.",
      "A strategy imposed word-for-word on the firm by external regulators.",
      "A strategy that is abandoned before any implementation occurs.",
      "A pattern of action that develops over time without a fully pre-formulated plan, in response to circumstances.",
    ],
    correct: 3,
    explanation:
      "An emergent strategy forms as a consistent pattern of decisions that develops in practice, responding to unfolding events rather than following a fully pre-set plan. A documented five-year plan is a deliberate strategy, a regulator-imposed rulebook is externally dictated, and a strategy dropped before action is an unrealised one — none captures Mintzberg's idea of strategy emerging through action.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBL2-B-24",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "Supporters of the rational (formal) planning approach to strategy argue that it offers which benefit?",
    options: [
      "It removes all need to monitor the external environment.",
      "It provides a structured, logical framework and clear coordination for setting and communicating objectives.",
      "It guarantees that the chosen strategy will succeed.",
      "It prevents the organisation from ever changing course.",
    ],
    correct: 1,
    explanation:
      "The rational planning approach offers a systematic, logical process that helps set clear objectives, coordinate activities and communicate direction across the organisation. It does not remove the need for environmental monitoring, cannot guarantee success, and does not lock a firm into an unchangeable course — plans can and should be reviewed.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-B-25",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "Using the Johnson, Scholes and Whittington criteria, the 'suitability' test of a proposed strategy asks primarily:",
    options: [
      "Does the strategy address the organisation's strategic position — its environment, capabilities and expectations?",
      "Can the strategy be funded and resourced in practice?",
      "Will the expected returns and risks be acceptable to stakeholders?",
      "Which competitor is likely to retaliate first?",
    ],
    correct: 0,
    explanation:
      "Suitability assesses whether a strategy fits the organisation's strategic position — addressing the opportunities and threats in its environment, exploiting its capabilities and matching stakeholder expectations. Whether it can be resourced is the feasibility test, whether returns and risks are acceptable is the acceptability test, and competitor retaliation is not one of the three SAF criteria.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-B-26",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "Under the SAF framework, which question is central to the 'acceptability' of a strategy?",
    options: [
      "Does the firm have the cash, people and technology to deliver it?",
      "Does the strategy fit the competitive environment and the firm's capabilities?",
      "Will the expected return, level of risk and stakeholder reactions be acceptable to key parties?",
      "Is the strategy written down in a formal planning document?",
    ],
    correct: 2,
    explanation:
      "Acceptability weighs the expected returns, the risk involved and the likely reactions of key stakeholders — whether the outcomes are acceptable to those who matter. Having the cash, people and technology is the feasibility test, fitting the environment and capabilities is suitability, and whether it is formally documented is irrelevant to the SAF evaluation.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBL2-B-27",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "The 'feasibility' test within the SAF framework is chiefly concerned with:",
    options: [
      "Whether stakeholders will approve of the expected returns.",
      "Whether the organisation has, or can obtain, the resources and competences to implement the strategy.",
      "Whether the strategy fits the external environment.",
      "Whether the strategy is the most exciting option available.",
    ],
    correct: 1,
    explanation:
      "Feasibility examines whether the strategy can actually be implemented — whether the necessary funding, people, technology and competences exist or can be secured. Stakeholder approval of returns is acceptability, fit with the environment is suitability, and how exciting an option is plays no part in the SAF assessment.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-B-28",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "For a competitive advantage to be considered sustainable, which condition is most important?",
    options: [
      "It can be quickly and cheaply copied by any competitor.",
      "It relies entirely on a temporary price promotion.",
      "It depends on a single customer who may leave at any time.",
      "It is difficult for competitors to imitate or substitute over time.",
    ],
    correct: 3,
    explanation:
      "A sustainable competitive advantage rests on something rivals find hard to imitate or substitute, allowing the firm to retain its edge over time. An advantage that is easily copied, based on a fleeting promotion, or dependent on one fickle customer is inherently fragile and cannot be sustained.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "SBL2-B-29",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "In Porter's model, which of the following would most strongly reduce the threat of new entrants to an industry?",
    options: [
      "High barriers to entry such as large capital requirements and strong brand loyalty.",
      "Low start-up costs and easy access to distribution channels.",
      "The absence of any economies of scale among incumbents.",
      "Weak, unrecognised brands held by the existing firms.",
    ],
    correct: 0,
    explanation:
      "High barriers to entry — heavy capital needs, established brand loyalty and economies of scale — deter new competitors and lower the threat of entry. Low start-up costs, easy distribution access, no scale advantages and weak incumbent brands all make entry easier, raising rather than reducing the threat.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-B-30",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "In Porter's five forces, which of the following is an example of the 'threat of substitutes' for a rail passenger operator?",
    options: [
      "A rival train company opening a competing rail line on the same route.",
      "Customers choosing to travel by long-distance coach or budget airline instead of by train.",
      "A signalling-equipment supplier raising its prices sharply.",
      "A rail regulator introducing new safety rules.",
    ],
    correct: 1,
    explanation:
      "A substitute meets the same customer need through a different product or industry — here, coaches or airlines replacing rail travel. A competing train company is direct rivalry within the same industry, a supplier raising prices is supplier power, and a regulator's rules are a macro-environmental (PESTEL) factor, not a substitute.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBL2-B-31",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "Which set of conditions is most likely to intensify competitive rivalry within an industry?",
    options: [
      "A rapidly growing market with few competitors and highly differentiated products.",
      "High customer switching costs and strong brand loyalty.",
      "Slow market growth, many similar-sized competitors and high exit barriers.",
      "A single dominant firm facing no meaningful competitors.",
    ],
    correct: 2,
    explanation:
      "Rivalry intensifies when growth is slow, numerous competitors of similar size fight for share, products are undifferentiated and high exit barriers keep struggling firms in the market. Fast growth with few players, high switching costs and loyalty, or a single dominant firm all dampen rivalry rather than heighten it.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-B-32",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "Under a PESTEL analysis, new legislation requiring firms to cut their carbon emissions would fall primarily under which two headings?",
    options: [
      "Environmental and Legal.",
      "Political and Product.",
      "Social and Sales.",
      "Technological and Team.",
    ],
    correct: 0,
    explanation:
      "Carbon-reduction legislation is an environmental concern enacted through law, placing it under the Environmental and Legal headings of PESTEL. The other pairings include terms — Product, Sales, Team — that are not PESTEL categories at all, since PESTEL covers only Political, Economic, Social, Technological, Environmental and Legal factors.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "SBL2-B-33",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "In Porter's value chain, what does the 'margin' represent?",
    options: [
      "The physical width of the factory floor.",
      "The interest charged on the company's borrowings.",
      "The spacing shown between primary and support activities on the diagram.",
      "The difference between the total value delivered to customers and the cost of performing the value activities.",
    ],
    correct: 3,
    explanation:
      "In the value chain, margin is the value created and captured — the excess of the total value customers are willing to pay over the collective cost of carrying out the value activities. It has nothing to do with factory dimensions, loan interest, or spacing on the diagram; it is the profit generated by the whole chain.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-B-34",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "A software firm launches an entirely new product aimed at its existing customer base. In Ansoff terms, this is:",
    options: [
      "Market penetration.",
      "Product development.",
      "Market development.",
      "Diversification.",
    ],
    correct: 1,
    explanation:
      "Offering a new product to existing customers is product development in Ansoff's matrix. Market penetration sells existing products to the same market, market development takes existing products to new markets, and diversification requires both a new product and a new market — whereas here only the product is new.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "SBL2-B-35",
    paper: "SBL",
    area: "B",
    type: "mcq",
    stem: "A retailer sets out a deliberate plan to expand online, but along the way abandons part of it and instead develops a successful click-and-collect service that was never in the original plan. Using Mintzberg's terms, how are the click-and-collect element and the abandoned part best described?",
    options: [
      "Both are purely deliberate strategy.",
      "Both are unrealised strategy.",
      "The click-and-collect service is emergent strategy; the dropped part is unrealised strategy.",
      "The click-and-collect service is unrealised strategy; the dropped part is emergent strategy.",
    ],
    correct: 2,
    explanation:
      "In Mintzberg's terms the realised click-and-collect service, which arose unplanned in response to circumstances, is emergent strategy, while the intended online element that was dropped is unrealised strategy. Calling both deliberate ignores the unplanned development, calling both unrealised denies that click-and-collect actually happened, and the final option simply swaps the two labels.",
    marks: 2,
    difficulty: "hard",
  },
]
