import type { AccaQuestion } from "@/lib/acca-content"

/* FR bank wave 6a — areas A-C, 45 verified originals (2026-07-11). */

export const FR_WAVE3A: AccaQuestion[] = [
  /* ───────────── Area A — conceptual & regulatory framework (10) ───────────── */
  {
    id: "FR3-A-01",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "Granholt Co has a decommissioning liability whose amount can only be estimated within a wide range. The directors want to leave it unrecognised 'because the figure cannot be measured precisely'. Per the Conceptual Framework, which statement is correct?",
    options: [
      "They are correct: items that cannot be measured precisely must not be recognised",
      "The liability should be recognised at the lowest amount in the range, to be prudent",
      "A reasonable estimate should be recognised: the use of estimates is essential to financial reporting and does not in itself prevent faithful representation, provided the estimate is clearly described and explained",
      "The liability should be recognised only once the amount has been verified by an independent expert",
    ],
    correct: 2,
    explanation:
      "The Framework states that measurement uncertainty does not automatically prevent information from being useful — a properly described estimate can still faithfully represent the item. Refusing to recognise anything imprecise confuses precision with faithful representation, picking the lowest figure is asymmetric 'prudence' (deliberate bias), and verifiability is only an ENHANCING characteristic, not a recognition hurdle.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-A-02",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "Under the current Conceptual Framework, prudence is best described as:",
    options: [
      "Deliberately understating assets and income to protect lenders",
      "The exercise of caution when making judgements under uncertainty, so that assets and income are not overstated and liabilities and expenses are not understated",
      "Recognising all possible future losses immediately while deferring all gains until realised",
      "Building hidden reserves in profitable years so that future losses can be absorbed",
    ],
    correct: 1,
    explanation:
      "The Framework reintroduced prudence as CAUTIOUS JUDGEMENT that SUPPORTS neutrality — it does not permit deliberate under- or overstatement. Systematic understatement, asymmetric loss recognition and hidden reserves are all forms of bias that BREACH neutrality, the classic misreadings of prudence.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR3-A-03",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "Elmsworth Co had net assets of $1,000,000 at 1 January and $1,300,000 at 31 December. During the year the owners introduced capital of $100,000 and dividends of $50,000 were paid. General prices rose by 10% during the year. Under REAL financial capital maintenance (constant purchasing power), what is profit for the year?",
    options: ["$150,000", "$250,000", "$300,000", "$200,000"],
    correct: 0,
    explanation:
      "Money profit = $1,300,000 − $1,000,000 − $100,000 capital introduced + $50,000 dividends = $250,000; real financial capital maintenance then deducts the inflation adjustment needed to maintain opening capital (10% × $1,000,000 = $100,000), giving $150,000. $250,000 stops at money capital maintenance, $300,000 ignores the owner transactions, and $200,000 adjusts for inflation but forgets the capital introduced and dividends.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-A-04",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "Divergent accounting treatments of an IFRS requirement have emerged in practice. Which body is responsible for issuing authoritative interpretations to resolve the divergence?",
    options: [
      "The IFRS Advisory Council",
      "The trustees of the IFRS Foundation",
      "IOSCO",
      "The IFRS Interpretations Committee",
    ],
    correct: 3,
    explanation:
      "The IFRS Interpretations Committee (IFRIC) issues interpretations where divergent practice has emerged, subject to IASB ratification. The Advisory Council only advises on agenda and priorities, the trustees handle governance and appointments (not technical output), and IOSCO is a securities-regulator body with no standard-setting role.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR3-A-05",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "Which of the following best describes the IASB's due process for developing a new IFRS Accounting Standard?",
    options: [
      "Research and discussion paper, then an exposure draft open to public comment, then the standard is issued",
      "An exposure draft is issued first, followed by a discussion paper, then the standard",
      "The standard is drafted and issued privately by the IASB and then ratified by IOSCO",
      "A standard takes effect only once it has been approved by the government of every country that applies IFRS",
    ],
    correct: 0,
    explanation:
      "Due process runs research/discussion paper → exposure draft with public consultation → final standard (followed by post-implementation review). Reversing the DP and ED order confuses the stages, IOSCO has no ratification role, and while some jurisdictions have their own ENDORSEMENT mechanisms, universal government approval is not part of the IASB's due process.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR3-A-06",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "Farlow Trust is a charity that provides free vaccination services. Which statement about applying the Conceptual Framework's concepts to Farlow is correct?",
    options: [
      "The Framework's concepts cannot be applied because they are written only for profit-oriented entities",
      "Farlow should measure its success primarily by profit, as for any reporting entity",
      "The objective of Farlow's reporting shifts towards stewardship and service delivery for funders and beneficiaries, although relevance and faithful representation still apply",
      "The qualitative characteristics of useful information do not apply to a charity's financial statements",
    ],
    correct: 2,
    explanation:
      "For a not-for-profit entity the PRIMARY USERS change (donors, funders, beneficiaries) and the objective centres on stewardship and service delivery rather than investor returns — but the qualitative characteristics still apply to whatever is reported. Saying the concepts 'cannot be applied', or forcing a profit focus, misses that it is the OBJECTIVE and users that adapt, not the need for useful information.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-A-07",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "In an exceptionally profitable year, Densmore Co's directors doubled the warranty provision to well above the IAS 37 best estimate 'to be prudent', intending to release the excess next year. In Conceptual Framework terms, this treatment:",
    options: [
      "Is acceptable, because prudence permits provisions to be overstated",
      "Breaches neutrality: the figures are deliberately biased to smooth profit, so they are not faithfully represented",
      "Is acceptable provided the approach is disclosed in the notes",
      "Breaches only comparability; faithful representation is unaffected",
    ],
    correct: 1,
    explanation:
      "Deliberately overstating a liability to shift profit between periods is BIAS — it fails neutrality and therefore faithful representation ('big bath'/profit-smoothing). Prudence in the current Framework supports neutrality and never licenses overstatement, disclosure cannot cure a misstatement, and while comparability also suffers, the primary breach is faithful representation itself.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-A-08",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "Under the Conceptual Framework, information is material if:",
    options: [
      "It exceeds a fixed benchmark of 5% of profit before tax",
      "The external auditor decides that it is material",
      "It is large in monetary amount, regardless of its nature",
      "Omitting, misstating or obscuring it could reasonably be expected to influence the decisions of the primary users of the financial statements",
    ],
    correct: 3,
    explanation:
      "Materiality is an ENTITY-SPECIFIC aspect of relevance: information is material if omitting, MISSTATING or OBSCURING it could influence primary users' decisions. There is no fixed percentage threshold in the Framework, materiality is management's judgement (not the auditor's decision), and NATURE as well as size can make an item material.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR3-A-09",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "Replacing Farrowgate Co's productive capacity would have cost $500,000 at 1 January and $550,000 at 31 December. Its net assets, measured at current cost, were $500,000 and $560,000 respectively, with no transactions with owners. The general price index rose 4% in the year. Under PHYSICAL capital maintenance, what is profit for the year?",
    options: ["$10,000", "$60,000", "$40,000", "$50,000"],
    correct: 0,
    explanation:
      "Physical capital maintenance treats profit as the surplus AFTER maintaining operating capability: $560,000 − $550,000 = $10,000; the $50,000 rise in replacement cost is a capital maintenance adjustment, not profit. $60,000 is money financial capital maintenance, $40,000 is REAL financial maintenance using the 4% general index ($560,000 − $520,000), and $50,000 is the capital maintenance adjustment itself.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-A-10",
    paper: "FR",
    area: "A",
    type: "mcq",
    stem: "Which statement about the enhancing characteristic of comparability is correct?",
    options: [
      "Comparability requires all entities to adopt identical accounting policies",
      "Consistency and comparability are two words for the same concept",
      "Comparability is the goal; consistency of methods helps achieve it, and it requires like items to look alike and different items to look different",
      "An entity should retain an accounting policy it knows is inappropriate in order to preserve comparability with prior years",
    ],
    correct: 2,
    explanation:
      "The Framework distinguishes comparability (the GOAL) from consistency (a MEANS of achieving it) and from uniformity: making unlike things look alike harms comparability as much as making like things look different. Demanding identical policies is uniformity, and retaining a known-inappropriate policy sacrifices relevance and faithful representation for false consistency.",
    marks: 2,
    difficulty: "medium",
  },

  /* ───────────── Area B — accounting for transactions, IFRS (25) ───────────── */
  {
    id: "FR3-B-01",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Gorsefield Co's plant cost $500,000 with a 25-year life and nil residual value. After exactly 5 years (carrying amount $400,000) it was revalued for the first time to $360,000; the deficit was recognised in profit or loss and total useful life is unchanged. What is the depreciation charge for the following year?",
    options: ["$20,000", "$18,000", "$14,400", "$25,000"],
    correct: 1,
    explanation:
      "After a revaluation, IAS 16 depreciates the REVALUED amount over the REMAINING life: $360,000 ÷ 20 years = $18,000. $20,000 carries on with the pre-revaluation charge, $14,400 spreads the new value over the original 25-year life, and $25,000 divides original cost by the remaining life.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-B-02",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Hazelmere Co exchanged a machine with a carrying amount of $60,000 and a fair value of $75,000, plus cash of $10,000, for a new machine. The exchange has commercial substance. At what amount is the new machine initially recognised under IAS 16?",
    options: ["$65,000", "$70,000", "$75,000", "$85,000"],
    correct: 3,
    explanation:
      "An exchange with commercial substance is measured at the FAIR VALUE of the consideration given: $75,000 + $10,000 cash = $85,000, with a $15,000 gain ($75,000 − $60,000) in profit or loss. $70,000 wrongly uses the carrying amount plus cash, $75,000 forgets the cash paid, and $65,000 deducts the cash instead of adding it.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-B-03",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "A cash-generating unit of Inglewood Co comprises goodwill of $60,000, plant of $180,000 and a licence of $60,000 (total $300,000). The CGU's recoverable amount is $220,000 and no individual asset's recoverable amount can be determined. Under IAS 36, how much of the impairment loss is allocated to the plant?",
    options: ["$15,000", "$48,000", "$60,000", "$20,000"],
    correct: 0,
    explanation:
      "IAS 36 allocates the $80,000 loss to GOODWILL FIRST ($60,000), then pro-rata to the other assets by carrying amount: remaining $20,000 × 180/240 = $15,000 to plant. $48,000 pro-rates the whole loss including goodwill, $60,000 pro-rates the loss over plant and licence ignoring the goodwill-first rule, and $20,000 dumps the entire residual on the plant.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-B-04",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Jarrowden Co's plant cost $400,000 (10-year life, nil residual). At the end of year 2 it was impaired from its carrying amount of $320,000 to $240,000. At the end of year 4 its recoverable amount is $250,000. What impairment reversal is recognised under IAS 36?",
    options: ["$0", "$80,000", "$60,000", "$70,000"],
    correct: 2,
    explanation:
      "After impairment, depreciation is $240,000 ÷ 8 = $30,000, so the carrying amount at the end of year 4 is $180,000. The reversal is capped at what the carrying amount WOULD have been with no impairment ($400,000 − 4 × $40,000 = $240,000), so the reversal is $240,000 − $180,000 = $60,000. $70,000 reverses up to the $250,000 recoverable amount ignoring the ceiling, $80,000 reverses the original loss in full, and $0 misapplies the goodwill no-reversal rule to plant.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-B-05",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Lockmere Co built a website through which customers place orders. Costs were: planning and feasibility $20,000; application and infrastructure development $70,000; graphical design $15,000; creating content advertising Lockmere's products $10,000; staff training $5,000. The IAS 38 recognition criteria were met before development began. How much is capitalised as an intangible asset?",
    options: ["$70,000", "$85,000", "$105,000", "$120,000"],
    correct: 1,
    explanation:
      "Under IAS 38/SIC-32, application and infrastructure development and graphical design are capitalised once the criteria are met ($70,000 + $15,000 = $85,000); the planning stage is research-like (expensed), content created to ADVERTISE products is expensed like all advertising, and training is always expensed. $70,000 wrongly expenses the graphics, $105,000 capitalises planning, and $120,000 capitalises everything.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-B-06",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Norcliffe Co pays $180,000 up front for three years' access to payroll software hosted and controlled by the supplier (a SaaS arrangement), plus $40,000 to the supplier for configuration work that does not create a resource Norcliffe controls. How should these costs be treated?",
    options: [
      "No intangible asset is recognised: the configuration cost is expensed as the service is received and the access fee is expensed over the three-year term",
      "Capitalise $220,000 as an intangible asset amortised over three years",
      "Capitalise only the $40,000 configuration cost as an intangible asset",
      "Recognise a right-of-use asset and lease liability under IFRS 16",
    ],
    correct: 0,
    explanation:
      "In a SaaS arrangement the customer does not CONTROL the software, so the IAS 38 asset definition fails — the fees are payments for a SERVICE: configuration is expensed as performed and the access fee over the contract term (a prepayment until then). Capitalising either amount asserts control that does not exist, and IFRS 16 excludes licences of intangible assets from right-of-use accounting.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-B-07",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Quenby Co is constructing an asset for a customer for a fixed price of $500,000 plus a $100,000 bonus if it finishes by 30 June. Quenby estimates a 70% chance of earning the bonus but, with little experience of similar contracts, cannot conclude it is highly probable that including the bonus would not cause a significant revenue reversal. The contract, satisfied over time, is 40% complete on an appropriate input basis. What revenue is recognised to date?",
    options: ["$500,000", "$228,000", "$240,000", "$200,000"],
    correct: 3,
    explanation:
      "IFRS 15's CONSTRAINT excludes variable consideration unless it is highly probable no significant reversal will occur — so the bonus is left out and revenue = 40% × $500,000 = $200,000. $240,000 includes the constrained bonus (40% × $600,000), $228,000 uses an unconstrained expected value (40% × $570,000), and $500,000 recognises the fixed price in full, ignoring the stage of completion.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-B-08",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Ruxley Co sells goods through its website that are shipped to customers directly from the manufacturer. Ruxley sets the selling prices, is primarily responsible to customers for the goods and bears the risk of returns, obtaining control of each item momentarily before transfer. Gross sales for the year were $80,000, of which $60,000 was payable to the manufacturer. What revenue does Ruxley recognise?",
    options: ["$20,000", "$60,000", "$80,000", "$140,000"],
    correct: 2,
    explanation:
      "Price discretion, primary responsibility and return/inventory risk show Ruxley CONTROLS the goods before transfer, so it is a PRINCIPAL under IFRS 15 even though goods ship direct from the manufacturer: revenue is the gross $80,000 with $60,000 in cost of sales. $20,000 treats it as an agent's commission because of the drop-shipping, $60,000 reports the supplier cost as revenue, and $140,000 double-counts gross and net.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-B-09",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Sorrel Co contracted to deliver 100 identical units at $10.00 each. After 60 units had been delivered, the contract was modified to add 40 more units at $7.20 each — below their standalone selling price of $8.00 at that date. The additional units are distinct. Under IFRS 15, what price per unit is recognised as the remaining units are delivered?",
    options: [
      "$8.60 for every unit delivered after the modification",
      "$10.00 for the remaining original units and $7.20 for the additional units",
      "$8.00 for every unit delivered after the modification",
      "$9.20 for every unit, with a cumulative catch-up adjustment on the 60 units already delivered",
    ],
    correct: 0,
    explanation:
      "Because the extra distinct units are NOT priced at their standalone selling price, the modification is treated as terminating the old contract and creating a new one: remaining consideration (40 × $10.00 + 40 × $7.20 = $688) is spread over the 80 undelivered units = $8.60 each, prospectively. Keeping the two prices separate treats it as a separate contract (which needs standalone pricing), $8.00 substitutes the standalone price, and $9.20 wrongly blends ALL 140 units with a catch-up, which applies only when the remaining goods are NOT distinct.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-B-10",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Trevance Co sold a building with a carrying amount of $600,000 to a buyer for its fair value of $1,000,000 and immediately leased it back; the transfer qualifies as a sale under IFRS 15. The present value of the leaseback payments is $400,000. What gain does Trevance recognise on the sale?",
    options: ["$0", "$240,000", "$400,000", "$160,000"],
    correct: 1,
    explanation:
      "In a sale and leaseback the seller-lessee recognises only the gain relating to rights TRANSFERRED to the buyer: $400,000 total gain × ($1,000,000 − $400,000)/$1,000,000 = $240,000. $400,000 books the full gain as if the building were sold outright, $160,000 is the portion relating to the rights RETAINED (embedded in the right-of-use asset), and $0 defers everything, echoing the old finance-leaseback rule.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-B-11",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Which of the following leases may Umberline Co choose to expense on a straight-line basis instead of recognising a right-of-use asset under IFRS 16?",
    options: [
      "An 11-month lease of a machine that contains an option to purchase the machine",
      "A 15-month lease of a delivery van",
      "A lease of a second-hand machine whose current value is low, although it cost $80,000 when new",
      "A 3-year lease of laptops, each of low value when new, even though the aggregate amounts are material to Umberline",
    ],
    correct: 3,
    explanation:
      "The low-value exemption is judged ASSET BY ASSET on the value WHEN NEW, regardless of materiality in aggregate — so the laptops qualify. A purchase option disqualifies an otherwise short-term lease, 15 months exceeds the 12-month short-term limit, and a low SECOND-HAND value is irrelevant because the test uses the value of the asset when new.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR3-B-12",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Kestrell Co (a lessor) leases a standard, non-specialised machine to a customer for 3 years. The machine's fair value is $90,000, its economic life is 8 years, and the present value of the lease payments is $50,000. The machine reverts to Kestrell at the end of the lease. How should Kestrell classify the lease, and why?",
    options: [
      "Finance lease, because the lessee controls the use of the machine for three years",
      "Finance lease, because the lease payments exceed half of the machine's fair value",
      "Operating lease, because the risks and rewards of ownership are not substantially transferred: the term is a minor part of the economic life and the present value is well below fair value",
      "Operating lease, because legal title never passes to the lessee",
    ],
    correct: 2,
    explanation:
      "Lessor classification under IFRS 16 rests on whether SUBSTANTIALLY ALL risks and rewards transfer: 3 of 8 years and a PV of only 56% of fair value, with the asset returned, point to an operating lease. Lessee 'control of use' exists in every lease so proves nothing, 'more than half' is not the 'substantially all' threshold, and legal title also stays with the lessor in most FINANCE leases, so it is the wrong reason.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-B-13",
    paper: "FR",
    area: "B",
    type: "number",
    stem: "Wraysbury Co has a contract that has become onerous: the unavoidable costs of fulfilling it are $120,000 and the benefits expected from it are $90,000. Cancelling the contract instead would trigger a penalty of $20,000. Under IAS 37, what provision is recognised, in $?",
    numericAnswer: 20000,
    unit: "$",
    tolerance: 0,
    explanation:
      "An onerous-contract provision is measured at the LOWER of the net cost of fulfilling ($120,000 − $90,000 = $30,000) and the cost of exiting (the $20,000 penalty) — the least net cost of escape, $20,000. Providing $30,000 ignores the cheaper exit, $50,000 adds both costs together, and providing nothing treats a contract that is already onerous as still executory.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-B-14",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Yelverton Co must pay an estimated $200,000 to rectify environmental damage (a present obligation from a past event). Its insurer has confirmed in writing that it will reimburse $150,000, which Yelverton judges virtually certain. How is this reported in the statement of financial position?",
    options: [
      "A provision of $200,000 and a separate reimbursement asset of $150,000",
      "A single net provision of $50,000",
      "A provision of $200,000, with the reimbursement recognised only when the cash is received",
      "A provision of $200,000, with the $150,000 disclosed as a contingent asset",
    ],
    correct: 0,
    explanation:
      "IAS 37 requires the provision in FULL and, because the reimbursement is virtually certain, a SEPARATE asset (capped at the provision) — offsetting is permitted in profit or loss but never on the statement of financial position. Netting to $50,000 offsets on the SOFP, waiting for cash ignores that 'virtually certain' has been met, and contingent-asset disclosure applies only when recovery is merely probable.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-B-15",
    paper: "FR",
    area: "B",
    type: "number",
    stem: "On 1 March Ambleford Co borrowed $2,000,000 at 9% specifically to construct a warehouse. Construction ran from 1 March to 31 December, but all activity stopped during July and August because of a commercial dispute unrelated to the construction process. Under IAS 23, what borrowing costs are capitalised for the year, in $?",
    numericAnswer: 120000,
    unit: "$",
    tolerance: 0,
    explanation:
      "IAS 23 SUSPENDS capitalisation during extended periods when active development is interrupted (the two-month dispute is not a necessary temporary delay), so only 8 months qualify: $2,000,000 × 9% × 8/12 = $120,000. Capitalising 10 months ($150,000) ignores the suspension and 12 months ($180,000) also capitalises interest incurred before construction began; the July–August interest is expensed.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-B-16",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Chalgrove Co revalued land upwards by $200,000 during the year. The tax rate is 25%, and tax on the gain will become payable only if and when the land is sold. Under IAS 12, what is the deferred tax consequence of the revaluation?",
    options: [
      "No deferred tax arises because the gain is unrealised",
      "A deferred tax liability of $50,000 is recognised, charged to other comprehensive income",
      "A deferred tax liability of $50,000 is recognised, charged to profit or loss",
      "No deferred tax arises because land is not depreciated",
    ],
    correct: 1,
    explanation:
      "The revaluation raises the carrying amount above the tax base, creating a taxable temporary difference of $200,000 × 25% = $50,000; because the gain sits in OCI, IAS 12 charges the related deferred tax to OCI too (the 'follow the item' rule). Charging P/L mismatches the gain, and 'unrealised' or 'not depreciated' arguments confuse temporary differences with current tax — recovery through eventual sale still triggers tax.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-B-17",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Nettlestone Co's dairy herd had a fair value less costs to sell of $400,000 at 1 January. During the year it purchased additional cattle for $30,000, and at 31 December the herd's fair value less costs to sell was $460,000. Under IAS 41, what gain is recognised in profit or loss for the year?",
    options: ["$0", "$60,000", "$90,000", "$30,000"],
    correct: 3,
    explanation:
      "Biological assets are measured at fair value less costs to sell with changes in PROFIT OR LOSS: gain = $460,000 − ($400,000 + $30,000 purchases) = $30,000. $60,000 forgets that part of the increase was simply bought, $90,000 adds the purchases instead of deducting them, and $0 wrongly applies a cost model — under IAS 41 the fair-value change is recognised even though unrealised.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-B-18",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Oakhurst Co measures an unquoted corporate bond using recent quoted prices for similar (but not identical) bonds, adjusted using observable market data. In the IFRS 13 fair value hierarchy, this measurement is:",
    options: [
      "Level 1",
      "Level 3",
      "Level 2",
      "Outside the hierarchy, because the bond itself is not quoted",
    ],
    correct: 2,
    explanation:
      "Quoted prices for SIMILAR assets, plus other observable inputs, are Level 2 of the IFRS 13 hierarchy. Level 1 requires unadjusted quoted prices for the IDENTICAL asset in an active market, Level 3 applies only when significant inputs are UNOBSERVABLE (e.g. own cash-flow models), and every fair value measurement sits somewhere in the hierarchy.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR3-B-19",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "While preparing its 20X5 financial statements, Foxwell Co discovers that closing inventory in the 20X4 statements was overstated by $50,000 because of a spreadsheet formula error. The 20X4 figures are presented as comparatives. Under IAS 8, how is the error corrected?",
    options: [
      "Restate the 20X4 comparatives, reducing 20X4 profit and closing equity by $50,000, so 20X5 opens with the corrected inventory figure",
      "Deduct $50,000 from 20X5 profit, because corrections are applied prospectively",
      "Adjust 20X5 opening retained earnings by $50,000 but leave the 20X4 comparative figures as originally reported",
      "Make no adjustment, because the error self-corrects: 20X4 profit is overstated and 20X5 profit understated by the same amount",
    ],
    correct: 0,
    explanation:
      "A material PRIOR-PERIOD ERROR is corrected RETROSPECTIVELY under IAS 8: the 20X4 comparatives are restated as if the error never occurred. Prospective treatment belongs to changes in ESTIMATE, adjusting retained earnings without restating comparatives leaves the prior-year columns wrong, and the 'self-correcting' argument still reports BOTH years' profits incorrectly.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-B-20",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Penrose Co has identified four reportable operating segments using the 10% size tests; together their external revenue is 68% of the entity's total external revenue. Under IFRS 8, Penrose must:",
    options: [
      "Do nothing more, because every reportable segment identified has passed a 10% test",
      "Identify additional reportable segments until at least 75% of external revenue is covered",
      "Combine all remaining segments into an 'all other segments' column, which completes the requirement",
      "Report every operating segment separately, however small",
    ],
    correct: 1,
    explanation:
      "IFRS 8 requires reportable segments to cover at least 75% of EXTERNAL revenue — if the 10% tests get you only to 68%, further segments are added (even ones below 10%) until the threshold is met. Stopping at the 10% tests misses this second hurdle, the 'all other segments' category is residual disclosure and does not count towards the 75%, and full disaggregation of every tiny segment is never required.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR3-B-21",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Silverdale Co had 1,000,000 ordinary shares in issue on 1 January. On 1 July it made a 1-for-4 rights issue at $1.60 per share when the cum-rights price was $2.10. Profit attributable to ordinary shareholders for the year was $460,000. What is basic EPS under IAS 33?",
    options: ["46.0 cents", "40.9 cents", "36.8 cents", "40.0 cents"],
    correct: 3,
    explanation:
      "TERP = (4 × $2.10 + $1.60) ÷ 5 = $2.00, so the bonus factor is 2.10/2.00 = 1.05. Weighted shares = 1,000,000 × 1.05 × 6/12 + 1,250,000 × 6/12 = 1,150,000; EPS = $460,000 ÷ 1,150,000 = 40.0c. 40.9c omits the bonus factor on the pre-rights period, 36.8c treats all 1,250,000 shares as in issue all year, and 46.0c ignores the rights issue entirely.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-B-22",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Thistlewood Co reports profit attributable to ordinary shareholders of $400,000 and has 1,000,000 ordinary shares in issue. It also has $500,000 of 8% convertible loan notes, convertible into 200,000 ordinary shares. The tax rate is 20%. What is diluted EPS?",
    options: ["40.0 cents", "33.3 cents", "36.0 cents", "36.7 cents"],
    correct: 2,
    explanation:
      "On assumed conversion the interest saved is added back NET OF TAX: earnings = $400,000 + ($500,000 × 8% × 80%) = $432,000; shares = 1,200,000; diluted EPS = 36.0c. 40.0c is basic EPS with no dilution, 36.7c adds back the gross $40,000 interest forgetting tax, and 33.3c increases the shares without adjusting earnings at all.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-B-23",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Maddox Co bought an office block for $800,000 solely to earn rentals and for capital appreciation, and adopted the IAS 40 fair value model. At the year end the property's fair value is $860,000. How is the $60,000 increase reported?",
    options: [
      "As a gain in profit or loss, with no depreciation charged on the property",
      "In other comprehensive income, accumulating in a revaluation surplus",
      "It is not recognised: the property is depreciated and carried at cost",
      "It is recognised only when the property is eventually sold",
    ],
    correct: 0,
    explanation:
      "Under the IAS 40 FAIR VALUE model, investment property is not depreciated and ALL fair value changes go to PROFIT OR LOSS. Routing the gain to OCI confuses IAS 40 with the IAS 16 revaluation model — the classic trap; carrying at cost applies only if the cost model is chosen, and waiting for sale is the realisation fallacy.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR3-B-24",
    paper: "FR",
    area: "B",
    type: "number",
    stem: "On 1 November Ledbury Co, whose functional currency is the dollar, bought goods for 300,000 crowns when the exchange rate was 7.5 crowns to $1. The invoice was still unpaid at the 31 December year end, when the rate was 8.0 crowns to $1. What exchange GAIN is recognised in profit or loss, in $?",
    numericAnswer: 2500,
    unit: "$",
    tolerance: 0,
    explanation:
      "The trade payable is a MONETARY item, retranslated at the closing rate under IAS 21: 300,000 ÷ 7.5 = $40,000 at purchase versus 300,000 ÷ 8.0 = $37,500 at year end — a $2,500 gain in profit or loss (fewer dollars are needed to settle). The inventory, a non-monetary item, stays at the historical $40,000, and the gain is NOT taken to OCI — that treatment is for foreign operations, not transactions.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-B-25",
    paper: "FR",
    area: "B",
    type: "mcq",
    stem: "Rivenhall Co classifies an item of plant as held for sale when its carrying amount, updated for depreciation to that date, is $500,000. The plant's fair value is $470,000 and costs to sell are $20,000. Under IFRS 5, the plant is then measured at:",
    options: [
      "$500,000, with depreciation continuing until the sale completes",
      "$450,000, with an impairment loss of $50,000 and no further depreciation",
      "$470,000, with an impairment loss of $30,000",
      "$450,000, with depreciation continuing until the date of sale",
    ],
    correct: 1,
    explanation:
      "Held-for-sale assets are measured at the LOWER of carrying amount and fair value LESS COSTS TO SELL: $470,000 − $20,000 = $450,000, giving a $50,000 impairment loss — and depreciation CEASES on classification. $470,000 forgets the costs to sell, $500,000 skips the write-down, and continuing to depreciate contradicts IFRS 5's explicit prohibition.",
    marks: 2,
    difficulty: "medium",
  },

  /* ───────────── Area C — analysing & interpreting (10) ───────────── */
  {
    id: "FR3-C-01",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Birchmoor Co's profit for the year rose by 25%, yet its cash generated from operations fell sharply. Which of the following is the most likely explanation?",
    options: [
      "Depreciation charges increased during the year",
      "A long-term loan was repaid during the year",
      "Plant was sold during the year at a loss",
      "Revenue growth was achieved by offering customers longer credit and building up inventories",
    ],
    correct: 3,
    explanation:
      "Growing receivables and inventories absorb cash even while profits rise — the classic profit/cash divergence (and a warning sign of overtrading). Higher depreciation is non-cash and is ADDED BACK (raising cash from operations relative to profit), a disposal loss is also added back with proceeds shown in investing, and a loan repayment is a FINANCING outflow that never touches cash generated from operations.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-C-02",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Which of the following statements about earnings per share (EPS) as a performance measure is correct?",
    options: [
      "EPS provides a reliable basis for comparing the performance of two different companies",
      "Because IAS 33 defines EPS precisely, reported EPS cannot be affected by the directors' accounting-policy choices",
      "EPS is of limited use for comparing different companies because it reflects each company's capital structure and number of shares, not just underlying performance",
      "Diluted EPS shows what EPS will actually be next year once options and convertibles are exercised",
    ],
    correct: 2,
    explanation:
      "EPS depends on the NUMBER of shares in issue and the capital structure, so two equally profitable companies can report very different EPS — inter-company comparison is its key limitation. IAS 33 standardises the DENOMINATOR, but the earnings numerator still absorbs every accounting-policy choice, and diluted EPS is a warning of POTENTIAL dilution, not a forecast.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR3-C-03",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Aldermere Co revalues its properties annually; its close competitor Bexford Co uses the cost model. Both are otherwise similar. When comparing their ROCE, which statement is correct?",
    options: [
      "Aldermere's ROCE will tend to be lower even if underlying performance is identical, because its capital employed is higher and its depreciation charge larger",
      "Aldermere's ROCE will be higher, because revaluation gains are added to operating profit",
      "There is no effect on ROCE, because revaluations affect only the statement of financial position",
      "The comparison is automatically valid because both policies comply with IFRS Accounting Standards",
    ],
    correct: 0,
    explanation:
      "Revaluation inflates capital employed (via the surplus in equity) AND raises depreciation, so both the denominator rises and the numerator falls — ROCE is depressed relative to a cost-model peer. Revaluation gains go to OCI, not operating profit; the 'balance-sheet only' view forgets the extra depreciation; and two IFRS-compliant policies can still destroy comparability — the analyst must adjust.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-C-04",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Just before its year end, Cranfell Co used $50,000 of cash to pay trade payables earlier than required. Immediately before the payment, current assets were $400,000 and current liabilities $200,000. What is the effect on the current ratio?",
    options: [
      "It is unchanged at 2.0",
      "It increases to 2.33",
      "It decreases to 1.75",
      "It increases to 2.67",
    ],
    correct: 1,
    explanation:
      "Paying $50,000 reduces BOTH sides: $350,000 ÷ $150,000 = 2.33 — because the ratio was already above 1, removing equal amounts flatters it, a classic WINDOW-DRESSING device. 'Unchanged' assumes equal changes cancel (only true at a ratio of exactly 1), 1.75 reduces only the assets ($350,000/$200,000), and 2.67 reduces only the liabilities ($400,000/$150,000).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-C-05",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Talwyn Co ($'000): revenue 730; cost of sales 547.5; year-end inventory 90; trade receivables 120; trade payables 60. Using year-end balances and a 365-day year, what is the working capital cycle?",
    options: ["160 days", "100 days", "90 days", "80 days"],
    correct: 3,
    explanation:
      "Inventory days (90/547.5 × 365 = 60) + receivables days (120/730 × 365 = 60) − payables days (60/547.5 × 365 = 40) = 80 days. 160 ADDS the payables days instead of deducting them, 100 computes receivables days on cost of sales (80 days), and 90 computes payables days on revenue (30 days) — each ratio must use the matching flow.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-C-06",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Which basis is MOST appropriate for assessing the performance of a charity-run vaccination programme (a not-for-profit entity)?",
    options: [
      "Return on capital employed and earnings per share",
      "Dividend cover and the price/earnings ratio",
      "Value for money: the economy, efficiency and effectiveness with which resources were used to achieve the programme's objectives",
      "Growth in revenue and gross profit margin",
    ],
    correct: 2,
    explanation:
      "Not-for-profit performance is judged against OBJECTIVES using the three Es — economy (cheap inputs), efficiency (output per input) and effectiveness (objectives achieved) — because there is no profit motive to anchor ROCE or margins. EPS, dividend cover and P/E need shareholders and distributable profits, and revenue growth says nothing about vaccinations delivered per dollar of funding.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR3-C-07",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Harnley Co's shares are trading at $4.80 and its basic EPS is 32 cents. What is Harnley's price/earnings (P/E) ratio?",
    options: ["15.0", "6.7", "150.0", "1.5"],
    correct: 0,
    explanation:
      "P/E = market price ÷ EPS = $4.80 ÷ $0.32 = 15.0 — the market is paying 15 years' worth of current earnings. 6.7 is the EARNINGS YIELD (the inverse, as a %), 150.0 slips a decimal by treating 32c as 3.2c, and 1.5 makes the opposite conversion error, treating 32c as $3.20.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FR3-C-08",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Ellcott Co's profit for the year is $300,000. During the year it paid preference dividends of $20,000 and ordinary dividends of $70,000. What is Ellcott's dividend cover?",
    options: ["4.3 times", "4.0 times", "4.6 times", "0.25 times"],
    correct: 1,
    explanation:
      "Dividend cover = earnings available to ORDINARY shareholders ÷ ordinary dividends = ($300,000 − $20,000) ÷ $70,000 = 4.0 times. 4.3 forgets to deduct the preference dividends, 4.6 ADDS them instead, and 0.25 inverts the ratio (that is the payout ratio).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FR3-C-09",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Marleigh Co signs 5-year store leases, recognising right-of-use assets and lease liabilities. A rival occupies similar stores under rolling 11-month leases and applies the IFRS 16 short-term exemption. When comparing their ratios, which statement is correct?",
    options: [
      "Marleigh's gearing will be lower, because right-of-use assets strengthen the statement of financial position",
      "There is no effect on any ratio, because IFRS 16 changes disclosure only",
      "Marleigh's profit for the year will always be higher, because rent is no longer an expense",
      "Marleigh will report higher gearing and a higher operating profit margin, so the ratios are not directly comparable",
    ],
    correct: 3,
    explanation:
      "Capitalising leases adds lease liabilities to debt (gearing UP) and replaces rent with depreciation (operating) plus finance cost (below operating), so operating margin also rises — economically similar businesses end up with incomparable ratios. Gearing falls only if you forget the liability side, IFRS 16 is recognition not disclosure, and because the interest charge is front-loaded, early-year PROFIT is typically lower, not higher.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FR3-C-10",
    paper: "FR",
    area: "C",
    type: "mcq",
    stem: "Verlow Co reports operating profit of $110,000 and capital employed of $1,200,000, which includes a revaluation surplus of $200,000; the depreciation charge includes $10,000 arising solely from the revaluation. To compare Verlow with a rival that uses the cost model, an analyst restates Verlow onto a cost basis. What is the restated ROCE?",
    options: ["9.2%", "10.0%", "12.0%", "11.0%"],
    correct: 2,
    explanation:
      "On a cost basis, profit = $110,000 + $10,000 excess depreciation = $120,000 and capital employed = $1,200,000 − $200,000 surplus = $1,000,000, so ROCE = 12.0%. 9.2% is the unadjusted figure, 10.0% adjusts the profit but not the capital ($120,000/$1,200,000), and 11.0% adjusts the capital but not the profit ($110,000/$1,000,000) — both sides must move together.",
    marks: 2,
    difficulty: "hard",
  },
]
