import type { AccaQuestion } from "@/lib/acca-content"

/*
 * TX-UK bank wave 3b — areas C+D+E, 69 verified originals (FA2024/25 basis, 2026-07-10).
 *
 * Tax basis (stated in stems wherever a threshold drives the answer):
 * - Corporation tax: main rate 25%, small profits rate 19%; augmented profits
 *   limits £50,000 / £250,000 (prorated for short periods, divided among
 *   associated companies + the company itself); marginal relief fraction 3/200.
 *   Indexation allowance for companies frozen at December 2017.
 * - VAT: registration threshold £90,000, deregistration threshold £88,000,
 *   standard rate 20%.
 * - IHT: nil-rate band £325,000; residence nil-rate band £175,000 (tapered
 *   above a £2m estate); lifetime rate on CLTs 20% (25% grossed up where the
 *   donor pays); death rate 40%; taper relief 3–4y 20%, 4–5y 40%, 5–6y 60%,
 *   6–7y 80%; annual exemption £3,000.
 *
 * Every question is ORIGINAL (aligned with the public ACCA syllabus only) and
 * every computation has been independently re-solved before inclusion.
 */

export const TX_WAVE2B: AccaQuestion[] = [
  /* ───────────── Area C — Corporation tax (30) ───────────── */
  {
    id: "TX2-C-01", paper: "TX", area: "C", type: "number",
    stem: "Ferndale Ltd's statement of profit or loss shows a profit of £80,000 after charging depreciation of £12,000, entertaining customers of £3,000 and a staff Christmas party costing £1,500. Capital allowances for the period are £9,000. What is the tax-adjusted trading profit in £?",
    numericAnswer: 86000,
    unit: "£",
    explanation: "Add back depreciation £12,000 and customer entertaining £3,000 (both disallowed); the staff party is allowable staff welfare, so no adjustment. Then deduct capital allowances: £80,000 + £12,000 + £3,000 − £9,000 = £86,000.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-C-02", paper: "TX", area: "C", type: "number",
    stem: "Bramwell Ltd's accounting profit for the year is £240,000 after charging depreciation of £35,000, amortisation of purchased goodwill of £10,000 (acquired in 2021) and a qualifying charitable donation of £4,000, and after crediting a profit of £8,000 on the sale of a machine. What is the tax-adjusted trading profit (before capital allowances) in £?",
    numericAnswer: 281000,
    unit: "£",
    explanation: "Add back depreciation £35,000, goodwill amortisation £10,000 (relief for goodwill acquired since 2015 is denied) and the qualifying donation £4,000 (relieved against total profits, not trading profit). Deduct the accounting profit on disposal £8,000 (dealt with via capital allowances/chargeable gains): £240,000 + £35,000 + £10,000 + £4,000 − £8,000 = £281,000.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-C-03", paper: "TX", area: "C", type: "mcq",
    stem: "In computing a company's tax-adjusted trading profit, which of the following expenses IS allowable?",
    options: [
      "A qualifying charitable donation to a national charity",
      "Legal fees on the renewal of a short (50-year or less) lease of business premises",
      "A fine for a breach of health and safety regulations",
      "Depreciation of office equipment",
    ],
    correct: 1,
    explanation: "Legal fees on renewing a short lease are allowable as a trading expense. Qualifying charitable donations are deducted from total profits (not trading profit), fines for law-breaking are disallowed, and depreciation is always added back (capital allowances are given instead).",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-C-04", paper: "TX", area: "C", type: "number",
    stem: "Kestrel Ltd (12-month period) has a main pool tax written down value brought forward of £40,000. During the period it bought second-hand machinery for £20,000 and a car with CO2 emissions of 30g/km for £15,000. The annual investment allowance (AIA) limit is £1,000,000; cars never qualify for AIA; cars with emissions of 1–50g/km go to the main pool (WDA 18%). What are the total capital allowances for the period in £?",
    numericAnswer: 29900,
    unit: "£",
    explanation: "AIA covers the machinery in full: £20,000. The car cannot take AIA, so it joins the main pool: (£40,000 + £15,000) × 18% = £9,900. Total = £20,000 + £9,900 = £29,900.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-C-05", paper: "TX", area: "C", type: "number",
    stem: "Osprey Ltd (12-month period) has a main pool brought forward of £100,000 (WDA 18%) and a special rate pool brought forward of £30,000 (WDA 6%). There were no additions or disposals. What are the total capital allowances for the period in £?",
    numericAnswer: 19800,
    unit: "£",
    explanation: "Main pool: £100,000 × 18% = £18,000. Special rate pool: £30,000 × 6% = £1,800. Total = £19,800.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-C-06", paper: "TX", area: "C", type: "number",
    stem: "Harrier Ltd prepares accounts for the NINE months to 31 December 2024. The main pool brought forward is £80,000 (WDA 18% per annum) and the company bought machinery for £50,000 (covered by the AIA, whose £1,000,000 annual limit is time-apportioned). What are the total capital allowances for the nine-month period in £?",
    numericAnswer: 60800,
    unit: "£",
    explanation: "WDAs are time-apportioned for a short period: £80,000 × 18% × 9/12 = £10,800. The AIA limit is prorated to £750,000, which easily covers the £50,000 addition in full. Total = £50,000 + £10,800 = £60,800. (AIA itself is not scaled down — only its limit is.)",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-C-07", paper: "TX", area: "C", type: "mcq",
    stem: "Which of the following additions qualifies for the annual investment allowance (AIA)?",
    options: [
      "A new car with zero CO2 emissions",
      "The purchase of freehold land for a new depot",
      "The structural cost of constructing a new warehouse",
      "A second-hand delivery van",
    ],
    correct: 3,
    explanation: "Vans are plant and machinery, so the van qualifies for AIA (second-hand assets are fine). Cars NEVER qualify for AIA (a new zero-emission car gets a 100% first-year allowance instead), land gets no allowances at all, and building structure is relieved through the structures and buildings allowance, not AIA.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-C-08", paper: "TX", area: "C", type: "number",
    stem: "Wren Ltd has taxable total profits of £40,000 for its 12-month period and receives no dividends. It has no associated companies. With a small profits rate of 19% below the £50,000 lower limit, what is the corporation tax liability in £?",
    numericAnswer: 7600,
    unit: "£",
    explanation: "Augmented profits of £40,000 are below the £50,000 lower limit, so the small profits rate applies: £40,000 × 19% = £7,600.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-C-09", paper: "TX", area: "C", type: "number",
    stem: "Dunlin Ltd has taxable total profits of £100,000 for its 12-month period, receives no dividends and has no associated companies. The main rate is 25%, the upper limit is £250,000 and the marginal relief fraction is 3/200. What is the corporation tax liability in £?",
    numericAnswer: 22750,
    unit: "£",
    explanation: "Tax at the main rate: £100,000 × 25% = £25,000. Marginal relief = (£250,000 − £100,000) × 3/200 = £2,250. Liability = £25,000 − £2,250 = £22,750.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-C-10", paper: "TX", area: "C", type: "number",
    stem: "Merlin Ltd has taxable total profits of £160,000 and received exempt dividends of £40,000 from non-group companies in its 12-month period. It has no associated companies. Main rate 25%, limits £50,000/£250,000, marginal relief fraction 3/200. What is the corporation tax liability in £?",
    numericAnswer: 39400,
    unit: "£",
    explanation: "Augmented profits = £160,000 + £40,000 = £200,000 (between the limits). Marginal relief = (£250,000 − £200,000) × 3/200 × (£160,000/£200,000) = £750 × 0.8 = £600. Liability = £160,000 × 25% − £600 = £39,400. Dividends increase augmented profits but are not themselves taxed.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-C-11", paper: "TX", area: "C", type: "number",
    stem: "Teal Ltd has taxable total profits of £200,000 and received exempt dividends of £50,000 from unconnected companies in its 12-month period. It has no associated companies. Main rate 25%, upper limit £250,000, marginal relief fraction 3/200. What is the corporation tax liability in £?",
    numericAnswer: 50000,
    unit: "£",
    explanation: "Augmented profits = £200,000 + £50,000 = £250,000, which is NOT below the £250,000 upper limit, so no marginal relief is due. Tax = £200,000 × 25% = £50,000. (Marginal relief only applies where augmented profits are between the limits, i.e. strictly below £250,000.)",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-C-12", paper: "TX", area: "C", type: "number",
    stem: "Plover Ltd has ONE associated company throughout its 12-month period. Its taxable total profits are £130,000 and it receives no dividends. The limits of £50,000 and £250,000 are divided by the number of associated companies plus one. Main rate 25%, small profits rate 19%, marginal relief fraction 3/200. What is Plover Ltd's corporation tax liability in £?",
    numericAnswer: 32500,
    unit: "£",
    explanation: "With one associate the limits are halved to £25,000 and £125,000. Augmented profits of £130,000 exceed the £125,000 upper limit, so the full main rate applies with no marginal relief: £130,000 × 25% = £32,500.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-C-13", paper: "TX", area: "C", type: "number",
    stem: "Sanderling Ltd has THREE associated companies throughout its 12-month period. Its taxable total profits are £70,000 with no dividends received. The £50,000/£250,000 limits are divided by the number of associated companies plus one; main rate 25%, small profits rate 19%. What is Sanderling Ltd's corporation tax liability in £?",
    numericAnswer: 17500,
    unit: "£",
    explanation: "The limits are divided by 4 (three associates plus the company): lower £12,500, upper £62,500. Augmented profits of £70,000 exceed £62,500, so the main rate applies in full: £70,000 × 25% = £17,500.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-C-14", paper: "TX", area: "C", type: "number",
    stem: "Avocet Ltd was incorporated and traded for a SIX-month accounting period. Its taxable total profits are £20,000 with no dividends and no associated companies. The £50,000/£250,000 limits are time-apportioned for short periods; small profits rate 19%, main rate 25%. What is the corporation tax liability in £?",
    numericAnswer: 3800,
    unit: "£",
    explanation: "For a six-month period the limits become £25,000 and £125,000. Augmented profits of £20,000 are below the £25,000 lower limit, so the small profits rate applies: £20,000 × 19% = £3,800.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-C-15", paper: "TX", area: "C", type: "number",
    stem: "Gadwall Ltd sold an investment property in March 2025 for £120,000. The property cost £50,000 in May 2005. The indexation factor from May 2005 to December 2017 (when indexation allowance was frozen) is 0.437. What is the chargeable gain in £?",
    numericAnswer: 48150,
    unit: "£",
    explanation: "Indexation allowance = £50,000 × 0.437 = £21,850, computed only up to December 2017 even though the disposal is in 2025. Gain = £120,000 − £50,000 − £21,850 = £48,150.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-C-16", paper: "TX", area: "C", type: "number",
    stem: "Pochard Ltd sold a warehouse for £85,000. It cost £80,000 in 2001, and the indexation factor to December 2017 is 0.350. What is the chargeable gain in £? (Enter 0 if there is no gain.)",
    numericAnswer: 0,
    unit: "£",
    explanation: "The unindexed gain is £85,000 − £80,000 = £5,000. Full indexation would be £80,000 × 0.350 = £28,000, but indexation allowance can only reduce a gain to nil — it cannot create or increase a loss. It is therefore restricted to £5,000, leaving a chargeable gain of £0 (and no allowable loss).",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-C-17", paper: "TX", area: "C", type: "mcq",
    stem: "Smew Ltd bought a chargeable asset in June 2019 and sold it at a profit in February 2025. How is indexation allowance applied to this disposal?",
    options: [
      "No indexation allowance is available because the asset was acquired after December 2017",
      "Indexation runs from June 2019 to the date of sale",
      "Indexation runs from June 2019 to December 2017, applied as a negative amount",
      "Indexation runs from December 2017 to the date of sale",
    ],
    correct: 0,
    explanation: "Indexation allowance was frozen at December 2017. Assets acquired after that date receive no indexation at all. Indexing to the sale date ignores the freeze, and indexation is never applied as a negative amount or from the freeze date forwards.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-C-18", paper: "TX", area: "C", type: "number",
    stem: "In its year ended 31 March 2025 Scaup Ltd made a chargeable gain of £30,000 and a current-year capital loss of £5,000, and has capital losses brought forward of £8,000. What amount of net chargeable gains is included in taxable total profits in £?",
    numericAnswer: 17000,
    unit: "£",
    explanation: "Current-year capital losses are set against gains of the same period, then brought-forward capital losses: £30,000 − £5,000 − £8,000 = £17,000. A company's capital losses can only ever be used against chargeable gains, not trading profits.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-C-19", paper: "TX", area: "C", type: "number",
    stem: "Redshank Ltd made a trading loss of £60,000 in its year ended 31 March 2025. In the same year it had property business income of £20,000 and a chargeable gain of £15,000. It claims current-period relief against total profits only (no carry-back). What trading loss is carried forward in £?",
    numericAnswer: 25000,
    unit: "£",
    explanation: "The current-period claim relieves the loss against TOTAL profits — property income and gains included: £20,000 + £15,000 = £35,000 relieved. Carried forward = £60,000 − £35,000 = £25,000.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-C-20", paper: "TX", area: "C", type: "number",
    stem: "Godwit Ltd made a trading loss of £80,000 in its year ended 31 March 2025, when it had no other income or gains. Its taxable total profits for the year ended 31 March 2024 were £50,000. It makes a current-period claim followed by a 12-month carry-back claim. What loss remains to carry forward in £?",
    numericAnswer: 30000,
    unit: "£",
    explanation: "The current-period claim relieves nothing (no other profits). The carry-back is limited to the prior year's total profits of £50,000. Carried forward = £80,000 − £50,000 = £30,000, available against future total profits.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-C-21", paper: "TX", area: "C", type: "mcq",
    stem: "Curlew Ltd wants to claim current-period relief for a trading loss against total profits, but doing so would waste its qualifying charitable donations. Which statement is correct?",
    options: [
      "The claim can be restricted to leave profits equal to the charitable donations",
      "The charitable donations can be carried forward instead and relieved next year",
      "The claim is all-or-nothing: it must be for the full loss up to available total profits, even if donations are wasted",
      "The charitable donations are converted into a trading loss and carried forward",
    ],
    correct: 2,
    explanation: "A current-period (and carry-back) loss claim against total profits cannot be restricted — it is all-or-nothing, so qualifying charitable donations may be wasted. Partial claims are not allowed, unrelieved donations cannot be carried forward, and donations never convert into trading losses.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-C-22", paper: "TX", area: "C", type: "number",
    stem: "Snipe Ltd owns 100% of Dotterel Ltd; both prepare accounts to 31 March 2025. Dotterel Ltd made a trading loss of £40,000 and surrenders the maximum possible as group relief. Snipe Ltd has taxable total profits of £100,000 before group relief. What are Snipe Ltd's taxable total profits after group relief in £?",
    numericAnswer: 60000,
    unit: "£",
    explanation: "The full £40,000 loss can be surrendered (it is below Snipe Ltd's available total profits): £100,000 − £40,000 = £60,000.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-C-23", paper: "TX", area: "C", type: "mcq",
    stem: "Lapwing Ltd has a trading loss. To which of the following companies could the loss be surrendered as group relief?",
    options: [
      "A company in which Lapwing Ltd owns 60% of the ordinary shares",
      "A company which owns 80% of Lapwing Ltd's ordinary shares",
      "A consortium member holding 40% of Lapwing Ltd",
      "An unrelated company owned by the same individual shareholder",
    ],
    correct: 1,
    explanation: "Group relief requires a 75% group relationship (direct or indirect). An 80% parent qualifies. A 60% holding fails the 75% test, 40% is only consortium territory (different, more restricted rules), and common ownership by an individual does not create a group-relief group.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-C-24", paper: "TX", area: "C", type: "number",
    stem: "Brambling Ltd acquired 100% of Twite Ltd on 1 January 2025. Both companies prepare accounts to 31 March 2025. For that year Twite Ltd made a trading loss of £48,000 and Brambling Ltd had taxable total profits of £100,000, both accruing evenly. What is the MAXIMUM group relief Twite Ltd can surrender to Brambling Ltd in £?",
    numericAnswer: 12000,
    unit: "£",
    explanation: "Group relief is only available for the overlapping period of group membership — the 3 months from 1 January to 31 March 2025. Maximum surrender = lower of the loss of the overlap (£48,000 × 3/12 = £12,000) and the claimant's profits of the overlap (£100,000 × 3/12 = £25,000), i.e. £12,000.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-C-25", paper: "TX", area: "C", type: "number",
    stem: "Whimbrel Ltd prepared accounts for the 15 months to 30 June 2025, so the period is split into a 12-month accounting period and a 3-month accounting period. Trading profit before capital allowances for the whole 15 months is £150,000, accruing evenly. What trading profit (before capital allowances) is allocated to the SECOND (3-month) accounting period in £?",
    numericAnswer: 30000,
    unit: "£",
    explanation: "Trading profit before capital allowances is time-apportioned across the two accounting periods: £150,000 × 3/15 = £30,000. (Capital allowances are then computed separately for each period.)",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-C-26", paper: "TX", area: "C", type: "mcq",
    stem: "A company prepares accounts for an 18-month period, which is split into two accounting periods for corporation tax. How is a chargeable gain allocated between the two periods?",
    options: [
      "Time-apportioned across the two periods",
      "Always allocated to the first 12-month period",
      "Allocated to the period in which the disposal actually occurs",
      "Allocated by election of the company",
    ],
    correct: 2,
    explanation: "Chargeable gains (like property income received and charitable donations paid) are allocated to the accounting period in which they arise — the date of disposal. Only trading profits (before capital allowances) are time-apportioned; there is no first-period default and no election.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-C-27", paper: "TX", area: "C", type: "mcq",
    stem: "Stonechat Ltd is not a large company. For its accounting period ended 31 March 2025, by what date must its corporation tax be PAID?",
    options: [
      "1 January 2026",
      "31 December 2025",
      "31 March 2026",
      "14 October 2025",
    ],
    correct: 0,
    explanation: "Companies that are not large pay corporation tax 9 months and 1 day after the end of the accounting period: 31 March 2025 + 9 months + 1 day = 1 January 2026. 31 December 2025 forgets the extra day, 31 March 2026 is the FILING deadline, and 14 October 2025 confuses this with a quarterly instalment date.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-C-28", paper: "TX", area: "C", type: "mcq",
    stem: "Wheatear Ltd prepared accounts for the year ended 30 June 2025. By what date must its corporation tax RETURN be filed?",
    options: [
      "1 April 2026",
      "31 January 2026",
      "30 June 2027",
      "30 June 2026",
    ],
    correct: 3,
    explanation: "The corporation tax return is due 12 months after the end of the period of account: 30 June 2026. 1 April 2026 approximates the payment date (9 months + 1 day), 31 January is the self-assessment deadline for individuals, and 30 June 2027 adds an extra year.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-C-29", paper: "TX", area: "C", type: "number",
    stem: "Bittern Ltd is a large company (augmented profits above £1,500,000) with an estimated corporation tax liability of £800,000 for its year ended 31 March 2025. It pays by quarterly instalments. What is the amount of EACH quarterly instalment in £?",
    numericAnswer: 200000,
    unit: "£",
    explanation: "Large companies pay in four equal instalments: £800,000 ÷ 4 = £200,000, due on the 14th day of months 7, 10, 13 and 16 from the START of the period (14 October 2024, 14 January 2025, 14 April 2025 and 14 July 2025) — the first two fall during the accounting period itself.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-C-30", paper: "TX", area: "C", type: "number",
    stem: "Nightjar Ltd prepared accounts for the NINE months to 31 December 2024, with taxable total profits of £87,500 and no dividends or associated companies. The £50,000/£250,000 limits are time-apportioned for short periods; main rate 25%, marginal relief fraction 3/200. What is the corporation tax liability in £?",
    numericAnswer: 20375,
    unit: "£",
    explanation: "For nine months the limits become £37,500 and £187,500. Augmented profits of £87,500 fall between them, so marginal relief applies: tax at 25% = £21,875, less (£187,500 − £87,500) × 3/200 = £1,500. Liability = £20,375. Using unprorated limits would wrongly give the small profits computation.",
    marks: 2, difficulty: "hard",
  },

  /* ───────────── Area D — Value added tax (21) ───────────── */
  {
    id: "TX2-D-01", paper: "TX", area: "D", type: "number",
    stem: "Hollis Interiors Ltd, a VAT-registered business, makes standard-rated sales of £48,000 (VAT-exclusive) in a quarter. With a standard rate of 20%, what is the output VAT for the quarter in £?",
    numericAnswer: 9600,
    unit: "£",
    explanation: "Output VAT on a VAT-exclusive amount is simply 20%: £48,000 × 20% = £9,600.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-D-02", paper: "TX", area: "D", type: "number",
    stem: "Marlow Tools Ltd invoices customers a total of £54,000 INCLUDING VAT at the standard rate of 20% during a quarter. What is the output VAT for the quarter in £?",
    numericAnswer: 9000,
    unit: "£",
    explanation: "For a VAT-inclusive figure, apply the VAT fraction 20/120 (i.e. 1/6): £54,000 × 20/120 = £9,000. Applying 20% directly to the gross amount (£10,800) double-counts the VAT.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-D-03", paper: "TX", area: "D", type: "mcq",
    stem: "Priya's taxable supplies for the 12 months ended 31 August 2024 exceeded the £90,000 registration threshold for the first time (the historic test). She is not expected to fall below the deregistration threshold. From what date is she registered for VAT?",
    options: [
      "31 August 2024, the date the threshold was exceeded",
      "30 September 2024, the date by which she must notify HMRC",
      "1 October 2024, the first day of the second month after the threshold was exceeded",
      "1 September 2024, the first day of the month after the threshold was exceeded",
    ],
    correct: 2,
    explanation: "Under the historic test HMRC must be notified within 30 days of the end of the month in which the threshold is exceeded (by 30 September), and registration takes effect from the START of the month AFTER that — 1 October 2024. The exceeding date and notification date are compliance dates, not the effective date, and 1 September skips the notification month.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-D-04", paper: "TX", area: "D", type: "number",
    stem: "In a quarter, Larkspur Ltd (fully taxable) incurs: purchases of goods £20,000 net (VAT £4,000); a new car for its sales director, available for private use (VAT £4,000); entertaining UK clients (VAT £240); and entertaining its own staff (VAT £120). How much input VAT is recoverable in £?",
    numericAnswer: 4120,
    unit: "£",
    explanation: "Recoverable: purchases £4,000 + staff entertaining £120 = £4,120. Input VAT is blocked on cars available for any private use and on UK business (client) entertaining; staff entertaining is specifically NOT blocked.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-D-05", paper: "TX", area: "D", type: "number",
    stem: "In a quarter, Foxglove Ltd makes standard-rated sales of £150,000 (net) and zero-rated sales of £20,000. It incurs input VAT of £12,000 on purchases, £2,000 on new machinery and £300 on entertaining UK customers. Standard rate 20%. What is the net VAT payable to HMRC in £?",
    numericAnswer: 16000,
    unit: "£",
    explanation: "Output VAT = £150,000 × 20% = £30,000 (zero-rated sales carry 0% but full input recovery). Recoverable input VAT = £12,000 + £2,000 = £14,000; the £300 on UK customer entertaining is blocked. Net payable = £30,000 − £14,000 = £16,000.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-D-06", paper: "TX", area: "D", type: "mcq",
    stem: "On which of the following purchases can a fully taxable business recover input VAT in full?",
    options: [
      "A delivery van used wholly in the business",
      "A car available for an employee's private use",
      "Entertaining UK customers at a trade show",
      "Goods bought for a director's personal use",
    ],
    correct: 0,
    explanation: "Input VAT on a van used for business is fully recoverable. Recovery is blocked on cars with any private availability and on UK business entertaining, and goods for private (non-business) use are not incurred for the business at all.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-D-07", paper: "TX", area: "D", type: "number",
    stem: "Wisteria Ltd provides fuel for the private motoring of a director and recovers all input VAT on fuel. The VAT-INCLUSIVE quarterly fuel scale charge for the car is £450. What output VAT must be accounted for on the scale charge for the quarter in £?",
    numericAnswer: 75,
    unit: "£",
    explanation: "The scale charge is VAT-inclusive, so output VAT = £450 × 20/120 = £75. The scale charge compensates for private fuel while allowing full input VAT recovery on all fuel purchased; applying 20% to £450 (£90) treats an inclusive figure as exclusive.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-D-08", paper: "TX", area: "D", type: "mcq",
    stem: "What is the principal cash-flow advantage of the CASH ACCOUNTING scheme for a business whose customers pay slowly?",
    options: [
      "Input VAT can be recovered as soon as a purchase invoice is received",
      "Output VAT is not due to HMRC until the customer actually pays, giving automatic relief for irrecoverable debts",
      "VAT is calculated as a flat percentage of turnover with no invoice records",
      "Only one VAT return is required each year",
    ],
    correct: 1,
    explanation: "Under cash accounting VAT is accounted for on cash paid and received, so output tax is deferred until receipt — and if the customer never pays, no output VAT is ever due (automatic bad debt relief). Input recovery is actually DELAYED until payment, the flat percentage describes the flat rate scheme, and one annual return describes the annual accounting scheme.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-D-09", paper: "TX", area: "D", type: "number",
    stem: "Rowan, a consultant, uses the flat rate scheme with a flat rate percentage of 12%. His VAT-INCLUSIVE turnover for the quarter is £84,000. What VAT is payable to HMRC for the quarter in £?",
    numericAnswer: 10080,
    unit: "£",
    explanation: "Under the flat rate scheme the percentage is applied to VAT-INCLUSIVE turnover: £84,000 × 12% = £10,080. No input VAT is recovered (except on certain capital items costing over £2,000). Applying the rate to a net figure understates the liability.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-D-10", paper: "TX", area: "D", type: "number",
    stem: "Bryony uses the flat rate scheme. Her spending on relevant goods is under 2% of turnover, making her a 'limited cost trader' with a flat rate of 16.5%. Her VAT-inclusive turnover for the quarter is £60,000. What VAT is payable for the quarter in £?",
    numericAnswer: 9900,
    unit: "£",
    explanation: "Limited cost traders must use 16.5% regardless of their sector rate: £60,000 × 16.5% = £9,900. Using the ordinary sector percentage ignores the limited cost trader override.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-D-11", paper: "TX", area: "D", type: "mcq",
    stem: "Nadia's sales have declined. With a deregistration threshold of £88,000 and a registration threshold of £90,000, when may she VOLUNTARILY deregister for VAT?",
    options: [
      "Only when her taxable supplies in the PREVIOUS 12 months have fallen below £90,000",
      "She must deregister automatically as soon as monthly sales fall",
      "Only after remaining registered for at least two further years",
      "When she satisfies HMRC that her expected taxable supplies in the NEXT 12 months will not exceed £88,000",
    ],
    correct: 3,
    explanation: "Voluntary deregistration uses a FORWARD-looking test: expected taxable supplies in the next 12 months of £88,000 or less. The historic (backward) test is for registration, not deregistration; deregistration on falling sales is optional, not automatic; and there is no two-year minimum.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-D-12", paper: "TX", area: "D", type: "number",
    stem: "Aster Ltd registered for VAT on 1 May 2025. Before registration it incurred input VAT of: £2,000 on goods bought in 2023 and still held at registration; £500 on goods bought in 2019 and since sold; £400 on services received in January 2025; and £300 on services received in July 2024. Pre-registration input VAT is recoverable on goods bought within 4 years (still held) and services within 6 months. How much is recoverable in £?",
    numericAnswer: 2400,
    unit: "£",
    explanation: "Goods 2023 (£2,000): within 4 years and still held — recoverable. Goods 2019 (£500): outside 4 years and no longer held — not recoverable. Services January 2025 (£400): within 6 months — recoverable. Services July 2024 (£300): more than 6 months before registration — not recoverable. Total = £2,400.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-D-13", paper: "TX", area: "D", type: "mcq",
    stem: "Juniper Ltd delivered goods to a customer on 20 March, issued the VAT invoice on 28 March and received payment on 30 April. What is the tax point of the supply?",
    options: [
      "20 March, the date the goods were delivered",
      "28 March, the date the invoice was issued",
      "30 April, the date payment was received",
      "31 March, the end of the VAT quarter",
    ],
    correct: 1,
    explanation: "The basic tax point is delivery (20 March), but because the invoice was issued within 14 days after delivery, the invoice date of 28 March becomes the actual tax point. Payment after delivery does not move the tax point, and quarter-ends are never tax points.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-D-14", paper: "TX", area: "D", type: "number",
    stem: "Sorrel Ltd discovers it under-declared output VAT on a previous return. Its annual turnover is £2,400,000. A net error can be corrected on the next VAT return if it does not exceed the HIGHER of £10,000 and 1% of turnover, capped at £50,000. What is the maximum net error Sorrel Ltd can correct on its next return in £?",
    numericAnswer: 24000,
    unit: "£",
    explanation: "1% of turnover = £2,400,000 × 1% = £24,000, which is higher than £10,000 and below the £50,000 cap, so the limit is £24,000. Larger errors must be separately disclosed to HMRC. Using £10,000 ignores the turnover-based alternative; using £50,000 applies the cap without earning it.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-D-15", paper: "TX", area: "D", type: "number",
    stem: "Under the points-based late submission regime, a quarterly VAT filer receives one point per late return and a fixed penalty once it reaches 4 points. Clover Ltd, a quarterly filer, files late for the fourth time and reaches the points threshold. What fixed penalty is charged in £?",
    numericAnswer: 200,
    unit: "£",
    explanation: "Reaching the points threshold (4 points for quarterly filers) triggers a fixed £200 penalty, and each further late return while at the threshold triggers another £200. The penalty is for late FILING and applies even if the VAT itself was paid on time.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-D-16", paper: "TX", area: "D", type: "number",
    stem: "Tansy Ltd owed VAT of £10,000 which it paid in full 25 days after the due date, with no time-to-pay arrangement. Under the late payment penalty rules, a first penalty of 2% is charged on the amount outstanding at day 15 (with a further 2% on any amount still outstanding at day 30). What late payment penalty is charged in £?",
    numericAnswer: 200,
    unit: "£",
    explanation: "The full £10,000 was still outstanding at day 15, so the first penalty is £10,000 × 2% = £200. Because payment was made on day 25 — before day 30 — no further 2% arises. (Late payment interest runs in addition from the due date.)",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-D-17", paper: "TX", area: "D", type: "mcq",
    stem: "Yarrow Ltd files quarterly VAT returns online and pays electronically (it is not in the payments-on-account or annual accounting regimes). For its quarter ended 31 March, when are the return and payment due?",
    options: [
      "30 April, one month after the quarter end",
      "7 April, seven days after the quarter end",
      "7 May, one month and seven days after the quarter end",
      "31 May, two months after the quarter end",
    ],
    correct: 2,
    explanation: "Online VAT returns and electronic payments are due one month and seven days after the end of the return period: 31 March + 1 month + 7 days = 7 May. One month exactly omits the 7-day extension; the other dates have no basis.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-D-18", paper: "TX", area: "D", type: "number",
    stem: "Campion Ltd joins the ANNUAL accounting scheme. Its VAT liability for the previous year was £18,000. Under the scheme it makes nine monthly payments on account, each of 10% of the prior year's liability, with a balancing payment on filing. What is the amount of EACH payment on account in £?",
    numericAnswer: 1800,
    unit: "£",
    explanation: "Each of the nine instalments is 10% of the previous year's liability: £18,000 × 10% = £1,800 (paid in months 4 to 12), with any balance due with the single annual return two months after the year end.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-D-19", paper: "TX", area: "D", type: "number",
    stem: "Betony Ltd sells goods for £10,000 (VAT-exclusive) offering a 5% prompt payment discount. The customer pays promptly and takes the discount. Standard rate 20%. What output VAT must Betony Ltd account for in £?",
    numericAnswer: 1900,
    unit: "£",
    explanation: "VAT is due on the consideration ACTUALLY received: £10,000 × 95% = £9,500, so VAT = £9,500 × 20% = £1,900. Charging VAT on the full £10,000 (£2,000) ignores that the discount was taken.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-D-20", paper: "TX", area: "D", type: "number",
    stem: "Vervain Ltd is owed £3,600 (including VAT at 20%) by a customer. The debt is more than six months overdue since the due date for payment, has been written off in the accounts, and the output VAT was paid to HMRC. How much VAT can Vervain Ltd reclaim as irrecoverable (bad) debt relief in £?",
    numericAnswer: 600,
    unit: "£",
    explanation: "All conditions for relief are met (6+ months overdue, written off, output tax accounted for). The reclaim is the VAT element of the gross debt: £3,600 × 20/120 = £600. Taking 20% of £3,600 (£720) treats the inclusive debt as net.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-D-21", paper: "TX", area: "D", type: "number",
    stem: "In a quarter, Tormentil Ltd has output VAT of £20,000 on its sales. Its input VAT comprises £8,000 on trading purchases, £150 on repairs to a car used partly for private motoring by an employee (fuel not provided), and £200 on entertaining UK clients. What is the net VAT payable to HMRC in £?",
    numericAnswer: 11850,
    unit: "£",
    explanation: "Input VAT on car REPAIRS and maintenance is fully recoverable even where there is private use (unlike VAT on the purchase of the car itself), so recoverable input = £8,000 + £150 = £8,150; the client entertaining £200 is blocked. Net VAT = £20,000 − £8,150 = £11,850.",
    marks: 2, difficulty: "hard",
  },

  /* ───────────── Area E — Inheritance tax (18) ───────────── */
  {
    id: "TX2-E-01", paper: "TX", area: "E", type: "number",
    stem: "In June 2024 Hana gave £10,000 cash to her daughter. She had made no gifts in 2023/24 or 2024/25 before this. With an annual exemption of £3,000 (unused amounts carried forward one year), what is the value of the potentially exempt transfer (PET) after exemptions in £?",
    numericAnswer: 4000,
    unit: "£",
    explanation: "The 2024/25 annual exemption of £3,000 applies first, then the unused 2023/24 exemption of £3,000 brought forward: £10,000 − £3,000 − £3,000 = £4,000 PET.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-E-02", paper: "TX", area: "E", type: "mcq",
    stem: "Which of the following lifetime gifts by an individual is a CHARGEABLE LIFETIME TRANSFER (CLT)?",
    options: [
      "A gift of £50,000 cash to a nephew",
      "A gift of £50,000 to the donor's UK-domiciled spouse",
      "A gift of £50,000 to a registered charity",
      "A gift of £50,000 into a discretionary trust",
    ],
    correct: 3,
    explanation: "Gifts into most trusts (including discretionary trusts) are CLTs, chargeable immediately at the lifetime rate. Gifts to individuals are PETs (only chargeable if the donor dies within 7 years), while transfers to a UK-domiciled spouse and to charity are wholly exempt.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-E-03", paper: "TX", area: "E", type: "number",
    stem: "In 2024/25 Marcus transfers £400,000 (after all exemptions) into a discretionary trust and agrees that HE will pay the lifetime IHT. He has made no previous transfers, so the full £325,000 nil-rate band is available. The lifetime rate is 20% (25% of the net transfer where the donor pays). What lifetime IHT is payable in £?",
    numericAnswer: 18750,
    unit: "£",
    explanation: "Excess over the nil-rate band = £400,000 − £325,000 = £75,000. Because Marcus pays, the transfer is net and must be grossed up: tax = £75,000 × 20/80 (i.e. 25%) = £18,750. Using a flat 20% (£15,000) forgets the gross-up when the DONOR bears the tax.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-E-04", paper: "TX", area: "E", type: "number",
    stem: "In 2024/25 Elif transfers £400,000 (after all exemptions) into a discretionary trust and the TRUSTEES agree to pay the lifetime IHT. She has made no previous transfers, so the full £325,000 nil-rate band is available; the lifetime rate is 20%. What lifetime IHT is payable in £?",
    numericAnswer: 15000,
    unit: "£",
    explanation: "Where the trustees pay, the transfer is already gross: (£400,000 − £325,000) × 20% = £15,000. Grossing up at 20/80 (£18,750) would be the answer only if the DONOR paid the tax.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-E-05", paper: "TX", area: "E", type: "number",
    stem: "In August 2024 Deniz gave his son £20,000 on the occasion of the son's wedding. Deniz had made no other gifts in 2023/24 or 2024/25. The marriage exemption for a gift from a parent is £5,000 and the annual exemption is £3,000 (with one-year carry-forward). What is the value of the PET after exemptions in £?",
    numericAnswer: 9000,
    unit: "£",
    explanation: "Deduct the £5,000 parental marriage exemption, then the current year annual exemption £3,000 and the brought-forward £3,000: £20,000 − £5,000 − £3,000 − £3,000 = £9,000.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-E-06", paper: "TX", area: "E", type: "mcq",
    stem: "The small gifts exemption covers outright gifts of up to £250 per donee per tax year. Which of the following is fully covered by the exemption?",
    options: [
      "Gifts of £250 each to ten different grandchildren, with nothing else given to them in the year",
      "The first £250 of a single gift of £1,000 to a friend",
      "A gift of £250 to a son who also received £5,000 from the donor earlier in the same tax year",
      "A gift of £400 to a niece, exempt as to £250 with only £150 taxable",
    ],
    correct: 0,
    explanation: "The exemption applies per donee with no limit on the number of donees, so ten gifts of £250 are all exempt. It is all-or-nothing: it cannot shelter part of a larger gift, and it is lost entirely if total gifts to that donee in the year exceed £250.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-E-07", paper: "TX", area: "E", type: "mcq",
    stem: "Which of the following gifts is most likely to qualify for the NORMAL EXPENDITURE OUT OF INCOME exemption?",
    options: [
      "A one-off gift of £40,000 from the proceeds of selling shares",
      "An annual gift of £8,000 funded by drawing down savings capital each year",
      "A regular monthly payment of £500 to a daughter from surplus salary, leaving the donor's standard of living unaffected",
      "Any gift of up to £3,000 per tax year",
    ],
    correct: 2,
    explanation: "The exemption requires a habitual pattern, funding out of INCOME (not capital), and that the donor's usual standard of living is maintained — the regular £500 from surplus salary meets all three. One-off gifts fail the habitual test, capital-funded gifts fail the income test, and 'up to £3,000' describes the separate annual exemption.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-E-08", paper: "TX", area: "E", type: "number",
    stem: "In January 2020 Priska made a PET of £500,000 (after all exemptions) to her son, having made no earlier gifts. She died in July 2024 — between 4 and 5 years after the gift. The nil-rate band at death is £325,000, the death rate is 40%, and taper relief for 4–5 years is a 40% reduction. What IHT is payable on the PET as a result of death in £?",
    numericAnswer: 42000,
    unit: "£",
    explanation: "Tax before taper = (£500,000 − £325,000) × 40% = £70,000. Taper relief reduces the TAX by 40%: £70,000 × 60% = £42,000. Taper relief reduces the tax, never the value of the gift, and it only exists because death occurred more than 3 years after the transfer.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-E-09", paper: "TX", area: "E", type: "number",
    stem: "Rafael made a gross chargeable lifetime transfer (CLT) of £200,000 into a trust in May 2018, and a PET of £300,000 (after exemptions) to his daughter in March 2022. He died in May 2025. The nil-rate band at death is £325,000; the death rate is 40%; taper relief for death 3–4 years after a gift is a 20% reduction. What IHT is payable on the PET as a result of death in £?",
    numericAnswer: 56000,
    unit: "£",
    explanation: "For death tax on the PET, cumulate gross chargeable transfers in the 7 years BEFORE the PET: the May 2018 CLT of £200,000 uses that much nil-rate band, leaving £325,000 − £200,000 = £125,000. Tax = (£300,000 − £125,000) × 40% = £70,000; death was 3–4 years after the PET, so taper relief of 20% applies: £70,000 × 80% = £56,000. Giving the PET the full nil-rate band ignores the earlier CLT's chronological priority.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-E-10", paper: "TX", area: "E", type: "number",
    stem: "In October 2019 Ingrid made a gross CLT of £400,000 into a trust (no earlier transfers); the trustees paid lifetime IHT of £15,000. Ingrid died in April 2025 — between 5 and 6 years later. Nil-rate band at death £325,000; death rate 40%; taper relief for 5–6 years is a 60% reduction; lifetime tax paid is credited but never repaid. What ADDITIONAL IHT is payable on the CLT as a result of death in £? (Enter 0 if none.)",
    numericAnswer: 0,
    unit: "£",
    explanation: "Death tax = (£400,000 − £325,000) × 40% = £30,000; after 60% taper relief this is £30,000 × 40% = £12,000. The £15,000 lifetime tax already paid exceeds £12,000, so no additional tax is due — and the £3,000 excess is NOT refunded. Answer: £0.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-E-11", paper: "TX", area: "E", type: "number",
    stem: "Tomas died in 2024/25 leaving his whole estate to his son: a house worth £400,000 (with an outstanding repayment mortgage of £100,000), plus bank accounts and investments of £250,000. Funeral expenses were £5,000. He made no lifetime gifts. The nil-rate band is £325,000 and the residence nil-rate band is £175,000 (the house passes to a direct descendant; the estate is below £2m). What IHT is payable on the death estate in £?",
    numericAnswer: 18000,
    unit: "£",
    explanation: "Chargeable estate = £400,000 − £100,000 + £250,000 − £5,000 = £545,000. Deduct RNRB £175,000 and NRB £325,000: taxable £45,000 × 40% = £18,000. Forgetting to deduct the mortgage or funeral costs, or omitting the RNRB, overstates the tax.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-E-12", paper: "TX", area: "E", type: "number",
    stem: "Freya died in 2024/25 with an estate of £600,000, including her home worth £120,000 which she left to her daughter (the rest to her brother). She made no lifetime gifts and was never married. Nil-rate band £325,000; residence nil-rate band £175,000, but limited to the value of the home passing to direct descendants. What IHT is payable in £?",
    numericAnswer: 62000,
    unit: "£",
    explanation: "The RNRB is capped at the value of the qualifying residence: min(£175,000, £120,000) = £120,000. Taxable = £600,000 − £325,000 − £120,000 = £155,000; tax = £155,000 × 40% = £62,000. Using the full £175,000 RNRB ignores the cap at the home's value.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-E-13", paper: "TX", area: "E", type: "number",
    stem: "Viktor died in 2024/25 with an estate of £2,200,000, including his home worth £300,000 left to his son; he made no lifetime gifts and had a full nil-rate band of £325,000. The residence nil-rate band of £175,000 is reduced by £1 for every £2 by which the estate exceeds £2,000,000. What IHT is payable in £?",
    numericAnswer: 720000,
    unit: "£",
    explanation: "RNRB taper: excess over £2m = £200,000, so the RNRB is reduced by £100,000 to £75,000. Taxable = £2,200,000 − £325,000 − £75,000 = £1,800,000; tax = £1,800,000 × 40% = £720,000. Using the full £175,000 RNRB ignores the taper for estates above £2m.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-E-14", paper: "TX", area: "E", type: "number",
    stem: "Amir died in 2022 leaving his entire estate to his wife Yasmin, using none of his £325,000 nil-rate band. Yasmin died in 2024/25 with an estate of £800,000 (no home, no lifetime gifts), left entirely to their children. Unused nil-rate band is transferable between spouses as a percentage. What IHT is payable on Yasmin's estate in £?",
    numericAnswer: 60000,
    unit: "£",
    explanation: "Amir's estate was wholly spouse-exempt, so 100% of his nil-rate band transfers: Yasmin has £325,000 × 2 = £650,000. Taxable = £800,000 − £650,000 = £150,000; tax = £150,000 × 40% = £60,000. Using only one nil-rate band (tax £190,000) ignores the transferable NRB.",
    marks: 2, difficulty: "medium",
  },
  {
    id: "TX2-E-15", paper: "TX", area: "E", type: "number",
    stem: "Klara's husband died in 2020 having used 40% of his nil-rate band on chargeable legacies to his children. Klara died in 2024/25 with an estate of £700,000 (no home) left to her son, having made no lifetime gifts. The nil-rate band at both deaths is £325,000; the UNUSED percentage of a spouse's band is transferable. What IHT is payable on Klara's estate in £?",
    numericAnswer: 72000,
    unit: "£",
    explanation: "60% of the husband's band was unused, so Klara's total band = £325,000 + (60% × £325,000 = £195,000) = £520,000. Taxable = £700,000 − £520,000 = £180,000; tax = £180,000 × 40% = £72,000. Transferring the full band (100%) or the used 40% are both errors — it is the unused percentage that transfers.",
    marks: 2, difficulty: "hard",
  },
  {
    id: "TX2-E-16", paper: "TX", area: "E", type: "number",
    stem: "In 2024/25 Soren sold a painting worth £100,000 to his daughter for £60,000 (a deliberate undervalue). His annual exemptions for this year and last year were already used against earlier gifts. What is the value of the potentially exempt transfer in £?",
    numericAnswer: 40000,
    unit: "£",
    explanation: "IHT works on the LOSS TO THE DONOR (diminution of the estate), not the amount received: £100,000 given up less £60,000 received = £40,000 PET. Treating the sale price as market value, or valuing the transfer at the full £100,000, are both wrong.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-E-17", paper: "TX", area: "E", type: "mcq",
    stem: "Which of the following lifetime transfers is WHOLLY exempt from IHT regardless of the amount and of how long the donor survives?",
    options: [
      "A gift of £500,000 to the donor's UK-domiciled spouse",
      "A gift of £10,000 to a son on his marriage",
      "A gift of £5,000 cash to a friend",
      "A transfer of £250,000 into a discretionary trust",
    ],
    correct: 0,
    explanation: "Transfers between UK-domiciled spouses/civil partners are exempt without limit. The marriage gift is exempt only up to £5,000 (parent), the gift to a friend is a PET beyond any annual exemption, and a transfer into a discretionary trust is an immediately chargeable CLT.",
    marks: 2, difficulty: "easy",
  },
  {
    id: "TX2-E-18", paper: "TX", area: "E", type: "number",
    stem: "Astrid owns 8,000 of the 10,000 shares in Fjord Ltd. An 80% holding is worth £50 per share, while a 50% holding is worth only £30 per share. She gives 3,000 shares to her son. Ignoring exemptions, what is the value of the transfer for IHT in £?",
    numericAnswer: 250000,
    unit: "£",
    explanation: "Diminution in value of the donor's estate: before, 8,000 × £50 = £400,000; after, 5,000 × £30 = £150,000. Transfer of value = £400,000 − £150,000 = £250,000. Valuing only the shares given away (3,000 × some price) misses the loss of the controlling-holding premium on the shares retained.",
    marks: 2, difficulty: "hard",
  },
]
