import type { AccaQuestion } from "@/lib/acca-content"

export const AFM_OFFICIAL_QUESTIONS: AccaQuestion[] = [
  { id: "AFM-F-O01", paper: "AFM", area: "F", type: "mcq", stem: "A proposed acquisition shows positive synergy only under management's most optimistic sales forecast. Which response best demonstrates scepticism?", options: ["Accept the forecast because directors approved it", "Challenge the assumptions and quantify downside and break-even outcomes", "Reject every acquisition", "Discuss only the financing method"], correct: 1, explanation: "Professional scepticism tests assertions and assumptions with evidence. Sensitivity, scenario and break-even analysis show whether the recommendation survives plausible downside.", marks: 2, difficulty: "medium" },
  { id: "AFM-F-O02", paper: "AFM", area: "F", type: "mcq", stem: "Which feature most strengthens a board report recommending a currency hedge?", options: ["A list of derivative definitions", "A clear recommendation linking exposure, cost, residual risk and strategic objective", "Unlabelled calculations", "Ignoring operational alternatives"], correct: 1, explanation: "Communication and commercial acumen require an implementable recommendation, supported by relevant analysis of costs, benefits, exposure and residual risk.", marks: 2, difficulty: "easy" },
  { id: "AFM-F-O03", paper: "AFM", area: "F", type: "mcq", stem: "A project has a positive base-case NPV but creates severe liquidity pressure before benefits arise. What is the strongest evaluation?", options: ["Approve because NPV is positive", "Integrate value, funding capacity, timing and strategic consequences", "Ignore liquidity because it is short term", "Replace NPV with payback only"], correct: 1, explanation: "Commercial evaluation balances value with financeability, timing, risk and organisational consequences rather than treating one metric as decisive.", marks: 2, difficulty: "medium" },
  { id: "AFM-G-O01", paper: "AFM", area: "G", type: "mcq", stem: "Before using spreadsheet cash flows supplied in different currencies, what should the adviser do first?", options: ["Add them directly", "Validate currencies, dates, exchange-rate bases and units", "Use the latest visible number", "Round every value"], correct: 1, explanation: "Digital competence starts with validating the basis of evidence; otherwise spreadsheet precision hides a conceptual error.", marks: 2, difficulty: "easy" },
  { id: "AFM-G-O02", paper: "AFM", area: "G", type: "mcq", stem: "Which spreadsheet design best supports review of an adjusted present value calculation?", options: ["Hard-coded totals", "Separated assumptions, labelled calculations and reconciliation from base NPV to APV", "Hidden discount rates", "A single unexplained result"], correct: 1, explanation: "Transparent inputs and linked, labelled workings make the calculation reviewable and reduce inconsistent amendments.", marks: 2, difficulty: "medium" },
  { id: "AFM-G-O03", paper: "AFM", area: "G", type: "mcq", stem: "A requirement asks for a report to the board. What is the most suitable digital response?", options: ["Generic essay", "Purposeful headings, traceable analysis, prioritised advice and limitations", "Copied exhibits", "Formulae without interpretation"], correct: 1, explanation: "The response must use the available tools to present decision-ready information in the required workplace format.", marks: 2, difficulty: "easy" },
]
