import type { AccaQuestion } from "@/lib/acca-content"

/* FM bank wave 8b part 2 — 32 verified originals (2026-07-13).
 * Blueprint: D17 E15; difficulty 8/15/9; 22 mcq / 10 number; every distractor
 * is a nameable student error. All computations re-solved from the stem before
 * inclusion. Merged into QUESTIONS in acca-content.ts.
 */

export const FM_WAVE3B: AccaQuestion[] = [
  /* ───────────── Area D — Business finance & cost of capital (17) ───────────── */
  {
    id: "FM4-D-01",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "Renwick Co has 7% preference shares of $1 nominal value in issue. The preference shares are quoted at 87c CUM-DIV, with the annual dividend of 7c per share about to be paid. Renwick Co pays corporation tax at 25%. What is the cost of the preference share capital?",
    options: ["8.05%", "7.00%", "8.75%", "6.56%"],
    correct: 2,
    explanation:
      "The ex-div price is 87 − 7 = 80c, and Kp = constant dividend ÷ ex-div price = 7 ÷ 80 = 8.75%. 8.05% divides by the CUM-DIV price of 87c, forgetting to strip out the dividend about to be paid. 6.56% applies 25% tax relief to the dividend (7 × 0.75 ÷ 80) — preference DIVIDENDS are an appropriation of profit, not a tax-deductible expense, so no tax adjustment is made. 7.00% is simply the coupon rate on nominal value, ignoring the market price entirely.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM4-D-02",
    paper: "FM",
    area: "D",
    type: "number",
    stem: "Kestrel Co has a fixed-rate bank loan carrying interest at 9% per year. The corporation tax rate is 30%, and tax relief on interest is received in the same year as the interest payment. What is the after-tax cost of the bank loan? Give your answer as a percentage to one decimal place.",
    numericAnswer: 6.3,
    unit: "%",
    tolerance: 0.05,
    explanation:
      "A bank loan is not traded, so its cost is simply the interest rate adjusted for tax relief: Kd(after tax) = 9% × (1 − 0.30) = 6.3%. The two classic slips are forgetting the tax shield entirely (9.0%) and multiplying by the tax rate instead of (1 − t), giving 2.7% — the company keeps the rate NET of the relief, not the relief itself.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM4-D-03",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "Arden Retail Co has 8 million ordinary shares quoted at $3.40 per share CUM-DIV, with a dividend of 40c per share about to be paid. It also has a $16 million bank loan carrying interest at 8% per year. The cost of equity is 13% and the corporation tax rate is 25%. What is Arden Retail Co's WACC?",
    options: ["10.2%", "10.4%", "11.0%", "9.5%"],
    correct: 0,
    explanation:
      "Market values must use the EX-DIV share price: 3.40 − 0.40 = $3.00, so equity = 8m × 3.00 = $24m; debt = $16m (a bank loan is valued at book). After-tax Kd = 8% × 0.75 = 6%. WACC = (24/40 × 13%) + (16/40 × 6%) = 7.8% + 2.4% = 10.2%. 10.4% values equity at the cum-div price of $3.40 ($27.2m), 11.0% forgets the tax relief on the loan interest (uses 8%), and 9.5% is the unweighted average of 13% and 6%.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM4-D-04",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "Bexley Foods Co has just paid a dividend of 29.78c per share; the dividend three years ago was 25.00c per share. The current ex-div share price is $3.50. Using the dividend growth model with the historic (compound) growth rate, what is Bexley Foods Co's cost of equity?",
    options: ["14.5%", "15.0%", "15.4%", "9.0%"],
    correct: 1,
    explanation:
      "Compound growth: 29.78 ÷ 25.00 = 1.1912 = 1.06³, so g = 6.0% per year over the THREE growth periods. Ke = D0(1 + g)/P0 + g = 29.78 × 1.06 ÷ 350 + 0.06 = 31.57 ÷ 350 + 0.06 = 9.0% + 6.0% = 15.0%. 14.5% forgets to grow the dividend just paid (uses D0 = 29.78 instead of D1), 15.4% uses ARITHMETIC growth (19.12% ÷ 3 = 6.37% per year) instead of compound growth, and 9.0% is the dividend yield alone, forgetting to add g.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM4-D-05",
    paper: "FM",
    area: "D",
    type: "number",
    stem: "Marlin Co's 6% loan notes are quoted at $96 per $100 nominal, EX-INTEREST, and will be redeemed at par in two years' time. The corporation tax rate is 25%, with tax relief received in the same year as the interest payment. Discount factors: at 6%, year 1 = 0.943, year 2 = 0.890; at 8%, year 1 = 0.926, year 2 = 0.857. Using linear interpolation between 6% and 8%, what is the after-tax cost of the loan notes? Give your answer as a percentage to one decimal place.",
    numericAnswer: 6.7,
    unit: "%",
    tolerance: 0.15,
    explanation:
      "After-tax interest = 6 × 0.75 = $4.50 per $100 nominal. Flows: t0 −96, t1 +4.50, t2 +104.50. NPV at 6% = 4.50 × 0.943 + 104.50 × 0.890 − 96 = 4.24 + 93.01 − 96 = +$1.25. NPV at 8% = 4.50 × 0.926 + 104.50 × 0.857 − 96 = 4.17 + 89.56 − 96 = −$2.28. IRR ≈ 6% + [1.25 ÷ (1.25 + 2.28)] × 2% = 6% + 0.7% = 6.7%. Common slips: forgetting the tax relief (using $6 interest, which pushes the answer above 8%), and discounting the redemption at $100 but the interest stream gross.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM4-D-06",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "Which of the following statements describes the TRADITIONAL view of capital structure?",
    options: [
      "The WACC is constant at all levels of gearing, so no optimal capital structure exists",
      "The WACC falls continuously as gearing rises, so the optimum is the maximum possible level of debt",
      "The cost of equity is unaffected by changes in gearing",
      "The WACC falls at first as cheap debt is introduced, then rises beyond some point, so an optimal capital structure exists at a moderate level of gearing",
    ],
    correct: 3,
    explanation:
      "The traditional view holds that at low gearing the benefit of cheap debt outweighs the gentle rise in the cost of equity, so WACC falls; beyond a certain point equity holders (and eventually lenders) demand sharply higher returns and WACC rises — producing a U-shaped WACC curve with an optimum at moderate gearing. A constant WACC (option A) is M&M WITHOUT tax, a continuously falling WACC (option B) is M&M WITH tax, and the cost of equity rises with gearing under every theory, so option C is wrong.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM4-D-07",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "Under Miller and Modigliani's capital structure theory WITHOUT corporate tax, what happens as a company replaces equity with debt?",
    options: [
      "The cost of equity rises in exact proportion to the extra financial risk, precisely offsetting the benefit of cheaper debt, so the WACC and company value are unchanged",
      "The WACC falls, because debt is cheaper than equity",
      "Company value rises, because of the tax shield on debt interest",
      "The cost of equity stays constant, so the WACC falls towards the cost of debt",
    ],
    correct: 0,
    explanation:
      "M&M (no tax) argue that gearing merely repackages the same operating cash flows: shareholders demand a linearly higher return as financial risk rises, and this exactly cancels the cheaper debt, leaving WACC and value constant. Option B counts the cheap debt but ignores the rising cost of equity — the precise error M&M expose. Option C imports the tax shield, which belongs to the WITH-tax version. Option D contradicts every capital structure theory: Ke always rises with gearing.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM4-D-08",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "A company wishes to obtain the use of machinery under Islamic finance principles, paying the financier for the use of the asset over an agreed period while the financier retains ownership. Which instrument does this describe?",
    options: ["Murabaha", "Mudaraba", "Ijara", "Sukuk"],
    correct: 2,
    explanation:
      "Ijara is the Islamic finance equivalent of a lease: the financier buys the asset and the customer pays for its USE while ownership (and the major risks of ownership) remain with the financier. Murabaha is cost-plus trade finance (the bank buys goods and resells them at a disclosed mark-up), mudaraba is a partnership where one party provides capital and the other expertise, and sukuk are certificates giving an ownership interest in an underlying asset — the bond-like instrument, not a lease.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM4-D-09",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "Which of the following correctly distinguishes MUSHARAKA from MUDARABA in Islamic finance?",
    options: [
      "In mudaraba all partners contribute capital, whereas in musharaka only the bank provides capital",
      "In musharaka all partners contribute capital and may participate in management, whereas in mudaraba one party provides the capital and the other provides expertise and management",
      "Mudaraba guarantees the capital provider a fixed periodic return",
      "In musharaka, losses are shared in proportion to the effort each partner contributes",
    ],
    correct: 1,
    explanation:
      "Musharaka is a joint venture: every partner injects capital and is entitled to a say in management, with profits shared in agreed ratios. Mudaraba splits the roles — the rab al mal provides capital, the mudarib provides skill and management. Option A states the distinction the wrong way round. Option C describes riba (a guaranteed fixed return), which Islamic finance prohibits — returns must be profit-based. Option D is wrong because losses are borne in proportion to CAPITAL contributed, not effort.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM4-D-10",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "Which of the following statements about SUKUK, compared with conventional loan notes, is correct?",
    options: [
      "Sukuk pay interest in the same way as conventional loan notes, but at a lower rate",
      "Sukuk must always be convertible into ordinary shares",
      "Sukuk holders rank as unsecured creditors with no connection to any specific asset",
      "Sukuk holders have an undivided ownership interest in an underlying asset, and their returns are generated by that asset rather than by interest",
    ],
    correct: 3,
    explanation:
      "Sukuk securitise an asset: certificate holders share ownership of the underlying asset and receive returns derived from its cash flows (e.g. rentals), which keeps the instrument Sharia-compliant. Option A fails because paying interest (riba) is prohibited — calling sukuk 'interest at a lower rate' is the classic misunderstanding. Option B confuses sukuk with convertible loan notes. Option C describes a conventional unsecured bond — the defining feature of sukuk is precisely the LINK to an identifiable asset.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM4-D-11",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "Tolworth Co is a large retailer with a strong credit rating; its small suppliers face high borrowing costs. Which of the following describes SUPPLY-CHAIN FINANCE (reverse factoring)?",
    options: [
      "A finance provider pays Tolworth Co's suppliers' approved invoices early, charging a financing cost based on Tolworth Co's stronger credit rating, and Tolworth Co pays the financier the full invoice amount at maturity",
      "Each supplier sells its own trade receivables to a factor, at a cost based on the supplier's own credit rating",
      "Suppliers borrow against their receivables ledger while keeping control of collections, without their customers' involvement",
      "Tolworth Co simply delays paying its suppliers beyond the agreed credit terms to conserve cash",
    ],
    correct: 0,
    explanation:
      "Supply-chain finance is initiated by the BUYER: because the financier's exposure is to the strong buyer (who has approved the invoices), suppliers get early payment at a financing cost far below what their own rating would command. Option B is ordinary factoring and option C is invoice discounting — both priced on the SUPPLIER's credit standing, which is exactly what supply-chain finance avoids. Option D is unilateral payment stretching, which damages suppliers rather than financing them.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM4-D-12",
    paper: "FM",
    area: "D",
    type: "number",
    stem: "Foxwell Co's shares trade at $2.75 (ex div). It announces a 1-for-4 rights issue at $2.00 per share. The funds raised will be invested in a project expected to earn a return of 15%, compared with the 10% return earned on the company's existing funds. What is the YIELD-ADJUSTED theoretical ex-rights price? Give your answer in $ to the nearest cent.",
    numericAnswer: 2.8,
    unit: "$",
    tolerance: 0.01,
    explanation:
      "The yield-adjusted TERP scales the new funds by the ratio of the new return to the existing return: [(4 × 2.75) + (1 × 2.00 × 0.15/0.10)] ÷ 5 = (11.00 + 3.00) ÷ 5 = $2.80. The unadjusted TERP would be (11.00 + 2.00) ÷ 5 = $2.60 — the standard error is stopping there and ignoring that the market will value the new funds more highly because they earn 15% rather than 10%. Inverting the ratio (× 0.10/0.15) gives $2.47, the other common slip.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM4-D-13",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "Halloway Co has 10 million ordinary shares in issue and no debt. It needs $6 million for an expansion and will raise it either with a bank loan at 8% per year or by issuing 3 million new shares at $2.00 each. Earnings before interest and tax after the expansion are forecast at $3.0 million and the tax rate is 20%. What would earnings per share be under the DEBT option?",
    options: ["18.5c", "20.2c", "25.2c", "24.0c"],
    correct: 1,
    explanation:
      "Debt option: interest = 6m × 8% = $0.48m; profit before tax = 3.0 − 0.48 = $2.52m; profit after tax = 2.52 × 0.80 = $2.016m; EPS = 2.016m ÷ 10m shares = 20.2c (existing shares only — no new shares are issued under the loan). 18.5c is the EQUITY option's EPS (3.0 × 0.8 = 2.4m ÷ 13m shares), i.e. answering the wrong financing route; 25.2c forgets tax (2.52 ÷ 10); 24.0c forgets the interest (2.4 ÷ 10).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM4-D-14",
    paper: "FM",
    area: "D",
    type: "number",
    stem: "Danbury Co has 5 million ordinary shares in issue with a market price of $1.80 per share, and $4 million (nominal) of 6% loan notes trading at $95 per $100 nominal. Calculate Danbury Co's financial gearing, measured as debt ÷ (debt + equity) using MARKET values. Give your answer as a percentage to one decimal place.",
    numericAnswer: 29.7,
    unit: "%",
    tolerance: 0.1,
    explanation:
      "Equity = 5m × 1.80 = $9.0m. Debt = 4m × 95/100 = $3.8m. Gearing = 3.8 ÷ (3.8 + 9.0) = 3.8 ÷ 12.8 = 29.7%. Two common slips: using the NOMINAL value of the loan notes ($4m), which gives 4 ÷ 13 = 30.8%, and computing debt ÷ equity (3.8 ÷ 9.0 = 42.2%) when the measure asked for is debt over total capital.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM4-D-15",
    paper: "FM",
    area: "D",
    type: "number",
    stem: "The risk-free rate of return is 3% and the expected RETURN on the market portfolio is 11%. Quayside Co's equity beta is 0.85. Using the capital asset pricing model, what is Quayside Co's cost of equity? Give your answer as a percentage to one decimal place.",
    numericAnswer: 9.8,
    unit: "%",
    tolerance: 0.05,
    explanation:
      "Ke = Rf + β(E(Rm) − Rf) = 3% + 0.85 × (11% − 3%) = 3% + 6.8% = 9.8%. The 11% given is the market RETURN, not the premium — the classic slip is computing 3% + 0.85 × 11% = 12.35%, which double-counts the risk-free rate inside the premium. The other slip is 0.85 × 8% = 6.8% alone, forgetting to add Rf back.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM4-D-16",
    paper: "FM",
    area: "D",
    type: "number",
    stem: "Silverton Co retains 30% of its earnings, and reinvested funds earn a return of 12% per year. The company has just paid a dividend of 25c per share and its ex-div share price is $2.59. Using the dividend growth model with Gordon's growth approximation (g = b × r), what is Silverton Co's cost of equity? Give your answer as a percentage to one decimal place.",
    numericAnswer: 13.6,
    unit: "%",
    tolerance: 0.1,
    explanation:
      "g = b × r = 0.30 × 12% = 3.6%. Ke = D0(1 + g)/P0 + g = 25 × 1.036 ÷ 259 + 0.036 = 25.9 ÷ 259 + 0.036 = 10.0% + 3.6% = 13.6%. Watch the two standard slips: using the PAYOUT ratio in Gordon's formula (0.70 × 12% = 8.4% — b is the RETENTION rate), and using the unadjusted D0 of 25c in the yield, which gives 9.65% + 3.6% = 13.3%.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM4-D-17",
    paper: "FM",
    area: "D",
    type: "mcq",
    stem: "Which of the following statements about crowdfunding as a source of finance for small and medium-sized entities (SMEs) is correct?",
    options: [
      "Reward-based crowdfunding gives contributors shares in the company",
      "Crowdfunding is available only to companies listed on a stock exchange",
      "Equity crowdfunding raises many small amounts from a large number of investors via an online platform, with each investor receiving shares in the company",
      "Peer-to-peer platforms provide equity finance rather than loans",
    ],
    correct: 2,
    explanation:
      "Equity crowdfunding pools small contributions from a crowd of online investors who each become shareholders — well suited to SMEs that cannot access capital markets. Reward-based crowdfunding gives contributors a product or perk, NOT shares (option A confuses the two models). Crowdfunding exists precisely because the company is NOT listed, so option B inverts its purpose. Peer-to-peer platforms match lenders with borrowers — debt, not equity — so option D swaps the two platform types.",
    marks: 2,
    difficulty: "medium",
  },

  /* ───────────── Area E — Business valuations & risk (15) ───────────── */
  {
    id: "FM4-E-01",
    paper: "FM",
    area: "E",
    type: "mcq",
    stem: "Oakmere Co has just paid a dividend of 15c per share. Dividends are expected to grow at 4% per year indefinitely, and shareholders require a return of 10%. Using the dividend growth model, what is the value of one Oakmere Co share?",
    options: ["$2.50", "$1.56", "$1.50", "$2.60"],
    correct: 3,
    explanation:
      "P0 = D0(1 + g) ÷ (Ke − g) = 15 × 1.04 ÷ (0.10 − 0.04) = 15.6 ÷ 0.06 = 260c = $2.60. $2.50 uses the dividend JUST PAID without growing it (15 ÷ 0.06) — the model needs next year's dividend D1; $1.56 divides D1 by Ke instead of (Ke − g), ignoring growth in the denominator; $1.50 makes both errors at once (15 ÷ 0.10).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM4-E-02",
    paper: "FM",
    area: "E",
    type: "number",
    stem: "Pindale Co is expected to pay a CONSTANT annual dividend of 24c per share indefinitely. Shareholders require a return of 8% per year. Using the dividend valuation model, what is the value of one Pindale Co share? Give your answer in $ to the nearest cent.",
    numericAnswer: 3.0,
    unit: "$",
    tolerance: 0.01,
    explanation:
      "With zero growth the share is a perpetuity: P0 = D ÷ Ke = 24 ÷ 0.08 = 300c = $3.00. The common slips are multiplying instead of dividing (24 × 0.08 = 1.92c, an obviously absurd share price worth sanity-checking) and applying a growth rate that the question does not give — with a constant dividend, g = 0.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM4-E-03",
    paper: "FM",
    area: "E",
    type: "mcq",
    stem: "Thornbeck Co's non-current assets have a book value of $7.0m; their replacement cost is $8.4m and their net realisable value is $5.9m. Current assets are $2.3m and total liabilities are $3.1m. A buyer wants the MAXIMUM price justified by an asset-based valuation. What is the valuation on a REPLACEMENT COST basis?",
    options: ["$7.6 million", "$6.2 million", "$5.1 million", "$10.7 million"],
    correct: 0,
    explanation:
      "Replacement cost basis = 8.4 + 2.3 − 3.1 = $7.6m — the ceiling a buyer would pay, since above that it could assemble the assets itself. $6.2m uses BOOK values (7.0 + 2.3 − 3.1), which reflect historic cost, not current worth; $5.1m uses net realisable value (5.9 + 2.3 − 3.1), which is the SELLER's break-up floor, not the buyer's ceiling; $10.7m forgets to deduct the liabilities (8.4 + 2.3).",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM4-E-04",
    paper: "FM",
    area: "E",
    type: "number",
    stem: "Larkfield Co generated free cash flow TO EQUITY of $0.9m in the year just ended, expected to grow at 4% per year indefinitely. Its cost of equity is 12%, its WACC is 9%, and the market value of its debt is $4m. What is the value of Larkfield Co's equity? Give your answer in $ million to one decimal place.",
    numericAnswer: 11.7,
    unit: "$m",
    tolerance: 0.05,
    explanation:
      "Free cash flow to EQUITY is already after debt servicing, so it is discounted at the COST OF EQUITY and values the equity directly: 0.9 × 1.04 ÷ (0.12 − 0.04) = 0.936 ÷ 0.08 = $11.7m. Three traps set by the stem: discounting at the WACC (0.936 ÷ 0.05 = $18.72m) — WACC is for flows to the whole FIRM; deducting the $4m of debt (11.7 − 4 = $7.7m) — debt is only deducted from a FIRM value, and FCFE is not one; and forgetting to grow the just-ended flow (0.9 ÷ 0.08 = $11.25m).",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM4-E-05",
    paper: "FM",
    area: "E",
    type: "mcq",
    stem: "Grantham Engineering Co is unlisted. Its maintainable profit after tax is $800,000 (profit before tax $1,000,000). An appropriate EARNINGS YIELD for valuing companies of this type is 12.5%. What is the value of Grantham Engineering Co's equity using the earnings yield method?",
    options: ["$10.0 million", "$6.4 million", "$8.0 million", "$0.1 million"],
    correct: 1,
    explanation:
      "The earnings yield method capitalises maintainable POST-TAX earnings: value = 800,000 ÷ 0.125 = $6.4m (an earnings yield of 12.5% is equivalent to a P/E of 1 ÷ 0.125 = 8). $10.0m treats 12.5 as a P/E MULTIPLE and multiplies (800,000 × 12.5) — the classic confusion between the two reciprocal methods; $8.0m capitalises PRE-tax profit (1,000,000 ÷ 0.125); $0.1m multiplies by the yield instead of dividing (800,000 × 0.125).",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM4-E-06",
    paper: "FM",
    area: "E",
    type: "mcq",
    stem: "A stock market is efficient in the WEAK form only. Which of the following investors could consistently earn abnormal returns?",
    options: [
      "A chartist who studies patterns in past share price movements",
      "An investor applying mechanical trading rules based on price history",
      "An analyst who identifies undervalued shares by studying published financial statements",
      "No investor can earn abnormal returns in a weak-form efficient market",
    ],
    correct: 2,
    explanation:
      "Weak-form efficiency means prices already reflect all information in PAST PRICES — so technical analysis and mechanical price-based rules (options A and B) cannot systematically win. But published accounting information is NOT yet fully impounded under weak form, so fundamental analysis of financial statements can still earn abnormal returns. Option D overstates the claim — 'no one can win' would require at least semi-strong efficiency for public-information traders; the test is always WHICH information set the price already contains.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM4-E-07",
    paper: "FM",
    area: "E",
    type: "mcq",
    stem: "Investors keep buying shares in a fashionable technology sector mainly because other investors are buying and prices keep rising, setting aside their own analysis of the companies' fundamentals. Which behavioural finance concept does this BEST illustrate?",
    options: ["Herding", "Anchoring", "Loss aversion", "Overconfidence"],
    correct: 0,
    explanation:
      "Following the crowd instead of one's own analysis is herding — the behaviour behind speculative bubbles. Anchoring is clinging to an initial reference value (such as the price paid) when updating estimates; loss aversion is feeling losses more keenly than equivalent gains, which typically makes investors hold losers too long; overconfidence is overrating one's OWN judgement — the investors here are doing the opposite, abandoning their own judgement for the crowd's.",
    marks: 2,
    difficulty: "easy",
  },
  {
    id: "FM4-E-08",
    paper: "FM",
    area: "E",
    type: "mcq",
    stem: "Corven Co's 7% loan notes will be redeemed at their $100 nominal value in three years' time. Investors in this class of debt require a return of 5% per year (discount factors at 5%: year 1 = 0.952, year 2 = 0.907, year 3 = 0.864). What is the expected market value of one loan note?",
    options: ["$100.00", "$140.00", "$99.97", "$105.46"],
    correct: 3,
    explanation:
      "Market value = PV of future receipts at the INVESTORS' required return: interest 7 × (0.952 + 0.907 + 0.864) = 7 × 2.723 = 19.06, plus redemption 100 × 0.864 = 86.40, total $105.46 — above par because the 7% coupon exceeds the 5% required yield. $100.00 assumes the note trades at par regardless of the coupon/yield gap; $140.00 values the interest as a PERPETUITY (7 ÷ 0.05), ignoring redemption in three years; $99.97 discounts at the 7% COUPON rate instead of the 5% required return, which mechanically returns roughly par.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM4-E-09",
    paper: "FM",
    area: "E",
    type: "mcq",
    stem: "Market interest rates are expected to change. The market price of which of the following loan notes would change by the LARGEST percentage?",
    options: [
      "A 9% coupon loan note with 15 years to maturity",
      "A 3% coupon loan note with 15 years to maturity",
      "A 3% coupon loan note with 2 years to maturity",
      "A 9% coupon loan note with 2 years to maturity",
    ],
    correct: 1,
    explanation:
      "Price sensitivity to interest rates rises with MATURITY and falls with COUPON: the longer and the lower-coupon the bond, the more of its value sits in distant cash flows, which are hit hardest by a change in the discount rate. So the 3% 15-year note is the most volatile. Picking the 9% 15-year note (option A) applies the maturity effect but misses that HIGH coupons return cash sooner and so dampen sensitivity; the two 2-year notes are the least sensitive, and the 9% 2-year note is the most stable of all.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM4-E-10",
    paper: "FM",
    area: "E",
    type: "mcq",
    stem: "A company with floating-rate borrowings wants protection against a rise in interest rates, but wishes to reduce the net premium cost of using options. Which combination creates a suitable interest rate COLLAR?",
    options: [
      "Buy an interest rate cap and buy an interest rate floor",
      "Sell an interest rate cap and buy an interest rate floor",
      "Buy an interest rate cap and sell an interest rate floor",
      "Sell an interest rate cap and sell an interest rate floor",
    ],
    correct: 2,
    explanation:
      "A borrower's collar = BUY a cap (a ceiling on the interest rate, the protection needed) and SELL a floor (the premium received reduces the net cost). The price is giving up the benefit if rates fall below the floor — the rate is confined to a band. Buying both (option A) pays two premiums and provides no offset, defeating the purpose; selling the cap and buying the floor (option B) is a DEPOSITOR'S collar, the mirror-image position; selling both (option D) collects premiums while leaving the company with unlimited exposure and no protection at all.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM4-E-11",
    paper: "FM",
    area: "E",
    type: "mcq",
    stem: "A company will need to borrow a large sum in three months' time and fears that interest rates will rise before then. Which statement correctly describes hedging this exposure with interest rate FUTURES?",
    options: [
      "Sell interest rate futures now; if rates rise, futures prices will fall, and the gain on closing out the position offsets the higher borrowing cost",
      "Buy interest rate futures now; if rates rise, futures prices will rise, producing an offsetting gain",
      "Sell interest rate futures now; if rates rise, futures prices will also rise, producing an offsetting gain",
      "Either buy or sell futures — the hedge is perfect in both directions because futures eliminate all interest rate risk",
    ],
    correct: 0,
    explanation:
      "Interest rate futures are priced at (100 − interest rate), so prices move INVERSELY to rates. A future borrower hedges by SELLING futures: if rates rise the futures price falls, and buying back cheaply yields a gain that offsets the dearer loan. Option B has the direction of the trade wrong — buying futures profits when rates FALL; option C sells correctly but has the price mechanics backwards; option D ignores basis risk and standardised contract sizes/dates, which make futures hedges imperfect in practice.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM4-E-12",
    paper: "FM",
    area: "E",
    type: "mcq",
    stem: "Brantley Co, a UK engineering exporter, invoices ALL overseas sales in sterling. Sterling then strengthens persistently over several years, and overseas customers gradually switch to cheaper foreign competitors. Which type of risk has Brantley Co suffered?",
    options: [
      "Transaction risk",
      "Translation risk",
      "No currency risk, because all invoicing is in sterling",
      "Economic risk",
    ],
    correct: 3,
    explanation:
      "The long-term erosion of competitiveness and value caused by exchange rate movements is ECONOMIC risk — and it strikes even a company that never holds a foreign currency receivable. Invoicing in sterling removes TRANSACTION risk on each individual sale (so option A is wrong), but it merely transfers the price effect to customers, who respond by buying elsewhere — which is why option C, the tempting 'fully protected' answer, is false. Translation risk concerns retranslating foreign subsidiaries' net assets on consolidation, which is not in point here.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM4-E-13",
    paper: "FM",
    area: "E",
    type: "number",
    stem: "Delmont Inc, a US company, must pay €505,000 to a supplier in six months' time. The spot exchange rate is $1.2500 per €1. Annual interest rates: euro deposits 2% (i.e. 1.0% for six months); dollar borrowing 6% (i.e. 3.0% for six months). Using a MONEY-MARKET hedge, what is the total dollar cost of the payment in six months' time? Give your answer in $ to the nearest dollar.",
    numericAnswer: 643750,
    unit: "$",
    tolerance: 50,
    explanation:
      "Deposit euros now so the deposit matures at exactly €505,000: 505,000 ÷ 1.01 = €500,000. Buying €500,000 at spot costs 500,000 × 1.2500 = $625,000, which is borrowed at 3.0% for six months: 625,000 × 1.03 = $643,750. The two standard slips: depositing the FULL €505,000 without discounting (505,000 × 1.25 × 1.03 = $650,188), and stopping at the $625,000 spot cost — a today-dollar figure that is not comparable with a six-month forward cost because it omits the borrowing interest.",
    marks: 2,
    difficulty: "hard",
  },
  {
    id: "FM4-E-14",
    paper: "FM",
    area: "E",
    type: "number",
    stem: "The spot exchange rate is $1.5000 per £1. Inflation over the next year is expected to be 4% in the United States and 2% in the United Kingdom. Using purchasing power parity, what is the expected spot rate ($ per £1) in one year's time? Give your answer to four decimal places.",
    numericAnswer: 1.5294,
    unit: "$ per £1",
    tolerance: 0.001,
    explanation:
      "Purchasing power parity: S1 = S0 × (1 + inflation of the COUNTED currency, $) ÷ (1 + inflation of the BASE currency, £) = 1.5000 × 1.04 ÷ 1.02 = 1.5294 — the higher-inflation currency (the dollar) weakens, so more dollars are needed per pound. Inverting the ratio (1.5000 × 1.02 ÷ 1.04 = 1.4712) is the classic error; simply adding the 2% inflation DIFFERENCE (1.5000 × 1.02 = 1.5300) is only an approximation and misses the required four-decimal answer.",
    marks: 2,
    difficulty: "medium",
  },
  {
    id: "FM4-E-15",
    paper: "FM",
    area: "E",
    type: "mcq",
    stem: "In which of the following situations would a currency OPTION be most clearly preferable to a forward exchange contract?",
    options: [
      "The foreign currency cash flow is certain in amount and date, and the company wants the cheapest possible hedge",
      "The company wants a hedge with no up-front cost of any kind",
      "The company is tendering for an overseas contract and will have a foreign currency receipt only IF the tender succeeds",
      "The company wants to be contractually committed to exchanging at a known rate",
    ],
    correct: 2,
    explanation:
      "An option gives the RIGHT but not the obligation to exchange — ideal when the underlying cash flow itself is uncertain: if the tender fails, the company simply abandons the option (or sells it), whereas a forward would leave it contractually bound to deliver currency it never received. For a CERTAIN cash flow (option A) a forward is normally cheaper, because option premiums are expensive; options have an up-front premium, so option B is factually wrong; and wanting a binding commitment at a known rate (option D) is the definition of a forward, not an option.",
    marks: 2,
    difficulty: "medium",
  },
]
