/*
 * MA's own content contract, following the pattern BT established.
 *
 * MA used to share the F1–F4 contract: 350 Section A items and 350 linked
 * Section B questions. Both were fictions for MA in different ways.
 *
 * The 350 Section A items were 177 authored questions padded with 173 prompts
 * permuted out of the study text. The 350 linked Section B questions were
 * generated by the same routine that produced BT's, in units of the wrong size
 * and shape entirely.
 *
 * MA's real exam is 35 objective-test questions of 2 marks (70) plus THREE
 * multi-task questions of TEN marks (30) — a very different Section B from BT's
 * six 4-mark units, which is why each paper needs its own contract rather than a
 * shared one.
 */

export const MA_CONTENT_TARGET = {
  /** Authored, exam-standard Section A questions. Derived drills do not count. */
  authoredBank: 478,
  /** Study chapters in the reading tree, one per syllabus sub-topic group. */
  chapters: 27,
  /** Official syllabus areas the chapters must cover between them. */
  syllabusAreas: 6,
  /**
   * Authored Section B multi-task questions. Three mocks × three MTQs = 9, so
   * this is exactly enough for three DISJOINT sittings at the real unit size.
   */
  mtqUnits: 9,
  /** Marks per MTQ in the real MA exam. */
  mtqMarks: 10,
  /** Section A marks in the real exam: 35 × 2. */
  sectionAMarks: 70,
  /** Section B marks in the real exam: 3 MTQs × 10. */
  sectionBMarks: 30,
  mockForms: 3,
  /** MA's exam is 100% objective test — there is no constructed-response section. */
  writtenQuestions: 0,
  /**
   * The three areas the real exam's Section B draws on, per the published
   * blueprint. Every mock form must cover all three, which is why the MTQ bank
   * holds three of each rather than nine of one.
   */
  mtqAreas: ["D", "E", "F"] as const,
  /**
   * MA is computational, so a substantial share of the bank must be numeric
   * ENTRY rather than multiple choice: a calculation offered as four options can
   * be reverse-engineered from the options, which tests something easier than
   * the exam does.
   */
  minNumericQuestions: 60,
} as const
